== Abhivadati

=== Renderings

- _abhivadati_: to proclaim

- _abhivadati_: to glorify

- _abhivadati_: to assert

- _abhivadati_: to welcome

=== Illustrations

.Illustration
====
abhivadanti

proclaim
====

[quote, Vin.2.96]
____
Those teachings which are excellent in the beginning, the middle, and the end, 
whose spirit and letter proclaim the utterly complete and pure religious life. 
Things like this are much heard by him.

_kevalaparipuṇṇaṃ parisuddhaṃ brahmacariyaṃ abhivadanti._
____

.Illustration
====
abhivadanti

proclaim
====

[quote, M.2.229]
____
Some [ascetics and Brahmanists] proclaim the _viññāṇa_ kasiṇa, limitless 
and imperturbable.

_viññāṇakasiṇaṃ eke abhivadanti appamāṇaṃ āneñjaṃ._
____

.Illustration
====
abhivadanti

proclaim
====

[quote, M.2.230]
____
Some [ascetics and Brahmanists] proclaim that the state of awareness of 
nonexistence, limitless and imperturbable, where one perceives that there is 
&#8203;[nowhere] anything at all, is the purest, highest, best, and greatest of those 
states of refined awareness, whether refined material states of awareness, or 
immaterial states of awareness, or states of refined awareness involving mental 
cognisance alone, or involving the external senses.

_Yā vā panetāsaṃ saññānaṃ parisuddhā paramā aggā anuttariyā 
akkhāyati yadi rūpasaññānaṃ yadi arūpasaññānaṃ yadi 
ekattasaññānaṃ yadi nānattasaññānaṃ natthi kiñci ti 
ākiñcaññāyatanaṃ eke abhivadanti appamāṇaṃ āneñjaṃ._
____

.Illustration
====
nābhivadiṃ

glorify
====

[quote, M.1.329]
____
I did not consider I was solidness, I did not consider I was part of solidness, 
I did not consider I was separate from solidness, I did not consider solidness 
to be "[in reality] mine," I did not glorify solidness.

_paṭhaviṃ nāhosiṃ paṭhaviyā nāhosiṃ paṭhavito nāhosiṃ 
paṭhaviṃ me ti nāhosiṃ paṭhaviṃ nābhivadiṃ._
____

.Illustration
====
abhivadanti

glorify
====

[quote, Vin.1.37]
____
'Brahmanic sacrifices glorify sights and sounds, also flavours, sensuous 
pleasures, and women.

_Rūpe ca sadde ca atho rase ca +
Kāmitthiyo cābhivadanti yaññā._
____

.Illustration
====
abhivadanti

assert
====

____
"Those who assert a doctrine different from this have strayed from spiritual 
purity. They are not spiritually perfected."

_Aññaṃ ito yābhivadanti dhammaṃ aparaddhā suddhimakevalī te_
____

[quote, Sn.v.891]
____
Non-Buddhist ascetics each say this because they are passionately attached to 
their own dogmatic views.

_Evampi titthiyā puthuso vadanti sandiṭṭhirāgena hi tebhirattā._
____

.Illustration
====
abhivadanti

assert
====

____
Some assert that the _attā_ is perceptive and unimpaired after death

_Saññī attā hoti arogo parammaraṇā ti ittheke abhivadanti._
____

____
Some assert that the _attā_ is unperceptive and unimpaired after death.

_asaññī attā hoti arogo parammaraṇā ti ittheke abhivadanti_
____

[quote, M.2.228]
____
Some assert that the _attā_ is neither perceptive nor unperceptive and 
unimpaired after death.

_nevasaññīnāsaññī attā hoti arogo parammaraṇā ti ittheke 
abhivadanti._
____

.Illustration
====
abhivadanti

assert
====

[quote, M.2.232]
____
'All these reverend ascetics and Brahmanists with lofty voices are only 
asserting their attachment in saying 'We shall be thus after passing on; we 
shall be thus after passing on.'

_sabbepime bhonto samaṇabrāhmaṇā uddhaṃsarā āsattiṃ yeva 
abhivadanti. Iti pecca bhavissāma iti pecca bhavissāmā ti._
____

.Illustration
====
abhivadati

welcome
====

• Engaged as he is in welcoming and rejecting, whatever sense impression he 
experiences -- whether pleasant, unpleasant, or neutral -- he takes delight in 
it, welcomes it, and persists in cleaving to it. In so doing, spiritually 
fettering delight arises. +
_So evaṃ anurodhavirodhaṃ samāpanno yaṃ kiñci vedanaṃ vedeti sukhaṃ 
vā dukkhaṃ vā adukkhamasukhaṃ vā so taṃ vedanaṃ abhinandati 
abhivadati ajjhosāya tiṭṭhati tassa taṃ vedanaṃ abhinandato abhivadato 
ajjhosāya tiṭṭhato uppajjati nandī_ (M.1.266).

.Illustration
====
abhivadatu

welcome
====

Once, when bhikkhus were noisy the Buddha told them 'Go I dismiss you. You 
should not live with me.' Later someone asked:

____
__'__Bhante, may the Blessed One take delight in the community of bhikkhus.

_abhinandatu bhante bhagavā bhikkhusaṅghaṃ_
____

____
May he welcome the community of bhikkhus.

_abhivadatu bhante bhagavā bhikkhusaṅghaṃ_
____

[quote, M.1.457]
____
May he assist them as he used to do in the past.

_seyyathā pi bhante bhagavatā pubbe bhikkhusaṅgho anuggahito evameva 
bhagavā etarahi anugaṇhātu bhikkhusaṅghaṃ._
____

.Illustration
====
abhivadiṃ welcome

[quote

M.1.330]
====

____
Seeing the danger of individual existence when searching for either [states of] 
individual existence or the cessation of [states of] individual existence, I 
did not welcome individual existence, nor rejoice in or grasp anything.

_Bhavevāhaṃ bhayaṃ disvā bhavañca vibhavesinaṃ +
Bhavaṃ nābhivadiṃ kiñci nandiñca na upādiyinti._
____

.Illustration
====
abhivadanti

welcome
====

Pañcasikha told the Buddha that Sakka, Lord of the Devas, was waiting to meet 
him. The Buddha said:

____
'Pañcasikha, may Sakka, Lord of the Devas, his ministers and followers be 
happy,

_Evaṃ sukhī hotu pañcasikha sakko devānamindo sāmacco saparijano_
____

____
'For they all desire happiness: devas, humans, asuras, magical serpents, 
heavenly musicians, and whatever other groups of beings there are.'

_sukhakāmā hi devā manussā asurā nāgā gandhabbā ye caññe santi 
puthukāyā ti._
____

____
For that is the way that Perfect Ones welcome such mighty deities.

_Evañca pana tathāgatā evarūpe mahesakkhe yakkhe abhivadanti._
____

Welcomed (_abhivadito_), Sakka entered the Indasāla Cave, venerated the 
Blessed One, and stood at a respectful distance (D.2.270).

