== Abhinandati

=== Renderings

- _abhinandati_: to take delight in

- _abhinandati_: to long for

- _abhinandati_: to applaud

=== Introduction

==== On longing for the future

One 'takes delight' in the present, or 'longs for' the future. 'Longing for' 
the future means directing the mind with desire (_cittaṃ paṇidahati_), as 
follows:

____
How does one long for the future?

_Kathañcāvuso anāgataṃ paṭikaṅkhati:_
____

[quote, M.3.195-6]
____
... One directs one's mind to acquire what has not yet been acquired, thinking, 
'May the visual sense and visible objects be thus in the future.' In directing 
one's mind thus, one longs for it. In doing so one longs for the future.

_iti me cakkhuṃ siyā anāgatamaddhānaṃ iti rūpāti appaṭiladdhassa 
paṭilābhāya cittaṃ paṇidahati. Cetaso paṇidhānapaccayā 
tadabhinandati. Tadabhinandanto anāgataṃ paṭikaṅkhati._
____

=== Illustrations

.Illustration
====
nābhinandati

take delight in
====

[quote, S.1.32]
____
They always take delight in food, both devas and human beings. So what sort of 
deity could it be that does not take delight in food?

_Annamevābhinandanti ubhaye devamānusā +
Atha ko nāma so yakkho yaṃ annaṃ nābhinandatī ti._
____

.Illustration
====
abhinandati

take delight in
====

[quote, S.2.175]
____
One who takes delight in the Solidness Phenomenon, takes delight in existential 
voidness. One who takes delight in existential voidness, I declare, is not 
freed from suffering, I declare.

_Yo bhikkhave paṭhavīdhātuṃ abhinandati dukkhaṃ so abhinandati. Yo 
dukkhaṃ abhinandati aparimutto so dukkhasmā vadāmi._
____

.Illustration
====
nābhinandeyya

take delight in
====

[quote, Dh.v.75]
____
The bhikkhu, the disciple of the Buddha, should not take delight in worldly 
honour. He should cultivate seclusion [from sensuous pleasures and spiritually 
unwholesome factors] instead.

_bhikkhu buddhassa sāvako sakkāraṃ nābhinandeyya vivekamanubrūhaye._
____

.Illustration
====
abhinandāmi

take delight in
====

[quote, Sn.v.1054]
____
And I would take delight in that supreme teaching, great Seer, understanding 
which, one living the religious life, one who is mindful, would overcome 
attachment to the world [of phenomena].

_tañcāhaṃ abhinandāmi mahesi dhammamuttamaṃ +
Yaṃ viditvā sato caraṃ tare loke visattikaṃ._
____

.Illustration
====
abhinanditaṃ

take delight in
====

[quote, Th.v.394]
____
See the body [according to reality], Kulla, as ailing, foul, and loathsome; 
oozing and dripping [from its nine orifices] -- but which fools take delight in.

_bālānaṃ abhinanditaṃ._
____

.Illustration
====
abhinandanti

take delight in
====

[quote, A.3.350]
____
In this regard, Ānanda, a person is gentle, pleasant to live with. His 
companions in the religious life take delight in his company

_abhinandanti sabrahmacārī ekattavāsena._
____

.Illustration
====
nābhinandāmi

long for; nābhinandāmi, take delight in
====

[quote, Th.v.1003]
____
I do not long for death. I take no delight in life. I await the inevitable hour 
like a servant for his wages.

_Nābhinandāmi maraṇaṃ nābhinandāmi jīvitaṃ +
Kālañca paṭikaṅkhāmi nibbisaṃ bhatako yathā._
____

.Illustration
====
nābhinandati

long for
====

[quote, Ud.33]
____
He abandons craving for states of individual existence but he does not long for 
the cessation of individual existence.

_Bhavataṇhā pahīyati vibhavaṃ nābhinandati._
____

.Illustration
====
abhinandanti

long for
====

____
Some people are revolted, appalled, and disgusted by individual existence.

_bhaveneva kho paneke aṭṭiyamānā harāyamāsā jigucchamānā_
____

[quote, It.44]
____
They long for the cessation of individual existence

_vibhavaṃ abhinandanti._
____

.Illustration
====
abhinandati

long for
====

[quote, S.4.208-9]
____
Being affected by an unpleasant sense impression, he longs for sensuous 
pleasure.

_so dukkhāya vedanāya phuṭṭho samāno kāmasukhaṃ abhinandati._
____

.Illustration
====
abhinandanti

applaud
====

[quote, Dh.v.219]
____
A man who has long been living abroad, who returns safely from afar, his 
relatives, friends, and comrades applaud his return.

__Ñātimittā suhajjā ca abhinandanti āgataṃ._
____

.Illustration
====
abhinandiṃsu

applaud
====

[quote, S.5.109]
____
Those bhikkhus neither applauded those ascetics words, nor criticised them, but 
rose and left.

_neva abhinandiṃsu nappaṭikkosiṃsu. Anabhinanditvā appaṭikkositvā 
uṭṭhāyāsanā pakkamiṃsu._
____

.Illustration
====
abhinandīti

applaud
====

[quote, M.2.266]
____
Venerable Ānanda was pleased and applauded the Blessed One's words.

_attamano āyasmā ānando bhagavato bhāsitaṃ abhinandīti._
____

.Illustration
====
abhinanditabbaṃ

applaud
====

____
A bhikkhu makes a declaration of arahantship.

_bhikkhu aññaṃ vyākaroti khīṇā jāti vusitaṃ brahmacariyaṃ kataṃ 
karaṇīyaṃ nāparaṃ itthattāyā ti pajānāmi ti._
____

____
The bhikkhus words should be neither applauded nor criticised

_tassa bhikkhave bhikkhuno bhāsitaṃ neva abhinanditabbaṃ 
nappaṭikkositabbaṃ_
____

But he should be asked a question. If he answers correctly, then:

[quote, M.3.29-30]
____
... expressing one's approval, one may applaud and acclaim that bhikkhu's words

_tassa bhikkhave bhikkhuno sādhū ti bhāsitaṃ abhinanditabbaṃ 
anumoditabbaṃ._
____

.Illustration
====
nābhinandāmi

applaud
====

If one does not pardon those who confess their faults, one harbours 
unfriendliness:

[quote, S.1.25]
____
I do not applaud that unfriendliness, thus I pardon your transgression

_Taṃ veraṃ nābhinandāmi patigaṇhāmi voccayan ti._
____

