== Abhibhū

=== Renderings

- _sabbābhibhū_: transcended the All

- _sabbalokābhibhū_: transcended the whole world [of phenomena]

=== Introduction

==== The dictionaries

- PED (sv _Abhibhū_): overcoming, conquering, vanquishing, having power over, 
a Lord or Master of.

- DOP (sv _Abhibhū_): vanquishing, overcoming, one who surpasses, a master, a 
sovereign

==== The world and attachment

But the suttas do not support the idea that the All or the world should be 
conquered or vanquished, but rather that attachment should be conquered:

[quote, M.1.160]
____
He has overcome attachment to the world.

_tiṇṇo loke visattikan ti._
____

This is confirmed in the following quotes, which link _Sabbābhibhū_ to 
freedom from attachment:

1. I have transcended the All. I have understood the All. I do not cleave to 
any phenomenon. I have abandoned the All.
+
****
_Sabbābhibhū sabbavidūhamasmi sabbesu dhammesu anupalitto +
****
Sabbañjaho_ (Dh.v.353).

2. One who has transcended the All, understood the All, who is of great wisdom, 
who does not cleave to any phenomenon, who has abandoned the All.
+
****
_Sabbābhibhuṃ sabbaviduṃ sumedhaṃ sabbesu dhammesu anupalittaṃ +
****
Sabbañjahaṃ_ (Sn.v.211).

3. free of attachment, who has transcended the whole world [of phenomena]
+
****
_nirupadhiṃ sabbalokābhibhuṃ_ (Sn.v.642; Dh.v.418).
****

==== Bhikkhu Bodhi: 'transcended'

Bhikkhu Bodhi recognises 'transcended':

[quote, Bodhi, M.1.171]
____
I am one who has transcended all, a knower of all, unsullied among all things, 
renouncing all, by craving's ceasing freed. Having known this all for myself, 
to whom should I point as teacher?

_Sabbābhibhū sabbavidūhamasmi sabbesu dhammesu anupalitto +
Sabbañjaho taṇhakkhaye vimutto sayaṃ abhiññāya kamuddiseyyaṃ._
____

[quote, Bodhi, M.2.262]
____
Suppose I were to abide with a mind abundant and exalted, having transcended 
the world and made a firm determination with the mind.

_Yaṃnūnāhaṃ vipulena mahaggatena cetasā vihareyyaṃ abhibhuyya lokaṃ 
adhiṭṭhāya manasā._
____

==== The All

[quote, S.4.15]
____
And what is the All? The visual sense and visible objects, the auditory sense 
and audible objects, the olfactory sense and smellable objects, the gustatory 
sense and tasteable objects, the tactile sense and tangible objects, the mental 
sense and mentally known objects. This is called the All.

_Kiñca bhikkhave sabbaṃ. Cakkhuñceva rūpā ca sotañca saddā ca 
ghānañca gandhā ca jivhā ca rasā ca kāyo ca phoṭṭhabbā ca mano ca 
dhammā ca. Idaṃ vuccati bhikkhave sabbaṃ.._
____

=== Illustrations

.Illustration
====
sabbābhibhū

transcended the All
====

[quote, Dh.v.353]
____
I have transcended the All. I have understood the All. I do not cleave to any 
phenomenon. I have abandoned the All. I am liberated [from perceptually 
obscuring states] through the destruction of craving. Having fully understood 
&#8203;[the All] by myself, who could I designate [as my teacher]?

_Sabbābhibhū sabbavidūhamasmi sabbesu dhammesu anupalitto +
Sabbañjaho taṇhakkhaye vimutto sayaṃ abhiññāya kamuddiseyyaṃ._
____

.Illustration
====
sabbābhibhuṃ

transcended the All
====

[quote, Sn.v.211]
____
One who has transcended the All, understood the All, who is of great wisdom, 
who does not cleave to any phenomenon, who has abandoned the All, who is 
liberated [from perceptually obscuring states] through the destruction of 
craving, the wise know him as truly a sage.

_Sabbābhibhuṃ sabbaviduṃ sumedhaṃ sabbesu dhammesu anupalittaṃ +
Sabbañjahaṃ taṇhakkhaye vimuttaṃ taṃ vāpi dhīrā muniṃ vedayanti._
____

.Illustration
====
sabbalokābhibhuṃ

transcended the whole world [of phenomena]
====

One who has abandoned both sensuous delight and disgruntlement [with the 
celibate life], who is freed from inward distress, free of attachment, who has 
transcended the whole world [of phenomena], a Hero, he is what I call a Brahman.

• _Hitvā ratiñca aratiñca sītibhūtaṃ nirupadhiṃ +
Sabbalokābhibhuṃ vīraṃ tamahaṃ brūmi brāhmaṇaṃ_ (Sn.v.642; 
Dh.v.418).

COMMENT

_Sabbalokābhibhuṃ_: 'transcended the whole world [of phenomena].' Which is 
defined in this quote:

[quote, S.4.53]
____
'Whatever is destined to decay is called 'the world [of phenomena]' in the 
&#8203;[terminology of the] Noble One's training system.

_Yaṃ kho ānanda palokadhammaṃ ayaṃ vuccati ariyassa vinaye loko._
____

.Illustration
====
abhibhuyya lokaṃ

transcending the world [of sensuous pleasure]
====

• How about if I, by transcending the world [of sensuous pleasure] with 
resolve, were to abide with an awareness that was abundant and enlarged? Having 
done so, unvirtuous, spiritually unwholesome mental states such as greed, ill 
will, and aggressiveness would not exist. With their abandonment, my mind would 
become immeasurable, unlimited, and well developed.' +
_Yaṃnūnāhaṃ vipulena mahaggatena cetasā vihareyyaṃ abhibhuyya lokaṃ 
adhiṭṭhāya manasā. Vipulena hi me mahaggatena cetasā viharato abhibhuyya 
lokaṃ adhiṭṭhāya manasā ye pāpakā akusalā mānasā abhijjhāpi 
vyāpādāpi sārambhāpi te na bhavissanti. Tesaṃ pahānā aparittañca me 
cittaṃ bhavissati appamāṇaṃ subhāvitan ti_ (M.2.262).

