== Abhinibbatti

=== Renderings

- _abhinibbatteti_: to be manifested

- _abhinibbatteti_: to arouse

- _abhinibbatteti_: to make

- _abhinibbattati_: to manifest

- _abhinibbatta_: reborn

- _abhinibbatti_: rebirth

=== Illustrations

.Illustration
====
abhinibbattati

manifest
====

[quote, S.2.97]
____
Bhikkhus, just as heat is generated and fire manifests from the rubbing 
together of two fire-sticks,

_Seyyathā pi bhikkhave dvinnaṃ kaṭṭhānaṃ saṅghaṭṭasamodhānā 
usmā jāyati tejo abhinibbattati._
____

.Illustration
====
abhinibbatteti

is manifested
====

[quote, A.3.411]
____
In one yearning for sensuous pleasure a corresponding personal disposition is 
manifested, either meritorious or demeritorious.

_yaṃ kho bhikkhave kāmayamāno tajjaṃ tajjaṃ attabhāvaṃ 
abhinibbatteti puññabhāgiyaṃ vā apuññabhāgiyaṃ vā._
____

.Illustration
====
abhinibbattissathā

be manifested
====

____
-- If a stream of sense consciousness did not arise in the womb, would 
denomination-and-bodily-form develop there?

_viññāṇañca hi ānanda mātukucchismiṃ na okkamissatha api nu kho 
nāmarūpaṃ mātukucchismiṃ samuccissathā ti_
____

-- No, bhante.

____
-- Or if the stream of sense consciousness having entered the womb should leave 
it, would denomination-and-bodily-form be manifested in this world?

_viññāṇañca hi ānanda mātukucchiṃ okkamitvā vokkamissatha api nu kho 
nāmarūpaṃ itthattāya abhinibbattissathā ti_
____

-- No, bhante (D.2.63).

.Illustration
====
abhinibbatteti

arouse
====

____
As he abides contemplating the nature of the body internally he becomes 
perfectly inwardly collected and perfectly serene.

_tattha sammāsamādhiyati sammāvippasīdati_
____

[quote, D.2.216]
____
Being thus perfectly inwardly collected and perfectly serene he arouses 
knowledge and vision externally of others' bodies [according to reality]

_so tattha sammā samāhito sammāvippasanno bahiddhā parakāye 
ñāṇadassanaṃ abhinibbatteti._
____

.Illustration
====
abhinibbattessāmi

make
====

[quote, M.1.241]
____
Seeing a piece of wood, a man might think, 'I will make fire; I will produce 
heat.'

_aggiṃ abhinibbattessāmi tejo pātukarissāmī ti._
____

.Illustration
====
abhinibbatti

rebirth
====

____
What is birth? It is the birth, being born, arising, rebirth, appearance of 
aggregates, acquiring of senses by the various beings in the various classes of 
beings. This is called birth.

_yā tesaṃ tesaṃ sattānaṃ tamhi tamhi sattanikāye jāti sañjāti 
okkanti abhinibbatti khandhānaṃ pātubhāvo āyatanānaṃ paṭilābho 
ayaṃ vuccatāvuso jāti._
____

.Illustration
====
abhinibbatti

rebirth
====

____
One is reckoned according to wherever the rebirth of one's individuality occurs

_yattha yattheva attabhāvassa abhinibbatti hoti tena teneva saṅkhaṃ 
gacchati_
____

____
If the rebirth of one's individuality occurs in a clan of _khattiyas_, one is 
reckoned as a noble.

_khattiyakule ce attabhāvassa abhinibbatti hoti khattiyotveva saṅkhaṃ 
gacchati_
____

[quote, M.2.181]
____
If the rebirth of one's individuality occurs in a clan of brahmans, one is 
reckoned as a brahman.

_brāhmaṇakule ce attabhāvassa abhinibbatti hoti brāhmaṇotveva 
saṅkhaṃ gacchati._
____

.Illustration
====
abhinibbattiyā

rebirth
====

• Spiritual instability, bhante, is an illness, a carbuncle, a [piercing] 
arrow. +
_ejā bhante rogo ejā gaṇḍo ejā sallaṃ_

• It draws man to this or that state of individual existence and rebirth. +
_ejā imaṃ purisaṃ parikaḍḍhati tassa tasseva bhavassa abhinibbattiyā_

• Thus he arises in various [states of individual existence]. +
_Tasmā ayaṃ puriso uccāvacamāpajjati_ (D.2.283).

.Illustration
====
abhinibbattiyā

rebirth
====

____
Craving is the seamstress

_taṇhā sibbanī_
____

[quote, A.3.400]
____
For craving stitches him to this or that state of individual existence and 
rebirth

_taṇhā hi naṃ sibbati tassa tasseva bhavassa abhinibbattiyā._
____

.Illustration
====
abhinibbatti

rebirth
====

____
Rebirth is suffering; non-rebirth is happiness.

_abhinibbatti kho āvuso dukkhā anabhinibbatti sukhā._
____

____
When there is rebirth, this suffering can be expected:

_abhinibbattiyā āvuso sati idaṃ dukkhaṃ pāṭikaṅkhaṃ_
____

Cold, heat, hunger, thirst, defaecation, urination, being burnt, beaten, 
chopped, being scolded in gatherings with relatives and old friends (A.5.121).

.Illustration
====
abhinibbattā

reborn
====

[quote, A.4.401]
____
There are beings unalike in body but alike in state of refined awareness, for 
example the devas newly reborn in the Brahmā group.

_Santi bhikkhave sattā nānattakāyā ekattasaññino seyyathā pi devā 
brahmakāyikā paṭhamābhinibbattā._
____

