== Acakkhussa

=== Renderings

- _acakkhussa_: gloomy

- _acakkhussa_: bad for the eyes

- _acakkhussa_: unsightly

=== Introduction

==== Three occurrences

_Acakkhussa_ occurs four times in the scriptures, and the occurrences at 
A.3.250 and Vin.2.137 are duplicates. Therefore only three times, all in the 
Illustrations below.

=== Illustrations

.Illustration
====
acakkhussā

gloomy
====

[quote, Vin.2.148]
____
Now at the time dwelling-places had no windows. They were gloomy and bad 
smelling.

_avātapānakā honti acakkhussā duggandhā_

The Buddha said: 'I allow three kinds of window aperture'.
____

.Illustration
====
acakkhusso

unsightly
====

[quote, Vin.2.137; A.3.250]
____
Bhikkhus, there are five disadvantages in not chewing tooth-wood:

_ādīnavā dantakaṭṭhassa akhādane_

&#8203;[Bad mouth hygiene] is unsightly,

_acakkhussaṃ_

The mouth stinks, etc.

_mukhaṃ duggandhaṃ hoti_

There are five advantages in chewing tooth-wood:

_ānisaṃsā dantakaṭṭhassa khādane_

&#8203;[Good mouth hygiene] is sightly,

_cakkhussaṃ_

The mouth does not stink, etc.

_mukhaṃ na duggandhaṃ hoti._
____

.Illustration
====
acakkhusso

bad for the eyes
====

[quote, A.3.256]
____
Bhikkhus, there are these five disadvantages of a campfire.

_ādīnavā aggismiṃ_

It is bad for the eyes,

_acakkhusso_

It causes a bad complexion,

_dubbaṇṇakaraṇo_

It causes weakness

_dubbalakaraṇo_

It promotes gregariousness

_saṅgaṇikāpavaddhano_

It leads to gossip

_tiracchānakathāpavattaniko._
____

