== Acakkhussa

=== Renderings

- _acakkhussa_: gloomy

- _acakkhussa_: bad for the eyes

- _acakkhussa_: unsightly

=== Introduction

==== Three occurrences

_Acakkhussa_ occurs four times in the scriptures, and the occurrences at 
A.3.250 and Vin.2.137 are duplicates. Therefore only three times, all in the 
Illustrations below.

=== Illustrations

.Illustration
====
acakkhussā

gloomy
====

____
Now at the time dwelling-places had no windows. They were gloomy and bad 
smelling.

_avātapānakā honti acakkhussā duggandhā_
____

The Buddha said: 'I allow three kinds of window aperture' (Vin.2.148).

.Illustration
====
acakkhusso

unsightly
====

____
Bhikkhus, there are five disadvantages in not chewing tooth-wood:

__ādīnavā dantakaṭṭhassa akhādane_
____

____
&#8203;[Bad mouth hygiene] is unsightly,

_acakkhussaṃ_
____

____
The mouth stinks, etc.

_mukhaṃ duggandhaṃ hoti_
____

____
There are five advantages in chewing tooth-wood:

__ānisaṃsā dantakaṭṭhassa khādane_
____

____
&#8203;[Good mouth hygiene] is sightly,

_cakkhussaṃ_
____

[quote, Vin.2.137; A.3.250]
____
The mouth does not stink, etc.

_mukhaṃ na duggandhaṃ hoti._
____

.Illustration
====
acakkhusso

bad for the eyes
====

____
Bhikkhus, there are these five disadvantages of a campfire.

__ādīnavā aggismiṃ_
____

____
It is bad for the eyes,

_acakkhusso_
____

____
It causes a bad complexion,

_dubbaṇṇakaraṇo_
____

____
It causes weakness

_dubbalakaraṇo_
____

____
It promotes gregariousness

_saṅgaṇikāpavaddhano_
____

[quote, A.3.256]
____
It leads to gossip

_tiracchānakathāpavattaniko._
____

