== Adhiṭṭhāna; Adhiṭṭhāti

=== Renderings

- _adhiṭṭhāna_: obstinate adherence

- _adhiṭṭhāna_: resolve

- _adhiṭṭhāti_: to doggedly assume

- _adhiṭṭhāti_: to concentrate

- _adhiṭṭhāti_: to organise

- _adhiṭṭhāti_: to formally determine

- _adhiṭṭhāti_: to resolve on

- _anadhiṭṭhāti_: to firmly reject

- _svādhiṭṭhitaṃ adhiṭṭhāti_: to properly concentrate

- _adhiṭṭhita_: firmly established

- _adhiṭṭhita_: committed

- _adhiṭṭhita_: controlled

=== Introduction

==== Dictionaries: concurrence

The Pāli dictionaries broadly concur with the renderings given here, though 
DOP says 'fixes the mind on' and 'supervise' and 'not undertaken' where we 
prefer 'concentrate' and 'organise' and 'firmly reject.'

==== On ignoring the dictionaries

In translation, dictionary renderings are mostly ignored. For example,

1. Horner says bhikkhus were 'looking after' repairs where we would say 
'organising' (Vin.2.159).

2. Bodhi says a shopkeeper 'diligently applies' himself to his work where we 
would say he 'carefully concentrates' (_sakkaccaṃ kammantaṃ 
adiṭṭhāti_) on it.

3. Norman often rejects the usual translations for the word. We accept his 
'established' at Th.v.768, a rendering not noted in the dictionaries.

=== Illustrations

.Illustration
====
adhiṭṭhānā

obstinate adherence
====

____
And what Ānanda, is the perception of disgust for the whole world [of 
phenomena]?

_sabbaloke anabhiratasaññā_
____

[quote, A.5.111]
____
In this regard, Ānanda, for whatever in the world [of phenomena] there is 
clinging, grasping, obstinate adherence, stubborn attachment, and 
identification, a bhikkhu abides abandoning, not grasping.

_bhikkhu ye loke upayupādānā cetaso adhiṭṭhānābhinivesānusayā te 
pajahanto viharati na upādiyanto._
____

.Illustration
====
adhiṭṭhānā

resolve
====

For a _khattiya_ (_khattiyā_), gaining power is his resolve 
(_balādhiṭṭhānā_).

For a brahman, learning the sacred texts is his resolve 
(_mantādhiṭṭhānā_).

For a householder, gaining a craft is his resolve (_sippādhiṭṭhānā_).

For a woman, having a son is her resolve (_puttādhiṭṭhānā_).

For a thief, gaining a caravan is his resolve (_saṭhādhiṭṭhānā_).

For an ascetic (_samaṇā_) maintaining virtue is his resolve 
(_sīlādhiṭṭhānā_) (A.3.363).

.Illustration
====
anadhiṭṭhānā

firmly reject
====

[quote, M.2.237]
____
Some ascetic or Brahmanist may... in every way firmly reject the ties to 
individual existence in the sensuous plane of existence

_sabbaso kāmasaṃyojanānaṃ anadhiṭṭhānā._
____

.Illustration
====
adhiṭṭhāti

doggedly assume
====

[quote, S.3.114]
____
He clings to bodily form, grasps it, and doggedly assumes that bodily form is 
"my [absolute] Selfhood."

_so rūpaṃ upeti upādiyati adhiṭṭhāti attā me ti._
____

.Illustration
====
adhiṭṭhātabbā

concentrate
====

____
When resentment has arisen for someone (_āghāto jāyetha_), one can 
concentrate on the ownership of karmically consequential conduct by that person

_kammassakatā tasmiṃ puggale adhiṭṭhātabbā_
____

• 'This Venerable is owner of his karmically consequential conduct, inheritor 
of it, born of it, intimately related to it, has it as his refuge. He is the 
inheritor of whatever karmically consequential conduct he undertakes whether 
meritorious or demeritorious' +
☸ _kammassako ayamāyasmā kammadāyādo... tassa dāyādo bhavissatī ti_).

• This is how resentment for that person can be dispelled +
☸ _evaṃ tasmiṃ puggale āghāto paṭivinetabbo_) (A.3.185).

.Illustration
====
adhiṭṭhāti

concentrate
====

• In this regard a bhikkhu possesses faith [in the perfection of the Perfect 
One's transcendent insight], virtue, learning, generosity, and wisdom. He 
thinks, 'Oh, that at the demise of the body at death, I might be reborn in the 
company of wealthy _khattiyas_.' He fixes his mind on that idea, concentrates 
on it, and develops it +
☸ _so taṃ cittaṃ dahati taṃ cittaṃ adhiṭṭhāti taṃ cittaṃ 
bhāveti_).

These aspirations and musings of his, when developed and cultivated, lead to 
his rebirth there (M.3.99).

.Illustration
====
svādhiṭṭhitaṃ adhiṭṭhehi

properly concentrate
====

[quote, Th.v.560]
____
Out of tender concern the Teacher gave me a [clean] foot-cloth, [saying]: 
'Properly concentrate on this pure thing somewhere quiet.'

_Anukampāya me satthā pādāsi pādapuñchaniṃ +
Etaṃ suddhaṃ adhiṭṭhehi ekamantaṃ svadhiṭṭhitaṃ._
____

Comment

Commentary: _manasikārena svadhiṭṭhitaṃ katvā._

Rhys Davids: 'Fix thou thy mind on this clean thing, the while/Well 
concentrated thou dost sit apart.

.Illustration
====
svādhiṭṭhitaṃ adhiṭṭhāti

properly concentrate
====

Suppose a foolish mountain cow -- foolish, incompetent, unknowledgeable about 
roaming mountains, improficient -- were to think, 'How about if I ate grass I 
have never eaten before and drank water I have never drunk before?' She would 
lift her hind hoof without having firmly placed her front hoof and thus would 
not go where she had never gone before. And neither would she safely return to 
where she had come from.

In the same way, a bhikkhu -- foolish, incompetent, unknowledgeable about first 
jhāna, improficient -- enters first jhāna but does not stick with that 
&#8203;[successful] meditation object (_so taṃ nimittaṃ na āsevati_), does not 
develop it (_na bhāveti_), cultivate it (_na bahulīkaroti_), or properly 
concentrate on it (_na svādhiṭṭhitaṃ adhiṭṭhāti_). The thought 
occurs to him, 'How about if I entered second jhāna?' He is not able to so. 
And when he tries to re-enter first jhāna he is not able to do that either. 
This is called a bhikkhu who has slipped and fallen from both sides, like the 
foolish mountain cow (A.4.418).

.Illustration
====
adhiṭṭheyyāsi

concentrate
====

If the torpor is unabandoned, then focus on the mental image of light 
(_ālokasaññaṃ manasikareyyāsi_), concentrate on the mental image of day 
(_divāsaññaṃ adhiṭṭheyyāsi_). As by day, so at night; as at night, so 
by day (_yathā divā tathā rattiṃ yathā rattiṃ tathā divā_).

If the torpor is unabandoned, then perceiving the constant nature of reality 
(_pacchāpuresaññī_), concentrate on pacing back and forth (_caṅkamaṃ 
adhiṭṭheyyāsi_), your senses inwardly immersed (_antogatehi indriyehi_), 
your mind not straying outwards (_abahigatena mānasena_) (A.4.86).

.Illustration
====
adiṭṭhāti

concentrate
====

____
Possessed of three factors a shopkeeper is unable to either gain or develop 
wealth. What three? Neither in the morning, afternoon, or evening does he 
carefully concentrate on his business

_na sakkaccaṃ kammantaṃ adiṭṭhāti_
____

[quote, A.1.115]
____
Likewise, possessed of three factors a bhikkhu is incapable of either gaining 
an unattained spiritually wholesome factor, or developing an attained 
spiritually wholesome factor. Which three? Neither in the morning, afternoon, 
or evening does he carefully concentrate on an object of meditation

_na sakkaccaṃ samādhinimittaṃ adhiṭṭhāti._
____

.Illustration
====
adhiṭṭheyya

concentrate on
====

The _Mettā Sutta_ says an arahant would have an unlimited attitude to all 
beings (_sabbabhūtesū mānasaṃ bhāvaye aparimānaṃ_) and that as long as 
he was free of torpor (_yāvatassa vigatamiddho_) he would concentrate on this 
&#8203;[practice] mindfully (_etaṃ satiṃ adhiṭṭheyya_) (Sn.v.151).

.Illustration
====
adhiṭṭhenti

organise
====

[quote, Vin.2.159]
____
Those bhikkhus who organised the building work

_yepi bhikkhū navakammaṃ adhiṭṭhenti._
____

.Illustration
====
adhiṭṭhāti

organise
====

When a bhikkhu is having a hut built for himself by a benefactor, then standing 
where there are no crops (_appaharite ṭhitena_), he should organise the use 
of a method that involves two or three layers of facing material 
(_dvatticchadanassa pariyāyaṃ adhiṭṭhātabbanti_) around the door. 
Should he organise the use of more than that, even if standing where there are 
no crops (_tato ce uttariṃ appaharite pi ṭhito adhiṭṭhaheyya_), it is 
an offence of pācittiya.

If he organises (the work) standing where there are crops it is a dukkaṭa 
offence (_sace harite ṭhito adhiṭṭhāti āpatti dukkaṭassa_) 
(Vin.4.47-8).

.Illustration
====
adhiṭṭhāyā

organise
====

It is an offence for a bhikkhu to commit an act of murder either by doing it 
himself or by organising someone else to do it, which is defined as:

[quote, Vin.3.74]
____
'by organising' means: while organising he orders "Hit thus. Strike thus. Kill 
thus"'

_Adhiṭṭhāyā ti adhiṭṭhahitvā āṇāpeti evaṃ vijjha evaṃ pahara 
evaṃ ghātehī ti._
____

.Illustration
====
adhiṭṭhātuṃ

formally determine [as personal possessions]
====

[quote, Vin.1.297]
____
I allow you bhikkhus to formally determine the three robes [as personal 
possessions]

_Anujānāmi bhikkhave ticīvaraṃ adhiṭṭhātuṃ._
____

.Illustration
====
adhiṭṭhātabbo

formally determine [as a water-strainer]
====

Bhikkhus travelling a highroad should carry a water-strainer.

[quote, Vin.2.119]
____
If there is no strainer or regulation water-pot, then a corner of the outer 
robe should be formally determined [as a water-strainer] with the words "I will 
drink [water] having strained it with this.'

_Sace na hoti parissāvanaṃ vā dhammakarako vā saṅghāṭikaṇṇo pi 
adhiṭṭhātabbo iminā parissāvetvā pivissāmī ti._
____

.Illustration
====
adhiṭṭhahaṃ

resolve
====

[quote, A.3.376]
____
If one's energy is excessive it leads to restlessness; if too lax it leads to 
indolence. Therefore Soṇa, resolve [to apply yourself] moderately 
energetically.

_accāraddhaṃ viriyaṃ uddhaccāya saṃvattati. Atilīnaṃ viriyaṃ 
kosajjāya saṃvattati. Tasmātiha tvaṃ soṇa viriyasamataṃ 
adhiṭṭhaha._
____

.Illustration
====
anadhiṭṭhāya

firmly rejecting
====

• Firmly rejecting the ego, I saw the supreme landing-place. +
_Anadhiṭṭhāya attānaṃ titthamaddakkhimuttamaṃ_ (Th.v.766).

.Illustration
====
adhiṭṭhāya

firmly established
====

[quote, D.2.99; S.5.153]
____
The Blessed One suppressed his illness with energy and lived on having firmly 
established the aspiration for further life.

_Atha kho bhagavā taṃ ābādhaṃ viriyena paṭippanāmetvā 
jīvitasaṅkhāraṃ adhiṭṭhāya vihāsi._
____

.Illustration
====
adhiṭṭhito

committed
====

[quote, Sn.v.824]
____
They considered him wise when he was committed to faring alone, but now that he 
is devoted to sexual intercourse he is harassed as a fool.

_Paṇḍito ti samaññāto ekacariyaṃ adhiṭṭhito +
Athāpi methune yutto mandova parikissati._
____

.Illustration
====
adhiṭṭhitaṃ

firmly established
====

[quote, Th.v.768]
____
The Buddha, cleanser of virulent spiritual flaws, removed the spiritual shackle 
&#8203;[of grasping] which had long been lurking in me, long been firmly established 
in me.

_Dīgharattānusayitaṃ cirarattamadhiṭṭhitaṃ +
Buddho me pānudi ganthaṃ visadosappavāhano ti._
____

.Illustration
====
adhiṭṭhahī

firmly established
====

[quote, D.3.159]
____
The Buddha is 'firmly established in non-anger'

_akkodhañca adhiṭṭhahī._
____

.Illustration
====
adhiṭṭhitaṃ

controlled
====

[quote, Th.v.1143]
____
Being [yourself] controlled by the power of the four perversions [of 
perception, mind, and view], mind, you lead me round and round like an ox 
around the threshing-floor.

_Catubbipallāsavasaṃ adhiṭṭhitaṃ gomaṇḍalaṃ va parinesi citta 
maṃ._
____

COMMENT

_Catubbipallāsa_: 'the four perversions [of perception, mind, and view].' 
_Cattāro'me bhikkhave saññāvipallāsā cittavipallāsā 
diṭṭhivipallāsā. Katame cattāro? Anicce bhikkhave niccanti... Dukkhe 
bhikkhave sukhanti... Anattani bhikkhave attāti... Asubhe bhikkhave subhan ti 
saññāvipallāso cittavipallāso diṭṭhivipallāso_ (A.2.52).

