== Agārasmā anagāriyaṃ pabbajito

=== Renderings

- _agārasmā anagāriyaṃ pabbajito_: gone forth from the household life into 
the ascetic life

- _pabbajito_: gone forth [into the ascetic life]

=== Introduction

==== Agārasmā anagāriyaṃ: abandonment of the household life

_Agāra_ means house or hut, 'usually implying the comforts of living at home,' 
says PED (sv _Agāra_). DOP calls _agāra_ 'the household life,' and _anagāra_ 
'the homeless state; the ascetic life.' We render _agārasmā anagāriyaṃ 
pabbajito_ as 'gone forth from the household life into the ascetic life.' What 
is abandoned in going forth is not a roof over one's head, but the property, 
security, and pleasures of lay people, as expressed here:

[quote, M.1.179]
____
Abandoning an inconsiderable or considerable fortune, and an inconsiderable or 
considerable circle of relatives, he shaves off his hair and beard, clothes 
himself in ochre robes, and goes forth from the household life into the ascetic 
life.

_So aparena samayena appaṃ vā bhogakkhandhaṃ pahāya mahantaṃ vā 
bhogakkhandhaṃ pahāya appaṃ vā ñātiparivaṭṭaṃ pahāya mahantaṃ 
cā ñātiparivaṭṭaṃ pahāya kesamassuṃ ohāretvā kāsāyāni 
vatthāni acchādetvā agārasmā anagāriyaṃ pabbajati._
____

=== Illustrations

.Illustration
====
agārasmā anagāriyaṃ pabbajeyyan

go forth from the household life into the ascetic life; pabbājetu, let someone 
go forth [into the ascetic life]
====

[quote, Ud.57]
____
Soṇa Koṭikaṇṇa said 'It is not easy while living the household life to 
live the religious life, utterly perfect and pure as a polished shell.'

_nayidaṃ sukaraṃ agāraṃ ajjhāvasatā ekantaparipuṇṇaṃ 
ekantaparisuddhaṃ saṅkhalikhitaṃ brahmacariyaṃ carituṃ_

He said 'How about if I shaved off my hair and beard, and went forth from the 
household life into the ascetic life?'

_Yannūnāhaṃ kesamassuṃ ohāretvā kāsāyāni vatthāni acchādetvā 
agārasmā anagāriyaṃ pabbajeyyan ti_

Let me go forth [into the ascetic life], Master Mahākaccāna!"

_Pabbājetu maṃ bhante ayyo mahākaccāyano ti._

Mahākaccāna replied, "It is hard, Soṇa, the life-long, one-meal-a-day, 
solitary bed, celibate life. Please, stay as a householder, apply yourself to 
the Buddha's training system and, on the Observance Day, to observing 
one-meal-a-day, the solitary bed, and celibacy.

_dukkaraṃ kho soṇa yāvajīvaṃ ekabhattaṃ ekaseyyaṃ brahmacariyaṃ 
iṅgha tvaṃ soṇa tattheva agārikabhuto samāno buddhānaṃ sāsanaṃ 
anuyuñja kālayuttaṃ ekabhattaṃ ekaseyyaṃ brahmacariyaṃ ti._
____

.Illustration
====
pabbajitā

gone forth [into the ascetic life]
====

[quote, S.1.15]
____
Having abandoned the household life and gone forth [into the ascetic life], 
having abandoned their beloved sons and cattle, having abandoned attachment and 
hatred, having discarded uninsightfulness into reality, the arahants, those 
whose _āsavas_ are destroyed, are those in the world no longer avid.

_Hitvā agāraṃ pabbajitā hitvā puttaṃ pasuṃ piyaṃ +
Hitvā rāgañca dosañca avijjañca virājiya +
Khīṇāsavā arahanto te lokasmiṃ anussukā ti._
____

.Illustration
====
agārasmā anagāriyaṃ pabbajito

gone forth from the household life into the ascetic life
====

[quote, A.1.148]
____
If I who have forsaken sensuous pleasures and gone forth from the household 
life into the ascetic life, should pursue sensuous pleasures still worse than 
before, that were unseemly of me.

_Ahañce'va kho pana yādisake vā kāme ohāya agārasmā anagāriyaṃ 
pabbajito tādisake vā kāme pariyeseyyaṃ tato vā pāpiṭṭhatare na me 
taṃ assa patirūpanti._
____

.Illustration
====
agārasmā anagāriyaṃ pabbajitvā

go forth from the household life into the ascetic life
====

[quote, Ud.51]
____
Those of the four castes, _khattiyas_, brahmans, _vessas_, and _suddas_, having 
gone forth from the household life into the ascetic life in the teaching and 
training system made known by the Perfect One, give up their former names and 
identities and are just called 'ascetic disciples of the Sakyans' Son.'

_cattāro me vaṇṇā khattiyā brāhmaṇā vessā suddā te 
tathāgatappavedite dhammavinaye agārasmā anagāriyaṃ pabbajitvā jahanti 
purimāni nāmagottāni samaṇā sakyaputtiyātveva saṅkhaṃ gacchantī._
____

.Illustration
====
pabbajitā

gone forth [into the ascetic life]
====

[quote, Thī.v.433]
____
Seven days after going forth [into the ascetic life] I attained the three final 
knowledges

_sattāhaṃ pabbajitā tisso vijjā aphassayiṃ._
____

.Illustration
====
pabbajjā

going forth [into the ascetic life]
====

[quote, D.2.251]
____
The going forth [into the ascetic life] of all those noble young men was 
not in vain or barren, but fruitful and productive.

_iti kho pana sabbesaṃ yeva tesaṃ kulaputtānaṃ amoghā pabbajjā ahosi 
avañjhā saphalā saudrayā ti._
____
