== Ajjhupekkhati

=== Renderings

- _ajjhupekkhati_: passively observe

=== Illustrations

.Illustration
====
ajjhupekkhitvā

passively observe
====

[quote, S.5.440]
____
-- 'Bhikkhus, if one's clothes or head were on fire, what should be done about it?'

-- 'Bhante, if one's clothes or head were on fire, to extinguish one's blazing 
clothes or head one should arouse extraordinary eagerness, endeavour, vigour, 
exertion, resolution, mindfulness, and full consciousness.'

-- 'Bhikkhus, one might passively observe one's blazing clothes or head, pay 
them no attention (_ajjhupekkhitvā amanasikaritvā_), but in order to 
understand the four noble truths according to reality, if they are not 
understood, one should arouse extraordinary eagerness, endeavour, vigour, 
exertion, resolution, mindfulness, and full consciousness.

_Ādittaṃ bhikkhave celaṃ vā sīsaṃ vā ajjhupekkhitvā amanasikaritvā 
anabhisametānaṃ catunnaṃ ariyasaccānaṃ yathābhūtaṃ abhisamayāya 
adhimatto chando ca vāyāmo ca ussāho ca ussoḷhi ca appaṭivānī ca sati 
ca sampajaññañca karaṇīyaṃ._
____

.Illustration
====
ajjhupekkheyyāmā

passively observe
====

A deer-catcher was frustrated in his attempts to catch a certain herd of deer. 
The deer were eating the bait without being caught. But he realised that if he 
scared away this herd of deer, all the other deer would be scared away too. So 
he and his companions decided:

[quote, M.1.155]
____
Suppose that we were to passively observe the fourth herd of deer?

_Yannūna mayaṃ catutthe migajāte ajjhupekkheyyāmā'ti_

... So the deer-catcher and his companions passively observed the fourth herd of deer.

_ajjhupekkhiṃsu kho bhikkhave nevāpiko ca nevāpikaparisā ca catutthe migajāte._
____

.Illustration
====
ajjhupekkhissatha

passively observe
====

When Venerable Udāyī contradicted Venerable Sāriputta three times, 
Sāriputta was surprised that none of the bhikkhus applauded him.

[quote, A.3.194]
____
Venerable Udāyī contradicts me for up to the third time, and not a single 
bhikkhu applauds me.

_yāva tatiyampi kho me āyasmā udāyī paṭikkosati na ca me koci bhikkhu 
anumodati_

&#8203;[The Buddha rebuked Venerable Ānanda:]

'Ānanda, would you just simply passively observe an elder bhikkhu while he is 
being harassed?

_atthi nāma ānanda theraṃ bhikkhuṃ vihesiyamānaṃ ajjhupekkhissatha_

... Truly, Ānanda, compassion does not develop in allowing an elder bhikkhu to 
be harassed'

_Na hi nāma ānanda kāruññampi bhavissati theramhi bhikkhumhi vihesiyamānamhī ti._
____

.Illustration
====
ajjhupekkhitabbo

passively observe
====

[quote, A.1.126-7]
____
'What kind of person should be passively observed, not associated with, 
followed, and honoured? Someone who is ill-tempered, who when anything, however 
trifling, is said to him becomes upset. Why so? Because he might curse or abuse 
or do some injury:

Therefore this kind of person should be passively observed, not associated 
with, followed, and honoured'

_tasmā evarūpo puggalo ajjhupekkhitabbo na sevitabbo na bhajitabbo na 
payirupāsitabbo._
____

.Illustration
====
ajjhupekkhato

passively observe
====

[quote, M.2.223]
____
He discerns thus: "When I confront the source of this suffering with effort, by 
confronting it with effort [the suffering] fades away.

_So evaṃ pajānāti imassa kho me dukkhanidānassa saṅkhāraṃ padahato 
saṅkhārappadhānā virāgo hoti_

When the source of this suffering is passively observed, through developing 
detached awareness, [the suffering] fades away.

_imassa pana me dukkhanidānassa ajjhupekkhato upekkhaṃ bhāvayato virāgo 
hotī ti._
____

.Illustration
====
ajjhupekkhitā

passively observe
====

____
At that time he abides contemplating the nature of certain objects of the 
systematic teachings, fully consciously, and mindfully, having eliminated greed 
and dejection in regard to the world [of phenomena].

_dhammesu dhammānupassī bhikkhave tasmiṃ samaye bhikkhu viharati ātāpī 
sampajāno satimā vineyya loke abhijjhādomanassaṃ_
____

[quote, M.3.84]
____
With the abandonment of greed and dejection, seeing [certain objects of the 
systematic teachings] carefully with discernment, he is one who carefully, 
passively observes.

_so yaṃ taṃ abhijjhādomanassānaṃ pahānaṃ taṃ paññāya disvā 
sādhukaṃ ajjhupekkhitā hoti._
____

.Illustration
====
ajjhupekkhitā

passively observe
====

____
'Whenever, Ānanda, the mind becomes collected in a bhikkhu whose body is 
tranquil and joyful, on that occasion the enlightenment factor of inward 
collectedness is aroused in the bhikkhu;

_Yasmiṃ samaye ānanda bhikkhuno passaddhakāyassa sukhino cittaṃ 
samādhiyati samādhisambojjhaṅgo tasmiṃ samaye bhikkhuno āraddho hoti_
____

[quote, S.5.332]
____
'Whenever, Ānanda, a bhikkhu carefully, passively observes his mind thus 
collected, on that occasion the enlightenment factor of detached awareness is 
aroused in the bhikkhu.

_Yasmiṃ samaye ānanda bhikkhu tathā samāhitaṃ cittaṃ sādhukaṃ 
ajjhupekkhitā hoti upekkhāsambojjhaṅgo tasmiṃ samaye bhikkhuno āraddho 
hoti._
____

.Illustration
====
ajjhupekkhati

passively observe
====

[quote, A.1.256]
____
A goldsmith should focus on three methods of working, not exclusively, but 
from time to time: blowing, sprinkling, and passively observing.

_kālena kālaṃ abhidhamati kālena kālaṃ udakena paripphoseti kālena 
kālaṃ ajjhupekkhati._

Because:

Exclusively blowing means the gold will burn up

_ekantaṃ abhidhameyya ṭhānaṃ taṃ jātarūpaṃ ḍaheyya_

Exclusively sprinkling with water will cool it

_ekantaṃ udakena paripphoseyya ṭhānaṃ taṃ jātarūpaṃ nibbāyeyya_

Exclusively passively observing will stop the gold coming to full perfection

_ekantaṃ ajjhupekkheyya ṭhānaṃ taṃ jātarūpaṃ na sammā paripākaṃ gaccheyya._
____

.Illustration
====
ajjhupekkhati

passively observe
====

[quote, A.3.435]
____
Bhikkhus, if a bhikkhu does six things, he cannot become one who realises 
unsurpassed freedom from inward distress. What six?

_abhabbo anuttaraṃ sītibhāvaṃ sacchikātuṃ_

If he checks not the mind when it should be checked

_cittaṃ na niggaṇhāti_

exerts not the mind when it should be exerted

_cittaṃ na paggaṇhāti_

gladdens not the mind when it should be gladdened

_cittaṃ na sampahaṃseti_

does not passively observe the mind when it should be so observed

_yasmiṃ samaye cittaṃ ajjhupekkhitabbaṃ tasmiṃ samaye cittaṃ na ajjhupekkhati._
____

.Illustration
====
ajjhupekkhitabbo

passively observe
====

[quote, A.4.45]
____
A wood fire (_kaṭṭhaggi_) must from time to time

be kindled

_kālena kālaṃ ujjaletabbo_

passively observed

_kālena kālaṃ ajjhupekkhitabbo_

quenched

_kālena kālaṃ nibbāpetabbo_

discarded

_kālena kālaṃ nikkhipitabboti._
____

