== Ajjhosāna

=== Renderings

- _ajjhosāna_: cleaving

=== Illustrations

.Illustration
====
ajjhosānaṃ

cleaving
====

• Because of fondness and attachment, cleaving._** +
**☸ chandarāgaṃ paṭicca ajjhosānaṃ_

[quote, A.4.401]
____
Because of cleaving, possessiveness.

_ajjhosānaṃ paṭicca pariggaho._
____

.Illustration
====
ajjhosānaṃ

cleaving
====

[quote, M.1.191]
____
The fondness, clinging, attraction, and cleaving within these five grasped 
aggregates is the origin of suffering._

_yo imesu pañcasupādānakkhandhesu chando ālayo anunayo ajjhosānaṃ so 
dukkhasamudayo._
____

.Illustration
====
ajjhosāya tiṭṭhato

cleaving to
====

[quote, S.4.76]
____
In seeing a visible object with mindfulness muddled, focusing on the agreeable 
aspect, one experiences it with a mind of attachment and persists in cleaving 
to it.

_Rūpaṃ disvā sati muṭṭhā piyaṃ nimittaṃ manasikaroto +
Sārattacitto vedeti tañca ajjhosa tiṭṭhati._
____

.Illustration
====
ajjhosāya

cleaving to
====

[quote, S.4.71]
____
Whether enjoying a sweet delicious tasteable object, or sometimes tasting what 
is unpalatable, eat the sweet tasteable object without cleaving, and do not 
show dislike for the unpalatable.

_Rasañca bhotvā sāditañca sāduṃ athopi bhotvāna asādumekadā +
Sāduṃ rasaṃ nājjhosāya bhuñje virodhamāsādusu nopadaṃsaye._
____

.Illustration
====
ajjhosāya

cleaving to
====

• Whatever sense impression he experiences, pleasant, unpleasant, or neutral, 
he takes delight in that sense impression, he welcomes it, and persists in 
cleaving to it. In so doing, spiritually fettering delight arises. +
_yaṃ kiñci vedanaṃ vedeti sukhaṃ vā dukkhaṃ vā adukkhamasukhaṃ vā 
so taṃ vedanaṃ abhinandati abhivadati ajjhosāya tiṭṭhati tassa taṃ 
vedanaṃ abhinandato abhivadato ajjhosāya tiṭṭhato uppajjati nandī_ 
(M.1.266)

