== Amatadhātu

=== Renderings

- _amatadhātu_: the immortal phenomenon

- _amatadhātu_: deathlessness

=== Introduction

==== The amatadhātu of arahants: deathlessness

PED (under _dhātu_) says that -_dhātu_ in _amatadhātu_ 'is so far weakened 
in meaning, that it simply corresponds to the English abstract suffix -hood or 
-ity.' But with no 'deathless-hood' or 'deathless-ity,' it would be 
'deathlessness.' When linked to freedom from attachment it means arahantship:

[quote, It.46]
____
Having touched with his very being deathlessness, which is free from attachment,

_Kāyena amataṃ dhātuṃ phassayitvā nirupadhiṃ._
____

Because it implies arahantship, _amataṃ dhātuṃ_ therefore equals 
_amataṃ_, which is defined as follows:

[quote, S.5.8]
____
The destruction of attachment, hatred, and undiscernment of reality: this is 
called the Deathless.

_Yo so bhikkhu rāgakkhayo dosakkhayo mohakkhayo idaṃ vuccati amataṃ._
____

==== The amatadhātu of non-arahants: the immortal phenomenon

Confusingly, there is another _amatadhātu_ that is realised by non-arahants, a 
state which is also called _nibbāna._ We call this 'the immortal phenomenon.' 
We will show that it is equivalent to inward collectedness that is focused upon 
the unabiding [phenomena] (_animitto cetosamādhi_). This latter state likewise 
does not necessarily mean arahantship, as Venerable MahāMoggallāna 
discovered: while he abided therein, his mind pursued phantasms.

==== Animitto cetosamādhi: Venerable MahāMoggallāna's mind pursued phantasms

MahāMoggallāna said:

____
Here, friends, while I was alone in solitary retreat, a reflection arose in my 
mind thus: 'It is said, "inward collectedness that is focused upon the 
unabiding [phenomena]; inward collectedness that is focused upon the unabiding 
&#8203;[phenomena]." What now is the inward collectedness that is focused upon the 
unabiding [phenomena]?'

_Animitto cetosamādhi animitto cetosamādhīti vuccati katamo nu kho animitto 
cetosamādhī ti_
____

____
... Then, friends, it occurred to me:

_Tassa mayhaṃ āvuso etadahosi_
____

____
... In this regard a bhikkhu, by not focusing upon any abiding phenomenon,

_Idha bhikkhu sabbanimittānaṃ amanasikārā_
____

____
... enters and abides in the inward collectedness that is focused upon the 
unabiding [phenomena].

_animittaṃ cetosamādhiṃ upasampajja viharati_
____

____
... This is called the inward collectedness that is focused upon the unabiding 
&#8203;[phenomena].

_ayaṃ vuccati animitto cetosamādhī ti._
____

____
... Then, friends, by not focusing upon any abiding phenomenon,

_So khvāhaṃ āvuso sabbanimittānaṃ amanasikārā_
____

____
... I entered and dwelt in inward collectedness that is focused upon the 
unabiding [phenomena].

_animittaṃ cetosamādhiṃ upasampajja viharāmi_
____

[quote, S.4.263-269]
____
... While I abided therein my mind pursued phantasms.

_tassa mayhaṃ āvuso iminā vihārena viharato nimittānusārī viññānam 
hoti._
____

==== Focusing one's mind on the immortal phenomenon

• In the _Mahāmāluṅkya Sutta_ the Buddha discusses the path and practice 
to abandon the five ties to individual existence in the low plane of existence 
(i.e. the path to non-returnership). +
☸ _Katamo cānanda maggo katamā paṭipadā pañcannaṃ orambhāgiyānaṃ 
saṃyojanānaṃ pahānāya_? (M.1.435).

He explains that in this path and practice a bhikkhu:

1. enters jhāna, then

2. contemplates the five aggregates as an illness, a carbuncle, a [piercing] 
arrow, suffering etc, then
+
****
_te dhamme aniccato dukkhato rogato gaṇḍato sallato aghato ābādhato 
parato palokato suññato anattato samanupassati_
****

3. averts his mind from those states, then
+
****
_So tehi dhammehi cittaṃ paṭivāpeti_
****

4. focuses his mind on the immortal phenomenon:
+
****
_so tehi dhammehi cittaṃ paṭivāpetvā amatāya dhātuyā cittaṃ 
upasaṃharati_
****

5. Focusing on the immortal phenomenon is followed in the sutta by the 
following reflection:

[quote, M.1.435]
____
This is peaceful, this is sublime, namely: the quelling of all originated 
phenomena, the relinquishment of the whole phenomenon of attachment, the 
destruction of craving, the passing away [of originated phenomena], the ending 
&#8203;[of originated phenomena], the Untroubled.

_etaṃ santaṃ etaṃ paṇītaṃ yadidaṃ sabbasaṅkhārasamatho 
sabbūpadhipaṭinissaggo taṇhākkhayo virāgo nirodho nibbānan ti._
____

6. The sutta then says: 'Established therein, he attains the destruction of 
perceptually obscuring states.
+
****
_So tattha ṭhito āsavānaṃ khayaṃ pāpuṇāti_
****

The destruction of perceptually obscuring states means the attainment of 
arahantship. Therefore arahantship occurs after having focused the mind on the 
immortal phenomenon, and even after the reflection 'this is _nibbāna_.' In 
this case, the immortal phenomenon and _nibbāna_ precede arahantship.

7. The sutta confirms this because it says that those who have the _etaṃ 
santaṃ_ reflection may not attain arahantship until the following life, 
because it says:

[quote, M.1.435]
____
'If the bhikkhu does not thereby attain the destruction of perceptually 
obscuring states, then he arises spontaneously [in the higher planes of 
existence], there to attain nibbāna-without-residue, never to return from 
those worlds.'

_no ce āsavānaṃ khayaṃ pāpuṇāti... opapātiko hoti tattha 
parinibbāyī anāvattidhammo tasmā lokā._
____

In other words, the immortal phenomenon that one focuses one's mind on is 
linked to either arahantship or non-returnership.

==== The immortal phenomenon means animittadhātu

That the immortal phenomenon means _animittadhātu_ (the unabiding phenomenon) 
can be demonstrated in seven steps:

1. The experience of focusing on the _amatadhātu_ is described in the _etaṃ 
santaṃ_ reflection, as noted above (M.1.435-7).

2. The _etaṃ santaṃ_ reflection is equivalent to the winning of inward 
collectedness such that though one does not contemplate the visual sense or 
visible object... yet one still contemplates.
+
****
_Idhānanda bhikkhu evaṃ manasikaroti etaṃ santaṃ... nibbānan ti evaṃ 
kho ānanda siyā bhikkhuno tathārūpo samādhipaṭilābho yathā na 
cakkhuṃ manasikareyya na rūpaṃ manasikareyya... yampidaṃ diṭṭhaṃ 
sutaṃ mutaṃ viññātaṃ pattaṃ pariyesitaṃ anuvicaritaṃ manasā 
tampi na manasikareyya manasi ca pana kareyyā ti_ (A.5.321).
****

3. These objects that one does not contemplate are called 'all _nimittāni'_ 
(_sabbanimittāni_) in this passage:

[quote, S.4.50]
____
He perceives all phenomena (_sabbanimittāni_) differently. He sees the visual 
sense differently, he sees visible objects differently... .

_sabbanimittāni aññato passati cakkhuṃ aññato passati rūpe aññato 
passati... mano aññato passati dhamme aññato passati manoviññāṇaṃ 
aññato passati manosamphassaṃ aññato passati yampidaṃ mano 
samphassapaccayā uppajjati sukhaṃ vā dukkhaṃ vā adukkhamasukhaṃ vā 
tampi aññato passati._
____

4. Thus focusing on the _amatadhātu_ is equivalent to not contemplating all 
_nimittāni_ (_sabbanimittāni na manasikareyya_) yet still contemplating 
(_manasi ca pana kareyyā ti_).

5. 'Still contemplating' implies contemplating what is _animitta._

6. Attaining the liberation [from perceptually obscuring states] by focusing 
upon the unabiding [phenomenon] (_animittāya cetovimuttiyā samāpattiyā_) 
involves two similar steps:

____
ignoring all _nimittāni_

_sabbanimittānañca amanasikāro_
____

[quote, M.1.297]
____
focusing upon the a__nimitta__ phenomenon

_animittāya ca dhātuyā manasikāro._
____

7. Therefore these phrases are equivalent:

[quote, M.1.435]
____
he focuses his mind on the _amatadhātu_

_amatāya dhātuyā cittaṃ upasaṃharati_
____

[quote, M.1.297]
____
focusing upon the _animittadhātu_

_animittāya ca dhātuyā manasikāro._
____

That focusing on _animittadhātu_ means perceiving the passing away and ending 
&#8203;[of originated phenomena] (_virāgasaññā_ and _nirodhasaññā_) is 
discussed sv _Nimitta_. Presumably the _amatadhātu_ is named as such (and even 
called _nibbāna_ in the _etaṃ santaṃ_ reflection) because of the immortal 
quality of these two perceptions.

=== Illustrations

.Illustration
====
amatāya dhātuyā

the immortal phenomenon
====

____
A bhikkhu enters and abides in first jhāna, which is accompanied by thinking 
and pondering, and rapture and physical pleasure born of seclusion [from 
sensuous pleasures and spiritually unwholesome factors].

_savitakkaṃ savicāraṃ vivekajaṃ pītisukhaṃ paṭhamaṃ jhānaṃ 
upasampajja viharati._
____

____
He regards whatever phenomena there that are connected with the five 
aggregates, as unlasting, as existentially void, as an illness, as a carbuncle, 
as a [piercing] arrow, as suffering, as an affliction, as alien, as destined to 
decay, as void [of personal qualities], as void of personal qualities.

_So yadeva tattha hoti rūpagataṃ vedanāgataṃ saññāgataṃ 
saṅkhāragataṃ viññāṇagataṃ te dhamme aniccato dukkhato rogato 
gaṇḍato sallato aghato ābādhato parato palokato suññato anattato 
samanupassati._
____

____
He averts his mind from those states.

_So tehi dhammehi cittaṃ paṭivāpeti_
____

____
and focuses his mind on the immortal phenomenon:

_so tehi dhammehi cittaṃ paṭivāpetvā amatāya dhātuyā cittaṃ 
upasaṃharati_
____

____
This is peaceful, this is sublime, namely: the quelling of all originated 
phenomena, the relinquishment of the whole phenomenon of attachment, the 
destruction of craving, the passing away [of originated phenomena], the ending 
&#8203;[of originated phenomena], the Untroubled.

_etaṃ santaṃ etaṃ paṇītaṃ yadidaṃ sabbasaṅkhārasamatho 
sabbūpadhipaṭinissaggo taṇhākkhayo virāgo nirodho nibbānan ti._
____

____
Established therein, he attains the destruction of perceptually obscuring 
states.

_So tattha ṭhito āsavānaṃ khayaṃ pāpuṇāti_
____

• If he does not attain the destruction of perceptually obscuring states, 
then because of that righteous attachment, righteous spiritually fettering 
delight, with the destruction of the five ties to individual existence in the 
low plane of existence, he arises spontaneously [in the higher planes of 
existence], there to attain nibbāna-without-residue, never to return from 
those worlds. +
☸ _no ce āsavānaṃ khayaṃ pāpuṇāti teneva dhammarāgena tāya 
dhammanandiyā pañcannaṃ orambhāgiyānaṃ saṃyojanānaṃ parikkhayā 
opapātiko hoti tattha parinibbāyī anāvattidhammo tasmā lokā. Ayampi kho 
ānanda maggo ayaṃ paṭipadā pañcannaṃ orambhāgiyānaṃ 
saṃyojanānaṃ pahānāya_ (M.1.435-7) (=A.4.421).

