== Anamatagga

=== Renderings

- _anamatagga_: long-lasting beyond conception

- _anamatagga_: endless beyond conception

=== Introduction

==== Anamatagga: uncertain derivation

_Anamatagga_ has long been a source of controversy. The difficulty of the word 
is acknowledged by PED when it says: 'The meaning can best be seen, not from 
the derivation (which is uncertain), but from the examples quoted__.'__

==== Translators' renderings

Translators render it in the following ways:

[quote, Norman, Thī.v.496]
____
'The journeying-on as being without beginning and end'

_saṃsāraṃ anamataggato._
____

[quote, Bodhi, S.5.441]
____
'This _saṃsāra_ is without discoverable beginning'

_anamataggoyaṃ bhikkhave saṃsāro._
____

Thus _anamatagga_ potentially means:

1. endless

2. beginningless

3. without discoverable beginning

We will now show the problem of these terms, and we will show why we follow 
PED's 'whose beginning and end are alike unthinkable,' and the commentary's (ad 
S.2.178) _aparicchinnapubbāparakoṭikoti attho_ ('first and last point cannot 
be determined').

==== Endlessness: the problem

1. The problem with calling the round of birth and death 'endless' is that 
arahants have ended it, and others will follow. The most one could say is 
'potentially endless' or 'perhaps endless for some.'

2. The second problem with calling the round of birth and death 'endless' is 
that the Buddha did not quite say that when he said:

[quote, S.3.149]
____
There comes a time when the great ocean dries up, evaporates, and exists no 
more, but not, I declare, an ending of suffering for beings roaming and 
wandering the round of birth and death, [obstructed by] uninsightfulness into 
reality, and [tethered to individual existence] by craving.

_Hoti kho so bhikkhave samayo yaṃ mahāsamuddo ussussati visussati na bhavani 
na tvevāhaṃ bhikkhave avijjānīvaraṇānaṃ sattānaṃ 
taṇhāsaṃyojanānaṃ sandhāvataṃ saṃsarataṃ dukkhassa antakiriyaṃ 
vadāmi._
____

To say that beings will continue to suffer as long as they wander the round of 
birth and death, is not to say that the round of birth and death is endless.

==== Beginningless: the problem

The problem with calling the round of birth and death 'beginningless' is that 
the Buddha again did not quite say that when he said 'a first point is not to 
be discerned' (_pubbā koṭi na paññāyati,_ S.2.181).

==== Without discoverable beginning: the problem

The problem with saying _anamataggoyaṃ_ means '_saṃsāra_ is without 
discoverable beginning' is that sometimes _anamataggoyaṃ_ is used in 
reference to the future. For example, the _Sattisata Sutta_ (S.5.441) says a 
man may be offered the opportunity to penetrate the four noble truths on the 
condition that he agrees to receive 300 spear wounds a day for a hundred years. 
Then the sutta says:

____
It would be fitting for a noble young man intent on [the development of his 
own] spiritual well-being to accept the offer. For what reason? Because the 
round of birth and death is _anamatagga_. A first point is not to be discerned 
of [a receiving of] blows by knives, swords, arrows, and axes.

_Atthavasikena bhikkhave kulaputtena alaṃ upagantuṃ. Taṃ kissa hetu? 
Anamataggoyaṃ bhikkhave saṃsāro pubbā koṭi na paññāyati 
sattippahārānaṃ asippahārānaṃ usuppahārānaṃ pharasuppahārānaṃ_
____

The logic for accepting the offer would be that _saṃsāra_ is 'without 
discoverable end,' not 'without discoverable beginning.'

==== Anamatagga: etymology

_Anamatagga_ is etymologically _ana_ (= a neg.) + _mata_ (fr. _man_) + _aggā_ 
(pl.) (PED), which have the following meanings:

- _mata_ is the past participle of _maññati_, meaning 'thought, understood, 
considered.' From this we call _anamata_ 'beyond conception.'

- _Agga_ means 'the very tip, the very end' (DOP sv _Agga1_).

- PED takes _agga_ as _aggā_ (plural) and translates the term 'whose beginning 
and end are alike unthinkable.' DOP says 'without beginning (or end).'

- That _agga_ can mean 'beginning' is seen in the term _aggena_ ('in the 
beginning, beginning from, from,' PED sv _Agga1_) and _aggañña_ ('recognized 
as primitive primeval').

[quote, Vin.2.95]
____
That _agga_ can mean 'end' is seen here: 'While bhikkhus are investigating that 
legal matter endless brawls arise.

_Tehi ce bhikkhave tasmiṃ adhikaraṇe vinicchiyamāne anaggāni ceva 
bhassāni jāyanti._
____

If _ana-aggā_ means 'without beginning or end,' it means 'long-lasting.' This 
is supported by quotes where the adjective is 'long': _Dīgho vo saṃsāro_ 
(Thī.v.474).

==== Anamatagga: endless beyond conception

Where the object is not the round of birth and death, we say 'endless beyond 
conception':

[quote, Thī.v.495]
____
For the fool, the round of birth and death is [truly] long-lasting, weeping 
again and again over the deaths of his fathers, the killings of his brothers, 
and the punishments of himself, which are endless beyond conception.

_Dīgho bālānaṃ saṃsāro punappunañca rodataṃ +
Anamatagge pitumaraṇe bhātuvadhe attano ca vadhe._
____

=== Illustrations

.Illustration
====
anamatagga

long-lasting beyond conception
====

• So long is the period of a universal cycle, bhikkhu. And of universal 
cycles of such length, we have wandered the round of birth and death for the 
periods of so many universal cycles, so many hundreds of universal cycles, so 
many thousands of universal cycles, so many hundreds of thousands of universal 
cycles. For what reason? +
_Evaṃ dīgho kho bhikkhu kappo. Evaṃ dīghānaṃ kho bhikkhu kappānaṃ 
neko kappo saṃsito nekaṃ kappasataṃ saṃsitaṃ nekaṃ kappasahassaṃ 
saṃsitaṃ nekaṃ kappasatasahassaṃ saṃsitaṃ. Taṃ kissa hetu?_

____
Because, bhikkhu, the round of birth and death is long-lasting beyond 
conception.

_Anamataggoyaṃ bhikkhu saṃsāro_
____

[quote, S.2.181-2]
____
A first point is not to be discerned of beings [obstructed by] uninsightfulness 
into reality, and [tethered to individual existence] by craving, roaming and 
wandering the round of birth and death.

_pubbā koṭi na paññāyati avijjānīvaraṇānaṃ sattānaṃ 
taṇhāsaṃyojanānaṃ sandhāvataṃ saṃsarataṃ._
____

.Illustration
====
anamatagga

long-lasting beyond conception
====

____
Suppose a man cut up whatever grass, sticks, branches, and foliage there are in 
this great subcontinent and collected them into a single heap of sticks four 
fingerbreadths long, and placed them down one by one, saying:

_Seyyathā pi bhikkhave puriso yaṃ imasmiṃ jambudīpe 
tīṇakaṭṭhasākhāpalāsaṃ taṃ chetvā ekajjhaṃ saṃhareyya 
ekajjhaṃ saṃharitvā caturaṅgulaṃ caturaṅgulaṃ ghaṭikaṃ 
karitvā nikkhipeyya_
____

____
'This is my mother, this my mother's mother.'

_ayaṃ me mātā tassā me mātu ayaṃ mātā ti_
____

____
The sequence of that man's mothers, and mothers of mothers, would not be 
exhausted, yet the grass, wood, branches, and foliage in this great 
subcontinent would be finished and exhausted. For what reason?

_Apariyādinnāva bhikkhave tassa purisassa mātu mātaro assu. Atha imasmiṃ 
jambudīpe tiṇakaṭṭhasākhāpalāsaṃ parikkhayaṃ pariyādānaṃ 
gaccheyya. Taṃ kissa hetu?_
____

[quote, S.2.178]
____
Because the round of birth and death is long-lasting beyond conception. A first 
point is not to be discerned of beings roaming and wandering the round of birth 
and death, [obstructed by] uninsightfulness into reality, and [tethered to 
individual existence] by craving.

_Anamataggoyaṃ bhikkhave saṃsāro pubbā koṭi na paññāyati 
avijjānīvaraṇānaṃ sattānaṃ taṇhāsaṃyojanānaṃ sandhāvataṃ 
saṃsarataṃ._
____

.Illustration
====
anamatagga

long-lasting beyond conception
====

[quote, S.5.441]
____
It would be fitting for a noble young man intent on [the development of his 
own] spiritual well-being to accept the offer. For what reason? Because the 
round of birth and death is long-lasting beyond conception. A first point is 
not to be discerned of [a receiving of] blows by knives, swords, arrows, and 
axes.

_Atthavasikena bhikkhave kulaputtena alaṃ upagantuṃ. Taṃ kissa hetu? 
Anamataggoyaṃ bhikkhave saṃsāro pubbā koṭi na paññāyati 
sattippahārānaṃ asippahārānaṃ usuppahārānaṃ pharasuppahārānaṃ._
____

