== Anaññaposin

=== Renderings

_• anaññaposin_: not supported by a patron

=== Introduction

==== Comprehending anaññaposin

_Anaññaposin_ occurs five times in the scriptures, and always in verse. It is 
associated with bhikkhus who walk on uninterrupted almsround (called 
_sapadānacārī_, M.1.30). This is an austere practice (_dhutaguṇa_, 
Vin.3.15) according to which a bhikkhu visits all houses on an almsroute, and 
therefore does not cultivate special supporters.

Comprehending _anaññaposin_ is confounded by the other meanings of _poseti_ 
and its derivatives. The PED, for example, suggests _anaññaposino_ means 'not 
nourished by another' (see under _posin_). Norman calls it 'not supporting 
others' (Sn.v.65). From this, we see the extent of the puzzle:

1. Question: Is _anaññaposino_ passive or active?

2. Question: Are bhikkhus on almsround not nourished by others?

3. Question: Do good bhikkhus not support others?

==== Objectives

In considering this issue, we will accomplish the following objectives:

1. We will review the meanings of _poseti_, and will show it means either to 
nourish or take care of.

2. We will confirm that bhikkhus are supported by others.

3. We will confirm that it is meritorious to take care of others by sharing 
one's almsfood with them.

4. We will show that _anaññaposin_ is a synonym of _attabhara_ 
('self-reliant'), and is therefore passive in meaning.

5. We will show that _anaññaposin_ is a synonym of _kule kule 
appaṭibaddhacitto_, which means 'not emotionally bound to any particular 
family.'

6. In conclusion, we will show that _anaññaposin_ means that a bhikkhu who 
collects food on uninterrupted house-to-house almsround is not supported by a 
patron, and has many admirable qualities. Even the devas envy such a bhikkhu.

==== Puṭṭha: nourished

_Puṭṭha_ is the past participle of _poseti_. Here it means 'to nourish':

[quote, Sn.v.831]
____
Like a hero nourished on royal food

_Sūro yathā rājakhādāya puṭṭho._
____

==== Posakā: feeding

_Posakā_ means 'feeding':

[quote, A.1.62]
____
Parents are of great help to their children, in nursing them, feeding them, and 
showing them the world.

_bahukārā bhikkhave mātāpitaro puttānaṃ āpādakā posakā imassa 
lokassa dassetāro._
____

==== Posa: support

_Posa_ is the absolutive of _poseti._ In the following passage it means 'to 
support,' where 'difficult to support' could mean either financially difficult 
to support, or emotionally difficult to support:

____
Formerly, the bhikkhus lived happily, the disciples of Gotama. They sought 
their almsfood without desire. They used their abodes without desire. Knowing 
the world's unlastingness [according to reality], they put an end to suffering.

_Sukhajivino pure āsuṃ bhikkhū gotamasāvakā +
Anicchā piṇḍamesanā anicchā sayanāsanaṃ +
Loke aniccataṃ ñatvā dukkhassantaṃ akaṃsu te._
____

[quote, S.1.61]
____
... But now, like headmen in a village, they make themselves difficult to 
support. They eat and eat, and then lie down, infatuated with other people's 
homes.

_Dupposaṃ katvā attānaṃ gāme gāmaṇikā viya +
Bhūtvā bhutvā nipajjanti parāgāresu mucchitā._
____

==== Poseti: to take care of

_Poseti_ means 'to take care of':

____
Then the brahman who took care of his mother said to the Blessed One

_mātuposako brāhmaṇo bhagavantaṃ etadavoca._
____

____
-- Master Gotama, I seek almsfood righteously and thereby take care of my 
parents. In doing so, am I doing my duty?_

_Ahaṃ hi bho gotama dhammena bhikkhaṃ pariyesāmi. Dhammena bhikkhaṃ 
pariyesitvā mātāpitaro posemi. Kaccāhaṃ bho gotama evaṃkārī 
kiccakārī homī ti?_
____

[quote, S.1.181-2]
____
-- Certainly, brahman, in doing so you are doing your duty. One who seeks 
almsfood righteously and thereby takes care of his parents begets much merit.

_Taggha tvaṃ brāhmaṇa evaṃkārī kiccakārī hosi. Yo kho brāhmaṇa 
dhammena bhikkhaṃ pariyesati. Dhammena bhikkhaṃ pariyesitvā mātāpitaro 
poseti. Bahuṃ so puññaṃ pasavatī ti._
____

==== Poseti: to take care of

Jīvaka, as a newborn baby, was discovered on a rubbish heap by Prince Abhaya, 
who told his men:

____
-- Well, sirs, take that boy to our women's quarters and give him to nurses to 
be taken care of (_posetuṃ_).

_Tena hi bhaṇe taṃ dārakaṃ amhākaṃ antepuraṃ netvā dhātīnaṃ 
detha posetun ti_
____

____
... The men took the boy to Prince Abhaya's women's quarters and gave him to 
nurses saying, 'Take care of him' (_posethā_)_

_taṃ dārakaṃ abhayassa rājakumārassa antepuraṃ netvā dhātīnaṃ 
adaṃsu posethā ti._
____

____
... Because it was said of him 'He's alive,' they named him Jīvaka._

_Tassa jīvatī ti jīvako ti nāmaṃ akaṃsu_
____

____
... Because the Prince had him taken care of (_posāpito_), they called him 
Komārabhacca._

_Kumārena posāpito ti komārabhacco ti nāmaṃ akaṃsu_
____

In due course, Jīvaka Komārabhacca approached Prince Abhaya, and asked:

____
-- Who, sire, is my mother? Who is my father?

_kā me deva mātā? Ko pitā ti_
____

[quote, Vin.1.269]
____
-- Not even I, good Jīvaka, know your mother, but I am your father, for I had 
you taken care of (_posāpito_)._

_Ahampi kho te bhaṇe jīvaka mātaraṃ na jānāmi. Apicāhaṃ te pitā. 
Mayāsi posāpito ti._
____

COMMENT

_Apicāhaṃ te pitā. Mayāsi posāpito ti_. Word play.

==== Synonym: attabharassa

_Anaññaposino_ is a synonym of _attabharassa_ ('self-reliant'), so it is 
passive not active:

[quote, Ud.30]
____
The devas envy the bhikkhu who collects his food on almsround, who is 
self-reliant, not supported by a patron, inwardly at peace, and continuously 
mindful.

_Piṇḍapātikassa bhikkhuno attabharassa anaññaposino. +
Devā pihayanti tādino upasantassa sadā satimato ti._
____

Context: Venerable MahāKassapa walking on uninterrupted house-to-house 
almsround in Rājagaha.

==== Not supported by a patron: not emotionally bound to any particular family

The following verse from the _Khagaggavisāṇa Sutta_ repeatedly shows that a 
bhikkhu who is _anaññaposī_ has no patron. Of particular interest is the 
link to _kule kule appaṭibaddhacitto._ The verse could be cynically 
interpreted as saying that patrons are for greedy, self-indulgent bhikkhus who 
do not walk on uninterrupted house-to-house almsround, and who are emotionally 
attached to particular supporters:

[quote, Sn.v.65]
____
Having no greed for flavours, not self-indulgent, not supported by a patron, 
walking on uninterrupted house-to-house almsround, not emotionally bound to any 
particular family, one should live the religious life as solitarily as a 
rhinoceros horn.

_Rasesu gedhaṃ akaraṃ alolo anaññaposī sapadānacārī +
Kule kule appaṭibaddhacitto eko care khaggavisāṇakappo._
____

==== Conclusion

1. We have reviewed the possible meanings of _poseti_, and shown it means 
either to nourish or to take care of.

2. We have confirmed that bhikkhus are supported by others.

3. We have confirmed that it is meritorious to take care of others by sharing 
one's almsfood with them.

4. We have showed that _anaññaposin_ is a synonym of _attabhara_ 
('self-reliant'), and is therefore passive in meaning.

5. We have shown that _anaññaposin_ is a synonym of _kule kule 
appaṭibaddhacitto_, which means 'not emotionally bound to any particular 
family.'

6. In conclusion, we have shown that _anaññaposin_ means that bhikkhu who 
collects food on uninterrupted house-to-house almsround is not supported by a 
patron, and has many admirable qualities. Even the devas envy such a bhikkhu.

=== Illustrations

.Illustration
====
not supported by a patron

[quote

S.1.141]
====

____
This bhikkhu Brahmadeva, madam, free of attachment has surpassed the devas. 
Liberated from the perception of existence, not supported by a patron, this 
very bhikkhu has entered your house for alms.

_Eso hi te brāhmaṇī brahmadevo nirupadhiko atidevappatto +
Akiñcano bhikkhu anaññaposī yo te so piṇḍāya gharaṃ paviṭṭho._
____

Context: Venerable Brahmadeva walking on uninterrupted almsround in Sāvatthī.

.Illustration
====
not supported by a patron

[quote

Ud.4]
====

____
One who is not supported by a patron, not well-known, inwardly tamed, 
established in excellent qualities, whose _āsavas_ are destroyed, and who is 
free of spiritual flaws, he is what I call a Brahman.

_Anaññaposiṃ aññātaṃ dantaṃ sāre patiṭṭhitaṃ +
Khīṇāsavaṃ vantadosaṃ tamahaṃ brūmi brāhmaṇan ti._
____

Context: Venerable MahāKassapa ('not well-known'!) walking on almsround in the 
poor district of Rājagaha.

.Illustration
====
not supported by a patron

[quote

Ud.31]
====

____
The devas envy the bhikkhu who collects his food on almsround, who is 
self-reliant, not supported by a patron, but not if it is based on desire for 
praise and fame.

_Piṇḍapātikassa bhikkhuno attabharassa anaññaposino +
Devā pihayanti tādino no ce saddasilokanissito ti._
____

Context: Bhikkhus walking on almsround for selfish reasons.

