== Anaṇa

=== Renderings

- _anaṇa_: free of karmic debt

- _anaṇa_: debtlessness

=== Introduction

==== Etymology: aṇa and iṇa

_Aṇa_ occurs only as _anaṇa_. Its synonym is _iṇa_. _Sāṇo_ is 
__sa+iṇo__='not free of karmic debt.'

==== Karmic debt

Karmic debt is defined in this quote:

[quote, A.3.352]
____
He misconducts himself by way of body, speech, and mind. This, I declare, is 
getting into karmic debt.

_kāyena duccaritaṃ carati vācāya duccaritaṃ carati manasā duccaritaṃ 
carati. Idamassa iṇādānasmiṃ vadāmi._
____

==== Freedom from karmic debt

'Free of karmic debt' is illustrated in Aṅgulimāla's verse.

[quote, M.2.105]
____
While I undertook much karmically consequential conduct that leads to [rebirth 
in] the plane of misery, yet its karmic consequence has reached me now. I enjoy 
my food free of karmic debt.

_Tādisaṃ kammaṃ katvāna bahuṃ duggatigāminaṃ; +
Phuṭṭho kammavipākena anaṇo bhuñjāmi bhojanaṃ._
____

==== Debtlessness

The meaning 'debtlessness' is seen in this passage:

• And what is the pleasure of debtlessness? +
_Katamañca gahapati anaṇasukhaṃ?_

• ... In this regard a noble young man owes no debt great or small to anyone. 
At the thought: I owe no debt, great or small, to anyone, physical and 
psychological pleasure come to him. This, householder, is called the pleasure 
of debtlessness. +
_Idha gahapati kulaputto na kassaci kiñci dhāreti appaṃ vā bahuṃ vā. So 
na kassaci kiñci dhāremi appaṃ vā bahuṃ vā ti adhigacchati sukhaṃ 
adhigacchati somanassaṃ. Idaṃ vuccati gahapati anaṇasukhaṃ_ (A.2.69).

=== Illustrations

.Illustration
====
anaṇā

not in karmic debt
====

[quote, Th.v.138]
____
We have brought about your death, sensuous yearning. Now we are no longer in 
karmic debt on account of you.

_Vadhaṃ carimha te kāma anaṇā dāni te mayaṃ._
____

COMMENTS

1. We take _te_ as instrumental case.

2. Karmic debt on account of sensuous yearning can be explained like this:

____
What is the consequence of sensuous yearnings?

_Katamo ca bhikkhave kāmānaṃ vipāko_
____

[quote, A.3.411]
____
... In one yearning for sensuous pleasure a corresponding personal disposition 
is manifested, either meritorious or demeritorious.

_yaṃ kho bhikkhave kāmayamāno tajjaṃ tajjaṃ attabhāvaṃ 
abhinibbatteti puññabhāgiyaṃ vā apuññabhāgiyaṃ vā ayaṃ vuccati 
bhikkhave kāmānaṃ vipāko._
____

.Illustration
====
sāṇo

not free of karmic debt
====

[quote, S.2.221]
____
For seven days I ate the country's almsfood whilst not free of karmic debt. But 
on the eighth day [complete] knowledge [of things according to reality] arose 
in me.

_sattāhameva kho ahaṃ āvuso sāṇo raṭṭhapiṇḍaṃ bhuñjiṃ. Atha 
aṭṭhamiyā aññā udapādi._
____

COMMENT

'[Complete] knowledge [of things according to reality]': arahantship is 
associated with _sammadaññā_, e.g. _sammadaññā vimutto_ (M.1.235), 
_sammadaññāya paṇḍitā_ (Sn.v.733).

COMMENT

_Sāṇo_ is _sa+iṇo._

