== Antagū

=== Renderings

- _antagū_: one who has reached the end of

=== Introduction

==== Antagū: reached the end of

_Antagū_ means 'one who has reached the end (of something),' and is therefore 
usually qualified. For example: 'the end of the spiritual path' 
(_paṭipadantaguṃ_) or 'the end of suffering' (_dukkhantagunā_), and so on.

==== Lokantagū__:__ reached the end of the world [of phenomena]

_Lokantagū_ means 'one who has reached the end of the world.' _Loka_ is dealt 
with in detail elsewhere in the Glossary, but in conclusion we take 'world' as 
'world [of phenomena].'

==== Vedantagū: completed his scriptural education

_Vedantagū_ means 'reached the end of scriptural knowledge,' but reads better 
as 'completed one's scriptural education,' as here:

[quote, Sn.v.463]
____
One who has submitted to inward taming, completed his scriptural education, 
fulfilled the religious life.

_damasā upeto vedantagū vusitabrahmacariyo._
____

=== Illustrations

.Illustration
====
antagū

reached the end of suffering
====

[quote, Sn.v.539]
____
You have reached the end of suffering, gone beyond suffering.

_antagūsi pāragū dukkhassa._
____

.Illustration
====
paṭipadantaguṃ

reached the end of the spiritual path
====

[quote, A.1.236]
____
They call him enlightened in the world, a wise person who has reached the end 
of the spiritual path.

_Tamāhu loke sambuddhaṃ dhīraṃ paṭipadantaguṃ._
____

.Illustration
====
lokantagū

one who has reached the end of the world [of phenomena]
====

____
The end of the world [of phenomena] can never be reached by means of 
travelling. Yet without reaching the end of the world [of phenomena] there is 
no freedom from suffering.

_Gamanena na pattabbo lokassanto kudācanaṃ +
Na ca appatvā lokantaṃ dukkhā atthi pamocanaṃ._
____

[quote, S.1.62]
____
Therefore, truly, one who knows the world [of phenomena] [according to 
reality], one of great wisdom, one who has reached the end of the world [of 
phenomena], fulfiller of the religious life, knowing the end of the world [of 
phenomena] [according to reality], inwardly at peace, longs not for this world 
or another.

_Tasmā have lokavidū sumedho lokantagū vusitabrahmacariyo +
Lokassa antaṃ samitāvī ñatvā nāsiṃsati lokamimaṃ parañcā ti._
____

.Illustration
====
lokantagū

one who has reached the end of the world [of phenomena]
====

[quote, Sn.v.1133]
____
The Enlightened One, dispeller of inward darkness, All-Seeing Eye, one who has 
reached the end of the world [of phenomena], transcended all states of 
individual existence

_tamonudo buddho samantacakkhu lokantagū sabbabhavātivatto._
____

.Illustration
====
dukkhantagunā

reached the end of suffering
====

[quote, A.1.215]
____
... proclaimed by the Buddha who has reached the end of suffering.

_Buddhena dukkhantagunā pakāsitaṃ._
____

.Illustration
====
antagū

'one who has completed his scriptural education
====

[quote, Sn.v.458]
____
'If one who has completed [his scriptural education], who is blessed with 
profound knowledge, should receive an offering at the time of alms bestowal, 
then, I declare, the offering would have a good result.

_Yadantagū vedagū yaññakāle yassāhutiṃ labhe tassijjheti brūmi._
____

Comment:

_Antagū_: 'one who has completed [his scriptural education].' Although 
_antagū_ is unqualified here, it is clarified as _vedantagū_ in Sn.v.463.

