== Anumodati; Abbhanumodati

=== Renderings

- _abbhanumodāti_: to approve of

- _abbhanumodāti_: to applaud

- _anumodati_: to offer the words of appreciation

- _anumodati_: to acclaim

- _anumodati_: to applaud

- _anumodati_: to encourage

- _anumodati_: to thank

- _anumodana_: the words of appreciation

- _anumodamāno_: appreciative

=== Illustrations

.Illustration
====
abbhanumodāmi

applaud; approve of
====

When the Buddha described a sacrifice in which no animals were killed, the 
brahmans asked Kūṭadanta why he did not applaud the ascetic Gotama's fine 
words (_samaṇassa gotamassa subhāsitaṃ subhāsitato nābbhanumodatī ti_). 
He replied:

____
'My dear sirs, I do not disapprove of the ascetic Gotama's fine words. One's 
head would split open if one did.'

_Nāhaṃ bho samaṇassa gotamassa subhāsitaṃ subhāsitato 
nābbhanumodāmi. Muddhāpi tassa vipateyya yo samaṇassa gotamassa 
subhāsitaṃ subhāsitato nābbhanumodeyya_
____

He said his silence was because the Buddha had described the sacrifice as if he 
himself had performed it in a previous life, which the Buddha confirmed 
(D.1.143).

.Illustration
====
abbhanumodati

approve of
====

[quote, M.1.146]
____
Venerable Sāriputta thought how wonderful for Puṇṇa Mantāṇiputta that 
his knowledgeable companions in the religious life praised him point by point 
in the Teacher's presence, and that the Teacher approves of it.

_lābhā āyasmato puṇṇassa mantāṇiputtassa yassa viññū 
sabrahmacārī satthu sammukhā anumāssa anumāssa vaṇṇaṃ bhāsanti 
tañca satthā abbhanumodati._
____

.Illustration
====
abbhanumodati

applaud
====

King Pasenadi mocked Queen Mallikā for always applauding the Buddha, saying:

[quote, M.2.107]
____
Just as a teacher, whatever he says to his pupil, the pupil applauds it: 'So it 
is, teacher! So it is!'

_Seyyathā pi nāma ācariyo yaññadeva antevāsissa bhāsati taṃ tadevassa 
antevāsī abbhanumodati evametaṃ ācariyā evametaṃ ācariyāti._
____

.Illustration
====
abbhanumodati

applaud
====

[quote, D.1.189]
____
Ascetics mocked Poṭṭhapāda: 'Whatever ascetic Gotama says, Poṭṭhapāda 
applauds it: "So it is, Blessed One. So it is, Sublime One."'

_yaññadeva samaṇo gotamo bhāsati taṃ tadevassa abbhanumodati. Evametaṃ 
bhagavā evametaṃ sugatā ti._
____

.Illustration
====
anumodeyyaṃ

offer the words of appreciation
====

[quote, M.1.28]
____
A bhikkhu may wish "Oh, that I may offer the words of appreciation in the 
refectory after the meal, not some other bhikkhu."

_aho vata ahameva bhattagge bhuttāvī anumodeyyaṃ. Na añño bhikkhu 
bhattagge bhuttāvī anumodeyyā ti._
____

.Illustration
====
anumodanassa

offering the words of appreciation; anumodati, to offer the words of 
appreciation
====

____
After eating the meal, the Buddha would sit in silence for a while, but not let 
the time go by for offering the words of appreciation.

_na ca anumodanassa kālamatināmeti._
____

[quote, M.2.139]
____
Having eaten, he offers the words of appreciation.

_So bhuttāvī anumodati._
____

.Illustration
====
anumoditabbaṃ

acclaim
====

____
If bhikkhu makes a declaration of arahantship, his words should be neither 
applauded nor criticised;

_bhāsitaṃ neva abhinanditabbaṃ nappaṭikkositabbaṃ_
____

[quote, M.3.30]
____
But he should be interrogated. If he answers correctly, expressing one's 
approval, one may applaud and acclaim the bhikkhu's words.

_sādhū ti bhāsitaṃ abhinanditabbaṃ anumoditabbaṃ._
____

.Illustration
====
anumodati

applaud
====

When Venerable Udāyī three times contradicted Venerable Sāriputta, 
Sāriputta thought:

[quote, A.3.194]
____
Venerable Udāyī contradicts me for up to the third time, and not a single 
bhikkhu applauds me.

_yāva tatiyampi kho me āyasmā udāyī paṭikkosati na ca me koci bhikkhu 
anumodati._
____

.Illustration
====
anumodamāno

appreciative
====

[quote, Sn.v.405]
____
And then having kept the observance, the wise man with a mind filled with 
faith, being appreciative, should in the morning share out food and drink to 
the community of bhikkhus, as is fitting.

_Tato ca pāto upavutthuposatho annena pānena ca bhikkhusaṅghaṃ +
Pasannacitto anumodamāno yathārahaṃ saṃvibhajetha viññū._
____

.Illustration
====
anumodamāno

applaud
====

____
Fools do indeed not praise generosity

_bālā have nappasaṃsanti dānaṃ_
____

[quote, Dh.v.177]
____
The wise applaud it

_Dhīro ca dānaṃ anumodamāno._
____

.Illustration
====
anumodanti

encourage
====

____
When a deva is due to pass away, other devas encourage him with three words of 
advice:

_tīhi vācāhi anumodanti_
____

[quote, It.76]
____
'Go, sir, to a good realm. Having done so, gain what is inwardly good. Having 
done so, become firmly established in it.'

_ito bho sugatiṃ gaccha. Sugatiṃ gantvā suladdhalābhaṃ labha. 
Suladdhalābhaṃ labhitvā suppatiṭṭhito bhavāhī ti._
____

.Illustration
====
anumodi

thank
====

____
Keṇiya, the matted-hair ascetic, served and satisfied the community of 
bhikkhus headed by the Buddha with various kinds of good food. Then the Blessed 
One thanked him with these verses.

_keṇiyaṃ jaṭilaṃ bhagavā imāhi gāthāhi anumodi._
____

Comment:

We say the Buddha 'thanked' Keṇiya. What he said was:

____
Fire veneration is the chief aspect of sacrifices. Sāvittī is the chief of 
Vedic hymns. A king is the chief of human beings. The sea is the chief of 
waters.

_Aggihuttamukhā yaññā sāvittī chandaso mukhaṃ +
Rājā mukhaṃ manussānaṃ nadinaṃ sāgaro mukhaṃ._
____

____
... The moon is the chief light amongst the constellations. The sun is the 
chief of luminary bodies. For those who make offerings, seeking merit, the 
community of bhikkhus, is the chief [recipient].

_Nakkhattānaṃ mukhaṃ cando ādicco tapataṃ mukhaṃ +
Puññaṃ ākaṅkhamānānaṃ saṅgho ve yajataṃ mukhan ti_
____

[quote, M.2.146; Sn.v.571-2; Vin.1.246]
____
When the Blessed One had thanked Keṇiya, the matted-hair ascetic, with these 
verses he rose from his seat and departed.

_Atha kho bhagavā keṇiyaṃ jaṭilaṃ imāhi gāthāhi anumoditvā 
uṭṭhāyāsanā pakkāmi._
____

Other translators say (_keṇiyaṃ jaṭilaṃ bhagavā imāhi gāthāhi 
anumodi_):

- Horner: the Lord thanked him in these verses

- Bodhi: the Blessed One gave him his blessing with these stanzas.

- Norman: the Blessed One gave thanks to the matted-hair ascetic

.Illustration
====
anumodanīyena anumodi

thank with words of appreciation
====

____
Then the Blessed One thanked the householder Ugga with these words of 
appreciation

_uggaṃ gahapatiṃ vesālikaṃ iminā anumodanīyena anumodi:_
____

- 'One who gives what is agreeable will gain what is agreeable. He who 
preferentially gives clothes, bed, food, drink and various requisites to those 
who are spiritually purified, knowing the arahants to be like a field for what 
is relinquished, offered, not held back, a spiritually outstanding person gives 
what is hard to give. One who gives what is agreeable will gain what is 
agreeable.'

[quote, A.3.50]
____
... When the Blessed One had thanked the householder Ugga with these words of 
appreciation he rose from his seat and departed.

_uggaṃ gahapatiṃ vesālikaṃ iminā anumodanīyena anumoditvā 
uṭṭhāyāsanā pakkāmi._
____

