== Anuneti

=== Renderings

- _anunīta_: motivated

- _anunīta_: attracted

- _anunaya_: attraction

- _anuneti_: to conciliate

- _anunetā_: diplomat

- _anunayasaṃyojanaṃ_: attraction [to sensuous pleasure], as a tie to 
individual existence

=== Introduction

==== Anunaya: 'leading along'

_Anunaya_ means 'leading along.'

==== Anunetar: 'diplomat'

_Anuneta(r)_ is 'one who leads or persuades or conciliates,' says DOP, so we 
call it 'diplomat.'

==== Anunayasaṃyojanaṃ: attraction [to sensuous pleasure]

The second of the seven ties to individual existence (_sattannaṃ 
saṃyojanānaṃ_ A.4.7-9) is repugnance, _paṭighasaṃyojanaṃ_. In 
opposition to repugnance is the first of the seven ties, 
_anunayasaṃyojanaṃ_ and we call this 'attraction.' This is in accordance 
with the root idea 'leading along,' and it harmonises with 'inclination 
towards,' a term suggested by DOP. But by 'attraction' we mean 'attraction [to 
sensuous pleasure],' which we explain in three steps:

1. The seven ties to individual existence (_satta saṃyojanāni_) are: 
_anunayasaṃyojanaṃ paṭighasaṃyojanaṃ diṭṭhisaṃyojanaṃ_ etc.

2. The seven unwholesome proclivities (_sattannaṃ anusayānaṃ_) are: 
_kāmarāgānusayo paṭighānusayo diṭṭhānusayo_ etc.

3. In these lists _anunayasaṃyojanaṃ_ corresponds to _kāmarāgānusaya,_ 
the proclivity to attachment to sensuous pleasure. Hence we render 
_anunayasaṃyojanaṃ_ as 'attraction [to sensuous pleasure]' not just 
'attraction.'

==== Anuneti: to conciliate

That _anuneti_ means 'to conciliate' is clear in two illustrations below.

==== Anunīta

PED calls _anunīta_ (pp of _anuneti_) 'led, induced.' We prefer 'motivated' or 
'attracted.'

=== Illustrations

.Illustration
====
anunīto

attracted
====

In smelling a fragrant, delightful smellable object, and in smelling a 
disgusting stench:

____
Dispel repugnance for the stench

_Akantiyasmiṃ paṭighaṃ vinodaye_
____

[quote, S.4.70]
____
And do not, by desire, be attracted to the pleasing.

_Chandānunīto na ca kantiye siyā._
____

.Illustration
====
anunīto

motivated
====

____
How indeed could someone motivated by desire

_chandānunīto_
____

____
Established in [the pursuit of] personal inclination

_ruciyā niviṭṭho_
____

[quote, Sn.v.781]
____
Transcend his own dogmatism?

_sakaṃ hi diṭṭhiṃ kathamaccayeyya._
____

.Illustration
====
anunayo

attraction
====

[quote, M.1.191]
____
The fondness, clinging, attraction, and cleaving within these five grasped 
aggregates is the origination of _dukkha_.

_Yo imesu pañcasupādānakkhandhesu chando ālayo anunayo ajjhosānaṃ so 
dukkhasamudayo._
____

.Illustration
====
anunentī

conciliating
====

Sumedhā conciliated Anikaratta about her decision to become a bhikkhunī 
instead of marrying him, by telling him 'This deathlessness has been attained 
by many, and it is to be obtained even today by one who properly applies 
himself, but it cannot be attained by one who does not properly strive.' The 
next verse says:

[quote, Thī.v.514]
____
Finding no delight in originated phenomenon, Sumedhā spoke thus. And, on 
conciliating Anikaratta, Sumedhā threw her hair onto the floor.

_Evaṃ bhaṇati sumedhā saṅkhāragate ratiṃ alabhamānā +
Anunentī anikarattaṃ kese ca chamaṃ khipi sumedhā._
____

Comment:

The conciliation is proven in the next verse, where Anikaratta begs Sumedhā's 
father:

[quote, Th.v.515]
____
'Let Sumedhā leave to go forth [into the ascetic life].'

_Vissajjetha sumedhaṃ pabbajituṃ._
____

.Illustration
====
anunayamāno

having conciliated
====

When a pauper was reborn amidst the Tāvatiṃsā devas, who then complained 
about his attaining outstanding glory. Sakka, Lord of the Devas, explained that 
when this deva was a human being, he properly trained himself in the Buddha's 
training system.

[quote, S.1.232]
____
Then Sakka, Lord of the Devas, on conciliating the Tāvatiṃsā devas, on that 
occasion recited these verses etc.

_Atha kho bhikkhave sakko devānamindo deve tāvatiṃse anunayamāno tāyaṃ 
velāyaṃ imā gāthāyo abhāsi._
____

.Illustration
====
anunetā

diplomat
====

[quote, D.3.192]
____
Kind and friendly, approachable, free of stinginess, a guide, teacher, and 
diplomat, such a person attains prestige.

_Saṅgāhako mittakaro vadaññū vītamaccharo +
Netā vinetā anunetā tādiso labhate yasaṃ._
____

