== Anusaya

=== Renderings

- _anusaya_: proclivity (to something)

- _anusaya_: unwholesome proclivity

- _anusaya_: identification

- _anuseti_: to lurk within

- _anuseti_: to identify with

- _anuseti_: to linger

=== Introduction

==== Anusaya: 'proclivity'

_Anusaya_ means tendency, but 'always in a bad sense,' says PED. The 
_Madhupiṇḍika Sutta_ appropriately calls the _anusayas_ 'unvirtuous, 
spiritually unwholesome factors' (_pāpakā akusalā dhammā_ M.1.109). 
Accordingly, we call _anusayas_ 'proclivities' which means 'a strong natural 
proneness, usually to something objectionable or evil' (Webster's).

==== Anuseti: 'lurk within' and 'linger'

_Anuseti_ means 'to lie down with.' Illustrations below show it can be called 
'to lurk within' or 'to linger.' Relevant quotes are presented below.

==== Anuseti: 'identify with.'

In some circumstances _anuseti_ means 'to identify with.' This needs a 
substantial explanation because it is unnoted by translators and lexicographers 
alike.

==== 'To identify with': explanation

To show that _anuseti_ means 'to identify with,' we will use an argument that 
includes the concept of 'being measured,' as follows:

1. Firstly, when we say 'to identify with' we mean 'to see things as "[in 
reality] mine," or "[in reality] what I am," "my [absolute] Selfhood."'
+
****
_etaṃ mama eso'hamasmi eso me attā ti_.
****

2. Secondly, when the _Dutiya Bhikkhu Sutta_ says 'one is measured because of 
_anuseti'_ (_yaṃ kho bhikkhu anuseti taṃ anumīyati_, S.3.36-7) we take 
'measured' to mean 'measured against others via the three modes of 
self-centredness.' These are the _tisso vidhā_, namely: 'I am better,' 'I am 
equal,' 'I am worse' (S.5.56).

3. That 'being measured' comes from 'identifying with' is shown in the 
_Surādha Sutta_, which says that transcending the modes [of self-centredness] 
(_vidhā samatikkantaṃ_) is attained by not identifying with the five 
aggregates, as follows:

____
One perceives all bodily form... advertence according to reality with perfect 
penetrative discernment as "not [in reality] mine," "not [in reality] what I 
am," "not my [absolute] Selfhood"'

_sabbaṃ rūpaṃ... sabbaṃ viññāṇaṃ n'etaṃ mama n'eso'hamasmi na 
me so attā ti._
____

[quote, S.3.80-1]
____
... Thus knowing, thus seeing, in regard to this [wretched human] body together 
with its advertence and all external phenomena, the mind is rid of the 
illusions of personal identity and personal ownership and self-centredness, it 
has transcended the modes [of self-centredness], and is peaceful and liberated 
&#8203;[from perceptually obscuring states].

_Evaṃ kho surādha jānato evaṃ passato imasmiñca saviññāṇake kāye 
bahiddhā ca sabbanimittesu ahaṅkāramamaṅkāramānāpagataṃ mānasaṃ 
hoti vidhā samatikkantaṃ santaṃ suvimuttanti._
____

4. We have seen that the _Surādha Sutta_ says 'being measured' comes from 
'identifying with,' and the _Dutiya Bhikkhu Sutta_ says being measured 
(_anumīyati_) comes from _anuseti._ Therefore _anuseti_ means 'to identify 
with.'

6. Accordingly, the _Dutiya Bhikkhu Sutta_ can be translated as follows:

[quote, S.3.36-7]
____
'What one identifies with, by that one is measured.'

_yaṃ kho bhikkhu anuseti taṃ anumīyati._
____

This makes perfect sense, and validates our argument.

==== Advantage: rational

Rendering _anuseti_ as 'to identify with' has two advantages. Firstly, 
translations are rational, as for example here:

[quote, S.3.35]
____
Whatever one identifies with, one is reckoned in terms of.

_yaṃ kho bhikkhu anuseti tena saṅkhaṃ gacchati._
____

==== Advantage: congruous

The second advantage of translating _anuseti_ as 'to identify with' is that it 
avoids the incongrous idea of 'having a tendency to the five aggregates.' For 
example Bodhi says:

[quote, translation of S.3.36]
____
If, venerable sir, one has an underlying tendency towards form, then one is 
measured in accordance with it

_Rūpaṃ ce bhante anuseti taṃ anumīyati._
____

This is incongruous, for the following reasons:

1. 'Tendency' goes with verbs and mental states, but not other nouns. For 
example, a tendency to argue, to doubt, to anger etc.

2. Webster's dictionary accordingly says tendency means 'a proneness to a 
particular kind of thought or action.'

3. The seven _anusaya's_ themselves follow this principle, with a list that 
includes the proclivity to repugnance, to self-centredness etc. But no 
'tendency to the five aggregates.'

Therefore when _anuseti_ is applied to nouns that are not mental states, we use 
the verb 'to identify with,' and our comparable rendering for S.3.36 is:

[quote, S.3.36]
____
If, bhante, one identifies with bodily form, by that one is measured.

_Rūpaṃ ce bhante anuseti taṃ anumīyati._
____

==== Anusaya: same principle

The same principle holds for the noun _anusaya_. Rendering it 'proclivity' 
makes good sense when it is linked to verbs and mental states. But when linked 
to other types of nouns, we call it 'identification.' This avoids the obvious 
problems of Bodhi's translations, where _anuseti_ is always 'underlying 
tendency.' Let us compare translations of two quotes:

Quote 1)

• Bodhi says: +
• the underlying tendency to lust lies within one. +
☸ _Tassa rāgānusayo anuseti_ (Bodhi, M.3.285).

This translation is satisfactory because lust is a mental state. Our 
translation of the quote is comparable:

• The proclivity to attachment lurks within him. +
_Tassa rāgānusayo anuseti_ (M.3.285).

Quote 2)

Bodhi says:

[quote, Bodhi, S.3.10]
____
The desire, lust, delight, and craving, the engagement and clinging, the mental 
standpoints, adherences, and underlying tendencies regarding the form element: 
these have been abandoned by the Tathāgata.

_rūpadhātuyā kho gahapati yo chando yo rāgo yā nandi yā taṇhā ye 
upayupādānā cetaso adhiṭṭhānābhinivesānusayā te tathāgatassa 
pahīnā._
____

This quote involves a noun that is not a mental state ('underlying tendencies 
regarding the form element'). We translate the passage with 'identification' 
('identification in regards to bodily form') as follows:

[quote, S.3.10]
____
The fondness, attachment, spiritually fettering delight, craving, clinging, 
grasping, obstinate adherence, stubborn attachment, and identification in 
regards to bodily form have been abandoned by the Perfect One

_rūpadhātuyā kho gahapati yo chando yo rāgo yā nandi yā taṇhā ye 
upayupādānā cetaso adhiṭṭhānābhinivesānusayā te tathāgatassa 
pahīnā._
____

==== Conclusion

In conclusion, where they involve nouns that are not mental states, _anusaya_ 
and _anuseti_ mean 'identification' and 'to identify with.'

=== Illustrations

.Illustration
====
anusaya

proclivity
====

[quote, S.1.188]
____
Discard the proclivity to self-centredness

_mānānusayamujjaha._
____

.Illustration
====
anusaya

proclivity
====

[quote, S.2.275]
____
The illusion of personal identity, the illusion of personal ownership, and the 
proclivity to self-centredness

_ahaṅkāramamaṅkāramānānusayā._
____

.Illustration
====
anusaya

proclivity
====

____
The proclivity to attachment should be abandoned in regard to pleasant sense 
impression

_sukhāya vedanāya rāgānusayo pahātabbo_
____

____
The proclivity to repugnance should be abandoned in regard to unpleasant sense 
impression

_dukkhāya vedanāya paṭighānusayo pahātabbo_
____

[quote, S.4.205]
____
The proclivity to uninsightfulness into reality should be abandoned in regard 
to neutral sense impression

_adukkhamasukhāya vedanāya avijjānusayo pahātabbo._
____

.Illustration
====
anusaya

proclivity
====

____
For whatever the reason that entrenched perception and conception assail a man

_yatonidānaṃ purisaṃ papañcasaññāsaṅkhā samudācaranti_
____

____
... if there is found nothing there to be delighted in, welcomed, or clung to

_ettha ce natthi abhinanditabbaṃ abhivaditabbaṃ ajjhositabbaṃ_
____

____
... this is the end of the proclivity to attachment

_esevanto rāgānusayānaṃ_
____

____
_..._ this is the end of the proclivity to repugnance

_esevanto paṭighānusayānaṃ_
____

____
_..._ this is the end of the proclivity to dogmatism

_esevanto diṭṭhānusayānaṃ_
____

[quote, M.1.109]
____
_..._ this is the end of the proclivity to doubt [about the significance of the 
teaching]

_esevanto vicikicchānusayānaṃ._
____

.Illustration
====
anusayā

unwholesome proclivities
====

[quote, Sn.v.14]
____
He in whom there are no unwholesome proclivities, in whom the origins of 
whatever is spiritually unwholesome are abolished,

_Yassānusayā na santi keci mūlā akusalā samūhatāse._
____

.Illustration
====
anusayā

unwholesome proclivities
====

• Seven unwholesome proclivities +
_Sattannaṃ bhikkhave anusayānaṃ_

____
proclivity to attachment to sensuous pleasure

_kāmarāgānusayassa_
____

____
proclivity to repugnance

_paṭighānusayassa_
____

____
proclivity to dogmatism

_diṭṭhānusayassa_
____

____
proclivity to doubt [about the significance of the teaching]

_vicikicchānusayassa_
____

____
proclivity to self-centredness

_mānānusayassa_
____

____
proclivity to attachment to individual existence

_bhavarāgānusayassa_
____

[quote, A.4.9]
____
proclivity to uninsightfulness into reality

_avijjānusayassa._
____

.Illustration
====
anusayā

identification
====

[quote, S.3.10]
____
The fondness, attachment, spiritually fettering delight, craving, clinging, 
grasping, obstinate adherence, stubborn attachment, and identification in 
regards to bodily form have been abandoned by the Perfect One

_rūpadhātuyā kho gahapati yo chando yo rāgo yā nandi yā taṇhā ye 
upayupādānā cetaso adhiṭṭhānābhinivesānusayā te tathāgatassa 
pahīnā._
____

.Illustration
====
anuseti

identify with
====

____
Whatever one is intent upon, conceives of, and identifies with, this becomes 
the basis for the establishment of one's stream of sense consciousness.

_bhikkhave ceteti yañca pakappeti yañca anuseti ārammaṇametaṃ hoti 
viññāṇassa ṭhitiyā_
____

____
When there is the basis, there is the establishment of one's stream of sense 
consciousness.

_Yañca ārammaṇe sati patiṭṭhā viññāṇassa hoti._
____

[quote, S.2.66]
____
When one's stream of sense consciousness is established and has [egoistically] 
matured, there is the appearance of denomination-and-bodily-form.

_Tasmiṃ patiṭṭhite viññāṇe virūḷhe nāmarūpassa avakkanti hoti._
____

.Illustration
====
anuseti

identify with
====

[quote, S.2.67]
____
Even if one is not intent upon something, and does not conceive of it, but 
nonetheless one identifies with it, this becomes the basis for the 
establishment of one's stream of sense consciousness.

_no ce bhikkhave ceteti no ce pakappeti atha ce anuseti ārammaṇametaṃ hoti 
viññāṇassa ṭhitiyā._
____

.Illustration
====
anuseti

identify with
====

____
Whatever one identifies with, one is reckoned in terms of.

_yaṃ kho bhikkhu anuseti tena saṅkhaṃ gacchati;_
____

____
Whatever one does not identify with, one is not reckoned in terms of._

_yaṃ nānuseti na tena saṅkhaṃ gacchatī ti._
____

____
If one identifies with bodily form... advertence, then one is reckoned in terms 
of it.

_Rūpaṃ... viññāṇaṃ ce anuseti tena saṅkhaṃ gacchati._
____

[quote, S.3.35]
____
If one does not identify with bodily form... advertence, then one is not 
reckoned in terms of it.

_Rūpaṃ... viññāṇaṃ ce nānuseti na tena saṅkhaṃ gacchati._
____

.Illustration
====
anuseti

identify with
====

____
What one identifies with, by that one is measured. By what one is measured, one 
is reckoned.

_Yaṃ kho bhikkhu anuseti taṃ anumīyati. Yaṃ anumīyati tena saṅkhaṃ 
gacchati_
____

____
What one does not identify with, by that one is not measured. By what one is 
not measured, one is not reckoned._

_yaṃ nānuseti na taṃ anumīyati yaṃ nānumīyati na tena saṅkhaṃ 
gacchatīti._
____

____
If one identifies with the five aggregates, by that one is measured. By what 
one is measured, one is reckoned.

_Rūpaṃ... viññāṇaṃ ce anuseti taṃ anumīyati yaṃ anumīyati tena 
saṅkhaṃ gacchati._
____

[quote, S.3.36-7]
____
If one does not identify with the five aggregates, by that one is not measured. 
By what one is not measured, one is not reckoned.

_Rūpaṃ... viññāṇaṃ ce nānuseti na taṃ anumīyati yaṃ 
nānumīyati na tena saṅkhaṃ gacchati._
____

.Illustration
====
anuseti

lurk within
====

____
Wrong view [of reality] has lurked within the ignorant for a long time

_Dīgharattamanusayitaṃ diṭṭhigatamajānataṃ_
____

[quote, Sn.v.649]
____
The ignorant indeed say one is a Brahman on account of birth._

_Ajānantā no pabruvanti jātiyā hoti brāhmano._
____

.Illustration
====
anuseti

lurk within
====

[quote, D.2.283]
____
The Blessed One has through his explanations removed the arrow of doubt and 
uncertainty [about the way of spiritual fulfilment, and of unfulfilment] long 
lurking in me.

_bhagavatā vyākatā dīgharattānusayitañca pana me 
vicikicchākathaṅkathāsallaṃ tañca bhagavatā abbūḷhanti._
____

.Illustration
====
anuseti

lurk within
====

____
When affected by a pleasant sense impression, he takes delight in it, he 
welcomes it, and persists in cleaving to it.

_so sukhāya vedanāya phuṭṭho samāno abhinandati abhivadati ajjhosāya 
tiṭṭhati._
____

[quote, M.3.286]
____
The proclivity to attachment lurks within him.

_Tassa rāgānusayo anuseti._
____

.Illustration
====
anuseti

lurk within one
====

____
The proclivity to attachment lurks within one in relation to pleasant sense 
impression.

_sukhāya kho āvuso visākha vedanāya rāgānusayo anuseti_
____

____
The proclivity to repugnance lurks within one in relation to unpleasant sense 
impression.

_dukkhāya vedanāya paṭighānusayo anuseti_
____

[quote, M.1.302]
____
The proclivity to uninsightfulness into reality lurks within one in relation to 
neutral sense impression.

_adukkhamasukhāya vedanāya avijjānusayo anusetīti._
____

.Illustration
====
anuseti

linger within
====

____
And of what sort is he who is like carving on a rock? In this regard, some 
person is frequently angry (_abhiṇhaṃ kujjhati_). Moreover that anger 
lingers within him for a long time

_so ca khvassa kodho dīgharattaṃ anuseti_
____

[quote, A.1.284]
____
And of what sort is he who is like carving on the ground? In this regard, some 
person is frequently angry (_abhiṇhaṃ kujjhati_), but his anger does not 
linger within him for a long time

_so ca khvassa kodho na dīgharattaṃ anuseti._
____

