== Anālaya

=== Renderings

- _allīyati_: to adhere to

- _allīyati_: to cling

- _ālaya_: clinging

- _anālaya_: letting go

=== Introduction

==== 1) Ālayo: 'repository,' 'shelter' or 'abode'

The noun _ālayo_ has two broad meanings. Firstly 'repository,' 'shelter' or 
'abode':

[quote, S.5.400]
____
'the great ocean, fearsome repository of heaps of gems'

_mahāsaraṃ bahubheravaṃ ratanagaṇānamālayaṃ._
____

[quote, Th.v.307]
____
the terrified crane 'takes flight, looking for shelter'

_palehiti ālayamālayesinī._
____

[quote, Thī.v.270]
____
the body, 'the abode of many miseries'

_bahu dukkhānamālayo._
____

==== 2) Ālayo: 'clinging,' 'adhering to.' Anālayo: 'letting go.'

We concentrate here on the second broad meaning, calling _ālaya_ 'clinging' or 
'adhering to,' and _anālayo_ 'letting go.'

=== Illustrations

.Illustration
====
allīyissanti

adhere to
====

____
Shall it be that those non-Buddhist ascetics, whose teachings are badly 
explained, should adhere to and undertake a rains residency period?

_vassāvāsaṃ allīyissanti saṅkāsayissanti._
____

____
Shall it be that these birds, having made nests in the tree-tops, should adhere 
to and undertake a rains residency period?

_vassāvāsaṃ allīyissanti saṅkāsayissanti._
____

But these ascetic disciples of the Sakyans' Son, walk on tour during the cold 
season, hot season, and wet season, trampling down crops and grass, and bring 
about the death of many small beings (Vin.1.137).

.Illustration
====
allīyetha

to cling to
====

[quote, M.1.260]
____
But if you cling to, prize, treasure, and cherish this perception [of reality] 
so perfect and pure would you then have understood that the teaching explained 
by me is comparable to a raft, being for the sake of crossing [the flood of 
suffering], not for the sake of clinging to it?

_Imañce tumhe bhikkhave diṭṭhiṃ evaṃ parisuddhaṃ evaṃ 
pariyodātaṃ allīyetha keḷāyetha dhanāyetha mamāyetha api nu tumhe 
bhikkhave kullūpamaṃ dhammaṃ desitaṃ ājāneyyātha nittharaṇatthāya 
no gahaṇatthāyāti?._
____

.Illustration
====
allīyanti

to cling to
====

[quote, S.3.190]
____
So long as they are not free of attachment, desire, love, thirst, passion, and 
craving regarding those sand castles, they cling to them, prize, treasure, and 
cherish them.

_yāvakivañca tesu paṃsvāgārakesu avigatarāgā honti avigatacchandā 
avigatapemā avigatapipāsā avigatapariḷāhā avigatataṇhā tāva tāni 
paṃsvāgārakāni allīyanti kelāyanti dhanāyanti mamāyanti._
____

.Illustration
====
ālayo

clinging
====

[quote, M.1.191]
____
The fondness, clinging, attraction, and cleaving within these five grasped 
aggregates is the origin of suffering.

_Yo imesu pañcasupādānakkhandhesu chando ālayo anunayo ajjhosānaṃ so 
dukkhasamudayo._
____

.Illustration
====
ālaya

clinging
====

[quote, M.1.167]
____
For beings who take pleasure and delight in clinging, finding satisfaction in 
clinging

__ālayarāmāya kho pana pajāya ālayaratāya ālayasammuditāya._
____

.Illustration
====
ālaya

clinging; anālaye, letting go
====

[quote, A.2.131]
____
Beings take pleasure and delight in clinging, find satisfaction in clinging. 
But they really listen to the teaching of letting go taught to them by the 
Perfect One, they lend an ear, they apply their minds to understand [it].

__ālayārāmā bhikkhave pajā ālayaratā ālayasammuditā sā tathāgatena 
anālaye dhamme desiyamāne sussūsati sotaṃ odahati aññācittaṃ 
upaṭṭhapeti._
____

.Illustration
====
anālayo

letting go
====

[quote, M.1.49]
____
The complete passing away and ending of this same craving, the giving up and 
relinquishment of it, the freedom from it, the letting go of it, is called the 
ending of suffering.

_Yo tassāyeva taṇhāya asesavirāganirodho cāgo paṭinissaggo mutti 
anālayo ayaṃ vuccatāvuso dukkhanirodho._
____

.Illustration
====
anālaya

letting go
====

____
Bhikkhus, I will teach you letting go and the path leading to letting go. 
Please listen.

_anālayañca vo bhikkhave desissāmi anālayagāmiñca maggaṃ taṃ 
suṇātha_
____

____
And what is letting go? The destruction of attachment, the destruction of 
hatred, the destruction of undiscernment of reality: this is called letting go.

_Katamañca bhikkhave anālayaṃ: yo bhikkhave rāgakkhayo dosakkhayo 
mohakkhayo idaṃ vuccati bhikkhave anālayaṃ_
____

____
And what is the path leading to letting go?

_Katamo ca bhikkhave anālayagāmī maggo_
____

[quote, S.4.369]
____
Inward calm and insightfulness: this is called the path leading to letting go

_samatho ca vipassanā ca. Ayaṃ vuccati bhikkhave anālayagāmī maggo._
____

