== Anīgha

=== Renderings

- _anīgha_ (adj): rid of spiritual defilement

- _anīgha_: one who is rid of spiritual defilement

- _nīgha_: spiritual defilement

=== Introduction

==== The derivation of anīgha

DOP says the etymology of _anīgha_ is uncertain, but suggests it means either 
_niddukkha_ or _a+īgha_ (without evil). But the scriptures do not support 
this_._

==== Etymology: a+nīgha not a+īgha

The scriptures show that _anīgha_ is _a+nīgha_ not _a+īgha_. For example, 
the _Kāmabhu Sutta_ (S.4.292) says the arahant is called _anīgho_ because he 
has abandoned _rāgo nīgho, doso nīgho, moho nīgho_:

____
Attachment, hatred, and undiscernment of reality are spiritual defilements

_rāgo kho bhante nīgho doso nīgho moho nīgho_
____

[quote, S.4.292]
____
... The arahant has abandoned them, chopped them down at the root, completely 
and irreversibly destroyed them, so they will never arise again in future, 
therefore the arahant is called 'one who is rid of spiritual defilement'_

_te khīṇāsavassa bhikkhuno pahīnā ucchinnamūlā tālāvatthukatā 
anabhāvakatā āyatiṃ anuppādadhammā tasmā khīṇāsavo bhikkhu anīgho 
ti vuccati._
____

==== Nīgha means rāgo, doso and moho

The _Kāmabhu Sutta_ also therefore shows that _nīgha_ means _rāgo, doso,_ 
and _moho._

==== Nīgha means spiritual defilement

Other suttas show the meaning of _anīgha_ is broader than that, showing that 
_nīgha_ means spiritual defilement.

1. The _Uraga Sutta_, quoted more fully below, links it to the abandonment of 
the five hindrances (_yo nīvaraṇe pahāya pañca anīgho_).

2. Other suttas associate _anīgha_ with freedom from, for example, longing 
(_nirāsaṃ_), doubt (_saṃsayaṃ_) and attachment (_asitaṃ; 
chinnaganthaṃ; saṃyojanabandhanacchidā_). See Illustrations.

Therefore _nīgha_ means any kind of spiritual defilement.

==== Anīgha means 'rid of spiritual defilement'

If _anīgha_ means freedom from a broad range of spiritual defilements through 
their being abandoned, chopped down at the root, completely and irreversibly 
destroyed, so they will never arise again in future, it is properly represented 
by the phrase 'rid of spiritual defilement.'

==== Spellings, anīgha and anigha

There are two spellings: _anīgha_ and _anigha_, but _anīgha_ seems more 
orthodox. _Anigha_ occurs only in verse, suggesting that _anīgha_ becomes 
_anigha_ for metrical purposes. Indeed, DOP says _anīgha_ is 'usually 
unmetrical.'

=== Illustrations

.Illustration
====
anigho

rid of spiritual defilement
====

&#8203;[The Blessed One:]

____
'Indeed, I am rid of spiritual defilement, deity;

_anigho ve ahaṃ yakkha_
____

____
and no spiritually fettering delight is found in me;

_atho nandi na vijjati_
____

____
And when I am sitting alone, disgruntlement [with the celibate life] does not 
overwhelm me.

_Atho maṃ ekamāsīnaṃ arati nābhikīratīti._
____

Then the Buddha explained:

____
Spiritually fettering delight is for one with spiritual defilement;

_aghajātassa ve nandi_
____

____
Spiritual defilement is for one with spiritually fettering delight;

_nandijātassa ve aghaṃ_
____

[quote, S.1.54]
____
Thus know me friend as a bhikkhu free of spiritually fettering delight and rid 
of spiritual defilement.

_Anandi anigho bhikkhu evaṃ jānāhi āvuso ti._
____

Comment:

I accept PTS spellings here. I take _anigha_ as standing for _anīgha_ because 
DOP says _anīgha_ is usually unmetrical_._ I take _aghaṃ_ to mean _nigha_ 
because the passage itself does so.

Although these readings are unsettled, other readings do no better in 
explaining the nature of the conversation here. Bodhi renders the word as 
'untroubled' throughout.

.Illustration
====
anīghaṃ

rid of spiritual defilement
====

• One whose spiritual shackles are destroyed, one rid of spiritual 
defilement, free of expectations +
_taṃ chinnaganthaṃ anīghaṃ nirāsaṃ_ (S.1.12).

.Illustration
====
anīghā

rid of spiritual defilement
====

[quote, M.3.55]
____
He has a benevolent mind and unhateful thoughts. He thinks 'May these creatures 
sustain themselves happily, and be rid of unfriendliness, hostility, and 
spiritual defilement.'_

_ime sattā averā avyāpajjhā anīghā sukhī attānaṃ pariharantū ti._
____

.Illustration
====
anīghaṃ

rid of spiritual defilement
====

[quote, It.97]
____
Rid of spiritual defilement, free of doubt [about the significance of the 
teaching], unattached to anything in the whole world [of phenomena]

_anīghaṃ chinnasaṃsayaṃ asitaṃ sabbalokassa._
____

.Illustration
====
anīgho

rid of spiritual defilement
====

[quote, Sn.v.17]
____
He who has abandoned the five hindrances, who is rid of spiritual defilement, 
who has overcome uncertainty [about the significance of the teaching], who is 
free of the arrow [of doubt and uncertainty about the significance of the 
teaching],

_yo nīvaraṇe pahāya pañca anīgho tiṇṇakathaṅkatho visallo._
____

Comment:

Because of its proximity to _tiṇṇakathaṅkatho_ we take _visallo_ to mean 
free of _vicikicchākathaṅkathāsallaṃ_, a term which occurs at D.3.250 and 
A.3.292.

.Illustration
====
anīghā

rid of spiritual defilement
====

[quote, Sn.v.491]
____
Those who have severed every tie and bond [to individual existence], inwardly 
tamed, liberated [from perceptually obscuring states], rid of spiritual 
defilement, free of expectations,

_Ye sabbasaṃyojanabandhanacchidā dantā vimuttā anīghā nirāsā;._
____

.Illustration
====
anīgho

rid of spiritual defilement
====

[quote, Sn.v.1060]
____
And whatever man here is wise, one who is blessed with profound knowledge, who 
has freed himself from this [wretched] bondage to all states of individual 
existence, he is free of craving, rid of spiritual defilement, and free of 
expectations [in regard to both this world and the world beyond]. He has 
overcome birth and old age, I declare.

_Vidvā ca yo vedagū naro idha bhavābhave saṅgamimaṃ visajja +
So vitataṇho anīgho nirāso atāri so jāti jaranti brūmiti._
____

.Illustration
====
nīghā

spiritual defilement
====

____
Bhikkhus, there are these three kinds of spiritual defilement. What three?

_Tayome bhikkhave nīghā. Katame tayo?_
____

____
the spiritual defilement of attachment

_rāgo nīgho_
____

____
the spiritual defilement of hatred

_doso nīgho_
____

[quote, S.5.57]
____
the spiritual defilement of undiscernment of reality

_moho nīgho._
____

