== Atammayo; No Sīlamayo; Mayo

=== Renderings

- _atammayo_: one who perceives that "It is void of personal qualities"

- _atammayataṃ_: the perception that "It is void of personal qualities"

- _tammayo_: regard as endowed with personal qualities

- _sīlamayo_: one who regards virtue as endowed with personal qualities

- _sīlamayo_: comprised of virtue

=== Introduction

==== Maya: meaning

_Maya_ means

1. Made of

2. Comprised of

3. Created by

4. Brought about by

5. Aroused by

==== Maya: examples

1. Made of:

[quote, Vin.1.203]
____
Ointment-boxes made of bone

_aṭṭhimayaṃ._
____

[quote, Sn.v.669]
____
With hammers made of iron

_ayomayakuṭehi._
____

2. Comprised of:

• There are three bases for the generating of merit: the basis for the 
generating of merit comprised of generosity, or of virtue, or of spiritual 
cultivation +
☸ _tīṇi puññakiriyavatthūni_: _dānamayaṃ puññakiriyavatthu, 
sīlamayaṃ puññakiriyavatthu, bhāvanāmayaṃ puññakiriyavatthu_ 
(D.3.218. It.51).

3. Created by:

[quote, D.1.77]
____
Mind-created material body

_rūpiṃ manomayaṃ._
____

[quote, S.4.70]
____
Perceptions (_saññā_) created by the mind

_manomayaṃ._
____

4. Aroused by

[quote, D.3.219]
____
Wisdom aroused by reflection, or by learning, or by spiritual development

_cintāmayā paññā sutamayā paññā bhāvanāmayā paññā._
____

There are two forms of _maya_ that cannot be rendered by this scheme: 
_atammayo_ and _sīlamayo_.

==== Atammayo

_Atammayo_ means literally 'not made of or produced by that.' Its actual 
meaning is uncertain. Horner calls _atammayataṃ_ lack of desire (MLS.3.92). 
Bodhi calls it non-identification (MLDB.911). The suttas show it means freedom 
from ego.

==== Atammayo and the perception of the voidness of personal qualities in all 
originated phenomena: Ukkhittāsika Sutta

The _Ukkhittāsika Sutta_ (A.3.444) (quoted next) says being _atammayo_ 
regarding the whole world [of phenomena] (_sabbaloke ca atammayo_) is one of 
the benefits of establishing without limit the perception of the voidness of 
personal qualities in all originated phenomena.

____
When a bhikkhu sees six advantages it should be enough to inspire him to 
establish [in himself] without limit the perception of the voidness of personal 
qualities in all originated phenomena. What six?

_Cha bhikkhave ānisaṃse sampassamānena alameva bhikkhunā 
sabbasaṅkhāresu anodhiṃ karitvā anattasaññaṃ upaṭṭhāpetuṃ 
katame cha:_
____

1. I will be free of the perception that "It is endowed with personal 
qualities" regarding the whole world [of phenomena].
+
****
_Sabbaloke ca atammayo bhavissāmi_ (A.3.444).
****

Thus _atammayo_ is linked to the perception of the voidness of personal 
qualities in all originated phenomena.

==== Atammayo and egotistical thought: Sappurisa Sutta

The _Sappurisa Sutta_ (M.3.42) says when the common person (a__sappuriso__) 
gains first jhāna, he thinks 'I am an attainer of the first jhāna; these 
other bhikkhus are not.' But when a spiritually outstanding person 
(_sappuriso_) gains jhāna, he thinks '_atammayatā_ even concerning the 
attainment of the first jhāna has been spoken of by the Blessed One 
(_paṭhamajjhānasamāpattiyāpi kho atammayatā vuttā bhagavatā_). Here 
_atammayatā_ is the opposite of the egotistical thought 'I am an attainer of 
the first jhāna.'

That _atammayatā_ is a queller of the ego is confirmed in this same passage 
because the sutta continues: _yena yena hi maññati tato taṃ hoti 
aññathā._ Horner renders this: 'for whatever they imagine it to be, it is 
otherwise.' Bodhi says: 'for in whatever way they conceive, the fact is ever 
other than that.'

But we have shown in this Glossary that _maññati_ is not just 'to think,' but 
'to think of in personal terms.' Even the passage in hand already suggests 
this, where the thoughts of the a__sappuriso__, dominated by the word _ahaṃ_ 
are so obviously egotistical.

Therefore, in context, the words mean:

- _atammayo_: one who perceives that "It is void of personal qualities."

- _atammayataṃ_: the perception that "It is void of personal qualities."

==== Sīlamayo: 'comprised of virtue'

_Sīlamayo_ can mean 'comprised of virtue.' For example, there are three bases 
for the generating of merit (_tīṇi puññakiriyavatthūni_ D.3.218. It.51).

1. The basis for the generating of merit comprised of generosity
+
****
_dānamayaṃ puññakiriyavatthu_
****

2. The basis for the generating of merit comprised of virtue
+
****
_sīlamayaṃ puññakiriyavatthu_
****

3. The basis for the generating of merit comprised of spiritual cultivation
+
****
_bhāvanāmayaṃ puññakiriyavatthu_ (D.3.218; It.51).
****

==== No sīlamayo: 'one who does not regard virtue as endowed with personal 
qualities'

However, the _Samaṇamaṇḍikā Sutta_ gives _sīlamayo_ a different 
meaning. It proclaims a bhikkhu for being virtuous (_sīlavā hoti_) and adds 
that he should also _no ca sīlamayo_ (i.e. _idha thapati bhikkhu sīlavā hoti 
no ca sīlamayo_). Bodhi renders this 'a bhikkhu is virtuous but he does not 
identify with his virtue (MLDB p.651). Horner says 'a monk is of moral habit 
and has no addition to make to moral habit' (MLS.2.226). Let us consider it in 
four steps:

1. if _atammayo_ means 'one who perceives that "It is void of personal 
qualities,"' then

2. _tammayo_ means 'one who perceives that "It is endowed with personal 
qualities"' and

3. _sīlamayo_ means 'one who regards virtue as endowed with personal 
qualities,' and therefore

4. _no sīlamayo_ means 'one who does not regard virtue as endowed with 
personal qualities.'

=== Illustrations

.Illustration
====
atammayataṃ

the perception that "It is void of personal qualities"
====

When the common person (a__sappuriso__) gains first jhāna, he thinks 'I am an 
attainer of the first jhāna; these other bhikkhus are not,' thereby glorifying 
himself and disparaging others (_attānukkaṃseti paraṃ vambheti_). When a 
spiritually outstanding person (_sappuriso_) gains jhāna, he thinks:

____
The perception that "It is void of personal qualities" even concerning the 
attainment of the first jhāna has been declared by the Blessed One.

_paṭhamajjhānasamāpattiyāpi kho atammayatā vuttā bhagavatā_
____

____
... Whatsoever one thinks of in personal terms, it is different than [how one 
thinks of it].'

_yena yena hi maññanti tato taṃ hoti aññathā'ti_
____

[quote, M.3.42-3]
____
... Therefore having prioritised the perception that "It is void of personal 
qualities," he neither glorifies himself nor disparages others concerning the 
attainment of first jhāna. This is the character of a spiritually outstanding 
person.

_so atammayataṃyeva antaraṃ karitvā tāya paṭhamajjhānasamāpattiyā 
neva attānukkaṃseti na paraṃ vambheti. Ayampi bhikkhave sappurisadhammo._
____

.Illustration
====
atammayataṃ

the perception that "It is void of personal qualities"
====

[quote, M.3.220]
____
Bhikkhus, with the help of and by means of the perception that "It is void of 
personal qualities" abandon and transcend the neutral attitude that is 
undiversified, associated with undiversity.

_Atammayataṃ bhikkhave nissāya atammayataṃ āgamma yā'yaṃ upekkhā 
ekattā ekattasitā taṃ pajahatha taṃ samatikkamatha._
____

.Illustration
====
atammayo

free of the perception that "It is endowed with personal qualities"
====

[quote, A.1.150]
____
Such a person as him, one who knows the world [of phenomena] [according to 
reality], one of great wisdom, is free of the perception that "It is endowed 
with personal qualities" regarding all things, a sage.

_Sa tādiso lokavidū sumedho sabbesu dhammesu atammayo munī ti._
____

.Illustration
====
tammayo

regard as endowed with personal qualities
====

[quote, M.1.319]
____
Purified states known through the eye or ear are found in the Perfect One. They 
are my path [of practice], my sphere of personal application, but I do not 
regard them as endowed with personal qualities.

_ye vodātā cakkhusotaviññeyyā dhammā saṃvijjanti te tathāgatassa 
etapathohamasmi etagocaro no ca tena tammayo ti._
____

.Illustration
====
sīlamayo

one who regards virtue as endowed with personal qualities
====

[quote, M.2.27]
____
A bhikkhu is virtuous but does not regard virtue as endowed with personal 
qualities

_bhikkhu sīlavā hoti no ca sīlamayo._
____

