== Atandita

=== Renderings

- _atandita_: tirelessly applied [to the practice]

- _atandita_: tirelessly applied [to benefiting]

- _atandita_: unwearied man

=== Introduction

==== Synonyms

_Atandita_ is close in meaning to _appamatto_, and we parenthesise it equally:

[quote, Th.v.83]
____
Sīha, dwell diligently applied [to the practice]. Dwell tirelessly applied [to 
the practice] night and day. Develop spiritually wholesome factors. Quickly 
give up [attachment to] the body.

_Sīhappamatto vihara rattindivamatandito +
Bhāvehi kusalaṃ dhammaṃ jaha sīghaṃ samussayan ti._
____

=== Illustrations

.Illustration
====
atanditā

being tirelessly applied [to the practice]
====

[quote, Thī.v.84]
____
Viewing it in this way, being tirelessly applied [to the practice] night and 
day, then, having profoundly understood it through my own penetrative 
discernment, I saw it [according to reality].

_Evametaṃ avekkhantī rattindivamatanditā +
Tato sakāya paññāya abhinibbijjha dakkhisaṃ._
____

.Illustration
====
atandite

tirelessly applied [to the practice]
====

• Having renounced [the household life] in faith, a novice bhikkhu newly gone 
forth [into the ascetic life] should associate with virtuous friends whose 
means of livelihood is pure, who are tirelessly applied [to the practice]. +
_Saddhāya abhinikkhamma navapabbajito navo +
Mitte bhajeyya kalyāṇe suddhājīve atandite_ (Th.v.249)

.Illustration
====
atandito

tirelessly applied [to the practice]
====

[quote, Thī.v.212]
____
'Being resolutely applied to inward striving, and tirelessly applied [to the 
practice] night and day, urged on by my mother, I realised supreme inward peace.

_Sohaṃ padhānapahitatto rattindivamatandito +
Mātarā codito santo aphusiṃ santimuttamaṃ._
____

.Illustration
====
atandito

tirelessly applied [to the practice]
====

[quote, Th.v.354]
____
'Recollecting the Perfectly Enlightened One, the best [of Buddhas], who is 
inwardly tamed and inwardly collected, being tirelessly applied [to the 
practice] night and day, I will abide in the woods.'

_Anussaranto sambuddhaṃ aggaṃ dantaṃ samāhitaṃ +
Atandito rattindivaṃ viharissāmi kānane ti._
____

.Illustration
====
atandito

tirelessly applied [to the practice]
====

[quote, Th.v.626]
____
Dwelling alone in the woods, tirelessly applied [to the practice], I followed 
the Teacher's advice. I did just as the Conqueror instructed me [to do].

_Sohaṃ eko araññasmiṃ viharanto atandito +
Akāsiṃ satthu vacanaṃ yathā maṃ ovadi jino._
____

.Illustration
====
atandito

tirelessly applied [to the practice]
====

[quote, Dh.v.305]
____
Sitting alone, sleeping alone, living alone, tirelessly applied [to the 
practice], taming oneself in solitude, one would be [thereby] delighted in the 
woods.

_Ekāsanaṃ ekaseyyaṃ eko caramatandito +
Eko damayamattānaṃ vanante ramito siyā._
____

.Illustration
====
atanditaṃ

tirelessly applied [to the practice]
====

[quote, Dh.v.366]
____
If, though he receives but little, a bhikkhu does not despise his gains, even 
the devas praise him, one of pure livelihood who is tirelessly applied [to the 
practice].

_Appalābho pi ce bhikkhu salābhaṃ nātimaññati +
Taṃ ve devā pasaṃsanti suddhājīviṃ atanditaṃ._
____

.Illustration
====
atandite

tirelessly applied [to the practice]
====

[quote, Dh.v.376]
____
Associate with virtuous friends who are of pure livelihood, and who are 
tirelessly applied [to the practice].

_Mitte bhajassu kalyāṇe suddhājīve atandite._
____

.Illustration
====
atandito

tirelessly applied [to benefiting]
====

[quote, A.4.245]
____
Tirelessly applied [to benefiting] his mother, father, and ancestors, night and 
day

_Mātaraṃ pitaraṃ pubbe rattindivamatandito._
____

.Illustration
====
atandito

unwearied man
====

[quote, Th.v.1138]
____
Therefore, I will make you as supple as an unwearied man makes a catskin bag.

_Tathā tu kassāmi yathā pi issaro yaṃ labbhati tena pi hotu me alaṃ +
Taṃ t'ahaṃ kassāmi yathā atandito biḷārabhastaṃ va tathā 
sumadditaṃ._
____

