== Atimaññati

=== Renderings

- _atimaññati_: despise

- _atimaññati_: spurn

- _atimaññati_: disdain

=== Illustrations

.Illustration
====
atimaññati

despised
====

[quote, S.1.187]
____
Venerable Vaṅgīsa despised other well-behaved bhikkhus on account of his own 
impromptu reflectiveness

__āyasmā vaṅgīso attano paṭibhānena aññe pesale bhikkhū 
atimaññati._
____

.Illustration
====
atimaññanti

despised
====

[quote, D.3.87]
____
Those that were beautiful despised those that were ugly, thinking: We are more 
beautiful than them; they are more ugly than us.

_Tattha ye te sattā vaṇṇavanto te dubbaṇṇe satte atimaññanti 
mayametehi vaṇṇavantatarā amhehete dubbaṇṇatarā ti._
____

.Illustration
====
atimaññeti

despises
====

[quote, Sn.v.104]
____
If any man being puffed up because of ancestry, wealth, or clan despises his 
own relatives, that is the cause of spiritual ruination.

_Jātitthaddho dhanatthaddho gottatthaddho ca yo naro +
Saññātiṃ atimaññeti taṃ parābhavato mukhaṃ._
____

.Illustration
====
atimaññe

despise
====

[quote, Sn.v.931]
____
He should not despise others for their lowly way of life, or wisdom, or 
observances and practices._

_Atha jivitena paññāya silabbatena nāññamatimaññe._
____

.Illustration
====
atimaññetha

despise
====

[quote, Sn.v.148]
____
One should not despise anyone in any way

_nātimaññetha katthaci naṃ kañci._
____

.Illustration
====
atimaññissatī

spurn
====

[quote, Vin.3.7]
____
In future days men will spurn meaty boiled rice and gruel

_Pacchimā janatā sālimaṃsodanaṃ atimaññissatī ti._
____

.Illustration
====
atimaññamāno

spurn
====

[quote, M.2.180]
____
A brahman who spurns his own wealth (i.e. walking on almsround) fails in his 
duty._

_Bhikkhācariyañca pana brāhmaṇo sandhanaṃ atimaññamāno akiccakārī 
hoti._
____

.Illustration
====
atimaññamāno

spurn
====

[quote, A.3.225]
____
Faring wholly on alms, spurning not the beggar's bowl

_kevalaṃ bhikkhācariyāya kapālaṃ anatimaññamāno._
____

.Illustration
====
atimaññitabbā

spurn
====

[quote, M.2.242]
____
If one thinks 'I am not able to make that person emerge from what is 
spiritually unwholesome and establish him in what is spiritually wholesome,' 
for such a person, detached awareness should not be spurned.

_Na cāhaṃ sakkomi etaṃ puggalaṃ akusalā vuṭṭhāpetvā kusale 
patiṭṭhāpetun ti. Evarūpe bhikkhave puggale upekkhā nātimaññitabbā._
____

.Illustration
====
atimaññasi

disdain
====

• There is no hiding place for the doer of unvirtuous deeds +
_Natthi loke raho nāma pāpakammaṃ pakubbato._

• You yourself, man, know what is true or false. +
_Attā te purisa jānāti saccaṃ vā yadi vā musā._

• Indeed, sir, you disdain the virtuous aspect of yourself which witnesses 
&#8203;[all that you do] +
_Kalyāṇaṃ vata bho sakkhi attānaṃ atimaññasi._

• You are [trying to] conceal from yourself unvirtuoushess existing within 
yourself +
_Yo santaṃ attani pāpaṃ attānaṃ parigūhasi_ (A.1.149).

