== Attabhāva

=== Renderings

- _attabhāva_: bodily form

- _attabhāva_: individuality

- _attabhāva_: state of individuality

- _attabhāva_: personal disposition

- _attabhāvapaṭilābho_: acquired bodily form

- _attabhāvapaṭilābho_: assumed individuality

=== Introduction

==== The -paṭilābho suffix

Often _attabhāva_ is suffixed to become _attabhāvapaṭilābho_, which means:

- 'Assumption of an existence, becoming reborn as an individual' (PED sv 
_Attan_).

- 'Obtaining a reincarnation, coming into existence' (PED sv _Paṭilābha_).

- 'The becoming reborn as an individual; reincarnation; type of body or 
existence' (DOP sv _Attan_).

But -_paṭilābho_ is sometimes better treated as a past participle:

1. 'Acquired':
+
One of Venerable MahāMoggallāna's supporters was reborn in a mind-made body 
(_aññataraṃ manomayaṃ kāyaṃ upapanno_), and his [newly] acquired 
bodily form (_tassa evarūpo attabhāvapaṭilābho hoti_) was such that he 
filled two or three Magadhan village fields, yet that [newly] acquired bodily 
form harmed neither himself nor another (_so tena attabhāvapaṭilābhena 
nevattānaṃ no paraṃ vyābādheti_) (A.3.122).

2. 'Assumed':
+
[quote, S.3.144]
____
Bhikkhu, there is not even this amount of one's assumed individuality that is 
everlasting

_ettakopi kho bhikkhu attabhāvapaṭilābho natthi nicco._
____

=== Illustrations

.Illustration
====
attabhāvaṃ

bodily forms
====

[quote, Th.v.1183]
____
In an instant I can fashion the bodily forms of ten billion [people].

_Koṭisatasahassassa attabhāvaṃ khaṇena nimmine._
____

.Illustration
====
attabhāvena

bodily form
====

Nanda's mother said that when her husband died, he 'revealed himself to me in 
his former bodily form' (_purimena attabhāvena uddassesi_); but she did not 
recall any inward disquiet on that account (A.4.66).

.Illustration
====
attabhāvaṃ

bodily form
====

When Brahmā Sanaṅkumāra appears to the Tāvatiṃsā devas, he appears 
having created [for himself] a less subtle bodily form (_oḷārikaṃ 
attabhāvaṃ abhinimminitvā_) because his natural appearance 
(_pakativaṇṇo_) is not perceptible to the eye (_anabhisambhavanīyo so 
devānaṃ tāvatiṃsānaṃ cakkhupathasmiṃ_) (D.2.210).

.Illustration
====
attabhāvo

bodily form
====

A bull elephant might plunge into a large pool of water and amuse himself 
squirting water into his ears or over his back. Then he drinks and leaves. How 
does he manage it? The greatness of his bodily form, Upāli, finds a footing in 
deep water (_mahāhupāli attabhāvo gambhīre gādhaṃ vindati_).

But suppose a hare or a cat tries the same thing, he will either sink to the 
bottom or float on the surface. Why so? The smallness of his bodily form, 
Upāli, finds no footing in deep water (_paritto hupāli attabhāvo gambhīre 
gādhaṃ na vindati_) (A.5.202).

.Illustration
====
attabhāvassa

bodily form
====

The small beings in the ocean that could not easily be impaled on stakes would 
be even more numerous than this.

[quote, S.5.442]
____
For what reason? Because of the minuteness of their bodily forms.

_Taṃ kissa hetu: sukhumattā bhikkhave attabhāvassa._
____

.Illustration
====
attabhāvīnaṃ

bodily form
====

• Chief of those of bodily form is Rāhu, Lord of the Asuras. +
_Etadaggaṃ bhikkhave attabhāvīnaṃ yadidaṃ rāhu asurindo_ (A.2.17).

Comment:

Rāhu is able to grasp the sun and the moon in his mouth (S.1.50-1), and can 
stop rain falling by gathering it into his hand (A.3.243). Therefore we take 
_attabhāvīnaṃ_ as referring to the size of his body.

.Illustration
====
attabhāvaṃ

bodily form
====

Hatthaka, the young deva, approached the Blessed One, thinking, 'I will stand 
in the presence of the Blessed One,' but he sank down and collapsed like butter 
or oil when poured on sand sinks down, sinks in, cannot abide. Then the Blessed 
One told him 'Create a less subtle bodily form, Hatthaka' (_oḷārikaṃ 
hatthaka attabhāvaṃ abhinimmināhī ti_). 'I will, bhante' he replied, and 
doing as he was bid, venerated the Blessed One, and stood at a respectful 
distance (A.1.279).

.Illustration
====
attabhāvā

bodily forms
====

Bhante, the mighty ocean is the home of vast beings (_mahataṃ bhūtānaṃ_). 
There are the fabulous fishy monsters, the timis, the _timiṅgalas_, and the 
_timirapiṅgalas_; there are the asuras, the magical serpents, and the 
heavenly musicians. There are in the mighty ocean bodily forms a hundred 
leagues long (_yojanasatikāpi attabhāvā_), two hundred (_dviyojanasatikāpi 
attabhāvā_), three (_tiyojanasatikāpi attabhāvā_), four 
(_catuyojanasatikāpi attabhāvā_) and five hundred leagues long 
(_pañcayojanasatikāpi attabhāvā_) (A.4.200).

.Illustration
====
attabhāvo

individuality
====

____
Karmically consequential conduct produced from greed, born of greed, due to 
greed, originated by greed bears fruit wherever the rebirth of one's 
individuality occurs.

_Yaṃ bhikkhave lobhapakataṃ kammaṃ lobhajaṃ lobhanidānaṃ 
lobhasamudayaṃ yatthassa attabhāvo nibbattati tattha taṃ kammaṃ 
vipaccati._
____

[quote, A.1.134]
____
Wherever that karmically consequential conduct bears fruit, there one 
experiences the karmic consequences of one's conduct, either in this life, or 
on rebirth, or in some other subsequent [existence].

_Yattha taṃ kammaṃ vipaccati tattha tassa kammassa vipākaṃ 
paṭisaṃvedeti diṭṭhe vā dhamme upapajje vā apare vā pariyāye._
____

.Illustration
====
attabhāvassa

individuality
====

One is reckoned according to wherever the rebirth of one's individuality occurs 
(_yattha yattheva attabhāvassa abhinibbatti hoti tena teneva saṅkhaṃ 
gacchati_).

- If the rebirth of one's individuality occurs in a clan of _khattiyas_ 
(_khattiyakule ce attabhāvassa abhinibbatti hoti_), one is reckoned as a 
_khattiya_ (_khattiyotveva saṅkhaṃ gacchati_).

- If the rebirth of one's individuality occurs in a clan of brahmans 
(_brāhmaṇakule ce attabhāvassa abhinibbatti hoti_), one is reckoned as a 
brahman (_brāhmaṇotveva saṅkhaṃ gacchati_).

- If the rebirth of one's individuality occurs in a clan of _vessas_ 
(_vessakule ce attabhāvassa abhinibbatti hoti_), one is reckoned as a _vessa_ 
(_vessotveva saṅkhaṃ gacchati_).

- If the rebirth of one's individuality occurs in a clan of _suddas_ 
(_suddakule ce attabhāvassa abhinibbatti hoti_), one is reckoned as a sudda 
(_suddotveva saṅkhaṃ gacchati_) (M.2.181).

.Illustration
====
attabhāvapaṭilābho

assumed individuality
====

____
Bhikkhu, there is nothing in the five aggregates which is everlasting, 
enduring, eternal, of an unchangeable nature, that will endure like unto 
eternity itself.

_Natthi kho bhikkhu kiñci rūpaṃ... vedanā... saññā... saṅkhārā... 
viññāṇaṃ yaṃ viññāṇaṃ niccaṃ dhuvaṃ sassataṃ 
aviparināmadhammaṃ sassatisamaṃ tatheva ṭhassati?_
____

Then the Blessed One took up a little piece of cowdung in his hand and said to 
that bhikkhu:

[quote, S.3.144]
____
Bhikkhu, there is not even this amount of one's assumed individuality that is 
everlasting, enduring, eternal, of an unchangeable nature, that will endure 
like unto eternity itself.

_ettakopi kho bhikkhu attabhāvapaṭilābho natthi nicco dhuvo sassato 
avipariṇāmadhammo._
____

.Illustration
====
attabhāvapaṭilābha

assumed individuality
====

____
Assumed individuality is of two kinds, I declare: to be fostered and not to be 
fostered. And one's assumed individuality is either the one or the other. So it 
was said by the Blessed One. And in reference to what was it said?

_Attabhāvapaṭilābhampahaṃ bhikkhave duvidhena vadāmi sevitabbampi 
asevitabbampi. Tañca aññamaññaṃ attabhāvapaṭilābhan ti iti kho 
panetaṃ vuttaṃ bhagavatā kiñcetaṃ paṭicca vuttaṃ._
____

• Bhante, such an assumed individuality as causes spiritually unwholesome 
factors to flourish and spiritually wholesome factors to fade in one who 
fosters it should not be fostered +
☸ _yathārūpaṃ bhante attabhāvapaṭilābhaṃ sevato akusalā dhammā 
abhivaḍḍhanti kusalā dhammā parihāyanti evarūpo attabhāvapaṭilābho 
na sevitabbo_).

____
But such an assumed individuality as causes spiritually unwholesome factors to 
fade and spiritually wholesome factors to flourish in one who fosters it should 
be fostered.

_Yathārūpañca kho bhante attabhāvapaṭilābhaṃ sevato akusalā dhammā 
parihāyanti. Kusalā dhammā abhivaḍḍhanti evarūpo attabhāvapaṭilābho 
sevitabbo._
____

____
And what assumed individuality causes spiritually unwholesome factors to 
flourish and spiritually wholesome factors to fade in one who fosters it?

_Kathaṃrūpaṃ bhante attabhāvapaṭilābhaṃ sevato akusalā dhammā 
abhivaḍḍhanti kusalā dhammā parihāyanti:_
____

____
If, bhante, an assumed individuality that is hostile is brought into being, 
unconducive to inner perfection, spiritually unwholesome factors flourish and 
spiritually wholesome factors fade in him.

_savyāpajjhaṃ bhante attabhāvapaṭilābhaṃ abhinibbattayato 
apariniṭṭhitabhāvāya akusalā dhammā abhivaḍḍhanti kusalā dhammā 
parihāyanti._
____

____
And what assumed individuality causes spiritually unwholesome factors to fade 
and spiritually wholesome factors to flourish in one who fosters it?

_Kathaṃrūpaṃ bhante attabhāvapaṭilābhaṃ sevato akusalā dhammā 
parihāyanti kusalā dhammā abhivaḍḍhanti._
____

[quote, M.3.52]
____
If, bhante, an assumed individuality that is not hostile is brought into being, 
conducive to inner perfection, spiritually unwholesome factors fade and 
spiritually wholesome factors flourish in him.

_Avyāpajjhaṃ bhante attabhāvapaṭilābhaṃ abhinibbattayato 
pariniṭṭhitabhāvāya akusalā dhammā parihāyanti kusalā dhammā 
abhivaḍḍhanti._
____

.Illustration
====
attabhāvena

state of individuality
====

[quote, M.2.32]
____
Bhante, given that I cannot even recall with their aspects and particulars what 
I have experienced in this present state of individuality, how should I recall 
my manifold past lives?

_iminā attabhāvena paccanubhūtaṃ tampi nappahomi sākāraṃ sauddesaṃ 
anussarituṃ kuto panāhaṃ anekavihitaṃ pubbenivāsaṃ anussarissāmi._
____

.Illustration
====
attabhāve

state of individuality
====

• There are devas whose lifespan is not to be reckoned by counting or 
computation, yet whatever state of individuality they formerly experienced, 
whether amongst beings in the refined material plane of existence or immaterial 
plane of existence, whether amongst beings who are perceptive, unperceptive, or 
neither perceptive nor unperceptive, they recall the details of those past 
lives. +
☸ _Santi bhante devā yesaṃ na sakkā gaṇanāya vā saṅkhānena vā 
āyuṃ saṅkhātuṃ api ca yasmiṃ yasmiṃ attabhāve abhinivutthapubbo 
hoti yadi vā rūpīsu yadi vā arūpīsu yadi vā saññīsu yadi vā 
asaññisu yadi vā nevasaññināsaññisu_. _Iti sākāraṃ sauddesaṃ 
anekavihitaṃ pubbenivāsaṃ anussarati_ (D.3.111).

.Illustration
====
attabhāvapaṭilābho

acquired state of individuality
====

Venerable MahāMoggallāna saw a skeleton flying through the air with vultures, 
crows, and hawks following in hot pursuit, tearing it apart, while it uttered 
cries of pain. He thought:

____
How astounding! How extraordinary!

_acchariyaṃ vata bho abbhutaṃ vata bho_
____

____
that there could be such a being

_evarūpo pi nāma satto bhavissati_
____

____
that there could be such a specter

_evarūpo pi nāma yakkho bhavissati_
____

____
that there could be such an acquired state of individuality

_evarūpo pi nāma attabhāvapaṭilābho bhavissatī ti_
____

The Buddha said that the being (_satto_) used to be a cattle butcher, because 
of which he was first roasted in hell for thousands of years, and was now 
experiencing such an acquired state of individuality (_evarūpaṃ 
attabhāvapaṭilābhaṃ paṭisaṃvedayatī ti_) (S.2.255).

.Illustration
====
attabhāvapaṭilābhesu

acquired state of individuality
====

And how, Elder, is dwelling alone fulfilled in detail? In this regard, Elder:

____
what lies in the past has been abandoned

_yaṃ atītaṃ taṃ pahīnaṃ_
____

____
what lies in the future has been relinquished

_yaṃ anāgataṃ taṃ paṭinissaṭṭhaṃ_
____

____
and fondness and attachment regarding one's presently acquired state of 
individuality have been thoroughly eliminated

_paccuppannesu ca attabhāvapaṭilābhesu chandarāgo suppaṭivinīto_
____

It is in such a way, Elder, that dwelling alone is fulfilled in detail 
(S.2.283).

.Illustration
====
attabhāvapaṭilābhā

acquiring a [particular] state of individuality
====

____
Four ways of acquiring a [particular] state of individuality.

_Cattārome bhikkhave attabhāvapaṭilābhā. Katame cattāro?_
____

____
There is the acquiring of a [particular] state of individuality 
(_attabhāvapaṭilābho_) in which one's own intentionality has effect not 
another person's (_attasañcetanā kamati no parasañcetanā_). Or another 
person's, not one's own. Or both one's own and another person's. Or neither 
one's own striving nor another person's (which is the case for devas of the 
realm neither having nor lacking perception).

_Atthi bhikkhave attabhāvapaṭilābho yasmiṃ attabhāvapaṭilābhe 
attasañcetanā kamati no parasañcetanā... parasañcetanā kamati no 
attasañcetanā... attasañcetanā ca kamati parasañcetanā ca.... neva 
attasañcetanā kamati no parasañcetanā._
____

Venerable Sāriputta said this meant that where there is the acquiring of a 
&#8203;[particular] state of individuality in which one's own intentionality has 
effect, not another person's, there is a passing away of beings from that group 
on account of their own intentionality (_attasañcetanāhetu tesaṃ 
sattānaṃ tamhā kāyā cuti hoti_). And corresponding statements for the 
other groups (A.2.159).

.Illustration
====
attabhāvapaṭilābho

acquiring of states of individuality
====

[quote, A.2.188]
____
"Life in the world [of beings] is of such a nature, and the acquiring of states 
of individuality is of such a nature, that eight worldly conditions whirl 
around the world [of beings], and the world [of beings] whirls around eight 
worldly conditions, namely: acquisition and loss, imprestige and prestige, 
criticism and praise, pleasure and pain.

_tathābhūto kho ayaṃ lokasannivāso tathābhūto attabhāvapaṭilābho 
yathābhūte lokasannivāse yathābhūte attabhāvapaṭilābhe aṭṭha 
lokadhammā lokaṃ anuparivattanti loko ca aṭṭha lokadhamme anuparivattati 
lābho ca alābho ca ayaso ca yaso ca nindā ca pasaṃsā ca sukhañca 
dukkhañcā ti._
____

.Illustration
====
personal disposition

[quote

A.3.411]
====

____
In one yearning for sensuous pleasure a corresponding personal disposition is 
manifested, either meritorious or demeritorious.

_yaṃ kho bhikkhave kāmayamāno tajjaṃ tajjaṃ attabhāvaṃ 
abhinibbatteti puññabhāgiyaṃ vā apuññabhāgiyaṃ vā._
____

.Illustration
====
personal disposition

[quote

A.3.411]
====

____
In one experiencing [a sense impression] a corresponding personal disposition 
is manifested, either meritorious or demeritorious.

_yaṃ bhikkhave vediyamāno tajjaṃ tajjaṃ attabhāvaṃ abhinibbatteti 
puññabhāgiyaṃ vā apuññabhāgiyaṃ vā._
____

.Illustration
====
personal disposition

[quote

A.3.414]
====

____
In one who has acquiesced in uninsightfulness into reality a corresponding 
personal disposition is manifested (_tajjaṃ tajjaṃ attabhāvaṃ 
abhinibbatteti_), either meritorious or demeritorious.

_yaṃ kho bhikkhave avijjāgato tajjaṃ tajjaṃ attabhāvaṃ abhinibbatteti 
puññabhāgiyaṃ vā apuññabhāgiyaṃ vā._
____

