== Attaniya

=== Renderings

- _attaniya_: what is [in reality] mine/his own/ours

- _attaniya_: what belongs to an [absolute] Selfhood

- _attaniya_: what could belong to an [absolute] Selfhood

- _attaniya_: [in reality] mine

- _anattaniya_: not [in reality] yours

=== Introduction

==== Attaniya: DOP vs. PED

Our renderings are close to DOP's 'belonging to', and far from PED's 'nature 
of.'

1. DOP:

- _attaniya_ (adj): belonging to one's self, one's own; belonging to an 
(enduring) self or soul.

- _attaniya_ (noun): what belongs to one's self; what belongs to an (enduring) 
self or soul;

- _anattaniya_ (adj): not belonging to a self; not concerned with oneself.

2. PED:

_• attaniya_ (adj): 'of the nature of soul, soul-like'

- _attaniya_ (noun): 'anything of the nature of the soul'

==== You and yours are interchangeable

The Buddha compared the five aggregates to the sticks and grass of Jeta's Grove 
which people carried off, burned, and made good use of (_jano hareyya vā 
ḍaheyya vā yathāpaccayaṃ vā kareyya_). The Buddha asked the bhikkhus why 
they did not think 'People are carrying us off, burning us, making good use of 
us' (_amhe jano harati vā ḍahati vā yathāpaccayaṃ vā karotī ti_). The 
bhikkhus said this was because with sticks and grass there was 'neither 
ourselves nor what belongs to ourselves' (_na hi no etaṃ bhante attā vā 
attaniyaṃ vā ti_). The Buddha concluded that each of the five aggregates 'is 
not [in reality] yours. Abandon it' (_rūpaṃ... viññāṇaṃ bhikkhave na 
tumhākaṃ. Taṃ pajahatha_).

So, whereas the question concerned people carrying 'us' off, the conclusion was 
that the aggregates are 'not yours.' Thus 'you' and 'yours' are interchangeable 
(M.1.141; S.3.34).

==== 'Could,' not 'would'

Horner's translation of M.1.138 reads:

[quote, Horner, M.1.138]
____
"If, monks, there were a Self, could it be said: 'It belongs to my self'?"

_attani vā bhikkhave sati attaniyaṃ me ti assā ti?._
____

Bodhi's translation reads:

[quote, Bodhi, M.1.138]
____
"Bhikkhus, there being a self, would there be for me what belongs to a self? 
Or, there being what belongs to a self, would there be for me a self?"

_attani vā bhikkhave sati attaniyaṃ me ti assā ti? attaniye vā bhikkhave 
sati attā me ti assā ti?._
____

He justifies this by saying there is a "mutual dependence" between the "twin 
notions 'I' and 'mine'" (Bodhi, MLDB n.264).

But the first of his 'would's is not easily justified, and here we follow 
Horner's 'could.' Our translation therefore reads:

____
-- Bhikkhus, if there were an [absolute] Selfhood, could there be for me what 
belongs to an [absolute] Selfhood?

_attani vā bhikkhave sati attaniyaṃ me ti assā ti?_
____

-- Yes, bhante.

____
-- If there were what belongs to an [absolute] Selfhood, would there be for me 
an [absolute] Selfhood?

_attaniye vā bhikkhave sati attā me ti assā ti?_
____

-- Yes, bhante.

____
-- Bhikkhus, since neither an [absolute] Selfhood, nor what could belong to an 
&#8203;[absolute] Selfhood are apprehended as real and actual,

_attani ca bhikkhave attaniye ca saccato thetato anupalabbhamāne_
____

____
... then this view: 'The world [of phenomena] is my [absolute] Selfhood. Having 
passed on, that I will be -- everlasting, enduring, eternal, of an unchangeable 
nature; I will endure like unto eternity itself':

_yampidaṃ diṭṭhiṭṭhānaṃ so loko so attā so pecca bhavissāmi 
nicco dhuvo sassato avipariṇāmadhammo sassatisamaṃ tatheva ṭhassāmī ti_
____

[quote, M.1.138]
____
... is it not an utterly and completely foolish teaching?

_nanāya bhikkhave kevalo paripūro bāladhammo ti?._
____

=== Illustrations

.Illustration
====
attanīyaṃ

&#8203;[in reality] mine
====

• Among these five grasped aggregates, I do not consider anything as [in 
reality] myself or as [in reality] mine +
_imesu khohaṃ āvuso pañcasupādānakkhandhesu na kiñci attānaṃ vā 
attanīyaṃ vā samanupassāmīti_ (S.3.128).

.Illustration
====
anattaniyaṃ

which is not [in reality] yours
====

You should abandon fondness

• for that which is void of personal qualities +
_Yo kho bhikkhu anattā tatra te chando pahātabbo ti._

• for that which is not [in reality] yours +
_Yaṃ kho bhikkhu anattaniyaṃ tatra te chando pahātabbo ti_ (S.3.77-78).

.Illustration
====
nāttaniyaṃ

&#8203;[in reality] his own
====

____
Suppose, friend, a man needing heartwood, seeking heartwood, wandering in 
search of heartwood, would take a sharp axe and enter a forest. There he would 
see the trunk of a large banana tree, standing erect, young, without a 
fruit-bud core. He would chop it down at the root, sever the crown, and unroll 
the coil. As he unrolls the coil, he would not find even softwood, let alone 
heartwood.

_So tattha pheggumpi nādhigaccheyya kuto sāraṃ._
____

[quote, S.4.167-8]
____
Likewise, a bhikkhu does not consider the six senses to be either [in reality] 
himself or [in reality] his own.

_Evameva kho āvuso bhikkhu chasu phassāyatanesu neva attānaṃ nāttaniyaṃ 
samanupassati._
____

.Illustration
====
attaniyena

what could belong to an [absolute] Selfhood
====

____
'Void [of personal qualities] is the world [of phenomena]': on what grounds, 
bhante, is this said?

_suñño loko suñño loko ti bhante vuccati kittāvatā nu kho bhante suñño 
loko ti vuccatī ti?_
____

[quote, S.4.54]
____
Because, Ānanda, it is void of an [absolute] Selfhood and of what could belong 
to an [absolute] Selfhood, therefore it is said that the world [of phenomena] 
is void [of personal qualities]._

_Yasmā ca kho ānanda suññaṃ attena vā attaniyena vā tasmā suñño loko 
ti vuccati._
____

Comment:

The subject of this reflection is the world [of phenomena] (_loko_), namely the 
eighteen elements of sensation.

