== Attha

=== Renderings

- _attha_: benefit

- _attha_: spiritual well-being

- _attha_: well-being

- _attha_: spirit (='the real meaning of')

- _attha_: meaning

- _attha_: meaning of expressions

- _attha_: context

- _attha_: point

- _attha_: meaning of the teaching

- _attha_: something

- _attha_: matter

- _attha_: what is useful

- _attha_: what is meaningful

- _attha_: purpose

- _atthāya_: for the sake of

- _attha_: the supreme goal

- _attha_: objective

- _attha_: beneficial (adj)

- _attha_: useful (adj)

- _anattha_: harm

- _anattha_: harmful (adj)

- _niratthaṃ_: useless (adj)

- _me attho_: I need (verb)

- _atthaṃ caratī_: benefit (verb)

- _anatthaṃ caratī_: harm (verb)

- _atthavatī_: meaningful

- _atthavasaṃ_: good reason

- _atthavasin_: intent on [the development of] spiritual well-being

- _etamatthaṃ_: this

- _ayampi attho_: this too

=== Introduction

==== 30+ meanings

The many meanings of _attha_ are confounding. In DOP the word entry takes over 
six columns. The PED gives it six major headings, each with alternatives, and 
extracts nearly thirty possible meanings. This Glossary offers a comprehensible 
solution. We render it in over thirty ways.

==== Artha/attha: via Illustrations and notes

_Attha_ has two different roots, _artha_ and _asta_.

1. _Asta/attha_ occurs as a prefix in terms such as _atthaṃ paleti, 
abbhatthaṃ gacchanti_ (=__abhi+atthaṃ gacchanti__) and _atthaṅgamo_, all 
of which can be rendered as 'vanish' or 'vanishing.' But these are covered 
under _Atthaṅgama_, not here.

2. _Artha/attha_ is so complicated that we will explain it primarily by way of 
illustrations and accompanying notes.

==== Attha: the problem of 'goal'

Although 'goal' is nowadays often used for _attha_, it is a newcomer. PED does 
not mention it. DOP mentions it thirteen times but is unsettled about it, 
because it always offers an alternative. For example:

- 'intent on the goal or meaning'

- 'expressing the meaning or goal'

- 'connected with the goal, or with what is beneficial,' and so on.

Norman, too, often uses 'goal,' but it is problematic. For example, consider 
these two passages:

1. 'Quenching is not hard to attain for him who sees the goal, even though it 
is very fine and subtle'
+
****
_Susukhumanipuṇatthadassinā... nibbānaṃ na hi tena dullabhanti_ (Norman, 
Th.v.210).
****
+
But quenching (_nibbāna_) surely is the goal. So here we prefer to say that 
the _attha_ he sees is not 'the goal' but 'the meaning of the teaching.' We 
would therefore say:
+
- _Nibbāna_ is not hard to attain to for one who sees the very fine and subtle 
meaning of the teaching.

2. 'There is no one who sees the subtle goal as well as you [the Buddha] do'
+
****
_Na c'atthi tulyo nipuṇatthadassī_ (Norman, Sn.v.377).
****
+
But this curiously suggests that the Buddha saw _nibbāna_ better than other 
arahants. The solution, again, is that _attha_ means not 'goal' but 'meaning of 
the teaching,' so the passage reads:
+
- There is no one who sees the subtle meaning of the teaching as well as you do.

==== Attho: supreme goal

When _attho_ means goal it always means _nibbāna_, which we call 'supreme 
goal,' and indeed it is often called _uttamatthaṃ_ (Dh.v.386; It.10; 
Sn.v.324) or _paramaṃ atthaṃ_ (Thī.v.93).

==== Atthavasaṃ: 'good reason'

The etymology of _atthavasaṃ_ is perplexing, but the dictionaries call it:

- DOP: 'reason, motive'

- PED: 'reasonableness, reason, consequence, cause.'

Bodhi likewise says 'reason,' for example:

[quote, Bodhi, A.1.98]
____
Bhikkhus, it is for these two reasons that the Tathāgata has established the 
training rules for his disciples.

_dveme bhikkhave atthavase paṭicca tathāgatena sāvakānaṃ sikkhāpadaṃ 
paññattaṃ._
____

Horner prefers 'good purpose':

[quote, Horner, Vin.2.202]
____
For what good purpose should a monk live constantly overcoming gain?

_Kiñca bhikkhave bhikkhu atthavasaṃ paṭicca uppannaṃ lābhaṃ 
abhibhuyya abhibhuyya vihareyya._
____

We call it 'good reason.'

==== Atthavasi: 'intent on [the development of] spiritual well-being'

_Atthavasi_ means:

- DOP: 'pursuing an aim'

- PED: 'bent on (one's) aim or purpose'

Bodhi says 'intent on the good':

[quote, Bodhi, S.3.93]
____
Clansmen intent on the good take up that way of life for a valid reason

_tañca kho evaṃ bhikkhave kulaputtā upenti atthavasikā atthavasaṃ 
paṭicca._
____

Norman says 'pursuing my aim':

[quote, Norman, Th.v.539]
____
Alone, pursuing my aim, I shall quickly enter the woods

_Eko atthavasī khippaṃ pavisissāmi kānanaṃ._
____

We say 'intent on [the development of] spiritual well-being.'

=== Illustrations

.Illustration
====
anatthaṃ

harm; atthaṃ, benefit
====

____
Ten bases of resentment

_Dasa imāni bhikkhave āghātavatthūni:_
____

____
He has harmed, is harming, or will harm me. Thinking thus, one arouses 
resentment.

_anatthamme acarīti... caratīti... carissatīti āghātaṃ bandhati_
____

____
He has harmed, is harming, or will harm someone beloved and dear to me. 
Thinking thus, one arouses resentment.

_Piyassa me manāpassa anatthaṃ acarīti... caratīti... carissatīti 
āghātaṃ bandhati_
____

____
He has benefited, is benefiting, or will benefit someone who is unbeloved or 
loathsome to me. Thinking thus, one arouses resentment.

_Appiyassa me amanāpassa atthaṃ acari... carati... carissatīti āghātaṃ 
bandhati_
____

[quote, A.5.150; D.3.263]
____
And tenthly, one is groundlessly irritated.

_aṭṭhāne ca kuppati._
____

.Illustration
====
anatthāya

harm
====

____
If unarisen unvirtuous, spiritually unwholesome factors arise in me, this would 
lead to my harm':

_anuppannā me pāpakā akusalā dhammā uppajjamānā anatthāya 
saṃvatteyyunti_
____

____
If unvirtuous, spiritually unwholesome factors that have arisen in me are not 
abandoned, this would lead to my harm';

_Uppannā me pāpakā akusalā dhammā appahīyamānā anatthāya 
saṃvatteyyunti_
____

____
If unarisen spiritually wholesome factors do not arise in me, this would lead 
to my harm;

_Anuppannā me kusalā dhammā nūppajjamānā anatthāya saṃvatteyyunti_
____

[quote, S.2.195-6]
____
If spiritually wholesome factors that have arisen in me cease, this would lead 
to my harm.

_Uppannā me kusalā dhammā nirujjhamānā anatthāya saṃvatteyyunti._
____

.Illustration
====
atthaṃ

benefit
====

The Buddha said that being diligent in performing meritorious deeds leads to 
benefits in this lifetime and in the hereafter (_diṭṭhadhammikañceva 
atthaṃ samparāyikañcā ti_), for example, long life, health, beauty, 
heaven, and noble birth. He concluded:

[quote, S.1.86]
____
'The wise person who is diligent [in performing meritorious deeds] secures both 
benefits: benefit in this lifetime, and benefit in the hereafter.

_Appamatto ubho atthe adhigaṇhāti paṇḍito +
Diṭṭhe dhamme ca yo attho yo cattho samparāyiko._
____

Bodhi says 'good' and 'kinds of good': .'.. secures both kinds of good: the 
good visible in this very life... ' (CDB p.180).

.Illustration
====
atthaṃ

meaning
====

[quote, S.1.198]
____
He listens but does not understand [the teaching], he looks but does not see 
&#8203;[the nature of reality]. Though the teaching is being spoken, the fool does not 
understand the meaning.

_Suṇāti na vijānāti āloketi na passati +
Dhammasmiṃ bhaññamānasmiṃ atthaṃ bālo na bujjhati._
____

.Illustration
====
attha

meaning
====

When a teacher explains the Buddha's teaching (_dhammaṃ deseti_) the bhikkhu 
accordingly realises the meaning and significance of the teaching (_dhamme 
atthappaṭisaṃvedī ca hoti dhammapaṭisaṃvedī ca_) (D.3.242).

.Illustration
====
attha

meaning;
====

____
A bhikkhu investigates the meaning of the teachings he has retained in mind._

_dhatānañca dhammānaṃ atthūpaparikkhitā hoti_
____

[quote, A.4.298]
____
Realising their meaning and significance, he practises in accordance with the 
teaching._

_atthamaññāya dhammamaññāya dhammānudhammapaṭipanno ca hoti._
____

.Illustration
====
atthaṃ

what is beneficial
====

[quote, It.84]
____
A greedy person does not know what is beneficial, nor see what is righteous,

_Luddho atthaṃ na jānāti luddho dhammaṃ na passati._
____

.Illustration
====
attha

beneficial
====

[quote, D.3.232]
____
Four bases for winning over a following (_cattāri saṅgahavatthūni_): 
generosity, agreeable speech, beneficial conduct, and impartiality.

_dānaṃ peyyavajjaṃ atthacariyaṃ samānattatā._
____

.Illustration
====
attha

beneficial
====

[quote, D.3.134-5]
____
Concerning things past, future, and present the Perfect One is one who 
speaks... what is beneficial... Therefore he is called the Perfect One.

_atītānāgatapaccuppannesu dhammesu tathāgato... atthavādī .. tasmā 
tathāgato ti vuccati._
____

.Illustration
====
anattho

harmful; attho, beneficial
====

What is harmful (_katamo ca bhikkhave anattho_)? It is the wrong ten factors 
(_micchādiṭṭhi... micchāsamādhi micchāñāṇaṃ micchāvimutti_).

____
This is called harmful._

_Ayaṃ vuccati bhikkhave anattho_
____

____
What is beneficial?

_katamo ca bhikkhave attho_
____

It is the right ten factors (_sammādiṭṭhi... sammāsamādhi 
sammāñāṇaṃ sammāvimutti_).

[quote, A.5.242]
____
This is called beneficial._

_Ayaṃ vuccati bhikkhave attho ti._
____

.Illustration
====
atthavase

good reason; attha, meaning
====

____
Considering three good reasons it is fitting to explain the teaching to others. 
What three?

_Tayo'me bhikkhave atthavase sampassamānena alameva paresaṃ dhammaṃ 
desetuṃ. Katame tayo_
____

[quote, A.1.151]
____
The one who explains the Buddha's teaching, or the one who listens, or both of 
them, realise the meaning and significance of the teachings.

_atthapaṭisaṃvedī ca hoti dhammapaṭisaṃvedī ca._
____

.Illustration
====
atthavasaṃ

good reason
====

____
-- But, great king, considering what good reason do you show such profound 
humility and pay such loving homage to this [wretched human] body of mine?

_Kaṃ pana tvaṃ mahārāja atthavasaṃ sampassamāno imasmiṃ sarīre 
evarūpaṃ paramanipaccākāraṃ karosi mettupahāraṃ upadaṃsesīti?_
____

[quote, A.5.65]
____
-- Out of gratitude and thankfulness I show such profound humility and pay such 
loving homage to the Blessed One.

_Kataññutaṃ kho ahaṃ bhante kataveditaṃ sampassamāno bhagavati 
evarūpaṃ paramanipaccākāraṃ karomi mettupahārāṃ upadaṃsemi._
____

.Illustration
====
atthavasaṃ

good reason
====

'Considering what good reason, Lord of the Devas (_kiṃ pana tvaṃ 
devānaminda atthavasaṃ sampassamāno_), do you announce the attainment of 
such inspiration and joy?'

'Considering six good reasons (_cha kho ahaṃ bhante atthavase 
sampassamāno_), bhante, I announce the attainment of such inspiration and joy.'

The reasons were, briefly, that as a result of this conversation his future 
lives would lead him to great happiness and enlightenment (D.2.285-6).

.Illustration
====
atthavase

good reason
====

[quote, M.1.23]
____
Considering two good reasons, brahman (_dve kho ahaṃ brāhmaṇa atthavase 
sampassamāno_) I frequent secluded abodes in forests and quiet groves: in 
considering a pleasant abiding for myself in this lifetime, and being tenderly 
concerned for future generations.

_dve kho ahaṃ brāhmaṇa atthavase sampassamāno araññe vanapatthāni 
pantāni senāsanāni paṭisevāmi: attano ca diṭṭhadhammasukhavihāraṃ 
sampassamāno pacchimañca janataṃ anukampamāno ti._
____

.Illustration
====
atthavase

good reasons
====

[quote, A.1.98]
____
For two good reasons the Perfect One establishes training rules for his 
disciples. To inspire faith in those without faith; and to increase the faith 
of those with faith.

_Dveme bhikkhave atthavase paṭicca tathāgatena sāvakānaṃ sikkhāpadaṃ 
paññattaṃ. Katame dve appasannānaṃ pasādāya pasannānaṃ 
bhiyyobhāvāya._
____

.Illustration
====
attha

spiritual well-being
====

[quote, M.1.126]
____
Bhikkhus, some might speak to you with speech that is: timely or untimely; true 
or untrue; gentle or harsh; conducive or unconducive to your spiritual 
well-being; spoken with a mind of [unlimited, all-encompassing] goodwill or 
with inner hatred.

_Kālena vā bhikkhave pare vadamānā vadeyyuṃ akālena vā. Bhūtena vā... 
abhūtena vā. Saṇhena vā... pharusena vā. Atthasaṃhitena vā... 
anatthasaṃhitena vā. Mettacittā vā... dosantarā vā._
____

.Illustration
====
anattha

spiritual well-being
====

[quote, M.3.113]
____
I will not talk that kind of talk which is low, vulgar, the way of the common 
man, ignoble, and unconducive to spiritual well-being... that is to say talk of 
kings...

_So yāyaṃ kathā hīnā gammā pothujjanikā anariyā anatthasaṃhitā... 
Seyyathīdaṃ rājakathā... iti vā iti evarūpiṃ kathaṃ na 
kathessāmiti._
____

.Illustration
====
anattha

spiritual well-being
====

[quote, Th.v.105]
____
One who is prudent would not stay in an abode that was unconducive to his 
spiritual well-being.

_Na tvevānatthasaṃhitaṃ vase vāsaṃ vicakkhaṇo ti._
____

.Illustration
====
anattha

spiritual well-being
====

____
There are, headman, these two unenlightening practices which should not be 
undertaken by one who has gone forth [into the ascetic life]:

_Dve'me bhikkhave antā pabbajitena na sevitabbā:_
____

____
the pursuit of sensuous pleasures, which is low, vulgar, the way of the common 
man, ignoble, and unconducive to spiritual well-being

_yo cāyaṃ kāmesu kāmasukhallikānuyogo hīno gammo pothujjaniko anariyo 
anatthasaṃhito_
____

[quote, Vin.1.10; S.4.331]
____
the pursuit of self-mortification, which is painful, ignoble, and unconducive 
to spiritual well-being

_yo cāyaṃ attakilamathānuyogo dukkho anariyo anatthasaṃhito._
____

.Illustration
====
anattha

spiritual well-being
====

[quote, Vin.4.305]
____
An occult art is defined as whatever is non-Buddhistic, and unconducive to 
spiritual well-being

_Tiracchānavijjaṃ nāma yaṃ kiñci bāhirakaṃ anatthasaṃhitaṃ._
____

.Illustration
====
atthavasaṃ

good reason; atthavasikā, intent on [the development of] spiritual well-being
====

[quote, S.3.93; It.89]
____
Bhikkhus, this is the lowest form of livelihood, namely, gathering alms... And 
yet noble young men intent on [the development of their own] spiritual 
well-being take up this way of life for a good reason.

_antamidaṃ bhikkhave jīvikānaṃ yadidaṃ piṇḍolyaṃ... tañca kho 
evaṃ bhikkhave kulaputtā upenti atthavasikā atthavasaṃ paṭicca._
____

.Illustration
====
atthavasikena

intent on [the development of] spiritual well-being
====

The Buddha said that if one was offered to be struck by three hundred spears a 
day for one hundred years, and told that one would afterwards penetrate the 
four noble truths, it would be fitting for a noble young man intent on [the 
development of his own] spiritual well-being to accept the offer 
(_atthavasikena bhikkhave kulaputtena alaṃ upagantuṃ_) because the round of 
birth and death is long-lasting beyond conception; a first point is not to be 
discerned of [a receiving of] blows by knives, swords, arrows, and axes 
(S.5.440-1).

.Illustration
====
atthāya

spiritual well-being
====

When the mental image of a skeleton (_aṭṭhikasaññā_) is developed and 
cultivated (_bhāvitā bahulīkatā_).

• it is of great fruit and benefit +
_mahapphalā hoti mahānisaṃsā_

• it leads to [one's own] great spiritual well-being +
_mahato atthāya saṃvattati_ (S.5.129).

.Illustration
====
attha

spiritual well-being
====

[quote, S.1.140]
____
Therefore one desiring [the development of] spiritual well-being, aspiring for 
inward greatness, should revere the true teaching, remembering the Buddhas' 
training system.

_Tasmā hi atthakāmena mahattamabhikaṅkhatā +
Saddhammo garu kātabbo saraṃ buddhānaṃ sāsanaṃ._
____

.Illustration
====
attha

spiritual well-being
====

Then the deva inhabiting that woodland grove, being tenderly concerned for that 
bhikkhu, desiring his spiritual well-being (_anukampikā atthakāmā_) desiring 
to stir up in him an earnest attitude [to the practice] (_saṃvejetukāmā_), 
approached him and addressed him in verses (S.1.203).

.Illustration
====
atthaṃ

well-being
====

[quote, S.5.354]
____
If someone destroyed my well-being by lying to me it would not be agreeable and 
pleasing to me.

_yo kho me musāvādena atthaṃ bhañjeyya na me taṃ assa piyaṃ 
manāpaṃ._
____

.Illustration
====
attha

well-being
====

My parents were killed by a king. But if I were to deprive the king of life, 
those who desired the king's well-being (_ye devassa atthakāmā_) would 
deprive me of life, and those who desired my well-being (_ye me atthakāmā_) 
would deprive these of life (Vin.1.347).

.Illustration
====
atthaṃ

spirit (=real meaning)
====

• Those teachings which are excellent in the beginning, the middle, and the 
end, whose spirit and letter proclaim the utterly complete and pure religious 
life: teachings like this are much heard by him. +
_ye te dhammā ādikalyāṇā majjhekalyāṇā pariyosānakalyāṇā 
sātthaṃ savyañjanaṃ kevalaparipuṇṇaṃ parisuddhaṃ brahmacariyaṃ 
abhivadanti tathārūpāssa dhammā bahussutā honti_ (Vin.2.96).

.Illustration
====
attha

spirit (=real meaning)
====

If the community of bhikkhus, not having investigated that case, not having got 
to the root of it, achieves unanimity, that unanimity is unrighteous, Upāli 
(_adhammikā sā upāli saṅghasāmaggī ti_). This is called unanimity that 
has arrived at the letter but not the spirit (_atthāpetā vyañjanupetā_).

If the community of bhikkhus, having investigated the case, having got to the 
root of it, achieves unanimity in the community of bhikkhus, that unanimity is 
righteous (_dhammikā sā upāli saṅghasāmaggī ti_). This is called 
unanimity that has arrived both at the letter and the spirit (_atthupetā ca 
vyañjanupetā ca_) (Vin.1.358).

.Illustration
====
atthavatī

meaningful
====

[quote, S.1.30-31]
____
Cūḷakokanadā, Pajjunna's daughter, spoke these meaningful verses

_gāthā cimā atthavatī abhāsi._
____

Comment:

The verses say one should avoid unvirtuous conduct (_pāpaṃ na kayirā_), 
abandon sensuous pleasures (_kāme pahāya_), and be mindful and fully 
conscious (_satimā sampajāno_). Bodhi calls them 'verses full of meaning.'

.Illustration
====
atthaṃ

meaning = suttavibhaṅgo
====

If the bhikkhu knows neither the rule nor the rule analysis (_neva suttaṃ 
āgataṃ hoti no suttavibhaṅgo_), not knowing the meaning (of the rule) 
(_atthaṃ asallakkhento_), he may conceal the meaning under the wording 
(_vyañjanacchāyāya atthaṃ paṭibāhati_) (Vin.2.97).

Comment:

The bhikkhu conceals the meaning (_atthaṃ_) under the wording because he is 
ignorant of the rule analysis (_suttavibhaṅgo_). Thus 'rule analysis' 
(_suttavibhaṅgo_) equals 'the meaning of the rule' (_atthaṃ_).

.Illustration
====
atthassa

meaning
====

Venerable Visākha Pañcāliputta was instructing the bhikkhus in the assembly 
hall with an explanation of the teaching, using speech that was polished, well 
enunciated, articulate, making the meaning clear (_atthassa viññāpaniyā_) 
(S.2.280).

.Illustration
====
atthaṃ

meaning
====

• Venerable Mahākaccāna is capable of explaining the meaning in detail of 
the brief synopsis recited by the Blessed One, where the meaning was not 
explained in detail. +
_Pahoti cāyasmā mahākaccāno imassa bhagavatā saṅkhittena uddesassa 
uddiṭṭhassa vitthārena atthaṃ avibhattassa vitthārena atthaṃ 
vibhajituṃ_ (M.3.195).

.Illustration
====
atthaṃ

meaning
====

____
Hearing the teaching, he bears it in mind.

_sutvā dhammaṃ dhāreti_
____

____
Bearing it in mind, he examines the meaning [of what he has memorised].

_atthaṃ upaparikkhati_
____

[quote, M.1.480]
____
Doing so, the teaching receives his considered approval.

_dhammā nijjhānaṃ khamanti._
____

.Illustration
====
attho

meaning
====

[quote, S.5.219]
____
It would be good if the Blessed One would explain the meaning of this 
statement. Having heard it from him, the bhikkhus will remember it.

_Sādhu vata bhante bhagavantaṃyeva paṭibhātu etassa bhāsitassa attho 
bhagavato sutvā bhikkhū dhāressantī ti._
____

.Illustration
====
attha

meaning of expressions
====

[quote, A.4.113]
____
How is a bhikkhu one who knows the meaning of expressions? In this regard a 
bhikkhu knows the meaning of this and that expressions thus: 'This is the 
meaning of this expression.

_Atthaññū ca kathaṃ hoti. Idha bhikkhave bhikkhu tassa tasseva bhāsitassa 
atthaṃ jānāti ayaṃ imassa bhāsitassa attho._
____

.Illustration
====
attha

meaning of expressions
====

[quote, Sn.v.382]
____
Whatever contentious brahmans there are, and even elderly brahmans, and others, 
too, who thought they were [good] arguers, all become obliged to you for 
&#8203;[explaining] the meaning of expressions.

_Ye kecime brāhmaṇā vādasīlā vuddhā cā pi brāhmaṇā santi keci +
Sabbe tayi atthabaddhā bhavanti ye cā pi aññe vādino maññamānā._
____

.Illustration
====
attha

meaning of the teaching
====

[quote, Sn.v.177; S.1.33]
____
One who sees the subtle meaning of the teaching

_nipuṇatthadassiṃ._
____

.Illustration
====
attha

meaning of the teaching
====

[quote, Th.v.210]
____
For one who sees the very fine and subtle meaning of the teaching... the 
Untroubled is not hard to attain to.

_Susukhumanipuṇatthadassinā... Nibbānaṃ na hi tena dullabhanti._
____

.Illustration
====
attha

meaning of the teaching
====

[quote, Sn.v.377]
____
There is no one who sees the subtle meaning of the teaching as well as you do

_na c'atthi tulyo nipuṇatthadassī._
____

.Illustration
====
atthe

context
====

• A bhikkhu who was ordained by a complete assembly of bhikkhus, and by a 
valid and legitimate act involving a motion and three invitations, such a 
person is what is meant in this context by the word 'bhikkhu'" +
_tatrayvāyaṃ bhikkhu samaggena saṅghena ñatticatutthena kammena akuppena 
ṭhānārahena upasampanno ayaṃ imasmiṃ atthe adhippeto bhikkhū ti_ 
(Vin.3.24).

Horner: this one is a monk as understood in this meaning. BD.1.42).

.Illustration
====
atthassa

point
====

____
And this is another way of explaining in brief that same point

_ayampi kho sāriputta pariyāyo etasseva atthassa saṅkhittena 
veyyākaraṇāya_
____

____
I am not unsure about the perceptually obscuring states spoken of by the 
Ascetic.

_ye āsavā samaṇena vuttā tesvāhaṃ na kaṅkhāmi_
____

[quote, S.2.54]
____
I do not doubt they have been abandoned by me.

_te me pahīṇāti na vicikicchāmī ti._
____

.Illustration
====
atthassa

point
====

[quote, S.2.53]
____
This is another method of explaining in brief that same point: 'Whatever is 
experienced is included within dukkha.'

_ayampi kho sāriputta pariyāyo etasseva atthassa saṅkhittena 
veyyākaraṇāya yaṃ kiñci vedayitaṃ taṃ dukkhasmin ti._
____

.Illustration
====
atthassa

something; attho, meaning
====

____
I devised this simile for the sake of explaining something

_upamā kho me ayaṃ bhikkhave katā atthassa viññāpanāya_
____

____
This is its meaning

_ayañcevettha attho_
____

____
The 'great low-lying marsh' is a term for sensuous pleasure

_kāmānametaṃ adhivacanaṃ_
____

____
The 'large herd of deer' is a term for beings

_sattānametaṃ adhivacanaṃ_
____

[quote, M.1.118]
____
The 'safe path' is a term for the noble eightfold path

_ariyassetaṃ aṭṭhaṅgikassa maggassa adhivacanaṃ._
____

.Illustration
====
attho

matter
====

[quote, A.3.359]
____
Thus do noble young men declare their [attainment of] arahantship: the matter 
is spoken of without any reference to themselves

_attho ca vutto attā ca anupanīto._
____

.Illustration
====
atthaṃ

matter
====

When Nigaṇṭho Nātaputto died at Pāvā, there was much trouble amongst his 
disciples. Venerable Ānanda and the sāmaṇera Cunda approached the Blessed 
One and told him about this matter (_etamatthaṃ ārocessāmā ti_) (D.3.118).

.Illustration
====
atthena attho

point by point; atthaṃ, matter
====

____
It is astounding and extraordinary, friend, that [the explanations of the] 
Teacher and disciple agree and correspond point by point, and phrase by phrase, 
and do not disagree as regards the highest state.

_Acchariyaṃ āvuso abbhutaṃ āvuso yatra hi nāma satthu ca sāvakassa ca 
atthena attho vyañjanena vyañjanaṃ saṃsaṃdissati samessati na 
viggahissati yadidaṃ aggapadasmiṃ._
____

____
Just now, friend, I approached the Blessed One and asked him about this matter.

_Idānāhaṃ āvuso bhagavantaṃ upasaṅkamitvā etamatthaṃ apucchiṃ._
____

[quote, A.5.320]
____
The Blessed One explained the matter to me in the very same terms and phrases 
that Venerable Sāriputta used.

_Bhagavāpi me eteheva padehi etehi vyañjanehi etamatthaṃ vyākāsi 
seyyathā pi āyasmā sāriputto._
____

Comment:

_Atthena attho vyañjanena vyañjanaṃ_ corresponds to _eteheva padehi etehi 
vyañjanehi ._

.Illustration
====
atthaṃ

matter; attha, spiritual well-being
====

____
Having heard the well-spoken explanation, the utterance connected with what is 
righteous and with spiritual well-being

_Sutvā subhāsitaṃ vācaṃ dhammatthasaṃhitaṃ padaṃ_
____

[quote, Th.v.347]
____
I properly reflected on the truth and reality of the matter

_Tathaṃ yāthāvakaṃ atthaṃ yoniso paccavekkhisaṃ._
____

.Illustration
====
etamatthaṃ

this; ayampi attho, this too
====

• I heard this was said by the Blessed One, the Arahant: +
_Vuttaṃ h'etaṃ bhagavatā vuttamarahatā ti me sutaṃ_

• Abandon one thing, bhikkhus, and I guarantee you non-returnership. Which 
one thing? +
_Ekadhammaṃ bhikkhave pajahatha ahaṃ vo pāṭibhogo anāgāmitāya. 
Katamaṃ ekadhammaṃ?_

• Abandon one thing, bhikkhus, greed, and I guarantee you non-returnership. +
_Lobhaṃ bhikkhave ekadhammaṃ pajahatha ahaṃ vo pāṭibhogo 
anāgāmitāyā ti._

• This is what the Blessed One said, and in connection with which he added: +
_Etamatthaṃ bhagavā avoca tatthetaṃ iti vuccati_

• The greed on account of which greedy beings are reborn in the plane of 
misery, +
_Yena lobhena luddhāse sattā gacchanti duggatiṃ_

• through the complete understanding of that greed, those with insight 
abandon it. +
_Taṃ lobhaṃ sammadaññāya pajahanti vipassino_

• Having done so they never return to this [low] plane of existence again. +
_Pahāya na punāyanti imaṃ lokaṃ kudācanan ti_

• This, too, was what the Blessed One said, so I heard. +
_Ayampi attho vutto bhagavatā iti me sutan ti_ (It.1).

Comment:

With verbs of saying, asking, etc _attho_ often means simply 'this' or 'that,' 
says DOP. Here the opening statement is 'I heard this was said by the Blessed 
One' (_vuttaṃ h'etaṃ bhagavatā... me sutaṃ_). _Etamatthaṃ_ and _ayampi 
attho_ correspond to it.

.Illustration
====
atthaṃ

matter; atthaṃ, atthena, what is useful; me attho, need (+ instrumental case)
====

&#8203;[Venerable Assaji:]

____
'I am not able to explain the teaching in detail, but I can tell you the matter 
in brief.'

_na tāhaṃ sakkomi vitthārena dhammaṃ desetuṃ. Api ca te saṅkhittena 
atthaṃ vakkhāmī ti_
____

&#8203;[The ascetic Sāriputta:]

____
'So be it, friend, tell me little or tell me much,

_hotu āvuso appaṃ vā bahuṃ vā bhāsassu_
____

____
but just tell me what is useful;

_atthaṃyeva me brūhi_
____

____
I need only what is useful.

_attheneva me attho_
____

[quote, Vin.1.41]
____
Why should you make a great elaboration?'

_kiṃ kāhasi vyañjanaṃ bahun ti._
____

.Illustration
====
attho hoti

need (with instrumental case)
====

[quote, Vin.4.100]
____
Once, bhikkhus became sick and needed (there was a need for) medicine.

_Tena kho pana samayena bhikkhu gilānā honti attho ca hoti bhesajjehi._
____

.Illustration
====
attho

need
====

[quote, Th.v.407]
____
'Should I resort to the knife, or [not]? What need have I of life? '

_Satthaṃ vā āharissāmi ko attho jīvitena me._
____

.Illustration
====
atthaṃ

purpose
====

When gold is refined it becomes malleable, wieldy and radiant. Whatever 
ornament one wishes to make from it, it would serve the purpose (_tañcassa 
atthaṃ anubhoti_) (A.3.16; S.5.92; A.1.254-7; M.3.243).

.Illustration
====
atthāya

for the sake of
====

While a bhikkhu is contemplating the nature of the body, there may arise in him 
either bodily anguish, or mental sluggishness, or his mind is distracted 
outwardly. He should then direct his mind towards some faith inspiring 
meditation object (_kismiñcideva pasādaniye nimitte cittaṃ 
paṇidahitabbaṃ_). When he does so, his mind becomes collected (_cittaṃ 
samādhiyati_). He should then reflect:

[quote, S.5.156]
____
The [purpose] for the sake of which I directed my mind has been achieved.

_yassa kho'haṃ atthāya cittaṃ paṇidahiṃ so me attho abhinipphanno._
____

.Illustration
====
atthāya

for the sake of
====

The teaching explained by me is comparable to a raft:

[quote, M.1.260]
____
Being for the sake of crossing [the flood of suffering], not for the sake of 
clinging to it.

_nittharaṇatthāya no gahaṇatthāyāti._
____

.Illustration
====
atthaṃ

for, for the sake of
====

In this regard a bhikkhu, properly reflecting, uses the robe simply to ward off 
cold and heat, and to ward off the touch of horseflies, mosquitoes, wind, sun, 
and snakes:

____
simply for covering his loins.

_yāvadeva hirikopīnapaṭicchādanatthaṃ._
____

Properly reflecting, he uses the abode simply to ward off cold and heat, and to 
ward off the touch of horseflies, mosquitoes, wind, sun, and snakes; simply to 
dispel the oppressiveness of the weather and:

[quote, M.1.10]
____
for the sake of enjoying solitary retreat.

_paṭisallānārāmatthaṃ._
____

.Illustration
====
attho

for (the sake of)
====

____
What is a mirror for?

_kimatthiyo ādāso ti._
____

[quote, M.1.416]
____
For (the sake of) reflection, bhante._

_Paccavekkhanattho bhante ti._
____

COMMENT

_Atthiya_ (adj.) [= _atthika_] having a purpose or end. _Kimatthiyo_ for what 
purpose? (PED).

.Illustration
====
attho

for the sake of
====

____
-- For what purpose, bhante, is non-attachment [to originated phenomena]?

_Virāgo pana bhante kimatthiyo ti?_
____

____
-- Non-attachment is for the sake of liberation [from perceptually obscuring 
states].

_Virāgo kho rādha vimuttattho_
____

____
-- For what purpose, bhante, is liberation [from perceptually obscuring states]?

_Vimutti pana bhante kimatthiyā ti?_
____

• -- Liberation [from perceptually obscuring states] is for the sake of 
&#8203;[realising] the Untroubled. +
_Vimutti kho rādha nibbānatthā_ (S.3.189).

.Illustration
====
atthaṃ

what is meaningful
====

&#8203;[Hemavata:]

____
'Does he not speak falsehood? Does he not have rough speech? Does he not speak 
what is untrue? Does he not speak what is frivolous?'

_Kacci musā na bhaṇati kacci na khīṇavyappatho +
Kacci vebhūtiyaṃ nāha kacci samphaṃ na bhāsati_
____

&#8203;[Sātāgira:]

[quote, Sn.v.158-9]
____
'He does not speak falsehood, nor does he have rough speech, and neither does 
he speak what is untrue. He is a wise person: he speaks what is meaningful.'

_Musā ca so na bhaṇati atho na khīṇavyappatho +
Atho vebhūtiyaṃ nāha mantā atthaṃ so bhāsati._
____

Comment:

_Atthaṃ_: 'what is meaningful.' Here, the opposite of 'what is frivolous' 
(_samphaṃ_).

.Illustration
====
atthaṃ

what is useful
====

Some unvirtuous bhikkhus are dependent on kings or kings' ministers, thinking 
that if anyone accuses them of misconduct, these people will say what is useful 
in their defence (_rājāno vā rāja mahāmattā vā pariyodhāya atthaṃ 
bhaṇissantī ti_) (A.1.153-5).

.Illustration
====
atthāya

useful
====

[quote, S.1.31]
____
When one's house is in flames, the vessel taken out is the one that is useful, 
not the one left burnt inside.

_Taṃ tassa hoti atthāya no ca yaṃ tattha ḍayhati._
____

.Illustration
====
niratthaṃ

useless
====

Not long, indeed, till it will rest, this [wretched human] body here, beneath 
the clod, discarded, void of mental consciousness:

[quote, Dh.v.41]
____
Like a useless block of wood.

_niratthaṃ va kaliṅgaraṃ._
____

.Illustration
====
anattha

useless
====

[quote, S.1.103]
____
It is good indeed that I am freed from that useless, unpleasant, 
self-mortifying practice.

_Sādhu mutto vatamhi tāya anatthasaṃhitāya dukkarakārikāya._
____

.Illustration
====
atthaṃ

supreme goal
====

[quote, Dh.v.386]
____
One who is meditative, one who sits [alone in the woods] and is spiritually 
undefiled, who has done what needed to be done, who is free of perceptually 
obscuring states, who has attained the supreme goal, he is what I call a 
Brahman.

_Jhāyiṃ virajamāsīnaṃ katakiccaṃ anāsavaṃ +
Uttamatthaṃ anuppattaṃ tamahaṃ brūmi brāhmaṇaṃ._
____

.Illustration
====
attho

supreme goal
====

[quote, D.1.230]
____
Gone forth from the household life into the ascetic life, but has not attained 
the supreme goal of asceticism

_agārasmā anagāriyaṃ pabbajito hoti svāssa sāmaññattho ananuppatto 
hoti._
____

.Illustration
====
atthaṃ

supreme goal
====

____
But following a lowly fool who has not attained the supreme goal and who is 
full of envy,

_Khuddañca bālaṃ upasevamāno anāgatatthañca usūyakañca_
____

[quote, Sn.v.318]
____
Having failed to understand the teaching clearly in this world, one reaches 
death, having not overcome one's unsureness [about the significance of the 
teaching].

_Idheva dhammaṃ avibhāvayitvā avitiṇṇakaṅkho maraṇaṃ upeti._
____

.Illustration
====
atthassa

objective
====

[quote, S.1.225]
____
A man should make an effort until his objective has been achieved.

_Vāyametheva puriso yāva atthassa nipphadā._
____

.Illustration
====
atthā

objective
====

[quote, M.1.141-2]
____
Those who are arahants with perceptually obscuring states destroyed, who have 
fulfilled [the religious life], done what had to be done, laid down the burden, 
achieved their objective.

_ye te bhikkhū arahanto khīṇāsavā vusitavanto katakaraṇīyā 
ohitabhārā anuppattasadatthā._
____

