== Attā, Anattā

=== Renderings

- _attā_ (noun): ego

- _attā_ (noun): aspect of yourself

- _attā_ (noun): [absolute] Selfhood

- _attā_ (adjective): endowed with personal qualities

- _attā_ (pronoun): myself; yourself; himself; themselves; oneself

- _attā_ (stressed pronoun): he himself; you yourself

- _anattā_ (noun): the voidness of personal qualities [in things]

- _anattā_ (adjective): void of personal qualities

=== Introduction

==== Explaining unconditionality: Chachakka Sutta

The _Chachakka Sutta_ (M.3.282) says that the [co-conditional] arising and 
disappearance of the six senses are discernable (_uppādo pi vayo pi 
paññāyati_), and that he for whom [co-conditional] arising and disappearance 
is discernable in something they regard as endowed with personal qualities 
would be forced to the conclusion that 'My [absolute] Selfhood arises and 
disappears' (_attā me uppajjati ca veti cā ti_). Thus the six senses are void 
of personal qualities.

The arguments used in this and the two following paragraphs are only meaningful 
if Selfhood is understood to be unconditional. Though _attā_ is commonly 
rendered as 'Self' or 'soul' these renderings obscure the important 
connotations of _anattā_: ungovernability, unlastingness and inherent 
unsatisfactoriness. Hence our term '[absolute] Selfhood.'

==== Explaining unconditionality: Pañcavaggiya Sutta

The _Pañcavaggiya Sutta_ (S.3.66-7) says that if the five aggregates were 
endowed with personal qualities they would not lead to affliction (_ābādhāya 
saṃvatteyya_) and one could command them: 'Be thus! Be not thus!' One could 
have them unconditionally according to one's will. The Buddha compared this to 
a claim a king might make concerning 'his own realm' (_sakasmiṃ vijite_) 
where he has the power to punish criminals as he wishes, but outside his realm 
he has no such power (M.1.230). Likewise the five aggregates are outside one's 
realm. They are ours conditionally not unconditionally. They cannot be regarded 
as endowed with personal qualities because they do not accord unconditionally 
with one's will.

==== Explaining unconditionality: Udāyī Sutta

In the _Udāyī Sutta_, Venerable Ānanda explained that _viññāṇa_ cannot 
be regarded as endowed with personal qualities because it arises dependent on 
conditions. If the indispensible and necessary conditions for _viññāṇa_ 
were to cease completely and totally without remainder (_so ca hetu so ca 
paccayo sabbena sabbaṃ sabbathā sabbaṃ aparisesaṃ nirujjheyya_) 
_viññāṇa_ would not be discerned. Thus _viññāṇa_ is conditional, not 
unconditional. Therefore it is void of personal qualities (_viññāṇaṃ 
anattā ti_ S.4.166).

==== Anattā (adjective): 'void of personal qualities'

As an adjective, _attā_ is rendered in this Glossary as 'endowed with personal 
qualities,' and _anattā_ as 'void of personal qualities' because it is part of 
the argument _yadanattā taṃ n'etaṃ mama n'eso'hamasmi na me so attā ti_ 
(S.4.1). This argument shows that _yadanattā_ has a meaning broad enough to 
cover _n'etaṃ mama n'eso'hamasmi na me so attā ti._ It covers all terms: 
"not [in reality] mine," "not [in reality] what I am," "not my [absolute] 
Selfhood." Thus we say: What is void of personal qualities should be seen 
according to reality with perfect penetrative discernment as "not [in reality] 
mine," "not [in reality] what I am," "not my [absolute] Selfhood."

==== Parenthesis: [in reality]

The parenthesis '[in reality]' is justified because of _attā_'s link to 
_yathābhūtaṃ_:

[quote, S.4.1]
____
What is void of personal qualities should be seen according to reality with 
perfect penetrative discernment as "not [in reality] mine," "not [in reality] 
what I am," "not my [absolute] Selfhood"

_yadanattā taṃ n'etaṃ mama n'eso'hamasmi na me so attā ti evametaṃ 
yathābhūtaṃ sammappaññāya daṭṭhabbaṃ._
____

Another example is this:

[quote, S.3.114]
____
He does not discern bodily form which is void of personal qualities according 
to reality, thus: 'Bodily form is void of personal qualities.'

_anattaṃ rūpaṃ anattā rūpan ti yathābhūtaṃ nappajānāti._
____

==== Inevitable link between the adjective and noun

The scriptures confirm the inevitable link between the adjective and noun:

1. For example, if something is _anattā_ (void of personal qualities, 
adjective), it should be seen as not my _attā_ ([absolute] Selfhood, noun: 
_yadanattā taṃ n'etaṃ mama n'eso'hamasmi na me so attā ti evametaṃ 
yathābhūtaṃ sammappaññāya daṭṭhabbaṃ_ S.4.1).

2. To say that the senses are _attā_ (endowed with personal qualities, 
adjective) is untenable because their [co-conditional] arising and 
disappearance are discernable and one would be forced to the conclusion that 
'My _attā_ ([absolute] Selfhood, noun) arises and disappears (M.3.282-4).

==== Distinguishing adjectives and nouns

It is sometimes difficult to distinguish adjectives and nouns in the 
scriptures; indeed, so difficult that DOP fails to recognise _attā_ as an 
adjective at all. This is surprising. Not only does its predecessor, the PED, 
recognise the adjective, but also the DOP itself (under _attan_) translates the 
term _attatthaṃ_ (S.2.29) as 'one's own interest or profit' where 'one's own' 
is adjectival. Bodhi also recognises that _attā_ in _attatthaṃ_ is an 
adjective and translates it 'your own good.' However, at M.3.282 both he and 
Horner do not recognise the adjective in the sentence _cakkhuṃ attā ti yo 
vadeyya taṃ na upapajjati_. This would be naturally rendered as 'endowed with 
personal qualities' but Bodhi and Horner render it as 'self':

- Bodhi: If anyone says, 'The eye is self,' that is not tenable.

- Horner: If anyone should say, 'Eye is self,' that is not fitting.

Although Ñāṇamoli agrees that _attā_ can be adjectival (in _Anattā 
According to the Theravāda_) in the section on Derivation and Usage he 
overlooks the adjective form, and in his translations in the same essay he 
consistently calls it 'not self.' For example, he renders _rūpaṃ anattā_ as 
'materiality is not self' where we would say 'is void of personal qualities.' 
Therefore, it seems he considered the adjective form to be negligible.

==== Attā: paradoxical useage

Occasionally the Buddha used _attā_ in a paradoxical way.

____
He used it to indicate Ultimate Reality, one's [absolute] Selfhood, but in 
conversation with young brahmans for whom this expression would be appropriate 
and meaningful (Vin.1.23): 'What do you think, young men: which is better for 
you: that you seek for a woman, or that you seek for your [absolute] Selfhood?

_katamaṃ nu kho tumhākaṃ varaṃ yaṃ vā tumhe itthiṃ gaveseyyātha 
yaṃ vā attānaṃ gaveseyyāthā ti_
____

- He used it as a manner of speech, saying that bhikkhus should abide 
spiritually self-reliant, and as refuges unto themselves (_attadīpo viharati 
attasaraṇo_ D.2.100), which he explained meant practising 
_satipaṭṭhānā_ and said that this was equivalent to abiding with the 
teaching as one's island and refuge (_dhammadīpo dhammasaraṇo_).

- He said 'a bhikkhu does not let his unmastered self be mastered by suffering 
(_bhikkhu na heva anaddhabhūtaṃ attānaṃ dukkhena addhabhāveti_ M.2.223). 
It is consonant with the scriptures to take the advice as meaning that 'the 
mind is intrinsically radiant: it is defiled by extrinsic defilements 
(_pabhassaramidaṃ bhikkhave cittaṃ tañca kho āgantukehi upakkilesehi 
upakkiliṭṭhanti_ (A.1.10). 'Unmastered self' is a manner of speech.

==== Suffix -atta: redundant

The suffix -_atta_ is usually redundant. For example, in _pahitatto_ 
('resolutely applied') and _sukhitattā_ ('happy') in these passages:

1. Enthusiastically applying himself [to the teaching], he scrutinises [it].
+
****
_ussahitvā tuleti_
****

____
... Having scrutinised [it], he strives [to practise it].

_tulayitvā padahati_
____

[quote, M.1.480]
____
... Being resolutely applied [to the practice] he realises with his very being 
the supreme truth, and he sees [the nature of reality] having penetrated it 
with discernment.

_pahitatto samāno kāyena ceva paramaṃ saccaṃ sacchikaroti paññāya ca 
naṃ paṭivijjha passati._
____

Comment: Here _padahati_ is directly linked to its suffixed past participle, 
where the suffix is clearly shown to be redundant.

2. May they be happy.
+
****
_bhavantu sukhitattā_ (Sn.v.145).
****

Comment: PED (sv _Sukhita_) likewise calls _sukhitattā_ 'happy, easy.' Norman 
says 'happy-minded.'

_Atta's_ role as a suffix is not noted in the Pāli grammar books, nor in the 
dictionaries sv _Atta_, though Duroiselle says _pahitatto_ means 'resolute, 
whose mind is bent upon, literally directed towards,' and _ṭhitatto_ means 
'of firm mind' (PGPL, para 555). Neither DOP nor PED mention 'mind' as a 
meaning of _atta_, but for _anavositatta_ DOP says 'whose mind has no firm 
convictions,' and for _susamāhitatto_ (sv _su_) PED says 'of steadfast mind.' 
PED adds 'will,' sv _Pahita,_ saying _pahitatta_ means 'of resolute will'. PED 
also sometimes considers -_atta_ redundant, for example in rendering 
_ṭhitatto_ as 'self-controlled, composed, steadfast,' and _sukhitatta_ as 
noted above. But if -_atta_ means 'mind', then it is still redundant. What, 
after all, is the difference between 'happy' and 'happy-minded'?

PED's collection of -_atta_ words is this:

_ubbilāvitatta_: rejoicing, exultancy, elation of mind

_katatta_: self-possessed, disciplined

_khematta_: one who is at peace

_gatatta_: self-perfected, perfect

_ṭhitatto_: self-controlled, composed, steadfast

_pahitatta_: of resolute will

_yatatta_: selfcontrolled, one whose heart is kept down

_rakkhitatta_: one who guards his character

_vadhatta_: self-destruction

_vimuttatta_: having an emancipated self

_saṃyatattaṃ_: having one's self restrained, self-controlled

_saṃvutatta_: self-controlled

_sukhitatta_: happy, easy

_susamāhitatto_: of steadfast mind

==== Parenthesising anattā

_Anattā_ usually has an object associated with it:

[quote, A.4.14]
____
He abides contemplating the voidness of personal qualities in all things.

_sabbadhammesu anattānupassī viharati._
____

[quote, A.5.109]
____
He abides contemplating the voidness of personal qualities in the six senses 
and their objects.

_imesu chasu ajjhattikabāhiresu āyatanesu anattānupassī viharati._
____

[quote, A.3.444]
____
the perception of the voidness of personal qualities in all originated 
phenomena.

_sabbasaṅkhāresu anattasaññaṃ._
____

Where _anattā_ occurs without an object, the context sometimes shows what 
should be parenthesised, sometimes not:

• And what, Ānanda, is the perception of the voidness of personal qualities 
&#8203;[in the six senses and their objects]. In this regard, Ānanda, a bhikkhu... 
reflects that the six senses and their objects are void of personal qualities. +
☸ _katamācānanda anattasaññā_? _Idhānanda bhikkhu_... _iti 
paṭisaṃcikkhati cakkhuṃ anattā rūpā anattā... mano anattā dhammā 
anattā ti_) (A.5.109).

[quote, Ud.37]
____
In one who perceives the voidness of personal qualities [in all things], 
self-centredness is uprooted. He realises the Untroubled in this very lifetime

_anattasaññi asmimānasamugghātaṃ pāpuṇāti diṭṭheva dhamme 
nibbānaṃ ti._
____

=== Illustrations

.Illustration
====
atto

ego
====

[quote, Sn.v.456]
____
Clad in robes, I live the religious life without a home, with shaven head, with 
ego completely extinguished.

_saṅghāṭivāsī agaho carāmi nivuttakeso abhinibbutatto._
____

.Illustration
====
attano

ego
====

[quote, Sn.v.1062]
____
Having heard my word, train yourself in the quenching of the ego.

_Ito sutvāna nigghosaṃ sikkhe nibbānamattano._
____

.Illustration
====
atto

ego
====

[quote, Sn.v.284]
____
The seers of old had egos restrained.

_Isayo pubbakā āsuṃ saṃyatattā._
____

.Illustration
====
attā

ego
====

[quote, Sn.v.490]
____
Those who roam the world who are truly liberated [from individual existence], 
liberated from the perception of existence, spiritually perfected, with egos 
restrained.

_Ye ve asattā vicaranti loke akiñcanā kevalino yatattā._
____

.Illustration
====
attā

ego
====

[quote, Sn.v.1119]
____
Walk on almsround through the streets with ego well-restrained.

_Susaṃvutatto visikhantare caraṃ._
____

.Illustration
====
attā

themselves
====

[quote, S.5.154]
____
Those bhikkhus, either now or after my passing, who abide spiritually 
self-reliant, with themselves as their refuge, with no other refuge; relying 
completely on the teaching, with the teaching as their refuge, with no other 
refuge; it is these bhikkhus, Ānanda, who will be for me foremost amongst 
those desirous of the training.

_Ye hi keci ānanda etarahi vā mamaccaye vā attadīpā viharissanti 
attasaraṇā anaññasaraṇā dhammasaraṇā anaññasaraṇā tamatagge me 
te ānanda bhikkhu bhavissanti ye keci sikkhākāmāti._
____

.Illustration
====
attā

you yourself; attānaṃ, yourself
====

• There is no hiding place for the doer of unvirtuous deeds +
_Natthi loke raho nāma pāpakammaṃ pakubbato._

• You yourself, man, know what is true or false. +
_Attā te purisa jānāti saccaṃ vā yadi vā musā._

• Indeed, sir, you disdain the virtuous aspect of yourself which witnesses 
&#8203;[all that you do]. +
_Kalyāṇaṃ vata bho sakkhi attānaṃ atimaññasi._

• You are [trying to] conceal from yourself unvirtuoushess existing within 
yourself +
_Yo santaṃ attani pāpaṃ attānaṃ parigūhasi_ (A.1.149).

.Illustration
====
attanā

yourself; myself; oneself; attā, himself
====

____
-- Is there, Mallikā, anyone more beloved to you than yourself?

_atthi nu kho te mallike ko cañño attanā piyataro ti?_
____

____
-- There is no one, great king, more beloved to me than myself. But is there 
anyone, great king, more beloved to you than yourself?

_Natthi kho me mahārāja ko cañño attanā piyataro. Tuyhaṃ pana mahārāja 
atthañño koci attanā piyataro ti?_
____

____
-- For me too, Mallikā, there is no one more beloved to me than myself.

_Mayhampi kho mallike natthañño koci attanā piyataroti._
____

Then the Blessed One... recited this verse:

____
Having traversed all quarters with the mind,

_Sabbā disā anuparigamma cetasā_
____

____
One finds nowhere anyone more beloved to oneself than oneself.

_Nevajjhagā piyataramattanā kvaci_
____

____
Others hold themselves likewise beloved;

_Evaṃ piyo puthu attā paresaṃ_
____

[quote, S.1.75]
____
Hence one who loves himself should not harm others.

_Tasmā na hiṃse paraṃ attakāmo ti._
____

.Illustration
====
attā

he himself; attānaṃ himself
====

[quote, M.1.440]
____
If a bhikkhu does not fulfil the training in virtue, the Buddha said the 
Teacher criticises him, his discerning wise companions in the religious life 
criticise him, the devas criticise him, and he himself even criticises himself.

_attā pi attānaṃ upavadati._
____

.Illustration
====
attānaṃ

himself
====

The Buddha said a bhikkhu should be straightforward and aboveboard presenting 
himself according to reality to his teachers and to his knowledgeable 
companions in the religious life (_yathābhūtaṃ attānaṃ āvīkattā 
satthari vā viññūsu vā sabrahmacārīsu_) (M.2.128).

.Illustration
====
attā

themselves
====

[quote, A.3.359]
____
Thus do noble young men declare their [attainment of] arahantship: the matter 
is spoken of without any reference to themselves.

_attho ca vutto attā ca anupanīto._
____

.Illustration
====
attā

endowed with personal qualities
====

If bodily form was endowed with personal qualities (_rūpañca hidaṃ 
bhikkhave attā abhavissa_) it would not lead to affliction (_ābādhāya 
saṃvatteyya_) and it would be possible to demand of bodily form (_labbhetha 
ca rūpe_): 'My bodily form: be thus! My bodily form: be not thus!' (_evaṃ me 
rūpaṃ hotu evaṃ me rūpaṃ mā ahosī ti_). But because bodily form is 
void of personal qualities it leads to affliction (_rūpaṃ anattā tasmā 
rūpaṃ ābādhāya saṃvattati_) and it is not possible to demand of bodily 
form: 'My bodily form: be thus! My bodily form: be not thus!' (S.3.66-7).

.Illustration
====
attā

himself; [absolute] Selfhood
====

Saccaka claimed that a person has the five aggregates as himself 
(_rūpattāyaṃ purisapuggalo... viññāṇattāyaṃ..._ ). The Buddha asked 
if Saccaka was claiming the khandhas were "my [absolute] Selfhood" (_rūpaṃ 
me attā... viññāṇaṃ me attā ti_) and compared this to a claim a king 
might make concerning his own realm (_sakasmiṃ vijite_), where he has the 
power to punish criminals as he wishes. The Buddha asked whether Saccaka 
exercised any such power over the five aggregates so as to command them 'Let 
them be thus, or not thus' (_vattati te tasmiṃ rūpe... viññāṇe vaso 
evaṃ me rūpaṃ... viññāṇaṃ hotu evaṃ me rūpaṃ... 
viññāṇaṃ mā ahosī ti_). Saccaka agreed he did not (M.1.230).

.Illustration
====
attā

endowed with personal qualities; [absolute] Selfhood
====

To say that the visual sense is endowed with personal qualities is untenable 
(_cakkhuṃ attā ti yo vadeyya taṃ na upapajjati_) because the 
&#8203;[co-conditional] arising and disappearance of the visual sense is discernable 
(_cakkhussa uppādo pi vayo pi paññāyati_) and he for whom [co-conditional] 
arising and disappearance is discernable, would be forced to the conclusion 
that 'My [absolute] Selfhood arises and disappears' (_attā me uppajjati ca 
veti cā ti_). Thus the visual sense is void of personal qualities (_iti 
cakkhuṃ anattā_) (M.3.282; S.2.95).

.Illustration
====
attā

&#8203;[absolute] Selfhood
====

[quote, M.1.234-5]
____
A disciple of mine... perceives all bodily form according to reality with 
perfect penetrative discernment as "not [in reality] mine," "not [in reality] 
what I am," "not my [absolute] Selfhood."

_Idha aggivessana mama sāvako... sabbaṃ rūpaṃ n'etaṃ mama n'eso'hamasmi 
na me so attā ti evametaṃ yathābhūtaṃ sammappaññāya passati._
____

.Illustration
====
attā

&#8203;[absolute] Selfhood
====

-- Is what (_rūpaṃ... viññāṇaṃ_) is unlasting (_aniccaṃ_), 
existentially void (_dukkhaṃ_), and destined to change fit to be regarded 
thus:

____
this is "[in reality] mine"

_etaṃ mama_
____

____
this is "[in reality] what I am"

_eso'hamasmi_
____

____
this is "my [absolute] Selfhood"?

_eso me attā ti_
____

-- No, bhante (S.3.66-7).

.Illustration
====
attā

&#8203;[absolute] Selfhood
====

The Buddha said there are three types of sense impression: pleasant, 
unpleasant, and neutral (_sukhaṃ vedanaṃ... dukkhaṃ vedanaṃ... 
adukkhamasukhaṃ vedanaṃ_). If anyone experiences these sense impressions 
considering them to be "my [absolute] Selfhood" (_eso me attā ti_), then when 
they cease he would have to hold that 'my [absolute] Selfhood has been 
shattered' (_vyaggo me attā ti_). Therefore it is not suitable to hold sense 
impression is "my [absolute] Selfhood" (_nakkhamati vedanā me attā ti 
samanupassituṃ_) (D.2.67).

.Illustration
====
attā

&#8203;[absolute] Selfhood
====

____
-- If there were no sense impression in any way, would there be the thought "I 
am this"?

_yattha panāvuso sabbaso vedayitaṃ natthi api nu kho tattha ayamahamasmī ti 
siyā ti_
____

-- No, bhante.

[quote, D.2.67]
____
-- Therefore this argument is invalid: Sense impression is not my [absolute] 
Selfhood. My [absolute] Selfhood is without sense impression.

_Tasmātihānanda etenapetaṃ nakkhamati na heva kho me vedanā attā 
appaṭisaṃvedano me attā ti samanupassituṃ._
____

Comment:

Claiming that "my [absolute] Selfhood is without sense impression" is to claim 
knowledge of something one is simultaneously claiming to be unaware of.

.Illustration
====
attā

&#8203;[absolute] Selfhood
====

There was once a number of non-Buddhist ascetics living around Sāvatthī. And 
they were of various dogmatic views, as follows:

____
Eternal are the [absolute] Selfhood and the world [of beings]

_sassato attā ca loko ca_
____

____
Not eternal

_asassato attā ca loko ca_
____

____
Both eternal and not eternal

_sassato asassato attā ca loko ca_
____

____
Neither eternal nor not eternal

_neva sassato nāsassato attā ca loko ca_
____

____
Produced by oneself are the [absolute] Selfhood and the world [of beings]

_sayaṃ kato attā ca loko ca_
____

____
Produced by another

_paraṃ kato attā ca loko ca_
____

____
Produced by oneself and another

_sayaṃ kato paraṅkato attā ca loko ca_
____

____
Produced by neither oneself nor another. They have arisen spontaneously

_asayaṃ kāro aparaṅkāro adhiccasamuppanno attā ca loko ca_
____

And they lived quarrelsome, cantankerous, contentious, stabbing each other with 
verbal daggers (Ud.70).

.Illustration
====
attā

&#8203;[absolute] Selfhood; anattā, void of personal qualities
====

When the ascetic Vacchagotta asked whether or not there is an [absolute] 
Selfhood (_atthattā ti... natthattā ti_) the Buddha refused to answer, 
because, as he later explained, if he had answered that:

____
There is an [absolute] Selfhood, this would have been siding with those 
ascetics and Brahmanists who are eternalists.

_ye te ānanda samaṇabrāhmaṇā sassatavādā tesametaṃ laddhi abhavissa._
____

____
There is no [absolute] Selfhood, this would have been siding with those 
ascetics and Brahmanists who are annihilationists.

_ye te ānanda samaṇabrāhmaṇā ucchedavādā tesametaṃ laddhi abhavissa._
____

____
There is an [absolute] Selfhood, "would this have been consistent on my part 
with the arising of the knowledge that 'all things are void of personal 
qualities'?"

_apinu me taṃ ānanda anulomaṃ abhavissa ñāṇassa uppādāya. Sabbe 
dhammā anattā ti no hetaṃ bhante._
____

[quote, S.4.400]
____
'There is no [absolute] Selfhood, "the ascetic Vacchagotta, already bewildered, 
would have become even more bewildered, thinking, 'It seems that the [absolute] 
Selfhood I formerly had does not exist now.'"

_sammūḷhassa ānanda vacchagottassa paribbājakassa bhiyyo sammohāya 
abhavissa ahu vā me nūna pubbe attā so etarahi natthī ti._
____

.Illustration
====
atta

&#8203;[absolute] Selfhood
====

____
-- Bhikkhus, you might well grasp a theory of an [absolute] Selfhood which 
would not arouse grief, lamentation, physical pain, psychological pain, and 
vexation, but do you see any such theory?

_Taṃ bhikkhave attavādūpādānaṃ upādiyetha yaṃsa 
attavādūpādānaṃ upādiyato na uppajjeyyuṃ 
sokaparidevadukkhadomanassupāyāsā._
____

-- No, bhante.

-- Good, bhikkhus. I also see no such theory (-M.1.137).

.Illustration
====
attā

&#8203;[absolute] Selfhood
====

____
The ignorant Everyman improperly contemplates

_ayoniso manasikaroti_
____

- Was I in the past?

- Was I not in the past?

- What was I in the past?

- How was I in the past?

- Having been what, what did I become in the past?

- Shall I be in the future?

- Shall I not be in the future?

- What shall I be in the future?

- How shall I be in the future?

- Having been what, what shall I become in the future?'

____
Or else he is uncertain about the present in regard to himself

_ajjhattaṃ kathaṅkathī hoti_
____

- Am I?

- Am I not?

- What am I?

- How am I?

- Where has this being come from?

- Where will it go?

____
As he improperly contemplates in this way, one of six dogmatic views arise in 
him as real and actual:

_channaṃ diṭṭhīnaṃ aññatarā diṭṭhi uppajjati_
____

____
I have an [absolute] Selfhood

_atthi me attā ti vā'ssa saccato thetato diṭṭhi uppajjati_
____

____
I do not have an [absolute] Selfhood

_natthi me attā ti vā'ssa saccato thetato diṭṭhi uppajjati_
____

____
I perceive an [absolute] Selfhood with an [absolute] Selfhood

_attanā'va attānaṃ sañjānāmī ti vā'ssa saccato thetato diṭṭhi 
uppajjati_
____

____
I perceive what is not an [absolute] Selfhood with an [absolute] Selfhood

_attanā'va anattānaṃ sañjānāmī ti vā'ssa saccato thetato diṭṭhi 
uppajjati_
____

____
I perceive an [absolute] Selfhood with what is not an [absolute] Selfhood

_anattanā'va attānaṃ sañjānāmī ti vā'ssa saccato thetato diṭṭhi 
uppajjati_
____

• or else he has a view like this: +
_Atha vā pana'ssa evaṃ diṭṭhi hoti_

[quote, M.1.8]
____
It is this [absolute] Selfhood of mine that speaks and experiences and feels 
here and there the karmic consequences of meritorious and demeritorious deeds; 
and this [absolute] Selfhood of mine is everlasting, enduring, eternal, of an 
unchangeable nature, and will endure like unto eternity itself._

_yo me ayaṃ attā vado vedeyyo tatra tatra kalyāṇapāpakānaṃ 
kammānaṃ vipākaṃ paṭisaṃvedeti. So kho pana me ayaṃ attā nicco 
dhuvo sassato avipariṇāmadhammo sassatisamaṃ tatheva ṭhassatī ti._
____

.Illustration
====
attā

&#8203;[absolute] Selfhood
====

____
From the time Ānanda when a bhikkhu

_yato kho panānanda bhikkhu_
____

____
no longer regards sense impression to be the [absolute] Selfhood,

_neva vedanaṃ attānaṃ samanupassati_
____

____
or considers that "my [absolute] Selfhood is without sense impression,"

_no pi appaṭisaṃvedanaṃ attānaṃ samanupassati_
____

____
or considers "my [absolute] Selfhood experiences"

_no pi attā me vediyati_
____

____
or considers "my [absolute] Selfhood is subject to sense impression,"

_vedanādhammo hi me attā ti samanupassati_
____

____
by not so regarding he does not grasp anything in the world [of phenomena].

_so evaṃ asamanupassanto na ca kiñci loke upādiyati_
____

____
Thus he is not apprehensive.

_anupādiyaṃ na paritassati_
____

[quote, D.2.68]
____
Being not apprehensive, he realises the Untroubled for himself.

_aparitassaṃ paccattaṃ yeva parinibbāyissati._
____

.Illustration
====
anatta

the voidness of personal qualities [in the six senses and their objects]; 
anattā, void of personal qualities
====

____
And what, Ānanda, is the perception of the voidness of personal qualities [in 
the six senses and their objects]

_katamācānanda anattasaññā_
____

• In this regard, Ānanda, a bhikkhu... reflects that the six senses and 
their objects are void of personal qualities +
☸ _iti paṭisaṃcikkhati cakkhuṃ anattā rūpā anattā... mano anattā 
dhammā anattā ti_) (A.5.109).

.Illustration
====
anattā

void of personal qualities
====

[quote, S.4.1]
____
Bhikkhus, the visual sense is unlasting. What is unlasting is existentially 
void. What is existentially void is void of personal qualities.

_Cakkhuṃ bhikkhave aniccaṃ. Yadaniccaṃ taṃ dukkhaṃ; yaṃ dukkhaṃ 
tadanattā._
____

