== Avassuta

=== Renderings

- _avassuta_: filled with lust

- _avassuta_: full of defilement

- _avassuta_: spiritually defiled

- _avassuta_: soaked

- _avassuta_: soggy

- _avassuta_: oozing

=== Illustrations

.Illustration
====
avassutā

filled with lust
====

[quote, Vin.4.213]
____
How can the lady Sundarīnandā, filled with lust, consent to physical contact 
with a male person who is filled with lust?

_Kathaṃ hi nāma ayyā sundarīnandā avassutā avatassussa purisapuggalassa 
kāyasaṃsaggaṃ sādiyissatī ti._
____

.Illustration
====
avassutā

filled with lust
====

[quote, Vin.4.214]
____
Filled with lust means: lustful, full of longing, emotionally bound.

_Avassutā nāma: sārattā apekkhavatī paṭibaddhacittā._
____

.Illustration
====
avassuto

full of defilement
====

____
How, friends, is one full of defilement?

_Kathañcāvuso avassuto hoti_
____

____
In this regard, in seeing a visible object via the visual sense, a bhikkhu is 
intent upon an agreeable visible object and troubled by a disagreeable visible 
object. He abides without having established mindfulness of the body, with a 
small mind, and he does not discern according to reality, with the liberation 
&#8203;[from attachment through inward calm] and the liberation [from 
uninsightfulness] through penetrative discernment, where those unvirtuous, 
spiritually unwholesome factors cease without remainder.

_idhāvuso bhikkhu cakkhunā rūpaṃ disvā piyarūpe rūpe adhimuccati 
appiyarūpe rūpe vyāpajjati anupaṭṭhitakāyasati ca viharati 
parittacetaso tañca cetovimuttiṃ paññāvimuttiṃ yathābhūtaṃ 
nappajānāti yatthassa te uppannā pāpakā akusalā dhammā aparisesā 
nirujjhanti._
____

[quote, S.4.184-187]
____
This is called, friends, a bhikkhu who is full of defilement amidst visible 
objects known via the visual sense,

_Ayaṃ vuccatāvuso bhikkhu avassuto cakkhuviññeyyesu rūpesu avassuto._
____

.Illustration
====
avassutaṃ

full of defilement
====

[quote, Ud.52]
____
And the Venerable MahāMoggallāna saw that person sitting in the midst of the 
assembly of bhikkhus -- unvirtuous, of an unvirtuous moral nature, of foul and 
odious behaviour, secretive in conduct, no ascetic though pretending to be one, 
not celibate though pretending to be so, spiritually rotten, full of 
defilement, and morally decayed.

_Addasā kho āyasmā mahāmoggallāno taṃ puggalaṃ dussīlaṃ 
pāpadhammaṃ asucisaṅkassarasamācāraṃ paṭicchannakammantaṃ 
assamaṇaṃ samaṇapaṭiññaṃ abrahmacāriṃ brahmacārīpaṭiññaṃ 
antopūtiṃ avassutaṃ kasambujātaṃ majjhe bhikkhusaṅghassa nisinnaṃ._
____

.Illustration
====
avassutaṃ

spiritually defiled: avassutā, soaked
====

____
If the mind is unsupervised [by mindfulness], acts of body, speech, and mind 
are unsupervised [by the mind].

_Citte gahapati arakkhite kāyakammampi arakkhitaṃ hoti. Vacī kammampi 
arakkhitaṃ hoti. Manokammampi arakkhitaṃ hoti._
____

____
When acts of body, speech, and mind are unsupervised [by the mind], they are 
spiritually defiled._

_Tassa arakkhitakāyakammantassa arakkhitavacīkammantassa 
arakkhitamanokammantassa kāyakammampi avassutaṃ hoti. Vacīkammampi 
avassutaṃ hoti. Manokammampi avassutaṃ hoti._
____

____
When acts of body, speech, and mind are spiritually defiled, they are rotten._

_Tassa avassutakāyakammantassa avassutavacīkammantassa 
avassutamanokammantassa kāyakammampi pūtiyaṃ hoti. Vacīkammampi pūtiyaṃ 
hoti. Manokammampi pūtiyaṃ hoti._
____

____
When acts of body, speech, and mind are rotten, one's death is inauspicious._

_Tassa pūtikāyakammantassa pūtivacīkammantassa pūtimanokammantassa na 
bhaddakaṃ maraṇaṃ hoti. Na bhaddikā kālakiriyā._
____

____
It is like when a hut is poorly thatched, the hut, the rafters, and the walls 
are unprotected._

_Seyyathā pi gahapati kūṭāgāre ducchanne kūṭampi arakkhitaṃ hoti. 
Gopānasiyo pi arakkhitā honti. Bhitti pi arakkhitā hoti._
____

____
The hut, the rafters, and the walls become soaked._

_Kūṭampi avassutaṃ hoti. Gopānasiyo pi avassutā honti. Bhitti pi 
avassutā hoti._
____

[quote, A.1.261]
____
The hut, the rafters, and the walls become rotten._

_Kūṭampi pūtikaṃ hoti. Gopānasiyo pi pūtikā honti. Bhitti pi pūtikā 
hoti._
____

.Illustration
====
avassutāni

soggy
====

[quote, A.4.171]
____
He would strike a number of trees with the blade of his axe. When so struck, 
the firm and pithy trees would give off a dull sound, but those that are 
inwardly rotten, soggy, and decayed would give off a hollow sound.

_Tattha yāni tāni rukkhāni daḷhāni sāravantāni kuṭhāripāsena 
ākoṭitāni kakkhalaṃ paṭinadanti yāni tāni rukkhāni antopūtīni 
avassutāni kasambujātāni tāni kuṭhāripāsena ākoṭitāni daddaraṃ 
paṭinadanti._
____

.Illustration
====
avassute

oozing
====

[quote, Th.v.279]
____
Woe upon oozing, stinking, bodies, which are in league with Māra! In your body 
there are nine ever-flowing streams.

_Dhiratthu pure duggandhe mārapakkhe avassute +
Navasotāni te kāye yāni sandanti sabbadā._
____

.Illustration
====
avassutā

oozing
====

[quote, Thī.v.68]
____
Oozing with lust for sensuous pleasure

_kāmarāgenavassutā._
____

