== Avijjānīvaraṇānaṃ sattānaṃ taṇhāsaṃyojanānaṃ

=== Renderings

- _Avijjānīvaraṇānaṃ sattānaṃ taṇhāsaṃyojanānaṃ_: beings 
&#8203;[obstructed by] uninsightfulness into reality, and [tethered to individual 
existence] by craving

=== Introduction

==== Pubbā koṭi na paññāyati avijjānīvaraṇānaṃ sattānaṃ 
taṇhāsaṃyojanānaṃ sandhāvataṃ saṃsarataṃ

This means:

[quote, S.2.181-2]
____
A first point is not to be discerned of beings with the hindrance of 
uninsightfulness into reality, and with the tie to individual existence of 
craving, roaming and wandering the round of birth and death

_Pubbā koṭi na paññāyati avijjānīvaraṇānaṃ sattānaṃ 
taṇhāsaṃyojanānaṃ sandhāvataṃ saṃsarataṃ._
____

We render the terms as:

_• avijjā_: uninsightfulness into reality

_• taṇhā_: craving

_• saṃyojanānaṃ_: tie to individual existence

But translators commonly render _nīvaraṇānaṃ_ and _saṃyojanānaṃ_ as 
past participles: 'hindered' and 'fettered':

- 'hindered by ignorance and fettered by craving' (Bodhi, S.2.181).

- 'hindered by ignorance, fettered by craving' (Horner, M.1.294).

But the suttas show that the relevant past participles are _nivutā_ and 
_saṃyuttā_.

==== Avijjanīvaraṇa Sutta: nivutā

The past participle given in the _Avijjanīvaraṇa Sutta_ for _nīvaraṇaṃ_ 
is _nivutā_ ('obstructed by'):

[quote, It.9]
____
Bhikkhus, I do not see any other single hindrance obstructed by which beings 
would roam and wander the round of birth and death for such a long time as the 
hindrance of uninsightfulness into reality. Obstructed by the hindrance of 
uninsightfulness into reality, beings roam and wander the round of birth and 
death for a long time.

_Nāhaṃ bhikkhave aññaṃ ekanīvaraṇampi samanupassāmi yena 
nīvaraṇena nivutā pajā dīgharattaṃ sandhāvanti saṃsaranti 
yathayidaṃ bhikkhave avijjānīvaraṇaṃ. Avijjānīvaraṇena hi bhikkhave 
nivutā pajā dīgharattaṃ sandhāvanti saṃsarantī ti._
____

The connection between _avijjā_ and _nivuto_ is confirmed in the _Vaṅgīsa 
Sutta_:

[quote, Sn.v.1033]
____
The world [of beings] is obstructed by uninsightfulness into reality

_Avijjāya nivuto loko._
____

==== Taṇhāsaṃyojana Suttas: saṃyuttā

The past participle given in the _Taṇhāsaṃyojana Sutta_ for 
_saṃyojanānaṃ_ is _saṃyuttā_ ('tethered by').

[quote, It.9]
____
Bhikkhus, I do not see any other single tie to individual existence, tethered 
by which beings would roam and wander the round of birth and death for such a 
long time as the tie of craving. Tethered [to individual existence] by the tie 
of craving, beings roam and wander the round of birth and death for a long time.

_Nāhaṃ bhikkhave aññaṃ ekasaṃyojanampi samanupassāmi yena 
saṃyojanena saṃyuttā sattā dīgharattaṃ sandhāvanti saṃsaranti 
yathayidaṃ bhikkhave taṇhāsaṃyojanaṃ. Taṇhāsaṃyojanena hi 
bhikkhave saṃyuttā sattā dīgharattaṃ sandhāvanti saṃsarantī ti._
____

==== Nivutā: meaning

_Nivuta_ is the past participle of _nivarati_ ('surrounded, hemmed in, 
obstructed, enveloped,' PED). We call it 'obstructed.' Some call it 'shrouded 
in' or 'enveloped in,' but it is associated in the suttas with the instrumental 
case, not the locative case:

[quote, Sn.v.1032]
____
By what is the world [of beings] obstructed?

_Kena ssu nivuto loko._
____

==== Saṃyuttā: meaning

Our research shows that _saṃyuttā_ means 'tethered [to individual 
existence].' See sv _Saṃyutta_. In the passage from the _Taṇhāsaṃyojana 
Sutta_ quoted above, the structure of the sentence rendered the parenthesis 
unnecessary.

==== Applying the past participles

If these missing past participles are inserted, it produces the following 
result, full of redundancy:

[quote, S.2.181-2]
____
A first point is not to be discerned of beings [obstructed by] the hindrance of 
uninsightfulness into reality, and [tethered to individual existence] by the 
tie to individual existence of craving, roaming and wandering the round of 
birth and death.

_pubbā koṭi na paññāyati avijjānīvaraṇānaṃ sattānaṃ 
taṇhāsaṃyojanānaṃ sandhāvataṃ saṃsarataṃ._
____

==== Removing the redundancy

Without redundancy, the phrase becomes:

[quote, S.2.181-2]
____
A first point is not to be discerned of beings [obstructed by] uninsightfulness 
into reality, and [tethered to individual existence] by craving, roaming and 
wandering the round of birth and death.

_pubbā koṭi na paññāyati avijjānīvaraṇānaṃ sattānaṃ 
taṇhāsaṃyojanānaṃ sandhāvataṃ saṃsarataṃ._
____

Ironically, then, we have simply replaced _nīvaraṇānaṃ_ and 
_saṃyojanānaṃ_ with _nivutā_ and _saṃyuttā_, and apart from adding 
brackets, have followed Bodhi and Horner exactly:

- 'hindered by ignorance and fettered by craving' (Bodhi, S.2.181).

- 'hindered by ignorance, fettered by craving' (Horner, M.1.294).

=== Illustrations

.Illustration
====
&#8203;[obstructed by] uninsightfulness into reality

and [tethered to individual existence] by craving
====

• For those beings, [obstructed by] uninsightfulness into reality, and 
&#8203;[tethered to individual existence] by craving, taking delight in this and that, 
renewed states of individual existence and rebirth occur in the future. +
_Avijjānīvaraṇānaṃ kho āvuso sattānaṃ taṇhāsaṃyojanānaṃ 
tatra tatrābhinandanā evaṃ āyatiṃ punabbhavābhinibbatti hotī ti_ 
(M.1.294).

