== Avijjā

=== Renderings

- _avijjā_: uninsightfulness into reality

- _avijjāgata_: void of insight into reality

- _avijjāgato hoti_: to lack insight into reality

- _vijjā_: insightfulness into reality

- _vijjā_: insightfulness

_• vijjāgata_: having insight into reality

_• vijjāgato hoti_: to be possessed of insight into reality

=== Introduction

==== Ignorance: extraordinary consensus

_Avijjā_ has been called 'ignorance' at least since 1875 when Childers' 
dictionary appeared. Even today this word is universally accepted. The 
consensus is extraordinary.

==== What is missing: insight

'Ignorance' means lack of knowledge or education that is abandoned through 
knowledge and education. But _avijjā_ is abandoned through transcendent 
insight (_abhiññā pahātabbā_ A.2.247). What is missing in _avijjā_ is not 
knowledge but insight.

==== Channa's stumbling block: lack of insight

The difference between knowledge and insight is illustrated in the case of 
Venerable Channa who knew the teaching but did not see the nature of reality 
(_dhammaṃ passato hoti_). Although he understood the theory of _anicca_, he 
lacked insight. So he asked Venerable Ānanda to explain the teaching in such a 
way that he might see the nature of reality (_dhammaṃ passeyyan ti_) 
(S.3.133). Channa's stumbling block was not knowledge, so he was not 'ignorant'.

==== Overcoming avijjā: a matter of insight

With enlightenment, when _avijjā_ is dispelled and _vijjā_ arises (_avijjā 
vihatā vijjā uppannā_) 'darkness is banished, and light arises' (_tamo 
vihato āloko uppanno_) (M.1.248). One knows and sees (_evaṃ jānato evaṃ 
passato_) the four noble truths as clearly as if one were looking at fish in a 
crystal clear pond (D.1.84). Overcoming _avijjā_ is therefore a matter of 
insight not knowledge. Other quotations below make the same point.

=== Illustrations

.Illustration
====
avijjā

uninsightfulness into reality
====

____
Which things must be abandoned through transcendent insight?

_Katame ca bhikkhave dhammā abhiññā pahātabbā?_
____

[quote, A.2.247]
____
Uninsightfulness into reality and craving for states of individual existence._

_Avijjā ca bhavataṇhā ca._
____

.Illustration
====
avijjā/vijjā

un/insightfulness into reality
====

____
This uninsightfulness into reality is indeed undiscernment of reality whereby 
this wandering the round of birth and death goes on for a long time.

_Avijjā hāyaṃ mahāmoho yenidaṃ saṃsitaṃ ciraṃ_
____

[quote, Sn.v.729-730]
____
But whatever beings have insight into reality, they do not come to renewed 
states of individual existence.

_Vijjāgatā va ye sattā nāgacchanti punabbhavan ti._
____

.Illustration
====
avijjā

uninsightfulness into reality
====

____
Camouflaged by skin, the body is not seen according to reality.

_Chaviyā kāyo paṭicchanno yathābhūtaṃ na dissati._
____

____
The fool, led on by uninsightfulness into reality, thinks it exquisite.

_Subhato naṃ maññati bālo avijjāya purakkhato._
____

____
However, having heard the Buddha's word, the bhikkhu here possessed of 
knowledge [of things according to reality] profoundly understands [the body], 
for he perceives it according to reality.

_bhikkhu paññāṇavā idha so kho naṃ pajānāti yathābhūtaṃ hi 
passati._
____

[quote, Sn.v.194; 199; 202; 206]
____
Whoever would think to be swelled-headed because of such a body, or would 
disparage another, what is this except not seeing it [according to reality]?

_kimaññatra adassanā ti._
____

.Illustration
====
avijjaṃ uninsightfulness into reality

[quote

S.3.155]
====

____
When the perception of the unlastingness [of the five aggregates] is developed 
and cultivated, it destroys all uninsightfulness into reality

_Aniccasaññā bhikkhave bhāvitā bahulīkatā... sabbaṃ avijjaṃ 
pariyādiyati._
____

.Illustration
====
avijjā/vijjā

un/insightfulness into reality
====

____
The ignorant Everyman does not discern according to reality the origination, 
vanishing, sweetness, wretchedness, and deliverance in regards to the five 
aggregates.

_assutavā puthujjano rūpassa... viññāṇassa samudayañca atthaṅgamañca 
assādañca ādīnavañca nissaraṇañca yathābhūtaṃ nappajānāti._
____

____
This is called uninsightfulness into reality

_ayaṃ vuccatāvuso avijjā_
____

____
The learned noble disciple discerns this according to reality

_sutavā ariyasāvako rūpassa... viññāṇassa assādañca ādīnavañca 
nissaraṇañca yathābhūtaṃ pajānāti_
____

[quote, S.3.173-4]
____
This is called insightfulness into reality

_Ayaṃ vuccatāvuso vijjā._
____

.Illustration
====
avijjā/vijjā

un/insightfulness into reality
====

[quote, S.4.49-50]
____
When a bhikkhu knows and sees the visual sense as unlasting, uninsightfulness 
into reality is abandoned and insightfulness into reality arises.

_cakkhuṃ kho bhikkhu aniccato jānato passato bhikkhuno avijjā pahīyati 
vijjā uppajjati._
____

.Illustration
====
avijjā

uninsightfulness into reality
====

____
Bhikkhus, ignorance of suffering [according to reality], the origin of 
suffering, the ending of suffering, the practice leading to the ending of 
suffering, is called uninsightfulness into reality, and it is on account of 
this quality that one lacks insight into reality.

_Yaṃ kho bhikkhu dukkhe aññāṇaṃ dukkhasamudaye aññāṇaṃ 
dukkhanirodhe aññāṇaṃ dukkhanirodhagāminiyā paṭipadāya 
aññāṇaṃ ayaṃ vuccati bhikkhu avijjā ettāvatā ca avijjāgato hoti._
____

[quote, S.5.430]
____
Bhikkhus, whatsoever is the knowledge of suffering [according to reality], of 
the origin of suffering, the ending of suffering, and of the practice leading 
to the ending of suffering, is called insightfulness into reality, and it is on 
these grounds that one is possessed of insight into reality.

_Yaṃ kho bhikkhu dukkhe ñāṇaṃ dukkhasamudaye ñāṇaṃ dukkhanirodhe 
ñāṇaṃ dukkhanirodhagāminiyā paṭipadāya ñāṇaṃ ayaṃ vuccati 
bhikkhu vijjā ettāvatā ca vijjāgato hoti._
____

.Illustration
====
avijjā

uninsightfulness into reality
====

____
What is the condition that nourishes uninsightfulness into reality? The five 
hindrances, one should reply._

_ko cāhāro avijjāya? Pañca nīvaraṇā tissa vacanīyaṃ_
____

• Magnifying the five hindrances magnifies uninsightfulness into reality. +
_Pañcanīvaraṇā paripūrā avijjaṃ paripūrenti_ (A.5.116).

.Illustration
====
avijjā

uninsightfulness into reality
====

____
'Bhante, when, in regard to those who are not perfectly enlightened, the view 
arises that they are in fact perfectly enlightened, due to what is this view to 
be discerned?'

_asammāsambuddhesu sammā sambuddhā ti. Ayaṃ nu kho bhante diṭṭhi kiṃ 
paṭicca paññāyatī ti_
____

[quote, S.2.153]
____
'Mighty, Kaccāna, is this phenomenon, namely the phenomenon of 
uninsightfulness into reality'

_mahati kho esā kaccāna dhātu yadidaṃ avijjādhātu._
____

.Illustration
====
avijjā/vijjā

un/insightfulness into reality
====

____
-- Bhante, how should a bhikkhu know, how should he see, for uninsightfulness 
into reality to be abandoned by him and insightfulness into reality to arise?"

_kathaṃ pana bhante jānato kathaṃ passato avijjā pahīyati vijjā 
uppajjatī ti?_
____

____
-- In this regard, bhikkhu, a bhikkhu has heard that all things are unsuited to 
stubborn attachment.'

_sabbe dhammā nālaṃ abhinivesāyā ti._
____

____
... When a bhikkhu has heard that all things are unsuited to stubborn 
attachment he fully understands the whole teaching,

_so sabbaṃ dhammaṃ abhijānāti_
____

____
... Through fully understanding the whole teaching, he profoundly understands 
the whole teaching.

_sabbaṃ dhammaṃ parijānāti_
____

____
... Through profoundly understanding the whole teaching, he perceives all 
phenomena differently.

_sabbanimittāni aññato passati_
____

[quote, S.4.49-50]
____
... When, bhikkhu, a bhikkhu knows and sees thus, uninsightfulness into reality 
is abandoned by him and insightfulness into reality arises."

_evaṃ kho bhikkhu jānato evaṃ passato bhikkhuno avijjā pahīyati vijjā 
uppajjatī ti._
____

.Illustration
====
vijjā

insightfulness into reality
====

[quote, S.5.329]
____
The seven factors of enlightenment, when developed and cultivated, bring to 
perfection insightfulness into reality and liberation [from perceptually 
obscuring states].

_satta bojjhaṅgā bhāvitā bahulīkatā vijjāvimuttiṃ paripūrenti._
____

.Illustration
====
vijjā

insightfulness
====

[quote, S.4.233]
____
'This is sense impression': in regard to profound truths not heard before, 
there arose in me vision, knowledge [of things according to reality], 
penetrative discernment, insightfulness, and illumination.

_Imā vedanā ti me bhikkhave pubbe ananussutesu dhammesu cakkhuṃ udapādi 
ñāṇaṃ udapādi paññā udapādi vijjā udapādi āloko udapādi._
____

.Illustration
====
avijjā/vijjā

un/insightfulness into reality
====

____
For an ignorant person void of insight into reality, wrong view [of reality] 
arises.

_avijjāgatassa bhikkhave aviddasuno micchādiṭṭhi pahoti_
____

[quote, S.5.1]
____
For an intelligent person with insight into reality, right perception [of 
reality] arises.

_vijjāgatassa bhikkhave viddasuno sammādiṭṭhi pahoti._
____

.Illustration
====
avijjāyogo

uninsightfulness into reality
====

____
What is the bondage [to individual existence] that arises from uninsightfulness 
into reality?

_avijjāyogo ca kathaṃ hoti_
____

____
In this regard, some person does not discern according to reality the 
origination, vanishing, sweetness, wretchedness, and deliverance in regards to 
the six senses.

_idha bhikkhave ekacco channaṃ phassāyatanānaṃ samudayañca 
atthaṅgamañca assādañca ādīnavañca nissaraṇañca yathābhūtaṃ 
nappajānāti_
____

____
For him who does not discern according to reality the origination, vanishing, 
sweetness, wretchedness, and deliverance in regards to the six senses.

_Tassa channaṃ phassāyatanānaṃ samudayañca atthaṅgamañca assādañca 
ādīnavañca nissaraṇañca yathābhūtaṃ appajānato_
____

[quote, A.2.10]
____
the uninsightfulness and ignorance regarding the six senses that lurk within 
him: this is called the bondage [to individual existence] that arises from 
uninsightfulness into reality.

_yā chasu phassāyatanesu avijjā aññāṇaṃ sānuseti ayaṃ vuccati 
bhikkhave avijjāyogo._
____

