== Aṇḍabhūta

=== Renderings

- _aṇḍabhūta_: enveloped [in uninsightfulness into reality]

- _aṇḍabhūta_: enveloped [in ailments]

=== Introduction

==== Aṇḍabhūta: occurrences

_Aṇḍabhūta_ occurs five times in the scriptures in just two phrases. 
Firstly, in relation to the manyfolk who are void of insight into reality 
(_avijjāgatā bhikkhave pajā aṇḍabhūtā pariyonaddhā_ (A.2.131) and 
secondly in relation to bodily illness (_āturohāyaṃ gahapati kāyo 
aṇḍabhūto pariyonaddho_, S.3.1). In both senses it occurs with 
_pariyonaddho_, smothered (pp. of _pariyonandhati_).

==== Aṇḍabhūto: born of eggs

Although _aṇḍabhūto_ means being enveloped [in uninsightfulness into 
reality] or enveloped [in ailments], like a chick within an eggshell, it could 
be taken as 'become of an egg.' But that would lead to the unpleasant prospect 
of explaining how the body or the manyfolk could be legitimately be called 
egg-born, as more than one translator has said: the Buddha pierced the shell of 
ignorance 'for the sake of creatures going in ignorance, born of eggs.'

==== Aṇḍabhūto: explanations

Bodhi says it could be a misspelling of _addabhūto_ ('weighed down'), and says 
the commentary suggests 'become weak like an egg' (CDB.1043 n.3). But its 
association with _pariyonaddho_ (smothered) counts against this, and supports 
our calling _aṇḍabhūto_ 'enveloped in or by.'

=== Illustrations

.Illustration
====
aṇḍabhūtāya

enveloped [in uninsightfulness into reality]
====

[quote, A.4.176; Vin.3.3]
____
Amongst the manyfolk who are void of insight into reality (_avijjāgatāya 
pajāya_), enveloped and smothered [in uninsightfulness into reality] 
(_aṇḍabhūtāya pariyonaddhāya_), having broken through the eggshell of 
uninsightfulness into reality (_avijjaṇḍakosaṃ padāletvā_), I alone in 
the world have fully awakened to unsurpassed, complete enlightenment.

_Evameva kho ahaṃ brāhmaṇa avijjāgatāya pajāya aṇḍabhūtāya 
pariyonaddhāya avijjaṇḍakosaṃ padāletvā eko'va loke anuttaraṃ 
sammāsambodhiṃ abhisambuddho._
____

.Illustration
====
aṇḍabhūtā

enveloped [in uninsightfulness into reality]
====

• The manyfolk who are void of insight into reality are enveloped and 
smothered [in uninsightfulness into reality]. But they really listen to the 
teaching on the elimination of uninsightfulness into reality taught to them by 
the Perfect One, they lend an ear, they apply their minds to understand [it]** +
**__☸ Avijjāgatā bhikkhave pajā aṇḍabhūtā pariyonaddhā sā 
tathāgatena avijjāvinaye dhamme desiyamāne sussūsati. Sotaṃ odahati. 
Aññācittaṃ upaṭṭhapeti__ (A.2.131).

.Illustration
====
aṇḍabhūto

enveloped [in ailments]
====

Nakulapitā complained that he was aged, burdened with years, advanced in life, 
come to the last stage, ailing in body, often unwell. The Buddha agreed, saying:

[quote, S.3.1]
____
'So it is, householder, so it is. This [wretched human] body of yours is 
ailing, enveloped and smothered [in ailments]. If anyone carrying around [such 
a wretched] body were to claim to be healthy even for a moment, that would only 
be folly. Therefore, householder, you should train yourself [with this 
reflection]: 'Though my body is ailing, my mind will not be ailing.'

_Evametaṃ gahapati evametaṃ gahapati. Āturohāyaṃ gahapati kāyo 
aṇḍabhūto pariyonaddho. Yo hi gahapati imaṃ kāyaṃ pariharanto 
muhuttampi ārogyaṃ paṭijāneyya kimaññatra bālyā. Tasmātiha te 
gahapati evaṃ sikkhitabbaṃ: āturakāyassa me sato cittaṃ anāturaṃ 
bhavissatī ti._
____

