== Aṭṭhikatvā

=== Renderings

- _aṭṭhikatvā_: as a matter of vital concern

=== Introduction

==== Aṭṭhikatvā: occurrences

_Aṭṭhikatvā_ occurs 39 times in the scriptures, in 38 times followed by 
either _manasikatvā_ or _manasikaroti._ In one case it is linked to 
_paṭipajjamāno._

==== Aṭṭhikatvā: not sluggishly

DOP says it means 'making something one's aim or object; paying attention.' But 
the _Upavāna Sutta_ (S.5.76) does not support this because it occurs in the 
phrase _aṭṭhikatvā manasikaromi no ca līnan ti._ Here _aṭṭhikatvā_ 
is opposed to _no ca līnaṃ_, which Bodhi translates as 'I attend as a matter 
of vital concern, not sluggishly.'

==== Aṭṭhikatvā equals nisamma

Bodhi's rendering 'as a matter of vital concern' is supported by Sn.v.317 where 
_aṭṭhikatvā_ is a synonym of _nisamma_ ('carefully, considerately, 
observing': PED). Here again _aṭṭhikatvā_ seems well rendered as 'as a 
matter of vital concern.' The verse is as follows:

[quote, Sn.v. 317]
____
The wise and diligent man who associates with such a person (described in the 
preceding verse), carefully (_nisamma_) practising in accordance with the 
teaching as a matter of vital concern (_tadaṭṭhikatvāna_), becomes 
knowledgeable, astute, and intelligent.

_Tadaṭṭhikatvāna nisamma dhīro dhammānudhammaṃ paṭipajjamāno +
Viññū vibhāvī nipuṇo ca hoti yo tādisaṃ bhajati appamatto._
____

=== Illustrations

.Illustration
====
aṭṭhikatvā

as a matter of vital concern
====

[quote, Vin.4.144]
____
It is to your loss, friend, it is to your detriment, that when the Pātimokkha 
is being recited you do not pay it proper attention as a matter of vital 
concern.

_tassa te āvuso alābhā tassa te dulladdhaṃ yaṃ tvaṃ pātimokkhe 
uddissamāne na sādhukaṃ aṭṭhikatvā manasikarosī ti._
____

.Illustration
====
aṭṭhikatvā

as a matter of vital concern
====

[quote, M.1.445]
____
When I am explaining the teaching, this worthless man does listen to it with 
eager ears, paying attention to it as a matter of vital concern, applying his 
whole mind to it.

_Nacāyaṃ moghapuriso mayā dhammaṃ desiyamāne aṭṭhikatvā 
manasikatvā sabbacetaso samannāharitvā ohitasoto dhammaṃ suṇātī ti._
____

.Illustration
====
aṭṭhikatvā

as a matter of vital concern
====

____
I will recite the Pātimokkha with one and all of us present.

_Pātimokkhaṃ uddisissāmi taṃ sabbeva santā_
____

____
Listen carefully. Pay attention.

_sādhukaṃ suṇoma manasikaroma_
____

[quote, Vin.1.103]
____
Listen carefully [means]: pay attention as a matter of vital concern, apply 
one's whole mind to it.

_sādhukaṃ suṇomā ti aṭṭhikatvā manasikatvā sabbacetasā 
samannāharāma._
____

.Illustration
====
aṭṭhikatvā

as a matter of vital concern
====

[quote, S.1.112]
____
Those bhikkhus were listening to the teaching with eager ears, paying attention 
to it as a matter of vital concern, applying their whole minds to it.

_Te ca bhikkhū aṭṭhikatvā manasikatvā sabbacetasā samannāharitvā 
ohitasotā dhammaṃ suṇanti._
____

