== Baddha

=== Renderings

- _baddha_: locked up

- _baddha_: bound

- _baddha_: tied up

- _baddha_: confined

- _baddha_: held captive

- _baddha_: emotionally bound

- _baddha_: bound [to individual existence]

=== Introduction

==== Baddha: bound [to individual existence]

We explain how _baddha_ means 'bound [to individual existence]' via two 
passages.

==== Passage 1: baddho so mārabandhanena, bound [to individual existence] by 
Māra's bond

_Baddho so mārabandhanena_ occurs in this passage:

[quote, S.4.92]
____
There are visible objects known via the visual sense that are likeable, 
loveable, pleasing, agreeable, connected with sensuous pleasure, and charming. 
If a bhikkhu takes delight in them, welcomes them, persists in cleaving to 
them, this is called a bhikkhu who has entered Māra's lair, who has come under 
Māra's control, who is trapped in Māra's snare, who is bound [to individual 
existence] by Māra's bond. The Maleficent One can do with him as he wishes.

_Santi bhikkhave cakkhuviññeyyā rūpā iṭṭhā kantā manāpā piyarūpā 
kāmūpasaṃhitā rajanīyā tañce bhikkhu abhinandati abhivadati ajjhosāya 
tiṭṭhati ayaṃ vuccati bhikkhave bhikkhu āvāsagato mārassa mārassa 
vasaṅgato paṭimukkassa mārapāso baddho so mārabandhanena 
yathākāmakaraṇīyo pāpimato._
____

Māra's bond is _mārabandhana_ (S.1.24; S.4.92) or _mārasaṃyoga_ 
(Sn.v.733). Māra's bond means bondage [to individual existence], as this quote 
shows:

[quote, Sn.v.733]
____
Having overcome Māra's tie [that ties one to renewed states of individual 
existence], they do not come to renewed states of individual existence.

_Abhibhuyya mārasaṃyogaṃ nāgacchanti punabbhavan ti._
____

Therefore _baddho so mārabandhanena_, means 'bound [to individual existence] 
by Māra's bond.'

==== Passage 2: mohena baddhā, bound [to individual existence] by undiscernment of reality

_Mohena baddhā_ occurs in this passage:

[quote, A.2.72]
____
Attached to charming things; taking delight in what is agreeable; vile 
creatures bound [to individual existence] by undiscernment of reality, 
reinforce that bondage.

_sārattā rajanīyesu piyarūpābhinandino +
Mohena adhamā sattā baddhā vaḍḍhenti bandhanaṃ._
____

That _baddhā_ means bound [to individual existence] is proven by its 
association with _bandhanaṃ_. That _bandhana_ means bondage [to individual 
existence] can be shown in three ways:

1. It is sometimes explicit:
+
[quote, S.1.35]
____
Through understanding your teaching they severed the bondage to individual 
existence.

_Yassa te dhammamaññāya acchiduṃ bhavabandhanaṃ._
____

2. Sometimes the meaning is conveyed through its association with words like 
_saṃyojana_:
+
[quote, D.2.274]
____
Like the elephant that bursts all its fastenings and chains, they severed the 
ties and bonds [to individual existence] in the sensuous plane of existence, 
those ties of the Maleficent One so hard to overcome.

_Te kāmasaṃyojanabandhanāni pāpimayogāni duraccayāni nāgoca 
sandānaguṇāni chetvā._
____

3. Sometimes, the context implies it. For example here, where its link to 
_bhava_ is proven by its link to _taṇhā_:
+
[quote, S.1.8]
____
Craving you call bondage [to individual existence].

_taṇhaṃ me brūsi bandhanan ti._
____
+
[quote, S.3.26]
____
Craving that leads to renewed states of individual existence

_taṇhā ponobhavikā._
____

Therefore _mohena baddhā_ means 'bound [to individual existence] by 
undiscernment of reality.'

=== Illustrations

.Illustration
====
baddho

locked up
====

[quote, D.1.72]
____
As if a man were locked up in prison, and later were released

_Seyyathā pi mahārāja puriso bandhanāgāre baddho assa so aparena samayena 
tamhā bandhanāgārā mucceyya._
____

.Illustration
====
baddhā

bound
====

[quote, S.1.133]
____
The Tāvatiṃsa devas, Yāmā devas, Tusita devas, Nimmānaratī devas, and 
Paranimmitavasavattī devas: they are still bound [to individual existence] in 
the sensuous plane of existence. They come again under Māra's control.

_Tāvatiṃsā ca yāmā ca tusitā cāpi devatā +
Nimmānaratino devā ye devā vasavattino +
Kāmabandhanabaddhā te enti māravasaṃ puna._
____

.Illustration
====
baddhā

bound
====

[quote, A.2.33]
____
Those royal bull elephants, bound by strong thongs and bonds in the villages, 
towns, and capital cities, burst and break those bonds.

_Yepi te bhikkhave rañño nāgā gāmanigamarājadhānīsu daḷhehi varattehi 
bandhanehi baddhā tepi tāni bandhanāni sañchinditvā sampadāḷetvā._
____

.Illustration
====
baddho

tied up
====

[quote, A.5.323]
____
The unbroken colt, Sandha, when tied up at the feeding trough mopes 'Fodder! 
Fodder!'

_Assakhaluṅko hi sandha doṇiyā baddho yavasaṃ yavasanti jhāyati._
____

.Illustration
====
abaddho

unconfined
====

[quote, Sn.v.39]
____
An unconfined deer in the forest goes where it wishes for pasture

_Migo araññamhi yathā abaddho yenicchakaṃ gacchati gocarāya._
____

.Illustration
====
baddho

held captive
====

[quote, Dh.v.324]
____
Being held captive, he does not eat a morsel.

_Baddho kabalaṃ na bhuñjati._
____

.Illustration
====
baddho

held captive
====

• By taking delight in bodily form one is held captive by Māra. By not 
taking delight in it one is freed from the Maleficent One. +
_Rūpaṃ kho bhante abhinandamāno baddho mārassa anabhinandamāno mutto 
pāpimato_ (S.3.75).

.Illustration
====
baddho

held captive
====

[quote, S.3.74]
____
By grasping bodily form one is held captive by Māra. By not grasping, one is 
freed from the Maleficent One.

_Rūpaṃ kho bhante upādiyamāno baddho mārassa anupādiyamāno mutto 
pāpimato._
____

.Illustration
====
baddho

not held captive
====

[quote, It.56]
____
Bhikkhus, one for whom attachment, hatred, and undiscernment of reality has 
been abandoned is said to be not held captive by Māra. He is free of Māra's 
snare. The Maleficent One cannot do with him as he wishes.

_Yassa kassaci bhikkhave rāgo pahīno doso pahīno moho pahīno ayaṃ vuccati 
bhikkhave abaddho mārassa omukkassa mārapāso. Na yathākāmakaraṇīyo 
pāpimato ti._
____

.Illustration
====
baddhā

emotionally bound
====

[quote, Sn.v.773]
____
Those fettered by desire, emotionally bound to the pleasures of individual 
existence, are not easily liberated, and indeed are not liberated except in 
relation to such ties.

_Icchānidānā bhavasātabaddhā te duppamuñcā na hi aññamokkhā._
____

.Illustration
====
baddho

emotionally bound
====

• There are among humans no sensuous pleasures that are lasting. Here there 
are attractive things. When one is emotionally bound to these... +
_Na santi kāmā manujesu niccā santīdha kamanīyāni yesu baddho_

[quote, S.1.22]
____
Negligently applied [to the practice] in their midst, one does not reach the 
state of non-returning to the realm of death.

_Yesu pamatto apunāgamanaṃ anāgantā puriso maccudheyyā ti._
____

.Illustration
====
baddhānaṃ

bound [to individual existence]
====

[quote, Sn.v.957]
____
Yearning [for an answer], I approach with a question on behalf of the many here 
who are bound [to individual existence].

_Bahūnamidha baddhānaṃ atthi pañhena āgamaṃ._
____

