== Bandhana

=== Renderings

- _bandhana_: prison

- _bandhana_: imprisonment

- _bandhana_: bond

- _bandhana_: bondage

- _bandhana_: bonds of lay life

- _bandhana_: bondage [to individual existence]

- _bandhana_: bond [to individual existence]

- _bandhana_: stalk

- _kāyabandhana_: waistband

=== Introduction

==== Imprisonment

_Bandhana_ means prison or imprisonment.

[quote, A.3.352]
____
He is confined to the prison of hell, or the prison of the animal realm.

_nirayabandhane vā bajjhati tiracchānayonibandhane vā._
____

____
As long as the five hindrances are unabandoned, a bhikkhu sees himself as... in 
prison (_bandhanāgāraṃ_).

_Evameva kho mahārāja bhikkhu... yathā bandhanāgāraṃ... evaṃ ime 
pañca nīvaraṇe appahīne attani samanupassati._
____

[quote, D.1.73]
____
... But when the five hindrances are abandoned, a bhikkhu sees himself as... 
released from imprisonment.

_Seyyathā pi mahārāja... yathā bandhanā mokkhaṃ... ime pañca 
nīvaraṇe pahīne attani samanupassati._
____

==== Bond or bondage

_Bandhana_ can mean bond or bondage:

____
That bond is not strong, say the wise, that is made of iron, wood, or rope.

_Na taṃ daḷhaṃ bandhanamāhu dhīrā yadāyasaṃ dārujaṃ babbajañca_
____

[quote, S.1.77]
____
... Passionate attachment to jewellery and earrings, and affection for children 
and wives, are the strong bonds, say the wise.

_Sārattarattā maṇikuṇḍalesu +
Puttesu dāresu ca yā apekkhā. +
Etaṃ daḷhaṃ bandhanamāhu dhīrā._
____

==== Bonds [of lay life]

_Bandhana_ sometimes needs parenthesising in accordance with this quote:

[quote, Sn.v.44]
____
Having cut the bonds of lay life, the hero should live the religious life as 
solitarily as a rhinoceros horn.

_Chetvāna vīro gihībandhanāni eko care khaggavisāṇakappo._
____

For example:

[quote, Dh.v.344]
____
&#8203;[But when] freed [from the bonds of lay life], he runs back to that same 
bondage.

_mutto bandhanameva dhāvati._
____

Commentary: _gharāvāsabandhanato mutto_.

==== Bondage to individual existence: explicit

When _bandhana_ means bondage to individual existence, sometimes this is 
explicit:

[quote, S.1.35]
____
Through understanding your teaching they severed the bondage to individual 
existence.

_Yassa te dhammamaññāya acchiduṃ bhavabandhanaṃ._
____

==== Bondage [to individual existence]: through association

Sometimes the meaning is conveyed through its association with words like 
_saṃyojana_:

[quote, D.2.274]
____
Like the elephant that bursts all its fastenings and chains, they severed the 
ties and bonds [to individual existence] in the sensuous plane of existence, 
those ties of the Maleficent One so hard to overcome.

_Te kāmasaṃyojanabandhanāni pāpimayogāni duraccayāni nāgoca 
sandānaguṇāni chetvā._
____

==== Bondage [to individual existence]: through context

Sometimes the context implies it. For example where its link to _bhava_ is 
proven by its link to _taṇhā_:

[quote, S.1.8]
____
Craving you call bondage [to individual existence].

_taṇhaṃ me brūsi bandhanan ti._
____

By comparison:

[quote, S.3.26]
____
Craving that leads to renewed states of individual existence

_taṇhā ponobhavikā._
____

==== Māra's bond/tie [to renewed states of individual existence]

Māra's bond is _mārabandhana_ (S.1.24). Māra's tie is _mārasaṃyoga_ 
(Sn.v.733). Māra's bond/tie means bondage [to individual existence].

[quote, Sn.v.733]
____
Having overcome Māra's tie [that ties one to renewed states of individual 
existence], they do not come to renewed states of individual existence.

_Abhibhuyya mārasaṃyogaṃ nāgacchanti punabbhavan ti._
____

Māra's bond means thinking in personal terms:

[quote, S.4.202]
____
By thinking in personal terms one is held captive by Māra. By not thinking in 
personal terms one is freed from the Maleficent One.

_maññamāno kho bhikkhave baddho Mārassa amaññamāno mutto pāpimato._
____

=== Illustrations: bondage [to individual existence]

.Illustration
====
bandhanaṃ

bondage [to individual existence]
====

[quote, A.2.72]
____
Vile creatures bound [to individual existence] by undiscernment of reality, 
reinforce that bondage.

_Mohena adhamā sattā baddhā vaḍḍhenti bandhanaṃ_
____

.Illustration
====
bandhanan

bondage [to individual existence]
====

[quote, D.1.245]
____
In the [terminology of the] Noble One's training system these five varieties of 
sensuous pleasure are called shackles and bondage [to individual existence].

_pañcime kāmaguṇā ariyassa vinaye andū ti pi vuccanti bandhanan ti pi 
vuccanti._
____

Comment:

[quote, M.1.433]
____
When attachment to sensuous pleasure is powerful and unsubdued in him, it is a 
tie to individual existence in the low plane of existence.

_tassa so kāmarāgo thāmagato appaṭivinīto orambhāgiyaṃ saṃyojanaṃ._
____

.Illustration
====
bandhanā

bondage [to individual existence]
====

[quote, A.4.340]
____
Free [from individual existence], I free [others] from bondage [to individual 
existence]

_mutto mocemi bandhanā._
____

.Illustration
====
bandhanā

bondage [to individual existence]
====

[quote, Ud.77]
____
That wise person free of bondage [to individual existence]

_Taṃ dhīraṃ bandhanā muttaṃ._
____

.Illustration
====
bandhana

bondage [to individual existence]
====

[quote, Dh.v.349]
____
The craving of a person of distracted thoughts, who is full of attachment and 
contemplates the loveliness [of the female body] will only develop. Such a 
person reinforces his bondage [to individual existence].

_Vitakkapamathitassa jantuno tibbarāgassa subhānupassino +
Bhiyyo taṇhā pavaḍḍhati esa kho daḷhaṃ karoti bandhanaṃ._
____

=== Illustrations: bond

.Illustration
====
bandhana

bond [to individual existence]
====

[quote, S.1.191; Th.v.1234]
____
Seers, rid of spiritual defilement, with renewed states of individual existence 
destroyed, having severed the ties and bonds [to individual existence].

_Saṃyojanabandhanacchidā anīghā khīṇapunabbhavā isī._
____

.Illustration
====
bandhanāni

bonds [to individual existence]
====

[quote, Sn.v.522]
____
Having freed himself of all ties and bonds [to individual existence], he is 
attached to nothing.

_Sabbasaṃyoge visajja bandhanāni sabbattha na sajjati._
____

.Illustration
====
bandhanehi

bonds
====

[quote, A.2.33]
____
Those royal bull elephants, bound by strong thongs and bonds in the villages, 
towns, and capital cities, burst and break those bonds.

_Yepi te bhikkhave rañño nāgā gāmanigamarājadhānīsu daḷhehi varattehi 
bandhanehi baddhā tepi tāni bandhanāni sañchinditvā sampadāḷetvā._
____

.Illustration
====
bandhanā

bond
====

[quote, M.2.44]
____
Thus, indeed, there rightly comes to be deliverance from the bond, that is, 
from the bond of uninsightfulness into reality.

_Evaṃ kira sammā bandhanā vippamokkho hoti yadidaṃ avijjābandhanā._
____

.Illustration
====
bandhanaṃ

bond
====

[quote, D.1.226]
____
It is as if a man having destroyed one bond should make himself another.

_Seyyathā pi nāma purāṇaṃ bandhanaṃ chinditvā aññaṃ navaṃ 
bandhanaṃ kareyya?._
____

=== Illustrations: Māra's bond [that binds one to renewed states of individual 
existence]

.Illustration
====
mārabandhanā

Māra's bond [that binds one to renewed states of individual existence]
====

[quote, S.1.24]
____
Those who meditate, are released from Māra's bond [that binds one to renewed 
states of individual existence].

_pamuccanti jhāyino mārabandhanā._
____

.Illustration
====
mārassa bandhanaṃ

Māra's bond [that binds one to renewed states of individual existence]
====

[quote, Th.v.298]
____
Having cut Māra's bond [that binds one to renewed states of individual 
existence]

_chetvā mārassa bandhanaṃ._
____

.Illustration
====
bandhanehi

bonds; bandhanaṃ, bondage; mārabandhanaṃ, Māra's bond [that binds one to 
renewed states of individual existence]
====

____
When Vepacitti, Lord of the Asuras, thought 'The devas are righteous, the 
asuras are unrighteous...' he was freed from bonds around his limbs and neck...

_yadā kho bhikkhave vepacittissa asurindassa evaṃ hoti dhammikā kho devā 
adhammikā asurā... atha kaṇṭhapañcamehi bandhanehi muttaṃ..._
____

____
But when he thought: 'The asuras are righteous, the devas are unrighteous...' 
he was bound by bonds around his limbs and neck...

_Yadā ca kho bhikkhave vepacittissa asurindassa evaṃ hoti dhammikā kho 
asurā adhammikā devā... atha kaṇṭapañcamehi bandhanehi baddhaṃ_
____

____
So subtle was the bondage of Vepacitti, but even subtler is Māra's bond [that 
binds one to renewed states of individual existence].

_evam sukhumam kho bhikkhave vepacittibandhanaṃ tato sukhumataraṃ 
mārabandhanaṃ_
____

[quote, S.4.202]
____
By thinking in personal terms one is held captive by Māra. By not thinking in 
personal terms one is freed from the Maleficent One.

_maññamāno kho bhikkhave baddho Mārassa amaññamāno mutto pāpimato._
____

=== Illustrations: minor meanings

.Illustration
====
bandhanā

stalk
====

[quote, Vin.1.96]
____
A withered leaf removed from its stalk could not become green again.

_paṇḍupalāso bandhanā pamutto abhabbo haritattāya._
____

.Illustration
====
kāyabandhana

waistband
====

• The borders of the waistband wore out. +
_Kāyabandhanassa anto jirati_ (Vin.2.136).

