== Bhava; Vibhava

=== Renderings: bhava

- _tibhavā_: three planes of existence

- _bhava_: development

- _bhava_: development of states

- _bhava_: existence

- _bhava_: individual existence

- _bhava_: state of individual existence

- _bhava_: renewed states of individual existence

- _bhava_: the [view of the] continuance of beings [at death]

- _bhavanetti_: the conduit to renewed states of individual existence

=== Renderings: vibhava

- _vibhava_: cessation

- _vibhava_: cessation of states

- _vibhava_: cessation of individual existence

- _vibhava_: the [view of the] cessation of beings [at death]

=== Introduction

==== Bhava: individual existence

Rendering _bhava_ as 'individual existence' is justified for several reasons:

1. _Bhava_ is linked to 'the way one exists' (_bhūta_):
+
[quote, A.3.202]
____
In whatever way one exists such that there is the immediate destruction of 
perceptually obscuring states is the foremost state of individual existence.

_Yathābhūtassa anantarā āsavānaṃ khayo hoti idaṃ bhavānaṃ aggan ti._
____

2. _Bhava_ is linked to an [absolute] Selfhood (_atta_):
+
[quote, It.44]
____
Some people are revolted, appalled, and disgusted by individual existence. They 
long for the cessation of individual existence, saying, 'When that [absolute] 
Selfhood is annihilated, destroyed, and does not exist with the demise of the 
body at death, this is peaceful, this is sublime, this is reality.

_bhaveneva kho paneke aṭṭiyamānā harāyamāsā jigucchamānā vibhavaṃ 
abhinandanti yato kira bho ayaṃ attaṃ kāyassa bhedā parammaraṇā 
ucchijjati vinassati na hoti parammaraṇā etaṃ santaṃ etaṃ paṇītaṃ 
etaṃ yathāvantī._
____

3. _Bhava_ is linked to the stream of sense consciousness (_viññāṇaṃ_):
+
[quote, A.1.223-4]
____
The stream of sense consciousness is established in the low plane of existence. 
In this way renewed states of individual existence and rebirth occur in the 
future.... This, Ānanda, is what is implied by the term 'individual existence.'

_Hīnāya dhātuyā viññāṇaṃ patiṭṭhitaṃ. Evaṃ āyatiṃ 
punabbhavābhinibbatti hoti... evaṃ kho ānanda bhavo hotī ti._
____
+
That the stream of sense consciousness is equivalent to the individual 
(_purisa_) is seen here:
+
[quote, D.3.105]
____
He comes to know man's stream of sense consciousness as an unbroken stream that 
is established in both this world and the world beyond.

_purisassa ca viññāṇasotaṃ pajānāti ubhayato abbocchinnaṃ idha loke 
patiṭṭhitañca paraloke patiṭṭhitaṃ ca._
____

4. _Bhava_ is linked to _puggala_:
+
[quote, S.3.25-6]
____
And what is the carrier of the burden. The person, one should reply, this 
Venerable of such a name and clan. This is called the carrier of the burden. 
And what is the taking up of the burden? It is this craving that leads to 
renewed states of individual existence.

_Katamo ca bhikkhave bhārahāro puggalotissa vacanīyaṃ yo'yaṃ āyasmā 
evannāmo evaṃgotto ayaṃ vuccati bhikkhave bhārahāro. Katamañca 
bhikkhave bhārādānaṃ yāyaṃ taṇhā ponobhavikā._
____

==== Bhavadiṭṭhi and vibhavadiṭṭhi: outline

The two views concerning _bhava_ are:

[quote, M.1.65]
____
The view of the continuance of beings [at death] and the view of the cessation 
of beings [at death]

_dvemā bhikkhave diṭṭhiyo bhavadiṭṭhi ca vibhavadiṭṭhi ca._
____

Commentary: _Tattha bhavadiṭṭhī ti sassatadiṭṭhi. Vibhavadiṭṭhī 
ti ucchedadiṭṭhi._

The two views can be illustrated as follows:

==== Vibhavadiṭṭhi: cessation of beings [at death]

The view of the cessation of beings [at death] is illustrated in this quote:

[quote, D.1.34]
____
There are some ascetics and Brahmanists who are annihilationists. They assert 
the annihilation, destruction, and cessation of beings [at death]

_santi bhikkhave eke samaṇabrāhmaṇā ucchedavādā sato sattassa 
ucchedaṃ vināsaṃ vibhavaṃ paññāpenti._
____

==== Bhavadiṭṭhi: continuance of beings [at death]

The view of the continuance of beings [at death] is illustrated in this quote:

[quote, M.2.228]
____
Bhikkhus, there are some ascetics and Brahmanists who speculate about the 
future and who hold dogmatic views concerning the future, who make various 
assertions about the future. They assert that the [absolute] Selfhood is 
perceptive... unperceptive... neither perceptive nor unperceptive and 
unimpaired after death

_santi bhikkhave eke samaṇabrāhmaṇā aparantakappikā 
aparantānudiṭṭhino aparantaṃ ārabbha anekavihitāni adhivuttipadāni 
abhivadanti. +
Saññī... asaññī... nevasaññīnāsaññī attā hoti arogo 
parammaraṇā ti ittheke abhivadanti._
____

==== Tibhavā: three planes of existence

The universe is comprised of three planes of existence (_dhātu_), which are 
named according to two systems:

1. the low plane of existence, the middle plane of existence, and the high 
plane of existence, or,
+
****
_hīnadhātu majjhimadhātu paṇītadhātu_ (D.3.215), or,
****

2. the sensuous plane of existence, the refined material plane of existence, 
and the immaterial plane of existence
+
****
_kāmadhātu... rūpadhātu... arūpadhātu_ (A.1.224).
****

=== Illustrations: planes of existence

.Illustration
====
tibhavā

three planes of existence
====

[quote, Th.v.1089]
____
He is entirely detached from the three planes of existence.

_tibhavābhinissaṭo._
____

.Illustration
====
tibhavā

three planes of existence
====

[quote, Th.v.1133]
____
The three planes of existence are ravaged [by old age and death].

_tibhavā upaddutā._
____

=== Illustrations: existence and cessation of existence

.Illustration
====
bhavā

individual existence
====

[quote, M.1.6]
____
On account of individual existence there is birth, and for one who has come to 
be there is old age and death.

_bhavā jāti bhūtassa jarāmaraṇan ti._
____

.Illustration
====
bhava

individual existence
====

[quote, M.1.330]
____
Sirs, though living in a generation that finds enjoyment, pleasure, and 
satisfaction in individual existence, he has eradicated individual existence 
together with its origin.

_Bhavarāmāya vata bho pajāya bhavaratāya bhavasammuditāya samūlaṃ 
bhavaṃ udabbahī ti._
____

.Illustration
====
bhavā

&#8203;[renewed] states of individual existence
====

____
I have abandoned my wrong view [of reality]. All [renewed] states of individual 
existence are obliterated. I [now] sacrifice to the fire which merits a gift: I 
revere the Perfect One.

_Micchādiṭṭhi pahīnā me bhavā sabbe vidālitā +
Juhāmi dakkhiṇeyyaggiṃ namassāmi tathāgataṃ._
____

[quote, Th.v.343-344]
____
I have abandoned all states of undiscernment of reality. Craving for states of 
individual existence is obliterated. The round of birth and death is destroyed. 
There are now [for me] no renewed states of individual existence.

_Mohā sabbe pahīnā me bhavataṇhā padālitā +
Vikkhīṇo jātisaṃsāro natthi dāni punabbhavo ti._
____

.Illustration
====
bhavāya

individual existence; vibhavāya, cessation of individual existence
====

[quote, Sn.v.856]
____
A person for whom there is no attachment, who, knowing the nature of reality 
&#8203;[according to reality], is not attached; and who has no craving for either 
individual existence or the cessation of individual existence.

_Yassa nissayatā natthi ñatvā dhammaṃ anissito +
Bhavāya vibhavāya vā taṇhā yassa na vijjati._
____

.Illustration
====
bhavo

individual existence
====

____
-- Bhante, it is said: 'Individual existence, individual existence'

_bhavo bhavo ti._
____

____
... On what grounds is there individual existence?

_kittāvatā nu kho bhante bhavo hotī ti?_
____

-- If there were no deed that produced karmic consequences in

____
the sensuous plane of existence

_kāmadhātuvepakkañca kammaṃ_
____

____
the refined material plane of existence

_rūpadhātuvepakkañca kammaṃ_
____

• the immaterial plane of existence +
☸ __arūpadhātu__vepakkañca kammaṃ

would there be discerned (_paññāyethā_) any

____
individual existence in the sensuous plane of existence

_kāmabhavo_
____

____
individual existence in the refined material plane of existence

_rūpabhavo_
____

____
individual existence in the immaterial plane of existence

_arūpabhavo_
____

-- No, bhante.

-- Thus Ānanda,

____
the [field of] operation of the karmic mechanism is the field

_kammaṃ khettaṃ_
____

____
the stream of sense consciousness, the seed

_viññāṇaṃ bījaṃ_
____

____
craving, the moisture

_taṇhā sneho._
____

For beings (_sattānaṃ_) obstructed by uninsightfulness into reality 
(_avijjānīvaraṇānaṃ_) and tethered [to individual existence] by craving 
(_taṇhāsaṃyojanānaṃ_) the stream of sense consciousness 
(_viññāṇaṃ_) is established (_patiṭṭhitaṃ_) in

____
the low plane of existence

_hīnāya dhātuyā_
____

____
the middle plane of existence

_majjhimāya dhātuyā_
____

____
the high plane of existence

_paṇītāya dhātuyā_
____

____
In this way renewed states of individual existence and rebirth occur in the 
future

_evaṃ āyatiṃ punabbhavābhinibbatti hoti._
____

[quote, A.1.223-4]
____
This, Ānanda, is what is implied by the term 'individual existence'

_evaṃ kho ānanda bhavo hotī ti._
____

.Illustration
====
bhava

individual existence
====

____
Man is bound to individual existence,

_bhavasatto loko_
____

____
Is afflicted by individual existence,

_bhavapareto_
____

____
Yet takes delight in individual existence.

_bhavamevābhinandati_
____

____
But what he takes delight in is fearsome.

_Yadabhinandati taṃ bhayaṃ_
____

____
And that which he fears is existentially void.

_yassa bhāyati taṃ dukkhaṃ._
____

____
It is to abandon individual existence

_bhavavippahānāya kho_
____

[quote, Ud.32-3]
____
That this religious life is lived.

_panidaṃ brahmacariyaṃ vussati._
____

.Illustration
====
bhavassa

individual existence; bhavena, [states of] individual existence
====

____
Whatever ascetics and Brahmanists have said that deliverance from individual 
existence is through [states of] individual existence

_bhavena bhavassa vippamokkhamāhaṃsu_
____

____
None of them, I declare, are freed from individual existence

_sabbe te avippamuttā bhavasmā ti vadāmi._
____

____
Whatever ascetics and Brahmanists have said that

_ye vā pana keci samaṇā vā brāhmaṇā vā_
____

____
Deliverance from individual existence is through the cessation of [states of] 
individual existence

_vibhavena bhavassa nissaraṇamāhaṃsu_
____

____
None of them, I declare

_sabbe te_
____

[quote, Ud.33]
____
Have escaped individual existence

_anissaṭā bhavasmā ti vadāmi._
____

Comment:

_Bhavena_ and _vibhavena_ are parenthesised to help make sense. Otherwise the 
sutta would say that 'Whatever ascetics and Brahmanists have said that 
deliverance from individual existence is through the ending of individual 
existence, none of them, I declare have escaped individual existence.' This 
would be perplexing, given that the ending of individual existence is 
_nibbāna_ (_bhavanirodho nibbānaṃ_ A.5.9).

The sutta means that the end of individual existence is not brought about by 
ending any particular state of existence. The next excerpt says that the end of 
individual existence is accomplished through abandoning craving (_bhavataṇhā 
pahīyati_).

.Illustration
====
bhavā

states of individual existence; vibhavaṃ cessation of individual existence.
====

____
Whatever states of individual existence there are

_ye hi keci bhavā_
____

____
In any way, anywhere

_sabbadhi sabbatthatāya_
____

____
All these states of individual existence are unlasting

_sabbe te bhavā aniccā_
____

____
Existentially void, destined to change

_dukkhā vipariṇāmadhammā_
____

____
On perceiving this according to reality with perfect penetrative discernment

_evametaṃ yathābhūtaṃ sammappaññāya passato_
____

____
he abandons craving for states of individual existence

_bhavataṇhā pahīyati_
____

____
But he does not long for the cessation of individual existence.

_vibhavaṃ nābhinandati_
____

____
With the destruction of all forms of craving

_sabbaso taṇhānaṃ khayā_
____

____
Comes the complete passing away and ending [of originated phenomena], the 
Untroubled

_asesavirāganirodho nibbānaṃ._
____

• For that bhikkhu who has realised the Untroubled +
☸ tassa nibbutassa bhikkhuno

____
Free of grasping

_anupādānā_
____

[quote, Ud.33]
____
There are no renewed states of individual existence

_punabbhavo na hoti._
____

.Illustration
====
bhava

individual existence
====

[quote, Ud.46]
____
For the bhikkhu of peaceful mind who has destroyed craving for states of 
individual existence, the round of birth and death is destroyed. For him there 
are no renewed states of individual existence.

_Ucchinnabhavataṇhassa santacittassa bhikkhuno +
Vikkhīṇo jātisaṃsāro natthi tassa punabbhavo ti._
____

.Illustration
====
bhava

individual existence; bhava, [states of] individual existence; vibhava, 
cessation of [states of] individual existence
====

____
Seeing the danger of individual existence

_bhavevāhaṃ bhayaṃ disvā_
____

____
When searching for either [states of] individual existence or the cessation of 
&#8203;[states of] individual existence,

_bhavañca vibhavesinaṃ_
____

____
I did not welcome individual existence,

_bhavaṃ nābhivadiṃ_
____

[quote, M.1.330]
____
Nor rejoice in or grasp anything.

_kiñci nandiñca na upādiyin ti._
____

.Illustration
====
bhavā

&#8203;[renewed] states of individual existence
====

[quote, Th.v.343-344]
____
I have abandoned my wrong view [of reality]. All [renewed] states of individual 
existence are obliterated.

_Micchādiṭṭhi pahīnā me bhavā sabbe vidālitā._
____

.Illustration
====
bhava

states of individual existence
====

Bhikkhus, there are these three quests. What three?

____
the quest for sensuous pleasure

_kāmesanā_
____

____
the quest for states of individual existence

_bhavesanā_
____

[quote, S.5.55]
____
the quest for a religious life

_brahmacariyesanā._
____

.Illustration
====
bhavā

states of individual existence: bhavo, individual existence
====

____
There are three states of individual existence

_tayo me āvuso bhavā_
____

____
individual existence in the sensuous plane of existence

_kāmabhavo_
____

____
individual existence in the refined material plane of existence

_rūpabhavo_
____

____
individual existence in the immaterial plane of existence

_arūpabhavo_
____

____
With the origination of grasping comes the origination of individual existence

_upādānasamudayā bhavasamudayo_
____

____
With the ending of grasping comes the ending of individual existence

_upādānanirodhā bhavanirodho_
____

The practice leading to the ending of individual existence is the noble 
eightfold path (M.1.50).

.Illustration
====
bhava

individual existence; bhavanetti, the conduit to renewed states of individual 
existence
====

____
The four noble truths have been awakened to and penetrated.

_Tayidaṃ bhikkhave dukkhaṃ ariyasaccaṃ... dukkhanirodhagāminī 
paṭipadā ariyasaccaṃ anubuddhaṃ paṭividdhaṃ_
____

____
Craving for states of individual existence has been eradicated

_ucchinnā bhavataṇhā_
____

____
The conduit to renewed states of individual existence has been destroyed

_khīṇā bhavanetti_
____

• There are now [for me] no renewed states of individual existence * +
☸* _natthi dāni punabbhavo ti_ (D.2.91).

.Illustration
====
bhavanetti

the conduit to renewed states of individual existence
====

[quote, S.3.191]
____
The fondness, attachment, spiritually fettering delight, craving, clinging, 
grasping, obstinate adherence, stubborn attachment, and identification in 
regards to bodily form: this is called the conduit to renewed states of 
individual existence.

_rūpe kho rādha yo chando yo rāgo yā nandi yā taṇhā ye upayūpādānā 
cetaso adhiṭṭhānābhinivesānusayā ayaṃ vuccati bhavanetti._
____

.Illustration
====
bhavanettiko

the conduit to renewed states of individual existence
====

[quote, D.1.46]
____
The body of the Perfect One stands with the conduit to renewed states of 
individual existence cut.

_Ucchinnabhavanettiko bhikkhave tathāgatassa kāyo tiṭṭhati._
____

=== Illustrations: cessation; continuance; development

.Illustration
====
vibhavaṃ

cessation
====

[quote, D.1.34]
____
There are some ascetics and Brahmanists who are annihilationists. They assert 
the annihilation, destruction, and cessation of beings [at death]

_ucchedavādā sato sattassa ucchedaṃ vināsaṃ vibhavaṃ paññāpenti._
____

.Illustration
====
vibhavā

cessation
====

____
When a bhikkhu has profoundly understood what is brought about as such,

_sa ve bhūtapariñño_
____

____
Being free of craving for all states of individual existence,

_so vītataṇho bhavābhave_
____

____
With the cessation of what is brought about [at death]

_bhūtassa vibhavā_
____

[quote, It.44]
____
He comes not to renewed states of individual existence

_bhikkhu nāgacchati punabbhavan ti._
____

.Illustration
====
vibhavaṃ

cessation
====

[quote, A.5.107]
____
Knowing the arising and cessation of the world [of phenomena] [according to 
reality], our minds will be imbued with that perception.

_Lokassa sambhavañca vibhavañca ñatvā +
taṃ saññā paricitañca no cittaṃ bhavissati._
____

.Illustration
====
bhavāya

development of states; vibhavāya, cessation of states
====

____
He knows that, 'If I were to direct this detached awareness so purified and 
refined to the state of awareness of boundless space etc, and to develop my 
mind accordingly, thus this detached awareness supported and fuelled by this 
would remain for a very long time.

_imaṃ ce ahaṃ upekkhaṃ evaṃparisuddhaṃ evaṃpariyodātaṃ 
ākāsānañcāyatanaṃ upasaṃhareyyaṃ tadanudhammañca cittaṃ 
bhāveyyaṃ evaṃ ayaṃ upekkhā tannissitā tadupādānā ciraṃ 
dīghamaddhānaṃ tiṭṭheyya._
____

____
He knows that, 'If I were to direct this detached awareness so purified and 
refined to the state of awareness of boundless space etc, and to develop my 
mind accordingly, that would be something originated.

_So evaṃ pajānāti imaṃ ce ahaṃ upekkhaṃ evaṃparisuddhaṃ 
evaṃpariyodātaṃ ākāsānañcāyatanaṃ upasaṃhareyyaṃ 
tadanudhammañca cittaṃ bhāveyyaṃ saṅkhatametaṃ._
____

[quote, M.3.244]
____
He does not undertake, nor is he intent upon the development or cessation of 
states. So doing, he does not grasp anything in the world [of phenomena].

_So neva taṃ abhisaṅkharoti nābhisañcetayati bhavāya vā vibhavāya vā. 
So anabhisaṅkharonto anabhisañcetayanto bhavāya vā vibhavāya vā na 
kiñci loke upādiyati._
____

Bodhi: He does not form any condition or generate any volition tending towards 
either being or non-being.

Horner: He therefore neither constructs nor thinks out for becoming or for 
de-becoming.

.Illustration
====
bhavāya

development; vibhavāya, cessation
====

[quote, Dh.v.282]
____
Penetrative discernment arises from effort [in proper contemplation]. Without 
effort [in proper contemplation] penetrative discernment is destroyed. 
Recognising these two paths to the development and cessation [of wisdom], let a 
man so conduct himself that his wisdom increases.

_Yogā ve jāyati bhūri ayogā bhūrisaṅkhayo +
Etaṃ dvedhāpathaṃ ñatvā bhavāya vibhavāya ca +
Tathattānaṃ niveseyya yathā bhūri pavaḍḍhati._
____

.Illustration
====
vibhavaṃ

&#8203;[view of the] cessation of beings [at death]; bhavañ: the [view of the] 
continuance of beings [at death]
====

[quote, Sn.v.514]
____
He who has realised the Untroubled via a path made by himself, who has overcome 
his unsureness [about the significance of the teaching], abandoned the [view of 
the] cessation of beings [at death] and the [view of the] continuance of beings 
&#8203;[at death], who has fulfilled [the religious life], who has destroyed renewed 
states of individual existence: he is a bhikkhu.

_Pajjena katena attanā parinibbānagato vitiṇṇakaṅkho vibhavañca 
bhavañca vippahāya +
Vusitavā khiṇapunabbhavo sa bhikkhu._
____

=== Illustrations: existence

.Illustration
====
bhavaṃ

existence
====

[quote, A.1.234]
____
Having arisen in human existence just once more, he then puts an end to 
suffering._

_ekaññeva mānusakaṃ bhavaṃ nibbattetvā dukkhassantaṃ karoti._
____

.Illustration
====
bhavo

existence
====

[quote, Th.v.258-259]
____
Existence as a human being, too, was successfully obtained

_mānuso ca bhavobhirādhito._
____

.Illustration
====
bhave

existence
====

[quote, Sn.v.1055]
____
Having thrust away spiritually fettering delight and attachment regarding these 
things, your stream of sense consciousness would not remain in existence.

_Etesu nandiñca nivesanañca panujja viññāṇaṃ bhave na tiṭṭhe._
____

