== Bhavābhava

=== Renderings

- _bhavābhava_: renewed states of individual existence

- _bhavābhava_: various states of individual existence

- _bhavābhava_: any state of individual existence

- _bhavābhava_: all states of individual existence

- _bhavābhava_: from one state of individual existence to another

=== Introduction

==== Bhavabhava: in verse

The term _bhavābhava_ occurs 20 times in the scriptures, always in poems, 
except for one passage in the _Madhupiṇḍika Sutta_ which is so lyrical as 
to be practically verse, which begins:

[quote, M.1.108]
____
&#8203;[I proclaim] a doctrine, friend, such that in the world [of beings] with its 
devas, māras, and brahmās, in the world of mankind with its ascetics and 
Brahmanists, its royalty and commoners, one does not abide quarrelling with 
anyone in the world.

_Yathāvādī kho āvuso sadevake loke samārake sabrahmake 
sassamaṇabrāhmaṇiyā pajāya sadevamanussāya na kenaci loke vigayha 
tiṭṭhati._
____

==== Norman's renderings

Norman regards _bhavābhava_ as 'rhythmical lengthening for _bhavabhava_ = 
repeated existence, various existences,' and not as __bhava__+_abhava_ 
(GD.n.496).

He translates it as:

- existences (Sn.v.776).

- different existences (Sn.v.786; Sn.v.801).

- various existences (Sn.v.877; Th.v.661).

- one existence after another (Sn.v.901).

- various kinds of existence (Sn.v.1060; Sn.v.1068).

In Sn.v.776 he treats _bhavesu_ and _bhavābhavesu_ as near synonyms:

- _bhavesu_: for existences

_• bhavābhavesu_: for various existences

==== PED's renderings

Duroiselle says the purpose of repetition is to express plurality, totality, 
distribution, variety, multiplicity, etc (PGPL, Para.610). PED accordingly 
renders _bhavābhava_ as 'this or that life, any form of existence, some sort 
of existence.'

=== Illustrations: renewed states of individual existence

.Illustration
====
bhavābhava

renewed states of individual existence
====

[quote, Th.v.661]
____
Fallen in time into the power of time, becoming subject to renewed states of 
individual existence, men come to suffering. Those men grieve in this world.

_Kāle kālavasaṃ pattā bhavābhavavasaṃ gatā +
Narā dukkhaṃ nigacchanti tedha socanti māṇavā._
____

- Norman: Come in time into the power of time, subject to various existences, 
men come to grief.

=== Illustrations: various states of individual existence

.Illustration
====
bhavābhavesu

various states of individual existence
====

[quote, Sn.v.776]
____
I see people in turmoil in the world, overcome by craving for states of 
individual existence, wretched characters wailing in the face of death, not 
free of craving for various states of individual existence.

_Passāmi loke pariphandamānaṃ pajaṃ imaṃ taṇhāgataṃ bhavesu +
Hinā narā maccumukhe lapanti avitataṇhāse bhavābhavesu._
____

- Norman: I see in the world this race [of mortals] floundering, obsessed with 
craving for existences. Base men wail in the jaws of death, with craving for 
various existences unallayed.

.Illustration
====
bhavābhavesu

various states of individual existence
====

• Dependent on ascetic practices and self-mortification, or on what is seen, 
heard, sensed, [or cognised], with raised voices they wail for spiritual 
purity, not free of craving for various states of individual existence. +
_Tapūpanissāya jigucchitaṃ vā atha vāpi diṭṭhaṃ vā sutaṃ mutaṃ 
vā +
Uddhaṃsarā suddhimanutthunanti avītataṇhāse bhavābhavesu_ (Sn.v.901).

- Norman: their craving for one existence after another not gone

.Illustration
====
bhavābhavesu

various states of individual existence
====

[quote, Th.v.784-5; M.2.73]
____
For because one has not gained perfection [of transcendent insight], one does 
unvirtuous deeds from undiscernment of reality in renewed states of individual 
existence.

_Avyositattā hi bhavābhavesu pāpāni kammāni karoti mohā._
____

- Norman: for because of not gaining the end in various existences (men) do 
evil actions from delusion.

- Horner: Not being accomplished in this becoming or that, they do evil deeds 
from delusion.

=== Illustrations: any state of individual existence

.Illustration
====
bhavābhavāya

any state of individual existence
====

[quote, Sn.v.496]
____
Those in whom there is no craving for anything in the world, in relation to any 
state of individual existence in this world or the world beyond, to them, at 
the right time, a brahman who is looking for merit should bestow an offering; 
he should offer them a gift.

_Yesaṃ taṇhā natthi kuhiñci loke bhavābhavāya idha vā huraṃ vā +
Kālena tesu havyaṃ pavecche yo brāhmaṇo puññapekkho yajetha._
____

Norman: But those in whom there is no craving for anything in the world, for 
various existences in this world or the next....

.Illustration
====
bhavābhavāya

any state of individual existence
====

[quote, Sn.v.1068]
____
Whatever you know, above, below, across, and also in the middle, knowing this 
to be a bond [to individual existence] in the world, do not foster craving for 
any state of individual existence.

_Yaṃ kiñci sampajānāsi uddhaṃ adho tiriyañcāpi majjhe: +
Etaṃ viditvā saṅgoti loke bhavābhavāya mākāsi taṇhan ti._
____

- Norman: do not make craving for various kinds of existences

.Illustration
====
bhavābhavesu

about any state of individual existence
====

[quote, Sn.v.786]
____
One who is spiritually purified conceives no dogmatic view about any state of 
individual existence in the world.

_Dhonassa hi natthi kuhiñci loke pakappitā diṭṭhi bhavābhavesu._
____

Norman: A purified man does not indeed form a view anywhere in the world in 
respect of different existences.

.Illustration
====
bhavābhavāya

for any state of individual existence
====

[quote, Sn.v.801]
____
One with no aspiration for any state of individual existence in either world, 
this world or the world beyond,

_Yassūbhayante paṇidhīdha natthi bhavābhavāya idhavā huraṃ vā._
____

Norman: If anyone has made no resolve in respect of both ends here, for the 
sake of different existences here or in the next world

.Illustration
====
bhavābhavāya

any state of individual existence
====

[quote, Sn.v.877]
____
The wise man is not involved with any state of individual existence.

_bhavābhavāya na sameti dhīro ti._
____

- Norman: The wise man does not go to various [renewed] existences.

=== Illustrations: all states of individual existence

.Illustration
====
bhavābhave

all states of individual existence
====

[quote, Sn.v.1060]
____
And whatever man here is wise, one who is blessed with profound knowledge, who 
has freed himself from this [wretched] bondage to all states of individual 
existence, he is free of craving, rid of spiritual defilement, and free of 
expectations [in regard to both this world and the world beyond]. He has 
overcome birth and old age, I declare.

_Vidvā ca yo vedagū naro idha bhavābhave saṅgamimaṃ visajja +
So vitataṇho anīgho nirāso atāri so jāti jaranti brūmiti._
____

- Norman: And whatever man here is knowing and has knowledge, giving up this 
attachment to various kinds of existence, he, I declare, with craving gone, 
without affliction, and without desire, has crossed over birth and old age.

- This [wretched] bondage: 'This' (_imaṃ_) has 'a touch of (often sarcastic) 
characterisation,' says PED (sv _Ayaṃ_). DOP (sv _Idaṃ_) says: 'such, like 
that (often implying contempt).'

.Illustration
====
bhavābhave

various states/all states of individual existence
====

____
Beings who are tethered [to individual existence] by the tie of craving, whose 
minds are attached to various states of individual existence... [Such] beings 
follow the round of birth and death, and go to rebirth and death.

_Taṇhāyogena saṃyuttā rattacittā bhavābhave... +
Sattā gacchanti saṃsāraṃ jātimaraṇagāmino._
____

[quote, It.50]
____
Those who have abandoned craving, being free of craving for all states of 
individual existence, are those in the world who have reached the Far Shore, 
having accomplished the destruction of perceptually obscuring states.

_Ye ca taṇhaṃ pahatvāna vītataṇha bhavābhave +
Te ca pāragatā loke ye pattā āsavakkhayan ti._
____

.Illustration
====
bhavābhave

all states of individual existence
====

[quote, M.1.108]
____
Free of craving for all states of individual existence

_bhavābhave vītataṇhaṃ._
____

- Bodhi: free from craving for any kind of being

- Horner: void of craving for becoming and non-becoming

.Illustration
====
bhavābhave

with all states of individual existence
====

[quote, Th.v.671]
____
Those who have abandoned both sensuous yearning and anger, whose minds are at 
peace with all states of individual existence

_Kāmakopappahīnā ye santacittā bhavābhave._
____

Comment:

- Norman: whose minds are calm in various existences

- The bhikkhu who has realised the Untroubled (_tassa nibbutassa bhikkhuno_) 
abandons craving for states of individual existence (_bhavataṇhā pahīyati_) 
but does not long for the cessation of individual existence (_vibhavaṃ 
nābhinandati_, Ud.32-3). So, peaceful with any state of individual existence.

=== Illustrations: from one state of individual existence to another

.Illustration
====
bhavābhavaṃ

from one state of individual existence to another
====

[quote, Thī.v.199]
____
Repeatedly, led on [by uninsightfulness into reality] from one state of 
individual existence to another in the sphere of personal identity, not 
transcending personal identity, they pursue birth and death.

_Kālaṃ kālaṃ bhavābhavaṃ sakkāyasmiṃ purakkhatā avitivattā 
sakkāyaṃ jātimaraṇasārino._
____

.Illustration
====
bhavābhavaṃ

from one state of individual existence to another
====

[quote, A.3.69]
____
Having acquiesced in [the perception of] time, are [by uninsightfulness into 
reality] led on within the round of birth and death from one state of 
individual existence to another.

_Kālaṃ gatiṃ bhavābhavaṃ saṃsārasmiṃ purakkhatā._
____

- Bodhi: 'plunged headlong into saṃsāra, [into] time, destination, and 
existence upon existence.'

