== Bhāra

=== Renderings

- _bhāra_: responsibility

- _bhāra_: load

- _bhāra_: burden

=== Illustrations

.Illustration
====
bhāraṃ

responsibility
====

[quote, A.1.84]
____
Two fools: he who shoulders a responsibility that does not fall to him, and he 
who shirks a responsibility that falls to him.

_dveme bhikkhave bālā. Katame dve? yo ca anāgataṃ bhāraṃ vahati yo ca 
āgataṃ bhāraṃ na vahati. Ime kho bhikkhave dve bālāti._
____

.Illustration
====
bhāraṃ

responsibility
====

____
The mother carries the foetus in her womb for nine or ten months with much 
anxiety for the heavy responsibility.

_Tamenaṃ bhikkhave mātā nava vā dasa vā māse gabbhaṃ kucchinā 
pariharati mahatā saṃsayena garumbhāraṃ_
____

[quote, M.1.266]
____
Then after nine or ten months, the mother gives birth with much anxiety for the 
heavy responsibility.

_Tamenaṃ bhikkhave mātā navannaṃ vā dasannaṃ cā māsānaṃ accayena 
vijāyati mahatā saṃsayena garumbhāraṃ._
____

.Illustration
====
bhārassa

load
====

[quote, S.4.177]
____
One greases an axle only for the sake of transporting a load.

_Seyyathā vā pana akkhaṃ abbhañjeyya yāvadeva bhārassa nitraṇatthāya._
____

.Illustration
====
bhāraṃ

load
====

[quote, M.3.95]
____
A man came carrying a load of water.

_atha puriso āgaccheyya udakabhāraṃ ādāya._
____

.Illustration
====
khāribhāro

load
====

[quote, S.1.169]
____
Conceit, O brahman, is your shoulder-load.

_Māno hi te brāhmaṇa khāribhāro._
____

.Illustration
====
bhāro

burden
====

____
And how is the bhikkhu a Noble One whose banner is lowered, whose burden [of 
the five grasped aggregates] is laid down__,__ who is emancipated [from 
individual existence]?

_Kathañca bhikkhave bhikkhu ariyo pannaddhajo pannabhāro visaṃyutto hoti?_
____

[quote, M.1.139]
____
In this regard a bhikkhu has abandoned self-centredness.

_Idha bhikkhave bhikkhuno asmimāno pahīno hoti._
____

.Illustration
====
bhāro

burden
====

[quote, S.3.26]
____
And what is the burden? The five grasped aggregates, one should reply

_Katamo ca bhikkhave bhāro pañcupādānakkhandhātissa vacanīyaṃ._
____

.Illustration
====
bhāra

burden
====

[quote, Th.v.708]
____
When the conduit to renewed states of individual existence is destroyed in this 
lifetime in accordance with truth, there is no fear of death, which is like 
casting off a burden..

_Khīṇāya bhavanettiyā diṭṭhe dhamme yathātathe +
Na bhayaṃ maraṇe hoti bhāranikkhepane yathā._
____

