== Bhūta

=== Renderings

- _bhūta_: brought about

- _bhūta_: what is brought about

- _bhūta_: brought into existence

- _bhūta_: true

=== Introduction

==== Past participles: past and passive

_Bhūta_ is the past participle of _bhavati_. Duroiselle says past participles 
are principally of past and passive meaning (PGPL, para.360). Therefore we 
render _bhūta_ as 'brought about.'

==== The bhūtamidan ti reflection

_Bhūta_ is of particular interest because it is the basis of this reflection:

____
-- Bhikkhus, do you see, 'This is brought about?'

_bhūtamidan ti bhikkhave passathā ti?_
____

-- Yes, bhante

____
-- Bhikkhus, do you see: 'It is arisen with that as its nourishing condition'?

_tadāhārasambhavan ti bhikkhave passathā ti?_
____

-- Yes, bhante

____
-- Bhikkhus, do you see: 'With the ending of that nourishing condition, what is 
brought about is destined to cease'?

_tadāhāranirodhā yaṃ bhūtaṃ taṃ nirodhadhamman ti bhikkhave passathā 
ti?_
____

-- Yes, bhante (M.1.260).

=== Illustrations

.Illustration
====
bhūtaṃ

what is brought about
====

____
How do those who are clear-sighted see [the nature of reality]?

_Kathañca bhikkhave cakkhumanto passanti?_
____

____
In this regard a bhikkhu sees what is brought about as what is brought about.

_Idha bhikkhu bhūtaṃ bhūtato passati_
____

____
Seeing what is brought about thus, he applies himself to disillusionment with 
what is brought about, to non-attachment to what is brought about, and to the 
ending of what is brought about.

_bhūtaṃ bhūtato disvā bhūtassa nibbidāya virāgāya nirodhāya 
paṭipanno hoti._
____

____
This is what the Blessed One said, and in connection with which he added:

_Etamatthaṃ bhagavā avoca. Tatthetaṃ iti vuccati_
____

____
Those who see what is brought about as what is brought about,

_ye bhūtaṃ bhūtato disvā_
____

____
Transcending what is brought about,

_bhūtassa ca atikkamā_
____

____
Are liberated [from perceptually obscuring states] according to reality

_yathābhūte vimuccanti_
____

• Having destroyed craving for states of individual existence ** +
**__☸ bhavataṇhāparikkhayā__

____
When a bhikkhu has profoundly understood what is brought about as such,

_sa ve bhūtapariñño_
____

____
Being free of craving for all states of individual existence,

_so vītataṇho bhavābhave_
____

____
With the cessation of what is brought about [at death]

_bhūtassa vibhavā_
____

[quote, It.44]
____
He comes not to renewed states of individual existence

_bhikkhu nāgacchati punabbhavan ti._
____

.Illustration
====
bhūtassa

brought about
====

____
If the visual sense is operational and visible objects come into its range, and 
there is an operative interaction between them, then the appropriate class of 
advertence is manifested.

_ajjhattikañce cakkhuṃ aparibhinnaṃ hoti bāhirā ca rūpā āpāthaṃ 
āgacchanti tajjo ca samannāhāro hoti evaṃ tajjassa viññāṇabhāgassa 
pātubhāvo hoti_
____

[quote, M.1.191]
____
The bodily form in whatever is thus brought about comprises the aggregate of 
grasped bodily form.

_Yaṃ tathābhūtassa rūpaṃ taṃ rūpūpādānakkhandhe saṅgahaṃ 
gacchati._
____

.Illustration
====
bhūtaṃ

brought about
====

[quote, It.44]
____
Those who see what is brought about as what is brought about, transcending what 
is brought about, are liberated [from perceptually obscuring states] according 
to reality, having destroyed craving for states of individual existence.

_Ye bhūtaṃ bhūtato disvā bhūtassa ca atikkamā +
Yathābhūte vimuccanti bhavataṇhāparikkhayā._
____

.Illustration
====
bhūtaṃ

brought about
====

____
-- 'Had it not been, it would not have been "mine." It will be not; not "mine" 
will it be.'

_no c'assa no ca me siyā na bhavissati na me bhavissati._
____

[quote, A.4.75]
____
That which is, that which is brought about, that I abandon._

_Yadatthi yaṃ bhūtaṃ taṃ pajahāmīti._
____

.Illustration
====
bhūtaṃ

brought about
====

[quote, It.37]
____
What is born, brought about, arisen, produced, originated, unenduring, 
conjoined with old age and death, a hotbed of illnesses, easily destroyed, 
having existential nourishment as its support and source: it is not fit to be 
delighted in._

_Jātaṃ bhūtaṃ samuppannaṃ kataṃ saṅkhatamaddhuvaṃ +
Jarāmaraṇasaṅghātaṃ roganiḍḍhaṃ pabhaṅguṇaṃ +
Āhāranettippabhavaṃ nālaṃ tadabhinandituṃ._
____

.Illustration
====
bhūtaṃ

brought about
====

[quote, It.61]
____
From whatever is brought about, originated, dependently arisen, the ending [of 
originated phenomena] is the deliverance._

_Yaṃ kho pana kiñci bhūtaṃ saṅkhataṃ paṭiccasamuppannaṃ nirodho 
tassa nissaraṇaṃ._
____

.Illustration
====
bhūtā

brought about
====

[quote, A.5.186-7]
____
That view is brought about, contrived, thought out, and dependently arisen.

_sā kho panesā diṭṭhi bhūtā saṅkhatā cetayitā paṭiccasamuppannā._
____

.Illustration
====
bhūtaṃ

brought about
====

[quote, S.5.164]
____
How could it be that what is born, brought about, originated, destined to 
decay, not decay? It is not possible._

_Taṃ kutettha bhikkhave labbhā yaṃ taṃ jātaṃ bhūtaṃ saṅkhataṃ 
palokadhammaṃ taṃ vata mā palujjīti netaṃ ṭhānaṃ vijjati._
____

.Illustration
====
bhūtānaṃ

brought into existence
====

[quote, S.2.101]
____
Bhikkhus, there are these four kinds of existential nourishment for the 
maintenance of beings that have been brought into existence and for the 
assistance of those about to arise [into new existence]. What four?_

_Cattārome bhikkhave āhārā bhūtānaṃ vā sattānaṃ ṭhitiyā 
sambhavesīnaṃ vā anuggahāya._
____

Comment:

Norman views _sambhavesīnaṃ_ as the future active participle in -_esin_ 
(Elders Verses I, n.527), to be translated with the words 'about to.'

.Illustration
====
bhūtā

true
====

[quote, D.3.272-3]
____
That makes ten teachings which are true, factual, correct, not incorrect, not 
mistaken, fully awakened to by the Perfect One.

_Iti ime dasa dhammā bhūtā tacchā tathā avitathā anaññathā sammā 
tathāgatena abhisambuddhā._
____

