== Brahmacariya

=== Renderings

- _brahmacariya_: religious life

- _brahmacariya_: celibate life

- _brahmacariya_: celibacy

- _brahmacariya_: the practice of celibacy

- _brahmacārino_: celibate

- _abrahmacāriṃ_: not celibate

=== Introduction

==== Brahmacariya: religious life

The religious life (_brahmacariya_) is practised by all the Buddha's disciples, 
whether ordained or not, whether celibate or not. Thus:

1. Sakka, surrounded by nymphs called Moggallāna his _sabrahmacārī_:

- _Sabrahmacārī me eso āyasmā mahāmoggallāno ti_ (M.1.255).

2. Māra invited the Buddha to return to lay life, and called it 
_brahmacariyaṃ_:

[quote, Sn.v.428]
____
'By living the religious life, by making offerings to the sacrificial fire, 
much merit will be heaped up by you.

_Carato ca te brahmacariyaṃ aggihuttañca juhato +
Pahūtaṃ cīyate puññaṃ kiṃ padhānena kāhasi._
____

==== Brahmacariya: celibate life

The celibate life (_brahmacariya_) is practised by all ordained disciples, and 
by some lay disciples. For arahants celibacy means avoiding all forms of 
sexuality including sexual thoughts, which is a blemish of the celibate life 
(_Idampi kho brāhmaṇa brahmacariyassa khaṇḍampi chiddampi sabalampi 
kammāsampi_: see _Methuna Sutta_, A.4.54).

==== Action noun: 'the practice of celibacy'

_Brahmacariya_ means 'religious life', 'celibate life', or 'celibacy'. But 
where the context implies an action noun, it means 'the practice of celibacy.' 
For 'religious life' to become an action noun, it is usually paired with an 
action noun. For example: _Carato ca te brahmacariyaṃ_ ('By living the 
religious life,' Sn.v.428).

So, consider three passages:

1. Austerity; the practice of celibacy; insight into the noble truths; the 
realisation of the Untroubled: this is supremely auspicious.
+
****
_Tapo ca brahmacariyañca ariyasaccāna dassanaṃ +
****
Nibbānasacchikiriyā ca etaṃ maṅgalamuttamaṃ_ (Th.v.267).

2. The practice of celibacy: this they call the supreme power.
+
****
_Brahmacariyaṃ etadāhu vasuttamaṃ_ (Sn.v.274).
****

3. Unrestraint of the sense faculties is an obstacle to the practice of 
celibacy.
+
****
_indriyāsaṃvaro brahmacariyassa paripantho_ (A.5.136).
****

=== Illustrations

.Illustration
====
brahmacariyaṃ

celibate life
====

[quote, A.3.146]
____
He lives the celibate life disgruntled...lives the celibate life with delight _

_anabhirato... abhirato ca brahmacariyaṃ carati._
____

.Illustration
====
brahmacārino

celibate; brahmacariyaṃ, religious life
====

____
If, Master Gotama, the only people who fulfilled this teaching were Master 
Gotama himself, together with

_sace hi bho gotama imaṃ dhammaṃ bhavañceva gotamo ārādhako abhavissa_
____

____
his bhikkhus, and

_bhikkhū ca ārādhakā abhaviṃsu_
____

____
bhikkhunīs, and

_bhikkhuniyo ca ārādhikā abhaviṃsu_
____

____
celibate men lay followers clothed in white, and

_upāsakā ca gihī odātavasanā brahmacārino ārādhakā abhaviṃsu_
____

____
non-celibate men lay followers clothed in white, and

_upāsakā ca gihī odātavasanā kāmabhogino ārādhakā abhaviṃsu_
____

____
celibate women lay followers clothed in white,

_upāsikā ca gihiniyo odātavasanā brahmacāriṇiyo ārādhikā abhaviṃsu_
____

[quote, M.1.493]
____
but there were no non-celibate women lay followers clothed in white who 
fulfilled it, then this religious life would be deficient in that respect;

_no ca kho upāsikā gihiniyo odātavasanā kāmabhoginiyo ārādhikā 
abhaviṃsu evamidaṃ brahmacariyaṃ aparipūraṃ abhavissa tenaṅgena._
____

.Illustration
====
abrahmacāriṃ

not celibate
====

[quote, Ud.52]
____
And the Venerable MahāMoggallāna saw that person sitting in the midst of the 
assembly of bhikkhus -- unvirtuous, of an unvirtuous moral nature, of foul and 
odious behaviour, secretive in conduct, no ascetic though pretending to be one, 
not celibate though pretending to be so, spiritually rotten, full of 
defilement, and morally decayed.

_Addasā kho āyasmā mahāmoggallāno taṃ puggalaṃ dussīlaṃ 
pāpadhammaṃ asucisaṅkassarasamācāraṃ paṭicchannakammantaṃ 
assamaṇaṃ samaṇapaṭiññaṃ abrahmacāriṃ brahmacārīpaṭiññaṃ 
antopūtiṃ avassutaṃ kasambujātaṃ majjhe bhikkhusaṅghassa nisinnaṃ._
____

.Illustration
====
brahmacariyañca

celibacy
====

____
He amongst them who was supremely devout, being unwavering in application [to 
his practice], refrained from sexual intercourse even in a dream.

_Yo nesaṃ paramo āsi brahmā daḷhaparakkamo +
Sa vāpi methunaṃ dhammaṃ supinantepi nāgamā_
____

[quote, Sn.v.293-294]
____
Some of the wise amongst them following his religious practices praised 
celibacy; virtue; and also patience.

_Tassa vattamanusikkhantā idheke viññujātikā +
Brahmacariyañca sīlañca khantiñcāpi avaṇṇayuṃ._
____

.Illustration
====
brahmacariyaṃ

religious life
====

[quote, Sn.v.289]
____
For forty-eight years they lived the religious life as virgins.

_Aṭṭhacattārīsaṃ vassāni komāraṃ brahmacariyaṃ cariṃsu te._
____

.Illustration
====
brahmacariyaṃ

religious life
====

[quote, Vin.1.12]
____
'Come, bhikkhu. Well explained is the teaching. Live the religious life for 
making a complete end of suffering.'

_Svākkhāto dhammo. Cara brahmacariyaṃ sammā dukkhassa antakiriyāyā ti._
____

.Illustration
====
brahmacariyaṃ

religious life
====

[quote, Ud.57]
____
According to the teaching Master Mahākaccāna teaches, it's not easy living at 
home to perfectly practice the religious life. How about if I shaved off my 
hair and beard, and went forth from the household life into the ascetic life?

_Yathā yathā kho ayyo mahākaccāyano dhammaṃ deseti nayidaṃ sūkaraṃ 
agāraṃ ajjhāvasatā ekantaparipuṇṇaṃ ekantaparisuddhaṃ 
saṅkhalikhitaṃ brahmacariyaṃ carituṃ. Yannūnāhaṃ kesamassuṃ 
ohāretvā kāsāyāni vatthāni acchādetvā agārasmā anagāriyaṃ 
pabbajeyyanti.._
____

.Illustration
====
sabrahmacāriṃ

a companion in the religious life
====

[quote, D.3.284-5]
____
One lives in spiritual discipleship under the Teacher or a companion in the 
religious life of the standing of a teacher

_satthāraṃ vā upanissāya viharati aññataraṃ vā garuṭṭhāniyaṃ 
sabrahmacāriṃ._
____

.Illustration
====
brahmacariyaṃ

religious life
====

[quote, S.4.314-5]
____
"Then, headman, just like the field of middling quality are the male and female 
lay followers to me. To them too I explain a teaching which is excellent in the 
beginning, the middle, and the end, whose spirit and letter proclaim the 
utterly complete and pure religious life.

_Seyyathāpi gāmaṇi yaṃ aduṃ khettaṃ majjhimaṃ evameva mayhaṃ 
upāsakaupāsikāyo. Tasempahaṃ dhammaṃ desemi ādikalyāṇaṃ 
majjhekalyāṇaṃ pariyosānakalyāṇaṃ sātthaṃ savyañjanaṃ kevala 
paripuṇṇaṃ parisuddhaṃ brahmacariyaṃ pakāsemi._
____

.Illustration
====
brahmacariyaṃ

religious life
====

The Buddha said that brahmans and householders are helpful in providing 
bhikkhus with robe material, almsfood, abodes, and therapeutic requisites. 
Bhikkhus are very helpful in explaining the teaching, and proclaiming the 
religious life in its complete purity. Thus the religious life is lived with 
the help of each other (_aññamaññaṃ nissāya brahmacariyaṃ vussati_) 
(It.111).

.Illustration
====
brahmacariyaṃ

religious life
====

• Those teachings which are excellent in the beginning, the middle, and the 
end, whose spirit and letter proclaim the utterly complete and pure religious 
life. +
_ye te dhammā ādikalyāṇā majjhekalyāṇā pariyosānakalyāṇā 
sātthaṃ savyañjanaṃ kevalaparipuṇṇaṃ parisuddhaṃ brahmacariyaṃ 
abhivadanti_ (Vin.2.96).

