== Brāhmaṇa

=== Renderings

- _brāhmaṇa_: brahman (=member of the brahman social class)

- _brāhmaṇa_: Brahmanist (=adherent of the religion of the brahmans)

- _brāhmaṇa_: Brahman (=arahant, or one striving to be an arahant)

=== Introduction

==== Brāhmaṇa and the four classes: lower case

In the Buddha's time, Indian society had four classes: _khattiyas,_ brahmans, 
_vessas,_ and _suddas_ (M.2.150). These four classes were not technically 
castes because intermarriage was still possible. Some grammarians would 
capitalise these groups. For example, Wikipedia says:

- 'Varna may be translated as "class," and refers to the four social classes 
which existed in the Vedic society, namely Brahmins, Kshatriyas, Vaishyas and 
Shudras.' http:// en.wikipedia.org/wiki/Caste_system_in_India

Many dictionaries say likewise. However, the Economist Style Guide supports us 
in saying:

- 'Indian castes are lower case italic, except for brahman, which has now 
become an English word and is therefore lower case roman (unless it is 
mentioned along with several other less familiar caste names in italic)' (www. 
economist.com/style-guide/capitals).

==== Brāhmaṇa as a religious term

In a religious context, we use the term 'Brahmanist.' Most translators would 
call this 'Brahman,' but we reserve capitalised 'Brahman' for arahants. 
Although unusual, Brahmanist is well-recognised:

- Brahmanist: an adherent of the religion of the brahmans (https:// 
en.wiktionary.org/wiki/Brahmanist).

We capitalise Brahmanist in accordance with established style manuals:

- Capitalization of religious terms: Baha'i, Baptist, Brahman, Buddhist... 
Hindu; Hinduism, Islam; Islamic, Jewish... (U.S. Government Printing Office 
Style Manual, 2008).

==== Brāhmaṇa: Brahman (=arahant, or one striving to be an arahant)

Where _brāhmaṇa_ means arahant, we capitalise it: Brahman. But sometimes 
_brāhmaṇa_ is applied to those still striving to be Brahmans. Two examples:

[quote, Dh.v.389]
____
One should not strike a Brahman. [Likewise], a Brahman should not vent 
[wrath on his assailant]. Shame on the one who strikes a Brahman! And shame on 
[the Brahman] who vents [wrath on his assailant]!

_Na brāhmaṇassa pahareyya nāssa muñcetha brāhmaṇo +
Dhī brāhmaṇassa hantāraṃ tato dhī y'assa muñcati._
____

This, of course, means one should not strike an arahant, and one who is 
striving to be an arahant should not vent his wrath.

[quote, Dh.v.390]
____
It is not worse for a Brahman when his mind is restrained from agreeable 
things. The more his mind turns away from agreeable things the more his 
miseries subside.

_Na brāhmaṇassetadakiñci seyyo yadā nisedho manaso piyehi +
Yato yato hiṃsamano nivattati tato tato sammatimeva dukkhaṃ._
____

Here again, where his miseries are still subsiding, _brāhmaṇa_ means 'one 
striving to be a Brahman.'

=== Illustrations

.Illustration
====
brāhmaṇā

brahman
====

[quote, Ud.51]
____
Those of the four castes, _khattiyas_, brahmans, _vessas_, and _suddas_, having 
gone forth from the household life into the ascetic life in the teaching and 
training system made known by the Perfect One, give up their former names and 
identities and are just called 'ascetic disciples of the Sakyans' Son.'

_cattāro me vaṇṇā khattiyā brāhmaṇā vessā suddā te 
tathāgatappavedite dhammavinaye agārasmā anagāriyaṃ pabbajitvā jahanti 
purimāni nāmagottāni samaṇā sakyaputtiyātveva saṅkhaṃ gacchantī._
____

.Illustration
====
brāhmaṇā

brahman
====

____
'Prosperous countries and kingdoms rendered honour to those brahmans with 
garments of various colours, with beds and residences.

_Nānārattehi vatthehi sayanehāvasathehi ca +
Phītā janapadā raṭṭhā te namassiṃsu brāhmaṇe_
____

____
'Brahmans were unpunishable, unimpeachable, protected by law. No one obstructed 
them in any way, even at the doors of their homes.

_Avajjhā brāhmaṇā āsuṃ ajeyyā dhammarakkhitā +
Na te koci nivāresi kuladvāresu sabbaso_
____

____
'For forty-eight years they lived the religious life as virgins. In those days 
the brahmans undertook the search for Vedic knowledge and virtuous conduct.

_Aṭṭhacattārīsaṃ vassāni komāraṃ brahmacariyaṃ cariṃsu te +
Vijjācaraṇapariyeṭṭhiṃ acaruṃ brāhmaṇā pure_
____

[quote, Sn.v.287-290]
____
'Brahmans did not couple with women of other [castes]. They did not buy wives. 
Their living together was through mutual affection, having come together for 
mutual pleasure.

_Na brāhmaṇā aññamagamuṃ napi bhariyaṃ kiṇiṃsu te +
Sampiyeneva saṃvāsaṃ saṅgantvā samarocayuṃ._
____

.Illustration
====
brāhmaṇā

brahman
====

____
If the rebirth of one's individuality occurs in a clan of brahmans, one is 
reckoned as a brahman.

_Brāhmaṇakule ce attabhāvassa abhinibbatti hoti brāhmaṇotveva 
saṅkhaṃ gacchati_
____

[quote, M.2.181]
____
If the rebirth of one's individuality occurs in a clan of _vessas_, one is 
reckoned as a _vessa_.

_Vessakule ce attabhāvassa abhinibbatti hoti vessotveva saṅkhaṃ gacchati._
____

.Illustration
====
brāhmaṇā

Brahmanists
====

[quote, Sn.v.529]
____
'Having investigated the entire scriptural collections both of the ascetics and 
the Brahmanists, free of attachment to all sense impression, gone beyond all 
scriptural knowledge, he is blessed with profound knowledge.

_Vedāni viceyya kevalāni samaṇānaṃ yānidhatthi brāhmaṇānaṃ +
Sabbavedanāsu vītarāgo sabbaṃ vedamaticca vedagū so._
____

.Illustration
====
brāhmaṇā

Brahmanists
====

[quote, Sn.p.103]
____
'He makes known [the nature of] this world [of beings] with its devas, māras, 
and brahmās, in the world of mankind with its ascetics and Brahmanists, its 
royalty and commoners, having realised it for himself through transcendent 
insight.'

_So imaṃ lokaṃ sadevakaṃ samārakaṃ sabrahmakaṃ 
sassamaṇabrāhmaṇiṃ pajaṃ sadevamanussaṃ sayaṃ abhiññā 
sacchikatvā pavedeti._
____

.Illustration
====
brāhmaṇā

Brahman
====

[quote, Ud.5]
____
One whose _āsavas_ are destroyed, and who is free of spiritual flaws, he is 
what I call a Brahman.

_Khīṇāsavaṃ vantadosaṃ tamahaṃ brūmi brāhmaṇan ti._
____

