== Camma

=== Renderings

- _camma_: fascia

- _camma_: hide

- _camma_: an animal's skin

- _camma_: leather

- _camma_: leather shield

- _camma_: leather soundboard

=== Introduction

==== Chavi and camma: human skin and fascia

_Chavi_ and _camma_ are the superficial and deep layers of human integument. In 
translation they are usually called 'outer skin' and 'inner skin.' We will show 
that in humans:

1. _chavi_ is skin

2. _camma_ is fascia.

Fascia lies below skin. Fascia is not skin.

==== Cammi: animal hide

In animals, _cammi_ is equivalent to English 'hide' because it means not only 
the skin of the living animal, but also the leather produced from that skin. 
Animals do not have _chavi_. In animals, hair grows on _cammi_; in humans it 
grows on _chavi_.

[quote, A.2.114]
____
Again, one kind of noble thoroughbred horse is not quickened nor does it 
acquire an earnest attitude [to its work] when it sees the shadow of the goad, 
nor when its hairs (_loma_) are struck by the goad, nor when its hide (_camma_) 
is struck by the goad. Only when its bone is struck by the goad is it quickened 
and it acquires an earnest attitude [to its work].

_Puna ca paraṃ bhikkhave idhekacco bhadro assājānīyo na heva kho 
patodacchāyaṃ disvā saṃvijjati saṃvegaṃ āpajjati napi 
lomavedhaviddho saṃvijjati saṃvegaṃ āpajjati. Napi cammavedhaviddho 
saṃvijjati saṃvegaṃ āpajjati. Api ca kho aṭṭhivedhaviddho 
saṃvijjati saṃvegaṃ āpajjati._
____

[quote, Vin.1.218]
____
At the moment the Blessed One saw her, that extensive wound was healed, and 
(her thigh became covered in) healthy skin (_chavi_) with hairs (_loma_) 
growing on it.

_Tassā sahadassanena bhagavato tāva mahāvaṇo rūḷho ahosi succhavi 
lomajāto._
____

==== Integumentary system

The integumentary system is the two layers that cover human bodies. The outer 
layer is 'skin,' and the inner layer is called by anatomists either:

1. subcutaneous tissue, or

2. hypodermis, or

3. superficial fascia.

'Skin' is comprised of epidermis and dermis. In animals, dermis, the lower part 
of skin, is the source of leather. Dermis rests on superficial fascia.

If skin is removed, it leaves superficial fascia (or 'hypodermis' or 
'subcutaneous tissue'). This superficial fascia is the lowermost layer of the 
integumentary system.

==== Anatomical dissection of the integumentary system

In the anatomical dissection of the integumentary system, skin is first 
stripped from superficial fascia. Consider these quotes:

- 'Incisions will be made on the back, and four large flaps of skin will be 
reflected laterally, exposing an underlying fatty layer known as superficial 
fascia' (http:// wings.buffalo.edu/smbs/ana/first.htm).

- 'Place the cat on its ventral surface. Massage the skin of the dorsal neck 
region to separate it from the underlying muscles and make a small longitudinal 
slit through the skin in the midline. Do not cut through the superficial fascia 
under the skin' (http:// core.ecu.edu/biol/singhasc/cat-muscles.htm).

References:

(http:// en.wikipedia.org/wiki/Subcutaneous_tissue).

(http:// en.wikibooks.org/wiki/Human_Physiology/Integumentary_System).

==== Dissection of the integumentary system by Prince Pāyāsi

Prince Pāyāsi dissected the integumentary system like this:

[quote, D.2.338]
____
Then I tell them to strip away the man's skin (_chaviṃ_), and perhaps we 
shall see his soul emerging. They do so, but we do not see any soul emerging. 
Then I tell them to strip away his fascia (_cammaṃ_), and perhaps we shall 
see his soul emerging.

_Tyāhaṃ evaṃ vadāmi tena hi bho imassa purisassa chaviṃ chindatha 
appevanāmassa jīvaṃ passeyyāmā ti. Te tassa purisassa chaviṃ chindanti 
nevassa mayaṃ jīvaṃ passāma. Tyāhaṃ evaṃ vadāmi tena hi bho imassa 
purisassa cammaṃ chindatha appevanāmassa jīvaṃ passeyyāmā ti._
____

==== Three types of fascia

Superficial fascia is the connective tissue and fat under skin. It is attached 
to deep fascia and visceral fascia. Fascia is therefore of three types:

1. superficial fascia: underlies skin (=hypodermis or subcutaneous tissue).

2. deep fascia: surrounds muscles, bones, nerves and blood vessels.

3. visceral fascia: suspends organs within their cavities.

Fascia has been called 'the biological fabric that holds us together.'

In this Glossary we call superficial fascia 'fascia,' because it is obvious 
which fascia we mean.

Reference: www. anatomytrains.com/fascia.

==== Leather: dermis not fascia

Like humans, animal integument has these layers:

1. epidermis (1% of integument thickness)

2. dermis (85% of integument thickness)

3. fascia (14% of integument thickness)

To produce leather:

1. The epidermis with hair and fur is removed (except by furriers).

2. The fascia is removed.

3. The dermis is processed to obtain leather.

Stripping epidermis from dermis is a complicated process.

Reference: www. leatherresource.com/whatisleather.html.

==== Camma: leather goods

_Camma_ ('hide') and _cammakhaṇḍaṃ_ ('piece of hide') are sometimes used 
as the name of leather objects. For example, _camma_ can mean 'leather shield' 
or 'leather soundboard.' _Cammakhaṇḍa_ can mean 'leather bucket' 
(Vin.2.122) or 'leather mat' (Vin.4.41).

==== Taco

_Taca_ is practically equivalent to _chavi_ (i.e. comprised of epidermis plus 
dermis):

[quote, A.3.323]
____
this very body... covered in skin (_taca_).

_imameva kāyaṃ... tacapariyantaṃ._
____

[quote, Sn.v.17]
____
as a snake sheds its old, worn-out skin (_tacaṃ_).

_urago jiṇṇamiva tacaṃ purāṇaṃ._
____

[quote, Sn.v.551]
____
a bhikkhu with golden skin (_taco_) is good to look at.

_Kalyāṇadassano bhikkhu kañcanasannibhattaco._
____

=== Illustrations

.Illustration
====
camman

fascia
====

[quote, D.2.164]
____
When the Blessed One's body was burned, of whatever had been skin, fascia, 
flesh, sinews, and synovial fluid, neither soot nor ash was discernable; only 
bony ashes remained.

_Jhāyamānassa kho pana bhagavato sarīrassa yaṃ ahosi chavī ti vā camman 
ti vā maṃsan ti vā naharū ti vā lasikā ti vā tassa neva chārikā 
paññāyittha na masi sarīrāneva avasissiṃsu._
____

.Illustration
====
cammaṃ

fascia
====

[quote, S.2.238]
____
Suppose a strong man wrapped both one's leg with a strong horsehair rope and 
pulled it tight, it would cut through the skin, the fascia, the flesh, the 
sinews, and the bone, until it reached the marrow..

_Seyyathā pi bhikkhave balavā puriso daḷhāya vālarajjuyā jaṅghaṃ 
veṭhetvā ghaṃseyya sā chaviṃ chindeyya chaviṃ chetvā cammaṃ 
chindeyya cammaṃ chetvā maṃsaṃ chindeyya maṃsaṃ chetvā nahāruṃ 
chindeyya nahāruṃ chetvā aṭṭhiṃ chindeyya aṭṭhiṃ chetvā 
aṭṭhimiñjaṃ āhacca tiṭṭheyya._
____

.Illustration
====
cammaṃ

fascia
====

[quote, Vin.1.83]
____
Love for sons, bhante, cuts through the skin, the fascia, the flesh, the 
sinews, and the bone, till it reaches the marrow.

_Puttapemaṃ bhante chaviṃ chindati. Chaviṃ chetvā cammaṃ chindati. 
Cammaṃ chetvā maṃsaṃ chindati. Maṃsaṃ chetvā nāhāruṃ chindati. 
Nahāruṃ chetvā aṭṭhiṃ chindati. Aṭṭhiṃ chetvā 
aṭṭhimiñjaṃ āhacca tiṭṭhati.._
____

.Illustration
====
cammaṃ

hide
====

[quote, M.3.105]
____
A bull's hide stretched with a hundred stakes so it is wrinkle-free.

__āsabhacammaṃ saṅkusatena suvihataṃ vigatavalikaṃ._
____

.Illustration
====
camma

hide
====

[quote, M.3.274-5]
____
Having removed the hide and then covered the cow again with the same hide, he 
might say 'This cow is joined to the hide just as it was before.'

_vidhunitvā bāhiraṃ cammakāyaṃ teneva cammena taṃ gāviṃ 
paṭicchādetvā evaṃ vadeyya tathevāyaṃ gāvī saṃyuttā imināva 
cammenā ti._
____

.Illustration
====
cammaṃ

hide
====

[quote, Vin.1.193]
____
Then that unvirtuous lay-follower, having slaughtered that calf, having skinned 
it ('removed its hide'), gave it to that unvirtuous bhikkhu.

_Atha kho so pāpūpāsako taṃ vacchakaṃ vadhitvā cammaṃ vidhunitvā 
tassa pāpabhikkhuno pādāsi._
____

.Illustration
====
camma

skin
====

[quote, A.4.393]
____
Eighty-four thousand chariots with upholstery of lion skins, tiger skins, 
leopard skins

_Caturāsīti rathasahassāni adāsi sīhacammaparivārāni 
vyagghacammaparivārāni dīpicammaparivārāni._
____

.Illustration
====
camma

skin
====

[quote, Vin.1.192]
____
Now at that time the Group-of-Six bhikkhus thinking, "High beds and luxurious 
covers are objected to by the Blessed One," used large skins: a lion's skin, a 
tiger's skin, a leopard's skin

_Mahācammāni dhārenti. Sīhacammaṃ byagghacammaṃ dipīcammaṃ._
____

.Illustration
====
cammaṃ

leather shield
====

[quote, M.2.99]
____
The robber Angulimala, having grabbed his sword and leather shield

_coro aṅgulimālo asicammaṃ gahetvā._
____

.Illustration
====
cammaṃ

leather soundboard
====

[quote, S.4.197]
____
'This lute, sire, consists of numerous components, a great many components, and 
it gives a sound when its numerous components are played upon; that is, in 
dependence on the body, the leather soundboard, the stem, the pegbox, the 
strings, the plectrum, and the appropriate effort of the musician.

_ayaṃ kho bhante vīṇā nāma anekasambhārā mahāsambhārā anekehi 
sambhārehi samāraddhā vadati seyyathīdaṃ doṇiñca paṭicca cammañca 
paṭicca daṇḍañca paṭicca upaveṇañca paṭicca tantiyo ca paṭicca 
koṇañca paṭicca purisassa ca tajjaṃ vāyāmaṃ paṭicca._
____

Comment:

The first guitar-like instrument was the tanbur. It was built of polished 
cedar, had a soundboard made of leather, and resembled a crude guitar. http:// 
gibsonguitarek.wikispaces.com/

