== Cetovimutti; Paññāvimutti

=== Renderings

- _cetovimutti_: liberation [from perceptually obscuring states]

- _cetovimutti_: liberation [from attachment through inward calm]

- _paññāvimutti_: liberation [from uninsightfulness] through penetrative 
discernment

=== Introduction

==== Cetovimutti (when without paññāvimutti)

In contexts without _paññāvimutti_, _cetovimutti_ means 'liberation [from 
perceptually obscuring states].' This can be demonstrated in two steps:

1. _Cetovimutti_ means freedom from attachment, hatred, and undiscernment of 
reality.
+
[quote, S.4.296-7]
____
Now that unshakeable liberation [from perceptually obscuring states] is void of 
attachment, void of hatred, void of undiscernment of reality.

_sā kho panākuppā cetovimutti suññā rāgena suññā dosena suññā 
mohena._
____

2. Freedom from attachment, hatred, and undiscernment of reality means 
liberation from perceptually obscuring states:

[quote, S.5.8]
____
The elimination of attachment, hatred, and undiscernment of reality: the 
destruction of perceptually obscuring states is spoken of in that way.

_rāgavinayo dosavinayo mohavinayo ti āsavānaṃ khayo tena vuccatī ti._
____

==== Cetovimutti: often not arahantship

_Cetovimutti_ usually does not mean arahantship:

[quote, D.3.248]
____
If the liberation [from perceptually obscuring states] through [unlimited, 
all-encompassing] goodwill is developed and cultivated, it is impossible, out 
of the question, that ill will would plague your mind.

_Aṭṭhānametaṃ āvuso anavakāso yaṃ mettāya cetovimuttiyā 
bhāvitāya bahulīkatāya... atha ca panassa vyāpādo cittaṃ pariyādāya 
ṭhassatī ti._
____

Where it does mean arahantship, it is called unshakeable (_akuppā 
cetovimutti_). See next paragraph.

==== Cetovimutti: temporary or permanent

_Cetovimutti_ may mean temporary or permanent liberation [from perceptually 
obscuring states]:

[quote, S.1.120]
____
Then Venerable Godhika, abiding diligently, vigorously, and resolutely applied 
&#8203;[to the practice] attained temporary liberation [from perceptually obscuring 
states]. But then Venerable Godhika fell away from that temporary liberation 
&#8203;[from perceptually obscuring states].

_Atha kho āyasmā godhiko appamatto ātāpī pahitatto viharanto sāmayikaṃ 
cetovimuttiṃ phusi. Atha kho āyasmā godhiko tāya sāmayikāya 
cetovimuttiyā parihāyi._
____

[quote, D.3.272-3]
____
Which one thing should be realised? Unshakeable liberation [from perceptually 
obscuring states].

_Katamo eko dhammo sacchikātabbo? Akuppā cetovimutti._
____

==== Cetovimutti plus paññāvimutti

When _cetovimutti_ occurs with _paññāvimutti_ it has a different 
meaning. _Paññāvimutti_ never occurs without _cetovimutti_, so has a single 
meaning. Here we will consider their meanings when they occur together, in the 
light of the eleventh _Bālavaggo_ sutta, where they correspond to _samatha_ 
and _vipassanā_:

____
Two things are conducive to insightfulness into reality. Which two? Inward calm 
and insightfulness.

_Dve me bhikkhave dhammā vijjābhāgiyā. Katame dve? Samatho ca vipassanā ca._
____

____
When inward calm is developed, what benefit accrues? The mind is developed.

_Samatho bhikkhave bhāvito kamatthamanubhoti? Cittaṃ bhāvīyati._
____

____
When the mind is developed, what benefit accrues? Attachment is abandoned.

_Cittaṃ bhāvitaṃ kamatthamanubhoti? Yo rāgo so pahīyati._
____

____
When insightfulness is developed, what benefit accrues? Penetrative discernment 
is developed.

_Vipassanā bhikkhave bhāvitā kamatthamanubhoti? Paññā bhāvīyati._
____

____
When penetrative discernment is developed, what benefit accrues? 
Uninsightfulness into reality is abandoned.

_Paññā bhāvitā kamatthamanubhoti? Yā avijjā sā pahīyati._
____

____
The mind that is defiled by attachment is not liberated [from perceptually 
obscuring states].

_Rāgupakkiliṭṭhaṃ vā bhikkhave cittaṃ na vimuccati._
____

____
Penetrative discernment that is defiled by uninsightfulness into reality is not 
developed.

_Avijjupakkiliṭṭhā vā paññā na bhāvīyati._
____

____
Therefore the liberation [from attachment] by [developing] the mind [in inward 
calm] is due to the fading away of attachment.

_Iti kho bhikkhave rāgavirāgā cetovimutti_
____

[quote, A.1.61]
____
And the liberation [from uninsightfulness] by [developing] penetrative 
discernment is due to the fading away of uninsightfulness into reality.

_avijjāvirāgā paññāvimuttī ti._
____

On the basis of this sutta this we render the terms as:

- _Cetovimutti_: liberation [from attachment through inward calm]

- _Paññāvimutti_: liberation [from uninsightfulness] through penetrative 
discernment

==== Cetovimuttiṃ plus paññāvimuttiṃ: not necessarily arahantship

The combination of _cetovimuttiṃ_ and _paññāvimuttiṃ_ may or may not 
imply arahantship:

[quote, A.5.139]
____
Some person is unvirtuous but he discerns according to reality, with the 
liberation [from attachment through inward calm] and the liberation [from 
uninsightfulness] through penetrative discernment, where that unvirtuousness 
ceases without remainder.

_Idha panānanda ekacco puggalo dussīlo hoti tañca cetovimuttiṃ 
paññāvimuttiṃ yathābhūtaṃ pajānāti yatthassa taṃ dussīlyaṃ 
aparisesaṃ nirujjhati._
____

[quote, "A.1.234, M.1.34"]
____
He, in this very lifetime, through the destruction of perceptually 
obscuring states, enters upon and abides in the liberation [from attachment 
through inward calm] and the liberation [from uninsightfulness] through 
penetrative discernment, realising it for himself through transcendent insight. 

_So āsavānaṃ khayā anāsavaṃ cetovimuttiṃ paññāvimuttiṃ 
diṭṭheva dhamme sayaṃ abhiññā sacchikatvā upasampajja viharati_ 
____

==== Ubhatobhāgavimutto; Paññāvimutto; Paññāvimuttin; Cetovimuttin

For discussion of these terms see Glossary sv _Ubhatobhāgavimutto_.

- _ubhatobhāgavimutto_: one who is liberated [from perceptually obscuring 
states] both through [penetrative discernment and through attaining the 
immaterial states of awareness]

- _paññāvimutto_: one who is liberated [from perceptually obscuring states] 
through penetrative discernment

- _paññāvimuttin_: one who is liberated [from uninsightfulness] through 
penetrative discernment

- _cetovimuttin_: one who is liberated [from attachment through inward calm]

=== Illustrations: cetovimutti plus paññāvimutti

.Illustration
====
cetovimuttiṃ paññāvimuttiṃ

liberation [from attachment through inward calm] and the liberation [from 
uninsightfulness] through penetrative discernment
====

____
We shall so enter and abide in the liberation [from attachment through inward 
calm] and the liberation [from uninsightfulness] through penetrative 
discernment,

_yañca cetovimuttiṃ paññāvimuttiṃ upasampajja viharato_
____

____
that the illusion of personal identity, the illusion of personal ownership, and 
the proclivity to self-centredness do not exist

_ahaṅkāramamaṅkāramānānusayā na honti_
____

[quote, A.1.133]
____
That is how you must train yourselves

_Evaṃ hi vo sāriputta sikkhitabbaṃ._
____

.Illustration
====
cetovimuttiṃ paññāvimuttiṃ

liberation [from attachment through inward calm] and the liberation [from 
uninsightfulness] through penetrative discernment,
====

____
And how is there unrestraint [of the sense faculties]?

_Katañcava bhikkhave asaṃvaro hoti._
____

____
In this regard, in seeing a visible object via the visual sense, a bhikkhu is 
intent upon an agreeable visible object and troubled by a disagreeable visible 
object.

_Idha bhikkhave bhikkhu cakkhunā rūpaṃ disvā piyarūpe rūpe adhimuccati 
appiyarūpe rūpe vyāpajjati_
____

[quote, S.4.190]
____
He abides without having established mindfulness of the body, with a small 
mind, and he does not discern according to reality, with the liberation [from 
attachment through inward calm] and the liberation [from uninsightfulness] 
through penetrative discernment, where those unvirtuous, spiritually 
unwholesome factors cease without remainder.

_anupaṭṭhitakāyasati ca viharati parittacetaso tañca cetovimuttiṃ 
paññāvimuttiṃ yathābhūtaṃ nappajānāti yatthassa te uppannā pāpakā 
akusalā dhammā aparisesā nirujjhanti._
____

.Illustration
====
cetovimuttiṃ paññāvimuttiṃ

the liberation [from attachment through inward calm] and the liberation [from 
uninsightfulness] through penetrative discernment
====

[quote, A.5.141]
____
Some person is virtuous and he discerns according to reality, with the 
liberation [from attachment through inward calm] and the liberation [from 
uninsightfulness] through penetrative discernment, where that virtuousness 
ceases without remainder.

_Idha panānanda ekacco puggalo sīlavā hoti tañca cetovimuttiṃ 
paññāvimuttiṃ yathābhūtaṃ pajānāti yatthassa taṃ sīlaṃ 
aparisesaṃ nirujjhati._
____

.Illustration
====
cetovimuttiṃ paññāvimuttiṃ

the liberation [from attachment through inward calm] and the liberation [from 
uninsightfulness] through penetrative discernment
====

[quote, A.5.141]
____
Some person is full of attachment but he discerns according to reality, with 
the liberation [from attachment through inward calm] and the liberation [from 
uninsightfulness] through penetrative discernment, where that attachment ceases 
without remainder.

_Idha panānanda ekacco puggalo tibbarāgo hoti tañca cetovimuttiṃ 
paññāvimuttiṃ yathābhūtaṃ pajānāti yatthassa so rāgo apariseso 
nirujjhati._
____

.Illustration
====
cetovimuttiṃ paññāvimuttiṃ

the liberation [from attachment through inward calm] and the liberation [from 
uninsightfulness] through penetrative discernment
====

[quote, A.5.142]
____
Some person is ill-tempered but he discerns according to reality, with the 
liberation [from attachment through inward calm] and the liberation [from 
uninsightfulness] through penetrative discernment, where that anger ceases 
without remainder.

_Idha panānanda ekacco puggalo kodhano hoti tañca cetovimuttiṃ 
paññāvimuttiṃ yathābhūtaṃ pajānāti yatthassa so kodho apariseso 
nirujjhati._
____

.Illustration
====
cetovimuttiṃ paññāvimuttiṃ

the liberation [from attachment through inward calm] and the liberation [from 
uninsightfulness] through penetrative discernment
====

[quote, A.5.142]
____
Some person is full of restlessness but he discerns according to reality, with 
the liberation [from attachment through inward calm] and the liberation [from 
uninsightfulness] through penetrative discernment, where that restlessness 
ceases without remainder.

_Idha panānanda ekacco puggalo uddhato hoti tañca cetovimuttiṃ 
paññāvimuttiṃ yathābhūtaṃ pajānāti yatthassa taṃ uddhaccaṃ 
aparisesaṃ nirujjhati._
____

.Illustration
====
cetovimutti

liberation [from attachment through inward calm]; paññāvimutti, liberation 
&#8203;[from uninsightfulness] through penetrative discernment
====

____
Bhikkhus, these five practices if developed and cultivated have liberation 
&#8203;[from attachment through inward calm], and liberation [from uninsightfulness] 
through penetrative discernment as their fruit and benefit. Which five?

_Pañcime bhikkhave dhammā bhāvitā bahulīkatā cetovimuttiphalā ca honti 
cetovimuttiphalānisaṃsā ca. Paññāvimuttiphalā ca honti 
paññāvimuttiphalānisaṃsā ca. Katame pañca?_
____

[quote, A.3.85]
____
The perception of the unlastingness [of the five aggregates], the perception 
that what is unlasting is existentially void, the perception that what is 
existentially void is void of personal qualities, the perception of the 
abandonment [of sensuous thoughts, unbenevolent thoughts, malicious thoughts, 
and unvirtuous, spiritually unwholesome factors], the perception of the passing 
away [of originated phenomena], the perception of the ending [of originated 
phenomena].

_Aniccasaññā anicce dukkhasaññā dukkhe anattasaññā pahānasaññā 
virāgasaññā nirodhasaññā._
____

=== Illustrations: cetovimutti

.Illustration
====
cetovimuttiyā

liberation [from perceptually obscuring states]
====

____
If the liberation [from perceptually obscuring states] through [unlimited, 
all-encompassing] goodwill is developed and cultivated, it is impossible, out 
of the question, that ill will would plague your mind.

_Aṭṭhānametaṃ āvuso anavakāso yaṃ mettāya cetovimuttiyā 
bhāvitāya bahulīkatāya... atha ca panassa vyāpādo cittaṃ pariyādāya 
ṭhassatī'ti_
____

____
If the liberation [from perceptually obscuring states] through [unlimited, 
all-encompassing] compassion is developed and cultivated, it is impossible, out 
of the question, that maliciousness would plague your mind.

_Aṭṭhānametaṃ āvuso anavakāso yaṃ karuṇāya cetovimuttiyā 
bhāvitāya bahulīkatāya... atha ca panassa vihesā cittaṃ pariyādāya 
ṭhassatī'ti_
____

____
If the liberation [from perceptually obscuring states] through [unlimited, 
all-encompassing] joy is developed and cultivated, it is impossible, out of the 
question, that disgruntlement [with the celibate life] would plague your mind.

_Aṭṭhānametaṃ āvuso anavakāso yaṃ muditāya cetovimuttiyā 
bhāvitāya bahulīkatāya... atha ca panassa arati cittaṃ pariyādāya 
ṭhassatī'ti_
____

[quote, D.3.248-250]
____
If the liberation [from perceptually obscuring states] through [unlimited, 
all-encompassing] detached awareness is developed and cultivated, it is 
impossible, out of the question, that attachment would plague your mind. There 
is no such possibility. For this is the liberation from attachment, namely the 
liberation [from perceptually obscuring states] through [unlimited, 
all-encompassing] detached awareness

_Aṭṭhānametaṃ āvuso anavakāso yaṃ upekkhāya cetovimuttiyā 
bhāvitāya bahulīkatāya... atha ca panassa rāgo cittaṃ pariyādāya 
ṭhassatī'ti._
____

.Illustration
====
cetovimutti

liberation [from perceptually obscuring states]
====

____
And what, bhante, is the liberation [from perceptually obscuring states] 
through the perception of nonexistence?

_Katamā ca bhante ākiñcaññā cetovimutti_
____

[quote, S.4.296]
____
In this regard, by completely transcending the state of awareness of boundless 
mental consciousness, a bhikkhu enters and abides in the state of awareness of 
nonexistence, where one perceives that there is [nowhere] anything at all.

_Idha bhante bhikkhu sabbaso viññāṇañcāyatanaṃ samatikkamma natthi 
kiñcī ti ākiñcaññāyatanaṃ upasampajja viharati._
____

.Illustration
====
cetovimutti

liberation [from perceptually obscuring states]
====

____
And what, bhante, is the liberation [from perceptually obscuring states] 
through the [perception of the] absence [of personal qualities]?

_Katamā ca bhante suññatā cetovimutti_
____

[quote, M.1.297-8]
____
In this regard a bhikkhu, gone to the wilderness, or the root of a tree, or a 
solitary abode, reflects thus: 'This is void of an [absolute] Selfhood and of 
what could belong to an [absolute] Selfhood.'

_Idha bhante bhikkhu araññagato vā rukkhamūlagato vā suññāgāragato vā 
itipaṭisaṃcikkhati suññamidaṃ attena vā attaniyena vā._
____

