== Chanda

=== Renderings

- _chanda_: fondness

- _chanda_: desire

- _chanda_: hankering

- _chanda_: favoritism

- _chanda_: aspiration

- _chanda_: eagerness

- _chanda_: eagerness [to understand the teaching]

- _chandīkata_: eager

- _chanda_: consent

- _chandataṃ_: partiality

- _chandasā_: preferentially

- _chandakaṃ_: voluntary donations

=== Introduction

==== Fondness vs. desire

One of the major divisions in meaning here is between fondness and desire. We 
present fifteen or more examples of each to illustrate this division.

==== Chandasamādhi

_Chandasamādhi_ means inward collectedness based on desire. The idea that 
inward collectedness can arise according to one's wishes is widely acknowledged 
in the scriptures:

[quote, M.1.33]
____
Attain at will, without difficulty or trouble, the four jhānas, the higher 
mental states which are pleasant states of meditation in this lifetime

_catunnaṃ jhānānaṃ ābhicetasikānaṃ diṭṭhadhammasukhavihārānaṃ 
nikāmalābhī assaṃ akicchalābhī akasiralābhī ti._
____

[quote, M.1.207]
____
Whenever we want... we enter and abide in first jhāna

_yāvadeva ākaṅkhāma... paṭhamaṃ jhānaṃ upasampajja viharāma._
____

[quote, M.1.214]
____
A bhikkhu wields power over his mind; his mind does not wield power over him; 
whatever abiding he wants to abide in in the morning, he does so.

_bhikkhu cittaṃ vasaṃ vatteti no ca bhikkhu cittassa vasena vattati. So 
yāya vihārasamāpattiyā ākaṅkhati pubbanhasamayaṃ viharituṃ tāya 
vihārasamāpattiyā pubbanhasamayaṃ viharati._
____

==== Chando: eagerness [to understand the teaching]

We parenthesise 'to understand the teaching' on the basis of the following 
quote:

____
-- 'But what quality is most helpful for enthusiastically applying oneself [to 
the teaching]?'

_Ussāhassa pana bho gotama katamo dhammo bahukāro?_
____

____
-- 'Eagerness [to understand the teaching]. If eagerness [to understand the 
teaching] did not arise, one wouldn't enthusiastically apply oneself [to the 
teaching].'

_Ussāhassa kho bhāradvāja chando bahukāro. No cetaṃ chando jāyetha 
nayidaṃ ussaheyya._
____

____
-- 'But what quality is most helpful for eagerness [to understand the 
teaching]?'

_Chandassa pana bho gotama katamo dhammo bahukāro?_
____

[quote, M.2.173]
____
-- 'The teaching receiving one's considered approval. If this did not happen, 
eagerness [to understand the teaching] wouldn't arise.'

_Chandassa kho bhāradvāja dhammanijjhānakkhanti bahukārā. No cetaṃ 
dhammanijjhānaṃ khameyyuṃ nayidaṃ chando jāyetha._
____

=== Illustrations: fondness

.Illustration
====
chandaṃ

fondness
====

Do not, sir, die filled with longing. To die filled with longing is unpleasant 
and blameworthy. Of your eighty-four thousand cities, Kusāvatī is the chief.

[quote, D.2.192]
____
Abandon fondness for them. Harbour no longing for life.

_ettha deva chandaṃ pajaha. Jīvite apekkhaṃ mākāsi._
____

.Illustration
====
chandaṃ

fondness for
====

[quote, S.1.197]
____
Desiring seclusion [from sensuous pleasures and spiritually unwholesome 
factors] you entered the woods, yet your mind gushes outwardly. Eliminate, man, 
your fondness for people; then you'll be truly happy, free of attachment.

_Jano janasmiṃ vinayassu chandaṃ tato sukhī hohisi vītarāgo._
____

.Illustration
====
chanda

fondness
====

[quote, A.4.339]
____
All things stem from fondness.

_chandamūlakā āvuso sabbe dhammā._
____

[quote, S.3.100-1]
____
These five grasped aggregates stem from fondness

_Ime kho bhikkhu pañcupādānakkhandhā chandamūlakā ti._
____

.Illustration
====
chanda

fondness for
====

[quote, S.1.186]
____
People are ensnared by objects of attachment, by what is seen, heard, sensed, 
and cognised. Dispel fondness for these. Be imperturbable.

_Upadhīsu janā gathitāse diṭṭhasute paṭighe ca mute ca +
Ettha vinodaya chandamanejo._
____

.Illustration
====
chando

fondness
====

[quote, M.1.191]
____
Whatever fondness, clinging, attraction, and cleaving there is within these 
five grasped aggregates is the origin of suffering.

_Yo imesu pañcasupādānakkhandhesu chando ālayo anunayo ajjhosānaṃ so 
dukkhasamudayo._
____

.Illustration
====
chanda

fondness
====

[quote, Sn.v.1091]
____
In this regard, Hemaka, in regards to pleasant things which are seen, heard, 
sensed, or cognised, the dispelling of fondness and attachment is the 
Untroubled, the Unshakeable State.

_Idha diṭṭhasutamutaviññātesu piyarūpesu hemaka +
Chandarāga vinodanaṃ nibbānapadamaccutaṃ._
____

.Illustration
====
chanda

fondness
====

[quote, S.4.329]
____
Those people in Uruvelakappa for whom grief etc. would arise in me 
(_uppajjeyyuṃ sokaparidevadukkhadomanassupāyāsā_) if they were executed, 
imprisoned, fined, or criticised are those for whom I have fondness and 
attachment.

_atthi me tesu chandarāgo._
____

.Illustration
====
chanda

fondness
====

____
Neither is grasping the same as the five grasped aggregates, nor is it separate.

_Na kho bhikkhu taññeva upādānaṃ te pañcupādānakkhandhā na pi 
aññatra pañcupādānakkhandhehi upādānaṃ_
____

[quote, S.3.100-1]
____
Whatever there is the fondness and attachment, that is the grasping.

_api ca yo tattha chandarāgo taṃ tattha upādānan ti._
____

.Illustration
====
chanda

fondness
====

____
How does one revive the past?

_kathañcāvuso atītaṃ anvāgameti_
____

[quote, M.3.195-6]
____
One remembers how one's visual sense and visible objects were in the past and 
one's mind is bound there by fondness and attachment.

_iti me cakkhuṃ ahosi atītamaddhānaṃ iti rūpāti tattha 
chandarāgapaṭibaddhaṃ hoti viññāṇaṃ._
____

.Illustration
====
chanda

fondness
====

____
Because of search, acquisition

_pariyesanaṃ paṭicca lābho_
____

____
Because of acquisition, examination

_lābhaṃ paṭicca vinicchayo_
____

____
Because of examination, fondness and attachment

_vinicchayaṃ paṭicca chandarāgo_
____

[quote, A.4.401; D.2.58-9]
____
Because of fondness and attachment, cleaving

_chandarāgaṃ paṭicca ajjhosānaṃ._
____

.Illustration
====
chando

fondness
====

____
As he abides contemplating the nature of the body, whatever fondness he has for 
the body is abandoned.

_Tassa kāye kāyānupassino viharato yo kāyasmiṃ chando so pahīyati._
____

[quote, S.5.182]
____
Because fondness is abandoned, the Deathless is realised.

_Chandassa pahānā amataṃ sacchikataṃ hoti._
____

.Illustration
====
chando

fondness
====

[quote, S.4.329-330]
____
-- 'What do you think, headman? Before you saw Ciravāsi's mother or heard 
about her, did you have any fondness, attachment, or love for her?'

_adiṭṭhā āsi assutā ahosi ciravāsissa mātuyā chando vā rāgo vā 
pemaṃ vā ti_

-- 'No, bhante'.
____

.Illustration
====
chandaṃ

fondness
====

____
"As is this one, so is that one. As is that one, so is this one."

_Yathā idaṃ tathā etaṃ yathā etaṃ tathā idaṃ_
____

[quote, Sn.v.203]
____
&#8203;[If one understood this] one would discard fondness for the body, both 
internally and externally.

_Ajjhattañca bahiddhā ca kāye chandaṃ virājaye._
____

.Illustration
====
chanda

fondness
====

[quote, A.1.264]
____
How does fondness arise based on past bases of fondness and attachment?

_Kathañca bhikkhave atīte chandarāgaṭṭhānīye dhamme ārabbha chando jāyati:_

Based on past bases of fondness and attachment, he thinks and ponders.

_atīte bhikkhave chandarāgaṭṭhānīye dhamme ārabbha cetasā anuvitakketi anuvicāreti._

For him, thinking and pondering on past bases of fondness and attachment, fondness arises.

_Tassa atīte chandarāgaṭṭhānīye dhamme ārabbha cetasā anuvitakkayato anuvicārayato chando jāyati._

With the arising of fondness, he is tethered to those things.

_Chandajāto tehi dhammehi saṃyutto hoti._
____

.Illustration
====
chando

fondness
====

[quote, S.1.203]
____
In the past I was fond of the teachings in verse so long as I had not realised 
non-attachment [to originated phenomena].

_Ahu pure dhammapadesu chando yāva virāgena na samāgamimha._
____

=== Illustrations: desire and hankering

.Illustration
====
chandaṃ

hankering
====

[quote, Th.v.1105]
____
When, like an elephant wandering free of attachment, shall I obliterate 
hankering for the varieties of sensuous pleasure?

_Kadā nu nāgo va asaṅgacārī padālaye kāmaguṇesu chandaṃ._
____

.Illustration
====
chandassa

hankering
====

[quote, S.5.64]
____
There is the quality of loveliness. Much improper contemplation in that regard 
is a condition that nourishes both the arising of unarisen sensuous hankering, 
and the increase and expansion of arisen sensuous hankering.

_Atthi bhikkhave subhanimittaṃ. Tattha ayoniso manasikārabahulīkāro 
ayamāhāro anuppannassa vā kāmacchandassa uppādāya uppannassa vā 
kāmacchandassa bhiyyobhāvāya vepullāya._
____

.Illustration
====
chando

hankering
====

• Bhikkhus, by much contemplating things that are a basis for attachment to 
sensuous pleasure, unarisen sensuous hankering arises, and arisen sensuous 
hankering increases and expands. +
_Kāmarāgaṭṭhāniyānaṃ bhikkhave dhammānaṃ manasikārabahulīkārā 
anuppanno ceva kāmacchando uppajjati uppanno ca kāmacchando bhiyyobhāvāya 
vepullāya saṃvattati_ (S.5.84).

.Illustration
====
chando

hankering
====

[quote, M.1.295]
____
When a bhikkhu has entered first jhāna, sensuous hankering is abandoned.

_idhāvuso paṭhamaṃ jhānaṃ samāpannassa bhikkhuno kāmacchando pahīno 
hoti._
____

.Illustration
====
chandaṃ

hankering
====

[quote, S.1.23]
____
The world's attractive things are not sensuous yearning. The sensuous yearning 
of a man is his thoughts bound up with attachment. The world's attractive 
things remain as they are. The wise eliminate their hankering for them.

_Na te kāmā yāni citrāni loke saṅkapparāgo purisassa kāmo +
Tiṭṭhanti citrāni tatheva loke athettha dhīrā vinayanti chandaṃ._
____

.Illustration
====
chando

hankering
====

____
Having abandoned hankering for past sensuous pleasures, bhante,

_Atītesu me bhante kāmesu kāmacchando pahīno._
____

[quote, S.5.315]
____
Having got rid of hankering for future sensuous pleasures....

_Anāgatesu me kāmesu kāmacchando vigato._
____

.Illustration
====
chando

hankering
====

[quote, D.2.300]
____
In this regard, if sensuous hankering is present in him, he knows that it is 
present. Or if not present, he knows that it is not present.

_Idha bhikkhave bhikkhu santaṃ vā ajjhattaṃ kāmacchandaṃ atthi me 
ajjhattaṃ kāmacchando ti pajānāti asantaṃ vā ajjhattaṃ 
kāmacchandaṃ natthi me ajjhattaṃ kāmacchando ti pajānāti._
____

.Illustration
====
chando

desire
====

____
Because of mental imagery of visible objects, thought of visible objects arises

_Rūpasaññaṃ paṭicca uppajjati rūpasaṅkappo_
____

____
Because of thought of visible objects, desire for visible objects arises

_Rūpasaṅkappaṃ paṭicca uppajjati rūpacchando_
____

[quote, S.2.144]
____
Because of desire for visible objects, passion for visible objects arises

_Rūpacchandaṃ paṭicca uppajjati rūpapariḷāho._
____

.Illustration
====
chanda

desire
====

____
Because of diversity in thought there is diversity in desire.

_saṅkappanānattaṃ paṭicca uppajjati chandanānattaṃ_
____

____
Because of diversity in desire there is diversity in passion.

_chandanānānattaṃ paṭicca uppajjati pariḷāhanānattaṃ_
____

[quote, D.3.289]
____
Because of diversity in passion there is diversity in quests

_paṭiḷāhanānattaṃ paṭicca uppajjati pariyesanānānattaṃ._
____

.Illustration
====
chanda

desire
====

[quote, A.3.274]
____
Possessed of five factors a bhikkhu should not be selected as a food steward: 
he goes astray from desire, hatred, undiscernment of reality, fear, and knows 
not a ration from what is not.

_chandāgatiṃ gacchati dosāgatiṃ gacchati mohāgatiṃ gacchati 
bhayāgatiṃ gacchati uddiṭṭhānuddiṭṭhaṃ na jānāti._
____

.Illustration
====
chanda

desire
====

[quote, M.1.119]
____
When a bhikkhu is focusing on some meditation object that arouses unvirtuous, 
spiritually unwholesome thoughts connected with desire, hatred, undiscernment 
of reality, then he should focus on some other meditation object connected with 
what is spiritually wholesome.

_yaṃ nimittaṃ āgamma yaṃ nimittaṃ manasikaroto uppajjanti pāpakā 
akusalā vitakkā chandūpasaṃhitāpi dosūpasaṃhitāpi mohūpasaṃhitāpi 
tena bhikkhave bhikkhunā tamhā nimittā aññaṃ nimittaṃ 
manasikātabbaṃ kusalūpasaṃhitaṃ._
____

.Illustration
====
chando

desire
====

[quote, Sn.v.835]
____
Seeing even Taṇhā, Arati, and Rāgā aroused in me no desire for sexual 
intercourse.

_Disvāna taṇhaṃ aratiṃ rāgañca nāhosi chando api methunasmiṃ._
____

.Illustration
====
chanda

desire
====

[quote, D.3.133]
____
A bhikkhu whose _āsavas_ are destroyed is incapable of acting wrongly through 
desire, hatred, undiscernment of reality, fear.

_Abhabbo khīṇāsavo bhikkhu chandāgatiṃ gantuṃ abhabbo khīṇāsavo 
bhikkhu dosāgatiṃ gantuṃ abhabbo khīṇāsavo bhikkhu mohāgatiṃ 
gantuṃ abhabbo khīṇāsavo bhikkhu bhayāgatiṃ gantuṃ._
____

.Illustration
====
chando

desire
====

____
And what is desire that is too lax?

_Katamo ca bhikkhave atilīno chando._
____

• It is desire accompanied by indolence, conjoined with indolence +
☸ yo bhikkhave chando kosajjasahagato kosajjasampayutto ayaṃ vuccati 
bhikkhave atilīno chando.

____
And what is desire that is too strained?

_Katamo ca bhikkhave atipaggahito chando._
____

____
It is desire accompanied by restlessness, conjoined with restlessness. This is 
called desire that is too strained.

_yo hi bhikkhave chando uddhaccasahagato uddhaccasampayutto ayaṃ vuccati 
bhikkhave atipaggahito chando._
____

____
And what is desire that is constricted internally?

_Katamo ca bhikkhave ajjhattaṃ saṅkhitto chando_
____

____
It is desire accompanied by lethargy and torpor, conjoined with lethargy and 
torpor. This is called will constricted internally.

_yo hi bhikkhave chando thīnamiddhasahagato thīnamiddhasampayutto ayaṃ 
vuccati bhikkhave ajjhattaṃ saṅkhitto chando._
____

____
And what is desire that is disturbed externally?

_Katamo ca bhikkhave bahiddhā vikkhitto chando_
____

[quote, S.5.277]
____
It is desire that is repeatedly distracted externally, repeatedly disturbed, 
because of the five varieties of sensuous pleasure. This is called desire that 
is distracted externally.

_yo hi bhikkhave chando bahiddhā pañcakāmaguṇe ārabbha anuvikkhitto 
anuvisaṭo ayaṃ vuccati bhikkhave bahiddhā vikkhitto chando._
____

.Illustration
====
chandaṃ

desire
====

[quote, Vin.4.232]
____
There is no offence to restore a bhikkhunī... if she restores her knowing that 
it is the desire of the group

_gaṇassa chandaṃ jānitvā._
____

.Illustration
====
chando

desire
====

____
The Buddha: Things are agreeable and wanted in the world on account of desire. 
Desire is also the source of the expectation and hope that a man has for the 
hereafter.

_Chandānidānāni piyāni loke ye cā pi lobhā vicaranti loke +
Āsā ca niṭṭhā ca itonidānā ye samparāyāya narassa honti_
____

____
Questioner: What is the source of desire in the world? And from where do 
dogmatic opinions come from, anger, lies, uncertainty [about the significance 
of the teaching], and other such things spoken of by the Ascetic?

_Chando nu lokasmiṃ kutonidāno vinicchayā cā pi kutopahūtā +
Kodho mosavajjañca kathaṅkathā ca ye vāpi dhammā samaṇena vuttā_
____

[quote, Sn.v.866-8]
____
The Buddha: Desire arises in the world dependent on what they call 'pleasing' 
and 'displeasing.'

_Sātaṃ asātanti yamāhu loke tamupanissāya pahoti chando._
____

.Illustration
====
chando

desire
====

____
What is agreeable and disagreeable have desire as their basis and origin, 
object of genesis and production. When there is desire they arise, without 
desire they do not arise.

_Piyāppiyaṃ kho devānaminda chandanidānaṃ chandasamudayaṃ 
chandajātikaṃ chandappabhavaṃ chande sati piyāppiyaṃ hoti chande asati 
piyāppiyaṃ na hotī ti._
____

[quote, D.2.277]
____
Desire has thought as its basis, origin, object of genesis and production. When 
there is thought it arises, without thought it does not arise.

_Chando kho devānaminda vitakkanidāno vitakkasamudayo vitakkajātiko 
vitakkapabhavo. Vitakke sati chande hoti vitakke asati chando na hotī ti._
____

.Illustration
====
chandā

desire
====

Master Gotama, we have such yearnings, desires, and aspirations (_evaṃ kāmā 
evañchandā evaṃ adhippāyā_) as these: 'May we dwell in a home crowded 
with children! May we enjoy Kāsian sandalwood! May we wear garlands, 
fragrances, and perfumes! May we receive gold and silver! With the demise of 
the body at death, may we be reborn in the realm of happiness, in the heavenly 
worlds!' (S.5.353).

.Illustration
====
chandā

desire
====

____
Bhikkhus, for the most part beings have such yearnings, desires, and aspirations

_yebhuyyena bhikkhave sattā evaṃ kāmā evaṃ chandā evaṃ adhippāyā_
____

[quote, M.1.309]
____
'If only unlikeable, unloveable, and displeasing things would diminish and 
likeable, loveable, and pleasing things would increase!'

_aho vata aniṭṭhā akantā amanāpā dhammā parihāyeyyuṃ iṭṭhā 
kantā manāpā dhammā abhivaḍḍheyyunti._
____

=== Illustrations: other

.Illustration
====
chanda

favoritism
====

[quote, Vin.4.335]
____
How can the lady Thullanandā ordain a sikkhamānā by showing favoritism to 
bhikkhus placed on probation.

_kathaṃ hi nāma ayyā thullanandā pārivāsikachandadānena sikkhamānaṃ 
vuṭṭhāpessatī ti._
____

Comment:

Thullanandā arranged an ordination ceremony with the help of bhikkhus on 
probation.

.Illustration
====
chandāya

favoritism
====

____
Dabba the Mallian distributes abodes and meals though favoritism.

_chandāya dabbo mallaputto senāsanaṃ paññāpeti chandāya ca bhattāni 
uddisatīti._
____

.Illustration
====
chando

aspiration
====

[quote, A.3.441]
____
The aspiration to spiritually wholesome factors is hard to come by in the world

_kusaladhammacchando dullabho lokasmiṃ._
____

.Illustration
====
chanda

aspiration
====

____
For a bhikkhu this is the foretoken and preindication of the arising of the 
noble eightfold path, namely, perfection in the aspiration [to abandon 
spiritually unwholesome factors and acquire spiritually wholesome factors].

_ariyassa aṭṭhaṅgikassa maggassa uppādāya etaṃ pubbaṅgamaṃ etaṃ 
pubbanimittaṃ yadidaṃ chandasampadā_
____

[quote, S.5.30]
____
When a bhikkhu is perfect in the aspiration [to abandon spiritually unwholesome 
factors and acquire spiritually wholesome factors], it is to be expected that 
he will develop and cultivate this noble eightfold path.

_Chandasampannassetaṃ bhikkhave bhikkhuno pāṭikaṅkhaṃ ariyaṃ 
aṭṭhaṅgikaṃ maggaṃ bhāvessati ariyaṃ aṭṭhaṅgikaṃ maggaṃ 
bahulīkarissatī ti._
____

Commentary: _Chandasampadā ti kusalakattukamyatāchando_.

.Illustration
====
chandā

aspiration
====

'Consent that I may go forth from the household life into the ascetic life.' 
Then the parents of those boys consented, thinking:

[quote, Vin.1.77-8]
____
'All these boys have the same aspiration. They are bent on what is virtuous.'

_sabbepi me dārakā samānacchandā kalyāṇadhippāyā ti._
____

.Illustration
====
chanda

aspiration
====

[quote, D.3.147]
____
If one such as he ends up going forth [into the ascetic life], the practice of 
unsensuousness being his aspiration and delight, being prudent, best of men 
he'll be, peerless, never more to be reborn.

_Nekkhammachandābhirato._
____

.Illustration
====
chanda

eager [to understand the teaching]
====

[quote, Thī.v.12]
____
One should be eager and determined [to understand the teaching]. One should 
suffuse [one's body] with the [pure and clean] mind [of fourth jhāna].

_Chandajātā avasāyī manasā ca phuṭhā siyā._
____

.Illustration
====
chanda

eager
====

[quote, Dh.v.218]
____
One should be eager [to realise] the Indescribable.'

_Chandajāto anakkhāte._
____

.Illustration
====
chando

eagerness
====

[quote, Vin.1.70]
____
One who was formerly a non-Buddhist ascetic has no eagerness for the recitation 
and interrogation, nor of developing the higher virtue, the higher mental 
states, and the higher penetrative discernment.

_aññatitthiyapubbo na tibbacchando hoti uddeso paripucchāya adhisīle 
adhicitte adhipaññāya._
____

.Illustration
====
chando

eager
====

[quote, A.4.15]
____
A bhikkhu is keenly eager to undergo the training and his dedication to this 
does not dwindle away in the course of time.

_bhikkhū sikkhāsamādāne tibbacchando hoti āyatiñca sikkhāsamādāne 
avigatapemo._
____

.Illustration
====
chando

eagerness
====

[quote, S.2.131]
____
Bhikkhus, one who does not know and see old age and death according to reality 
should stir up eagerness to know this according to reality.

_Jarāmaraṇaṃ bhikkhave ajānatā apassatā yathābhūtaṃ jarāmaraṇe 
yathābhūtaṃ ñāṇāya chando karaṇīyo._
____

.Illustration
====
chandaṃ

consent
====

-- 'Gather together bhikkhus, the community of bhikkhus will carry out a formal 
act.'

-- 'Sir there is a bhikkhu who is ill. He has not come.'

[quote, Vin.1.121]
____
-- 'I allow you bhikkhus to convey the consent from a bhikkhu who is ill.'

_anujānāmi bhikkhave gilanena bhikkhunā chandaṃ dātuṃ._
____

.Illustration
====
chanda

consent
====

____
Bhikkhus, if a disciplinary issue is settled thus, and if one who carries it 
out opens it up again, in opening up there is an offence of pācittiya

_Evaṃ vūpasantañce bhikkhave adhikaraṇaṃ kārako ukkoṭeti 
ukkoṭanakaṃ pācittiyaṃ_
____

[quote, Vin.2.94]
____
If one who has given his consent criticises it, in criticising there is an 
offence of pācittiya.

_Chandadāyako khīyati khīyanakaṃ pācittiyaṃ._
____

.Illustration
====
chandaṃ

consent
====

[quote, Vin.4.152]
____
The community of bhikkhus came to be convened on some business or other. The 
Group-of-Six bhikkhus making robes gave their consent to one bhikkhu.

_Chabbaggiyā bhikkhu cīvarakammaṃ karontā ekassa chandaṃ adaṃsu._
____

.Illustration
====
chandataṃ

partiality
====

In former lives the Perfect One made himself beloved through the four bases for 
winning over a following (_cattāri saṅgahavatthūni_): generosity, agreeable 
speech, beneficial conduct, and impartiality (_dānena peyyavajjena 
atthacariyāya samānattatāya_: see A.4.219). About this it is said:

____
Through giving and through beneficial conduct

_Dānampi catthacariyatañca_
____

____
Agreeable speech and impartiality ('equal partiality')

_Piyavadanañca samānachandataṃ ca_
____

Of benefit to all, he at death to heaven went. (D.3.153).

.Illustration
====
chandasā

preferentially
====

[quote, A.3.50]
____
He who preferentially gives clothes, bed, food, drink and various requisites to 
upright men

_yo ujjubhūtesu dadāti chandasā +
Acchādanaṃ sayanamathannapānaṃ nānappakārāni ca paccayāni._
____

Comment:

Giving 'in a timely way' includes giving the first-fruits of field and orchard 
to the virtuous (_sīlavantesu patiṭṭhāpeti_, (A.3.41).

.Illustration
====
chandakaṃ

voluntary donations
====

[quote, Vin.4.250]
____
Lay followers having collected voluntary donations for robe material for a 
community of bhikkhunīs, laid aside the support in a certain cloth store

_tena kho pana samayena upāsikā bhikkhunī saṅghassa cīvaratthāya 
chandakaṃ saṃharitvā aññatarassa pāvārikassa ghare parikkhāraṃ 
nikkhipitvā._
____
