== Cittaṃ pariyādāya tiṭṭhati

=== Renderings

- _cittaṃ pariyādāya tiṭṭhati_: to plague the mind

- _cittaṃ pariyādāya tiṭṭhati_: obsess the mind

=== Introduction

==== Pariyādāti and pariyādiyati

_Pariyādāti_ means 'to exhaust,' 'to consume,' 'to destroy,' and 'to 
overcome.' See Illustrations.

_Pariyādiyati_ is the passive of _pariyādāti_, but both verbs have an active 
sense. Thus PED says both mean 'to exhaust.'

==== Cittaṃ pariyādāya tiṭṭhati

Knowing the meaning of _pariyādāti_ is of no avail in the search for the 
meaning of _cittaṃ pariyādāya tiṭṭhati_, which is to be discerned 
through context. We use two phrases:

1. 'plague the mind'

2. 'obsess the mind'

We regard mental states as 'plaguing' the mind, and sensations as 'obsessing' 
it.

=== Illustrations: pariyādāti, pariyādiyati

==== Pariyādāti: to exhaust

[quote, S.2.98]
____
Our limited provisions are finished and exhausted.

_amhākaṃ kho yā parittā sambalamattā sā parikkhīṇā pariyādinnā._
____

==== Pariyādāti: to overcome

[quote, A.1.216]
____
One who is attached, overpowered, and overcome by attachment, misconducts 
himself by way of body, speech, and mind.

_Ratto kho āvuso rāgena abhibhūto pariyādinnacitto kāyena duccaritaṃ 
carati vācāya duccaritaṃ carati manasā duccaritaṃ carati._
____

==== Pariyādiyati: to consume

[quote, D.2.342]
____
They rapidly consumed all the grass, wood and greenstuff

_khippameva pariyādiyati tiṇakaṭṭhodakaṃ haritakapaṇṇaṃ._
____

==== Pariyādiyati: to destroy

[quote, S.3.157]
____
And how is the perception of the unlastingness [of the five aggregates] 
developed and cultivated so that it destroys all attachment to sensuous 
pleasure.

_kathaṃ bhāvitā ca bhikkhave aniccasaññā kathaṃ bahulīkatā sabbaṃ 
kāmarāgaṃ pariyādiyati._
____

=== Illustrations: cittaṃ pariyādāya tiṭṭhati

.Illustration
====
cittaṃ pariyādāya tiṭṭhati

plague the mind
====

[quote, A.3.69]
____
Lethargy and torpor plague my mind.

_Thīnamiddhañca me cittaṃ pariyādāya tiṭṭhati._
____

.Illustration
====
cittaṃ pariyādāya tiṭṭhanti

plague the mind
====

____
The bodily form of the ignorant Everyman changes and alters. With the change 
and alteration of bodily form, his mind is preoccupied with the change

_Tassa taṃ rūpaṃ vipariṇamati aññathā hoti. Tassa 
rūpavipariṇāmaññathābhāvā rūpavipariṇāmānuparivatti 
viññāṇaṃ hoti._
____

[quote, S.3.16]
____
Distress and other mental states born of this preoccupation plague his mind.

_Tassa rūpavipariṇāmānuparivattijā paritassanā dhammasamuppādā 
cittaṃ pariyādāya tiṭṭhanti._
____

.Illustration
====
cittaṃ pariyādāya ṭhassatī

plague the mind
====

[quote, D.3.280]
____
Disgruntlement [with the celibate life] plagues my mind

_arati cittaṃ pariyādāya ṭhassatī ti._
____

.Illustration
====
cittaṃ pariyādāya ṭhassatī

plague the mind
====

[quote, D.3.248]
____
If the liberation [from perceptually obscuring states] through [unlimited, 
all-encompassing] goodwill is developed and cultivated, it is impossible, out 
of the question, that ill will would plague your mind.

_Aṭṭhānametaṃ āvuso anavakāso yaṃ mettāya cetovimuttiyā 
bhāvitāya... atha ca panassa vyāpādo cittaṃ pariyādāya ṭhassatī ti 
netaṃ ṭhānaṃ vijjati._
____

.Illustration
====
cittaṃ pariyādāya ṭhassatī

plague the mind
====

[quote, D.3.250]
____
If the notion "I am" has vanished, and one does not regard anything as "[in 
reality] what I am,"' it is impossible, out of the question, that the arrow of 
doubt and uncertainty [about the significance of the teaching] would plague 
your mind.

_aṭṭhānametaṃ āvuso anavakāso yaṃ asmī ti vigate ayamahamasmī ti 
asamanupassato atha ca panassa vicikicchākathaṅkathāsallaṃ cittaṃ 
pariyādāya ṭhassatī ti._
____

.Illustration
====
cittaṃ na pariyādāya ṭhassanti

obsess the mind
====

[quote, M.1.423]
____
Just as space is not established anywhere, Rāhula, likewise develop the 
meditation on space; for when you do so, arisen pleasing and displeasing 
sensations will not obsess your mind

_seyyathā pi rāhula ākāso na katthaci patiṭṭhito evameva kho tvaṃ 
rāhula ākāsasamaṃ bhāvanaṃ bhāvehi. Ākāsasamaṃ hi te rāhula 
bhāvanaṃ bhāvayato uppannā manāpāmanāpā phassā cittaṃ na 
pariyādāya ṭhassanti._
____

.Illustration
====
cittaṃ pariyādāya tiṭṭhati

obsess the mind
====

[quote, A.4.157]
____
His mind is obsessed by acquisition. His mind is obsessed by loss... 
prestige... imprestige... criticism... praise... pleasure... pain.

_Tassa lābho pi cittaṃ pariyādāya tiṭṭhati alobho pi cittaṃ 
pariyādāya tiṭṭhati yaso pi cittaṃ pariyādāya tiṭṭhati ayaso pi 
cittaṃ pariyādāya tiṭṭhati nindā pi cittaṃ pariyādāya tiṭṭhati 
pasaṃsā pi cittaṃ pariyādāya tiṭṭhati. Sukham pi cittaṃ 
pariyādāya tiṭṭhati dukkham pi cittaṃ pariyādāya tiṭṭhati._
____

