== Citta

=== Renderings

- _citta_: mind

- _citta_: mental state

- _citta_: idea

- _citta_: minded

- _citta_: attitude

- _citta_: mentality

- _citta_: inward

- _citta_: spiritually

- _citta_: spiritually

- _citta_: disposition

- _cetasā_: mind

- _cetasā_: attitude

- _cittuppāda_: mental state

- _adhicitta_: the higher mental states

- _cittasamādhi_: inward collectedness based on reflection

=== Introduction

==== Citta: mind

Citta can usually be called 'mind':

[quote, S.2.231]
____
He sees women there lightly attired and lust invades his mind

_rāgo cittaṃ anuddhaṃseti._
____

[quote, M.3.30]
____
Through being without grasping his mind was liberated from perceptually 
obscuring states

_anupādāya āsavehi cittaṃ vimuttan ti._
____

[quote, D.1.71]
____
He purifies his mind of lethargy and torpor.

_thīnamiddhā cittaṃ parisodheti._
____

[quote, A.3.16-17]
____
When one's mind is free of these five defilements

_Yato ca kho bhikkhave cittaṃ imehi pañcahi upakkilesehi vippamuttaṃ hoti._
____

[quote, M.3.89]
____
His mind becomes settled, calm, concentrated, and collected.

_ajjhattameva cittaṃ santiṭṭhati sannisīdati ekodi hoti samādhiyati._
____

==== The four paths to psychic power

The four paths to psychic power are:

_• chandasamādhi-padhānasaṅkhārasamannāgataṃ iddhipādaṃ_

_• viriyasamādhi-padhānasaṅkhārasamannāgataṃ iddhipādaṃ_

_• cittasamādhi-padhānasaṅkhārasamannāgataṃ iddhipādaṃ_

_• vīmaṃsāsamādhi-padhānasaṅkhārasamannāgataṃ iddhipādaṃ_

==== Developing the four paths to psychic power

The _Chanda Sutta_ (S.5.268) says that to develop these four paths one must 
first develop the four _samādhis_:

_• chandasamādhi_

_• viriyasamādhi_

_• cittasamādhi_

_• vīmaṃsāsamādhi_

==== Cittasamādhi = dhammasamādhi

The _Pāṭaliya Sutta_ (S.4.350-2) shows that _cittasamādhi_ is synonymous 
with _dhammasamādhi_

[quote, S.4.352]
____
'This is _dhammasamādhi_. If you were to obtain _cittasamādhi_ in this way, 
you would abandon that state of unsureness.'

_Ayaṃ kho so gāmaṇi dhammasamādhī tatra ce tvaṃ cittasamādhiṃ 
paṭilabheyyāsi evaṃ tvaṃ imaṃ kaṅkhādhammaṃ pajaheyyāsi._
____

==== Cittasamādhi: inward collectedness based on reflection

The _Pāṭaliya Sutta_ (S.4.351-2) concerns the development of 
_dhammasamādhi_ through reflecting on one's virtue. See Illustrations below. 
Therefore our renderings are:

- _dhammasamādhi_: inward collectedness based on righteous reflection

- _cittasamādhi_: inward collectedness based on reflection

==== Citta=ceto

In some of the illustrations we take for granted the equivalence of _citta_ and 
_ceto_, as confirmed in PED sv _ceto_.

=== Illustrations

.Illustration
====
cittuppādaṃ

mental state; cetasā, mind
====

____
Fostering what mental states do spiritually unwholesome factors fade and 
spiritually wholesome factors flourish?

_Kathaṃrūpaṃ bhante cittuppādaṃ sevato akusalā dhammā parihāyanti 
kusalā dhammā abhivaḍḍhanti_
____

In this regard, some person is

____
not greedy and abides with an ungreedy mind.

_anabhijjhālu hoti anabhijjhāsahagatena cetasā viharati_
____

____
benevolent and abides with a benevolent mind

_Avyāpādavā hoti avyādapādasahagatena cetasā viharati_
____

[quote, M.3.51]
____
compassionate and abides with a compassionate mind.

_Avihesavā hoti avihesāsahagatena cetasā viharati._
____

Comment:

PED sv _cittuppāda_: 'state of consciousness.'

.Illustration
====
citto

mind
====

[quote, Th.v.98; S.4.76]
____
In seeing a visible object with mindfulness muddled, focusing on the agreeable 
aspect, one experiences it with a mind of attachment and persists in cleaving 
to it.

_Rūpaṃ disvā sati muṭṭhā piyaṃ nimittaṃ manasikaroto +
Sārattacitto vedeti tañca ajjhosa tiṭṭhati._
____

.Illustration
====
citta

mind; citto, mental state
====

• And how does a bhikkhu abide contemplating the nature of the mind +
_Kathañca bhikkhave bhikkhu citte cittānupassī viharati?_

In this regard a bhikkhu discerns

____
a mental state with attachment as just that

_sarāgaṃ vā cittaṃ sarāgaṃ cittan ti pajānāti_
____

____
a mental state without attachment as just that

_vītarāgaṃ vā cittaṃ vītarāgaṃ cittan ti pajānāti_
____

____
a mental state with hatred as just that

_sadosaṃ vā cittaṃ sadosaṃ cittan ti pajānāti_
____

____
a mental state without hatred as just that

_vītadosaṃ vā cittaṃ vītadosaṃ cittan ti pajānāti_
____

____
a mental state with undiscernment of reality as just that

_samohaṃ vā cittaṃ samohaṃ cittan ti pajānāti_
____

____
a mental state without undiscernment of reality as just that

_vītamohaṃ vā cittaṃ vītamohaṃ cittan ti pajānāti_
____

____
a contracted mental state as just that

_saṅkhittaṃ vā cittaṃ saṅkhittaṃ cittan ti pajānāti_
____

____
a distracted mental state as just that

_vikkhittaṃ vā cittaṃ vikkhittaṃ cittan ti pajānāti_
____

____
an exalted mental state as just that

_mahaggataṃ vā cittaṃ mahaggataṃ cittan ti pajānāti_
____

____
an unexalted mental state as just that

_amahaggataṃ vā cittaṃ amahaggataṃ cittan ti pajānāti_
____

____
a surpassed mental state as just that

_sauttaraṃ vā cittaṃ sauttaraṃ cittan ti pajānāti_
____

____
an unsurpassed mental state as just that

_anuttaraṃ vā cittaṃ anuttaraṃ cittan ti pajānāti_
____

____
a collected mental state as just that

_samāhitaṃ vā cittaṃ samāhitaṃ cittan ti pajānāti_
____

____
an uncollected mental state as just that

_asamāhitaṃ vā cittaṃ asamāhitaṃ cittan ti pajānāti_
____

____
a liberated mental state as just that

_vimuttaṃ vā cittaṃ vimuttaṃ cittan ti pajānāti_
____

[quote, M.1.59]
____
an unliberated mental state as just that

_avimuttaṃ vā cittaṃ avimuttaṃ cittan ti pajānāti._
____

.Illustration
====
cittassa

spiritual; cetaso, mind
====

____
Fondness and attachment regarding the visual sense... the mental sense is a 
spiritual defilement;

_Yo bhikkhave cakkhusmiṃ... manasmiṃ chandarāgo cittasse'so upakkileso_
____

[quote, S.3.232]
____
In so far as one abandons the spiritual defilement in these six cases, his mind 
inclines to the practice of unsensuousness.

_Yato kho bhikkhave bhikkhuno imesu chasu ṭhānesu cetaso upakkileso pahīno 
hoti nekkhammaninnaṃ cassa cittaṃ hoti._
____

.Illustration
====
citto

-minded; citto, spiritually
====

[quote, A.1.192]
____
The noble disciple, Kālāmas, who is so friendly-minded, so unhostile-minded, 
so spiritually undefiled, and so spiritually purified, is one by whom four 
sources of comfort are found in this very lifetime.

_Sa kho so kālāmā ariyasāvako evaṃ averacitto evaṃ avyāpajjhacitto 
evaṃ asaṅkiliṭṭhacitto evaṃ visuddhacitto. Tassa diṭṭheva dhamme 
cattāro assāsā adhigatā honti._
____

.Illustration
====
cittassa

inward
====

[quote, A.4.66]
____
When my husband died, he rose amongst the deities and he revealed himself to me 
in his former bodily form, but I do not recall any inward disquiet on that 
account.

_Na kho panāhaṃ bhante abhijānāmi tatonidānaṃ cittassa aññathattan 
ti._
____

.Illustration
====
citta

mental
====

[quote, M.1.301]
____
Perception and sense impression are mental activity

_saññā ca vedanā ca cittasaṅkhāro ti._
____

.Illustration
====
adhicitta

the higher mental states
====

____
What is the training in the higher mental states?

_Katamā ca bhikkhave adhicittasikkhā_
____

[quote, A.1.235]
____
In this regard, secluded from sensuous pleasures and spiritually unwholesome 
factors, a bhikkhu enters and abides in first jhāna... fourth jhāna.

_Idha bhikkhave bhikkhu vivicceva kāmehi vivicca akusalehi dhammehi 
savitakkaṃ savicāraṃ vivekajaṃ pītisukhaṃ paṭhamajjhānaṃ... 
catutthaṃ jhānaṃ upasampajja viharati._
____

.Illustration
====
cittaṃ

idea
====

• "Did you earlier have the idea, 'I will go to the monastery,'and after you 
arrived at the monastery, was the corresponding idea quelled?" "Yes, sir." +
☸ _Ahosi te pubbe cittaṃ ārāmaṃ gamissāmī ti. Tassa te ārāmagatassa 
yaṃ tajjaṃ_ cittaṃ _taṃ paṭippassaddhanti. Evaṃ bho._

"It is exactly the same, brahman, with a bhikkhu who is an arahant:

[quote, S.5.273]
____
He earlier had the idea to attain arahantship, and when he attained 
arahantship, the corresponding idea was quelled.

_Yaṃ pubbe cittaṃ ahosi arahattappattiyā arahatte patte yaṃ tajjaṃ 
cittaṃ taṃ paṭippassaddhaṃ._
____

.Illustration
====
cittasamādhiṃ

inward collectedness based on reflection
====

A headman said he was unsure which religious doctrine was true. The Buddha told 
him he should overcome unsureness through the inward collectedness attained by 
reflecting on virtuousness as follows:

____
-- 'I harm no one at all, whether weak or strong. In both respects I have made 
a lucky throw: since I am restrained in conduct of body, speech, and mind, and 
since, with the demise of the body at death, I will be reborn in the realm of 
happiness, in the heavenly worlds.'

_sohaṃ na kiñci vyābādhemi tasaṃ vā thāvaraṃ vā. Ubhayamettha 
kaṭaggāho yañcamhi kāyena saṃvuto vācāya saṃvuto manasā saṃvuto 
yañca kāyassa bhedā parammaraṇā sugatiṃ saggaṃ lokaṃ 
upapajjissāmī ti._
____

____
'[As he reflects thus] gladness arises. In one who is glad, rapture arises. For 
one whose mind is rapturous, his body grows tranquil. His body tranquil, he 
experiences physical pleasure. Experiencing physical pleasure, his mind becomes 
collected.

_tassa pāmojjaṃ jāyati pamuditassa pīti jāyati pītimanassa kāyo 
passambhati passaddhakāyo sukhaṃ vediyati sukhino cittaṃ samādhiyati_
____

____
'This, headman, is inward collectedness based on righteous reflection.

_Ayaṃ kho so gāmaṇi dhammasamādhī._
____

[quote, S.4.351-2]
____
'If you were to obtain inward collectedness based on reflection in this way, 
you would abandon that state of unsureness.

_Tatra ce tvaṃ cittasamādhiṃ paṭilabheyyāsi evaṃ tvaṃ imaṃ 
kaṅkhādhammaṃ pajaheyyāsi._
____

.Illustration
====
citto

thought
====

____
Bhikkhus, a bhikkhu might approach families with the thought:

_Yo hi koci bhikkhave bhikkhu evaṃcitto kulāni upasaṅkamati_
____

'May they give to me, not hold back. May they give much, not little.' (S.2.200).

.Illustration
====
citta

attitude
====

[quote, A.3.213]
____
One should develop an unhostile, beneficent attitude which leads to the world 
of the devas

_Avyāpajjhaṃ hitaṃ cittaṃ devalokāya bhāvaye._
____

.Illustration
====
citto

attitude
====

____
If a bhikkhu takes from village or wilderness by what is reckoned as theft, 
something not given... he is pārājika, no longer in communion.

_Yo pana bhikkhu gāmā vā araññā vā adinnaṃ theyyasaṅkhātaṃ 
ādiyeyya... ayampi pārājiko hoti asaṃvāso._
____

Word Commentary says:

- by what is reckoned as theft (__theyyasaṅkhātan t__i): a thieving attitude 
(_theyyacitto_), a stealing attitude (_avaharaṇacitto_).

.Illustration
====
cittaṃ

attitude
====

____
How about if I developed [unlimited, all-encompassing] goodwill further?_

_yannūnāhaṃ uttariṃ mettaṃ bhāveyyantī._
____

[quote, A.4.104]
____
Then for seven years the teacher Sunetta developed a mind of [unlimited, 
all-encompassing] goodwill._

_Atha kho bhikkhave sunetto satthā sattavassāni mettaṃ cittaṃ bhāvesi._
____

.Illustration
====
cittaṃ

attitude
====

____
-- Being not tenderly concerned for their welfare, would he have a mind of 
&#8203;[unlimited, all-encompassing] goodwill or of enmity?

_ahitānukampissa mettaṃ vā tesu cittaṃ paccupaṭṭhitaṃ hoti 
sapattakaṃ vā ti_
____

[quote, D.1.228]
____
-- Of enmity, reverend Gotama.

_Sapattakaṃ bho gotama._
____

.Illustration
====
cetasā

attitude; cittaṃ mind
====

____
In this regard a bhikkhu focuses on the mental image of light, concentrates on 
the mental image of day. As by day, so by night; as by night, so by day.

_bhikkhu ālokasaññaṃ manasikaroti divāsaññaṃ adhiṭṭhāti. Yathā 
divā tathā rattiṃ yathā rattiṃ tathā divā_
____

[quote, A.3.323-6]
____
Thus with an attitude open and unclouded, he makes his mind radiant.

_iti vivaṭena cetasā apariyonaddhena sappabhāsaṃ cittaṃ bhāveti._
____

.Illustration
====
citto

attitude
====

[quote, A.4.27]
____
He listens to the teaching with an appreciative attitude, not looking for weak 
spots

_Anupārambhacitto dhammaṃ suṇāti na randhagavesi._
____

Comment:

1. _randhagavesi_: seeking weak spots

2. _anupārambhacitto ≅ tuṭṭhena cittena_, appreciative attitude 
(Th.v.360-4).

.Illustration
====
citta

disposition
====

[quote, A.1.228]
____
If Ānanda were to die not free of attachment, by virtue of his faithful 
disposition, he would rule as Lord of the Devas seven times

_Sace udāyi ānando avītarāgo kālaṃ kareyya tena cittappasādena 
sattakkhattuṃ devesu devarajjaṃ kareyya._
____

.Illustration
====
cittaṃ

mentality
====

____
He develops a doglike mentality fully and uninterruptedly;

_kukkuracittaṃ bhāveti paripuṇṇaṃ abbokiṇṇaṃ_
____

____
he develops a doglike way of behaviour fully and uninterruptedly.

_kukkurākappaṃ bhāveti paripuṇṇaṃ abbokiṇṇaṃ_
____

Having done so, with the demise of the body at death, he reappears in the 
company of dogs (M.1.387-8).

