== Dhātu

=== Renderings

- _dhātu_: phenomenon

- _dhātu_: elements of existence

- _dhātu_: constituent element

- _dhātu_: material phenomenon

- _dhātu_: element of sensation

- _dhātu_: element

- _dhātu_: aspect

- _dhātu_: plane of existence

- _dhātu_: (redundancy)

- _lokadhātu_: multi-universe system

=== Introduction

==== 'Element' vs. 'phenomenon'

_Dhātu_ can be rendered 'element' where it means constituent part, but 
otherwise it is better called 'phenomenon.' In many cases, the word is 
practically redundant.

==== Amatadhātu

Because of its importance, _amatadhātu_ is treated separately sv _Amatadhātu_.

=== Illustrations

.Illustration
====
dhātu

phenomena
====

____
The bhikkhu... enters and abides in fourth jhāna, which is free of pleasure 
and pain, and [is imbued with] purified detached awareness and mindfulness.

_catutthaṃ jhānaṃ upasampajja viharati_
____

[quote, A.3.325]
____
This mode of meditation when developed and cultivated leads to the 
understanding of many phenomena.

_Idaṃ bhante anussatiṭṭhānaṃ evaṃ bhāvitaṃ evaṃ bahulīkataṃ 
anekadhātu paṭivedhāya saṃvattatī._
____

.Illustration
====
dhātuṃ

phenomenon
====

[quote, S.2.144]
____
Because of the phenomenon of visible objects, mental imagery of visible objects 
arises

_rūpadhātuṃ paṭicca uppajjati rūpasaññā._
____

.Illustration
====
dhātuyo

phenomenon
====

____
What three things are hard to fathom?

_tayo dhammā duppaṭivijjhā_
____

____
The three phenomena leading to deliverance.

_tisso nissaraṇiyā dhātuyo_
____

____
The deliverance from sensuous pleasure, namely the practice of unsensuousness.

_kāmānametaṃ nissaraṇaṃ yadidaṃ nekkhammaṃ_
____

____
The deliverance from refined material states of awareness, namely immaterial 
states of awareness.

_rūpānametaṃ nissaraṇaṃ yadidaṃ āruppaṃ_
____

[quote, D.3.275]
____
From whatever is brought about, originated, dependently arisen, the ending [of 
originated phenomena] is the deliverance.

_yaṃ kho pana kiñci bhūtaṃ saṅkhataṃ paṭiccasamuppannaṃ nirodho 
tassa nissaraṇaṃ._
____

.Illustration
====
dhātu

phenomenon
====

____
-- Bhante, when, in regard to those who are not perfectly enlightened, the view 
arises that they are in fact perfectly enlightened, due to what is this view to 
be discerned?

_yāyaṃ bhante diṭṭhi asammāsambuddhesu sammā sambuddhā ti. Ayaṃ nu 
kho bhante diṭṭhi kiṃ paṭicca paññāyatī ti_
____

[quote, S.2.153]
____
-- Mighty, Kaccāna, is this phenomenon, namely the phenomenon of 
uninsightfulness into reality.

_mahati kho esā kaccāna dhātu yadidaṃ avijjādhātu._
____

.Illustration
====
dhātuyā

phenomenon
====

[quote, It.80]
____
For one who abides contemplating the unloveliness of the body the proclivity to 
attachment to the phenomenon of loveliness is abandoned.

_asubhānupassīnaṃ bhikkhave kāyasmiṃ viharataṃ yo subhāya dhātuyā 
rāgānusayo so pahīyati._
____

.Illustration
====
dhātu

phenomenon
====

[quote, S.5.103-108]
____
There are the phenomenon of exertion, the phenomenon of endeavour, the 
phenomenon of application [to the practice]:

_Atthi bhikkhave ārambhadhātu nikkamadhātu parakkamadhātu._
____

.Illustration
====
dhātu

constituent elements
====

[quote, M.1.70]
____
The Perfect One discerns according to reality the world [of phenomena] with its 
many and various constituent elements.

_anekadhātunānādhātulokaṃ yathābhūtaṃ pajānāti._
____

.Illustration
====
dhātuso

material phenomena; dhātu, Phenomenon
====

____
Furthermore, the bhikkhu contemplates this very body however placed or disposed 
in terms of material phenomena

_imameva kāyaṃ yathāṭhitaṃ yathāpaṇihitaṃ dhātuso paccavekkhati_
____

• -- In this [wretched human] body there is the Solidness Phenomenon, the 
Liquidness Phenomenon, the Warmth Phenomenon, and the Gaseousness Phenomenon. +
A__tthi imasmiṃ kāye paṭhavīdhātu āpodhātu tejodhātu vāyodhātū 
ti__ (M.1.57).

.Illustration
====
dhātuyo

elements of sensation; dhātu, phenomenon
====

• There are these eighteen elements of sensation: +
_Aṭṭhārasa kho imā ānanda dhātuyo_

____
the phenomenon of sight, the phenomenon of visible objects, the phenomenon of 
advertence to the visual field._

_cakkhudhātu rūpadhātu cakkhuviññāṇadhātu;_
____

[quote, M.3.62]
____
the phenomenon of hearing, the phenomenon of audible objects, the phenomenon of 
advertence to the auditory field._

_sotadhātu saddadhātu sotaviññāṇadhātu._
____

.Illustration
====
dhātu

elements
====

[quote, D.2.282]
____
The [religious] world is made up of many and various elements, and whatever of 
these elements that beings stubbornly adhere to, then dogmatically grasping and 
stubbornly adhering they assert 'This alone is true, all else is false.'

_Anekadhātunānādhātu kho devānaminda loko. Tasmiṃ 
anekadhātunānādhātusmiṃ loke yaṃ yadeva sattā dhātuṃ abhinivisanti 
taṃ tadeva thāmasā parāmassa abhinivissa voharanti idameva saccaṃ 
moghamaññan ti._
____

.Illustration
====
dhātu

aspect
====

[quote, S.2.56]
____
Bhikkhu, that aspect of the teaching has been correctly penetrated by 
Sāriputta, which through being correctly penetrated... if I had for seven days 
and nights questioned Sāriputta about the matter in various ways and manners, 
then for seven days and nights Sāriputta would have been able to answer me in 
various ways and manners.

_Sā hi bhikkhu sāriputtassa dhammadhātu suppaṭividdhā yassa 
dhammadhātuyā suppaṭividdhattā... satta rattindivāni cepahaṃ 
sāriputtaṃ etamattaṃ puccheyyaṃ aññamaññehi padehi aññamaññehi 
pariyāyehi satta rattindivānipi me sāriputto etamatthaṃ vyākareyya 
aññamaññehi padehi aññamaññehi pariyāyehī ti._
____

.Illustration
====
dhātu

aspect
====

____
These two aspects of the Untroubled were made known by the Seer, free of 
attachment, and of excellent qualities.

_Duve imā cakkhumatā pakāsitā nibbānadhātu anissitena tādinā_
____

____
One aspect is realisable in this lifetime, with residue, but with the conduit 
to renewed states of individual existence destroyed;

_Ekā hi dhātu idha diṭṭhadhammikā saupādisesā bhavanettisaṅkhayā._
____

[quote, It.38-9]
____
The other, having no residue, is that wherein states of individual existence 
altogether cease.

_Anupādisesā pana samparāyikā yamhi nirujjhanti bhavāni sabbaso._
____

.Illustration
====
dhātu

plane of existence
====

Deed that produces karmic consequences in:

____
the sensuous plane of existence

_kāmadhātuvepakkañca kammaṃ_
____

____
the refined material plane of existence

_rūpadhātuvepakkañca kammaṃ_
____

[quote, A.1.223-4]
____
the immaterial plane of existence

_arūpadhātuvepakkañca kammaṃ._
____

.Illustration
====
dhātu

plane of existence
====

____
For beings [obstructed by] uninsightfulness into reality, and [tethered to 
individual existence] by craving

_avijjānīvaraṇānaṃ sattānaṃ taṇhāsaṃyojanānaṃ_
____

• the stream of sense consciousness is established in the low plane of 
existence** +
☸** _hīnāya dhātuyā viññāṇaṃ patiṭṭhitaṃ_

____
... the stream of sense consciousness is established in the middle plane of 
existence

_majjhimāya dhātuyā viññāṇaṃ patiṭṭhitaṃ_
____

____
... the stream of sense consciousness is established in the high plane of 
existence

_paṇītāya dhātuyā viññāṇaṃ patiṭṭhitaṃ_
____

[quote, A.1.223-4]
____
In this way renewed states of individual existence and rebirth occur in the 
future

_evaṃ āyatiṃ punabbhavābhinibbatti hoti._
____

.Illustration
====
dhātu

elements of existence
====

____
Now if other people insult, malign, exasperate and harass a bhikkhu he knows 
that an unpleasant sense impression born of auditory sensation has arisen 
within him which is dependent, not self-sufficient. Dependent on what? 
Dependent on sensation.

_uppannā kho me ayaṃ sotasamphassajā dukkhā vedanā sā ca kho paṭicca 
no appaṭicca. Kiṃ paṭicca? Phassaṃ paṭicca._
____

____
He sees that sensation is unlasting, sense impression is unlasting, perception 
is unlasting, intentional activities are unlasting, advertence is unlasting.

_So phasso anicco ti passati. Vedanā aniccā ti passati. Saññā aniccā ti 
passati. Saṅkhārā aniccā ti passa ti. Viññāṇaṃ aniccan ti passati._
____

[quote, M.1.186]
____
Having elements of existence as the basis [for spiritual development] his mind 
becomes energised, serene, settled, and intent upon [their contemplation].

_Tassa dhātārammaṇameva cittaṃ pakkhandati pasīdati santiṭṭhati 
adhimuccati._
____

.Illustration
====
dhātu

phenomenon; dhātu, practically redundant; dhātu, elements of existence
====

____
There are these six phenomena: the phenomenon of sensuous yearning, the 
phenomenon of unsensuousness, the phenomenon of ill will, the phenomenon of 
goodwill, the phenomenon of maliciousness, the phenomenon of compassion.

_Chayimā ānanda dhātuyo: kāmadhātu nekkhammadhātu vyāpādadhātu 
avyāpādadhātu vihiṃsādhātu avihiṃsādhātu_
____

[quote, M.3.62]
____
... Through knowing and seeing these six phenomena [according to reality], 
Ānanda, a bhikkhu can be called knowledgeable about elements of existence

_imā kho ānanda cha dhātuyo yato jānāti passati ettāvatā pi kho ānanda 
dhātukusalo bhikkhū ti alaṃ vacanāyā ti._
____

COMMENT

We say 'practically redundant,' meaning that, for example, 'the phenomenon of 
sensuous yearning' could be equally called 'sensuous yearning.'

.Illustration
====
dhātu

phenomenon; dhātu, practically redundant; dhātu, elements of existence
====

____
Six phenomena: the phenomenon of physical pleasure, the phenomenon of physical 
pain; the phenomenon of psychological pleasure; the phenomenon of psychological 
pain; the phenomenon of neutral experience; the phenomenon of uninsightfulness 
into reality

_chayimā ānanda dhātuyo: sukhadhātu dukkhadhātu somanassadhātu 
domanassadhātu upekkhādhātu avijjādhātu._
____

[quote, M.3.62]
____
... Through knowing and seeing these six phenomena [according to reality], 
Ānanda, a bhikkhu can be called knowledgeable about elements of existence

_Imā kho ānanda cha dhātuyo yato jānāti passati._
____

COMMENT

We say 'practically redundant,' meaning that, for example, 'the phenomenon of 
physical pleasure' could be equally called 'physical pleasure.'

.Illustration
====
dhātu

element: practically redundant
====

[quote, D.3.274]
____
Which two things should be fully understood? Two elements: the originated 
element and the unoriginated element

_Katame dve dhammā abhiññeyyā? Dve dhātuyo: saṅkhatā ca dhātu 
asaṅkhatā ca dhātu._
____

COMMENT

We say 'practically redundant,' meaning that, for example, 'the originated 
element' could be equally called 'what is originated.'

.Illustration
====
dhātu

phenomenon: redundant in some cases
====

The phenomenon of light (_ābhādhātu_), the phenomenon of loveliness 
(_subhadhātu_), the state of awareness of boundless space 
(_ākāsānañcāyatanadhātu_), the state of awareness of boundless mental 
consciousness (_viññāṇañcāyatanadhātu_), and the state of awareness of 
nonexistence (_ākiñcaññāyatanadhātu_): these phenomena are to be attained 
with perception (_imā dhātuyo saññāsamāpatti pattabbā_).

The state of awareness neither having nor lacking perception 
(_nevasaññānāsaññāyatanadhātu_) is a phenomena attained with a residue 
of effort (_ayaṃ dhātu saṅkhārāvasesā samāpatti pattabbā_, which 
M.2.231-2 shows means _saṅkhāra-avasesā_).

The phenomenon of the ending of perception and sense impression 
(_saññāvedayitanirodhadhātu_) is a phenomenon attained with the ending [of 
originated phenomena] (_ayaṃ dhātu nirodhasamāpatti pattabbāti_) (S.2.151).

COMMENT

We say 'redundant in some cases.' Here, for example, referring to 'the state of 
awareness of boundless space' as 'the phenomenon of the state of awareness of 
boundless space' is unwieldy.

.Illustration
====
dhātuyā

phenomenon: redundant
====

____
This, bhikkhu, is a designation for the Untroubled: the elimination of 
attachment, hatred, and undiscernment of reality.

_Nibbānadhātuyā kho etaṃ bhikkhu adhivacanaṃ rāgavinayo dosavinayo 
mohavinayo ti_
____

[quote, S.5.8]
____
The destruction of perceptually obscuring states is spoken of in that way.

_Āsavānaṃ khayo tena vuccatī ti._
____

COMMENT

We say 'redundant,' meaning that referring to the Untroubled as 'the phenomenon 
of the Untroubled' is a redundancy.

.Illustration
====
dhātu

phenomenon: redundant
====

[quote, D.2.141]
____
'Here the Perfect One passed away to the Untroubled-without-residue.

_idha tathāgato anupādisesāya nibbānadhātuyā parinibbuto ti pi._
____

COMMENT

We say 'redundant,' meaning that referring to 'the Untroubled-without-residue' 
as 'the phenomenon of the Untroubled-without-residue' is unwieldy.

.Illustration
====
lokadhātu

multi-universe system
====

• The ten thousandfold multi-universe system trembled, quaked, and shook +
_dasasahassī lokadhātu saṅkampi sampakampi sampavedhi_ (Vin.1.12).

