== Diṭṭhe dhamme; Sandiṭṭhika

=== Renderings

- _sandiṭṭhika_: discernable in this lifetime

- _sandiṭṭhika_: fathomable in this lifetime

- _sandiṭṭhika_: directly visible

- _diṭṭhe dhamme_: in this lifetime

- _diṭṭhe dhamme_: realisable in this lifetime

- _diṭṭhe dhamme_: fathomable in this lifetime

- _diṭṭheva dhamme_: in this very lifetime

- _diṭṭheva dhamme_: even in this lifetime

- _diṭṭhadhamma_: in this lifetime

- _diṭṭhadhammika_: realisable in this lifetime

- _diṭṭhadhammika_: in this lifetime

=== Illustrations: sandiṭṭhika

.Illustration
====
sandiṭṭhikaṃ

directly visible
====

____
-- Enjoy sensuous human pleasures, sirs; do not abandon what is directly 
visible in order to pursue what takes time.

_bhuñjantu bhonto mānusake kāme mā sandiṭṭhikaṃ hitvā kālikaṃ 
anudhāvitthāti_
____

[quote, S.1.117]
____
-- We have not abandoned what is directly visible, brahman, in order to pursue 
what takes time. We have abandoned what takes time in order to pursue what is 
directly visible.

_Na kho mayaṃ brāhmaṇa sandiṭṭhikaṃ hitvā kālikaṃ anudhāvāma 
kālikañca kho mayaṃ brāhmaṇa hitvā sandiṭṭhikaṃ anudhāvāma._
____

.Illustration
====
sandiṭṭhikā

discernable in this lifetime
====

____
As to previous karmically consequential conduct, he nullifies it by the gradual 
experience [of its consequences].

_purāṇañca kammaṃ phussa phussa vyantīkaroti._
____

• Its elimination is discernable in this lifetime, realisable in the here and 
now, intriguing, personally significant, to be realised by the wise for 
themselves +
☸ _sandiṭṭhikā nijjarā akālikā ehipassikā opanayikā paccattaṃ 
veditabbā viññūhīti_) (A.2.197).

.Illustration
====
sandiṭṭhiko

discernable in this lifetime
====

• Due to whatever craft by which a noble young man makes his living... he is 
exposed to cold and heat, he is injured by contact with horseflies, mosquitoes, 
wind, sun, and snakes; he faces death by hunger and thirst. +
☸ __Idha bhikkhave kulaputto yena sippaṭṭhānena jīvikaṃ kappeti... 
sītassa purakkhato uṇhassa purakkhato 
ḍaṃsamakasavātātapasiriṃsapasamphassehi rissamāno khuppipāsāya 
mīyamāno (M.__1.85).

[quote, M.1.85-7]
____
This is the danger of sensuous pleasures, a mass of suffering discernable in 
this lifetime

_Ayampi bhikkhave kāmānaṃ ādīnavo sandiṭṭhiko dukkhakkhandho._
____

.Illustration
====
sandiṭṭhikaṃ

discernable in this lifetime
====

[quote, D.1.59]
____
How can he, when asked about a fruit of the contemplative life discernable in 
this lifetime, answer with evasion?'

_Kathaṃ hi nāma sandiṭṭhikaṃ sāmaññaphalaṃ puṭṭho samāno 
vikkhepaṃ vyākarissati ti._
____

.Illustration
====
sandiṭṭhikā

discernable in this lifetime
====

____
When attachment is abandoned, he is not intent upon his own harm, or the harm 
of others, or the harm of both.

_rāge pahīne neva attavyābādhāyapi ceteti na paravyābādhāyapi ceteti na 
ubhayavyābādhāyapi ceteti._
____

[quote, S.4.339]
____
Its elimination is discernable in this lifetime, realisable in the here and 
now, intriguing, personally significant, to be realised by the wise for 
themselves.

_Sandiṭṭhikā nijjarā akālikā ehipassikā opanayikā paccattaṃ 
veditabbā viññūhi._
____

.Illustration
====
sandiṭṭhiko

fathomable in this lifetime
====

[quote, S.2.199]
____
'The teaching is well explained by the Blessed One, fathomable in this 
lifetime, realisable in the here and now, intriguing, personally applicable, to 
be realised by the wise for themselves.

_svākkhāto bhagavatā dhammo sandiṭṭhiko akāliko ehipassiko opanayiko 
paccattaṃ veditabbo viññūhī ti._
____

=== Illustrations: diṭṭhe dhamme

.Illustration
====
diṭṭhe dhamme

in this lifetime
====

[quote, S.1.86]
____
The wise person who is diligent [in performing meritorious deeds] secures both 
benefits: benefit in this lifetime, and benefit in the hereafter.

_Appamatto ubho atthe adhigaṇhāti paṇḍito +
Diṭṭhe dhamme ca yo attho yo cattho samparāyiko._
____

.Illustration
====
diṭṭhe dhamme

in this lifetime
====

[quote, S.4.207]
____
He is free of perceptually obscuring states in this lifetime.

_diṭṭhe dhamme anāsavo._
____

.Illustration
====
diṭṭhe dhamme

realisable in this lifetime
====

[quote, Sn.v.1066]
____
I shall explain inward peace to you, which is realisable in this lifetime, 
which is not just hearsay.

_Kintiyissāmi te santiṃ diṭṭhe dhamme anitihaṃ._
____

.Illustration
====
diṭṭhe dhamme

fathomable in this lifetime
====

[quote, Sn.v.1053]
____
I shall explain the teaching to you, which is fathomable in this lifetime, 
which is not just hearsay.

_kittayissāmi te dhammaṃ diṭṭhe dhamme anitihaṃ._
____

=== Illustrations: diṭṭheva dhamm

.Illustration
====
diṭṭheva dhamme

in this very lifetime
====

[quote, M.1.62]
____
If anyone practises the four _satipaṭṭhāna_ for seven days, one of two 
fruits can be expected. Either [the attainment of] arahantship in this very 
lifetime, or if there is a remnant of grasping, non-returnership.

_dvinnaṃ phalānaṃ aññataraṃ phalaṃ pāṭikaṅkhaṃ diṭṭheva 
dhamme aññā sati vā upādisese anāgāmitā ti._
____

.Illustration
====
diṭṭheva dhamme

in this very lifetime
====

[quote, Ud.37]
____
He realises the Untroubled in this very lifetime

_pāpuṇāti diṭṭheva dhamme nibbānaṃ ti._
____

.Illustration
====
diṭṭheva dhamme

even in this lifetime
====

[quote, M.1.139-140]
____
The Perfect One is untraceable even in this lifetime, I declare.'

_Diṭṭhevāhaṃ bhikkhave dhamme tathāgataṃ ananuvejjoti vadāmi._
____

=== Illustrations: diṭṭhadhamm

.Illustration
====
diṭṭhadhamma

in this lifetime
====

• Some proclaim a view concerning the highest pleasure in this lifetime. +
_Diṭṭhadhammanibbānaṃ vā paneke abhivadanti_ (M.2.229)

.Illustration
====
diṭṭhadhamma

in this lifetime
====

[quote, D.1.36]
____
The [absolute] Selfhood has not at that point attained to the highest pleasure 
in this lifetime.

_no ca kho bho ayaṃ attā ettāvatā paramadiṭṭhadhammanibbānaṃ patto 
hoti._
____

.Illustration
====
diṭṭhadhamma

in this lifetime
====

[quote, S.2.18]
____
One is fit to be called a bhikkhu who has realised the Untroubled in this 
lifetime.

_diṭṭhadhammanibbānappatto bhikkhū ti alaṃ vacanāya._
____

.Illustration
====
diṭṭhadhamma

in this lifetime
====

[quote, M.1.23]
____
Considering two good reasons, brahman, I frequent secluded abodes in forests 
and quiet groves: in considering a pleasant abiding for myself in this 
lifetime, and being tenderly concerned for future generations.

_attano ca diṭṭhadhammasukhavihāraṃ sampassamāno pacchimañca janataṃ 
anukampamāno ti._
____

.Illustration
====
diṭṭhadhamma

in this lifetime
====

[quote, S.5.150]
____
That foolish, incompetent, improficient bhikkhu does not gain pleasant states 
of meditation in this lifetime.

_Sakho so bhikkhave bālo avyatto akusalo bhikkhu naceva lābhī hoti 
diṭṭhadhammasukhavihārānaṃ._
____

.Illustration
====
diṭṭhadhamma

in this lifetime
====

[quote, D.1.36]
____
When the [absolute] Selfhood is enjoying itself, provided with and possessed of 
the five varieties of sensuous pleasure, at that point it has attained to the 
highest pleasure in this lifetime

_yato kho bho ayaṃ attā pañcahi kāmaguṇehi samappito samaṅgībhūto 
paricāreti ettāvatā kho bho ayaṃ attā paramadiṭṭhadhammanibbānaṃ 
patto hotī ti._
____

=== Illustrations: diṭṭhadhammikā

.Illustration
====
diṭṭhadhammikā

realisable in this lifetime
====

____
These two aspects of the Untroubled were made known by the Seer, free of 
attachment, and of excellent qualities.

_Duve imā cakkhumatā pakāsitā +
Nibbānadhātu anissitena tādinā_
____

____
One aspect is realisable in this lifetime, with residue, but with the conduit 
to renewed states of individual existence destroyed;

_Ekā hi dhātu idha diṭṭhadhammikā +
Saupādisesā bhavanettisaṅkhayā._
____

[quote, It.38-9]
____
The other, having no residue, is that wherein states of individual existence 
altogether cease.

_Anupādisesā pana samparāyikā +
Yamhi nirujjhanti bhavāni sabbaso._
____

.Illustration
====
diṭṭhadhammikā

in this lifetime
====

• Because one who is passionately attached to sensuous pleasure, fastened by 
fondness and attachment, is neither free of danger in this lifetime, nor in the 
hereafter, therefore 'danger' is an epithet for sensuous pleasures. +
_Yasmā ca kāmarāgarattāyaṃ bhikkhave chandarāgavinibaddho 
diṭṭhadhammikāpi bhayā na parimuccati samparāyikāpi bhayā na 
parimuccati. Tasmā bhayanti kāmānametaṃ adhivacanaṃ_ (A.3.310).

.Illustration
====
diṭṭhadhammikā

in this lifetime; of this lifetime
====

[quote, M.2.261-2]
____
Sensuous pleasures in this lifetime and in the hereafter, mental images of 
sensuous pleasures of this lifetime and of the hereafter, both alike are 
Māra's realm, Māra's domain, Māra's bait, Māra's hunting ground.

_Ye ca diṭṭhadhammikā kāmā ye ca samparāyikā kāmā yā ca 
diṭṭhadhammikā kāmasaññā yā ca samparāyikā kāmasaññā 
ubhayametaṃ māradheyyaṃ mārassesavisayo marassesanivāpo 
mārassesagocaro._
____

.Illustration
====
diṭṭhadhammikānaṃ

in this lifetime
====

[quote, A.1.99]
____
For two good reasons the Perfect One establishes the mānatta penance for his 
disciples: to restrain perceptually obscuring states in this lifetime and to 
ward them off in the hereafter.

_Dveme bhikkhave atthavase paṭicca tathāgatena sāvakānaṃ 
mānattadānaṃ paññattaṃ. Katame dve? Diṭṭhadhammikānaṃ 
āsavānaṃ saṃvarāya samparāyikānaṃ āsavānaṃ paṭighātāya._
____

