== Diṭṭhi

=== Renderings

- _micchādiṭṭhi_: wrong view [of reality]

- _sammādiṭṭhi_: right view [of reality]

- _sammādiṭṭhi_: right perception [of reality]

- _diṭṭhi_: perception [of reality]

- _diṭṭhi_: view

- _diṭṭhi_: dogmatic view

- _diṭṭhi_: right view

- _diṭṭhi_: basic religious understanding

- _diṭṭhi_: dogmatism

- _diṭṭhi ujukā_: view [of reality] that is correct

- _diṭṭhappatto_: attained to [right] perception [of reality]

- _diṭṭhigata_: view

- _diṭṭhigata_: theory

- _diṭṭhigata_: wrong view [of reality]

- _diṭṭhigata_: dogmatic view

- _diṭṭhigata_: acquiescence in dogmatism

- _diṭṭhigata_: acquiescence in wrong view [of reality]

=== Introduction

==== Micchādiṭṭhi means wrong view [of reality]

The definition of _micchādiṭṭhi_ shows why it should be called 'wrong view 
&#8203;[of reality]':

____
And what is wrong view [of reality]?

_Katamā ca bhikkhave micchādiṭṭhi?_
____

[quote, M.3.71]
____
... [The view that] 'There is no merit in giving, donating and offering; no 
fruit or result of good or bad deeds; no this world; no hereafter; no duties to 
parents; no spontaneously arisen beings; no ascetics or Brahmanists who, 
conducting and applying themselves rightly in the world, proclaim this world 
and the hereafter after having realising it for themselves through transcendent 
insight.

_Natthi dinnaṃ natthi yiṭṭhaṃ natthi hutaṃ natthi 
sukaṭadukkaṭānaṃ kammānaṃ phalaṃ vipāko natthi ayaṃ loko natthi 
paro loko natthi mātā natthi pitā natthi sattā opapātikā natthi loke 
samaṇabrāhmaṇā sammaggatā sammāpaṭipannā ye imañca lokaṃ parañca 
lokaṃ sayaṃ abhiññā sacchikatvā pavedentī ti._
____

==== Sammādiṭṭhi: right view and right perception

_Sammādiṭṭhi_ is defined in two ways, so it has two meanings:

1. right view [of reality]

2. right perception [of reality]

Right view [of reality] is a primary practice, right perception [of reality] is 
more advanced:

____
What is right view/perception [of reality]?

_Katamā ca bhikkhave sammādiṭṭhi_
____

____
Right view/perception [of reality] is of two sorts, I declare.

_sammādiṭṭhimpahaṃ bhikkhave dvayaṃ vadāmi:_
____

____
There is (1) right view [of reality] associated with perceptually obscuring 
states, that is meritorious and results in attachment, and (2) there is right 
perception [of reality] that is noble, free of perceptually obscuring states, 
transcendental, a factor of the Path.

_atthi bhikkhave sammādiṭṭhi sāsavā puññābhāgiyā upadhivepakkā 
atthi bhikkhave sammādiṭṭhi ariyā anāsavā lokuttarā maggaṅgā._
____

____
What is right view [of reality] associated with perceptually obscuring states, 
that is meritorious and results in attachment?

_Katamā ca bhikkhave sammādiṭṭhi sāsavā puññabhāgiyā upadhivepakkā_
____

____
There is merit in giving, donating and offering; there is a fruit and result of 
good and bad deeds; there exists both this world and a world beyond; there are 
duties to parents; there are spontaneously arisen beings; there are ascetics 
and Brahmanists conducting and applying themselves rightly in the world who, 
having realised this world and the world hereafter for themselves through 
transcendent insight, make them known to others.

_atthi dinnaṃ atthi yiṭṭhaṃ atthi hutaṃ atthi sukaṭadukkaṭānaṃ 
kammānaṃ phalaṃ vipāko atthi ayaṃ loko atthi paro loko atthi mātā 
atthi pitā atthi sattā opapātikā atthi loke samaṇabrāhmaṇā 
sammaggatā sammāpaṭipannā ye imañca lokaṃ parañca lokaṃ sayaṃ 
abhiññā sacchikatvā pavedentīti_
____

____
And what is right perception [of reality] that is noble, free of perceptually 
obscuring states, transcendental, a factor of the Path?

_Katamā ca bhikkhave sammādiṭṭhi ariyā anāsavā lokuttarā maggaṅgā:_
____

[quote, M.3.72]
____
The penetrative discernment, the faculty of penetrative discernment, the power 
of penetrative discernment, the enlightenment factor of examination of the 
teaching, the right perception [of reality] in one whose mind is noble, whose 
mind is free of perceptually obscuring states, who is developing the noble 
path, is right perception [of reality] that is noble, free of perceptually 
obscuring states, transcendental, a factor of the Path.

_Yā kho bhikkhave ariyacittassa anāsavacittassa ariyamaggasamaṅgino 
ariyamaggaṃ bhāvayato paññā paññindriyaṃ paññābalaṃ 
dhammavicayasambojjhaṅgo sammādiṭṭhi maggaṅgaṃ ayaṃ vuccati 
bhikkhave sammādiṭṭhi ariyā anāsavā lokuttarā maggaṅgā._
____

==== Sammādiṭṭhi means perception: four reasons

There are four definitions that support us rendering the higher meaning of 
_sammādiṭṭhi_ in terms of perception, not view:

The scriptures define _sammādiṭṭhi_ in terms of discernment (_pajānāti_):

[quote, M.1.46-7]
____
When a noble disciple discerns suffering... On these grounds a noble disciple 
has right perception [of reality]

_Yato kho āvuso ariyasāvako dukkhañca pajānāti... ettāvatā pi kho āvuso 
ariyasāvako sammādiṭṭhi hoti._

When a noble disciple discerns what is spiritually unwholesome... On these 
grounds a noble disciple has right perception [of reality].

_Yato kho āvuso ariyasāvako akusalañca pajānāti... Ettāvatā pi kho 
āvuso ariyasāvako sammādiṭṭhi hoti._
____

[quote, M.3.72]
____
He knows wrong view [of reality] as wrong view [of reality] and right 
perception [of reality] as right perception [of reality]. That is his right 
perception [of reality].

_Micchādiṭṭhiṃ micchādiṭṭhī ti pajānāti sammādiṭṭhiṃ 
sammādiṭṭhī ti pajānāti sāssa hoti sammādiṭṭhi._
____

The scriptures define _sammādiṭṭhi_ in terms of insightfulness (_vijjāgata_):

[quote, S.5.1]
____
For an intelligent person with insight into reality, right perception [of 
reality] arises.

_vijjāgatassa bhikkhave viddasuno sammādiṭṭhi pahoti._
____

The scriptures define _sammādiṭṭhi_ in terms of perceiving (_passati_):

[quote, S.3.51]
____
A bhikkhu perceives as unlasting, bodily form which is indeed unlasting. That 
is his right perception [of reality].

_Aniccaññeva bhikkhave bhikkhu rūpaṃ aniccanti passati sāssa hoti 
sammādiṭṭhi._
____

The scriptures define _sammādiṭṭhi_ in terms of knowledge [of things according to reality] (_ñāṇaṃ_):

[quote, M.3.251]
____
Whatsoever is the knowledge of suffering [according to reality], of the origin 
of suffering, the ending of suffering, and of the practice leading to the 
ending of suffering, is called right perception [of reality].

_yaṃ kho āvuso dukkhe ñāṇaṃ dukkhasamudaye ñāṇaṃ dukkhanirodhe 
ñāṇaṃ dukkhanirodhagāminiyā paṭipadāya ñāṇaṃ. Ayaṃ 
vuccatāvuso sammādiṭṭhi._
____

==== Diṭṭhi: view and dogmatic view

_Diṭṭhi_ sometimes means simply 'view.' But where a view is formally 
propounded we call it 'dogmatic view'. A dogmatic view is associated with the 
idea 'This alone is true.' For example, Sn.v.895 asks:

[quote, Sn.v.895]
____
For those who dispute, maintaining a dogmatic view, saying "This alone is 
true," is criticism all that they bring upon themselves? Do they not also 
receive praise?

_Ye kecime diṭṭhiṃ paribbasānā idameva saccan ti vivādayanti +
Sabbeva te nindamanvānayanti atho pasaṃsampi labhanti tattha._
____

[quote, M.2.171]
____
The wise do not resort to any dogmatic view because it may turn out to be 
either true or false. Under such conditions, 'it is not fitting for a wise man 
who preserves truth to come to the unqualified conclusion, "This alone is true, 
all else is false."'

_saccamanurakkhatā bhāradvāja viññunā purisena nālamettha ekaṃsena 
niṭṭhaṃ gantuṃ idameva saccaṃ moghamaññan ti._
____

==== Diṭṭhi ujukā: a view [of reality] that is correct

_Diṭṭhi ujukā_ is a rudimentary practice, not an advanced practice, and 
therefore means 'view [of reality] that is correct' not 'perception [of 
reality] that is correct':

[quote, S.5.143]
____
And what is the basis of spiritually wholesome factors? Virtue that is well 
purified and view [of reality] that is correct.

_Ko ca ādi kusalānaṃ dhammānaṃ. Sīlañca suvisuddhaṃ diṭṭhi ca 
ujukā._
____

=== Illustrations: right perception [of reality]; micchādiṭṭhi, wrong view 
&#8203;[of reality]

.Illustration
====
sammādiṭṭhi

right perception [of reality]; micchādiṭṭhi, wrong view [of reality]
====

[quote, A.5.218]
____
For one with right perception [of reality], wrong view [of reality] is purged 
away.

_Sammādiṭṭhikassa bhikkhave micchādiṭṭhi viritto hoti._
____

.Illustration
====
sammādiṭṭhi

right perception [of reality]
====

____
When a noble disciple discerns what is spiritually unwholesome, the origin of 
what is spiritually unwholesome, what is spiritually wholesome, and the origin 
of what is spiritually wholesome,

_Yato kho āvuso ariyasāvako akusalañca pajānāti akusalamūlañca 
pajānāti. Kusalañca pajānāti kusalamūlañca pajānāti_
____

[quote, M.1.46-7]
____
On these grounds a noble disciple has right perception [of reality], has a 
perception [of reality] that is correct, has unshakeable faith in the 
&#8203;[significance of the] teaching, and has fathomed this true teaching.

_Ettāvatā pi kho āvuso ariyasāvako sammādiṭṭhi hoti ujugatāssa 
diṭṭhi dhamme aveccappasādena samannāgato āgato imaṃ saddhamman ti._
____

.Illustration
====
sammādiṭṭhi

right perception [of reality]
====

[quote, M.3.251]
____
Whatsoever is the knowledge of suffering [according to reality], of the origin 
of suffering, the ending of suffering, and of the practice leading to the 
ending of suffering, is called right perception [of reality].

_yaṃ kho āvuso dukkhe ñāṇaṃ dukkhasamudaye ñāṇaṃ dukkhanirodhe 
ñāṇaṃ dukkhanirodhagāminiyā paṭipadāya ñāṇaṃ. Ayaṃ 
vuccatāvuso sammādiṭṭhi._
____

.Illustration
====
sammādiṭṭhi

right perception [of reality]
====

[quote, D.2.217]
____
From right perception [of reality] arises right thought; from right thought 
arises right speech.

_sammādiṭṭhissa bho sammāsaṅkappo pahoti sammāsaṅkappassa 
sammāvācā pahoti sammāvācassa sammākammanto pahoti._
____

.Illustration
====
sammādiṭṭhi

right perception [of reality]
====

[quote, S.3.51]
____
A bhikkhu perceives as unlasting, bodily form which is indeed unlasting. That 
is his right perception [of reality].

_Aniccaññeva bhikkhave bhikkhu rūpaṃ aniccanti passati sāssa hoti 
sammādiṭṭhi._
____

.Illustration
====
micchādiṭṭhi

wrong view [of reality]; sammādiṭṭhi, right perception [of reality]
====

[quote, M.3.72]
____
He knows wrong view [of reality] as wrong view [of reality] and right 
perception [of reality] as right perception [of reality]. That is his right 
perception [of reality].

_Micchādiṭṭhiṃ micchādiṭṭhī ti pajānāti sammādiṭṭhiṃ 
sammādiṭṭhī ti pajānāti sāssa hoti sammādiṭṭhi._
____

.Illustration
====
micchādiṭṭhi

wrong view [of reality]; sammādiṭṭhi, right perception [of reality]
====

____
For an ignorant person void of insight into reality, wrong view [of reality] 
arises.

_avijjāgatassa bhikkhave aviddasuno micchādiṭṭhi pahoti_
____

[quote, S.5.1-2]
____
For an intelligent person with insight into reality, right perception [of 
reality] arises.

_vijjāgatassa bhikkhave viddasuno sammādiṭṭhi pahoti._
____

.Illustration
====
micchādiṭṭhi

wrong view [of reality]
====

____
-- What do you think, bhikkhus? Is bodily form lasting or unlasting?

_taṃ kiṃ maññatha bhikkhave rūpaṃ niccaṃ vā aniccaṃ vā ti_
____

____
-- That which is unlasting, is it existentially void or existentially 
substantial?

_dukkhaṃ vā taṃ sukhaṃ vā_
____

____
-- Without grasping that which is unlasting, existentially void, destined to 
change, would there arise wrong view [of reality]?

_api nu taṃ anupādāya micchādiṭṭhi uppajjeyyā ti?_
____

-- No, bhante (S.3.184).

.Illustration
====
micchādiṭṭhi

wrong view [of reality]
====

[quote, S.4.148]
____
Bhikkhu, when one knows and sees the visual sense as unlasting, wrong view [of 
reality] is abandoned.

_cakkhuṃ kho bhikkhū aniccato jānato passato micchādiṭṭhi pahīyati._
____

=== Illustrations: diṭṭhi, [right] perception [of reality]

.Illustration
====
diṭṭhi

&#8203;[right] perception [of reality]
====

[quote, D.3.253]
____
A bhikkhu is keenly eager to acquire [right] perception [of reality] and his 
dedication to this does not dwindle away in the course of time

_diṭṭhipaṭivedhe tibbacchando hoti āyatiñca diṭṭhipaṭivedhe 
avigatapemo._
____

.Illustration
====
diṭṭhi

&#8203;[right] perception [of reality]
====

____
And what is the individual attained to [right] perception [of reality]?

_Katamo ca bhikkhave puggalo diṭṭhappatto_
____

____
In this regard, some person does not abide touching with his very being those 
immaterial states of awareness, those peaceful states of refined awareness that 
transcend the refined material states of awareness,

_idha bhikkhave ekacco puggalo ye te santā vimokkhā atikkamma rūpe āruppā 
te na kāyena phassitvā viharati_
____

____
but by seeing [reality] with penetrative discernment, some of his perceptually 
obscuring states are destroyed

_paññāya cassa disvā ekacce āsavā parikkhīṇā honti_
____

____
and he has reviewed and examined with penetrative discernment the teachings 
proclaimed by the Perfect One

_tathāgatappaveditā cassa dhammā paññāya vodiṭṭhā honti vocaritā_
____

[quote, M.1.477-9]
____
This is called an individual attained to [right] perception [of reality].

_Ayaṃ vuccati bhikkhave puggalo diṭṭhappatto._
____

=== Illustrations: sammādiṭṭhi, right view [of reality]

.Illustration
====
sammādiṭṭhi

right view [of reality]; diṭṭhi, basic religious understanding
====

____
What is perfection in basic religious understanding?

_Katamā ca bhikkhave diṭṭhisampadā?_
____

[quote, A.1.268-9]
____
In this regard, some person has right view [of reality]. He has the unerroneous 
view that there is merit in giving, donating and offering; there is a fruit and 
result of good and bad deeds; there exists both this world and a world beyond; 
there are duties to parents; there are spontaneously arisen beings; there are 
ascetics and Brahmanists conducting and applying themselves rightly in the 
world who, having realised this world and the world hereafter for themselves 
through transcendent insight, make them known to others.

_Idha bhikkhave ekacco sammādiṭṭhiko hoti aviparītadassano atthi dinnaṃ 
atthi yiṭṭhaṃ atthi hutaṃ atthi sukaṭadukkaṭānaṃ kammānaṃ 
phalaṃ vipāko atthi ayaṃ loko atthi paro loko atthi mātā atthi pitā 
atthi sattā opapātikā atthi loke samaṇabrāhmaṇā sammaggatā 
sammāpaṭipannā ye imañca lokaṃ parañca lokaṃ sayaṃ abhiññā 
sacchikatvā pavedentī'ti._
____

=== Illustrations: diṭṭhi, basic religious understanding

.Illustration
====
diṭṭhi

basic religious understanding
====

[quote, A.1.268-9]
____
What is perfection in basic religious understanding? In this regard, some 
person has right view [of reality]. He has the unerroneous view that there is 
merit in giving, donating and offering...

_Katamā ca bhikkhave diṭṭhisampadā? Idha bhikkhave ekacco 
sammādiṭṭhiko hoti aviparītadassano atthi dinnaṃ atthi yiṭṭhaṃ 
atthi hutaṃ...._
____

.Illustration
====
diṭṭhi

basic religious understanding
====

• Wrong view [of reality], and grasping an unenlightening doctrine: this is 
errancy in basic religious understanding +
_Micchādiṭṭhi antaggāhikādiṭṭhi ayaṃ diṭṭhivipatti ti_ 
(Vin.1.172).

.Illustration
====
diṭṭhi

basic religious understanding
====

____
What is errancy in basic religious understanding? In this regard, some person 
has wrong view [of reality].

_Katamā ca bhikkhave diṭṭhivipatti? Idha bhikkhave ekacco 
micchādiṭṭhiko hoti._
____

____
He has the erroneous view that:

_Viparītadassano_
____

____
there is no merit in giving, donating and offering

_natthi dinnaṃ natthi yiṭṭhaṃ natthi hutaṃ_
____

____
there are no fruits or results of good and bad deeds

_natthi sukaṭadukkaṭānaṃ kammānaṃ phalaṃ vipāko_
____

____
there is no this world; no hereafter; no duties to parents; no spontaneously 
arisen beings;

_natthi ayaṃ loko natthi paroloko natthi mātā natthi pitā natthi sattā 
opapātikā_
____

[quote, A.1.268-9]
____
there are no ascetics and Brahmanists conducting and applying themselves 
rightly in the world who, having realised this world and the hereafter for 
themselves through transcendent insight make them known to others.

_natthi loke samaṇabrāhmaṇā sammaggatā sammāpaṭipannā ye imañca 
lokaṃ parañca lokaṃ sayaṃ abhiññā sacchikatvā pavedentī ti. Ayaṃ 
vuccati bhikkhave diṭṭhivipatti._
____

.Illustration
====
diṭṭhi

basic religious understanding
====

____
So, too, for a bhikkhu this is the foretoken and preindication of the arising 
of the noble eightfold path, namely, perfection in basic religious 
understanding.

_bhikkhuno ariyassa aṭṭhaṅgikassa maggassa uppādāya etaṃ 
pubbaṅgamaṃ etaṃ pubbanimittaṃ yadidaṃ diṭṭhisampadā_
____

[quote, S.5.30]
____
When a bhikkhu is perfect in basic religious understanding, it is to be 
expected that he will develop and cultivate this noble eightfold path

_Diṭṭhisampannassetaṃ bhikkhave bhikkhuno pāṭikaṅkhaṃ ariyaṃ 
aṭṭhaṅgikaṃ maggaṃ bhāvessati ariyaṃ aṭṭhaṅgikaṃ maggaṃ 
bahulīkarissatīti._
____

.Illustration
====
diṭṭhi

basic religious understanding
====

[quote, M.1.324]
____
This is the character of a person who is perfect in basic religious 
understanding. If he commits some kind of offence for which a means of 
rehabilitation has been laid down, then he at once confesses, reveals, and 
discloses it to the teacher or to wise companions in the religious life, and 
having done that he shows restraint in future.

_Dhammatā esā bhikkhave diṭṭhisampannassa puggalassa kiñcāpi 
tathārūpiṃ āpattiṃ āpajjati yathārūpāya āpattiyā uṭṭhānaṃ 
paññāyati atha kho khippameva satthari vā viññūsu vā sabrahmacārīsu 
deseti vivarati uttānī karoti. Desetvā vivaritvā uttānī karitvā 
āyatiṃ saṃvaraṃ āpajjati._
____

.Illustration
====
diṭṭhi

basic religious understanding
====

When a noble disciple (_ariyasāvako_) has perfectly and fully realised these 
two kinds of knowledge (_dve ñāṇāni parisuddhāni honti pariyodātāni_ -- 
knowledge of the nature of reality and knowledge of conformity -- he is then 
called a noble disciple

____
perfect in basic religious understanding _

_diṭṭhisampanno_
____

____
with perfect vision [of things according to reality]_

_dassanasampanno_
____

• who has fathomed this true teaching _ +
☸ āgato imaṃ saddhammaṃ_

[quote, S.2.58]
____
who understands this true teaching _

_passati imaṃ saddhammaṃ._
____

=== Illustrations: diṭṭhi, perception [of reality]

.Illustration
====
diṭṭhi

perception [of reality]
====

In this regard a bhikkhu discerns according to reality (_yathābhūtaṃ 
pajānāti_) that:

____
This is suffering

_idaṃ dukkhan ti yathābhūtaṃ pajānāti_
____

____
This is the origin of suffering

_ayaṃ dukkhasamudayo ti yathābhūtaṃ pajānāti_
____

____
This is the ending of suffering

_ayaṃ dukkhanirodho ti yathābhūtaṃ pajānāti_
____

____
This is the practice leading to the ending of suffering

_ayaṃ dukkhanirodhagāminī paṭipadā ti yathābhūtaṃ pajānāti_
____

[quote, A.2.195]
____
This, Men of the Leopard Path, is called the utter purification of one's 
perception [of reality]

_ayaṃ vuccati byagghapajjā diṭṭhipārisuddhi._
____

.Illustration
====
diṭṭhiṃ

perception [of reality]
====

____
-- Bhikkhus, do you see, 'This is brought about?'

_bhūtamidan ti bhikkhave passathā ti?_
____

-- Yes, bhante

____
-- Bhikkhus, do you see: 'It is arisen with that as its nourishing condition'?

_tadāhārasambhavan ti bhikkhave passathā ti?_
____

-- Yes, bhante

____
-- Bhikkhus, do you see: 'With the ending of that nourishing condition, what is 
brought about is destined to cease'?

_tadāhāranirodhā yaṃ bhūtaṃ taṃ nirodhadhamman ti bhikkhave passathā 
ti?_
____

-- Yes, bhante

____
-- But if you cling to, prize, treasure, and cherish this perception [of 
reality] so perfect and pure would you then have understood that the teaching 
explained by me is comparable to a raft, being for the sake of crossing [the 
flood of suffering], not for the sake of clinging to it?

_Imañce tumhe bhikkhave diṭṭhiṃ evaṃ parisuddhaṃ evaṃ 
pariyodātaṃ allīyetha keḷāyetha dhanāyetha mamāyetha api nu tumhe 
bhikkhave kullūpamaṃ dhammaṃ desitaṃ ājāneyyātha nittharaṇatthāya 
no gahaṇatthāyāti?_
____

-- No, bhante (M.1.260).

=== Illustrations: diṭṭhi, view

.Illustration
====
diṭṭhi

view
====

• -- But, bhante, how does the view of personal identity come to be?" +
_Kathampana bhante sakkāyadiṭṭhi hotī ti?_

-- In this regard, householder, the ignorant Everyman... regards

____
bodily form to be the [absolute] Selfhood

_rūpaṃ attato samanupassati_
____

____
the [absolute] Selfhood to be corporeal

_rūpavantaṃ vā attānaṃ_
____

____
bodily form to be part of the [absolute] Selfhood

_attani vā rūpaṃ_
____

____
the [absolute] Selfhood to be part of bodily form...

_rūpasmiṃ vā attānaṃ_
____

[quote, S.4.286-7]
____
In this way the view of personal identity comes to be

_evaṃ kho gahapati sakkāyadiṭṭhi hotī ti._
____

.Illustration
====
diṭṭhi

view
====

____
-- Bhante, when, in regard to those who are not perfectly enlightened, the view 
arises that they are in fact perfectly enlightened, due to what is this view to 
be discerned?

_yāyaṃ bhante diṭṭhi asammāsambuddhesu sammā sambuddhā ti. Ayaṃ nu 
kho bhante diṭṭhi kiṃ paṭicca paññāyatī ti_
____

[quote, S.2.153]
____
-- Mighty, Kaccāna, is this phenomenon, namely the phenomenon of 
uninsightfulness into reality

_mahati kho esā kaccāna dhātu yadidaṃ avijjādhātu._
____

.Illustration
====
diṭṭhi

view
====

[quote, S.3.204]
____
When there is bodily form, by grasping bodily form, by stubbornly adhering to 
bodily form, this view arises: 'This is "[in reality] mine," this is "[in 
reality] what I am," this is "my [absolute] Selfhood."'

_rūpe kho bhikkhave sati rūpaṃ upādāya rūpaṃ abhinivissa evaṃ 
diṭṭhi uppajjati: etaṃ mama eso'hamasmi eso me attā ti._
____

.Illustration
====
diṭṭhi

view
====

[quote, S.4.148]
____
When one knows and sees the visual sense as void of personal qualities, the 
view that it is an [absolute] Selfhood is abandoned.

_Cakkhuṃ kho bhikkhu anattato jānato passato attānudiṭṭhi pahīyati._
____

.Illustration
====
diṭṭhiyā

view
====

[quote, A.3.447]
____
To abandon the view that there is sweetness in originated phenomena the 
perception of the unlastingness [of the five aggregates] should be developed .

_Assādadiṭṭhiyā pahānāya aniccasaññā bhāvetabbā._
____

=== Illustrations: diṭṭhi, dogmatic view

.Illustration
====
diṭṭhi

dogmatic view; diṭṭhi, view [of reality]
====

[quote, M.1.402]
____
Since there is indeed a world beyond, one who has the dogmatic view 'There is 
no world beyond' has a wrong view [of reality].

_Santaṃyeva kho pana paraṃ lokaṃ natthi paro lokotissa diṭṭhi hoti 
sāssa hoti micchādiṭṭhi._
____

.Illustration
====
diṭṭhi

dogmatic view; view [of reality]
====

In this regard, Seniya, some person develops the bovine practice, bovine 
conduct, mentality, and way of behavious completely and constantly. Having done 
so, at death he arises in companionship with cattle.

[quote, M.1.388]
____
But if he has the dogmatic view that (_evaṃ diṭṭhi hoti_) through this 
practice he will become some kind of deva that is his wrong view [of reality] 
(_sāssa hoti micchādiṭṭhi_). 

_sace kho panassa evaṃ diṭṭhi hoti: iminā'haṃ sīlena vā vatena vā 
tapena vā brahmacariyena vā devo vā bhavissāmi devaññataro vā ti sāssa 
hoti micchādiṭṭhi._
____

.Illustration
====
diṭṭhi

dogmatic view
====

____
Although questioned, interrogated, and examined by those bhikkhus, the bhikkhu 
Sāti, son of a fisherman, dogmatically grasping and stubbornly adhering to 
that same odious dogmatic view, asserted

_tadeva pāpakaṃ diṭṭhigataṃ thāmasā parāmassa abhinivissa voharati_
____

• 'As I understand the teaching explained by the Blessed One, it is this 
personal _viññāṇa_ that roams and wanders the round of birth and death, 
not another. +
☸... _yathā tadevidaṃ viññāṇaṃ sandhāvati saṃsarati anaññan 
ti_ (M.1.257).

.Illustration
====
diṭṭhi

dogmatic view
====

____
Resorting to what kind of dogmatic view (_diṭṭhipaṭilābhaṃ_) do 
spiritually unwholesome factors flourish and spiritually wholesome factors fade?

_Kathaṃrūpaṃ bhante diṭṭhipaṭilābhaṃ sevato akusalā dhammā 
abhivaḍḍhanti kusalā dhammā parihāyanti:_
____

____
In this regard some person has this dogmatic view:

_idha bhante ekacco evaṃdiṭṭhiko hoti_
____

____
there is no merit in giving, donating and offering _

_natthi dinnaṃ natthi yiṭṭhaṃ natthi hutaṃ_
____

____
there are no fruits or results of good and bad deeds

_natthi sukaṭadukkaṭānaṃ kammānaṃ phalaṃ vipāko_
____

____
there is no this world; no hereafter; no duties to parents; no spontaneously 
arisen beings;_

_natthi ayaṃ loko natthi paro loko natthi mātā natthi pitā natthi sattā 
opapātikā_
____

____
there are no ascetics and Brahmanists conducting and applying themselves 
rightly in the world who, having realised this world and the hereafter for 
themselves through transcendent insight make them known to others

_natthi loke samaṇabrāhmaṇā sammaggatā sammāpaṭipannā ye imañca 
lokaṃ parañca lokaṃ sayaṃ abhiññā sacchikatvā pavedentī ti_
____

____
Resorting to what kind of dogmatic view do spiritually unwholesome factors fade 
and spiritually wholesome factors flourish?

_Kathaṃrūpaṃ bhante diṭṭhipaṭilābhaṃ sevato akusalā dhammā 
parihāyanti kusalā dhammā abhivaḍḍhanti_
____

____
In this regard some person has this dogmatic view,

_Idha bhante ekacco evaṃ diṭṭhiko hoti_
____

there are results of gifts, donations and offerings. There are results of good 
and bad deeds. There is this world, a world beyond, mother, father, 
spontaneously arisen beings, There are ascetics and Brahmanists who realising 
this world and the world hereafter, declare it (M.3.52).

.Illustration
====
diṭṭhi

dogmatic view
====

____
Or he has this dogmatic view: 'The [absolute] Selfhood is the whole world [of 
phenomena]. Having passed on, that I will be -- everlasting, enduring, eternal, 
of an unchangeable nature.' That eternalist view is an originated phenomenon...

_evaṃ diṭṭhi hoti. So attā so loko so pecca bhavissāmi nicco dhuvo 
sassato avipariṇāmadhammoti. Yā kho pana sā bhikkhave sassatadiṭṭhi 
saṅkhāro so_
____

[quote, S.3.99]
____
Or he has this dogmatic view: 'Had I not been, it would not have been "mine." I 
will be not, not "mine" will it be.' That annihilationist view is an originated 
phenomenon...

_evaṃ diṭṭhi hoti no c'assaṃ no ca me siyā na bhavissāmi na me 
bhavissatī ti. Yā kho pana sā bhikkhave ucchedadiṭṭhi saṅkhāro so._
____

.Illustration
====
diṭṭhi

dogmatic views
====

[quote, Sn.v.891]
____
'Those who assert a doctrine different from this have strayed from spiritual 
purity. They are not spiritually perfected.' Non-Buddhist ascetics each say 
this because they are passionately attached to their own dogmatic views.

_Aññaṃ ito yābhivadanti dhammaṃ aparaddhā suddhimakevalī te +
Evampi titthiyā puthuso vadanti sandiṭṭhirāgena hi tebhirattā._
____

.Illustration
====
diṭṭhino

dogmatic view
====

There are certain ascetics and Brahmanists whose doctrine and dogmatic view is 
this (_evaṃ vādino evaṃ diṭṭhino_): 'Purification comes about through 
venerating fire (_aggiparicariyāya suddhī ti_) (M.1.77-82).

.Illustration
====
diṭṭhino

dogmatic views
====

____
Bhikkhus, there are some ascetics and Brahmanists who speculate about the 
future and who hold dogmatic views concerning the future, who make various 
assertions about the future

_Santi bhikkhave eke samaṇabrāhmaṇā aparantakappikā 
aparantānudiṭṭhino aparantaṃ ārabbha anekavihitāni adhivuttipadāni 
abhivadanti:_
____

____
Some assert that the [absolute] Selfhood is perceptive and unimpaired after 
death

_Saññī attā hoti arogo parammaraṇā ti ittheke abhivadanti._
____

[quote, M.2.228]
____
Some assert that the [absolute] Selfhood is unperceptive and unimpaired after 
death.

_asaññī attā hoti arogo parammaraṇā ti ittheke abhivadanti._
____

.Illustration
====
diṭṭhi

dogmatism; diṭṭhi, views
====

____
What is the bondage [to individual existence] that arises from dogmatism?

_Diṭṭhiyogo ca kathaṃ hoti?_
____

____
In this regard, some person does not discern according to reality the 
origination, vanishing, sweetness, wretchedness, and deliverance in regards to 
views.

_Tassa diṭṭhīnaṃ samudayañca atthaṅgamañca assādañca ādīnavañca 
nissaraṇañca yathābhūtaṃ appajānato_
____

____
And so in relation to views, whatever the

_yo diṭṭhisu_
____

____
attachment to views

_diṭṭhirāgo_
____

____
spiritually fettering delight in views

_diṭṭhinandi_
____

____
love of views

_diṭṭhisineho_
____

____
infatuation with views

_diṭṭhimucchā_
____

____
thirst for views

_diṭṭhipipāsā_
____

____
passion for views

_diṭṭhipariḷāho_
____

____
clinging to views

_diṭṭhiajjhosānaṃ_
____

____
craving for views that lurk within him:_

_diṭṭhitaṇhā sānuseti_
____

[quote, A.2.11]
____
this is called the bondage [to individual existence] that arises from dogmatism

_diṭṭhiyogo._
____

.Illustration
====
diṭṭhi

dogmatic views
====

____
Four floods: flood of sensuous pleasure; flood of states of individual 
existence; flood of dogmatic views; flood of uninsightfulness into reality.

_kāmogho bhavogho diṭṭhogho avijjogho._
____

.Illustration
====
diṭṭhi

dogmatic view
====

[quote, Sn.v.895]
____
For those who dispute, maintaining a dogmatic view, saying "This alone is 
true," is criticism all that they bring upon themselves? Do they not also 
receive praise?

_Ye kecime diṭṭhiṃ paribbasānā idameva saccan ti vivādayanti +
Sabbeva te nindamanvānayanti atho pasaṃsampi labhanti tattha._
____

.Illustration
====
diṭṭhiyo

dogmatic views
====

____
The religious philosophers outside this [training system] are attached to 
dogmatic views.

_ito bahiddhā pāsaṇḍā diṭṭhiyo upanissitā_
____

[quote, Thī.v.184]
____
They do not know the Buddha's teaching. They are ignorant of the Buddha's 
teaching.

_na te dhammaṃ vijānanti na te dhammassa kovidā._
____

=== Illustrations: diṭṭhi, dogmatism

.Illustration
====
diṭṭhiṃ

dogmatism
====

• How indeed could someone motivated by desire, established in [the pursuit 
of] personal inclination, transcend his own dogmatism? +
_Sakaṃ hi diṭṭhiṃ kathamaccayeyya chandānunīto ruciyā niviṭṭho_

• Having come to his own conclusions, then, just as he sees things, so would 
he speak. +
_Sayaṃ samattāni pakubbamāno yathā hi jāneyya tathā vadeyya_ (Sn.v.781).

.Illustration
====
diṭṭhiṃ

dogmatism
====

The ignorant Everyman (_assutavā puthujjano_) does not discern

____
dogmatism

_diṭṭhiṃ nappajānāti_
____

____
the origin of dogmatism

_diṭṭhisamudayaṃ nappajānāti_
____

____
the ending of dogmatism

_diṭṭhinirodhaṃ nappajānāti_
____

____
the practice leading to the ending of dogmatism

_diṭṭhinirodhagāminiṃ paṭipadaṃ nappajānāti_
____

____
For him dogmatism grows

_diṭṭhi pavaḍḍhati_
____

The learned noble disciple discerns:

- dogmatism

- the origin of dogmatism

- the ending of dogmatism

- the practice leading to the ending of dogmatism

[quote, A.4.69-70]
____
For him, dogmatism ceases

_diṭṭhi nirujjhati._
____

.Illustration
====
diṭṭhi

dogmatism
====

____
Asserting that the Perfect One exists after death: this is acquiescence in 
dogmatism.

_Hoti tathāgato parammaraṇā ti kho bhikkhu diṭṭhigatametaṃ_
____

____
Asserting that the Perfect One does not exist after death: this is acquiescence 
in dogmatism,

_na hoti tathāgato parammaraṇā ti kho bhikkhu diṭṭhigatametaṃ_
____

____
Asserting that the Perfect One both exists and does not exist after death: this 
is acquiescence in dogmatism,

_hoti ca na hoti ca tathāgato parammaraṇā ti kho bhikkhu 
diṭṭhigatametaṃ_
____

[quote, A.4.68]
____
Asserting that the Perfect One neither exists nor does not exist after death: 
this is acquiescence in dogmatism.

_neva hoti na na hoti tathāgato parammaraṇā ti kho bhikkhu 
diṭṭhigatametaṃ._
____

=== Illustrations: diṭṭhigata

.Illustration
====
diṭṭhigataṃ

views
====

[quote, Sn.v.836]
____
'If you do not want such a jewel, a woman sought after by many kings, then what 
views, observances, practices, way of life, and rebirth into individual 
existence do you proclaim?'

_Etādisaṃ ce ratanaṃ na icchasi nāriṃ narindehi bahūhi patthitaṃ +
Diṭṭhigataṃ sīlavataṃ nu jīvitaṃ bhavūpapattiñca vadesi 
kīdisaṃ._
____

.Illustration
====
diṭṭhigatānaṃ

view
====

____
Of those outside [this teaching and training system], this view is highest

_Etadaggaṃ bhikkhave bāhirakānaṃ diṭṭhigatānaṃ yadidaṃ_
____

• Had I not been, it would not have been "mine." I will be not, not "mine" 
will it be +
_no c'assaṃ no ca me siyā +
na bhavissāmi na me bhavissantī ti_ (A.5.63-4).

.Illustration
====
diṭṭhigatāni

theories
====

[quote, Sn.v.834]
____
So here you come, speculating, mulling over [various] theories in your mind. 
But you are paired off with a purified man. With him you will not be able to 
proceed.

_Atha tvaṃ pavitakkamāgamā manasā diṭṭhigatāni cintayanto +
Dhonena yugaṃ samāgamā na hi tvaṃ sakkhasi sampayātaveti._
____

.Illustration
====
diṭṭhigata

wrong view [of reality]
====

[quote, Sn.v.649]
____
'Wrong view [of reality] has lurked within the ignorant for a long time. The 
ignorant indeed say one is a Brahman on account of birth.

_Dīgharattamanusayitaṃ diṭṭhigatamajānataṃ +
Ajānantā no pabruvanti jātiyā hoti brāhmaṇo._
____

COMMENT

_Diṭṭhigata_: 'wrong view [of reality].' See IGPT sv _Diṭṭhi_.

.Illustration
====
diṭṭhigatāni

dogmatic views
====

[quote, S.4.286]
____
The sixty-two dogmatic views of the _Brahmajāla Sutta_

_dvāsaṭṭhidiṭṭhigatāni brahmajāle._
____

.Illustration
====
diṭṭhigatāni

dogmatic views
====

[quote, Th.v.933]
____
Pursuing dogmatic views they think 'This [view] is best. [All else is wrong].'

_Diṭṭhigatāni anventā idaṃ seyyo ti maññare._
____

.Illustration
====
diṭṭhigataṃ

dogmatic view
====

[quote, M.1.257]
____
Dogmatically grasping and stubbornly adhering to that same odious dogmatic view.

_tadeva pāpakaṃ diṭṭhigataṃ thāmasā parāmassa abhinivissa._
____

.Illustration
====
diṭṭhigataṃ

dogmatic view
====

[quote, D.2.316-7]
____
Once, this odious dogmatic view had arisen in Prince Pāyāsi: 'There is not a 
world beyond. There are no spontaneously born beings. There is no fruit and 
result of good and bad deeds.'

_Tena kho pana samayena pāyāsissa rājaññassa evarūpaṃ pāpakaṃ 
diṭṭhigataṃ uppannaṃ hoti iti pi natthi paro loko natthi sattā 
opapātikā natthi sukaṭadukkaṭānaṃ kammānaṃ phalaṃ vipāko ti._
____

.Illustration
====
diṭṭhigataṃ

acquiescence in dogmatism
====

____
It is this [absolute] Selfhood of mine that speaks and experiences and feels 
here and there the karmic consequences of meritorious and demeritorious deeds; 
and this [absolute] Selfhood of mine is everlasting, enduring, eternal, of an 
unchangeable nature, and will endure like unto eternity itself.

_Yo me ayaṃ attā tatra tatra kalyāṇapāpakānaṃ kammānaṃ vipākaṃ 
paṭisaṃvedeti. So kho pana me ayaṃ attā nicco dhuvo sassato 
avipariṇāmadhammo sassatisamaṃ tatheva ṭhassatī ti._
____

____
This is called

_idaṃ vuccati bhikkhave_
____

____
acquiescence in dogmatism

_diṭṭhigataṃ_
____

____
the thicket of dogmatism,

_diṭṭhigahanaṃ_
____

____
the wilderness of dogmatism,

_diṭṭhikantāro_
____

____
the writhing of dogmatism,

_diṭṭhivisūkaṃ_
____

____
the spiritual unsteadiness of dogmatism,

_diṭṭhivipphanditaṃ_
____

[quote, M.1.8]
____
the bond of dogmatism

_diṭṭhisaṃyojanaṃ._
____

.Illustration
====
diṭṭhigata

acquiescence in dogmatism
====

____
Asserting that the Perfect One exists after death: this is acquiescence in 
dogmatism.

_Hoti tathāgato parammaraṇā ti kho bhikkhu diṭṭhigatametaṃ_
____

____
Asserting that the Perfect One does not exist after death: this is acquiescence 
in dogmatism,

_na hoti tathāgato parammaraṇā ti kho bhikkhu diṭṭhigatametaṃ_
____

____
Asserting that the Perfect One both exists and does not exist after death: this 
is acquiescence in dogmatism,

_hoti ca na hoti ca tathāgato parammaraṇā ti kho bhikkhu 
diṭṭhigatametaṃ_
____

[quote, A.4.69-70]
____
Asserting that the Perfect One neither exists nor does not exist after death: 
this is acquiescence in dogmatism.

_neva hoti na na hoti tathāgato parammaraṇā ti kho bhikkhu 
diṭṭhigatametaṃ._
____

.Illustration
====
diṭṭhigata

acquiescence in wrong view [of reality]
====

[quote, S.1.135]
____
But why do you assume 'a being'? That is just your acquiescence in wrong view 
&#8203;[of reality], Māra. This is nothing but a heap of originated phenomena. Here 
no being is found.

_Kinnu satto ti paccesi māradiṭṭhigatannu te +
Suddhasaṅkhārapuñjoyaṃ nayidha sattūpalabbhati._
____

.Illustration
====
diṭṭhigatehi

acquiescing in wrong views [of reality]
====

____
Through acquiescing in two wrong views [of reality], some devas and men hold 
back, and some overreach.

_Dvīhi bhikkhave diṭṭhigatehi pariyuṭṭhitā devamanussā oliyantī eke 
atidhāvanti eke._
____

• How do some hold back? +
_Kathañca bhikkhave oliyanti eke?_

• Devas and men find enjoyment, pleasure, and satisfaction in individual 
existence. +
_bhavārāmā bhikkhave devamanussā bhavaratā bhavasammuditā._

• When the teaching is taught to them to put an end to individual existence, 
their minds do not become energised, serene, settled, and intent upon it. +
_tesaṃ bhavanirodhāya dhamme desiyamāne na cittaṃ pakkhandati na 
pasīdati na santiṭṭhati nādhimuccati. Evaṃ kho bhikkhave olīyanti eko._

• How do some overreach? +
Kathañca bhikkhave atidhāvanti eke?

• Some people are revolted, appalled, and disgusted by individual existence. +
_bhaveneva kho paneke aṭṭiyamānā harāyamāsā jigucchamānā_

• They long for the cessation of individual existence +
_vibhavaṃ abhinandanti_

• saying that 'When that [absolute] Selfhood is annihilated, destroyed, and 
does not exist with the demise of the body at death, this is peaceful, this is 
sublime, this is reality. +
_yato kira bho ayaṃ attaṃ kāyassa bhedā parammaraṇā ucchijjati 
vinassati na hoti parammaraṇā etaṃ santaṃ etaṃ paṇītaṃ etaṃ 
yathāvantī_ (It.44).

.Illustration
====
micchādiṭṭhigatā

acquiesce in wrong view [of reality]
====

[quote, A.2.52]
____
Perceiving the unlovely to be lovely, beings who acquiesce in wrong view [of 
reality], their minds troubled, their perception deranged.

_asubhe subhasaññino +
Micchādiṭṭhigatā sattā khittacittā visaññino._
____

