== Domanassa

=== Renderings

- _domanassa_: psychological pain

- _domanassa_: dejection

=== Introduction

==== Fathoming domanassa

The puzzling nature of _domanassa_ is apparent in Bodhi's renderings:

- grief, MLDB (1995)

- displeasure, CDB (2000)

- dejection, NDB (2012)

==== Domanassa in the five faculties of sense impression

One meaning of _domanassa_ is found in the five faculties of sense impression, 
which concern the pleasantness and unpleasantness of sense impression and 
moods, where we call _domanassa_ 'psychological pain.' The five faculties of 
sense impression are:

____
the faculty of physical pleasure

_sukhindriyaṃ_
____

____
the faculty of physical pain

_dukkhindriyaṃ_
____

____
the faculty of psychological pleasure

_somanassindriyaṃ_
____

____
the faculty of psychological pain

_domanassindriyaṃ_
____

[quote, S.5.211]
____
the faculty of physical-plus-psychological neutral experience, namely, whatever 
sense impression, either physical or psychological, that is neither pleasing 
nor displeasing

_upekkhindriyaṃ yaṃ kho bhikkhave kāyikaṃ vā cetasikaṃ vā neva 
sātaṃ nāsātaṃ vedayitaṃ._
____

Psychological pain apparently stems from thought, because it ceases in second 
jhāna, when thought ceases (_vitakkavicārānaṃ vūpasamā_, S.5.214). 
Psychological pleasure (_somanassa_) is obviously unrelated to thought, because 
it is not abandoned till fourth jhāna (S.5.215).

==== Dukkhadomanassa: psychological pain

A common pairing for _domanassa_ is with _dukkha_ in the phrase 
_dukkhadomanassa_ which means 'physical and psychological pain.' It may seem 
curious that attachment would cause not only psychological but also physical 
pain:

- Some person is by nature full of attachment (_pakatiyāpi tibbarāgajātiko 
hoti_); he experiences the physical and psychological pain that are born of 
attachment (_rāgajaṃ dukkhaṃ domanassaṃ paṭisaṃvedeti_) (A.2.149).

But this is well documented in the scriptures, particularly with reference to 
_taṇhā_:

____
Craving that leads to renewed states of individual existence, accompanied by 
spiritually fettering delight and attachment, taking delight in this and that, 
grows.

_Taṇhā cassa ponobhavikā nandirāgasahagatā tatra tatrābhinandinī sā 
cassa pavaḍḍhati._
____

____
... One's physical and psychological sufferings, torments, and anguishes 
increase.

_tassa kāyikāpi darathā pavaḍḍhanti cetasikāpi darathā pavaḍḍhanti 
kayikāpi santāpā pavaḍḍhanti cetasikāpi santāpā pavaḍḍhanti 
kāyikāpi pariḷāhā pavaḍḍhanti cetasikāpi pariḷāhā 
pavaḍḍhanti_
____

[quote, M.3.287]
____
... One experiences physical and psychological unpleasantness

_so kāyadukkhampi cetodukkhampi paṭisaṃvedeti._
____

==== Dejection

_Domanassa_, as a mood, means dejection. It occurs for example in the phrase 
_abhijjhādomanassā_ greed and dejection. Dejection means 'lowness of spirits 
or downheartedness.'

=== Illustrations

.Illustration
====
domanassa

faculty of psychological pain
====

[quote, S.5.213-4]
____
And where does the arisen faculty of psychological pain cease without 
remainder? With the subsiding of thinking and pondering, and [the development 
of] internal serenity and concentration, being without thinking and pondering, 
and being filled with rapture and physical pleasure born of inward 
collectedness, a bhikkhu enters and abides in second jhāna. And it is here 
that the arisen faculty of psychological pain ceases without remainder.

_Kattha cuppannaṃ domanassindriyaṃ aparisesaṃ nirujjhati: idha bhikkhave 
bhikkhu vitakkavicārānaṃ vūpasamā ajjhattaṃ sampasādanaṃ cetaso 
ekodibhāvaṃ avitakkaṃ avicāraṃ samādhijaṃ pītisukhaṃ 
dutiyajjhānaṃ upasampajja viharati. Ettha cuppannaṃ domanassindriyaṃ 
aparisesaṃ nirujjhati._
____

.Illustration
====
domanassa

psychological pain
====

____
-- Would that man, being struck with three hundred spears, experience physical 
and psychological pain (_dukkhaṃ domanassaṃ_) on that account?

_api nu so puriso divasaṃ tīhi sattisatehi haññamāno tatonidānaṃ 
dukkhaṃ domanassaṃ paṭisaṃvedayethā'ti_
____

[quote, S.2.100]
____
-- Even if he were struck with one spear he would experience physical and 
psychological pain on that account, not to speak of three hundred spears

_Ekissāpi bhante sattiyā haññamāno tatonidānaṃ dukkhaṃ domanassaṃ 
paṭisaṃvedayetha. Ko pana vādo tīhi sattisatehi haññamāno'ti._
____

.Illustration
====
domanassa

psychological pain
====

Some person is by nature full of attachment (_pakatiyāpi tibbarāgajātiko 
hoti_); he experiences the physical and psychological pain that are born of 
attachment (_rāgajaṃ dukkhaṃ domanassaṃ paṭisaṃvedeti_) (A.2.149).

.Illustration
====
domanassa

psychological pain
====

____
What is physical pain (_dukkhaṃ_)? It is physical pain, physical 
unpleasantness, unpleasant and displeasing sense impression born of bodily 
sensation

_yaṃ kho āvuso kāyikaṃ dukkhaṃ kāyikaṃ asātaṃ kāyasamphassajaṃ 
dukkhaṃ asātaṃ vedayitaṃ idaṃ vuccatāvuso dukkhaṃ._
____

[quote, D.2.307]
____
What is psychological pain (_domanassaṃ_)? It is psychological pain, 
psychological unpleasantness, unpleasant and displeasing sense impression born 
of mental sensation. This is called psychological pain

_yaṃ kho āvuso cetasikaṃ dukkhaṃ cetasikaṃ asātaṃ 
manosamphassajaṃ dukkhaṃ asātaṃ vedayitaṃ idaṃ vuccatāvuso 
domanassaṃ._
____

.Illustration
====
domanassa

psychological pain
====

A bhikkhu might approach families with the thought: 'May they give to me, not 
hold back.' When a bhikkhu approaches families with such a thought.

[quote, S.2.200]
____
If they do not give, he thereby becomes resentful. On that account he 
experiences physical and psychological pain.

_na denti tena bhikkhu sandīyati. So tatonidānaṃ dukkhaṃ domanassaṃ 
paṭisaṃvedayati._
____

.Illustration
====
domanassa

psychological pain
====

[quote, M.1.303]
____
With the abandonment of physical pleasure and pain, and following the vanishing 
of psychological pleasure and pain, a bhikkhu enters and abides in fourth 
jhāna, which is free of pleasure and pain, and [is imbued with] purified 
detached awareness and mindfulness

_bhikkhu sukhassa ca pahānā dukkhassa ca pahānā pubbeva 
somanassadomanassānaṃ atthaṅgamā adukkhaṃ asukhaṃ 
upekkhāsatipārisuddhiṃ catutthaṃ jhānaṃ upasampajja viharati._
____

.Illustration
====
domanassa

psychological pain
====

[quote, S.5.142]
____
This is the one-destination path for the purification of beings, for the 
overcoming of grief and lamentation, for the vanishing of physical and 
psychological pain

_ekāyano ayaṃ bhikkhave maggo sattānaṃ visuddhiyā sokapariddavānaṃ 
samatikkamāya dukkhadomanassānaṃ atthaṅgamāya._
____

.Illustration
====
domanassa

psychological pain
====

[quote, M.1.303]
____
A bhikkhu thinks 'When will I attain that supreme state of deliverance which 
the Noble Ones have attained? In arousing desire for supreme deliverance [from 
perceptually obscuring states], psychological pain arises due to desire.

_kudassu nāmāhaṃ tadāyatanaṃ upasampajja viharissāmi yadariyā etarahi 
āyatanaṃ upasampajja viharantī ti. Iti anuttaresu vimokkhesu pihaṃ 
upaṭṭhāpayato uppajjati pihappaccayā domanassaṃ._
____

.Illustration
====
domanassa

dejection
====

____
One who is attached, overpowered, and overcome by attachment, is intent upon 
his own harm, upon the harm of others, upon the harm of both, and so 
experiences psychological pain and dejection.

_Ratto kho āvuso rāgena abhibhūto pariyādinnacitto attavyābādhāya pi 
ceteti paravyābādhāya pi ceteti. Ubhayavyābādhāya pi ceteti. Cetasikampi 
dukkhaṃ domanassaṃ paṭisaṃvedeti._
____

[quote, A.1.156]
____
But if attachment be abandoned he is not intent upon his own harm, upon the 
harm of others, upon the harm of both, and thus does not experience 
psychological pain and dejection.

_Rāge pahīṇe nevattavyābādhāya pi ceteti na paravyābādhāya pi tetti. 
Na ubhayavyābādhāya pi ceteti. Na cetasikaṃ dukkhaṃ domanassaṃ 
paṭisaṃvedeti._
____

.Illustration
====
domanassa

dejection
====

[quote, S.4.178]
____
In seeing a visible object via the visual sense, do not grasp its aspects and 
features. Since by abiding with the faculty of sight unrestrained [from 
attraction and repulsion, through mindfulness], greed, dejection, and 
unvirtuous, spiritually unwholesome factors would pursue you.

_Cakkhunā rūpaṃ disvā mā nimittaggāhino ahuvattha mānuvyañjanaggāhino 
yatvādhikaraṇamenaṃ cakkhundriyaṃ asaṃvutaṃ viharantaṃ 
abhijjhādomanassā pāpakā akusalā dhammā anvāssaveyyuṃ._
____

.Illustration
====
domanassa

dejection
====

____
When we hear that the Blessed One will set out from amongst the Kosalan people 
on tour in the Mallan country, on that occasion there arises in us 
dissatisfaction and dejection at the thought: 'The Blessed One will be far away 
from us.'

_hoti no tasmiṃ samaye anattamanatā hoti domanassaṃ. Dūre no bhagavā 
bhavissatī ti._
____

[quote, S.5.349]
____
When we hear that the Blessed One will set out from among the Magadhans on tour 
in the Kāsian country, on that occasion there arises in us satisfaction and 
joy at the thought: 'The Blessed One will be near to us.'

_hoti no tasmiṃ samaye attamanatā hoti somanassaṃ. Āsanne no bhagavā 
bhavissatī ti._
____

.Illustration
====
domanassa

dejection
====

They received a poor meal.

[quote, Vin.2.77-8]
____
Out of dejection, they did not eat as much as expected.

_te teneva domanassena na cittarūpaṃ bhuñjiṃsu._
____

.Illustration
====
domanassa

dejection
====

[quote, S.5.182]
____
A bhikkhu abides contemplating the nature of the body, vigorously, fully 
consciously, and mindfully, having eliminated greed and dejection in regard to 
the world [of phenomena].

_bhikkhu kāye kāyānupassī viharati ātāpī sampajāno satimā vineyya loke 
abhijjhādomanassaṃ._
____

