== Dve Ante; Majjhimā Paṭipadā; Majjhena

=== Renderings

- _anta_: unenlightening practice

- _majjhimā paṭipadā_: enlightening practice

- _anta_: unenlightening doctrine

- _majjha_: enlightening doctrine

- _anta_: doctrinal principle

_• ubho ante_: origin and destiny

- _ubho ante_: in either world (i.e. this world or the world beyond)

- _antaggāhika diṭṭhi_: unenlightening doctrine

=== Introductions

==== Ordinary meanings of anta

_Anta_ ordinarily means the end of something:

[quote, Vin.2.136]
____
The end of a waistband

_Kāyabandhanassa anto._
____

[quote, Thī.v.447]
____
I have [now] put an end to all that [demerit].

_Tassapi anto kato mayā ti._
____

[quote, S.1.32]
____
Then in the end one abandons the body along with one's possessions

_Atha antena jahati sarīraṃ sapariggahaṃ._
____

==== Ordinary meanings of majjhe

_Majjhe_ ordinarily means 'what lies in between' e.g. 'side,' 'middle,' or 
'present':

[quote, S.2.184-5]
____
A stick thrown into the air falls now on its bottom, now on its side, now on 
its top.

_daṇḍo upari vehāsaṃ khitto sakimpi mūlena nipatati sakimpi majjhena 
nipatati sakimpi aggena nipatati...._
____

[quote, D.2.160]
____
Having carried the Blessed One's body through the middle of the city

_bhagavato sarīraṃ... majjhena majjhaṃ nagarassa haritvā._
____

[quote, Dh.v.348]
____
Abandon the past. Abandon the future. Abandon the present.

_Muñca pure muñca pacchato majjhe muñca._
____

==== Ordinary meanings of majjhima

_Majjhima_ ordinarily means 'middle' or 'medium':

[quote, D.3.215]
____
Three planes of existence: the low plane of existence, the middle plane of 
existence, the high plane of existence

_tisso dhātuyo: hīnadhātu majjhimadhātu paṇītadhātu._
____

[quote, Vin.3.3-4]
____
the first watch... middle watch... last watch of the night;

_rattiyā paṭhame yāme... majjhime yāme... pacchime yāme._
____

[quote, Vin.4.243]
____
Three sizes of bowls: large, medium, small

_Tayo pattassa vaṇṇā ukkaṭṭho patto majjhimo patto omako patto._
____

[quote, D.1.243]
____
Do you know whether she is tall, short, or medium height

_dīghā vā rassā vā majjhimā vā._
____

==== Fathoming the special meanings

The meaning of _dve anta_ cannot be fathomed from the ordinary meaning of 
_anta_, and likewise the special meanings of _majjhe_ and _majjhima_ cannot be 
fathomed from their ordinary meanings. Failing to appreciate this has led to 
the neologisms, 'the two extremes' (_dve antā_) and 'the Middle Way' 
(_majjhimā paṭipadā_).

==== Anta: doctrinal principle

_Anta_ can mean 'doctrinal principle', which the dictionaries call 'opposing 
principle' (DOP), and 'constituent principle' (PED).

____
Three doctrinal principles

_Tayo antā_
____

1. personal identity as a doctrinal principle
+
****
_sakkāyo anto_
****

2. the origin of personal identity as a doctrinal principle
+
****
_sakkāyasamudayo anto_
****

3. the ending of personal identity as a doctrinal principle
+
****
_sakkāyanirodho anto_ (D.3.216).
****

==== Anta and majjhimā paṭipadā: Rāsiya Sutta

That _anta_ and _majjhimā paṭipadā_ mean unenlightening practice and 
enlightening practice is demonstrated in the _Rāsiya Sutta_ (S.4.331) which 
says:

____
There are these two unenlightening practices which should not be undertaken by 
one who has gone forth [into the ascetic life]:

_Dve'me bhikkhave antā pabbajitena na sevitabbā:_
____

____
The pursuit of sensuous pleasures, which is low, vulgar, the way of the common 
man, ignoble, and unconducive to spiritual well-being

_yo cāyaṃ kāmesu kāmasukhallikānuyogo hīno gammo pothujjaniko anariyo 
anatthasaṃhito_
____

____
The pursuit of self-mortification, which is painful, ignoble, and unconducive 
to spiritual well-being

_yo cāyaṃ attakilamathānuyogo dukkho anariyo anatthasaṃhito._
____

____
Not veering towards these two unenlightening practices, the Perfect One has 
awakened to an enlightening practice, which gives rise to vision, which gives 
rise to knowledge, which leads to inward peace, to transcendent insight, to 
enlightenment, and to the Untroubled.

_Ete te bhikkhave ubho ante anupagamma majjhimā paṭipadā tathāgatena 
abhisambuddhā cakkhukaraṇī ñāṇakaraṇi upasamāya abhiññāya 
sambodhāya nibbānaya saṃvattati._
____

____
And what is that enlightening practice awakened to by the Perfect One, which 
gives rise to vision... leads to the Untroubled?

_Katamā ca sā gāmaṇi majjhimā paṭipadā tathāgatena abhisambuddhā 
cakkhukaraṇī ñāṇakaraṇī upasamāya abhiññāya sambodhāya 
nibbānāya saṃvattati_
____

[quote, Vin.1.10; S.4.331]
____
It is this noble eightfold path, namely: right perception [of reality]... right 
inward collectedness

_Ayameva ariyo aṭṭhaṅgiko maggo seyyathīdaṃ sammādiṭṭhi 
sammāsaṅkappo sammāvācā sammākammanto sammāājivo sammāvāyāmo 
sammāsati sammāsamādhi._
____

Here:

1. _dve ante_ are unconducive to spiritual well-being (_anatthasaṃhito_).

2. _majjhimā paṭipadā_ 'gives rise to vision, which gives rise to 
knowledge, which leads to inward peace, to transcendent insight, to 
enlightenment, and to the Untroubled.'

Therefore _ubho ante_ means 'two unenlightening practices,' and _majjhimā 
paṭipadā_ means 'enlightening practice.'

==== Anta and majjhimā paṭipadā: Araṇavibhaṅga Sutta

That _anta_ and _majjhimā paṭipadā_ mean unenlightening practice and 
enlightening practice is demonstrated in the _Araṇavibhaṅga Sutta_ which 
says:

- The pursuit of the pleasure and happiness that is linked to sensuous pleasure 
is wrong practice (_micchāpaṭipadā_).

- Disengagement from the pursuit of such pleasure and happiness is right 
practice (_sammāpaṭipadā_).

- The pursuit of self-mortification is wrong practice (_micchāpaṭipadā_).

- Disengagement from the pursuit of self-mortification is right practice 
(_sammāpaṭipadā_).

[quote, M.3.230-1]
____
Not veering towards these two unenlightening practices, the Perfect One has 
awakened to an enlightening practice, which gives rise to vision, which gives 
rise to knowledge, which leads to inward peace, to transcendent insight, to 
enlightenment, and to the Untroubled.

_Ete te ubho ante anupagamma majjhimā paṭipadā tathāgatena abhisambuddhā 
cakkhukaraṇī ñāṇakaraṇi upasamāya abhiññāya sambodhāya nibbānaya 
saṃvattati.._
____

Here:

1. _ubho ante_ means the two forms of _micchāpaṭipadā_

2. _majjhimā paṭipadā_ corresponds to the two forms of _sammāpaṭipadā_, 
and is a practice 'which gives rise to vision, which gives rise to knowledge, 
which leads to inward peace, to transcendent insight, to enlightenment, and to 
the Untroubled.'

Therefore _ubho ante_ can again be called 'two unenlightening practices,' and 
_majjhimā paṭipadā_ 'enlightening practice.'

==== Sassatadiṭṭhi and ucchedadiṭṭhi

The eternalist view (_sassatadiṭṭhi_, S.3.99) is the view that 'I am or 
will be everlasting' (_bhavissāmi nicco_). The annihilationist view 
(_ucchedadiṭṭhi_) is the view 'I will be not' (_na bhavissāmi_, S.3.99). 
These views are sometimes called _sassataṃ_ and _ucchedaṃ_, as if 
_diṭṭhi_ was redundant, for example in this quote:

____
Such a belief amounts to eternalism.

_iti vadaṃ sassataṃ etaṃ pareti_
____

[quote, S.2.19-20]
____
Such a belief amounts to annihilationism

_iti vadaṃ ucchedaṃ etaṃ pareti._
____

==== Sassataṃ and ucchedaṃ: 'two ante'

In the _Acelakassapa Sutta sassataṃ_ and _ucchedaṃ_ are called 'two _ante'_:

____
Not veering towards these two _ante_, the Perfect One explains a teaching via 
_majjhena_.

_Ete te kassapa ubho ante anupagamma majjhena tathāgato dhammaṃ deseti_
____

____
(Namely, the doctrine of dependent origination, _paṭiccasamuppāda_)_

_Avijjāpaccayā saṅkhārā..._
____

[quote, S.2.19-20]
____
Such is the ending of this whole mass of suffering._

_Evametassa kevalassa dukkhakkhandhassa nirodho hotī ti._
____

Thus _ubho ante_ is an abbreviation for _sassatadiṭṭhi_ and 
_ucchedadiṭṭhi_, which we call 'unenlightening doctrines.'

_Majjhena_ is the counterpart of _anta_. It leads to 'the ending of this whole 
mass of suffering.' We call it 'enlightening doctrine.'

==== Ubho ante: origin and destiny

The _Salla Sutta_ says:

[quote, Sn.v.582]
____
He whose path you do not know, whether arriving or departing, knowing neither 
his origin nor destiny, you lament for him uselessly.

_Yassa maggaṃ na jānāsi āgatassa gatassa vā +
Ubho ante asampassaṃ niratthaṃ paridevasi._
____

We render _ubho ante_ here according to the context, by which it is linked to 
_maggaṃ... āgatassa gatassa_. The commentary likewise says: _Yassa 
mātukucchiṃ āgatassa āgatamaggaṃ vā ito cavitvā aññattha gatassa 
gatamaggaṃ vā na jānāsi, tassa ime ubho ante asampassaṃ niratthaṃ 
paridevasi._

==== Ubho ante: in either world

This verse links _ubho ante_ to _idha vā huraṃ vā_:

[quote, Sn.v.801]
____
One with no aspiration for any state of individual existence in either world, 
this world or the world beyond, has no attachment to dogmatic religious views.

_Yassūbhayante paṇidhīdha natthi bhavābhavāya idha vā huraṃ vā +
Nivesanā tassa na santi keci dhammesu niccheyya samuggahītaṃ._
____

This allows us to parenthesise accordingly:

[quote, Sn.v.778]
____
You should eliminate desire for both worlds, [this world and the world beyond].

_Ubhosu antesu vineyya chandaṃ._
____

This parenthesis hopefully solves a puzzle with a long history: see Norman's 
note on this verse.

=== Illustrations

.Illustration
====
antā

doctrinal principles
====

____
There are these four doctrinal principles. Which four?

_Cattāro me bhikkhave antā. Katame cattāro?_
____

____
Personal identity as a doctrinal principle

_sakkāyanto _
____

____
The origin of personal identity as a doctrinal principle

_sakkāyasamudayanto _
____

____
The ending of personal identity as a doctrinal principle

_sakkāyanirodhanto _
____

____
The practice leading to the ending of personal identity as a doctrinal 
principle._

_sakkāyanirodhagāminī paṭipadanto._
____

____
What is personal identity as a doctrinal principle? The five grasped 
aggregates, one should reply

_Katamo ca bhikkhave sakkāyanto? Pañcupādānakkhandhātissa vacanīyaṃ_
____

____
What is the origin of personal identity as a doctrinal principle? It is this 
craving that leads to renewed states of individual existence...

_Katamo ca bhikkhave sakkāyasamudayanto? Yāyaṃ taṇhā ponobhavikā..._
____

____
What is the ending of personal identity as a doctrinal principle? It is the 
complete passing away and ending of this same craving...

_Katamo ca bhikkhave sakkāyanirodhanto? Yo tassā yeva taṇhāya 
asesavirāganirodho..._
____

[quote, S.3.157-8]
____
What is the practice leading to the ending of personal identity as a doctrinal 
principle? It is this noble eightfold path, namely: right perception [of 
reality]... right inward collectedness

_Katamo ca bhikkhave sakkāyanirodhagāminī paṭipadanto? Ayameva ariyo 
aṭṭhaṅgiko maggo seyyathīdaṃ sammādiṭṭhi... sammāsamādhi._
____

.Illustration
====
ante

doctrinal principles: ubhante (=ubho ante)
====

The _Majjhe Sutta_ (A.3.399-402) gives six explanations of the following verse:

• 'Knowing both doctrinal principles, the wise person does not cleave to the 
middle. I call him a Great Man. In this world he has overcome the seamstress.' +
☸ _So ubhante_ (_=ubho ante_) _viditvāna majjhe mantā na limpati +
Taṃ brūmi mahāpuriso ti sodha sibbanimaccagā ti_

____
What is the first doctrinal principle?

_Katamo nu kho āvuso eko anto_
____

____
What is the second doctrinal principle?

_katamo dutiyo anto_
____

____
What is in the middle?

_kiṃ majjhe_
____

____
And what is the seamstress?

_kā sibbanī ti_
____

The six answers are as follows:

*Answer 1*

____
Sensation is the first doctrinal principle.

_phasso kho āvuso eko anto_
____

____
The origination of sensation is the second doctrinal principle.

_phassasamudayo dutiyo anto_
____

____
The ending of sensation is in the middle.

_phassanirodho majjhe_
____

[quote, A.3.400]
____
Craving is the seamstress. For craving stitches him to this or that state of 
individual existence and rebirth.

_taṇhā sibbanī. Taṇhā hi naṃ sibbati tassa tasseva bhavassa 
abhinibbattiyā._
____

*Answer 2*

____
The past is the first doctrinal principle.

_atītaṃ kho āvuso eko anto_
____

____
The future is the second doctrinal principle

_anāgataṃ dutiyo anto_
____

____
The present is in the middle

_paccuppannaṃ majjhe_
____

____
Craving is the seamstress.

_taṇhā sibbanī._
____

*Answer 3*

____
Pleasant sense impression is the first doctrinal principle.

_sukhā kho āvuso vedanā eko anto_
____

____
Unpleasant sense impression is the second doctrinal principle.

_dukkhā vedanā dutiyo anto_
____

____
Neutral sense impression is in the middle

_adukkhamasukhā vedanā majjhe_
____

____
Craving is the seamstress.

_taṇhā sibbanī._
____

*Answer 4*

____
Denomination is the first doctrinal principle

_nāmaṃ kho āvuso eko anto_
____

____
Bodily form is the second doctrinal principle

_rūpaṃ dutiyo anto_
____

____
The stream of sense consciousness is in the middle

_viññāṇaṃ majjhe_
____

____
Craving is the seamstress.

_taṇhā sibbanī._
____

*Answer 5*

____
The six senses are the first doctrinal principle

_cha kho āvuso ajjhattikāni āyatanāni eko anto_
____

____
The six sense objects are the second doctrinal principle

_cha bāhirāni āyatanāni dutiyo anto_
____

____
Advertence is in the middle

_viññāṇaṃ majjhe_
____

____
Craving is the seamstress.

_taṇhā sibbanī._
____

*Answer 6*

____
Personal identity is the first doctrinal principle

_sakkāyo kho āvuso eko anto_
____

____
The origin of personal identity is the second doctrinal principle

_sakkāyasamudayo dutiyo anto_
____

____
The ending of personal identity is in the middle

_sakkāyanirodho majjhe_
____

____
Craving is the seamstress.

_taṇhā sibbanī_
____

*The Buddha's verdict:*

The Buddha said that:

1. Each of the bhikkhus had spoken well in turn
+
****
_Sabbesaṃ vo bhikkhave subhāsitaṃ pariyāyena_
****

2. What he originally meant by the verse was given in Answer 1
+
****
_api ca yaṃ mayā sandhāya bhāsitaṃ pārāyane mettayyapañhe... Phasso 
kho bhikkhave eko anto..._ (A.3.399-402).
****

.Illustration
====
ante

unenlightening practice; majjhimā paṭipadā, enlightening practice
====

____
The pursuit of the pleasure and happiness that is linked to sensuous pleasure 
is low, vulgar, the way of the common man, ignoble, and unconducive to 
spiritual well-being. It is a state associated with pain, distress, vexation, 
and anguish. It is wrong practice.

_yo kāmapaṭisandhisukhino somanassānuyogo hīno gammo pothujjaniko anariyo 
anatthasaṃhito sadukkho eso dhammo saupaghāto saupāyāso sapariḷāho 
micchāpaṭipadā._
____

____
Disengagement from the pursuit of such pleasure and happiness is a state not 
associated with pain, distress, vexation, and anguish. It is a right practice.

_Yo kāmapaṭisandhisukhino somanassānuyogaṃ ananuyogo hīnaṃ gammaṃ 
pothujjanikaṃ anariyaṃ anatthasaṃhitaṃ adukkho eso dhammo anupaghāto 
anupāyāso apariḷāho sammāpaṭipadā._
____

____
The pursuit of self-mortification, which is painful, ignoble, and unconducive 
to spiritual well-being, is a state associated with pain, distress, vexation, 
and anguish. It is wrong practice.

_Yo attakilamathānuyogo dukkho anariyo anatthasaṃhito sadukkho eso dhammo 
saupaghāto saupāyāso sapariḷāho micchāpaṭipadā_
____

____
Disengagement from the pursuit of self-mortification, which is painful, 
ignoble, and unconducive to spiritual well-being, is a state not associated 
with pain, distress, vexation, and anguish. It is a right practice.

_yo attakilamathānuyogaṃ ananuyogo dukkhaṃ anariyaṃ anatthasaṃhitaṃ 
adukkho eso dhammo anupaghāto anupāyāso apariḷāho sammāpaṭipadā '_
____

____
Not veering towards these two unenlightening practices, the Perfect One has 
awakened to an enlightening practice, which gives rise to vision, which gives 
rise to knowledge, which leads to inward peace, to transcendent insight, to 
enlightenment, and to the Untroubled.

_Ete te ubho ante anupagamma majjhimā paṭipadā tathāgatena abhisambuddhā 
cakkhukaraṇi ñāṇakaraṇī upasamāya abhiññāya sambodhāya 
nibbānāya saṃvattatī ti_
____

____
So it was said. And in reference to what was it said?

_iti ko panetaṃ vuttaṃ. Kiñcetaṃ paṭicca vuttaṃ:_
____

[quote, M.3.230-1]
____
It is just this noble eightfold path, namely, right perception [of reality]... 
right inward collectedness .

_ayameva ariyo aṭṭhaṅgiko maggo. Seyyathīdaṃ sammādiṭṭhi... 
sammāsamādhi._
____

.Illustration
====
anto

unenlightening doctrine; majjhena, enlightening doctrine
====

____
The view that everything exists, Kaccāna, is the first unenlightening doctrine

_sabbamatthī ti kho kaccāna ayameko anto_
____

____
The view that nothing exists is the second unenlightening doctrine

_sabbaṃ natthī ti ayaṃ dutiyo anto_
____

____
Not veering towards these two unenlightening doctrines, the Perfect One 
explains a teaching via an enlightening doctrine.

_Ete te kaccāna ubho ante anupagamma majjhena tathāgato dhammaṃ deseti._
____

[quote, S.2.17]
____
(Namely, the doctrine of dependent origination, _paṭiccasamuppāda_)_

_Avijjāpaccayā saṅkhārā... Evametassa kevalassa dukkhakkhandhassa nirodho 
hotī ti._
____

.Illustration
====
anto

unenlightening doctrine
====

____
Those who hold the training rules as the essence of religious practice, or 
observances and practices, mode of livelihood, living of the religious life, 
and performing of service as the essence of religious practice, this is the 
first unenlightening doctrine.

_Ye ca sikkhāsārā sīlabbatajīvitabrahmacariyaupaṭṭhānasārā ayameko 
anto_
____

____
Those whose doctrine is that there is no spiritual flaw in [pursuing] sensuous 
pleasures, this is the second unenlightening doctrine.

_Ye ca evaṃvādino natthi kāmesu doso ti ayaṃ dutiyo anto._
____

• These two unenlightening doctrines cause the cemeteries to grow, and the 
cemeteries cause dogmatism to grow. +
_Iccete ubho antā kaṭasivaḍḍhanā. Kaṭasiyo diṭṭhiṃ 
vaḍḍhenti._

• Through not fully understanding these two unenlightening doctrines, some 
get held up, some go too far. +
_Ete te ubho ante anabhiññāya oliyanti eke atidhāvanti eko_ (Ud.71-2).

.Illustration
====
ante

unenlightening doctrine; majjhena, enlightening doctrine
====

____
-- Master Gotama, is suffering produced by oneself?

_sayaṃ kataṃ dukkhan ti_
____

-- Not so, Kassapa.

____
-- Then, is suffering produced by another?

_parakataṃ dukkhan ti_
____

____
-- Not so, Kassapa... Kassapa, if one asserts that 'The one who acts is the 
same as the one who experiences [the karmic consequences],' then one speaks 
with reference to one existing from the beginning: 'Suffering is produced by 
oneself.'

_so karoti so paṭisaṃvediyatī ti kho kassapa ādito sato sayaṃ kataṃ 
dukkhan ti_
____

____
Such a belief amounts to eternalism._

_iti vadaṃ sassataṃ etaṃ pareti_
____

____
But if one asserts that the one who acts is one person, the one who experiences 
&#8203;[the karmic consequences] is another, then one speaks as one who is stricken by 
sense impression: 'Suffering is produced by another'

_añño karoti añño paṭisaṃvediyatī ti kho kassapa vedanāhitunnassa 
sato paraṅkataṃ dukkhan ti_
____

____
Such a belief amounts to annihilationism

_iti vadaṃ ucchedaṃ etaṃ pareti._
____

____
Not veering towards these two unenlightening doctrines, the Perfect One 
explains a teaching via an enlightening doctrine.

_Ete te kassapa ubho ante anupagamma majjhena tathāgato dhammaṃ deseti_
____

____
(Namely, the doctrine of dependent origination, _paṭiccasamuppāda_)_

_Avijjāpaccayā saṅkhārā..._
____

[quote, S.2.19-20]
____
Such is the ending of this whole mass of suffering._

_Evametassa kevalassa dukkhakkhandhassa nirodho hotī ti._
____

.Illustration
====
antaggāhikāya diṭṭhiyā

unenlightening doctrine
====

[quote, A.1.154]
____
The unvirtuous bhikkhu has a wrong view [of reality]. He is possessed of an 
unenlightening doctrine.

_pāpabhikkhu micchādiṭṭhiko hoti antaggāhikāya diṭṭhiyā 
samannāgato._
____

.Illustration
====
antaggāhikādiṭṭhi

unenlightening doctrine
====

• Wrong view [of reality], and grasping an unenlightening doctrine: this is 
errancy in basic religious understanding. +
_Micchādiṭṭhi antaggāhikādiṭṭhi ayaṃ diṭṭhivipatti ti_ 
(Vin.1.172).

