== Ekamantaṃ

=== Renderings

- _ekamantaṃ_: somewhere separately

- _ekamantaṃ_: somewhere quiet

- _ekamantaṃ_: somewhere out of the way

- _ekamantaṃ_: somewhere suitable

- _ekamantaṃ_: somewhere removed

- _ekamantaṃ_: at a distance

- _ekamantaṃ_: aside

- _ekamantaṃ_: at one end

- _ekamantaṃ_: to one side

- _ekamantaṃ... ekamantaṃ_: on the one side... to the other side

- _ekamantaṃ_: beside

- _ekamantaṃ_: at an appropriate distance

- _ekamantaṃ_: at a respectful distance

=== Introduction

==== Sitting at a respectful distance

Horner says that _ekamantaṃ nisīdi_ means 'literally sat down to one side, 
or end. In sitting down in the presence of an honoured person, care should be 
taken not to sit down in any of the six wrong ways. These are

- too far

- too near

- to windward

- on a higher seat

- too much in front

- too much behind' (BD Part 2 p.42 n.5).

Accordingly, she renders the term as 'he sat down at a respectful distance.'

==== 'Respectful distance' and 'appropriate distance'

[quote, Vin.2.216]
____
Horner's phrase 'at a respectful distance' and our preference 'at an 
appropriate distance' would seem to be justified by comparison with the 
etiquette concerning almsround. According to this, when a bhikkhu approaches a 
house for food, he should not stand too far away, he should not stand too close.

_Nātidure ṭhātabbaṃ. Nāccāsanne ṭhātabbaṃ._
____

'At an appropriate distance' would be a good way to negotiate the following 
passage:

[quote, S.1.166]
____
Going on uninterrupted house-to-house almsround in Rājagaha, the Blessed One 
approached the residence of the brahman Aggika Bhāradvāja and stood at an 
appropriate distance.

_Rājagahe sapadānaṃ piṇḍāya caramāno yena aggikabhāradvājassa 
brāhmaṇassa nivesanaṃ tenupasaṅkami. Upasaṅkamitvā ekamantaṃ 
aṭṭhāsi.._
____

==== Other meanings

See Illustrations.

==== DOP renderings

DOP's renderings are:

1. to one side, at a respectful distance

2. on one side, aside; out of the way; a little apart

3. apart, at a distance; in private, on one's own; in a solitary place

=== Illustrations

.Illustration
====
somewhere separately
====

[quote, Vin.4.228]
____
Then that man, in love with that bhikkhunī, appointing a bedroom for those 
bhikkhunīs, appointed a bedroom somewhere separately for that bhikkhunī.

_Atha kho so puriso tāsaṃ bhikkhunīnaṃ seyyaṃ paññāpento tassā 
bhikkhuniyā seyyaṃ ekamantaṃ paññāpesi._
____

.Illustration
====
somewhere quiet
====

[quote, Th.v.317]
____
Being mindful and fully conscious, I sat down somewhere quiet.

_Satimā sampajānohaṃ ekamantaṃ upāvisiṃ._
____

.Illustration
====
somewhere quiet
====

[quote, Thī.v.118]
____
Undertake the Buddha's training system. Having done so one does not [later] 
regret it. Wash your feet quickly and sit down somewhere quiet.

_Karotha buddhasāsanaṃ yaṃ katvā nānutappati +
Khippaṃ pādāni dhovitvā ekamante nisīdatha._
____

.Illustration
====
somewhere quiet
====

[quote, Th.v.560]
____
Out of tender concern the Teacher gave me a [clean] foot-cloth, [saying]: 
'Properly concentrate on this pure thing somewhere quiet.'

_Etaṃ suddhaṃ adhiṭṭhehi ekamantaṃ svadhiṭṭhitaṃ._
____

.Illustration
====
somewhere out of the way
====

Wanting to spy on someone:

[quote, Vin.3.22]
____
they hid themselves somewhere out of the way.

_ekamantaṃ nilīyiṃsu._
____

.Illustration
====
out of the way
====

[quote, A.3.75]
____
When they saw him, they put down their bows and sent their dogs out of the way.

_Disvāna sajjāni dhanūni nikkhipitvā kukkurasaṅghaṃ ekamantaṃ 
uyyojetvā._
____

.Illustration
====
somewhere out of the way
====

[quote, Vin.2.141]
____
Now at that time bhikkhus urinated here and there in the monastery; the 
monastery was fouled. They told this matter to the Blessed One. He said: "I 
allow you bhikkhus, to urinate somewhere out of the way.

_Tena kho pana samayena bhikkhū ārāme tahaṃ tahaṃ passāvaṃ karonti. 
Ārāmo dussati. Bhagavato etamatthaṃ ārocesuṃ. Anujānāmi bhikkhave 
ekamantaṃ passāvaṃ kātunti._
____

.Illustration
====
somewhere suitable
====

[quote, Vin.2.154]
____
Now at that time bhikkhus made fireplaces here and there in the monastic 
compound; the monastic compound became dirty. They told this matter to the 
Blessed One. He said: "I allow you to make a fire-hall somewhere suitable."

_Tena kho pana samayena bhikkhū parivene tahaṃ tahaṃ aggiṭṭhānaṃ 
karonti. Parivenaṃ uklāpaṃ hoti. Bhagavato etamatthaṃ ārocesuṃ. 
Anujānāmi bhikkhave ekamantaṃ aggisālaṃ kātunti._
____

.Illustration
====
somewhere suitable
====

&#8203;[Cūḷapanthaka:]

[quote, Th.v.564-5]
____
Then the Teacher sent a messenger to me to announce the mealtime. When the 
mealtime was announced, I approached [Jīvaka's residence] through the air. 
Having venerated the Teacher's feet I sat down somewhere suitable. Seeing that 
I was seated the Teacher received [the food offering].

_Vanditvā satthuno pāde ekamantaṃ nisīdahaṃ +
Nisinnaṃ maṃ viditvāna atha satthā paṭiggahī._
____

.Illustration
====
somewhere removed
====

[quote, Vin.1.94]
____
I allow you, bhikkhus, having first instructed somewhere removed, to ask about 
obstacles to ordination in the midst of the assembly of bhikkhus.

_Anujānāmi bhakkhave ekamantaṃ anusāsitvā saṅghamajjhe antarāyike 
dhamme pucchituṃ._
____

.Illustration
====
at a distance
====

____
Venerable MahāMoggallāna performed a feat of psychic power such that he made 
the Mansion of Migāra's Mother shake,
quake, and tremble with his big toe. Then the resident bhikkhus, dismayed and 
terrified, stood at a distance...

_Atha kho te bhikkhū saṃviggā lomahaṭṭhajātā ekamantaṃ aṭṭhaṃsu._
____

[quote, S.5.270]
____
Then the Blessed One approached those bhikkhus and said to them: "Why are you 
standing at a distance, dismayed and terrified?"

_Atha kho bhagavā yena te bhikkhu tenupasaṅkami. Upasaṅkamitvā te bhikkhu 
etadavoca kinnu tumhe bhikkhave saṃviggā lomahaṭṭhajātā ekamantaṃ 
ṭhitāti?._
____

.Illustration
====
at a distance
====

[quote, Vin.2.140]
____
Now at that time the Blessed One was seated, explaining the teaching, 
surrounded by a large assembly. A certain bhikkhu had eaten garlic, and had sat 
down at a distance, thinking: "May the bhikkhus not be troubled [by the stench 
of garlic]." The Blessed One saw that bhikkhu sitting at a distance, and asked 
the bhikkhus: "Bhikkhus, why is this bhikkhu sitting at a distance?"_

_Tena kho pana samayena bhagavā mahatiyā parisāya parivuto dhammaṃ desento 
nisinno hoti. Aññatarena bhikkhunā lasunaṃ khāyitaṃ hoti. So mā 
bhikkhū vyābādhiyiṃsū ti ekamantaṃ nisīdi. Addasā kho bhagavā taṃ 
bhikkhuṃ ekamantaṃ nisinnaṃ. Disvāna bhikkhū āmantesi. Kinnu kho so 
bhikkhave bhikkhu ekamantaṃ nisinno ti._
____

.Illustration
====
aside
====

[quote, Vin.1.47]
____
Having received his preceptor's robe, he should lay it aside.

_cīvaraṃ paṭiggahetvā ekamantaṃ nikkhipitabbaṃ._
____

.Illustration
====
aside
====

[quote, Vin.2.218]
____
When he is cleaning the dwelling-place, having first taken out the bowl and 
robes, he should lay them aside.

_Vihāraṃ sodhentena paṭhamaṃ pattacīvaraṃ nīharitvā ekamantaṃ 
nikkhipitabbaṃ._
____

.Illustration
====
aside
====

[quote, Vin.2.192]
____
Then that man, having laid aside his sword and shield, having laid down his bow 
and quiver, approached the Blessed One.

_Atha kho so puriso asicammaṃ ekamantaṃ karitvā dhanukalāpaṃ 
nikkhipitvā yena bhagavā tenupasaṅkami._
____

.Illustration
====
aside
====

[quote, Vin.1.173]
____
Having taken that bhikkhu aside, having had him dealt with according to the 
rule...

_bhikkhu ekamantaṃ apanetvā yathādhammaṃ kārāpetvā._
____

.Illustration
====
aside
====

[quote, D.1.221]
____
Then, Kevaḍḍha, the Great Brahmā took that bhikkhu by the arm, led him 
aside and said...

_Atha kho so kevaḍḍha mahābrahmā taṃ bhikkhuṃ bāhāyaṃ gahetvā 
ekamantaṃ apanetvā taṃ bhikkhuṃ etadavoca._
____

.Illustration
====
aside
====

[quote, Vin.1.122]
____
Please will you, venerable ones, stand aside for a short time while this 
bhikkhu declares his entire purity?

_iṅgha tumhe āyasmantā muhuttaṃ ekamantaṃ hotha yāvāyaṃ bhikkhu 
pārisuddhiṃ deti'ti._
____

.Illustration
====
at one end
====

[quote, M.3.238]
____
Then the Blessed One entered the potter's workshop, prepared a spread of grass 
at one end, seated himself cross-legged, set his body erect, and established 
mindfulness within himself

_Atha kho bhagavā kumbhakārāvesanaṃ pavisitvā ekamantaṃ tiṇasanthā 
rakaṃ paññāpetvā nisīdi pallaṅkaṃ ābhujitvā ujuṃ kāyaṃ 
paṇidhāya parimukhaṃ satiṃ upaṭṭhapetvā._
____

.Illustration
====
to one side
====

[quote, D.2.180]
____
Being thus refused by the King, they withdrew to one side and considered:

_Te raññā paṭikkhittā ekamantaṃ apakkamma evaṃ samacintesuṃ._
____

.Illustration
====
on the one side... to the other side
====

[quote, A.4.170]
____
When a large heap of grain is being winnowed, the grains that are firm and 
pithy form a pile on the one side, and the wind blows the spoiled grains and 
chaff to the other side.

_Seyyathā pi bhikkhave mahato dhaññarāsissa pūyamānassa tattha yāni 
dhaññāni daḷhāni sāravannāni tāni ekamantaṃ puñjaṃ hoti yāni 
pana tāni dhaññāni dubbalāni palāpāni tāni vāto ekamantaṃ 
apakassati.._
____

.Illustration
====
beside them
====

[quote, Ud.47-8]
____
Then Suppabuddha the leper approached that large crowd. He saw the Blessed One 
sitting down, surrounded by a large assembly, explaining the teaching. Seeing 
this, he thought 'There is no snacks or food being distributed here. This is 
the ascetic Gotama explaining his teaching to the assembly. Perhaps I should 
also listen to the teaching. So he took a seat right there beside them, 
thinking: 'I, too, will listen to the teaching.'.. The Blessed One saw 
Suppabuddha the leper seated in that assembly...

_Atha kho suppabuddho kuṭṭhi yena so mahājanakāyo tenupasaṅkami. 
Addasā kho suppabuddho kuṭṭhi bhagavantaṃ mahatiyā parisāya 
parivutaṃ dhammaṃ desentaṃ nisinnaṃ. Disvānassa etadahosi na kho ettha 
kiñci khādanīyaṃ vā bhojanīyaṃ vā bhājiyati. Samaṇo ayaṃ gotamo 
parisatiṃ dhammaṃ deseti. Yannūnāhampi dhammaṃ suṇeyyanti. Tattheva 
ekamantaṃ nisīdi. Ahampi dhammaṃ sossāmī ti... Addasā kho bhagavā 
suppabuddhaṃ kuṭṭhiṃ tassaṃ parisāyaṃ nisinnaṃ...._
____

.Illustration
====
at a respectful distance
====

[quote, Vin.4.117]
____
Now at one time bhikkhus were bathing in the Tapoda Hot Springs. Then King 
Seniya Bimbisāra of Magadha, wanting to bathe his head, having gone to Tapoda, 
waited for them at a respectful distance while they were bathing.

_Tena kho pana samayena bhikkhu tapode nahāyanti. Atha kho rājā māgadho 
seniyo bimbisāro sīsaṃ nahāyissāmīti tapodaṃ gantvā yāva ayyā 
nahāyantiti ekamantaṃ patimānesi._
____

.Illustration
====
at a respectful distance
====

[quote, D.1.50]
____
Then King Ajātasattu approached the Blessed One and stood at a respectful 
distance. Standing thus, King Ajātasattu gazed at the assembly of bhikkhus 
which remained as silent as a serene lake.

_Atha kho rājā māgadho ajātasattu vedehiputto yena bhagavā 
tenupasaṅkami. Upasaṅkamitvā ekamantaṃ aṭṭhāsi. Ekamantaṃ dhito 
kho rājā māgadho ajātasattu vedehiputto tuṇhībhūtaṃ tuṇhībhūtaṃ 
bhikkhusaṅghaṃ anuviloketvā rahadamiva vippasannaṃ._
____

.Illustration
====
at a respectful distance
====

[quote, D.2.270]
____
Welcomed, Sakka entered the Indasāla Cave, venerated the Blessed One, and 
stood at a respectful distance.

_Abhivadito sakko devānamindo bhagavatā indasālaguhaṃ pavisitvā 
bhagavantaṃ abhivādetvā ekamantaṃ aṭṭhāsi._
____

.Illustration
====
at a respectful distance
====

[quote, M.2.142-3]
____
'I shall sit here in front of the ascetic Gotama.' Then the brahman Brahmāyu 
approached the Blessed One; and having exchanged greetings and words of 
cordiality he sat down at a respectful distance... Then sitting down at a 
respectful distance the brahman Brahmāyu looked for the thirty-two marks of a 
Great Man on the Blessed One's body

_idhāhaṃ samaṇassa gotamassa santike nisīdissāmīti. Atha kho brahmāyu 
brāhmaṇo yena bhagavā tenupasaṅkami. Upasaṅkamitvā bhagavatā 
saddhiṃ sammodi. Sammodanīyaṃ kathaṃ sārāṇīyaṃ vītisāretvā 
ekamantaṃ nisīdi... Ekamantaṃ nisinno kho brahmāyu brāhmaṇo bhagavato 
kāye dvattiṃsamahāpurisalakkhaṇāni sammannesi._
____

COMMENT

_santike_: in the presence of, before, with (PED).

.Illustration
====
at a respectful distance
====

[quote, D.2.102]
____
Then the Blessed One approached the Cāpāla Shrine and seated himself on the 
prepared seat. Venerable Ānanda, having paid respects, sat down at a 
respectful distance. Then the Blessed One said to Venerable Ānanda, who was 
seated thus:

_Atha kho bhagavā yena cāpālaṃ cetiyaṃ tenupasaṅkami. Upasaṅkamitvā 
paññatte āsane nisīdi. Āyasmā pi kho ānando bhagavantaṃ abhivādetvā 
ekamantaṃ nisīdi. Ekamantaṃ nisinnaṃ kho āyasmantaṃ ānandaṃ 
bhagavā etadavoca:._
____

.Illustration
====
at a respectful distance
====

[quote, M.1.393]
____
When the Blessed One had eaten and had withdrawn his hand from the bowl, Prince 
Abhaya taking a low seat, sat down at a respectful distance.

_Atha kho abhayo rājakumāro bhagavantaṃ bhuttāviṃ onītapattapāṇiṃ 
aññataraṃ nīcaṃ āsanaṃ gahetvā ekamantaṃ nisīdi._
____

