== Eko care khaggavisāṇakappo

=== Renderings

==== Renderings: eko care khaggavisāṇakappo

- _eko care khaggavisāṇakappo_: live the religious life as solitarily as a 
rhinoceros horn

==== Renderings: carati

- _carati_: to go

- _carati_: to travel

- _carati_: to walk

- _carati_: to fare

- _carati_: to wander

- _carati_: to walk on almsround

- _carati_: to undertake

- _carati_: to graze

- _carati_: to bring about

- _carati_: to live

- _carati_: to live the religious life

- _cārikaṃ caramāno_: journeying on foot

=== Introduction

==== Khaggavisāṇa means 'rhinoceros horn'

Norman has carefully explained why _khaggavisāṇa_ means 'rhinoceros horn' 
not 'rhinoceros.' He concludes that:

- 'When the Pāli can be so translated, when the earliest interpretation takes 
it that way, and when the Indian rhinoceros is unique among animals in India in 
having only one horn, it seems certain to me that the reference is to the 
single horn, and I think that there is no problem if we translate: 'Let him 
wander all by himself (_eko adutiyo_) having a resemblance to the rhinoceros 
horn, which is also _eko adutiyo_' (GD p.154).

But Norman is not curious to understand why translators have persisted to 
render _khaggavisāṇa_ as 'rhinoceros,' and why even today we find it as a 
meaning in the 2001 Dictionary of Pāli. So let us see why that is.

==== Persistently 'rhinoceros': the underlying problems

The continual refrain of the _Khaggavisāṇa Sutta_ is _eko care 
khaggavisāṇakappo_, and many would agree with Norman when he says it means 
one should 'wander solitary as a rhinoceros horn.' But this is unconvincing for 
two reasons:

1. It is unconvincing because of the obvious fact that although rhinceroses 
wander, their horns really do not. But the impossible conception of 'wandering 
horns' is not the only problem of Norman's translation.

2. Another problem of 'wandering solitary as a rhinoceros horn' is where the 
bhikkhu is in fact stationary. For example in verse in Sn.v.72 Norman says 'one 
should resort to secluded abodes, one should wander solitary as a rhinoceros 
horn.' And, even more problematic, in verse Sn.v.74, which apparently concerns 
the time of death, Norman says 'not trembling at [the time of] the complete 
destruction of life, one should wander solitary as a rhinoceros horn.'

We translate the verses like this:

[quote, Sn.v.72]
____
Like a strong-toothed lion, the king of beasts, having overpowered [Māra], 
having overcome [the Destroyer], conducting oneself [in accordance with the 
teaching], one should make use of secluded abodes. One should live the 
religious life as solitarily as a rhinoceros horn.

_Sīho yathā dāṭhabalī pasayha rājā migānaṃ abhibhuyya cārī +
Sevetha pantāni senāsanāni eko care khaggavisāṇakappo._
____

[quote, Sn.v.74]
____
Having abandoned attachment, hatred, and undiscernment of reality, having 
slashed the ties to individual existence, being unterrified at the [imminent] 
destruction of one's life, one should live the religious life as solitarily as 
a rhinoceros horn.

_Rāgañca dosañca pahāya mohaṃ sandālayitvāna saṃyojanāni +
Asantasaṃ jīvitasaṅkhayamhi eko care khaggavisāṇakappo._
____

==== Carati means brahmacariyaṃ carati

Both problems are resolved if we recognise _eko care khaggavisāṇakappo_ as 
an abbreviation for _eko brahmacariyaṃ care khaggavisāṇakappo_ 'live the 
religious life as solitarily as a rhinoceros horn.' The abbreviation of 
_carati_ in this way occurs elsewhere in the scriptures, not only in the 
_Khaggavisāṇa Sutta_, but only in verses, and is therefore to be explained 
and excused on metrical grounds. See Illustrations below. In prose 
_brahmacariyaṃ carati_ is common enough, but never abbreviated. Even in verse 
it is sometimes unabbreviated, for example:

[quote, S.1.169]
____
I am an arahant living the religious life.

_arahaṃ ahaṃ brahmacariyaṃ carāmi._
____

[quote, Ud.48]
____
He would live the religious life vigorously applied [to the practice].

_Ātāpiyo brahmacariyaṃ careyyā ti._
____

==== Kappo

That _kappo_ means 'like' or 'resembling,' see Group of Discourses p.154.

==== Carati

We first illustrate the meanings of _carati_, then afterwards deal with _eko 
care khaggavisāṇakappo_.

=== Illustrations: carati

.Illustration
====
carāmi

go
====

• Seeing that the body subsists on food, I go searching +
_Āhāraṭṭhitiko samussayo iti disvāna carāmi esanaṃ_ (Th.v.123).

.Illustration
====
carantu

go
====

• Go, sirs. The religious life is lived under the ascetic Gotama +
_carantu bhonto samaṇe gotame brahmacariyavāso_ (M.1.524).

.Illustration
====
carāmi

travel
====

[quote, Sn.v.25]
____
I travel the whole world on my own earnings

_Nibbiṭṭhena carāmi sabbaloke._
____

.Illustration
====
carāmi

wander
====

[quote, Sn.v.455]
____
I wander in the world, a sage, liberated from the perception of existence.

_akiñcano manta carāmi loke._
____

.Illustration
====
caraṃ

walking
====

[quote, It.117]
____
Whether walking, standing, sitting, or reclining

_Caraṃ vā yadi vā tiṭṭhaṃ nisinno uda vā sayaṃ._
____

.Illustration
====
cārikaṃ

caramāno, journeying
====

[quote, Vin.1.82]
____
Journeying by stages he arrived at Kapilavatthu.

_Anupubbena cārikaṃ caramāno yena kapilavatthu tadavasari._
____

.Illustration
====
caritvāna

walked
====

[quote, Sn.v.414]
____
Having walked on almsround

_piṇḍacāraṃ caritvāna._
____

.Illustration
====
caritvāna

fare
====

[quote, Sn.v.820]
____
Whoever formerly fared alone who then pursues sexual intercourse, in the world 
is called a 'lurching vehicle,' 'contemptible,' a 'common man.'

_Eko pubbe caritvāna methunaṃ yo nisevati +
Yānaṃ bhantaṃ va taṃ loke hīnamāhu puthujjanaṃ._
____

.Illustration
====
carati

fare
====

[quote, S.1.182]
____
He in this world who lives the religious life having spurned [the accumulating 
of] merit and demerit, who fares in the world with reflectiveness, he is truly 
called a bhikkhu.

_Yodha puññañca pāpañca bāhetvā brahmacariyavā +
Saṅkhāya loke carati sa ve bhikkhū ti vuccati._
____

.Illustration
====
carantaṃ

walking on almsround
====

[quote, M.1.10-11]
____
Walking on almsround in such unsuitable alms resorts (that would make his 
knowledgeable companions in the religious life suspect him of unvirtuous ways 
of conduct)

_yathārūpe agocare carantaṃ._
____

Comment:

[quote, Vin.2.208]
____
An incoming bhikkhu should ask about suitable and unsuitable alms resorts, 
called _gocara_ and _agocara_

_Gocaro pucchitabbo agocaro pucchitabbo._
____

.Illustration
====
caraṃ

walk on almsround
====

[quote, Th.v.1119]
____
Walk on almsround through the streets,

_visikhantare caraṃ._
____

.Illustration
====
careyya

walk (for alms)
====

[quote, Sn.v.386]
____
He should walk on almsround in the village at the right time. Bonds [to 
individual existence] bind one who walks on almsround at the wrong time.

_Gāmañca piṇḍāya careyya kāle +
Akālacāriṃ hi sajanti saṅgā._
____

.Illustration
====
caranti

graze
====

[quote, Sn.v.20]
____
The cows are grazing in the water-meadow where the grass grows lush

_kacche rūḷhatiṇe caranti gāvo._
____

.Illustration
====
caritvā

undertake
====

[quote, Sn.v.665]
____
Having undertaken many bad deeds

_Bahuni ca duccaritāni caritvā._
____

.Illustration
====
carati

conduct oneself
====

[quote, A.3.386]
____
He conducts himself rightly by way of body, speech, and mind.

_So kāyena sucaritaṃ carati vācāya sucaritaṃ carati manasā sucaritaṃ 
carati._
____

.Illustration
====
carati

conduct oneself
====

[quote, A.1.216]
____
One who is attached, overpowered, and overcome by attachment, misconducts 
himself by way of body, speech, and mind.

_Ratto kho āvuso rāgena abhibhūto pariyādinnacitto kāyena duccaritaṃ 
carati vācāya duccaritaṃ carati manasā duccaritaṃ carati._
____

.Illustration
====
carimha

bring about
====

[quote, Th.v.138]
____
We have brought about your death, sensuous yearning

_Vadhaṃ carimha te kāma._
____

.Illustration
====
cariṃsu

live
====

[quote, Sn.v.289]
____
For forty-eight years they lived the religious life as virgins.

_Aṭṭhacattārīsaṃ vassāni komāraṃ brahmacariyaṃ cariṃsu te._
____

.Illustration
====
carāmase

live
====

[quote, S.1.210]
____
Because we have not known the true teaching we've been living miserably mother.

_addhammassa anaññāya amma dukkhaṃ carāmase._
____

.Illustration
====
brahmacariyaṃ caritvā

live the religious life
====

[quote, D.2.50]
____
Lived the religious life under the Blessed One Vipassī

_vipassimhi bhagavatī brahmacariyaṃ caritvā._
____

.Illustration
====
brahmacariyamacariṃsu

live the religious life
====

[quote, Sn.v.1128]
____
They lived the religious life under the one of excellent wisdom.

_Brahmacariyamacariṃsu varapaññassa santike._
____

.Illustration
====
brahmacariyaṃ carati

live the religious life
====

[quote, A.3.69]
____
He lives the celibate life disgruntled

_anabhirato ca brahmacariyaṃ carati._
____

.Illustration
====
carassu brahmacariyaṃ

live the religious life
====

[quote, Sn.v.696]
____
Live the religious life under that Blessed One

_carassu tasmiṃ bhagavati brahmacariyaṃ._
____

.Illustration
====
caraṃ

live the religious life
====

[quote, Sn.v.1054]
____
And I would take delight in that supreme teaching, great Seer, understanding 
which, one living the religious life, one who is mindful, would overcome 
attachment to the world [of phenomena].

_Tañcāhaṃ abhinandāmi mahesi dhammamuttamaṃ +
Yaṃ viditvā sato caraṃ tare loke visattikaṃ._
____

.Illustration
====
carāmi

live the religious life
====

[quote, Sn.v.456]
____
Clad in robes, I live the religious life without a home, with a shaven head, 
with ego completely extinguished.

_Saṅghāṭivāsī agaho carāmi nivuttakeso abhinibbutatto._
____

.Illustration
====
carantaṃ

live the religious life
====

[quote, Ud.77]
____
The world [of beings] with its devas does not despise the sage living the 
religious life, free of craving.

_Taṃ taṃ nittaṇhaṃ muniṃ carantaṃ +
Nāvajānāti sadevako pi loko ti._
____

Ireland: the world with its devas does not despise that cravingless sage as he 
fares along.

.Illustration
====
carantaṃ

live the religious life
====

[quote, Sn.v.220]
____
A sage, living the religious life, abstaining from sexual intercourse,

_Muniṃ carantaṃ virataṃ methunasmā._
____

.Illustration
====
caranti

live the religious life
====

[quote, Th.v.1215]
____
Everything is unlasting. Having understood this, the wise live the religious 
life.

_sabbamaniccaṃ evaṃ samecca caranti mutattā._
____

.Illustration
====
caranti

live the religious life
====

[quote, Sn.v.1078]
____
Those who live the religious life without confrontation, rid of spiritual 
defilement, free of expectations, I call them sages.

_Visenikatvā anīghā nirāsā caranti ye te munayo ti brūmi._
____

.Illustration
====
carissasi

live the religious life
====

[quote, Sn.v.949]
____
Let wither what is past. Let there not be for you anything at all [hoped for] 
in the future. If you do not grasp at what is in between you will live the 
religious life inwardly at peace.

_Yaṃ pubbe taṃ visosehi pacchā te māhu kiñcanaṃ +
Majjhe ce no gahessasi upasanto carissasi._
____

=== Illustrations: eko care khaggavisāṇakappo

.Illustration
====
care

live the religious life
====

[quote, Sn.v.35]
____
Having renounced violence towards all creatures, not harming any of them, one 
should not wish for a son, let alone a companion. One should live the religious 
life as solitarily as a rhinoceros horn.

_Sabbesu bhūtesu nidhāya daṇḍaṃ aviheṭhayaṃ aññatarampi tesaṃ +
Na puttamiccheyya kuto sahāyaṃ eko care khaggavisāṇakappo._
____

.Illustration
====
care

live the religious life
====

[quote, Sn.v.75]
____
&#8203;[People] consort and associate [with others] for the sake of selfish advantage. 
Nowadays friends without selfish motives are hard to find. Men who are wise as 
to selfish benefits are foul. One should live the religious life as solitarily 
as a rhinoceros horn.

_Bhajanti sevanti ca kāraṇatthā nikkāraṇā dullabhā ajja mittā +
Attaṭṭhapaññā asucī manussā eko care khaggavisāṇakappo._
____

