== Gaṇḍa

=== Renderings

- _gaṇḍa_: carbuncle

=== Introduction

==== Carbuncles and ordination

_Gaṇḍa_ is a serious disease that can block a bhikkhu candidate's 
ordination (_na bhikkhave pañcahi ābādhehi phuṭṭho pabbājetabbo_, 
Vin.1.73). Accordingly, it seems appropriate to call _gaṇḍa_ 'carbuncle,' 
not 'boil,' because a carbuncle is 'somewhat like a boil, but more serious in 
its effects' (http:// dictionary.reference.com). One would not expect a boil to 
block one's ordination.

==== The body as a carbuncle

The body is compared to a _gaṇḍa_ with nine orifices (_nava vaṇamukhāni_ 
A.4.386). Whatever flows out of a _gaṇḍa_ is foul, foul-smelling, and 
disgusting (_asuciññeva pagghareyya duggandhañceva pagghareyya 
jegucchiyaññeva pagghareyya_). This again suggests carbuncle, not boil, 
because a carbuncle 'is an abscess larger than a boil, usually with one or more 
openings, draining pus onto the skin' (en.wiktionary.org).

==== The aggregates: carbuncles

The five aggregates are like five carbuncles, presumably because of the chronic 
misery associated with them:

[quote, M.1.435-7; A.4.422-6]
____
Whatever phenomena are connected with the five aggregates, he sees those 
states... as an illness, as a carbuncle...

_so yadeva tattha hoti rūpagataṃ vedanāgataṃ saññāgataṃ 
saṅkhāragataṃ viññāṇagataṃ te dhamme... rogato gaṇḍato... 
samanupassati._
____

For full quote, see Illustrations.

==== The notion "I am": carbuncle

The Buddha applied the term metaphorically to the notion "I am":

____
The notion "I am" is a matter of thinking in personal terms

_asmī ti maññitametaṃ_
____

____
'I am this' is a matter of thinking in personal terms

_ayamahamasmī ti maññitametaṃ_
____

____
'I will be' is a matter of thinking in personal terms

_bhavissan ti maññitametaṃ_
____

____
'I will not be' is a matter of thinking in personal terms

_na bhavissan ti maññitametaṃ_
____

• ... Thinking in personal terms is an illness, a carbuncle, a [piercing] 
arrow. Therefore train yourselves with the thought, 'We will live with minds 
free of thinking in personal terms' +
_maññitaṃ bhikkhave rogo maññitaṃ gaṇḍo maññitaṃ sallaṃ 
tasmātiha bhikkhave amaññamānena cetasā viharissāmāti evaṃ hi vo 
bhikkhave sikkhitabbaṃ_ (S.4.203).

==== Sensuous pleasures: carbuncle

Sensuous pleasures are called a carbuncle because they are associated with 
carbuncles, presumably meaning the aggregates, or even the notion "I am":

[quote, A.3.310]
____
Bhikkhus, 'carbuncle' is an epithet for sensuous pleasures. Why so? Because one 
who is passionately attached to sensuous pleasure, fastened by fondness and 
attachment, is neither free of carbuncles in this lifetime, nor in the 
hereafter, therefore 'carbuncle' is an epithet for sensuous pleasures.

_gaṇḍo ti bhikkhave kāmānametaṃ adhivacanaṃ. Kasmā ca bhikkhave 
gaṇḍo ti kāmānametaṃ adhivacanaṃ. Yasmā ca kāmarāgarattāyaṃ 
bhikkhave chandarāgavinibaddho diṭṭhadhammikāpi gaṇḍā na parimuccati 
samparāyikāpi gaṇḍā na parimuccati. Tasmā gaṇḍanti kāmānametaṃ 
adhivacanaṃ._
____

=== Illustrations

.Illustration
====
gaṇḍo

carbuncle
====

____
Bhikkhus, suppose there was a carbuncle many years old, and which had nine 
openings, nine orifices. Whatever oozes out of them would be foul, 
foul-smelling, and disgusting.

_gaṇḍo anekavassagaṇiko tassassu nava vaṇamukhāni nava 
abhedanamukhāni tato yaṃ kiñci pagghareyya asuciññeva pagghareyya 
duggandhañceva pagghareyya jegucchiyaññeva pagghareyya._
____

____
A 'carbuncle' is a metaphor for this [wretched human] body made of the four 
great material phenomena.

__'Gaṇḍo ti kho bhikkhave imasseva cātummahābhūtikassa kāyassa 
adhivacanaṃ_
____

____
It has nine openings, nine orifices.

_tassa nava vanamukhāni nava abhedanamukhāni_
____

[quote, A.4.386]
____
Whatever oozes out of them is foul, foul-smelling, and disgusting._

_yaṃ kiñci paggharati asuciññeva paggharati duggandhaññeva paggharati 
jegucchiyaññeva paggharati._
____

.Illustration
====
gaṇḍaṃ

carbuncle
====

[quote, Vin.4.316]
____
Whatever bhikkhunī, without having obtained permission from a community or 
group of bhikkhunīs, should together with a man, the one with the other, make 
a carbuncle or a scab that has formed on the lower part of her body burst or 
break, or allow it to be washed, smeared, bound up, or unbound, there is an 
offence of pācittiya.

_Yā pana bhikkhunī pasākhe jātaṃ gaṇḍaṃ vā ruhitaṃ vā 
anapaloketvā saṅghaṃ vā gaṇaṃ vā purisena saddhiṃ ekenekā 
bhedāpeyya vā phālāpeyya vā dhovāpeyya vā ālimpāpeyya vā bandhāpeyya 
vā mocāpeyya vā pācittiyan ti._
____

.Illustration
====
gaṇḍaṃ

carbuncle
====

[quote, M.1.435]
____
He regards whatever phenomena there that are connected with the five 
aggregates, as unlasting, as existentially void, as an illness, as a carbuncle, 
as a [piercing] arrow, as suffering, as an affliction, as alien, as destined to 
decay, as void [of personal qualities], as void of personal qualities.

_so yadeva tattha hoti rūpagataṃ vedanāgataṃ saññāgataṃ 
saṅkhāragataṃ viññāṇagataṃ te dhamme aniccato dukkhato rogato 
gaṇḍato sallato aghato ābādhato parato palokato suññato anattato 
samanupassati._
____

