== Gocara

=== Renderings

- _gocara_: pasture

- _gocara_: hunting ground

- _gocara_: feeding ground

- _gocara_: alms resort

- _gocara_: suitable alms resort

- _gocara_: sphere of personal application

- _gocara_: sphere of activity

- _gocara_: sphere of application

- _gocarāya_: searching for food

=== Illustrations

.Illustration
====
gocarāya

pasture
====

[quote, Sn.v.39]
____
An unconfined deer in the forest goes where it wishes for pasture

_Migo araññamhi yathā abaddho yenicchakaṃ gacchati gocarāya._
____

.Illustration
====
gocarāya

to find some food
====

[quote, S.2.270]
____
Then that gentle mouse came out to find some food.

_Atha kho bhikkhave mudumūsī gocarāya pakkami._
____

.Illustration
====
gocarāya

hunting ground
====

[quote, A.2.33]
____
Having roared three leonine roars, he sets out for the hunting ground._

_Tikkhattuṃ sīhanādaṃ naditvā gocarāya pakkamati._
____

.Illustration
====
gocaro

hunting ground
====

[quote, M.2.261-2]
____
Sensuous pleasures in this lifetime and in the hereafter, mental images of 
sensuous pleasures of this lifetime and of the hereafter, both alike are 
Māra's realm, Māra's domain, Māra's bait, Māra's hunting ground.

_Ye ca diṭṭhadhammikā kāmā ye ca samparāyikā kāmā yā ca 
diṭṭhadhammikā kāmasaññā yā ca samparāyikā kāmasaññā 
ubhayametaṃ māradheyyaṃ mārassesavisayo marassesanivāpo 
mārassesagocaro._
____

.Illustration
====
gocare

feeding ground
====

[quote, S.4.198]
____
Suppose a man caught six animals with different domains and different feeding 
grounds, and tied them together with a strong rope... Then those six animals 
would each pull in the direction of its own feeding ground and domain. The 
snake would pull, thinking, 'Let me enter an anthill.' The crocodile would 
pull, thinking, 'Let me enter the water.' The bird would pull, thinking, 'Let 
me fly into the sky.' The dog would pull, thinking, 'Let me enter a village.' 
The jackal would pull, thinking, 'Let me enter a charnel ground.' The monkey 
would pull, thinking, 'Let me enter a forest.'

_Seyyathā pi bhikkhave puriso chappāṇake gahetvā nānāvisaye nānāgocare 
daḷhāya bandheyya... atha kho te bhikkhave chappāṇakā nānāvisayā 
nānāgocarā sakaṃ sakaṃ gocaravisayaṃ āviñjeyyuṃ. Ahi āviñjeyya 
vammikaṃ pavekkhāmī ti suṃsumāro āviñjeyya udakaṃ pavekkhāmī ti 
pakkhi āviñjeyya ākāsaṃ ḍessāmīti kukkuro āviñjeyya gāmaṃ 
pavekkhāmī ti sigālo āviñjeyya sīvathikaṃ pavekkhāmī ti makkaṭo 
āviñjeyya vanaṃ pavekkhāmī ti._
____

.Illustration
====
gocara

pastures; gocara, sphere of personal application
====

[quote, A.5.348]
____
Bhikkhus, possessing eleven factors, a cowherd is incapable of keeping and 
rearing a herd of cattle. What eleven? Here, a cowherd... is unknowledgeable 
about pastures.

_Ekādasahi bhikkhave aṅgehi samannāgato gopālako abhabbo gogaṇaṃ 
pariharituṃ phātikattuṃ. Katamehi ekādasahi. Idha bhikkhave gopālako... 
na gocarakusalo hoti._
____

[quote, A.5.349]
____
And how is a bhikkhu unknowledgeable about the [proper] sphere of personal 
application? Here, a bhikkhu does not discern according to reality the 
&#8203;[contemplation of the] four bases of mindfulness. It is in this way that a 
bhikkhu is unknowledgeable about the [proper] sphere of personal application.

_Kathañca bhikkhave bhikkhu na gocarakusalo hoti: idha bhikkhave bhikkhu 
cattāro satipaṭṭhāne yathābhūtaṃ nappajānāti._
____

.Illustration
====
gocaro

alms resort
====

[quote, Vin.1.70]
____
One who was formerly a non-Buddhist ascetic has his alms resort amongst 
prostitutes, widows, fat girls, eunuchs, or bhikkhunīs.

_aññatitthiyapubbo vesiyagocaro vā hoti. Vidhavagocaro vā hoti. 
Thullakumārikagocaro vā hoti. Paṇḍakagocaro vā hoti. Bhikkhunīgocaro 
vā hoti._
____

.Illustration
====
gocaro

suitable alms resorts
====

[quote, Vin.2.208]
____
An incoming bhikkhu should ask about suitable and unsuitable alms resorts.

_Gocaro pucchitabbo agocaro pucchitabbo._
____

.Illustration
====
agocare

unsuitable alms resorts
====

In this regard a bhikkhu, properly reflecting, avoids... walking on almsround 
in such unsuitable alms resorts (_yathārūpe agocare carantaṃ_), and 
associating with the sorts of unvirtuous friends that would make his 
knowledgeable companions in the religious life suspect him of unvirtuous ways 
of conduct (M.1.10-11).

.Illustration
====
gocaro

sphere of personal application
====

[quote, M.1.319]
____
Purified states known through the eye or ear are found in the Perfect One. They 
are my path [of practice], my sphere of personal application, but I do not 
regard them as endowed with personal qualities.

_ye vodātā cakkhusotaviññeyyā dhammā saṃvijjanti te tathāgatassa 
etapathohamasmi etagocaro no ca tena tammayo ti._
____

.Illustration
====
gocara

sphere of personal application
====

[quote, M.3.2]
____
Come, bhikkhu! Be virtuous. Abide restrained [in conduct] within the 
constraints of the rules of discipline, and be perfect in conduct and sphere of 
personal application, seeing danger in the slightest wrongdoing.

_ehi tvaṃ bhikkhu sīlavā hohi pātimokkhasaṃvarasaṃvutā viharāhi 
ācāragocarasampanno aṇumattesu vajjesu bhayadassāvi._
____

.Illustration
====
gocare

sphere of personal application
====

____
Keep to your own sphere of personal application, to your ancestral haunts. If 
you do so, Māra will not get his chance, his opportunity [to attack] you.

_Gocare bhikkhave caratha sake pettike visaye. Gocare bhikkhave carataṃ sake 
pettike visaye na lacchati māro otāraṃ na lacchati māro ārammaṇaṃ_
____

[quote, S.5.147-8]
____
And where is a bhikkhu's sphere of personal application and ancestral haunt? It 
is the [contemplation of the] four bases of mindfulness.

_ko ca bhikkhave bhikkhuno gocaro sako pettiko visayo yadidaṃ cattāro 
satipaṭṭhānā._
____

.Illustration
====
gocaro

sphere of personal application
====

[quote, Dh.v.93]
____
Those people whose perceptually obscuring states are destroyed, who are not 
attached to existential nourishment, whose sphere of personal application is 
the state of refined awareness that is void [of the perception of personal 
qualities] and that is focused upon the unabiding [phenomena], their path of 
practice is as hard to emulate as that of the birds in the sky.

_Yassāsavā parikkhīṇā āhāre ca anissito +
Suññato animitto ca vimokkho yassa gocaro +
Ākāse va sakuntānaṃ padaṃ tassa durannayaṃ._
____

.Illustration
====
gocare

sphere of personal application
====

[quote, Dh.v.22]
____
The wise, recognising this special quality of diligence, rejoice in it, taking 
delight in the Noble People's sphere of personal application.

_Etaṃ visesato ñatvā appamādamhi paṇḍitā +
Appamāde pamodanti ariyānaṃ gocare ratā._
____

.Illustration
====
gocarā

sphere of personal application
====

[quote, S.3.83]
____
Those who have profoundly understood the five aggregates, whose sphere of 
personal application is the seven good qualities, those spiritually outstanding 
people are praiseworthy, the Buddha's spiritual sons.

_Pañcakkhandhe pariññāya sattasaddhammagocarā +
Pāsaṃsiyā sappurisā puttā buddhassa orasā._
____

Comment:

[quote, D.3.252]
____
The seven good qualities: In this regard a bhikkhu has faith [in the perfection 
of the Perfect One's transcendent insight], shame of wrongdoing, a fear of 
wrongdoing, is learned, energetic, has mindfulness established, and is blessed 
with penetrative discernment.

_Satta saddhammā: idhāvuso bhikkhu saddho hoti hirīmā hoti ottappī hoti 
bahussuto hoti āraddhaviriyo hoti upaṭṭhitasati hoti paññavā hoti._
____

.Illustration
====
gocarā

sphere of personal application
====

[quote, Sn.v.961]
____
What should be his manner of speech? What his sphere of personal application in 
this world? What should be that resolute bhikkhu's observances and practices?

_Kyāssa vyappathayo assu kyāssassu idha gocarā +
Kāni sīlabbatānāssu pahitattassa bhikkhuno._
____

.Illustration
====
gocare

sphere of activity
====

[quote, Sn.v.605]
____
Then consider fish, also, denizens of the deep, beings with water as their 
sphere of activity.

_Tato macche pi jānātha odake vārigocare._
____

.Illustration
====
gocarāni

spheres of activity
====

[quote, S.5.218]
____
Brahman, these five sense faculties have different domains, different spheres 
of activity. They do not experience each others' sphere of activity and domain. 
What five? The faculties of sight, hearing, smell, taste, and touch.

_Pañcimāni brāhmaṇa indriyāni nānāvisayāni nānāgocarāni na 
aññamaññassa gocaravisayaṃ paccanunabhonti. Katamāni pañca: 
cakkhundriyaṃ sotindriyaṃ ghānindriyaṃ jivhindriyaṃ kāyindriyaṃ.._
____

.Illustration
====
gocara

sphere of application
====

____
Possessed of six qualities, a bhikkhu could destroy the Himalayas, the king of 
mountain ranges, not to speak of vile ignorance. What six?

_Chahi bhikkhave dhammehi samannāgato bhikkhu himavantaṃ pabbatarājaṃ 
padāleyya, ko pana vādo chavāya avijjāya_
____

____
In this regard a bhikkhu is:

_Idha bhikkhave bhikkhū_
____

____
proficient in attaining inward collectedness _

_samādhissa samāpattikusalo hoti_
____

____
proficient in maintaining inward collectedness _

_Samādhissa ṭhitikusalo hoti_
____

____
proficient in emerging from inward collectedness _

_Samādhissa vuṭṭhānakusalo hoti_
____

____
proficient in preparing for inward collectedness _

_Samādhissa kallitakusalo hoti_
____

____
knowledgeable about the [proper] sphere of application of inward collectedness _

_Samādhissa gocarakusalo hoti_
____

[quote, A.3.311]
____
proficient in directing inward collectedness _

_Samādhissa abhinīhārakusalo hoti._
____

