== Gutta

=== Renderings

- _gutta_: safeguarded

- _gutta_: guarded [by mindfulness]

=== Introduction

==== Indriyesu guttadvāro: linked to mindfulness

Because _indriyesu guttadvāro_ is linked to mindfulness, it implies that the 
sense faculties are not just 'guarded,' but guarded by mindfulness, which 
should therefore be parenthesised.

[quote, A.3.138]
____
Come on, friend, abide with sense portals guarded [by mindfulness]. Take 
mindfulness as your supervisor. Be aware and mindful, and have a mind that is 
supervised [by mindfulness], a mind under the supervision of mindfulness.

_Etha tumhe āvuso indriyesu guttadvārā viharatha ārakkhasatino 
nipakkasatino sārakkhitamānasā satārakkhena cetasā samannāgatāti._
____

==== Indriyesu guttadvāro: linked to mindfulness via saṃvara

_Indriyesu guttadvāro_ is sometimes linked to mindfulness via _saṃvara_, 
again implying that the sense faculties are not just 'guarded,' but guarded by 
mindfulness. These quotes show _saṃvara_'s relationship to mindfulness:

1. When a bhikkhu has developed and cultivated mindfulness of the body, the eye 
does not incline towards pleasing visible objects nor are displeasing visible 
objects loathsome... In this way there is restraint [of the sense faculties] 
&#8203;[from attraction and repulsion, through mindfulness].
+
****
_kāyagatā sati bhāvitā bahulīkatā cakkhu nāviñjati manāpikesu rūpesu 
amanāpikassa rūpāni nappaṭikkūlā honti... evaṃ kho bhikkhave saṃvaro 
hoti_ (S.4.200).
****

2. What is the condition that nourishes unrestraint of the sense faculties? 
Lack of mindfulness and full consciousness, one should reply.
+
****
_Ko cāhāro indriyāsaṃvarassa? Asatāsampajaññan tissa vacanīyaṃ_ 
(A.5.113).
****

3. What is the condition that nourishes restraint of the sense faculties [from 
attraction and repulsion, through mindfulness]? Mindfulness and full 
consciousness, one should reply.
+
****
_Ko cāhāro indriyasaṃvarassa. Satisampajaññantissa vacanīyaṃ_ 
(A.5.115).
****

==== 'One with sense portals unguarded [by mindfulness]': definition

____
-- By virtue of what attributes, Master Kaccāna, is one 'with sense portals 
unguarded [by mindfulness]'?"

_kittāvatā nu kho bho kaccāna aguttadvāro hotī ti?_
____

____
-- In this regard, brahman, in seeing a visible object via the visual sense, 
some person is intent upon an agreeable visible object and troubled by a 
disagreeable visible object.

_Idha brāhmaṇa ekacco cakkhunā rūpaṃ disvā piyarūpe rūpe adhimuccati 
appiyarūpe rūpe vyāpajjati_
____

____
... He abides without having established mindfulness of the body, with a small 
mind, and he does not discern according to reality, with the liberation [from 
attachment through inward calm] and the liberation [from uninsightfulness] 
through penetrative discernment, where those unvirtuous, spiritually 
unwholesome factors cease without remainder.

_anupaṭṭhitakāyasati ca viharati parittacetaso tañca cetovimuttiṃ 
paññāvimuttiṃ yathābhūtaṃ nappajānāti yatthassa te uppannā pāpakā 
akusalā dhammā aparisesā na nirujjhanti_
____

[quote, S.4.120]
____
... It is in such a way, brahman, that one has sense portals unguarded [by 
mindfulness]

_Evaṃ kho brāhmaṇa aguttadvāro hotī ti._
____

==== 'One with sense portals guarded [by mindfulness]': definition

____
And how is a bhikkhu one with sense portals guarded [by mindfulness]?

_kathañca bhikkhave bhikkhu indriyesu guttadvāro hoti._
____

____
In this regard, in seeing a visible object via the visual sense, a bhikkhu does 
not grasp its aspects and features. Since, by abiding with the faculty of sight 
unrestrained [from attraction and repulsion, through mindfulness], greed, 
dejection, and unvirtuous, spiritually unwholesome factors would pursue him. He 
applies himself to the restraint of the faculty [from attraction and repulsion, 
through mindfulness], he supervises the faculty of sight [with mindfulness], he 
attains restraint of the faculty of sight [through mindfulness].

_cakkhunā rūpaṃ disvā na nimittaggāhī hoti nānuvyañjanaggāhī 
yatvādhikaraṇamenaṃ cakkhundriyaṃ asaṃvutaṃ viharantaṃ abhijjhā 
domanassā pāpakā akusalā dhammā anvāssaveyyuṃ tassa saṃvarāya 
paṭipajjati rakkhati cakkhundriyaṃ cakkhundriye saṃvaraṃ āpajjati._
____

Suppose a chariot harnessed to thoroughbreds was standing ready on even ground 
at a crossroads, with a goad on hand. Then a proficient handler, a trainer of 
horses to be tamed, would mount it and, taking the reins in his left hand and 
the goad in his right, would drive away and return by any route he wants, 
whenever he wants.

So, too, a bhikkhu trains in

____
supervising these six sense faculties [with mindfulness]

_imesaṃ channaṃ indriyānaṃ ārakkhāya sikkhati_
____

____
restraining them [with mindfulness]

_saṃyamāya sikkhati_
____

____
taming them [with mindfulness]

_damāya sikkhati_
____

____
calming them [with mindfulness]

_upasamāya sikkhati_
____

[quote, S.4.176]
____
In this way a bhikkhu has sense portals guarded [by mindfulness].

_evaṃ kho bhikkhave bhikkhu indriyesu guttadvāro hoti._
____

=== Illustrations

.Illustration
====
gutta

guarded [by mindfulness]
====

[quote, A.5.134]
____
To one with sense portals guarded [by mindfulness], watching shows is a thorn.

_indriyesu guttadvārassa visūkadassanaṃ kaṇṭako._
____

.Illustration
====
guttaṃ

guarded [by mindfulness]
====

[quote, Dh.v.36]
____
A mind that is guarded [by mindfulness] brings happiness.

_cittaṃ guttaṃ sukhāvahaṃ._
____

.Illustration
====
gutto

guarded
====

[quote, Dh.v.257]
____
The wise person, guarded by righteousness, is called righteous.

_Dhammassa gutto medhāvī dhammaṭṭho ti pavuccati._
____

.Illustration
====
guttassa

guarded
====

[quote, S.1.222]
____
The strength of a fool, they say, is the strength without strength. But there 
is no such rejoinder for the strength of one guarded by righteousness.

_Abalantaṃ balaṃ āhu yassa bālabalaṃ balaṃ +
Balassa dhammaguttassa paṭivattā na vijjati._
____

.Illustration
====
gutta

guarded [by mindfulness]
====

____
Bhikkhus, this is how Nanda has sense portals guarded [by mindfulness]

_Tatiradaṃ bhikkhave nandassa indriyesu guttadvāratāya hoti_
____

____
Bhikkhus, if Nanda looks at the eastern quarter, applying his whole mind to it, 
he looks thereat reflecting:

_sace bhikkhave nandassa puratthimā disā āloketabbā hoti sabbaṃ cetasā 
samannāharitvā nando puratthimaṃ disaṃ āloketi_
____

____
'Thus while I look to the eastern quarter, greed, dejection, and unvirtuous, 
spiritually unwholesome factors will not pursue me'

_evaṃ me puratthimaṃ disaṃ ālokayato na abhijjhā domanassā pāpakā 
akusalā dhammā anvāssavissantī ti_
____

[quote, A.4.167]
____
Thus indeed in this respect is he fully conscious

_itiha tattha sampajāno hoti._
____

.Illustration
====
guttaṃ

safeguarded
====

[quote, Dh.v.315]
____
Just as a border city is safeguarded within and without, likewise keep watch 
over yourself. May the [rare] opportunity [to live the religious life] not pass 
you by.

_Nagaraṃ yathā paccantaṃ guttaṃ santarabāhiraṃ +
Evaṃ gopetha attānaṃ khaṇo vo mā upaccagā._
____

.Illustration
====
gutto

safeguard
====

When a boy has grown up and has enough wisdom, then his nurse is unconcerned 
about him, thinking:

[quote, A.3.6]
____
The boy can now safeguard himself. He will not be negligent [in looking after 
himself].

_attaguttodāni kumāro nālaṃ pamādāyā ti._
____

.Illustration
====
guttā

safeguard
====

An acrobat told his apprentice Medakathālikā to join him on the bamboo pole 
and stand on his shoulders, and said:

____
-- 'You protect me, dear Medakathālikā, and I'll protect you.

_tvaṃ samma medakathālike mamaṃ rakkha. Ahaṃ tvaṃ rakkhikissāmi._
____

____
'Thus safeguarding one another, protecting one another, we'll exhibit our 
skills, collect our fee, and get safely off the bamboo pole.'

_Evaṃ mayaṃ aññamaññaguttā aññamaññarakkhitā_
____

Medakathālikā replied:

[quote, S.5.168-9]
____
-- 'That's not the way to do it, teacher. You protect yourself, teacher, and 
I'll protect myself. Thus, each safeguarding ourselves, and protecting 
ourselves, we'll exhibit our skills, collect our fee, and get safely off the 
bamboo pole.'

_na kho nāmenaṃ ācariya evaṃ bhavissati tvaṃ ācariya attānaṃ rakkha 
ahaṃ attānaṃ rakkhissāmi. Evaṃ mayaṃ attaguttā attarakkhitā 
sippāni ceva dassessāma lābhañca lacchāma sotthinā ca 
caṇḍālavaṃsā orohessāmā ti._
____

