== Guṇa

=== Renderings

- _guṇa_: times

- _guṇa_: spiritual quality

- _guṇa_: level of

- _guṇa_: stage of

- _guṇa_: way/manner

- _guṇa_: practice

- _guṇa_: kind of

- _guṇa_: variety

- _guṇa_: layered

- _guṇavant_: virtuous

- _saguṇaṃ karoti_: to fold

=== Introduction

==== Guṇā: constituent parts

The only problem with _guṇa_ is its use in _pañcakāmaguṇā_, which is 
often called 'the five strands of sense pleasure.' The word 'strand' is used 
because rope is made of strands, where strands are its constituent parts, says 
PED. If this is the case, then _guṇā_ would be less confusingly called 
constituent parts, not strands.

==== Guṇā: kinds of

Norman says 'It is sometimes said that _guṇā_ has no meaning in 
_kāmaguṇā._ It actually means "kinds of... "' (Group of Discourses, p.160, 
note 50-51).

==== Guṇā: varieties of

We say 'kinds of' in the phrase 'he undertakes and practises some kind of 
austerity' (_aññataraṃ vā pana tapoguṇaṃ samādāya vattati_: M.2.36). 
Bodhi likewise says 'some kind of asceticism'; but we say 'varieties' in the 
phrase _pañcime bhikkhave kāmaguṇā_: 'five varieties of sensuous pleasure.'

==== The other guṇa

There are two words _guṇa_, the other one meaning 'ball, cluster, chain,' and 
which commonly substitutes with _guḷa_:

• the elephant that bursts all its fastenings and chains** +
☸** _nāgoca sandānaguṇāni chetvā_ (D.2.274).

• one adorned with a chain of garlands +
_mālāguṇaparikkhittāpi_ (M.1.286).

Also _antaguṇaṃ_ (mesentary), is part of this group.

=== Illustrations

.Illustration
====
guṇaṃ__

__ times
====

[quote, D.3.13]
____
However many superhuman displays of psychic power the ascetic Gotama performs, 
I will perform twice (two times) as many.

_iti yāvatakaṃ samaṇo gotamo uttarimanussadhammā iddhipāṭihāriyaṃ 
karissati taddiguṇaṃ taddiguṇāhaṃ karissāmī ti._
____

.Illustration
====
guṇaṃ__

__ times
====

[quote, D.3.187]
____
When some business is to be done he lets you have twice (two times) the money 
you ask for.

_uppanne kiccakaraṇīye taddiguṇaṃ bhogaṃ anuppadeti._
____

.Illustration
====
guṇaṃ

two times/one time
====

[quote, Sn.v.714]
____
They do not go to the Far Shore twice (two times); this [Far Shore] is not 
experienced [even] once (one time).

_Na pāraṃ diguṇaṃ yanti na idaṃ ekaguṇaṃ mutaṃ._
____

.Illustration
====
guṇaṃ

times
====

[quote, Thī.v.153]
____
However much Anopamā weighs, that daughter of yours, I will give you eight 
times that in gold and gems [as a dowry].

_Yattakaṃ tulitā esā tuyhaṃ dhītā anūpamā. +
Tato aṭṭhaguṇaṃ dassaṃ hiraññaṃ ratanāni ca._
____

.Illustration
====
guṇā

times
====

[quote, M.3.255]
____
By giving a gift to an animal, the gift may be expected to repay a hundredfold 
(hundred times).

_tatrānanda tiracchānagate dānaṃ datvā sataguṇā dakkhiṇā 
pāṭikaṅkhitabbā._
____

.Illustration
====
saguṇaṃ katvā

to fold
====

[quote, Vin.1.46]
____
Having folded them, his [outer and upper] robes are to be given to him.

_Saguṇaṃ katvā saṅghāṭiyo dātabbā._
____

.Illustration
====
guṇaṃ

fold
====

[quote, D.2.128]
____
Come, Ānanda, double up my outer robe for me; I am tired and will lie down.

_catugguṇaṃ saṅghāṭi paññapehi._
____

Comment:

The outer robe is double thickness. Folding it once makes it four thicknesses 
(_catugguṇaṃ_).

.Illustration
====
guṇaṃ

fold
====

[quote, D.2.135]
____
On a doubled-up robe I will lie down

_catugguṇaṃ patthara me nipacchaṃ._
____

.Illustration
====
guṇaṃ

fold
====

[quote, A.5.126]
____
Then the Blessed One having doubled up his outer robe lay down on his right 
side in the lion's posture

_Atha kho bhagavā catugguṇaṃ saṅghāṭiṃ paññapetvā dakkiṇena 
passena sīhaseyyaṃ kappesi._
____

.Illustration
====
guṇā

layered
====

[quote, Vin.1.185]
____
I allow sandals with one layer. Bhikkhus, double-layered sandals should not be 
worn; triple-layered sandals should not be worn, multi-layered sandals should 
not be worn.

_anujānāmi bhikkhave ekapalāsikaṃ upāhanaṃ. Na bhikkhave diguṇā 
upāhanā dharetabbā. Na tiguṇā upāhanā dharetabbā na 
guṇaṅguṇūpāhanā dhāretabbā._
____

.Illustration
====
guṇaṃ

layered
====

[quote, Vin.1.288]
____
I allow you bhikkhus three robes: a double-layered outer robe, a single-layered 
upper robe, a single-layered inner robe.

_anujānāmi bhikkhave ticīvaraṃ: diguṇaṃ saṅghāṭiṃ ekacciyaṃ 
uttarāsaṅgaṃ ekacciyaṃ antaravāsakan ti._
____

.Illustration
====
guṇaṃ

layered
====

• When garments are thin from use, I allow a four-layered outer robe, a 
double-layered upper robe, a double-layered inner robe. +
☸ _anujānāmi bhikkhave... utuddhaṭānaṃ dussānaṃ catugguṇaṃ 
saṅghāṭiṃ dviguṇaṃ uttarāsaṅghaṃ dviguṇaṃ antaravāsakaṃ_ 
Vin.1.290).

.Illustration
====
guṇā

varieties
====

____
These are the five varieties of sensuous pleasure.

_Pañcime bhikkhave kāmaguṇā_
____

____
Visible objects known via the visual sense that are likeable, loveable, 
pleasing, agreeable, connected with sensuous pleasure, and charming.

_cakkhuviññeyyā rūpā iṭṭhā kantāmanāpā piyarūpā 
kāmūpasaṃhitā rajaniyā._
____

and likewise for audible objects, smellable objects, tasteable objects, and 
tangible objects.

.Illustration
====
guṇaṃ

kind of
====

[quote, M.2.36]
____
He undertakes and practises some kind of austerity

_aññataraṃ vā pana tapoguṇaṃ samādāya vattati._
____

.Illustration
====
guṇa

way/manner
====

[quote, A.1.199]
____
Those who talk aggressively, dogmatically, arrogantly, offending in an ignoble 
way, seeking to expose each other's faults,

_Ye viruddhā sallapanti viniviṭṭhā samussitā +
Anariyaguṇamāsajja aññamañña vivaresino._
____

.Illustration
====
guṇā

stages
====

[quote, S.1.3]
____
Time flies by, the nights swiftly pass; the stages of life successively desert 
us.

_Accenti kālā tarayanti rattiyo vayoguṇā anupubbaṃ jahanti._
____

.Illustration
====
guṇe

level
====

____
-- 'Soṇa, when its strings were neither too tight nor too loose but adjusted 
to an even level, was your lute tuneful and good for playing?'

_na accāyatā honti na atisithilā same guṇe patiṭṭhitā_
____

-- 'Yes, bhante' (A.3.375; Vin.1.182).

.Illustration
====
guṇavant

virtuous
====

[quote, Thī.v.399]
____
Two virtuous bhikkhunīs

_dve bhikkhunīyo hi guṇavatiyo._
____

.Illustration
====
guṇavant

virtuous
====

[quote, Thī.v.445]
____
He had another wife, a moral, virtuous, and glorious woman.

_Tassapi aññā bhariyā sīlavatī guṇavatī yasavatī ca._
____

.Illustration
====
guṇā

practice
====

[quote, Vin.3.163-4]
____
Thus perhaps I may drive him away from this religious life: I may drive him 
away from bhikkhuhood, asceticism, the aggregate of virtuous practices, the 
practice of austerity.

_Appevanāma naṃ imamhā brahmacariyā cāveyyanti bhikkhubhāvā cāveyyaṃ 
samaṇadhammā cāveyyaṃ sīlakkhandhā cāveyyaṃ tapoguṇā cāveyyaṃ._
____

.Illustration
====
guṇā

practice
====

[quote, Vin.3.15]
____
Venerable Sudinna practised these kinds of ascetic practises: dwelling in the 
forest, only accepting food given on almsround, wearing rag-robes, walking on 
uninterrupted house-to-house almsround.

__āyasmā sudinno evarūpe dhutaguṇe samādāya vattati: āraññako hoti 
piṇḍapātiko paṃsukuliko sapadānacāriko._
____

.Illustration
====
guṇe

spiritual quality
====

[quote, Sn.v.663]
____
He who is given to the spiritual quality of greed reviles others with his 
speech.

_Yo lobhaguṇe anuyutto so vacasā paribhāsati aññe._
____

.Illustration
====
guṇa

spiritual quality
====

[quote, Th.v.955]
____
Administrating the community of bhikkhus though being full of despicable 
spiritual qualities.

_Guṇahīnā pi saṅghamhi voharantā._
____

.Illustration
====
guṇesu

spiritual quality
====

[quote, Sn.v.678]
____
In the midst of those who are pure, well behaved, with good spiritual 
qualities, one should constantly guard speech and mind.

_Tasmā suci pesala sādhu guṇesu +
Vācaṃ manaṃ satataṃ parirakkheti._
____

