== Hetu

=== Renderings

- _hetu_: conditionality

- _hetu_: conditionally

- _hetu_: indispensible condition

- _hetu_: cause

- _hetu_: on account of

- _hetu_: due to

- _hetu_: for the sake of

- _taṃ kissa hetu_: for what reason?

- _sahetudhamma_: the conditioned nature of reality

=== Introduction

==== Conditionality not causality

The Buddha's teachings primarily concern conditionality not causality. Hence we 
render _hetu_ as 'cause' only when it means 'reason,' where it is often linked 
to _paccayo_:

[quote, S.4.324]
____
Eight causes and reasons for the ruination of families:

_Aṭṭha kho gāmaṇī hetu aṭṭha paccayā kulānaṃ upaghātāya._
____

[quote, A.2.167]
____
This is the cause and reason for some beings here not realising the Untroubled 
in this lifetime.

_Ayaṃ kho āvuso ānanda hetu ayaṃ paccayo yena midhekacce sattā 
diṭṭheva dhamme na parinibbāyantī ti._
____

[quote, A.4.337]
____
Bhante, what is the cause and reason for the Perfect One being sometimes 
disposed to explain the teaching, and sometimes not?

_Ko nu kho bhante hetu ko paccayo yena appekadā tathāgataṃ dhammadesanā 
paṭibhāti appekadā nappaṭibhātīti._
____

==== Conditionality

The Buddha's teachings primarily concern conditionality not causality. Saying 
that 'Dependent on birth, there arises old-age-and-death (S.2.1) does not mean 
that birth causes old-age-and-death, but that birth is old-age-and-death's 
indispensible condition.

==== The abstract formula of dependent origination

Conditionality is summarised in the abstract formula of dependent origination:

[quote, S.2.70]
____
When there is this, that comes to be. With the arising of this, that arises. 
Without this, that does not come to be. With the ending of this, that ceases.

_iti imasmiṃ sati idaṃ hoti imassuppādā idaṃ uppajjati imasmiṃ asati 
idaṃ na hoti imassa nirodhā idaṃ nirujjhati._
____

=== Illustrations

.Illustration
====
hetu

conditionality; conditionally
====

[quote, A.3.444]
____
Conditionality will be clearly seen by me, as well as conditionally arisen 
phenomena

_Hetuca me sudiṭṭho bhavissati hetusamuppannā ca dhammā._
____

.Illustration
====
hetu

conditionality
====

[quote, M.1.408]
____
Since there is indeed conditionality, one who has the dogmatic view 'There is 
no conditionality' has a wrong view [of reality].

_Santaṃyeva kho pana hetu natthi hetū'tissa diṭṭhi hoti. Sāssa hoti 
micchādiṭṭhi._
____

Comment:

The previous passage says:

[quote, M.1.407]
____
There is an indispensible and necessary condition for the spiritual defilement 
of beings; beings are spiritually defiled due to an indispensible or necessary 
condition

_atthi hetu atthi paccayo sattānaṃ saṅkilesāya sahetu sappaccayā sattā 
saṅkilissanti._
____

.Illustration
====
hetuṃ

indispensible condition
====

[quote, Vin.1.40]
____
Of those phenomena arisen from an indispensible condition, the Perfect One 
speaks of their indispensible condition and of their ending. Such is the 
doctrine of the Great Ascetic.

_Ye dhammā hetuppabhavā tesaṃ hetuṃ tathāgato āha +
Tesañca yo nirodho evaṃvādi mahāsamaṇo ti._
____

.Illustration
====
hetuso

indispensible condition
====

[quote, M.1.70]
____
The Perfect One discerns according to reality the karmic consequence of deeds 
undertaken in the past, future, or present, with the causal basis and 
indispensible condition.

_atītānāgatapaccuppannānaṃ kammasamādānānaṃ ṭhānaso hetuso 
vipākaṃ yathābhūtaṃ pajānāti._
____

Comment:

'Causal basis' means the 'reason' for karmic consequences.

.Illustration
====
hetu

indispensible conditions
====

[quote, A.1.82]
____
Unvirtuous, spiritually unwholesome factors arise with indispensible 
conditions, not without indispensible conditions.

_Sahetukā bhikkhave uppajjanti pāpakā akusalā dhammā no ahetukā. Tasseva 
hetussa pahānā evaṃ te pāpakā akusalā dhammā na honti._
____

Also:

____
... with grounds

_sanimittā bhikkhave uppajjanti pāpakā akusalā dhammā no animittā_
____

____
... with a source

_sanidānā bhikkhave uppajjanti pāpakā akusalā dhammā no anidānā_
____

[quote, A.1.82]
____
... with necessary conditions

_sappaccayā bhikkhave uppajjanti pāpakā akusalā dhammā no appaccayā._
____

.Illustration
====
hetu

indispensible condition
====

[quote, D.2.58]
____
Therefore, this is the indispensible condition, the source, the origin, the 
necessary condition of grasping, namely craving.

_Tasmātihānanda eseva hetu etaṃ nidānaṃ esa samudayo esa paccayo 
upādānassa yadidaṃ taṇhā._
____

.Illustration
====
hetu

indispensible condition
====

____
Which two things are hard to fathom?

_Katame dve dhammā duppaṭivijjhā?_
____

[quote, D.3.273-4]
____
The indispensible and necessary conditions for the spiritual defilement and 
purification of beings.

_Yo ca hetu yo ca paccayo sattānaṃ saṅkilesāya yo ca hetu yo ca paccayo 
sattānaṃ visuddhiyā._
____

.Illustration
====
hetu

indispensible condition
====

[quote, M.3.17]
____
The four great material phenomena are the indispensible and necessary 
conditions by which the aggregate of bodily form is to be discerned._

_Cattāro kho bhikkhu mahābhūtā hetu cattāro mahābhūtā paccayo 
rūpakkhandhassa paññāpanāya._
____

.Illustration
====
hetu

cause
====

____
Eight causes and reasons for the ruination of families:

_Aṭṭha kho gāmaṇī hetu aṭṭha paccayā kulānaṃ upaghātāya_
____

[quote, S.4.324]
____
Families are ruined due to the king, thieves, fire, flooding, things getting 
lost, mismanagement, a squanderer in the family, unlastingness.

_rājato... corato... aggito... udakato vā kulāni upaghātaṃ gacchanti... 
nihitaṃ vā nādhigacchanti... duppayuttā vā kammantaṃ jahanti... 
kulānaṃ vā kulaṅgāro uppajjati yo te bhoge vikirati vidhamati 
viddhaṃseti aniccatāyeva aṭṭhamī ti._
____

.Illustration
====
hetu

cause
====

Beings do not know according to reality that:

1. This perception/ mental image leads to worsening.
+
****
_imā hānabhāgiyā saññā ti yathābhūtaṃ nappajānanti_
****

2. This perception/ mental image leads to stasis.
+
****
_Imā ṭhitibhāgiyā saññā ti yathābhūtaṃ nappajānanti_.
****

3. This perception/ mental image leads to distinction.
+
****
_Imā visesabhāgiyā saññā ti yathābhūtaṃ nappajānanti_
****

4. This perception/ mental image leads to the profound understanding [and 
destruction of the great masses of greed, hatred, and undiscernment of reality].
+
****
_Imā nibbedhabhāgiyā saññā ti yathābhūtaṃ nappajānanti_
****

[quote, A.2.167]
____
This is the cause and reason for some beings here not realising the Untroubled 
in this lifetime.

_Ayaṃ kho āvuso ānanda hetu ayaṃ paccayo yena midhekacce sattā 
diṭṭheva dhamme na parinibbāyantī ti._
____

Comment:

'The profound understanding [and destruction of the great masses of greed, 
hatred, and undiscernment of reality]': _Nibbijjhati_ means 'to pierce,' which 
we call 'to profoundly understand.' At S.5.88 _nibbijjhati_ is linked to 
_padāleti_ (to destroy), and to _lobhakkhandhaṃ dosakkhandhaṃ 
mohakkhandhaṃ._

.Illustration
====
hetu

cause
====

____
Bhante, what is the cause and reason for the Perfect One being sometimes 
disposed to explain the teaching, and sometimes not?"

_Ko nu kho bhante hetu ko paccayo yena appekadā tathāgataṃ dhammadesanā 
paṭibhāti appekadā nappaṭibhātīti_
____

1. "When, Puṇṇiya, a bhikkhu is endowed with faith but does not approach 
him, the Perfect One is not disposed to explain the teaching.
+
****
_Saddho ca puṇṇiya bhikkhu hoti no ca upasaṅkamitā. Neva tāva 
tathāgataṃ dhammadesanā paṭibhāti._
****

2. But when a bhikkhu is endowed with faith and approaches him, the Perfect One 
is disposed to explain the teaching.
+
****
_Yato ca kho puṇṇiya bhikkhu saddho ca hoti upasaṅkamitā ca. Evaṃ 
tathāgataṃ dhammadesanā paṭibhāti_ (A.4.337).
****

.Illustration
====
hetu

on account of
====

[quote, A.2.159]
____
Venerable Sāriputta said that where there is the acquiring of a [particular] 
state of individuality in which one's own intentionality has effect, not 
another person's, there is a passing away of beings from that group on account 
of their own intentionality

_attasañcetanāhetu tesaṃ sattānaṃ tamhā kāyā cuti hoti._
____

.Illustration
====
hetu

on account of
====

____
Ānanda, when there is the body, then on account of bodily intentionality, 
pleasure and pain arise for oneself;_

_Kāye vā hānanda sati kāyasañcetanāhetu uppajjati ajjhattaṃ 
sukhadukkhaṃ_
____

.Illustration
====
hetu

on account of
====

[quote, M.1.87]
____
On account of sensuous pleasures, due to sensuous pleasures, as a consequence 
of sensuous pleasures, simply on account of sensuous pleasures they misconduct 
themselves by way of body, speech, and mind.

_kāmahetu kāmanidānaṃ kāmādhikaraṇaṃ kāmānameva hetu kāyena 
duccaritaṃ caranti vācāya duccaritaṃ caranti manasā duccaritaṃ 
caranti._
____

.Illustration
====
hetu

due to
====

[quote, M.1.285]
____
Householders, it is due to unrighteous conduct, due to unvirtuous conduct that 
some beings here, with the demise of the body at death, are reborn in the plane 
of sub-human existence, in the plane of misery, in the plane of damnation, or 
in hell.

_Adhammacariyā visamacariyā hetu kho gahapatayo evamidhekacce sattā kāyassa 
bhedā parammaraṇā apāyaṃ duggatiṃ vinipātaṃ nirayaṃ upapajjanti._
____

.Illustration
====
hetu

for the sake of
====

[quote, A.1.147]
____
It was not for the sake of robe material that I went forth from the household 
life into the ascetic life, nor almsfood, nor abodes, nor honour and renown.

_na kho panā'haṃ cīvarahetu... piṇḍapātahetu... senāsanahetu... 
itibhavābhavahetu agārasmā anagāriyaṃ pabbajito._
____

.Illustration
====
taṃ kissa hetu

for what reason?
====

[quote, S.5.442]
____
The small beings in the ocean that could not easily be impaled on stakes would 
be even more numerous than this. For what reason? Because of the minuteness of 
their bodily forms.

_Ato bahutarā kho bhikkhave mahāsamudde sukhumakā pāṇā ye na sukarā 
sūlesu āvuṇituṃ. Taṃ kissa hetu: sukhumattā bhikkhave attabhāvassa._
____

.Illustration
====
sahetudhammaṃ

the conditioned nature of reality
====

____
When profound truths become manifest to the vigorous, meditative Brahman,

_Yadā have pātubhavanti dhammā ātāpino jhāyato brāhmaṇassa_
____

[quote, Ud.1]
____
... then all his unsureness [about the significance of the teaching] 
disappears, for he discerns the conditioned nature of reality.

_Athassa kaṅkhā vapayanti sabbā yato pajānāti sahetudhamman ti._
____

== Illustrated Glossary of Pāli Terms

By Varado Bhikkhu

