== Imaṃ kāyaṃ

=== Renderings

- _imaṃ kāyaṃ_: this [wretched human] body

=== Introduction

==== Justifying parentheses

1. We call _imaṃ kāyaṃ_ 'this [wretched human] body.' The parenthesis 
'wretched' is justified because the dictionaries say _ayaṃ_ and _idaṃ_ 
often imply sarcasm or contempt:

- _Imaṃ_ has 'a touch of (often sarcastic) characterisation,' says PED (sv 
_Ayaṃ_).

- DOP (sv _Idaṃ_) says: 'such, like that (often implying contempt).'

2. The parenthesis 'human' is for stylistic purposes. The same idea is seen in 
Pāli, because the suttas sometimes refer to the human body as _mānusaṃ 
dehaṃ_ (S.1.27). Thus we take _imaṃ kāyaṃ_ as standing for _imaṃ 
&#8203;[mānusaṃ] kāyaṃ_.

=== Illustrations

.Illustration
====
imasmiṃ kāye

this [wretched human] body
====

[quote, M.1.186]
____
Now, willingly, let blows from hands affect this [wretched human] body, let 
bows from clods of earth affect it and blows from sticks affect it and blows 
from weapons affect it, for this teaching of the Buddhas is being done.

_Kāmaṃdāni imasmiṃ kāye pāṇisamphassāpi kamantu 
leḍḍusamphassāpi kamantu daṇḍasamphassāpi kamantu satthasamphassāpi 
kamantu karīyati hidaṃ buddhānaṃ sāsanan ti._
____

.Illustration
====
imaṃ kāyaṃ

this [wretched human] body
====

• When this [wretched human] body is bereft of three states -- vitality, 
warmth, and mental consciousness -- it is then discarded and forsaken, left 
lying senseless like a log. +
__☸ Yadā kho āvuso imaṃ kāyaṃ tayo dhammā jahanti āyu usmā ca 
viññāṇaṃ athāyaṃ kāyo ujjhito avakkhitto seti yathā kaṭṭhaṃ 
acetanan__ti (M.1.296).

.Illustration
====
imaṃ kāyaṃ

this [wretched human] body
====

[quote, S.4.40]
____
'Come friends, lift this [wretched human] body of mine onto the bed and carry 
it outside before it is scattered in this very world like a handful of chaff.'

_etha me āvuso imaṃ kāyaṃ mañcakaṃ āropetvā bahiddhā nīharatha 
purā'yaṃ kāyo idheva vikirati seyyathāpi bhusamuṭṭhiti._
____

.Illustration
====
imaṃ kāyaṃ

this [wretched human] body
====

[quote, Thī.v.89]
____
I took delight in ornaments and finery. Afflicted by lust for sensuous 
pleasure, I ministered to this [wretched human] body by bathing it, and 
anointing it [with oil and perfume].

_Vibhūsāmaṇḍanaratā nahāpanucchādanehi va +
Upakāsiṃ imaṃ kāyaṃ kāmarāgena aṭṭitā._
____

.Illustration
====
imaṃ kāyaṃ

this [wretched human] body
====

[quote, S.3.1]
____
'So it is, householder, so it is. This [wretched human] body of yours is 
ailing, enveloped and smothered [in ailments]. If anyone carrying around [such 
a wretched] body were to claim to be healthy even for a moment, that would only 
be folly. '

_Evametaṃ gahapati evametaṃ gahapati. Āturohāyaṃ gahapati kāyo 
aṇḍabhūto pariyonaddho. Yo hi gahapati imaṃ kāyaṃ pariharanto 
muhuttampi ārogyaṃ paṭijāneyya kimaññatra bālyā._
____

.Illustration
====
imaṃ kāyaṃ

this [wretched human] body
====

[quote, Th.v.575]
____
The foolish common men who cherish this [wretched human] body cause the 
terrible cemeteries to grow. They take on renewed states of individual 
existence.

_Yemaṃ kāyaṃ mamāyanti andhabālā puthujjanā +
Vaḍḍhenti kaṭasiṃ ghoraṃ ādiyanti punabbhavaṃ._
____

.Illustration
====
imaṃ kāyaṃ

this [wretched human] body
====

[quote, Th.v.576]
____
Those who abandon [attachment to] this [wretched human] body as if it were a 
dung-smeared snake, having rejected the origin of individual existence will 
realise the Untroubled and be free of perceptually obscuring states.

_Yemaṃ kāyaṃ vivajjenti gūthalittaṃ va pannagaṃ +
Bhavamūlaṃ vamitvāna parinibbissantināsavā ti._
____

.Illustration
====
imasmiṃ kāye

this [wretched human] body
====

• And what, Ānanda, is the perception of the danger [of the body]? In this 
regard, Ānanda, a bhikkhu... reflects that this [wretched human] body is very 
unpleasant and a great danger. Many illnesses arise in it, namely, illnesses of 
the eye, ear, nose... cold, heat, hunger, thirst, faeces and urine. Thus he 
abides contemplating the danger of this [wretched human] body. +
☸ _Katamācānanda ādīnavasaññā? Idhānanda bhikkhu araññagato vā 
rukkhamūlagato vā suññāgāragato vā itipaṭisañcikkhatibahu dukkho kho 
ayaṃ kāyo bahu ādīnavo_. _Iti imasmiṃ kāye vividhā ābādhā 
uppajjanti seyyathīdaṃ cakkhurogo sotarogo ghānarogo... sītaṃ uṇhaṃ 
jighacchā pipāsā uccāro passāvo ti. Iti imasmiṃ kāye ādīnavānupassī 
viharati_ (A.5.110).

.Illustration
====
imasmiṃ kāye

this [wretched human] body
====

[quote, M.1.58]
____
Just as a butcher or his apprentice having killed a cow and cut it into pieces 
were seated with it at a crossroads, the bhikkhu contemplates this very body 
however placed or disposed in terms of material phenomena; likewise a bhikkhu 
contemplates this very body however placed or disposed in terms of material 
phenomena: 'In this [wretched human] body there is the Solidness Phenomenon, 
the Liquidness Phenomenon, the Warmth Phenomenon, and the Gaseousness 
Phenomenon.'

_seyyathāpi bhikkhave dakkho goghātako vā goghātakantevāsī vā gāviṃ 
vadhitvā cātummahāpathe bilaso paṭivibhajitvā nisinno assa evameva kho 
bhikkhave bhikkhu imameva kāyaṃ yathāṭhitaṃ yathāpaṇihitaṃ 
dhātuso paccavekkhati: atthi imasmiṃ kāye paṭhavīdhātu āpodhātu 
tejodhātu vāyodhātū ti._
____

.Illustration
====
imasmiṃ kāye

this [wretched human] body
====

[quote, A.4.386]
____
A 'carbuncle' is a metaphor for this [wretched human] body made of the four 
great material phenomena. It has nine openings, nine orifices. Whatever oozes 
out of them is foul, foul-smelling, and disgusting. Therefore be disillusioned 
with this [wretched human] body.

__'Gaṇḍo ti kho bhikkhave imasseva cātummahābhūtikassa kāyassa 
adhivacanaṃ. Tassa nava vanamukhāni nava abhedanamukhāni. Yaṃ kiñci 
paggharati asuciññeva paggharati duggandhaññeva paggharati 
jegucchiyaññeva paggharati. Tasmātiha bhikkhave imasmiṃ kāye nibbindathā 
ti._
____

.Illustration
====
iminā kāyena

this [wretched human] body
====

[quote, S.5.282-4]
____
But, bhante, does the Blessed One recall ever having gone to the brahmā world 
by means of psychic power, using this [wretched human] body composed of the 
four great material phenomena?"

_Abhijānāti kho pana bhante bhagavā iminā cātummahābhūtikena kāyena 
iddhiyā brahmalokaṃ upasaṅkamitāti._
____

.Illustration
====
kāyamimaṃ

this [wretched human] body
====

[quote, Dh.v.40]
____
Knowing this [wretched human] body is [fragile] like a clay pot, having made 
this mind [powerful] like a city, battle Māra with the weapon of penetrative 
discernment. One should guard the victory. One should be free of attachment.

_Kumbhūpamaṃ kāyamimaṃ viditvā nagarūpamaṃ cittamidaṃ ṭhapetvā +
Yodhetha māraṃ paññāvudhena jitañca rakkhe anivesano siyā._
____

.Illustration
====
ayaṃ kāyo

this [wretched human] body
====

[quote, S.2.64-5]
____
Bhikkhus, this [wretched human] body is not [in reality] yours, nor is it [in 
reality] owned by others. It should be seen as [the consequence of] previous 
karmically consequential conduct, originated, arisen from intentionality, and 
to be necessarily experienced.

_Nāyaṃ bhikkhave kāyo tumhākaṃ nāpi aññesaṃ. purāṇamidaṃ 
bhikkhave kammaṃ a**bhisaṅkhat**aṃ abhisañcetayitaṃ vedaniyaṃ 
daṭṭhabbaṃ._
____

.Illustration
====
ayaṃ kāyo

this [wretched human] body
====

[quote, S.5.64]
____
This [wretched human] body subsists on food, it survives because of food, 
without food it does not survive.

_ayaṃ kāyo āhāraṭṭhitiko āhāraṃ paṭicca tiṭṭhati anāhāro 
no tiṭṭhati._
____

.Illustration
====
ayaṃ kāyo

this [wretched human] body
====

[quote, Dh.v.41]
____
Not long, indeed, till it will rest, this [wretched human] body here, beneath 
the clod, discarded, void of mental consciousness, like a useless block of wood.

_Aciraṃ vatayaṃ kāyo paṭhaviṃ adhisessati +
Chuddho apetaviññāṇo niratthaṃ va kaliṅgaraṃ._
____

.Illustration
====
ayaṃ kāyo

this [wretched human] body
====

• Willingly let this [wretched human] body be broken apart, let the lumps of 
flesh be dissolved, let both my legs drop off at the knee-joint: I will neither 
eat, nor drink, nor leave my dwelling, nor even lie down on my side as long as 
the arrow of craving is unremoved. +
_Kāmaṃ bhijjatuyaṃ kāyo maṃsapesī visīyaruṃ +
Ubho jaṇṇukasandhīhi jaṅghāyo papatantu me +
Nāsissaṃ na pivissāmi vihārā ca na nikkhame +
Napi passaṃ nipātessaṃ taṇhāsalle anūhate_ (Th.v.312-3).

.Illustration
====
kāyaṃ imaṃ

this [wretched human] body
====

[quote, Th.v.1093]
____
When will I dwell alone in the woods, free of fear, seeing [according to 
reality] that this [wretched human] body is unlasting, a seat of punishment and 
illness, ravaged by old age and death? When, oh when, will it be?

_Kadā aniccaṃ vadharoganīḷaṃ kāyaṃ imaṃ maccujarāyupaddutaṃ +
Vipassamāno vītabhayo vihassaṃ eko vane taṃ nu kadā bhavissati._
____

.Illustration
====
imassa kāyassa

this [wretched human] body
====

[quote, M.3.134]
____
Properly reflecting, you should use almsfood not for fun, not for exuberance, 
not for the sake of comeliness and good looks, but just for the maintenance and 
nourishment of this [wretched human] body for restraining its troublesomeness, 
for supporting the religious life.

_Paṭisaṅkhā yoniso āhāraṃ āhāreyyāsi neva davāya na madāya na 
maṇḍanāya na vibhūsanāya yāvadeva imassa kāyassa ṭhitiyā yāpanāya 
vihiṃsūparatiyā brahmacariyānuggahāya._
____

