== Jahāti orapāraṃ

=== Renderings

- _jahāti orapāraṃ_: he sheds the [ties to individual existence in the] low 
plane of existence and the other planes beyond it

=== Introduction

==== The dictionaries: orapāra

The dictionaries (sv _Ora_) render _orapāra_ as follows:

- PED: 'the lower and higher worlds.'

- DOP: 'the nearer and the farther shore.'

We will now explain our support of PED.

==== Pāra and Apāra: then Pāra means nibbāna

Where _pāra_ means the Far Shore (i.e. _nibbāna_), then the Near Shore is 
called _apāra_:

1. going from the Near Shore to the Far Shore
+
****
_apārā pāraṃ gamanāyāti_ (A.5.4).
****

2. He would go from the Near Shore to the Far Shore if he developed the Supreme 
Way.
+
****
_Apārā pāraṃ gaccheyya bhāvetto maggamuttamaṃ_ (Sn.v.1130).
****

When _pāra_ is linked to _apāra_, it always means _nibbāna._ It does not 
mean the far side of something. We can discount the single exception at Ud.90, 
where people wanted to go to the far side of the Ganges: _apārā pāraṃ 
gantukāmā_ (Ud.90). This can be regarded as a misquote because it is 
contradicted by other versions of the same story:

☸ _orā pāraṃ gantukāmā_ (D.2.89).

☸ _orā pāraṃ gantukāmā_ (Vin.1.230).

==== Pāra and Ora: then Pāra does not mean nibbāna

When _pāra_ is paired with _ora_, then _pāra_ means the far side of 
something, or further from the observer than something:

1. Unsatisfied with this side of the ocean, he would desire the other side as 
well.
+
****
_Oraṃ samuddassa atittarūpo pāraṃ samuddassapi patthayetha_ (M.2.72).
****

The same relationship is seen with cognate words:

1. The foolish cowherd makes the cows cross 'without examining the near shore 
(_orimaṃ tīraṃ_) or the far shore (_pārimaṃ tīraṃ_) of the river 
Ganges'
+
****
_asamavekkhitvā gaṅgāya nadiyā orimaṃ tīraṃ asamavekkhitvā 
pārimaṃ tīraṃ_ (M.1.225).
****

2. The village called Setakaṇṇika is in the southern direction. Beyond that 
(_parā_) are border districts, nearer than that (_orato_) are middle 
(districts).
+
****
_dakkhiṇāya disāya setakaṇṇikaṃ nāma nigamo. Tato parā paccantimā 
janapadā orato majjhe_ (Vin.1.197).
****

3. Having taken the robe in one hand, and wiped the robe-rail or robe-cord with 
the other hand, having got the edges away from him (_parato_), and the fold 
towards him (_orato_), the robe should be laid aside.
+
****
_Cīvaraṃ nikkhipantena ekena hatthena cīvaraṃ gahetvā ekena hatthena 
cīvaravaṃsaṃ vā cīvararajjuṃ vā pamajjitvā pārato antaṃ orato 
bhogaṃ katvā cīvaraṃ nikkhipitabbaṃ_ (Vin.2.209).
****

==== Pāraṃ in the Uraga Sutta does not mean nibbāna

Translators of the _Uraga Sutta_ usually say that the bhikkhu 'abandons the 
near and far shore'. For example, Norman says:

[quote, Norman, Sn.v.1]
____
That bhikkhu... leaves this shore and the far shore as a snake leaves its old, 
worn-out skin.

_So bhikkhu jahāti orapāraṃ urago jiṇṇamiva tacaṃ purāṇaṃ._
____

Because 'far shore' implies _nibbāna_, we disagree with this translation for 
two reasons:

1. _nibbāna_ is nowhere else said to be left or abandoned.

2. in combination with _oraṃ, pāraṃ_ means the far side of something, or 
further from the observer than something, which are nowhere in the suttas said 
to be qualities of _nibbāna_.

==== Verse 15: key to the meaning of orapāraṃ

The key to the meaning of _orapāraṃ_ is found in verse 15 which concerns the 
non-returner. The verse says this:

[quote, Sn.v.15]
____
He in whom there is nothing born of suffering which is a cause for returning to 
the low plane of existence (_oraṃ_), that bhikkhu sheds _orapāraṃ_, as a 
snake sheds its old, worn-out skin.

_Yassa darathajā na santi keci oraṃ āgamanāya paccayāse +
So bhikkhu jahāti orapāraṃ urago jiṇṇamiva tacaṃ purāṇaṃ._
____

Here, in _oraṃ's_ first occurrence its meaning is clear: 'the low plane of 
existence.' So let us now discuss the three planes of existence.

==== The three planes of existence

Each universe is comprised of three planes of existence (_dhātu_), which are 
named according to two systems:

System 1)

[quote, D.3.215]
____
the low plane of existence, the middle plane of existence, and the high plane 
of existence

_hīnadhātu majjhimadhātu paṇītadhātu._
____

System 2)

[quote, A.1.224]
____
the sensuous plane of existence, the refined material plane of existence, and 
the immaterial plane of existence

_kāmadhātu... rūpadhātu... arūpadhātu._
____

Once-returners return once to this [low] plane of existence' (_sakideva imaṃ 
lokaṃ āgantvā_, meaning the low plane of existence, _hīnadhātu_) because 
they have not abandoned the five ties to individual existence in the low plane 
of existence (_orambhāgiyāni saṃyojanāni_). Note that we render both 
_hīna_ and _oraṃ_ as 'low.'

Non-returners do not return from 'that world' (_anāvattidhammo tasmā lokā_, 
A.1.245) meaning the two higher planes of existence: the refined material plane 
of existence (_rūpadhātu_) and the immaterial plane of existence 
(_arūpadhātu_), because that is where they are reborn, either in the Pure 
Abodes (M.1.81; A.4.73), or as Brahmās (S.1.149), or as immaterial beings 
(A.2.127).

So _oraṃ_ in the phrase _orambhāgiyāni saṃyojanāni_ stands for 
_hīnadhātu_, i.e. where non-returners do not return to. Therefore in 
_orapāraṃ_, _pāraṃ_ stands for _majjhimadhātu_ and _paṇītadhātu_. If 
shedding _oraṃ_ means abandoning the low plane of existence, then shedding 
_pāraṃ_ means shedding the middle and high planes of existence. This, then, 
gives us the meaning of _jahāti orapāraṃ:_

- He sheds the [ties to individual existence in the] low plane of existence and 
the other planes beyond it.

The commentary explains _orapāra_ in several ways, one of which is: _Oraṃ 
kāmadhātu, pāraṃ rūpārūpadhātu_. This confirms our explanation.

==== Parenthesis: '[ties to individual existence in the]'

Norman translation says:

[quote, Norman, Sn.v.1]
____
That bhikkhu... leaves this shore and the far shore as a snake leaves its old, 
worn-out skin.

_So bhikkhu jahāti orapāraṃ urago jiṇṇamiva tacaṃ purāṇaṃ._
____

But one cannot rationally say one leaves what one does not have, in this case 
the far shore. The commentary to verse 1 says it means _saṃyojanāni_ is 
abandoned:

- _So bhikkhu jahāti orapāranti so evaṃ kodhaṃ vinento bhikkhu yasmā 
kodho tatiyamaggena sabbaso pahīyati, tasmā orapārasaññitāni 
pañcorambhāgiyasaṃyojanāni jahātīti veditabbo_

We parenthesise accordingly.

=== Illustrations

.Illustration
====
jahāti orapāraṃ

he sheds the [ties to individual existence in the] low plane of existence and 
the other planes beyond it
====

[quote, Sn.v.15]
____
He in whom there is nothing born of suffering which is a cause for returning to 
the low plane of existence, that bhikkhu sheds the [ties to individual 
existence in the] low plane of existence and the other planes beyond it, as a 
snake sheds its old, worn-out skin.

_Yassa darathajā na santi keci oraṃ āgamanāya paccayāse +
So bhikkhu jahāti orapāraṃ urago jiṇṇamiva tacaṃ purāṇaṃ._
____

.Illustration
====
jahāti orapāraṃ

he sheds the [ties to individual existence in the] low plane of existence and 
the other planes beyond it
====

[quote, Sn.v.6]
____
He in whom there is no inward anger, and who has transcended [craving for] 
honour and renown, that bhikkhu sheds the [ties to individual existence in the] 
low plane of existence and the other planes beyond it, as a snake sheds its 
old, worn-out skin.

_Yassantarato na santi kopā itibhavābhavatañca vītivatto_ +
_So bhikkhu jahāti orapāraṃ urago jiṇṇamiva tacaṃ purāṇaṃ._
____

