== Jhāyati; Jhāna

=== Renderings

- _jhāyati_: to meditate

- _jhāyati_: to practise

- _jhāyati_: to apply oneself (to a practice)

- _jhāyati_: to mope

- _jhāyati_: to burn

- _jhāna_: meditation

- _jhāna_: jhāna

=== Introduction

==== Meditation and burning: different roots

_Jhāyati_ is two words, meditation and burning. These are from different roots 
and cannot be used to explain each other.

==== Jhāna 'never means vaguely meditation': untrue

PED concludes that _jhāna_ 'never means vaguely meditation. It is the 
technical term for a special religious experience, reached in a certain order 
of mental states. It was originally divided into four such states. These may be 
summarized [as the four jhānas].' We will show in the illustrations that this 
statement is untrue.

=== Illustrations

.Illustration
====
jhāyino

meditate
====

____
A consideration came to the ascetic, the bhikkhu Pārāpariya, while he was 
seated alone, meditating in seclusion.

_Samaṇassa ahu cintā pārāpariyassa bhikkhuno +
Ekakassa nisinnassa pavivittassa jhāyino._
____

____
&#8203;[He asked himself this:] '[By means of] what training, what practice, what 
conduct, would a man fulfil his duty to himself, and not do any harm?

_Kimānupubbaṃ puriso kiṃ vataṃ kiṃ samācāraṃ +
Attano kiccakirissa na ca kiñci viheṭhaye_
____

____
&#8203;[He reflected thus:] 'The sense faculties of men are for their welfare or harm. 
Unsupervised [by mindfulness] they are for their harm; supervised [by 
mindfulness] they are for their welfare.

_Indriyāni manussānaṃ hitāya ahitāya ca +
Arakkhitāni ahitāya rakkhitāni hitāya ca._
____

[quote, Th.v.726-8]
____
'By supervising and keeping watch over one's sense faculties, one would fulfil 
one's duty to oneself and not do any harm.

_Indriyāneva sārakkhaṃ indriyāni ca gopayaṃ +
Attano kiccakārīssa na ca kiñci viheṭhaye._
____

.Illustration
====
jhāyetha

meditate
====

____
The wise man intent on meditation would be delighted in the woods.

_Sa jhānapasuto dhīro vanante ramito siyā_
____

[quote, Sn.v.709]
____
He would meditate at the root of a tree, being completely content within 
himself.

_Jhāyetha rukkhamūlasmiṃ attānamabhitosayaṃ._
____

.Illustration
====
jhāyati

meditate
====

[quote, Thī.v.362]
____
Having attained to the Imperturbable she meditates at the root of a tree.

_Anejaṃ upasampajja rukkhamūlamhi jhāyati._
____

.Illustration
====
jhāyeyya

meditate
====

[quote, Th.v.37]
____
They go to different countries, wandering unrestrained. If they lose their 
inward collectedness, what good will this international travelling do? 
Therefore one should eliminate [such] harmful conduct. One should meditate 
unaccompanied.

_Tasmā vineyya sārambhaṃ jhāyeyya apurakkhato ti._
____

.Illustration
====
jhāyatha

meditate
====

[quote, M.1.46]
____
Meditate, Cunda! Do not be negligently applied [to the practice] lest you 
regret it later!

_Jhāyatha cunda mā pamādattha. Mā pacchā vippaṭisārino ahuvattha._
____

.Illustration
====
jhāyasi

meditate
====

[quote, S.1.180]
____
With a motionless body, steady, lovely, how beautifully you meditate, bhikkhu!

_aniñjamānena ṭhitena vaggunā sucārurūpaṃ vata bhikkhu jhāyasi._
____

.Illustration
====
jhānaṃ jhāyati

practise meditation
====

[quote, D.2.237]
____
He who abides in solitary retreat for the four months of the Rains, practising 
the meditation on [unlimited, all-encompassing] compassion, sees Brahmā.

_yo vassike cattāro māse paṭisallīyati karuṇaṃ jhānaṃ jhāyati so 
brahmānaṃ passati._
____

.Illustration
====
jhānaṃ jhāyeyyan

practise meditation
====

[quote, M.1.243]
____
How about if I practised the breathingless meditation? So I stopped the 
in-breaths and out-breaths through my nose and mouth.

_yannūnāhaṃ appāṇakaṃ jhānaṃ jhāyeyyan ti._
____

.Illustration
====
jhāyantaṃ

applying myself
====

[quote, Sn.v.425-6]
____
While I was nearby the Nerañjara River, resolutely applied to inward striving, 
applying myself with all my strength to the attainment of safety from the 
danger of bondage [to individual existence].

_Taṃ maṃ padhānapahitattaṃ nadiṃ nerañjaraṃ pati +
Viparakkamma jhāyantaṃ yogakkhemassa pattiyā._
____

.Illustration
====
jhāyiṃ

apply himself; jhāyī, meditating
====

____
-- 'How should he apply himself so sensuous mental images are kept at bay and 
fail to grip him?'

_Kathaṃ jhāyiṃ bahulaṃ kāmasaññā paribāhirā honti aladdha yo tan 
ti_
____

(The Blessed One:)

____
-- 'Tranquil in body, with his mind liberated [from perceptually obscuring 
states],

_Passaddhakāyo suvimuttacitto_
____

____
Free of karmically consequential conduct, mindful, free of worldliness,

_asaṅkhārāno satimā anoko_
____

____
Having understood the teaching, meditating thought-free,

_Aññāya dhammaṃ avitakkajhāyī_
____

[quote, S.1.126]
____
He does not shake, or drift, or stiffen.

_na kuppati na sarati na thīno._
____

.Illustration
====
jhāyasi

mope; jhāyami, meditate
====

____
&#8203;[Māra:] +
-- 'Is it because you are overcome by grief that you mope in the woods?'

_Sokāvatiṇṇo nu vanamhi jhāyasi_
____

[quote, S.1.122]
____
&#8203;[The Buddha:] +
-- 'Having extirpated the origin of grief entirely, free of evil deeds, I 
meditate free of grief.'

_Sokassa mūlaṃ palikhāya sabbaṃ anāgu jhāyāmi asocamāno._
____

.Illustration
====
jhāyanti

mope
====

[quote, Dh.v.155]
____
Those who have neither lived the religious life nor, in their youth, 
accumulated savings, mope [in their declining years] like old herons beside a 
lake without fish.

_Acaritvā brahmacariyaṃ aladdhā yobbane dhanaṃ +
Jiṇṇakoñcā va jhāyanti khīṇamacche va pallale._
____

.Illustration
====
jhāyati

mope
====

____
As the carter who abandoned the highway, a road with an even surface, and 
entered upon a rugged bypath, mopes [mournfully] indeed with a broken axle

_Yathā sākaṭiko patthaṃ samaṃ hitvā mahāpathaṃ +
Visamaṃ maggamāruyha akkhacchinno va jhāyati._
____

[quote, S.1.57]
____
So the fool, having left the teaching to follow a way opposed to the teaching, 
mopes like [the carter] with a broken axle when he falls into the mouth of 
Death.

_Evaṃ dhammā apakkamma adhammamanuvattiya +
Mando maccumukhaṃ patto akkhacchinno va jhāyatī ti._
____

.Illustration
====
jhāyati

mope
====

[quote, A.5.323]
____
The unbroken colt, Sandha, when tied up at the feeding trough mopes 'Fodder! 
Fodder!' For what reason? Because it never occurs to him 'I wonder what task 
the trainer will set me today? What can I do for him in return?

_Assakhaluṅko hi sandha doṇiyā baddho yavasaṃ yavasanti jhāyati._
____

.Illustration
====
jhāyanti

mope
====

____
These shaven-headed ascetics who claim to be meditators, with shoulders 
drooping, heads down as if drugged, they mope, brood, ruminate, and cogitate.

_ime pana muṇḍakā samaṇakā ibbhā kiṇhā bandhupādāpaccā 
jhāyinosmā jhāyinosmā ti pattakkhandhā adhomukhā madhurakajātā 
jhāyanti pajjhāyanti nijjhāyanti apajjhāyanti._
____

[quote, M.1.334]
____
Just as an owl on a branch waiting for a mouse mopes, broods, ruminates, and 
cogitates.

_Seyyathā pi nāma ulūko rukkhasākhāya mūsikaṃ magayamāno jhāyati 
pajjhāyati nijjhāyati apajjhāyati._
____

.Illustration
====
jhāno

meditation
====

Venerable Revata said the bhikkhu who would illuminate the Gosinga Sāla-tree 
Grove would be one who:

____
takes pleasure and delight in solitary retreat

_paṭisallāṇārāmo hoti paṭisallāṇarato_
____

____
is given to inward calm

_ajjhattaṃ cetosamathamanuyutto_
____

____
does not neglect meditation

_anirākatajjhāno_
____

• possesses insightfulness +
☸ vipassanāya samannāgato

[quote, M.1.213]
____
is devoted to solitary abodes

_brūhetā suññāgārānaṃ._
____

.Illustration
====
jhāna

meditation
====

[quote, M.3.13]
____
That the Bamboo Grove is delightful, quiet, undisturbed by voices, with a quiet 
atmosphere, remote from people, suitable for solitary retreat, is because of 
the Venerables who meditate there and are given to meditation.

_yathā taṃ bhavantehi jhāyīhi jhānasīlīhi._
____

.Illustration
====
jhānaṃ

meditation; jhānaṃ, jhāna
====

____
What type of meditation did the Blessed One not praise?

_Kathaṃrūpañca brāhmaṇa so bhagavā jhānaṃ na vaṇṇesi._
____

____
In this regard, brahman, some person abides with a mind absorbed in and 
overcome by attachment to sensuous pleasure and he does not discern according 
to reality the deliverance from arisen attachment to sensuous pleasure.

_Idha brāhmaṇa ekacco kāmarāgapariyuṭṭhitena cetasā viharati 
kāmarāgaparetena. Uppannassa ca kāmarāgassa nissaraṇaṃ yathābhūtaṃ 
nappajānāti._
____

____
While he thus cultivates attachment to sensuous pleasure within, he mopes, 
broods, ruminates, and cogitates.

_So kāmarāgaṃyeva antaraṃ karitvā jhāyati pajjhāyati nijjhāyati 
apajjhāyati._
____

And likewise for the other five hindrances:

_• Vyāpādapariyuṭṭhitena cetasā viharati_

_• Vicikicchāpariyuṭṭhitena cetasā viharati_

____
And what type of meditation did the Blessed One praise?

_Kathaṃ rūpañca brāhmaṇa so bhagavā jhānaṃ vaṇṇesi._
____

- First jhāna,

- Second jhāna,

- Third jhāna,

- Fourth jhāna.

_• Idha brāhmaṇa bhikkhu vivicceva kāmehi vivicca akusalehi dhammehi 
savitakkaṃ savicāraṃ vivekajaṃ pītisukhaṃ paṭhamaṃ jhānaṃ... 
catutthaṃ jhānaṃ upasampajja viharati_ (M.3.13-14).

.Illustration
====
jhānaṃ

jhāna
====

____
There is no jhāna for one without penetrative discernment. There is no 
penetrative discernment for one who does not meditate.

_Natthi jhānaṃ apaññassa paññā natthi ajjhāyato_
____

[quote, Dh.v.372]
____
Whoever has jhāna together with penetrative discernment is right in the 
presence of the Untroubled.

_Yamhi jhānañca paññā ca sa ve nibbānasantike._
____

.Illustration
====
jhānāni

jhāna
====

[quote, A.3.354]
____
Abandoning the five hindrances, ever energetic, he enters the jhānas. His mind 
is concentrated. He is aware and mindful.

_Pañcanīvaraṇe hitvā niccaṃ āraddhaviriyo +
Jhānāni upasampajja ekodi nipako sato._
____

.Illustration
====
jhāyantī

burning
====

[quote, D.1.50]
____
There are lights burning in the round pavilion

_Ete maṇḍalamāḷe dīpā jhāyantī ti._
____

Comment:

Meditation and burning are both _jhāyati_ but come from different roots and 
cannot be used to explain each other.

.Illustration
====
jhāyamānassa

burnt
====

[quote, D.2.164]
____
When the Blessed One's body had been burnt

_Jhāyamānassa kho pana bhagavato sarīrassa._
____

.Illustration
====
jhāyamānassa

burnt
====

[quote, D.2.164]
____
Just as when butter or oil is burnt.

_Seyyathā pi nāma sa pi'ssa vā telassa vā jhāyamānassa._
____

