== Jāla; Jālin

=== Renderings

- _jāla_: web

- _jāla_: net

- _jāla_: entanglement

- _jālin_: entangling

=== Introduction

==== PED's terms for Jāla and Jālin

PED (sv _Jāla_) says: 'a net; netting, entanglement (lit. or fig.): snare, 
deception.'

PED (sv _Jālin_) says:

\a) adj: "having a net," ensnaring, deceptive

\b) noun: a fisherman, ensnarer, witch

==== Taṇhā: entanglement

We call _taṇhā_ an entanglement not a net for two reasons:

1. _Taṇhā_ is a synonym of _saṅghāṭa_, which is 'a weft, tangle, mass,' 
says PED, and means literally 'binding together.'
+
[quote, M.1.271]
____
The bhikkhu Sāti, son of a fisherman, is caught in the vast entanglement of 
craving, in the tangle of craving.

_Sātiṃ pana bhikkhuṃ kevaṭṭaputtaṃ mahātaṇhājāla taṇhā 
saṅghāṭa paṭimukkan ti._
____

2. Because _taṇhā_ is the reason that this world is 'tangled up like string, 
a knotted ball of thread, a twisted mass of reeds and rushes':
+
[quote, A.2.212-3]
____
I will explain to you the craving that entangles, that floats along, that is 
far-flung, that is sticky, by which this world [of beings] is blanketed, 
smothered, tangled up like string, a knotted ball of thread, a twisted mass of 
reeds and rushes.

_Taṇhaṃ vo bhikkhave desissāmi jāliniṃ saritaṃ visaṭaṃ 
visattikaṃ yāya ayaṃ loko uddhasto pariyonaddho tantākulakajāto 
gulāguṇḍikajāto muñjababbajabhūto._
____

==== Venerable Surādha's 'entanglement'

Venerable Surādha said:

[quote, Th.v.135]
____
Birth is destroyed by me. The Conqueror's training system has been fulfilled. 
What is considered 'the entanglement' has been abandoned [by me]. The conduit 
to renewed states of individual existence has been abolished.

_Khīṇā hi mayhaṃ jāti vusitaṃ jinasāsanaṃ +
Pahīno jālasaṅkhāto bhavanetti samūhatā._
____

_Jālasaṅkhāto_ ("considered 'the entanglement'") could be pointing to 
_mohajālaṃ_ (S.3.83), _maccuno jālaṃ_ (Sn.v.357), or _taṇhājālo_ 
(Th.v.308). But the association with _bhavanetti_ means _taṇhājālo_ is 
likely meant, because _taṇhā_ is part of _bhavanetti_:

[quote, S.3.191]
____
The fondness, attachment, spiritually fettering delight, craving, clinging, 
grasping, obstinate adherence, stubborn attachment, and identification in 
regards to bodily form: this is called the conduit to renewed states of 
individual existence.

_rūpe kho rādha yo chando yo rāgo yā nandi yā taṇhā ye upayūpādānā 
cetaso adhiṭṭhānābhinivesānusayā ayaṃ vuccati bhavanetti._
____

Although _taṇhā_ is usually 'destroyed' or 'obliterated,' it is also said to 
be 'abandoned':

1. _Yā taṇhā ye upayupādānā cetaso adhiṭṭhānābhinivesānusayā te 
tathāgatassa pahīnā_ (S.3.10).

2. _Taṇhā hissa dutiyā sāssa pahīnā_ (S.4.37).

=== Illustrations

.Illustration
====
jālaṃ

web
====

[quote, Dh.v.347]
____
A spider on its self-spun web

_sayaṃkataṃ makkaṭakova jālaṃ._
____

.Illustration
====
jālaṃ

net
====

[quote, Sn.v.357]
____
He destroyed the strong, extensive net of deceitful death.

_Acchidā maccuno jālaṃ tataṃ māyāvino daḷhaṃ._
____

.Illustration
====
jālaṃ

net
====

[quote, Sn.v.62]
____
Like a fish breaching a net in the water

_jālambhetvā salilambucārī._
____

.Illustration
====
jālaṃ

net
====

[quote, Sn.v.71]
____
The wind is not bound by a net

_vāto va jālamhi asajjamāno._
____

.Illustration
====
jālaṃ

net
====

[quote, Dh.v.174]
____
Like birds escaped from a net

_Sakunto jālamutto va._
____

.Illustration
====
jālaṃ

entanglement
====

[quote, S.3.83]
____
The entanglement of undiscernment of reality is obliterated

_mohajālaṃ padālitaṃ._
____

.Illustration
====
jālaṃ

entanglement
====

[quote, Dh.v.251]
____
There is no entanglement like undiscernment of reality

_Natthi mohasamaṃ jālaṃ._
____

.Illustration
====
jālo

entanglement
====

[quote, Th.v.308]
____
The entanglement of craving has been done away with.

_taṇhājālo samūhato._
____

.Illustration
====
jāla

entanglement
====

• [Most folk] are blinded by sensuous yearning, wrapped in the entanglement 
&#8203;[of craving], enfolded in the cloak of craving. +
_Kāmandhā jālapacchannā taṇhāchadanachāditā_ (Th.v.297).

.Illustration
====
jāliniṃ

entangling
====

[quote, M.3.70]
____
Usabha destroyed the entangling origin of suffering.

_Usabhacchidā jāliniṃ dukkhamūlaṃ._
____

.Illustration
====
jālinī

entangling
====

[quote, S.1.107]
____
He for whom entangling and sticky craving no more exists to lead him anywhere.

_Yassa jālinī visattikā taṇhā natthi kuhiñci netave._
____

