== Jāneyyāti

=== Renderings

- _jāneyyāti_: could gauge

- _jāneyyāti_: should understand

- _jāneyyāti_: could comprehend

- _jāneyyāti_: would recognise

- _jāneyyāti_: should consider

- _jāneyyāti_: might consider

- _jāneyyāti_: could know

- _jāneyyāti_: knew

- _jāneyyāti_: would know

- _jāneyyāti_: might know

=== Introduction

==== Kālāma Sutta: yadā attanāva jāneyyātha

The _Kālāma Sutta_'s notoriety as the 'freethinker's kit to truth' is partly 
due to a frequent mistranslation of the prominent phrase in the sutta by 
ignoring the optative tense, thus:

[quote, A.1.190]
____
When you know for yourselves: 'These things are unwholesome... then you should 
abandon them.

_Yadā tumhe kālāmā attanāva jāneyyātha ime dhammā akusalā... atha 
tumhe kālāmā pajaheyyātha._
____

This flawed instruction would only be valid if the Buddha trusted an untrained 
disciple to know for himself what is unwholesome and wholesome. But if he could 
be trusted in this way, it would negate the rationale for a religious training 
system. We propose that the excerpt is more accurately and more rationally 
translated with 'should consider.' The context obliges one to translate _yadā_ 
as 'if' not 'when':

[quote, A.1.190]
____
Kālāmas, if you yourselves should consider: "These teachings are 
unwholesome... you should abandon them.

_Yadā tumhe kālāmā attanāva jāneyyātha ime dhammā akusalā... atha 
tumhe kālāmā pajaheyyātha._
____

==== Saṅkhitta Sutta: jāneyyāsi

In the _Saṅkhitta Sutta jāneyyāsi_ is a synonym of _dhāreyyāsi_, both 
words in the optative tense, and both with the meaning 'to consider,' not 'to 
know'.

[quote, A.4.280]
____
Gotamī, things of which you might consider: 'These things lead to 
non-attachment [to originated phenomena], not to attachment to originated 
phenomena... you can definitely consider this is [in accordance with] the 
teaching

_ye ca kho tvaṃ gotami dhamme jāneyyāsi ime dhammā virāgāya 
saṃvattanti no sarāgāya... ekaṃsena gotami dhāreyyāsi eso dhammo._
____

=== Illustrations

.Illustration
====
jāneyyāti

could gauge
====

[quote, M.1.175]
____
Who am I, sir, to gauge the ascetic Gotama's accomplishment in wisdom? Surely, 
he would be his equal who could gauge the ascetic Gotama's accomplishment in 
wisdom.

_Ko cāhaṃ bho ko ca samaṇassa gotamassa paññāveyyattiyaṃ jānissāmi. 
Sopi nūnassa tādisova yo samaṇassa gotamassa paññāveyyattiyaṃ 
jāneyyāti._
____

.Illustration
====
jāneyyāsi

should understand
====

[quote, M.2.158]
____
Should you not understand the meaning of what is said by me, you should ask me 
further about it: 'How is this, Master Udena? What is the meaning of this?'

_yassa ca pana me bhāsitassa attha na jāneyyāsi mamaṃyeva tattha uttariṃ 
paṭipuccheyyāsi: idaṃ bho udena kathaṃ imassa kvattho ti._
____

.Illustration
====
jāneyyāsi

could comprehend
====

[quote, M.2.210]
____
My dear and noble friend, if you could comprehend the Blessed One's virtue and 
knowledge [of things according to reality], you would never think that he 
should be abused and reviled.

_Sace tvaṃ tāta bhadramukha tassa bhagavato sīlapaññāṇaṃ jāneyyāsi 
na tvaṃ tāta bhadramukha taṃ bhagavantaṃ akkositabbaṃ 
paribhāsitabbaṃ maññeyyāsī ti._
____

.Illustration
====
jāneyyāsi

would recognise
====

[quote, M.3.238]
____
But, bhikkhu, have you ever seen that Blessed One? And if you saw him, would 
you recognise him?

_Diṭṭhapubbo pana te bhikkhu so bhagavā. Disvā ca pana jāneyyāsī'ti._
____

.Illustration
====
jāneyyāsi

should consider
====

[quote, M.1.415]
____
If, on reflection, you should consider that this act of body which I wish to do 
would lead my own harm, to the harm of others, or to the harm of both, that it 
is spiritually unwholesome, has an unpleasant result, and unpleasant karmic 
consequences, as far as possible you should avoid this type of bodily act.

_Sace tvaṃ rāhula paccavekkhamāno evaṃ jāneyyāsi: yaṃ kho ahaṃ 
idaṃ kāyena kammaṃ kattukāmo idamme kāyakammaṃ attavyābādhāyapi 
saṃvatteyya paravyābādhāyapi saṃvatteyya ubhayavyābādhāyapi 
saṃvatteyya akusalaṃ idaṃ kāyakammaṃ dukkhudrayaṃ dukkhavipākanti. 
Evarūpaṃ te rāhula kāyena kammaṃ sasakkaṃ na karaṇīyaṃ._
____

.Illustration
====
jāneyyātha

should consider
====

____
Kālāmas, if you yourselves should consider:

_Yadā tumhe kālāmā attanāva jāneyyātha_
____

____
"These teachings are unwholesome;

_ime dhammā akusalā_
____

____
these teachings are blameworthy;

_ime dhammā sāvajjā_
____

____
these teachings are denounced by the wise;

_ime dhammā viññugarahitā_
____

____
when followed and taken up

_ime dhammā samattā samādinnā_
____

____
these teachings lead to harm and suffering,"

_ahitāya dukkhāya saṃvattantīti_
____

[quote, A.1.190]
____
you should abandon them.

_atha tumhe kālāmā pajaheyyātha._
____

.Illustration
====
jāneyyāsi

might consider
====

____
Gotamī, things of which you might consider

_ye ca kho tvaṃ gotami dhamme jāneyyāsi_
____

____
These things lead to non-attachment [to originated phenomena], not to 
attachment to originated phenomena

_ime dhammā virāgāya saṃvattanti no sarāgāya_
____

____
lead to emancipation [from individual existence], not bondage [to individual 
existence]

_visaṃyogāya saṃvattanti no saṃyogāya_
____

____
lead to a dwindling away of the five grasped aggregates, not to a proliferation 
of the five grasped aggregates

_apacayāya saṃvattanti no ācayāya_
____

____
lead to fewness of needs, not abundance of needs

_appicchatāya saṃvattanti no mahicchatāya_
____

____
lead to contentment, not to discontentment

_santuṭṭhiyā saṃvattanti no asantuṭṭhiyā_
____

____
lead to physical seclusion, not to gregariousness

_pavivekāya saṃvattanti no saṅgaṇikāya_
____

____
lead to right effort, not to indolence

_viriyārambhāya saṃvattanti no kosajjāya_
____

____
lead to being easy to support, not to being difficult to support

_subharatāya saṃvattanti no dubbharatāyā_
____

____
You can definitely consider

_ekaṃsena gotami dhāreyyāsi_
____

____
this is [in accordance with] the teaching

_eso dhammo_
____

____
this is [in accordance with] the discipline

_eso vinayo_
____

[quote, A.4.280]
____
this is [in accordance with] the Teacher's training system

_etaṃ satthusāsanan ti._
____

.Illustration
====
jāneyyaṃ

could know
====

[quote, M.1.323]
____
Is there any absorption unabandoned in myself that might so preoccupy my mind 
that I could not know or see things according to reality?

_atthi nu kho me taṃ pariyuṭṭhānaṃ ajjhattaṃ appahīnaṃ yenāhaṃ 
pariyuṭṭhānena pariyuṭṭhitacitto yathābhūtaṃ na jāneyyaṃ na 
passeyyanti._
____

.Illustration
====
jāneyyātha

knew
====

[quote, M.2.215]
____
Nigaṇṭhas, friends, if you knew that you existed in the past, and that you 
did not not-exist... that being so, then it would be fitting for the venerable 
Nigaṇṭhas to declare... all suffering will be exhausted.

_Sace tumbhe āvuso nigaṇṭhā jāneyyātha ahuvamheva mayaṃ pubbe na 
nāhuvamhā ti. evaṃ sante āyasmantānaṃ nigaṇṭhānaṃ kallamassa 
veyyākaraṇāya... sabbaṃ dukkhaṃ nijjiṇṇaṃ bhavissatī ti._
____

.Illustration
====
jāneyyāsi

would know
====

[quote, M.1.486-7]
____
If a fire was burning in front of you, would you know this fire was burning in 
front of you?

_sace te purato aggi jaleyya jāneyyāsi tvaṃ ayaṃ me purato aggi 
jalatīti?._
____

.Illustration
====
jāneyyāsi

might know
====

[quote, M.1.510]
____
Māgandiya, you do not have noble vision by which you might know [spiritual] 
health and see the Untroubled.

_Taṃ hi te māgandiya ariyaṃ cakkhuṃ natthi yena tvaṃ ariyena cakkhunā 
ārogyaṃ jāneyyāsi nibbānaṃ passeyyāsī ti._
____

