== Kappa

=== Renderings

- _kappa_: one hundred years

- _kappa_: a universal cycle

- _kappa_: the period of a universal cycle

- _saṃvaṭṭavivaṭṭakappa_: the period of a universal cycle

=== Introduction

==== The period of a universal cycle

The period of a universal cycle (_kappa_) is long (_dīgho kho bhikkhu kappo_ 
S.2.181). If a square city had sides 10 kilometres long, and walls 10 
kilometres high, and was filled with mustard seeds, and a man removed one seed 
every hundred years, he would have removed all the seeds, but the universal 
cycle would still be unfinished (S.2.182).

The maths is easily totted. If a mustard seed is a cubic millimetre, then the 
seeds would be emptied in 10,000 million million years.

==== Living for a kappa

But perplexingly, the Buddha said that by developing the four paths to psychic 
power (_cattāro iddhipādā_), if one wished one could live for a _kappa_ or 
slightly more than a _kappa_ (_kappaṃ vā tiṭṭheyya kappāvasesaṃ vā_ 
S.5.259). He said he could do the same himself (D.2.103). But is this the same 
_kappa_? Could an arahant live for billions of years?

==== The problem of co-existing Buddhas

Some, amazingly, say yes, he can. But there are problems with this. Firstly, 
there can never simultaneously be two Perfectly Enlightened Buddhas in the 
world (_yaṃ ekissā lokadhātuyā dve arahanto sammāsambuddho apubbaṃ 
acarimaṃ uppajjeyyuṃ netaṃ ṭhānaṃ vijjatī ti_, M.3.65). And if 
these Perfectly Enlightened Buddhas lived for the period of a universal cycle, 
their lives would overlap, which would break this law. The births of recent 
Buddhas are as follows:

- Buddha Vipassī: 91 kappas ago

- Buddha Sikhī and Buddha Vessabhū: 31 kappas ago

- Buddha Kakusandha, Buddha Konāgamana, Buddha Kassapa and Buddha Gotama arose 
in this present 'fortunate kappa' (_bhaddakappe_), and Buddha Metteyya is 
expected here, too (D.2.2; BDPPN).

Thus, with up to five Perfectly Enlightened Buddhas in one _kappa_, with each 
Buddha capable of living one _kappa_, but unable to co-exist with other 
Perfectly Enlightened Buddhas, it would only be possible if _kappa_ had more 
than one meaning, with one _kappa_ being much shorter, at most a fifth of the 
other.

==== Venerable MahāKassapa: less than 220 years old

In more recent times, consider Venerable MahāKassapa. He was 120 years old at 
the First Council (BDPPN), and some even claim he is still alive today, 
dwelling in the Kukkutagiri Mountains, wrapt in samādhi, awaiting the arrival 
of Metteyya Buddha (BDPPN). According to this he is therefore now approximately 
2,600 years old. But at the Second Council, 100 years after the First Council, 
the oldest bhikkhu on earth (_paṭhavyā saṅghatthero_, Vin.2.303) was 
Venerable Sabbakāma. Therefore Kassapa must have passed away before his 
220^th^ birthday. But 220 is too generous, because by the laws of normal 
distribution, Sabbakāma must have been marking the end of the bell curve. And 
as, at the Second Council, he had been in robes for 120 years, and if we can 
assume he ordained at aged 20 after leaving his wife (Th.v.453), then it would 
seem that the absolute end of the bell curve would not be many hours or minutes 
beyond 140, and that 140 is therefore as old as a bhikkhu can possibly get.

==== Kappa: length is not fixed

The _Mahāpadāna Sutta_ (D.2.3) says human lifespan (_āyuppamāṇaṃ_) has 
varied considerably in the times of previous Perfectly Enlightened Buddhas, as 
follows:

[quote, D.2.53]
____
Buddha Vipassī: 80,000 years.

_asīti vassasahassāni āyuppamāṇaṃ ahosi_
____

- Buddha Sikhī: 70,000 years

- Buddha Vessabhū: 60,000 years

- Buddha Kakusandhu: 40,000 years

- Buddha Konāgamana: 30,000 years

- Buddha Kassapa: 20,000 years

- Buddha Gotama: 100 years.

The _Mahāpadāna Sutta_ (D.2.11) gives further details of Buddha Vipassī:

____
He was born of the _khattiya_ race in a _khattiya_ family

_Vipassī bhikkhave bhagavā arahaṃ sammāsambuddho khattiyo jātiyā ahosi 
khattiyakule udapādi_
____

____
He lived for 80,000 years

_Vipassissa bhikkhave bhagavato arahato sammāsambuddhassa 
asītivassasahassāni āyuppamāṇaṃ ahosi_
____

Thus Buddha Vipassī lived for the lifespan of his era. And because his own 
lifespan and the human lifespan correspond, and because Buddhas can live for a 
_kappa_, it suggests that _kappa_ means the human lifespan, and that all the 
figures for human lifespans given in the list above can be read as _kappas_. So 
the length of this kind of _kappa_ diminishes over time. Therefore _kappa_ in 
our present era means 'a century'.

==== Universal cycle: four incalculable phases

Now we will examine the other meanings of _kappa_: 'universal cycle' and 
'period of a universal cycle.' We have already explained the timespan of the 
universal cycle. These cycles have four incalculable phases (_cattāri kappassa 
asaṅkheyyānī_):

1. a period when the universal cycle is in its contracting phase
+
****
_yadā kappo saṃvaṭṭati_
****

2. a period when the universal cycle is in its stationary contracted phase
+
****
_yadā kappo saṃvaṭṭo tiṭṭhati_
****

3. a period when the universal cycle is in its expanding phase
+
****
_yadā kappo vivaṭṭati_
****

4. a period when the universal cycle is in its stationary expanded phase
+
****
_yadā kappo vivaṭṭo tiṭṭhati_ (A.2.142).
****

These cycles of expansion and contraction affect the heavenly realms, too, up 
to and including the world of Brahmā (D.1.15). With the contraction phase, the 
world of Brahmā disappears, and residents there must move temporarily into the 
Ābhassarā world.

==== Universal cycles: incalculable number of sand grains

How many of these universal cycles have there ever been? There have been so 
many, that the Buddha likened them to the numbers of sand grains between 'the 
point where the river Ganges originates and the point where it enters the great 
ocean' (S.2.183-4). And if we remember that each sand grain represents billions 
of centuries, that is a very long time indeed.

==== Recalling previous lives

When ascetics and Brahmanists recall previous lives, the _Brahmajāla Sutta_ 
says they fall into three groups:

____
those who remember up to several hundred thousand lifetimes

_anekāni pi jātisatasahassāni_
____

____
those who recall [past lives in the last] 10 universal cycles

_dasa pi saṃvaṭṭavivaṭṭāni_
____

____
those who recall [past lives in the last] 40 universal cycles

_cattārīsampi saṃvaṭṭavivaṭṭāni_
____

These feats of memory are extraordinary, but nothing compared to Venerable 
Sobhita, called the 'chief of disciples who could recall past lives' (A.1.25). 
In the course of one night he was able to recall [past lives in the last] 500 
universal cycles (_pañcakappasatānāhaṃ ekarattiṃ anussarinti_, 
Th.v.165-6). Anuruddha could remember further, but may have needed more nights:

[quote, S.5.303]
____
It is because I have developed and cultivated these four bases of mindfulness 
that I recall [past lives in the last] 1,000 universal cycles.

_Imesañca panāhaṃ āvuso catunnaṃ satipaṭṭhānānaṃ bhāvitattā 
bahulīkatattā kappasahassaṃ anussarāmīti._
____

But that merely 1,000 sand grains in the 2500 kilometres of the River Ganges. 
The Buddha's ability was unlimited. His usual ability during conversations was 
91 universal cycles (M.1.483; S.4.325):

[quote, M.1.483]
____
When I recollect the past ninety-one universal cycles, Vaccha, I do not recall 
any Ājīvaka ascetic who went to heaven.

_Ito kho so vaccha ekanavuto kappo yamahaṃ anussarāmi nābhijānāmi kañci 
ājīvakaṃ saggūpagaṃ._
____

[quote, S.4.324]
____
When I recollect the past ninety-one universal cycles, headman, I do not recall 
any family being destroyed merely by giving cooked almsfood.

_Ito so gāmaṇi ekanavuto kappo yamahaṃ anussarāmi nābhijānāmi 
kiñcikulaṃ pakkabhikkhāanuppadānamattena upahatapubbaṃ._
____

But at full stretch he could recall hundreds of thousands of universal cycles. 
In fact, as far as he liked (_so yāvatakaṃ ākaṅkhati tāvatakaṃ 
anussarati_, D.3.134). Thus he could legitimately proclaim:

[quote, S.2.181-2]
____
So long is the period of a universal cycle, bhikkhu. And of universal cycles of 
such length, we have wandered the round of birth and death for the periods of 
so many universal cycles, so many hundreds of universal cycles, so many 
thousands of universal cycles, so many hundreds of thousands of universal 
cycles.

_Evaṃ dīgho kho bhikkhu kappo. Evaṃ dīghānaṃ kho bhikkhu kappānaṃ 
neko kappo saṃsito nekaṃ kappasataṃ saṃsitaṃ nekaṃ kappasahassaṃ 
saṃsitaṃ nekaṃ kappasatasahassaṃ saṃsitaṃ._
____

==== Recollecting kappas of contraction and expansion: centuries

When bhikkhus recall their previous lives, they describe it as follows:

[quote, S.2.214]
____
'I recall my manifold past lives, that is, one birth, two lifetimes, three 
lifetimes... a hundred lifetimes, a thousand lifetimes, a hundred thousand 
lifetimes, [past lives in the last] many _kappas_ of contraction, many _kappas_ 
of expansion, many _kappas_ of contraction and expansion.

_aneke pi saṃvaṭṭakappe aneke pi vivaṭṭakappe aneke pi 
saṃvaṭṭavivaṭṭakappe._
____

Because _kappa_ is part of the contraction and expansion phases of the 
universal cycle, in this context it must mean 'century':

- '... many centuries of the universal cycle's contraction phase, many 
centuries of the universal cycle's expansion phase... .'

=== Illustrations

.Illustration
====
kappaṃ

century
====

[quote, S.5.259]
____
If one develops and cultivates the four paths to psychic power, if one wishes, 
one could live for a century or for slightly more than a century.

_so ākaṅkhamāno kappaṃ vā tiṭṭheyya kappāvasesaṃ vā._
____

.Illustration
====
kappaṃ

century
====

[quote, S.2.181]
____
Beings have wandered the round of birth and death for many centuries, many 
hundreds of centuries, many thousands of centuries, many hundreds of thousands 
of centuries

_neko kappo saṃsito nekaṃ kappasataṃ saṃsitaṃ nekaṃ kappasahassaṃ 
saṃsitaṃ nekaṃ kappasatasahassaṃ saṃsitaṃ._
____

.Illustration
====
kappe

centuries
====

[quote, S.2.214]
____
Bhikkhus, to whatever extent I wish, I recall my manifold past lives, that is, 
one birth, two lifetimes... a hundred thousand lifetimes, [past lives in the 
last] many centuries of the universal cycle's contraction phase, many centuries 
of the universal cycle's expansion phase, many centuries of the universal 
cycle's contraction and expansion phases.

_aneke pi saṃvaṭṭakappe aneke pi vivaṭṭakappe aneke pi 
saṃvaṭṭavivaṭṭakappe._
____

.Illustration
====
kappaṃ

the period of a universal cycle
====

____
-- 'Bhante, how long is the period of a universal cycle?'

_kīvadīgho nu kho bhante kappo ti?_
____

[quote, S.2.181]
____
-- 'The period of a universal cycle is long, bhikkhu. It is not easy to count 
it and say it is so many years, or so many hundreds of years, or so many 
thousands of years, or so many hundreds of thousands of years."

_Dīgho kho bhikkhu kappo. So na sukaro saṅkhātuṃ ettakāni vassāni iti 
vā ettakāni vassasatāni iti vā ettakāni vassasahassāni iti vā ettakāni 
vassasatasahassāni iti vā ti._
____

.Illustration
====
kappā

universal cycle
====

____
-- 'Master Gotama, how many universal cycles have elapsed and gone by?'

_Kīvabahukā nu kho bho gotama kappā abbhatītā atikkantā ti._
____

[quote, S.2.183-4]
____
-- 'Brahman, many universal cycles have elapsed and gone by. It is not easy to 
count them and say that there have been so many universal cycles, or so many 
hundreds of universal cycles, or so many thousands of universal cycles, or so 
many hundreds of thousands of universal cycles.'

_Bahukā kho brāhmaṇa kappā abbhatītā atikkantā. Te na sukarā 
saṅkhātuṃ ettakā kappā iti vā ettakāni kappasatāni iti vā ettakāni 
kappasahassāni iti vā ettakāni kappasatasahassāni iti vā ti._
____

.Illustration
====
kappe

universal cycle; saṃvaṭṭavivaṭṭakappa, the period of a universal 
cycle;
====

____
Having cultivated a mind of [unlimited, all-encompassing] goodwill for seven 
years, then for the periods of seven universal cycles I did not return to this 
&#8203;[low] plane of existence.

_Satta vassāni mettacittaṃ bhāvetvā satta saṃvaṭṭavivaṭṭakappe 
nayimaṃ lokaṃ punarāgamāsiṃ._
____

____
During the universal cycle's contraction phase, I went to the Ābhassarā world.

_Saṃvaṭṭamāne sudaṃ bhikkhave kappe ābhassarūpago homi._
____

[quote, It.14-16]
____
During the universal cycle's expansion phase, I was reborn in an empty Brahmā 
palace.

_Vivaṭṭamāne kappe suññaṃ brahmavimānaṃ upapajjāmi._
____

.Illustration
====
kappa

period of a universal cycle
====

[quote, A.3.402]
____
Devadatta is bound for [rebirth in] the plane of sub-human existence, bound for 
hell, and he will remain there for the period of a universal cycle, 
unredeemable.

__āpāyiko devadatto nerayiko kappaṭṭho atekiccho._
____

