== Karuṇā; Anuddaya; Anukampa; Anukampati

=== Renderings

- _karuṇā_: [unlimited, all-encompassing] compassion

- _kāruñña_: compassion

- _anuddaya_: sympathy

- _parānuddayata_: feeling sorry for others

- _anukampa_: tender concern

- _anukampati_: to be tenderly concerned for

- _anukampati_: tenderly reciprocate

- _anukampin_: being tenderly concerned

=== Introduction

==== [Unlimited, all-encompassing] compassion

The practices of _mettā_, _karuṇā_, _muditā_ and _upekkhā_ are sometimes 
called the four divine abidings (_cattāro brahmavihārā_, D.2.196) and 
sometimes the four unlimited states (_catasso appamaññā_, D.3.223). 
Practising them together is called the 'unlimited liberation [from perceptually 
obscuring states]' (_appamāṇā cetovimutti_, S.4.296). The _Mahāvedalla 
Sutta_ (M.1.298) and _Godatta Sutta_ (S.4.296) say the 'makers of limitation' 
(_pamāṇakaraṇo_) are _rāgo doso_ and _moho_ (_rāgo kho āvuso 
pamāṇakaraṇo doso pamāṇakaraṇo moho pamāṇakaraṇo_). Therefore 
the four _brahmavihāras_ should be practised unlimited by _rāgo doso_ and 
_moho_. And therefore we call _karuṇā_ '[unlimited, all-encompassing] 
compassion':

[quote, S.4.296]
____
In this regard a bhikkhu abides pervading one quarter with a mind of 
&#8203;[unlimited, all-encompassing] compassion, likewise the second quarter, the 
third quarter, and the fourth quarter. Thus above, below, across, in all 
directions, everywhere, he abides pervading the whole world [of beings] with a 
mind of [unlimited, all-encompassing] compassion, vast, exalted, unlimited, 
free of unfriendliness and hostility.

_Idha bhante bhikkhu karuṇāsahagatena cetasā ekaṃ disaṃ pharitvā 
viharati tathā dutiyaṃ tathā tatiyaṃ tathā catutthiṃ iti uddhamadho 
tiriyaṃ sabbadhi sabbatthatāya sabbāvantaṃ lokaṃ karuṇāsahagatena 
cetasā vipulena mahaggatena appamāṇena averena avyāpajjhena pharitvā 
viharati._
____

[quote, D.3.249]
____
It is impossible, friend, out of the question, that one might develop and 
cultivate the liberation [from perceptually obscuring states] through 
&#8203;[unlimited, all-encompassing] compassion, make it one's vehicle and practice, 
carry it out, pursue it, and properly undertake it, yet still maliciousness 
would plague your mind. There is no such possibility.

_Aṭṭhānametaṃ āvuso anavakāso yaṃ karuṇāya cetovimuttiyā 
bhāvitāya bahulīkatāya yānīkatāya vatthukatāya anuṭṭhitāya 
paricitāya susamāraddhāya atha ca panassa vihesā cittaṃ pariyādāya 
ṭhassatī'ti netaṃ ṭhānaṃ vijjati. Nissaraṇaṃ hetaṃ āvuso 
vihesāya yadidaṃ karuṇā cetovimutti._
____

[quote, A.3.185]
____
When resentment has arisen for someone one can develop [unlimited, 
all-encompassing] compassion for that person.

_Yasmiṃ bhikkhave puggale āghāto jāyetha karuṇā tasmiṃ puggale 
bhāvetabbā._
____

=== Illustrations

.Illustration
====
karuṇā

&#8203;[unlimited, all-encompassing] compassion
====

• -- 'The Blessed One abides in a state of [unlimited, all-encompassing] 
compassion' +
_bhagavā hi bhante karuṇāvihārī ti._

• -- 'Jīvaka, any attachment, hatred, or undiscernment of reality whereby 
maliciousness might arise, have been abandoned by the Perfect One... If what 
you said referred to that, then I allow it to you' +
☸... _vihesavā assa.._ (M.1.370).

.Illustration
====
karuṇaṃ

&#8203;[unlimited, all-encompassing] compassion
====

[quote, D.2.237]
____
He who abides in solitary retreat for the four months of the Rains, practising 
the meditation on [unlimited, all-encompassing] compassion, sees Brahmā.

_yo vassike cattāro māse paṭisallīyati karuṇaṃ jhānaṃ jhāyati so 
brahmānaṃ passati._
____

.Illustration
====
karuṇaṃ

&#8203;[unlimited, all-encompassing] compassion
====

[quote, M.1.284]
____
If anyone from a clan of _khattiyas_ goes forth from the household life into 
the ascetic life, and on account of the teaching and discipline proclaimed by 
the Perfect One, develops [unlimited, all-encompassing] goodwill, [unlimited, 
all-encompassing] compassion, [unlimited, all-encompassing] joy, and 
&#8203;[unlimited, all-encompassing] detached awareness, and thereby gains inward 
peace: on account of that inward peace, he is one who is applied to a practice 
that is proper for ascetics, I declare.

_Evameva kho bhikkhave khattiyakulā cepi agārasmā anagāriyaṃ pabbajito 
hoti so ca tathāgatappaveditaṃ dhammavinayaṃ āgamma evaṃ mettaṃ 
karuṇaṃ muditaṃ upekkhaṃ bhāvetvā labhati ajjhattaṃ vūpasamaṃ. 
Ajjhattaṃ vūpasamā samaṇasāmīcipaṭipadaṃ paṭipanno ti vadāmi._
____

.Illustration
====
karuṇaṃ

&#8203;[unlimited, all-encompassing] compassion
====

[quote, S.5.120]
____
_Karuṇā_: the liberation [from perceptually obscuring states] through 
&#8203;[unlimited, all-encompassing] compassion has the state of awareness of 
boundless space as its culmination.

__ākāsānañcāyatanaparamāhaṃ bhikkhave karuṇā cetovimuttiṃ vadāmi._
____

.Illustration
====
kāruññam

compassion
====

____
'Ānanda, would you just simply passively observe an elder bhikkhu while he is 
being harassed?

_atthi nāma ānanda theraṃ bhikkhuṃ vihesiyamānaṃ ajjhupekkhissatha_
____

[quote, A.3.194]
____
... Truly, Ānanda, compassion does not develop in allowing an elder bhikkhu to 
be harassed'

_Na hi nāma ānanda kāruññampi bhavissati theramhi bhikkhumhi 
vihesiyamānamhī ti._
____

.Illustration
====
karuṇaṃ (Commentary: anuddayaṃ)

sympathetic
====

____
Namuci approached me, uttering sympathetic words

_Namuci karuṇaṃ vācaṃ bhāsamāno upāgamī_
____

[quote, Sn.v.425-6]
____
'You are thin and sallow-faced. You are nearly dead... Live, sir. Life is 
better [than death].... The path of striving is hard: hard to undertake, and 
hard to bear'

_duggo maggo padhānāya dukkaro durabhisambhavo._
____

COMMENT

_Karuṇaṃ_: 'sympathetic.' Treating _karuṇaṃ_ as _anuddayaṃ_. 
Commentary: _Karuṇaṃ vācan ti anuddayāyuttaṃ vācaṃ_.

.Illustration
====
kāruññataṃ

compassion
====

[quote, S.1.137]
____
Then the Blessed One, understanding the Brahmā's request, out of compassion 
for beings surveyed the world with the vision of a Buddha.

_atha kho bhagavā brahmuno ca ajjhesanaṃ viditvā sattesu ca kāruññataṃ 
paṭicca buddhacakkhunā lokaṃ volokesi._
____

.Illustration
====
kāruññatā

compassion; anukampatā, tender concern
====

____
If a bhikkhu is wanting to reprove another, having contemplated five principles 
within himself he may do so:

_paraṃ codetukāmena pañca dhamme ajjhattaṃ manasikaritvā paro codetabbo_
____

____
&#8203;[I will speak out of] compassion

_kāruññatā_
____

____
&#8203;[I will speak out of] seeking welfare

_hitesitā_
____

____
&#8203;[I will speak out of] tender concern

_anukampatā_
____

____
&#8203;[I will speak aiming at the] removal of offences

__āpattivuṭṭhānatā_
____

[quote, Vin.2.250]
____
&#8203;[I will speak] aiming at vinaya

_vinayapurekkhāratā ti._
____

COMMENT

Parentheses in accordance with _Codanā Sutta_:

____
If a bhikkhu is reproving, wanting to reprove another, he should do so having 
established five principles within himself.

_Codakena āvuso bhikkhunā paraṃ codetukāmena pañca dhamme ajjhattaṃ 
upaṭṭhepetvā paro codetabbo:_
____

____
I will speak at the right time, not the wrong time

_kālena vakkhāmi no akālena_
____

____
I will speak truth not falsehood

_bhūtena vakkhāmi no abhūtena_
____

____
I will speak gently not harshly

_saṇhena vakkhāmi no pharusena_
____

____
I will speak what is conducive to spiritual well-being not unconducive to 
spiritual well-being

_atthasaṃhitena vakkhāmi no anatthasaṃhitena_
____

[quote, D.3.236-7; A.3.196]
____
I will speak with a mind of [unlimited, all-encompassing] goodwill not with 
inner hatred

_mettacittena vakkhāmi no dosantarenā ti._
____

.Illustration
====
kāruññaṃ

compassion ; anuddayaṃ, sympathy; anukampaṃ, tender concern
====

He explains the Buddha's teaching to others

____
out of compassion

_kāruññaṃ paṭicca paresaṃ dhammaṃ deseti_
____

____
out of sympathy

_anuddayaṃ paṭicca paresaṃ dhammaṃ deseti_
____

[quote, S.2.200]
____
out of tender concern

_Anukampaṃ upādāya paresaṃ dhammaṃ deseti._
____

.Illustration
====
kāruññaṃ

compassion; anuddayaṃ, sympathy; anukampaṃ, tender concern
====

Suppose a sick and ailing man were to go along the highway with no village 
nearby, and unable to get proper food and medicine; and suppose another man, 
also going along the road, were to see him; it might

____
raise compassion in that man

_kāruññaṃ yeva upaṭṭhāpeyya_
____

____
raise sympathy

_anuddayaṃ yeva upaṭṭhāpeyya_
____

____
raise tender concern

_anukampaṃyeva upaṭṭhāpeyya_
____

so that he might say to himself: Alas for this man! he ought to have proper 
food and medicine, or a guide to some village. Wherefore? Lest he suffer 
misfortune and disaster.

Equally, of one whose ways are impure, who obtains no mental clarity, mental 
calm: for such a person

____
compassion ought to arise

_kāruññaṃ eva upaṭṭhāpetabbaṃ_
____

____
sympathy ought to arise

_anuddayāyeva upaṭṭhāpetabbā_
____

____
tender concern ought to arise

_anukampāyeva upaṭṭhāpetabbā_
____

so one says to oneself: 'Alas for this Venerable! He should give up bad habits 
in deed, word and thought and develop good habits. Wherefore? Lest this 
Venerable, with the demise of the body at death, is reborn in the plane of 
sub-human existence, in the plane of misery, in the plane of damnation, or in 
hell (A.3.189).

.Illustration
====
anukampituṃ

have tender concern; anuddayā, sympathy
====

____
If, O Sakka, for some reason intimacy with anyone should arise, the wise man 
ought not to have tender concern in his mind for such a person.

_Yena kenaci vaṇṇena saṃvāso sakka jāyati +
Na taṃ arahati sappañño manasā anukampituṃ._
____

[quote, S.1.206]
____
But if with a pure mind he teaches others, he does not become tethered [to 
them] by his tender concern and sympathy.

_Manasā ce pasannena yadaññamanusāsati +
Na tena hoti saṃyutto sānukampā anuddayā ti._
____

.Illustration
====
anuddayataṃ sympathy

____
One who explains the teaching to others should establish five principles within 
himself. What five?

_Paresaṃ ānanda dhammaṃ desentena pañca dhamme ajjhattaṃ 
upaṭṭhapetvā paresaṃ dhammo desetabbo. Katame pañca:_
____

One should explain the teaching to others with the thought:

1. 'I will speak step-by-step
+
****
_Ānupubbīkathaṃ kathessāmīti paresaṃ dhammo desetabbo_
****

2. 'I will speak observing a proper method of exposition
+
****
_Pariyāyadassāvī kathaṃ kathessāmīti paresaṃ dhammo desetabbo_
****

3. 'I will speak out of sympathy
+
****
_Anuddayataṃ paṭicca kathaṃ kathessāmīti paresaṃ dhammo desetabbo_
****

4. 'I will speak not for the sake of worldly benefits
+
****
_Na āmisantaro kathaṃ kathessāmīti paresaṃ dhammo desetabbo_
****

5. 'I will speak without hurting myself or others
+
****
_Attānañca parañca anupahacca kathaṃ kathessāmī ti paresaṃ dhammo 
desetabbo_ (A.3.184).
****

==== Illustration: anuddayatā

sympathy
====

There are these three kinds of spiritually unwholesome thinking 
(_akusalavitakkā_). Which three?

____
thinking concerned with not wanting to be despised

_anavaññattipaṭisaṃyutto vitakko_
____

____
thinking concerned with gains, honour, and renown

_lābhasakkārasilokapaṭisaṃyutto vitakko_
____

[quote, It.72]
____
thinking concerned with feeling sorry for others

_parānuddayatāpaṭisaṃyutto vitakko._
____

Comment:

As an example of feeling sorry for others, consider Nissaggiyā Pācittiyā 
Rule 22 which says that if a bhikkhu wrongfully gets himself a new bowl from a 
lay supporter, that bowl should be forfeited to the group of bhikkhus. The bowl 
should be first offered to the senior bhikkhu, who should be persuaded to swap 
his own bowl for the new bowl if he prefers it. The senior bhikkhu should not 
refuse to swap out of feeling sorry for the offender (_na ca tassa 
anuddayatāya na gahetabbo_), otherwise it is a dukkaṭa offence (_yo na 
gaṇheyya āpatti dukkaṭassa_) (Vin.3.247).

.Illustration
====
anukampamāno

being tenderly concerned
====

[quote, Sn.v.37]
____
Being tenderly concerned for friends and comrades, one neglects one's own 
spiritual well-being, being emotionally bound [to others]. Seeing this danger 
in intimacy, one should live the religious life as solitarily as a rhinoceros 
horn.

_Mitte suhajje anukampamāno hāpeti atthaṃ paṭibaddhacitto +
Etaṃ bhayaṃ santhave pekkhamāno eko care khaggavisāṇakappo._
____

.Illustration
====
anukampanti

tenderly reciprocate
====

____
'There are five ways in which a son should minister to his parents as the 
eastern direction'

_Pañcahi kho gahapatiputta ṭhānehi puttena puratthimā disā mātāpitaro 
paccupaṭṭhātabbā_
____

[quote, D.3.189]
____
'And there are five ways in which the parents, so ministered to by their son as 
the eastern direction, will tenderly reciprocate'

_Imehi kho gahapatiputta pañcahi ṭhānehi puttena puratthimā disā 
mātāpitaro paccupaṭṭhitā pañcahi ṭhānehi puttaṃ anukampanti._
____

.Illustration
====
anukampanti

tenderly reciprocate
====

____
Wherever a wise man makes his dwelling, here he should feed the virtuous, those 
restrained [in conduct], those who live the religious life. He should dedicate 
a gift to the devas who are in that place.

_Yasmiṃ padese kappeti vāsaṃ paṇḍitajātiyo +
sīlavantettha bhojetvā saṃyate brahmacārayo +
Yā tattha devatā āsuṃ tāsaṃ dakkhiṇamādise._
____

• Venerated, they will venerate them, revered, they will revere them. They 
will tenderly reciprocate, as a mother for her own son. He with whom the devas 
tenderly reciprocate always has good fortune. +
☸ _Tā pūjitā pūjayanti mānitā mānayanti naṃ +
tato naṃ anukampanti mātā puttaṃ'ca orasaṃ +
Devatānukampito poso sadā bhadrāni passatī ti_ (D.2.88-9) (Ud.89) 
(Vin.1.229-230).

.Illustration
====
anukampāya

tender concern
====

____
For two good reasons the Perfect One establishes training rules for disciples:

_sāvakānaṃ sikkhāpadaṃ paññattaṃ_
____

[quote, A.1.98]
____
Out of tender concern for the layfolk; and to stop factions of bhikkhus with 
unvirtuous desires._

_gihīnaṃ anukampāya pāpicchānaṃ bhikkhūnaṃ pakkhupacchedāya._
____

.Illustration
====
anukampako

have tender concern
====

[quote, D.2.143]
____
'The [attainment to the] Untroubled-without-residue of the Teacher who had such 
tender concern for me [will be tonight in the last watch].'

_satthu ca me parinibbānaṃ bhavissati yo mamaṃ anukampako ti._
____

.Illustration
====
anukampikāya

tender concern
====

If a foolish baby through the negligence of the nurse puts a stick or stone 
into its mouth, the nurse would quickly pay attention, and quickly remove it. 
If she failed to do so, then, taking hold of his head with her left hand, and 
crooking the finger of her right hand, she would fetch it out even if she drew 
blood. Why so? There would be some injury to the boy, I don't deny it, but 
really, bhikkhus:

[quote, A.3.6]
____
This is what should be done by the nurse wishing for the child's well-being, 
seeking its welfare, from tender concern, out of tender concern.'

_karaṇīyañca kho etaṃ bhikkhave dhātiyā atthakāmāya hitesiniyā 
anukampikāya anukampaṃ upādāya._
____

.Illustration
====
anukampamāno

tender concerned for
====

[quote, M.1.23]
____
Considering two good reasons, brahman, I frequent secluded abodes in forests 
and quiet groves: in considering a pleasant abiding for myself in this 
lifetime, and being tenderly concerned for future generations.

_attano ca diṭṭhadhammasukhavihāraṃ sampassamāno pacchimañca janataṃ 
anukampamāno ti._
____

.Illustration
====
anukampī

tenderly concerned
====

The Buddha told bhikkhus that in whatever way they are spoken to, they should 
train themselves thus:

[quote, M.1.126]
____
'Neither shall our minds be worsened by this, nor shall we utter unvirtuous 
words, but we shall abide tenderly concerned for their welfare, with a mind of 
&#8203;[unlimited, all-encompassing] goodwill, without inner hatred.'

_na ceva no cittaṃ vipariṇataṃ bhavissati. Na ca pāpakaṃ vācaṃ 
nicchāressāma. Hitānukampī ca viharissāma mettacittā na dosantarā._
____

.Illustration
====
anukampī

tenderly concerned
====

[quote, A.5.290]
____
He abides tenderly concerned for the welfare of all living beings.

_sabbapāṇabhūtahitānukampī viharati._
____

.Illustration
====
anukampī

be tenderly concerned
====

-- Lohicca, do you reside at Sālavatikā?

-- Yes, reverend Gotama.

____
-- Well, if anyone said: "The Brahman Lohicca resides at Sālavatikā, and he 
should enjoy the entire revenue and produce of Sālavatikā, not giving 
anything to others" would not anyone who spoke like that be a source of danger 
to your tenants?

_evaṃvādi so ye taṃ upajīvanti tesaṃ antarāyakaro vā hoti no vā ti_
____

____
-- He would be a source of danger, reverend Gotama.

_Antarāyakaro bho gotama_
____

____
-- And as such, would he be tenderly concerned for their welfare or not?

_Antarāyakaro samāno lohicca hitānukampī vā tesaṃ hoti ahitānukampī 
vā ti_
____

[quote, D.1.228]
____
-- He would not, reverend Gotama.

_Ahitānukampī bho gotama._
____

