== Khaya

=== Renderings

- _khaya_: destruction

- _parikhaya_: destruction

=== Illustrations

.Illustration
====
khayo

destruction
====

[quote, S.4.251]
____
The destruction of attachment, hatred, and undiscernment of reality: this is 
called the Untroubled.

_Yo kho āvuso rāgakkhayo dosakkhayo mohakkhayo idaṃ vuccati nibbānan ti._
____

.Illustration
====
khayāya

destruction
====

____
Apply yourself to the destruction of craving

_taṇhakkhayāya paṭipajjatha_
____

[quote, S.3.190]
____
For the destruction of craving, Rādha, is the Untroubled

_taṇhakkhayo hi rādha nibbānan ti._
____

.Illustration
====
khayāya

destruction
====

[quote, S.5.340]
____
Meditation through mindfulness with breathing if developed and cultivated leads 
to the destruction of perceptually obscuring states.

_Ānāpānasatisamādhi bhikkhave bhāvito bahulīkato āsavānaṃ khayāya 
saṃvattati._
____

.Illustration
====
parikkhayaṃ gaccheyya

destroyed
====

____
If a man let two or three drops of water fall onto a red-hot iron plate, slow 
might be the falling of the water drops

_dandho bhikkhave udakaphusitānaṃ nipāto_
____

[quote, S.4.190]
____
but then they would be quickly destroyed and consumed

_khippameva parikkhayaṃ pariyādānaṃ gaccheyya._
____

.Illustration
====
parikkhayā

destruction
====

[quote, A.1.234]
____
Destroyed the first three ties to individual existence

_tiṇṇaṃ saṃyojanānaṃ parikkhayā._
____

.Illustration
====
parikkhayā

destruction
====

[quote, S.1.2]
____
The destruction of the spiritually fettering delight in individual existence

_Nandibhavaparikkhayā._
____

.Illustration
====
parikkhayā

destruction
====

[quote, It.44]
____
Destroyed craving for states of individual existence._

_bhavataṇhāparikkhayā._
____

