== Khema

=== Renderings

- _khema_: safety

- _khema_: security

- _khema_: sure

- _khema_: place of safety

- _khemin_: one who has reached safety from the danger of bondage [to 
individual existence] (=__yogakkhemin__)

- _khemattaṃ_: one who has reached safety from the danger of bondage [to 
individual existence] (=__yogakkhemin__)

=== Introduction

==== Khemin and khematta = yogakkhemin

_Khemin_ and _khematta_ occur only in verses and are abbreviations for 
_yogakkhemin_, meaning 'One who has reached safety from the danger of bondage 
&#8203;[to individual existence].' They are dealt with under _Yogakkhema_.

=== Illustrations

.Illustration
====
khemato

safety
====

[quote, Th.v.980]
____
Seeing negligence [in the practice] as danger, and diligence [in the practice] 
as safety.

_Pamādaṃ bhayato disvā appamādañca khemato._
____

.Illustration
====
khema

safety
====

[quote, Sn.v.809]
____
Looking for safety sages therefore abandon possessiveness and live the 
religious life.

_Tasmā munayo pariggahaṃ/ Hitvā acariṃsu khemadassino._
____

.Illustration
====
khemaṃ

safety
====

[quote, D.1.11]
____
There will be safety; there will be danger.

_khemaṃ bhavissati bhayaṃ bhavissati._
____

.Illustration
====
khemo

safety
====

[quote, It.31]
____
Two trains of thought often occur to the Perfect One, the Arahant, the 
Perfectly Enlightened One: the thought of [others'] safety and the thought of 
physical seclusion.

_Tathāgataṃ bhikkhave arahantaṃ sammāsambuddhaṃ dve vitakkā bahulaṃ 
samudācaranti khemo ca vitakko paviveko ca._
____

Comment:

Parenthesising 'others' is justified by the two sentences that follow:

[quote, It.31]
____
The Perfect One takes pleasure and delight in non-hostility. In doing so, this 
thought often occurs: 'By this behaviour I harm no one at all, whether weak or 
strong.'

_Avyāpajjhārāmo bhikkhave tathāgato avyāpajjharato. Tamenaṃ bhikkhave 
tathāgataṃ avyāpajjhārāmaṃ avyāpajjharataṃ esova vitakko bahulaṃ 
samudācarati: imāyāhaṃ irīyāya na kiñci vyābādhemi tasaṃ vā 
thāvaraṃ vā ti._
____

.Illustration
====
khemo

safety
====

[quote, Sn.v.953]
____
For one who is imperturbable, for one who understands [the teaching], there is 
no accumulated merit or demerit. Abstaining from [karmically consequential] 
endeavours, he sees safety everywhere.

_Anejassa vijānato natthi kāci nisaṅkhiti +
Virato so viyārambhā khemaṃ passati sabbadhi._
____

.Illustration
====
khemato

safety
====

[quote, Thī.v.226]
____
Seeing danger in sensuous pleasures, and safety in the practice of 
unsensuousness

_Kāmesvādīnavaṃ disvā nekkhammaṃ daṭṭhu khemato._
____

.Illustration
====
khema

safety
====

[quote, Th.v.422]
____
&#8203;[The noble eightfold path] leads to great safety

_Mahākhemaṅgamo._
____

.Illustration
====
khema

safety
====

[quote, Sn.v.896]
____
Disputes have but two fruits, I declare [i.e. jubilation and dejection]. Seeing 
this, you should not dispute. Recognise that safety is a state that is without 
dispute.

_Etampi disvā na vivādayetha khemābhipassaṃ avivādabhūmiṃ._
____

.Illustration
====
kheme

safe
====

[quote, Vin.4.296]
____
She goes somewhere safe, not dangerous

_kheme appaṭibhaye gacchati._
____

.Illustration
====
khemā

safe
====

[quote, Th.v.310]
____
The River Ajakaraṇī is safe, pleasant, delightful.

_Khemā ajakaraṇī sivā surammā ti._
____

.Illustration
====
khemaṃ

safe
====

[quote, Dh.v.189]
____
Those are not safe refuges. Those are not the supreme refuge.

_Netaṃ kho saraṇaṃ khemaṃ netaṃ saraṇamuttamaṃ._
____

.Illustration
====
khemaṃ

safe
====

[quote, D.1.73]
____
Just as a man, laden with wealth and riches, might travel on a desert road 
where food was scarce and danger abounded, and after a time he would cross the 
desert and arrive at the edge of a village, safe and free of danger.

_Seyyathā pi mahārāja puriso sadhano sabhogo kantāraddhānamaggaṃ 
paṭipajjeyya dubbhikkhaṃ sappaṭibhayaṃ. So aparena samayena taṃ 
kantāraṃ nitthareyya sotthinā gāmantaṃ anupāpuṇeyya khemaṃ 
appaṭibhayaṃ ti._
____

.Illustration
====
khemino

safe [from the danger of bondage to individual existence]
====

[quote, Sn.v.145]
____
May all creatures be happy and safe [from the danger of bondage to individual 
existence].

_Sukhino va khemino hontu sabbe sattā._
____

.Illustration
====
khemaṃ

sure
====

[quote, Thī.v.360]
____
I shall follow that griefless, stainless, sure, eightfold, direct path, by 
which the great seers have crossed [to the Far Shore].

_Asokaṃ virajaṃ khemaṃ ariyaṭṭhaṅgikaṃ ujuṃ_ +
_Taṃ maggaṃ anugacchāmi yena tiṇṇā mahesino._
____

.Illustration
====
khemaṃ

sure
====

[quote, Sn.v.454]
____
The sure word which the Buddha speaks for the attainment of _nibbāna_.

_Yaṃ buddho bhāsatī vācaṃ khemaṃ nibbānapattiyā._
____

.Illustration
====
khemaṃ

place of safety
====

[quote, A.3.104]
____
In a time of peril, people migrate to places of safety

_Bhaye kho pana sati manussā yena khemaṃ tena saṅkamanti._
____

