== Kulaputta

=== Renderings

- _kulaputta_: noble young man

- _kulaputta_: of noble ancestry

- _kulaputta_: a member of the gentry

- _kulaputta_: son of a genteel family

- _kulaputta_: son of an aristocratic family

=== Introduction

==== Kulaputta: sonship, youth, and high social background

DOP says _kulaputta_ means either

1. the son of a good or noble family

2. a noble youth.

So -_putta_ does not necessarily mean 'son.' We will see that it more often 
indicates 'youth.' In some cases it indicates a high social background ('of the 
genteel classes'). That -_putta_ indicates youth but not boyhood is our next 
point.

==== Kulaputta: youth not boyhood, part 1

Although -_putta_ means youth, it does not mean boyhood. For example, when 
Venerable Anuruddha is called _kulaputta_ at M.1.205, he would have been at 
least 35 years old for the following reasons:

1. At that time he was an arahant (M.1.205).

2. Th.v.904 says it took him 30 years to overcome torpor (_middhaṃ 
samūhataṃ_), which is therefore when he attained arahantship, because only 
arahants have completely abandoned lethargy and torpor 
(_thīnamiddhanīvaraṇaṃ_, S.5.327).

3. His age at ordination is uncertain, but given that his brother informed him 
of the duties that would fall to him if he remained a layperson, he was likely 
between 5-20 years old (Vin.2.180-1).

==== Kulaputta: youth not boyhood, part 2

That _kulaputta_ means youth not boyhood is also obvious in the 
_Licchavikumāra Sutta_, which says this:

[quote, A.3.76]
____
Mahānāma, in whatever _kulaputta_ five qualities are found -- whether he is a 
consecrated noble king, a country gentleman, an army general, a village 
headman, a guildmaster, or someone who exercises personal authority over 
various families -- only growth [in spiritually wholesome factors] is to be 
expected for him, not a falling away [from them]. What five?

_Yassa kassaci mahānāma kulaputtassa pañcadhammā saṃvijjanti yadi vā 
rañño khattiyassa muddhābhisittassa yadi vā raṭṭhikassa pettanikassa 
yadi vā senāya senāpatikassa yadi vā gāmagāmikassa yadi vā 
pūgagāmaṇikassa ye vā pana kulesu paccekādhipaccaṃ kārenti vuddhiyeva 
pāṭikaṅkhā no parihāni. Katame pañca?._
____

If army generals and village headmen are _kulaputtas_, then _kulaputta_ does 
not mean boyhood. We also see that _kulaputta_ is associated with the gentry, 
which suggests the rendering 'noble young man.'

==== Kulaputto: of noble ancestry

Although Ambaṭṭha considered himself a brahman, the Buddha said he was in 
fact descended from a slavegirl (_dāsiputto_ D.1.92). Ambaṭṭha's friends 
initially defended him, saying he was of pure ancestry (_sujāto_) and a 
_kulaputto_. But on discovering the truth, they said he was of impure ancestry 
(_dujjāto_), an _akulaputto_, descended from a slave (_dāsiputto_).

So, according to brahmans, _kulaputto_ was an exalted term associated with the 
most prestigious members of their group, the _sujāto_, and incompatible with 
slavish forebears. _Kulaputta_ therefore means 'of noble ancestry.'

The significance of _sujāto_ can be seen in the following conversation, where 
it is the first quality expected of a brahman who is a master of threefold 
Vedic knowledge:

____
-- 'In what way, brahman, do brahmans declare a brahman to be a master of 
threefold Vedic knowledge?'

_Yathākathaṃ pana brāhmaṇa brāhmaṇā brāhmaṇaṃ tevijjaṃ 
paññāpentī ti_
____

[quote, A.1.166]
____
-- In this regard, Master Gotama, a brahman is of pure ancestry (_sujāto 
hoti_) on both sides of his family, of pure descent, unimpeachable and 
irreproachable with respect to birth as far back as the seventh generation.

_Idha pana bho gotama brāhmaṇo ubhato sujāto hoti mātito ca pitito ca 
saṃsuddhagahaṇiko yāva sattamā pitāmahāyugā akkhitto anupakkuṭṭho 
jātivādena._
____

==== Kulaputto: member of the gentry

Related to noble ancestry is gentility. When Venerable Upananda asked a certain 
great merchant (_aññataro seṭṭhiputto_) to give him one of his two robes, 
the man replied:

[quote, Vin.3.211]
____
But, bhante, for us who are members of the gentry, it is awkward to walk around 
with only one piece of cloth.

_Amhākaṃ kho bhante kulaputtānaṃ kismiṃ viya ekasāṭakaṃ gantuṃ._
____

Comment:

We call _seṭṭhiputto_ 'great merchant' not 'son of a great merchant,' 
taking _-putto_ as pleonastic.

==== Kulaputto: sons of genteel families

Related to noble ancestry and gentility is a delicate upbringing. For example, 
Anuruddha the Sakyan had three palaces. When his brother invited him to become 
a bhikkhu, he complained:

[quote, Vin.2.180]
____
But I have been delicately nurtured, I am not able to go forth from the 
household life into the ascetic life.

_Ahaṃ kho sukhumālo. Nāhaṃ sakkomi agārasmā anagāriyaṃ pabbajituṃ._
____

The Buddha helped such individuals by providing them with sufficient clothing. 
He reflected:

[quote, Vin.1.288]
____
Even those in this teaching and training system who are sons of genteel 
families and susceptible to cold, afraid of cold, even these are able to keep 
themselves going with three robes.

_yepi kho te kulaputtā imasmiṃ dhammavinaye pabbajitā sītālukā 
sītabhīrukā tepi sakkonti ticīvarena yāpetu._
____

==== Kulaputto: sons of aristocratic families

In relation to 'highly distinguished,' we give _kulaputtā_ the meaning 'sons 
of the aristocratic families':

[quote, Vin.1.43]
____
Now at that time highly distinguished sons of the aristocratic families of 
Magadha were living the religious life under the Blessed One.

_Tena kho pana samayena abhiññātā abhiññātā māgadhakā kulaputtā 
bhagavati brahmacariyaṃ caranti._
____

==== Kulaputta: spiritual nobility

• When Venerables Anuruddha, Nandiya, and Kimbila were living together in the 
Gosinga Sāla-tree Wood, their utmost harmony was shielded by a zealous 
gatekeeper who so diligently defended the place against visitors, that when on 
one occasion the Buddha dared enter uninvited, he was told 'Do not enter this 
grove, ascetic! There are three _kulaputtas_ here seeking their Soul. Do not 
disturb them!' +
☸ _mā samaṇa etaṃ dāyaṃ pāvisi sant'ettha tayo kulaputtā 
attakāmarūpā viharanti mā tesaṃ aphāsumakāsī ti_, M.1.206).

The gatekeeper would hardly have meant this with social connotations 'There are 
three member of the gentry living here,' and _kulaputta_ here seems to imply 
spiritual nobility. We have seen above that this sense is not just for 
bhikkhus. We render it as 'noble young man.'

==== Kulaputta versus moghapurisā: noble young man

That the elevated connotations of _kulaputto_ extend to the spiritual sphere 
can be discerned when the Buddha contrasted _kulaputtā_ and _moghapurisā_:

____
Thus do noble young men (_kulaputtā_) declare their [attainment of] 
arahantship. The matter is spoken of without any reference to themselves.

_evaṃ kho bhikkhave kulaputtā aññaṃ vyākaronti attho ca vutto attā ca 
anupanīto._
____

[quote, A.3.359]
____
... Yet there are some worthless men (_moghapurisā_) here who apparently 
declare [that they have attained] arahantship for fun.

_Atha ca pana idhekacce moghapurisā hasamānakā maññe aññaṃ 
vyākaronti._
____

==== Kulaputta versus 'persons' (puggalā)

Similarly, Gaṇaka Moggallāna contrasted _kulaputtā_ with _puggalā_:

____
\a) persons (_puggalā_) without faith who have gone forth from the household 
life into the ascetic life merely for the sake of a livelihood

_puggalā assaddhā jīvikatthā agārasmā anagāriyaṃ pabbajitā_
____

[quote, M.3.6]
____
\b) noble young men (_kulaputtā_) who have gone forth from the household life 
into the ascetic life out of faith

_kulaputtā saddhā agārasmā anagāriyaṃ pabbajitā._
____

=== Illustrations

.Illustration
====
kulaputto

noble young man
====

[quote, M.1.85]
____
By whatever profession a noble young man makes his living, whether counting, 
accountancy, calculation, farming, trading, animal husbandry, archery, or in 
the royal service, or whatever the profession may be, he is exposed to cold and 
heat.

_kulaputto yena sippaṭṭhānena jīvikaṃ kappeti yadi muddāya yadi 
gaṇanāya yadi saṅkhānena yadi kasiyā yadi gorakkhena yadi issatthena 
yadi rājaporisena yadi sippaññatarena sītassa purakkhato uṇhassa 
purakkhato._
____

.Illustration
====
kulaputtānaṃ

noble young men
====

____
It is fitting for all you noble young men who have gone forth from the 
household life into the ascetic life to take delight [in the celibate life].

_etaṃ kho anuruddhā tumhākaṃ patirūpaṃ kulaputtānaṃ saddhā 
agārasmā anagāriyaṃ pabbajitānaṃ yaṃ tumhe abhirameyyātha 
brahmacariye_
____

[quote, M.1.463]
____
As you are still endowed with the blessing of youth, black-haired young men in 
the prime of life, you could have been indulging in sensuous pleasures.

_Yena tumhe anuruddhā bhadrena yobbanena samannāgatā paṭhamena vayasā 
susu kālakesā kāme paribhuñjeyyātha._
____

