== Kusala; Akusala

=== Renderings

- _kusala_: welfare

- _kusala_: good/excellent

- _kusala_: wholesome

- _kusala_: well behaved

- _kusala_: an expert

- _kusala_: a pandit

- _kusalā_: the wise (people)

- _kusala_: proficient

- _kusala_: spiritual proficiency

- _kusala_: knowledgeable

- _kusala_: spiritually wholesome

- _kusala_: what is spiritually wholesome

- _akusala_: improficient

- _akusala_: ignorant

- a__kusala__: badly behaved

- _akusala_: spiritually unwholesome

- _akusala_: what is spiritually unwholesome

- a__kusala__: unwholesome

=== Introduction

==== Rendering akusala and kusala

Rendering _akusala_ and _kusala_ as spiritually unwholesome or wholesome is 
justified by their association with defilement and purity, with 
uninsightfulness and insightfulness, as seen in the following passages:

1. He has been struck down by unvirtuous, spiritually unwholesome factors that 
are defiling, and which lead to renewed states of individual existence, 
suffering, unpleasant karmic consequences, and future birth, old age, and death.
+
****
_avadhiṃsu naṃ pāpakā akusalā dhammā saṅkilesikā ponobhavikā 
sadarā dukkhavipākā āyatiṃ jātijarāmaraṇiyā_ (M.3.116).
****

2. Even so did I see the danger, degradation, and defilement in spiritually 
unwholesome factors, and in spiritually wholesome factors and in the practice 
of unsensuousness, I saw the advantage and associated purity.
+
****
_Evameva kho ahaṃ bhikkhave addasaṃ akusalānaṃ dhammānaṃ ādīnavaṃ 
okāraṃ saṅkilesaṃ kusalānaṃ dhammānaṃ nekkhamme ānisaṃsaṃ 
vodānapakkhaṃ._ (M.1.115).
****

3. There are these three kinds of spiritually unwholesome thoughts that produce 
spiritual blindness, uninsightfulness, ignorance [of things according to 
reality], and are destructive of penetrative discernment, vexatious, and not 
conducive to the Untroubled. Which three?
+
****
_Tayo'me bhikkhave akusalavitakkā andhakaraṇā acakkhukaraṇā 
aññāṇakaraṇā paññānirodhikā vighātapakkhikā 
anibbānasaṃvattanikā. Katame tayo?_ (It.82).
****

[quote, It.82]
____
There are these three kinds of spiritually wholesome thoughts that produce 
insightful vision, knowledge [of things according to reality], lead to the 
development of discernment, are undistressing, and are conducive to the 
Untroubled. Which three?

_Tayo'me bhikkhave kusalavitakkā anandhakaraṇā cakkhukaraṇā 
ñāṇakaraṇā paññāvuddhikā avighatapakkhikā nibbānasaṃvattanikā 
katame tayo?._
____

==== Essence of akusala: five hindrances

The essence of _akusala_ is found in the five hindrances, because:

____
If one were to say of anything 'a spiritually unwholesome heap,' it is about 
the five hindrances that one could rightly say this.

_Akusalarāsī ti bhikkhave vadamāno pañcanīvaraṇe sammā vadamano 
vadeyya._
____

Each of the five hindrances is called:

[quote, S.5.95]
____
a spiritual obstruction, a spiritual hindrance, a spiritual defilement, a 
weakener of penetrative discernment.

__āvaraṇā nīvaraṇā cetaso upakkilesā paññāya dubbalīkaraṇā._
____

==== Essence of kusala: four bases of mindfulness

The essence of _kusala_ is found in four bases of mindfulness, because:

[quote, S.5.145-6]
____
If one were to say of anything 'a spiritually wholesome heap,' it is about the 
&#8203;[contemplation of the] four bases of mindfulness that one could rightly say 
this.

_Kusalarāsī ti bhikkhave vadamāno cattāro satipaṭṭhāne sammā 
vadamāno vadeyya._
____

The [contemplation of the] four bases of mindfulness is called:

[quote, S.5.142]
____
the one-destination path for the purification of beings

_ekāyano ayaṃ bhikkhave maggo sattānaṃ visuddhiyā._
____

==== Kusala and akusala: conduct of body, speech, and mind

1. _Akusala_ is found in conduct like frivolous speech (_samphappalāpo 
akusalaṃ_) and killing (_pāṇātipāto akusalaṃ_).

2. Refraining from such conduct is _kusala_ (_samphappalāpā veramaṇī 
kusalaṃ_).

3. _Akusala_ is found in mental conduct:

____
Sensuous thought, unbenevolent thought, malicious thought. These are called 
spiritually unwholesome thoughts.

_kāmasaṅkappo vyāpādasaṅkappo vihiṃsāsaṅkappo ime vuccanti thapati 
akusalasaṅkappā._
____

4. Refraining from such conduct is _kusala_:

[quote, M.2.28]
____
Unsensuous thought, thought of goodwill, compassionate thought. These are 
called spiritually wholesome thoughts

_nekkhammasaṅkappo avyāpādasaṅkappo avihiṃsāsaṅkappo ime vuccanti 
thapati kusalasaṅkappā._
____

==== Kusala and akusala: mental states

_Akusala_ is found in mental states:

____
Greed is spiritually unwholesome

_abhijjhā akusalaṃ_
____

____
Ill will is spiritually unwholesome

_vyāpādo akusalaṃ_
____

____
Wrong view [of reality] is spiritually unwholesome

_micchādiṭṭhi akusalaṃ_
____

_Kusala_ is found in their opposites.

____
Non-greed is spiritually wholesome

_anabhijjhā kusalaṃ_
____

____
Goodwill is spiritually wholesome

_avyāpādo kusalaṃ_
____

[quote, M.1.47]
____
Right perception [of reality] is spiritually wholesome

_sammādiṭṭhi kusalaṃ._
____

==== People and objects: not kusala or akusala

Therefore people and objects (apart from mental objects) are not spiritually 
wholesome or unwholesome. Neither, in themselves, are religious teachings, 
which instead we call 'wholesome' and 'unwholesome':

[quote, A.1.190]
____
Kālāmas, if you yourselves should consider: "These teachings are wholesome... 
you should accept and abide by them.

_Yadā tumhe kālāmā attanā'va jāneyyātha ime dhammā kusalā... atha 
tumhe kālāmā upasampajja vihareyyātha_
____

[quote, A.1.190]
____
Kālāmas, if you yourselves should consider: "These teachings are 
unwholesome... you should abandon them.

_Yadā tumhe kālāmā attanāva jāneyyātha ime dhammā akusalā... atha 
tumhe kālāmā pajaheyyātha._
____

But the practice of religious teachings is a different matter:

[quote, A.5.241]
____
Wrong view [of reality], wrong thought, wrong speech, wrong conduct, wrong 
means of livelihood, wrong endeavour, wrong mindfulness, wrong inward 
collectedness, wrong knowledge [of things according to reality], wrong 
liberation [from perceptually obscuring states]: this is called spiritually 
unwholesome.

_Micchādiṭṭhi micchāsaṅkappo micchāvācā micchākammanto 
micchāājīvo micchāvāyāmo micchāsati micchāsamādhi micchāñāṇaṃ 
micchāvimutti idaṃ vuccati bhikkhave akusalaṃ._
____

[quote, A.5.241]
____
Right perception [of reality], right thought, right speech, right conduct, 
right means of livelihood, right endeavour, right mindfulness, right inward 
collectedness, right knowledge [of things according to reality], right 
liberation [from perceptually obscuring states]: this is called spiritually 
wholesome.

_Sammādiṭṭhi sammāsaṅkappo sammāvācā sammākammanto sammāājīvo 
sammāvāyāmo sammāsati sammāsamādhi sammāñāṇaṃ sammāvimutti idaṃ 
vuccati bhikkhave kusalan ti._
____

=== Illustrations

.Illustration
====
kusalaṃ

welfare
====

[quote, Sn.v.981]
____
He asked after his comfort and welfare.

_Sukhañca kusalaṃ pucchi._
____

.Illustration
====
kusalā

wholesome
====

[quote, Sn.p.139]
____
These teachings which are wholesome, noble, and which lead to deliverance [from 
suffering] and to enlightenment.

_Ye te bhikkhave kusalā dhammā ariyā niyyānikā sambodhagāmino._
____

.Illustration
====
kusalā

wholesome
====

[quote, A.1.190]
____
Kālāmas, if you yourselves should consider: "These teachings are wholesome... 
you should accept and abide by them.

_Yadā tumhe kālāmā attanā'va jāneyyātha ime dhammā kusalā... atha 
tumhe kālāmā upasampajja vihareyyātha_
____

.Illustration
====
akusalehi

unwholesome
====

[quote, A.4.11-13]
____
A person whose spiritual qualities are wholly black and unwholesome

_samannāgato hoti ekanta kāḷakehi akusalehi dhammehī._
____

.Illustration
====
akusalā

unwholesome
====

[quote, A.1.190]
____
Kālāmas, if you yourselves should consider: "These teachings are 
unwholesome... you should abandon them.

_Yadā tumhe kālāmā attanāva jāneyyātha ime dhammā akusalā... atha 
tumhe kālāmā pajaheyyātha._
____

.Illustration
====
kusalaṃ

good
====

____
&#8203;[He would reflect:] "Since I received something, that is alright," or "Since I 
received nothing, that is good."

_Alatthaṃ yadidaṃ sādhu nālatthaṃ kusalaṃ iti_
____

[quote, Sn.v.712]
____
Being the same in either event, he [would] return to that same tree._

_Ubhayeneva so tādī rukkhaṃvupanivattati._
____

.Illustration
====
kusalā

good/excellent
====

[quote, S.5.374]
____
I would not say anything about Mahānāma the Sakyan except what is excellent 
and good.

_mahānāma sakkaṃ na kiñci vadāmi aññatra kalyāṇā aññatra kusalā 
ti._
____

COMMENT

_Kalyāṇā_ and _kusalā_ are synonyms here. Both could be rendered 
'excellent' or 'good.'

.Illustration
====
kusalā

the wise
====

[quote, Sn.v.830]
____
One should not dispute. Spiritual purity is not attained thereby, say the wise.

_na hi tena suddhiṃ kusalā vadanti._
____

.Illustration
====
kusalo

well behaved
====

[quote, Sn.v.536]
____
Whoever in this world amongst those living the religious life has attained the 
&#8203;[supreme] attainment, who is well behaved always, who understands the teaching, 
who is attached to nothing, who is liberated [from perceptually obscuring 
states], and in whom there are no states of repugnance, he is one of good 
conduct.

_Yo idha caraṇesu pattipatto kusalo sabbadā ājānāti dhammaṃ +
Sabbattha na sajjati vimutto paṭighā yassa na santi caraṇavā so._
____

.Illustration
====
kusalo

proficient
====

[quote, Th.v.1194]
____
In a moment I can fashion the bodily forms of 100,000 people. I am proficient 
in supernormal transformations. I am master of psychic power.

_Ahaṃ vikubbanāsu kusalo vasībhūtomhi iddhiyā._
____

.Illustration
====
kusalo

proficient
====

A meditator (_jhāyī_) can be:

____
proficient in attaining inward collectedness but improficient in maintaining 
inward collectedness

_samādhismiṃ samāpattikusalo hoti na samādhismiṃ ṭhitikusalo._
____

[quote, S.3.264-269]
____
proficient in maintaining inward collectedness but improficient in emerging 
from inward collectedness

_samādhismiṃ ṭhitikusalo hoti na samādhismiṃ vuṭṭhānakusalo._
____

.Illustration
====
kusalo

proficient
====

[quote, A.5.155]
____
Someone declares his arahantship. The Perfect One or his disciple who is a 
meditator, proficient in attaining inward collectedness, proficient in reading 
others' minds, proficient in reading the habits of others' minds, closely 
examines, questions and talks with him.

_tathāgato vā tathāgatasāvako vā jhāyī samāpattikusalo paracittakusalo 
paracittapariyāyakusalo samanuyuñjati samanugāhati samanubhāsati._
____

.Illustration
====
kusalena

proficient
====

[quote, Th.v.158]
____
With [the assistance of] the enlightened kinsman of the Sun clan, who is 
proficient in methods of teaching, having applied myself properly [to the 
eightfold path] I removed my mind from states of individual existence

_Upāyakusalenāhaṃ buddhenādiccabandhunā +
Yoniso paṭipajjitvā bhave cittaṃ udabbahinti._
____

.Illustration
====
kusalaṃ

spiritually wholesome; kusalaṃ, spiritual proficiency
====

____
An individual endowed with which ten qualities is one whom I describe as being 
perfect in what is spiritually wholesome, of the highest spiritual proficiency, 
an invincible ascetic who has attained the supreme attainment?

_sampannakusalaṃ paramakusalaṃ uttamapattipattaṃ samaṇaṃ ayojjhaṃ_
____

[quote, M.2.29]
____
The one possessed of the right perception [of reality] of a finished 
disciple... the right liberation [from perceptually obscuring states] of a 
finished disciple.

_asekhāya sammādiṭṭhiyā samannāgato hoti... asekhāya sammāvimuttiyā 
samannāgato hoti._
____

.Illustration
====
akusala

improficient
====

[quote, Vin.2.159]
____
Then that poor tailor, having kneaded mud and made bricks, erected wattle and 
daub walls. But because he was improficient, the piling was crooked and the 
wall fell down.

_Atha kho so daḷiddo tunnavāyo sāmaṃ cikkhallaṃ madditvā 
iṭṭhakāyo cinitvā kuḍḍaṃ uṭṭhāpesi. Tena akusalakena citā 
vaṅkā bhitti paripati._
____

.Illustration
====
kusalo

knowledgeable
====

____
On what grounds, bhante, can a bhikkhu be called knowledgeable about elements 
of existence?

_Kittāvatā pana bhante dhātukusalo bhikkhu ti alaṃ vacanāyā ti._
____

____
There are these eighteen elements of sensation, Ānanda:

_Aṭṭhārasa kho imā ānanda dhātuyo:_
____

____
The phenomenon of sight... phenomenon of advertence to the mental field.

_cakkhudhātu... manoviññāṇadhātu ti_
____

[quote, M.3.62]
____
Through knowing and seeing these eighteen elements of sensation [according to 
reality], Ānanda, a bhikkhu can be called knowledgeable about elements of 
existence.

_Imā kho ānanda aṭṭhārasa dhātuyo yato jānāti passati ettāvatā pi 
kho ānanda dhātukusalo bhikkhū ti alaṃ vacanāyā ti._
____

.Illustration
====
akusalo

unknowledgeable
====

[quote, A.5.359]
____
A cowherd cannot help his herd to prosper if he does not know about bodily 
form, and is unknowledgeable about physical characteristics

_na rūpaññū hoti na lakkhaṇa kusalo hoti._
____

.Illustration
====
kusalo

knowledgeable; akusalo, ignorant
====

____
'The man ignorant of the path' represents the common man.

_puriso amaggakusalo ti kho tissa puthujjanassetaṃ adhivacanaṃ_
____

[quote, S.3.108-9]
____
'The man knowledgeable about the path' represents the Perfect One, the Arahant, 
the Perfectly Enlightened One.

_Puriso maggakusalo ti kho tissa tathāgatassetaṃ adhivacanaṃ arahato 
sammāsambuddhassa._
____

.Illustration
====
kusalo

pandit
====

[quote, Sn.v.978]
____
Maintaining their own dogmatic views, contentious, different [so-called] 
pandits say: "Whoever knows this knows Perfect Truth. Whoever rejects it is not 
spiritually perfected."

_Sakaṃ sakaṃ diṭṭhiṃ paribbasānā vigayha nānā kusalā vadanti +
Yo evaṃ jānāti sa vedi dhammaṃ idaṃ paṭikkosamakevalī so._
____

.Illustration
====
kusalo

expert
====

[quote, M.1.395-6]
____
Bhante, I am well known as a charioteer, and an expert in the parts of a 
chariot. All the parts of a chariot are well known to me.

_Ahaṃ hi bhante rathiko saññato kusalo rathassa aṅgapaccaṅgānaṃ 
sabbāni me rathassa aṅgapaccaṅgāni suviditāni._
____

.Illustration
====
akusale

badly behaved
====

[quote, Vin.1.315]
____
Bhante, a transgression overcame us, in that, foolishly, stupidly, and badly 
behaved, we suspended a pure bhikkhu, not an offender, without cause, without 
reason.

_accayo no bhante accagamā yathā bāle yathā mūḷhe yathā akusale ye 
mayaṃ suddhaṃ bhikkhuṃ anāpattikaṃ avatthusmiṃ akāraṇe 
ukkhipimha._
____

.Illustration
====
akusalaṃ

badly behaved
====

[quote, D.1.85]
____
'A transgression overcame me, bhante, in that, foolishly, stupidly, and badly 
behaved, I deprived my father of life -- a righteous man, a righteous king -- 
for the sake of sovereign rulership.'

_Accayo maṃ bhante accagamā yathābālaṃ yathāmūḷhaṃ yathā 
akusalaṃ yo'haṃ pītaraṃ dhammikaṃ dhammarājānaṃ issariyassa 
kāraṇā jīvitā voropesiṃ._
____

.Illustration
====
kusalesu

spiritually wholesome
====

____
Also, bhante, the Blessed One's teaching concerning spiritually wholesome 
factors is unsurpassed.

_Aparaṃ pana bhante etadānuttariyaṃ yathā bhagavā dhammaṃ deseti 
kusalesu dhammesu._
____

[quote, D.3.102]
____
That is, these spiritually wholesome factors: the [contemplation of the] four 
bases of mindfulness, the four modes of right inward striving, the four paths 
to psychic power, the five spiritual faculties, the five spiritual powers, the 
seven factors of enlightenment, the eightfold path.

_Tatrime kusalā dhammā seyyathīdaṃ cattāro satipaṭṭhānā cattāro 
sammappadhānā cattāro iddhipādā pañcindriyāni pañca balāni satta 
bojjhaṅgā ariyo aṭṭhaṅgiko maggo._
____

.Illustration
====
kusala

spiritually wholesome; akusala, spiritually unwholesome
====

• Three spiritually unwholesome ways of thought: sensuous thought, 
unbenevolent thought, and malicious thought. +
_Tayo akusalavitakkā: kāmavitakko vyāpādavitakko vihiṃsāvitakko_.

• Three spiritually wholesome ways of thought: unsensuous thought, benevolent 
thought, compassionate thought. +
_Tayo kusalavitakkā: nekkhammavitakko avyāpādavitakko avihiṃsāvitakko_ 
(D.3.215).

.Illustration
====
akusalehi

spiritually unwholesome
====

[quote, M.1.303]
____
Secluded from sensuous pleasures and spiritually unwholesome factors, a bhikkhu 
enters and abides in first jhāna, which is accompanied by thinking and 
pondering, and rapture and physical pleasure born of seclusion [from sensuous 
pleasures and spiritually unwholesome factors].

_Idhāvuso visākha bhikkhu vivicceva kāmehi vivicca akusalehi dhammehi 
savitakkaṃ savicāraṃ vivekajaṃ pītisukhaṃ paṭhamaṃ jhānaṃ 
upasampajja viharati._
____

.Illustration
====
akusalā

spiritually unwholesome
====

[quote, S.4.178]
____
In seeing a visible object via the visual sense, do not grasp its aspects and 
features. Since by abiding with the faculty of sight unrestrained [from 
attraction and repulsion, through mindfulness], greed, dejection, and 
unvirtuous, spiritually unwholesome factors would pursue you.

_Cakkhunā rūpaṃ disvā mā nimittaggāhino ahuvattha mānuvyañjanaggāhino 
yatvādhikaraṇamenaṃ cakkhundriyaṃ asaṃvutaṃ viharantaṃ 
abhijjhādomanassā pāpakā akusalā dhammā anvāssaveyyuṃ._
____

.Illustration
====
kusala

spiritually wholesome
====

[quote, M.1.163]
____
'Having gone forth [into the ascetic life] in search of what is spiritually 
wholesome, seeking the supreme state of sublime peace, I approached Āḷāra 
Kālāma.'

_So evaṃ pabbajito samāno kiṃkusalagavesī anuttaraṃ santivarapadaṃ 
pariyesamāno yena āḷāro kālāmo tenupasaṅkamiṃ._
____

.Illustration
====
akusala

spiritually unwholesome
====

____
How is a bhikkhu an ascetic?

_Kathañca bhikkhave bhikkhu samaṇo hoti?_
____

[quote, M.1.280]
____
He has quieted down unvirtuous, spiritually unwholesome factors that are 
defiling, and which lead to renewed states of individual existence, suffering, 
unpleasant karmic consequences, and future birth, old age, and death.

_Samitāssa honti pāpakā akusalā dhammā saṅkilesikā ponobhavikā sadarā 
dukkhavipākā āyatiṃ jātijarāmaraṇīyā._
____

.Illustration
====
akusala

spiritually unwholesome
====

There are these three kinds of spiritually unwholesome thinking 
(_akusalavitakkā_). Which three?

____
thinking concerned with not wanting to be despised;

_anavaññattipaṭisaṃyutto vitakko_
____

____
thinking concerned with gains, honour, and renown

_lābhasakkārasilokapaṭisaṃyutto vitakko_
____

[quote, It.72]
____
thinking concerned with feeling sorry for others

_parānuddayatāpaṭisaṃyutto vitakko._
____

.Illustration
====
kusalānaṃ

spiritually wholesome; akusalānaṃ, spiritually unwholesome
====

____
If, friends, one could enter and abide amidst spiritually unwholesome factors 
and dwell happily in this very lifetime, without distress, vexation, and 
anguish, and if, with the break up of the body, after death, one could expect 
the realm of happiness, then the Blessed One would not praise the abandonment 
of spiritually unwholesome factors.

_Akusale cāvuso dhamme upasampajja viharato diṭṭhe ceva dhamme sukho 
vihāro abhavissa avighāto anupāyāso apariḷāho kāyassa ca bhedā 
parammaraṇā sugati pāṭikaṅkhā nayidaṃ bhagavā akusalānaṃ 
dhammānaṃ pahānaṃ vaṇṇeyya._
____

____
But because one who enters and abides amidst spiritually unwholesome factors 
abides in misery in this very lifetime, with distress, vexation, and anguish, 
and because he can expect [rebirth in] the plane of misery with the demise of 
the body at death, the Blessed One praises the abandonment of spiritually 
unwholesome factors.

_Yasmā ca kho āvuso. Akusale dhamme upasampajja viharato diṭṭheva dhamme 
dukkho vihāro savighāto saupāyāso sapariḷāho kāyassa ca bhedā 
parammaraṇā duggati pāṭikaṅkhā tasmā bhagavā akusalānaṃ 
dhammānaṃ pahānaṃ vaṇṇeti._
____

____
"If, friends, one who enters and abides amidst spiritually wholesome factors 
would abide in misery in this very lifetime, with distress, vexation, and 
anguish, and if, with the demise of the body at death, he could expect [rebirth 
in] the plane of misery, then the Blessed One would not praise the undertaking 
of spiritually wholesome factors.

_Kusale cāvuso dhamme upasampajja viharato diṭṭhe ceva dhamme dukkho 
vihāro abhavissa savighāto saupāyāso sapariḷāho kāyassa ca bhedā 
parammaraṇā duggati pāṭikaṅkhā nayidaṃ bhagavā kusalānaṃ 
dhammānaṃ upasampadaṃ vaṇṇeyya_
____

[quote, S.3.8-9]
____
But because one who enters and abides amidst spiritually wholesome factors 
abides happily in this very lifetime, without distress, vexation, and anguish, 
and because he can expect the realm of happiness with the demise of the body at 
death, the Blessed One praises the undertaking of spiritually wholesome 
factors."

_Yasmā ca kho āvuso kusale dhamme upasampajja viharato diṭṭhe ceva dhamme 
sukho vihāro avighāto anupāyāso apariḷāho kāyassa ca bhedā 
parammaraṇā sugati pāṭikaṅkhā tasmā bhagavā kusalānaṃ 
dhammānaṃ upasampadaṃ vaṇṇetī ti._
____

.Illustration
====
kusalaṃ

spiritually wholesome; kusala, what is spiritually wholesome
====

And what is spiritually wholesome (_katamañcāvuso kusalaṃ_)?

____
refraining from killing is spiritually wholesome

_pāṇātipātā veramaṇī kusalaṃ_
____

____
refraining from stealing is spiritually wholesome

_adinnādānā veramaṇī kusalaṃ_
____

____
refraining from sexual misconduct is spiritually wholesome

_kāmesumicchācārā veramaṇī kusalaṃ_
____

____
refraining from lying is spiritually wholesome

_musāvādā veramaṇī kusalaṃ_
____

____
refraining from malicious speech is spiritually wholesome

_pisuṇāya vācāya veramaṇī kusalaṃ_
____

____
refraining from harsh speech is spiritually wholesome

_pharusāya vācāya veramaṇī kusalaṃ_
____

____
refraining from frivolous speech is spiritually wholesome

_samphappalāpā veramaṇī kusalaṃ_
____

____
non-greed is spiritually wholesome

_anabhijjhā kusalaṃ_
____

____
goodwill is spiritually wholesome

_avyāpādo kusalaṃ_
____

____
right perception [of reality] is spiritually wholesome

_sammādiṭṭhi kusalaṃ_
____

____
And what is the origin of what is spiritually wholesome

_katamañcāvuso kusalamūlaṃ_
____

____
Non-greed is an origin of what is spiritually wholesome.

_alobho kusalamūlaṃ_
____

____
Non-hatred is an origin of what is spiritually wholesome.

_adoso kusalamūlaṃ_
____

[quote, M.1.47]
____
Discernment of reality is an origin of what is spiritually wholesome.

_amoho kusalamūlaṃ._
____

.Illustration
====
akusalā

spiritually unwholesome; kusala, what is spiritually wholesome
====

[quote, M.1.119]
____
When a bhikkhu is focusing on some meditation object that arouses unvirtuous, 
spiritually unwholesome thoughts connected with desire, hatred, and 
undiscernment of reality, then he should focus on some other meditation object 
connected with what is spiritually wholesome.

_Idha bhikkhave bhikkhunā yaṃ nimittaṃ āgamma yaṃ nimittaṃ 
manasikaroto uppajjanti pāpakā akusalā vitakkā chandūpasaṃhitāpi 
dosūpasaṃhitāpi mohūpasaṃhitāpi tena bhikkhave bhikkhunā tamhā 
nimittā aññaṃ nimittaṃ manasikātabbaṃ kusalūpasaṃhitaṃ._
____

.Illustration
====
kusalaṃ

spiritually wholesome; akusalaṃ, spiritually unwholesome
====

____
What is spiritually unwholesome?

_Katamañca bhikkhave akusalaṃ_
____

____
The tenfold path of wrong factors.

_micchādiṭṭhi micchāsaṅkappo micchāvācā micchākammanto 
micchāājīvo micchāvāyāmo micchāsati micchāsamādhi micchāñāṇaṃ 
micchāvimutti._
____

____
This is called spiritually unwholesome

_Idaṃ vuccati bhikkhave akusalaṃ._
____

____
What is spiritually wholesome?

_katamañca bhikkhave kusalaṃ_
____

____
The tenfold path of right factors.

_sammādiṭṭhi sammāsaṅkappo sammāvācā sammākammanto sammāājīvo 
sammāvāyāmo sammāsati sammāsamādhi sammāñāṇaṃ sammāvimutti._
____

[quote, A.5.241]
____
This is called spiritually wholesome

_Idaṃ vuccati bhikkhave kusalan ti._
____

.Illustration
====
kusala

spiritually wholesome
====

____
Bhikkhus, there are these four streams of merit, streams of what is spiritually 
wholesome, conditions that nourish happiness. What four?

_puññābhisandā kusalābhisandā sukhassāhārā_
____

[quote, S.5.391]
____
In this regard, a noble disciple has unshakeable faith in the [perfection of 
the] Buddha's [transcendent insight]... in the [significance of the] 
teaching... in the [praiseworthiness of the] community of disciples' 
&#8203;[application to the practice]... possesses the virtues dear to the Noble Ones

_ariyasāvako buddhe... dhamme... saṅghe aveccappasādena samannāgato 
hoti... ariyakantehi sīlehi samannāgato hoti._
____

.Illustration
====
akusalehi

spiritually unwholesome
====

[quote, A.2.12]
____
He is emancipated from unvirtuous, spiritually unwholesome factors that are 
defiling and which lead to renewed states of individual existence, suffering, 
unpleasant karmic consequences, and future birth, old age, and death.

_Visaṃyutto pāpakehi akusalehi dhammehi saṅkilesikehi ponobhavikehi 
sadarehi dukkhavipākehi āyatiṃ jātijarāmaraṇikehi._
____

.Illustration
====
kusalānaṃ

spiritually wholesome
====

[quote, D.3.58]
____
It is by the undertaking of spiritually wholesome factors that this merit 
increases.

_Kusalānaṃ bhikkhave dhammānaṃ samādānahetu evamidaṃ puññaṃ 
pavaḍḍhati._
____

.Illustration
====
akusalaṃ

spiritually unwholesome; kusalaṃ, spiritually wholesome
====

____
Conduct produced from, born of, due to, originated by greed, hatred, and 
undiscernment of reality is spiritually unwholesome and blameworthy.

_yaṃ bhikkhave lobhapakataṃ... dosapakataṃ... mohapakataṃ kammaṃ 
mohajaṃ mohanidānaṃ mohasamudayaṃ taṃ kammaṃ akusalaṃ taṃ 
kammaṃ sāvajjaṃ_
____

____
It has unpleasant karmic consequences and leads to the [further] origination of 
karmically consequential conduct. It does not lead to the ending of karmically 
consequential conduct.

_taṃ kammaṃ dukkhavipākaṃ taṃ kammaṃ kammasamudayāya saṃvattati. 
Na taṃ kammaṃ kammanirodhāya saṃvattati._
____

____
Conduct produced from, born of, due to, originated by non-greed, non-hatred, 
and discernment of reality is spiritually wholesome and blameless.

_yaṃ bhikkhave alobho... adoso... amohapakataṃ kammaṃ amohajaṃ 
amohanidānaṃ amohasamudayaṃ. Taṃ kammaṃ kusalaṃ taṃ kammaṃ 
anavajjaṃ_
____

[quote, A.1.263]
____
It has pleasant karmic consequences and leads to the ending of karmically 
consequential conduct. It does not lead to the origination of karmically 
consequential conduct.

_taṃ kammaṃ sukhavipākaṃ taṃ kammaṃ kammanirodhāya. Na taṃ 
kammaṃ kammasamudayāya saṃvattati._
____

.Illustration
====
kusalesu

spiritually unwholesome
====

[quote, D.3.145-6]
____
He was resolute in applying himself to spiritually wholesome factors... By 
undertaking that karmically consequential conduct, heaping it up, lavishly and 
abundantly, with the demise of the body at death he was reborn in the realm of 
happiness, in the heavenly worlds.

_daḷhasamādāno ahosi kusalesu dhammesu... so tassa kammassa katattā 
upacitattā ussannattā vipulantā kāyassa bhedā parammaraṇā sugatiṃ 
saggaṃ lokaṃ upapajjati._
____

