== Kvaci

=== Renderings

- _kvaci_: anywhere

- _kvaci_: in any way

=== Introduction

==== Tautology: 'all directions anywhere'

Kvaci means 'anywhere' (PED), but it is commonly paired with another locative 
adverb so it becomes redundant. For instance, 'all directions anywhere':

[quote, Ud.__4__7]
____
On traversing all directions with the mind one finds no one anywhere more 
beloved oneself.

_Sabbā disā anuparigamma cetasā +
Nevajjhagā piyataramattanā kvaci._
____

==== Tautology: 'in any place anywhere'

Or 'in any place anywhere' in the mocking, ironic, improbable verse:

[quote, S.1.218]
____
If there exists any place anywhere where without work one won't decline, that 
indeed is the Untroubled's path.

_Sace atthi akammena koci kvaci na jīvati nibbānassa hi so maggo._
____

==== Emphasis: 'in any way'

Sometimes _kvaci_ implies the emphasis, 'in any way':

1. Though a youth, he is not attached in any way.
+
****
_yo yobbane nopanibajjhate kvaci_ (Sn.v.218).
****

2. May attachment to charming things of any kind never in any way or in any 
place surge within me;
+
****
_Mā me kvacani katthaci kiñcana rajanīyesu dhammesu rāgo udapādi_ 
(A.3.170).
****

==== Other renderings: DOP and Bodhi

DOP seems to reject the emphatic effect of _kvacani_, because it explains it as 
'somewhere, anywhere, in or regard to anything.' But Bodhi accepts it, saying 
'Let no lust at all arise in me anywhere in any way regarding things 
provocative of lust' (NDB p.762).

=== Illustrations

==== kvacani, in any way

____
I am not in any way anything "belonging to anyone"

_nāhaṃ kvacani kassaci kiñcanatasmiṃ_
____

• ... And not in any way is there anywhere anything "belonging to me." +
_na ca mama kvacani katthaci kiñcanatātthī ti_ (M.2.263-4, A.1.206, 
A.2.176-7).

Comment:

The _Uposatha Sutta_ (A.1.206) says the particular application of this 
contemplation is in personal relationships, where:

1. a man's parents know him as their son, and he knows them as his parents
+
****
_ayaṃ amhākaṃ putto ti so pi jānāti ime mayhaṃ mātāpitaro ti_.
****

2. a man's slaves and servants know him as their master, and he knows them as 
his slaves and servants
+
****
_ayaṃ amhākaṃ ayyo ti. So pi jānāti ime mayhaṃ dāsakammakaraporisā 
ti._
****

This reflection therefore helps overcome the idea that beings possess each 
other.

