== Kāma

=== Renderings

- _kāma_: sensuous pleasure

- _kāma_: sensuous yearning

- _kāma_: want

- _kāma_: yearning

- _kāmā_: desiring

- _kāmā_: sensuous

- _kāmeti_: to yearn for

- _kāmaṃ_: willingly

- _kāmabhoginā_: devoted to sensuous pleasures

- _kāmabhoginā_: non-celibate

- _kāma_: sensuous plane of existence

=== Introduction

==== Five varieties of sensuous pleasure

The five varieties of sensuous pleasure (_pañcakāmaguṇā_) are visible 
objects, audible objects, smellable objects, tasteable objects, and tangible 
objects that are likeable, loveable, pleasing, agreeable, connected with 
sensuous pleasure, and charming (_iṭṭhā kantā manāpā piyarūpā 
kāmūpasaṃhitā rajanīyā_).

These pleasures are vile, coarse and ignoble (_mīḷhasukhaṃ 
puthujjanasukhaṃ anariyasukhaṃ_). They should not be pursued, developed or 
cultivated (_na sevitabbaṃ na bhāvetabbaṃ na bahulīkātabbaṃ_ M.1.454).

The five varieties of sensuous pleasure (_pañcakāmaguṇā_) are sometimes 
euphemistically called 'the music of the fivefold ensemble' (_pañcaṅgikena 
turiyena_: S.1.131).

==== Kāma: sexual pleasure

_Kāma_ strongly implies sexual pleasure (_mānusake kāme_: S.1.9). There is 
no other object which so overwhelms a man's mind as a woman, or a woman's mind, 
a man (_cittaṃ pariyādāya tiṭṭhati_: A.1.1).

==== Kāma: not just sex

But _kāma_ is not just sex. After all, the attractiveness of women is more 
than their sexuality. It is their wealth, virtue, industriousness, and ability 
to beget children (S.4.238). And during the pregnancy of the Bodhisatta's 
mother, the sensuous thoughts that arose in her mind did not involve men (_na 
bodhisattamātu purisesu mānasaṃ uppajjati kāmaguṇūpasaṃhitaṃ_) 
(D.2.13).

Likewise for men. When a group of young Licchavis discussed the 'five 
treasures,' the Buddha mocked them for their preoccupation with _kāma_ 
(_kāmaññeva ārabbha antarā kathā udapādi_), explaining the five 
treasures as not just the Woman Treasure, but the Elephant, Horse, Jewel, and 
Steward Treasures (D.2.172).

==== Bhikkhus and sensuous pleasure

Bhikkhus are not allowed the five varieties of sensuous pleasure:

____
He for whom the five varieties of sensuous pleasure are allowed, you can 
definitely conclude that this is not the practice of an ascetic, not the 
practice of a disciple of the Sakyans' Son.

_Yassa pañcakāmaguṇā kappanti ekaṃsenetaṃ gāmaṇi dhāreyyāsi 
assamaṇadhammo asakyaputtiyadhammo ti._
____

Such pleasure is only allowed to those for whom money is allowed:

[quote, S.4.326]
____
Those for whom gold and silver are allowed, the five varieties of sensuous 
pleasure are allowed._

_yassa kho gāmaṇi jātarūparajataṃ kappati pañcapi tassa kāmaguṇā 
kappanti._
____

Bhikkhus should regard sensuous pleasure like a [red-hot] charcoal pit:

• So, too, when sensuous pleasures are seen by a bhikkhu as similar to a 
&#8203;[red-hot] charcoal pit, then sensuous hankering, love, infatuation, and passion 
for sensuous pleasures do not lurk within him. +
_Evameva kho bhikkhave bhikkhuno aṅgārakāsūpamā kāmā diṭṭhā honti 
yathāssa kāme passato yo kāmesu kāmacchando kāmasneho kāmamucchā 
kāmapariḷāho so nānuseti_ (S.4.188).

Indeed, the undoing (_upaddava_) of a recluse is, once surrounded by laypeople, 
reverting to indulgence:

[quote, M.3.116]
____
Being visited by brahmans and householders from town and country, he becomes 
infatuated, falls in love, succumbs to greed, and reverts to luxury. This is 
called the teacher who is undone through the undoing of teachers.

_So anvāvaṭṭantesu brāhmaṇagahapatikesu negamesu ceva jānapadesu ca 
mucchati nikāyamati gedhaṃ āpajjati āvaṭṭati bāhullāya. Ayaṃ 
vuccatānanda upaddavo ācariyo ācariyūpaddavena._
____

==== Objects of sensuous pleasure

Objects of sensuous pleasure include:

- fancy carriages, earrings (M.1.365)

- palaces and female musicians (M.1.504).

- fields, property and gold, cattle and horses, slaves, servants, and maids 
(Sn.v.769).

- Heavenly objects of sensuous pleasure includes the company of celestial 
nymphs (_accharā_) in the Nandana Grove (M.1.505).

- For Wheel-turning monarchs such objects include the seven Treasures (M.3.172).

==== Allowances in times of sickness

Some items are considered not sensuous pleasures in the case of sickness. For 
instance, vehicles, sunshades, and sandals are allowed to bhikkhus and 
bhikkhunīs when they are sick.

==== Kāma: sensuous yearning

_Kāma_ can also mean 'sensuous yearning':

____
There are five varieties of sensuous pleasure.

_pañcime bhikkhave kāmaguṇā_
____

____
Visible objects known via the visual sense... tangible objects known via the 
tactile sense, all of which are likeable, loveable, pleasing, agreeable, 
connected with sensuous pleasure, and charming

_cakkhuviññeyyā rūpā... kāyaviññeyyā phoṭṭhabbā iṭṭhā 
kantāmanāpā piyarūpā kāmupasaṃhitā rajaniyā._
____

____
These however are not sensuous yearnings.

_Apica kho bhikkhave nete kāmā_
____

____
In the [terminology of the] Noble One's training system they are called the 
varieties of sensuous pleasure.

_kāmaguṇā nāmete ariyassa vinaye vuccanti_
____

____
The sensuous yearning of a man is his thoughts bound up with attachment.

_Saṅkapparāgo purisassa kāmo_
____

____
The world's attractive things are not sensuous yearning

_Nete kāmā yāni citrāni loke_
____

• The sensuous yearning of a man is his thoughts bound up with attachment. +
_Saṅkapparāgo purisassa kāmo_

____
The world's attractive things remain as they are

_Tiṭṭhanti citrāni tatheva loke_
____

[quote, A.3.411]
____
The wise eliminate their hankering for them

_Athettha dhīrā vinayanti chandan ti._
____

Comment:

We render _saṅkapparāgo_ as 'thoughts bound up with attachment' in 
accordance with the term 'thoughts bound up with attachment' (_saṅkappā 
rāganissitā_, A.1.280; Th.v.760; Dh.v.339).

==== Kāmadhātu: the sensuous plane of existence

So because the low plane of existence is called _kāmadhātu_, should it be 
called the sensuous plane of existence? Or the plane of sensuous yearning? For 
example, Bodhi calls it 'the sensory realm' (A.1.223) whereas Woodward and 
Walshe call it the 'world of sense-desire' (A.1.223; D.2.57). We prefer Bodhi's 
term for the following reason:

The _Lokāyatika Brāhmaṇa Sutta_ (A.4.430) says that in the [terminology of 
the] Noble One's training system, the five varieties of sensuous pleasure are 
called 'the world [of sensuous pleasure]' (_pañcime brāhmaṇā kāmaguṇā 
ariyassa vinaye loko ti vuccati_), and says that if a bhikkhu enters first 
jhāna, he is called a bhikkhu who has arrived at the end of the world (i.e. 
arrived at the end of the world [of sensuous pleasure], _lokassa antaṃ 
āgamma_).

But just as the jhānas transcend the five varieties of sensuous pleasure, so 
they are themselves transcended by the immaterial states of awareness, which 
are said to 'transcend the refined material states of awareness' (_atikkamma 
rūpe_) (M.1.34). Because the first of these spheres, the sphere of infinite 
space, is attained by 'completely transcending refined material states of 
awareness' (_sabbaso rūpasaññānaṃ samatikkamā_), it shows that the 
refined material states of awareness means the four jhānas.

Thus on attaining first jhāna, sensuous mental imagery is ended (_paṭhamaṃ 
jhānaṃ samāpannassa kāmasaññā niruddhā hoti_, A.4.409), and in 
attaining the state of awareness of boundless space, the perception of the 
refined material states of awareness is ended (_ākāsānañcāyatanaṃ 
samāpannassa rūpasaññā niruddhā hoti_, A.4.409). Thus there are three 
levels of meditative attainment. These three levels correspond to the three 
states of individual existence (_tayo bhavā_), namely:

- _kāmabhavo_: individual existence in the sensuous plane of existence 
(_kāmadhātu_)

- _rūpabhavo_: individual existence in the refined material plane of existence 
(_rūpadhātu_)

- _arūpabhavo_: individual existence in the immaterial plane of existence 
(_arūpadhātu_) (M.1.50).

The correspondence between the three levels of meditative attainment and the 
three states of individual existence is confirmed in connection to rebirth. 
Those practising first jhāna, which is the first of the refined material 
meditations, when they die, get reborn in the refined material plane of 
existence amongst the devas of the Brahmā group (_brahmakāyikānaṃ 
devānaṃ sahavyataṃ upapajjati_). Those who practise the state of awareness 
of boundless space, which is the first of the immaterial meditations, are 
reborn amongst the immaterial devas in the state of awareness of boundless 
space (_ākāsānañcāyatanūpagānaṃ devānaṃ sahavyataṃ upapajjati_).

Thus:

- the perception of the five varieties of sensuous pleasure corresponds to 
individual existence in the sensuous plane of existence (_kāmadhātu_)

- the refined material states of awareness correspond to the refined material 
plane of existence.

- immaterial states of awareness correspond to the immaterial plane of 
existence.

This shows that _kāmadhātu_ means 'the sensuous plane of existence,' not 'the 
plane of sensuous yearning.'

==== Sensuous, adjective

_Kāmā_ is sometimes used as an adjective: 'sensuous.'

[quote, M.1.433]
____
sensuous hankering for sensuous pleasure

_kāmesu kāmacchando._
____

[quote, M.3.125]
____
I do not recall a sensuous thought having ever arisen in me.

_nābhijānāmi kāmavitakkaṃ uppannapubbaṃ._
____

==== Possessions suitable for laymen devoted to sensuous pleasures

When bhikkhus entered a village with their sandals on, people complained, 
muttered, and grumbled that the bhikkhus were like laymen devoted to sensuous 
pleasures (_seyyathā pi gihī kāmabhogino ti_ Vin.1.194). This led to the 
Buddha forbidding bhikkhus entering the village with sandals on. Other similar 
events led to a many items being grouped as suitable for laymen devoted to 
sensuous pleasures (_gihī kāmabhogino_) but not bhikkhus. For example, animal 
hides (Vin.1.192), gold and silver ointment boxes (Vin.1.203), brightly 
coloured or beautiful robes (Vin.1.287, 306), jewellery (Vin.2.106), long hair 
(Vin.2.107), hair-dressing equipment (Vin.2.107), fleece clothes with the 
fleece outside (Vin.2.108); gold, silver and crystal bowls; ornamented 
bowl-stands; gold and silver knives (Vin.2.115); gold and silver thimbles 
(Vin.2.117); attractive waistbands (Vin.2.136); gold and silver buckles 
(Vin.2.136); large pillows (Vin.2.150).

==== Activities suitable for laymen devoted to sensuous pleasures, gihī kāmabhogino

Likewise there are activities suitable only for laymen devoted to sensuous 
pleasures, not bhikkhus: using mirrors (Vin.2.107), wearing make-up 
(Vin.2.107), singing (Vin.2.107), sharing dishes and cups (Vin.2.123); trimming 
one's hair with scissors (Vin.2.134); removing grey hairs (Vin.2.134); learning 
and teaching metaphysics and worldy knowledge (Vin.2.139); going to see 
dancing, singing or music (Vin.2.107; Vin.4.267); bathing with perfume 
(Vin.4.341); using sunshades (Vin.4.337); using vehicles (Vin.4.338); sharing 
beds (Vin.4.288); going to art galleries, public parks and lakes (Vin.4.298); 
financial transactions (Vin.3.239); keeping animals (_tiracchānagataṃ 
upaṭṭhāpenti_) (Vin.2.267); keeping male and female slaves and servants 
(_dāsaṃ... dāsiṃ... kammakāraṃ... kammakāriṃ upaṭṭhāpenti_) 
(Vin.2.267); engaging in trade (Vin.2.267).

==== Gihī kāmabhogino: non-celibate laypeople

The Buddha's lay disciples are divided into four groups, according to the sex 
and sexuality of their bodies. Here, we call _kāmabhogino_ 'non-celibate .' 
All disciples are 'clothed in white' (_odātavasanā_).

____
celibate men lay followers

_upāsakā gihī odātavasanā brahmacārino_
____

____
non-celibate men lay followers

_upāsakā gihī odātavasanā kāmabhogino_
____

____
celibate women lay followers,

_upāsikā gihiniyo odātavasanā brahmacāriṇiyo_
____

[quote, M.1.493]
____
non-celibate women lay followers

_upāsikā gihiniyo odātavasanā kāmabhoginiyo._
____

==== Food and 'sensuous pleasure'

Although food is pleasant, if it was considered a 'sensuous pleasure' the 
ascetic life would be impossible. It is nonetheless surprising that there are 
no rules on luxurious foods because the _Vatthūpama Sutta_ (M.1.38) shows that 
luxurious food is a spiritual obstruction for those with defiled mental states 
(_cittassa upakkilesā_) because it says that for the virtuous bhikkhu whose 
mind is collected (_cittaṃ samādhiyati_), even if he eats fine almsfood 'the 
black grains removed, with various curries and vegetables, that will not be a 
spiritual obstruction for him' (_nevassa naṃ hoti antarāyāya_, M.1.38). 
This implies that luxurious food is a spiritual obstruction for less 
accomplished bhikkhus.

==== Food: the training for bhikkhus

Regarding food, the training in restraint for bhikkhus does not concern the 
quality of the food but the timing, the quantity, and the bhikkhu's attitude:

- bhikkhus should ideally eat just once a day.

- they should not eat after midday.

- they should eat in moderation

- they should eat without either cleaving to what is delicious (_nājjhosāya 
bhuñje_) or rejecting what is unpalatable (_virodhamāsādusu nopadaṃsaye_ 
S.4.71; M.1.102; M.1.437).

==== Alcohol

Alcohol is not considered a sensuous pleasure even for Wheel-turning monarchs 
because, even by laypeople, it is not a pleasure to be enjoyed at all.

=== Illustrations

.Illustration
====
kāma

sensuous pleasure
====

[quote, D.1.245]
____
In the [terminology of the] Noble One's training system these five varieties of 
sensuous pleasure are called shackles and bondage [to individual existence].

_pañcime kāmaguṇā ariyassa vinaye andū ti pi vuccanti bandhanan ti pi 
vuccanti._
____

.Illustration
====
kāme

sensuous pleasures
====

[quote, Sn.v.769-770]
____
A man greedy for fields, for property and gold, cattle and horses, slaves and 
servants, maids and relatives, and many sensuous pleasures, is overpowered by 
what is weak.

_Khettaṃ vatthuṃ hiraññaṃ vā gavassaṃ dāsaporisaṃ +
Thiyo bandhū puthu kāme yo naro anugijjhati +
Abalā naṃ baliyanti._
____

.Illustration
====
kāmā

sensuous pleasures
====

[quote, D.1.36]
____
Sensuous pleasures are unlasting, existentially void, and destined to change, 
and from their change and alteration there arises grief, lamentation, physical 
pain, psychological pain, and vexation.

_Kāmā hi bho aniccā dukkhā vipariṇāmadhammā tesaṃ 
vipariṇāmaññathābhāvā uppajjanti sokaparidevadukkhadomanassupāyāsā._
____

.Illustration
====
kāmehi

sensuous pleasures
====

[quote, D.1.182]
____
Secluded from sensuous pleasures and spiritually unwholesome factors, he enters 
and abides in first jhāna, which is accompanied by thinking and pondering, and 
rapture and physical pleasure born of seclusion [from sensuous pleasures and 
spiritually unwholesome factors]. For him the mental imagery of previous 
sensuous pleasure ceases.

_So vivicceva kāmehi vivicca akusalehi dhammehi savitakkaṃ savicāraṃ 
vivekajaṃ pītisukhaṃ paṭhamaṃ jhānaṃ upasampajja viharati. Tassa 
yā purimā kāmasaññā sā nirujjhati._
____

.Illustration
====
kāma

sensuous pleasure
====

____
Whatever physical and psychological pleasure arises from the five varieties of 
sensuous pleasure is the sweetness of sensuous pleasures.

_Yaṃ kho bhikkhave ime pañcakāmaguṇe paṭicca uppajjati sukhaṃ 
somanassaṃ ayaṃ kāmānaṃ assādo_
____

[quote, M.1.87]
____
The elimination and abandonment of fondness and attachment regarding sensuous 
pleasures is the deliverance from sensuous pleasures.

_Yo kho bhikkhave kāmesu chandarāgavinayo chandarāgappahānaṃ idaṃ 
kāmānaṃ nissaraṇaṃ._
____

.Illustration
====
kāmā

sensuous pleasures
====

____
Sensuous pleasures -- attractive, sweet, and charming -- distract the mind 
through their many different forms.

_Kāmā hi citrā madhurā manoramā virūparūpena mathenti cittaṃ_
____

[quote, M.2.74]
____
Seeing danger in the varieties of sensuous pleasure, I went forth [into the 
ascetic life], O king.

_Ādīnavaṃ kāmaguṇesu disvā tasmā ahaṃ pabbajitomhi rāja._
____

.Illustration
====
kāma

sensuous pleasure
====

[quote, M.3.114]
____
If a bhikkhu on reflection knows that his mind has some dealing with some 
aspect of the five varieties of sensuous pleasure, then he knows that he has 
undiscarded fondness and attachment regarding the five varieties of sensuous 
pleasure.

_atthi kho me imesu pañcasu kāmaguṇesu aññatarasmiṃ vā 
aññatarasmiṃ vā āyatane uppajjati cetaso samudācāro ti. Evaṃ 
santametaṃ ānanda bhikkhu evaṃ pajānāti yo kho imesu pañcasu 
kāmaguṇesu chandarāgo so me appahīno ti._
____

.Illustration
====
kāmā

sensuous pleasures; kāma, sensuous
====

[quote, S.4.188]
____
So, too, when sensuous pleasures are regarded by a bhikkhu as similar to a 
&#8203;[red-hot] charcoal pit, sensuous hankering, love, infatuation, and passion for 
sensuous pleasures do not lurk within him.

_Evameva kho bhikkhave bhikkhuno aṅgārakāsūpamā kāmā diṭṭhā honti 
yathāssa kāme passato yo kāmesu kāmacchando kāmasneho kāmamucchā 
kāmapariḷāho so nānuseti._
____

.Illustration
====
kāma

sensuous
====

[quote, M.1.454]
____
Now, Udāyī, the physical and psychological pleasure that arises from the five 
varieties of sensuous pleasure is called sensuous pleasure._

_Yaṃ kho udāyi ime pañcakāmaguṇe paṭicca uppajjati sukhaṃ 
somanassaṃ idaṃ vuccati kāmasukhaṃ._
____

.Illustration
====
kāma

sensuous
====

• Friend, in the eighty years since I went forth [into the ascetic life] I do 
not recall a sensuous mental image having ever arisen in me. +
_Asīti me āvuso kassapa vassāni pabbajitassa nābhijānāmi kāmasaññaṃ 
uppannapubbaṃ_ (M.3.125).

.Illustration
====
kāmā

yearnings
====

____
Master Gotama, we have such yearnings, desires, and aspirations as these:

_mayaṃ bho gotama evaṃ kāmā evañchandā evaṃ adhippāyā_
____

[quote, S.5.353]
____
'May we dwell in a home crowded with children! May we enjoy Kāsian sandalwood! 
May we wear garlands, fragrances, and perfumes! May we receive gold and silver! 
With the demise of the body at death, may we be reborn in the realm of 
happiness, in the heavenly worlds!'

_puttasambādhasayanaṃ ajjhāvaseyyāma. Kāsikacandanaṃ paccanubhaveyyāma 
mālāgandhavilepanaṃ dhāreyyāma jātarūparajataṃ sādiyeyyāma. 
Kāyassa bhedā parammaraṇā sugatiṃ saggaṃ lokaṃ upapajjeyyāma._
____

.Illustration
====
kāmayamānassa

yearning; kāmaṃ, sensuous pleasure
====

____
If, yearning for sensuous pleasure, it prospers for him, he's ecstatic, yes, 
the mortal who gets what he wants.

_Kāmaṃ kāmayamānassa tassa ce taṃ samijjhati +
Addhā pītimano hoti laddhā macco yadicchati_
____

[quote, Sn.v.766-7]
____
But yearning and desirous, if that being's pleasures diminish he is as wounded 
as if pierced by an arrow.

_Tassa ce kāmayānassa chandajātassa jantuno +
Te kāmā parihāyanti sallaviddhova ruppati._
____

.Illustration
====
kāmā

yearning
====

____
Bhikkhus, for the most part beings have such yearnings, desires, and aspirations

_yebhuyyena bhikkhave sattā evaṃ kāmā evaṃ chandā evaṃ adhippāyā_
____

[quote, M.1.309]
____
'If only unlikeable, unloveable, and displeasing things would diminish and 
likeable, loveable, and pleasing things would increase!'

_aho vata aniṭṭhā akantā amanāpā dhammā parihāyeyyuṃ iṭṭhā 
kantā manāpā dhammā abhivaḍḍheyyunti._
____

.Illustration
====
kāmemī

yearn for
====

[quote, M.2.33]
____
I want and yearn for the most beautiful girl in this country

_ahaṃ yā imasmiṃ janapade janapadakalyāṇī taṃ icchāmi taṃ 
kāmemī ti._
____

.Illustration
====
kāmo

yearning
====

[quote, S.2.99-100]
____
A man would come along wanting to live, not die, yearning for pleasure and 
loathing pain.

_Atha puriso āgaccheyya jīvitukāmo amaritukāmo sukhakāmo 
dukkhapaṭikkūlo._
____

.Illustration
====
kāmaṃ

willingly
====

[quote, M.1.481]
____
Willingly let just my skin, sinews and bone remain, and let the flesh and blood 
dry up on my body, but my right effort shall not be relaxed so long as I have 
not attained what can be attained by manly strength, by manly energy, by manly 
application [to the practice].

_kāmaṃ taco ca nahāru ca aṭṭhi ca avasissatu upasussatu sarīre 
maṃsalohitaṃ yaṃ taṃ purisatthāmena purisaviriyena purisaparakkamena 
pattabbaṃ na taṃ apāpuṇitvā viriyassa satthānaṃ bhavissatī ti._
____

.Illustration
====
kāmā

want
====

[quote, D.1.94]
____
'Ambaṭṭha, this is a rightful question for you which you may not want to 
answer.'

_ayaṃ kho pana te ambaṭṭha sahadhammiko pañho āgacchati akāmāpi 
vyākātabbo._
____

.Illustration
====
kāmā

desiring
====

Once a certain bhikkhu had gone for his daytime abiding, he kept thinking 
unvirtuous, thoughts associated with the household life. Then the deva 
inhabiting that woodland grove, being tenderly concerned for that bhikkhu, 
desiring his spiritual well-being (_atthakāmā_), desiring to stir up in him 
an earnest attitude [to the practice] (_saṃvejetukāmā_), approached him and 
addressed him in verses (S.1.197).

.Illustration
====
kāmā

desire
====

[quote, S.2.198]
____
'May those desiring gains acquire them; may those desiring merit do meritorious 
deeds!'

_labhantu lābhakāmā puññakāmā karontu pana puññānī ti._
____

.Illustration
====
kāmabhoginā

devoted to sensuous pleasures
====

[quote, Ud.65]
____
This is hard for you to know, great king, a layman devoted to sensuous 
pleasures, living in a home crowded with children, using Kāsian sandalwood, 
wearing garlands, fragrances, and perfumes, accepting gold and silver.

_Dujjānaṃ ko panetaṃ mahārāja tayā gihinā kāmabhoginā 
puttasambādhasayanaṃ ajjhāvasantena kāsikacandanaṃ paccanubhontena 
mālāgandhavilepanaṃ dhārayantena jātarūparajataṃ sādiyantena._
____

.Illustration
====
kāmabhogino

devoted to sensuous pleasures
====

[quote, Vin.2.107]
____
Bhikkhus examined a facial mark in a mirror and in a bowl of water. People 
complained, muttered, and grumbled that they were like laymen devoted to 
sensuous pleasures

__ādāse pi udakapatte pi mukhanimittaṃ olokenti. Manussā ujjhāyanti 
khīyanti vipācenti seyyathā pi gihī kāmabhogino ti._
____

