== Limpati

=== Renderings

- _limpati_: to tarnish

- _limpati_: to cleave to

- _lippati_: to be tarnished by

- _upalimpati_: to cleave to

- _upalippati_: to be tarnished by

=== Introduction

==== Spelling: lippati and limpati

PED says that in the _Suttanipāta_, whether the spelling is _limpati_ or 
_lippati_ is 'doubtful,' because both words are found as readings, but it 
acknowledges that _lippati_ is passive. Therefore _limpati_ is active.

Support for either spelling can be found amongst the various sutta editions, so 
we choose spelling according to our own schedule. Where the passive sense is 
meant, we choose _lippati_, _lippasi_ and _upalippati_ in preference to 
_limpati_, _limpasi_ and _upalimpati_. This spelling is usually supported by 
the VRI edition, and usually unsupported by the BJT edition.

==== Case indicators

- The passive sense (_lippati_) is indicated by the instrumental case.

- The active sense (_limpati_) takes an object in the locative case.

==== Limpati: cleave to, or tarnish

The active sense (_limpati_) mostly means 'cleave to,' but occasionally 
'tarnish':

- Just as a waterdrop does not cleave to a lotus leaf (_udabindu yathāpi 
pokkhare... na limpati_)... likewise the sage does not cleave to what is seen 
(_evaṃ muni nopalimpati yadidaṃ diṭṭha_ Sn.v.812).

[quote, Sn.v.811]
____
Lamentation and stinginess do not tarnish him, just as water does not tarnish a 
lotus leaf.

_Tasmiṃ paridevamaccharaṃ paṇṇe vāri yathā na limpati._
____

==== Lippati: tarnished by [attachment to]

The passive sense (_lippati_) always means 'tarnished by [attachment to]' or 
'tarnished by [contact with].'

- a white lotus is untarnished by [contact with] water (_nūpalippati_ A.2.39).

The advantage of these parentheses can be seen in illustrations below, but 
consider this one:

[quote, Th.v.1180]
____
He is untarnished by [attachment to] originated phenomena as the lotus is 
untarnished by [contact with] water.

_Puṇḍarīkaṃ va toyena saṅkhārenupalippati._
____

Norman says: 'He is not defiled by the constituent elements as the lotus is not 
defiled by water.' But constituent elements are not themselves defiling. As the 
suttas say:

[quote, A.3.411]
____
The world's attractive things remain as they are. The wise eliminate their 
hankering for them.

_Tiṭṭhanti citrāni tatheva loke athettha dhīrā vinayanti chandan ti._
____

==== Upalitta: past participle

_Upalitta_ operates as the past participle of both _upalimpati_ and 
_upalippati_. Thus it means either 'one who cleaves' or 'one who is tarnished 
by [attachment to].'

==== Upa- prefix

The _upa_- prefix is insignificant. It associated with both cleaving and 
tarnishing. Words with or without the prefix are used interchangeably.

=== Illustrations: limpati

.Illustration
====
limpati

cleaves to
====

[quote, Thī.v.388]
____
Knowing that what is originated is unlovely, my mind cleaves to nothing at all.

_Saṅkhatamasubhan ti jāniya sabbattheva mano na limpati._
____

.Illustration
====
upalimpati

cleave to; limpati, cleave to
====

[quote, Sn.v.812]
____
Just as a waterdrop does not cleave to a lotus leaf, just as water does not 
cleave to a lotus flower, likewise the sage does not cleave to what is seen, 
heard, sensed, [or cognised].

_Udabindu yathāpi pokkhare padume vāri yathā na limpati +
Evaṃ muni nopalimpati yadidaṃ diṭṭhasutaṃ mutesu vā._
____

.Illustration
====
limpati

cleave to
====

[quote, Sn.v.625]
____
Whoever does not cleave to sensuous pleasures as water does not cleave to a 
lotus leaf, or as a mustard seed does not cleave to the tip of an arrow, he is 
what I call a Brahman.

_Vāri pokkharapatte va āraggeriva sāsapo +
Yo na limpati kāmesu tamahaṃ brūmi brāhmaṇaṃ._
____

.Illustration
====
limpati

cleave to
====

[quote, Sn.v.778]
____
A wise person does not cleave to what is seen or heard.

_Na limpati diṭṭhasutesu dhīro._
____

.Illustration
====
limpasi

cleave to; upalimpati, cleave to
====

[quote, Sn.v.547]
____
As a beautiful white lotus does not cleave to water, so you do not cleave to 
merit and demerit.

_Puṇḍarikaṃ yathā vaggu toye na upalimpati +
Evaṃ puññe ca pāpe ca ubhaye tvaṃ na limpasi._
____

=== Illustrations: lippati

.Illustration
====
nupalippati

untarnished
====

[quote, A.3.347]
____
He is untarnished by [attachment to] the world [of phenomena], like the lotus 
is untarnished by [contact with] water.

_Nūpalippati lokena toyena padumaṃ yathā._
____

.Illustration
====
nūpalippati

untarnished; nūpalitto, untarnished
====

[quote, A.2.39]
____
Just as a beautiful white lotus is untarnished by [contact with] water, I am 
untarnished by [attachment to] the world. Therefore, brahman, I am a Buddha.

_Puṇḍarīkaṃ yathā vaggu toyena nūpalippati +
Nūpalittomhi lokena tasmā buddhosmi brāhmaṇā ti._
____

.Illustration
====
alippamāno

untarnished
====

[quote, Sn.v.456]
____
Clad in robes, I live the religious life without a home, with a shaven head, 
with ego completely extinguished, untarnished in the world by [attachment to] 
human beings.

_Saṅghāṭivāsī agaho carāmi nivuttakeso abhinibbutatto +
Alippamāno idha māṇavehi._
____

.Illustration
====
upalippati

untarnished
====

• [He is] like the fragrant and charming lotus born in water: it grows in 
water but is untarnished by [contact with] water. Likewise, the Buddha born 
into the world dwells in the world yet is untarnished by [attachment to] the 
world, just as the lotus is untarnished by [contact with] water. +
☸ _Yathāpi udake jātaṃ puṇḍarīkaṃ pavaḍḍhati +
Nopalippati toyena sucigandhaṃ manoramaṃ. +
Tatheva ca loke jāto buddho loke viharati +
Nopalippati lokena toyena padumaṃ yathā_ (Th.v.700-1) (A.3.347).

=== Illustrations: litto

.Illustration
====
upalitto

untarnished
====

[quote, Sn.v.845]
____
As the prickly water lotus is untarnished by [contact with] water and mud, so 
the sage, professing peace, and free of greed, is untarnished by [attachment 
to] sensuous pleasure and the world [of phenomena].

_Elambujaṃ kaṇṭakaṃ vārijaṃ yathā jalena paṅkena canupalittaṃ +
Evaṃ muni santivādo agiddho kāme ca loke ca anupalitto._
____

.Illustration
====
upalitto

cleaving
====

[quote, Sn.v.790]
____
Not cleaving to merit and demerit

_Puññe ca pāpe ca anupalitto._
____

.Illustration
====
upalitto

cleaving
====

[quote, Sn.v.779]
____
The sage, not cleaving to possessions.

_pariggahesu muni nopalitto._
____

