== Mada

=== Renderings

- _mada_: exuberance

- _madanīya_: intoxicating

- _matta_: intoxicated

=== Illustrations

.Illustration
====
mado

exuberance
====

[quote, A.3.72]
____
In the youth of beings, there is an exuberance on account of youth, intoxicated 
with which they misconduct themselves by way of body, speech, and mind.

_Atthī bhikkhave sattānaṃ yobbane yobbanamado yena madena mattā kāyena 
duccaritaṃ caranti vācāya duccaritaṃ caranti manasā duccaritaṃ 
caranti._
____

[quote, A.3.72]
____
In the health of beings, there is an exuberance on account of health, 
intoxicated with which they misconduct themselves by way of body, speech, and 
mind.

_Atthi bhikkhave sattānaṃ ārogye ārogyamado yena madena mattā kāyena 
duccaritaṃ caranti vācāya duccaritaṃ caranti manasā duccaritaṃ 
caranti._
____

[quote, A.3.72]
____
In the life of beings, there is an exuberance on account of life, intoxicated 
with which they misconduct themselves by way of body, speech, and mind.

_Atthi bhikkhave sattānaṃ jīvite jīvitamado yena madena mattā kāyena 
duccaritaṃ caranti vācāya duccaritaṃ caranti manasā duccaritaṃ 
caranti._
____

.Illustration
====
mado

exuberance
====

[quote, A.1.146]
____
When I reflected thus my exuberance on account of youth was completely 
abandoned.

_Tassa mayhaṃ bhikkhave iti paṭisañcikkhato yo yobbane yobbanamado so 
sabbaso pahīyi._
____

[quote, A.1.146]
____
When I reflected thus my exuberance on account of health was completely 
abandoned.

_Tassa mayhaṃ bhikkhave iti paṭisañcikkhato yo ārogye ārogyamado so 
sabbaso pahīyi._
____

[quote, A.1.146]
____
When I reflected thus my exuberance on account of life was completely abandoned.

_Tassa mayhaṃ bhikkhave iti paṭisañcikkhato yo jīvite jīvitamado so 
sabbaso pahīyī'ti._
____

.Illustration
====
mada

exuberance
====

____
Intoxicated with the exuberance on account of youth a bhikkhu gives up the 
training and returns to lay life.

_Yobbanamadamatto vā bhikkhave bhikkhu sikkhaṃ paccakkhāya 
hīnāyāvattati._
____

____
Intoxicated with the exuberance on account of health a bhikkhu gives up the 
training and returns to lay life.

_Ārogyamadamatto vā bhikkhave bhikkhu sikkhaṃ paccakkhāya hīnāyāvattati_
____

[quote, A.1.147]
____
Intoxicated with the exuberance on account of life a bhikkhu gives up the 
training and returns to lay life.

_jīvitamadamatto vā bhikkhave bhikkhu sikkhaṃ paccakkhāya 
hīnāyāvattatī' ti._
____

.Illustration
====
mada

exuberance
====

[quote, Sn.v.218]
____
A sage, living the religious life, abstaining from sexual intercourse, who, 
though a youth, is not attached in any way, abstaining from [any form of] 
exuberance and from negligence [in the practice], free [from individual 
existence], the wise know him as truly a sage.

_Muniṃ carantaṃ virataṃ methunasmā yo yobbane nopanibajjhate kvaci +
Madappamādā virataṃ vippamuttaṃ taṃ vāpi dhīrā muniṃ vedayanti._
____

.Illustration
====
madāya

exuberance
====

[quote, M.3.134]
____
Properly reflecting, you should use almsfood not for fun, not for exuberance, 
not for the sake of comeliness and good looks, but just for the maintenance and 
nourishment of this [wretched human] body for restraining its troublesomeness, 
for supporting the religious life.

_Paṭisaṅkhā yoniso āhāraṃ āhāreyyāsi neva davāya na madāya na 
maṇḍanāya na vibhūsanāya yāvadeva imassa kāyassa ṭhitiyā yāpanāya 
vihiṃsūparatiyā brahmacariyānuggahāya._
____

.Illustration
====
madamatto

intoxicated
====

[quote, Th.v.423]
____
Intoxicated with my superior parentage, wealth, and authority, I walked the 
earth intoxicated with the form and complexion of my body.

_Jātimadena mattohaṃ bhogaissariyena ca +
Saṇṭhānavaṇṇarūpena madamatto acārihaṃ._
____

.Illustration
====
madanīyā

intoxicating
====

[quote, D.2.234]
____
Sensuous pleasures are intoxicating

_Madanīyā kāmā._
____

.Illustration
====
madanīyaṃ

intoxicating
====

[quote, A.3.68]
____
I see no single visible object so attractive, so sensuous, so intoxicating, so 
captivating, so infatuating, so obstructive to the reaching of unsurpassed 
safety from the danger of bondage [to individual existence], as the sight of a 
woman.

_Nāhaṃ bhikkhave aññaṃ ekarūpampi samanupassāmi yaṃ evaṃ 
rajanīyaṃ evaṃ kamanīyaṃ evaṃ madanīyaṃ evaṃ bandhanīyaṃ 
evaṃ mucchanīyaṃ evaṃ antarāyakaraṃ anuttarassa yogakkhemassa 
adhigamāya yathayidaṃ bhikkhave itthirūpaṃ._
____

.Illustration
====
madanīyo

intoxicating
====

[quote, A.4.263]
____
The music of the devas was beautiful, attractive, sensuous, lovely, and 
intoxicating.

_vaggu ca rajanīyo ca kamanīyo ca pemanīyo ca madanīyo ca._
____

.Illustration
====
majjī

intoxicated; madanīyesu, intoxicating
====

[quote, A.2.120]
____
May my mind not be intoxicated with intoxicating things

_Mā me madanīyesu dhammesu cittaṃ majjī ti._
____

