== Mama

=== Renderings

- _mama_: my

- _mama_: mine

- _mama_: belonging to me

- _mama_: "[in reality] mine"

=== Introduction

==== Mama

_Mama_ is the genitive of _ahaṃ,_ i.e. 'of me.' The genitive case indicates 
close connection, not just possession. Therefore it covers a range of concepts 
such as 'belonging to me' or 'associated with me' or 'connected with me.' It 
can be rendered as either 'my' or 'mine.'

[quote, D.2.120]
____
My life (life belonging to me) is short

_parittaṃ mama jīvitaṃ._
____

[quote, D.2.144]
____
Beckon Ānanda in my name (name connected with me) 

_mama vacanena ānandaṃ āmantehi._
____

[quote, D.2.166]
____
Listen, lords, to my proposal (proposal connected with me)

_mama ekavākyaṃ._
____

[quote, D.2.196]
____
Those eighty-four thousand cities of which Kusāvatī was chief were mine 
(cities belonging to me)

_mama tāni caturāsītinagarasahassāni kusāvatīnagarapamukhāni._
____

[quote, D.2.212]
____
He is sitting on my couch (couch belonging to me)

_mama pallaṅke._
____

[quote, D.2.284]
____
They became my disciples (disciples associated with me)

_mama yeva sāvakā sampajjanti._
____

==== Me

_Me_ is synonymous with _mama_. For example:

[quote, M.2.104]
____
my enemies

_disā hi me._
____

[quote, M.1.230]
____
my [absolute] Selfhood

_me attā._
____

[quote, Ud.46]
____
my life

_me jīvitaṃ._
____

[quote, M.1.12]
____
my disciples

_me sāvakā._
____

[quote, S.1.112]
____
this is not mine

_n'etaṃ me._
____

==== Rendering doctrinal contexts

But things that are conventionally mine are not [in reality] mine. We word 
doctrinal contexts accordingly, for example by rendering _n'etaṃ mama_ as 
'This is "not [in reality] mine."'

The parenthesis '[in reality]' is justified because of _mama_'s link to 
_yathābhūtaṃ_:

[quote, S.4.1]
____
What is void of personal qualities should be seen according to reality with 
perfect penetrative discernment as "not [in reality] mine," "not [in reality] 
what I am," "not my [absolute] Selfhood"

_yadanattā taṃ n'etaṃ mama n'eso'hamasmi na me so attā ti evametaṃ 
yathābhūtaṃ sammappaññāya daṭṭhabbaṃ._
____

==== Inverted commas

Inverted commas are used in the way we have done because the Buddha would tell 
bhikkhus to see things as 'not mine.' He obviously did not mean that their five 
aggregates were not his, the Buddha's (_n'etaṃ mama_).

If an object either one's own or another's is "not [in reality] mine," then it 
is not something that anyone, myself or another, could say is "[in reality] 
mine." The reflection on _n'etaṃ mama_ thus embraces not just one's own 
perspective on the world, but also one's insight into the perspective of others.

=== Illustrations

.Illustration
====
mama

of mine
====

A disciple of mine (_mama sāvako_) sees each of the five aggregates according 
to reality with perfect penetrative discernment (_yathābhūtaṃ 
sammappaññāya passati_): M.1.234).

.Illustration
====
mama

belonging to me
====

____
I am not in any way anything "belonging to anyone"

_nāhaṃ kvacani kassaci kiñcanatasmiṃ_
____

• And not in any way is there anywhere anything "belonging to me." +
_na ca mama kvacani katthaci kiñcanatātthī ti_ (M.2.263-4, A.1.206, 
A.2.176-7).

Comment:

The Uposatha Sutta says the particular application of this contemplation is in 
personal relationships, where usually a man's parents know him as their son, 
and he knows them as his parents ☸ _ayaṃ amhākaṃ putto ti so pi jānāti 
ime mayhaṃ mātāpitaro ti_.

Similarly, his slaves and servants know him as their master, and he knows them 
as his slaves and servants ☸ _ayaṃ amhākaṃ ayyo ti. So pi jānāti ime 
mayhaṃ dāsakammakaraporisā ti._

The reflection therefore overcomes the idea that beings possess each other 
(A.1.206).

.Illustration
====
mama

"[in reality] mine"
====

[quote, M.3.265]
____
I regard these things as "not [in reality] mine," "not [in reality] what I am," 
"not my [absolute] Selfhood."'

_n'etaṃ mama n'eso'hamasmi na me so attā ti samanupassāmi._
____

.Illustration
====
mama

"[in reality] mine"
====

• Whatever bodily form... advertence, past, future, or present, internal or 
external, gross or subtle, inferior or sublime, far or near, one perceives all 
advertence according to reality with perfect penetrative discernment as "not 
&#8203;[in reality] mine," "not [in reality] what I am," "not my [absolute] Selfhood." 
+
_Yaṃ kiñci viññāṇaṃ atītānāgatapaccuppannaṃ ajjhattaṃ vā 
bahiddhā vā oḷārikaṃ vā sukhumaṃ vā hīnaṃ vā paṇītaṃ vā 
yaṃ dūre santike vā sabbaṃ viññāṇaṃ n'etaṃ mama n'eso'hamasmi na 
me so attā_ ti (M.3.18-9).

