== Manosañcetanāhāro

=== Renderings

- _manosañcetanāhāro_: the existential nourishment of mental intentionality

=== Introduction

==== Existential nourishment

____
There are these four kinds of existential nourishment for the maintenance of 
beings that have been brought into existence and for the assistance of those 
about to arise [into new existence]

_Cattāro... āhārā bhūtānaṃ vā sattānaṃ ṭhitiyā sambhavesīnaṃ 
vā anuggahāya._
____

1. physical food, gross or subtle
+
****
_kabaliṅkāro āhāro oḷāriko vā sukhumo vā_
****

2. secondly, sensation;
+
****
_phasso dutiyo_
****

3. thirdly, mental intentionality;
+
****
_manosañcetanā tatiyā_
****

4. fourthly, the stream of sense consciousness
+
****
_viññāṇaṃ catutthaṃ_ (M.1.48).
****

Comment:

Norman views _sambhavesīnaṃ_ as the future active participle in -_esin_ 
(Elders Verses I, n.527), to be translated with the words 'about to.'

==== Manosañcetanāhāro: red-hot charcoal pit simile

The scriptures hardly clarify the meaning of _manosañcetanāhāro._ For 
example, the _Puttamaṃsa Sutta_ says it can be compared to a man being 
dragged reluctantly towards a red-hot charcoal pit, but it is not clear which 
aspect of the simile is illustrative of _manosañcetanāhāro_. We therefore 
look elsewhere for an explanation.

==== Sañcetanā: classification systems

_Sañcetanā_ is classified according to either objects or means, as follows:

1. intentionality concerning visible objects, audible objects, smellable 
objects, tasteable objects, tangible objects, and mentally known objects ** +
**☸ _rūpasañcetanā saddasañcetanā gandhasañcetanā rasasañcetanā 
phoṭṭhabbasañcetanā dhammasañcetanā_ (D.2.309).

2. intentionality by way of body, speech, and mind
+
****
_kāyasañcetanā_, _vacīsañcetanā manosañcetanā_ (S.2.40).
****

The latter classification occurs in the following passage:

____
When there is the body, then on account of bodily intentionality, pleasure and 
pain arise for oneself;_

_Kāye vā hānanda sati kāyasañcetanāhetu uppajjati ajjhattaṃ 
sukhadukkhaṃ_
____

____
When there is speech, then on account of verbal intentionality, pleasure and 
pain arise for oneself;_

_vācāya vā hānanda sati vacīsañcetanāhetu uppajjati ajjhattaṃ 
sukhadukkhaṃ_
____

[quote, S.2.40]
____
When there is the mind, then on account of mental intentionality, pleasure and 
pain arise for oneself -- and with uninsightfulness into reality as the 
necessary condition.

_mane vā hānanda sati manosañcetanāhetu uppajjati ajjhattaṃ 
sukhadukkhaṃ avijjāpaccayā ca._
____

==== Manosañcetanāhāro and taṇhā

The _Puttamaṃsa Sutta_ links mental intentionality to _taṇhā_, saying that:

[quote, S.2.100]
____
When the existential nourishment of mental intentionality is profoundly 
understood, the three kinds of craving are profoundly understood.

_manosañcetanāya bhikkhave āhāre pariññāte tisso taṇhā pariññātā 
honti._
____

Thus _manosañcetanā_ is somehow associated with _taṇhā._

==== Mental intentionality within taṇhā

_Taṇhā_ is practically an existential nourishment, because 'when a being has 
laid down this [wretched human] body but is not yet possessed of another body, 
I declare that it is fuelled by _taṇhā_.' The full quotation is given below 
in the Illustrations.

That _taṇhā_ implies mental intentionality is seen in the _Taṇhājālinī 
Sutta_ (A.2.212-3) which says that thoughts of 'I am' are 'imbued with 
_taṇhā'_ (_taṇhāvicaritāni_)_,_ for example, the thoughts "I am here," 
"I am this way" "I am otherwise." The sutta also lists thoughts which clearly 
involve mental intentionality, namely:

- May I be

- May I be here

- May I be this way

- May I be otherwise.

==== Mental intentionality: Mahakaccānabhaddekaratta Sutta

Examples of mental intentionality are common in the scriptures. For example, 
the _Mahakaccānabhaddekaratta Sutta_ says:

____
How does one long for the future?

_Kathañcāvuso anāgataṃ paṭikaṅkhati_
____

[quote, M.3.196]
____
One directs one's mind to acquire what has not yet been acquired, thinking, 
'May the visual sense and visible objects be thus in the future.'

_iti me cakkhuṃ siyā anāgatamaddhānaṃ iti rūpāti appaṭiladdhassa 
paṭilābhāya cittaṃ paṇidahati._
____

==== Mental intentionality and rebirth: the Cetanā Sutta

The four existential nourishments are 'for the assistance of those about to 
arise [into new existence],' and are therefore the basis of rebirth. The 
_Cetanā Sutta_ illustrates the link between mental intentionality and rebirth 
as follows:

____
Whatever one is intent upon, conceives of, and identifies with, this becomes 
the basis for the establishment of one's stream of sense consciousness.

_yañca bhikkhave ceteti yañca pakappeti yañca anuseti ārammaṇametaṃ 
hoti viññāṇassa ṭhitiyā_
____

____
When there is the basis, there is the establishment of one's stream of sense 
consciousness.

_Yañca ārammaṇe sati patiṭṭhā viññāṇassa hoti._
____

[quote, S.2.65]
____
When one's stream of sense consciousness is established and has [egoistically] 
matured, renewed states of individual existence and rebirth occur in the future.

_Tasmiṃ patiṭṭhite viññāṇe virūḷhe āyatiṃ 
punabbhavābhinibbatti hoti._
____

The sutta says that in ending intentness, conceiving, and identifying, one ends 
individual existence and rebirth in the future:

[quote, S.2.65]
____
If one is not intent upon, and does not conceive or identify with... there are 
no renewed states of individual existence and rebirth in the future

_Yato ca kho bhikkhave no ceva ceteti no ca pakappeti no ca anuseti... 
āyatiṃ punabbhavābhinibbatti na hoti._
____

==== Mental intentionality and rebirth: the Saṅkhāruppatti Sutta

The _Saṅkhāruppatti Sutta_ says:

[quote, M.3.99 (A.4.239]
____
In this regard a bhikkhu possesses faith [in the perfection of the Perfect 
One's transcendent insight], virtue, learning, generosity, and wisdom. He 
thinks, 'Oh, that at the demise of the body at death, I might be reborn in the 
company of wealthy _khattiyas_.' He fixes his mind on that idea, concentrates 
on it, and develops it. These aspirations and musings of his, when developed 
and cultivated, lead to his rebirth there.

_So taṃ cittaṃ dahati taṃ cittaṃ adhiṭṭhāti taṃ cittaṃ 
bhāveti. Tassa te saṅkhārā ca viharā ca evaṃ bhāvitā 
evaṃbahulīkatā tatrūpapattiyā saṃvattanti._
____

The scriptures therefore show how mental intentionality 'maintains beings that 
have been brought into existence and assists those about to arise [into new 
existence].' Therefore mental intentionality is one of the four nourishments, 
and is likely the meaning of _manosañcetanāhāro_.

=== Illustrations

.Illustration
====
manosañcetanāhāro

existential nourishment of mental intentionality
====

____
And how should the existential nourishment of mental intentionality 
(_manosañcetanāhāro_) be seen?

_Kathañca bhikkhave manosañcetanāhāro daṭṭhabbo?_
____

____
Suppose there is a [red-hot] charcoal pit deeper than a man's height, filled 
with glowing coals without flame or smoke. A man would come along wanting to 
live, not die, yearning for pleasure and loathing pain. Then two strong men 
would grab him by both arms and drag him towards the [red-hot] charcoal pit.

_Seyyathā pi bhikkhave aṅgārakāsu sādhikaporisā puṇṇā 
aṅgārānaṃ vītaccikānaṃ vītadhūmānaṃ. Atha puriso āgaccheyya 
jīvitukāmo amaritukāmo sukhakāmo dukkhapaṭikkūlo. Tamenaṃ dve 
balavanto purisā nānābāhāsu gahetvā taṃ aṅgārakāsuṃ 
upakaḍḍheyyuṃ._
____

The man's

- intention (_cetanā_) would be to get away,

- his desire (_patthanā_) would be to get away,

____
his resolve (_paṇidhi_) would be to get away [from the red-hot charcoal pit]

_Atha kho bhikkhave tassa purisassa ārakāvassa cetanā ārakā patthanā 
ārakā paṇidhi_
____

[quote, S.2.99-100]
____
For what reason? Because he knows: 'I will fall into this [red-hot] charcoal 
pit and on that account I will meet with death or deadly pain.'

_imañcāhaṃ aṅgārakāsuṃ papatissāmi tatonidānaṃ maraṇaṃ vā 
nigacchāmi maraṇamattaṃ vā dukkhan ti. Evameva khvāhaṃ bhikkhave 
manosañcetanāhāro daṭṭhabbo ti vadāmi._
____

.Illustration
====
manosañcetanāhāro

existential nourishment of mental intentionality
====

____
If there is attachment to the existential nourishment of mental intentionality, 
if there is spiritually fettering delight, if there is craving, the stream of 
sense consciousness is established there and [egoistically] matures.

_manosañcetanāya ce bhikkhave āhāre atthi rāgo atthi nandi atthi taṇhā 
patiṭṭhitaṃ tattha viññāṇaṃ virūḷhaṃ._
____

____
Wherever the stream of sense consciousness is established and has 
&#8203;[egoistically] matured, there is the appearance of denomination-and-bodily-form.

_Yattha patiṭṭhitaṃ viññāṇaṃ virūḷhaṃ atthi tattha 
nāmarūpassa avakkanti._
____

____
Where there is the appearance of denomination-and-bodily-form, there is the 
growth of karmically consequential deeds.

_Yattha atthi nāmarūpassa avakkanti atthi tattha saṅkhārānaṃ vuddhi._
____

[quote, S.2.101]
____
Where there is the growth of karmically consequential deeds, renewed states of 
individual existence and rebirth occur in the future.

_Yattha atthi saṅkhārānaṃ vuddhi atthi tattha āyatiṃ 
punabbhavābhinibbatti._
____

.Illustration
====
manosañcetanāhāro

existential nourishment of mental intentionality
====

____
If there is no attachment to the existential nourishment of mental 
intentionality, if there is no spiritually fettering delight, if there is no 
craving, the stream of sense consciousness is not established there and does 
not grow.

_Manosañcetanāya ce bhikkhave āhāre natthi rāgo natthi nandi natthi 
taṇhā. Appatiṭṭhitaṃ tattha viññāṇaṃ avirūḷhaṃ_
____

[quote, S.2.101]
____
Where the stream of sense consciousness is not established and does not grow, 
there is the non-appearance of denomination-and-bodily-form.

_yattha appatiṭṭhitaṃ viññāṇaṃ avirūḷhaṃ natthi tattha 
nāmarūpassa avakkanti._
____

.Illustration
====
'May I be reborn!'

-- 'Bhante

what is the cause and reason for some person here, with the demise of the body 
at death, being reborn in the company of egg-born magical serpents?"
====

____
-- 'In this regard, bhikkhu, someone acts ambivalently by way of body, speech, 
and mind.

_kāyena dvayakārī hoti vācāya dvayakāri manasā dvayakāri_
____

'He has heard: 'Egg-born magical serpents are long-lived, beautiful, and abound 
in happiness.'

____
He thinks: 'Oh, with the demise of the body at death, may I be reborn in the 
company of egg-born magical serpents!'

_tassa evaṃ hoti: aho vatāhaṃ kāyassa bhedā parammaraṇā 
aṇḍajānaṃ nāgānaṃ sahavyataṃ upapajjeyyan ti._
____

'Then, with the demise of the body at death, he is reborn in the company of 
egg-born magical serpents.

'This is the cause and reason for some person here, with the demise of the body 
at death, being reborn in the company of egg-born magical serpents." (S.3.242).

.Illustration
====
'May I be reborn!'

-- 'Bhante

what is the cause and reason for some person here, with the demise of the body 
at death, being reborn in the company of the devas of the heavenly musician 
order (_gandhabbakāyikā devā_)?"
====

-- 'In this regard, bhikkhu, some person practises good conduct of body, 
speech, and mind. He has heard: 'The devas of the heavenly musician order are 
long-lived, beautiful, and abound in happiness.' He thinks: 'Oh, with the 
demise of the body at death, may I be reborn in the company of the devas of the 
heavenly musician order!' Then, with the demise of the body at death, he is 
reborn in the company of the devas of the heavenly musician order.

'This is the cause and reason for some person here, with the demise of the body 
at death, being reborn in the company of the devas of the heavenly musician 
order' (S.3.250).

.Illustration
====
fuelled by craving

-- Master Gotama

when a flame is flung by the wind and goes some distance, what does Master 
Gotama declare to be its fuel on that occasion?
====

-- When, Vaccha, a flame is flung by the wind and goes some distance, I declare 
that it is fuelled by the wind. For on that occasion the wind is its fuel.

-- And, Master Gotama, when a being has laid down this [wretched human] body 
but is not yet possessed of another body, what does Master Gotama declare to be 
&#8203;[the being's] fuel on that occasion?

[quote, S.4.399]
____
-- When, Vaccha, a being has laid down this [wretched human] body but is not 
yet possessed of another body, I declare that [the being] is fuelled by 
craving. For on that occasion craving is [the being's] fuel.

_Yasmiṃ kho vaccha samaye imañca kāyaṃ nikkhipati satto ca aññataraṃ 
kāyaṃ anuppanno hoti tamahaṃ taṇhūpādānaṃ vadāmi. Taṇhāhissa 
vaccha tasmiṃ samaye upādānaṃ hotī ti._
____

.Illustration
====
sañcetanā

intentionality
====

____
Four ways of acquiring a [particular] state of individuality.

_Cattārome bhikkhave attabhāvapaṭilābhā. Katame cattāro?_
____

There is the acquiring of a [particular] state of individuality in which one's 
own intentionality has effect, not another's; another's intentionality has 
effect, not one's own; both; neither.

_atthāvuso attabhāvapaṭilābho yasmiṃ attabhāvapaṭilābhe_

_• attasañcetanā yeva kamati no parasañcetanā._

_• parasañcetanā yeva kamati no attasañcetanā._

_• attasañcetanā ceva kamati parasañcetanā ca._

_• neva attasañcetanā kamati no parasañcetanā_ (D.3.231).

Comment:

Venerable Sāriputta said this meant that where there is the acquiring of a 
&#8203;[particular] state of individuality in which one's own intentionality has 
effect, not another person's, there is a passing away of beings from that group 
on account of their own intentionality (_attasañcetanāhetu tesaṃ 
sattānaṃ tamhā kāyā cuti hoti_). And corresponding statements for the 
other groups (A.2.159).

