== Mantabhāṇin

=== Renderings

- _Mantabhāṇin_: one whose speech is pithy

=== Introduction

==== Mantabhāṇī in the Bahubhāṇi Sutta

The meaning of _mantabhāṇī_ is suggested in the _Bahubhāṇi Sutta_, where 
it is the opposite of _bahubhāṇī,_ as follows:

____
Bhikkhus, there are these five dangers for a person in speaking profusely. 
Which five?

_Pañcime bhikkhave ādīnavā bahubhāṇiyasmiṃ puggale. Katame pañca._
____

____
... He speaks falsely, maliciously, harshly, and frivolously; and with the 
demise of the body at death, he is reborn in the plane of sub-human existence, 
in the plane of misery, in the plane of damnation, or in hell.

_Musā bhaṇati. Pisunaṃ bhaṇati pharusaṃ bhaṇati samphappalāpaṃ 
bhaṇati kāyassa bhedā parammaraṇā apāyaṃ duggatiṃ vinipātaṃ 
nirayaṃ uppajjati._
____

____
... Bhikkhus, there are these five advantages for a person whose speech is 
pithy. Which five?

_Pañcime bhikkhave ānisaṃsā mantabhāṇismiṃ puggale. Katame pañca:_
____

[quote, A.3.254]
____
... He does not speak falsely, maliciously, harshly, or frivolously; and with 
the demise of the body at death, he is reborn in the realm of happiness, in the 
heavenly worlds.

_Na musā bhaṇati na pisunaṃ bhaṇati na pharusaṃ bhaṇati na 
samphappalāpaṃ bhaṇati. Kāyassa bhedā parammaraṇā sugatiṃ saggaṃ 
lokaṃ upapajjati._
____

==== Mantabhāṇī in Dh.v.363

The meaning of _mantabhāṇī_ is suggested in Dh.v.363 where it is linked to 
restraint in speech, and said to be ambrosial:

[quote, Dh.v.363]
____
Whatever bhikkhu is restrained in speech, whose speech is pithy, who is not 
vain, who explains the meaning and significance [of the teaching], his speech 
is ambrosial.

_Yo mukhasaṃyato bhikkhu mantabhāṇī anuddhato +
Atthaṃ dhammañca dīpeti madhuraṃ tassa bhāsitaṃ._
____

==== Mantabhāṇī in Sn.v.850

The meaning of _mantabhāṇī_ is suggested in Sn.v.850 where it is linked to 
sagehood:

[quote, Sn.v.850]
____
A person who is not ill-tempered, not fearful, not boastful, not fretful, whose 
speech is pithy, who is not vain, who is restrained in speech: he is truly a 
sage.

_Akkodhano asantāsī avikatthī akukkucco +
Mantabhāṇī anuddhato sa ve vācāyato muni._
____

==== Mantabhāṇī and frivolous speech

If _mantabhāṇī_ is the opposite of profuse speech, then its qualities are 
likely to be found with the abandonment of frivolous speech, which are seen in 
the following quote:

[quote, A.5.205]
____
He abandons and abstains from frivolous speech, and speaks what is timely, 
truthful and conducive to spiritual well-being. He speaks what accords with the 
teaching and discipline. At the right time, he speaks what is worth treasuring, 
congruous, appropriate, and conducive to spiritual well-being.

_samphappalāpaṃ pahāya samphappalāpā paṭivirato hoti kālavādī 
bhūtavādī atthavādī dhammavādī vinayavādī nidhānavatiṃ vācaṃ 
bhāsitā hoti kālena sāpadesaṃ pariyantavatiṃ atthasaṃhitaṃ._
____

'Words that are worth treasuring, congruous, appropriate, and conducive to 
spiritual well-being' if associated with brevity in speech are all suggestive 
of pithiness.

==== Pithy: definition and useage

Pithy means:

- 'Having substance and point; tersely cogent'

- 'Pithy' adds to 'succinct' or 'terse' the implication of richness of meaning 
or substance (Webster's).

Pithiness is effective because:

- 'Men of talents are sooner to be convinced by short sentences than by long 
preachments, because the short sentences drive themselves into the heart and 
stay there, while long discourses, though ever so good, tire the attention; and 
one good thing drives out another, and so on till all is forgotten.' (Clarissa 
Harlowe by Samuel Richardson).

