== Mathita

=== Renderings

- _mathita_: inward distraction

- _mathita_: distracted

- _mathita_: churned

- _mathita_: oppressed

- _matheti_: to distract

=== Illustrations

.Illustration
====
mathenti

distract
====

[quote, Sn.v.50]
____
Sensuous pleasures -- attractive, sweet, and charming -- distract the mind 
through their many different forms.

_Kāmā hi citrā madhurā manoramā virūparūpena mathenti cittaṃ._
____

.Illustration
====
mathenti

distract
====

[quote, Th.v.674]
____
There are many attractive things in the world, on this wide earth. They 
distract [the mind], it seems, [by promoting] thoughts of lovely objects that 
are associated with attachment.

_Bahūni loke citrāni asmiṃ paṭhavimaṇḍale +
Mathenti maññe saṅkappaṃ subhaṃ rāgūpasaṃhitaṃ._
____

.Illustration
====
mathenti

distract
====

[quote, A.4.159-160]
____
Likeable things do not distract his mind, unlikeable things are not considered 
repulsive. His welcoming and rejecting are scattered, gone to their end, do not 
exist.

_Iṭṭhassa dhammā na mathenti cittaṃ aniṭṭhato no paṭighātameti. +
Tassānurodhā athavā virodhā vidhūpitā atthagatā na santi._
____

.Illustration
====
pamathitassa

distracted
====

[quote, Dh.v.349]
____
The craving of a person of distracted thoughts, who is full of attachment and 
contemplates the loveliness [of the female body] will only develop. Such a 
person reinforces his bondage [to individual existence].

_Vitakkapamathitassa jantuno tibbarāgassa subhānupassino +
Bhiyyo taṇhā pavaḍḍhati esa kho daḷhaṃ karoti bandhanaṃ._
____

.Illustration
====
mathitānaṃ

states of inward distraction
====

[quote, M.1.486]
____
Therefore I say with the destruction, fading away, ending, giving up, and 
relinquishment of all thinking in personal terms, of all states of inward 
distraction, all illusions of personal identity, all illusions of personal 
ownership, and of the proclivity to self-centredness, the Perfect One is 
liberated [from perceptually obscuring states] through being without grasping.

_Tasmā tathāgato sabbamaññitānaṃ sabbamathitānaṃ 
sabbaahaṅkāramamaṅkāramānānusayānaṃ khayā virāgā nirodhā cāgā 
paṭinissaggā anupādā vimutto ti vadāmī ti._
____

.Illustration
====
mathitā

distracted
====

[quote, Th.v.102]
____
Being distracted by their various gains, they do not attain inward 
collectedness.

_Lābhālābhena mathitā samādhiṃ nādhigacchantī ti._
____

.Illustration
====
mathito

oppressed
====

[quote, Th.v.659]
____
Just as a noble thoroughbred yoked to a load, enduring a load, oppressed by the 
excessive burden, does not try to escape from its yoke

_Yathā pi bhaddo ājañño dhure yutto dhurassaho +
Mathito atibhārena saṃ yugaṃ nātivattati._
____

Commentary: _saṃ yugan ti attano khandhe ṭhapitaṃ yugaṃ_. _Saṃ_ is 
therefore a possessive pronoun_._

.Illustration
====
mathita

churned
====

[quote, Vin.2.301]
____
The practlce concerning unchurned [milk]

_amathitakappo._
____

Notes:

[quote, Vin.2.301]
____
This practice concerns milk which has passed the stage of being milk but has 
not arrived at the stage of being cream.

_yaṃ taṃ khīraṃ khīrabhāvaṃ vijahitaṃ asampattaṃ dadhibhāvaṃ._
____

