== Mettā

=== Renderings

- _mettā_: [unlimited, all-encompassing] goodwill

- _mettacitta_: mind of [unlimited, all-encompassing] goodwill

- _mettā_: state of [unlimited, all-encompassing] goodwill

- _metta_: loving

- _metta_: lovingly

=== Introduction

==== Four unlimited states

The practices of _mettā_, _karuṇā_, _muditā_ and _upekkhā_ are sometimes 
called the four divine abidings (_cattāro brahmavihārā_, D.2.196) and 
sometimes the four unlimited states (_catasso appamaññā_, D.3.223). 
Practising them together is called the 'unlimited liberation [from perceptually 
obscuring states]' (_appamāṇā cetovimutti_, S.4.296).

==== The makers of limitation

The _Mahāvedalla Sutta_ (M.1.298) and _Godatta Sutta_ (S.4.296) say the 
'makers of limitation' (_pamāṇakaraṇo_) are _rāgo doso_ and _moho_ 
(_rāgo kho āvuso pamāṇakaraṇo doso pamāṇakaraṇo moho 
pamāṇakaraṇo_). Therefore the four _brahmavihāras_ should be practised 
unlimited by _rāgo doso_ and _moho_.

==== Loving-kindness

_Mettā_ is usually called loving-kindness, which means 'tender and benevolent 
affection,' says Webster's. But if affection means fondness and attachment, it 
is not an attitude to be developed at all, say the suttas:

[quote, M.1.191]
____
Whatever within these five grasped aggregates is the elimination and rejection 
of fondness and attachment is the ending of suffering.

_Yo imesu pañcasupādānakkhandhesu chandarāgavinayo chandarāgappahānaṃ 
so dukkhanirodho ti._
____

Ṭhānissaro says:

- 'There are probably people you've harmed in the past who would rather not 
have anything to do with you ever again, so the intimacy of loving-kindness 
would actually be a source of pain for them, rather than joy. There are also 
people who, when they see that you want to express loving-kindness, would be 
quick to take advantage of it. And there are plenty of animals out there who 
would feel threatened by any overt expressions of love from a human being. In 
these cases, a more distant sense of goodwill, that you promise yourself never 
to harm those people or those beings, would be better for everyone involved.' 
(_Mettā Means Goodwill_: www. accesstoinsight.org).

==== Mettā overcomes resentment, hatred, and ill will

Mettā is for overcoming resentment, hatred, and ill will:

1. When resentment has arisen for someone, one can develop [unlimited, 
all-encompassing] goodwill for him. Thus can one dispel aversion for that 
person.
+
****
_Yasmiṃ bhikkhave puggale āghāto jāyetha mettā tasmiṃ puggale 
bhāvetabbā. Evaṃ tasmiṃ puggale āghāto paṭivinetabbo_ (A.3.185).
****

2. To abandon hatred, [unlimited, all-encompassing] goodwill should be 
developed._ +
☸ Dosassa pahānāya mettā bhāvetabbā_ (A.3.446).

3. I do not see any other single thing of such power to prevent the arising of 
ill will, if not already arisen, or, if arisen, to cause its abandonment, as 
the liberation [from perceptually obscuring states] through [unlimited, 
all-encompassing] goodwill.
+
****
_Nāhaṃ bhikkhave aññaṃ ekadhammampi samanupassāmi yena anuppanno vā 
vyāpādo nuppajjati uppanno vā vyāpādo pahīyati yathayidaṃ bhikkhave 
mettā cetovimutti_ (A.1.4).
****

==== Benefits of mettā

Mettā leads 1) to 'the Exquisite' (i.e. fourth jhāna. See IGPT sv _Subha_), 
and 2) to non-returnership:

1. Bhikkhus, the liberation [from perceptually obscuring states] through 
&#8203;[unlimited, all-encompassing] goodwill has the Exquisite as its culmination, I 
declare, for a wise bhikkhu here who has not penetrated to a superior 
liberation.
+
****
_Subhaparamāhaṃ bhikkhave mettā cetovimuttiṃ vadāmi idha paññassa 
bhikkhuno uttariṃ vimuttiṃ appaṭivijjhato_ (S.5.119).
****

2. Thus developed, the liberation [from perceptually obscuring states] through 
&#8203;[unlimited, all-encompassing] goodwill leads to non-returnership for a wise 
bhikkhu here who has not penetrated to a more exalted liberation.
+
****
_Evaṃ bhāvitā kho bhikkhave mettācetovimutti anāgāmitāya saṃvattati 
idha paññassa bhikkhuno uttariṃ vimuttiṃ appaṭivijjhato_ (A.5.300).
****

==== Arousing faith with mettā

The Buddha suffused others with [unlimited, all-encompassing] goodwill 
(_mettena cittena pharati_) to arouse faith in them. Two examples:

1. 'It would not be hard, Ānanda, for the Perfect One to arouse faith in this 
teaching and training system in Roja the Malla.' Then the Blessed One, having 
suffused Roja the Malla with a mind of [unlimited, all-encompassing] goodwill 
rising from his seat, entered his dwelling. Then Roja the Malla, suffused by 
the Blessed One with a mind of [unlimited, all-encompassing] goodwill, even as 
young calves follow their mothers, having approached dwelling after dwelling, 
compound after compound, asked the bhikkhus: 'Where, bhante, is the Blessed One 
staying just now, the Arahant, the Perfectly Enlightened One? For I long to see 
the Blessed One, the Arahant, the Perfectly Enlightened One'.
+
****
_Na kho taṃ ānanda dukkaraṃ tathāgatena yathā rojo mallo imasmiṃ 
dhammavinaye pasīdeyyā ti. Atha kho bhagavā rojaṃ mallaṃ mettena cittena 
pharitvā uṭṭhāyāsanā vihāraṃ pāvisi. Atha kho rojo mallo bhagavatā 
mettena cittena phuṭṭho seyyathā pi nāma gāvī taruṇavacchā, evameva 
vihārena vihāraṃ pariveṇena pariveṇaṃ upasaṅkamitvā bhikkhū 
pucchati: kahannu kho bhante etarahi so bhagavā viharati arahaṃ sammā 
sambuddho? Dassanakāmā hi mayaṃ taṃ bhagavantaṃ arahantaṃ 
sammāsambuddhan ti_ (Vin.1.247).
****

2. 'Bhante, this elephant Nālāgiri approaching on this carriage road is an 
uncontrollable mankiller. Bhante, may the Blessed One turn back, may the 
Sublime One turn back.'... Then the Blessed One suffused the elephant 
Nālāgiri with a mind of [unlimited, all-encompassing] goodwill. Then the 
elephant Nālāgiri, suffused by the Blessed One with a mind of [unlimited, 
all-encompassing] goodwill, lowered his trunk, approached the Blessed One, and 
stood in front of him...And so it was in this way that the elephant Nālāgiri 
became tamed.
+
****
_ayaṃ bhante nālāgiri hatthi caṇḍo manussaghātako imaṃ racchaṃ 
paṭipanno. Paṭikkamatu bhante bhagavā paṭikkamatu sugato ti... Atha kho 
bhagavā nālāgiriṃ hatthiṃ mettena cittena phari. Atha kho bhagavā 
nālāgiriṃ hatthiṃ mettena cittena eri. Atha kho nālāgiri hatthi 
bhagavatā mettena cittena phuṭo soṇḍaṃ oropetvā yena bhagavā 
tenupasaṅkami. Upasaṅkamitvā bhagavato purato aṭṭhāsi... Tathā danto 
ca pana nālāgiri hatthi ahosi_ (Vin.2.195).
****

==== Mettā and unlimitedness

The unlimitedness of _mettā_ (i.e. _mettā_ unlimited by _rāgo doso_ and 
_moho_) is seen in this quote:

____
Bhikkhus, even if thugs should sever your limbs one by one with a two-handled 
saw, he whose mind was thereby filled with hatred would not on that account be 
a practiser of my training system.

_Ubhatodaṇḍakena pi ce bhikkhave kakacena corā ocarakā aṅgamaṅgāni 
okanteyyuṃ tatrāpi yo mano padūseyya na me so tena sāsanakaro._
____

[quote, M.1.129]
____
... In this regard, you should train yourselves thus: 'Neither shall our minds 
be worsened by this, nor shall we utter unvirtuous words, but we shall abide 
tenderly concerned for their welfare, with a mind of [unlimited, 
all-encompassing] goodwill, without inner hatred.'_

_Tatrāpi vo bhikkhave evaṃ sikkhitabbaṃ: na ceva no cittaṃ 
vipariṇataṃ bhavissati. Na ca pāpakaṃ vācaṃ nicchāressāma. 
Hitānukampī ca viharissāma mettacittā na dosantarā._
____

==== Sabbatthatāya not sabbattatāya

_Sabbatthatāya_ is a long-standing issue in the scriptures because of its 
alternative spelling, _sabbattatāya,_ which Bodhi renders as 'to all as to 
himself,' as follows:

[quote, Bodhi, M.1.38]
____
... everywhere, and to all as to himself, he abides pervading the 
all-encompassing world with a mind imbued with loving-kindness

_sabbadhi sabbatthatāya sabbāvantaṃ lokaṃ mettāsahagatena cetasā... 
pharitvā viharati._
____

Horner translates it as 'in every way':

- he dwells having suffused the whole world everywhere, in every way, with a 
mind of friendliness (Horner, M.1.38).

The phrase _sabbadhi sabbatthatāya_ also occurs at Ud.33 where the phrase 'to 
all as to himself' (_sabbattatāya_) is clearly inappropriate:

[quote, Ud.33]
____
Whatever states of individual existence there are in any way, anywhere ('to all 
as to himself'), all these states of individual existence are unlasting

_ye hi keci bhavā sabbadhi sabbatthatāya sabbe te bhavā aniccā._
____

The Vipassana Research Institute consistently favours _sabbattatāya_ over 
_sabbatthatāya_, except at one place, the just quoted Ud.33, where they take 
_sabbatthatāya_, thereby acknowledging the decisiveness of the quote.

Although the Buddha Jayanti Version consistently favours _sabbattatāya_, 
including at Ud.33, it consistently notes that _sabbatthatāya_ is a variant 
reading.

The PED does not recognise _sabbattatāya_ as a word, only _sabbatthatāya_ 
whose meaning is 'the state of being everywhere.' The PED says that _atthata_ 
is the past participle of _attharati_, meaning 'spread, covered, spread over 
with.' Likewise, DOP recognises _atthata_ but not _attata_.

Therefore we take _atthata_ (everywhere) as the correct spelling, and translate 
as follows:

[quote, S.4.323]
____
in all directions, everywhere, he abides pervading the whole world [of beings] 
with a mind of [unlimited, all-encompassing] goodwill.

_sabbadhi sabbatthatāya sabbāvantaṃ lokaṃ mettāsahagatena cetasā... 
viharati._
____

==== Pervading [unlimited, all-encompassing] goodwill: world [of beings]

When one abides pervading the whole world with a mind of [unlimited, 
all-encompassing] goodwill (_sabbāvantaṃ lokaṃ mettāsahagatena cetasā... 
pharitvā_), what does 'world' mean? Other suttas, and clues in the sutta 
itself show that _mettā_ should be pervaded to the 'world [of beings],' a 
practice which would therefore include devas.

==== Metta: adjective and adverb

For the adjective, we render _metta_ as 'loving.' In one case below we say 
'lovingly.'

=== Illustrations

.Illustration
====
mettaṃ

loving
====

[quote, A.5.353]
____
A bhikkhu maintains loving conduct of body, both openly and privately to those 
bhikkhus who are senior, long gone forth [into the ascetic life] who are 
fathers of the community of bhikkhus, leaders of the community of bhikkhus.

_Idha bhikkhave bhikkhu ye te bhikkhu therā rattaññū cirapabbajitā 
saṅghapitaro saṅghaparināyakā tesu mettaṃ kāyakammaṃ 
paccupaṭṭhāpeti āvī ceva raho ca._
____

.Illustration
====
mettena

loving
====

[quote, D.2.144]
____
For a long time, Ānanda, you have offered the Perfect One loving conduct of 
body, beneficent, pleasant, unselfish, beyond measure.

_Dīgharattaṃ kho te ānanda tathāgato paccupaṭṭhito mettena 
kāyakammena hitena sukhena advayena appamāṇena._
____

.Illustration
====
mettena

loving
====

[quote, Th.v.1041]
____
For twenty-five years I served the Blessed One with loving conduct of body, 
like a shadow never leaving him.

_Paṇṇavīsati vassāni bhagavantaṃ upaṭṭhahiṃ +
Mettena kāyakammena chāyā va anapāyinī._
____

.Illustration
====
metta

loving
====

King Pasenadi of Kosala prostrated his head to the Blessed One's feet, covered 
them with kisses and caressed them with his hands, pronouncing his name:

-- 'Bhante, I am King Pasenadi of Kosala! Bhante, I am King Pasenadi of Kosala!'

____
-- 'But, great king, considering what good reason do you show such profound 
humility and pay such loving homage to this [wretched human] body of mine?'

_Kaṃ pana tvaṃ mahārāja atthavasaṃ sampassamāno imasmiṃ sarīre 
evarūpaṃ paramanipaccākāraṃ karosi mettupahāraṃ upadaṃsesī ti?_
____

[quote, A.5.65]
____
-- Out of gratitude and thankfulness I show such profound humility and pay such 
loving homage to the Blessed One.

_Kataññutaṃ kho ahaṃ bhante kataveditaṃ sampassamāno bhagavati 
evarūpaṃ paramanipaccākāraṃ karomi mettupahārāṃ upadaṃsemi._
____

.Illustration
====
mettā

lovingly
====

[quote, A.3.443]
____
The Teacher will be lovingly venerated by me through my practice [in accordance 
with the teaching]

_Satthā ca me pariciṇṇo bhavissati mettāvatāyā tī._
____

Comment:

_Pariciṇṇo mayā satthā_: the Teacher has been [lovingly] venerated by me 
&#8203;[through my practice in accordance with the teaching]. See Glossary sv 
_Pariciṇṇo mayā satthā._

.Illustration
====
mettā

state of [unlimited, all-encompassing] goodwill
====

[quote, M.1.369-371]
____
The Blessed One, bhante, abides in a state of [unlimited, all-encompassing] 
goodwill.

_bhagavā hi bhante mettāvihārī ti._
____

.Illustration
====
mettacitto

mind of [unlimited, all-encompassing] goodwill
====

[quote, A.3.144]
____
He nurses the patient for worldly benefits not with a mind of [unlimited, 
all-encompassing] goodwill.

__āmisantaro gilānaṃ upaṭṭhahati no mettacitto._
____

.Illustration
====
mettaṃ cittaṃ

mind of [unlimited, all-encompassing] goodwill
====

____
-- Being not tenderly concerned for their welfare, would he have a mind of 
&#8203;[unlimited, all-encompassing] goodwill or of enmity?

_ahitānukampissa mettaṃ vā tesu cittaṃ paccupaṭṭhitaṃ hoti 
sapattakaṃ vā ti_
____

[quote, D.1.228]
____
-- Enmity, Master Gotama.

_Sapattakaṃ bho gotama._
____

.Illustration
====
mettacitto

mind of [unlimited, all-encompassing] goodwill
====

[quote, M.1.18]
____
I am one with a mind of [unlimited, all-encompassing] goodwill.

_mettacitto'hamasmi._
____

.Illustration
====
mettacitta

a mind of [unlimited, all-encompassing] goodwill
====

[quote, S.5.169]
____
In what way in protecting others does one protect oneself? By developing 
patience, compassion, a mind of [unlimited, all-encompassing] goodwill, and 
sympathy.

_Kathañca bhikkhave paraṃ rakkhanto attānaṃ rakkhati: khantiyā 
avihiṃsāya mettacittatāya anuddayatāya._
____

.Illustration
====
mettena cittena

mind of [unlimited, all-encompassing] goodwill
====

[quote, A.2.72; Vin.2.110]
____
Surely that bhikkhu did not pervade the four royal families of snakes with a 
mind of [unlimited, all-encompassing] goodwill. For if that bhikkhu had done 
so, then that bhikkhu when bitten by a snake, would certainly not have died.

_Nahanūna so bhikkhave bhikkhu cattāri ahirājakulāni mettena cittena phari. 
Sace hi so bhikkhave bhikkhu cattāri ahirājakulāni mettena cittena phareyya 
na hi so bhikkhave bhikkhu ahinā daṭṭho kālaṃ kareyya._
____

.Illustration
====
mettena cittena

mind of [unlimited, all-encompassing] goodwill
====

[quote, M.1.126]
____
Bhikkhus, some might speak to you with speech that is: timely or untimely; true 
or untrue; gentle or harsh; conducive or unconducive to your spiritual 
well-being; spoken with a mind of [unlimited, all-encompassing] goodwill or 
with inner hatred.

_Kālena vā bhikkhave pare vadamānā vadeyyuṃ akālena vā. Bhūtena vā... 
abhūtena vā. Saṇhena vā... pharusena vā. Atthasaṃhitena vā... 
anatthasaṃhitena vā. Mettacittā vā... dosantarā vā._
____

____
On all occasions you should train yourselves thus: 'Neither shall our minds be 
worsened by this, nor shall we utter unvirtuous words, but we shall abide 
tenderly concerned for their welfare, with a mind of [unlimited, 
all-encompassing] goodwill, without inner hatred.'

_na ceva no cittaṃ vipariṇataṃ bhavissati na ca pāpakaṃ vācaṃ 
nicchāressāma. Hitānukampī ca viharissāma mettacittā na dosantarā._
____

____
We shall abide pervading that person with a mind of [unlimited, 
all-encompassing] goodwill,

_tañca puggalaṃ mettāsahagatena cetasā pharitvā viharissāma._
____

• With this as our basis [for spiritual development] ** +
**☸ _Tadārammaṇañca_

____
we shall abide pervading the whole world [of beings] with a mind of [unlimited, 
all-encompassing] goodwill, vast, exalted, unlimited, free of unfriendliness 
and hostility.

_sabbāvantaṃ lokaṃ mettāsahagatena cetasā vipulena mahaggatena 
appamāṇena averena avyāpajjhena pharitvā viharissāmāti._
____

Thus bhikkhus should you train yourselves (M.1.126).

