== Middha

=== Renderings

- _middha_: torpor

=== Illustrations

.Illustration
====
middha

torpor
====

[quote, S.5.110]
____
Whatever lethargy there is, is a spiritual hindrance; whatever torpor there is, 
is also a spiritual hindrance. Thus what is concisely called the hindrance of 
lethargy and torpor becomes twofold by this method of exposition.

_Yadapi bhikkhave thīnaṃ tadapi nīvaraṇaṃ. Yadapi middhaṃ tadapi 
nīvaraṇāṃ. Thīnamiddhanīvaraṇanti itihidaṃ uddesaṃ gacchati. 
Tadamināpetaṃ pariyāyena dvayaṃ hoti._
____

.Illustration
====
middhassa

torpor
====

[quote, S.5.102-3]
____
There are disgruntlement [with the celibate life], sloth, languor, drowsiness 
after meals, mental sluggishness. Much improper contemplation in that regard is 
a condition that nourishes both the arising of unarisen lethargy and torpor, 
and the increase and expansion of arisen lethargy and torpor.

_Atthi bhikkhave arati tandi vijambhitā bhattasammado cetaso ca līnattaṃ. 
Tattha ayoniso manasikārabahulīkāro ayamāhāro anuppannassa vā 
thīnamiddhassa uppādāya uppannassa vā thīnamiddhassa bhiyyobhāvāya 
vepullāya._
____

.Illustration
====
middhaṃ

torpor
====

• If, while he is walking, any greed in a bhikkhu is done away with, any ill 
will, any lethargy and torpor, any restlessness and anxiety, any doubt [about 
the significance of the teaching] is done away with; +
_Carato ce pi bhikkhave bhikkhuno abhijjhā vigatā hoti vyāpādo vigato hoti 
thīnamiddhaṃ vigataṃ hoti uddhaccakukkuccaṃ vigataṃ hoti vicikicchā 
pahīṇā hoti._

• if unflagging energy is aroused; if unmuddled mindfulness is established; 
if his body is tranquil and peaceful; if his mind is collected and concentrated 
+
_Āraddhaṃ hoti viriyaṃ asallīnaṃ upaṭṭhitā sati asammuṭṭhā 
passaddho kāyo asāraddho samāhitaṃ cittaṃ ekaggaṃ_

• then a bhikkhu walking like this is said to be constantly and continuously 
afraid of wrongdoing, and vigorously, energetically, and resolutely applied [to 
the practice]. +
_carampi bhikkhave bhikkhu evambhūto ātāpī ottappī satataṃ samitaṃ 
āraddhaviriyo pahitatto ti vuccati_ (It.118-9).

.Illustration
====
middhaṃ

torpor
====

____
Are you nodding, Moggallāna? Are you nodding, Moggallāna? Yes, bhante.

_Pacalāyasi no tvaṃ moggallāna pacalāyasi no tvaṃ moggallānā ti. 
Evaṃ bhante ti._
____

1. In which case, whatever state of perception you are abiding in when torpor 
arises in you, do not focus on that perception, do not cultivate it. It is 
possible that by abiding in this way, that the torpor will be abandoned.
+
****
_Tasmātiha tvaṃ moggallāna yathā saññino te viharato taṃ middhaṃ 
okkamati taṃ saññaṃ mā manasākāsi taṃ saññaṃ mā bahulamakāsi. 
Ṭhānaṃ kho panetaṃ moggallāna vijjati yaṃ te evaṃ viharato taṃ 
middhaṃ pahīyetha._
****

2. If the torpor is unabandoned, then think about the teaching, ponder it, 
examine it, as you have heard and memorised it. It is possible that by abiding 
in this way, that the torpor will be abandoned.
+
****
_No ce te evaṃ viharato taṃ middhaṃ pahīyetha tato tvaṃ moggallāna 
yathā sutaṃ yathāpariyattaṃ dhammaṃ cetasā anuvitakkeyyāsi 
anūvicāreyyāsi manasānupekkheyyāsi. Ṭhānaṃ kho panetaṃ vijjati 
yaṃ te evaṃ viharato taṃ middhaṃ pahīyetha._
****

3. If the torpor is unabandoned, then recite the teaching in detail as you have 
heard and memorised it. It is possible that by abiding in this way, that the 
torpor will be abandoned.
+
****
_No ce te evaṃ viharato taṃ middhaṃ pahīyetha tato tvaṃ moggallāna 
yathāsutaṃ yathāpariyattaṃ dhammaṃ vitthārena sajjhāyaṃ kareyyāsi. 
Ṭhānaṃ kho panetaṃ vijjati yaṃ te evaṃ viharato taṃ middhaṃ 
pahīyetha._
****

4. If the torpor is unabandoned, then tug your ears and massage your limbs. It 
is possible that by abiding in this way, that the torpor will be abandoned.
+
****
_No ce te evaṃ viharato taṃ middhaṃ pahīyetha tato tvaṃ moggallāna 
ubho kaṇṇasotāni āviñjeyyāsi pāṇinā gattāni anumajjeyyāsi. 
Ṭhānaṃ kho panetaṃ vijjati yaṃ te evaṃ viharato taṃ middhaṃ 
pahīyetha._
****

5. If the torpor is unabandoned, then get up from your seat 
(_uṭṭhāyāsanā_) and, after washing your eyes out with water (_udakena 
akkhīni anumajjitvā_), look around in all directions and upward to the lunar 
mansions and the glittering stars (_disā anuvilokeyyāsi nakkhattāni 
tārakarūpāni ullokeyyāsi_). It is possible that by abiding in this way, 
that the torpor will be abandoned.

6. If the torpor is unabandoned, then focus on the mental image of light 
(_ālokasaññaṃ manasikareyyāsi_), concentrate on the mental image of day 
(_divāsaññaṃ adhiṭṭheyyāsi_). As by day, so at night; as at night, so 
by day (_yathā divā tathā rattiṃ yathā rattiṃ tathā divā_). Thus with 
an attitude open and unclouded, you should make your mind radiant (_iti 
vivaṭena cetasā apariyonaddhena_) (_sappabhāsaṃ cittaṃ bhāveyyāsi_). 
It is possible that by abiding in this way, that the torpor will be abandoned

7. If the torpor is unabandoned, then perceiving the constant nature of reality 
(_pacchāpuresaññī_), concentrate on pacing back and forth (_caṅkamaṃ 
adhiṭṭheyyāsi_), your senses inwardly immersed (_antogatehi indriyehi_), 
your mind not straying outwards (_abahigatena mānasena_). It is possible that 
by abiding in this way, that the torpor will be abandoned.

8. If the torpor is unabandoned, then, mindful and fully conscious, lie down on 
your right side in the lion's posture with your feet placed together, having 
contemplated the idea of rising. When you awaken, get up quickly, with the 
thought, 'I will not abide given to the pleasures of sleep, languor, and 
torpor.' That is how you should train yourself.
+
****
_No ce te evaṃ viharato taṃ middhaṃ pahīyetha tato tvaṃ moggallāna 
dakkhiṇena passena sīhaseyyaṃ kappeyyāsi pāde pādaṃ accādhāya sato 
sampajāno uṭṭhānasaññaṃ manasikaritvā. Paṭibuddheneva te 
moggallāna khippaṃyeva paccuṭṭhātabbaṃ: na seyyasukhaṃ na 
phassasukhaṃ na middhasukhaṃ anuyutto viharissāmiti. Evaṃ hi te 
moggallāna sikkhitabbaṃ_ (A.4.85-86).
****

.Illustration
====
middhaṃ

torpor
====

[quote, Th.v.904]
____
It is now fifty-five years since I adopted the practice of sleeping in the 
sitting position, and twenty-five years since torpor was abolished in me.

_Pañcapaññāsavassāni yato nesajjiko ahaṃ +
Pañcavīsativassāni yato middhaṃ samūhataṃ._
____

.Illustration
====
middho

torpor
====

[quote, Sn.v.151]
____
Whether standing, walking, seated or lying down, as long as he was free of 
torpor he would concentrate on this [practice] mindfully. They call this a 
divine abiding.

_Tiṭṭhaṃ caraṃ nisinno vā sayāno vā yāvatassa vigatamiddho +
Etaṃ satiṃ adhiṭṭheyya brahmametaṃ vihāraṃ idhamāhu._
____

