== Moghapurisa

=== Renderings

- _mogha_: in vain

- _mogha_: false

- _moghapurisa_: worthless man

=== Introduction

==== Mogha: false

Where _mogha_ is the opposite of _sacca_, we render it as 'false':

[quote, M.1.498]
____
This alone is true. All else is false.

_idameva saccaṃ moghamaññan ti._
____

On this basis, _moghapurisa_ would be 'a false man' or 'an untrue man.'

==== Mogha: in vain

But in many contexts _mogha_ means 'in vain':

[quote, D.2.251]
____
The going forth [into the ascetic life] of all those noble young men was not in 
vain or barren, but fruitful and productive.

_iti kho pana sabbesaṃ yeva tesaṃ kulaputtānaṃ amoghā pabbajjā ahosi 
avañjhā saphalā saudrayā ti._
____

On this basis a _moghapurisa_ would be, for example, futile, unavailing, 
incompetent, ineffectual, or useless. But 'vain' means something else, and its 
synonyms seem harsh. Our 'worthless' is in accordance with other admonishments, 
which including 'empty' and 'hollow':

[quote, M.1.440]
____
Bhaddali, on that occasion, were you not an empty, hollow wrongdoer?

_Nanu tvaṃ bhaddāli tasmiṃ samaye ritto tuccho aparaddho ti._
____

==== Worthless defined

Worthless means:

- contemptible, despicable (Webster's)

- without merit (Collins)

- having no good qualities or useful skills (Oxford)

=== Illustrations

.Illustration
====
mogha

in vain
====

[quote, Dh.v.260]
____
One is not a senior [bhikkhu] [just] because one's head is grey. If one has 
matured [just] in age one is called 'aged in vain.'

_Na tena thero hoti yenassa palitaṃ siro +
Paripakko vayo tassa moghajiṇṇo ti vuccati._
____

.Illustration
====
moghaṃ

in vain
====

[quote, S.5.385]
____
One who has faith in the community of disciples and purified vision [of things 
according to reality]: they say he is not poor. His life is not [lived] in vain.

_Saṅghe pasādo yassatthi ujubhūtañca dassanaṃ +
Adaḷiddoti taṃ āhu amoghaṃ tassa jīvitaṃ._
____

.Illustration
====
moghaṃ

in vain
====

[quote, Sn.v.354]
____
Surely the useful religious life which Kappa lived was not in vain.

_yad atthiyaṃ brahmacariyaṃ acari kappāyano kaccissa taṃ amoghaṃ._
____

.Illustration
====
moghaṃ

in vain
====

[quote, Sn.v.356]
____
Hearing your voice, best of seers, I have faith [in you]. Truly my question was 
not in vain.

_Esa sutvā pasīdāmi vaco te isisattama +
Amoghaṃ kira me puṭṭhaṃ._
____

.Illustration
====
moghaṃ

in vain
====

[quote, Th.v.451]
____
Should make one's day lived not in vain, whether by a little or by much.

_Amoghaṃ divasaṃ kayirā appena bahukena vā._
____

.Illustration
====
moghaṃ

in vain
====

[quote, Th.v.995-6]
____
I listened desirously; my listening was not in vain.

_sotamodhesimatthiko +
Taṃ me amoghaṃ savanaṃ._
____

.Illustration
====
moghaṃ

in vain
====

[quote, Thī.v.150]
____
The three final knowledges are attained. The Buddha's training system is not 
&#8203;[undertaken] in vain.

_Tisso vijjā anuppattā amoghaṃ buddhasāsanaṃ._
____

.Illustration
====
mogho

in vain
====

[quote, Th.v.334]
____
Your instruction was not in vain: I am your trained student.

_Amogho tuyhamovādo antevāsimhi sikkhito ti._
____

.Illustration
====
mogho

false
====

[quote, D.1.201]
____
My past acquired self was at the time my only true one; the future and present 
ones were false.

_yo me ahosi atīto attapaṭilābho sveva me attapaṭilābho tasmiṃ samaye 
sacco ahosi mogho anāgato mogho paccuppanno._
____

.Illustration
====
moghapurisā

worthless man
====

[quote, A.3.359]
____
Thus do noble young men declare their [attainment of] arahantship. The matter 
is spoken of without any reference to themselves. Yet there are some worthless 
men here who apparently declare [that they have attained] arahantship for fun.

_evaṃ kho bhikkhave kulaputtā aññaṃ vyākaronti attho ca vutto attā ca 
anupanīto. Atha ca pana idhekacce moghapurisā hasamānakā maññe aññaṃ 
vyākaronti._
____

.Illustration
====
moghapurisā

worthless man
====

[quote, M.1.480]
____
Bhikkhus, you have lost your way. Bhikkhus, you are conducting yourselves 
wrongly. Bhikkhus, how far you have strayed, you worthless men, from this 
teaching and training system.

_Vippaṭipannā'ttha bhikkhave. Micchāpaṭipannā'ttha bhikkhave. 
Kīvadūrevime bhikkhave moghapurisā apakkantā imasmā dhammavinayā._
____

.Illustration
====
moghapuriso

worthless man
====

[quote, M.1.445]
____
When I am explaining the teaching, this worthless man does listen to it with 
eager ears, paying attention to it as a matter of vital concern, applying his 
whole mind to it.

_Nacāyaṃ moghapuriso mayā dhammaṃ desiyamāne aṭṭhikatvā 
manasikatvā sabbacetaso samannāharitvā ohitasoto dhammaṃ suṇātī ti._
____

.Illustration
====
moghapurisa

worthless man
====

[quote, M.1.258]
____
Worthless man, to whom indeed have you known me to explain the teaching that 
way?

_Kassa nu kho nāma tvaṃ moghapurisa mayā evaṃ dhammaṃ desitaṃ 
ājānāsi?._
____

.Illustration
====
moghapurisassa

worthless man
====

[quote, Vin.3.42]
____
This worthless man must have absolutely no sympathy, tender concern, or 
compassion for living beings.

_Na hi nāma bhikkhave tassa moghapurisassa pāṇesu anuddayā anukampā 
avihesā bhavissati._
____

.Illustration
====
moghapurisena

worthless man
====

[quote, M.3.208-9]
____
The ascetic Potaliputta's question should have been analysed before being 
answered. Samiddhi, the worthless man, answered it without qualification.

_Iminā ca ānanda samiddhinā moghapurisena potaliputtassa paribbājakassa 
vibhajjavyākaraṇīyo pañho ekaṃsena vyākato ti._
____

.Illustration
====
moghapuriso

worthless man
====

[quote, A.1.33]
____
I do not see any other single person who so acts for the harm of the manyfolk, 
for the unhappiness of the manyfolk, for the ruin, harm and suffering of devas 
and men as Makkhali, that worthless man.

_Nāhaṃ bhikkhave aññaṃ ekapuggalampi samanupassāmi yo evaṃ 
bahujanāhitāya paṭipanno bahujanāsukhāya bahuno janassa anatthāya 
ahitāya dukkhāya devamanussānaṃ yathayidaṃ bhikkhave makkhalī 
moghapuriso._
____

.Illustration
====
moghapurisānaṃ

worthless persons
====

[quote, D.3.116]
____
And, by listening to such talk, any worthless persons' unsureness or 
uncertainty about the [perfection of the] Perfect One's [transcendent insight] 
will be abandoned.

_Yesampi hi sāriputta moghapurisānaṃ bhavissati tathāgate kaṅkhā vā 
vimati vā tesamimaṃ dhammapariyāyaṃ sutvā yā tathāgate kaṅkhā vā 
vimati vā sā pahīyissatī ti._
____

