== Moha

=== Renderings

- _moha_: undiscernment of reality

- _amoha_: discernment of reality

- _vītamoha_: free of undiscernment of reality

- _asammūḷho_: discerning of reality

- _sammūḷho_: undiscerning of reality

=== Introduction

==== Moha: not 'delusion'

Because _moha_ is related to _muyhati,_ to be deluded, it is therefore usually 
known as 'delusion.' However, this would imply that _moha_ is:

- 'a belief that has no evidence in fact' (www. vocabulary.com).

- 'a mistaken or unfounded opinion or idea' (WordWeb)

==== Moha: 'undiscernment of reality'

In this essay we will show that:

1. _moha_ is antonymous to _paññā_

2. _moha_ is synonymous with _avijjā_

3. _moha_ is associated with _aññāṇa_

4. _moha_ occurs in those who are _ariyadhamme akovide_

These four terms are shown in the Glossary to mean:

1. _paññā_: penetrative discernment

2. _avijjā_: uninsightfulness into reality

3. _aññāṇa_: ignorance [of things according to reality]

4. _ariyadhamme akovide_: those who are ignorant of the noble teaching

These associations suggest that _moha_ means uninsightfulness, which, to 
discriminate it, we will call 'undiscernment of reality.'

==== Moha equals avijjā

_Moha_ equals _avijjā_ (i.e. uninsightfulness into reality):

[quote, A.1.195]
____
'What do you think, Sāḷha, is there discernment of reality?' -- 'Yes, 
bhante' -- 'I call it insightfulness into reality.'

_Taṃ kiṃ maññatha sāḷhā atthi amoho ti? Evambhante. Vijjā ti kho 
ahaṃ sāḷhā etamatthaṃ vadāmi._
____

[quote, Sn.v.730]
____
This uninsightfulness into reality is indeed undiscernment of reality whereby 
this wandering the round of birth and death goes on for a long time.

_Avijjā hāyaṃ mahāmoho yenidaṃ saṃsitaṃ ciraṃ._
____

==== Moha and avijjā: same relationship to āsavas

_Moha_ and _avijjā_ both have the same relationship to perceptually obscuring 
states (_āsavā_):

[quote, M.1.250]
____
_Moha_: It is through the abandonment of perceptually obscuring states that one 
is discerning of reality.

_Āsavānaṃ hi aggivessana pahānā asammūḷho hoti._
____

[quote, M.1.55]
____
_Avijjā_: With the ending of perceptual obscuration comes the ending of 
uninsightfulness into reality

__āsavanirodhā avijjānirodho._
____

==== Moha: associated with aññāṇa

_Moha_ is associated with ignorance [of things according to reality] 
(_aññāṇapakkhā_):

[quote, Sn.v.347]
____
Whatever spiritual shackles there are in the world, [or] paths of undiscernment 
of reality, [or] whatever is associated with ignorance [of things according to 
reality], [or] whatever bases for doubt [about the significance of the 
teaching] there are, when they reach the Perfect One they vanish.

_Ye keci ganthā idha mohamaggā aññāṇapakkhā vicikicchaṭṭhānā +
Tathāgataṃ patvā na te bhavanti._
____

==== Moha: opposed to paññā

_Moha_ is opposed to _paññā,_ penetrative discernment:

[quote, A.3.446]
____
To abandon undiscernment of reality, penetrative discernment should be 
developed._

_Mohassa pahānāya paññā bhāvetabbā._
____

• They extinguish... the fire of undiscernment of reality with the 
penetrative discernment that leads to the profound understanding [and 
destruction of the great masses of greed, hatred, and undiscernment of 
reality]. +
☸ _nibbāpenti... mohaggiṃ pana paññāya yāyaṃ nibbedhagāminī_ 
(It.93). +
☸ _lobhakkhandhaṃ dosakkhandhaṃ mohakkhandhaṃ_ (S.5.88). See 
Illustration for notes on this quote.

==== Moha and ariyadhamme akovide

_Moha_ occurs in those who are _ariyadhamme akovide_, i.e. ignorant of the 
noble teaching:

[quote, It.92]
____
The fire of undiscernment of reality burns those who are undiscerning of 
reality, who are ignorant of the noble teaching.

_Mohaggi pana sammūḷhe ariyadhamme akovide._
____

==== Negative of moha

When 'lack of _moha'_ is a noun, we call it 'discernment of reality':

[quote, A.1.263]
____
Conduct produced from, born of, due to, originated by discernment of reality is 
spiritually wholesome and blameless.

_Yaṃ bhikkhave amohapakataṃ kammaṃ amohajaṃ amohanidānaṃ 
amohasamudayaṃ. Taṃ kammaṃ kusalaṃ taṃ kammaṃ anavajjaṃ taṃ 
kammaṃ._
____

=== Illustrations

.Illustration
====
moho

undiscernment of reality
====

____
What is the cause and reason that unarisen undiscernment of reality arises, or 
that arisen undiscernment of reality increases and expands?

_Ko panāvuso hetu ko paccayo yena anuppanno vā moho uppajjati uppanno vā 
moho bhiyyobhāvāya vepullāya saṃvattatī ti?_
____

[quote, A.1.200]
____
Improper contemplation, one should reply.

_Ayoniso manasikārotissa vacanīyaṃ._
____

.Illustration
====
moho

undiscernment of reality
====

____
What is the cause and reason that unarisen undiscernment of reality does not 
arise, or that arisen undiscernment of reality is abandoned?

_Ko panāvuso hetu ko paccayo yena anuppanno vā moho nuppajjati uppanno vā 
moho pahiyyatī ti._
____

[quote, A.1.201]
____
Proper contemplation, one should reply.

_Yoniso manasikārotissa vacanīyaṃ._
____

.Illustration
====
moho

undiscernment of reality
====

____
Bhikkhus, there are three bases for the arising of karmically consequential 
deeds. What three?

_Tīṇi'māni bhikkhave nidānāni kammānaṃ samudayāya. Katamāni tīṇi_
____

[quote, A.1.134]
____
Greed is a basis for the origination of karmically consequential deeds. Hatred 
is a basis for the origination of karmically consequential deeds. Undiscernment 
of reality is a basis for the origination of karmically consequential deeds.

_lobho nidānaṃ kammānaṃ samudayāya doso nidānaṃ kammānaṃ 
samudayāya moho nidānaṃ kammānaṃ samudayāya._
____

.Illustration
====
moho

undiscernment of reality
====

[quote, It.93]
____
They extinguish... the fire of undiscernment of reality with the penetrative 
discernment that leads to the profound understanding [and destruction of the 
great masses of greed, hatred, and undiscernment of reality].

_nibbāpenti... mohaggiṃ pana paññāya yāyaṃ nibbedhagāminī._
____

COMMENT

_Nibbedhagāminī_: 'leads to the profound understanding [and destruction of 
the great masses of greed, hatred, and undiscernment of reality]': 
_Nibbijjhati_ means 'to pierce,' which we call 'to profoundly understand.' At 
S.5.88 _nibbijjhati_ is linked to _padāleti_ (to destroy), and to 
_lobhakkhandhaṃ dosakkhandhaṃ mohakkhandhaṃ_ ('the great masses of greed, 
hatred, and undiscernment of reality').

.Illustration
====
moho

undiscernment of reality
====

[quote, S.4.217]
____
For a bhikkhu whose _āsavas_ are destroyed, attachment, hatred, and 
undiscernment of reality are ended.

_khīṇāsavassa bhikkhuno rāgo niruddho hoti doso niruddho hoti moho 
niruddho hoti._
____

.Illustration
====
avītamohā

undiscerning of reality; moha, undiscernment of reality
====

[quote, S.4.307]
____
In the theatre or arena, among beings who are undiscerning of reality, who are 
bound [to individual existence] by the bondage of undiscernment of reality, an 
actor entertains them with confusing things that excite them even more strongly 
to undiscernment of reality.

_Pubbe kho gāmaṇi sattā avītamohā mohabandhanabaddhā tesaṃ naṭo 
raṅgamajjhe samajjamajjhe ye dhammā mohanīyā te upasaṃharati bhīyyo 
samohāya._
____

.Illustration
====
mūḷho

undiscerning of reality; moha, undiscernment of reality
====

____
A person who is undiscerning of reality does not know what is beneficial, nor 
see what is righteous.

_Mūḷho atthaṃ na jānāti mūḷho dhammaṃ na passati_
____

____
Blinding darkness then prevails when undiscernment of reality overcomes a 
person.

_Andhantamaṃ tadā hoti yaṃ moho sahate naraṃ._
____

____
But one who abandons undiscernment of reality is not deluded by deluding things.

_Yo ca mohaṃ pahatvāna mohaneyye na muyhati_
____

[quote, It.84]
____
He puts an end to all undiscernment of reality like the sun dispels the night.

_Mohaṃ vihanti so sabbaṃ ādiccovudayaṃ taman ti._
____

.Illustration
====
vītamoho

free of undiscernment of reality
====

[quote, Sn.v.13]
____
He who neither longs for the cessation of individual existence nor is unintent 
upon it, knowing that everything is untrue [to itself], being free of 
undiscernment of reality, that bhikkhu sheds the [ties to individual existence 
in the] low plane of existence and the other planes beyond it, as a snake sheds 
its old, worn-out skin.

_Yo nāccasārī na paccasārī sabbaṃ vitathamidanti vītamoho +
So bhikkhu jahāti orapāraṃ urago jiṇṇamiva tacaṃ purāṇaṃ._
____

