== Muditā

=== Renderings

- _muditā_: [unlimited, all-encompassing] joy

=== Introduction

==== Unlimitedness

The practices of _mettā_, _karuṇā_, _muditā_ and _upekkhā_ are sometimes 
called the four divine abidings (_cattāro brahmavihārā_, D.2.196) and 
sometimes the four unlimited states (_catasso appamaññā_, D.3.223). 
Practising them together is called the 'unlimited liberation [from perceptually 
obscuring states]' (_appamāṇā cetovimutti_, S.4.296). The _Mahāvedalla 
Sutta_ (M.1.298) and _Godatta Sutta_ (S.4.296) say the 'makers of limitation' 
(_pamāṇakaraṇo_) are _rāgo doso_ and _moho_ (_rāgo kho āvuso 
pamāṇakaraṇo doso pamāṇakaraṇo moho pamāṇakaraṇo_). Therefore 
the four _brahmavihāras_ should be practised unlimited by _rāgo doso_ and 
_moho_.

==== Parisā Sutta: muditā brahmavihāra

____
The _Parisā Sutta_ (A.1.243) shows that _muditā_ is a joy associated with 
living in harmony with others. It says that in whatever community the bhikkhus 
dwell together in unity, on friendly terms, without quarrelling, like milk and 
water mixed, viewing each other with affection, such a community is called 
united.

_Idha bhikkhave yassaṃ parisāyaṃ bhikkhū samaggā sammodamānā 
avivadamānā khīrodakībhūtā aññamaññaṃ piyacakkhūhi sampassantā 
viharanti. Ayaṃ vuccati bhikkhave samaggā parisā._
____

____
The sutta says when bhikkhus dwell like this, they beget much merit.

_Yasmiṃ bhikkhave samaye bhikkhū samaggā sammodamānā avivadamānā 
khīrodakībhūtā aññamaññaṃ piyacakkhūhi sampassantā viharanti 
bahuṃ bhikkhave bhikkhū tasmiṃ samaye puññaṃ pasavanti._
____

____
At such time they dwell in a divine abiding, that is to say, in the liberation 
&#8203;[from perceptually obscuring states] through _muditā_ (_muditāya 
cetovimuttiyā_).

_Brahmaṃ bhikkhave vihāraṃ tasmiṃ samaye bhikkhū viharanti yadidaṃ 
muditāya cetovimuttiyā._
____

The sutta says that in one who is glad, rapture arises (_pamuditassa pīti 
jāyati_). The sutta therefore treats _muditā_ and gladness (_pamudita_) as 
synonyms (i.e. ..._yadidaṃ muditāya cetovimuttiyā. Pamuditassa pīti 
jāyati..._).

_Pamuditassa_ more usually follows _pāmojjaṃ._ For example, when a bhikkhu 
realises the five hindrances have been abandoned within him, 'gladness arises. 
In one who is glad, rapture arises': _tassime pañca nīvaraṇe pahīṇe 
attani samanupassato pāmojjaṃ jāyati. Pamuditassa pīti jāyati_ (D.1.204). 
This suggests that _muditā_ is close in meaning to _pāmojjaṃ_ gladness.

The phrases 'on friendly terms, without quarrelling, like milk and water mixed, 
viewing each other with affection' support _muditā_ being rendered 
'[unlimited, all-encompassing] joy.' This is confirmed in the _Cūḷagosiṅga 
Sutta_.

==== The Cūḷagosiṅga Sutta

Venerable Anuruddha, living with Venerables Nandiya and Kimbila, was asked by 
the Buddha:

____
-- But, Anuruddha, how do you abide in unity, on friendly terms, without 
quarrelling, like milk and water mixed, viewing each other with affection?

_Yathākathaṃ pana tumhe anuruddhā samaggā sammodamānā avivadamānā 
khīrodakībhūtā aññamaññaṃ piyacakkhūhi sampassantā viharathāti?_
____

-- Bhante, as to that:

1. I reflect: 'It is a gain for me, it is a great gain for me, that I am living 
with such companions in the religious life.
+
****
_Idha mayhaṃ bhante evaṃ hoti: lābhā vata me suladdhaṃ vata me yohaṃ 
eva rūpehi sabrahmacārīhi saddhiṃ viharāmī ti._
****

2. I maintain loving conduct of body, speech, and mind, both openly and 
privately towards those venerable ones.
+
****
_Tassa mayhaṃ bhante imesu āyasmantesu mettaṃ kāyakammaṃ 
paccupaṭṭhitaṃ āvī ceva raho ca mettaṃ vacīkammaṃ 
paccupaṭṭhitaṃ āvī ceva raho ca mettaṃ manokammaṃ 
paccupaṭṭhitaṃ āvī ceva raho ca._
****

3. I think 'How about if I set aside my own wishes and lived according to the 
wishes of these venerables?' And so I do so.
+
****
_Tassa mayhaṃ bhante evaṃ hoti yannūnāhaṃ sakaṃ cittaṃ nikkhipitvā 
imesaṃyeva āyasmantānaṃ cittassa vasena vatteyyan ti. So kho ahaṃ 
bhante sakaṃ cittaṃ nikkhipitvā imesaṃyeva āyasmantānaṃ cittassa 
vasena vattāmi_
****

4. Though we have different bodies, bhante, we assuredly have only one mind.
+
****
_Nānā hi kho no bhante kāyā ekañca pana maññe cittan ti_ (M.1.206).
****

This again supports _muditā_ being rendered as '[unlimited, all-encompassing] 
joy,' i.e. joy unlimited by _rāgo doso_ and _moho._

==== Arati: disgruntlement [with the celibate life]

The _Dasuttara Sutta_ says disgruntlement [with the celibate life] can be 
overcome by [unlimited, all-encompassing] joy:

____
For this is the liberation from disgruntlement [with the celibate life] namely 
the liberation [from perceptually obscuring states] through [unlimited, 
all-encompassing] joy.

_nissaraṇaṃ hetaṃ āvuso aratiyā yadidaṃ muditā cetovimuttī ti._
____

[quote, D.3.249]
____
The sutta says if the practice of [unlimited, all-encompassing] joy is 
developed and cultivated, it is impossible, out of the question, that 
disgruntlement [with the celibate life] would plague one's mind. There is no 
such possibility.

_arati cittaṃ pariyādāya ṭhassati netaṃ ṭhānaṃ vijjati._
____

==== Overcoming disgruntlement: Saṅkhadhama Sutta

The _Saṅkhadhama Sutta_ describes in more detail the practice of _muditā_:

[quote, S.4.322]
____
The noble disciple abides pervading one quarter with a mind of [unlimited, 
all-encompassing] joy, likewise the second quarter, the third quarter, and the 
fourth quarter. Thus above, below, across, in all directions, everywhere, he 
abides pervading the whole world [of beings] with a mind of [unlimited, 
all-encompassing] joy, vast, exalted, unlimited, free of unfriendliness and 
hostility.

_muditāsahagatena cetasā ekaṃ disaṃ pharitvā viharati tathā dutiyaṃ 
tathā tatiyaṃ tathā catutthiṃ; iti uddhamadhotiriyaṃ sabbadhi 
sabbatthatāya sabbāvantaṃ lokaṃ muditāsahagatena cetasā vipulena 
mahaggatena appamāṇena averena avyāpajjhena pharitvā viharati._
____

This meditation can be practised in either a quiet room or deep solitude. For 
example, King Mahāsudassana practised _muditā_ in his golden-gabled chamber 
sitting on a silver couch (D.2.188). The Buddha practised it in a quiet grove 
sitting on a bundle of grass (A.1.183). Thus although the _Parisā Sutta_ says 
_muditā_ arises where the bhikkhus dwell together in unity, it does not mean 
that the formal practice of _muditā_ involves the company of others.

==== Muditā: cure for envy?

The _Visuddhimagga_ says the function of _muditā_ 'resides in being unenvious' 
(Chapter 9, paragraph 95) and 'is always in the sense of gladness at others' 
success' (p.309 n.10). But if _muditā_ meant unenviousness, it would surely 
have featured in the cure of odious envy (_pāpikā issā_) expounded in the 
_Kāya Sutta_ (A.5.40) which says when an envious person sees a fortunate 
layperson or bhikkhu, he is envious about it:

- 'Oh that this grain, silver and gold did not belong to this householder!'

- 'Oh that this Venerable did not receive a good supply of requisites.'

The sutta says envy is abandoned not through _muditā_ but through seeing envy 
over and over again with discernment (_paññāya disvā disvā pahātabbā_).

If envy can be considered part of aversion (_āghāto_), then again _muditā_ 
is not for overcoming envy, says the _Āghātapaṭivinaya Sutta_ (A.3.185), 
saying that three ways of dispelling aversion involve developing _mettā_, 
_karuṇā_, and _upekkhā_, but not _muditā_: _Yasmiṃ bhikkhave puggale 
āghāto jāyetha mettā... karuṇā... upekkhā tasmiṃ puggale 
bhāvetabbā_ (A.3.185).

==== Cultivating pāmojjaṃ gladness

We said above that _muditā_ is close in meaning to _pāmojjaṃ_. Therefore we 
might understand how to develop it by examining _pāmojjaṃ_.

1. Gladness (_pāmojjaṃ_) is associated with virtuous conduct. For one who is 
virtuous (_sīlavato_) there is no need to harbour the aspiration: 'May freedom 
from an uneasy conscience (_avippaṭisāro_) arise in me. It is quite natural 
that this should happen (_dhammatā esā bhikkhave yaṃ sīlavato 
sīlasampannassa avippaṭisāro uppajjati_). For one free from an uneasy 
conscience, there is no need to harbour the aspiration: 'May gladness arise in 
me.' It is quite natural that this should happen (A.5.2).

2. Gladness is associated with physical seclusion (_divā pavivekāya rattiṃ 
paṭisallānāya_). Abiding thus diligently, gladness arises (_evaṃ 
appamattassa viharato pāmujjaṃ jāyati_, S.5.398).

3. Gladness is associated with faith inspiring meditation objects (_tassa 
kismiñcideva pasādaniye nimitte cittaṃ paṇidahato pāmujjaṃ jāyati_, 
S.5.156). This means reflecting on the Buddha, the teaching, the community of 
disciples, one's own virtue, and on how one has the virtuous qualities of the 
devas. As one reflects like this, one's mind becomes serene and gladness arises 
(_cittaṃ pasīdati pāmujjaṃ uppajjati_ A.1.207).

4. Gladness is associated with abandoning the five hindrances. Seeing that the 
five hindrances are abandoned, one becomes glad (_pāmojjaṃ jāyati_); glad, 
rapture arises (_pamuditassa pīti jāyati_ D.1.74).

5. Gladness is associated with righteous conversations (_labhati ca 
tatonidānaṃ pītipāmujjaṃ_): conversations on faith [in the perfection of 
the Perfect One's transcendent insight], virtue, learning, generosity, and 
wisdom (_saddhākathā sīlakathā bāhusaccakathā cāgakathā 
paññākathā_, A.3.181).

6. Gladness is associated with grasping the meaning and truth of the teaching 
_dhamme atthappaṭisaṃvedī ca hoti dhammapaṭisaṃvedī ca_. This gives 
rise to gladness (_pāmujjaṃ jāyati_) This can happen either in the process 
of

- being taught by a teacher ☸ _satthā dhammaṃ deseti_

- teaching others ☸ _paresaṃ deseti_

- reciting the teaching ☸ _sajjhāyaṃ karoti_

- pondering the teaching ☸ _anuvitakketi anuvicāreti manasānupekkhati_

- contempating a meditation object ☸ _samādhinimittaṃ_ (A.3.21).

==== Six principles of cordiality: dhammā sārāṇīyā

Cultivating _muditā_ likely involves the six principles of cordiality, because 
they are the key to harmonious relationships: _chayime bhikkhave dhammā 
sārāṇīyā piyakaraṇā garukaraṇā saṅgahāya avivādāya 
sāmāggiyā ekībhāvāya saṃvattanti_ (M.1.322).

These principles are:

____
(1-3) Maintaining loving conduct of body, speech, and mind, both openly and 
privately towards one's companions in the religious life.

_Idha bhikkhave bhikkhuno mettaṃ kāyakammaṃ... vacīkammaṃ... 
manokammaṃ paccupaṭṭhitaṃ hoti sabrahmacārīsu āvī ceva raho ca._
____

(4) Sharing one's gains with one's virtuous companions in the religious life 
without reservation, including even the contents one's almsbowl.

****
_Puna ca paraṃ bhikkhave bhikkhu ye te lābhā dhammikā dhammaladdhā 
antamaso pattapariyāpannamattampi tathārūpehi lābhehi 
appaṭivibhattabhogī hoti sīlavantehi sabrahmacārīhi sādhāraṇa bhogī._
****

(5) Maintaining virtues that are pure and conducive to inward collectedness both 
openly and privately together with one's companions in the religious life.

****
_Puna ca paraṃ bhikkhave bhikkhu yāni tāni sīlāni akhaṇḍāni 
acchiddāni asabalāni akammāsāni bhujissāni viññuppasatthāni 
aparāmaṭṭhāni samādhisaṃvattanikāni tathārūpesu sīlesu 
sīlasāmaññagato viharati sabrahmacārīhi āvī ceva raho ca._
****

(6) But the chief, the most cohesive, the most unifying of these principles is 
&#8203;[having a shared] view that is noble, and which leads to deliverance [from 
suffering], and which leads the one who practises it to the complete 
destruction of suffering.'

****
_Imesaṃ kho bhikkhave channaṃ sārāṇīyānaṃ dhammānaṃ etaṃ 
aggaṃ etaṃ saṅgāhikaṃ etaṃ saṅghātanikaṃ yadidaṃ yāyaṃ 
diṭṭhi ariyā niyyātikā niyyāti takkarassa sammā dukkhakkhayāya_ 
(M.1.322).
****

We parenthesise '[having a shared]' because the sutta affirms this previously, 
by saying that:

[quote, M.1.322]
____
Whatever view is noble, and which leads to deliverance [from suffering], and 
which leads the one who practises it to the complete destruction of suffering, 
a bhikkhu abides united in a view such as this with his companions in the 
religious life, both in public and in private

_bhikkhu yāyaṃ diṭṭhi ariyā niyyānikā niyyāti takkarassa sammā 
dukkhakkhayāya tathārūpāya diṭṭhiyā diṭṭhisāmaññagato viharati 
sabrahmacārīhi āvī ceva raho ca._
____

==== Limits of muditā

The _Saṅkhadhama Sutta_ says the essential practice of _muditā_ involves 
pervading the whole world [of beings] with a mind of [unlimited, 
all-encompassing] joy. But [unlimited, all-encompassing] joy does not mean 
unconditionally [unlimited, all-encompassing] joy because the scriptures say 
that establishing community harmony involves firstly excluding troublesome 
individuals. The _Dhammacariya Sutta_ says:

[quote, Sn.v.282-283]
____
Then winnow the chaff, those who are not ascetics but consider themselves so. 
Having banished those of unvirtuous desires, conduct, and sphere of personal 
application, live in unity, mindfully, the pure with the pure. Thus living in 
unity, being mindful, you will put an end to suffering.

_Tato palāpe vāhetha assamaṇe samaṇamānine +
Niddhamitvāna pāpicche pāpaācāragocare +
Suddhā suddhehi saṃvāsaṃ kappayavho patissatā +
Tato samaggā nipakā dukkhassantaṃ karissathā ti._
____

[quote, M.1.206]
____
Secondly, one needs a zealous gatekeeper. When the three arahants, Venerables 
Anuruddha, Nandiya, and Kimbila were living together in the Gosinga Sāla-tree 
Wood, their utmost harmony was shielded by a zealous gatekeeper who so 
diligently defended the place against visitors, that when on one occasion the 
Buddha dared enter uninvited, he was swiftly rebuked: 'Do not enter this grove, 
ascetic! There are three noble young men here seeking their Soul. Do not 
disturb them!'

_mā samaṇa etaṃ dāyaṃ pāvisi sant'ettha tayo kulaputtā 
attakāmarūpā viharanti mā tesaṃ aphāsumakāsī ti._
____

==== The problem with muditā

The _Parisā Sutta_ alludes to a potential problem with _muditā_ by suggesting 
that [unlimited, all-encompassing] joy may mean less time for solitude and 
meditation. It says the 'assembly that is foremost' (_aggavatī parisā_) is 
better than a 'harmonious assembly' (_samaggā parisā_) because it is 
dedicated to solitude and to applying energy for the sake of spiritual 
attainment (_paviveke pubbaṅgamā viriyaṃ ārabhanti appattassa pattiyā_ 
(A.1.243).

==== Comparing muditā with mettā and karuṇā

The fragility of _muditā_ is not seen in _mettā_ and _karuṇā_, which 
remain operational under great stress:

____
Bhikkhus, even if thugs should sever your limbs one by one with a two-handled 
saw, he whose mind was thereby filled with hatred would not on that account be 
a practiser of my training system.

_Ubhatodaṇḍakena pi ce bhikkhave kakacena corā ocarakā aṅgamaṅgāni 
okanteyyuṃ tatrāpi yo mano padūseyya na me so tena sāsanakaro._
____

[quote, M.1.129]
____
... In this regard, you should train yourselves thus: 'Neither shall our minds 
be worsened by this, nor shall we utter unvirtuous words, but we shall abide 
tenderly concerned for their welfare, with a mind of [unlimited, 
all-encompassing] goodwill, without inner hatred.'_

_Tatrāpi vo bhikkhave evaṃ sikkhitabbaṃ: na ceva no cittaṃ 
vipariṇataṃ bhavissati. Na ca pāpakaṃ vācaṃ nicchāressāma. 
Hitānukampī ca viharissāma mettacittā na dosantarā._
____

The practice of _muditā_ seems more successful where incompatible individuals 
live apart. _Mettā_ may be strengthened where they live together. But 
_muditā_ is nonetheless an ego-dissolving exercise in which one can live with 
others like milk and water, and allows one to joyously overlook or endure their 
idiosyncracies.

=== Illustrations

.Illustration
====
muditā

&#8203;[unlimited, all-encompassing] joy
====

Now at such time as the bhikkhus dwell in unity, on friendly terms, without 
quarrelling, like milk and water mixed, viewing each other with affection, at 
such time they beget much merit. At such time they dwell in a divine abiding: 
that is to say, in the liberation [from perceptually obscuring states] through 
&#8203;[unlimited, all-encompassing] joy (A.1.243).

.Illustration
====
muditā

&#8203;[unlimited, all-encompassing] joy
====

The noble disciple abides pervading one quarter with a mind of [unlimited, 
all-encompassing] joy, likewise the second quarter, the third quarter, and the 
fourth quarter. Thus above, below, across, in all directions, everywhere, he 
abides pervading the whole world [of beings] with a mind of [unlimited, 
all-encompassing] joy (S.4.322).

.Illustration
====
muditā

&#8203;[unlimited, all-encompassing] joy
====

[quote, D.3.248]
____
If the liberation [from perceptually obscuring states] through [unlimited, 
all-encompassing] joy is developed and cultivated, it is impossible, out of the 
question, that disgruntlement [with the celibate life] would plague your mind. 
There is no such possibility.

_aṭṭhānametaṃ āvuso anavakāso yaṃ muditāya cetovimuttiyā 
bhāvitāya bahulīkatāya yānīkatāya vatthukatāya anuṭṭhitāya 
paricitāya susamāraddhāya atha ca panassa arati cittaṃ pariyādāya 
ṭhassatī ti netaṃ ṭhānaṃ vijjati._
____

.Illustration
====
muditā

&#8203;[unlimited, all-encompassing] joy
====

[quote, S.5.120]
____
The liberation [from perceptually obscuring states] through [unlimited, 
all-encompassing] joy has the state of awareness of boundless mental 
consciousness as its culmination.

_viññāṇañcāyatanaparamāhaṃ bhikkhave muditā cetovimuttiṃ vadāmi._
____

