== Mutta; Vippamutta

=== Renderings

- _mutta_: free from/of

- _mutta_: freed from

- _mutta_: free [from individual existence]

- _mutti_: freedom from

- _mutti_: freedom [from individual existence]

- _vippamutta_: free from/of

- _vippamutta_: freed from

- _vippamutta_: freed from [bondage to]

- _vippamutta_: free [from individual existence]

=== Introduction

==== Mutta and vippamutta: with objects

_Mutta_ and _vippamutta_ can mean 'freed/free from/of some object' or 
'freed/free from/of [bondage to] some object':

[quote, S.3.73]
____
By not grasping one is freed from the Maleficent One.

_anupādiyamāno mutto pāpimato ti._
____

[quote, A.3.16-17]
____
When one's mind is free of these five defilements

_Yato ca kho bhikkhave cittaṃ imehi pañcahi upakkilesehi vippamuttaṃ hoti._
____

[quote, Sn.v.373]
____
Free of [bondage to] the six senses and their objects

_Sabbāyatanehi vippamutto._
____

==== Mutta and vippamutta: when linked to saṅgā and bandhanā

When _mutta_ and _vippamutta_ are linked to _saṅgā_ and _bandhanā_ they 
mean 'free of bondage [to individual existence]', because both _saṅgā_ and 
_bandhanā_ mean 'bondage [to individual existence].' See Glossary sv _Saṅga_ 
and _Bandhana._

[quote, Sn.v.212]
____
One who is free of bondage [to individual existence]

_Saṅgā pamuttaṃ._
____

[quote, Ud.77]
____
Free of bondage [to individual existence].

_bandhanā muttaṃ._
____

==== Mutta and vippamutta: objectless

Where _mutta_ and _vippamutta_ are not linked to an object, various word 
associations show that 'individual existence' is again the object:

[quote, A.4.340]
____
Free [from individual existence], I free [others] from bondage [to individual 
existence]

_mutto mocemi bandhanā._
____

[quote, S.1.198]
____
Free [from individual existence] among those bound [to individual existence]

_Baddhesu muttaṃ._
____

[quote, S.2.279]
____
He is free [from individual existence], emancipated [from individual existence].

_Vippamutto visaṃyutto._
____

That the object of _bandhanā_, _baddhesu_, and _visaṃyutto_ is likewise 
'individual existence,' we have shown sv _Baddha_, _Bandhana_, and _Saṃyutta._

=== Illustrations: mutta

.Illustration
====
muttā

freed
====

[quote, Th.v.11]
____
I am well freed, gloriously freed through my freedom from three crooked things: 
my mortar, my pestle, and my hunchbacked husband. I am freed from birth and 
death. The conduit to renewed states of individual existence has been abolished.

_Sumuttā sādhu muttāmhi tīhi khujjehi muttiyā +
Udukkhalena musalena patinā khujjakena ca +
Muttāmhi jātimaraṇā bhavanetti samūhatā ti._
____

.Illustration
====
mutto

freed
====

[quote, S.1.103]
____
I am indeed freed from that unpleasant self-mortifying practice. It is good 
indeed that I am freed from that useless, unpleasant, self-mortifying practice.

_mutto vatamhi tāya dukkarakārikāya. Sādhu mutto vatamhi tāya 
anatthasaṃhitāya dukkarakārikāya._
____

.Illustration
====
muttaṃ

freed
====

[quote, Ud.6]
____
He did not take delight in her arrival; he did not grieve at her departure; 
Saṅgāmajiṃ, free of bondage [to individual existence], he is what I call a 
Brahman.

_Āyantiṃ nābhinandati pakkamantiṃ na socati. +
Saṅgā saṅgāmajiṃ muttaṃ tamahaṃ brūmi brāhmaṇan ti._
____

.Illustration
====
mutto

freed
====

[quote, Th.v.711]
____
One freed from the place of execution

_mutto āghātanā._
____

[quote, Th.v.712]
____
One who has been freed from a burning house

__ādittāva gharā mutto._
____

.Illustration
====
muttaṃ

freed
====

[quote, M.2.144]
____
One who is completely freed from attachment.

_muttaṃ rāgehi sabbaso._
____

.Illustration
====
muttassa

free [from individual existence]
====

[quote, M.1.386]
____
I am the disciple of the Blessed One who has overcome the bonds [to individual 
existence], who is free [from individual existence].

_Saṅgātigassa muttassa bhagavato tassa sāvako'hamasmi._
____

.Illustration
====
mutti

freedom
====

[quote, M.1.49]
____
The complete passing away and ending of this same craving, the giving up and 
relinquishment of it, the freedom from it, the letting go of it, is called the 
ending of suffering.

_Yo tassāyeva taṇhāya asesavirāganirodho cāgo paṭinissaggo mutti 
anālayo ayaṃ vuccatāvuso dukkhanirodho._
____

.Illustration
====
muttiṃ

freedom [from individual existence]
====

____
Bhikkhus, I will teach you freedom [from individual existence] and the path 
leading to freedom [from individual existence]. Please listen._

_muttiñca vo bhikkhave desissāmi muttigāmiñca maggaṃ taṃ suṇātha._
____

____
What is freedom [from individual existence]?_

_Katamañca bhikkhave muttiṃ:_
____

[quote, S.4.372]
____
The destruction of attachment, hatred, and undiscernment of reality. This is 
called freedom [from individual existence]._

_yo bhikkhave rāgakkhayo dosakkhayo mohakkhayo idaṃ vuccati bhikkhave 
muttiṃ._
____

=== Illustrations: vippamutta

.Illustration
====
vippamutto

free of
====

[quote, Sn.v.913]
____
He is free of dogmatic views._

_Sa vippamutto diṭṭhigatehi._
____

.Illustration
====
vippamuttassa

free of
====

[quote, Dh.v.213]
____
For one who is free of love there is neither grief nor fear.

_Pemato vippamuttassa natthi soko kuto bhayaṃ._
____

.Illustration
====
vippamutto

free of
====

[quote, Sn.v.363]
____
Free of things conducive to psychological bondage,

_saṃyojaniyehi vippamutto._
____

.Illustration
====
vippamuttā

freed from
====

____
Whatever ascetics and Brahmanists have said that deliverance from individual 
existence is through [states of] individual existence

_bhavena bhavassa vippamokkhamāhaṃsu_
____

[quote, Ud.32-3]
____
None of them, I declare, are freed from individual existence

_sabbe te avippamuttā bhavasmā ti vadāmi._
____

.Illustration
====
vippamutto

freed from
====

[quote, Sn 230-232]
____
He is also [forever] freed from the four states of misery

_Catūhapāyehi ca vippamutto._
____

.Illustration
====
vippamutto

freed from [bondage to]
====

[quote, Sn.v.373]
____
One of purified wisdom who has utterly transcended egocentric conception in 
regards to things of the past and future, who is free of [bondage to] the six 
senses and their objects: he would properly fulfil the ideals of religious 
asceticism in the world.

_Atītesu anāgatesu cā pi kappātīto aticca suddhipañño +
Sabbāyatanehi vippamutto sammā so loke paribbajeyya._
____

.Illustration
====
vippamuttā

free [from individual existence]
====

[quote, Sn.v.501]
____
Those who roam the world, spiritually self-reliant, liberated from the 
perception of existence, free [from individual existence] in every respect.

_Ye attadīpā vicaranti loke akiñcanā sabbadhi vippamuttā._
____

.Illustration
====
vippamuttaṃ

free [from individual existence]
====

[quote, Sn.v.176]
____
Behold him, one of profound wisdom, one who sees the subtle meaning of the 
teaching, liberated from the perception of existence, liberated [from 
individual existence] in the sensuous plane of existence, free [from individual 
existence] in every respect, a great seer following the path of divinity.

_Gambhīrapaññaṃ nipuṇatthadassiṃ akiñcanaṃ kāmabhave asattaṃ +
Taṃ passatha sabbadhi vippamuttaṃ dibbe pathe kamamānaṃ mahesiṃ._
____

