== Mā anussavena

=== Renderings

- _mā anussavena_: Do not [abandon religious teachings merely] because they 
do not accord with an oral tradition.

- _mā anussavena_: Do not [accept and abide by religious teachings merely] 
because they accord with an oral tradition.

=== Introduction

==== Kālāma Sutta: for those without faith

The _Kālāma Sutta_ (A.1.188) answers this question: On what basis should 
religious teachings be abandoned or accepted? The sutta is therefore aimed at 
people lacking in established religious faith. It was preached twice by the 
Buddha to such kinds of people, in the _Kālāma Sutta_ and the _Bhaddiya 
Sutta_ (A.2.190). It was never preached to disciples with established faith, 
and it was neither praised nor even mentioned by any of the bhikkhus when 
speaking amongst themselves, showing that for those with established faith, the 
_Kālāma Sutta_ is irrelevant. The _Sāḷha Sutta_ is an unusual sutta which 
we will discuss separately.

==== For those with established faith: irrelevant

For those with established faith the _Kālāma Sutta_ is irrelevant because for 
disciples with faith (_saddhassa sāvakassa_) it is in accordance with the 
teaching (_anudhammo_) to reflect 'The Blessed One is the teacher, I am a 
disciple. The Blessed One knows, I do not know' (_Jānāti bhagavā nāhaṃ 
jānāmī ti_ M.1.480). For those with established faith, the _Kālāma Sutta_ 
is irrelevant, because considering whether the Buddha's teaching should be 
abandoned or accepted implies a denial of one's faith in the Buddha as the 
Teacher.

==== The Sāḷha Sutta

The _Sāḷha Sutta_ (A.1.194) describes an occasion when the _Kālāma Sutta_ 
was preached inappropriately. Firstly, the preacher was Venerable Nandaka, 
foremost among exhorters of the bhikkhunīs (A.1.25). Sāḷha was the grandson 
of Visākhā, not to be confused with Sāḷha the Licchavi who visited the 
Buddha at Kūṭāgārasāla (see _Sāḷha Sutta_, A.2.200).

Why Nandaka preached the _Kālāma Sutta_ to Sāḷha is hard to fathom. 
Sāḷha had asked no questions, and his visit to Nandaka was merely a social 
call with his friend, Rohana. Not only was Sāḷha free of questions, later 
events showed he was free of moral sensibility. This would in due course lead 
him into taking an unhealthy interest in the bhikkhunīs, and on the pretext of 
being their supporter, repeatedly attempting to seduce the beautiful bhikkhunī 
Sundarīnandā, till eventually she became pregnant by him and disrobed 
(Vin.4.211-6).

It can be no surprise, therefore, that the _Sāḷha Sutta_ has a rather 
different conclusion to the _Bhaddiya_ and __Kālāma Sutta__s. Whereas those 
suttas had ended with listeners full of praise and thanks, in the _Sāḷha 
Sutta_, while Venerable Nandaka waxed lyrical about exalted fruits of the 
practice, from Sāḷha and Rohana we hear in appreciation not a word. Bhikkhu 
Bodhi says that the advice of the _Kālāma Sutta_ 'can be dangerous if given 
to those whose ethical sense is undeveloped.' In the _Sāḷha Sutta_ we have a 
good example of what exactly that means.

==== Where the Kālāma Sutta is irrelevant

The _Kālāma Sutta_ is intended for those who have no established religious 
faith, but who nonetheless, as Bodhi says, are 'of refined moral sensitivity.' 
If this is misunderstood, problems arise. This is most obvious in people who 
claim to be disciples of the Buddha but have no faith in him, and no shame of 
wrongdoing, and who therefore easily gravitate to the philosophy of the 
_Kālāma Sutta_. Two suttas show the result of this.

==== The Kīṭāgiri Sutta

In the _Kīṭāgiri Sutta_ (M.1.473) the bhikkhus Assaji and Punabbasuka 
refused the Buddha's request that they abandon the evening meal, because by 
eating all day they claimed they were free of affliction and illness, and 
enjoyed health, strength and a comfortable abiding. When bhikkhus tried to stop 
them, they joked: 'Why should we abandon a benefit visible here and now to 
pursue a benefit in the future?' This defence is reminiscent of the _Kālāma 
Sutta_: 'If you yourselves should consider that this leads to benefit and 
happiness, you should abide by it.' The Buddha summoned them, roundly 
castigated them, and concluded:

[quote, M.1.480]
____
'Bhikkhus, you have lost your way. Bhikkhus, you are conducting yourselves 
wrongly. Bhikkhus, how far you have strayed, you worthless men, from this 
teaching and training system.'

_vippaṭipannā'ttha bhikkhave. Micchāpaṭipannā'ttha bhikkhave. 
Kīvadūrevime bhikkhave moghapurisā apakkantā imasmā dhammavinayā._
____

This, then, is the result of applying the philosophy of the _Kālāma Sutta_, 
when, as a disciple of the Buddha, one should already be established in faith. 
As if to confirm the limitations of the _Kālāma Sutta_, the Buddha told the 
bhikkhus to reflect that 'The Blessed One knows, I do not know.'

The _Kālāma Sutta_ says 'if you yourselves should consider these teachings 
are blameworthy and denounced by the wise, you should abandon them.' The 
admonishment of Assaji and Punabbasuka shows that in certain contexts, one 
should apply this message to the _Kālāma Sutta_ itself.

==== The Bhaddāli Sutta

In the second situation, Venerable Bhaddali was another bhikkhu who was 
apparently swayed by the philosophy of the _Kālāma Sutta_, again with 
reference to avoiding the evening meal (_Bhaddāli Sutta_, M.1.437). Bhaddali's 
excuse was 'I might become anxious and uneasy about it.' This is reminiscent of 
the _Kālāma Sutta_'s advice: 'If you yourselves should consider these things 
lead to harm and suffering you should abandon them.'

The Buddha criticised Bhaddali for not simply following the bhikkhu's code of 
conduct as laid down, and said that the faith most bhikkhus had for the Buddha 
was such that, if asked by him to 'be a plank for me across the mud' they would 
simply obey. He said Bhaddali had no faith at all in the Buddha, and was 
therefore not even a _saddhānusārī_. He was an empty, hollow wrongdoer 
(_ritto tuccho aparaddho_).

This shows that the problem with following 'what one knows for oneself' lies in 
the fact that religious practice is often uncomfortable, and the advice in the 
_Kālāma Sutta_ to follow what one considers beneficial is rather easily 
confused with following what one considers pleasant. Bhikkhu Bodhi calls it 
'that egregious old tendency to interpret the Dhamma according to whatever 
notions are congenial to oneself.'

It is pertinent to recall the words of the bhikkhu who said:

[quote, M.2.225]
____
'When I live as I please, spiritually unwholesome factors flourish, spiritually 
wholesome factors fade. But when I apply myself to what is unpleasant, 
spiritually unwholesome factors fade, spiritually wholesome factors flourish. 
How about if I applied myself to what is unpleasant?'

_Puna ca paraṃ bhikkhave bhikkhu iti paṭisañcikkhati 'yathāsukhaṃ kho 
me viharato akusalā dhammā abhivaḍḍhanti kusalā dhammā parihāyanti. 
Dukkhāya pana me attānaṃ padahato akusalā dhammā parihāyanti kusalā 
dhammā abhivaḍḍhanti. Yannūnāhaṃ dukkhāya attānaṃ padaheyyan ti._
____

==== Mā anussavena: what is the verb?

_Mā anussavena_ is commonly translated: 'Do not go by oral tradition.' The 
verb 'go' is assumed because the verb is apparently missing. But the sentence 
does indeed have a verb, because the sutta concerns the question, on what basis 
should religious teachings be abandoned or accepted. The verbs 'abandon' and 
'accept' occur when the Buddha tells the Kālāmas that under certain 
circumstances this is what they should do (_atha tumhe kālāmā 
pajaheyyātha... atha tumhe kālāmā upasampajja vihareyyātha_). These, then, 
are the verbs to use instead of 'go.'

- _mā anussavena_: Do not [abandon religious teachings merely] because they 
do not accord with an oral tradition.

- _mā anussavena_: Do not [accept and abide by religious teachings merely] 
because they accord with an oral tradition.

==== Dhammā: teachings

Another problem with the _Kālāma Sutta_ is how to render _dhammā_ because it 
has two fields of application. In one case, it means 'teachings,' and is 
equivalent to _vādaṃ_ in the following passage, which we have divided into 
Question and Answer:

*Question:*

____
-- There are some ascetics and Brahmanists, bhante, who visit Kesaputta. They 
expound and explain only their own teachings (_sakaṃyeva vādaṃ_); the 
teachings of others (_parappavādaṃ_) they despise, revile, and pull to 
pieces. Some other ascetics and Brahmanists too, bhante, come to Kesaputta. 
They also expound and explain only their own teachings; the teachings of others 
they despise, revile, and pull to pieces.

_Te sakaṃyeva vādaṃ dīpenti jotenti parappavādaṃ pana khuṃsenti 
vambhenti paribhavanti omakkhiṃ karonti_

... Bhante, there is unsureness, there is doubt in us concerning them. Which of 
these reverend ascetics and Brahmanists spoke the truth and which falsehood?"

_Tesaṃ no bhante amhākaṃ hoteva kaṅkhā hoti vicikicchā. Ko su nāma 
imesaṃ bhavataṃ samaṇabrāhmaṇānaṃ saccaṃ āha ko musā ti?_
____

*Answer:*

[quote, A.1.189]
____
-- Kālāmas, if you yourselves should consider:

_Yadā tumhe kālāmā attanāva jāneyyātha_

... These teachings (_dhammā_) are unwholesome;

_ime dhammā akusalā_

... these teachings are blameworthy;

_ime dhammā sāvajjā_

... these teachings are denounced by the wise;

_ime dhammā viññugarahitā_

... when followed and taken up

_ime dhammā samattā samādinnā_

... these teachings lead to harm and suffering,"

_ahitāya dukkhāya saṃvattantīti_

... you should abandon them.

_atha tumhe kālāmā pajaheyyātha._
____

==== Dhammā: six phenomena

In the other case, _dhammā_ is used in reference to six phenomena: greed, 
hatred, and undiscernment of reality (_lobho doso moho_) and their opposites, 
non-greed, non-hatred, and discernment of reality (_alobho adoso amoho_). The 
sutta calls these phenomena _dhammā_ which we render as 'factors.'

[quote, A.1.189-191]
____
-- 'What do you think, Kālāmas? Are these factors spiritually wholesome, or 
spiritually unwholesome?'

_Taṃ kiṃ maññatha kālāmā ime dhammā kusalā vā akusalā vā ti?_

-- 'Spiritually unwholesome, bhante.'

_Akusalā bhante._
____

==== Two lists of reasons

Another problem with the _Kālāma Sutta_ is that there are two lists:

1. ten reasons for not abandoning teachings, and

2. ten reasons for not accepting teachings

But the two lists are identical, where it would make more sense if they were 
not. For example, _mā anussavena_ means teachings should not be abandoned or 
accepted merely because of their relationship to an oral tradition. But this 
would be clearer if _mā anussavena_ was phrased either positively or 
negatively, as follows:

- Do not [abandon religious teachings merely] because they do not accord with 
an oral tradition.

- Do not [accept and abide by religious teachings merely] because they accord 
with an oral tradition.

We say 'merely because' because the _Kālāma Sutta_ is not about _whether_ 
teachings should be abandoned or accepted, but on what basis and for what 
reason this should happen. By all means, abandon teachings, but not merely 
because they do not accord with an oral tradition etc.

==== If you yourselves should consider: yadā attanāva jāneyyātha

We deal with this issue elsewhere, sv _Jāneyyāti_, where we note that the 
prominent phrase in the sutta is often translated by ignoring the optative 
tense, saying:

[quote, A.1.190]
____
When you know for yourselves: 'These things are unwholesome... then you should 
abandon them.

_Yadā tumhe kālāmā attanāva jāneyyātha ime dhammā akusalā... atha 
tumhe kālāmā pajaheyyātha._
____

But to propose that the Buddha is saying an untrained disciple could really 
know for himself what things are unwholesome would negate the rationale for a 
religious training system. We suggest that this excerpt is more accurately and 
more rationally translated with 'should consider.' The context obliges one to 
translate _yadā_ as 'if' not 'when':

[quote, A.1.190]
____
Kālāmas, if you yourselves should consider: "These teachings are 
unwholesome... you should abandon them.

_Yadā tumhe kālāmā attanāva jāneyyātha ime dhammā akusalā... atha 
tumhe kālāmā pajaheyyātha._
____

For further notes, see sv _Jāneyyāti._

==== The Buddha's attitude to self-reliance

To what degree the Buddha expected self-reliance from his disciples is obvious 
in these two quotes:

1. So long as in relation to spiritually wholesome factors, [what should be 
done] by a bhikkhu is not done, neither with the help of faith [in the 
perfection of the Buddha's transcendent insight], nor with the help of shame of 
wrongdoing, nor with the help of fear of wrongdoing, nor with the help of 
energetic application [to the practice], nor with the help of wisdom, that 
bhikkhu should be looked after by me.
+
****
_Evameva kho bhikkhave yāvakīvañca bhikkhuno saddhāya akataṃ hoti 
kusalesu dhammesu hiriyā akataṃ hoti kusalesu dhammesu ottappena akataṃ 
hoti kusalesu dhammesu viriyena akataṃ hoti kusalesu dhammesu paññāya 
akataṃ hoti kusalesu dhammesu anurakkhitabbo tāva me so bhikkhave bhikkhu 
hoti._
****
+
[quote, A.3.6]
____
But when [what should be done] by a bhikkhu is done, either with the help of 
faith [in the perfection of the Buddha's transcendent insight], or with the 
help of shame of wrongdoing, or with the help of fear of wrongdoing, or with 
the help of energetic application [to the practice], or with the help of 
wisdom, I am unconcerned about him, thinking: 'The bhikkhu can now look after 
himself. He will not be negligently applied [to the practice].'

_Yato ca kho bhikkhave bhikkhuno saddhāya kataṃ hoti kusalesu dhammesu 
hiriyā kataṃ hoti kusalesu dhammesu ottappena kataṃ hoti kusalesu dhammesu 
viriyena kataṃ hoti kusalesu dhammesu paññāya kataṃ hoti kusalesu 
dhammesu anapekkho dānāhaṃ bhikkhave tasmiṃ bhikkhusmiṃ homi 
Attaguttodāni bhikkhu nālaṃ pamādāyā ti._
____

2. Therefore, Ānanda, dwell spiritually self-reliant, with yourself as your 
refuge, with no other refuge, relying completely on the teaching, with the 
teaching as your refuge, with no other refuge. How do you do this?
+
****
_Tasmātihānanda attadīpā viharatha attasaraṇā anaññasaraṇā 
dhammadīpā dhammasaraṇā anaññasaraṇā. Kathañcānanda bhikkhu 
attadīpo viharati attasaraṇo anaññasaraṇo dhammadīpo dhammasaraṇo 
anaññasaraṇo:_
****

[quote, S.5.154]
____
... In this regard a bhikkhu abides contemplating the nature of the body, 
vigorously, fully consciously, and mindfully, having eliminated greed and 
dejection in regard to the world [of phenomena].

_idhānanda bhikkhu kāye kāyānupassī viharati ātāpī sampajāno satimā 
vineyya loke abhijjhādomanassaṃ._

... He abides contemplating the nature of sense impressions... the nature of 
the mind... the nature of certain objects of the systematic teachings

_Vedanāsu vedanānupassī viharati ātāpī sampajāno satimā vineyya loke 
abhijjhādomanassaṃ. Citte cittānupassī viharati ātāpī sampajāno 
satimā vineyya loke abhijjhādomanassaṃ. Dhammesu dhammānupassī viharati 
ātāpī sampajāno satimā vineyya loke abhijjhādomanassaṃ._

... Thus a bhikkhu abides spiritually self-reliant, with himself as his refuge, 
with no other refuge, relying completely on the teaching, with the teaching as 
his refuge, with no other refuge.

_Evaṃ kho ānanda bhikkhu attadīpo viharati attasaraṇo anaññasaraṇo 
dhammadīpo dhammasaraṇo anaññasaraṇo_

... Those bhikkhus, either now or after my passing, who abide spiritually 
self-reliant, with themselves as their refuge, with no other refuge; relying 
completely on the teaching, with the teaching as their refuge, with no other 
refuge; it is these bhikkhus, Ānanda, who will be for me foremost amongst 
those desirous of the training.

_Ye hi keci ānanda etarahi vā mamaccaye vā attadīpā viharissanti 
attasaraṇā anaññasaraṇā dhammasaraṇā anaññasaraṇā tamatagge me 
te ānanda bhikkhu bhavissanti ye keci sikkhākāmāti._
____

=== Illustrations

.Illustration
====
mā anussavena

Do not [abandon religious teachings]:
====

[quote, A.1.189]
____
&#8203;[merely] because they do not accord with an oral tradition.

_mā anussavena_

&#8203;[merely] because they do not accord with a religious lineage.

_mā paramparāya_

&#8203;[merely] because they do not accord with popular opinion.

_mā itikirāya_

&#8203;[merely] because they do not accord with the scriptural collections.

_mā piṭakasampadānena_

&#8203;[merely] because they do not accord with logical reasoning.

_mā takkahetu_

&#8203;[merely] because they not accord with inferential reasoning.

_mā nayahetu_

&#8203;[merely] because they do not accord with reasoned cogitation.

_mā ākāraparivitakkena_

&#8203;[merely] because of a considered disapproval of some view.

_mā diṭṭhinijjhānakkhantiyā_

&#8203;[merely] because of their implausibility.

_mā bhabbarūpatāya_

&#8203;[merely] because the expounding ascetic is not your teacher.

_mā samaṇo no garū ti_

Kālāmas, if you yourselves should consider:

_Yadā tumhe kālāmā attanāva jāneyyātha_

"These teachings are unwholesome;

_ime dhammā akusalā_

these teachings are blameworthy;

_ime dhammā sāvajjā_

these teachings are denounced by the wise;

_ime dhammā viññugarahitā_

when followed and taken up

_ime dhammā samattā samādinnā_

these teachings lead to harm and suffering,"

_ahitāya dukkhāya saṃvattantīti_

you should abandon them.

_atha tumhe kālāmā pajaheyyātha._
____

.Illustration
====
mā anussavena

Do not [accept and abide by religious teachings]:
====

[quote, A.1.190]
____
&#8203;[merely] because they accord with an oral tradition.

_mā anussavena_

&#8203;[merely] because they accord with a religious lineage.

_mā paramparāya_

&#8203;[merely] because they accord with popular opinion.

_mā itikirāya_

&#8203;[merely] because they accord with the scriptural collections.

_mā piṭakasampadānena_

&#8203;[merely] because they accord with logical reasoning.

_mā takkahetu_

&#8203;[merely] because they accord with inferential reasoning.

_mā nayahetu_

&#8203;[merely] because they accord with reasoned cogitation.

_mā ākāraparivitakkena_

&#8203;[merely] because of a considered approval of some view.

_mā diṭṭhinijjhānakkhantiyā_

&#8203;[merely] because of their plausibility.

_mā bhabbarūpatāya_

&#8203;[merely] because the expounding ascetic is your teacher.

_mā samaṇo no garū ti_

Kālāmas, if you yourselves should consider:

_Yadā tumhe kālāmā attanāva jāneyyātha_

"These teachings are wholesome;

_ime dhammā kusalā_

these teachings are blameless;

_ime dhammā anavajjā_

these teachings are praised by the wise;

_ime dhammā viññuppasatthā_

when followed and taken up

_ime dhammā samattā samādinnā_

these teachings lead to benefit and happiness,"

_hitāya sukhāya saṃvattantīti_

you should accept and abide by them.

_atha tumhe kālāmā upasampajja vihareyyātha._
____

