== Mūlakā

=== Renderings

- _mūlakā_: stem from

=== Illustrations

.Illustration
====
mūlakā

stem from
====

[quote, A.4.339]
____
All things stem from fondness.

_chandamūlakā āvuso sabbe dhammā._
____

.Illustration
====
mūlakā

stem from
====

[quote, S.4.215]
____
Bhikkhus, these three types of sense impression are born of sensation, stem 
from sensation...

_tisso imā bhikkhave vedanā phassajā phassamūlakā._
____

Bodhi: these three feelings are born of contact, rooted in contact

.Illustration
====
mūlakā

stem from
====

[quote, It.35]
____
Whatever bad bourns there are in this world or in the world beyond, all stem 
from uninsightfulness into reality

_Yā kācimā duggatiyo asmiṃ loke paramhi ca avijjāmūlakā sabbā._
____

Woodward: All rooted are in ignorance.

.Illustration
====
mūlakā

stem from
====

____
Nine conditions that stem from craving:

_nava taṇhāmūlakā dhammā_
____

____
Because of craving, search._

_taṇhaṃ paṭicca pariyesanā_
____

[quote, A.4.401]
____
Because of search, acquisition

_pariyesanaṃ paṭicca lābho._
____

Bodhi: nine things rooted in craving

.Illustration
====
mūlakā

stem from
====

[quote, S.3.100-1]
____
These five grasped aggregates stem from fondness

_Ime kho bhikkhu pañcupādānakkhandhā chandamūlakā ti._
____

.Illustration
====
mūlakā

stem from
====

[quote, A.4.157]
____
Bhante, for us the teachings stem from the Blessed One.

_bhagavammūlakā no bhante dhammā._
____

.Illustration
====
mūlakā

stem from
====

[quote, S.5.42]
____
Whatever spiritually wholesome factors there are, they all stem from diligence 
&#8203;[in the practice]._

_ye keci kusalā dhammā sabbe te appamādamūlakā._
____

.Illustration
====
mūlakā

stem from
====

[quote, S.5.91]
____
Bhikkhus, whatever factors that are spiritually wholesome, part of what is 
spiritually wholesome, pertaining to what is spiritually wholesome, they all 
stem from proper contemplation

_ye keci bhikkhave dhammā kusalā kusalabhāgiyā kusalapakkhiyā sabbe te 
yoniso manasikāramūlakā._
____

.Illustration
====
mūlakā

stem from
====

[quote, S.2.263]
____
All spiritually unwholesome factors stem from uninsightfulness into reality.

_ye keci akusalā dhammā sabbe te avijjāmūlakā._
____

