== Mūla

=== Renderings

- _mūla_: origin

- _mūla_: essence

- _mūla_: root

=== Illustrations

.Illustration
====
mūlaṃ

origin
====

____
"'A carbuncle,' bhikkhus, is a metaphor for this [wretched human] body made of 
the four great material phenomena, arisen from parents, and fed on rice and 
gruel. It is unlasting, and is liable to be injured, abraded, broken, and 
demolished.

_Gaṇḍo ti kho bhikkhave imassetaṃ cātummahābhūtikassa kāyassa 
adhivacanaṃ mātāpettikasambhavassa odanakummāsūpacayassa 
aniccucchādana-parimaddana-bhedana-viddhaṃsanadhammassa._
____

____
The origin of the carbuncle, is a metaphor for craving

_Gaṇḍamūlan ti kho bhikkhave taṇhāyetaṃ adhivacanaṃ._
____

[quote, S.4.83]
____
When a bhikkhu has abandoned craving, so it is chopped down at the root, 
completely and irreversibly destroyed, never to arise again in future, in such 
a case the bhikkhu has extirpated the origin of the carbuncle not extirpated 
before

_Yato kho bhikkhave bhikkhuno taṇhā pahīnā hoti ucchinnamūlā 
tālāvatthukatā anabhāvakatā āyatiṃ anuppādadhammā. Evaṃ kho 
bhikkhave bhikkhuno apalikhataṃ gaṇḍamūlaṃ palikhataṃ hoti._
____

.Illustration
====
mūlaṃ

origin
====

____
And what, friends, is spiritually unwholesome

_katamaṃ panāvuso akusalaṃ_
____

____
killing is spiritually unwholesome

_pāṇātipāto akusalaṃ_
____

...

And what is the origin of what is spiritually unwholesome (_akusalamūlaṃ_)?

____
Greed is an origin of what is spiritually unwholesome.

_lobho akusalamūlaṃ_
____

____
Hatred is an origin of what is spiritually unwholesome.

_doso akusalamūlaṃ_
____

____
Undiscernment of reality is an origin of what is spiritually unwholesome.

_moho akusalamūlaṃ_
____

And what is spiritually wholesome (_kusalaṃ_)?

Refraining from killing is spiritually wholesome _pāṇātipātā veramaṇī 
kusalaṃ_

...

And what is the origin of what is spiritually wholesome (_kusalamūlaṃ_)?

____
Non-greed is an origin of what is spiritually wholesome.

_alobho kusalamūlaṃ_
____

____
Non-hatred is an origin of what is spiritually wholesome.

_adoso kusalamūlaṃ_
____

[quote, M.1.47]
____
Discernment of reality is an origin of what is spiritually wholesome.

_amoho kusalamūlaṃ._
____

.Illustration
====
mūlaṃ

origin
====

[quote, M.1.453-4]
____
Attachment is the origin of suffering

_upadhi dukkhassa mūlan ti._
____

.Illustration
====
mūlaṃ

origin
====

____
Having removed [the arrow of] craving together with its origin,

_samūlaṃ taṇhaṃ abbuyha_
____

[quote, S.3.26]
____
One is free of craving. One has realised the Untroubled.

_nicchāto parinibbuto._
____

Comment:

Craving arises from seeing things the wrong way, which is therefore its origin, 
as follows:

____
Whatever ascetics and Brahmanists at present regard that in the world which is 
agreeable and pleasing as lasting, as existentially substantial, as endowed 
with personal qualities, as unailing, as free of danger: they nurture craving.

_Yepi hi keci bhikkhave etarahi samaṇā vā brāhmaṇā vā yaṃ loke 
piyarūpaṃ sātarūpaṃ taṃ niccato passanti sukhato passanti attato 
passanti ārogyato passanti khemato passanti te taṇhaṃ vaḍḍhenti_
____

[quote, S.2.110-112]
____
Whatever ascetics and Brahmanists at present regard that in the world which is 
agreeable and pleasing as unlasting, as existentially void, as void of personal 
qualities, as an illness, as full of danger: they abandon craving.

_Yepi hi ke ci bhikkhave etarahi samaṇā vā brāhmaṇā vā yaṃ loko 
piyarūpaṃ sātarūpaṃ taṃ aniccato passanti dukkhato passanti anattato 
passanti rogato passanti bhayato passanti. Te taṇhaṃ pajahanti._
____

.Illustration
====
mūlaṃ

origin
====

[quote, A.2.63]
____
Having eliminated the stain of stinginess together with its origin, they are 
beyond criticism.

_Vineyya maccheramalaṃ samūlaṃ aninditā._
____

.Illustration
====
mūlaṃ

origin
====

[quote, Sn.v.916]
____
A wise person should completely destroy the origin of entrenched conception, 
the notion "I am."

_mūlaṃ papañcasaṅkhāya mantā asmī ti sabbamuparundhe._
____

.Illustration
====
mūlā

origin
====

[quote, Th.v.98; S.4.76]
____
One's perceptually obscuring states develop, the origin of individual 
existence, leading to renewed states of individual existence.

_Tassa vaḍḍhanti āsavā bhavamūlā bhavagāmino ti._
____

.Illustration
====
mūla

essence
====

[quote, M.1.1]
____
I will expound for your benefit a systematic exposition on the essence of the 
whole teaching.

_Sabbadhammamūlapariyāyaṃ vo bhikkhave desessāmi._
____

.Illustration
====
mūlaṃ

essence
====

[quote, Th.v.1027]
____
One should devote oneself to one of great learning. One should not allow the 
teaching to be lost. It is the essence of the religious life. Therefore one 
should be an expert in the teaching.

_Bahussutaṃ upāseyya sutañca na vināsaye +
Taṃ mūlaṃ brahmacariyassa tasmā dhammadharo siyā._
____

.Illustration
====
mūlāni

root
====

[quote, S.4.368-373]
____
These are the roots of trees. These are the solitary abodes. Meditate, 
bhikkhus. Do not be negligently applied [to the practice].

_Etāni bhikkhave rukkhamūlāni etāni suññāgārāni jhāyatha bhikkhave 
mā pamādattha._
____

.Illustration
====
mūlaṃ

root
====

____
If the community of bhikkhus, not having investigated that case, not having got 
to the root of it, achieves unanimity, that unanimity is unrighteous.

_saṅgho taṃ vatthuṃ avinicchinitvā amūlā mūlaṃ gantvā 
saṅghasāmaggiṃ karoti adhammikā sā upāli saṅghasāmaggī ti_
____

[quote, Vin.1.358]
____
If the community of bhikkhus, having investigated the case, having got to the 
root of it, achieves unanimity in the community of bhikkhus, that unanimity is 
righteous

_saṅgho taṃ vatthuṃ vinicchinitvā mūlā mūlaṃ gantvā 
saṅghasāmaggiṃ karoti, dhammikā sā upāli saṅghasāmaggī ti._
____

.Illustration
====
mūlajātā

rooted
====

[quote, M.1.320]
____
When one's faith in the [perfection of the] Perfect One's [transcendent 
insight] is settled, rooted, and established, and described in these terms, 
words, and phrases, then one's faith is said to be supported by reasons, rooted 
in vision [of things according to reality], and firm. It is not shakeable by 
any ascetic, Brahmanist, deva, māra, or brahmā, or by anyone in the world.

_Yassa kassa ci bhikkhave imehi ākārehi imehi padehi imehi vyañjanehi 
tathāgate saddhā niviṭṭhā hoti mūlajātā patiṭṭhitā ayaṃ 
vuccatī bhikkhave ākāravatī saddhā dassanamūlikā daḷhā asaṃhāriyā 
samaṇena vā brāhmaṇena vā devena vā mārena vā brahmunā vā kenaci 
vā lokasmiṃ._
____

