== Na ca maṃ dhammādhikaraṇaṃ vihesesi

=== Renderings

- _na ca maṃ dhammādhikaraṇaṃ vihesesi_ (or _viheṭhesi_): he did not 
trouble me through [failure to quickly understand] the teaching

=== Introduction

==== The Buddha's objection

On six occasions when disciples died, the Buddha spoke in homage of them, 
saying that:

[quote, or _viheṭhesi_]
____
'He did not trouble me on account of the teaching.'

_na ca maṃ dhammādhikaraṇaṃ vihesesi._
____

Are we meant to understand from this that the Buddha objected to being 
lengthily questioned on the teachings? Or objected to rude or pestering 
disciples placing demands on his time and energy? We will show that neither of 
these are the case, but rather, he was complaining about those who fail to 
quickly penetrate the teaching. A good example of this would be Sāti:

____
Although questioned, interrogated, and examined by those bhikkhus, the bhikkhu 
Sāti, son of a fisherman, dogmatically grasping and stubbornly adhering to 
that same odious dogmatic view, asserted:

_tadeva pāpakaṃ diṭṭhigataṃ thāmasā parāmassa abhinivissa voharati_
____

• 'As I understand the teaching explained by the Blessed One, it is this 
personal _viññāṇa_ that roams and wanders the round of birth and death, 
not another. +
☸... _yathā tadevidaṃ viññāṇaṃ sandhāvati saṃsarati anaññan 
ti_ (M.1.257).

==== Time and energy consuming teachings

Firstly, all six occasions when our phrase was used involved the Buddha in 
making himself available as a teacher, even visiting disciples in their homes. 
So his complaint could not be about offering others his time and energy. 
Indeed, some of these occasions involved extensive conversations, for example 
with Puṇṇa (_Puṇṇovāda Sutta_, M.3.267) and Pukkusāti 
(_Dhātuvibhaṅga Sutta_, M.3.247). So when the Buddha praised Puṇṇa and 
Pukkusāti for _na ca maṃ dhammādhikaraṇaṃ vihesesi_, it was obviously 
not in reference to the amount of his time and energy they had consumed.

==== Two cases of nuisance

In two of our six cases, there was some actual nuisance involved.

1. Firstly, Bāhiya of the Bark Robe demanded an immediate explanation of the 
teaching when the Buddha was on almsround. Twice he asked, and twice the Buddha 
refused:
+
[quote, Ud.7]
____
This is not the right time, Bāhiya. We have entered the village for almsfood.

_akālo kho tāva bāhiya. Antaragharaṃ paviṭṭhamhā piṇḍāyā ti._
____
+
Only at the third request did the Buddha comply, standing there with his laden 
almsbowl.

2. The second potential nuisance was with Pukkusāti, who later confessed lack 
of respect:
+
[quote, M.3.246]
____
A transgression overcame me, bhante, in that, foolishly, stupidly, and badly 
behaved, I presumed to address the Blessed One as 'friend.'

_accayo maṃ bhante accagamā yathābālaṃ yathāmūḷhaṃ yathā 
akusalaṃ yohaṃ bhagavantaṃ āvusovādena samudācaritabbaṃ 
amaññissaṃ._
____

Thus, when the Buddha praised Bāhiya and Pukkusāti for _na ca maṃ 
dhammādhikaraṇaṃ vihesesi_, it was obviously not in reference to being 
pressurised to teach at an inappropriate moment, nor was it in reference to the 
lack of proper respect that he had been shown. We will see what the Buddha was 
complaining about when we examine the _Kinti Sutta_.

==== Four cases of imperfect discipleship

In only two of our cases, with Puṇṇa and Bāhiya, did the Buddha's 
instruction lead to arahantship. The other four cases led to non-returnership 
or stream-entry, which is considered blameworthy because:

[quote, S.4.60]
____
He who lays down one body and takes up a new body is one I call blameworthy.

_yo kho sāriputta imañca kāyaṃ nikkhipati aññañca kāyaṃ upādiyati 
tamahaṃ saupavajjoti vadāmi._
____

Thus, when the Buddha praised the brahman Brahmāyu, Pukkusāti, Dīghāvu, and 
Suppabuddha for _na ca maṃ dhammādhikaraṇaṃ vihesesi_, it was obviously 
not in reference to their blameworthiness in failing to attain arahantship 
before rebirth.

==== Kinti Sutta

The expression _vihesā bhavissati_ is explained in the _Kinti Sutta_, which 
says that when one bhikkhu admonishes another there may be problems for both 
parties. The possible combination of problems is found in these reflections:

1. I will not be troubled, and the other person will not be distressed, for he 
is not ill-tempered and resentful, and not strongly opinionated and 
relinquishes his views readily.
+
****
_mayhañca avihesā bhavissati parassa ca puggalassa anupaghāto. Paro hi 
puggalo akkodhano anupanāhī adaḷhadiṭṭhī suppaṭinissaggī._
****

2. I will not be troubled, but the other person will be distressed, for though 
he is ill-tempered and resentful, he is not strongly opinionated and 
relinquishes his views readily.
+
****
_mayhaṃ kho avihesā bhavissati parassa ca puggalassa upaghāto. Paro hi 
puggalo kodhano upanāhī adaḷhadiṭṭhī suppaṭinissaggī._
****

3. I will be troubled, but the other person will not be distressed, for though 
he is not ill-tempered and resentful, he is strongly opinionated and 
relinquishes his views reluctantly.
+
****
_mayhaṃ kho vihesā bhavissati parassa ca puggalassa anupaghāto. +
****
Paro hi puggalo akkodhano anupanāhī daḷhadiṭṭhī duppaṭinissaggī._

4. I will be troubled, and the other person will be distressed, for he is 
ill-tempered and resentful, and strongly opinionated and relinquishes his views 
reluctantly.
+
****
_mayhañca kho vihesā bhavissati parassa ca puggalassa upaghāto. +
****
Paro hi puggalo kodhano upanāhī daḷhadiṭṭhī duppaṭinissaggī_ 
(M.2.241).

This shows that the Buddha would not be troubled by those who become angry and 
resentful, but by those who are strongly opinionated and who relinquish their 
views reluctantly. The same pattern is seen in our six cases, all of which 
involve individuals who, though not necessarily arahants, nonetheless quickly 
achieved high spiritual attainments. The six cases are enumerated below.

Thus, _vihesā bhavissati_ means slowness to comprehend a teaching. It shows 
that what the Buddha appreciated from disciples was quick understanding. This 
is confirmed when he said:

[quote, Vin.1.5]
____
If I were to explain the teaching to others and they did not understand, it 
would be wearisome and troublesome for me.

_Ahañceva kho pana dhammaṃ deseyyaṃ pare ca me na ājāneyyuṃ so 
mama'ssa kilamathe sā mama'ssa vihesā ti._
____

==== The six cases: quick understanding of the teaching

The six cases we refer to are these:

1. The brahman Brahmāyu became a non-returner before his death, which occurred 
within days of meeting the Buddha (M.2.146).

2. Pukkusāti became a non-returner during his overnight teaching from the 
Buddha, or on the following morning before his untimely death (M.3.247).

3. Puṇṇa became an arahant in his first rains residency period after 
meeting the Buddha (M.3.270) (S.4.63).

4. Dīghāvu was already a stream-enterer when he asked the Buddha to visit him 
on his deathbed, and became a non-returner before he died (S.5.346).

5. Bāhiya became an arahant immediately on being exposed to the teaching 
(Ud.8-9).

6. Suppabuddha became a stream-enterer either while listening to his first 
discourse on the teaching or immediately thereafter, before his untimely death 
(Ud.50).

==== Failure to quickly understand the teaching: conclusion

The six cases suggest that 'to understand the teaching' means to achieve at 
least stream-entry. To 'quickly understand' means either:

1. to achieve stream-entry while listening to one's first discourse, or

2. to achieve non-returnership within days of hearing one's first discourse, or

3. to achieve arahantship in one's first rains residency period.

=== Illustrations

.Illustration
====
na ca maṃ dhammādhikaraṇaṃ vihesesi

he did not trouble me through [failure to quickly understand] the teaching
====

[quote, Ud.8-9]
____
Bāhiya of the Bark Robe was wise, bhikkhus. He practised in accordance with 
the teaching and did not trouble me through [failure to quickly understand] the 
teaching. Bāhiya of the Bark Robe has passed away to the 
Untroubled-without-residue.

_Paṇḍito bhikkhave bāhiyo dārucīriyo paccapādi dhammassānudhammaṃ na 
ca maṃ dhammādhikaraṇaṃ vihesesi. Parinibbuto bhikkhave bāhiyo 
dārucīriyo ti._
____

