== Nahātaka

=== Renderings

- _nahātaka_: spiritually cleansed

=== Introduction

==== Nahāta: externally bathed or spiritually cleansed

_Nahāta_ can mean externally bathing, or spiritually cleansing:

[quote, Vin.2.220-1]
____
By one who has bathed and is getting out (of the water), way should be made for 
those who are getting into it.

_Nahātena uttarantena otarantānaṃ maggo dātabbo._
____

[quote, A.5.249]
____
One's head washed

_sīsaṃ nahātaṃ._
____

[quote, M.1.280]
____
Unvirtuous, spiritually unwholesome factors are cleansed away

_Nahātāssa honti pāpakā akusalā dhammā._
____

==== Nahāna, bath, external or inward

_Nahāna_ can likewise be applied both externally and inwardly. When someone 
told Nandaka, the minister of the Licchavis: 'It is time for your bath, sir' 
(_nahānakālo bhante ti_) he replied:

[quote, S.5.390]
____
-- 'Enough now, I say, with that external bath. This internal bath will 
suffice, namely, faith in the Blessed One.'

_Alaṃ dāni bhaṇe etena bāhirena nahānena. Alamidaṃ ajjhattaṃ 
nahānaṃ bhavissati yadidaṃ bhagavati pasādo ti._
____

==== Nahātaka: religious connotations

By comparison, _nahātaka_ has only religious connotations, meaning 
'spiritually cleansed' (Thī.v.251). The word is never applied to external 
cleansing, and it always implies arahantship.

==== Ninhāta and ninhāya: religious connotations

Likewise, _ninhāta_ and _ninhāya_ have only religious connotations. 
_Ninhāta_ (adj.) is _nis+nahāta_, where _nis_ means 'the finishing, 
completion or vanishing of an action' (PED sv _ni_). _Ninhāya_ is not in PED, 
but it is equivalent to _ninhāta_, and linked to _nahātaka_:

1. _Ninhāta_:

[quote, Th.v.348]
____
I have [now] cleansed away all demerit, I am free of [the three] spiritual 
stains, of purified conduct, pure.

_Ninhātasabbapāpomhi nimmalo payato suci._
____

2. _Ninhāya_:

[quote, Sn.v.521]
____
He has cleansed away all unvirtuous deeds in the whole world, both internally 
and externally. Amidst devas and men caught up in egocentric conception, he is 
not caught up in egocentric conception. They call him spiritually cleansed.

_Ninhāya sabbapāpakāni ajjhattaṃ bahiddhā ca sabbaloke +
Devamanussesu kappiyesu kappaṃ n'eti tamāhu nahātako ti._
____

=== Illustrations

.Illustration
====
nahātako

spiritually cleansed
====

____
And how is a bhikkhu spiritually cleansed?

_Kathañca bhikkhave bhikkhu nahātako hoti?_
____

[quote, M.1.280]
____
Unvirtuous, spiritually unwholesome factors that are defiling, and which lead 
to renewed states of individual existence, suffering, unpleasant karmic 
consequences, and future birth, old age, and death are cleansed away.

_Nahātāssa honti pāpakā akusalā dhammā saṅkilesikā ponobhavikā 
sadarā dukkhavipākā āyatiṃ jātijarāmaraṇīyā._
____

.Illustration
====
nahātako

spiritually cleansed
====

____
Formerly I was Brahmā's offspring, now I am a Brahman indeed,

_Brahmabandhu pure āsiṃ so idānimhi brāhmaṇo_
____

[quote, Thī.v.290]
____
A master of the three final knowledges, fully versed in profound knowledge, one 
who is blessed with profound knowledge, spiritually cleansed.

_Tevijjo sottiyo camhi vedagū camhi nahātako ti._
____

.Illustration
====
nahātako

spiritually cleansed
====

____
Through the cleansing away of seven things a bhikkhu is spiritually cleansed.

_Sattannaṃ bhikkhave dhammānaṃ nahātattā nahātako hoti_
____

____
the view of personal identity is cleansed away

_sakkāyadiṭṭhi nahātā hoti_
____

____
doubt [about the significance of the teaching] is cleansed away

_vicikicchā nahātā hoti_
____

____
adherence to observances and practices is cleansed away

_sīlabbataparāmāso nahāto hoti_
____

____
attachment is cleansed away

_rāgo nahāto hoti_
____

____
hatred is cleansed away

_doso nahāto hoti_
____

____
undiscernment of reality is cleansed away

_moho nahāto hoti_
____

[quote, A.4.145]
____
conceit is cleansed away

_māno nahāto hoti._
____

