== Nandi; Nandati

=== Renderings

- _nandati_: to rejoice

- _nandi_: spiritually fettering delight

- _dhammanandi_: righteous spiritually fettering delight

=== Introduction

==== Renderings for nandi

_Nandi_ has been called:

- PED: 'joy, enjoyment, pleasure, delight in.'

- Norman: enjoyment (Sn.v.1115; 1055), joy (Sn.v.1101; 637), pleasure 
(Sn.v.175).

- Bodhi: delight (M.3.32, S.2.101, A.2.11).

==== Nandi is spiritually fettering

We say _nandi_ is 'spiritually fettering' for four reasons:

1. Through its association with _saṃyojana_ ('bond [to individual 
existence]'):
+
[quote, S.4.36]
____
Tethered [to individual existence] by the bond of spiritually fettering 
delight, Migajāla, a bhikkhu is called 'one living with a partner.'

_nandisaṃyojanasaṃyutto kho migajāla bhikkhu sadutiyavihārī ti vuccati. 
Taṇhā hissa dutiyā sāssa appahīnā tasmā sadutiya vihārīti vuccati._
____

2. Through its association with _upadānaṃ_ ('grasping'):
+
[quote, M.1.266]
____
Spiritually fettering delight in sense impression is grasping.

_Yā vedanāsu nandī tadupadānaṃ._
____

3. Through its association with _saṃyojano_ ('bond'):
+
[quote, Sn.v.1109]
____
Spiritually fettering delight is the bond of the world [by which it is tethered 
to individual existence].

_Nandi saṃyojano loko._
____

4. Through its association with _rāgo_ ('attachment'):
+
[quote, S.4.36]
____
When there is spiritually fettering delight, there is attachment.

_nandiyā sati sārāgo hoti._
____

==== The objects of nandi

Spiritually fettering delight is usually associated with attractive objects, 
but sometimes with hostile attitudes, as follows:

[quote, A.2.10]
____
spiritually fettering delight in sensuous pleasure

_kāmanandi._

spiritually fettering delight in views

_diṭṭhinandi._

spiritually fettering delight in individual existence _

_bhavanandi._
____

[quote, A.3.245]
____
spiritually fettering delight in ill will

_vyāpādanandī._

spiritually fettering delight in maliciousness

_vihesānandī._
____

[quote, A.3.246]
____
spiritually fettering delight in the refined material states of awareness

_rūpanandī._
____

[quote, A.3.246]
____
spiritually fettering delight in personal identity

_sakkāyanandī._
____

==== Dhammanandi: in those who practise the teaching

Spiritually fettering delight has a righteous form, _dhammanandi_ (righteous 
spiritually fettering delight) that occurs in those who practise the teaching, 
and, according to this quote, would be equivalent to clinging:

[quote, M.1.135]
____
Thus the teaching explained by me is comparable to a raft, being for the sake 
of crossing [the flood of suffering], not for the sake of clinging to it. When 
you know that the teaching explained by me is comparable to a raft, you should 
abandon even what is righteous, how much more so what is unrighteous.

_evameva kho bhikkhave kullūpamo mayā dhammo desito nittharaṇatthāya no 
gahaṇatthāya. Kullūpamaṃ vo bhikkhave dhammaṃ desitaṃ ājānantehi 
dhammā pi vo pahātabbā pageva adhammā._
____

For example, see Illustrations below.

==== Nandati: not always unwholesome

The verb _nandati_ is not always unwholesome_._ For example, though an 
unvirtuous bhikkhu rejoices (_nandati_) in schism, a sympathetic friend 
rejoices (_nandati_) in your good fortune.

=== Illustrations

.Illustration
====
nandati

rejoice
====

[quote, Dh.v.18]
____
In this world he rejoices, having passed on he rejoices; the doer of 
meritorious deeds rejoices in both places. He rejoices in the thought of having 
done meritorious deeds. He further rejoices having gone to heaven.

_Idha nandati pecca nandati katapuñño ubhayattha nandati; +
Puññaṃ me katan ti nandati bhiyyo nandati sugatiṃ gato._
____

.Illustration
====
nandati

rejoice
====

• An enemy does not rejoice in an enemy's +
_na bhikkhave sapatto sapattassa_

- good looks ☸ _vaṇṇavatāya nandati_

- happy sleep ☸ _sukhaseyyāya nandati_

- prosperity ☸ _pacuratthatāya nandatī_

- wealth ☸ _bhogavatāya nandati_

- prestige ☸ _yasavatāya nandati_

- popularity ☸ _mittavatāya nandati_

- going to heaven ☸ _sugatigamanena nandati_ (A.4.94).

.Illustration
====
nandati

rejoice
====

The sympathetic friend is seen as loyal in four ways

____
he does not rejoice in your misfortune

_abhavenassa na nandati_
____

[quote, D.3.187]
____
he rejoices in your good fortune

_bhavenassa nandati._
____

.Illustration
====
nandati

rejoice
====

[quote, A.2.240]
____
An unvirtuous bhikkhu rejoices in schism in the community of bhikkhus

_pāpabhikkhu saṅghabhedena nandati._
____

.Illustration
====
nandasi

rejoice; nandi, spiritually fettering delight
====

____
-- Do you rejoice, ascetic?

_Nandasi samaṇā ti?_
____

____
-- Having gained what, friend?

_Kiṃ laddhā āvuso ti?_
____

____
-- Well, do you grieve, then?

_Tena hi samaṇa socasī ti?_
____

____
-- What is lost, friend?

_Kiṃ jīyittha āvuso ti?_
____

____
-- Then do you neither rejoice nor grieve, ascetic?

_Tena hi samaṇa neva nandasi neva socasī ti?_
____

____
-- That's it, friend.

_Evamāvuso ti._
____

____
-- I hope you're rid of spiritual defilement, bhikkhu; I hope no spiritually 
fettering delight is found in you; I hope when you sit alone that 
disgruntlement [with the celibate life] does not overwhelm you.

_Kacci tvaṃ anigho bhikkhu kacci nandi na vijjati +
Kacci taṃ ekamāsīnaṃ arati nābhikīratīti._
____

[quote, S.1.54]
____
-- Indeed, I am rid of spiritual defilement, deity; and no spiritually 
fettering delight is found in me. And when I am sitting alone, disgruntlement 
&#8203;[with the celibate life] does not overwhelm me.

_Anigho ve ahaṃ yakkha atho nandi na vijjati +
Atho maṃ ekamāsīnaṃ arati nābhikīratīti._
____

Comment:

If _nandi_ is taken as unqualified 'delight,' as it usually is in translation, 
this would be hard to explain because the Buddha has said he takes delight in 
the woods (_svāhaṃ vane nibbanatho visallo eko rame aratiṃ vippahāyā 
ti_, S.1.180) and said that the wise man should be delighted in the woods 
(_dhīro vanante ramito siyā_, Sn.v.709-710). Venerable Revata said the 
bhikkhu who would illuminate the Gosinga Grove would be one who takes pleasure 
and delight in solitary retreat (_paṭisallāṇārāmo hoti 
paṭisallāṇarato_ M.1.213). Taking delight in solitude (_suññāgāre 
abhirati_) is regarded as a supernormal attainment.

.Illustration
====
dhammanandiyā

righteous spiritually fettering delight
====

____
Ānanda, what is the path and practice to abandon the five ties to individual 
existence in the low plane of existence?

_Katamo cānanda maggo katamā paṭipadā pañcannaṃ orambhāgiyānaṃ 
saṃyojanānaṃ pahānāya?_
____

A bhikkhu enters first jhāna; whatever of the khandhas there, he sees as 
_aniccato dukkhato rogato gaṇḍato sallato aghato ābādhato parato palokato 
suññato anattato._

• He averts his mind from those states. +
_So tehi dhammehi cittaṃ paṭivāpeti_

• and focuses his mind on the immortal phenomenon +
_so tehi dhammehi cittaṃ paṭivāpetvā amatāya dhātuyā cittaṃ 
upasaṃharati_

• "This is peaceful, this is sublime, namely the quelling of all originated 
phenomena, the relinquishment of the whole phenomenon of attachment, the 
destruction of craving, the passing away [of originated phenomena], the ending 
&#8203;[of originated phenomena], the Untroubled. +
_etaṃ santaṃ etaṃ paṇītaṃ yadidaṃ sabbasaṅkhārasamatho 
sabbūpadhipaṭinissaggo taṇhākkhayo virāgo nirodho nibbānan ti._

• Established therein, he attains the destruction of perceptually obscuring 
states. +
_So tattha ṭhito āsavānaṃ khayaṃ pāpuṇāti;_

If he does not attain the destruction of perceptually obscuring states, then 
because of

____
that righteous attachment,

_teneva dhammarāgena_
____

____
that righteous spiritually fettering delight

_tāya dhammanandiyā_
____

with the destruction of the five ties to individual existence in the low plane 
of existence, he arises spontaneously [in the higher planes of existence], 
there to attain nibbāna-without-residue, never to return from those worlds 
(_anāvattidhammo tasmā lokā_) (M.1.435-7, A.4.421).

.Illustration
====
nandī

spiritually fettering delight
====

[quote, S.2.53]
____
Friends, there are these three types of sense impression. What three? Pleasant 
sense impression, unpleasant sense impression, and neutral sense impression. 
These three types of sense impression, friends, are unlasting; whatever is 
unlasting is existentially void. When this was understood, spiritually 
fettering delight in sense impression no longer remained present in me.'

_tisso kho imā āvuso vedanā katamā tisso? Sukhā vedanā dukkhā vedanā 
adukkhamasukhā vedanā imā kho āvuso tisso vedanā aniccā. Yadaniccaṃ 
taṃ dukkhan ti viditaṃ. Yā vedanāsu nandī sā na upaṭṭhāsī ti. 
Evaṃ puṭṭhohaṃ bhante evaṃ vyākareyyanti._
____

.Illustration
====
nandi

spiritually fettering delight
====

[quote, Sn.v.1055]
____
Whatever you know, above, below, across, and also in the middle, having thrust 
away spiritually fettering delight and attachment regarding these things, your 
stream of sense consciousness would not remain in existence.

_Yaṃ kiñci sampajānāsi uddhaṃ adho tiriyañcāpi majjhe etesu nandiñca 
nivesanañca panujja viññāṇaṃ bhave na tiṭṭhe._
____

.Illustration
====
nandi

spiritually fettering delight
====

____
He takes delight in bodily form, welcomes it, and persists in cleaving to it.

_rūpaṃ abhinandati abhivadati ajjhosāya tiṭṭhati_
____

____
In so doing, spiritually fettering delight arises.

_tassa rūpaṃ abhinandato abhivadato ajjhosāya tiṭṭhato uppajjati nandi_
____

[quote, S.3.14]
____
Spiritually fettering delight in bodily form is grasping.

_Yā rūpe nandi tadupādānaṃ._
____

.Illustration
====
nandi

spiritually fettering delight
====

1. And how does one revive the past? One thinks: 'Such was my bodily form in 
the past, and thereby nurtures spiritually fettering delight.
+
****
_Kathañca bhikkhave atītaṃ anvāgameti. Evaṃrūpo ahosiṃ 
atītamaddhānanti tattha nandiṃ samanvāneti_ (M.3.188).
****

2. How does one long for the future? One thinks: 'May my bodily form be thus in 
the future, and thereby nurtures spiritually fettering delight._ +
Katañcānanda anāgataṃ paṭikaṅkhati. Evaṃrūpo siyaṃ 
anāgatamaddhānanti tattha nandiṃ samanvāneti_ (M.3.188).

.Illustration
====
nandi

spiritually fettering delight
====

____
What is the noble truth of the origin of suffering?

_dukkhasamudayo ariyasaccaṃ_
____

[quote, M.3.251]
____
It is this craving that leads to renewed states of individual existence, 
accompanied by spiritually fettering delight and attachment, taking delight in 
this and that, namely craving for sensuous pleasure, craving for states of 
individual existence, and craving for the cessation of states of individual 
existence.

_yāyaṃ taṇhā ponobhavikā nandirāgasahagatā tatra tatrābhinandinī 
seyyathīdaṃ kāmataṇhā bhavataṇhā vibhavataṇhā. Idaṃ vuccatāvuso 
dukkhasamudayo ariyasaccaṃ._
____

