== Nibbāna; Nibbuta; Nibbuti

=== Renderings

==== Nibbāna & Parinibbāna

- _nibbāna_: highest pleasure

- _nibbāna_: quenching

- _nibbāna_: the Untroubled

- _nibbānapada_: Untroubled State

- _parinibbāna_: passing away to the Untroubled-without-residue

==== Nibbāyati & Parinibbāyati

- _nibbāyati_: to go out

- _parinibbāyati_: to become untroubled

- _parinibbāyati_: to realise the Untroubled

- _parinibbāyati_: to pass away to the Untroubled-without-residue

==== Nibbuto & Parinibbuto

- _nibbuto_: quenched, extinguished

- _nibbuto_: inwardly at peace

- _nibbuto_: realised the Untroubled (standing, in verse, for _parinibbuto_)

- _parinibbuto_: realised the Untroubled

- _parinibbuto_: passed away to the Untroubled-without-residue

==== Miscellaneous

- _nibbuti_: inward peace

- _parinibbānagato_: realised the Untroubled

- _anupādisesāya nibbānadhātuyā parinibbuto_: passed away to the 
Untroubled-without-residue

=== Introduction

==== Nibbāna: not beyond words

To ask whether _nibbāna_ is either something or nothing is a question outside 
the range of conception (_appapañcaṃ papañceti_) (A.2.161). But although 
_nibbāna_ is beyond conception, it is clearly not beyond words, as is proven 
by its many epithets.

==== Nibbāna: the via negativa

_Nibbāna_ can be named in positive terms, 'what it is,' the _via positiva_; or 
in negative terms, 'what it is not,' the _via negativa_. For example, consider 
the list of thirty-three epithets at S.4.368-373. The positives are, for 
example, the Peaceful (_santañca_), the Sublime (_paṇītañca_), the 
Auspicious (_sivañca_). The negatives are, for example, the Unoriginated 
(_asaṅkhatañca_), the Uninclined (_anatañca_), freedom from perceptual 
obscuration (_anāsavañca_).

But if _nibbāna_ is beyond conception, and therefore unapproachable by the 
_via positiva_, we would not have expected this list to include positives, 
except on one condition: that the positives are concealed negatives. That is, 
we call _nibbāna_ 'peaceful' but mean 'free of unpeacefulness'; 'sublime' but 
mean 'free of unsublimeness'; 'auspicious' but mean 'free of inauspiciousness.' 
And so on.

==== Nibbuto: etymology

_Nibbuto_ is two words represented in Sanskrit by _nivṛta_, quenched, and 
_nirvṛta_, motionless, both past participles of _vṛ_ (PED). Thus _nibbuto_ 
is the extinguishing of fire and also the spiritual quality of an arahant:

[quote, M.1.487]
____
the fire is extinguished

_aggi nibbuto._
____

[quote, M.2.237]
____
I am inwardly at peace

_nibbuto'ham._
____

==== Nibbuto means peace not quenching

The two meanings, 'extinguished' and 'inwardly at peace', are 'used 
promiscuously in the one word because of their semantic affinity,' says PED. 
Thus, referring to the arahant, _nibbuto_ is sometimes wrongly called 
'quenched' but the scriptures do not support this. They do not say, for 
instance, that in arahantship _rāgadosamoha_ or the _āsavas_ are quenched. 
The Buddha said one should know _nibbuto_ as peace (_santī ti nibbutiṃ 
ñatvā_ Sn.v.933) and other suttas support this, linking _nibbuto_ to peaceful 
qualities, for example:

[quote, M.1.341]
____
inwardly at peace, freed from inward distress

_nibbuto sītibhūto._
____

[quote, M.1.323]
____
I obtain inward calm and inward peace

_labhāmi paccattaṃ samathaṃ labhāmi paccattaṃ nibbutin ti._
____

[quote, Sn.v.933]
____
Knowing inward peace as Peace

_santī ti nibbutiṃ ñatvā._
____

Likewise, _nibbuto_ is contrasted with unpeaceful qualities, for example:

[quote, M.2.196, Dh.v.406]
____
inwardly at peace amidst the violent

_attadaṇḍesu nibbutaṃ._
____

[quote, Th.v.1060]
____
Inwardly at peace amidst those who are tormented [by spiritual defilement]_

_ḍayhamānesu nibbuto._
____

Therefore in the context of arahantship _nibbuto_ means peace. Our term for 
this is 'inwardly at peace' (adjective) or 'inward peace' (_nibbuti,_ noun).

==== Nibbāna and quenching

_Nibbāna_ shares the _vṛ_ root, and therefore like _nibbuto_, has two 
meanings: quenching and the Untroubled.

[quote, S.1.159]
____
the quenching of a lamp

_pajjotasseva nibbānaṃ._
____

[quote, S.2.18]
____
one who has realised the Untroubled.

_nibbānappatto._
____

The confusion between meanings is made more probable when the scriptures 
compare the attainment of arahantship (_vimokkho_) to the quenching 
(_nibbāna_) of a flame. For example, the bhikkhunī Paṭācārā said:

[quote, Thī.v.116]
____
The deliverance of my mind was like the quenching of the lamp.

_padīpasseva nibbānaṃ vimokkho ahu cetaso._
____

But arahantship does not involve anything being quenched. The _nibbāna_ of 
arahantship is repeatedly linked elsewhere to 'destruction.' For example:

[quote, Ud.32-3]
____
With the destruction of all forms of craving comes the complete passing away 
and ending [of originated phenomena], _nibbāna_

_sabbaso taṇhānaṃ khayā asesavirāganirodho nibbānaṃ._
____

[quote, S.4.251]
____
The destruction of attachment, hatred, and undiscernment of reality: this is 
called _nibbāna_.

_rāgakkhayo dosakkhayo mohakkhayo idaṃ vuccati nibbānan ti._
____

==== Nibbāna, peace and the Untroubled

Our rendering of _nibbāna_ as 'the Untroubled' stems firstly from its 
relationship to our rendering for _nibbuto_ ('inwardly at peace'), and secondly 
from the _Attadīpa Sutta_ (S.3.43) and the _Bhaddāli Sutta_ (M.1.446). Bodhi 
translates the _Bhaddāli Sutta_ like this:

- 'Suppose a horse trainer obtains a fine thoroughbred colt. He first makes him 
used to wearing the bit. While the colt is being made to get used to wearing 
the bit, because he is doing something that he has never done before, he 
displays some writhing, scuffling and trembling, but through constant 
repetition and gradual practice, he becomes peaceful in that action (_so 
abhiṇhakāraṇā anupubbakāraṇā tasmiṃ ṭhāne parinibbāyati_)' 
(Bodhi, S.3.43).

Bodhi says 'the verb used here is the verbal form of _parinibbāna_ and could 
be literally, though erroneously, translated, "He attains final _Nibbāna_ in 
that action" (MLDB n.668). Although 'peaceful' indeed suits the context, the 
via negativist would say 'untroubled.'

In the _Attadīpa Sutta_ (S.3.43) a bhikkhu accepts the changeable nature of 
the five aggregates, and so is not agitated when they change. Therefore he 
abides happily. The text says _sukhaṃ viharaṃ bhikkhu tadaṅganibbuto ti 
vuccati_: __'__a bhikkhu who abides happily is said to be untroubled in that 
respect,' meaning with respect to the change of the aggregates. Bodhi, however, 
says (CDB p.883) 'a bhikkhu who abides happily is said to be quenched in that 
respect.' In the note to this (CDB p.1055 n.56) he says the phrase might have 
been rendered '"one who has attained _Nibbāna_ in that respect" i.e. only in 
regards to a particular freedom.' But if he had used 'peaceful,' as he did at 
M.1.446, his translation would have read more naturally: 'a bhikkhu who abides 
happily is said to be peaceful in that respect,' and this would have once again 
supported our 'untroubled.'

==== Two aspects of nibbāna

The scriptures distinguish two aspects of _nibbāna_:

(1) the Untroubled-with-residue
+
****
_saupādisesā nibbānadhātu_
****

(2) the Untroubled-without-residue
+
****
_anupādisesā nibbānadhātu_
****

1. The Untroubled-with-residue involves the destruction of _rāgadosamoha_ by 
the living arahant (_tassa yo rāgakkhayo dosakkhayo mohakkhayo ayam vuccati 
saupādisesā nibbānadhātu_). Being 'with residue' means the arahant has 
unperished sense faculties and therefore continues to experience what is 
pleasing and displeasing, both pleasure and pain (_pañcindriyāni yesaṃ 
avighātattā manāpāmanāpaṃ paccanubhoti sukhadukkhaṃ 
paṭisaṃvedeti_) (It.38).

2. The Untroubled-without-residue refers to the passing away of the arahant, 
for whom sense impression ceases (_tassa idheva bhikkhave sabbavedayitāni 
anabhinanditāni sītibhavissanti_), who utterly abandons all modes of being 
(_pahaṃsu te sabbabhavāni tādino_, It.38-9).
+
The Untroubled-without-residue is sometimes called 'final _nibbāna_,' but the 
idea that the _nibbāna_ at death is somehow more 'final' than the 
Untroubled-with-residue has no support in the scriptures.

==== Nibbāna and parinibbāna

_Parinibbāna_ is sometimes considered to be the _nibbāna_ attained by the 
arahant at death, but the scriptures do not support this. For example, consider 
these passages:

1. I make known the realisation of the Untroubled (_parinibbānaṃ_) through 
having no grasping in this very lifetime.
+
****
_diṭṭheva dhamme... anupādā paññāpemī ti_ (A.5.65).
****

2. He who has realised the Untroubled (_parinibbānagato_) via a path made by 
himself... he is a bhikkhu.
+
****
_Pajjena katena attanā parinibbānagato... sa bhikkhu_ (Sn.v.514).
****

The effect of the _pari_- prefix is explained like this:

- 'The prefix _pari_- converts the noun from the expression of a state into the 
expression of the achievement of that state. Thus _nibbāna_ means the state of 
release, _parinibbāna_ the attaining of that state' (Bodhi, CDB p.49).

This rule does not apply to verbs and past participles because the verbs are 
never expressions of a state, whereas the past participles are always 
expressions of a state. Our renderings are as follows:

1. Verbs:

- _nibbāyati_: to go out

- _parinibbāyati_: to become untroubled

- _parinibbāyati_: to realise the Untroubled

- _parinibbāyati_: to pass away to the Untroubled-without-residue

2. Past participles:

- _nibbuto_: quenched, extinguished

- _nibbuto_: inwardly at peace

- _nibbuto_: realised the Untroubled (standing, in verse, for _parinibbuto_)

- _parinibbuto_: realised the Untroubled

- _parinibbuto_: passed away to the Untroubled-without-residue

==== Parinibbuto: two meanings

_Parinibbuto_ means either:

1. realised the Untroubled, or

2. passed away to the Untroubled-without-residue

Consider the following quotes:

[quote, Th.v.1218]
____
He has realised the Untroubled. He awaits the inevitable hour [fully 
consciously and mindfully].

_parinibbuto kaṅkhati kālaṃ._
____

[quote, S.3.26]
____
One is free of craving. One has realised the Untroubled.

_nicchāto parinibbuto._
____

[quote, D.2.141]
____
Here the Perfect One passed away to the Untroubled-without-residue

_idha tathāgato anupādisesāya nibbānadhātuyā parinibbuto ti pi._
____

==== Nibbuto: in verse

In verse, _parinibbuto_ is often abbreviated to _nibbuto_.

[quote, Sn.v.638]
____
One who has realised the Untroubled through being without grasping, he is what 
I call a Brahman.

_anupādāya nibbuto tamahaṃ brūmi brāhmaṇaṃ._
____

But this point could be argued. For example, the passage would also make sense 
if rendered 'One who is inwardly at peace through being without grasping.' But 
the mention of Brahman (i.e. arahant) makes our rendering more likely.

Sometimes the context suggests that _nibbuto_ does not mean _parinibbuto_:

[quote, M.2.196; Dh.v.406]
____
Inwardly at peace amidst the violent

_attadaṇḍesu nibbutaṃ._
____

It makes less sense to render this: 'realised the Untroubled amidst the 
violent.'

==== Nibbuti

_Nibbuti_ may or may not imply arahantship. For example:

[quote, _labhāmi paccattaṃ samathaṃ labhāmi paccattaṃ nibbutin ti_ 
(M.1.323]
____
A bhikkhu knows that "When I pursue, develop, and cultivate this view, I obtain 
inward calm and inward peace

_imaṃ kho ahaṃ diṭṭhiṃ āsevanto bhāvento bahulīkaronto._
____

• All his perceptually obscuring states are destroyed and he attains inward 
peace +
☸ _Khīyanti āsavā sabbe nibbutiñcādhigacchatī ti_. (Th.v.586).

==== Non-Buddhist ascetics: highest happiness

For non-Buddhist ascetics, _nibbāna_ meant 'highest pleasure':

[quote, D.1.36]
____
When the _attā_ is enjoying itself, provided with and possessed of the five 
varieties of sensuous pleasure, at that point it has attained to the highest 
pleasure in this lifetime

_attā pañcahi kāmaguṇehi samappito samaṅgībhūto paricāreti ettāvatā 
kho bho ayaṃ attā paramadiṭṭhadhammanibbānaṃ patto hotī ti._
____

==== Parinibbanti: to pass away to the Untroubled-without-residue

PED and Norman accept the spelling _parinibbanti_ without comment. The word 
also occurs at A.4.98; Dh.v.126; It.93; Sn.v.765. The commentary to S.4.128 
glosses _parinibbanti_ as _parinibbāyanti_.

[quote, S.4.128]
____
Those free of perceptually obscuring states pass away to the 
Untroubled-without-residue.

_parinibbanti anāsavā._
____

=== Illustrations: nibbāna; parinibbāna

.Illustration
====
nibbānaṃ

quenching
====

[quote, S.1.159]
____
The deliverance of his mind [from individual existence] was like the quenching 
of a lamp

_pajjotasseva nibbānaṃ vimokkho cetaso ahūti._
____

.Illustration
====
parinibbānāya

extinguish
====

____
A person given to maliciousness has compassion to extinguish it.

_vihiṃsakassa purisapuggalassa avihiṃsā hoti parinibbānāya._
____

____
A person given to killing has refraining from killing to extinguish it.

_pāṇātipātissa purisapuggalassa pāṇātipātā veramaṇī hoti 
parinibbānāya._
____

[quote, M.1.45]
____
A person given to stealing has refraining from stealing to extinguish it.

_adinnādāyissa purisapuggalassa adinnādānā veramaṇī hoti 
parinibbānāya._
____

.Illustration
====
nibbāna

the Untroubled
====

[quote, S.5.8]
____
This, bhikkhu, is a designation for the Untroubled: the elimination of 
attachment, hatred, and undiscernment of reality.

_Nibbānadhātuyā kho etaṃ bhikkhu adhivacanaṃ rāgavinayo dosavinayo 
mohavinayo ti._
____

.Illustration
====
nibbāna

the Untroubled
====

[quote, S.3.190]
____
The destruction of craving, Rādha, is the Untroubled.

_taṇhakkhayo hi rādha nibbānan ti._
____

.Illustration
====
nibbāna

the Untroubled
====

[quote, S.2.18]
____
One is fit to be called a bhikkhu who has realised the Untroubled in this 
lifetime.

_diṭṭhadhammanibbānappatto bhikkhū ti alaṃ vacanāya._
____

.Illustration
====
nibbāna

Untroubled
====

[quote, Sn.v.1086]
____
'In this regard, Hemaka, in regards to pleasant things which are seen, heard, 
sensed, or cognised, the dispelling of fondness and attachment is the 
Untroubled, the Unshakeable State.

_Idha diṭṭhasutamutaviññātesu piyarūpesu hemaka +
Chandarāgavinodanaṃ nibbānapadamaccutaṃ._
____

.Illustration
====
nibbānapada

Untroubled State
====

[quote, Sn.v.365]
____
Longing for the Untroubled State.

_Nibbānapadābhipatthayāno._
____

.Illustration
====
parinibbānaṃ

passing away to the Untroubled-without-residue
====

[quote, D.2.149]
____
Tonight in the last watch will be the ascetic Gotama's passing away to the 
Untroubled-without-residue.

_ajjeva rattiyā pacchime yāme samaṇassa gotamassa parinibbānaṃ 
bhavissati._
____

.Illustration
====
parinibbātu

pass away to the Untroubled-without-residue; parinibbāna, passing away to the 
Untroubled-without-residue
====

[quote, S.5.262]
____
Bhante, let the Blessed One now pass away to the Untroubled-without-residue! 
Let the Sublime One now pass away to the Untroubled-without-residue! Now is the 
time for the Blessed One's passing away to the Untroubled-without-residue!

_Parinibbātu'dāni bhante bhagavā parinibbātu sugato parinibbānakālo'dāni 
bhante bhagavato ti._
____

.Illustration
====
parinibbutesu

passed away to the Untroubled-without-residue
====

[quote, S.5.164]
____
The assembly [of bhikkhus] appears to me empty now that Sāriputta and 
Moggallāna have passed away to the Untroubled-without-residue.

_parisā suññā viya khāyati parinibbutesu sāriputtamoggallānesu._
____

.Illustration
====
parinibbāyī

one who realises the Untroubled
====

[quote, A.2.155]
____
He is one who realises the Untroubled with effort in this very lifetime

_diṭṭheva dhamme sasaṅkhāraparinibbāyī hoti._
____

=== Illustrations: nibbuta

.Illustration
====
nibbuto

extinguished
====

[quote, Sn.v.456]
____
Ego completely extinguished.

_abhinibbutatto._
____

.Illustration
====
nibbutaṃ

quenched
====

An iron ball that had been heated all day:

[quote, D.2.335]
____
After a time it was cool and quenched.

_aparena samayena sītaṃ nibbutaṃ._
____

.Illustration
====
nibbuto

extinguished
====

When a fire has used up its fuel:

[quote, M.1.486-7]
____
Being without fuel material it is reckoned as extinguished.

_anāhāro nibbuto'teva saṅkhaṃ gacchatī ti._
____

.Illustration
====
nibbuto

go out
====

[quote, D.2.340]
____
I hope, dear, that the fire did not go out.

_kacci te tāta aggi na nibbuto ti._
____

.Illustration
====
nibbuto

extinguished
====

[quote, Sn.v.19]
____
My fire is extinguished.

_nibbuto'gini._
____

Comment:

'Fire' here perhaps means the three fires: the fire of attachment, hatred, 
undiscernment of reality (_rāgaggī dosaggi mohaggi_) (D.3.217).

.Illustration
====
nibbuto

inwardly at peace
====

[quote, Th.v.1060]
____
Inwardly at peace amidst those who are tormented [by spiritual defilement].

_ḍayhamānesu nibbuto._
____

.Illustration
====
nibbuto

inwardly at peace
====

[quote, Sn.v.1041]
____
'The bhikkhu who in the face of sensuous pleasures lives the religious life 
with reflectiveness, free of craving, ever mindfully, and inwardly at peace, 
for him there are no states of spiritual instability.

_Kāmesu brahmacariyavā vītataṇho sadā sato +
Saṅkhāya nibbuto bhikkhu tassa no santi iñjitā._
____

.Illustration
====
nibbuto

realised the Untroubled
====

[quote, D.2.136]
____
Through the destruction of attachment, hatred, and undiscernment of reality he 
has realised the Untroubled.

_rāgadosamohakkhayā sa nibbuto ti._
____

Comment:

In verse, _parinibbuto_ is often abbreviated to _nibbuto._

.Illustration
====
nibbutā

realised the Untroubled
====

[quote, S.1.24]
____
Through knowledge [of things according to reality] the wise have realised the 
Untroubled.

_Aññāya nibbutā dhīrā._
____

Comment:

In verse, _parinibbuto_ is often abbreviated to _nibbuto._

.Illustration
====
nibbutā

realised the Untroubled
====

[quote, Thī.v.16]
____
You are freed from inward distress. You have realised the Untroubled.

_sītibhūtāsi nibbutā ti._
____

Comment:

In verse, _parinibbuto_ is often abbreviated to _nibbuto._

.Illustration
====
anupādisesāya nibbānadhātuyā parinibbuto

passed away to the Untroubled-without-residue
====

[quote, D.2.140]
____
Here the Perfect One passed away to the Untroubled-without-residue

_idha tathāgato anupādisesāya nibbānadhātuyā parinibbuto ti pi._
____

Comment:

_Anupādisesāya nibbānadhātuyā parinibbuto_: 'passed away to the Untroubled 
in relation to the Untroubled-without-residue.'

=== Illustrations: nibbuti

.Illustration
====
nibbutiṃ

inward peace
====

[quote, Sn.v.933]
____
Knowing inward peace as Peace, he should not be negligent in [practising] 
Gotama's training system.

_Santī ti nibbutiṃ ñatvā sāsane gotamassa napamajjeyya._
____

.Illustration
====
nibbutiṃ

inward peace
====

[quote, Th.v.32]
____
I will exchange ageing for agelessness, the torment [of spiritual defilement] 
for inward peace, for supreme inward peace, for unsurpassed safety from the 
danger of bondage [to individual existence].

_Ajaraṃ jiramānena tappamānena nibbutiṃ +
Nimissaṃ paramaṃ santiṃ yogakkhemaṃ anuttaran ti._
____

