== Nibbidā; Nibbindati

=== Renderings

- _nibbidā_: disillusionment

- _nibbidā_: disillusionment [with sensuous pleasure]

- _nibbidā_: disillusionment [with originated phenomena]

- _nibbindati_: to be disillusioned

- _nibbindati_: to be disillusioned [with originated phenomena]

=== Introduction

==== With specified objects

_Nibbidā_ and _nibbindati_ often have specified objects. For example:

[quote, S.3.21]
____
disillusioned with bodily form

_rūpasmimpi nibbindati._
____

[quote, S.2.18]
____
disillusionment with old age and death

_jarāmaraṇassa ce bhikkhu nibbidāya._
____

==== With a broad specified object

Sometimes they have a broad specified object e.g. 'originated phenomena':

[quote, S.2.191]
____
disillusioned with all originated phenomena

_sabbasaṅkhāresu nibbindituṃ._
____

==== With a broad unspecified object due to abbreviation

Sometimes the object is unspecified due to abbreviation. For example, a bhikkhu 
who realises the nature of the five aggregates becomes disillusioned with each 
of them (_rūpasmimpi nibbindati... viññāṇasmimpi nibbindati_ S.3.21). The 
sutta continues:

____
Being disillusioned, he is unattached.

_nibbindaṃ virajjati_
____

This _nibbindaṃ_ means 'being disillusioned with all five aggregates', which 
are unspecified due to abbreviation.

==== With a broad object implied by context

Sometimes a broad object is indicated by the context. For example, in twenty 
five years since his going forth [into the ascetic life], Venerable Sappadāsa 
attained not a moment's inward peace, being oppressed by attachment to sensuous 
pleasure (_kāmarāgena addito_). So he picked up a razor in order to cut a 
vein:

[quote, Th.v.409]
____
Then proper contemplation arose in me. The danger [of sensuous pleasure] became 
apparent [to me]; and disillusionment [with originated phenomena] was firmly 
established [in me]

_Tato me manasikāro yoniso udapajjatha +
Ādīnavo pāturahu nibbidā samatiṭṭhatha._
____

[quote, Th.v.410]
____
... Whereupon my mind was liberated [from perceptually obscuring states].

_tato cittaṃ vimucci._
____

Because it led to arahantship, we take the object of _nibbidā_ to be 
originated phenomena (_sabbasaṅkhārā_), not just sensuous pleasure.

==== Rendering a broad object: 'originated phenomena' or 'things'?

In the scriptures, the five aggregates are collectively called either 
'originated phenomena' (_saṅkhārā_), or 'things' (_dhammā_), for example 
in this quote:

____
Bodily form... advertence is unlasting

_Rūpaṃ bhikkhave aniccaṃ... viññāṇaṃ aniccaṃ_
____

____
... Bodily form... advertence is void of personal qualities

_Rūpaṃ bhikkhave anattā... viññāṇaṃ anattā_
____

____
... All originated phenomena (_saṅkhārā_) are unlasting;

_sabbe saṅkhārā aniccā_
____

[quote, M.1.228]
____
... All things (_dhammā_) are void of personal qualities

_sabbe dhammā anattā ti._
____

Therefore consider again the phrase we used above:

____
Being disillusioned, he is unattached.

_nibbindaṃ virajjati_
____

This could be rendered as either:

1. Being disillusioned [with all things], he is unattached [to all things].

2. Being disillusioned [with originated phenomena], he is unattached [to 
originated phenomena].

For stylistic reasons we choose the latter, for example in this passage:

____
For one who knows and sees things according to reality, there is no need to 
harbour the aspiration: 'May I be disillusioned [with originated phenomena] and 
unattached [to originated phenomena]':

_Yathābhūtaṃ bhikkhave jānato passato na cetanāya karaṇīyaṃ 
nibbindāmi virajjāmī ti._
____

[quote, A.5.3]
____
... It is quite natural that one who knows and sees things according to 
reality, is disillusioned [with originated phenomena] and unattached [to 
originated phenomena].'

_Dhammatā esā bhikkhave yaṃ yathābhūtaṃ jānaṃ passaṃ nibbindati 
virajjati._
____

=== Illustrations

.Illustration
====
nibbida

disillusionment
====

[quote, A.1.51]
____
He who abides contemplating things conducive to psychological bondage with 
disillusionment abandons attachment, hatred, and undiscernment of reality.

_Saṃyojaniyesu bhikkhave dhammesu nibbidānupassī viharanto rāgaṃ 
pajahati dosaṃ pajahati mohaṃ pajahati._
____

.Illustration
====
nibbidāya

disillusionment
====

The noble disciple is

• indifferent to the visual sense of the past, +
_atītasmiṃ cakkhusmiṃ anapekkho hoti_

• he does not long for the visual sense of the future, +
_anāgataṃ cakkhuṃ nābhinandati_

• he applies himself to disillusionment with the visual sense of the present, 
to non-attachment to it, and to the ending of it +
_paccappannassa cakkhussa nibbidāya virāgāya nirodhāya paṭipanno hoti_ 
(S.4.4).

.Illustration
====
nibbida

disillusionment
====

[quote, A.3.443]
____
An attitude of disillusionment with all originated phenomena will be as present 
to me as it might in relation to a murderer with a drawn sword

_sabbasaṅkhāresu ca me nibbidasaññā paccupaṭṭhitā bhavissati 
seyyathā pi ukkhittāsike vadhake._
____

.Illustration
====
nibbindati

disillusioned
====

____
Bhikkhus, contemplate the visual sense properly. Recognise the unlastingness of 
the visual sense according to reality.

_Cakkhuṃ bhikkhave yoniso manasikarotha cakkhu aniccatañca yathābhūtaṃ 
samanupassatha_
____

[quote, S.4.142]
____
When a bhikkhu, reflecting properly upon the visual sense, recognises the 
unlastingness of the visual sense according to reality, he is disillusioned 
with the visual sense.

_cakkhusmimpi nibbindati._
____

.Illustration
====
nibbindathā

disillusioned
====

____
A 'carbuncle' is a metaphor for this [wretched human] body made of the four 
great material phenomena.

__'Gaṇḍo ti kho bhikkhave imasseva cātummahābhūtikassa kāyassa 
adhivacanaṃ_
____

____
It has nine openings, nine orifices.

_tassa nava vanamukhāni nava abhedanamukhāni_
____

____
Whatever oozes out of them is foul, foul-smelling, and disgusting._

_yaṃ kiñci paggharati asuciññeva paggharati duggandhaññeva paggharati 
jegucchiyaññeva paggharati_
____

[quote, A.4.386]
____
Therefore be disillusioned with this [wretched human] body

_Tasmātiha bhikkhave imasmiṃ kāye nibbindathā ti._
____

.Illustration
====
nibbidāya

disillusionment [with sensuous pleasure]
====

Then Yasa, having awoken sooner than usual saw his retinue asleep: one with a 
lute in her arm, one with a tabor under her chin, one with a drum under her 
arm, one with dishevelled hair, one who was dribbling, and others who were 
muttering. One would think it was a charnel ground before one's eyes 
(_hatthappattaṃ susānaṃ maññe_).

Seeing this, the danger [of sensuous pleasure] became apparent to him 
(_disvānassa ādīnavo pāturahosi_). His mind was established in 
disillusionment [with sensuous pleasure] (_nibbidāya cittaṃ saṇṭhāsi_) 
(Vin.1.15).

Comment:

This disillusionment did not lead to arahantship, so we do not parenthesise it 
'disillusionment [with originated phenomena].'

.Illustration
====
nibbindati

disillusioned [with originated phenomena]
====

____
Bodily form is existentially void... advertence is existentially void. Seeing 
thus, the noble disciple is disillusioned with bodily form... advertence.

_rūpaṃ bhikkhave... viññāṇaṃ dukkhā. Evaṃ passaṃ bhikkhave 
sutavā ariyasāvako rūpasmimpi nibbindati... viññāṇasmimpi nibbindati._
____

[quote, S.3.21]
____
Being disillusioned [with originated phenomena], he is unattached [to 
originated phenomena]. Being unattached [to originated phenomena], he is 
liberated [from perceptually obscuring states].

_Nibbindaṃ virajjati. Virāgā vimuccati._
____

.Illustration
====
nibbindati

disillusioned [with originated phenomena]
====

____
For one who knows and sees things according to reality, there is no need to 
harbour the aspiration: 'May I be disillusioned with and unattached [to 
originated phenomena]':

_Yathābhūtaṃ bhikkhave jānato passato na cetanāya karaṇīyaṃ 
nibbindāmi virajjāmī ti._
____

[quote, A.5.3]
____
It is natural that one who knows and sees things according to reality, is 
disillusioned with and unattached [to originated phenomena].'

_Dhammatā esā bhikkhave yaṃ yathābhūtaṃ jānaṃ passaṃ nibbindati 
virajjati._
____

.Illustration
====
nibbindituṃ

to be disillusioned
====

____
Unlasting are originated phenomena.

_evaṃ aniccā bhikkhave saṅkhārā_
____

____
Unenduring are originated phenomena.

_evaṃ addhuvā bhikkhave saṅkhārā_
____

____
Unconsoling are originated phenomena.

_evaṃ anassāsikā bhikkhave saṅkhārā._
____

[quote, A.4.101]
____
It is time enough, bhikkhus, to be disillusioned with all originated phenomena, 
to be unattached to them, to be liberated from them.

_yāvañcidaṃ bhikkhave alameva sabbasaṅkhāresu nibbindituṃ alaṃ 
virajjituṃ alaṃ vimuccituṃ._
____

.Illustration
====
nibbindituṃ

to be disillusioned
====

____
A first point is not to be discerned of beings [obstructed by] uninsightfulness 
into reality, and [tethered to individual existence] by craving, roaming and 
wandering the round of birth and death.

_pubbā koṭi na paññāyati avijjānīvaraṇānaṃ sattānaṃ 
taṇhāsaṃyojanānaṃ sandhāvataṃ saṃsarataṃ._
____

• It is time enough, bhikkhus, to be disillusioned with all originated 
phenomena, to be unattached to them, to be liberated from them. +
☸ _Yāvañcidaṃ bhikkhave alameva sabbasaṅkhāresu nibbindituṃ alaṃ_ 
virajjituṃ _alaṃ vimuccituṃ_ (S.2.181-2).

.Illustration
====
nibbindati

disillusioned; nibbindaṃ disillusioned [with originated phenomena]
====

The noble disciple is disillusioned with

____
pleasant sense impression

_sukhāyapi vedanāya nibbindati_
____

____
unpleasant sense impression

_dukkhāyapi vedanāya nibbindati_
____

____
neutral sense impression

_adukkhamasukhāyapi vedanāya nibbindati_
____

____
Being disillusioned [with originated phenomena] he is unattached [to originated 
phenomena].

_nibbindaṃ virajjati_
____

[quote, M.1.500]
____
Being unattached [to originated phenomena] he is liberated [from perceptually 
obscuring states].

_virāgā vimuccati._
____

