== Nicchāta

=== Renderings

- _nicchātā_: free of craving

- _nicchātā_: free of hunger

=== Introduction

==== Chāta: hungry

_Chāta_ means hungry. For example, 'hungry dog' (_chātā sunakhaṃ_ 
Th.v.509).

==== Nicchātā: free of hunger

_Nicchātā_ can mean 'free of physical hunger' (_nis+chātā_, PED):

[quote, Sn.v.707]
____
One who is free of the hunger that is due to desire

_Sa ve icchāya nicchāto._
____

==== Nicchātā: free of craving

_Nicchātā_ can also mean arahantship (_bhikkhu nicchāto parinibbuto ti,_ 
It.48). Here the commentary says _nicchāto_ means _nittaṇho._ Bodhi calls it 
'hungerless.' When Norman follows the commentary he calls it 'without craving'; 
otherwise, 'without hunger':

[quote, Bodhi, A.4.411. Commentary: _Nicchātā ti 
taṇhādiṭṭhicchātānaṃ abhāvena nicchātā_]
____
Hungerless and quenched

_nicchātā nibbutā._
____

[quote, Bodhi, S.3.26. Commentary: _Nicchāto ti nittaṇho_]
____
Free from hunger, fully quenched

_nicchāto parinibbuto._
____

[quote, Norman, Sn.v.735. Commentary: _Nicchāto ti nittaṇho_]
____
Without craving, quenched.

_nicchāto parinibbuto._
____

[quote, Norman, Thī.v.168. Commentary: _Nicchātā ti nittaṇhā._]
____
Without hunger, stilled.

_nicchātā upasantā carissasī ti._
____

==== Nicchāto ti nittaṇho: on favouring the commentary

We follow the commentary in connecting _nicchāto_ and _nittaṇho_ because the 
suttas also link the words:

[quote, S.3.26. Commentary: _Nicchāto ti nittaṇho_]
____
Having removed [the arrow of] craving together with its origin, one is free of 
craving.

_samūlaṃ taṇhaṃ abbuyha nicchāto._
____

[quote, Thī.v.53. Commentary: _Sājja abbūḷhasallāhan ti sā ahaṃ ajja 
sabbaso uddhaṭataṇhāsallā tato eva nicchātā_]
____
Today I have the arrow [of craving] removed. I am free of craving.

_Sājja abbūḷhasallāhaṃ nicchātā._
____

=== Illustrations

.Illustration
====
nicchātā

free of craving
====

[quote, A.4.411]
____
Where sensuous pleasures cease, and those who have put an end to sensuous 
pleasures abide, surely those Venerables are free of craving. They have 
realised the Untroubled.

_Yattha kāmā nirujjhanti ye ca kāme nirodhetvā nirodhetvā viharanti addhā 
te āyasmanto nicchātā nibbutā._
____

Commentary: _Nicchātā ti taṇhādiṭṭhicchātānaṃ abhāvena 
nicchātā._

.Illustration
====
nicchātā

free of craving
====

[quote, Thī.v.168]
____
In this very lifetime you will live the religious life free of craving, 
inwardly at peace.

_Diṭṭheva dhamme nicchātā upasantā carissasī ti._
____

Commentary: _Nicchātā ti nittaṇhā._

.Illustration
====
nicchāto

free of craving
====

[quote, Sn.v.735]
____
By the subsiding of the stream of sense consciousness, a bhikkhu is free of 
craving. He has realised the Untroubled.

_viññāṇupasamā bhikkhu nicchāto parinibbuto ti._
____

Commentary: _Nicchāto ti nittaṇho_

.Illustration
====
nicchāto

free of craving
====

[quote, A.5.65]
____
For one who is free of craving, inwardly at peace, freed from inward distress, 
I make known the realisation of the Untroubled through having no grasping in 
this very lifetime.

_diṭṭheva dhamme nicchāto nibbuto sītibhūto anupādā parinibbānaṃ 
paññāpemī ti._
____

