== Niketa

=== Renderings

- _niketa_: permanent abode

- _niketa_: abode

- _niketa_: home

- _niketin_: dwelling (adjective)

=== Introduction

==== Permanent abodes

The Buddha was critical of permanent abodes, called _niketā_:

[quote, Sn.v.207]
____
Permanent abodes breed spiritual defilement.

_niketā jāyate rajo._
____

[quote, Dh.v.91]
____
The mindful exert themselves. They take no delight in permanent abodes. They 
abandon one home after another like geese leaving a lake.

_Uyyuñjanti satimanto na nikete ramanti te +
Haṃsā va pallalaṃ hitvā okamokaṃ jahanti te._
____

[quote, S.1.199]
____
The bhikkhus abide like deer, free of bondage [to individual existence], and 
with no permanent abodes.

_Migā viya asaṅgacārino aniketā viharanti bhikkhavo ti._
____

=== Illustrations

.Illustration
====
aniketā

with no permanent abodes
====

[quote, S.1.199]
____
The bhikkhus abide like deer, free of bondage [to individual existence], and 
with no permanent abodes.

_Migā viya asaṅgacārino aniketā viharanti bhikkhavo ti._
____

.Illustration
====
aniketa

with no permanent abode
====

[quote, Th.v.36]
____
Abiding with no permanent abode is always excellent.

_Sādhu sadā aniketavihāro._
____

.Illustration
====
aniketa

with no permanent abode
====

[quote, Sn.v.844]
____
With home-life abandoned, wandering with no permanent abode, the sage does not 
create intimate relationships in the village.

_Okaṃ pahāya aniketasārī gāme akubbaṃ muni santhavāni._
____

.Illustration
====
aniketa

with no permanent abode
====

[quote, Sn.v.970]
____
'What will I eat [tomorrow]?' 'Where will I eat [tomorrow]?' 'How uncomfortably 
I slept [last night]!' 'Where will I sleep tonight?' The disciple in training 
wandering with no permanent abode should eliminate such lamentable thoughts.

_Kiṃsū asissāmi kuvaṃ vā asissaṃ dukkhaṃ vata settha kvajja sessaṃ 
+
Ete vitakke paridevaneyye vinayetha sekho aniketacārī._
____

.Illustration
====
niketā

permanent abode
====

[quote, Sn.v.207]
____
Intimate relationships breed fear. Permanent abodes breed spiritual defilement.

_Santhavāto bhayaṃ jātaṃ niketā jāyate rajo._
____

.Illustration
====
niketa

permanent abode
====

____
How does one wander with a permanent abode?

_Kathañca gahapati niketasārī hoti_
____

[quote, S.3.10]
____
One is called 'one who wanders with a permanent abode' through dwelling with, 
pursuing, and emotional bondage to the phantasm of a visible object.

_rūpanimittaniketavisāravinibandhā kho gahapati niketasārīti vuccati._
____

____
How does one wander without a permanent abode?

_Kathañca gahapati aniketasārī hoti_
____

[quote, S.3.10]
____
The abiding with, pursuing, and emotional bondage to the phantasm of visible 
objects has been abandoned by the Perfect One, chopped down at the root, 
completely and irreversibly destroyed, never to arise again in future. 
Therefore the Perfect One is called one who wanders without a permanent abode.

_rūpanimittaniketavisāravinibandhā kho gahapati tathāgatassa pahīnā 
ucchinnamūlā tālāvatthukatā anabhāvakatā āyatiṃ anuppādadhammā. 
Tasmā tathāgato aniketasārīti vuccati._
____

Comment:

PED says _visāra_ is 'spreading, diffusion, scattering,' which does not fit 
here. We therefore take the meaning of _visāra_ from _sara_ because both stem 
from the root sṛ. The meaning of _sarati_ is 'to go, flow, run, move along.' 
_Sara_ is 'going, moving, following' (PED).

.Illustration
====
niketaṃ

abode
====

[quote, D.3.171]
____
In whatever former birth, former state of individual existence, former abode, 
that the Perfect One was a human being, he abandoned malicious speech.

_Yampi bhikkhave tathāgato purimaṃ jātiṃ purimaṃ bhavaṃ purimaṃ 
niketaṃ pubbe manussabhūto samāno pisuṇaṃ vācaṃ pahāya._
____

.Illustration
====
niketino

dwelling
====

[quote, Sn.v.422]
____
Straight ahead in that direction, king, there is a people on the flank of the 
Himalayas endowed with wealth and energy, dwelling amongst the Kosalan people.

_Ujuṃ janapado rāja himavantassa passato +
Dhanaviriyena sampanno kosalesu niketino._
____

.Illustration
====
niketa

home
====

[quote, Th.v.599]
____
The black crow dwelling [and feasting] in its home in the charnel ground.

_Apaṇḍaro aṇḍasambhavo sīvathikāya niketacāriko._
____

