== Nimitta

=== Renderings

- _nimitta_: hint

- _nimitta_: boundary mark

- _nimitta_: sexual organ

- _nimitta_: phenomena

- _nimitta_: quality

- _nimitta_: aspect

- _nimitta_: attribute

- _nimitta_: body mark

- _nimitta_: telltale sign

- _nimitta_: grounds

- _nimitta_: practice

- _nimitta_: way of practice

- _nimitta_: abiding phenomenon

- _mukhanimitta_: facial image

- _samādhinimitta_: object of meditation

- _pubbanimitta_: preindication

- _pubbanimitta_: premonitory sign

- _animitta dhātu_: the unabiding phenomenon

- _animitta cetosamādhi_: inward collectedness that is focused upon the 
unabiding [phenomena]

- _animitta cetovimutti_: liberation [from perceptually obscuring states] by 
focusing upon the unabiding [phenomenon]

=== Introduction

==== Nimitta: phantasm

A phantasm is a mental representation of a sense object that one attaches to 
and pursues:

____
If a bhikkhu sees a visible object via the visual sense,

_cakkhunā rūpaṃ disvā_
____

____
... and his mind pursues the phantasm of the visible object,

_rūpanimittānusāri viññāṇaṃ hoti_
____

____
... is tied to the sweetness of the phantasm of the visible object,

_rūpanimittassādagathitaṃ_
____

[quote, M.3.225]
____
... then his mind is called 'distracted and scattered externally'

_bahiddhā viññāṇaṃ vikkhittaṃ visaṭanti vuccati._
____

==== Nimitta: not 'mental image'

Visual phantasms could be called 'mental images,' but not all phantasms are 
visual, so 'image' is incorrect for _nimitta_. For example:

____
In hearing an audible object via the auditory sense, if his mind pursues the 
phantasm of the audible object _

_Sotena saddaṃ sutvā saddanimittānusārī viññāṇaṃ hoti_
____

____
In knowing a mentally known object via the mental sense, if his mind pursues 
the phantasm of the mentally known object _

_Manasā dhammaṃ viññāya dhammanimittānusāri viññāṇaṃ hoti_
____

==== Reification: overcome by focusing upon the unabiding phenomenon

Phantasms persist in the mind if sense objects are 'reified'; that is, if sense 
objects are seen as real and unchanging. Phantasms are overcome by focusing 
upon the unabiding phenomenon. This is the end of reification.

____
It is impossible, friend, out of the question, that one might develop and 
cultivate the liberation [from perceptually obscuring states] by focusing upon 
the unabiding [phenomenon], make it one's vehicle and practice, carry it out, 
pursue it, and properly undertake it, yet the mind would still pursue 
phantasms. There is no such possibility.

_Aṭṭhānametaṃ āvuso anavakāso yaṃ animittāya cetovimuttiyā 
bhāvitāya bahulīkatāya yānīkatāya vatthukatāya anuṭṭhitāya 
paricitāya susamāraddhāya atha ca panassa nimittānusārī viññāṇaṃ 
bhavissati ti ti netaṃ ṭhānaṃ vijjati._
____

[quote, A.3.292]
____
... For this is the liberation from all abiding phenomena, namely the 
liberation [from perceptually obscuring states] by focusing upon the unabiding 
&#8203;[phenomenon]._

_Nissaraṇaṃ hetaṃ āvuso sabbanimittānaṃ yadidaṃ animittā 
cetovimutti._
____

We will discuss the nature of the unabiding phenomenon below.

==== Nimitta: abiding phenomena

_Nimitta_ can mean 'abiding phenomenon,' which means a phenomenon that is 
regarded as an actual, existing thing instead of an everchanging condition. 
Abiding phenomena are illusions produced by attachment, hatred, and 
undiscernment of reality (_rāgo kho bhante nimittakaraṇo doso 
nimittakaraṇo moho nimittakaraṇo_, S.4.296-7). A meditator can choose to 
not focus on abiding phenomena, and instead focus on 'the unabiding phenomenon' 
(_animitta dhātu_ M.1.297). For fuller versions of the quotes here, see 
Illustrations below.

==== Focusing upon the unabiding phenomenon equals perceiving the passing away and ending [of originated phenomena]

Focusing on the unabiding phenomenon (i.e. the _animittadhātu_) is equivalent 
to perceiving the passing away and ending [of originated phenomena]. This can 
be proven in four steps as follows:

1. Attaining the liberation [from perceptually obscuring states] by focusing 
upon the unabiding [phenomenon] (_animittāya cetovimuttiyā samāpattiyā_) 
involves these steps:
+
[quote, M.1.297]
____
not focusing upon any abiding phenomenon

_sabbanimittānañca amanasikāro_

focusing upon the unabiding phenomenon

_animittāya ca dhātuyā manasikāro._
____

2. 'Any/all abiding phenomena' (_sabbanimittāni_) means the senses, their 
objects, and the phenomena involved in sense impression, as this passage shows:
+
[quote, S.4.50]
____
He perceives all phenomena (_sabbanimittāni_) differently. He sees the visual 
sense differently, he sees visible objects differently... .

_sabbanimittāni aññato passati cakkhuṃ aññato passati rūpe aññato 
passati... mano aññato passati dhamme aññato passati manoviññāṇaṃ 
aññato passati manosamphassaṃ aññato passati yampidaṃ mano 
samphassapaccayā uppajjati sukhaṃ vā dukkhaṃ vā adukkhamasukhaṃ vā 
tampi aññato passati._
____

3. Not focusing upon any abiding phenomenon (_sabbanimittānañca 
amanasikāro_) is equivalent to the _etaṃ santaṃ_ reflection, as this 
passage shows:
+
[quote, A.5.321]
____
A bhikkhu reflects thus: This is peaceful, this is sublime, namely: the 
quelling of all originated phenomena, the relinquishment of the whole 
phenomenon of attachment, the destruction of craving, the passing away [of 
originated phenomena], the ending [of originated phenomena], the Untroubled.

_Idhānanda bhikkhu evaṃ manasikaroti: etaṃ santaṃ etaṃ paṇītaṃ 
yadidaṃ sabbasaṅkhārasamatho sabbūpadhipaṭinissaggo taṇhakkhayo 
virāgo nirodho nibbānan ti_

... In this way his winning of inward collectedness is such that though he does 
not contemplate the visual sense or visible object... nor what is seen, heard, 
sensed, cognised, attained, sought after, thought out by mind, all that he does 
not contemplate, but yet he still contemplates.

_evaṃ kho ānanda siyā bhikkhuno tathārūpo samādhipaṭilābho yathā na 
cakkhuṃ manasikareyya na rūpaṃ manasikareyya... yampidaṃ diṭṭhaṃ 
sutaṃ mutaṃ viññātaṃ pattaṃ pariyesitaṃ anuvicaritaṃ manasā 
tampi na manasikareyya manasi ca pana kareyyā ti._
____

4. The _etaṃ santaṃ_ reflection equals the perceptions of non-attachment to 
and ending [of originated phenomena]. This is obvious in the passage in 3). The 
following passages also show it:
+
[quote, A.5.110]
____
And what, Ānanda, is the perception of the passing away [of originated 
phenomena]?

_virāgasaññā_

... In this regard, Ānanda, a bhikkhu... contemplates thus: This is peaceful, 
this is sublime, namely: the quelling of all originated phenomena, the 
relinquishment of the whole phenomenon of attachment, the destruction of 
craving, the passing away [of originated phenomena], the Untroubled.

_etaṃ santaṃ etaṃ paṇītaṃ yadidaṃ sabbasaṅkhārasamatho 
sabbūpadhipaṭinissaggo taṇhakkhayo virāgo nibbānan ti._

What is the perception of the ending [of originated phenomena]?

_nirodhasaññā_

... In this regard, Ānanda, a bhikkhu... contemplates: This is peaceful, this 
is sublime, namely: the quelling of all originated phenomena, the 
relinquishment of the whole phenomenon of attachment, the destruction of 
craving, the ending [of originated phenomena], the Untroubled.

_etaṃ santaṃ etaṃ paṇītaṃ yadidaṃ sabbasaṅkhārasamatho 
sabbūpadhipaṭinissaggo taṇhakkhayo nirodho nibbānan ti._
____

Thus focusing upon the unabiding phenomenon is equivalent to perceiving the 
passing away and ending of originated phenomena.

==== Focusing upon the unabiding phenomenon means the disappearance of personal identity

That the _etaṃ santaṃ_ reflection, and therefore the _animittadhātu_, is 
equivalent to the disappearance of the illusions of personal identity and 
personal ownership, and of the proclivity to self-centredness is indicated in 
the following passage:

____
In this regard a bhikkhu reflects thus: This is peaceful, this is sublime, 
namely: the quelling of all originated phenomena, the relinquishment of the 
whole phenomenon of attachment, the destruction of craving, the passing away 
&#8203;[of originated phenomena], the ending [of originated phenomena], the Untroubled.

_Idhānanda bhikkhuno evaṃ hoti etaṃ santaṃ etaṃ paṇītaṃ yadidaṃ 
sabbasaṅkārasamatho sabbūpadhipaṭinissaggo taṇhakkhayo virāgo nirodho 
nibbānanti._
____

____
... In this way his winning of inward collectedness would be such that 
regarding this [wretched human] body together with its advertence he would have 
no illusions of personal identity or personal ownership, and no proclivity to 
self-centredness. Likewise in all external phenomena he would have no illusions 
of personal identity or personal ownership, and no proclivity to 
self-centredness.

_Evaṃ kho ānanda siyā bhikkhuno tathārūpo samādhipaṭilābho yathā 
imasmiñca saviññāṇake kāye ahaṅkāramamaṅkāramānānusayā nāssu 
bahiddhā ca sabbanimittesu ahaṅkāramamaṅkāramānānusayā nāssu_
____

[quote, A.1.133]
____
... He would so enter and abide in the liberation [from attachment through 
inward calm] and the liberation [from uninsightfulness] through penetrative 
discernment, that he would have no illusions of personal identity or personal 
ownership, and no proclivity to self-centredness.

_yañca cetovimuttiṃ paññāvimuttiṃ upasampajja viharato 
ahaṅkāramamaṅkāramānānusayā na honti tañca cetovimuttiṃ 
paññāvimuttiṃ upasampajja vihareyya._
____

=== Illustrations

.Illustration
====
nimitte

hint
====

[quote, S.5.259]
____
But though Venerable Ānanda was given such a broad hint by the Blessed One, 
such an obvious suggestion, he was unable to perceive it._

_Evampi kho āyasmā ānando bhagavatā oḷārike nimitte kayiramāne 
oḷārike obhāse kayiramāne nāsakkhi paṭivijjhituṃ._
____

.Illustration
====
nimittaṃ

boundary mark
====

____
I allow you to agree upon a boundary. And thus should it be agreed upon:

_anujānāmi bhikkhave sīmaṃ sammannituṃ. Evañca pana bhikkhave 
sammannitabbā._
____

____
First, boundary marks should be announced

_Paṭhamaṃ nimittā kittetabbā_
____

[quote, Vin.1.106]
____
A boundary mark consisting of a hillside, a rock, a grove, a tree, a road, an 
anthill, a river, a body of water.

_pabbatanimittaṃ pāsāṇanimittaṃ vananimittaṃ rukkhanimittaṃ 
magganimittaṃ vammikanimittaṃ nadīnimittaṃ udakanimittaṃ._
____

.Illustration
====
nimittaṃ

sexual organ
====

[quote, Vin.1.28]
____
Sexual organ penetrated by a sexual organ, a reproductive organ by a 
reproductive organ, even if only the diametre of a sesame seed.

_yo nimittena nimittaṃ aṅgajātena aṅgajātaṃ antamaso 
tilaphalamattampi paveseti._
____

.Illustration
====
nimittesu

phenomena
====

[quote, M.3.18]
____
Knowing and seeing what in this [wretched human] body together with its 
advertence and all external phenomena, do the illusion of personal identity, 
the illusion of personal ownership, and the proclivity to self-centredness not 
exist?

_Kathaṃ pana bhante jānato kathaṃ passato imasmiñca saviññāṇake 
kāye bahiddhā ca sabbanimittesu ahaṅkāramamaṅkāramānānusayā na 
hontī ti?._
____

.Illustration
====
nimittāni

phenomena
====

____
Through profoundly understanding the whole teaching, he perceives all phenomena 
differently.

_sabbaṃ dhammaṃ pariññāya sabbanimittāni aññato passati_
____

[quote, S.4.50]
____
He sees the visual sense differently, he sees visible objects differently... 
whatever sense impression that arises due to mental sensation... that too he 
sees differently.

_cakkhuṃ aññato passati rūpe... cakkhuviññāṇaṃ... 
cakkhusamphassaṃ... yampidaṃ cakkhusamphassapaccayā uppajjati vedayitaṃ 
sukhaṃ vā dukkhaṃ vā adukkhamasukhaṃ vā tampi aññato passati._
____

.Illustration
====
nimittaṃ

quality
====

____
There is the quality of loveliness:

_Atthi bhikkhave subhanimittaṃ_
____

[quote, S.5.64]
____
Much improper contemplation in that regard is a condition that nourishes both 
the arising of unarisen sensuous hankering, and the increase and expansion of 
arisen sensuous hankering.

_Tattha ayoniso manasikārabahulīkāro ayamāhāro anuppannassa vā 
kāmacchandassa uppādāya uppannassa vā kāmacchandassa bhiyyobhāvāya 
vepullāya._
____

.Illustration
====
nimittaṃ

quality
====

[quote, S.1.188]
____
Avoid the quality of loveliness that is associated with attachment

_Nimittaṃ parivajjehi subhaṃ rāgūpasaṃhitaṃ._
____

.Illustration
====
nimitta

aspect
====

[quote, M.3.134]
____
In seeing a visible object via the visual sense do not grasp its aspects and 
features.

_Cakkhunā rūpaṃ disvā mā nimittaggāhī mānuvyañjanaggāhī._
____

.Illustration
====
nimittaṃ

aspect
====

[quote, S.4.76]
____
In seeing a visible object with mindfulness muddled, focusing on the agreeable 
aspect,

_Rūpaṃ disvā sati muṭṭhā piyaṃ nimittaṃ manasikaroto._
____

.Illustration
====
nimittaṃ

aspect
====

• Ignoring the aspect of shape but contemplating the aspect of light. +
_rūpanimittaṃ amanasikaritvā obhāsanimittaṃ manasikaromi_ (M.3.161).

.Illustration
====
nimittā

attributes
====

[quote, M.1.360]
____
You have the traits, marks, and attributes of a householder

_Te hi te gahapati ākārā te liṅgā te nimittā yathā taṃ gahapatissā 
ti._
____

.Illustration
====
nimitta

body marks
====

[quote, D.3.152]
____
Experts in body marks and conformations (i.e. physiognomists)

_vyañjananimittakovidā._
____

.Illustration
====
nimittaṃ

telltale signs
====

____
Suppose a wise, competent, proficient cook presented a king or a royal minister 
with various kinds of savoury dishes. Such a cook would notice his master's 
telltale signs.

_paṇḍito viyatto kusalo sūdo sakassa bhattu nimittaṃ uggaṇhāti:_
____

____
'Today this dish pleased my master' or 'He reached for this one' or 'He took a 
lot of this one' or 'He praised this one'_

_idaṃ vā me ajja bhattu sūpeyyaṃ ruccati imassa vā abhiharati imassa vā 
bahuṃ gaṇhāti imassa vā vaṇṇaṃ bhāsati_
____

[quote, S.5.151]
____
That cook gains gifts of clothing, wages and bouses. Why? Because that wise, 
competent, proficient cook notices his master's telltale signs.

_Tathā hi so bhikkhave paṇḍito byatto kusalo sūdo sakassa bhattu 
nimittaṃ uggaṇhāti._
____

.Illustration
====
nimittaṃ

telltale sign
====

____
As he abides contemplating the nature of the body, his mind becomes collected, 
his defilements are abandoned.

_Tassa kāye kāyānupassino viharato cittaṃ samādhiyati upakkilesā 
pahīyanti_
____

____
He notices that telltale sign._

_so taṃ nimittaṃ uggaṇhāti._
____

____
That wise, competent, proficient bhikkhu gains pleasant states of meditation in 
this lifetime and mindfulness and full consciousness. For what reason?_

_Sakho so bhikkhave paṇḍito viyatto kusalo bhikkhu lābhī ceva hoti 
diṭṭhadhammasukhavihārānaṃ lābhī hoti satisampajaññassa. Taṃ 
kissa hetu:_
____

[quote, S.5.151-2]
____
Because that wise, competent, proficient bhikkhu notices the telltale signs of 
his own mind._

_tathā hi so bhikkhave paṇḍito vyatto kusalo bhikkhu sakassa cittassa 
nimittaṃ uggaṇhātī ti._
____

.Illustration
====
nimittassa

telltale signs
====

[quote, Th.v.85]
____
One who is proficient [in discerning] the telltale signs of the mind.

_Cittanimittassa kovido._
____

.Illustration
====
pubbanimittāni

premonitory sign
====

____
When a deva is due to pass away from the group of devas, five premonitory signs 
appear:

_pañcassa pubbanimittāni pātubhavanti_
____

[quote, It.76-7]
____
his garlands wither, his clothes get dirty, his armpits sweat, his body 
radiance fades, he no longer enjoys his throne.

_mālā milāyanti vatthāni kilissanti kacchehi sedā muccanti kāye 
dubbaṇṇiyaṃ okkamati sake devo devāsane nābhiramatī ti._
____

.Illustration
====
pubbanimittaṃ

preindication
====

• Bhikkhus, this is the foretoken and preindication of the rising of the sun, 
namely dawn. +
_Suriyassa bhikkhave udayato etaṃ pubbaṅgamaṃ etaṃ pubbanimittaṃ 
yadidaṃ aruṇaggaṃ_ (S.5.30).

.Illustration
====
pubbanimittaṃ

preindication
====

____
So, too, for a bhikkhu this is the foretoken and preindication of the arising 
of the noble eightfold path, namely virtuous friendship.

_evameva kho bhikkhave bhikkhuno ariyassa aṭṭhaṅgikassa maggassa 
uppādāya etaṃ pubbaṅgamaṃ etaṃ pubbanimittaṃ yadidaṃ 
kalyāṇamittatā_
____

[quote, S.5.30]
____
When a bhikkhu has a virtuous friend, it is to be expected that he will develop 
this noble eightfold path

_Kalyāṇamittassetaṃ bhikkhave bhikkhuno pāṭikaṅkhaṃ ariyaṃ 
aṭṭhaṅgikaṃ maggaṃ bhāvessati._
____

.Illustration
====
nimittaṃ

image
====

[quote, A.5.92]
____
A woman or man examining their facial image in a bowl of clear water.

_acche vā udapatte sakaṃ mukhanimittaṃ paccavekkhamāno._
____

.Illustration
====
nimittaṃ

grounds
====

[quote, S.5.215]
____
There has arisen in me this faculty of physical-plus-psychological neutral 
experience. That arises with grounds, with a source, with originative factors, 
with necessary conditions.

_uppannaṃ kho me idaṃ upekkhindriyaṃ. Tañca kho sanimittaṃ 
sanidānaṃ sasaṅkhāraṃ sappaccayaṃ._
____

.Illustration
====
nimittaṃ

grounds
====

[quote, A.1.82]
____
Unvirtuous, spiritually unwholesome factors arise with grounds, not without 
grounds. By abandoning those grounds those unvirtuous, spiritually unwholesome 
factors do not exist.

_Sanimittā bhikkhave uppajjanti pāpakā akusalā dhammā no animittā. 
Tasseva nimittassa pahānā evaṃ te pāpakā akusalā dhammā na honti._
____

.Illustration
====
samādhinimittaṃ

object of meditation
====

[quote, A.1.115]
____
He carefully concentrates on an object of meditation

_sakkaccaṃ samādhinimittaṃ adhiṭṭhāti._
____

.Illustration
====
samādhinimittaṃ

meditation object
====

____
A bhikkhu fosters a favourable meditation object,

_Idha bhikkhave bhikkhu uppannaṃ bhaddakaṃ samādhinimittaṃ anurakkhati_
____

____
the mental image of a skeleton

_aṭṭhikasaññaṃ_
____

____
the mental image of a maggot-infested corpse

_puḷavakasaññaṃ_
____

____
the mental image of a discoloured corpse

_vinīlakasaññaṃ_
____

____
the perception of a festering corpse

_vipubbakasaññaṃ_
____

____
the mental image of a cut up corpse

_vicchiddakasaññaṃ_
____

[quote, A.2.16-7]
____
the mental image of a bloated corpse

_uddhumātakasaññaṃ._
____

.Illustration
====
nimitte

meditation object
====

[quote, S.5.156]
____
That bhikkhu should direct his mind towards some faith inspiring meditation 
object.

_kismiñcideva pasādaniye nimitte cittaṃ paṇidahitabbaṃ._
____

.Illustration
====
nimittaṃ

ways of practice
====

____
A bhikkhu who is applied to the higher mental states should focus on three ways 
of practice not exclusively, but from time to time: inward collectedness, 
effort, and detached awareness

_Adhicittamanuyuttena bhikkhave bhikkhunā tīṇi nimittāni kālena kālaṃ 
manasikātabbāni kālena kālaṃ samādhinimittaṃ manasikātabbaṃ kālena 
kālaṃ paggahanimittaṃ manasikātabbaṃ kālena kālaṃ 
upekkhānimittaṃ manasikātabbaṃ._
____

____
If such a bhikkhu focuses exclusively on the practice of inward collectedness 
it is likely that his mind will fall into indolence

_ekantaṃ samādhinimittaññeva manasikareyya ṭhānaṃ taṃ cittaṃ 
kosajjāya saṃvatteyya_
____

____
If he focuses exclusively on the practice of effort it is likely that his mind 
will fall into restlessness

_ekantaṃ paggahanimittaññeva manasikareyya ṭhānaṃ taṃ cittaṃ 
uddhaccāya saṃvatteyya_
____

[quote, A.1.256]
____
If he focuses exclusively on the practice of detached awareness it is likely 
that his mind will be not properly collected for the destruction of 
perceptually obscuring states

_ekantaṃ upekkhānimittaññeva manasikareyya ṭhānaṃ taṃ cittaṃ na 
sammā samādhiyetha āsavānaṃ khayāya._
____

.Illustration
====
nimittāni

ways of practice; nimittaṃ, meditation object
====

____
A bhikkhu who is applied to the higher mental states should from time to time 
focus on five ways of practice.

_Adhicittamanuyuttena bhikkhave bhikkhunā pañca nimittāni kālena kālaṃ 
manasikātabbāni. Katamāni pañca?_
____

____
When a bhikkhu is focusing on some meditation object that arouses unvirtuous, 
spiritually unwholesome thoughts connected with desire, hatred, and 
undiscernment of reality

_Idha bhikkhave bhikkhunā yaṃ nimittaṃ āgamma yaṃ nimittaṃ 
manasikaroto uppajjanti pāpakā akusalā vitakkā chandūpasaṃhitāpi 
dosūpasaṃhitāpi mohūpasaṃhitāpi._
____

____
then he should focus on some other meditation object connected with what is 
spiritually wholesome.

_tena bhikkhave bhikkhunā tamhā nimittā aññaṃ nimittaṃ 
manasikātabbaṃ kusalūpasaṃhitaṃ_
____

____
then he should examine the danger of those thoughts, that they are spiritually 
unwholesome, blameworthy, and have an unpleasant karmic consequence

_tena bhikkhave bhikkhunā tesaṃ vitakkānaṃ ādīnavo upaparikkhitabbo 
itipime vitakkā akusalā itipime vitakkā sāvajjā itipime vitakkā 
dukkhavipākāti_
____

____
then he should arouse unmindfulness and inattention towards those thoughts

_tena bhikkhave bhikkhunā tesaṃ vitakkānaṃ asati amanasikāro 
āpajjitabbo._
____

____
then he should pay attention to the dynamic quality of those thoughts

_tena bhikkhave bhikkhunā tesaṃ vitakkānaṃ 
vitakkasaṅkhārasaṇṭhānaṃ manasikātabbaṃ_
____

• then he should beat down, restrain, crush mind with the mind +
_tena bhikkhave bhikkhunā dante'bhidantamādhāya jivhāya tāluṃ āhacca 
cetasā cittaṃ abhiniggaṇhitabbaṃ abhinippīḷetabbaṃ 
abhisantāpetabbaṃ._

[quote, M.1.118-122]
____
Thus, those unvirtuous, spiritually unwholesome thoughts connected with desire, 
hatred, and undiscernment of reality are abandoned.

_ye pāpakā akusalā vitakkā chandūpasaṃhitāpi dosūpasaṃhitāpi 
mohūpasaṃhitāpi te pahīyanti._
____

.Illustration
====
nimittaṃ

practice
====

____
There are the practice of inward calm, the practice of inward composure:

_Atthi bhikkhave samathanimittaṃ avyagganimittaṃ_
____

[quote, S.5.66]
____
Much proper contemplation in that regard is a condition that nourishes both the 
arising of the unarisen enlightenment factor of inward collectedness and the 
perfection through spiritual cultivation of the arisen enlightenment factor of 
inward collectedness.

_tattha yoniso manasikārabahulīkāro ayamāhāro anuppannassa vā 
samādhisambojjhaṅgassa uppādāya uppannassa vā samādhisambojjhaṅgassa 
bhāvanāya pāripūriyā._
____

.Illustration
====
nimittānaṃ

perception of any abiding phenomenon; animittāya dhātuyā, the unabiding 
phenomenon
====

____
Two necessary conditions for the attainment of the liberation [from 
perceptually obscuring states] by focusing upon the unabiding [phenomenon]

_dve kho āvuso paccayā animittāya cetovimuttiyā samāpattiyā_
____

____
not focusing upon any abiding phenomenon

_sabbanimittānañca amanasikāro_
____

____
focusing upon the unabiding phenomenon

_animittāya ca dhātuyā manasikāro_
____

____
Three necessary conditions for the persistence of the liberation [from 
perceptually obscuring states] by focusing upon the unabiding [phenomenon]

_Tayo kho āvuso paccayā animittāya cetovimuttiyā ṭhitiyā_
____

____
not focusing upon any abiding phenomenon

_sabbanimittānañca amanasikāro_
____

____
focusing upon the unabiding phenomenon,

_animittāya ca dhātuyā manasikāro_
____

____
a prior aspiration [for its persistence]

_pubbeva abhisaṅkhāro_
____

To emerge, there must be

____
focusing upon the perception of all abiding phenomena

_sabbanimittānañca manasikāro_
____

[quote, M.1.297]
____
not focusing upon the unabiding phenomenon

_animittāya ca dhātuyā amanasikāro._
____

.Illustration
====
nimitta

perception of any abiding phenomenon
====

____
In this regard, by not focusing upon any abiding phenomenon, a bhikkhu enters 
and abides in the inward collectedness that is focused upon the unabiding 
&#8203;[phenomena].

_Idha bhante bhikkhu sabbanimittānaṃ amanasikārā animittaṃ 
cetosamādhiṃ upasampajja viharati_
____

[quote, S.4.296-7]
____
This is called the liberation [from perceptually obscuring states] by focusing 
upon the unabiding [phenomenon]...

_ayaṃ vuccati bhante animittā cetovimutti...._
____

.Illustration
====
nimitta

abiding phenomenon
====

[quote, S.4.296-7]
____
Attachment, bhante, is a producer of abiding phenomena. Hatred is a producer of 
abiding phenomena. Undiscernment of reality is a producer of abiding phenomena.

_rāgo kho bhante nimittakaraṇo doso nimittakaraṇo moho nimittakaraṇo._
____

.Illustration
====
animitto cetosamādhi

inward collectedness that is focused upon the unabiding [phenomena]; 
nimittānaṃ, any abiding phenomenon; nimittā, phantasm
====

Venerable MahāMoggallāna said this:

____
'Here, friends, while I was alone in solitary retreat, a reflection arose in my 
mind thus: 'It is said, "inward collectedness that is focused upon the 
unabiding [phenomena]; inward collectedness that is focused upon the unabiding 
&#8203;[phenomena]." What now is the inward collectedness that is focused upon the 
unabiding [phenomena]?'

_Animitto cetosamādhi animitto cetosamādhīti vuccati katamo nu kho animitto 
cetosamādhī ti_
____

____
Then, friends, it occurred to me:

_Tassa mayhaṃ āvuso etadahosi_
____

____
In this regard a bhikkhu, by not focusing upon any abiding phenomenon,

_Idha bhikkhu sabbanimittānaṃ amanasikārā_
____

____
enters and abides in the inward collectedness that is focused upon the 
unabiding [phenomena].

_animittaṃ cetosamādhiṃ upasampajja viharati_
____

____
This is called the inward collectedness that is focused upon the unabiding 
&#8203;[phenomena].

_ayaṃ vuccati animitto cetosamādhī ti._
____

____
Then, friends, by not focusing upon any abiding phenomenon,

_So khvāhaṃ āvuso sabbanimittānaṃ amanasikārā_
____

____
I entered and dwelt in inward collectedness that is focused upon the unabiding 
&#8203;[phenomena].

_animittaṃ cetosamādhiṃ upasampajja viharāmi_
____

____
While I abided therein my mind pursued phantasms.

_tassa mayhaṃ āvuso iminā vihārena viharato nimittānusārī viññānam 
hoti_
____

____
Then, friends, the Blessed One came to me by means of psychic power and said:

_Atha kho maṃ āvuso bhagavā iddhiyā upasaṅkamitvā etadavoca_
____

____
'Moggallāna, Moggallāna, do not be negligent, brahman, in [practising] inward 
collectedness that is focused upon the unabiding [phenomena].

_moggallāna moggallāna mā brāhmaṇa animittaṃ cetosamādhiṃ pamādo_
____

____
Steady your mind in inward collectedness that is focused upon the unabiding 
&#8203;[phenomena]

_animittena cetosamādhismiṃ cittaṃ saṇṭhapehi_
____

____
Concentrate your mind in inward collectedness that is focused upon the 
unabiding [phenomena]

_animittena cetosamādhismiṃ cittaṃ ekodiṃ karohi_
____

[quote, S.4.263-269]
____
Compose your mind in inward collectedness that is focused upon the unabiding 
&#8203;[phenomena]

_animitte cetosamādhismiṃ cittaṃ samādahāti._
____

Comment:

At D.3.249, it says that one who has developed _animitta cetovimuttī_, it is 
impossible, out of the question, that his mind would pursue phantasms. So, 
Moggallāna's attainment must have been weakly developed.

