== Nindā

=== Renderings

- _nindā_: criticism

- _nindati_: to criticise

- _anindita_: beyond criticism

=== Introduction

==== Nindā: criticism not blame

Praise and blame are wrongfully used as opposites in English, where praise's 
opposite is in fact criticism. The problem is so deeply ingrained that 
'blameworthy' actually means 'worthy of criticism,' and 'blameless' means 'not 
worthy of criticism.' To understand _ninda_, we will first discuss the 
difference between blame and criticism:

- Blame answers the question: 'Who or what is responsible for something bad?' 
It involves no should's or shouldn'ts.

- Criticism means saying something should have been better, or should or 
shouldn't have happened, or be the way it is.

==== Criticism and blame: illustration

We might either blame the cook (tell him he was responsible), or criticise him 
(tell him he should have been better). And though we criticise the food (it 
should have been better), we do not blame it, because it was not responsible.

==== Considering the Illustrations

Now let us consider the Illustrations to be presented below:

1. When the bhikkhu Kokālika accused bhikkhus of unvirtuous desires (S.1.150), 
he was saying they should have been better. Therefore he was criticising them. 
But he was not holding them responsible, so it was not a matter of blame.

2. When in _Dhammapada_ verse 227 a bhikkhu talked too much, people complained. 
He should have been better. So it is criticism. And although the bhikkhu's 
speech could be criticised (it should have been better) it cannot be blamed, 
because it was not responsible.

3. In _Dhammapada_ verse 309, a man commits adultery. If people criticise him, 
they would be saying he should not have done it. But if her character is 
ruined, they could blame him, because he was responsible.

==== No Pāli word for blame

There is no Pāli word for 'to blame.' Buddhadatta's English to Pāli 
Dictionary gives three words for blame: _upavadati, codeti_ and _nindati_. 
These all in fact mean 'to criticise' or 'to reprove':

[quote, M.1.440]
____
If a bhikkhu does not fulfil the training in virtue, the Teacher criticises 
(_upavadati_) him, his discerning wise companions in the religious life 
criticise him, the devas criticise him, and he himself even criticises himself.

_satthāpi upavadati. Anuvicca pi viññū sabrahmacārī upavadanti. Devatāpi 
upavadanti. Attāpi attānaṃ upavadati._
____

[quote, Vin.2.250]
____
If a bhikkhu is wanting to reprove another (_codetu_), having contemplated five 
principles within himself he may do so:

_Codakenupāli bhikkhunā paraṃ codetukāmena pañca dhamme ajjhattaṃ 
manasikaritvā paro codetabbo._
____

=== Illustrations

.Illustration
====
nindiyaṃ

criticism
====

The bhikkhu Kokālika was reborn in hell for repeatedly criticising Venerables 
Sāriputta and Moggallāna as follows:

____
-- 'Bhante, Sāriputta and Moggallāna have unvirtuous desires and are 
dominated by unvirtuous desires.'

_pāpicchā bhante sāriputtamoggallānā pāpikānaṃ icchānaṃ 
vasaṅgatā ti._
____

The Buddha later reflected:

[quote, S.1.150-153]
____
-- 'He who praises one deserving criticism, or criticises one deserving praise, 
accumulates demerit with his mouth, by which he finds no happiness.

_Yo nindiyaṃ pasaṃsati taṃ vā nindati yo pasaṃsiyo +
Vicināti mukhena so kaliṃ kalinā tena sukhaṃ na vindati._
____

.Illustration
====
aninditā

beyond criticism
====

[quote, A.2.63]
____
Having eliminated the stain of stinginess together with its origin, they are 
beyond criticism.

_Vineyya maccheramalaṃ samūlaṃ aninditā._
____

.Illustration
====
nindanti

criticise; anindito, beyond criticism
====

[quote, Dh.v.227]
____
&#8203;[People] criticise one who sits silently. They criticise one who speaks a lot. 
They even criticise one who speaks moderately. There is no one beyond criticism 
in the world.

_Nindanti tuṇhimāsīnaṃ nindanti bahubhāṇinaṃ +
Mitabhāṇimpi nindanti natthi loke anindito._
____

.Illustration
====
nindaṃ

criticism
====

[quote, Dh.v.309]
____
The man negligently applied [to the practice] who pursues another's wife meets 
with four states: the accumulation of demerit; insomnia; thirdly, criticism; 
fourthly, hell.

_Cattāri ṭhānāni naro pamatto āpajjati paradārūpasevī +
Apuññalābhaṃ na nikāmaseyyaṃ nindaṃ tatiyaṃ nirayaṃ catutthaṃ._
____

.Illustration
====
nindāya

criticism
====

[quote, Sn.v.826]
____
In the midst of the assembly, engaged in dispute, [each] is desirous of praise, 
but anxious about the outcome. If his argument is refuted he becomes downcast. 
Shaken by criticism, he seeks his opponent's weak spots.

_Yutto kathāyaṃ parisāya majjhe pasaṃsamicchaṃ vinighātī hoti +
Apāhatasmiṃ pana maṅku hoti nindāya so kuppati randhamesi._
____

.Illustration
====
nindā

criticism
====

[quote, A.2.188]
____
Eight worldly conditions whirl around the world [of beings], and the world [of 
beings] whirls around eight worldly conditions, namely: acquisition and loss, 
imprestige and prestige, criticism and praise, pleasure and pain.

_aṭṭha lokadhammā lokaṃ anuparivattanti loko ca aṭṭha lokadhamme 
anuparivattati: lābho ca alābho ca ayaso ca yaso ca nindā ca pasaṃsā ca 
sukhañca dukkhañcā ti._
____

