== Nipaka; Nepakka

=== Renderings

- _nipaka_: mindful

- _nipaka_: aware

- _nepakka_: awareness

=== Introduction

==== The problem of nipaka

The meaning of _nipaka_ is unsettled. Translators render it as follows:

- PED: intelligent, clever, prudent, wise.

- Bodhi: worthy (M.3.154).

- Bodhi: alert (A.3.138).

- Norman: zealous (Sn.v.1038; Dh.v.328).

- Horner: intelligent (M.1.340).

- Horner: apt (Vin.1.350).

- Ireland: discerning (It.93).

_Nepakka_ (_nipaka's_ noun) is a quality that a good bhikkhu is keen to develop 
(_satinepakke tibbacchando hoti_, D.3.253). Although 'discernment' would fit 
well here as a quality to strive for, could a bhikkhu be fittingly described as 
eager to develop zeal, or alertness, or intelligence?

==== Not discernment

Developing the quality of _nipaka_ is considered part of ethical conduct, 
together with _sato_ (_sato ca nipako ca. Etadānuttariyaṃ bhante 
purisasīlasamācāre_ D.3.107). This counts against _nipaka_ being 
'discerning,' which is part of penetrative discernment not ethical conduct -- 
although this is somewhat unclear in the scriptures, because of the division 
changes. For example, the _Mahāsīhanāda Sutta_ would place discernment under 
_paññāsampadā_ (D.1.174), and _sato_ not under _sīlasampadā_ (D.1.172), 
but under _cittasampadā_ (D.1.173). But nonetheless, the point is clear: 
however the factors are divided, _nipaka_ is not part of _paññā_, so it is 
not discernment.

==== Nipaka and sati

_Nipaka_ and _nepakka_ are repeatedly linked to _sati_. For example:

- 'There are bhikkhus who are _nipakā nipakavuttino_ who abide with their 
minds well established in the [contemplation of the] four bases of mindfulness' 
(_nipakā nipakavuttino te catusu satipaṭṭhānesu sūpaṭṭhitacittā 
viharanti_ M.1.339). _Nipakā_ is therefore a quality of those who practise 
_satipaṭṭhāna._

- 'A bhikkhu is mindful. He is possessed of paramount mindfulness and 
_nepakka'_ (_bhikkhu satimā hoti paramena satinepakkena samannāgato_ 
D.3.267). Here, _nepakka_ is part of _satimā hoti._

This suggests that _sati_ and _nepakka_ both mean 'mindfulness,' though when 
the words occur together, we call _nepakka_ 'awareness' and _nipaka_ 'aware.'

==== Adjective for conduct

Finding the correct word for _nipaka_ is again challenged where it is used as 
an adjective for 'conduct.' Here, 'mindful' seems the only way to resolve the 
translation:

[quote, M.1.339]
____
There are, Kandaraka, bhikkhus in this community of bhikkhus who are disciples 
in training whose virtue is consistent, whose conduct is consistent, who are 
mindful, whose conduct is mindful. They abide with their minds well established 
in the [contemplation of the] four bases of mindfulness.

_Santi pana kandaraka bhikkhū imasmiṃ bhikkhusaṅghe sekhā santatasīlā 
santatavuttino nipakā nipakavuttino. Te catusu satipaṭṭhānesu 
sūpaṭṭhitacittā viharanti._
____

=== Illustrations

.Illustration
====
nipaka

aware
====

[quote, A.3.138]
____
Come on, friend, abide with sense portals guarded [by mindfulness]. Take 
mindfulness as your supervisor. Be aware and mindful, and have a mind that is 
supervised [by mindfulness], a mind under the supervision of mindfulness.

_Etha tumhe āvuso indriyesu guttadvārā viharatha ārakkhasatino 
nipakkasatino sārakkhitamānasā satārakkhena cetasā samannāgatāti._
____

.Illustration
====
nipako

aware
====

[quote, Th.v.85]
____
One who is proficient [in discerning] the telltale signs of the mind, and who 
knows the sweetness of physical seclusion, being meditative, aware, and 
mindful, can attain unworldly pleasure.

_Cittanimittassa kovido pavivekarasaṃ vijāniya +
Jhāyaṃ nipako patissato adhigaccheyya sukhaṃ nirāmisan ti._
____

.Illustration
====
nipakā

aware
====

[quote, It.39]
____
Those of peaceful minds, who are aware, mindful, and meditative, rightly see 
the nature of reality, and long not for sensuous pleasures.

_Ye santacittā nipakā satimanto ca jhāyino** +
**Sammā dhammaṃ vipassanti kāmesu anapekkhino._
____

.Illustration
====
nipako

aware
====

[quote, Sn.v.1062]
____
Therefore vigorously apply yourself [to the practice]. Be aware and mindful 
right here and now. Having heard my word, train yourself in the quenching of 
the ego.

_Tenahātappaṃ karohi idheva nipako sato +
Ito sutvāna nigghosaṃ sikkhe nibbānamattano._
____

.Illustration
====
nipako

aware
====

[quote, A.3.354]
____
Abandoning the five hindrances, ever energetic, he enters the jhānas. His mind 
is concentrated. He is aware and mindful.

_Pañcanīvaraṇe hitvā niccaṃ āraddhaviriyo +
Jhānāni upasampajja ekodi nipako sato._
____

.Illustration
====
nepakkena

awareness
====

[quote, D.3.267]
____
A bhikkhu is mindful. He is possessed of paramount mindfulness and awareness. 
He recalls and recollects what was done and said long ago.

_Puna ca paraṃ āvuso bhikkhu satimā hoti paramena satinepakkena 
samannāgato cirakatampi cirabhāsitampi saritā anussaritā._
____

.Illustration
====
nepakkena

awareness
====

[quote, D.3.253]
____
In this regard a bhikkhu is keenly eager to develop mindfulness and awareness 
and his dedication to this does not dwindle away in the course of time

_Satinepakke tibbacchando hoti āyatiñca satinepakke avigatapemo._
____

.Illustration
====
nipakassa

mindful
====

[quote, S.1.48]
____
For one whose _āsavas_ are destroyed, who is mindful and meditative, having 
reached the end of birth and death, he does not strain for he has reached the 
Far Shore.

_khīṇāsavassa nipakassa jhāyino +
Pappuyya jātimaraṇassa antaṃ nāyūhati pāragato hi soti._
____

.Illustration
====
nipakaṃ mindful

[quote

Sn.v.45; M.3.154; Dh.v.328; Vin.1.350]
====

____
If one should find a mindful companion, a wise comrade of good disposition, 
then, overcoming all adversities, pleased and mindful, one should live the 
religious life with him.

_Sace labhetha nipakaṃ sahāyaṃ saddhiṃ caraṃ sādhuvihāriṃ 
dhīraṃ +
Abhibhuyya sabbāni parissayāni careyya tenattamano satimā._
____

.Illustration
====
nipako

mindful
====

[quote, Th.v.1081]
____
One who is not vain or puffed up, who is mindful, whose sense faculties are 
restrained [from attraction and repulsion, through mindfulness], looks glorious 
in rag-robes. He is like a lion in a mountain cave.

_Anuddhato acapalo nipako saṃvutindriyo +
Sobhati paṃsukūlena sīho va girigabbhare._
____

.Illustration
====
nipakā

mindful
====

[quote, Sn.v.283; A.4.172]
____
Thus living in unity, being mindful, you will put an end to suffering.

_Tato samaggā nipakā dukkhassantaṃ karissathā ti._
____

.Illustration
====
nipakā

mindful
====

[quote, M.1.339]
____
There are, Kandaraka, bhikkhus in this community of bhikkhus who are disciples 
in training whose virtue is consistent, whose conduct is consistent, who are 
mindful, whose conduct is mindful. They abide with their minds well established 
in the [contemplation of the] four bases of mindfulness.

_Santi pana kandaraka bhikkhū imasmiṃ bhikkhusaṅghe sekhā santatasīlā 
santatavuttino nipakā nipakavuttino. Te catusu satipaṭṭhānesu 
sūpaṭṭhitacittā viharanti._
____

