== Nirodha

=== Renderings

- _nirodha_: ending

- _nirodha_: ending [of originated phenomena]

- _nirodhāya_: to put an end to

- _niruddho hoti_: is ended

- _nirujjhati_: to cease

- _nirodheti_: to put an end to, to be stopped

- _nirodhiko_: destructive

=== Introduction

==== Nirodha: ending not cessation

PED says _nirodha_ 'is synonymous with _nibbāna_ and _parinibbāna_; it may be 
said to be even a stronger expression as far as the active destruction of the 
causes of life is concerned.' _Nirodha_ is therefore better represented in 
'ending' than 'cessation,' though some translators prefer to call it 'stopping':

[quote, Horner, M.1.9]
____
This is the stopping of anguish.

_ayaṃ dukkhanirodho ti._
____

[quote, Norman, Sn.p.140]
____
This is the stopping of misery

_ayaṃ dukkhanirodho._
____

==== Nirodho plus named object

_Nirodha_ always means the ending of something; it never means just 'ending.' 
This is most obvious, of course, when it has a named object. For example, the 
_Rahogata Sutta_ describes the 'successive ending of originated phenomena,' 
calling it _anupubbasaṅkhārānaṃ nirodho_:

____
The successive ending of originated phenomena is explained by me.

_mayā anupubbasaṅkhārānaṃ nirodho akkhāto_
____

____
... For one who attains first jhāna, speech is ended.

_paṭhamaṃ jhānaṃ samāpannassa vācā niruddhā hoti_
____

____
... For one who attains second jhāna, thinking and pondering are ended...

_dutiyaṃ jhānaṃ samāpannassa vitakkavicārā niruddhā honti..._
____

____
... For one who attains the ending of perception and sense impression, 
perception and sense impression are ended.

_saññāvedayitanirodhaṃ samāpannassa saññā ca vedanā ca niruddhā 
honti_
____

[quote, _Rahogata Sutta,_ S.4.217]
____
... For a bhikkhu whose _āsavas_ are destroyed, attachment, hatred, and 
undiscernment of reality are ended.

_Khīṇāsavassa bhikkhuno rāgo niruddho hoti doso niruddho hoti moho 
niruddho hoti._
____

==== Nirodho means 'ending of the five aggregates'

Sometimes _nirodha_ occurs without a named object. This has always been 
perplexing, because it once led Venerable Ānanda to question the Buddha on the 
matter:

____
-- 'Bhante, it is said, 'Ending, ending.' Through the ending of what things is 
ending spoken of?'

_Nirodho nirodho ti bhante vuccati katamesānaṃ kho bhante dhammānaṃ 
nirodhā nirodho ti vuccatī ti?_
____

____
-- 'Bodily form, Ānanda, is unlasting, originated, and dependently arisen. It 
is destined to be destroyed, to disappear, to pass away, to cease. Through its 
ending, ending is spoken of.

_Rūpaṃ kho ānanda aniccaṃ saṅkhataṃ paṭiccasamuppannaṃ 
khayadhammaṃ vayadhammaṃ virāgadhammaṃ nirodhadhammaṃ. Tassa nirodhā 
nirodho ti vuccati_
____

The same is said about the other aggregates, and the sutta concludes:

[quote, S.3.24]
____
-- 'It is through the ending of these things, Ānanda, that ending is spoken 
of.'

_Imesaṃ kho ānanda dhammānaṃ nirodho nirodho ti vuccatī ti._
____

Thus if _nirodha_ has no designated object, then this sutta says the five 
aggregates are the object. Other suttas support this principle, though in 
slightly different terms, as we will see.

==== Nirodho means 'ending of originated phenomena'

The _Anupubbanirodha Sutta_ (A.4.456) describes the same steps as the _Rahogata 
Sutta_, but calls it _anupubbanirodho_ not _anupubbasaṅkhārānaṃ nirodho_, 
where _nirodha_ (ending) is therefore an abbreviation for _saṅkhārānaṃ 
nirodha_ (ending of originated phenomena). The conclusion to the sutta should 
therefore be parenthesised accordingly:

[quote, A.4.456]
____
It is in reference to this that the successive ending [of originated phenomena] 
is spoken of by the Blessed One.

_Ettāvatā pi kho āvuso anupubbanirodho vuttā bhagavatā._
____

==== Nirodho means 'ending of perception and sense impression'

The _Sattadhātu Sutta_ (S.2.151) links _nirodha_ to 'ending of perception and 
sense impression'. Because this is likewise the final step in the _Rahogata 
Sutta_, we can be sure that _nirodha_ again means the ending of originated 
phenomena:

[quote, _Sattadhātu Sutta,_ S.2.151]
____
The phenomenon of the ending of perception and sense impression is a phenomenon 
attained with the ending [of originated phenomena].

_yāyaṃ bhikkhu saññāvedayitanirodhadhātu ayaṃ dhātu nirodhaṃ 
paṭicca paññāyatī ti._
____

Thus although unnamed objects of _nirodha_ can be explained differently, for 
example as the five aggregates, or as originated phenomena, the scriptures 
consistently agree that _nirodha_ always has an object, and is never simply 
'ending.'

==== Step-by-step ending, and continuous ending

When the _Rahogata Sutta_ describes the 'successive ending of originated 
phenomena,' it is step-by-step ending:

• For one who attains first jhāna, speech is ended. For one who attains 
second jhāna, thinking and pondering are ended. +
☸ _paṭhamaṃ jhānaṃ samāpannassa vācā niruddhā hoti dutiyaṃ 
jhānaṃ samāpannassa vitakkavicārā niruddhā honti_... (_Rahogata Sutta,_ 
S.4.217).

But _nirodha_ can also mean ending as a continuous process:

[quote, A.4.146]
____
In this regard, some person in relation to the visual sense abides 
contemplating ending, perceiving ending, experiencing ending continuously, 
without a break, uninterruptedly, intent upon it mentally, penetrating it with 
penetrative discernment

_idha bhikkhave ekacco puggalo cakkhusmiṃ nirodhānupassī viharati 
nirodhasaññī nirodhapaṭisaṃvedī satataṃ samitaṃ abbokiṇṇaṃ 
cetasā adhimuccamāno paññāya pariyogāhamāno._
____

==== The goal of practice: ending

Where _nirodha_ is the goal of one's practice, _nibbida_ is often included in 
the formula, as follows:

[quote, S.4.4]
____
The noble disciple is indifferent to the visual sense of the past, he does not 
long for the visual sense of the future, he applies himself to disillusionment 
with the visual sense of the present, to non-attachment to it, and to the 
ending of it.

_sutavā ariyasāvako atītasmiṃ cakkhusmiṃ anapekkho hoti; anāgataṃ 
cakkhuṃ nābhinandati paccappannassa cakkhussa nibbidāya virāgāya 
nirodhāya paṭipanno hoti._
____

[quote, It.44]
____
Devas and men find enjoyment, pleasure, and satisfaction in individual 
existence. When the teaching is taught to them to put an end to individual 
existence, their minds do not become energised, serene, settled, and intent 
upon it.

_bhavārāmā bhikkhave devamanussā bhavaratā bhavasammuditā. Tesaṃ 
bhavanirodhāya dhamme desiyamāne na cittaṃ pakkhandati na pasīdati na 
santiṭṭhati nādhimuccati._
____

==== Practising for the ending of objects

The idea of practising for the ending of objects is shown in the following two 
quotes to involve not delighting (_anabhinanditāni_):

1. Just as an oil lamp burns because of oil and a wick, and with the exhaustion 
of the oil and wick it is extinguished through lack of fuel, so too, 
bhikkhus... a bhikkhu knows that with the demise of the body, and with the 
ending of life, all sense impression being not delighted in will be dissipated 
right here in this world.
+
****
_Seyyathā pi bhikkhave telañca paṭicca vaṭṭiñca paṭicca telappadīpo 
jhāyeyya tasseva telassa ca vaṭṭiyā ca pariyādānā anāhāro 
nibbāyeyya; evameva kho bhikkhave bhikkhu... kāyassa bhedā uddhaṃ 
jīvitapariyādānā idheva sabbavedayitāni anabhinanditāti 
sītibhavissantīti pajānātī' ti_ (S.4.213-4).
****

2. And what is the vanishing of bodily form... of advertence?
+
****
_rūpassa atthaṅgamo... viññāṇassa atthaṅgamo_
****

[quote, S.3.13-15]
____
In this regard, one does not take delight in, welcome, or persist in cleaving.

_Idha bhikkhave bhikkhu nābhinandati nābhivadati nājjhosāya tiṭṭhati._
____

==== Ablative nirodhā: 'from' or 'with'

The ablative _nirodhā_ occurs in the reverse sequence of _paṭiccasamuppāda_ 
(called _paṭiloma_ at Ud.2). The Ablative shows motive, cause, reason, and 
can be translated by 'for,' 'on account of,' 'by reason of,' 'through' (PGPL, 
600 xi). We render it as 'with.' For example:

[quote, S.2.8-9]
____
With (=on account of) the ending of birth comes the ending of old age and death.

_Jātinirodhā jarāmaraṇanirodho ti._
____

[quote, S.2.48]
____
With (=on account of) the ending of nourishment, what is brought about is 
destined to cease

_Tadāhāranirodhā yaṃ bhūtaṃ taṃ nirodhadhamman ti._
____

==== Ablative nirodhā: 'to put an end to'

The ablative 'shows motive, cause, reason,' says Duroiselle (para 600, xi), 
therefore _nirodhā/nirodhāya_ can mean 'to put an end to.' For example:

[quote, Thī.v.458]
____
To put an end to craving for states of individual existence, allow me to go 
forth [into the ascetic life].

_Bhavataṇhāya nirodhā anujānātha pabbajissāmi._
____

[quote, A.1.100]
____
To put an end to attachment, two things should be developed. Which two? Inward 
calm and insightfulness.

_Rāgassa bhikkhave nirodhāya dve dhammā bhāvetabbā. Katame dve? Samatho ca 
vipassanā ca._
____

Other examples are given below.

=== Illustrations

.Illustration
====
nirodhāya

to put an end to
====

[quote, A.3.416]
____
A person overpowered and overcome by suffering roams abroad in search of 
someone who knows a spell or two to put an end to this suffering

_dukkhena abhibhūto pariyādinna citto bahiddhā pariyeṭṭhiṃ ājjati ko 
ekapadaṃ dipadaṃ pajānāti imassa dukkhassa nirodhāyā ti._
____

.Illustration
====
nirodhāya

to put an end to
====

[quote, M.1.435]
____
While the teaching is being explained to someone to put an end to personal 
identity...

_yassa kassaci sakkāya nirodhāya dhamme desiyamāne._
____

.Illustration
====
nirodhāya

to put an end to
====

[quote, M.2.28]
____
And applying himself in what way, carpenter, is he doing so to put an end to 
spiritually unwholesome thoughts?

_Kathaṃ paṭipanno ca thapati akusalānaṃ saṅkappānaṃ nirodhāya 
paṭipanno hoti._
____

.Illustration
====
nirujjhanti

cease; nirodhetvā, to put an end to
====

[quote, A.4.410]
____
Where sensuous pleasures cease, and those who have put an end to sensuous 
pleasures abide, surely those Venerables are free of craving. They have 
realised the Untroubled.

_Yattha kāmā nirujjhanti ye ca kāme nirodhetvā nirodhetvā viharanti addhā 
te āyasmanto nicchātā nibbutā._
____

.Illustration
====
nirodhetabbaṃ

to be stopped
====

[quote, S.4.298]
____
One who thinks that thinking and pondering can be stopped might as well think 
he could catch the wind in a net, or arrest the flow of the river Ganges with 
his fist.

_vātaṃ vā so jālena bādhetabbaṃ maññeyya yo vitakkavicāre 
nirodhetabbaṃ maññeyya sakamuṭṭhinā vā so gaṅgāya sotaṃ 
āvāretabbaṃ maññeyyāti._
____

.Illustration
====
nirodhāya

ending
====

• This is called a bhikkhu who is applying himself to the complete 
destruction of suffering, and to the ending of old age and death. +
_Ayaṃ vuccati bhikkhave bhikkhu sabbaso sammā dukkhakkhayāya paṭipanno 
hoti jarāmaraṇanirodhāya_ (S.2.81).

.Illustration
====
nirodho

ending
====

• With the ending of sense impression comes the ending of craving. +
_vedanānirodhā taṇhānirodho ti_ (D.2.34).

.Illustration
====
nirodho

ending
====

[quote, S.2.8-9]
____
With the ending of birth comes the ending of old age and death.

_Jātinirodhā jarāmaraṇanirodho ti._
____

.Illustration
====
nirodho

ending
====

[quote, A.5.9]
____
The ending of individual existence is the Untroubled.

_Bhavanirodho nibbānaṃ._
____

.Illustration
====
nirodha

ending
====

• This is the practice leading to the ending of personal identity * +
☸* _Ayaṃ kho pana bhikkhave sakkāya nirodhagāminī paṭipadā_ (M.3.284).

.Illustration
====
nirodho

ending of originated phenomena; niruddhā hoti, is ended
====

____
Ānanda, I have taught the successive ending of originated phenomena.

_anupubbasaṅkhārānaṃ nirodho akkhāto_
____

For one who attains:

____
first jhāna, speech is ended.

_vācā niruddhā hoti_
____

____
second jhāna, thinking and pondering are ended.

_vitakkavicārā niruddhā honti_
____

____
third jhāna, rapture is ended.

_pīti niruddhā hoti_
____

____
fourth jhāna, breathing is ended.

_assāsapassāsā niruddhā honti_
____

____
the state of awareness of boundless space, the perception of the refined 
material states of awareness is ended.

_rūpasaññā niruddhā hoti_
____

____
the state of awareness of boundless mental consciousness, the perception of the 
state of awareness of boundless space is ended.

__ākāsānañcāyatanasaññā niruddhā hoti_
____

____
the state of awareness of nonexistence, the state of awareness of boundless 
mental consciousness is ended.

_viññāṇañcāyatanasaññā niruddhā hoti_
____

____
the ending of perception and sense impression, perception and sense impression 
are ended.

_saññā ca vedanā ca niruddhā honti_
____

[quote, S.4.217]
____
For a bhikkhu whose _āsavas_ are destroyed, attachment, hatred, and 
undiscernment of reality are ended.

_khīṇāsavassa bhikkhuno rāgo niruddho hoti doso niruddho hoti moho 
niruddho hoti._
____

.Illustration
====
nirodho

ending [of originated phenomena]
====

____
The three phenomena leading to deliverance.

_tisso nissaraṇiyā dhātuyo_
____

____
The deliverance from sensuous pleasure, namely the practice of unsensuousness.

_kāmānametaṃ nissaraṇaṃ yadidaṃ nekkhammaṃ_
____

____
The deliverance from refined material states of awareness, namely immaterial 
states of awareness.

_rūpānametaṃ nissaraṇaṃ yadidaṃ āruppaṃ_
____

[quote, D.3.275]
____
from whatever is brought about, originated, dependently arisen, the ending [of 
originated phenomena] is the deliverance.

_yaṃ kho pana kiñci bhūtaṃ saṅkhataṃ paṭiccasamuppannaṃ nirodho 
tassa nissaraṇaṃ. Ime tayo dhammā duppaṭivijjhā._
____

.Illustration
====
nirodhaṃ

ending [of originated phenomena]
====

____
Those beings who have reached the refined material plane of existence and those 
living in the immaterial plane of existence, if they do not discern the ending 
&#8203;[of originated phenomena] they [continue to] come back to renewed states of 
individual existence.

_ye ca rūpūpagā sattā ye ca āruppavāsino +
nirodhaṃ appajānantā āgantāro punabbhavaṃ._
____

[quote, It.62]
____
Those who profoundly understand the refined material states of awareness and 
are not stuck in the immaterial states of awareness, with the ending [of 
originated phenomena], they are liberated [from perceptually obscuring states] 
and abandon death.

_ye ca rūpe pariññāya arūpesu asaṇṭhitā +
nirodhe ye vimuccanti te janā maccuhāyino ti._
____

.Illustration
====
nirodha

ending [of originated phenomena]
====

____
And what, Ānanda, is the perception of the ending [of originated phenomena]?

_nirodhasaññā_
____

In this regard, Ānanda, a bhikkhu having gone to the wilderness, or the root 
of a tree, or a solitary abode, contemplates thus:

____
'This is peaceful, this is sublime, namely:

_etaṃ santaṃ etaṃ paṇītaṃ yadidaṃ_
____

____
the quelling of all originated phenomena

_sabbasaṅkhārasamatho_
____

____
relinquishment of the whole phenomenon of attachment

_sabbūpadhipaṭinissaggo_
____

____
the destruction of craving,

_taṇhakkhayo_
____

____
the ending [of originated phenomena],

_nirodho_
____

[quote, A.5.110]
____
the Untroubled.'

_nibbānan ti._
____

.Illustration
====
nirodhaṃ ending; cease

nirujjhati
====

____
-- Therefore that supreme state of deliverance should be known

_se āyatane veditabbe_
____

____
where the visual sense ceases and perception of visible objects passes away.

_yattha cakkhuñca nirujjhati rūpasaññā ca virajjati_
____

where the auditory sense ceases and perception of audible objects passes away...

• where the mental sense ceases and perception of mentally known objects 
passes away . +
_☸... yattha mano ca nirujjhati dhammasaññā ca virajjati se āyatane 
veditabbeti_

Venerable Ānanda:

[quote, S.4.98]
____
-- This was stated by the Blessed One, friends, with reference to the ending of 
the six senses.

_Saḷāyatananirodhaṃ no etaṃ āvuso bhagavatā sandhāya bhāsita._
____

Comment:

_Saḷāyatananirodhaṃ_ means _nibbāna_ at A.2.161-2 (_channaṃ āvuso 
phassāyatanānaṃ asesavirāganirodhā papañcanirodho_). Venerable Ānanda 
indicates it has the same meaning here. This justifies us calling _āyatane_ 
'that supreme state of deliverance.'

Comment:

_Se āyatane_ is an Eastern form of Pāli. Discussed by Bodhi: CDB p.1414 
n.102).

.Illustration
====
nirodhā

ending
====

• He abides contemplating unlastingness in relation to the body and pleasant 
sense impression +
_so kāye ca sukhāya ca vedanāya aniccānupassī viharati_

____
their disappearance

_vayānupassī viharati_
____

____
their passing away

_virāgānupassī viharati_
____

• their ending * +
☸* _nirodhānupassī viharati_

[quote, S.4.211]
____
their relinquishment

_paṭinissaggānupassī viharati._
____

.Illustration
====
nirodha

ending
====

[quote, M.3.265]
____
Sāriputta, friend, it is through seeing and fully understanding the ending of 
the visual sense, advertence to the visual field, and things known through 
advertence to the visual field, that I regard these things as "not [in reality] 
mine," "not [in reality] what I am," "not my [absolute] Selfhood."'

_Cakkhusmiṃ āvuso sāriputta cakkhuviññāṇe 
cakkhuviññāṇaviññātabbesu dhammesu nirodhaṃ disvā nirodhaṃ 
abhiññāya cakkhuṃ cakkhuviññāṇaṃ cakkhuviññāṇaviññātabbe 
dhamme n'etaṃ mama n'eso'hamasmi na me so attā ti samanupassāmi._
____

.Illustration
====
nirodha

ending
====

I will breathe in... I will breathe out contemplating

____
unlastingness [in relation to certain objects of the systematic teachings]

_aniccānupassī assasissāmī ti sikkhati_
____

• passing away [in relation to certain objects of the systematic teachings] +
☸ virāgā__nupassī assasissāmī ti sikkhati__

____
ending [in relation to certain objects of the systematic teachings]

_nirodhānupassī assasissāmī ti sikkhati_
____

____
relinquishment [in relation to certain objects of the systematic teachings]

_paṭinissaggānupassī assasissāmī ti sikkhati_
____

.Illustration
====
nirodhaṃ

ending
====

____
For one who sees the origination of the world [of phenomena] according to 
reality with perfect penetrative discernment

_lokasamudayañca kho kaccāna yathābhūtaṃ sammappaññāya passato_
____

____
there is no view of nonexistence in regards to the world [of phenomena]_

_yā loke natthitā sā na hoti._
____

____
And for one who sees the ending of the world [of phenomena] according to 
reality with perfect penetrative discernment

_lokanirodhaṃ kho kaccāna yathābhūtaṃ sammappaññāya passato_
____

[quote, S.2.17]
____
there is no view of existence in regards to the world [of phenomena]_

_yā loke atthitā sā na hoti._
____

.Illustration
====
nirodhāya

ending
====

[quote, S.4.4]
____
The noble disciple is indifferent to the visual sense of the past, he does not 
long for the visual sense of the future, he applies himself to disillusionment 
with the visual sense of the present, to non-attachment to it, and to the 
ending of it.

_sutavā ariyasāvako atītasmiṃ cakkhusmiṃ anapekkho hoti; anāgataṃ 
cakkhuṃ nābhinandati paccappannassa cakkhussa nibbidāya virāgāya 
nirodhāya paṭipanno hoti._
____

.Illustration
====
nirodhāya

ending
====

[quote, A.2.177]
____
He is applied to the practice of disillusionment with states of individual 
existence, to non-attachment to states of individual existence, and to the 
ending of states of individual existence.

_bhavānaṃ yeva nibbidāya virāgāya nirodhāya paṭipanno hoti._
____

.Illustration
====
nirodhāya

ending
====

[quote, S.3.60]
____
They are applying themselves to disillusionment with sense impression, to 
non-attachment to it, and to the ending of it

_vedanāya nibbidāya virāgāya nirodhāya paṭipannā._
____

.Illustration
====
nirodhāya

ending
====

____
All states of individual existence are unlasting, existentially void, destined 
to change.

_sabbe bhavā aniccā dukkhā vipariṇāmadhammā ti._
____

[quote, A.2.176-7]
____
In fully understanding the truth of this saying one is applying oneself to 
disillusionment with states of individual existence, to non-attachment to 
states of individual existence, and to the ending of states of individual 
existence

_Api ca yadeva tattha saccaṃ tadabhiññāya bhavānaṃ yeva nibbidāya 
virāgāya nirodhāya paṭipanno hoti._
____

.Illustration
====
nirodhāya

ending
====

[quote, S.2.18]
____
If a bhikkhu is applying himself to disillusionment with old age and death, to 
non-attachment to it, and to the ending of it, he is fit to be called a bhikkhu 
who is practising in accordance with the teaching.

_Jarāmaraṇassa ce bhikkhu nibbidāya virāgāya nirodhāya paṭipanno hoti 
dhammānudhammapaṭipanno bhikkhū ti alaṃ vacanāya._
____

.Illustration
====
nirodha

ending [of originated phenomena]
====

[quote, M.1.11]
____
In this regard a bhikkhu, properly reflecting, develops the enlightenment 
factor of mindfulness which conduces to seclusion [from sensuous pleasures and 
spiritually unwholesome factors], to non-attachment [to originated phenomena], 
to the ending [of originated phenomena], and which results in the 
relinquishment [of the whole phenomenon of attachment].

_Idha bhikkhave bhikkhu paṭisaṅkhā yoniso satisambojjhaṅgaṃ bhāveti 
vivekanissitaṃ virāganissitaṃ nirodhanissitaṃ vossaggapariṇāmiṃ._
____

.Illustration
====
nirodhāya

the ending [of originated phenomena]
====

[quote, D.2.285]
____
Bhante, whatever pleasure and joy is due to blows and wounds does not conduce 
to disillusionment [with originated phenomena], to non-attachment [to 
originated phenomena], to the ending [of originated phenomena], to inward 
peace, to transcendent insight, to enlightenment, nor to the Untroubled.

_So kho me bhante vedapaṭilābho somanassapaṭilābho sadaṇḍāvacaro 
sasatthāvacaro na nibbidāya na virāgāya na nirodhāya na upasamāya na 
abhiññāya na sambodhāya na nibbānāya saṃvattati._
____

.Illustration
====
nirujjhati

ceases
====

____
Heat is generated and fire manifests from the rubbing together of two 
fire-sticks,

_usmā jāyati tejo abhinibbattati._
____

[quote, S.5.212]
____
but when the sticks are separated and laid aside the heat ceases and subsides;

_yā tajjā usmā sā nirujjhati sā vūpasammati._
____

.Illustration
====
nirujjhati

ceases
====

[quote, A.5.9]
____
Just as with a little twig fire, one flame arises and another ceases,

_seyyathā pi āvuso sakalikaggissa jhāyamānassa aññāva acci uppajjati 
aññāva acci nirujjhati._
____

.Illustration
====
niruddho hoti

is ended
====

[quote, S.4.217]
____
For a bhikkhu whose _āsavas_ are destroyed, attachment is ended, hatred is 
ended, undiscernment of reality is ended.

_khīṇāsavassa bhikkhuno rāgo niruddho hoti doso niruddho hoti moho 
niruddho hoti._
____

.Illustration
====
nirodhiko

destructive
====

[quote, A.1.216-7]
____
Attachment produces spiritual blindness, uninsightfulness, ignorance [of things 
according to reality], is destructive of penetrative discernment, vexatious, 
and not conducive to the Untroubled.

_Rāgo kho āvuso andhakaraṇo acakkhukaraṇo aññāṇakaraṇo 
paññānirodhiko vighātapakkhiko anibbānasaṃvattaniko._
____

