== Nissaya; Nissāya; Nissita

=== Renderings

==== Renderings: nissaya

- _nissaya_: rich resources

- _nissaya_: spiritual resources

- _nissaya_: formal spiritual support

- _nissaya_: state of attachment

- _nissayaṃ karoti_: to be attached

- _nissayatā_: attachment

==== Renderings: upanissaya

- _upanissaya_: basic resource

- _upanissaya_: necessary condition

- _upanissaya_: spiritual support

==== Renderings: diṭṭhinissaya

- _diṭṭhinissaya_: view

==== Renderings: nissāya

- _nissāya_: beside

- _nissāya_: in

- _nissāya_: near

- _nissāya_: upon

- _nissāya nissāya_: right next to

- _nissāya_: relying on

- _nissāya_: with the support of

- _nissāya_: with the help of

- _nissāya_: helped by (= 'out of')

- _nissāya nissāya_: by one support or another

- _nissāya_: based on

- _nissāya_: dependent upon

- _nissāya_: for the sake of

- _nissāya_: formal discipleship under a teacher

- _yaṃ nissāya_: by reason of which

==== Renderings: upanissāya

- _upanissāya_: in

- _upanissāya_: near

- _upanissāya_: nearby

- _upanissāya_: beside

- _upanissāya_: in and around

- _upanissāya_: spiritually supported by

- _upanissāya_: spiritually relying on

- _upanissāya_: physically relying on

- _upanissāya_: in spiritual discipleship under

- _upanissāya_: dependent on

==== Renderings: nissita

- _nissita_: embedded

- _nissita_: immersed

- _nissita_: conduces to

- _nissita_: on account of

- _nissita_: supported by

- _nissita_: rely on

- _nissita_: associated with

- _nissita_: bound up with

- _nissita_: based on

- _nissita_: attached

- _kiṃ nissitā_: for what reason

==== Renderings: upanissita

- _upanissitā_: attached

=== Introduction

==== Diṭṭhinissaya means diṭṭhi

PED says _diṭṭhinissaya_ means 'the foundation of speculation.' But the 
scriptures treat _diṭṭhinissaya_ as a synonym of _diṭṭhi_. For example, 
in this passage _nānādiṭṭhi_ (in _nānādiṭṭhikā_) is synonymous 
with _nānādiṭṭhinissaya_:

[quote, Ud.67]
____
At that time there were a number of non-Buddhist ascetics living around 
Sāvatthī. And they were of various dogmatic views, various persuasions, 
various inclinations, attached to various dogmatic views... '

_nānādiṭṭhikā nānākhantikā nānārucikā 
nānādiṭṭhinissayanissitā._
____

Similarly, in the next passage, when the Buddha asked what are the 
_diṭṭhinissayā_ about the past, he answered in terms of doctrines and 
views (_evaṃ vādino evaṃ diṭṭhino_), as if in English one might answer 
a question about viewpoints in terms of views. The passage is this:

[quote, D.3.137]
____
Cunda, what are those views connected with the past that I have explained to 
you as they should be explained? There are certain ascetics and Brahmanists 
whose doctrine and dogmatic view is this: 'The _attā_ and _loko_ are eternal; 
this alone is true, all else is false.'

_Katame ca te cunda pubbantasahagatā diṭṭhinissayā ye vo mayā vyākatā 
yathā te vyākātabbā? Santi kho cunda eke samaṇabrāhmaṇā evaṃ 
vādino evaṃ diṭṭhino sassato attā ca loko ca idameva saccaṃ 
moghamaññan ti._
____

==== Other translators

Some translators render _diṭṭhinissaya_ as 'dependence on view' or 'support 
of views,' with convoluted results. For instance, consider this passage:

____
-- 'Bhikkhus, you might best rely on that dogmatic view, relying on which there 
would not arise grief, lamentation, physical pain, psychological pain, and 
vexation. But do you see any such view?'

_Taṃ bhikkhave diṭṭhinissayaṃ nisseyyātha yaṃsa diṭṭhinissayaṃ 
nissayato na uppajjeyyuṃ sokaparidevadukkhadomanassupāyāsā. Passatha no 
tumhe bhikkhave taṃ diṭṭhinissayaṃ yaṃsa diṭṭhinissayaṃ 
nissayato na uppajjeyyuṃ sokaparidevadukkhadomanassupāyāsā ti._
____

____
-- 'No, bhante.'

_No hetaṃ bhante_
____

[quote, M.1.137-8]
____
-- 'Good, bhikkhus. I also see no such view relying on which there would not 
arise grief, lamentation, physical pain, psychological pain, and vexation.'

_Sādhu bhikkhave. Ahampi kho taṃ bhikkhave diṭṭhinissayaṃ na 
samanupassāmi yaṃsa diṭṭhinissayaṃ nissayato na uppajjeyyuṃ 
sokaparidevadukkhadomanassupāyāsā._
____

Horner translates the last sentence as: 'Neither do I see that dependence on 
view by depending on which dependence of view there would not arise grief, 
suffering, anguish, lamentation, despair' (MLS.1.177).

==== Pitfalls

The negatives of the _nissaya nissāya nissita_ group are associated with a 
range of pitfalls. For instance, _issita_ means 'giving offence.' Its negative 
is _anissita_ (i.e. '_an-issita'_ not '_a-nissita'_):

[quote, S.4.179]
____
Not causing offence, not tormenting others, one who has realised the 
Untroubled, a bhikkhu would not abuse anyone.

_Anissito aññamaheṭhayāno parinibbuto na upavadeyya kañciti._
____

The following passage has been quietly misleading us for centuries:

[quote, S.2.280; A.2.51]
____
Venerable Visākha was instructing the bhikkhus with speech that was polished, 
well enunciated, articulate, making the meaning clear, comprehensive, not 
causing offence.

_poriyā vācāya vissaṭṭhāya anelagalāya atthassa viññāpaniyā 
pariyāpannāya anissitāyā ti._
____

However, Buddhaghosa's commentary says the speech was 'unattached to the round 
of rebirth' (_vaṭṭaṃ anissitāya_) (PTS: AA.3.90). Another translator 
simply says the bhikkhu's speech was 'unattached.'

The correct root of a negative is easier to recognise when paired with its 
positive. For instance, if '_issāya'_ means 'of envy,' _anissāya_ clearly 
means 'of non-envy' (_an-issāya_). For example, here:

____
Possessed of two qualities one lives miserably: envy and stinginess.

_issāya ca macchariyena ca_
____

[quote, A.1.94]
____
Possessed of two qualities one lives happily: non-envy and non-stinginess.

_anissāya ca amacchariyena ca._
____

==== Humour

_Nissita's_ different meanings make it an easy source of humour. For instance 
the Buddha said that Brahmanists and householders are helpful in providing 
bhikkhus with robe material, almsfood, abodes, and therapeutic requisites; and 
bhikkhus are helpful in return by explaining the teaching. He said householders 
and ascetics are each supported by the other (_aññoññanissitā_ It.111). A 
bhikkhu preacher might well remind his audience that this does not mean 
householders and ascetics are 'each attached to each other' 
(_aññoññanissitā_) but instead they both should try to 'each not give 
offence to each other' (_aññoññanissitā_).

=== Illustrations: nissaya

.Illustration
====
nissaya

rich resources
====

____
And how is a shopkeeper endowed with rich resources?_

_Kathañca bhikkhave pāpaṇiko nissayasampanno hoti_
____

The shopkeeper becomes known to wealthy householders as capable of providing 
interest on loans. They offer him money, telling him to trade with it, support 
his family, and pay it back with interest in due course (A.1.117).

.Illustration
====
nissaya

rich resources
====

____
And how is a bhikkhu endowed with rich resources?

_Kathañca bhikkhave bhikkhu nissayasampanno hoti:_
____

From time to time a bhikkhu approaches those bhikkhus who are learned, to whom 
the tradition has been handed down, experts in the teaching and discipline and 
summaries, and asks and interrogates them 'How is that, bhante? What does that 
mean?' Thus those Venerables can reveal what is hidden and clarify what is 
obscure, and dispel his unsureness about various matters that are cause for 
unsureness (A.1.118).

.Illustration
====
nissaya

spiritual resources
====

____
On what grounds, bhante, is a bhikkhu endowed with spiritual resources?

_Kittāvatā nu kho bhante bhikkhu nissayasampanno hotī ti._
____

____
If, either with the help of faith [in the perfection of the Buddha's 
transcendent insight], or with the help of shame of wrongdoing, or with the 
help of fear of wrongdoing, or with the help of energetic application [to the 
practice], or with the help of wisdom, a bhikkhu abandons what is spiritually 
unwholesome and develops what is spiritually wholesome, that which is 
spiritually unwholesome is indeed abandoned.

_saddhañce... hiriñce... ottappañce... viriyañce... paññañce bhikkhu 
bhikkhu nissāya akusalaṃ pajahati kusalaṃ bhāveti pahīnamevassa taṃ 
akusalaṃ hoti._
____

____
When he is established (_patiṭṭhāya_) in these five states, there are four 
other things spiritually supported by which a bhikkhu should abide

_cattāro dhammā upanissāya vihātabbā._
____

In this regard a bhikkhu judges that:

____
one thing should be followed.

_saṅkhāyekaṃ paṭisevati_
____

____
one thing should be endured.

_saṅkhāyekaṃ adhivāseti_
____

____
one thing should be avoided.

_saṅkhāyekaṃ parivajjeti_
____

____
one thing should be dispelled.

_saṅkhāyekaṃ vinodeti_
____

[quote, A.4.353-4]
____
Thus is a bhikkhu endowed with spiritual resources.

_nissayasampanno hotī ti._
____

.Illustration
====
nissayaṃ

formal spiritual support
====

[quote, M.2.126]
____
In the eighty years since I went forth [into the ascetic life], I do not recall 
having ever offered anyone formal spiritual support.

_Asīti me āvuso vassāni pabbajitassa nābhijānāmi nissayaṃ dātā._
____

.Illustration
====
nissayaṃ

formal spiritual support
====

____
Ānanda, friend, the Blessed One has established a standard of ten years formal 
discipleship under a teacher.

_bhagavatā āvuso ānanda paññattaṃ dasavassāni nissāya vatthuṃ_
____

[quote, Vin.1.80]
____
One of ten years' standing can offer formal spiritual support.

_dasavassena nissayaṃ dātuṃ._
____

.Illustration
====
nissayo

formal spiritual support
====

____
If he is possessed of five factors, formal spiritual support may be offered by 
a bhikkhu.

_bhikkhunā nissayo dātabbo_
____

[quote, A.3.271]
____
If he is possessed of the aggregate of a finished disciple's virtuous 
practices, inward collectedness, penetrative discernment, liberation [from 
perceptually obscuring states], and the knowledge and vision that follows 
liberation [from perceptually obscuring states].

_asekhena sīlakkhandhena... samādhikkhandhena... paññākkhandhena... 
vimuttikkhandhena... vimuttiñāṇadassanakkhandhena samannāgato hoti._
____

.Illustration
====
nissayaṃ karoti

be attached
====

____
Having abandoned whatever he was clinging to

_attaṃ pahāya_
____

____
being free of grasping

_anupādiyāno_
____

[quote, Sn.v.800]
____
He is not attached even to knowledge.

__ñāṇe pi so nissayaṃ no karoti._
____

Comment:

Norman says 'he should not depend even upon knowledge.' But how can one not 
depend on knowledge?

.Illustration
====
nissayatā

attachment
====

[quote, Sn.v.856]
____
A person for whom there is no attachment, who, knowing the nature of reality 
&#8203;[according to reality], is not attached; and who has no craving for either 
individual existence or the cessation of individual existence.

_Yassa nissayatā natthi ñatvā dhammaṃ anissito +
Bhavāya vibhavāya vā taṇhā yassa na vijjati._
____

[quote, Sn.v.857]
____
This is someone I call inwardly at peace. He is indifferent to sensuous 
pleasures. Spiritual shackles are not found in him. He has overcome attachment 
&#8203;[to the world of phenomena].

_Taṃ brūmi upasanto ti kāmesu anapekkhinaṃ +
Ganthā tassa na vijjanti atāri so visattikaṃ._
____

Comment:

Norman says 'no stage of dependence, knowing the doctrine is not dependent.'

.Illustration
====
nissayesu

states of attachment
====

____
One who is free of attachment does not tremble.

_Anissito na calati_
____

____
But one who is attached,

_nissito ca_
____

____
Grasping states of individual existence in this world or another

_upādiyaṃ itthabhāvaññathābhāvaṃ_
____

____
Does not transcend the round of birth and death.

_saṃsāraṃ nātivattati_
____

____
Recognising this danger,

_Etamādīnavaṃ ñatvā_
____

____
That there is great peril in states of attachment,

_nissayesu mahabbhayaṃ_
____

[quote, Sn.v.752-3]
____
Then, unattached, free of grasping, the bhikkhu should mindfully fulfil the 
ideals of religious asceticism.

_Anissito anupādāno sato bhikkhu paribbaje ti._
____

Comment:

Norman says: 'Knowing this peril, that "There is great fear in dependences," a 
bhikkhu should wander, not dependent nor grasping.' But _anissito_ and 
_anupādāno_ appear as synonyms, which makes 'unattached, not grasping' more 
likely than 'not dependent nor grasping.'

=== Illustrations: upanissaya

.Illustration
====
upanissayo

basic resources
====

____
Leftover scraps as almsfood,

_Uttiṭṭhapiṇḍo uñcho ca_
____

____
Discarded cloth [for rag-robes],

_paṃsukūlañca cīvaraṃ_
____

____
These are indeed fitting for me,

_Etaṃ kho mama sāruppaṃ_
____

[quote, Thī.v.349]
____
The basic resources of the ascetic life.

_anāgārūpanissayo._
____

.Illustration
====
upanissaya

necessary condition
====

[quote, A.3.20]
____
For a virtuous person, perfect in virtue, right inward collectedness is endowed 
with its necessary condition.

_Sīlavato bhikkhave sīlasampannassa upanissayasampanno hoti sammāsamādhi._
____

.Illustration
====
upanissayo

spiritual support
====

Which four things greatly help (_bahukārā_)?

____
a suitable abiding place

_patirūpadesavāso_
____

____
the spiritual support of spiritually outstanding people

_sappurisūpanissayo_
____

____
a rightly directed disposition

_attasammāpaṇidhi_
____

[quote, D.3.276]
____
the previous performance of meritorious deeds

_pubbe ca katapuññatā._
____

=== Illustrations: nissāya

.Illustration
====
nissāya

beside
====

[quote, M.2.92]
____
The Blessed One stood beside the lowest step of the staircase.

_Atha kho bhagavā pacchimaṃ sopāṇakaḷeparaṃ nissāya aṭṭhāsi._
____

.Illustration
====
nissāya

beside
====

[quote, M.1.354]
____
He entered the hall and sat down beside the central pillar facing east.

_santhāgāraṃ pavisitvā majjhimaṃ thambhaṃ nissāya puratthābhimukho 
nisīdi._
____

Comment:

The Buddha would not lean against the pillar, because when he goes indoors 'he 
does not bend his body backwards' (M.2.138).

.Illustration
====
nissāya

in
====

The lion thought:

• 'How about if I were to make my lair in a certain woodland grove? +
☸ _aññataraṃ vanasaṇḍaṃ nissāya āsayaṃ kappeyyaṃ_).'

'Then I could emerge from my lair in the evening... and make for the cattle 
pasture' (D.3.23).

.Illustration
====
nissāya

in
====

[quote, S.1.144]
____
Then Venerable MahāMoggallāna stationed himself in the eastern quarter and 
sat cross-legged in the air above that brahmā.

_Atha kho āyasmā mahāmoggallāno puratthimaṃ disaṃ nissāya tassa 
brahmuno uparivehāsaṃ pallaṅkena nisīdi._
____

.Illustration
====
nissāya

in/near
====

Suppose there is a flayed cow. If it stands near a wall (_kuḍḍañce 
nissāya_), the creatures living in the wall (_kuḍḍanissītā pāṇā_) 
would nibble her. If near a tree (_rukkhañce nissāya_), the creatures living 
in the tree (_rukkhanissitā pāṇā_); if in water (_udakañce nissāya_), 
the creatures living in the water (_udakanissitā pāṇā_); if in the open 
air (_ākāsañce nissāya_), the creatures living in the open air 
(_ākāsanissitā pāṇā_).

[quote, S.2.99]
____
Wherever that flayed cow stands in or near to (_nissāya tiṭṭheyya_), the 
creatures living there (_tannissitā tannissitā pāṇā_) would nibble her

_Yaññadeva hi sā bhikkhave gāvī niccammā nissāya tiṭṭheyya ye 
tannissitā tannissitā pāṇā te naṃ khādeyyuṃ._
____

.Illustration
====
nissāya nissāya

right next to
====

[quote, D.2.130]
____
Āḷāra Kālāma went and sat under a tree. Then, bhante, five hundred carts 
went rumbling by right next to him.

_Atha kho bhante pañcamattāni sakaṭasatāni āḷāraṃ kālāmaṃ 
nissāya nissāya atikkamiṃsu._
____

.Illustration
====
nissāya

upon
====

[quote, S.3.91]
____
Homage to you, O best of men. We do not know what you are meditating upon.

_namo te purisuttama yassa te nābhijānāma yampi nissāya jhāyasī ti._
____

.Illustration
====
nissāya

supported by
====

[quote, S.2.114]
____
Two sheaves of reeds might stand supported by each other

_dve naḷakalāpiyo aññamaññaṃ nissāya tiṭṭheyyuṃ._
____

.Illustration
====
nissāya

with the support of
====

At the four gates of his city, King Seri gave gifts to the needy. His wives 
asked:

[quote, S.1.58]
____
'Your majesty gives gifts but we do not give gifts. It would be good if, with 
your majesty's support, we too might give gifts and perform acts of merit.'

_sādhu mayampi devaṃ nissāya dānāni dadeyyāma puññāni kareyyāmā ti._
____

.Illustration
====
nissāya

with the support of
====

[quote, S.2.218]
____
May those of unvirtuous desires, with the support of a faction, not create a 
schism in the community of bhikkhus.

_mā pāpicchā pakkhaṃ nissāya saṅghaṃ bhindeyyuṃ._
____

.Illustration
====
nissāya

with the help of
====

[quote, M.1.135]
____
How about if I collected grass, twigs, branches, and leaves, and bound them 
together into a raft, and with the help of that raft and making an effort with 
my hands and feet, I got safely across to the far shore.

_taṃ kullaṃ nissāya hatthehi ca pādehi ca vāyamamāno sotthinā pāraṃ 
uttareyyanti._
____

.Illustration
====
nissāya

with the help of
====

____
... In this regard, with the help of and by means of the neutral attitude that 
is undiversified, associated with undiversity, abandon and transcend the 
neutral attitude that is diversified, associated with diversity

_Tatra bhikkhave yā'yaṃ upekkhā ekattā ekattasitā taṃ nissāya taṃ 
āgamma yā'yaṃ upekkhā nānattā nānattasitā taṃ pajahatha taṃ 
samatikkamatha_
____

[quote, M.3.220]
____
... With the help of and by means of the perception that "It is void of 
personal qualities" abandon and transcend the neutral attitude that is 
undiversified, associated with undiversity.

_Atammayataṃ bhikkhave nissāya atammayataṃ āgamma yā'yaṃ upekkhā 
ekattā ekattasitā taṃ pajahatha taṃ samatikkamatha._
____

.Illustration
====
nissāya

with the help of
====

[quote, Sn.v.1070]
____
With the help of the reflection 'It does not exist,' cross the flood [of 
suffering].

_natthī ti nissāya tarassu oghaṃ._
____

.Illustration
====
nissāya

with the help of
====

[quote, M.2.185]
____
Friend, the brahman Dhanañjāni plunders brahman householders with the help of 
the king, and plunders the king with the help of brahman householders.

_Dhanañjāni āvuso brāhmaṇo rājānaṃ nissāya brāhmaṇagahapatike 
vilumpati. Brāhmaṇagahapatike nissāya rājānaṃ vilumpati._
____

.Illustration
====
nissāya

with the help of
====

This [wretched human] body has come into being through food, sister.

____
With the help of food, food must be abandoned.

_Āhāraṃ nissāya āhāro pahātabbo_
____

This [wretched human] body has come into being through craving.

[quote, A.2.145]
____
With the help of craving, craving must be abandoned.

_Taṇhaṃ nissāya taṇhā pahātabbā._
____

.Illustration
====
nissāya

with the help of
====

• Brahmanists and householders are helpful in providing bhikkhus with robe 
material, almsfood, abodes, and therapeutic requisites. Bhikkhus are very 
helpful in explaining the teaching, and proclaiming the religious life in its 
complete purity. +
☸ _Bahukārā bhikkhave brāhmaṇagahapatikā tumhākaṃ ye vo 
paccupaṭṭhitā 
cīvara-piṇḍapāta-senāsana-gilānapaccayabhesajjaparikkhārehi. Tumhepi 
bhikkhave bahukārā brāhmaṇagahapatikānaṃ_...

[quote, It.111]
____
Thus the religious life is lived with the help of each other for the sake of 
crossing the flood [of suffering], and for making a complete end of suffering.

_Evamidaṃ bhikkhave aññamaññaṃ nissāya brahmacariyaṃ vussati oghassa 
nittharaṇatthāya sammā dukkhassa antakiriyāyā ti._
____

.Illustration
====
nissāya

with the help of
====

[quote, S.5.268]
____
If a bhikkhu gains inward collectedness, gains mental concentration with the 
help of desire, this is called inward collectedness based on desire.

_Chandaṃ ce bhikkhave bhikkhu nissāya labhati samādhiṃ labhati 
cittassekaggataṃ ayaṃ vuccati chandasamādhi._
____

.Illustration
====
nissāya

physically/spiritually relying on
====

The mighty sal trees physically relying on the Himalayas, the king of mountain 
ranges (_himavantaṃ bhikkhave pabbatarājaṃ nissāya_) grow in three ways: 
in branches, leaves and foliage; in bark and shoot; in softwood and pith_._

Likewise, spiritually relying on the head of a family who has faith [in the 
perfection of the Perfect One's transcendent insight] (_saddhaṃ kulapatiṃ 
nissāya_), the folk in his house grow in three ways: faith [in the perfection 
of the Perfect One's transcendent insight], virtue, and penetrative discernment 
(A.1.152).

.Illustration
====
nissāya nissāya

by one support or another
====

[quote, M.2.265]
____
The Blessed One, bhante, has indeed explained to us the crossing of the flood 
&#8203;[of suffering] by one support or another.

_Nissāya nissāya kira no bhante bhagavatā oghassa nittharaṇā akkhātā._
____

.Illustration
====
nissāya

dependent upon
====

____
Whatever creatures there are which assume the four postures, all assume the 
four postures dependent upon the earth, established upon the earth

_sabbe te paṭhaviṃ nissāya paṭhaviyaṃ patiṭṭhāya_
____

[quote, S.5.78]
____
So, too, dependent upon virtue, established upon virtue, a bhikkhu develops and 
cultivates the seven factors of enlightenment.

_Evameva kho bhikkhave bhikkhu sīlaṃ nissāya sīle patiṭṭhāya satta 
bojjhaṅge bhāveti satta bojjhaṅge bahulīkaroti._
____

.Illustration
====
nissāya

dependent upon
====

[quote, M.1.230]
____
When seeds and plants, whatever their kind, grow and reach maturity, all do so 
dependent upon the earth, established upon the earth.

_sabbe te paṭhaviṃ nissāya paṭhaviyaṃ patiṭṭhāya._
____

.Illustration
====
yaṃ nissāya

by reason of which
====

[quote, A.3.340-1]
____
A bhikkhu with psychic power and mental mastery could, if he wished, focus on 
the solidness of that wooden log. How is that? There is the Solidness 
Phenomenon in that log of wood, by reason of which a bhikkhu with psychic power 
and mental mastery could focus on its solidness.

_Ākaṅkhamāno āvuso bhikkhu iddhimā cetovasippatto amuṃ dārukkhandhaṃ 
paṭhavītveva adhimucceyya. Taṃ kissa hetu? Atthi āvuso amumhi 
dārukkhandhe paṭhavīdhātu yaṃ nissāya bhikkhu iddhimā cetovasippatto 
amuṃ dārukkhandhaṃ paṭhavītveva adhimucceyya._
____

.Illustration
====
nissāya

for the sake of
====

Bhikkhus, there are five types of rag-robe wearers (_paṃsukulikā_), the best 
of whom undertakes the practice simply:

____
for the sake of fewness of needs

_appicchataṃ yeva nissāya_
____

____
for the sake of being content [with what is paltry and easily gotten]

_santuṭṭhiṃ yeva nissāya_
____

____
for the sake of erasing defilements

_sallekhaṃ yeva nissāya_
____

____
for the sake of physical seclusion

_pavivekaṃ yeva nissāya_
____

[quote, A.3.219]
____
for the sake of frugality

_idamatthitaṃ yeva nissāya._
____

.Illustration
====
nissāya

formal discipleship under a teacher
====

____
Ānanda, friend, the Blessed One has established a standard of ten years of 
formal discipleship under a teacher.

_bhagavatā āvuso ānanda paññattaṃ dasavassāni nissāya vatthuṃ_
____

[quote, Vin.1.80]
____
One of ten years' standing can offer formal spiritual support.

_dasavassena nissayaṃ dātuṃ._
____

.Illustration
====
nissāya

in formal discipleship under
====

____
Bhante, be my teacher

_acariyo me bhante hohī_
____

[quote, Vin.1.60-61]
____
I will live in formal discipleship under the Venerable.

_Ayasmato nissāya vacchāmi._
____

=== Illustrations: upanissāya

.Illustration
====
upanissāya

in
====

[quote, M.1.104]
____
A bhikkhu lives in some quiet grove. While living there, his unestablished 
mindfulness does not become established.

_Idha bhikkhave bhikkhu aññataraṃ vanapatthaṃ upanissāya viharati. Tassa 
taṃ vanapatthaṃ upanissāya viharato anupaṭṭhitā ceva sati na 
upaṭṭhāti._
____

.Illustration
====
upanissāya

near, in
====

[quote, M.1.106]
____
A bhikkhu lives near some city... in some country... near some man

_Idha pana bhikkhave bhikkhu aññataraṃ nagaraṃ upanissāya viharati... 
aññataraṃ janapadaṃ upanissāya viharati... aññataraṃ puggalaṃ 
upanissāya viharati._
____

.Illustration
====
upanissāya

nearby
====

[quote, S.2.269]
____
Bhikkhus, once there was a great lake in a forest with bull elephants living 
nearby.

_Bhūtapubbaṃ bhikkhave araññāyatane mahāsarasi taṃ nāgā upanissāya 
viharanti._
____

.Illustration
====
upanissāya

beside
====

[quote, S.1.146]
____
The independent Brahmās approached the Blessed One and stood, one beside each 
doorpost.

_Atha kho subrahmā ca paccekabrahmā suddhāvāso ca paccekabrahmā yena 
bhagavā tenupasaṅkamiṃsu. Upasaṅkamitvā paccekaṃ dvārabāhaṃ 
upanissāya aṭṭhaṃsu._
____

.Illustration
====
upanissāya

in and around
====

[quote, D.2.76]
____
Ānanda, go to all the bhikkhus who live in and around Rājagaha, and summon 
them to the assembly hall.

_gaccha tvaṃ ānanda yāvatikā bhikkhū rājagahaṃ upanissāya viharanti 
te sabbe upaṭṭhānasālāyaṃ sannipātehī ti._
____

.Illustration
====
upanissāya

spiritually supported by
====

____
There are four things spiritually supported by which a bhikkhu should abide

_cattāro dhammā upanissāya vihātabbā._
____

In this regard a bhikkhu judges that:

____
one thing should be followed.

_saṅkhāyekaṃ paṭisevati_
____

____
one thing should be endured.

_saṅkhāyekaṃ adhivāseti_
____

____
one thing should be avoided.

_saṅkhāyekaṃ parivajjeti_
____

____
one thing should be dispelled.

_saṅkhāyekaṃ vinodeti_
____

[quote, A.4.353-4]
____
In this way a bhikkhu is endowed with spiritual resources

_evaṃ kho bhikkhū bhikkhu nissayasampanno hotī ti._
____

.Illustration
====
upanissāya

physically relying on; spiritually relying on
====

____
Just as the trees in a mighty forest physically relying on (_upanissāya_) a 
rocky mountain might become forest giants,

_Yathāpi pabbato selo araññasmiṃ brahāvane +
Taṃ rukkhā upanissāya vaḍḍhante te vanappatī._
____

[quote, A.1.152]
____
Likewise in this world, spiritually relying on (_upanissāya_) the head of a 
family who has faith [in the perfection of the Perfect One's transcendent 
insight], +
His children, wife and relatives spiritually mature.

_Tatheva sīlasampannaṃ saddhaṃ kulapatiṃ idha +
Upanissāya vaḍḍhanti puttadārā ca bandhavā._
____

.Illustration
====
upanissāya

spiritually supported by
====

[quote, S.1.89]
____
You should abide spiritually supported by one thing: diligence in [cultivating] 
spiritually wholesome factors.

_Eko dhammo upanissāya vihātabbo appamādo kusalesu dhammesu._
____

.Illustration
====
upanissāya

spiritually supported by
====

[quote, A.2.151]
____
He lives spiritually supported by the five powers of a disciple in training: 
the powers of faith [in the perfection of the Perfect One's transcendent 
insight], shame of wrongdoing, fear of wrongdoing, energetic application [to 
the practice], and wisdom.

_So imāni pañca sekhabalāni upanissāya viharati: saddhābalaṃ hiribalaṃ 
ottappabalaṃ viriyabalaṃ paññābalaṃ._
____

.Illustration
====
upanissāya

spiritually supported by
====

[quote, S.1.139]
____
How about if I honoured, respected and abided spiritually supported by this 
very teaching to which I have fully awakened?

_Yannūnāhaṃ yvāyaṃ dhammo mayā abhisambuddho tameva dhammaṃ sakkatvā 
garukatvā upanissāya vihareyyanti._
____

.Illustration
====
upanissāya

in spiritual discipleship under
====

[quote, S.1.139]
____
What ascetic or Brahmanist can I honour and respect and dwell under in 
spiritual discipleship?

_Kannu khvāhaṃ samaṇaṃ vā brāhmaṇaṃ vā sakkatvā garukatvā 
upanissāya vihareyyan ti._
____

.Illustration
====
upanissāya

in spiritual discipleship under
====

[quote, D.3.284-5]
____
One lives in spiritual discipleship under the Teacher or a companion in the 
religious life of the standing of a teacher

_satthāraṃ vā upanissāya viharati aññataraṃ vā garuṭṭhāniyaṃ 
sabrahmacāriṃ._
____

.Illustration
====
upanissāya

in spiritual discipleship under
====

[quote, D.1.152]
____
Soon I shall have lived in spiritual discipleship under the Blessed One for 
three years.

_yadagge ahaṃ mahāli bhagavantaṃ upanissāya viharāmi na ciraṃ tīṇi 
vassāni._
____

.Illustration
====
upanissāya

dependent on
====

[quote, Sn.v.867]
____
Desire arises in the world dependent on what they call 'pleasing' and 
'displeasing.'

_Sātaṃ asātanti yamāhu loke tamupanissāya pahoti chando._
____

.Illustration
====
upanissāya

dependent on
====

• Dependent on ascetic practices and self-mortification, or on what is seen, 
heard, sensed, [or cognised], with raised voices they wail for spiritual 
purity, not free of craving for various states of individual existence. +
_Tapūpanissāya jigucchitaṃ vā atha vāpi diṭṭhaṃ vā sutaṃ mutaṃ 
vā +
Uddhaṃsarā suddhimanutthunanti avītataṇhāse bhavābhavesu_ (Sn.v.901).

=== Illustrations: nissita

.Illustration
====
nissitaṃ

embedded in
====

[quote, Thī.v.52]
____
He indeed removed from me the arrow [of craving], hard to discern, embedded in 
my heart;

_Abbuhi vata me sallaṃ duddasaṃ hadayanissitaṃ._
____

.Illustration
====
nissitaṃ

immersed in
====

Whoever you know to be of such a kind, immersed in worldly life 
(_gehanissitaṃ_), of unvirtuous desires, thoughts, conduct, and sphere of 
personal application, all of you unitedly shun him (Sn.v.280-281).

.Illustration
====
nissitā

living in
====

[quote, S.2.152]
____
The creatures living in the grass and wood will meet with calamity and disaster

_ye tiṇakaṭṭhanissitā pāṇā te anayavyasanaṃ āpajjeyyuṃ._
____

.Illustration
====
nissitā

living in
====

Suppose there is a flayed cow. If it stands near a wall, the creatures living 
in the wall (_kuḍḍanissītā pāṇā_) would nibble her (S.2.99).

.Illustration
====
nissitaṃ

conduces to
====

____
So, too, dependent upon virtue, established upon virtue, a bhikkhu develops and 
cultivates the seven factors of enlightenment.

_Evameva kho bhikkhave bhikkhu sīlaṃ nissāya sīle patiṭṭhāya satta 
bojjhaṅge bhāveti satta bojjhaṅge bahulīkaroti._
____

____
How does he do this?

_Kathañca bhikkhave bhikkhu sīlaṃ nissāya sīle patiṭṭhāya satta 
bojjhaṅge bhāveti satta bojjhaṅge bahulīkaro ti?_
____

____
In this regard a bhikkhu develops the enlightenment factor of mindfulness (... 
detached awareness) which conduces to seclusion [from sensuous pleasures and 
spiritually unwholesome factors], to non-attachment [to originated phenomena], 
to the ending [of originated phenomena], and which results in the 
relinquishment [of the whole phenomenon of attachment].

_Idha bhikkhave bhikkhu satisambojjhaṅgaṃ bhāveti (... 
upekkhāsambojjhaṅgaṃ bhāveti) vivekanissitaṃ virāganissitaṃ 
nirodhanissitaṃ vossaggapariṇāmiṃ._
____

____
In this way, dependent upon virtue, established upon virtue, a bhikkhu develops 
and cultivates the seven factors of enlightenment.

_Evaṃ kho bhikkhave bhikkhu sīlaṃ nissāya sīle patiṭṭhāya satta 
bojjhaṅge bhāveti satta bojjhaṅge bahulīkarotī ti._
____

Comment:

There are five reasons why _nissitaṃ_ does not mean 'supported by.'

1. Given that the sutta says the _bojjhaṅgā_ are brought to development 
through virtue, it would be discordant in the same sutta to say that the 
_bojjhaṅgā_ are 'supported by' _viveka virāga_ and _nirodha_.

2. What the _bojjhaṅgā_ are 'supported by' is explained in the 
_Bojjhaṅgasaṃyuttaṃ_: virtue (S.5.63), listening to the teaching 
(S.5.67), developing the [contemplation of the] four bases of mindfulness 
(S.5.73), virtuous friendship (S.5.78), proper contemplation (S.5.79), and 
diligence [in the practice] (S.5.91).

3. The Nibbidā Sutta (S.5.82) says seven factors of enlightenment when 
developed and cultivated lead to _ekantanibbidāya virāgāya nirodhāya 
upasamāya abhiññāya sambodhāya nibbānaya saṃvattanti_. This list makes 
it clear that _virāga_ and _nirodha_ are goals of the practice, not supports 
for it.

4. The factors of the eightfold path are similarly called _vivekanissitaṃ 
virāganissitaṃ nirodhanissitaṃ vossaggapariṇāmiṃ_ (S.5.54). To 
propose that social activites like right speech, right conduct and right means 
of livelihood are 'supported by' or 'based upon' _viveka virāga_ and _nirodha_ 
is obviously untrue.

5. Bodhi says that 'the terms 'seclusion' (_viveka_), 'dispassion' 
(__virā__ga), and 'cessation' (_nirodha_) may all be understood as referring 
to Nibbāna. Their use in this context signifies that the development of the 
enlightenment factors is directed to Nibbāna' (MLDB p.1172 n.48).

.Illustration
====
nissitaṃ

conduce to
====

[quote, Th.v.599]
____
The black crow dwelling [and feasting] in its home in the charnel ground 
arouses mindfulness in me regarding the body that conduces to non-attachment 
&#8203;[to originated phenomena].

_Apaṇḍaro aṇḍasambhavo sīvathikāya niketacāriko uppādayātava me 
satiṃ sandehasmiṃ virāganissitaṃ._
____

.Illustration
====
nissito

on account of
====

[quote, Sn.v.798]
____
The wise call that thing a spiritual shackle if, on account of it, one regards 
other people as inferior.

_Taṃ vāpi ganthaṃ kusalā vadanti yaṃ nissito passati hinamaññaṃ._
____

.Illustration
====
nissitā

supported by
====

[quote, M.3.243]
____
If I were to direct this detached awareness so purified and refined to the 
state of awareness of boundless space, and to develop my mind accordingly, then 
this detached awareness of mine, supported by that, fuelled by it, would remain 
for a very long time.

_imaṃ ce ahaṃ upekkhaṃ evaṃparisuddhaṃ evaṃpariyodātaṃ 
ākāsānañcāyatanaṃ upasaṃhareyyaṃ tadanudhammañca cittaṃ 
bhāveyyaṃ evaṃ ayaṃ upekkhā tannissitā tadupādānā ciraṃ 
dīghamaddhānaṃ tiṭṭheyya._
____

.Illustration
====
nissito

supported by
====

____
Alone and unsupported, Sakyan, I am not able to cross the great flood [of 
suffering].

_Eko ahaṃ sakka mahantamoghaṃ anissito no visahāmi tārituṃ_
____

[quote, Sn.v.1073]
____
Tell me, All-Seeing Eye, a basis [for spiritual development] (_ārammaṇaṃ_) 
supported by which I might cross this [wretched] flood [of suffering].

_Ārammaṇaṃ brūhi samantacakkhu yaṃ nissito oghamimaṃ tareyyaṃ._
____

.Illustration
====
nissitā

supported by
====

[quote, It.111]
____
Householders and ascetics alike, each supported by the other, both fathom the 
true teaching; both attain unsurpassed safety from the danger of bondage [to 
individual existence]:

_sāgārā anagārā ca ubho aññoññanissitā; ārādhayanti saddhammaṃ 
yogakkhemaṃ anuttaraṃ._
____

.Illustration
====
nissito

relies on
====

____
By three means, a brigand robs, plunders, burgles, and ambushes.

_Tīhi bhikkhave aṅgehi samannāgato mahācoro sandhimpi chindati nillopampi 
harati ekāgārikampi karoti paripanthe pi tiṭṭhati._
____

____
He relies on the inaccessible, the impenetrable, and the powerful.

_visamanissito ca hoti gahananissito ca hoti balavanissito ca hoti._
____

____
How does a brigand rely on the inaccessible?

_Kathañca bhikkhave mahācoro visamanissito hoti._
____

____
He relies on impassible rivers and mountains hard to climb.

_idha bhikkhave mahācoro nadīviduggaṃ vā nissito hoti pabbatavisamaṃ 
vā._
____

____
How does a brigand rely on the impenetrable?

_Kathañca bhikkhave mahācoro gahananissito hoti._
____

____
He relies on jungles of grass or trees, or thickets, or woodland groves.

_idha bhikkhave mahācoro tiṇagahanaṃ vā nissito hoti rukkhagahanaṃ vā 
gedhaṃ vā pana vanasaṇḍaṃ._
____

____
How does a brigand rely on the powerful?

_Kathañca bhikkhave mahācoro balavanissito hoti_
____

____
He relies on kings or kings' ministers (_rājānaṃ vā rājamahāmattānaṃ 
vā nissito hoti_), thinking that if anyone accuses him, these people will say 
what is useful in defence, and they do so.

_idha bhikkhave mahācoro rājānaṃ vā rājamahāmattānaṃ vā nissito 
hoti. Tassa evaṃ hoti: sace maṃ koci kiñci vakkhati ime me rājāno vā 
rāja mahāmattā vā pariyodhāya atthaṃ bhaṇissantī ti._
____

In the same way, an unvirtuous bhikkhu possessed of three qualities (_tīhi 
dhammehi samannāgato_) wanders about hurting and injuring himself; he is 
blameworthy, criticised by the wise, and begets much demerit. What are the 
three?

____
In this regard, an unvirtuous bhikkhu relies on the crooked, the impenetrable 
and the powerful.

_visamanissito ca hoti gahananissito ca balavanissito ca._
____

____
How does an unvirtuous bhikkhu rely on the crooked?

_Kathañca bhikkhave pāpabhikkhu visamanissito hoti._
____

____
In this regard, an unvirtuous bhikkhu is possessed of crookedness in deeds of 
body, speech, and mind.

_idha bhikkhave pāpabhikkhu visamena kāyakammena... vacīkammena... 
manokammena samannāgato hoti._
____

• How does an unvirtuous bhikkhu rely on the impenetrable? +
☸ Kathañca bhikkhave pāpabhikkhu gahananissito hoti

____
In this regard, the unvirtuous bhikkhu has a wrong view [of reality]. He is 
possessed of an unenlightening doctrine.

_idha bhikkhave pāpabhikkhu micchādiṭṭhiko hoti antaggāhikāya 
diṭṭhiyā samannāgato_
____

____
How does an unvirtuous bhikkhu rely on the powerful?

_Kathañca bhikkhave pāpabhikkhu balavanissito hoti_
____

[quote, A.1.153-5]
____
He relies on kings or kings' ministers thinking that if anyone accuses him, the 
kings or kings' ministers will defend him. And they do so.

_idha bhikkhave pāpabhikkhu rājānaṃ vā rājamahāmattānaṃ vā nissito 
hoti. Tassa evaṃ hoti: sace maṃ koci kiñci vakkhati ime me rājāno vā 
rājamahāmattā vā pariyodhāya atthaṃ bhaṇissantī ti._
____

.Illustration
====
nissitaṃ

associated with
====

[quote, It.117]
____
Whoever thinks such thoughts as are unvirtuous and associated with the 
household life is following a wrong path.

_Yo vitakkaṃ vitakketi pāpakā gehanissitaṃ kummaggaṃ paṭipanno so._
____

.Illustration
====
nissitaṃ

associated with
====

[quote, M.3.31]
____
With the destruction, fading away, ending, giving up, and relinquishment of 
clinging, grasping, obstinate adherence, stubborn attachment, and 
identification associated with the Solidness Phenomenon, I know that my mind is 
liberated [from perceptually obscuring states]

_ye ca paṭhavīdhātunissitā upayūpādānā cetaso 
adhiṭṭhānābhinivesānusayā tesaṃ khayā virāgā nirodhā cāgā 
paṭinissaggā vimuttaṃ me cittanti pajānāmi._
____

.Illustration
====
nissitā

associated with
====

____
What is the neutral attitude that is diversified, associated with diversity?

_Katamā ca bhikkhave upekkhā nānattā nānattasitā:_
____

____
There is a neutral attitude associated with visible objects, audible objects... 
mentally known objects.

_atthi bhikkhave upekkhā rūpesu atthi saddesu atthi gandhesu atthi rasesu 
atthi phoṭṭhabbesu._
____

____
What is the neutral attitude that is undiversified, associated with undiversity?

_Katamā ca bhikkhave upekkhā ekattā ekattasitā._
____

[quote, M.3.220]
____
There is a neutral attitude associated with the state of awareness of boundless 
space, associated with the state of awareness of boundless mental 
consciousness, associated with the state of awareness of nonexistence, 
associated with the state of awareness neither having nor lacking perception.

_atthi bhikkhave upekkhā ākāsānañcāyatananissitā atthi 
viññāṇañcāyatananissitā atthi ākiñcaññāyatananissitā atthi 
nevasaññānāsaññāyatananissitā._
____

Comment:

Here _nissitā_ and _sitā_ are synonyms.

.Illustration
====
nissitaṃ

associated with
====

[quote, M.3.32]
____
Friends, I have treated the Solidness Phenomenon as void of personal qualities, 
and the Solidness Phenomenon as having no [absolute] Selfhood associated with 
it.

_paṭhavīdhātuṃ kho ahaṃ āvuso na attato upagacchiṃ na ca 
paṭhavīdhātunissitaṃ attānaṃ._
____

.Illustration
====
nissitā

bound up with
====

[quote, Dh.v.339]
____
Thoughts bound up with attachment are the winds which carry along a man with a 
wrong view [of reality].

_Vāhā vahanti duddiṭṭhiṃ saṅkappā rāganissitā._
____

.Illustration
====
nissitā

based on
====

[quote, M.1.186]
____
It is a loss for me, not a gain; it is unfortunate for me, not fortunate, that 
when I recollect the Buddha, the teaching, and the community of the Blessed 
One's disciples in this way, detached awareness based on what is spiritually 
wholesome is not established within me.

_upekkhā kusalanissitā na saṇṭhātī ti._
____

.Illustration
====
nissito

based on
====

[quote, Ud.31]
____
The devas envy the bhikkhu who collects his food on almsround, who is 
self-reliant, not supported by a patron, but not if it is based on desire for 
praise and fame.

_Piṇḍapātikassa bhikkhuno attabharassa anaññaposino +
Devā pihayanti tādino no ce saddasilokanissito ti._
____

=== Illustrations: nissita, attached

==== Introduction

In the following group of contexts, I take _nissita_ to mean 'attached' not 
'dependent' for two reasons:

1. Because _nissita_ is frequently linked to other words implying grasping: 
_upādāya, upādiyati, chandarāgaṃ, paṭibaddho,_ and _saṃyutto_. For 
example:

[quote, Sn.v.752]
____
One who is attached, grasping states of individual existence in this world or 
another does not transcend the round of birth and death

_nissito ca upādiyaṃ +
Itthabhāvaññathābhāvaṃ saṃsāraṃ nātivattati._
____

[quote, D.2.292]
____
And he (practising _satipaṭṭhāna_ mindfulness) abides unattached, not 
grasping anything in the world

_anissito ca viharati na ca kiñci loke upādiyati._
____

2. Secondly, certain of these contexts do not support 'dependent.' For 
instance, it seems more sensible to say a bhikkhu is free of attachment to 
nourishment of all kinds (_sabbāhāramanissito_: Sn.v.749) than to say he is 
not dependent on them. Being not attached to food does not mean not dependent. 
Similarly, it seems more sensible to say a bhikkhu is not attached to the past 
(_pubbamantamanissito_: Sn.v.849) than to say he is not dependent on the past, 
as Norman puts it.

.Illustration
====
nissitena

attached
====

[quote, It.39]
____
These two aspects of the Untroubled were made known by the Seer, free of 
attachment, and of excellent qualities.

_Duve imā cakkhumatā pakāsitā +
Nibbānadhātu anissitena tādinā._
____

.Illustration
====
nissito

attached
====

[quote, Sn.v.363]
____
Having abandoned whatever is beloved or unbeloved, being without grasping, one 
who is not attached to anything at all, who is free of things conducive to 
psychological bondage, he would properly fulfil the ideals of religious 
asceticism in the world.

_Hitvāna piyañca appiyañca anupādāya anissito kuhiñci +
Saṃyojaniyehi vippamutto sammā so loke paribbajeyya._
____

.Illustration
====
anissito

free of attachment
====

____
He sees no substantial reality in objects of attachment.

_Na so upadhīsu sārameti_
____

____
Having eliminated his fondness and attachment regarding objects of attachment,

_Ādānesu vineyya chandarāgaṃ_
____

____
He is free of attachment, not needing to be led by others,

_So anissito anaññaneyyo_
____

[quote, Sn.v.364]
____
He would properly fulfil the ideals of religious asceticism in the world.

_Sammā so loke paribbajeyya._
____

.Illustration
====
nissitā

attached
====

[quote, A.2.9]
____
Those doctrines, at variance with each other, to which ascetics and Brahmanists 
are attached; .

_Ye keci'me vādapathā puthussitā yannissitā samaṇabrāhmaṇā ca._
____

.Illustration
====
anissito

free of attachment
====

[quote, Sn.v.947]
____
Knowing the nature of reality [according to reality], he is free of attachment.

__ñatvā dhammaṃ anissito._
____

.Illustration
====
anissito

unattached
====

[quote, D.2.292]
____
And he (practising _satipaṭṭhāna_ mindfulness) abides unattached, not 
grasping anything in the world.

_Anissito ca viharati na ca kiñci loke upādiyati._
____

.Illustration
====
nissita

attached
====

____
There is trembling in one who is attached.

_nissitassa calitaṃ_
____

[quote, M.3.266]
____
There is no trembing in one who is free of attachment.

_Anissitassa calitaṃ natthi._
____

.Illustration
====
nissitaṃ

attached
====

[quote, M.3.259]
____
Therefore, householder, you should train yourself [with this reflection]: 'I 
will not grasp the visual sense; my mind will not be attached to the visual 
sense.

_Tasmātiha te gahapati evaṃ sikkhitabbaṃ na cakkhuṃ upādiyissāmī na 
ca me cakkhunissitaṃ viññāṇaṃ bhavissatī ti._
____

.Illustration
====
nissitaṃ

attached to
====

When the devas with Inda, Brahmā, and Pajāpati seek a bhikkhu who is 
liberated in mind (_vimuttacittaṃ_), they do not find [anything of which they 
could say]

____
'The stream of sense consciousness of the Perfect One is attached to this'

_idaṃ nissitaṃ tathāgatassa viññāṇan ti._
____

[quote, M.1.140]
____
For what reason? The Perfect One is untraceable even in this lifetime, I 
declare.

_Taṃ kissa hetu diṭṭhevāhaṃ bhikkhave dhamme tathāgataṃ ananuvejjo 
ti vadāmi._
____

.Illustration
====
nissitaṃ

attached to
====

[quote, M.2.265]
____
If he takes delight in that detached awareness, welcomes it, and persists in 
cleaving to it then the mind is attached to it. That is grasping.

_So taṃ upekkhaṃ abhinandati abhivadati ajjhosāya tiṭṭhati tassa taṃ 
upekkhaṃ abhinandato abhivadato ajjhosāya tiṭṭhato tannissitaṃ hoti 
viññāṇaṃ tadupādānaṃ._
____

.Illustration
====
kiṃ nissitā

for what reason
====

[quote, Sn.v.1043]
____
For what reason have seers, men, _khattiyas_, and brahmans, so many of them, 
offered gifts to devas here in the world. I ask you, Blessed One. Tell me this.

_Kiṃ nissitā isayo manujā khattiyā brāhmaṇā devatānaṃ +
Yaññamakappayiṃsu puthūdha loke pucchāmi taṃ bhagavā brūhi me taṃ._
____

[quote, Sn.v.1044]
____
These many seers, men, _khattiyas_, and brahmans who offered gifts to devas 
here in the world, Puṇṇaka, being tied to old age, offered gifts hoping for 
states of individual existence in this world [or another].

_Ye kecime isayo manujā khattiyā brāhmaṇā devatānaṃ +
Yaññamakappayiṃsu puthūdha loke āsiṃsamānā puṇṇaka itthabhāvaṃ 
+
Jaraṃ sitā yaññamakappayiṃsu._
____

=== Illustrations: upanissita

.Illustration
====
upanissitā

attached
====

[quote, Thī.v.184]
____
The religious philosophers outside this [training system] are attached to 
dogmatic views.

_Ito bahiddhā pāsaṇḍā diṭṭhiyo upanissitā._
____

.Illustration
====
upanissitā

attached
====

[quote, Sn.v.877]
____
The investigating sage knowing that these [so-called pandits] are attached, and 
knowing their states of attachment [according to reality], knowing this, 
liberated [from perceptually obscuring states], he does not dispute.

_Ete ca ñatvā upanissitā ti ñatvā muni nissaye so vīmaṃsi +
Ñatvā vimutto na vivādameti._
____

