== Nivesana

=== Renderings

- _nivesana_: residence

- _nivesana_: attachment

- _nivesana_: object of attachment

=== Introduction

==== Attachment of the mind: views and egocentric thoughts

The _Sundarikabhāradvāja Sutta_ says:

[quote, Sn.v.470]
____
'He who has abandoned the attachment of the mind [to views and egocentric 
thoughts], in whom there is no possessiveness at all, not grasping anything in 
either this world or the world beyond: the Perfect One is worthy of the 
oblation.

_Nivesanaṃ yo manaso ahāsi pariggahā yassa na santi keci +
Anupādiyāno idha vā huraṃ vā tathāgato arahati pūraḷāsaṃ._
____

That the attachment of the mind is to views and egocentric thoughts is 
supported by the commentary and the suttas:

1. Commentary: _taṇhādiṭṭhinivesanaṃ_. The notion "I am" and other 
egocentric thoughts are imbued with _taṇhā_, says the _Taṇhājālinī 
Sutta_ (A.2.212-3).

2. 'Objects of attachment' is linked in the following quote to views and 
thoughts that are regarded as personal.

[quote, Sn.v.846]
____
One who is blessed with profound knowledge has no conceit about any view or 
thought because he does not regard them as endowed with personal qualities. 
Such a person is not to be gauged by his conduct, nor by his learning. He is 
not attracted to objects of attachment.

_Na vedagū diṭṭhiyāyako na mutiyā sa mānameti na hi tammayo so +
Na kammunā no pi sutena neyyo anupanīto sa nivesanesu._
____

=== Illustrations

.Illustration
====
nivesanaṃ

residence
====

[quote, S.5.396]
____
He went to the residence of Kaligodha the Sakyan lady.

_yena kāligodhāya sākiyāniyā nivesanaṃ tenupasaṅkami._
____

.Illustration
====
nivesanañca

attachment
====

[quote, Sn.v.1055]
____
Whatever you know, above, below, across, and also in the middle, having thrust 
away spiritually fettering delight and attachment regarding these things.

_Yaṃ kiñci sampajānāsi uddhaṃ adho tiriyañcāpi majjhe etesu nandiñca 
nivesanañca panujja._
____

.Illustration
====
nivesanesu

attachments
====

[quote, Sn.v.785]
____
Therefore a man rejects or accepts a doctrine simply in accordance with his 
attachments.

_Tasmā naro tesu nivesanesu nirassati ādiyati ca dhammaṃ._
____

.Illustration
====
anivesano

attachment
====

[quote, Dh.v.40]
____
One should be free of attachment.

_anivesano siyā._
____

.Illustration
====
nivesanesu

objects of attachment
====

[quote, Sn.v.846]
____
He is not attracted to objects of attachment.

_anupanīto sa nivesanesu._
____

.Illustration
====
nivesanāni

objects of attachment
====

[quote, Sn.v.210]
____
Having understood all objects of attachment, and not desiring any of them

_Aññāya sabbāni nivesanāni anikāmayaṃ aññatarampi tesaṃ._
____

