== Niyyāna

=== Renderings

- _niyyāna_: salvation

- _niyyāna_: deliverance [from suffering]

- _niyyānaṃ bhavati_: to march forth

=== Introduction

==== Niyyānaṃ bhavati: to march forth

In its unexalted sense, _niyyāna_ means 'going out, departure,' says PED, as 
here:

[quote, D.1.9]
____
The king will march forth; the king will not march forth;

_raññaṃ niyyānaṃ bhavissati. Raññaṃ aniyyānaṃ bhavissati._
____

==== Niyyāna: salvation

For brahmans _niyyāna_ was the highest attainment, meaning union with Brahmā, 
i.e. 'salvation':

[quote, D.1.235]
____
This indeed is the direct path, the straight way, which leads to salvation, 
which leads the one who practises it to union with Brahmā.

_ayameva ujumaggo ayamañjasāyano niyyāṇiko niyyāti takkarassa 
brahmasahavyatāya._
____

==== Niyyāna: deliverance [from suffering]

For Buddhists _niyyāna_ has three associations:

1. freedom from suffering (_dukkhā pamuccati_)

2. inward peace (_upasama_)

3. enlightenment (_sambodha_)

These associations support us calling __niyyāna '__deliverance [from 
suffering].'

1. This I tell you: This deliverance [from suffering] for the world [of beings] 
has been declared to you [by me] in accordance with truth. In this way [the 
world of beings] is released from suffering.
+
****
_Etaṃ lokassa niyyānaṃ akkhātaṃ vo yathātathaṃ +
****
Etaṃ vo ahamakkhāmi evaṃ dukkhā pamuccati_ (Sn.v.172).

2. Where a teacher is not perfectly enlightened, the teaching is 
ill-proclaimed, ill-expounded, and does not lead to deliverance [from 
suffering], or to inward peace. It is expounded by one who is not perfectly 
enlightened.
+
****
_satthā ca hoti asammāsambuddho dhammo ca durakkhāto duppavedito aniyyāniko 
anupasamasaṃvattaniko asammāsambuddhappavedito_ (D.3.120).
****

3. These teachings which are wholesome, noble, and which lead to deliverance 
&#8203;[from suffering] and to enlightenment.
+
****
_Ye te bhikkhave kusalā dhammā ariyā niyyānikā sambodhagāmino_ (Sn.p.139).
****

==== Niyyānika and saṃsāra

PED says _niyyānika_ means 'leading out (of _saṃsāra_),' but _niyyānika_ 
cannot be rendered as such because it is never in the suttas directly linked to 
_saṃsāra_.

=== Illustrations

.Illustration
====
niyyānaṃ

deliverance [from suffering]
====

[quote, Sn.v.170]
____
What is that grasping because of which the world [of beings] suffers hardship? 
Being asked about deliverance [from suffering], tell me how [the world of 
beings] is released from suffering.

_Katamaṃ taṃ upādānaṃ yattha loko vihaññati +
Niyyānaṃ pucchito brūhi kathaṃ dukkhā pamuccati._
____

.Illustration
====
niyyānikā

lead to deliverance [from suffering]
====

• But, Ānanda, in regard to those thoughts which are noble, and which lead 
to deliverance [from suffering], and lead the one who practises them to the 
complete destruction of suffering, that is to say unsensuous thought, 
benevolent thought, compassionate thought, he thinks: 'I will think thoughts 
like these.' +
_Ye ca kho ime ānanda vitakkā ariyā niyyānikā niyyanti takkarassa sammā 
dukkhakkhayāya. Seyyathīdaṃ nekkhamma vitakko avyāpādavitakko 
avihiṃsāvitakko iti evarūpe vitakke vitakkessāmī ti_ (M.3.113-4).

.Illustration
====
niyyānikā

lead to deliverance [from suffering]
====

[quote, S.5.82]
____
The seven factors of enlightenment when developed and cultivated are noble and 
lead to deliverance [from suffering], and lead the one who practises them to 
the complete destruction of suffering.

_Ime kho bhikkhave satta bojjhaṅgā bhāvitā bahulīkatā ariyā niyyānikā 
niyyanti takkarassa sammā dukkhakkhayāyāti._
____

