== No c'assa no ca me siyā

=== Renderings

- _no c'assa no ca me siyā_: had it not been, it would not have been "mine"

- _na bhavissati na me bhavissati_: it will be not; not "mine" will it be

- _yadatthi yaṃ bhūtaṃ taṃ pajahāmī ti_: that which is, that which is 
brought about, that I abandon

=== Introduction

==== Assa and siyā: renderings

_Assa_ and _siyā_ are optative forms of _atthi_, meaning either:

1. 'if he were or should be' (PGPL, section 510).

2. 'it might be' (DOP, sv _atthi_).

==== Assa: alternative renderings

_Assa_ can also be rendered as:

1. 'it would be' i.e. the conditional simple tense. For example:
+
[quote, D.2.225]
____
'May the Blessed One live for a long time, free of sickness and illness! That 
would be for the welfare and happiness of the manyfolk'

_tadassa bahujanahitāya bahujanasukhāya._
____

2. 'it would have been' i.e. the conditional perfect progressive tense. For 
example, if the Buddha were to die prematurely, Venerable Sāriputta said he 
would think:
+
[quote, S.2.274]
____
'If the Blessed One had lived for a long time, that would have been for the 
welfare and happiness of the manyfolk'

_sace hi bhagavā ciraṃ dīghamaddhānaṃ tiṭṭheyya tadassa 
bahujanahitāya bahujanasukhāya._
____

==== Ca/ca connective

1. The truncated c' in the first line of the formula stands for _ca_ not _ce_ 
because it is part of the _ca/ca_ connective. This usually means 'and... and,' 
but not here as we will see.

2. Bodhi says 'The commentaries take the truncated particle c' to represent ce, 
"if," and interpret the two parts of the formula as conditionals' (NDB note 
1532). Thus he says the commentaries would render the opening phrase: 'If it 
had not been, it would not be mine.'

3. Bodhi says 'I dissent from the commentaries on the meaning of c', which I 
take to represent ca (="and"). The syntax of the phrase as a whole requires 
this.' By which he means the syntax of a _ca/ca_ connective requires this. 
Bodhi thus assumes the _ca/ca_ connective has but one meaning: 'and... and.' 
But Norman says: '_ca_ in the sense of "if" is common in Pāli' (EVI n.37).

==== Ca and the conditional sense

PED says _ca_ has four meanings:

\(a) indefinite sense (with a demonstrative pronoun) e.g. _yañ ca kho ceteti_: 
whatever he thinks.

\(b) connective sense: 'and, then, now.'

\(c) disjunctive sense: 'but.'

\(d) conditional sense: 'if,' 'might,' 'may.'

Examples of conditional _ca_ are as follows:

==== Examples of conditional ca: 'if'

PED gives an example of _ca_ in its conditional sense ('if'), which is 
especially noteworthy because it is part of a _ca/ca_ connective:

[quote, J.5.216]
____
If Sakka will give me a wish, that wish will be granted

_Sakko ca me varaṃ dajjā so ca labbhetha me varo._
____

==== Examples of conditional ca: 'if'

• If there were no deed that produced karmic consequences in the sensuous 
plane of existence would individual existence in the sensuous plane of 
existence be discerned? +
☸ _Kāmadhātuvepakkañca ānanda kammaṃ nābhavissa api nu kho kāmabhavo 
paññāyethā ti_? (A.1.223).

==== Examples of conditional ca: 'might there not be'

____
-- Come now, bhikkhus, let me invite you (to censure me): might there not be 
any deed of mine (_na ca me kiñci_), either bodily or verbal, which you would 
censure?

_Handadāni bhikkhave pavārayāmi vo na ca me kiñci garahatha kāyikaṃ vā 
vācasikaṃ vā ti_
____

[quote, S.1.190]
____
-- Bhante, there is no deed of the Blessed One, either bodily or verbal, that 
we would censure.

_na kho mayaṃ bhante bhagavato kiñci garahāma kāyikaṃ vā vācasikaṃ 
vā._
____

==== Examples of conditional ca: 'May I not waste away!'

[quote, S.3.125]
____
Formerly, bhante, when I was ill I dwelt with my bodily form tranquillised. Now 
I do not attain that inward collectedness. As I do not attain that inward 
collectedness, bhante, it occurs to me: 'May I not waste away! (_no ca 
khvāhaṃ parihāyāmī ti_).

_Pubbeva khvāhaṃ bhante gelaññe passambhetvā kāyasaṅkhāre viharāmi. 
Sohaṃ taṃ samādhiṃ nappaṭilabhāmi. Tassa mayhaṃ bhante taṃ 
samādhiṃ appaṭilabhato evaṃ hoti no ca khvāhaṃ parihāyāmī ti._
____

==== The trailer phrase

Occasionally a trailer phrase is added to the _no c'assa_ formula, as follows:

[quote, A.4.75]
____
'That which is, that which is brought about, that I abandon'

_yadatthi yaṃ bhūtaṃ taṃ pajahāmī ti._
____

This second phrase is a logical progression of the first phrase:

1. If it had not been (_no c'assa_)

2. I abandon that which is (_yadatthi_)

==== The application of the no c'assa reflection

[quote, S.3.57]
____
The _Udāna Sutta_ (S.3.57) says the _no c'assa_ reflection concerns the five 
aggregates. That is, with the cessation of the five aggregates, a bhikkhu 
reflects that had the aggregates not been, they would not have been "mine." 
They will be not; not "mine" will they be.' See Illustrations below.

_So rūpassa vibhavā vedanāya vibhavā saññā vibhavā saṅkhārānaṃ 
vibhavā viññāṇassa vibhavā evaṃ kho bhikkhu no cassaṃ no ca me siyā 
nābhavissa na me bhavissatī ti evaṃ adhimuccamāno bhikkhu chindeyya 
orambhāgiyāni saṃyojanānī ti._
____

For the ignorant Everyman, this reflection arouses terror (_tāsaṃ āpajjati_ 
S.3.57).

==== The Annihilationists formula

A similar formula is ascribed to annihilationists. Its slight distortion 
implies the view "I will be destroyed," as follows:

____
'Had I not been, it would not have been "mine." I will be not, not "mine" will 
it be'

_no c'assaṃ no ca me siyā na bhavissāmi na me bhavissatī ti._
____

This annihilationist attitude can be similarly applied to the five aggregates.

=== Illustrations

.Illustration
====
no c'assa

had it not been
====

____
-- 'A bhikkhu practises thus:

_Idhānanda bhikkhu evaṃ paṭipanno hoti_
____

____
'Had it not been, it would not have been "mine." It will be not; not "mine" 
will it be. That which is, that which is brought about, that I abandon.'

_no c'assa no ca me siyā na bhavissati na me bhavissati. Yadatthi yaṃ 
bhūtaṃ taṃ pajahāmī ti_
____

[quote, M.2.265]
____
In this way he attains detached awareness.

_evaṃ upekkhaṃ paṭilabhati._
____

.Illustration
====
no c'assaṃ

Had I not been
====

Annihilationist formula:

[quote, S.3.99]
____
'Had I not been, it would not have been "mine." I will be not, not "mine" will 
it be'

_no c'assaṃ no ca me siyā na bhavissāmi na me bhavissatī ti._
____

____
That annihilationist view is an originated phenomenon.

_Yā kho pana sā bhikkhave ucchedadiṭṭhi saṅkhāro so._
____

.Illustration
====
no c'assa

had it not been
====

____
The ignorant Everyman is terrified of an unterrifying matter. For this is 
terrifying to the ignorant Everyman: 'Had it not been, it would not have been 
"mine." It will be not; not "mine" will it be.'

_Idha bhikkhu assutavā puthujjano atasitāye ṭhāne tāsaṃ āpajjati tāso 
heso bhikkhu assutavato puthujjanassa no c'assa no ca me siyā na bhavissati na 
me bhavissatī ti._
____

[quote, S.3.57]
____
The noble disciple is not terrified of an unterrifying matter. For this is not 
terrifying to the noble disciple: 'Had it not been, it would not have been 
"mine." It will be not; not "mine" will it be.'

_Sutavā ca kho bhikkhu ariyasāvako atasitāye ṭhāne na tāsaṃ āpajjati. 
Na heso bhikkhu tāso sutavato ariyasāvakassa no c'assa no ca me siyā na 
bhavissati na me bhavissatī ti._
____

.Illustration
====
no c'assa

had it not been
====

____
A bhikkhu discerns according to reality that the five aggregates will cease

_Rūpaṃ... Viññāṇaṃ vibhavissatī ti yathābhūtaṃ pajānāti._
____

____
With the cessation of the five aggregates, a bhikkhu reflects thus.

_So rūpassa vibhavā... viññāṇassa vibhavā evaṃ kho bhikkhu_
____

____
-- 'Had it not been, it would not have been "mine." It will be not; not "mine" 
will it be.'

_no c'assa no ca me siyā na bhavissati na me bhavissatī ti_
____

[quote, S.3.57]
____
A bhikkhu intent upon liberation [from perceptually obscuring states] in this 
way can sever the ties to individual existence in the low plane of existence

_evaṃ vimuccamāno bhikkhu chindeyyorambhāgiyāni saṃyojanānī ti._
____

