== Ogha

=== Renderings

- _ogha_: flood

- _ogha_: the flood [of suffering]

- _oghatiṇṇa_: flood-crosser, one who has crossed the flood [of suffering]

=== Introduction

==== PED: the old word 'ogha'

PED (sv _Ogha_) says that one who has 'crossed the flood' (_oghatiṇṇa_) is 
ascribed the mental and moral qualifications of the arahant, but adds that 
'less often we have details of what the flood consists of.' It says that 
'towards the end of the Nikāya period we find, for the first time, the use of 
the word in the plural, and the mention of the four _oghas_ identical with the 
four _āsavas_... The 5^th^ century commentators persist in the error of 
explaining the old word _ogha_, used in the singular, as referring to the four 
_āsavas.'_

==== The ocean of the six senses

Before discussing 'the flood,' we will first deal with 'the ocean.' This has 
two meanings:

1. the ocean of the six senses (_cakkhu bhikkhave purisassa samuddo_ etc, 
S.4.157) in which 'ocean currents' are the six sense objects. This is the ocean 
that the arahant has crossed (_atari cakkhu samuddaṃ_: crossed the ocean of 
the eye). This ocean with its six sense objects is elsewhere called 
'everything' (_cakkhuñceva rūpā ca... mano ca dhammā ca idaṃ vuccati 
bhikkhave sabbaṃ_ S.4.15). Therefore, in crossing the ocean, one crosses over 
everything.

2. the ocean [of the six sensuous objects]':

[quote, S.4.158]
____
There are visible objects known via the visual sense that are likeable, 
loveable, pleasing, agreeable, connected with sensuous pleasure, and charming. 
In the [terminology of the] Noble One's training system this is called the 
ocean.

_Santi bhikkhave cakkhuviññeyyā rūpā iṭṭhā kantā manāpā piyarūpā 
kāmūpasaṃhitā rajanīyā ayaṃ vuccati bhikkhave ariyassa vinaye samuddo._
____

[quote, S.4.158]
____
There are mentally known objects known via the mental sense that are likeable, 
loveable, pleasing, agreeable, connected with sensuous pleasure, and charming. 
In the [terminology of the] Noble One's training system this is called the 
ocean.

_Santi bhikkhave manoviññeyyā dhammā iṭṭhā kantā manāpā piyarūpā 
kāmūpasaṃhitā rajanīyā. Ayaṃ vuccati bhikkhave ariyassa vinaye 
samuddo._
____

==== The flood of birth, old age, and death

But in crossing the flood, what is crossed? The nature of the flood is revealed 
in the scriptures as follows:

1. In the _Pārāyanavaggo_, the Chapter on The Way to the Far Shore, Venerable 
Mettagū called it 'the flood of birth, old age, grief, and lamentation' 
(_oghaṃ jātijaraṃ sokapariddavañca_).

2. The bhikkhunī Upasamā told herself to cross the flood, the realm of death 
so hard to get beyond (_upasame tare oghaṃ maccudheyyaṃ suduttaraṃ_ 
Thī.v.10), where 'flood' therefore means the realm of death.

3. Venerable Kappa compared being afflicted by old age and death 
(_jarāmaccuparetānaṃ_) to standing in the middle of a lake when a very 
fearful flood has arisen (_majjhe sarasmiṃ tiṭṭhataṃ oghe jāte 
mahabbhaye_ Sn.v.1092) where 'flood' therefore means the flood of old age and 
death.

4. Venerable Nanda referred to those who had not overcome birth and old age 
(_nātariṃsu jātijaranti_ Sn.v.1080-1082) as 'not flood-crossers' 
(_anoghatiṇṇo_), where 'flood' therefore means the flood of birth and old 
age.

==== The flood of dukkhakkhandha

The scriptures show that 'old age and death' is an abbreviation for the whole 
mass of suffering (_dukkhakkhandha_), as follows:

1. In the _Mahānidāna Sutta_ the Buddha initially said birth produces old age 
and death, grief, lamentation, physical pain, psychological pain, and vexation 
(_jātipaccayā jarāmaraṇaṃ sokaparidevadukkhadomanassūpāyāsā_ 
D.2.56), and then said'birth produces old age and death' (_jātipaccayā 
jarāmaraṇan ti_). The full meaning of the condensed second statement is in 
the first statement.

2. In the _Parivīmaṃsana Sutta_ (S.2.80) a bhikkhu investigates 'the many 
and various kinds of suffering that arise in the world [headed by] old age and 
death' (_anekavidhaṃ nānappakārakaṃ dukkhaṃ loke uppajjati 
jarāmaraṇaṃ_). The bhikkhu then realises when there is birth, then old age 
and death come to be (_jātiyā sati jarāmaraṇaṃ hoti_). Here 'old age and 
death' stands for 'the many and various kinds of suffering that arise in the 
world [headed by] old age and death.'

3. Venerable Mettagū first called the flood 'birth, old age, grief, and 
lamentation' (_jātijaraṃ sokapariddavañca_ Sn.v.1052), he then said that 
one who had 'crossed this flood' (_oghamimaṃ atāri_) had overcome birth and 
old age (_atāri so jāti jaran ti_, Sn.v.1060) where 'birth and old age' 
stands for what he previously called birth, old age, grief, and lamentation.

==== Oghatiṇṇo and dukkhotiṇṇā

That 'flood' means 'flood of _dukkhakkhandha'_ is also evident in the 
association of _otiṇṇā_ and _tiṇṇā_. When young men take up the 
ascetic way of life, they do so with the thought:

____
'I am overwhelmed by suffering, overcome by suffering.

_dukkhotiṇṇā dukkhaparetā_
____

[quote, S.3.93; It.89]
____
... Perhaps an ending of this whole mass of suffering might be discerned!'

_appeva nāma imassa kevalassa dukkhakkhandhassa antakiriyā paññāyethā ti._
____

So _dukkhotiṇṇā_ is shown to mean _dukkhakkhandhotiṇṇā_. But 
flood-crossers are called _oghatiṇṇo_ (Sn.v.108), where _ogha_ corresponds 
to _dukkha_, and therefore to _dukkhakkhandha._

==== Oghataraṇa Sutta

In the _Oghataraṇa Sutta_ (S.1.1) a deva asks the Buddha how he crossed 'the 
flood' (_kathaṃ nu tvaṃ mārisa oghamatarī ti_) without explaining which 
flood. Bodhi says the four floods are meant (CDB p.341 n.1). But the deva 
clarified the issue by equating 'crossing the flood' to 'overcoming attachment 
to the world [of phenomena]':

[quote, S.1.1]
____
At long last, I see a Brahman who has realised the Untroubled who, without 
halting or overstraining, has overcome attachment to the world [of phenomena]

_Cirassaṃ vata passāmi brāhmaṇaṃ parinibbutaṃ +
Appatiṭṭhaṃ anāyūhaṃ tiṇṇaṃ loke visattikaṃ._
____

That the flood in the _Oghataraṇa Sutta_ can again be taken as the flood of 
_dukkhakkhandha_, in spite of the later reference to attachment, is proven by 
comparison with the _Mettagū Sutta_ where the same thing happens. Firstly 
Venerable Mettagū asked:

____
How do the wise cross the flood of birth, old age, grief, and lamentation?

_Kathaṃ nu dhīrā vitaranti oghaṃ jātijaraṃ sokapariddavañca_
____

The Buddha replied:

[quote, Sn.v.1052-3]
____
I shall explain the teaching to you, which is fathomable in this lifetime, 
which is not just hearsay, understanding which, one living the religious life, 
one who is mindful, would overcome attachment to the world [of phenomena].

_Kittayissāmi te dhammaṃ, diṭṭhe dhamme anitihaṃ +
Yaṃ viditvā sato caraṃ, tare loke visattikaṃ._
____

So when the deva asked about crossing the flood, he meant the flood of 
_dukkhakkhandha_. Both references show this is accomplished by overcoming 
attachment to the world of phenomena.

==== In conclusion: flood [of suffering]

In conclusion, 'ocean' means 'everything' and _ogha_ means 'the flood of the 
whole mass of suffering__.'__ But 'of the whole mass' is redundant, so we call 
it 'flood [of suffering].'

=== Illustrations

.Illustration
====
ogha

flood [of suffering]
====

The ascetic Sabhiya said to the Buddha:

____
You have left the darkness [of hell] and the flood [of suffering]...

_oghatamagā_
____

[quote, Sn.v.538-9]
____
You have reached the end of suffering, gone beyond suffering

_antagūsi pāragū dukkhassa._
____

Comment:

The commentary says _oghatamagā_ stands for _ogha-tamaṃ agā_ where darkness 
is paired with the flood of suffering. Like 'flood,' darkness in the scriptures 
means intense suffering, as follows:

1. Having passed on they go to darkness, falling headlong into hell
+
****
_pecca tamaṃ vajanti ye patanti sattā nirayaṃ avaṃsirā_ (Sn.v.248).
****

2. Defilement is the road to hell. Reaching [on rebirth] the plane of 
damnation, going from womb to womb, from darkness to darkness, such a bhikkhu 
goes to misery when he passes on.
+
****
_maggaṃ nirayagāminaṃ; vinipātaṃ samāpanno gabbhā gabbhaṃ tamā 
tamaṃ save tādisako bhikkhu pecca dukkhaṃ nigacchati_ (Sn.v.278).
****

3. How is a person heading from darkness to darkness? In this regard, some 
person has been reborn in a low family... after death he is reborn in the plane 
of sub-human existence, in the plane of misery, in the plane of damnation, or 
in hell.
+
****
_tamo hoti tamaparāyaṇo... nīce kule paccājāto hoti... parammaraṇā 
apāyaṃ duggatiṃ vinipātaṃ nirayaṃ upapajjati_ (A.2.85).
****

.Illustration
====
flood [of suffering]

[quote

S.1.142]
====

____
Seeing a sage who had crossed the flood [of suffering], the lady made merit 
leading to future happiness.

_Akāsi puññaṃ sukhamāyatikaṃ +
Disvā muniṃ brāhmaṇi oghatiṇṇan ti._
____

.Illustration
====
oghatiṇṇo

one who has crossed the flood [of suffering]
====

[quote, Th.v.633; S.1.3]
____
The bhikkhu who has overcome the five bonds [to individual existence] is called 
one who has crossed the flood [of suffering].

_Pañcasaṅgātigo bhikkhu oghatiṇṇo ti vuccati._
____

.Illustration
====
oghatiṇṇā

those who have crossed the flood [of suffering]
====

[quote, Sn.v.1082]
____
I do not say that all ascetics and Brahmanists are hemmed in by birth and old 
age. Whosoever have abandoned [attachment] in this world to what is seen, 
heard, sensed, [or cognised], and [adherence to] all observances and practices, 
and have abandoned [attachment to] all various bodily forms, and who, through 
profoundly understanding craving are free of perceptually obscuring states, 
these are men who have crossed the flood [of suffering], I declare.

_Nāhaṃ sabbe samaṇabrāhmaṇāse jātijarāya nivutā ti brūmi +
Ye sīdha diṭṭhaṃ vā sutaṃ mutaṃ vā silabbataṃ vāpi pahāya 
sabbaṃ +
Anekarūpampi pahāya sabbaṃ taṇhaṃ pariññāya anāsavāse +
Te ve narā oghatiṇṇā ti brūmi._
____

.Illustration
====
oghaṃ

flood [of suffering]
====

[quote, Sn.v.21]
____
I have crossed [to the Far Shore], reached the Far Shore, having eliminated the 
flood [of suffering].

_Tiṇṇo pāragato vineyya oghaṃ._
____

Comment:

Here the flood is not 'crossed.'

