== Opanayika

=== Renderings

- _opanayika_: personally applicable

- _opanayika_: personally significant

- _attūpanāyikaṃ_: with reference to oneself

- _attūpanāyikaṃ_: involving comparison with oneself

=== Introduction

==== Fit for bringing near

_Opanayika_ has long been rendered as 'leading onward' or 'leading to 
salvation.' But DOP says it means 'fit for bringing near, for taking to 
oneself; fit for making use of; deserving to be used,' and says it is derived 
from _upanaya_, which means 'bringing near; bringing near (to death); 
application.'

==== Applicable

Bodhi renders _opanayika_ as 'applicable' in accordance with the 
_Visuddhimagga_ (Vism.217) where he says 'the word is glossed by the gerundive 
_upanetabba_, "to be brought near, to be applied"' (CDB p.353 n.33).

==== Personally applicable; personally significant

The scriptures use _opanayika_ in two situations:

1. Firstly, regarding the teachings, where we call it 'personally applicable.' 
See Illustrations.

2. Secondly, regarding the elimination of attachment (_rāga_) and of previous 
karmically consequential conduct (_purāṇañca kammaṃ_). The text says the 
elimination of attachment and previous karmically consequential conduct is 
_opanayikā_. But 'elimination' cannot rationally be called 'applicable,' so we 
say 'personally significant.' This is in accordance with DOP's 'fit for taking 
to oneself; deserving to be used.'

[quote, A.1.221]
____
He undertakes no new karmically consequential conduct; as to previous 
karmically consequential conduct, he nullifies it by the gradual experience [of 
its consequences]. Its elimination is discernable in this lifetime, realisable 
in the here and now, intriguing, personally significant, to be realised by the 
wise for themselves.

_So navañca kammaṃ na karoti. Purāṇañca kammaṃ phussa phussa 
vyantīkaroti. Sandiṭṭhikā nijjarā akālikā ehipassikā opanayikā 
paccattaṃ veditabbā viññūhī'ti._
____

==== Attūpanāyiko: with/through reference to oneself

_Attūpanāyiko_ means either:

1. 'with reference to oneself,' or

2. 'involving comparison with oneself.'

See Illustrations.

=== Illustrations

.Illustration
====
opanayiko

personally applicable
====

____
On what grounds is the teaching fathomable in this lifetime, realisable in the 
here and now, intriguing, personally applicable, to be realised by the wise for 
themselves?

_kittāvatā nu kho bhante sandiṭṭhiko dhammo hoti akāliko ehipassiko 
opanayiko paccattaṃ veditabbo viññūhī ti?_
____

____
In this regard, in seeing a visible object via the visual sense a bhikkhu 
experiences the visible object and the attachment to the visible object. When 
there is attachment to visible objects in him, he discerns: 'There is 
attachment to visible objects in me.'

_Idhūpavāṇa bhikkhu cakkhunā rūpaṃ disvā rūpapaṭisaṃvedī ca hoti 
rūparāgapaṭisaṃvedī ca. Santañca ajjhattaṃ rūpesu rāgaṃ atthi me 
ajjhattaṃ rūpesu rāgo ti pajānāti yantaṃ upavāṇa bhikkhu cakkhunā 
rūpaṃ disvā rūpapaṭisaṃvedī ca hoti rūparāgapaṭisaṃvedī ca 
santañca ajjhattaṃ rūpesu rāgaṃ atthi me ajjhattaṃ rūpesu rāgo ti 
pajānāti._
____

[quote, S.4.41]
____
On these grounds is the teaching fathomable in this lifetime, realisable in the 
here and now, intriguing, personally applicable, to be realised by the wise for 
themselves.

_Evampi kho upavāṇa sandiṭṭhiko dhammo hoti akāliko ehipassiko 
opanayiko paccattaṃ veditabbo viññūhi._
____

.Illustration
====
opanayiko

personally applicable
====

____
On what grounds is the teaching fathomable in this lifetime, realisable in the 
here and now, intriguing, personally applicable, to be realised by the wise for 
themselves?

_sandiṭṭhiko dhammo sandiṭṭhiko dhammo'ti bho gotama vuccati 
kittāvatā nu kho bho gotama sandiṭṭhiko dhammo hoti akāliko ehipassiko 
opanayiko paccattaṃ veditabbo viññūhī ti._
____

____
One who is attached, overpowered, and overcome by attachment, is intent upon 
his own harm, upon the harm of others, upon the harm of both, and so 
experiences psychological pain and dejection.

_Ratto kho brāhmaṇa rāgena abhibhūto pariyādinnacitto attavyābādhāyapi 
ceteti paravyābādhāyapi ceteti ubhayavyābādhāyapi ceteti. Cetasikampi 
dukkhaṃ domanassaṃ paṭisaṃvedeti._
____

____
But if attachment be abandoned he is not intent upon his own harm, upon the 
harm of others, upon the harm of both, and thus does not experience 
psychological pain and dejection.

_Rāge pahīṇe nevattavyābādhāyapi ceteti. Na paravyābādhāyapi ceteti 
na ubhayavyābādhāyapi ceteti. Na cetasikaṃ dukkhaṃ domanassaṃ 
paṭisaṃvedeti._
____

____
One who is attached, overpowered, and overcome by attachment, misconducts 
himself by way of body, speech, and mind. But if attachment be abandoned he 
does not do so.

_Ratto kho brāhmaṇa rāgena abhibhūto pariyādinnacitto kāyena 
duccaritaṃ carati vācāya duccaritaṃ carati manasā duccaritaṃ carati 
rāge pahīṇe neva kāyena duccaritaṃ carati na vācāya duccaritaṃ 
carati na manasā duccaritaṃ carati._
____

____
One who is attached, overpowered, and overcome by attachment, does not discern 
according to reality his own well-being, nor that of others, nor that of both 
himself and others. But if attachment be abandoned he discerns this.

_Ratto kho brāhmaṇa rāgena abhibhūto pariyādinnacitto attatthampi 
yathābhūtaṃ nappajānāti paratthampi yathābhūtaṃ nappajānāti 
ubhayatthampi yathābhūtaṃ nappajānāti. Rāge pahīṇe attatthampi 
yathābhūtaṃ pajānāti paratthampi yathābhūtaṃ pajānāti ubhayatthampi 
yathābhūtaṃ pajānāti._
____

[quote, A.1.157-8]
____
On these grounds is the teaching fathomable in this lifetime, realisable in the 
here and now, intriguing, personally applicable, to be realised by the wise for 
themselves.

_Evampi kho brāhmaṇa sandiṭṭhiko dhammo hoti akāliko ehipassiko 
opanayiko paccattaṃ veditabbo viññūhī'ti._
____

.Illustration
====
opanayikā

personally significant
====

____
There are, headman, these three kinds of elimination that are discernable in 
this lifetime, realisable in the here and now, intriguing, personally 
significant, to be realised by the wise for themselves. What three?

_Tisso imā gāmaṇi sandiṭṭhikā nijjarā akālikā ehipassikā 
opanayikā paccattaṃ veditabbā viññūhi. Katamā tisso:_
____

____
Someone is attached, and because of attachment he is intent upon his own harm, 
upon the harm of others, upon the harm of both.

_Yaṃ ratto rāgādhikaraṇaṃ attavyābādhāyapi ceteti 
paravyābādhāyapi ceteti ubhayavyābādhāyapi ceteti_
____

____
When attachment is abandoned, he is not intent upon his own harm, or the harm 
of others, or the harm of both.

_rāge pahīne neva attavyābādhāyapi ceteti na paravyābādhāyapi ceteti na 
ubhayavyābādhāyapi ceteti._
____

[quote, S.4.339]
____
Its elimination is discernable in this lifetime, realisable in the here and 
now, intriguing, personally significant, to be realised by the wise for 
themselves.

_Sandiṭṭhikā nijjarā akālikā ehipassikā opanayikā paccattaṃ 
veditabbā viññūhi._
____

.Illustration
====
attūpanāyikaṃ

with reference to himself
====

[quote, Vin.3.91]
____
If a bhikkhu, though not recalling it, should claim with reference to himself a 
superhuman attainment of knowledge and vision that is worthy of the Noble Ones, 
saying "Thus I know; thus I see."..

_Yo pana bhikkhu anabhijānaṃ uttarimanussadhammaṃ attūpanāyikaṃ 
alamariyañāṇadassanaṃ samudācareyya Iti jānāmi iti passāmī ti...._
____

Comment:

The rule continues in a way that is not significant, as follows:

____
.'.. then, whether or not he is later interrogated about it, fallen and seeking 
purification, he says "Friends, though not knowing, I said 'I know'; though not 
seeing, I said 'I see.' I boasted vainly and falsely"; unless it was from 
over-estimation, he is pārājika, no longer in communion.

_tato aparena samayena samanuggāhiyamāno vā asamanuggāhiyamāno vā āpanno 
visuddhāpekkho evaṃ vadeyya Ajānam evaṃ āvuso avacaṃ jānāmi'; 
apassaṃ passāmi.' Tucchaṃ musā vilapin ti. Aññatra adhimānā ayampi 
pārājiko hoti asaṃvāso._
____

.Illustration
====
attūpanāyikaṃ

involving comparison with oneself
====

____
I will expound for your benefit a systematic exposition of the teaching that 
involves a comparison with oneself.

_Attūpanāyikaṃ vo gahapatayo dhammapariyāyaṃ desissāmī ti_
____

____
What is the systematic exposition of the teaching that involves a comparison 
with oneself?

_Katamo ca gahapatayo attūpanāyiko dhammapariyāyo:_
____

____
In this regard, householders, a noble disciple reflects thus: 'I am one who 
wishes to live, who does not wish to die; I desire happiness and loathe pain. 
Since I am one who wishes to live... and loathe pain, if someone were to take 
my life, that would not be agreeable and pleasing to me.

_idha gahapatayo ariyasāvako iti paṭisañcikkhati ahaṃ khosmi jīvitukāmo 
amaritukāmo sukhakāmo dukkhapaṭikkūlo. Yo kho maṃ jīvitukāmaṃ 
amaritukāmaṃ sukhakāmaṃ dukkhapaṭikkūlaṃ jīvitā voropeyya na me 
taṃ assa piyaṃ manāpaṃ_
____

____
Now if I were to take the life of another -- of one who wishes to live, who 
does not wish to die, who desires happiness and loathes pain -- that would not 
be agreeable and pleasing to the other either. What is disagreeable and 
displeasing to me is disagreeable and displeasing to the other too. How can I 
inflict upon another what is disagreeable and displeasing to me?'

_ahañceva kho pana paraṃ jīvitukāmaṃ. Sukhakāmaṃ 
dukkhapaṭikkūlaṃ jīvitā voropeyya parassapi taṃ assa appiyaṃ 
amanāpaṃ. Yo kho myāyaṃ dhammo appiyo amanāpo. Parassapeso dhammo appiyo 
amanāpo. Yo kho myāyaṃ dhammo appiyo amanāpo kathāhaṃ paraṃ tena 
saṃyojeyyanti_
____

[quote, S.5.354]
____
In reflecting thus, he himself abstains from killing, exhorts others to abstain 
from killing, and speaks in praise of abstaining from killing.

_So iti paṭisaṅkhāya attanā ca pāṇātipātā paṭivirato hoti. 
Parañca pāṇātipātā veramaṇiyā samādapeti. Pāṇātipātā 
veramaṇiyā ca vaṇṇaṃ bhāsati._
____

