== Oḷārika

=== Renderings

- _oḷārika_: gross

- _oḷārika_: gross material

- _oḷārika_: obvious

- _oḷārika_: self-evident

- _oḷārika_: less subtle

- _oḷārika_: less refined

- _oḷārika_: not particularly refined

- _oḷārika_: effortful

- _oḷārika_: morally unrefined

=== Illustrations

.Illustration
====
gross

[quote

M.3.18-9]
====

____
Whatever bodily form, past, future, or present, internal or external, gross or 
subtle, inferior or sublime, far or near

_Yaṃ kiñci rūpaṃ atītānāgatapaccuppannaṃ ajjhattaṃ vā bahiddhā 
vā oḷārikaṃ vā sukhumaṃ vā hīnaṃ vā paṇītaṃ vā yaṃ dūre 
santike vā._
____

.Illustration
====
gross

[quote

M.1.48]
====

____
Physical food, gross or subtle;

_kabaliṅkāro āhāro oḷāriko vā sukhumo._
____

.Illustration
====
gross

[quote

Vin.1.199]
====

____
What now if I allowed medicine for bhikkhus, both medicine itself as well as 
what could be regarded as medicine, which though it serves as nourishment in 
the world, could not be regarded as gross food?

_Kinnū kho ahaṃ bhikkhūnaṃ bhesajjaṃ anujāneyyaṃ yaṃ 
bhesajjañceva assa bhesajjasammatañca lokassa āhāratthañca phareyya na ca 
oḷāriko āhāro paññāyeyyā ti._
____

.Illustration
====
gross material

[quote

D.1.202]
====

____
Whenever the gross material acquired self is present, it is not reckoned as a 
mind-made material acquired self, nor an immaterial acquired self. It is 
reckoned only as a gross material acquired self on that occasion.

_yasmiṃ samaye oḷāriko attapaṭilābho hoti neva tasmiṃ samaye manomayo 
attapaṭilābho ti saṅkhaṃ gacchati. Na arūpo attapaṭilābho ti 
saṅkhaṃ gacchati. 'Oḷāriko attapaṭilābho'tveva tasmiṃ samaye 
saṅkhaṃ gacchati._
____

.Illustration
====
self-evident

____
In this regard

in seeing a visible object via the visual sense, there arises in a bhikkhu 
pleasure, or displeasure, or pleasure plus displeasure.
====

_cakkhunā rūpaṃ disvā uppajjati manāpaṃ uppajjati amanāpaṃ uppajjati 
manāpāmanāpaṃ._
____

____
He knows that 'This pleasure has arisen in me, this displeasure... this 
pleasure plus displeasure has arisen in me.

_uppannaṃ kho me idaṃ manāpaṃ uppannaṃ amanāpaṃ uppannaṃ 
manāpāmanāpaṃ_
____

____
And that is originated, self-evident, dependently arisen.

_saṅkhataṃ oḷārikaṃ paṭiccasamuppannaṃ_
____

[quote, M.3.299]
____
But this is peaceful, this is sublime, namely, detached awareness.

_Etaṃ santaṃ etaṃ paṇītaṃ yadidaṃ upekkhā ti._
____

.Illustration
====
self-evident

____
Some [ascetics and Brahmanists] proclaim that the state of awareness of 
nonexistence

limitless and imperturbable, where one perceives that there is [nowhere] 
anything at all, is the purest, highest, best, and greatest of those states of 
refined awareness, whether refined material states of awareness, or immaterial 
states of awareness, or states of refined awareness involving mental cognisance 
alone, or involving the external senses.
====

_Yā vā panetāsaṃ saññānaṃ parisuddhā paramā aggā anuttariyā 
akkhāyati yadi rūpasaññānaṃ yadi arūpasaññānaṃ yadi 
ekattasaññānaṃ yadi nānattasaññānaṃ natthi kiñci ti 
ākiñcaññāyatanaṃ eke abhivadanti appamāṇaṃ āneñjaṃ._
____

[quote, M.2.229-230]
____
But that [state of refined awareness] is originated and self-evident. And there 
is a ending of originated phenomena. Knowing the truth of this, seeing the 
deliverance [from originated phenomena] the Perfect One has gone beyond it.

_Tayidaṃ saṅkhataṃ oḷārikaṃ. Atthi kho pana saṅkhārānaṃ 
nirodho atthetanti iti viditvā tassa nissaraṇadassāvī tathāgato 
tadupātivatto._
____

.Illustration
====
obvious

[quote

S.5.259]
====

____
But though Venerable Ānanda was given such a broad hint by the Blessed One, 
such an obvious suggestion, he was unable to perceive it._

_Evampi kho āyasmā ānando bhagavatā oḷārike nimitte kayiramāne 
oḷārike obhāse kayiramāne nāsakkhi paṭivijjhituṃ._
____

.Illustration
====
less subtle

[quote

D.2.210]
====

____
Whenever Brahmā Sanaṅkumāra appears to the Tāvatiṃsā devas, he appears 
having created [for himself] a less subtle bodily form (_oḷārikaṃ 
attabhāvaṃ abhinimminitvā_) because his natural appearance 
(_pakativaṇṇo_) is not perceptible to the eye

_Yadā bhante brahmā sanaṅkumāro devānaṃ tāvatiṃsānaṃ pātubhavati 
oḷārikaṃ attabhāvaṃ abhinimminitvā pātubhavati. Yo kho pana bhante 
brahmuno pakativaṇṇo anabhisambhavanīyo so devānaṃ tāvatiṃsānaṃ 
cakkhupathasmiṃ._
____

.Illustration
====
less subtle

Hatthaka

the deva's son, approached the Blessed One, thinking, 'I will stand in the 
presence of the Blessed One,' but he sank down, collapsed, could not stand 
upright. Just as butter or oil when poured upon sand sinks down, sinks in, 
cannot abide.
====

[quote, A.1.279]
____
Then the Blessed One told him 'Create a less subtle bodily form, Hatthaka'

_oḷārikaṃ hatthaka attabhāvaṃ abhinimmināhī ti._
____

.Illustration
====
less refined

____
'Poṭṭhapāda

once the bhikkhu is possessed of that preliminary state of refined awareness, 
he proceeds from stage to stage till he reaches the highest state of refined 
awareness.
====

_Yato kho poṭṭhapāda bhikkhu idha sakasaññī hoti so tato amutra tato 
amutra anupubbena saññaggaṃ phusati._
____

____
Then, remaining in the highest state of refined awareness it occurs to him, 
'Intentionality is worse for me, being free of intentionality is better.

_Tassa saññagge ṭhitassa evaṃ hoti cetayamānassa me pāpiyo 
acetayamānassa me seyyo._
____

____
If I were to be intent upon or to aim [at anything further], these states of 
refined awareness that I have attained would cease and less refined states of 
refined awareness would arise in me. 

_Ahañceva kho pana ceteyyaṃ abhisaṅkhareyyaṃ imā ca me saññā 
nirujjheyyuṃ aññā ca oḷārikā saññā uppajjeyyuṃ._
____

____
How about if I were not to be intent upon or to aim [at anything further]?'

_Yannūnāhaṃ na ceva ceteyyaṃ na cābhisaṅkhareyyan ti._
____

____
So he is neither intent [upon anything], nor aims [at anything further].

_So na ceva ceteti na cābhisaṅkharoti._
____

____
And thus in him just these states of refined awareness cease, and other less 
refined states of refined awareness do not arise.

_Tassa acetayato anabhisaṅkharoto tā ceva saññā nirujjhanti aññā ca 
oḷārikā saññā na uppajjanti._
____

____
He attains to the ending [of originated phenomena].

_So nirodhaṃ phusati._
____

[quote, D.1.183-4]
____
And that, Poṭṭhapāda, is how the ending of successively refined states of 
refined awareness is attained in full consciousness.

_Evaṃ kho poṭṭhapāda anupubbābhisaññānirodhasampajānasamāpatti 
hoti._
____

.Illustration
====
not particularly refined

____
-- Moggallāna

friend, your [mental] faculties are serene, your countenance is pure and 
bright. Venerable MahāMoggallāna surely spent today in a peaceful abiding.
====

_vippasannāni kho te āvuso moggallāna indriyāni parisuddho mukhavaṇṇo 
pariyodāto santena nūnāyasmā mahāmoggallāno ajja vihārena vihāsī'ti_
____

[quote, S.2.275]
____
-- Friend, I spent the day in a not particularly refined abiding, but I had 
some discussion on the teaching [with the Blessed One].

_Oḷārikena kho ahaṃ āvuso ajja vihārena vihāsiṃ. Api ca me ahosi 
dhammī kathā ti._
____

Bodhi: "I spent the day in a gross dwelling, friend, but I did have some Dhamma 
talk."

.Illustration
====
effortful

It is just as if a man walking fast might ask himself why he is walking fast. 
Why not walk slowly? Then walking slowly

why not stand? Then standing, why not sit? Then sitting, why not lie down?
====

[quote, M.1.121]
____
In this way the man would substitute for each more effortful posture one that 
was less effortful.

_Evaṃ hi so bhikkhave puriso oḷārikaṃ oḷārikaṃ iriyāpathaṃ 
abhinivajjetvā sukhumaṃ sukhumaṃ iriyāpathaṃ kappeyya._
____

.Illustration
====
morally unrefined

____
There are three pathways to happiness discovered by the Blessed One who knows 
and sees [the nature of reality]

the second of which is for someone in whom the morally unrefined deeds of body, 
speech, and mind are unquelled
====

_oḷārikā kāyasaṅkhārā... vacīsaṅkhārā... cittasaṅkhārā 
appaṭippassaddhā honti_
____

Then he hears the noble teaching, and properly contemplates it and practises in 
conformity with it. By doing so:

[quote, D.2.214-5]
____
His morally unrefined deeds of body, speech, and mind are quelled

_oḷārikā kāyasaṅkhārā paṭippasasambhanti oḷārikā 
vacīsaṅkhārā paṭippassambhanti oḷārikā cittasaṅkhārā 
paṭippassambhanti._
____

