== Pacceti

=== Renderings

- _pacceti_: to believe in

- _pacceti_: to believe

- _pacceti_: to assume

- _pacceti_: to suppose

- _pacceti_: to realise

- _pacceti_: to rebound

- _pacceti_: to revert

- _pacceti_: to return

=== Illustrations

.Illustration
====
pacceti

believe in
====

____
He was a practitioner of water-purification. He believed in spiritual 
purification through [bathing in] water.

_Udakasuddhiko udakena parisuddhiṃ pacceti._
____

[quote, S.1.182-3]
____
Is it true, brahman, that you are a practitioner of water-purification? That 
you believe in spiritual purification through [bathing in] water?

_saccaṃ kira tvaṃ brāhmaṇa udakasuddhiko udakena parisuddhiṃ paccesi._
____

.Illustration
====
pacceti

believe in
====

____
He is superstitious. He believes in luck, not in the operation of the karmic 
mechanism.

_kotuhalamaṅgaliko hoti maṅgalaṃ pacceti no kammaṃ_
____

[quote, A.3.206]
____
He is not superstitious. He believes in the operation of the karmic mechanism, 
not in luck.

_akotuhalamaṅgaliko hoti kammaṃ pacceti no maṅgalaṃ._
____

.Illustration
====
paccesi

believe in
====

____
What type of Self do you believe in, Poṭṭhapāda?

_Kiṃ pana tvaṃ poṭṭhapāda attānaṃ paccesī ti._
____

[quote, D.1.185]
____
I believe in a gross material Self, material, made of the four great material 
phenomena feeding on physical food._

_oḷārikaṃ kho ahaṃ bhante attānaṃ paccemi rūpiṃ 
cātummahābhūtikaṃ kabaliṅkārāhārabhakkhanti._
____

.Illustration
====
pacceti

believe
====

[quote, Sn.v.840]
____
For some believe that spiritual purity is on account of one's view.

_diṭṭhiyā eke paccenti suddhiṃ_
____

Norman: 'Some do believe that purity is by means of view'

.Illustration
====
paccesi

assume
====

____
By whom was this being created? Where is the being's creator ? Where has the 
being arisen? Where does the being cease?

_Kenāyaṃ pakato satto kuvaṃ sattassa kārako +
Kuvaṃ satto samuppanno kuvaṃ satto nirujjhatī ti._
____

[quote, S.1.135]
____
But why do you assume 'a being'? That is just your acquiescence in wrong view 
&#8203;[of reality], Māra. This is nothing but a heap of originated phenomena. Here 
no being is found.

_Kinnu satto ti paccesi māradiṭṭhigatannu te +
Suddhasaṅkhārapuñjoyaṃ nayidha sattūpalabbhati._
____

.Illustration
====
paccethā

suppose
====

____
Yet although beings have such yearnings, desires, and aspirations, unlikeable, 
unloveable, and displeasing things increase, and likeable, loveable, and 
pleasing things diminish.

_Tesaṃ bhikkhave sattānaṃ evaṃ kāmānaṃ evaṃ chandānaṃ evaṃ 
adhippāyānaṃ aniṭṭhā akantā amanāpā dhammā abhivaḍḍhanti 
iṭṭhā kantā manāpā dhammā parihāyanti._
____

[quote, M.1.309]
____
Now what do you suppose is the reason for this?_

_Tatra tumhe bhikkhave kaṃ hetuṃ paccethā ti?._
____

.Illustration
====
paccesi

suppose
====

____
Do you remember it, Bhaddāli?

_sarasi tvaṃ bhaddālī ti_
____

____
No, bhante.

_No hetaṃ bhante_
____

____
What do you suppose is the reason for this?

_Tatra bhaddāli kaṃ hetuṃ paccesī ti_
____

[quote, M.1.445]
____
Bhante, I have long been one who did not fulfil the training in the Teacher's 
training system.

_So hi nūnāhaṃ bhante dīgharattaṃ satthusāsane sikkhāya 
aparipūrakārī ahosin ti._
____

.Illustration
====
paccenti

realise
====

[quote, S.5.344]
____
Those with faith [in the perfection of the Perfect One's transcendent insight], 
and virtue, serenity and vision of things [according to reality], in due course 
realise the happiness that is the culmination of the religious life.

_Yesaṃ saddhā ca sīlañca pasādo dhammadassanaṃ +
Te ve kālena paccenti brahmacariyogadhaṃ sukhan ti.._
____

.Illustration
====
paccenti

realise
====

[quote, A.3.329]
____
In due course they realise where suffering ceases.

_Te me kālena paccenti yattha dukkhaṃ nirujjhatī ti._
____

.Illustration
====
pacceti

rebound
====

[quote, S.1.13]
____
Whoever wrongs an innocent man, a pure person unblemished [by spiritual 
defilement], the demerit rebounds upon that same fool like fine dust thrown 
against the wind.

_Yo appaduṭṭhassa narassa dussati suddhassa posassa anaṅgaṇassa +
Tameva bālaṃ pacceti pāpaṃ sukhumo rajo paṭivātaṃ va khitto ti._
____

.Illustration
====
pacceti

revert
====

[quote, Sn.v.788]
____
&#8203;[A man might think:] 'I see the Purified, the Highest, the Unailing. A man's 
spiritual purity is on account of his vision.' Understanding [purity] in this 
way, knowing [what he sees] as 'the Highest,' and [thinking] 'I am a seer of 
the Purified,' he reverts to knowledge.

_Passāmi suddhaṃ paramaṃ arogaṃ, diṭṭhena saṃsuddhi narassa hoti +
Evābhijānaṃ paraman ti ñatvā, suddhānupassī ti pacceti ñāṇaṃ_
____

Norman: 'He believes that knowledge [leads to purity].'

.Illustration
====
pacceti

revert
====

[quote, Sn.v.800]
____
Amongst those in dispute he does not take sides. He does not revert to any 
dogmatic view whatsoever.

_Sa ve viyattesu na vaggasārī, diṭṭhimpi so na pacceti kiñci_
____

Norman: 'He does not fall back on any view at all.'

.Illustration
====
pacceti

return
====

[quote, Sn.v.803]
____
Gone to the Far Shore, one of such good qualities does not return.

_pāragato na pacceti tādī ti_
____

