== Paccaya

=== Renderings

- _paccaya_: necessary condition

- _paccaya_: necessity

- _paccaya_: reason

- _paccaya_: dependent on

- _paccaya_: due to

- _paccaya_: out of

- _paccaya_: in

- _paccaya_: on that account

_• paccayata_: conditionality

_• idappaccayata_: specific conditionality

=== Introduction

==== Paccaya: 'dependent on'

In some cases we have rendered _paccaya_ as 'dependent on.' For example:

[quote, M.1.262]
____
Dependent on birth, there arises old-age-and-death.

_Jātipaccayā jarāmaraṇan ti._
____

Others translate this as:

- Horner: Conditioned by birth is ageing and dying

- Bodhi: With birth as condition, ageing and death.

Norman translates _paccaya_ as 'because of':

[quote, Sn.v.735]
____
Whatever misery arises, all this is because of contact.

_yaṃ kiñci dukkhaṃ sambhoti sabbaṃ phassapaccayā ti._
____

PED says: 'literally resting on, falling back on, foundation; cause, motive 
etc. 1. support, requisite, means, stay. 2. reason, cause, ground, motive, 
means, condition.' It says ablative _paccayā_ means 'of, through, by reason 
of, caused by.'

==== Abstract formula of dependent origination

That _paccaya_ means dependent can be seen in abstract formula of dependent 
origination, as follows:

[quote, S.2.70]
____
When there is this, that comes to be. With the arising of this, that arises. 
Without this, that does not come to be. With the ending of this, that ceases.

_iti imasmiṃ sati idaṃ hoti imassuppādā idaṃ uppajjati imasmiṃ asati 
idaṃ na hoti imassa nirodhā idaṃ nirujjhati._
____

If this formula is applied to _jātipaccayā jarāmaraṇan ti_ it leads to the 
following statements:

- When there is birth, old age and death come to be. With the arising of birth, 
old age and death arise. Without birth, old age and death do not come to be. 
With the ending of birth, old age and death ceases.

This well supports us rendering _jātipaccayā jarāmaraṇan ti_ as 'Dependent 
on birth, there arises old-age-and-death,' though other translations are 
clearly possible.

=== Illustrations

.Illustration
====
paccayaṃ

necessary condition
====

[quote, S.5.215]
____
'There has arisen in me this faculty of physical-plus-psychological neutral 
experience. That arises with grounds, with a source, with originative factors, 
with necessary conditions. It would be impossible for that faculty of 
physical-plus-psychological neutral experience to arise without grounds, 
without a source, without originative factors, without necessary conditions.'

_uppannaṃ kho me idaṃ upekkhindriyaṃ. Tañca kho sanimittaṃ 
sanidānaṃ sasaṅkhāraṃ sappaccayaṃ. Taṃ vata animittaṃ anidānaṃ 
asaṅkhāraṃ appaccayaṃ upekkhindriyaṃ uppajjissatī ti netaṃ 
ṭhānaṃ vijjati._
____

.Illustration
====
paccayo

necessary condition
====

[quote, S.2.13]
____
The existential nourishment of a stream of sense consciousness is a necessary 
condition for future renewed states of individual existence and rebirth.

_viññāṇāhāro āyatiṃ punabbhavābhinibbattiyā paccayo._
____

.Illustration
====
paccayānaṃ

necessary conditions
====

[quote, Ud.1]
____
When profound truths become manifest to the vigorous, meditative Brahman, then 
all his unsureness [about the significance of the teaching] disappears, for he 
knows the destruction of necessary conditions.

_Yadā have pātubhavanti dhammā ātapino ātāpino jhāyato brāhmaṇassa +
Athassa kaṅkhā vapayanti sabbā yato khayaṃ paccayānaṃ avedī ti._
____

.Illustration
====
paccayaṃ

necessary condition
====

[quote, S.4.68]
____
When advertence to the visual field has arisen dependent on a necessary 
condition that is unlasting, how could it be lasting?

_Aniccaṃ kho pana bhikkhave paccayaṃ paṭiccasamuppannaṃ 
cakkhuviññāṇaṃ kuto niccaṃ bhavissati._
____

.Illustration
====
paccayā

necessary conditions
====

____
Three necessary conditions for the persistence of the liberation [from 
perceptually obscuring states] by focusing upon the unabiding [phenomenon]:

_Tayo kho āvuso paccayā animittāya cetovimuttiyā ṭhitiyā_
____

____
not focusing upon any abiding phenomenon

_sabbanimittānañca amanasikāro_
____

____
focusing upon the unabiding phenomenon,

_animittāya ca dhātuyā manasikāro_
____

[quote, M.1.297]
____
a prior aspiration [for its persistence]

_pubbeva abhisaṅkhāro._
____

.Illustration
====
paccayā

necessary conditions
====

[quote, M.1.258]
____
Without necessary conditions there is no arising of _viññāṇa_

_aññatra paccayā natthi viññāṇassa sambhavo ti._
____

.Illustration
====
paccayaṃ

necessary condition
====

____
Fire is reckoned by the necessary condition dependent upon which it burns.

_yaññadevāpaccayaṃ paṭicca aggi jalati tena teneva saṅkhaṃ gacchati_
____

____
When fire burns because of logs it is reckoned as a log fire

_kaṭṭhañca paṭicca aggi jalati kaṭṭhaggiteva saṅkhaṃ gacchati_
____

[quote, M.1.259-230]
____
or on woodchips, a woodchip fire

_Sakalikañca paṭicca aggi jalati sakalikaggiteva saṅkhaṃ gacchati._
____

.Illustration
====
paccayo

necessary condition
====

[quote, M.3.17]
____
The four great material phenomena are the indispensible and necessary 
conditions by which the aggregate of bodily form is to be discerned._

_Cattāro kho bhikkhu mahābhūtā hetu cattāro mahābhūtā paccayo 
rūpakkhandhassa paññāpanāya._
____

.Illustration
====
paccaya

necessities
====

[quote, Vin.4.102]
____
A four-month invitation [to ask] for necessities can be accepted by a bhikkhu 
who is not ill.

_Agilānena bhikkhunā cātumāsapaccayapavāraṇā sāditabbā._
____

[quote, Vin.4.102]
____
A four-month invitation [to ask] for necessities can be accepted by a bhikkhu 
who is not ill means: an invitation [to ask] for necessities [that are needed] 
when ill may be accepted.

_Agilānena bhikkhunā cātumāsappaccayapavāraṇā sāditabbā ti: 
gilānapaccayapavāraṇā sāditabbā._
____

.Illustration
====
paccayata

conditionality
====

[quote, M.1.167]
____
So that for beings who take pleasure and delight in clinging, finding 
satisfaction in clinging, this were a matter difficult to see, that is to say 
dependent origination with specific conditionality

__ālayarāmāya kho pana pajāya ālayaratāya ālayasammuditāya duddasaṃ 
idaṃ ṭhānaṃ yadidaṃ idappaccayatāpaṭiccasamuppādo._
____

.Illustration
====
paccayata

conditionality
====

[quote, S.2.25]
____
And what is dependent origination? Old-age-and-death arises dependent on birth. 
Whether or not there is an arising of Perfect Ones, there persists that 
phenomenon, that stability in the nature of reality, that orderliness in the 
nature of reality, that specific conditionality.

_Katamo ca bhikkhave paṭiccasamuppādo? Jātipaccayā bhikkhave 
jarāmaraṇaṃ uppādā vā tathāgatānaṃ anuppādā vā tathāgatānaṃ 
ṭhitāva sā dhātu dhammaṭṭhitatā dhammaniyāmatā idapaccayatā._
____

.Illustration
====
paccayata

conditionality
====

____
Thus far the round of rebirth revolves and personal existence is to be 
discerned,

_ettāvatā vaṭṭaṃ vattati itthattaṃ paññāpanāya_
____

____
namely denomination-and-bodily-form together with the stream of sense 
consciousness,

_yadidaṃ nāmarūpaṃ saha viññāṇena_
____

[quote, D.2.63-4]
____
which continue through mutual conditionality.

_aññamaññapaccayatāya pavattati._
____

.Illustration
====
paccayo

reason
====

[quote, A.4.68-70]
____
This is the cause and reason why doubt [about the significance of the teaching] 
does not arise in the noble disciple on account of the unexplained issues.

_Ayaṃ kho bhikkhu hetu ayaṃ paccayo yena sutavato ariyasāvakassa 
vicikicchā nuppajjati avyākatavatthusūti._
____

.Illustration
====
paccayo

reason
====

[quote, A.2.167]
____
This is the cause and reason for some beings here not realising the Untroubled 
in this lifetime.

_Ayaṃ kho āvuso ānanda hetu ayaṃ paccayo yena midhekacce sattā 
diṭṭheva dhamme na parinibbāyantī ti._
____

.Illustration
====
paccayo

reason
====

[quote, A.4.439]
____
What now is the cause and reason that my mind does not become energised, 
serene, settled, and intent upon the practice of unsensuousness, though I see 
it as peaceful.

_ko nu kho hetu ko paccayo yena me nekkhamme cittaṃ na pakkhandati 
nappasīdati na santiṭṭhati na vimuccati (read as adhimuccati. See IGPT sv 
Adhimuccati) etaṃ santanti passato._
____

.Illustration
====
paccayā

reasons
====

____
Eight causes and reasons for the ruination of families:

_Aṭṭha kho gāmaṇī hetu aṭṭha paccayā kulānaṃ upaghātāya_
____

[quote, S.4.324]
____
Families are ruined due to the king, thieves, fire, flooding, things getting 
lost, mismanagement, a squanderer in the family, unlastingness

_rājato... corato... aggito... udakato vā kulāni upaghātaṃ gacchanti... 
nihitaṃ vā nādhigacchanti... duppayuttā vā kammantaṃ jahanti... 
kulānaṃ vā kulaṅgāro uppajjati yo te bhoge vikirati vidhamati 
viddhaṃseti aniccatāyeva aṭṭhamī ti._
____

.Illustration
====
paccayā

dependent on
====

[quote, Sn.v.731]
____
Whatever suffering arises, all of it arises dependent on karmically 
consequential deeds.

_Yaṃ kiñci dukkhaṃ sambhoti sabbaṃ saṅkhārapaccayā._
____

Comment:

_Saṅkhārā_ here is in the context of _paṭiccasammupāda._

.Illustration
====
paccayā

dependent on
====

____
Individual existence arises dependent on grasping.

_tassūpādānapaccayā bhavo_
____

[quote, S.3.14]
____
Birth arises dependent on individual existence;

_bhavapaccayā jāti._
____

.Illustration
====
paccayā

dependent on
====

[quote, S.3.83]
____
In regard to the core of the religious life, they are no longer dependent on 
others

_Yo sāro brahmacariyassa tasmiṃ aparapaccayā._
____

.Illustration
====
paccayo

dependent on
====

[quote, M.1.234-5]
____
He abides no longer dependent on others regarding the [understanding of the] 
Teacher's training system.

_aparappaccayo satthusāsane viharatī ti._
____

.Illustration
====
paccayā

due to
====

[quote, M.1.303]
____
In arousing desire for supreme deliverance [from perceptually obscuring 
states], psychological pain arises due to desire.

_Iti anuttaresu vimokkhesu pihaṃ upaṭṭhāpayato uppajjati pihappaccayā 
domanassaṃ._
____

.Illustration
====
paccayā

due to
====

[quote, M.3.287]
____
Whatever sense impression that arises due to visual sensation -- whether 
pleasant, unpleasant, or neutral.

_yampidaṃ cakkhusamphassapaccayā uppajjati vedayitaṃ sukhaṃ vā 
dukkhaṃ vā adukkhamasukhaṃ vā._
____

.Illustration
====
paccayā

due to
====

• When those ascetics and Brahmanists who are eternalists proclaim the 
eternity of an [absolute] Selfhood and the world [of beings] in four ways, that 
is simply due to sensation +
_Tatra bhikkhave ye te samaṇabrāhmaṇā sassatavādā sassataṃ 
attānañca lokañcapaññapenti catūhi vatthūhi tadapi phassapaccayā_ 
(D.1.40).

==== Illustration:paccayā, due to

[quote, M.1.361]
____
Whereas vexatious and anguishing perceptually obscuring states would arise due 
to killing, there are no vexatious and anguishing perceptually obscuring states 
in abstaining from it.

_ye ca pāṇātipātapaccayā uppajjeyyuṃ āsavā vighātapariḷāhā 
pāṇātipātā paṭiviratassa evaṃsa te āsavā vighātapariḷāhā na 
honti._
____

.Illustration
====
paccayā

due to
====

[quote, A.2.196-7]
____
Those vexatious and anguishing perceptually obscuring states that arise due to 
mental endeavour

_ye manosamārambhapaccayā uppajjanti āsavā vighātapariḷāhā._
____

.Illustration
====
paccayā

out of
====

[quote, D.3.88]
____
Out of [sensuous] passion they engaged in sexual intercourse.

_Te pariḷāhapaccayā methunaṃ dhammaṃ paṭiseviṃsu._
____

.Illustration
====
paccayā

in
====

• One directs one's mind to acquire what has not yet been acquired, thinking, 
'May the visual sense and visible objects be thus in the future.' In directing 
one's mind thus, one longs for it. +
_iti me cakkhuṃ siyā anāgatamaddhānaṃ iti rūpāti appaṭiladdhassa 
paṭilābhāya cittaṃ paṇidahati. Cetaso paṇidhānapaccayā 
tadabhinandati_ (M.3.195-6).

.Illustration
====
paccayā

on that account
====

[quote, Th.v.719]
____
Do what you have to do with my body, as you wish. There will be neither hatred 
nor love by me [of you] about that [or] on that account.

_Yaṃ vo kiccaṃ sarīrena taṃ karotha yadicchatha +
Na me tappaccayā tattha doso pemañca hehiti._
____

