== Pacchāpuresaññī

=== Renderings

- _pacchāpuresaññī_: perceiving the constant nature of reality

- _pacchāpuresaññā_: the perception of the constant nature of reality

=== Introduction

==== Pacchāpuresaññī: background

_Pacchāpuresaññī_ is a form of meditation that occurs as part of the 
development of the four paths to psychic power (_catusu iddhipādesu_). It 
therefore leads to both the attainment of various kinds of psychic power 
(_anekavihitaṃ iddhividhaṃ_) and the destruction of perceptually obscuring 
states (_āsavānaṃ khayā_, S.5.282).

It was also a meditation taught to Venerable MahāMoggallāna to overcome 
torpor, to be used in conjunction with walking meditation:

[quote, A.4.87]
____
Perceiving the constant nature of reality, concentrate on pacing back and 
forth, your senses inwardly immersed, your mind not straying outwards. It is 
possible that by abiding in this way, that the torpor will be abandoned

_pacchāpuresaññī caṅkamaṃ adhiṭṭheyyāsi antogatehi indriyehi 
abahigatena mānasena. Ṭhānaṃ kho panetaṃ vijjati yaṃ te evaṃ 
viharato taṃ middhaṃ pahīyetha._
____

This meditation is analysed in the commentary, but Bodhi says its 'explanation 
sounds strained' (CDB p.1946 n.272).

==== Pacchā and pura: physically behind and in front

One problem is that _pacchā_ and _pura_ can refer to either space or time. For 
example, it is an offence for the one who is walking behind on a path 
(_pacchato gacchanto_) to explain the teaching to someone walking in front 
(_purato gacchantassa_) (Vin.4.205). According to this, _pacchāpuresaññī_ 
would involve meditating on 'what is physically behind and in front.'

==== Pacchā and pura: past and future

But _pacchā_ and _pura_ can also refer to time:

1. 'First' and 'afterwards': one can ridicule others of saying first what they 
should have said afterwards, or afterwards what they should have said first 
(_pure vacanīyaṃ pacchā avaca. Pacchā vacanīyaṃ pure avaca_ D.1.8).

2. 'Past' and 'what is in the future': some people wish for what is in the 
future or the past, longing for present and former pleasures (_pacchā pure 
vāpi apekkhamānā ime va kāme purime va jappaṃ_ Sn.v.773).

==== Yathā pure tathā pacchā

The term _pacchāpuresaññī_ is explained by the reflection _yathā pure 
tathā pacchā; yathā pacchā tathā pure._ If we take _pacchā_ and _pura_ as 
referring to time, it leads to the following translation:

[quote, S.5.277]
____
He abides perceiving the constant nature of reality: 'As what is past, so what 
is to come; as what is to come, so what is past.'

_pacchāpuresaññī ca viharati: yathā pure tathā pacchā yathā pacchā 
tathā pure._
____

This is further explained as follows:

[quote, S.5.277]
____
And how does a bhikkhu abide perceiving the constant nature of reality: 'As 
what is past, so what is to come; as what is to come, so what is past'? In this 
regard, the perception of the constant nature of reality is correctly grasped 
by the bhikkhu, correctly contemplated, correctly pondered, correctly 
penetrated by penetrative discernment.

_Kathañca bhikkhave bhikkhu pacchāpure saññī ca viharati? Yathā pure 
tathā pacchā yathā pacchā tathā pure. Idha bhikkhave bhikkhuno pacchā 
pure saññā suggahitā hoti sumanasikatā sūpadhāritā suppaṭividdhā 
paññāya._
____

==== Sāriputta: either later or sooner

The last passage should be compared to Venerable Sāriputta saying:

[quote, Th.v.1004]
____
Either way this [life ends in] death, not no death, either later or sooner.

_Ubhayenamidaṃ maraṇameva nāmaraṇaṃ pacchā vā pure vā._
____

This supports our saying that _pacchāpuresaññī_ means the perception of the 
constant nature of reality. The near future and the distant future have the 
same mortal nature. In this respect the present is no different from any other 
time period.

==== Pārājika recitation: 'defeated' until the time of his death

The same conclusion can be drawn from the Pārājika recitation, which 
concludes that a bhikkhu who commits a pārājika offence is no longer in 
communion with the bhikkhus:

• 'The four rules that merit expulsion have been recited. If a bhikkhu 
commits any of them, he is no longer in communion with the bhikkhus. As in the 
near future, so in the distant future, he is expelled, not in communion' +
☸ _Uddiṭṭhā kho āyasmanto cattāro pārājikā dhammā. Yesaṃ bhikkhu 
aññataraṃ vā aññataraṃ vā āpajjitvā na labhati bhikkhuhi saddhiṃ 
saṃvāsaṃ yathā pure tathā pacchā pārājiko hoti asaṃvāso_ 
Vin.3.109).

This illustrates 'the constant nature of reality': the bhikkhu's status as 
'expelled' is the same from the time of the offence until the time of his 
death: he cannot be reinstated.

==== Comparing present past and future in the scriptures

The idea of comparing the present to the past and the future is 
well-established in the scriptures. For instance:

[quote, M.3.18-9]
____
Whatever bodily form, past, future, or present... one should see all bodily 
form with perfect penetrative discernment as this is "not [in reality] mine" etc

_Yaṃ kiñci rūpaṃ atītānāgatapaccuppannaṃ ajjhattaṃ vā bahiddhā 
vā oḷārikaṃ vā sukhumaṃ vā hīnaṃ vā paṇītaṃ vā yaṃ dūre 
santike vā sabbaṃ rūpaṃ n'etaṃ mama n'eso'hamasmi na me so attā ti._
____

[quote, M.3.219]
____
Formerly as well as now all these visible objects are unlasting

_pubbe ceva rūpā etarahi ca sabbe te rūpā aniccā._
____

==== Dhammaṭṭhitatā: comparison

[quote, S.2.25]
____
And what is dependent origination? Old-age-and-death arises dependent on birth. 
Whether or not there is an arising of Perfect Ones, there persists that 
phenomenon, that stability in the nature of reality, that orderliness in the 
nature of reality, that specific conditionality.

_Katamo ca bhikkhave paṭiccasamuppādo? Jātipaccayā bhikkhave 
jarāmaraṇaṃ uppādā vā tathāgatānaṃ anuppādā vā tathāgatānaṃ 
ṭhitāva sā dhātu dhammaṭṭhitatā dhammaniyāmatā idapaccayatā._
____

[quote, A.1.286]
____
Whether or not there is an arising of Perfect Ones, there persists that 
phenomenon, that stability in the nature of reality, that orderliness in the 
nature of reality, [namely] the unlastingness of all originated phenomena.

_Uppādā vā bhikkhave tathāgatānaṃ anuppādā vā tathāgatānaṃ 
ṭhitāva sā dhātu dhammaṭṭhitatā dhammaniyāmatā sabbe saṅkhārā 
aniccā ti._
____

==== Conclusion

The reflection on _pacchāpuresaññī_ suggests that one should contemplate 
the constant nature of reality. Although reality is inconstant, its nature is 
constant.

=== Illustrations

.Illustration
====
pacchāpuresaññī

perceiving the constant nature of reality
====

[quote, S.5.277]
____
And he abides perceiving the constant nature of reality: 'As what is past, so 
what is to come; as what is to come, so what is past; as below, so above; as 
above, so below; as by day, so at night; as at night, so by day.' Thus with an 
attitude open and unclouded, he makes his mind radiant.

_pacchāpuresaññī ca viharati: yathā pure tathā pacchā yathā pacchā 
tathā pure yathā adho tathā uddhaṃ yathā uddhaṃ tathā adho yathā 
divā tathā rattiṃ yathā rattiṃ tathā divā Iti vivaṭena cetasā 
apariyonaddhena sappabhāsaṃ cittaṃ bhāveti._
____

COMMENT

- 'As below, so above,' as explained in the _Vibhaṅga Sutta_ (S.5.277), means 
one reviews bodies from head to toe as being full of various foul things (_idha 
bhikkhave bhikkhu imameva kāyaṃ uddhaṃ pādatalā adho kesamatthakā 
tacapariyantaṃ pūraṃ nānappakārassa asucino paccacekkhati_).

- 'As by day, so by night,' says the _Vibhaṅga Sutta_, means one practises 
the meditation similarly, during the day and during the night.

