== Pahitatta

=== Renderings

- _pahitatta_: resolute

- _pahitatta_: resolutely

- _pahitatta_: resolutely applied [to the practice]

- _pahitatta_: resolutely applied [to inward striving]

=== Introduction

==== Padahati and pahitatta

_Padahati_ means 'to strive', for example:

[quote, D.2.312]
____
In this regard a bhikkhu stirs up eagerness, endeavours, applies energy, exerts 
his mind, and strives to prevent the arising of unarisen unvirtuous, 
spiritually unwholesome factors.

_Idha bhikkhave bhikkhu anuppannānaṃ pāpakānaṃ akusalānaṃ 
dhammānaṃ anuppādāya chandaṃ janeti vāyamati viriyaṃ ārabhati 
cittaṃ paggaṇhāti padahati._
____

Although _pahita_ is the past participle of _padahati_, it only occurs in the 
compound _pahitatta_. The relationship between the _padahati_ and _pahita_ can 
be seen in the following quote:

____
Enthusiastically applying himself [to the teaching], he scrutinises [it].

_ussahitvā tuleti_
____

____
... Having scrutinised [it], he strives [to practise it].

_tulayitvā padahati_
____

[quote, M.1.480]
____
... Being resolutely applied [to the practice] he realises with his very being 
the supreme truth, and he sees [the nature of reality] having penetrated it 
with discernment.

_pahitatto samāno kāyena ceva paramaṃ saccaṃ sacchikaroti paññāya ca 
naṃ paṭivijjha passati._
____

The -_atta_ suffix is therefore shown to be redundant. For further notes see 
IGPT sv _Attā_.

==== Pahitatta: renderings of the -atta suffix

We have noted that the past participle of _padahati_ occurs in the compound 
_pahitatta_ ('strived self'). The PED says it occurs only in this compound, 
i.e. there is no word _pahita_. In their translations, Horner, Norman, and PED 
attempt to incorporate the _atta_ suffix. See below. Like Bodhi, we ourselves 
regard the -_atta_ suffix as redundant. The same redundancy is seen also in 
_sukhitattā_ (May they be happy, _bhavantu sukhitattā,_ Sn.v.145) and 
_samāhitatto_ (inwardly collected, S.1.169). For further notes, see Glossary 
sv _Attā_.

[quote, Horner, M.1.207]
____
living diligent, ardent, self-resolute

_appamattā ātāpino pahitattā viharāmā._
____

[quote, Norman, Sn.v.432]
____
My self is thus intent [upon striving]

_Evaṃ maṃ pahitattampi._
____

[quote, Norman, Sn.v.961]
____
for a bhikkhu with intent self

_pahitattassa bhikkhuno._
____

[quote, PED sv _Pahita_, S.4.145]
____
resolute will

_pahitatta._
____

[quote, Bodhi, M.1.207]
____
abide diligent, ardent, and resolute.

_appamattā ātāpino pahitattā viharāmā._
____

==== Pahitatta: qualifiers

_Pahitatta_ often occurs in the scriptures without qualification. We consider 
it to be an abbreviation that should be parenthesised in translation according 
to suttas where it is linked to some qualifier. In the following quotes it is 
linked to inward striving (_padhāna_) and 'practising as I instructed him' 
(_yathā mayānusiṭṭhaṃ tathā paṭipajjamāno_). We usually choose to 
render it in accordance with the second quote as 'resolutely applied [to the 
practice]' (i.e. 'as I instruct him'), because the first quote refers to the 
Buddha's practice before his enlightenment, that is, before the discovery of 
the teaching and the practice of the teaching.

[quote, Sn.v.425-6]
____
While I was nearby the Nerañjara River, resolutely applied to inward striving.

_Taṃ maṃ padhānapahitattaṃ nadiṃ nerañjaraṃ pati._
____

[quote, A.5.86]
____
My disciple who abides diligently, vigorously, and resolutely applied [to the 
practice] for one night and day, practising as I instructed him, might 
experience exclusively happiness for a hundred years.

_Idha mama sāvako... ekaṃ rattindivaṃ appamatto ātāpī pahitatto 
viharanto yathā mayānusiṭṭhaṃ tathā paṭipajjamāno satampi vassāni 
ekanta sukhapaṭisaṃvedī vihareyya._
____

==== Translations

Our translations of the passages above are therefore:

[quote, M.1.207]
____
we abide diligently, vigorously, and resolutely applied [to the practice]

_appamattā ātāpino pahitattā viharāmā._
____

[quote, i.e. before enlightenment, Sn.v.432]
____
I am thus resolutely applied [to inward striving].

_Evaṃ maṃ pahitattampi._
____

[quote, Sn.v.961]
____
resolute bhikkhu's

_pahitattassa bhikkhuno._
____

[quote, S.4.145]
____
resolutely applied [to the practice].

_pahitatto._
____

==== Similar issue with Ātāpī

We have made similar comments about _Ātāpī_ (sv _Ātāpī_). _Ātāpī_ 
likewise occurs in the scriptures without qualification. We consider _ātāpī_ 
to be an abbreviation to be parenthesised in translation, and we therefore 
render it as 'vigorously applied [to the practice]':

=== Illustrations

.Illustration
====
pahitatto

resolutely applied [to the practice]
====

[quote, A.5.86]
____
My disciple who abides diligently, vigorously, and resolutely applied [to the 
practice] for one night and day, practising as I instructed him, might 
experience exclusively happiness for a hundred years.

_Idha mama sāvako... ekaṃ rattindivaṃ appamatto ātāpī pahitatto 
viharanto yathā mayānusiṭṭhaṃ tathā paṭipajjamāno satampi vassāni 
ekanta sukhapaṭisaṃvedī vihareyya._
____

.Illustration
====
pahitatto

resolutely applied [to the practice]
====

[quote, S.4.145]
____
Bhante, it would be good if the Blessed One would explain the teaching to me in 
brief, so that, having heard the teaching from the Blessed One, I might abide 
alone, withdrawn [from human fellowship, sensuous pleasures, and spiritually 
unwholesome factors], diligently, vigorously, and resolutely applied [to the 
practice].

_sādhu me bhante bhagavā saṅkhittena dhammaṃ desetu yamahaṃ bhagavato 
dhammaṃ sutvā eko vūpakaṭṭho appamatto ātāpī pahitatto vihareyyanti._
____

.Illustration
====
pahitattam

resolutely applied [to inward striving]
====

[quote, Sn.v.432]
____
'Faith, energy, and wisdom are found in me [regarding the development of 
spiritually wholesome factors]. Why do you ask about life when I am thus 
resolutely applied [to inward striving].

_Atthi saddhā tathā viriyaṃ paññā ca mama vijjati +
Evaṃ maṃ pahitattampi kiṃ jīvamanupucchasi._
____

Comment:

This is spoken before the discovery of the teaching, so before the practice of 
the teaching.

.Illustration
====
pahitattassa

resolute
====

[quote, Sn.v.961]
____
What should be his manner of speech? What his sphere of personal application in 
this world? What should be that resolute bhikkhu's observances and practices?

_Kyāssa vyappathayo assu kyāssassu idha gocarā +
Kāni sīlabbatānāssu pahitattassa bhikkhuno._
____

.Illustration
====
pahitattā

resolute
====

The diligent and resolute practisers of my training system will go without your 
approval where, having gone, they will not grieve.

• _Te appamattā pahitattā mama sāsanakārakā +
Akāmā te gamissanti yattha gantvā na socare_ (Sn.v.445).

.Illustration
====
pahitattassa

resolutely
====

[quote, Sn.p.140]
____
For a bhikkhu who abides properly considering pairs [of teachings] in this way, 
diligently, vigorously, and resolutely, one of two fruits can be expected.

_Evaṃ sammā dvayatānupassino kho bhikkhave bhikkhuno appamattassa ātāpino 
pahitattassa viharato dvinnaṃ phalānaṃ aññataraṃ phalaṃ 
pāṭikaṅkhaṃ._
____

