== Pajānāti; Paññā

=== Renderings

- _pajānāti_: to discern

- _pajānāti_: to know that

- _pajānāti_: to understand how

- _paññā_: wisdom

- _paññā_: penetrative discernment

- _pañña_: one who knows that

- _pañña_: one of wisdom

- _paññavā_: blessed with penetrative discernment

- _duppañña_: void of penetrative discernment

=== Introduction

==== Pajānāti: three meanings

We render _pajānāti_ as either:

1. to 'discern'

2. to 'know that'

3. to 'understand how'

For examples, see Illustrations, grouped accordingly.

==== Paññā: wisdom or penetrative discernment

_Paññā_ is etymologically and functionally related to _pajānāti._ Where it 
linked to conduct of body and speech we call it wisdom. Where it is linked to 
conduct of mind we call it penetrative discernment.

==== Paññā: 'wisdom' or 'one who is wise'

When _paññā_ is linked to a person we usually call it wisdom, especially if 
it is:

1. given a prefix like _mahā-_ or _bhūri-_ e.g. _bhūripañño_

2. accompanied by terms _paṇḍito_ or _mahāpurisa_ e.g. _paṇḍito 
mahāpañño_

For example:

[quote, A.2.179]
____
One who is wise, one of great wisdom, is not intent upon his own harm, the harm 
of others, the harm of both.

_Idha bhikkhu paṇḍito mahāpañño nevattavyābādhāya ceteti na 
paravyābādhāya ceteti na ubhayavyābādhāya ceteti._
____

[quote, M.1.304]
____
Wise is the bhikkhunī Dhammadinnā, of great wisdom is the bhikkhunī 
Dhammadinnā.

_paṇḍitā visākha dhammadinnā bhikkhunī mahāpaññā visākha 
dhammadinnā bhikkhunī._
____

=== Illustrations: to discern

.Illustration
====
pajānāti

discerns
====

• And how does a bhikkhu abide contemplating the nature of the mind +
_Kathañca bhikkhave bhikkhu citte cittānupassī viharati?_

In this regard a bhikkhu discerns

____
a mental state with attachment as just that.

_sarāgaṃ vā cittaṃ sarāgaṃ cittan ti pajānāti_
____

[quote, M.1.59]
____
a mental state without attachment as just that.

_vītarāgaṃ vā cittaṃ vītarāgaṃ cittan ti pajānāti._
____

.Illustration
====
pajānāti

discern
====

____
And what is old age and death?_

_Katamañca bhikkhave jarāmaraṇaṃ?_
____

____
The ageing, decrepitude, broken teeth, graying hair, wrinkled skin, dwindling 
of the life-span, decay of the sense faculties for the various beings in the 
various classes of beings. This is called old age.

_yā tesaṃ tesaṃ sattānaṃ tamhi tamhi sattanikāye jarā jīraṇatā 
khaṇḍiccaṃ pāliccaṃ valittacatā āyuno saṃhāni indriyānaṃ 
paripāko ayaṃ vuccati jarā._
____

____
The passing away, the deceasing, the dissolution, the ending, the perishing, 
the death, the breaking up of aggregates, the laying down of the body for the 
various beings in the various classes of beings. This is called death.

_yā tesaṃ tesaṃ sattānaṃ tamhā tamhā sattanikāyā cuti cavanatā 
bhedo antaradhānaṃ maccu maraṇaṃ kālakiriyā khandhānaṃ bhedo 
kaḷevarassa nikkhepo jīvitindriyassa upacchedo idaṃ vuccati maraṇaṃ._
____

____
Thus this is old age, and this is death. This is called old age and death.

_Iti ayañca jarā idañca maraṇaṃ idaṃ vuccati bhikkhave 
jarāmaraṇaṃ. ṇaṃ_
____

____
With the origination of birth comes the origination of old age and death

_jātisamudayā jarāmaraṇasamudayo_
____

____
With the ending of birth comes the ending of old age and death

_jātinirodhā jarāmaraṇanirodho_
____

• The practice leading to the ending of old age and death is the noble 
eightfold path. +
☸ _ayameva ariyo aṭṭhaṅgiko maggo jarāmaraṇa nirodhagāminī 
paṭipadā seyyathidaṃ– sammādiṭṭhi... pe... sammāsamādhi_

____
When a noble disciple thus discerns

_yato kho bhikkhave ariyasāvako_
____

• old age and death +
_evaṃ jarāmaraṇaṃ pajānāti_

• the origin of old age and death +
_evaṃ jarāmaraṇasamudayaṃ pajānāti_

• the ending of old age and death +
_evaṃ jarāmaraṇanirodhaṃ pajānāti_

• the practice leading to its ending +
_evaṃ jarāmaraṇanirodhagāminiṃ paṭipadaṃ pajānāti_

• this is his knowledge of the nature of reality +
_idamassa dhamme ñāṇaṃ_ (S.2.57-8).

.Illustration
====
pajānāti

discerns
====

[quote, A.3.417]
____
The Perfect One discerns according to reality the possible as possible, and the 
impossible as impossible.

__ṭhānañca ṭhānato aṭṭhānañca aṭṭhānato yathābhūtaṃ 
pajānāti._
____

.Illustration
====
pajānāti

discern
====

[quote, S.4.208]
____
The ignorant Everyman does not discern any deliverance from unpleasant sense 
impression other than through sensuous pleasure.

_na bhikkhave pajānāti assutavā puthujjano aññatra kāmasukhā dukkhāya 
vedanāya nissaraṇaṃ._
____

.Illustration
====
pajānāmi

discern
====

[quote, M.1.73-4]
____
I discern the Untroubled and the path and practice leading to the Untroubled.

_Nibbānañcāhaṃ sāriputta pajānāmi nibbānagāmiñca maggaṃ 
nibbānagāminiñca paṭipadaṃ._
____

.Illustration
====
pajānāti

discern
====

____
The ignorant Everyman does not discern what issues should be contemplated or 
what issues should not be contemplated.

_assutavā puthujjano... manasikaraṇīye dhamme nappajānāti 
amanasikaraṇīye dhamme nappajānāti_
____

[quote, M.1.7]
____
This being so, he does not contemplate issues that should be contemplated but 
contemplates issues that should not be contemplated.

_So manasikaraṇīye dhamme appajānanto amanasikaraṇīye dhamme 
appajānanto ye dhammā na manasikaraṇīyā te dhamme manasikaroti ye dhammā 
manasikaraṇīyā te dhamme na manasikaroti._
____

=== Illustrations: to know that

.Illustration
====
pajānāmi

know that
====

[quote, M.3.31]
____
I know that my mind is liberated [from perceptually obscuring states]

_vimuttaṃ me cittan ti pajānāmi._
____

.Illustration
====
pajānāti

know that
====

[quote, S.5.229-230]
____
This, too, is a method by which a bhikkhu who is a finished disciple knows 
that: 'I am a finished disciple.'

_asekhosmīti pajānātī ti._
____

.Illustration
====
pajānāti

know that
====

[quote, S.5.341]
____
Breathing in long he knows that "I breathe in long." Breathing out long he 
knows that "I breathe out long

_Dīghaṃ assasāmī ti pajānāti. Dīghaṃ passasāmī ti pajānāti._
____

.Illustration
====
pajānāti

know that; discern
====

____
Now of these the Perfect One knows that these views thus grasped and adhered to 
will lead to such-and-such a place of rebirth, to such-and-such an afterlife 
destination.

_Tayidaṃ bhikkhave tathāgato pajānāti ime diṭṭhiṭṭhānā evaṃ 
gahitā evaṃ parāmaṭṭhā evaṃ gatikā bhavanti evaṃ abhisamparāyā 
ti_
____

____
That does he know, and he discerns also what transcends them;

_tañca tathāgato pajānāti tato ca uttaritaraṃ pajānāti;_
____

____
and he is not attached to that discernment,

_tañca pajānanaṃ na parāmasati_
____

[quote, D.1.17]
____
and thus unattached he has realised inward peace,

_aparāmasato cassa paccattaṃ yeva nibbuti viditā._
____

.Illustration
====
pajānāti

know that; discern
====

____
"In this regard, while a bhikkhu is abiding diligently, vigorously, and 
resolutely applied [to the practice], there arises in him the faculty of 
physical pain. He knows that: 'There has arisen in me this faculty of physical 
pain.'

_Idha bhikkhave bhikkhuno appamattassa ātāpino pahitattassa viharato 
uppajjati dukkhindriyaṃ. So evaṃ pajānāti uppannaṃ kho me idaṃ 
dukkhindriyaṃ_
____

[quote, S.5.213]
____
He discerns the faculty of physical pain; he discerns the origin of the faculty 
of physical pain; he discerns the ending of the faculty of physical pain; and 
he discerns where the arisen faculty of physical pain ceases without remainder.

_so dukkhindriyañca pajānāti. Dukkhindriyanirodhañca pajānāti. Yattha 
cuppannaṃ dukkhindriyaṃ aparisesaṃ nirujjhati. Tañca pajānāti._
____

=== Illustrations: to understand how

.Illustration
====
pajānāti

know that; pajānāti, understands how
====

____
In this regard, if sensuous hankering is present in him, he knows that it is 
present. Or if not present, he knows that it is not present.

_Idha bhikkhave bhikkhu santaṃ vā ajjhattaṃ kāmacchandaṃ atthi me 
ajjhattaṃ kāmacchando ti pajānāti asantaṃ vā ajjhattaṃ 
kāmacchandaṃ natthi me ajjhattaṃ kāmacchando ti pajānāti._
____

____
He understands how unarisen sensuous hankering arises in him.

_Yathā ca anuppannassa kāmacchandassa uppādo hoti tañca pajānāti_
____

____
He understands how arisen sensuous hankering is abandoned.

_yathā ca uppannassa kāmacchandassa pahānaṃ hoti tañca pajānāti._
____

[quote, D.2.300]
____
He understands how abandoned sensuous hankering does not arise

_Yathā ca pahīnassa kāmacchandassa anuppādo hoti tañca pajānāti._
____

.Illustration
====
pajānāti

discern; pajānāti, understand how
====

____
And how does a bhikkhu abide contemplating the nature of certain objects of the 
systematic teachings with regard to the six senses and their objects?

_Kathañca pana bhikkhave bhikkhu dhammesu dhammānupassī viharati chasu 
ajjhattikabāhiresu āyatanesu_
____

____
A bhikkhu discerns the visual sense, visible objects, and the bond that arises 
dependent on them both.

_Idha bhikkhave bhikkhu cakkhuñca pajānāti rūpe ca pajānāti yañca 
tadubhayaṃ paṭicca uppajjati saṃyojanaṃ tañca pajānāti._
____

____
He understands how the unarisen bond arises in him.

_yathā ca anuppannassa saṃyojanassa uppādo hoti tañca pajānāti._
____

____
He understands how the arisen bond is abandoned.

_yathā ca uppannassa saṃyojanassa pahānaṃ hoti tañca pajānāti._
____

[quote, D.2.302]
____
He understands how the abandoned bond does not arise in the future.

_yathā ca pahīnassa saṃyojanassa āyatiṃ anuppādo hoti tañca 
pajānāti._
____

.Illustration
====
pajānāti

understand how
====

____
With purified divine vision surpassing that of men, he sees beings passing away 
and being reborn, inferior and superior, well-favoured and ill-favoured, 
fortunate and unfortunate,

_dibbena cakkhunā visuddhena atikkantamānusakena satte passati cavamāne 
upapajjamāne hīne paṇīte suvaṇṇe dubbaṇṇe sugate duggate_
____

[quote, D.1.82]
____
and he understands how beings fare according to their deeds.

_yathākammūpage satte pajānāti._
____

=== Illustrations: to be discerned

.Illustration
====
paññāyati

discernable
====

____
There are three marks of the originated

_Tīṇi'māni bhikkhave saṅkhatassa saṅkhatalakkhaṇāni_
____

____
an arising is discernable

_uppādo paññāyati_
____

____
a disappearance is discernable

_vayo paññāyati_
____

[quote, A.1.152]
____
a changeability while persisting is discernable

__ṭhitassa aññathattaṃ paññāyati._
____

.Illustration
====
paññāyittha

discernable
====

[quote, D.2.164]
____
When the Blessed One's body was burned, of whatever had been skin, fascia, 
flesh, sinews, and synovial fluid, neither soot nor ash was discernable; only 
bony ashes remained.

_Jhāyamānassa kho pana bhagavato sarīrassa yaṃ ahosi chavī ti vā camman 
ti vā maṃsan ti vā naharū ti vā lasikā ti vā tassa neva chārikā 
paññāyittha na masi sarīrāneva avasissiṃsu._
____

.Illustration
====
paññāpanāya

to be discerned
====

[quote, M.3.17]
____
The four great material phenomena are the indispensible and necessary 
conditions by which the aggregate of bodily form is to be discerned._

_Cattāro kho bhikkhu mahābhūtā hetu cattāro mahābhūtā paccayo 
rūpakkhandhassa paññāpanāya._
____

.Illustration
====
paññāyatī

to be discerned
====

[quote, Ud.80]
____
But since there is an unborn, a not-brought-about, an unproduced, an 
unoriginated, therefore a deliverance is to be discerned from what is born, 
brought about, produced, originated.

_yasmā ca kho bhikkhave atthi ajātaṃ abhūtaṃ akataṃ asaṅkhataṃ 
tasmā jātassa bhūtassa katassa saṅkhatassa nissaraṇaṃ paññāyatī 
ti._
____

=== Illustrations: one of wisdom/who knows that

.Illustration
====
pañño

one of wisdom
====

[quote, Sn.v.1143]
____
In whatever direction the one of extensive wisdom goes, to that place that I am 
also inclined to go.

_Yaṃ yaṃ disaṃ vajati bhūripañño sa tena teneva nato'hamasmi._
____

.Illustration
====
pañño

one of wisdom; paññā, wisdom
====

____
When, householder, a noble disciple has realised that

_Yato ca kho gahapati ariyasāvakassa_
____

____
Greed and voracity are a defilement of the mind, he abandons them.

_abhijjhāvisamalobho cittassa upakkileso ti iti viditvā abhijjhāvisamalobho 
cittassa upakkileso pahīṇo hoti_
____

____
Ill will is a defilement of the mind, he abandons it.

_vyāpādo cittassa upakkileso ti iti viditvā vyāpādo cittassa upakkileso 
pahīṇo hoti_
____

____
Lethargy and torpor are a defilement of the mind, he abandons them.

_thīnamiddhaṃ cittassa upakkileso ti iti viditvā thīnamiddhaṃ cittassa 
upakkileso pahīṇo hoti_
____

____
Restlessness and anxiety are a defilement of the mind, he abandons them.

_uddhaccakukkuccaṃ cittassa upakkileso ti iti viditvā uddhaccakukkuccaṃ 
cittassa upakkileso pahīṇo hoti._
____

____
Doubt [about the significance of the teaching] is a defilement of the mind, he 
abandons it.

_Vicikicchā cittassa upakkileso ti iti viditvā vicikicchā cittassa 
upakkileso pahīṇo hoti._
____

____
This, householder, is called a noble disciple of great wisdom, of broad wisdom, 
one who profoundly sees whatever enters into the range of consciousness, of 
perfect wisdom.

_Ayaṃ vuccati gahapati ariyasāvako mahāpañño puthupañño āpāthadaso 
paññāsampanno._
____

[quote, A.2.67]
____
This is called perfection in wisdom._

_Ayaṃ vuccati gahapati paññāsampadā._
____

.Illustration
====
pañño

one who knows that
====

• In what way is a bhikkhu one who knows that his mind is liberated [from 
perceptually obscuring states]? +
_Kathañca bhikkhave bhikkhu suvimuttapañño hoti:_

[quote, A.5.32]
____
In this regard a bhikkhu knows that his attachment... hatred... undiscernment 
of reality is abandoned, chopped down at the root, completely and irreversibly 
destroyed, never to arise again in future.

_rāgo... doso... moho me pahīno ucchinnamūlo tālāvatthukato 
anabhāvaṃkato āyatiṃ anuppādadhammoti pajānāti._
____

=== Illustrations: penetrative discernment

.Illustration
====
paññā

penetrative discernment
====

____
Bhikkhus, there is one thing if developed and cultivated leads

_Ekadhammo bhikkhave bhāvito bahulīkato_
____

____
to the attaining of penetrative discernment

_paññāpaṭilābhāya saṃvattati_
____

____
to the growth of penetrative discernment

_paññāvuddhiyā saṃvattati_
____

____
to the expansion of penetrative discernment

_paññāvepullāya saṃvattati_
____

____
to greatness of penetrative discernment

_mahāpaññatāya saṃvattati_
____

____
to breadth of penetrative discernment

_puthupaññatāya saṃvattati_
____

____
to vastness of penetrative discernment

_vipulapaññatāya saṃvattati_
____

____
to profundity of penetrative discernment

_gambhīrapaññatāya saṃvattati_
____

____
to a state of unsurpassed penetrative discernment

_asāmantapaññatāya saṃvattati_
____

____
to extensiveness of penetrative discernment

_bhūripaññatāya saṃvattati_
____

____
to abundance of penetrative discernment

_paññābāhullāya saṃvattati_
____

____
to quickness of penetrative discernment

_sīghapaññatāya saṃvattati_
____

____
to buoyancy of penetrative discernment

_lahupaññatāya saṃvattati_
____

____
to joyousness of penetrative discernment

_hāsupaññatāya saṃvattati_
____

____
to swiftness of penetrative discernment

_javanapaññatāya saṃvattati_
____

____
to keenness of penetrative discernment

_tikkhapaññatāya saṃvattati_
____

____
to penetrativeness of penetrative discernment

_nibbedhikapaññatāya saṃvattati_
____

[quote, A.1.45]
____
What is the one thing? Mindfulness of the body.

_katamo ekadhammo? Kāyagatāsati._
____

.Illustration
====
paññāya

penetrative discernment
====

[quote, A.5.136]
____
Unwillingness to listen and not asking questions are obstacles to penetrative 
discernment.

_asussusā aparipucchā paññāya paripantho._
____

.Illustration
====
paññā

penetrative discernment
====

____
How does one discern a knowable phenomenon?

_Neyyaṃ panāvuso dhammaṃ kena pajānātī ti_
____

____
One discerns a knowable phenomenon with the eye of penetrative discernment.

_Neyyaṃ kho āvuso dhammaṃ paññācakkhunā pajānātī ti_
____

____
For what purpose is penetrative discernment?

_Paññā panāvuso kimatthiyā ti?_
____

[quote, M.1.293]
____
Penetrative discernment is for the sake of full understanding, profound 
understanding, and abandonment.

_Paññā kho āvuso abhiññatthā pariññatthā pahānatthā ti._
____

.Illustration
====
paññā

penetrative discernment
====

[quote, Dh.v.372]
____
There is no jhāna for one without penetrative discernment. There is no 
penetrative discernment for one who does not meditate. Whoever has jhāna 
together with penetrative discernment, is right in the presence of the 
Untroubled.

_Natthi jhānaṃ apaññassa paññā natthi ajjhāyato +
Yamhi jhānañca paññā ca sa ve nibbānasantike._
____

.Illustration
====
paññā

penetrative discernment
====

[quote, A.3.446]
____
To abandon undiscernment of reality, penetrative discernment should be 
developed._

_Mohassa pahānāya paññā bhāvetabbā._
____

.Illustration
====
paññā

penetrative discernment
====

____
What is the faculty of penetrative discernment?

_Katamañca bhikkhave paññindriyaṃ_
____

[quote, S.5.199]
____
In this regard a noble disciple is blessed with penetrative discernment. He is 
endowed with noble and penetrative discernment of arising and vanishing which 
leads to the complete destruction of suffering.

_idha bhikkhave ariyasāvako paññavā hoti udayatthagāminiyā paññāya 
samannāgato ariyāya nibbedhikāya sammā dukkhakkhayagāminiyā._
____

.Illustration
====
paññāya

penetrative discernment
====

[quote, M.3.136]
____
The five hindrances which are spiritual defilements and weakening to 
penetrative discernment.

_pañca nīvaraṇe pahāya cetaso upakkilese paññāya dubbalikaraṇe._
____

.Illustration
====
paññā

penetrative discernment
====

[quote, A.4.339]
____
Penetrative discernment is the examiner of all things.

_paññuttarā sabbe dhammā._
____

____
And how is penetrative discernment the examiner?

_Kathañca bhikkhave paññuttaraṃ hoti?_
____

____
In this regard, the teachings are explained by me to disciples for the complete 
destruction of suffering.

_Idha bhikkhave mayā sāvakānaṃ dhammā desitā sabbaso sammā 
dukkhakkhayāya._
____

____
In accordance with way I explain the teachings to disciples for the complete 
destruction of suffering, those teachings are examined by them with penetrative 
discernment.

_Yathā yathā bhikkhave mayā sāvakānaṃ dhammā desitā sabbaso sammā 
dukkhakkhayāya tathā tathāssa te dhammā paññāya samavekkhitā honti._
____

[quote, A.2.243]
____
In this way penetrative discernment is the examiner

_Evaṃ kho bhikkhave paññuttaraṃ hoti._
____

.Illustration
====
duppañño

void of penetrative discernment
====

____
-- 'One who is void of penetrative discernment, one who is void of penetrative 
discernment,' is said, friend. In reference to what was it said?

_Duppañño duppañño ti āvuso vuccati. Kittāvatā nu kho āvuso 
duppaññoti vuccatī ti?_
____

____
-- 'He does not discern. He does not discern' therefore 'one who is void of 
penetrative discernment' is said

_Nappajānāti nappajānātī ti kho āvuso tasmā duppañño ti vuccati._
____

____
... What does he not discern?_

_Kiñca nappajānāti?_
____

[quote, M.1.292]
____
... He does not discern 'This is suffering... This is the origin of 
suffering... This is the ending of suffering... This is the practice leading to 
the ending of suffering...

_Idaṃ dukkhan ti nappajānāti ayaṃ dukkhasamudayo ti nappajānāti ayaṃ 
dukkhanirodho ti nappajānāti ayaṃ dukkhanirodhagāminī paṭipadā ti 
nappajānāti._
____

.Illustration
====
paññavā

blessed with penetrative discernment
====

• -- 'Blessed with penetrative discernment, blessed with penetrative 
discernment,' is said, friend. In reference to what was it said? +
_Paññavā paññavā ti āvuso vuccati. Kittāvatā nu kho āvuso paññavā 
ti vuccatī ti?_

• -- 'He discerns. He discerns' therefore 'blessed with penetrative 
discernment' is said +
_Pajānāti pajānātī ti kho āvuso tasmā paññavāti vuccati._

____
... What does he discern?_

_Kiñca pajānāti?_
____

[quote, M.1.292]
____
... He discerns 'This is suffering... This is the origin of suffering... This 
is the ending of suffering... This is the practice leading to the ending of 
suffering...

_Idaṃ dukkhan ti pajānāti... Ayaṃ dukkhanirodhagāminī paṭipadā ti 
pajānāti._
____

