== Parakkama

=== Renderings

- _parakkama_: application [to the practice]

=== Introduction

==== Parenthesis of parakkama: application [to the practice]

Our parenthesis of _parakkama_ follows how we likewise treat _appamatta_, 
_ātāpī_, and _pahitatta_:

[quote, S.4.145]
____
diligently, vigorously, and resolutely applied [to the practice].

_appamatto ātāpī pahitatto._
____

=== Illustrations

.Illustration
====
parakkamā

apply themselves [to the practice]
====

[quote, Dh.v.23]
____
Wise people, those who meditate perseveringly, who constantly and resolutely 
apply themselves [to the practice], they reach the Untroubled, the unsurpassed 
safety from the danger of bondage [to individual existence].

_Te jhāyino sātatikā niccaṃ daḷhaparakkamā +
Phusanti dhīrā nibbānaṃ yogakkhemaṃ anuttaraṃ._
____

.Illustration
====
parakkamo

application [to the practice]
====

[quote, A.1.117]
____
And how is a bhikkhu proficient? In this regard, a bhikkhu abides energetically 
applied to the abandoning of spiritually unwholesome factors and the 
undertaking of spiritually wholesome factors, steadfast, unwavering in 
application [to the practice], not shirking the responsibility of [undertaking] 
spiritually wholesome factors.

_Kathañca bhikkhave bhikkhu vidhuro hoti? Idha bhikkhave bhikkhu 
āraddhaviriyo viharati akusalānaṃ dhammānaṃ pahānāya kusalānaṃ 
dhammānaṃ upasampadāya thāmavā daḷhaparakkamo anikkhittadhuro kusalesu 
dhammesu._
____

.Illustration
====
parakkamo

application [to his practice]
====

[quote, Sn.v.293]
____
'He amongst them who was supremely devout, being unwavering in application [to 
his practice], refrained from sexual intercourse even in a dream.

_Yo nesaṃ paramo āsi brahmā daḷhaparakkamo +
Sa vāpi methunaṃ dhammaṃ supinantepi nāgamā._
____

.Illustration
====
parakkamaṃ

application [to the practice]
====

[quote, Th.v.167]
____
That which should be done by one of resolute energy, that which should be done 
by one desiring enlightenment, that I shall undertake to do. I will not fail. 
See my [unwavering] energy and application [to the practice].

_Yaṃ kiccaṃ daḷhaviriyo yaṃ kiccaṃ boddhumicchatā +
Karissaṃ nāvarajjhissaṃ passa viriyaṃ parakkamaṃ._
____

