== Pariyuṭṭhāna; Pariyuṭṭhita

=== Renderings

- _pariyuṭṭhānaṃ_: absorption

- _pariyuṭṭhita_: absorbed

- _pariyuṭṭhita_: mentally preoccupied

=== Illustrations

.Illustration
====
pariyuṭṭhāna

absorption; pariyuṭṭhita, absorbed; pariyuṭṭhita, preoccupied
====

____
Is there any absorption unabandoned in myself that might so preoccupy my mind 
that I could not know or see things according to reality?

_atthi nu kho me taṃ pariyuṭṭhānaṃ ajjhattaṃ appahīnaṃ yenāhaṃ 
pariyuṭṭhānena pariyuṭṭhitacitto yathābhūtaṃ na jāneyyaṃ na 
passeyyanti_
____

____
If a bhikkhu is absorbed in attachment to sensuous pleasure then his mind is 
preoccupied

_Sace bhikkhave bhikkhu kāmarāgapariyuṭṭhito hoti pariyuṭṭhitacittova 
hoti._
____

____
If a bhikkhu is absorbed in ill will then his mind is preoccupied

_Sace bhikkhave bhikkhu vyāpādapariyuṭṭhito hoti pariyuṭṭhitacittova 
hoti._
____

____
If a bhikkhu is absorbed in lethargy and torpor then his mind is preoccupied

_Sace bhikkhave bhikkhu thīnamiddhapariyuṭṭhito hoti 
pariyuṭṭhitacittova hoti._
____

____
If a bhikkhu is absorbed in restlessness and anxiety then his mind is 
preoccupied

_Sace bhikkhave bhikkhu uddhaccakukkuccapariyuṭṭhito hoti 
pariyuṭṭhitacittova hoti._
____

____
If a bhikkhu is absorbed in doubt [about the significance of the teaching] then 
his mind is preoccupied

_Sace bhikkhave bhikkhu vicikicchāpariyuṭṭhito hoti 
pariyuṭṭhitacittova hoti._
____

____
if a bhikkhu is absorbed in speculation about this world then his mind is 
preoccupied

_Sace bhikkhave bhikkhu idhalokacintāya pasuto hoti pariyuṭṭhitacittova 
hoti_
____

____
if a bhikkhu is absorbed in speculation about the world hereafter then his mind 
is preoccupied

_Sace bhikkhave bhikkhu paralokacintāya pasuto hoti pariyuṭṭhitacittova 
hoti_
____

[quote, M.1.323]
____
if a bhikkhu abides quarrelsome, cantankerous, contentious, stabbing others 
with verbal daggers, then his mind is preoccupied.

_Sace bhikkhave bhikkhu bhaṇḍanajāto kalahajāto vivādāpanno 
aññamaññaṃ mukhasattīhi vitudanto viharati pariyuṭṭhitacittova hoti._
____

.Illustration
====
pariyuṭṭhitena

absorbed
====

Ānanda, the ignorant Everyman

____
abides with a mind absorbed in and overcome by the view of personal identity.

_sakkāyadiṭṭhipariyuṭṭhitena cetasā viharati 
sakkāyadiṭṭhiparetena_
____

____
abides with a mind absorbed in and overcome by doubt [about the significance of 
the teaching]

_vicikicchāpariyuṭṭhitena cetasā viharati vicikicchāparetena_
____

____
abides with a mind absorbed in and overcome by adherence to observances and 
practices

_sīlabbataparāmāsapariyuṭṭhitena cetasā viharati 
sīlabbataparāmāsaparetena_
____

____
abides with a mind absorbed in and overcome by attachment to sensuous pleasure

_kāmarāgapariyuṭṭhitena cetasā viharati kāmarāgaparetena_
____

[quote, M.1.434]
____
abides with a mind absorbed in and overcome by ill will

_vyāpādapariyuṭṭhitena cetasā viharati vyāpādaparetena._
____

.Illustration
====
pariyuṭṭhitaṃ absorbed

____
Bhikkhus

when the noble disciple reflects on the Perfect One,
====

_Yasmiṃ bhikkhave samaye ariyasāvako tathāgataṃ anussarati_
____

[quote, A.3.313]
____
his mind is not absorbed in attachment, hatred, or undiscernment of reality;

_nevassa tasmiṃ samaye rāgapariyuṭṭhitaṃ cittaṃ hoti. Na 
dosapariyuṭṭhitaṃ cittaṃ hoti. Na mohapariyuṭṭhitaṃ cittaṃ 
hoti._
____

.Illustration
====
pariyuṭṭhita

absorbed in
====

____
The ignorant Everyman lives absorbed in the views: 'I am bodily form. Bodily 
form is mine.'

_assutavā puthujjano... ahaṃ rūpaṃ mama rūpan ti 
pariyuṭṭhitaṭṭhāyī hoti._
____

____
Whilst absorbed in such a way, that bodily form changes and alters

_Tassa ahaṃ rūpaṃ mama rūpan ti pariyuṭṭhitaṭṭhāyino taṃ 
rūpaṃ vipariṇamati aññathā hoti_
____

[quote, S.3.3]
____
And there arises grief, lamentation, physical pain, psychological pain, and 
vexation._

_Tassa rūpavipariṇāmaññathābhāvā uppajjanti 
sokaparidevadukkhadomanassupāyāsā._
____

Comment:

PED (sv _Pariyuṭṭhita_) says _pariyuṭṭhaṭṭhāyin_ should read 
_pariyuṭṭhitaṭṭhāyin._

