== Pariyāya

=== Renderings

- _pariyāya_: way

- _pariyāya_: method

- _pariyāya_: some other

- _pariyāya_: other kinds

- _pariyāya_: another way

- _pariyāya_: another reason

- _pariyāyena_: in a way that is qualified

- _pariyāya_: consecutively

- _pariyāya_: in turn

- _pariyāya_: systematic schedule

- _pariyāya_: proper method of exposition

- _pariyāya_: systematic exposition

- _pariyāya_: on the theme of

- _imaṃ pariyāyamakāsi yadidaṃ idhāgamanāya_: found an opportunity to 
come here

=== Introduction

==== Imaṃ pariyāyamakāsi yadidaṃ idhāgamanāya: found an opportunity to 
come here

This phrase occurs 12 times in the suttas. Its meaning is clarified in this 
exchange:

&#8203;[The Buddha:]

____
-- At long last, lay follower, you have found an opportunity to come here.

_cirassaṃ kho tvaṃ upāsakaṃ imaṃ pariyāyamakāsi yadidaṃ 
idhāgamanāyā ti._
____

&#8203;[Lay follower:]

[quote, Ud.13]
____
-- Bhante, I have wanted to come and see the Blessed One for ages, but I have 
been busy with various tasks and duties so I have not been able to do so.

_Cirapaṭikāhaṃ bhante bhagavantaṃ dassanāya upasaṅkamitukāmo api 
cāhaṃ kehi ci kehi ci kiccakaraṇiyehi vyāvaṭo. Evāhaṃ nāsakkhiṃ 
bhagavantaṃ dassanāya upasaṅkamitun tī._
____

=== Illustrations

.Illustration
====
pariyāyena

way
====

[quote, S.4.166]
____
In this way, friend, it has been declared by the Blessed One that advertence is 
void of personal qualities

_imināpi kho etaṃ āvuso pariyāyena bhagavatā akkhātaṃ vivaṭaṃ 
pakāsitaṃ itipidaṃ viññāṇaṃ anattā ti._
____

.Illustration
====
pariyāya

ways
====

[quote, S.1.146]
____
Proficient [in discerning] the ways of others' minds.

_cetopariyāyakovidā._
____

.Illustration
====
pariyāyena

ways
====

[quote, M.3.7]
____
Just so, bhante, has the Blessed One expounded the teaching in various ways

_evamevaṃ bhotā gotamena anekapariyāyena dhammo pakāsito._
____

.Illustration
====
pariyāyena

ways
====

[quote, M.1.132]
____
Have not obstructive things been called obstructions in many ways by me?

_Nanu mayā moghapurisa anekapariyāyena antarāyikā dhammā antarāyikā 
vuttā._
____

.Illustration
====
pariyāya

ways
====

____
This bhikkhu is called a master of the ways and paths of thought.

_Ayaṃ vuccati bhikkhave bhikkhu vasī vitakkapariyāyapathesu_
____

[quote, M.1.122]
____
He thinks whatever thought he wishes to think, and does not think whatever 
thought he does not wish to think.

_yaṃ vitakkaṃ ākaṅkhissati taṃ vitakkaṃ vitakkessati yaṃ 
vitakkaṃ nākaṅkhissati na taṃ vitakkaṃ vitakkessati._
____

.Illustration
====
pariyāyaṃ

method
====

[quote, Vin.4.47-8]
____
He should organise the use of a method that involves two or three layers of 
facing material around the door

_dvatticchadanassa pariyāyaṃ adhiṭṭhātabbanti._
____

.Illustration
====
pariyāye

some other
====

[quote, A.3.415]
____
The karmic consequence of karmically consequential deeds is threefold: that 
which arises in this life, or on rebirth, or in some other subsequent 
&#8203;[existence].

_Tividhāhaṃ bhikkhave kammānaṃ vipākaṃ vadāmi diṭṭhevā dhamme 
upajje vā apare vā pariyāye._
____

.Illustration
====
pariyāye

some other
====

[quote, Th.v.941]
____
By chicanery or some other strategem or artifice, for the sake of a [luxurious] 
lifestyle they accumulate vast wealth.

_Lesakappe pariyāye parikappenudhāvitā +
Jīvikatthā upāyena saṅkaḍḍhanti bahuṃ dhanaṃ._
____

COMMENT

_Parikappenudhāvitā_: 'strategem.' Literally: 'pursuing a strategem.'

COMMENT

_Upāyena_: 'artifice.' PED (sv _Upāya_): 'by artifice or by means of a trick.'

.Illustration
====
pariyāye

other kinds
====

____
Four kinds of knowledge

_Cattāri ñāṇāni_
____

____
knowledge of the nature of reality

_dhamme ñāṇaṃ_
____

____
knowledge of conformity

_anvaye ñāṇaṃ_
____

____
other kinds of knowledge [of things according to reality]

_pariyāye ñāṇaṃ_
____

[quote, D.3.226]
____
common knowledge

_sammutiyā ñāṇaṃ._
____

COMMENT

_Pariyāye ñāṇaṃ_: 'Other kinds of knowledge [of things according to 
reality].' For notes on the parenthesis, see Glossary sv _Ñāṇa_.

.Illustration
====
pariyāyo

another way
====

____
And this is another way of explaining in brief that same point

_ayampi kho sāriputta pariyāyo etasseva atthassa saṅkhittena 
veyyākaraṇāya_
____

• I am not unsure about the perceptually obscuring states spoken of by the 
Ascetic +
_ye āsavā samaṇena vuttā tesvāhaṃ na kaṅkhāmi_;

• I do not doubt they have been abandoned by me +
_te me pahīṇāti na vicikicchāmī ti_ (S.2.54).

.Illustration
====
pariyāyo

another reason
====

____
But is there another reason, Prince, that leads you to think: 'There is not a 
world beyond. There are no spontaneously born beings. There is no fruit or 
result of good and bad deeds'?

_Atthi pana rājañña pariyāyo yena te pariyāyena evaṃ hoti: 'iti pi 
natthi paro loko natthi sattā opapātikā natthi sukaṭadukkaṭānaṃ 
kammānaṃ phalaṃ vipāko'ti?_
____

[quote, D.2.329-30]
____
There is another reason, Master Kassapa, that leads me to think: 'There is not 
a world beyond. There are no spontaneously born beings. There is no fruit or 
result of good and bad deeds.'_

_Atthi bho kassapa pariyāyo yena me pariyāyena evaṃ hoti: 'iti pi natthi 
paro loko natthi sattā opapātikā natthi sukaṭadukkaṭānaṃ kammānaṃ 
phalaṃ vipāko'ti._
____

.Illustration
====
pariyāyena

other way
====

A bhikkhu asked Ānanda:

[quote, A.3.402]
____
'Was it after applying his whole mind to [the matter] that the Blessed One 
declared of Devadatta: "Devadatta is bound for [rebirth in] the plane of 
sub-human existence, bound for hell, and he will remain there for the period of 
a universal cycle, unredeemable," or was it in some other way?'

_Kiṃ nu ko āvuso ānanda sabbaṃ cetaso samannāharitvā nu kho devadatto 
bhagavatā vyākato āpāyiko devadatto nerayiko kappaṭṭho atekiccho ti 
udāhu kenacideva pariyāyenā ti._
____

COMMENT:

'In some other way?' This implies the question: 'Was the Buddha fully conscious 
when he said that?' Ānanda relayed the question to the Buddha, who replied 
with the following two statements:

1. 'Ānanda, that bhikkhu must be either newly ordained, or a foolish and 
incompetent elder. When [the statement] was declared by me categorically, how 
on earth could he be unclear about it?'
+
****
_So vā kho ānanda bhikkhu navo bhavissati acirapabbajito thero vā pana bālo 
avyatto. Kathaṃ hi nāma yaṃ mayā ekaṃsena vyākataṃ tattha dvejjhaṃ 
āpajjissati?_
****

He continued:

2. 'I do not see any other single person about whom I have made a declaration 
after [more completely] applying my whole mind to [the matter] as [I did with] 
Devadatta.'
+
****
_Nāhaṃ ānanda aññaṃ ekapuggalampi samanupassāmi yo evaṃ mayā 
sabbaṃ cetaso samannāharitvā vyākato yathayidaṃ devadatto_ (A.3.403).
****

.Illustration
====
pariyāyena

in a way that is qualified
====

[quote, A.4.449-451]
____
It is in reference to this that a deliverance from what is inwardly troublesome 
is spoken of by the Blessed One, in a way that is qualified, because again 
there is something inwardly troublesome. What is troublesome in this case?

_Ettāvatā pi kho āvuso sambādhe okāsādhigamo vutto bhagavatā 
pariyāyena. Tattha'patthi sambādho._
____

.Illustration
====
nippariyāyena

in a way that is unqualified
====

[quote, A.4.449-451]
____
It is in reference to this that a deliverance from what is inwardly troublesome 
is spoken of by the Blessed One in a way that is unqualified.

_Ettāvatā pi kho āvuso sambādhe okāsādhigamo vutto bhagavatā 
nippariyāyenāti._
____

.Illustration
====
pariyāyena

consecutively
====

____
There are two religious discourses of the Perfect One, the Arahant, the 
Perfectly Enlightened One proclaimed consecutively. Which two?

_Tathāgatassa bhikkhave arahato sammāsambuddhassa dve dhammadesanā 
pariyāyena bhavanti. Katamā dve?_
____

1. Recognise unvirtuousness as unvirtuous. This is the first religious 
discourse.
+
****
_Pāpaṃ pāpakato passathā ti ayaṃ paṭhamā dhammadesanā._
****

2. Seeing unvirtuousness as unvirtuous, become in that respect disillusioned, 
unattached, and liberated. This is the second religious discourses
+
****
_Pāpaṃ pāpakato disvā tattha nibbindatha virajjatha vimuccathā ti ayaṃ 
dutiyā dhammadesanā_ (It.33).
****

[quote, It.33-4]
____
See the two statements proclaimed consecutively by the Perfect One, the Buddha, 
tenderly concerned for all beings. These are 'Recognise unvirtuousness' and 
then 'Be unattached to it.' With a mind that is unattached, you will put an end 
to suffering.'

_Tathāgatassa buddhassa sabbabhūtānukampino +
Pariyāyavacanaṃ passa dve ca dhammā pakāsitā +
Pāpakaṃ passatha cetaṃ tattha cā pi virajjatha +
Tato virattacittā se dukkhassantaṃ karissathā ti._
____

.Illustration
====
pariyāyena

in turn
====

[quote, A.3.402]
____
Each of you has spoken well in turn

_Sabbesaṃ vo bhikkhave subhāsitaṃ pariyāyena._
____

.Illustration
====
pariyāya

systematic schedule
====

[quote, M.1.78]
____
I ate only once a day, once in two days, once in seven days. In this way, 
eating even only once a fortnight, I dwelt given to eating food according to a 
systematic schedule.

_Ekāhikampi āhāraṃ āhāremi dvīhikampi āhāraṃ āhāremi 
sattāhikampi āhāraṃ āhāremi. Iti evarūpaṃ addhamāsikampi 
pariyāyabhattabhojanānuyogamanuyutto viharāmi.._
____

.Illustration
====
pariyāya

systematic schedule
====

[quote, M.1.282]
____
I do not say that the asceticism of one who eats according to a systematic 
schedule is merely due to his eating according to a systematic schedule.

_Nāhaṃ bhikkhave pariyāyabhattikassa pariyāyabhattikamattena sāmaññaṃ 
vadāmi_
____

.Illustration
====
pariyāya

proper method of exposition
====

____
One who explains the teaching to others should establish within himself five 
principles. Which five?

_Paresaṃ ānanda dhammaṃ desentena pañca dhamme ajjhattaṃ 
upaṭṭhapetvā paresaṃ dhammo desetabbo. Katame pañca:_
____

One should explain the teaching to others with the thought:

1. I will speak step-by-step.
+
****
_Ānupubbīkathaṃ kathessāmīti paresaṃ dhammo desetabbo_
****

2. I will speak observing a proper method of exposition.
+
****
_Pariyāyadassāvī kathaṃ kathessāmīti paresaṃ dhammo desetabbo_
****

3. I will speak out of sympathy.
+
****
_Anuddayataṃ paṭicca kathaṃ kathessāmīti paresaṃ dhammo desetabbo_
****

4. I will speak not for the sake of worldly benefits.
+
****
_Na āmisantaro kathaṃ kathessāmīti paresaṃ dhammo desetabbo_
****

5. I will speak without hurting myself or others.
+
****
_Attānañca parañca anupahacca kathaṃ kathessāmī ti paresaṃ dhammo 
desetabbo_ (A.3.184).
****

.Illustration
====
pariyāyaṃ

systematic exposition
====

____
I will expound for your benefit a systematic exposition of the teaching that 
involves a comparison with oneself.

_Attūpanāyikaṃ vo gahapatayo dhammapariyāyaṃ desissāmī ti_
____

____
What is the systematic exposition of the teaching that involves a comparison 
with oneself?

_Katamo ca gahapatayo attūpanāyiko dhammapariyāyo:_
____

____
In this regard, householders, a noble disciple reflects thus: 'I am one who 
wishes to live, who does not wish to die; I desire happiness and loathe pain. 
Since I am one who wishes to live... and loathe pain, if someone were to take 
my life, that would not be agreeable and pleasing to me.

_idha gahapatayo ariyasāvako iti paṭisañcikkhati ahaṃ khosmi jīvitukāmo 
amaritukāmo sukhakāmo dukkhapaṭikkūlo. Yo kho maṃ jīvitukāmaṃ 
amaritukāmaṃ sukhakāmaṃ dukkhapaṭikkūlaṃ jīvitā voropeyya na me 
taṃ assa piyaṃ manāpaṃ_
____

____
Now if I were to take the life of another -- of one who wishes to live, who 
does not wish to die, who desires happiness and loathes pain -- that would not 
be agreeable and pleasing to the other either. What is disagreeable and 
displeasing to me is disagreeable and displeasing to the other too. How can I 
inflict upon another what is disagreeable and displeasing to me?'

_ahañceva kho pana paraṃ jīvitukāmaṃ. Sukhakāmaṃ 
dukkhapaṭikkūlaṃ jīvitā voropeyya parassapi taṃ assa appiyaṃ 
amanāpaṃ. Yo kho myāyaṃ dhammo appiyo amanāpo. Parassapeso dhammo appiyo 
amanāpo. Yo kho myāyaṃ dhammo appiyo amanāpo kathāhaṃ paraṃ tena 
saṃyojeyyanti_
____

[quote, S.5.354]
____
In reflecting thus, he himself abstains from killing, exhorts others to abstain 
from killing, and speaks in praise of abstaining from killing.

_So iti paṭisaṅkhāya attanā ca pāṇātipātā paṭivirato hoti. 
Parañca pāṇātipātā veramaṇiyā samādapeti. Pāṇātipātā 
veramaṇiyā ca vaṇṇaṃ bhāsati._
____

.Illustration
====
pariyāyaṃ

systematic exposition
====

[quote, M.1.1]
____
I will expound for your benefit a systematic exposition on the essence of the 
whole teaching.

_Sabbadhammamūlapariyāyaṃ vo bhikkhave desessāmi._
____

.Illustration
====
pariyāyaṃ

systematic exposition
====

____
Then, while the Blessed One was alone in solitary retreat, he spoke this 
systematic exposition of the teaching.

_Atha kho bhagavā rahogato paṭisallīno imaṃ dhammapariyāyaṃ abhāsi:_
____

[quote, S.2.74]
____
Dependent on the visual sense and visible objects, advertence to the visual 
field arises. The association of the three is sensation. Sense impression 
arises dependent on sensation. Craving arises dependent on sense impression. 
Grasping arises dependent on craving. Individual existence arises dependent on 
grasping. Birth arises dependent on individual existence. Dependent on birth, 
there arises old-age-and-death, grief, lamentation, physical pain, 
psychological pain, and vexation. Such is the origin of this whole mass of 
suffering._

_Cakkhuñca paṭicca rūpe ca uppajjati cakkhuviññāṇaṃ. Tiṇṇaṃ 
saṅgati phasso. Phassapaccayā vedanā. Vedanāpaccayā taṇhā. 
Taṇhāpaccayā upādānaṃ. Upādānapaccayā bhavo. Bhavapaccayā jāti. 
Jātipaccayā jarāmaraṇaṃ sokaparidevadukkhadomanassupāyāsā 
sambhavanti. Evametassa kevalassa dukkhakkhandhassa samudayo hoti._
____

.Illustration
====
pariyāyassa

systematic exposition
====

[quote, Sn.p.218]
____
These teachings go to the Far Shore, hence this systematic exposition of the 
teaching is called The Way to the Far Shore.

_Pāraṅgamanīyā ime dhammā ti tasmā imassa dhammapariyāyassa 
pārāyananteva adhivacanaṃ._
____

Comment:

The _Pārāyanavagga_ is in fact a collection of teachings, not a systematic 
exposition.

.Illustration
====
pariyāyaṃ

systematic exposition; pariyāyaṃ, theme
====

____
Bhikkhus, I will expound for your benefit a systematic exposition of the 
teaching on the theme of 'The one who proclaims that an effort should be made.' 
Please listen...

_yogakkhemipariyāyaṃ vo bhikkhave dhammapariyāyaṃ desissāmi taṃ 
suṇātha._
____

____
And what is the systematic exposition of the teaching on the theme of 'The one 
who proclaims that an effort should be made'?

_Katamo ca bhikkhave yogakkhemipariyāyo dhammapariyāyo?_
____

____
There are visible objects known via the visual sense that are likeable, 
loveable, pleasing, agreeable, connected with sensuous pleasure, and charming. 
These have been abandoned by the Perfect One, chopped down at the root, 
completely and irreversibly destroyed, never to arise again in future.

_Santi bhikkhave cakkhuviññeyyā rūpā iṭṭhā kantā manāpā piyarūpā 
kāmūpasaṃhitā rajanīyā te tathāgatassa pahīnā ucchinnamūlā 
tālāvatthukatā anabhāvakatā āyatiṃ anuppādadhammā_
____

[quote, S.4.85]
____
He proclaims that an effort should be made for their abandonment. Therefore the 
Perfect One is called 'The one who proclaims that an effort should be made.'

_tesañca pahānāya akkhāsi yogaṃ tasmā tathāgato yogakkhemī ti vuccati._
____

.Illustration
====
pariyāyaṃ

systematic exposition; pariyāyaṃ, on the theme of
====

____
I will expound for your benefit a systematic exposition of the teaching on the 
theme of burning.

_Ādittapariyāyaṃ vo bhikkhave dhammapariyāyaṃ desissāmi. Taṃ 
suṇātha._
____

____
And what is the systematic exposition of the teaching on the theme of burning?_

_Katamo ca bhikkhave ādittāpariyāyo dhammapariyāyo?_
____

[quote, S.4.168]
____
It would be better for the faculty of sight to be blotted out by a red-hot iron 
pin, burning, blazing, and glowing, than for one to grasp the features or 
aspects of a visible object known via the visual sense. For if one's stream of 
sense consciousness should stand tied to the sweetness of the features or 
aspects of the object, and if one should die on that occasion, it is possible 
that one will go to one of two places of rebirth: hell or the animal realm. 
Seeing this danger, I speak thus.

_Varaṃ bhikkhave tattāya ayosalākāya ādittāya sampajjalitāya 
sajotibhūtāya cakkhundriyaṃ sampalimaṭṭhaṃ na tveva 
cakkhuviññeyyesu rūpesu anuvyañjanaso nimittaggāho. 
Nimittassādagathitaṃ vā bhikkhave viññāṇaṃ tiṭṭhamānaṃ 
tiṭṭheyya anuvyañjanassādagathitaṃ vā tasmiṃ ce samaye kālaṃ 
kareyya ṭhānametaṃ vijjati yaṃ dvinnaṃ gatīnaṃ aññataraṃ 
gatiṃ gaccheyya nirayaṃ vā tiracchānayoniṃ vā. Imaṃ khvāhaṃ 
bhikkhave ādīnavaṃ disvā evaṃ vadāmi._
____

.Illustration
====
imaṃ pariyāyamakāsi yadidaṃ idhāgamanāya

found an opportunity to come here
====

[quote, D.1.179]
____
At long last, bhante, the Blessed One has found an opportunity to come here.

_Cirassaṃ kho bhante bhagavā imaṃ pariyāyamakāsi yadidaṃ 
idhāgamanāya._
____

