== Parimukhaṃ satiṃ upaṭṭhapetvā

=== Renderings

- _parimukhaṃ satiṃ upaṭṭhapetvā_: having established mindfulness 
within oneself

=== Introduction

==== Parimukhaṃ: objective

Here we will explain here our translation of _parimukhaṃ satiṃ 
upaṭṭhapetvā_, as it occurs in this phrase:

[quote, M.2.139]
____
He seats himself. Having crossed his legs, having set his body erect, having 
established mindfulness within himself,

_nisīdati pallaṅkaṃ ābhujitvā ujuṃ kāyaṃ paṇidhāya parimukhaṃ 
satiṃ upaṭṭhapetvā._
____

==== Parimukhaṃ: 'round the mouth'

_Parimukhaṃ_ can mean 'round the mouth' and is therefore used for 
'moustache'_:_

[quote, Vin.2.134]
____
The hair round the mouth should not be coiffed.

_na parimukhaṃ kārāpetabbaṃ._
____

==== Mindfulness around the mouth

But does this necessarily mean that meditators should establish mindfulness 
around their mouths? Because this would only be remotely appropriate where the 
meditation is on breathing. In fact _parimukhaṃ satiṃ upaṭṭhapetvā_ 
occurs in other meditations, too. For example, as a prelude to meditation on 
&#8203;[unlimited, all-encompassing] goodwill:

[quote, A.1.183]
____
I seat myself cross-legged, setting my body erect, establishing mindfulness 
within myself. Then I abide pervading one quarter with a mind of [unlimited, 
all-encompassing] goodwill...

_nisīdāmi pallaṅkaṃ ābhujitvā ujuṃ kāyaṃ paṇidhāya parimukhaṃ 
satiṃ upaṭṭhapetvā so mettāsahagatena cetasā ekaṃ disaṃ pharitvā 
viharāmi._
____

==== Parimukhaṃ with ajjhattaṃ

Most translators agree that _parimukhaṃ_ is an adverb of place, and commonly 
render our phrase 'he establishes mindfulness in front of him.' In the _Udāna_ 
and _Itivuttaka_, _parimukhaṃ_ occurs together with another adverb of place, 
_ajjhattaṃ_:

[quote, Ud.77-8]
____
The Blessed One saw Venerable Mahākaccāna sitting nearby, seated 
cross-legged, with his body upright, with mindfulness of the body 
well-established internally within himself (_ajjhattaṃ parimukhaṃ_).

_Addasā kho bhagavā āyasmantaṃ mahākaccānaṃ avidūre nisinnaṃ 
pallaṅkaṃ ābhujitvā ujuṃ kāyaṃ paṇidhāya kāyagatāya satiyā 
ajjhattaṃ parimukhaṃ supaṭṭhitāya._
____

[quote, It.80]
____
When mindfulness with breathing is well-established internally within yourself 
(_ajjhattaṃ parimukhaṃ_), the proclivity to extraneous thoughts that are 
vexatious does not exist.

_Ānāpānasatiyā ajjhattaṃ parimukhaṃ sūpaṭṭhitāya ye bāhirā 
vitakkāsayā vighātapakkhikā te na honti._
____

There are three reasons why _parimukhaṃ_ must mean 'within himself':

1. The stringing together of synonyms is a common feature of Pāli. If this is 
also the case here, then _parimukhaṃ_ is simply a synonym of _ajjhattaṃ_, 
meaning 'within himself.'

2. If _parimukhaṃ_ is an adverb of place, then it must inevitably be a 
synonym of _ajjhattaṃ_, because otherwise it leads to this contradiction:

- His body upright, with mindfulness of the body well-established internally in 
front of himself (Ud.77-8).

- When mindfulness with breathing is well-established internally in front of 
yourself (It.80).

3. In the construction of similar expressions in other contexts, mindfulness is 
shown to be established in a locative sense in relation to the meditator:

____
Whenever, Ānanda, a bhikkhu abides contemplating the nature of the body, on 
that occasion unmuddled mindfulness is established within him (_tassa_).

_Yasmiṃ samaye ānanda bhikkhu kāye kāyānupassī viharati upaṭṭhitā 
tassa tasmiṃ samaye sati hoti asammuṭṭhā._
____

[quote, S.5.331]
____
... Whenever, Ānanda, unmuddled mindfulness is established in a bhikkhu 
(_bhikkhuno_), on that occasion the enlightenment factor of mindfulness is 
aroused in the bhikkhu (_bhikkhuno_).

_Yasmiṃ samaye ānanda bhikkhuno upaṭṭhitā sati hoti asammuṭṭhā 
satisambojjhaṅgo tasmiṃ samaye bhikkhuno āraddho hoti._
____

==== Genitives rendered as locatives

We will now digress to justify our rendering of genitives _tassa_ and 
_bhikkhuno_ as locatives, and hence show that according to the passage just 
quoted, that mindfulness is established in a locative sense, namely 'within 
oneself.' Our justification is that both Bodhi and Horner also render them as 
locatives in a similar passage at M.3.85:

• Bodhi: On whatever occasion unremitting mindfulness is established in a 
bhikkhu—on that occasion the mindfulness enlightenment factor is aroused in 
him. +
• Horner: At the time, monks, when unmuddled mindfulness is aroused in the 
monk, at that time the link in awakening that is mindfulness is stirred up in 
the monk. +
☸ _Yasmiṃ samaye bhikkhave bhikkhuno upaṭṭhitā sati hoti 
asammuṭṭhā satisambojjhaṅgo tasmiṃ samaye bhikkhuno āraddho hoti_ 
(M.3.85).

In conclusion, _parimukhaṃ_ has a locative sense and is a synonym of 
_ajjhattaṃ_. Therefore mindfulness is established within oneself, not in 
front of oneself.

==== Expansion of meditation: parimukhaṃ the first step

We have seen that _parimukhaṃ_ means that mindfulness is established within 
oneself because it is a synonym of _ajjhattaṃ_. Following this, we can now 
see that _parimukhaṃ_ is the first of several steps, because meditations that 
begin with oneself are repeatedly said to be expanded outwards:

1. As he abides contemplating the nature of the body internally he becomes 
perfectly inwardly collected and perfectly serene. Being thus perfectly 
inwardly collected and perfectly serene he arouses knowledge and vision 
externally of others' bodies [according to reality].
+
****
_Ajjhattaṃ kāye kāyānupassī viharanto tattha sammāsamādhiyati 
sammāvippasīdati. So tattha sammā samāhito sammāvippasanno bahiddhā 
parakāye ñāṇadassanaṃ abhinibbatteti_ (D.2.216).
****

2. You should develop the [contemplation of the] four bases of mindfulness in a 
threefold way. Which four?
+
****
_cattāro satipaṭṭhāne tividhena bhaveyyāsi. Katame cattāro. Idha tvaṃ 
bhikkhu_
****

____
In this regard, bhikkhu, abide contemplating the nature of the body internally

_idha tvaṃ bhikkhu ajjhattaṃ kāye kāyānupassī viharāhi_
____

____
abide contemplating the nature of the body externally

_bahiddhā kāye kāyānupassī viharāhi_
____

[quote, S.5.143]
____
abide contemplating the nature of the body internally and externally

_ajjhattabahiddhā kāye kāyānupassī viharāhi._
____

3. Having washed his feet he seats himself. Having crossed his legs, having set 
his body erect, having established mindfulness within himself,
+
****
_So pāde pakkhāletvā nisīdati pallaṅkaṃ ābhujitvā ujuṃ kāyaṃ 
paṇidhāya parimukhaṃ satiṃ upaṭṭhapetvā._
****

• ... He sits reflecting on his own welfare, on the welfare of others and on 
the welfare of both, indeed on the welfare of the whole world. +
_Attahitaṃ parahitaṃ ubhayahitaṃ sabbalokahitameva so bhavaṃ gotamo 
cintento nisinno hoti_ (M.2.139).

==== Connecting the absolutives

Ānandajoti says:

- 'The absolutives here and in the next line are connected with the finite 
verbs _assasati_ and _passasati_, and not with _nisīdati_ in the preceding 
line, in which case the folding of the legs, setting the body straight, and 
establishment of mindfulness would all occur before he sat down!'

We render _pallaṅkaṃ ābhujitvā_ as 'having crossed his legs,' ('having 
bent in the round lap,' says PED, sv _Ābhujati_), and thus the sentence as 
follows:

[quote, M.1.56]
____
He seats himself. Having crossed his legs, having set his body erect, having 
established mindfulness within himself, mindfully he breathes in; mindfully he 
breathes out.

_nisīdati pallaṅkaṃ ābhujitvā ujuṃ kāyaṃ paṇidhāya parimukhaṃ 
satiṃ upaṭṭhapetvā. So satova assasati sato passasati._
____

