== Pariciṇṇo mayā satthā

=== Renderings

- _Pariciṇṇo mayā satthā_: the Teacher has been [lovingly] venerated by 
me [through my practice in accordance with the teaching]

=== Introduction

==== Gratitude plus arahantship

_Pariciṇṇo mayā satthā_ is an expression of gratitude to the Buddha that 
simultaneously indicates the attainment of arahantship. For example, it was 
used in this way by Venerable Vacchagotta (M.1.497), and also by ten bhikkhus 
in the _Theragāthā_. See Illustrations.

==== Origin: veneration of fires

_Pariciṇṇo_ may have stemmed from its application to the veneration of 
sacrificial fires. For example, the Buddha said:

[quote, M.1.82]
____
'It would not be easy to find a kind of fire that has not been venerated by me 
(_apariciṇṇapubbo_) in this long time':

_Na kho paneso sāriputta aggi sulabharūpo yo mayā apariciṇṇapubbo iminā 
dīghena addhunā._
____

Venerating fires and people is intimately linked through words like 
_namassati_, _paricarati,_ and _pūjeti_:

[quote, Dh.v.392]
____
From whoever one might learn the teaching explained by the Perfectly 
Enlightened One, one should respectfully venerate him like a brahman venerates 
the sacrificial fire.

_Yamhā dhammaṃ vijāneyya sammāsambuddhadesitaṃ +
Sakkaccaṃ taṃ namasseyya aggihuttaṃ va brāhmaṇo._
____

[quote, Dh.v.107]
____
If a person venerated fire in the forest for a century, but then venerated even 
for a moment someone who had spiritually developed himself, that veneration 
would be certainly better than that [fire] veneration for a century.

_Yo ca vassasataṃ jantu aggiṃ paricare vane +
Ekañca bhāvitattānaṃ muhuttamapi pūjaye +
Sā yeva pūjanā seyyo yañce vassasataṃ hutaṃ._
____

==== Venerating the sacrificial fire

The ceremony of venerating the sacrificial fire has three aspects:

1. It begins with pouring foodstuffs into the fire (_aggiṃ juhati_), for 
example, milk rice (S.1.166) or milk (A.2.207) or ghee, oil and butter 
(A.5.234), though sometimes animals (A.4.41; D.1.141).

2. Then follows the veneration of the sacrificial fire (_aggihuttaṃ 
paricarati_). This is done by venerating the fire with joined palms, and 
solemnly addressing it:
+
[quote, A.5.234]
____
'We lower ourselves before thee, Lord. We lower ourselves before thee, Lord.'

_paccorohāma bhavantaṃ paccorohāma bhavantan ti._
____

3. Then comes the distribution of the remains of the oblation (_havyasesaṃ_ 
Sn.p.79) to any available ascetics or Brahmanists.
+
For example:
+
[quote, S.1.166]
____
At one time milk rice with ghee had been set out for the brahman Aggika 
Bhāradvāja, who had thought 'I will offer them to the fire. I will venerate 
the sacrificial fire.'

_Tena kho pana samayena aggikabhāradvājassa brāhmaṇassa sappinā pāyāso 
sannihito hoti aggiṃ juhissāmi. Aggihuttaṃ paricarissāmī ti._
____
+
[quote, Sn.p.79]
____
At that time the brahman Sundarika Bhāradvāja was making offerings to fire 
and venerating the sacrificial fire on the bank of the River Sundarikā. Having 
done so, and having risen from his seat, he looked around in the four 
directions to see who might eat the remains of the oblation.

_Tena kho pana samayena sundarikabhāradvājo brāhmaṇo sundarikāya nadiyā 
tīre aggiṃ juhati aggihuttaṃ paricarati atha kho sundarikabhāradvājo 
brāhmaṇo aggiṃ juhitvā aggihuttaṃ paricaritvā uṭṭhāyāsanā 
amannā catuddisā anuvilokesi ko nu kho imaṃ havyasesaṃ bhuñjeyyāti._
____

==== Two meanings of paricarati

_Pariciṇṇo_ is the past particle of _paricarati_, and therefore its meaning 
would stem from one of the two meanings of _paricarati_ which can be explained 
as follows:

1. A matted-hair ascetic told a boy to look after the fire, not let it go out 
(_aggiṃ tāta paricareyyāsi. Mā ca te aggi nibbāyi_ D.2.340). Here 
_paricarati_ does not mean veneration, but just keeping the fire going.

2. More usually in the scriptures, _paricarati_ is a ceremonial activity that 
means venerating, and occurs in the phrase _aggihuttaṃ paricarati_. 
_Aggihuttaṃ_ means 'sacrificial fire.' _Huttaṃ_ is the past participle of 
_juhati_.

==== Pariciṇṇo: therefore two possible meanings

_Pariciṇṇo_ could therefore mean either the Teacher has been 'looked after 
by me' or 'venerated by me.' The latter is obviously more likely. The Buddha 
said to look after him one should look after the sick (_yo bhikkhave maṃ 
upaṭṭhaheyya so gilānaṃ upaṭṭhaheyya,_ Vin.1.302) -- which is not 
the issue here.

==== To venerate the Perfect One: meaning

So, what does it mean to venerate the Perfect One? The Buddha said:

[quote, D.2.138]
____
Those who practise in accordance with the teaching, applying themselves 
properly, and conducting themselves in accordance with the teaching, honour, 
revere, respect, reverence, and venerate the Perfect One with the highest 
veneration.

_yo kho ānanda bhikkhu vā bhikkhunī vā upāsako vā upāsikā vā 
dhammānudhammapaṭipanno viharati sāmīcipaṭipanno anudhammacārī so 
tathāgataṃ sakkaroti garukaroti māneti pūjeti apaciyati paramāya 
pūjāya._
____

Therefore _pariciṇṇo mayā satthā_ means 'the Teacher has been [lovingly] 
venerated by me [through my practice in accordance with the teaching].' For 
this reason _pariciṇṇo mayā satthā_ not only expresses gratitude to the 
Buddha, but simultaneously indicates the attainment of arahantship.

==== Lovingly

The _Ukkhittāsika Sutta_ says that venerating the Buddha is done with 
_mettā_. It explains the six advantages of practising according to the 
teaching, the last of which is:

[quote, A.3.443]
____
The Teacher will be lovingly venerated by me through my practice [in accordance 
with the teaching]

_Satthā ca me pariciṇṇo bhavissati mettāvatāyā tī._
____

This is the source of our parenthesis.

==== Channovāda Sutta

Venerable Channa said that for a long time he had 'venerated the Teacher 
_manāpeneva no amanāpena_, [through his practice in accordance with the 
teaching], as was fitting for a disciple to do': _Api cāvuso sāriputta 
pariciṇṇo me satthā dīgharattaṃ manāpeneva no amanāpena. Etaṃ hi 
āvuso sāriputta sāvakassa patirūpaṃ yaṃ satthāraṃ paricareyya 
manāpeneva no amanāpena_ (M.3.264).

Let us consider how to translate this. Firstly, _manāpa_ and _amanāpa_ can 
mean pleasing and displeasing:

[quote, S.4.172]
____
The eye is attacked by pleasing and displeasing sights.

_Cakkhu bhikkhave haññati manāpāmanāpesu rūpesu._
____

Venerable Channa would then be saying 'the Teacher has been [lovingly] 
venerated by me [through my practice in accordance with the teaching] which has 
been pleasing, not displeasing,' which does not fit.

Alternatively _manāpa_ and _amanāpa_ are synonyms of _piya_ and _appiya_, 
meaning dear and loathsome:

____
He has harmed, is harming, or will harm someone beloved and dear to me.

_Piyassa me manāpassa anatthaṃ acarīti... caratīti... carissatīti_
____

[quote, A.5.150; D.3.263]
____
He has benefited, is benefiting, or will benefit someone who is unbeloved or 
loathsome to me.

_Appiyassa me amanāpassa atthaṃ acari... carati... carissatī ti._
____

In this case, Channa would be saying that his practice had been dear, not 
loathsome. This again is inapt, but supports us saying 'lovingly, not 
unlovingly,' which is likewise Bodhi's solution: 'with love, not without love.'

[quote, M.3.264]
____
But Sāriputta, friend, the Teacher has been lovingly venerated by me [through 
my practice in accordance with the teaching], not unlovingly, as was fitting 
for a disciple to do.

_Api cāvuso sāriputta pariciṇṇo me satthā dīgharattaṃ manāpeneva no 
amanāpena. Etaṃ hi āvuso sāriputta sāvakassa patirūpaṃ yaṃ 
satthāraṃ paricareyya manāpeneva no amanāpena._
____

=== Illustrations

.Illustration
====
pariciṇṇo mayā satthā

the Teacher has been [lovingly] venerated by me [through my practice in 
accordance with the teaching]
====

[quote, Th.v.604]
____
The Teacher has been [lovingly] venerated by me [through my practice in 
accordance with the teaching]. I have fulfilled the Buddha's training system. 
The heavy burden [of the five grasped aggregates] is laid down. The conduit to 
renewed states of individual existence has been abolished.

_Pariciṇṇo mayā satthā kataṃ buddhassa sāsanaṃ +
Ohito garuko bhāro bhavanetti samūhatā._
____

