== Paritassati

=== Renderings

- _paritassanā_: distress

- _paritassati_: to be distressed

- _paritassati_: to be apprehensive

=== Introduction

==== Paritassati: to be distressed or apprehensive

_Paritassati_ means to be either distressed or apprehensive. The difference is 
this:

1. Distress arises from lack:

- lack of company

- lack of success

- failing to obtain something

- losing something.

2. Apprehension is often associated with trembling. It arises from

____
grasping

_upādiyati; upādānaṃ_
____

____
craving

_taṇhā_
____

____
attachment

_upadhi_
____

==== Paritassanā: distress

The noun _paritassanā_ means distress. It never means apprehension.

=== Illustrations

.Illustration
====
paritassanā

distress
====

[quote, D.1.17]
____
A being passes away from the Ābhassarā world and arises in an empty Brahmā 
palace. After dwelling alone for a long time, there arises in him uneasiness, 
dissatisfaction, and distress, and he thinks, 'If only some other beings would 
come here!'

_Tassa tattha ekakassa dīgharattaṃ nibbusitattā anabhirati paritassanā 
uppajjati aho vata aññe pi sattā itthattaṃ āgaccheyyun ti._
____

.Illustration
====
paritassanā

distress
====

[quote, D.2.239]
____
The Great Steward practised a meditation on [unlimited, all-encompassing] 
compassion for four months, hoping to see Brahmā with his eyes, but after that 
time just felt dissatisfaction and distress.

_Atha kho bho mahāgovindasasa brāhmaṇassa catunnaṃ māsānaṃ accayena 
ahu deva ukkaṇṭhanā ahu paritassanā._
____

.Illustration
====
paritassanā

distress
====

Then it occurred to Venerable Channa:

'I too think in this way: "Bodily form is unlasting... advertence is unlasting. 
Bodily form is void of personal qualities... advertence is void of personal 
qualities. All originated phenomena are unlasting; all things are void of 
personal qualities."'

• 'But my mind is not energised for the quelling of all originated phenomena, 
the relinquishment of the whole phenomenon of attachment, the destruction of 
craving, the passing away [of originated phenomena], the ending [of originated 
phenomena], the Untroubled; nor does it become serene, settled, intent upon it. 
+
_Atha ca pana me sabbasaṅkhārasamathe sabbūpadhipaṭinissagge 
taṇhakkhaye virāge nirodhe nibbāne cittaṃ na pakkhandati nappasīdati na 
santiṭṭhati nādhimuccati_

• Instead, distress and grasping arise [in me], and my mind turns back on 
itself, thinking: 'But what, then, is my [absolute] Selfhood?' +
_paritassanā upādānaṃ uppajjati paccudāvattati mānasaṃ atha ko carahi 
me attā ti_ (S.3.133).

.Illustration
====
paritassanā

distressed
====

[quote, M.1.136]
____
In this regard, some person thinks, 'Alas, it was mine, but now is not mine! 
What might have been mine, alas, I do not get it!' He grieves, suffers, and 
laments, weeps beating his chest, and falls into bewilderment. Thus is he 
distressed about what does not exist externally.

_idha bhikkhu ekaccassa evaṃ hoti ahu vata me taṃ vata me natthi siyā vata 
me taṃ vatāhaṃ na labhāmīti. So socati kilamati paridevati 
urattāḷiṃ kandati sammohaṃ āpajjati. Evaṃ kho bhikkhu bahiddhā asati 
paritassanā hotī ti._
____

.Illustration
====
paritassati

distressed
====

[quote, D.3.224; A.2.27]
____
If a bhikkhu who is true to the ancient, primordial noble tradition (_bhikkhu 
porāṇe aggaññe ariyavaṃse ṭhito_) does not get robe material he is not 
distressed.

_aladdhā ca cīvaraṃ na paritassati._
____

.Illustration
====
paritassati

distressed
====

[quote, A.3.133]
____
When a bhikkhu is neither renowned, nor distressed by a lack of renown, in this 
way he can dwell at ease while living in a monastic community

_bhikkhu... appaññāto ca hoti tena ca appaññātakena no paritassati 
ettāvatā pi kho ānanda bhikkhu saṅghe viharanto phāsuṃ vihareyyāti._
____

.Illustration
====
paritassita

apprehension
====

[quote, D.1.40]
____
When those ascetics and Brahmanists who are eternalists proclaim the eternity 
of an [absolute] Selfhood and the world [of beings] in four ways, that is 
merely a matter of sense impression in reverend ascetics and Brahmanists that 
is neither known nor seen [according to reality]. It is merely the apprehension 
and trembling of those overcome by craving.

_Tatra bhikkhave ye te samaṇabrāhmaṇā sassatavādā sassataṃ 
attānañca lokañca paññāpenti catūhi vatthūhi tadapi tesaṃ bhavataṃ 
samaṇabrāhmaṇānaṃ ajānataṃ apassataṃ vedayitaṃ 
taṇhāgatānaṃ paritassitavipphanditameva._
____

.Illustration
====
paritassanā

distress; paritassati, apprehensive
====

____
When the bodily form of the ignorant Everyman changes and alters.

_Tassa taṃ rūpaṃ vipariṇamati aññathā hoti._
____

____
With the change and alteration of bodily form, his mind is preoccupied with the 
change

_Tassa rūpavipariṇāmaññathābhāvā rūpavipariṇāmānuparivatti 
viññāṇaṃ hoti._
____

____
Distress and other mental states born of this preoccupation plague his mind.

_Tassa rūpavipariṇāmānuparivattijā paritassanā dhammasamuppādā 
cittaṃ pariyādāya tiṭṭhanti._
____

____
Thus he is fearful, distressed, and full of concern,

_Cetaso pariyādānā uttāsavā ca hoti vighātavā ca apekkhavā ca_
____

[quote, S.3.16]
____
and because of grasping he is apprehensive.

_upādāya ca paritassati._
____

.Illustration
====
paritassati

apprehensive
====

____
When a bhikkhu abides contemplating unlastingness, passing away, ending, and 
relinquishment of sense impression he does not grasp anything in the world [of 
phenomena]

_so tāsu vedanāsu aniccānupassī viharanto virāgānupassī viharanto 
nirodhānupassī viharanto paṭinissaggānupassī viharanto na ca kiñci loke 
upādiyati._
____

• Being without grasping, he is not apprehensive. +
☸ a__nupādiyaṃ na paritassati__.

[quote, M.1.251]
____
Being not apprehensive, he realises the Untroubled for himself.

_aparitassaṃ paccattaṃ yeva parinibbāyati._
____

.Illustration
====
paritassati

apprehensive
====

[quote, M.2.138]
____
When the Buddha is seated indoors he is not afraid, he does not shake or 
tremble, he is not apprehensive.

_So antaraghare nisinnova samāno nacchambhati na kampati na vedhati na 
paritassati._
____

.Illustration
====
paritassati

apprehensive
====

____
If a bhikkhu's mind is unattached to bodily form... advertence, it is liberated 
from perceptually obscuring states through being without grasping.

_Rūpadhātuyā... viññāṇadhātuyā ce bhikkhave bhikkhuno cittaṃ 
virattaṃ vimuttaṃ hoti anupādāya āsavehi._
____

____
Being thus liberated it is inwardly stable

_Vimuttattā ṭhitaṃ_
____

____
Being inwardly stable it is inwardly at peace

__Ṭhitattā santusitaṃ_
____

____
Being inwardly at peace, he is not apprehensive

_Santusitattā na paritassati._
____

[quote, S.3.45]
____
Being not apprehensive, he realises the Untroubled for himself.

_Aparitassaṃ paccattaṃ yeva parinibbāyati._
____

.Illustration
====
na paritassati

free of apprehension
====

[quote, Sn.v.621; Dh.v.397]
____
He who has severed every tie to individual existence is truly free of 
apprehension.

_Sabbasaṃyojanaṃ chetvā yo ve na paritassati._
____

.Illustration
====
paritassati

apprehensive
====

____
Likewise, a bhikkhu does not consider the six senses to be either [in reality] 
himself or [in reality] his own.

_Evameva kho āvuso bhikkhu chasu phassāyatanesu neva attānaṃ nāttaniyaṃ 
samanupassati_
____

____
Therefore he does not grasp anything in the world [of phenomena].

_so evaṃ asamanupassanto na kiñci loke upādiyati_
____

____
Therefore he is not apprehensive.

_anupādiyaṃ na paritassati_
____

[quote, S.4.167-8]
____
Being not apprehensive, he realises the Untroubled for himself.

_aparitassaṃ paccattaṃ yeva parinibbāyati._
____

