== Passati; Vipassati

=== Renderings

- _passati_: to see

- _passati_: to perceive

- _passati_: to regard

- _passati_: to contemplate

- _passati_: to find

- _passati_: to experience

- _passati_: to examine

- _passati_: to acknowledge

- _passati_: to notice

- _passati_: to understand

- _passati_: to realise

- _passati_: to see [according to reality]

- _passati_: to see [the nature of reality]

- _vipassati_: to see [according to reality]

- _vipassati_: to see [the nature of reality]

=== Introduction

==== See

_Passati_ means 'see':

[quote, D.2.237]
____
He sees Brahmā.

_so brahmānaṃ passati._
____

[quote, Vin.1.295]
____
One sees no odious dreams.

_Na pāpakaṃ supinaṃ passati._
____

==== Synonyms of 'see'

_Passati_ can also be rendered with words like 'perceive,' 'regard,' or 
'contemplate' etc:

[quote, S.3.51]
____
Perceive: A bhikkhu perceives as unlasting, bodily form which is indeed 
unlasting.

_Aniccaññeva bhikkhave bhikkhu rūpaṃ aniccanti passati._
____

[quote, Sn.v.798]
____
Regard: The wise call that thing a spiritual shackle if, on account of it, one 
regards other people as inferior.

_Taṃ vāpi ganthaṃ kusalā vadanti +
Yaṃ nissito passati hinamaññaṃ._
____

[quote, Dh.v.113]
____
Contemplate: Better than the life of one who lives a hundred years not 
contemplating [co-conditional] arising and disappearance, is the life of a 
single day of one who contemplates [co-conditional] arising and disappearance.

_Yo ca vassasataṃ jīve apassaṃ udayabbayaṃ +
Ekāhaṃ jīvitaṃ seyyo passato udayabbayaṃ._
____

[quote, Sn.v.1119]
____
Find: Viewing the world in this way, the King of Death does not find one.

_Evaṃ lokaṃ avekkhantaṃ maccurājā na passatī ti._
____

[quote, S.3.141]
____
Examine: A mirage is shimmering. A clear-sighted man would examine it, ponder 
it, and properly investigate it.

_marici phandati tamenaṃ cakkhumā puriso passeyya nijjhāyeyya yoniso 
upaparikkheyya._
____

[quote, Vin.2.21]
____
Acknowledge: Now at that time Venerable Channa, having fallen into an offence, 
did not want to acknowledge the offence.

_Tena kho pana samayena āyasmā chanto āpattiṃ āpajjitvā na icchati 
āpattiṃ passituṃ._
____

• Notice: Whoever notices the pots of water for drinking, washing, or for the 
toilets is empty or drained, he replenishes them. +
_Yo passati pānīyaghaṭaṃ vā paribhojanīyaghaṭaṃ vā vaccaghaṭaṃ 
vā rittaṃ tucchaṃ so upaṭṭhapeti_ (M.1.207).

[quote, Dh.v.115]
____
Understand: Better than the life of one who lives a hundred years not 
understanding the supreme teaching, is the life of a single day of one who 
understands the supreme teaching.

_Yo ca vassasataṃ jīve apassaṃ dhammamuttamaṃ +
Ekāhaṃ jīvitaṃ seyyo passato dhammamuttamaṃ._
____

[quote, Dh.v.114]
____
Realise: Better than the life of one who lives a hundred years not realising 
the Deathless State, is the life of a single day of one who realises the 
Deathless State.

_Yo ca vassasataṃ jīve apassaṃ amataṃ padaṃ +
Ekāhaṃ jīvitaṃ seyyo passato amataṃ padaṃ._
____

[quote, Dh.v.120]
____
Experience: Even a virtuous person experiences misfortune as long as his merit 
does not bear fruit. But when his merit bears fruit, then the virtuous person 
experiences [the karmic consequences of] his virtuous [deeds].

_Bhadro pi passati pāpaṃ yāva bhadraṃ na paccati +
Yadā ca paccati bhadraṃ atha bhadro bhadrāni passati._
____

==== With yathābhūtaṃ

In its exalted sense, _passati_ is sometimes linked to _yathābhūtaṃ_:

[quote, M.1.234-5]
____
A disciple of mine... perceives all bodily form according to reality with 
perfect penetrative discernment as "not [in reality] mine," "not [in reality] 
what I am," "not my [absolute] Selfhood."

_Idha aggivessana mama sāvako... sabbaṃ rūpaṃ n'etaṃ mama n'eso'hamasmi 
na me so attā ti evametaṃ yathābhūtaṃ sammappaññāya passati._
____

[quote, Th.v.716]
____
There is no fear for one who perceives according to reality +
The pure and simple origination of phenomena +
And the pure and simple continuity of originated phenomena, captain.

_suddhaṃ dhammasamuppādaṃ suddhaṃ saṅkharasantatiṃ +
passantassa yathābhūtaṃ na bhayaṃ hoti gāmaṇi._
____

[quote, Ud.32-3]
____
On perceiving this according to reality with perfect penetrative discernment

_evametaṃ yathābhūtaṃ sammappaññāya passato._
____

• I know and see things according to reality _ +
yathābhūtaṃ jānāmi passāmī ti_ (A.5.313).

==== With dhamma

In its exalted sense, _passati_ is sometimes linked to _dhamma_, which together 
means 'see the nature of reality' and is equivalent to arahantship. The 
parentheses in this section will be explained in the following section.

[quote, S.3.132-3]
____
Who could possibly explain the teaching to me such that I might see the nature 
of reality?

_ko nu kho me tathā dhammaṃ deseyya yathāhaṃ dhammaṃ passeyyan ti._
____

[quote, M.1.190]
____
He who sees dependent origination [according to reality] sees the nature of 
reality; he who sees the nature of reality sees dependent origination 
&#8203;[according to reality].

_yo paṭiccasamuppādaṃ passati so dhammaṃ passati. Yo dhammaṃ passati 
so paṭiccasamuppādaṃ passatī ti._
____

[quote, S.3.120]
____
One who sees the nature of reality sees me [according to reality]. One who sees 
me [according to reality] sees the nature of reality.

_yo kho vakkali dhammaṃ passati so maṃ passati yo maṃ passati so 
dhammaṃ passati._
____

[quote, Dh.v.259]
____
He who, after hearing just a little, realises the nature of reality with his 
very being, and is not negligent of the practice, is truly expert in the 
teaching.

_Yo ca appampi sutvāna dhammaṃ kāyena passati sa ve dhammadharo hoti yo 
dhammaṃ nappamajjati._
____

==== Exalted sense: objectless

In its exalted sense, _passati_ is sometimes objectless. We have noticed this 
already in the parentheses of the previous paragraph. This is the aspect which 
justifies our particular interest in the word. For sentences to remain 
comprehensible, some exalted noun or adverb needs adding. We do this in 
accordance with word combinations noted above. Accordingly:

1. for the noun, we parenthesise _dhammaṃ_ (='see [the nature of reality]')

2. for the adverb we parenthesise _yathābhūtaṃ_ (='see [according to 
reality]').

==== Noun parentheses

Similar parentheses may need adding to _passato_:

[quote, Ud.79]
____
For one who sees [the nature of reality], there is [nowhere] anything at all.

_passato natthi kiñcanaṃ ti._
____

[quote, It.21]
____
For one who sees [the nature of reality], attachment is destroyed.

_passato upadhikkhayaṃ._
____

==== Synonym parentheses

The same parentheses may need adding to synonyms. For example, in the following 
quote, _na dissati_ is linked to _yathābhūtaṃ_. Therefore the _adassanā_ 
that follows stands for _yathābhūtaṃ adassanā_:

____
Camouflaged by skin, the body is not seen according to reality 
(_yathābhūtaṃ na dissati_)...

_Chaviyā kāyo paṭicchanno yathābhūtaṃ na dissati..._
____

• ... Whoever would think to be swelled-headed because of such a body, or 
would disparage another, what is this except not seeing it [according to 
reality] (_adassanā_)? +
_☸ ... kimaññatra adassanā ti_ (Sn.v.194; Sn.v.206).

==== Vipassati: to see [according to reality]; to see [the nature of reality]

We treat _vipassati_ as _passati_ in its exalted form, parenthesising 
accordingly:

[quote, Dh.v.174]
____
Spiritually blind is this world [of beings]: few [men] here see [the nature of 
reality].

_Andhabhūto ayaṃ loko tanuk'ettha vipassati._
____

[quote, Sn.v.1115]
____
Knowing the arising of nonexistence [according to reality], and knowing that 
spiritually fettering delight is a tie to individual existence, knowing this 
thus, then he sees this matter [according to reality].

_Ākiñcaññasambhavaṃ ñatvā nandi saṃyojanaṃ iti +
Evametaṃ abhiññāya tato tattha vipassati._
____

[quote, Th.v.1091]
____
Seeing all states of individual existence [according to reality] as unlasting? 
This wish of mine, when, oh when, will it be [fulfilled]?

_Aniccato sabbabhavaṃ vipassaṃ taṃ me idaṃ taṃ nu kadā bhavissati._
____

Sometimes it is not necessary to parenthesise, because the qualification is 
explicit:

[quote, Th.v.1071]
____
There is not such delight in the music of the fivefold ensemble as there is for 
one with an undistracted mind who rightly sees the nature of reality.

_Na pañcaṅgikena turiyena na ratī hoti tādisī +
Yathā ekaggacittassa sammā dhammaṃ vipassato._
____

=== Illustrations: see the nature of reality

.Illustration
====
dhammaṃ passeyyaṃ

see the nature of reality
====

[quote, S.3.132]
____
Venerable Ānanda is capable of explaining the teaching to me such that I might 
see the nature of reality.

_pahoti ca me āyasmā ānando tathā dhammaṃ desetaṃ yathāhaṃ dhammaṃ 
passeyyaṃ._
____

.Illustration
====
dhammaṃ vipassato

see the nature of reality with insight
====

[quote, S.1.129]
____
What difference does womanhood make when the mind is well-collected, when 
knowledge [of things according to reality] exists in one who rightly sees the 
nature of reality?

_Itthibhāvo kiṃ kayirā cittamhi susamāhite +
Ñāṇamhi vattamānamhi sammā dhammaṃ vipassato._
____

=== Illustrations: see [according to reality]

.Illustration
====
passati

see [according to reality]
====

[quote, S.5.121]
____
On that occasion one neither knows nor sees [according to reality] one's own 
good.

_Attatthampi tasmiṃ samaye yathābhūtaṃ na jānāti na passati._
____

.Illustration
====
passati

see [according to reality]
====

____
There are these eighteen elements of sensation:

_Aṭṭhārasa kho imā ānanda dhātuyo:_
____

____
The phenomenon of sight... phenomenon of advertence to the mental field.

_cakkhudhātu... manoviññāṇadhātu ti_
____

[quote, M.3.62]
____
Through knowing and seeing these eighteen elements of sensation [according to 
reality], a bhikkhu can be called knowledgeable about elements of existence

_Imā kho ānanda aṭṭhārasa dhātuyo yato jānāti passati ettāvatā pi 
kho ānanda dhātukusalo bhikkhū ti alaṃ vacanāyā ti._
____

.Illustration
====
passati

see [according to reality]
====

[quote, M.1.111]
____
For in knowing, the Blessed One knows [according to reality]; in seeing, he 
sees [according to reality].

_So hāvuso bhagavā jānaṃ jānāti passaṃ passati._
____

.Illustration
====
passati

seeing [according to reality]
====

[quote, M.3.62]
____
Through knowing and seeing these six phenomena [according to reality] a bhikkhu 
can be called knowledgeable about elements of existence.

_Imā kho ānanda cha dhātuyo yato jānāti passati ettāvatā pi kho ānanda 
dhātukusalo bhikkhū ti alaṃ vacanāyā ti._
____

.Illustration
====
passami

see [according to reality]
====

[quote, D.2.110-111]
____
Being in a refined material state of awareness, one sees a limited quantity of 
shapes, beautiful or ugly. By gaining mastery over them, he is aware that he 
knows and sees them [according to reality]. This is the first practice of 
spiritual development leading to mastery.

_Ajjhattaṃ rūpasaññī eko bahiddhā rūpāni passati parittāni 
suvaṇṇadubbaṇṇāni tāni abhibhuyya jānāmi passāmī ti 
evaṃsaññī hoti. Idaṃ paṭhamaṃ abhibhāyatanaṃ._
____

=== Illustrations: see [the nature of reality]

.Illustration
====
passato

see [the nature of reality]
====

[quote, Ud.80]
____
For one who has mastered craving, for one who knows and sees [the nature of 
reality], there is [nowhere] anything at all.

_Paṭividdhā taṇhā jānato passato natthi kiñcanaṃ ti._
____

.Illustration
====
passato

sees [the nature of reality]
====

[quote, Ud.10]
____
Blissful is the physical seclusion of one who is content [with what is paltry 
and easily gotten], who has heard the teaching, and who sees [the nature of 
reality]._

_Sukho viveko tuṭṭhassa sutadhammassa passato._
____

.Illustration
====
passāmi

see [the nature of reality]
====

[quote, S.5.226]
____
Those things I had previously only heard about, I now abide contacting with my 
very being. I see [the nature of reality] having penetrated it with discernment.

_ime kho te dhammā ye me pubbe sutāva ahesuṃ tenāhaṃ etarahi kāyena ca 
phusitvā viharāmi. Paññāya ca ativijjha passāmī ti._
____

