== Pasīdati; Pasāda; Pasanna

=== Renderings

==== Unprefixed words

- _pasīdati_: to believe in

- _pasīdati_: to gain/have faith in

- _pasīdati_: to gain faith [in the perfection of the Perfect One's 
transcendent insight]

- _pasīdati_: to be filled with faith

- _pasīdati_: to be/become serene

- _pasādeti_: to be serene

- _pasādeti_: to be filled with faith

- _pasāda_: serenity

- _pasāda_: serene

- _pasāda_: faith

- _pasāda_: faith [in the perfection of the Perfect One's transcendent insight]

- _pasādaniya_: faith inspiring

- _pasādaniya_: worthy of faith

- _pasanna_: serenity

- _pasanna_: serene

- _pasanna_: pure

- _pasanna_: believe in

- _pasanna_: faith

- _pasanna_: having faith

- _pasanna_: to be convinced

- _puggalappasāde_: having faith which is based on a single individual

==== Prefixed words

- _abhippasanno_: have complete faith

- _vippasīdati_: become serene

- _vippasādeti_: to make serene (the mind)

- _vippasanna_: limpid

- _vippasanna_: serene

- _sampasīdati_: be settled

- _sampasīdati_: to have faith

- _sampasāda_: serenity

- _sampasāda_: faith

- _sampasādaniya_: inspiring of faith

- _sampasādana_: serenity

=== Introduction

==== Introduction: word family

The word family considered here is:

_• pasīdati_: believe in, gain faith in, be serene

_• pasāda_: faith, serenity

- _pasādeti_: be serene

_• pasādaniya_: faith inspiring, worthy of faith

_• pasanna_: serene, believe in, faith

==== Introduction: prefixes

These terms are straightforward, but their number of associated prefixes is 
daunting. Fortunately the effect of these prefixes (_abhi- vi-_ and _sam-_) is 
negligible except in two respects:

1. Whereas _pasīdati_ and _sampasīdati_ mean 'have faith in,' 
_abhippasīdati_ means 'have complete faith'

2. The unprefixed word family has a larger range of meaning than the prefixed 
words, and so the meanings of prefixed words all fall within the range of 
unprefixed words, with one exception: whereas _vippasanna_ can mean limpid, 
_pasanna_ cannot.

==== Introduction: objects of faith

The objects of faith are sometimes explicit:

[quote, S.1.160]
____
A brahman lady had complete faith in the Buddha, the teaching, and the 
community of the Blessed One's disciples.

_Tena kho pana samayena aññatarassa bhāradvājagottassa brāhmaṇassa 
dhanañjānī nāma brāhmaṇī abhippasannā hoti buddhe ca dhamme ca 
saṅghe ca._
____

If not, the object can be easily gathered from context:

[quote, Th.v.1276]
____
Hearing your voice, best of seers, I have faith [in you].

_Esa sutvā pasīdāmi vaco te isisattama._
____

==== Faith: technically speaking

_Pasanna_ is a synonym of _saddha,_ as seen in the following quotes:

- _tīhi bhikkhave ṭhānehi saddho pasanno veditabbo_ (A.1.150).

- _so saddho pasanno_ (D.1.212).

Because the object of _saddha_ is 'the perfection of the Perfect One's 
transcendent insight,' the same applies to _pasanna_.

[quote, S.5.225]
____
The noble disciple who has complete faith in the [perfection of the] Perfect 
One's [transcendent insight] does not have any unsureness or doubt about the 
&#8203;[perfection of the] Perfect One's [transcendent insight], or about the 
&#8203;[significance of the] Perfect One's training system.

_Yo so bhante ariyasāvako tathāgate ekantagato abhippasanno na so tathāgate 
vā tathāgatasāsane vā kaṅkheyya vā vicikiccheyya vā._
____

[quote, Th.v.673]
____
Having heard the teaching of great flavour, I have even more faith [in the 
perfection of the Perfect One's transcendent insight].

_Esa bhiyyo pasīdāmi sutvā dhammaṃ mahārasaṃ._
____

==== Introduction: aveccappasāda

_Aveccappasāda_ is presented separately, sv _Aveccappasāda_.

=== Illustrations: abhippasanno

.Illustration
====
abhippasannā

have complete faith in
====

[quote, M.1.502]
____
Many learned _khattiyas_, brahmans, householders and ascetics have complete 
faith in Master Gotama.

_bahū hi tassa bhoto gotamassa khattiyapaṇḍitāpi 
brāhmaṇapaṇḍitāpi gahapatipaṇḍitāpi samaṇapaṇḍitāpi 
abhippasannā._
____

.Illustration
====
abhippasanno

have complete faith
====

[quote, D.2.206]
____
From the time when I had complete faith in the Blessed One, from then on for a 
long time I have perceived that I will not be reborn in the plane of damnation, 
that [I will not go to] the plane of damnation.

_Yadagge ahaṃ bhante bhagavati ekantagato abhippasanno tadagge ahaṃ bhante 
dīgharattaṃ avinipāto avinipātaṃ sañjānāmi._
____

.Illustration
====
abhippasannā

complete faith in
====

[quote, D.1.116]
____
Truly sirs, many devas and men have complete faith in the ascetic Gotama

_Samaṇe khalu bho gotame bahū devā manussā ca abhippasannā._
____

.Illustration
====
abhippasannā

complete faith in
====

[quote, D.1.211]
____
This Nāḷandā is rich, prosperous, populous, and crowded with people with 
complete faith in the Blessed One. It were well if the Blessed One got a 
bhikkhu to perform superhuman displays of psychic power. In this way even more 
people in Nāḷandā would have complete faith in the Blessed One.

_ayaṃ bhante nāḷandā iddhā ceva thitā ca bahujanā ākiṇṇamanussā 
bhagavati abhippasannā. Sādhu bhante bhagavā ekaṃ bhikkhuṃ samādisatu 
yo uttarimanussadhammā iddhipāṭihāriyaṃ karissati. Evāyaṃ nāḷandā 
bhiyyosomattāya bhagavati abhippasīdissatī ti._
____

.Illustration
====
abhippasanno

complete faith in
====

[quote, M.2.146]
____
The matted-hair ascetic had complete faith in the brahman Sela.

_tena kho pana samayena keṇiyo jaṭilo sele brāhmaṇe abhippasanno hoti._
____

=== Illustrations: vippasīdati

.Illustration
====
sammāvippasīdati

become serene
====

[quote, D.2.216]
____
As he abides contemplating the nature of the body internally he becomes 
perfectly inwardly collected and perfectly serene. Being thus perfectly 
inwardly collected and perfectly serene he arouses knowledge and vision 
externally of others' bodies [according to reality].

_Ajjhattaṃ kāye kāyānupassī viharanto tattha sammāsamādhiyati 
sammāvippasīdati. So tattha sammā samāhito sammāvippasanno bahiddhā 
parakāye ñāṇadassanaṃ abhinibbatteti._
____

.Illustration
====
vippasīdati

become serene
====

• When Master Gotama is spoken to offensively the colour of his skin 
brightens and his countenance becomes serene as is to be expected of one who is 
accomplished and perfectly enlightened. +
☸ _chavivaṇṇo ceva pariyodāyati mukhavaṇṇo ca vippasīdati_, _yathā 
taṃ arahato sammā sambuddhassa_ (M.1.250).

.Illustration
====
vippasīdati

become serene
====

[quote, A.5.342]
____
One who practises [unlimited, all-encompassing] goodwill, their countenance 
becomes serene

_mettāya bhikkhave cetovimuttiyā āsevitāya bhāvitāya... mukhavaṇṇo 
vippasīdati._
____

=== Illustrations: vippasādeti

.Illustration
====
vippasādehi

make serene
====

[quote, Sn.v.506]
____
Make offerings, Māgha, and while offering make your mind serene in every 
respect

_yajassu yajamāno sabbattha ca vippasādehi cittaṃ._
____

=== Illustrations: vippasannaṃ

.Illustration
====
vippasanno

limpid
====

[quote, D.1.76]
____
Just as if there were a gem, a beryl, exquisite, of genuine quality, a well-cut 
octahedron, translucent, limpid, unblemished, excellent in every respect, 
strung on a blue, yellow, white, or orange cord

_Seyyathā pi mahārāja maṇi veḷuriyo subho jātimā aṭṭhaṃso 
suparikammakato accho vippasanno anāvilo sabbākārasampanno tatra'ssa 
suttaṃ āvutaṃ nīlaṃ vā pītaṃ vā lohitaṃ vā odātaṃ vā 
paṇḍusuttaṃ vā._
____

.Illustration
====
vippasanno

limpid
====

[quote, D.1.84]
____
Just as in a mountain valley there were a lake of water, crystal clear, limpid, 
unturbid, and a man standing on the bank with eyes to see should perceive the 
oysters and shells, the gravel and pebbles, and shoals of fish as they move 
about or lie within it.

_Seyyathā pi mahārāja pabbatasaṅkhepe udakarahado accho vippasanno 
anāvilo. Tattha cakkhumā puriso tīre ṭhito passeyya sippisambūkampi 
sakkharakaṭhalampi macchagumbampi carantampi tiṭṭhantamp._
____

.Illustration
====
vippasannā

limpid
====

[quote, Ud.84]
____
As Venerable Ānanda approached, that shallow water, stirred up by the wheels 
and flowing muddied, flowed crystal clear, limpid, and pure.

_Atha kho sā nadī cakkacchinnā parittā luḷitā āvilā sandamānā 
āyasmante ānande upasaṅkamante acchā vippasannā anāvilā sandati._
____

.Illustration
====
vippasanna

limpid
====

[quote, S.5.125]
____
Bowl of water that is crystal clear, limpid, unturbid, set out in the light.

_udapatto accho vippasanno anāvilo āloke nikkhitto._
____

.Illustration
====
vippasanna

serene
====

[quote, M.2.196]
____
&#8203;[One whose mind is] as stainless as the moon, purified, serene, and free of 
impurity

_candaṃ va vimalaṃ suddhaṃ vippasannamanāvilaṃ._
____

.Illustration
====
vippasannāni

serene
====

• Your faculties are serene, your countenance is pure and bright. Under whom 
have you gone forth friend? +
_*☸* vippasannāni kho te āvuso indriyāni parisuddho chavivaṇṇo 
pariyodāto. Kaṃsi tvaṃ āvuso uddissa pabbajito_ (M.1.171).

.Illustration
====
vippasannattā

serene
====

[quote, D.2.205]
____
The Blessed One's looks peaceful, his countenance is radiant, his faculties are 
serene.

_Upasantapadisso bhante bhagavā bhātiriva bhagavato mukhavaṇṇo 
vippasannattā indriyānaṃ._
____

.Illustration
====
vippasannaṃ serene

____
The assembly of bhikkhus remained completely silent like a serene lake

_rahadamiva vippasannaṃ_
____

[quote

D.1.50]
====

____
The king wished that Prince Udāyibhaddo were possessed of such peacefulness.

_iminā me upasamena udāyibhaddo kumāro samannāgato hotu yenetarahi 
upasamena bhikkhusaṅgho samannāgato ti._
____

.Illustration
====
vippasanna

serene
====

[quote, S.5.144]
____
Bhikkhus, those bhikkhus abide contemplating the nature of the body, vigorously 
applied [to the practice], fully conscious, mentally concentrated, serene, 
inwardly collected, inwardly undistracted, in order to know the body according 
to reality.

_kāye kāyānupassino viharatha ātāpino sampajānā ekodibhūtā 
vippasannacittā samāhitā ekaggacittā kāyassa yathābhūtaṃ ñāṇāya._
____

.Illustration
====
vippasanno

serene
====

[quote, Th.v.1008]
____
Inwardly at peace, free of vexation, with a serene and undefiled [mind]

_Upasanto anāyāso vippasanno anāvilo._
____

.Illustration
====
vippasannena

serene
====

[quote, It.19]
____
Rid of the stain of stinginess, with a serene mind, he would give at the right 
time to the Noble Ones where giving is of great fruit.

_Vineyyuṃ maccheramalaṃ vippasannena cetasā +
Dajjuṃ kālena ariyesu yattha dinnaṃ mahapphalaṃ._
____

Comment:

[quote, Sn.v.506]
____
'Make offerings, Māgha, and while offering make your mind serene in every 
respect. For one making offerings, the act of charity is the basis [for 
spiritual development]. Based on this one abandons one's spiritual flaws.

_Yajassu yajamāno sabbattha ca vippasādehi cittaṃ +
Ārammaṇaṃ yajamānassa yañño etthappatiṭṭhāya jahāti dosaṃ._
____

.Illustration
====
vippasannena

serene
====

[quote, Dh.v.79]
____
One who drinks the teaching sleeps well, with a serene mind.

_Dhammapīti sukhaṃ seti vippasannena cetasā._
____

=== Illustrations: sampasīdati

.Illustration
====
na sampasīdati

to be unsettled
====

____
One is unsure

_kaṅkhati_
____

____
one is doubtful about

_vicikicchati_
____

____
one is undecided

_nādhimuccati_
____

____
one is unsettled

_na sampasīdati_
____

[quote, D.3.217]
____
about the [nature of reality in the] periods of the past, the future, and the 
present

_atītaṃ vā addhānaṃ ārabbha kaṅkhati vicikicchati nādhimuccati na 
sampasīdati anāgataṃ vā addhānaṃ ārabbha kaṅkhati vicikicchati 
nādhimuccati na sampasīdati etarahi vā paccuppannaṃ addhānaṃ ārabbha 
kaṅkhati vicikicchati nādhimuccati na sampasīdati._
____

.Illustration
====
sampasīdati

to have faith [in the perfection of the Perfect One's transcendent insight]
====

[quote, A.3.248]
____
Suppose a bhikkhu is unsure, doubtful, undecided about, and has no faith in the 
&#8203;[perfection of the] Teacher's [transcendent insight], his mind is not inclined 
to vigorous endeavour, application, perseverance, and inward striving

_Idha bhikkhave bhikkhu satthari kaṅkhati vicikicchati nādhimuccati na 
sampasīdati. Yo so bhikkhave bhikkhu satthari kaṅkhati vicikicchati 
nādhimuccati na sampasīdati tassa cittaṃ na namati ātappāya anuyogāya 
sātaccāya padhānāya._
____

.Illustration
====
sampasīdati

to have faith [in the perfection of the Perfect One's transcendent insight]
====

• In this regard a bhikkhu is not unsure or doubtful about the [perfection of 
the] Teacher's [transcendent insight], he is decided about him, has faith in 
him. +
_Idha bhikkhave bhikkhu satthari na kaṅkhati na vicikicchati adhimuccati 
sampasīdati_ (A.5.19).

=== Illustrations: sampasāda

.Illustration
====
sampasāde

serenity
====

____
Practising and frequently abiding in this way, his mind becomes serene through 
that practice of spiritual development.

_Tassa evaṃ paṭipannassa tabbahulavihārino āyatane cittaṃ pasīdati._
____

[quote, M.2.262]
____
When there is serenity, he either attains the Imperturbable now, or else he is 
intent upon discernment.

_Sampasāde sati etarahi vā āneñjaṃ samāpajjati paññāya vā 
adhimuccati._
____

.Illustration
====
sampasādaṃ

faith
====

____
This was how Venerable Sāriputta proclaimed his faith face to face with the 
Blessed One.

_Itihidaṃ āyasmā sāriputto bhagavato sammukhā sampasādaṃ pavedesi._
____

[quote, D.3.116]
____
And so the name for this exposition is The Inspiring of Faith

_Tasmā imassa veyyākaraṇassa sampasādaniyantveva adhivacananti._
____

.Illustration
====
sampasādaṃ

faith
====

____
Those devas who, having lived the religious life under the Blessed One, had 
recently appeared in the Tāvatiṃsā Heaven, outshone the other devas in 
brightness and glory. And for that reason the Tāvatiṃsā devas were pleased, 
happy, filled with rapture and joy

_attamanā honti pamuditā pītisomanassajātā_
____

____
They said 'The deva hosts are growing; the āsura hosts are declining.'

_Dibbā vata bho kāyā paripūranti hāyanti asurā kāyā_
____

[quote, D.2.208]
____
Then Sakka, Lord of the Devas, realising the faith of the Tāvatiṃsā devas, 
uttered these verses of rejoicing

_devānaṃ tāvatiṃsānaṃ sampasādaṃ viditvā imāhi gāthāhi anumodi._
____

=== Illustrations: sampasādana

.Illustration
====
sampasādanaṃ

serenity
====

[quote, S.5.307]
____
With the subsiding of thinking and pondering, and [the development of] internal 
serenity and concentration, he enters and abides in second jhāna which is 
without thinking and pondering, and is filled with rapture and physical 
pleasure born of inward collectedness.

_Vitakkavicārānaṃ vūpasamā ajjhattaṃ sampasādanaṃ cetaso 
ekodibhāvaṃ avitakkaṃ avicāraṃ samādhijaṃ pītisukhaṃ 
dutiyajjhānaṃ upasampajja viharati._
____

=== Illustrations: pasīdati

.Illustration
====
pasīdanti

believe in
====

____
The religious philosophers outside this [training system] believe in dogmatic 
views.

_Ito bahiddhā pāsaṇḍā diṭṭhīsu pasīdanti te_
____

[quote, S.1.133]
____
I do not approve of their teachings; they are ignorant of the Buddha's teaching.

_na tesaṃ dhammaṃ rocemi na te dhammassa kovidā._
____

.Illustration
====
pasīdati

to gain faith in
====

____
As the teacher explains the teaching, through transcendent insight into a 
certain one of those teachings the bhikkhu comes to a conclusion about the 
teachings

_so tasmiṃ dhamme abhiññāya idhekaccaṃ dhammaṃ dhammesu niṭṭhaṃ 
gacchati_
____

____
He gains faith in the Teacher thus

_satthari pasīdati_
____

[quote, M.1.319]
____
The Blessed One is perfectly enlightened. The teaching is well explained by the 
Blessed One. The community of disciples is applied to an excellent practice

_sammāsambuddho bhagavā svākkhāto bhagavatā dhammo supaṭipanno saṅgho 
ti._
____

.Illustration
====
pasīdanti

to gain faith
====

[quote, It.11]
____
When the community of bhikkhus is divided, those without faith do not gain 
faith, and some with faith start wavering.

_Saṅghe kho pana bhikkhave bhinne... Tattha appasannā ceva nappasīdanti. 
Pasannānañca ekaccānaṃ aññathattaṃ hotī ti._
____

.Illustration
====
pasīdati

to gain faith [in the perfection of the Perfect One's transcendent insight]
====

[quote, A.2.37]
____
He explained the noble practice which is of benefit to devas and men, hearing 
and understanding which the manyfolk gain faith [in the perfection of the 
Perfect One's transcendent insight].

_Hitaṃ devamanussānaṃ ñāyaṃ dhammaṃ pakāsayī_ +
_Yaṃ ve disvā ca sutvā ca pasīdati bahujjano._
____

.Illustration
====
pasīdi

to be filled with faith [in him]
====

When I first saw the Blessed One a long way off, at the mere sight of him my 
mind was filled with faith [in him] (_cittaṃ pasīdi_). This is the first 
astounding and extraordinary quality found in me. Then with a mind filled with 
faith (_pasannacitto_) I paid respect to the Blessed One... When he knew my 
mind was ready, teachable, free of the five hindrances, uplifted, and serene 
(_pasannacittaṃ_), then he preached the religious discourse unique to the 
Buddhas (A.4.209-210).

.Illustration
====
pasīdanti

become serene
====

[quote, S.1.76]
____
Such a sacrifice is truly vast and the devas, too, become serene.

_Yañño ca vipulo hoti pasīdanti ca devatā ti._
____

.Illustration
====
pasīdati

to become serene
====

[quote, Th.v.706]
____
Those we slaughtered in the past, either for sacrifice or for robbery, were 
paralysed with fear. They trembled and wailed. But with you, you are fearless. 
Your countenance is even more serene. Why do you not weep when in such danger?

_Tassa te natthī bhītattaṃ bhiyyo vaṇṇo pasīdati +
Kasmā na paridevesi evarūpe mahabbhaye._
____

.Illustration
====
pasīdatī

to be serene
====

____
"Those who dwell deep in the forest, peaceful, leading the religious life, 
eating but a single meal a day: why is their countenance so serene?"

_kena vaṇṇo pasīdatī ti_
____

• "They do not grieve over the past, nor do they long for the future. They 
maintain themselves with what is present. Hence their countenance is so 
serene."* +
☸* _Atītaṃ nānusocanti nappajappanti'nāgataṃ +
Paccuppannena yāpenti tena vaṇṇo pasīdati_ (S.1.5).

.Illustration
====
pasīdati

to become serene
====

[quote, Sn.v.434]
____
&#8203;[But] as the flesh wastes away, my mind becomes serene. My mindfulness, 
penetrative discernment, and inward collectedness stand firmly all the more.

_Maṃsesu khīyamānesu bhiyyo cittaṃ pasīdati +
Bhiyyo sati ca paññā ca samādhi mama tiṭṭhati._
____

.Illustration
====
pasīdati

to become serene
====

[quote, M.1.435]
____
When the teaching is being explained to someone to put an end to personal 
identity, if his mind does not become energised, serene, settled, and intent 
upon it then he can be regarded as like a feeble man.

_Evameva kho ānanda yassa kassaci sakkāya nirodhāya dhamme desiyamāne 
cittaṃ na pakkhandati nappasīdati na santiṭṭhati na vimuccati (read as 
adhimuccati. See IGPT sv Adhimuccati). Seyyathā pi so dubbalako puriso evamete 
daṭṭhabbā._
____

.Illustration
====
pasīdati

to become serene
====

[quote, A.3.245]
____
In this regard, when a bhikkhu is contemplating sensuous pleasure, his mind is 
not energised, nor does it becomes serene, settled, intent upon it. But when 
contemplating the practice of unsensuousness his mind becomes energised, 
serene, settled, and intent upon it.

_Idha bhikkhave bhikkhuno kāmaṃ manasikaroto kāmesu cittaṃ na pakkhandati 
nappasīdati na santiṭṭhati na vimuccati (read as adhimuccati. See IGPT sv 
Adhimuccati). Nekkhammaṃ kho panassa manasikaroto nekkhamme cittaṃ 
pakkhandati pasīdati santiṭṭhati vimuccati (read as adhimuccati. See IGPT 
sv Adhimuccati)._
____

.Illustration
====
pasīdati

to become serene
====

Further, Ānanda, the bhikkhu, ignoring the perception of the state of 
awareness of nonexistence and of the state of awareness neither having nor 
lacking perception, he focuses undistractedly on the inward collectedness that 
is focused upon the unabiding [phenomena].

[quote, M.3.108]
____
His mind becomes energised, serene, settled, and intent upon inward 
collectedness that is focused upon the unabiding [phenomena].

_Tassa animitte cetosamādhimhi cittaṃ pakkhandati pasīdati santiṭṭhati 
adhimuccati._
____

.Illustration
====
pasīdati

to become serene
====

[quote, A.4.61]
____
One gives thinking, 'When this gift is given, my mind will become serene. 
Satisfaction and joy will arise in me

_imaṃ me dānaṃ dadato cittaṃ pasīdati attamanatā somanassaṃ 
upajāyatī ti._
____

.Illustration
====
pasīdati

to become serene
====

____
As he reflects on the [perfection of the] Perfect One's [transcendent insight] 
his mind becomes serene;

_Tassa tathāgataṃ anussarato cittaṃ pasīdati._
____

____
gladness arises

_pāmujjaṃ uppajjati._
____

[quote, A.1.207]
____
the spiritual defilements are abandoned

_ye cittassa upakkilesā te pahīyanti._
____

.Illustration
====
pasīdeyyā

to become serene
====

[quote, D.1.47]
____
Can we not today honour some ascetic or Brahmanist through whom our mind would 
become serene?

_kannu khvajja samaṇaṃ vā brāhmaṇaṃ vā payirupāseyyāma yanno 
payirupāsato cittaṃ pasīdeyyā ti._
____

=== Illustrations: pasādeti

.Illustration
====
pasādeti

to become serene
====

• In giving his mind becomes serene.* +
☸* _dadaṃ cittaṃ pasādeti_

[quote, A.4.244]
____
After giving he is pleased.

_datvā attamano hoti._
____

.Illustration
====
pasādenti

to become serene
====

• In thinking, 'This is the stupa of the Blessed One, the Arahant, the 
Perfectly Enlightened One,' Ānanda, the minds of the manyfolk become serene** +
☸** _Ayaṃ tassa bhagavato arahato sammāsambuddhassa thūpo ti ānanda 
bahū janā cittaṃ pasādenti_

[quote, D.2.143]
____
and having serene minds, with the demise of the body at death, they are reborn 
in the realm of happiness, in the heavenly worlds.

_te tatthacittaṃ pasādetvā kāyassa bhedā parammaraṇā sugatiṃ 
saggaṃ lokaṃ papajjanti._
____

.Illustration
====
pasādetvā

being filled with faith
====

[quote, Th.v.912]
____
Then I saw the Perfectly Enlightened One, the Teacher who is free of fear from 
any quarter. My mind being filled with faith in him, I went forth into the 
ascetic life.

_Athaddasāsiṃ sambuddhaṃ satthāraṃ akutobhayaṃ +
Tasmiṃ cittaṃ pasādetvā pabbajiṃ anagāriyaṃ._
____

=== Illustrations: pasāda

.Illustration
====
pasādaṃ

serenity
====

____
As a man afflicted by hunger and weakness may find a honey-cake, and wherever 
he tastes it, he enjoys a sweet delicious flavour.

_yato yato sāyetha labhateva sādhurasaṃ asecanakaṃ_
____

[quote, A.3.237]
____
Even so, whenever one hears Master Gotama's teaching... one wins satisfaction, 
and one attains mental serenity.

_yato yato tassa bhoto gotamassa dhammaṃ suṇāti... tato tato labhateva 
attamanataṃ labhati cetaso pasādaṃ._
____

.Illustration
====
pasādaye

serene
====

[quote, A.3.337]
____
Where one is happy even before the offering; where in giving one's mind is 
serene; where, having given, one is pleased: this is an accomplished act of 
generosity.

_Pubbeva dānā sumano dadaṃ cittaṃ pasādaye +
Datvā attamano hoti esā yaññassa sampadā._
____

.Illustration
====
pasādāya

inspire faith
====

[quote, A.1.98]
____
For two good reasons the Perfect One establishes training rules for his 
disciples. To inspire faith in those without faith; and to increase the faith 
of those with faith.

_Dveme bhikkhave atthavase paṭicca tathāgatena sāvakānaṃ sikkhāpadaṃ 
paññattaṃ. Katame dve? appasannānaṃ pasādāya pasannānaṃ 
bhiyyobhāvāya._
____

.Illustration
====
pasādaṃ

faith
====

Bhikkhus, possessed of two qualities a foolish, incompetent, ordinary person 
wanders about hurting and injuring himself; he is blameworthy, criticised by 
the wise, and begets much demerit. Which two? Through lack of investigation and 
penetration (_ananuvicca apariyogāhetvā_) he exhibits

• *•* faith in a matter that is not worthy of faith; +
☸ _appasādaniye ṭhāne pasādaṃ upadaṃseti_

[quote, A.1.90]
____
lack of faith in a matter that is worthy of faith.

_pasādaniye ṭhāne appasādaṃ upadaṃseti._
____

.Illustration
====
pasādaṃ

faith
====

____
The Blessed One has inspired in me

_ajanesi vata me bhante bhagavā samaṇesu_
____

____
an affection for ascetics

_samaṇapemaṃ_
____

____
faith in ascetics

_samaṇesu samaṇappasādaṃ_
____

[quote, M.1.368]
____
a respect for ascetics

_samaṇesu samaṇagāravaṃ._
____

.Illustration
====
puggalappasāde

having faith which is based on a single individual
====

____
Five dangers of having faith which is based on a single individual.

_Pañcime bhikkhave ādīnavā puggalappasāde. Katame pañca:_
____

[quote, A.3.270]
____
When a person's complete faith is based on a single individual (_puggale 
puggalo abhippasanno hoti_) and that person falls into an error such that the 
community of bhikkhus suspends him, then he will think: 'The community of 
bhikkhus has suspended he who is beloved and dear to me.' And he will be no 
more full of faith in the bhikkhus (_bhikkhūsu appasādabahulo hoti_), and 
from being without faith he will not follow other bhikkhus, and from not 
following other bhikkhus he will not hear the true teaching, and from not 
hearing the true teaching he will fall away from the true teaching.

_Yasmiṃ bhikkhave puggale puggalo abhippasanno hoti so tathārūpaṃ 
āpattiṃ āpanno hoti yathārūpāya āpattiyā saṅgho ukkhipati. Tassa 
evaṃ hoti: yo kho myāyaṃ puggalo piyo manāpo so saṅghena ukkhitto ti 
bhikkhūsu appasādabahulo hoti. Bhikkhūsu appasādabahulo samāno aññe 
bhikkhū na bhajati aññe bhikkhū na bhajanto saddhammaṃ na suṇāti 
saddhammaṃ asuṇanto saddhammā parihāyati. Ayaṃ bhikkhave paṭhamo 
ādīnavo puggalappasāde._
____

.Illustration
====
pasādā

faith
====

• There are three foremost kinds of faith** +
☸** _aggappasādā_

[quote, It.88]
____
Those who have faith in Buddha have faith in best. Those who have faith in best 
will have the best result

_ye bhikkhave buddhe pasannā agge te pasannā. Agge kho pana pasannānaṃ 
aggo vipāko hoti._
____

.Illustration
====
pasādo

faith
====

You, householder, do not have that lack of faith in the Buddha (_buddhe 
appasādena_) which the ignorant Everyman possesses because of which the 
latter, with the demise of the body at death, is reborn in hell (S.5.381).

=== Illustrations: pasādaniya

.Illustration
====
pasādaniye

worthy of faith
====

Bhikkhus, possessed of two qualities a foolish, incompetent, ordinary person 
wanders about hurting and injuring himself; he is blameworthy, criticised by 
the wise, and begets much demerit. Which two? Through lack of investigation and 
penetration (_ananuvicca apariyogāhetvā_) he exhibits

• *•* faith in a matter that is not worthy of faith +
☸ _appasādaniye ṭhāne pasādaṃ upadaṃseti_

[quote, A.1.90]
____
lack of faith in a matter that is worthy of faith

_pasādaniye ṭhāne appasādaṃ upadaṃseti._
____

.Illustration
====
pasādaniye

faith inspiring
====

____
That bhikkhu should then direct his mind towards some faith inspiring 
meditation object.

_kismiñcideva pasādaniye nimitte cittaṃ paṇidahitabbaṃ_
____

[quote, S.5.156]
____
When he directs his mind to some faith inspiring meditation object, gladness 
arises.

_tassa kismicideva pasādanīye nimitte cittaṃ paṇidahato pāmujjaṃ 
jāyati._
____

.Illustration
====
pasādaniyā

faith inspiring
====

____
The Blessed One declared ten faith inspiring qualities (_dasa pasādaniyā 
dhammā_) that if they are found in someone, we honour, revere, respect, and 
venerate him:

_dasa pasādaniyā dhammā akkhātā_
____

(Namely: virtue, learning, contentment, four jhānas, psychic powers, divine 
ear, knowledge of others' minds, recollects many past lives, sees beings' death 
and rebirth, destruction of perceptually obscuring states) (M.3.11).

.Illustration
====
pasādaniyaṃ faith inspiring

[quote

Th.v.591]
====

____
Undertaking [what is virtuous], refraining [what is unvirtuous], having a 
deportment that is faith inspiring, and being applied to the higher mental 
states, this is fitting for an ascetic.

_Cārittaṃ atha vārittaṃ iriyāpathiyaṃ pasādaniyaṃ +
Adhicitte ca āyogo etaṃ samaṇassa patirūpaṃ._
____

.Illustration
====
pasādaniyaṃ faith inspiring

____
You will see the Blessed One

_dakkhissasi tvaṃ soṇa taṃ bhagavantaṃ_
____

____
who is beautifully behaved

faith inspiring,
====

_pāsādikaṃ pasādaniyaṃ_
____

[quote, Ud.58]
____
who has peaceful [mental] faculties and a peaceful mind,

_santindriyaṃ santamānasaṃ._
____

.Illustration
====
pasādaniyaṃ faith inspiring

[quote

A.2.38]
====

____
The brahman Doṇa followed the Blessed One's footprints and saw him sitting at 
the root of some tree, beautifully behaved, faith inspiring, with peaceful 
&#8203;[mental] faculties and a peaceful mind

_pāsādikaṃ pasādaniyaṃ santindriyaṃ santamānasaṃ._
____

=== Illustrations: pasanno

.Illustration
====
pasannacittaṃ

serene
====

[quote, D.1.110]
____
When the Blessed One knew that Pokkharasāti's mind was ready, teachable, free 
of the five hindrances, uplifted, and serene, then he preached the religious 
discourse unique to the Buddhas:

_Yadā bhagavā aññāsi brāhmaṇaṃ pokkharasātiṃ kallacittaṃ 
muducittaṃ vinīvaraṇacittaṃ udaggacittaṃ pasannacittaṃ atha yā 
buddhānaṃ sāmukkaṃsikā dhammadesanā taṃ pakāsesi._
____

.Illustration
====
pasanna

serene
====

[quote, Sn.v.553]
____
You have serene eyes, a fair face

_pasannanetto sumukho._
____

.Illustration
====
pasannena

pure
====

If one speaks or acts with a defiled mind (_manasā ce paduṭṭhena bhāsati 
vā karoti vā_), suffering thence follows one as surely as the cartwheel 
follows the foot of the ox (Dh.v.1).

If one speaks or acts with a pure mind (_manasā ce pasannena bhāsati vā 
karoti vā_), happiness thence follows one as surely as one's never-departing 
shadow (Dh.v.2).

.Illustration
====
pasannena

pure
====

[quote, S.1.206]
____
If with a pure mind he teaches others, he does not become tethered [to them] by 
his tender concern and sympathy.

_Manasā ce pasannena yadaññamanusāsati +
Na tena hoti saṃyutto sānukampā anuddayāti._
____

.Illustration
====
pasannā

filled with faith
====

[quote, S.1.142]
____
Therefore, filled with faith, free of vacillation, present your offering to one 
who is worthy of gifts.

_Tasmiṃ pasannā avikampamānā +
patiṭṭhapesi dakkhiṇaṃ dakkhiṇeyye._
____

.Illustration
====
pasannacitto

filled with faith
====

He with a mind filled with faith who goes to the Buddha for refuge 
(_pasannacitto buddhaṃ saraṇaṃ gacchati_), the teaching, and the 
community of the Blessed One's disciples -- this is a sacrifice (_yañño_) 
which is greater (D.1.146).

.Illustration
====
pasanna

filled with faith
====

[quote, D.2.141]
____
Any who die whilst on pilgrimage to these shrines with a mind filled with 
faith, with the demise of the body at death, all will be reborn in the realm of 
happiness, in the heavenly worlds.

_Ye hi keci ānanda cetiyacārikaṃ āhiṇḍantā pasannacittā kālaṃ 
karissanti sabbe te kāyassa bhedā parammaraṇā sugatiṃ saggaṃ lokaṃ 
upapajjissanti ti._
____

.Illustration
====
pasannā

have faith
====

[quote, D.2.166]
____
Let stupas far and wide be established so that many people will have faith in 
the Seer.

_Vitthārikā hontu disāsu thūpā +
Bahū janā cakkhumato pasannā ti._
____

.Illustration
====
pasanno

faith
====

Four persons in the world:

____
He who guages by appearance, and whose faith is inspired by appearance

_rūpappamāṇo rūpappasanno_
____

____
He who guages by voice, and whose faith is inspired by voice

_ghosappamāṇo ghosappasanno_
____

____
He who guages by asceticism, and whose faith is inspired by asceticism

_lūkhappamāṇo lūkhappasanno_
____

[quote, A.2.71]
____
He who guages by the teaching, and whose faith is inspired by the teaching

_dhammappamāṇo dhammappasanno._
____

.Illustration
====
pasannaṃ

faith
====

____
In this regard, bhante, some issue concerning the teaching may arise. The 
Blessed One might take one side, and the bhikkhus' and bhikkhunīs' communities 
might take the other side. Whatever side the Blessed One would take, I would 
take that same side.

_Idha bhante kocideva dhammasamuppādo uppajjeyya ekato assa bhagavā ekato 
bhikkhusaṅgho ekato bhikkhunīsaṅgho ca yeneva bhagavā tenevāhaṃ 
assaṃ._
____

[quote, S.5.374]
____
Let the Blessed One remember me as one who has such faith in him.

_Evaṃ pasannaṃ maṃ bhante bhagavā dhāretu._
____

.Illustration
====
appasannā

have no faith in
====

Now, bhante, there are disciples of the Blessed One who live in remote forest 
abodes. And there are high ranking deities settled there who have no faith in 
the teaching of the Blessed One (_ye imasmiṃ bhagavato pāvacane 
appasannā_). To inspire faith in them (_tesaṃ pasādāya_), bhante, may the 
Blessed One learn this Āṭānāṭiyaṃ protection (D.3.195).

.Illustration
====
appasannā

those without faith
====

[quote, It.11]
____
When the community of bhikkhus is divided, those without faith do not gain 
faith, and some with faith start wavering.

_Tattha appasannā ceva nappasīdanti. Pasannānañca ekaccānaṃ 
aññathattaṃ hotī ti._
____

.Illustration
====
pasannā

faith
====

[quote, A.2.34]
____
Those with faith in the Buddha have faith in the best. They with faith in the 
best will have the best result.

_Ye bhikkhave buddhe pasannā agge te pasannā agge kho pana pasannānaṃ aggo 
vipāko hoti._
____

.Illustration
====
pasannānaṃ faith

[quote

A.1.26]
====

____
Foremost amongst my lay disciples whose faith is based on a single individual 
is Jīvaka Komārabhacca.

_Etadaggaṃ bhikkhave mama sāvakānaṃ upāsakānaṃ puggalappasannānaṃ 
yadidaṃ jīvako komārabhacco._
____

Compare:

[quote, A.3.270]
____
Five dangers of having faith which is based on a single individual

_Pañcime bhikkhave ādīnavā puggalappasāde._
____

.Illustration
====
pasanno

faith
====

[quote, A.1.150]
____
By three features a person with faith and confidence in the Perfect One is to 
be known.

_tīhi bhikkhave ṭhānehi saddho pasanno veditabbo._
____

.Illustration
====
pasannā

believe in
====

Devadatta promoted forest-dwelling, almsgathering, rag-robe wearing, tree-root 
dwelling, vegetarianism. He said it would be possible to create a schism with 
these five items because people believe in asceticism (_lukhappasannā hi 
āvuso manussā ti_) (Vin.2.197).

.Illustration
====
pasanno

convinced
====

[quote, D.2.149]
____
A state of unsureness has arisen in me. I am convinced that the ascetic Gotama 
can explain the issue so I might abandon that state of unsureness

_atthi ca me ayaṃ kaṅkhādhammo uppanno. Evaṃ pasanno ahaṃ samaṇe 
gotame pahoti me samaṇo gotamo tathā dhammaṃ desetuṃ yathāhaṃ imaṃ 
kaṅkhādhammaṃ pajaheyyan ti._
____

.Illustration
====
pasanno

convinced
====

Then Venerable Ānanda said this to the Blessed One:

-- 'It is astounding, bhante, it is extraordinary, bhante, I am convinced, 
bhante (_evaṃ pasanno ahaṃ bhante_), that in this assembly of bhikkhus 
there is not one bhikkhu in this assembly of bhikkhus who is unsure or 
uncertain about the [perfection of the] Buddha's [transcendent insight], or 
about the [significance of the] teaching, or about the [praiseworthiness of 
the] community of disciples' [application to the practice], or about the 
&#8203;[significance of the] Path and the practice.'

-- 'Out of faith, Ānanda, you speak (_pasādā kho tvaṃ ānanda vadesi_), 
but the Perfect One, Ānanda, has the actual knowledge that there is not one 
bhikkhu in this assembly of bhikkhus who is unsure or uncertain about the 
&#8203;[perfection of the] Buddha's [transcendent insight], or about the [significance 
of the] teaching, or about the [praiseworthiness of the] community of 
disciples' [application to the practice], or about the [significance of the] 
Path and the practice' (D.2.155).

.Illustration
====
pasanno

convinced
====

[quote, D.2.82]
____
-- I am convinced, Blessed One, that there never has been, there never will be, 
and there does not exist in the present another ascetic or Brahmanist who has 
greater transcendent insight regarding enlightenment than the Blessed One.

_evaṃ pasanno ahaṃ bhante bhagavatī na cāhu na ca bhavissati na cetarahi 
vijjati añño samaṇo vā brāhmaṇo bhagavatā bhiyyo'bhiññataro 
yadidaṃ sambodhiyanti._
____

