== Patilīna

=== Renderings

- _patilīna_: free of self-centredness

- _patilīna_: withdrawn from society

=== Introduction

==== Patilīyati: 'draw back'

_Patilīyati_ means 'to draw back':

____
His mind draws back, bends back, turns away from involvement in sexual 
intercourse

_methunadhammasamāpattiyā cittaṃ patilīyati patikuṭati pativaṭṭati_
____

[quote, A.4.47]
____
A piece of gristle thrown on fire draws back, bends back, turns away

_nahārudaddulaṃ vā aggimhi pakkhīttaṃ patilīyati patikuṭati 
pativaṭṭati._
____

==== Patilīna: withdrawn from society

_Patilīna_, the past participle of _patilīyati_, can mean 'withdrawn from 
society:

[quote, Sn.v.810]
____
For a bhikkhu living withdrawn from society, resorting to a secluded abode, 
they say it is fitting for him to not exhibit his ego in any residence.

_Patilīnacarassa bhikkhuno bhajamānassa vivittamāsanaṃ +
Sāmaggiyamāhu tassa taṃ yo attānaṃ bhavane na dassaye._
____

==== Patilīna: free of self-centredness

_Patilīno_ is defined as _asmimāno pahīṇo hoti_, and accordingly must 
sometimes be called 'free of self-centredness':

____
How is a bhikkhu free of self-centredness?

_Kathañca bhikkhave bhikkhu patilīno hoti?_
____

[quote, A.2.41]
____
... In this regard, self-centredness is abandoned in a bhikkhu._

_Idha bhikkhave bhikkhuno asmimāno pahīṇo hoti._
____

=== Illustrations

.Illustration
====
patilīna

free of self-centredness
====

[quote, A.4.449-451]
____
The Buddha who discovered jhāna, the chief bull, free of self-centredness, the 
Sage.

_Yo jhānambudhā buddho patilīnanisabho munī ti._
____

.Illustration
====
patilīno

free of self-centredness
====

____
That peaceful, mindful bhikkhu, tranquil, undefeated [by Māra's army],

_Sa ve santo sato bhikkhu passaddho aparājito_
____

[quote, A.2.42]
____
Through rightly penetrating self-centredness, enlightened, he is called free of 
self-centredness

_Mānābhisamayā buddho patilīno ti vuccatī ti._
____

