== Paññuttara

=== Renderings

- _paññuttara_: penetrative discernment is the examiner

- _paññuttara_: penetrative discernment as the examiner

=== Introduction

==== Dictionaries

_Uttara_ means:

- DOP: 'chief result or characteristic; what is left; excess.'

- PED: 'having something above or higher, having a superior.'

But neither explanation fits the contexts of _paññuttara_. We will show that 
_uttara_ means 'examiner.'

==== Translators

Bodhi says the commentary 'does not explain in what sense _paññā_ is called 
_uttarā,'_ and renders _paññuttarā sabbe dhammā_ as 'Wisdom is of all 
things their supervisor' (Bodhi, A.4.339).

==== Sikkhānisaṃsa Sutta

The _Sikkhānisaṃsa Sutta_ (A.2.243) shows that the meaning of 
_paññuttaraṃ_ can be derived from _paññāya samavekkhitā honti_:

[quote, A.2.243]
____
In accordance with way I explain the teachings to disciples for the complete 
destruction of suffering, those teachings are examined by them with penetrative 
discernment (_paññāya samavekkhitā honti_). In this way penetrative 
discernment is the examiner (_paññuttaraṃ hoti_).

_Yathā yathā bhikkhave mayā sāvakānaṃ dhammā desitā sabbaso sammā 
dukkhakkhayāya tathā tathāssa te dhammā paññāya samavekkhitā honti. 
Evaṃ kho bhikkhave paññuttaraṃ hoti._
____

This suggests that _uttaraṃ_ can be named after _samavekkhati_, for which PED 
says:

_• Samavekkhati_: to consider, examine.

_• Samavekkhitar_: one who considers.

This supports our term for _paññuttarā._

=== Illustrations

.Illustration
====
paññuttaraṃ

penetrative discernment as the examiner
====

[quote, A.2.243]
____
This religious life is lived for the sake of a benefit from the training, with 
penetrative discernment as the examiner, with liberation [from perceptually 
obscuring states] as its essence, with mindfulness as its master.

_Sikkhānisaṃsamidaṃ bhikkhave brahmacariyaṃ vussati paññuttaraṃ 
vimuttisāraṃ satādhipateyyaṃ._
____

.Illustration
====
paññuttaraṃ

penetrative discernment is the examiner
====

____
And how is penetrative discernment the examiner?

_Kathañca bhikkhave paññuttaraṃ hoti?_
____

____
In this regard, the teachings are explained by me to disciples for the complete 
destruction of suffering

_Idha bhikkhave mayā sāvakānaṃ dhammā desitā sabbaso sammā 
dukkhakkhayāya._
____

____
In accordance with way I explain the teachings to disciples for the complete 
destruction of suffering, those teachings are examined by them with penetrative 
discernment.

_Yathā yathā bhikkhave mayā sāvakānaṃ dhammā desitā sabbaso sammā 
dukkhakkhayāya tathā tathāssa te dhammā paññāya samavekkhitā honti._
____

[quote, A.2.243]
____
In this way penetrative discernment is the examiner

_Evaṃ kho bhikkhave paññuttaraṃ hoti._
____

.Illustration
====
paññuttarā

penetrative discernment is the examiner
====

____
Penetrative discernment is the examiner of all things.

_paññuttarā sabbe dhammā_
____

[quote, A.4.339]
____
Liberation [from perceptually obscuring states] is the essence of all things.

_vimuttisārā sabbe dhammā ti._
____

