== Paṭipadā; Paṭipajjati; Paṭipanna

=== Renderings

- _paṭipadā_: practice

- _paṭipadā_: the practice

- _paṭipajjati_: to conduct oneself

- _paṭipajjati_: to apply oneself

- _paṭipajjati_: to apply oneself [to the eightfold path]

- _paṭipajjati_: to practise

- _paṭipajjati_: to treat

- _paṭipanna_: apply oneself

- _paṭipanna_: one who applies himself [to the eightfold path]

- _paṭipanna_: conduct oneself

- _paṭipanna_: practise

- _paṭipanna_: strive

- _paṭipanna_: travel

- _sammāpaṭipanna_: one who applies himself correctly [to the eightfold path]

- _sammāpaṭipadā_: right practice [of the eightfold path]

- _micchāpaṭipadā_: wrong practice [of the eightfold path]

=== Introduction

==== Micchāpaṭipadā: wrong practice [of the eightfold path]

____
What is wrong practice?

_Katamā ca bhikkhave micchāpaṭipadā_
____

• It is wrong view [of reality]... wrong inward collectedness. This is called 
wrong practice +
_seyyathīdaṃ micchādiṭṭhi... micchāsamādhi ayaṃ vuccati bhikkhave 
micchāpaṭipadā_ (S.5.18).

==== Sammāpaṭipadā: right practice [of the eightfold path]

• What is right practice. It is right perception [of reality]_..._ right 
inward collectedness. This is called right practice +
_Katamā ca bhikkhave sammāpaṭipadā seyyathīdaṃ sammādiṭṭhi... 
sammāsamādhi. Ayaṃ vuccati bhikkhave sammāpaṭipadā ti_ (S.5.18).

==== Sammāpaṭipanna: one who applies himself correctly [to the eightfold path]

If _sammāpaṭipadā_ means right practice [of the eightfold path], then 
_sammāpaṭipanna_ means 'one who applies himself correctly [to the eightfold 
path]':

[quote, S.5.19]
____
Whether it is a layperson or one gone forth [into the ascetic life] who applies 
himself correctly [to the eightfold path], because of doing so he fulfils the 
noble practice that is spiritually wholesome.

_Gihī vā bhikkhave pabbajito vā sammāpaṭipanno 
sammāpaṭipattādhikaraṇahetu ārādhako hoti ñāyaṃ dhammaṃ kusalan 
ti._
____

==== Paṭipanna: one who applies himself [to the eightfold path]

Accordingly, where it lacks an object, _paṭipanna_ means 'one who applies 
himself [to the eightfold path]':

[quote, Dh.v.276]
____
Meditators who apply themselves [to the eightfold path] will be delivered from 
Māra's bond [that binds one to renewed states of individual existence].

_Paṭipannā pamokkhanti jhāyino mārabandhanā._
____

=== Illustrations: paṭipada

.Illustration
====
paṭipadā

practice
====

[quote, A.3.48]
____
A noble disciple wanting long life should apply himself to the practice 
conducive to long life.

_Āyukāmena gahapati ariyasāvakena āyusaṃvattanikā paṭipadā 
paṭipajjitabbā._
____

.Illustration
====
paṭipadā

practice
====

____
Bhikkhus, develop the path and the practice leading to the destruction of 
craving.

_Yo bhikkhave maggo yā paṭipadā taṇhakkhayāya saṃvattati taṃ 
maggaṃ taṃ paṭipadaṃ bhāvetha._
____

[quote, S.5.86]
____
And what is the path and practice leading to the destruction of craving? It is 
the seven factors of enlightenment.

_Katamo ca bhikkhave maggo katamā ca paṭipadā taṇhakkhayāya 
saṃvattati: yadidaṃ satta bojjhaṅgā._
____

.Illustration
====
paṭipadaṃ

practice
====

____
Bhikkhus, whether for a layperson or one gone forth [into the ascetic life], I 
do not praise wrong practice.

_Gihino vāhaṃ bhikkhave pabbajitassa vā micchāpaṭipadaṃ na vaṇṇemi_
____

[quote, S.5.19]
____
Whether it is a layperson or one gone forth [into the ascetic life] who applies 
himself to wrong practice, because of doing so he does not fulfil the noble 
practice that is spiritually wholesome.

_Gihī vā bhikkhave pabbajito vā micchāpaṭipanno 
micchāpaṭipattādhikaraṇahetu nārādhako hoti ñāyaṃ dhammaṃ 
kusalaṃ._
____

.Illustration
====
paṭipadaṃ

practice
====

[quote, M.1.69-71]
____
The Perfect One discerns according to reality the practices leading to all 
destinations.

_sabbatthagāminiṃ paṭipadaṃ yathābhūtaṃ pajānāti._
____

=== Illustrations: paṭipajjati

.Illustration
====
paṭipajjati

conduct oneself
====

[quote, S.2.152]
____
The learned noble disciple conducts himself rightly in three ways: by body, 
speech, and mind.

_sutavā ariyasāvako tīhi ṭhānehi sammā paṭipajjati kāyena vācāya 
manasā._
____

.Illustration
====
paṭipajjati

applies himself
====

____
Bhikkhus, in seeing a visible object via the visual sense,

_cakkhunā rūpaṃ disvā_
____

____
he does not grasp its aspects and features

_na nimittaggāhī nānuvyañjanaggāhī_
____

____
since by abiding with the faculty of sight unrestrained [from attraction and 
repulsion, through mindfulness]

_yatvādhikaraṇametaṃ cakkhundriyaṃ asaṃvutaṃ viharantaṃ_
____

____
greed, dejection, and unvirtuous, spiritually unwholesome factors would pursue 
him.

_abhijjhādomanassā pāpakā akusalā dhammā anvāssaveyyuṃ_
____

____
He applies himself to the restraint of the faculty [from attraction and 
repulsion, through mindfulness]

_tassa saṃvarāya paṭipajjati_
____

____
He supervises the faculty of sight [with mindfulness]

_rakkhati cakkhundriyaṃ_
____

[quote, A.3.163]
____
He attains restraint of the faculty of sight [through mindfulness]

_cakkhundriye saṃvaraṃ āpajjati._
____

.Illustration
====
paṭipajjatha

apply yourself
====

____
Apply yourself to the destruction of craving

_taṇhakkhayāya paṭipajjatha_
____

[quote, S.3.190]
____
For the destruction of craving, Rādha, is the Untroubled

_taṇhakkhayo hi rādha nibbānan ti._
____

.Illustration
====
paṭipajjitvā

apply oneself [to the eightfold path]
====

[quote, Th.v.158]
____
Having applied myself properly [to the eightfold path] I removed my mind from 
states of individual existence

_Yoniso paṭipajjitvā bhave cittaṃ udabbahinti._
____

.Illustration
====
paṭipajjatha

apply oneself [to the eightfold path]
====

[quote, Th.v.1004]
____
Apply yourself [to the eightfold path]. Do not be condemned [to the plane of 
sub-human existence]. May the [rare] opportunity [to live the religious life] 
not pass you by.

_Paṭipajjatha mā vinassatha khaṇo vo mā upaccagā._
____

.Illustration
====
paṭipajjamāno

practise
====

[quote, Sn.v.317]
____
Practising in accordance with the teaching

_Dhammānudhammaṃ paṭipajjamāno._
____

.Illustration
====
paṭipajjāmā

treat
====

____
-- Bhante Ānanda, how should we treat the Perfect One's body?

_kathaṃ mayaṃ bhante ānanda tathāgatassa sarīre paṭipajjāmā ti?_
____

[quote, D.2.161]
____
-- You should treat it in the same way one treats a Wheel-turning monarch's 
body.

_Yathā kho vāsiṭṭhā rañño cakkavattissa sarīre paṭipajjatti evaṃ 
tathāgatassa sarīre paṭipajjitabbanti._
____

=== Illustrations: paṭipanna

.Illustration
====
paṭipanno

applies himself
====

____
Possessed of five factors a bhikkhu applies himself to his own welfare and the 
welfare of others. What five?

_Pañcahi bhikkhave dhammehi samannāgato bhikkhu attahitāya ca paṭipanno 
hoti parahitāya ca. Katamehi pañcahi_
____

He is perfect in virtue, inward collectedness, penetrative discernment, 
liberation [from perceptually obscuring states], and the knowledge and vision 
that follows liberation [from perceptually obscuring states] himself, and he 
encourages others to also be perfect in these things (A.3.14).

.Illustration
====
paṭipanno

apply oneself
====

[quote, M.1.453-4]
____
Some person applies himself to the abandonment and relinquishment of attachment.

_Idha panudāyi ekacco puggalo upadhipahānāya paṭipanno hoti 
upadhipaṭinissaggāya._
____

.Illustration
====
paṭipanno

apply oneself
====

____
I, too, proclaim a man, if he possesses four qualities, as one of great wisdom, 
as a Great Man. What four?

_Catūhi kho ahaṃ brāhmaṇa dhammehi samannāgataṃ mahāpaññaṃ 
mahāpurisaṃ paññapemi. Katamehi catūhi?_
____

____
He applies himself to the welfare and happiness of the manyfolk.

_Idha brāhmaṇa bahujanahitāya paṭipanno hoti bahujanasukhāya_
____

[quote, A.2.36]
____
By him are many folk established in the noble practice, namely in the aggregate 
of practices that are virtuous and spiritually wholesome.

_bahu'ssa janatā ariye ñāye patiṭṭhāpitā yadidaṃ kalyāṇadhammatā 
kusaladhammatā._
____

.Illustration
====
paṭipanno

apply oneself
====

The noble disciple is

____
indifferent to the visual sense of the past,

_atītasmiṃ cakkhusmiṃ anapekkho hoti_
____

____
he does not long for the visual sense of the future,

_anāgataṃ cakkhuṃ nābhinandati_
____

[quote, S.4.4]
____
he applies himself to disillusionment with the visual sense of the present, to 
non-attachment to it, and to the ending of it

_paccappannassa cakkhussa nibbidāya virāgāya nirodhāya paṭipanno hoti._
____

.Illustration
====
paṭipanno

apply oneself
====

____
I discern the Untroubled and the path and practice leading to the Untroubled.

_Nibbānañcāhaṃ sāriputta pajānāmi nibbānagāmiñca maggaṃ 
nibbānagāminiñca paṭipadaṃ_
____

[quote, M.1.73-4]
____
And I know that one who applies himself accordingly will, through the 
destruction of perceptually obscuring states, in his lifetime enter upon and 
abide in the liberation [from attachment through inward calm] and the 
liberation [from uninsightfulness] through penetrative discernment, realising 
it for himself through transcendent insight.

_Yathāpaṭipanno ca āsavānaṃ khayā anāsavaṃ cetovimuttiṃ 
paññāvimuttiṃ diṭṭheva dhamme sayaṃ abhiññā sacchikatvā 
upasampajja viharati tañca pajānāmi._
____

.Illustration
====
paṭipanno

apply oneself
====

____
The community of the Blessed One's disciples is applied to an excellent 
practice,

_supaṭipanno bhagavato sāvakasaṅgho_
____

____
The community of the Blessed One's disciples is applied to the correct practice,

_ujupaṭipanno bhagavato sāvakasaṅgho_
____

____
The community of the Blessed One's disciples is applied to the noble practice.

__ñāyapaṭipanno bhagavato sāvakasaṅgho_
____

[quote, S.5.343]
____
The community of the Blessed One's disciples is applied to a proper practice.

_sāmīcipaṭipanno bhagavato sāvakasaṅgho._
____

.Illustration
====
paṭipanno

conduct himself; paṭipanno, practise
====

[quote, D.2.279]
____
How does he conduct himself, sir, the bhikkhu who practises within the 
constraints of the rules of discipline?'

_kathaṃ paṭipanno pana mārisa bhikkhu pātimokkhasaṃvarāya paṭipanno 
hotī ti._
____

.Illustration
====
paṭipannā

conducting yourselves
====

[quote, M.1.480]
____
'Bhikkhus, you have lost your way. Bhikkhus, you are conducting yourselves 
wrongly. Bhikkhus, how far you have strayed, you worthless men, from this 
teaching and training system.

_vippaṭipannā'ttha bhikkhave. Micchāpaṭipannā'ttha bhikkhave. 
Kīvadūrevime bhikkhave moghapurisā apakkantā imasmā dhammavinayā._
____

.Illustration
====
paṭipanno

apply oneself; paṭipanno, practising
====

If a bhikkhu is applying himself to

- disillusionment with old age and death

- and to non-attachment to it, and to the ending of it,

[quote, S.2.18]
____
he is fit to be called a bhikkhu who is practising in accordance with the 
teaching.

_Jarāmaraṇassa ce bhikkhu nibbidāya virāgāya nirodhāya paṭipanno hoti 
dhammānudhammapaṭipanno bhikkhū ti alaṃ vacanāya._
____

.Illustration
====
paṭipannā

striving
====

____
They are free of attachment or striving to eliminate it

_vītarāgā vā honti rāgavinayāya vā paṭipannā._
____

____
They are free of hatred or striving to eliminate it

_vītadosā vā honti dosavinayāya vā paṭipannā._
____

[quote, A.3.336]
____
They are free of undiscernment of reality or striving to eliminate it

_vītamohā vā honti mohavinayāya vā paṭipannā._
____

.Illustration
====
paṭipanno

travel
====

[quote, A.4.345]
____
When I travel the high road and see no one either in front or behind me

_Yasmāhaṃ nāgita samaye addhānamaggapaṭipanno na kañci passāmi purato 
vā pacchato vā._
____

