== Paṭicca

=== Renderings

- _paṭicca_: dependent

- _paṭicca_: because of

- _paṭicca_: on

- _paṭicca_: by

- _paṭicca_: in

- _paṭicca_: for

- _paṭicca_: from

- _paṭicca_: in reference to

- _appaṭicca_: self-sufficient

=== Illustrations

.Illustration
====
paṭicca

dependent, appaṭicca, self-sufficient
====

____
There has arisen in me a pleasant sense impression.

_uppannā kho myāyaṃ sukhā vedanā_
____

____
Now that is dependent, not self-sufficient.

_paṭicca no appaṭicca_
____

____
Dependent on what?

_kiṃ paṭicca_
____

[quote, S.4.211]
____
Dependent on this very body.

_imameva kāyaṃ paṭicca._
____

.Illustration
====
paṭicca

dependent on
====

[quote, S.4.15]
____
Dependent on a sensation to be experienced as pleasant, a pleasant sense 
impression arises

_Sukhavedaniyaṃ bhikkhave phassaṃ paṭicca uppajjati sukhā vedanā._
____

.Illustration
====
paṭicca

dependently
====

[quote, It.61]
____
From whatever is brought about, originated, dependently arisen, the ending [of 
originated phenomena] is the deliverance.

_Yaṃ kho pana kiñci bhūtaṃ saṅkhataṃ paṭiccasamuppannaṃ nirodho 
tassa nissaraṇaṃ._
____

.Illustration
====
paṭicca

dependent on
====

[quote, M.3.281]
____
Dependent on the visual sense and visible objects, advertence to the visual 
field arises.

_Cakkhuñca paṭicca rūpe ca uppajjati cakkhuviññāṇaṃ._
____

.Illustration
====
paṭicca

because of
====

• Because of craving, search. _ +
taṇhaṃ paṭicca pariyesanā_

• Because of search, acquisition +
_pariyesanaṃ paṭicca lābho_ (A.4.401).

.Illustration
====
paṭicca

because of
====

____
Suffering arises because of attachment.

_upadhiṃ paṭicca dukkhamidaṃ sambhoti_
____

.Illustration
====
paṭicca

because of
====

____
The phenomenon of light is discernable because of darkness.

_Yāyaṃ bhikkhu ābhādhātu ayaṃ dhātu andhakāraṃ paṭicca 
paññāyati_
____

____
The phenomenon of loveliness is discernable because of unloveliness.

_yāyaṃ bhikkhu subhadhātu ayaṃ dhātu asubhaṃ paṭicca paññāyati_
____

[quote, S.2.150]
____
The phenomenon of the ending of perception and sense impression is discernable 
because of the ending [of originated phenomena].

_yāyaṃ bhikkhu saññāvedayitanirodhadhātu ayaṃ dhātu nirodhaṃ 
paṭicca paññāyatī ti._
____

.Illustration
====
paṭicca

on
====

[quote, M.3.105]
____
Further, Ānanda, the bhikkhu, not focusing upon the perceptions of man and 
forest, focuses undistractedly on the perception of earth.

_amanasikaritvā manussasaññaṃ amanasikaritvā araññasaññaṃ 
paṭhavīsaññaṃ paṭicca manasikaroti ekattaṃ._
____

.Illustration
====
paṭicca

by
====

____
Just as a space that is enclosed by stakes, creepers, grass and clay is 
reckoned as a dwelling,

_Seyyathā pi āvuso kaṭṭhañca paṭicca valliñca paṭicca tiṇañca 
paṭicca mattikañca paṭicca ākāso parivārito agāranteva saṅkhaṃ 
gacchati_
____

[quote, M.1.190]
____
so a volume that is enclosed by bones, sinews, flesh, and skin is known as a 
bodily form.

_evameva kho āvuso aṭṭhiñca paṭicca nahāruñca paṭicca maṃsañca 
paṭicca cammañca paṭicca ākāso parivārito rūpanteva saṅkhaṃ 
gacchati._
____

.Illustration
====
paṭicca

in
====

[quote, M.1.507-8]
____
Yet they find a certain measure of pleasure and sweetness in the five varieties 
of sensuous pleasure

_hoti ceva sātamattā assādamattā yadidaṃ pañcakāmaguṇe paṭicca._
____

Bodhi: yet they find a certain measure of satisfaction and enjoyment in 
dependence on the five cords of sensuous pleasure

.Illustration
====
paṭicca

for
====

[quote, A.1.98]
____
For two good reasons the Perfect One establishes training rules for his 
disciples.

_Dveme bhikkhave atthavase paṭicca tathāgatena sāvakānaṃ sikkhāpadaṃ 
paññattaṃ._
____

.Illustration
====
paṭicca

for
====

[quote, S.3.93; It.89]
____
And yet noble young men take up that way of life for a good reason.

_tañca kho evaṃ bhikkhave kulaputtā upenti atthavasikā atthavasaṃ 
paṭicca._
____

.Illustration
====
paṭicca

from
====

[quote, M.1.454]
____
Whatever happiness or joy arises from the five varieties of sensuous pleasure

_Yaṃ kho udāyi ime pañcakāmaguṇe paṭicca uppajjati sukhaṃ 
somanassaṃ._
____

.Illustration
====
paṭicca

in reference to
====

[quote, M.3.52]
____
Assumed individuality is of two kinds, I declare: to be fostered and not to be 
fostered. And one's assumed individuality is either the one or the other. So it 
was said by the Blessed One. And in reference to what was it said?

_Attabhāvapaṭilābhampahaṃ bhikkhave duvidhena vadāmi sevitabbampi 
asevitabbampi. Tañca aññamaññaṃ attabhāvapaṭilābhan ti iti kho 
panetaṃ vuttaṃ bhagavatā kiñcetaṃ paṭicca vuttaṃ._
____

