== Paṭisallāna

=== Renderings

- _paṭisallāna_: solitary retreat

- _paṭisallīyati_: to abide in solitary retreat

- _paṭisallīno_: one who abides in solitary retreat

=== Illustrations

.Illustration
====
paṭisallīnā

solitary retreat
====

[quote, D.2.265]
____
It is hard for the likes of us to get near the Perfect Ones when they are 
meditating, taking delight in meditation and therefore withdrawn into solitary 
retreat.

_durupasaṅkamā kho tāta pañcasikha tathāgatā mādisena jhāyi 
jhānaratā tadantarapaṭisallīnā._
____

.Illustration
====
paṭisallāna

solitary retreat
====

[quote, It.39]
____
Abide in solitary retreat taking pleasure and delight in it, apply yourself to 
inward calm, do not be neglectful of meditation, be endowed with 
insightfulness, and cultivate solitary abodes.

_Paṭisallānārāmā bhikkhave viharatha paṭisallānaratā ajjhattaṃ 
cetosamathamanuyuttā anirākatajjhāni vipassanāya samannāgatā brūhetā 
suññāgārānaṃ._
____

.Illustration
====
paṭisallānāya

solitary retreat
====

• Content with that unshakeable faith in the [perfection of the] Buddha's 
&#8203;[transcendent insight], he does not make further effort for physical seclusion 
by day nor for solitary retreat at night +
☸ s__o tena buddhe aveccappasādena santuṭṭho na uttariṃ vāyamati 
divā pavivekāya rattiṃ paṭisallānāya__ (S.5.398).

.Illustration
====
paṭisallāna

solitary retreat
====

[quote, A.4.87-8]
____
Dwellings that are quiet, undisturbed by voices, with a quiet atmosphere, 
remote from people, suitable for solitary retreat, I praise the association 
with such dwellings.

_yāni ca kho tāni senāsanāni appasaddāni appanigghosāni vijanavātāni 
manussarāhaseyyakāni paṭisallānasāruppāni tathārūpehi senāsanehi 
saṃsaggaṃ vaṇṇayāmī ti._
____

.Illustration
====
paṭisallīnassa

solitary retreat
====

[quote, S.1.139]
____
While the Blessed One was alone in solitary retreat, this reflection arose in 
his mind:

_bhagavato rahogatassa paṭisallīnassa evaṃ cetaso parivitakko udapādi._
____

.Illustration
====
paṭisallīyati

abide in solitary retreat
====

[quote, D.2.237]
____
He who abides in solitary retreat for the four months of the Rains, practising 
the meditation on [unlimited, all-encompassing] compassion, sees Brahmā.

_yo vassike cattāro māse paṭisallīyati karuṇaṃ jhānaṃ jhāyati so 
brahmānaṃ passati._
____

.Illustration
====
paṭisallīno

abides in solitary retreat
====

[quote, A.5.168]
____
A bhikkhu abides in solitary retreat, and speaks in favour of this,

_bhikkhu paṭisallīno hoti paṭisallānassa vaṇṇavādī._
____

.Illustration
====
paṭisallāne

solitary retreat; one who abides in solitary retreat, paṭisallīno
====

[quote, S.3.15]
____
Bhikkhus, make an effort with solitary retreat. A bhikkhu who abides in 
solitary retreat discerns things according to reality.

_Paṭisallāne bhikkhave yogamāpajjatha. Paṭisallīno bhikkhave bhikkhu 
yathābhūtaṃ pajānāti._
____

.Illustration
====
paṭisallīno

abide in solitary retreat
====

[quote, D.2.270]
____
'It is not the right time to see the Blessed One. The Blessed One is abiding in 
solitary retreat.'

_akālo kho mārisa bhagavantaṃ dassanāya paṭisallīno bhagavā ti._
____

