== Paṭinissaggānupassī assasissāmī ti sikkhati

=== Renderings

- _paṭinissaggānupassī assasissāmī ti sikkhati_: He trains himself: 'I 
will breathe in contemplating relinquishment [in relation to certain objects of 
the systematic teachings]

=== Introduction

==== Paṭinissagga's usual objects

_Paṭinissagga_ usually has a specified object in the genitive case. For 
example:

1. Views: relinquishment of views
+
****
_diṭṭhīnaṃ paṭinissaggo hoti_ (M.1.40).
****

2. Attachment: Relinquishment of the whole phenomenon of attachment
+
****
_sabbūpadhipaṭinissaggo_ (A.3.164).
****

3. Craving: The relinquishment of all forms of craving
+
****
_sabbaso taṇhānaṃ... paṭinissaggā_ (M.1.6).
****

==== Paṭinissagga's objects during contemplation

When _paṭinissagga_ is for contemplation, it usually has a specified object 
in the locative case. For example:

1. The visual sense (_cakkhu_): In this regard, some person in relation to the 
visual sense abides contemplating relinquishment, perceiving relinquishment, 
experiencing relinquishment continuously, without a break, uninterruptedly, 
intent upon it mentally, penetrating it with penetrative discernment
+
****
_Idha bhikkhave ekacco puggalo cakkhūsmiṃ paṭinissaggānupassī viharati 
paṭinissaggasaññī paṭinissaggapaṭisaṃvedī satataṃ samitaṃ 
abbokiṇṇaṃ cetasā adhimuccamāno paññāya pariyogāhamāno_ (A.4.146; 
A.4.13).
****

2. Sense impression: Whatever sense impression he experiences whether pleasant, 
unpleasant, or neutral, in relation to that sense impression he abides... 
contemplating relinquishment
+
****
_yaṃ kiñci vedanaṃ vedeti sukhaṃ vā dukkhaṃ vā adukkhamasukhaṃ vā 
so tāsu vedanāsu... paṭinissaggānupassī viharati_ (M.1.251).
****

3. The body and pleasant sense impression: He abides contemplating 
relinquishment in relation to the body and pleasant sense impression.
+
****
_so kāye ca sukhāya ca vedanāya... paṭinissaggānupassī viharati_ 
(S.4.211).
****

==== Paṭinissagga in mindfulness with breathing

However, in mindfulness with breathing _paṭinissagga_ occurs without an 
object:

____
He trains himself: 'I will breathe in... I will breathe out contemplating 
relinquishment.

_paṭinissaggānupassī assasissāmī ti... passasissāmī ti sikkhati_
____

The object of contemplation in this case is said to be the fourth of the bases 
of mindfulness, which we have explained (sv _Dhamma_) means 'certain objects of 
the systematic teachings.' Therefore we translate as follows:

[quote, S.5.325]
____
When a bhikkhu is training himself to breathe in and breathe out contemplating 
relinquishment, at that time he abides contemplating the nature of certain 
objects of the systematic teachings.

_Yasmiṃ samaye ānanda bhikkhu... paṭinissaggānupassī assasissāmī ti 
sikkhati paṭinissaggānupassī passasissāmī ti sikkhati dhammesu 
dhammānupassī ānanda bhikkhu tasmiṃ samaye viharati._
____

Objects of the systematic teachings are therefore the objects when 
contemplating relinquishment during mindfulness with breathing, and they should 
be regarded as a locative:

[quote, S.5.324]
____
I will breathe in... I will breathe out contemplating relinquishment [in 
relation to certain objects of the systematic teachings]

_paṭinissaggānupassī assasissāmī ti... passasissāmī ti sikkhati._
____

==== Dhammesu dhammānupassī viharati: objects of the systematic teachings

Objects of the systematic teachings given in the _Satipaṭṭhāna Sutta_ are:

[quote, M.1.59-62]
____
In this regard a bhikkhu abides contemplating the nature of certain objects of 
the systematic teachings in respect of the five hindrances... the five 
aggregates... the six senses and their objects... the seven enlightenment 
factors... the four noble truths.

_Idha bhikkhave bhikkhu dhammesu dhammānupassī viharati pañcasu 
nīvaraṇesu... pañcasupādānakkhandhesu... chasu ajjhattikabāhiresu 
āyatanesu... sattasu bojjhaṅgesu... catusu ariyasaccesu._
____

But only the aggregates and sense bases really fit here. For discussion of this 
point, see Glossary sv _Dhamma_.

=== Illustrations

.Illustration
====
relinquishment [in relation to certain objects of the systematic teachings]

He trains himself: I will breathe in... I will breathe out contemplating

____
unlastingness [in relation to certain objects of the systematic teachings]

_Aniccānupassī assasissāmī ti... passasissāmī ti sikkhati_
____

• passing away [in relation to certain objects of the systematic teachings] +
☸ virāgā__nupassī assasissāmī ti... passasissāmī ti sikkhati__

____
ending [in relation to certain objects of the systematic teachings]

_nirodhānupassī assasissāmī ti... passasissāmī ti sikkhati_
____

[quote

S.5.324]
====

____
relinquishment [in relation to certain objects of the systematic teachings]

_paṭinissaggānupassī assasissāmī ti... passasissāmī ti sikkhati._
____

