== Paṭibhāna

=== Renderings

- _appaṭibhāna_: unable to speak

- _paṭibhāna_: reply

- _paṭibhāna_: way of replying

- _paṭibhāna_: impromptu reflection

- _paṭibhāna_: intuitive knowledge

- _paṭibhāna_: intuitive insight

- _paṭibhāna_: intuition

- _paṭibhāna_: intuitive investigativeness

- _paṭibhāneyyaka_: conversable

=== Introduction

==== Intuition

Some aspects of _paṭibhāna_ concern intuition, meaning 'quick and ready 
insight' (Webster's). Intuition is one of the benefits of mindfulness of the 
body:

[quote, M.3.96]
____
Whoever develops and cultivates mindfulness of the body can turn his mind to 
the realisation through transcendent insight of whatever condition is 
realisable through transcendent insight, and become an eye-witness in every 
case, if there is the practice of spiritual development.

_Yassa kassaci bhikkhave kāyagatā sati bhāvitā bahulīkatā so yassa yassa 
abhiññā sacchikaraṇīyassa dhammassa cittaṃ abhininnāmeti abhiññā 
sacchikiriyāya. Tatra tatrave sakkhibhabbataṃ pāpuṇāti sati sati 
āyatane._
____

=== Illustrations

.Illustration
====
appaṭibhāno

unable to speak
====

[quote, A.3.57]
____
When the king was told the queen had died he sat there pained, saddened, with 
drooped shoulders, head down, brooding, unable to speak.

_Evaṃ vutte rājā pasenadi kosalo dukkhī dummano pattakkhandho adhomukho 
pajjhāyanto appaṭibhāno nisīdi._
____

.Illustration
====
appaṭibhānā

unable to speak
====

[quote, D.3.57]
____
Having lost an argument, those ascetics sat there silent, embarrassed, with 
drooped shoulders, heads down, brooding, unable to speak.

_Evaṃ vutte te paribbājakā tuṇhībhūtā maṅkubhūtā pattakkhandhā 
adhomukhā pajjhāyantā appaṭibhānā nisidiṃsu._
____

.Illustration
====
paṭibhāneyyakānaṃ

conversable
====

The Buddha addressed numerous discourses to Rādha (S.3.79; S.3.188-200; 
S.4.48-49), and accordingly said:

[quote, A.1.25]
____
'Foremost of my bhikkhu disciples who are conversable is Rādha.'

_Etadaggaṃ bhikkhave mama sāvakaṃ bhikkhūnaṃ paṭibhāneyyakānaṃ 
yadidaṃ rādho._
____

.Illustration
====
paṭibhāneyyakānaṃ

conversable
====

____
Now at that time a certain person, formerly a barber, who had gone forth [into 
the ascetic life] when old, was living in Atuma. He had two sons, sweet-voiced, 
conversable, clever, accomplished in the barber's profession.

_Tena kho pana samayena aññataro buḍḍhapabbajito ātumāyaṃ 
paṭivasati nahāpitapubbo. Tassa dve dārakā honti mañjukā 
paṭibhāneyyakā dakkhā pariyodātasippā sake ācariyake nahāpitakamme._
____

The bhikkhu asked his sons to collect funds.

[quote, Vin.1.249]
____
Those people who, having seen these sweet-voiced, conversable boys, but had not 
wanted to offer, even they offered, and in offering, gave much.

_Manussā te dārake mañajuke paṭibhāneyyake passitvā yepi na 
kārāpetukāmā tepi kārāpenti. Kārāpetvāpi bahuṃ denti._
____

.Illustration
====
paṭibhānāni

reply
====

[quote, D.2.352]
____
I was so pleased and satisfied with Master Kassapa's first parable, I wanted to 
hear his brilliant replies to these other various questions.

_Purimeneva ahaṃ opammena bhoto kassapassa attamano abhiraddho api cāhaṃ 
imāni vicitrāni pañhāpaṭibhānāni sotukāmo._
____

.Illustration
====
paṭibhāno

way of replying
====

There are four kinds of persons:

____
Those whose way of replying is fitting but halting

_yuttapaṭibhāno na muttapaṭibhāno_
____

____
Those whose way of replying is fluent but unfitting

_muttapaṭibhāno na yuttapaṭibhāno_
____

____
Those whose way of replying is fitting and fluent

_yuttapaṭibhāno ca muttapaṭibhāno ca_
____

[quote, A.2.135]
____
Those whose way of replying is unfitting and halting

_neva yuttapaṭibhāno neva muttapaṭibhāno._
____

.Illustration
====
paṭibhānaṃ

impromptu reflection
====

____
Of profound wisdom, intelligent, knowledgeable about what is the Path and what 
is not the Path, Sāriputta, of great wisdom, explains the Buddha's teaching to 
the bhikkhus.

_Gambhīrapañño medhāvī maggāmaggassa kovido +
Sāriputto mahāpañño dhammaṃ deseti bhikkhunaṃ._
____

[quote, S.1.190]
____
He teaches in brief, he speaks in detail. His voice, like a myna bird, pours 
forth his impromptu reflection.

_Saṅkhittena pi deseti vitthārena pi bhāsati +
Sālikāyiva nigghoso paṭibhānaṃ udīrayi._
____

.Illustration
====
paṭibhānaṃ

impromptu reflection
====

____
Five things, once arisen, are hard to dispel.

_Pañcime bhikkhave uppannā duppaṭivinodayā_
____

____
Attachment

_uppanno rāgo duppaṭivinodayo_
____

____
Hatred

_uppanno doso duppaṭivinodayo_
____

____
Undiscernment of reality

_uppanno moho duppaṭivinodayo_
____

____
Impromptu reflection

_uppannaṃ paṭibhānaṃ duppaṭivinodayaṃ_
____

[quote, A.3.185]
____
The urge to travel

_uppannaṃ gamikacittaṃ duppaṭivinodayaṃ._
____

.Illustration
====
paṭibhānavantānaṃ

impromptu reflectiveness
====

[quote, A.1.24]
____
Foremost of my bhikkhu disciples of impromptu reflectiveness is Vaṅgīsa.

_Etadaggaṃ bhikkhave mama sāvakānaṃ bhikkhūnaṃ paṭibhānavantānaṃ 
yadidaṃ vaṅgīso._
____

.Illustration
====
paṭibhāna

impromptu reflective
====

____
Bhikkhus, there are these four kinds of poets. What four?

_cattārome bhikkhave kavī. Katame cattāro?_
____

____
The metaphysical poet

_cintākavi_
____

____
the narrational poet

_sutakavi_
____

____
the didactic poet

_atthakavi_
____

[quote, A.2.230]
____
the impromptu reflective poet

_paṭibhānakavi._
____

Comment:

Bodhi says the last one, which he calls the 'inspirational poet,' creates 
poetry spontaneously through his own inspiration, like Venerable Vaṅgīsa.

.Illustration
====
paṭibhānena

impromptu reflectiveness
====

[quote, S.1.187]
____
Venerable Vaṅgīsa despised other well-behaved bhikkhus on account of his own 
impromptu reflectiveness

__āyasmā vaṅgīso attano paṭibhānena aññe pesale bhikkhū 
atimaññati._
____

.Illustration
====
paṭibhāna

intuitive knowledge
====

Venerable Sāriputta told the bhikkhus:

____
Within two weeks of my ordination I attained analytical insight into the 
meaning of expressions with their divisions and features;

_Addhamāsūpasampannena me āvuso atthapaṭisambhidā sacchikatā odhiso 
vyañjanaso_
____

____
Within two weeks of my ordination I attained analytical insight into the 
teachings with their divisions and features;

_Addhamāsūpasampannena me āvuso dhammapaṭisambhidā sacchikatā odhiso 
vyañjanaso_
____

____
Within two weeks of my ordination I attained analytical insight into the use of 
conventional expressions with their divisions and features;

_Addhamāsūpasampannena me āvuso niruttipaṭisambhidā sacchikatā odhiso 
vyañjanaso_
____

[quote, A.2.160]
____
Within two weeks of my ordination I attained analytical insight into intuitive 
knowledge with its divisions and features;

_Addhamāsūpasampannena me āvuso paṭibhānapaṭisambhidā sacchikatā 
odhiso vyañjanaso._
____

Comment:

Bodhi says the last analytical insight 'seems to refer to the ability to 
spontaneously apply the other three types of knowledge to clearly communicate 
the Dhamma.'

This ability is illustrated in the _Bhūta Sutta_ (S.2.47-50) and the 
_Kaḷāra Sutta_ (S.2.51-6) when the Buddha asked Sāriputta about _The 
Questions of Ajita._ Sāriputta hesitated because he had not previously 
considered the issue (_pubbe appaṭisaṃviditaṃ_). But when the Buddha 
prompted him and then approved of his answer, Sāriputta said:

[quote, S.2.55]
____
If the Blessed One had for seven days and nights questioned me about the matter 
in various ways and manners, then for seven days and nights I would have been 
able to answer him in various ways and manners.

_Satta rattindivāni cepi maṃ bhagavā etamatthaṃ puccheyya aññamaññehi 
padehi aññamaññehi pariyāyehi satta rattindivānipahaṃ bhagavato 
etamatthaṃ vyākareyyaṃ aññamaññehi padehi aññamaññehi pariyāyehī 
ti._
____

This ability to talk for seven days on a topic he had never before considered, 
we call 'intuitive knowledge.' The Buddha said Sāriputta was able to answer 
like this because he had correctly penetrated "that aspect of the teaching" 
(_sā dhammadhātu suppaṭividdhā_) that made such an ability possible.

[quote, S.2.56]
____
That aspect of the teaching has been correctly penetrated by Sāriputta, which 
through being correctly penetrated... if I had for seven days and nights 
questioned Sāriputta about the matter in various ways and manners, then for 
seven days and nights Sāriputta would have been able to answer me in various 
ways and manners.

_Sā hi bhikkhu sāriputtassa dhammadhātu suppaṭividdhā yassa 
dhammadhātuyā suppaṭividdhattā... satta rattindivāni cepahaṃ 
sāriputtaṃ etamattaṃ puccheyyaṃ aññamaññehi padehi aññamaññehi 
pariyāyehi satta rattindivānipi me sāriputto etamatthaṃ vyākareyya 
aññamaññehi padehi aññamaññehi pariyāyehī ti._
____

.Illustration
====
paṭibhānaṃ

intuitive
====

[quote, M.1.68]
____
The ascetic Gotama explains his teaching, hammering it out by logical 
reasoning, following his own intuitive line of inquiry

_Takkapariyāhataṃ samaṇo gotamo dhammaṃ deseti vīmaṃsānucaritaṃ 
sayampaṭibhānaṃ._
____

.Illustration
====
paṭibhānaṃ

intuitive
====

[quote, D.1.16]
____
A certain ascetic or Brahmanist is a thinker, a philosopher. Hammering it out 
by logical reasoning, following his own intuitive line of inquiry, he argues: 
The [absolute] Selfhood and the world [of beings] are eternal.

_Idha bhikkhave ekacco samaṇo vā brāhmaṇo vā takkī hoti vīmaṃsī. So 
takkapariyāhataṃ vīmaṃsānucaritaṃ sayampaṭibhānaṃ evamāha: 
sassato attā ca loko ca._
____

.Illustration
====
paṭibhānaṃ

intuition
====

Ānanda answered the question: 'Which kind of bhikkhu do you think would most 
illuminate the Gosinga Sāla-tree Wood?' Then Sāriputta said to Revata:

[quote, M.1.213]
____
-- 'Revata, friend, it has been answered by Venerable Ānanda according to his 
own intuition. Now we ask Venerable Revata.'

_vyākataṃ kho āvuso revata āyasmatā ānandena yathā sakaṃ 
paṭibhānaṃ. Tatthadāni mayaṃ āyasmantaṃ revataṃ pucchāma._
____

.Illustration
====
paṭibhānaṃ

intuition
====

After bhikkhus had expressed their opinions on a certain matter, Venerable 
Sāriputta said:

[quote, A.1.119]
____
"Friends, we have each explained [the matter] according to our own intuition.

_vyākataṃ kho āvuso amhehi sabbeheva yathā sakaṃ paṭibhānaṃ._
____

.Illustration
====
paṭibhāno

intuitive insight
====

[quote, A.3.58]
____
A good report has been circulated about Venerable Nārada: he is wise, capable, 
intelligent, very learned, a brilliant speaker, of excellent intuitive insight, 
mature, and truly an arahant.

_Taṃ kho pana āyasmantaṃ nāradaṃ evaṃ kalyāṇo kittisaddo 
abbhuggato: paṇḍito vyatto medhāvī bahussuto cittakathī 
kalyāṇapaṭibhāno vuddho ceva arahā ca._
____

.Illustration
====
paṭibhāno

intuitive insight
====

[quote, D.3.107]
____
One should be truthful, and have faith [in the perfection of the Perfect One's 
transcendent insight]... and should be moderate in the use of food, of 
consistent virtue, devoted to wakefulness, tirelessly applied [to the 
practice], energetic, meditative, mindful, and of excellent intuitive insight.

_Idha bhante ekacco sacco cassa saddho ca... bhojane mattaññu samakārī 
jāgariyānuyogamanuyutto atandito āraddhaviriyo jhāyī satimā 
kalyāṇapaṭibhāno._
____

.Illustration
====
paṭibhānaṃ

intuitive insight
====

When Venerable Uttara agreed that he had once taught something, Sakka asked him:

[quote, A.4.163]
____
"But, bhante, was [the teaching] your own intuitive insight, or was it the word 
of the Blessed One, the Arahant, the Perfectly Enlightened One?"

_Kiṃ panidaṃ bhante āyasmato uttarassa sakaṃ paṭibhānaṃ udāhu 
tassa bhagavato vacanaṃ arahato sammāsambuddhassāti._
____

.Illustration
====
paṭibhānenā

intuitive insight
====

____
And how is a bhikkhu one who knows himself?

_Attaññū ca kathaṃ hoti_
____

[quote, A.4.114]
____
In this regard a bhikkhu knows himself thus: 'I have so much faith, virtue, 
learning, generosity, penetrative discernment, and intuitive insight.'

_Idha bhikkhave bhikkhu attānaṃ jānāti ettakomhi saddhāya sīlena sutena 
cāgena paññāya paṭibhānenā ti._
____

.Illustration
====
paṭibhānavantaṃ

intuitively insightful
====

[quote, Sn.v.58]
____
One should associate with one of great learning, who is an expert in the 
teaching, a noble friend, one who is intuitively insightful.

_Bahussutaṃ dhammadharaṃ bhajetha mittaṃ uḷāraṃ 
paṭibhānavantaṃ._
____

.Illustration
====
paṭibhānaṃ

intuitive investigativeness
====

Venerable Bhadda asked:

____
-- 'What, friend, is the religious life and what is the conclusion of the 
religious life?'

_Katamaṃ nu kho āvuso brahmacariyaṃ? Katamaṃ brahmacariyapariyosānan 
ti?_
____

Venerable Ānanda replied:

____
-- 'Well asked, Bhadda, friend! Your inquiry is excellent, your intuitive 
investigativeness is excellent, your question is good.'

_Sādhu sādhu āvuso bhadda bhaddako te āvuso bhadda ummaggo bhaddakaṃ 
paṭibhānaṃ kalyāṇī paripucchā_
____

.Illustration
====
paṭibhānaṃ

intuitive investigativeness
====

____
-- 'On what grounds, bhante, is one of great learning, an expert in the 
teaching?'

_Kittāvatā nu kho bhante bahussuto dhammadharo hotī ti_
____

[quote, A.2.178]
____
-- 'Well asked, bhikkhu! Your inquiry is excellent! Your intuitive 
investigativeness is excellent! Your question is good!'

_Sādhu sādhu bhikkhu bhaddako te bhikkhu ummaggo bhaddakaṃ paṭibhānaṃ 
kalyāṇī paripucchā._
____

