== Paṭisaṃyutta

=== Renderings

- _paṭisaṃyutta_: connected with

- _paṭisaṃyutta_: concerning

- _paṭisaṃyutta_: about

=== Illustrations

.Illustration
====
paṭisaṃyutto

about
====

[quote, A.1.253]
____
Thoughts about being disparaged

_anavaññattipaṭisaṃyutto vitakko._
____

.Illustration
====
paṭisaṃyutta

concerning
====

[quote, Ud.80]
____
He was instructing the bhikkhus with a religious discourse concerning the 
Untroubled,

_nibbānapaṭisaṃyuttāya dhammiyā kathāya sandasseti._
____

.Illustration
====
paṭisaṃyuttā

concerning
====

[quote, M.1.453-4]
____
Memories and thoughts concerning objects of attachment

_upadhipaṭisaṃyuttā sarasaṅkappā samudācaranti._
____

.Illustration
====
paṭisaṃyuttā

connected
====

[quote, Th.v.589]
____
Mental images connected with physical seclusion overwhelm me

_Saññā me abhikīranti vivekapaṭisaṃyuttā._
____

.Illustration
====
paṭisaṃyutta

connected with
====

[quote, A.4.233]
____
One whose words are exclusively connected with religious inspiration.

_uyyojanikapaṭisaṃyuttaṃyeva kathaṃ kattā hoti._
____

