== Paṭhavī; Āpo; Tejo; Vāyo

=== Renderings

- _paṭhavī_: earth

- _paṭhavī_: solidness

- _paṭhavī_: land

- _paṭhavī_: subcontinent

- _paṭhavīdhātu_: the Solidness Phenomenon

- _āpodhātu_: the Liquidness Phenomenon

- _tejodhātu_: the Warmth Phenomenon

- _vāyodhātu_: the Gaseousness Phenomenon

=== Introduction

==== Elements: definitions

The four material phenomena are _paṭhavīdhātu āpodhātu tejodhātu 
vāyodhātū_ (M.1.57). They are defined like this:

[quote, M.1.185]
____
The Solidness Phenomenon: whatever is hard or rough

_paṭhavīdhātu: yaṃ... kakkhalaṃ kharigataṃ._
____

[quote, M.1.187]
____
The Liquidness Phenomenon: whatever is liquid or watery

__āpodhātu: yaṃ... āpo āpogataṃ._
____

[quote, M.1.188]
____
The Warmth Phenomenon: whatever is warmth or heat

_tejodhātu: yaṃ... tejo tejogataṃ._
____

[quote, M.1.188]
____
The Gaseousness Phenomenon: whatever is gaseous or windy

_vāyodhātu: yaṃ... vāyo vāyogataṃ._
____

We render the -_gata_ suffix according to PED's definition, namely 'being in a 
state or condition, or having come into a state or condition.'

==== Instruction on the Log: the nature of the elements

Venerable Sāriputta pointed to a large wooden log and said:

[quote, A.3.340-1]
____
'A bhikkhu with psychic power and mental mastery could, if he wished, focus on 
the solidness (_paṭhavī_) of that wooden log. How is that? There is the 
Solidness Phenomenon (_paṭhavīdhātu_) in that log of wood, by reason of 
which a bhikkhu with psychic power and mental mastery could focus on its 
solidness (_paṭhavī_).'

_Ākaṅkhamāno āvuso bhikkhu iddhimā cetovasippatto amuṃ dārukkhandhaṃ 
paṭhavītveva adhimucceyya. Taṃ kissa hetu? Atthi āvuso amumhi 
dārukkhandhe paṭhavīdhātu yaṃ nissāya bhikkhu iddhimā cetovasippatto 
amuṃ dārukkhandhaṃ paṭhavītveva adhimucceyya._
____

____
the Liquidness Phenomenon in that log of wood... could focus on its liquidness 
(_āpo_).

__āpodhātu... āpotveva adhimucceyya_
____

____
the Warmth Phenomenon in that log of wood... could focus on its warmth (_tejo_).

_tejodhātu... tejotveva adhimucceyya_
____

• the Gaseousness Phenomenon in that log of wood... could focus on its 
gaseousness (_vāyo_). +
☸ _vāyodhātu_... _vāyotveva adhimucceyya_

____
the phenomenon of loveliness in that log of wood... could focus on its 
loveliness (_subha_).

_subhadhātu... subhantveva adhimucceyya_
____

• the phenomenon of unloveliness in that log of wood... could focus on its 
unloveliness (_asubha_). +
☸ a__subhadhātu... asubhantveva adhimucceyyā ti__ (A.3.340-1).

==== Definition: Solidness Phenomenon

The four great material phenomena are defined in full as follows:

____
What is the internal Solidness Phenomenon?

_Katamā cāvuso ajjhattikā paṭhavīdhātu?_
____

____
... Whatever is internal that is hard or rough, part of an individual, and 
taken personally

_Yaṃ ajjhattaṃ paccattaṃ kakkhalaṃ kharigataṃ upādinnaṃ_
____

[quote, M.1.185]
____
... namely, head hairs, body hairs, nails, teeth, skin, flesh, sinews, bones, 
marrow, kidneys, heart, liver, diaphragm, spleen, lungs, bowels, mesentery, 
stomach contents, faeces, and whatever else is internal that is hard or rough, 
part of an individual, and taken personally, this is called the internal 
Solidness Phenomenon.

_seyyathidaṃ kesā lomā nakhā dantā taco maṃsaṃ nahāru aṭṭhi 
aṭṭhimiñjaṃ vakkaṃ hadayaṃ yakanaṃ kilomakaṃ pihakaṃ 
papphāsaṃ antaṃ antaguṇaṃ udariyaṃ karīsaṃ yaṃ vā panaññampi 
kiñci ajjhattaṃ paccattaṃ kakkhalaṃ kharigataṃ upādinnaṃ._
____

==== Definition: Liquidness Phenomenon

____
What is the internal Liquidness Phenomenon?

_ajjhattikā āpodhātu_
____

[quote, M.1.185]
____
Whatever is internal that is liquid or watery, part of an individual, and taken 
personally: bile, gastric mucus, pus, blood, sweat, fat, tears, skin-grease, 
spittle, snot, synovial fluid, urine, and whatever else is internal that is 
liquid or watery, part of an individual, and taken personally, this is called 
the internal Liquidness Phenomenon.

_Yaṃ ajjhattaṃ paccattaṃ āpo āpogataṃ upādinnaṃ seyyathidaṃ 
pittaṃ semhaṃ pubbo lohitaṃ sedo medo assu vasā khelo siṅghāṇikā 
lasikā muttaṃ yaṃ vā panaññampi kiñci ajjhattaṃ paccattaṃ āpo 
āpogataṃ upādinnaṃ ayaṃ vuccatāvuso ajjhattikā āpodhātu._
____

==== Definition: Warmth Phenomenon

____
What is the internal Warmth Phenomenon?

_Katamā ca bhikkhu ajjhattikā tejodhātu_
____

____
Whatever is internal that is warm or hot, part of an individual, and taken 
personally

_yaṃ ajjhattaṃ paccattaṃ tejo tejogataṃ upādinnaṃ_
____

[quote, M.3.241]
____
Namely, that by which one is heated, that by which one is hurt, that by which 
one is burnt, that by which what is eaten, drunk, chewed and savored gets 
digested, and whatever else is internal that is warm or hot, part of an 
individual, and taken personally, this is called the internal Warmth Phenomenon.

_yena ca santappati yena ca jīrīyati yena ca pariḍayhati yena ca 
asitapītakhāyitasāyitaṃ sammā pariṇāmaṃ gacchati yaṃ vā 
panaññampi kiñci ajjhattaṃ paccattaṃ tejo tejogataṃ upādinnaṃ 
ayaṃ vuccatāvuso ajjhattikā tejodhātu._
____

==== Definition: Gaseousness Phenomenon

____
What is the internal Gaseousness Phenomenon

_ajjhattikā vāyodhātu_
____

____
Whatever is internal that is gaseous or windy, part of an individual, and taken 
personally

_yaṃ ajjhattaṃ paccattaṃ vāyo vāyogataṃ upādinnaṃ_
____

____
up-going winds

_uddhaṅgamā vātā_
____

____
down-going winds

_adhogamā vātā_
____

____
wind in the stomach

_kucchisayā vātā_
____

____
wind in the intestines

_koṭṭhāsayā vātā_
____

____
bodily energies that course through the limbs

_aṅgamaṅgānusārino vātā_
____

____
in-breathing and out-breathing

_assāso passāso iti_
____

[quote, M.1.188]
____
and whatever else is internal that is gaseous or windy, part of an individual, 
and taken personally, this is called the internal Gaseousness Phenomenon

_ayaṃ vuccatāvuso ajjhattikā vāyodhātu._
____

==== Similes: the butchered cow

The contemplation of the four great material phenomena is described like this:

____
The bhikkhu contemplates this very body however placed or disposed in terms of 
material phenomena.

_imameva kāyaṃ yathāṭhitaṃ yathāpaṇihitaṃ dhātuso paccavekkhati_
____

• ... In this [wretched human] body there is the Solidness Phenomenon, the 
Liquidness Phenomenon, the Warmth Phenomenon, and the Gaseousness Phenomenon. +
A__tthi imasmiṃ kāye paṭhavīdhātu āpodhātu tejodhātu vāyodhātū ti__

... Just as a butcher or his apprentice having killed a cow and cut it into 
pieces were seated with it at a crossroads, the bhikkhu contemplates this very 
body however placed or disposed in terms of material phenomena (M.1.57).

The butchered cow simile suggests that one who meditates on the four great 
material phenomena will see just material qualities, and will realise that, in 
that respect, living bodies are indistinguishable from dead ones.

==== Kasiṇas

The four great material phenomena are subjects of kasiṇa practices, as 
follows:

[quote, D.3.268]
____
One individual perceives the kasiṇa of earth extending above, below, and 
across from himself, with no subject/object duality and without limitation

_paṭhavīkasiṇameko sañjānāti uddhaṃ adho tiriyaṃ advayaṃ 
appamāṇaṃ._
____

____
The other kasiṇas are: water, fire, wind, blue, yellow, red, white, space, 
and advertence

__āpokasiṇa tejokasiṇa vāyokasiṇa nīlakasiṇa pītakasiṇa 
lohitakasiṇa odātakasiṇa ākāsakasiṇa viññāṇakasiṇa_
____

The kasiṇas apparently involve imagining the Elements in their concrete sense 
extending in all directions.

=== Illustrations: paṭhavī

.Illustration
====
paṭhaviyā

earth
====

____
Suppose the seed of a nimb or creeper or bitter gourd be planted in moist earth.

_allāya paṭhaviyā nikkhittaṃ_
____

____
Whatever of the earth-nutriment or water-nutriment it absorbs

_yañceva paṭhavirasaṃ upādiyati yañca āporasaṃ upādiyati_
____

[quote, A.5.212]
____
all that leads to its bitterness, its acridity, its displeasing taste

_sabbaṃ taṃ tittakattāya kaṭukattāya asātattāya saṃvattanti._
____

.Illustration
====
paṭhaviyā

earth
====

[quote, S.2.212]
____
Bhikkhus, to whatever extent I wish I dive in and out of earth as though it 
were water

_paṭhaviyā pi ummujjanimujjaṃ karomi seyyathā pi udake._
____

.Illustration
====
paṭhaviyā

earth
====

• They throw what is clean or foul onto earth** +
☸** _paṭhaviyā sucimpi nikkhipanti asucimpi nikkhipanti_ (M.1.423).

.Illustration
====
paṭhaviyā

earth
====

[quote, M.1.516]
____
If, with a razor-rimmed wheel, one were to make the living beings of this earth 
into one mass of flesh, into one heap of flesh

_Khurapariyantena cepi cakkena yo imissā paṭhaviyā pāṇe ekaṃ 
maṃsakhalaṃ ekaṃ maṃsapuñjaṃ kareyya._
____

.Illustration
====
paṭhavyā

earth
====

[quote, Vin.2.303]
____
The oldest bhikkhu on earth

_paṭhavyā saṅghatthero._
____

.Illustration
====
paṭhaviṃ

solidness
====

A bhikkhu who is a disciple in training (_sekho_)

____
... fully understands solidness to be solidness

_sopi paṭhaviṃ paṭhavito abhijānāti_
____

____
... Fully understanding solidness to be solidness

_paṭhaviṃ paṭhavito abhiññāya_
____

____
... may he not think of solidness in personal terms

_paṭhaviṃ mā maññi_
____

____
... may he not think 'I am part of solidness'

_paṭhaviyā mā maññi_
____

____
... may he not think 'I am separate from solidness'

_paṭhavito mā maññi_
____

____
... may he not think that solidness is "[in reality] mine"

_paṭhaviṃ me ti mā maññi_
____

____
... may he not take delight in solidness

_paṭhaviṃ mābhinandi_
____

[quote, M.1.4]
____
... For what reason? So that he may profoundly understand it, I declare

_Pariññeyyaṃ tassā ti vadāmi._
____

.Illustration
====
paṭhaviyā

Earth; paṭhavattena, solidness
====

[quote, M.1.329]
____
The mind with no attribute, boundless, altogether free of defilement: that is 
not reached by the solidness of earth, the liquidness of water, the warmth of 
fire, the gaseousness of wind... the totality of everything

_Viññāṇaṃ anidassanaṃ anantaṃ sabbato pabhaṃ taṃ paṭhaviyā 
paṭhavattena ananubhūtaṃ āpassa āpattena ananubhūtaṃ tejassa 
tejattena ananubhūtaṃ vāyassa vāyattena ananubhūtaṃ... sabbassa 
sabbattena ananubhūtaṃ._
____

.Illustration
====
paṭhavi

earth
====

[quote, Sn.v.990]
____
Then who, pray, on this wide earth knows about heads and headsplitting?

_Atha ko carahi jānāti asmiṃ paṭhavimaṇḍale +
Muddhaṃ muddhādhipātañca._
____

.Illustration
====
paṭhavi

land
====

[quote, S.1.100]
____
Having conquered a great area of land.

_mahantaṃ paṭhavimaṇḍalaṃ abhivijiya._
____

.Illustration
====
paṭhavi

land
====

[quote, A.3.363]
____
For the _khattiya_, land is his relentless attachment

_paṭhavibhinivesā._
____

.Illustration
====
paṭhaviṃ

subcontinent
====

[quote, D.3.142]
____
He abides having conquered this sea-girt subcontinent

_so imaṃ paṭhaviṃ sāgarapariyantaṃ... abhivijīya ajjhāvasati._
____

=== Illustrations: āpo

.Illustration
====
āpaṃ liquidness

A bhikkhu who is a disciple in training (_sekho_)

____
fully understands liquidness to be liquidness

__āpaṃ āpato abhijānāti_
____

____
Fully understanding liquidness to be liquidness

__āpaṃ āpato abhiññāya_
____

____
may he not think of liquidness in personal terms

__āpaṃ mā maññi_
____

____
may he not think 'I am part of liquidness'

__āpasmiṃ mā maññi_
____

____
may he not think 'I am separate from liquidness'

__āpato mā maññi_
____

____
may he not think that liquidness is "[in reality] mine"

__āpaṃ me ti mā maññi_
____

____
may he not take delight in liquidness

__āpaṃ mābhinandi_
____

[quote

M.1.4]
====

____
For what reason? So that he may profoundly understand it, I declare

_Pariññeyyaṃ tassā ti vadāmi._
____

.Illustration
====
apo

liquidness
====

____
Now there comes a time, friends, when the external Liquidness Phenomenon is 
agitated

_bāhirā āpodhātu pakuppati_
____

[quote, M.1.187]
____
It washes away village, town, city, district, and country.

_Sā gāmampi vahati nigamampi vahati nagarampi vahati janapadampi vahati 
janapadapadesampi vahati._
____

.Illustration
====
apo

liquidness
====

[quote, M.1.185-9]
____
There comes a time when the water in the great ocean is not even the depth of 
the first joint of a finger. So when even in the external Liquidness Phenomenon 
with all its vastness, unlastingness is discernable, destruction is 
discernable, disappearance is discernable, changeableness is discernable, then 
what to say of this short-lasting body evolved from craving? .

_Hoti kho so āvuso samayo yaṃ mahāsamudde aṅgulipabbatemanamattampi 
udakaṃ na hoti. Tassā hi nāma āvuso bāhirāya āpodhātuyā tāva 
mahallikāya aniccatā paññāyissati khayadhammatā paññāyissati 
vayadhammatā paññāyissati vipariṇāmadhammatā paññāyissati. Kiṃ 
panimassa mattaṭṭhakassa kāyassa taṇhūpādinnassa._
____

.Illustration
====
āpo

water
====

[quote, M.1.423]
____
People wash what is clean or foul in water -- faeces, urine, spit, pus, and 
blood -- and the water is not revolted, appalled, or disgusted by it.

__āpasmiṃ sucimpi dhovanti asucimpi dhovanti gūthagatampi dhovanti 
muttagatampi dhovanti kheḷagatampi dhovanti pubbagatampi dhovanti 
lohitagatampi dhovanti na ca tena āpo aṭṭīyati vā harāyati vā 
jigucchati vā._
____

=== Illustrations: tejo

.Illustration
====
tejaṃ warmth

A bhikkhu who is a disciple in training (_sekho_)

____
knows warmth as warmth

_tejaṃ tejato abhijānāti_
____

____
Knowing warmth as warmth

_tejaṃ tejato abhiññāya_
____

____
may he not think of warmth in personal terms

_tejaṃ mā maññi_
____

____
may he not think 'I am part of warmth'

_tejasmiṃ mā maññi_
____

____
may he not think 'I am separate from warmth'

_tejato mā maññi_
____

____
may he not think that warmth is "[in reality] mine"

_tejaṃ me ti mā maññi_
____

____
may he not take delight in warmth

_tejaṃ mābhinandi_
____

[quote

M.1.4]
====

____
For what reason? So that he may profoundly understand it, I declare

_Pariññeyyaṃ tassā ti vadāmi._
____

.Illustration
====
tejo

fire
====

[quote, M.1.424]
____
Fire burns what is clean or foul -- faeces, urine, spit, pus, and blood -- and 
the fire is not revolted, appalled, or disgusted by it.

_tejo sucimpi ḍahati asucimpi ḍahati gūthagatampi ḍahati muttagatampi 
ḍahati kheḷagatampi ḍahati pubbagatampi ḍahati lohitagatampi ḍahati 
na ca tena tejo aṭṭīyati vā harāyati vā jigucchati vā._
____

=== Illustrations: vāyo

.Illustration
====
vāyaṃ

gaseousness
====

A bhikkhu who is a disciple in training (_sekho_)

____
fully understands gaseousness to be gaseousness

_vāyaṃ vāyato abhijānāti_
____

____
Fully understanding gaseousness to be gaseousness

_vāyaṃ vāyato abhiññāya_
____

____
may he not think of gaseousness in personal terms

_vāyaṃ mā maññi_
____

____
may he not think 'I am part of gaseousness'

_vāyasmiṃ mā maññi_
____

____
may he not think 'I am separate from gaseousness'

_vāyato mā maññi_
____

____
may he not think that gaseousness is "[in reality] mine"

_vāyaṃ me ti mā maññi_
____

____
may he not take delight in gaseousness

_vāyaṃ mābhinandi_
____

[quote, M.1.4]
____
For what reason? So that he may profoundly understand it, I declare

_Pariññeyyaṃ tassā ti vadāmi._
____

.Illustration
====
vāyo

wind
====

[quote, M.1.424]
____
Wind blows on what is clean or foul -- faeces, urine, spit, pus, and blood -- 
and the wind is not revolted, appalled, or disgusted by it.

_vāyo sucimpi upavāyati asucimpi upavāyati gūthagatampi upavāyati 
muttagatampi upavāyati kheḷagatampi upavāyati pubbagatampi upavāyati 
lohitagatampi upavāyati na ca tena vāyo aṭṭīyati vā harāyati vā 
jigucchati vā._
____

.Illustration
====
vāyo

Gaseousness
====

____
Now there comes a time, friends, when the external Gaseousness Phenomenon is 
agitated

_bāhirā vāyodhātu pakuppati_
____

[quote, M.1.188]
____
It blows away village, town, city, district, and country.

_sā gāmampi vahati nigamampi vahati nagarampi vahati janapadampi vahati 
janapadapadesampi vahati._
____

