== Pema

=== Renderings

- _pema_: love

- _pema_: affection

- _pema_: devotion

- _pema_: dedication

- _pemanīya_: lovely

=== Illustrations

.Illustration
====
pemaṃ

love
====

[quote, S.4.329-330]
____
Before you saw Ciravāsi's mother or heard about her, did you have any 
fondness, attachment, or love for her?

_yadā te ciravāsissa mātā adiṭṭhā āsi assutā ahosi ciravāsissa 
mātuyā chando vā rāgo vā pemaṃ vā ti._
____

.Illustration
====
pemo

love
====

[quote, D.3.238]
____
A bhikkhu has not got rid of attachment, fondness, love, thirst, passion, and 
craving regarding sensuous pleasures _

_bhikkhu kāmesu avigatarāgo hoti avigatachando avigatapemo avigatapipāso 
avigatapariḷāho avigatataṇho._
____

.Illustration
====
pemaṃ

love
====

[quote, Th.v.719]
____
Do what you have to do with my body, as you wish. There will be neither hatred 
nor love by me [of you] about that [or] on that account.

_Yaṃ vo kiccaṃ sarīrena taṃ karotha yadicchatha +
Na me tappaccayā tattha doso pemañca hehiti._
____

.Illustration
====
pemato

love
====

[quote, Dh.v.213]
____
From love come grief and fear. For one who is free of love there is neither 
grief nor fear.

_Pemato jāyati soko pemato jāyati bhayaṃ +
Pemato vippamuttassa natthi soko kuto bhayaṃ._
____

.Illustration
====
pemaṃ

love
====

[quote, Sn.v.41]
____
There is great love for sons

_Puttesu ca vipulaṃ hoti pemaṃ._
____

.Illustration
====
pemaṃ

love
====

[quote, Vin.1.83]
____
Love for sons, bhante, cuts into the skin.

_Puttapemaṃ bhante chaviṃ chindati._
____

.Illustration
====
pemaṃ

love
====

____
-- Do your thoughts go to the one you love, Your Majesty?

_Āgamā kho tvaṃ mahārāja yathāpemaṃ ti?_
____

[quote, D.1.50]
____
-- Bhante, Prince Udāyabhadda is dear to me.

_Piyo me bhante udāyibhaddo kumāro._
____

.Illustration
====
pemaṃ

affection
====

1. Affection is born from affection
+
****
_pemā pemaṃ jāyati_
****

2. Hatred is born from affection
+
****
_pemā doso jāyati_
****

3. Affection is born from hatred
+
****
_dosā pemaṃ jāyati_
****

4. Hatred is born from hatred
+
****
_dosā doso jāyati_
****

1. How is affection born from affection?
+
****
_pemā pemaṃ jāyati?_
****

____
In this regard, someone is likeable, loveable, and dear to another, so when 
others treat the former as likeable, loveable, and dear, the latter thinks: 'He 
who is to me likeable, loveable, and dear is treated by others as likeable, 
loveable, and dear' and he therefore evokes affection for them. Thus is 
affection born of affection.

_yo kho myāyaṃ puggalo iṭṭho kanto manāpo taṃ pare iṭṭhena 
kantena manāpena samudācarantī ti so tesu pemaṃ janeti._
____

2. How is hatred born from affection?
+
****
_Kathañca bhikkhave pemā doso jāyati?_
****

____
In this regard, someone is likeable, loveable, and dear to another, so when 
others treat the former as unlikeable, unloveable, and loathsome, the latter 
thinks: 'He who is to me likeable, loveable, and dear is treated by others as 
unlikeable, unloveable, and loathsome' and he therefore evokes hatred for them. 
Thus is hatred born of affection.

_yo kho myāyaṃ puggalo iṭṭho kanto manāpo taṃ pare aniṭṭhena 
akantena amanāpena samudācarantī ti. So tesu dosaṃ janeti._
____

3. How is affection born from hatred?
+
****
_Kathañca bhikkhave dosā pemaṃ jāyati_
****

____
In this regard, one person is unlikeable, unloveable, and loathsome to another 
person, so when others treat the former as unlikeable, unloveable, and 
loathsome, the latter thinks: 'He who is unlikeable, unloveable, and loathsome 
to me is treated by others as unlikeable, unloveable, and loathsome' and he 
therefore evokes affection for them. Thus is affection born of hatred.

_yo kho myāyaṃ puggalo aniṭṭho akanto amanāpo taṃ pare aniṭṭhena 
akantena amanāpena samudācarantī ti so tesu pemaṃ janeti._
____

4. How is hatred born from hatred?
+
****
_Kathañca bhikkhave dosā doso jāyati?_
****

[quote, A.2.213-4]
____
In this regard, one person is unlikeable, unloveable, and loathsome to another 
person, so when others treat the former as likeable, loveable, and dear, the 
latter thinks: 'He who is unlikeable, unloveable, and loathsome to me is 
treated by others as likeable, loveable, and dear' and he therefore evokes 
hatred for them. Thus is hatred born of hatred.

_yo kho myāyaṃ puggalo aniṭṭho akanto amanāpo taṃ pare iṭṭhena 
kantena manāpena samudācarantī ti. So tesu dosaṃ janeti._
____

.Illustration
====
pema

affection
====

[quote, M.1.141-2]
____
Those who have a degree of faith in me, a degree of affection for me, are all 
destined for heaven.

_yesaṃ mayi saddhāmattaṃ pemamattaṃ sabbe te saggaparāyaṇā ti._
____

.Illustration
====
pemaṃ

affection
====

____
The Blessed One has inspired in me

_ajanesi vata me bhante bhagavā samaṇesu_
____

____
an affection for ascetics

_samaṇapemaṃ_
____

____
faith in ascetics

_samaṇesu samaṇappasādaṃ_
____

[quote, M.1.368]
____
a respect for ascetics

_samaṇesu samaṇagāravaṃ._
____

.Illustration
====
pemaṃ

devotion
====

[quote, Vin.1.55]
____
There is profound devotion to and faith in his preceptor

_upajjhāyamhi adhimattaṃ pemaṃ hoti adhimatto pasādo hoti._
____

.Illustration
====
pemaṃ

devotion
====

[quote, D.3.284]
____
One lives in spiritual discipleship under the Teacher or a companion in the 
religious life of the standing of a teacher such that he is strongly 
established in shame of wrongdoing and fear of wrongdoing, in devotion and 
respect

_bhikkhu satthāraṃ vā upanissāya viharati aññataraṃ vā 
garuṭṭhāniyaṃ sabrahmacāraṃ yatthassa tibbaṃ hirottappaṃ 
paccupaṭṭhitaṃ hoti pemañca gāravo ca._
____

.Illustration
====
pemaṃ

devotion
====

[quote, M.1.448]
____
Out of devotion to and respect for the Blessed One, and out of shame and fear 
of wrongdoing, we abandoned the after noon meal.

_Te mayaṃ bhante bhagavati pemañca gāravañca hiriñca ottappañca 
sampassamānā evaṃ taṃ divāvikālabhojanaṃ pajahimhā._
____

.Illustration
====
pemo

dedication
====

____
A bhikkhu is keenly eager to undertake the training and his dedication to this 
does not dwindle away in the course of time

_sikkhāsamādāne tibbacchando hoti āyatiñca sikkhāsamādāne avigatapemo_
____

____
A bhikkhu is keenly eager to make a close study of the teaching and his 
dedication to this does not dwindle away in the course of time

_dhammanisantiyā tibbacchando hoti āyatiñca dhammanisantiyā avigatapemo_
____

[quote, D.3.252]
____
A bhikkhu is keenly eager to eliminate desire and his dedication to this does 
not dwindle away in the course of time

_icchāvinaye tibbacchando hoti āyatiñca icchāvinaye avigatapemo._
____

.Illustration
====
pemanīyo

lovely
====

[quote, A.4.263]
____
The music of the devas was beautiful, attractive, sensuous, lovely, and 
intoxicating.

_vaggu ca rajanīyo ca kamanīyo ca pemanīyo ca madanīyo ca._
____

.Illustration
====
pemanīyā

lovely
====

[quote, D.1.4]
____
He speaks words which are gentle, pleasant to hear, lovely...

_Yā sā vācā neḷā kaṇṇasukhā pemanīyā... tathārūpiṃ vācaṃ 
bhāsitā ti._
____

