== Phandana

=== Renderings

- _phandati_: to tremble

- _phandati_: to shimmer

- _phandati_: to thrash about

- _phandati_: to flicker

- _phandita_: spiritual unsteadiness

- _phandana_: unsteady

- _pariphandati_: to flutter about

- _pariphandamāna_: in turmoil

- _pariphandamāna_: quivering

=== Illustrations

.Illustration
====
pariphandamānaṃ

in turmoil; phandamāne, trembling
====

____
I see people in turmoil in the world, overcome by craving for states of 
individual existence, wretched characters wailing in the face of death, not 
free of craving for various states of individual existence.

_Passāmi loke pariphandamānaṃ pajaṃ imaṃ taṇhāgataṃ bhavesu +
Hīnā narā maccumukhe lapanti avītataṇhāse bhavābhavesu_
____

[quote, Sn.v.776-7]
____
Look at them, trembling amidst their cherished possessions, like fish in a 
dwindling stream._

_Mamāyite passatha phandamāne maccheva appodake khīṇasote._
____

.Illustration
====
phandati

trembles
====

[quote, S.1.174]
____
Again and again one suffers and trembles.

_Punappunaṃ kilamati phandati ca._
____

By comparison:

[quote, A.2.188]
____
Afflicted by the loss of relatives, or wealth, or health, he grieves, suffers, 
and laments, weeps beating his chest, and falls into bewilderment.

_So ñātivyasanena vā phuṭṭho samāno bhogavyasanena vā phuṭṭho 
samāno rogavyasanena vā phuṭṭho samāno socati kilamati paridevati 
urattāḷiṃ kandati sammohaṃ āpajjati._
____

.Illustration
====
phandamānaṃ

trembling
====

[quote, A.4.290]
____
He looks upon the trembling people, clinging to birth and old age.

_Pajaṃ jāti jarūpetaṃ phandamānaṃ avekkhatī ti._
____

.Illustration
====
phandante

tremble
====

[quote, Sn.v.587]
____
Living beings that tremble here having fallen under the power of death.

_Maccuno vasamāgamma phandante vidha pāṇino._
____

.Illustration
====
phandati

shimmer
====

[quote, S.3.141]
____
In the last month of the hot season, at high noon, a mirage is shimmering.

_gimhānaṃ pacchime māse ṭhite majjhantike kāle marici phandati._
____

.Illustration
====
phandamānaṃ

thrash about
====

[quote, Sn.v.936]
____
I saw people thrashing about like fish in a small pool, feuding with each 
other. Seeing this, I was filled with consternation.

_Phandamānaṃ pajaṃ disvā macche appodake yathā +
Aññamaññehi vyāruddhe disvā maṃ bhayamāvisi._
____

.Illustration
====
phandita

spiritual unsteadiness
====

• The notion "I am" is a matter of spiritual unsteadiness +
☸ _asmī ti_ phandita__metaṃ__

____
'I am this' is a matter of spiritual unsteadiness

_ayamahamasmī ti phanditametaṃ_
____

____
'I will be' is a matter of spiritual unsteadiness

_bhavissan ti phanditametaṃ_
____

____
'I will not be' is a matter of spiritual unsteadiness

_na bhavissan ti phanditametaṃ_
____

____
'I will be material' is a matter of spiritual unsteadiness

_rūpi bhavissanti phanditametaṃ_
____

____
'I will be immaterial' is a matter of spiritual unsteadiness

_arūpī bhavissan ti phanditametaṃ_
____

____
'I will be aware' is a matter of spiritual unsteadiness

_saññībhavissan ti phanditametaṃ_
____

____
'I will be unaware' is a matter of spiritual unsteadiness

_asaññī bhavissan ti phanditametaṃ_
____

____
'I will be neither aware nor unaware' is a matter of spiritual unsteadiness

_nevasaññināsaññī bhavissan ti phanditametaṃ_
____

[quote, S.4.203]
____
Spiritual unsteadiness is an illness, a carbuncle, a [piercing] arrow. 
Therefore train yourselves with the thought, 'We will live with minds taking 
delight in being free of spiritual unsteadiness.'

_phanditaṃ bhikkhave rogo phanditaṃ gaṇḍo phanditaṃ sallaṃ 
tasmātiha bhikkhave aphandamānena cetasā viharissāmāti evaṃ hi vo 
bhikkhave sikkhitabbaṃ._
____

.Illustration
====
vipphanditaṃ

spiritual unsteadiness
====

When he improperly contemplates in this way, one of six dogmatic views 
(_channaṃ diṭṭhīnaṃ aññatarā diṭṭhi uppajjati_) arises in him 
as real and actual (_saccato thetato_):

1. I have an [absolute] Selfhood
+
****
_atthi me attā ti_
****

2. I do not have an [absolute] Selfhood
+
****
_natthi me attā ti_
****

3. I perceive an [absolute] Selfhood with an [absolute] Selfhood
+
****
_attanā' va attānaṃ sañjānāmī ti_
****

4. I perceive what is not an [absolute] Selfhood with an [absolute] Selfhood
+
****
_attanā'va anattānaṃ sañjānāmī ti_
****

5. I perceive an [absolute] Selfhood with what is not an [absolute] Selfhood
+
****
_anattanā'va attānaṃ sañjānāmī ti_
****

• or else he has a view like this +
_atha vā pana'ssa evaṃ diṭṭhi hoti_

6. It is this [absolute] Selfhood of mine that speaks and experiences and feels 
here and there the karmic consequences of meritorious and demeritorious deeds; 
and this [absolute] Selfhood of mine is everlasting, enduring, eternal, of an 
unchangeable nature, and will endure like unto eternity itself.
+
****
_Yo me ayaṃ attā tatra tatra kalyāṇapāpakānaṃ kammānaṃ vipākaṃ 
paṭisaṃvedeti. So kho pana me ayaṃ attā nicco dhuvo sassato 
avipariṇāmadhammo sassatisamaṃ tatheva ṭhassatī ti._
****

____
This is called

_idaṃ vuccati bhikkhave_
____

____
acquiescence in dogmatism

_diṭṭhigataṃ_
____

____
the thicket of dogmatism,

_diṭṭhigahanaṃ_
____

____
the wilderness of dogmatism,

_diṭṭhikantāro_
____

____
the writhing of dogmatism,

_diṭṭhivisūkaṃ_
____

____
the spiritual unsteadiness of dogmatism,

_diṭṭhivipphanditaṃ_
____

[quote, M.1.8]
____
the bond of dogmatism

_diṭṭhisaṃyojanaṃ._
____

.Illustration
====
phandanaṃ

unsteady
====

[quote, Dh.v.33]
____
Like a fletcher straightens an arrow, the wise man straightens up his unsteady, 
fluttery mind, which is hard to supervise, hard to restrain.

_Phandanaṃ capalaṃ cittaṃ durakkhaṃ dunnivārayaṃ +
Ujuṃ karoti medhāvī usukāro va tejanaṃ._
____

.Illustration
====
phanditattaṃ

unsteadiness
====

[quote, S.5.316]
____
When inward collectedness by mindfulness with breathing has been developed and 
cultivated, no trembling or unsteadiness arises either in body or mind.

__ānāpānasatisamādhissa bhikkhave bhāvitattā bahulīkatattā neva 
kāyassa iñjitattaṃ vā hoti phanditattaṃ vā na cittassa iñjitattaṃ 
vā hoti phanditattaṃ vā._
____

.Illustration
====
pariphandati

flutter about
====

[quote, Dh.v.34]
____
Like a fish removed from its watery abode and thrown onto dry land, the mind 
flutters about in order to escape Māra's dominion.

_Vārijo va thale khitto okamokato ubbhato +
Pariphandatidaṃ cittaṃ māradheyyaṃ pahātave._
____

.Illustration
====
pariphandamāno

quivering
====

[quote, Sn.v.1145]
____
Lying quivering in the swamp, I floated from island to island.

_Paṅke sayāno pariphandamāno dipā dipaṃ upapalaviṃ._
____

.Illustration
====
phandati

flicker
====

[quote, Th.v.49]
____
Amidst the screeching of the birds and shrieking of the squirrels, this mind of 
mine does not flicker.

_Vihavihābhinadite sippikābhirutehi ca na me taṃ phandati cittaṃ._
____

