== Phassa

=== Renderings

- _phassa_: sensation

- _phassa_: tangible object (in poetry)

- _phassa_: physical sensation

=== Introduction

==== Phassa: sensation

_Phassa_ usually means 'sensation':

• When one is reborn, sensations affect one. +
☸ _upapannamenaṃ phassā phusanti_ M.1.390).

[quote, M.1.423]
____
Just as space is not established anywhere, Rāhula, likewise develop the 
meditation on space; for when you do so, arisen pleasing and displeasing 
sensations will not obsess your mind.

_seyyathā pi rāhula ākāso na katthaci patiṭṭhito evameva kho tvaṃ 
rāhula ākāsasamaṃ bhāvanaṃ bhāvehi. Ākāsasamaṃ hi te rāhula 
bhāvanaṃ bhāvayato uppannā manāpāmanāpā phassā cittaṃ na 
pariyādāya ṭhassanti._
____

==== Phassa: conjunction of three elements

In a technical sense, _phassa_ is the conjunction of three bases of sensation. 
We likewise call this 'sensation':

• Dependent on the visual sense and visible objects, advertence to the visual 
field arises. The association of the three is sensation. +
☸ _Cakkhuñca paṭicca rūpe ca uppajjati cakkhuviññāṇaṃ_. 
_Tiṇṇaṃ saṅgati phasso_ (S.2.72).

==== Phassa: relationship to vedanā

____
Bhikkhus, there are these three types of sense impression

_tisso imā bhikkhave vedanā_
____

____
which are born of sensation

_phassajā_
____

____
stem from sensation

_phassamūlakā_
____

____
are due to sensation

_phassanidānā_
____

____
arise dependent on sensation

_phassapaccayā_
____

What three?

____
pleasant sense impression

_sukhā vedanā_
____

____
unpleasant sense impression

_dukkhā vedanā_
____

[quote, S.4.215]
____
neutral sense impression

_adukkhamasukhā vedanā._
____

==== Six types of sensation

_Phassa_ is synonymous with _samphasso_, of which there are six types:

____
visual sensation

_cakkhusamphasso_
____

____
auditory sensation

_sotasamphasso_
____

____
olfactory sensation

_ghānasamphasso_
____

____
gustatory sensation

_jivhāsamphasso_
____

____
tactile sensation

_kāyasamphasso_
____

____
mental sensation

_manosamphasso_
____

==== In poetry: tangible object

In poetry, _phassa_ is used instead of _phoṭṭhabba._

[quote, S.4.75]
____
In feeling a tangible object

_phoṭṭhabbaṃ phusitvā._
____

[quote, Th.v.802]
____
When touched by a tangible object

_phassaṃ phussa._
____

[quote, S.4.71]
____
When touched by a tangible object

_Phassena phuṭṭho._
____

=== Illustrations

.Illustration
====
phassena

tangible object
====

[quote, S.4.71]
____
When touched by a tangible object do not be elated by pleasure. Do not tremble 
when touched by pain.

_Phassena phuṭṭho na sukhena majje dukkhena phuṭṭhopi na sampavedhe._
____

.Illustration
====
phassa

physical sensation
====

[quote, S.4.71]
____
Maintain detached awareness towards physical sensation, both pleasant and 
painful, not attracted or repelled by anything.

_Phassadvayaṃ sukhadukkhe upekkhe anānuruddho aviruddhakenaci._
____

Context:

_• Disvāna rūpāni manoramāni... Saddañca sutavā dubhayaṃ 
piyāppiyaṃ etc_

.Illustration
====
samphasso

sensation
====

____
Dependent on the visual sense and visible objects there arises advertence to 
the visual field...

_Cakkhuñca paṭicca rūpe uppajjati cakkhuviññāṇaṃ..._
____

____
The meeting, the encounter, the concurrence of these three things is called 
visual sensation...

_Yā kho bhikkhave imesaṃ tiṇṇaṃ dhammānaṃ saṅgati sannipāto 
samavāyo ayaṃ vuccati bhikkhave cakkhusamphasso..._
____

[quote, S.4.68]
____
With sensation one experiences, with sensation one perceives, with sensation 
one aspires.

_Phuṭṭho bhikkhave vedeti phuṭṭho sañjānāti phuṭṭho ceteti._
____

.Illustration
====
phasso

sensation
====

[quote, A.3.411]
____
Sensation is the basis for the arising of sensuous yearnings

_phasso bhikkhave kāmānaṃ nidānasambhavo._
____

.Illustration
====
phassā

sensations
====

[quote, M.1.390]
____
He is reborn in a hostile world where hostile sensations affect him and he 
experiences sense impression that is exclusively unpleasant, as experienced by 
the beings in hell.

_savyāpajjhaṃ lokaṃ upapajjati. Tamenaṃ savyāpajjhaṃ lokaṃ 
upapannaṃ samānaṃ savyāpajjhā phassā phusanti. So savyāpajjhehi 
phassehi phuṭṭho samāno savyāpajjhaṃ vedanaṃ vedeti ekantadukkhaṃ 
seyyathā pi sattā nerayikā._
____

.Illustration
====
phasso

sensation
====

____
When a bhikkhu has emerged from the attainment of the ending of perception and 
sense impression, sensations of three types affect him

_Saññāvedayitanirodhasamāpattiyā vuṭṭhitaṃ kho āvuso visākha 
bhikkhuṃ tayo phassā phusanti_
____

1. sensation that is void [of the perception of personal qualities] (cf. 
_suññamidaṃ attena vā attaniyena vā_, M.1.297-8).
+
****
_suññato phasso_
****

2. sensation that is void of the perception of abiding phenomena
+
****
_animitto phasso_
****

3. sensation that is void of aspiration
+
****
_appaṇihito phasso ti_ (M.1.302).
****

.Illustration
====
phassa

sensation
====

____
Because of diversity in the elements of sensation there is diversity in 
sensation.

_dhātunānattaṃ paṭicca uppajjati phassanānattaṃ_
____

[quote, D.3.289]
____
Because of diversity in sensation there is diversity in sense impression.

_phassanānattaṃ paṭicca uppajjati vedanānānattaṃ._
____

.Illustration
====
phassa

sensation
====

[quote, A.4.339]
____
Sensation is the origin of all things.

_phassasamudayā sabbe dhammā._
____

.Illustration
====
phassa

sensation
====

[quote, M.3.17]
____
Sensation is the indispensible and necessary condition by which the aggregates 
of sense impression, perception, and intentional activities are to be 
discerned._

_phasso hetu phasso paccayo vedanakkhandhassa... saññākkhandhassa... 
saṅkhārakkhandhassa paññāpanāya._
____

.Illustration
====
phassaṃ

sensation
====

____
Dependent on a sensation to be experienced as physically pleasant the faculty 
of physical pleasure arises._

_Sukhavedanīyaṃ bhikkhave phassaṃ paṭicca uppajjati sukhindriyaṃ_
____

____
Being physically pleased, he knows that: 'I am physically pleased.'

_So sukhito va samāno sukhitosmi ti pajānāti_
____

[quote, S.5.211]
____
He knows that: 'With the ending of that sensation to be experienced as 
physically pleasant, the corresponding sense impression -- the faculty of 
physical pleasure that arose dependent on that sensation to be experienced as 
physically pleasant -- ceases and subsides.

_Tasseva sukhavedanīyassa phassassa nirodhā yaṃ tajjaṃ vedayitaṃ 
sukhavedanīyaṃ phassaṃ paṭicca uppannaṃ sukhindriyaṃ taṃ 
nirujjhati._
____

.Illustration
====
samphassa

sensation
====

[quote, S.3.46-7]
____
When the ignorant Everyman is affected by sense impression born of sensation 
and uninsightfulness into reality the notion "I am" occurs to him.

_avijjāsamphassajena vedayitena phuṭṭhassa asmī ti pi'ssa hoti._
____

.Illustration
====
phassaṃ

sensation
====

[quote, S.4.213-4]
____
He knows that: 'There has arisen in me an unpleasant sense impression. Now that 
is dependent, not self-sufficient. Dependent on what? Dependent on sensation. 
But sensation is unlasting, originated, dependently arisen. So when an 
unpleasant sense impression has arisen dependent on sensation, which is 
unlasting, originated, dependently arisen, how could it be lasting?'

_so evaṃ pajānāti; uppannā kho myāyaṃ dukkhā vedanā sā ca kho 
paṭicca no apaṭicca kiṃ paṭicca: imameva phassaṃ paṭicca ayaṃ kho 
pana phasso anicco saṅkhato paṭiccasamuppanno aniccaṃ kho pana 
saṅkhataṃ paṭiccasamuppannaṃ phassaṃ paṭicca uppannā dukkhā 
vedanā kuto niccā bhavissatī ti._
____

.Illustration
====
phassa

sensation
====

[quote, Sn.v.870]
____
'Sensation is the source of the pleasing and displeasing. When there is no 
sensation, the pleasing and displeasing do not arise. Of the cessation and 
continuance of bodily forms, which I mentioned, I tell you that sensation is 
the source, too.'

_Phassanidānaṃ sātaṃ asātaṃ phasse asante na bhavanti hete +
Vibhavaṃ bhavañcāpi yametamatthaṃ etaṃ te pabrūmi itonidānaṃ._
____

.Illustration
====
phassa

sensation
====

____
And what is the faculty of physical pleasure? It is physical pleasure, physical 
pleasantness, pleasant and pleasing sense impression born of bodily sensation.

_yaṃ kho bhikkhave kāyikaṃ sukhaṃ kāyikaṃ sātaṃ 
kāyasamphassajaṃ sukhaṃ sātaṃ vedayitaṃ idaṃ vuccati bhikkhave 
sukhindriyaṃ._
____

[quote, S.5.211]
____
And what is the faculty of psychological pleasure? It is psychological 
pleasure, psychological pleasantness, pleasant and pleasing sense impression 
born of mental sensation:

_yaṃ kho bhikkhave cetasikaṃ sukhaṃ cetasikaṃ sātaṃ 
manosamphassajaṃ sukhaṃ sātaṃ vedayitaṃ idaṃ vuccati bhikkhave 
somanassindriyaṃ._
____

