== Piya

=== Renderings

- _piya_: agreeable

- _piya_: beloved

=== Introduction

==== Two spheres: sattā vā piyā, sankhārā vā piyā

PED accepts the two applications of _piya_ noted in the commentary, viz: _dve 
piyā: sattā vā piyā sankhārā vā piyā_, with reference to 1) living 
beings, 2) sensations.

We likewise recognise this division.

1. Beings are beloved or unbeloved.

2. Sense impression is agreeable or disagreeable.

In the context of ascetic renunciation, 'beloved' fits better than 'agreeable':

[quote, Sn.v.811]
____
The sage is not attached in any way. He does not hold anything as either 
beloved or unbeloved.

_Sabbattha muni anissito na piyaṃ kubbati no pi appiyaṃ._
____

[quote, Dh.v.211]
____
Therefore hold nothing beloved. Separation from the beloved is wretched.

_Tasmā piyaṃ na kayirātha piyāpāyo hi pāpako._
____

=== Illustrations

.Illustration
====
piyaṃ

agreeable
====

• I recall that for a long time I experienced the desirable, likeable, 
agreeable, and pleasing karmic consequences of meritorious deeds. +
_*☸* abhijānāmi kho panāhaṃ bhikkhave dīgharattaṃ katānaṃ 
puññānaṃ iṭṭhaṃ kantaṃ piyaṃ manāpaṃ vipākaṃ 
paccanubhūtaṃ_ (It.14-16).

.Illustration
====
piya

agreeable
====

[quote, A.2.72]
____
Taking delight in what is agreeable;

_piyarūpābhinandino._
____

.Illustration
====
piyarūpaṃ

agreeable
====

[quote, S.4.189]
____
So, too, whatever in the world [of phenomena] is agreeable and pleasing is 
called a thorn in the [terminology of the] Noble One's training system.

_evaṃ kho bhikkhave yaṃ loke piyarūpaṃ sātarūpaṃ ayaṃ vuccati 
ariyassa vinaye kaṇṭako._
____

.Illustration
====
piya

agreeable
====

[quote, Th.v.98]
____
In seeing a visible object with mindfulness muddled, focusing on the agreeable 
aspect,

_Rūpaṃ disvā sati muṭṭhā piyaṃ nimittaṃ manasikaroto._
____

.Illustration
====
piyarūpe

agreeable
====

[quote, M.1.266]
____
In seeing a visible object via the visual sense a bhikkhu is attached to an 
agreeable visible object and troubled by a disagreeable visible object.

_So cakkhunā rūpaṃ disvā piyarūpe rūpe sārajjati appiyarūpe rūpe 
vyāpajjati._
____

.Illustration
====
piyaṃ

agreeable
====

[quote, S.5.354]
____
If someone destroyed my well-being by lying to me it would not be agreeable and 
pleasing to me.

_yo kho me musāvādena atthaṃ bhañjeyya na me taṃ assa piyaṃ 
manāpaṃ._
____

.Illustration
====
piyaṃ

beloved
====

[quote, S.2.98]
____
Their only son, beloved and dear

_taṃ ekaputtakaṃ piyaṃ manāpaṃ._
____

.Illustration
====
piyaṃ

beloved
====

[quote, S.1.15]
____
Having abandoned the household life and gone forth [into the ascetic life], 
having abandoned their beloved sons and cattle

_Hitvā agāraṃ pabbajitā hitvā puttaṃ pasuṃ piyaṃ._
____

.Illustration
====
piyataro

more beloved
====

____
-- Is there, Mallikā, anyone more beloved to you than yourself?

_atthi nu kho te mallike ko cañño attanā piyataro ti?_
____

____
-- There is no one, great king, more beloved to me than myself. But is there 
anyone, great king, more beloved to you than yourself?

_Natthi kho me mahārāja ko cañño attanā piyataro. Tuyhaṃ pana mahārāja 
atthañño koci attanā piyataro ti?_
____

____
-- For me too, Mallikā, there is no one more beloved to me than myself.

_Mayhampi kho mallike natthañño koci attanā piyataroti._
____

Then the Blessed One... recited this verse:

____
Having traversed all quarters with the mind,

_Sabbā disā anuparigamma cetasā_
____

____
One finds nowhere anyone more beloved to oneself than oneself.

_Nevajjhagā piyataramattanā kvaci_
____

____
Others hold themselves likewise beloved;

_Evaṃ piyo puthu attā paresaṃ_
____

[quote, S.1.75]
____
Hence one who loves himself should not harm others.

_Tasmā na hiṃse paraṃ attakāmo ti._
____

.Illustration
====
piyassa

beloved
====

____
He has harmed, is harming, or will harm someone beloved and dear to me. 
Thinking thus, one arouses resentment.

_Piyassa me manāpassa anatthaṃ acarīti... caratīti... carissatīti 
āghātaṃ bandhati_
____

[quote, A.5.150; D.3.263]
____
He has benefited, is benefiting, or will benefit someone who is unbeloved or 
loathsome to me. Thinking thus, one arouses resentment.

_Appiyassa me amanāpassa atthaṃ acari... carati... carissatīti āghātaṃ 
bandhati._
____

.Illustration
====
piyāppiyaṃ

beloved or unbeloved
====

[quote, Th.v.671]
____
Those who have abandoned both sensuous yearning and anger, whose minds are at 
peace with all states of individual existence, live the religious life in the 
world unattached. Nothing is beloved or unbeloved for them.

_Kāmakopappahīnā ye santacittā bhavābhave +
Caranti loke asitā natthi tesaṃ piyāppiyaṃ._
____

