== Puthujjana

=== Renderings

- _puthujjana_: Everyman

- _puthujjana_: common man

=== Introduction

==== Puthujjana vs. ariyasāvaka

_Puthujjano_ usually occurs in the suttas as _assutavā puthujjano_, the 
ignorant Everyman. The _assutavā puthujjano_ is repeatedly contrasted with the 
learned noble disciple, _sutavā ariyasāvako_.

==== Puthujjana: options

Because _puthujjano_ usually occurs with an adjective like _assutavā_, 
rendering it as 'common man' or 'ordinary person' is avoided here, because it 
results in double adjectives. The _assutavā puthujjano_ would be an 'ignorant, 
ordinary person' or an 'ignorant, common man,' which are clumsy and 
condemnatory.

Words like 'commoner' or 'plebeian' are unuseable because they designate 
members of a lower social class, where _puthujjano_ implies averageness without 
implications of class.

==== Puthujjana: the Everyman

Everyman is the allegorical character in The Summoning of Everyman, a 15^th^ 
Century morality play in which the central figure represents the common man. 
The spelling is either 'everyman' or 'Everyman.' Capitalisation is chosen here 
because it emphasises the individuality of the ordinary man, his helplessness, 
and pitifulness.

==== Puthujjano: contexts without an adjective

Where _puthujjana_ occurs without an adjective, we render it 'common man.' As a 
plural we render it 'common men':

[quote, Th.v.575]
____
The foolish common men who cherish this [wretched human] body

_Yemaṃ kāyaṃ mamāyanti andhabālā puthujjanā._
____

==== The Summoning of Everyman: synopsis

The synopsis of the play _The Summoning of Everyman_ is this:

God commands Death to summon Everyman to make his final reckoning. Death allows 
Everyman a companion for the journey to speak for his virtues. Most of 
Everyman's friends refuse to accompany him, for example Fellowship, who 
represents Everyman's friends, and Kindred, who represents his family.

Goods refuses, saying that since Everyman was so devoted to gathering Goods, 
but never shared them, Goods' presence would make God's judgement more severe.

Good Deeds says she is too weak to go because Everyman has never appreciated 
her. But, in the presence of Confession, Everyman repents of his sins, and as a 
result, Good Deeds becomes strong enough to accompany him on his final journey. 
Everyman then climbs into his grave with Good Deeds. They ascend into heaven 
where they are warmly welcomed.

The play closes with the Doctor, representing a scholar, explaining the moral: 
in the end, man will only have Good Deeds to accompany him beyond the grave.

About the author of the play, nothing is known.

=== Illustrations

.Illustration
====
Everyman

[quote

S.4.207]
====

____
When the ignorant Everyman is affected by unpleasant bodily sense impression, 
he grieves, suffers, and laments, weeps beating his chest, and falls into 
bewilderment. This is called the ignorant Everyman who has not risen up in the 
bottomless abyss, one who has not gained a foothold.

_Assutavā bhikkhave puthujjano sārīrikāya dukkhāya vedanāya phuṭṭho 
samāno socati kilamati paridevati urattāḷiṃ kandati sammohaṃ āpajjati. 
Ayaṃ vuccati bhikkhave assutavā puthujjano pātāle na paccuṭṭhāsi 
gādhañca nājajhagā._
____

.Illustration
====
Everyman

[quote

M.1.8]
====

____
The ignorant Everyman is not freed from birth, old age, and death, from grief, 
lamentation, physical pain, psychological pain, and vexation. He is not freed, 
I declare, from suffering.

_assutavā puthujjano na parimuccati jātiyā jarāmaraṇena sokehi paridevehi 
dukkhehi domanassehi upāyāsehi na parimuccati dukkhasmā ti vadāmi._
____

.Illustration
====
Everyman

• Engaged in sensuous quests

the ignorant Everyman conducts himself wrongly in three ways: by body, speech, 
and mind. +
====

_Kāmapariyesanaṃ bhikkhave pariyesamāno assutavā puthujjano tīhi 
ṭhānehi micchā paṭipajjati: kāyena vācāya manasā_ (S.2.152).

.Illustration
====
Everyman

• The ignorant Everyman has no faith in the Buddha. When he considers within 
himself that lack of faith in the Buddha

there is fright, trepidation, and fear of death and the future life. +
====

_assutavā puthujjano buddhe appasādena samannāgato hoti. Tañca panassa 
buddhe appasādaṃ attani samanupassato hoti uttāso hoti chambhitattaṃ hoti 
samparāyikaṃ maraṇabhayaṃ_ (S.5.386).

.Illustration
====
Everyman

[quote

S.4.286-7]
====

____
The ignorant Everyman, who has no regard for the Noble Ones or for spiritually 
outstanding people, and who is ignorant of and uninstructed in their teaching, 
considers bodily form to be the [absolute] Selfhood.

_Assutavā puthujjano ariyānaṃ adassāvī ariyadhammassa akovido ariyadhamme 
avinīto sappurisānaṃ adassāvī sappurisadhammassa akovido sappurisadhamme 
avinīto rūpaṃ attato samanupassati._
____

.Illustration
====
Everyman

[quote

S.3.139-40]
====

____
When [bodily form] has been explained, taught, proclaimed, established, 
disclosed, analysed, and elucidated by the Perfect One, whoever does not know 
or see it [according to reality], what can I do with that foolish, blind, 
sightless, unknowing, unseeing Everyman?

_Yo bhikkhave tathāgatena evaṃ ācikkhiyamāne desiyamāne paññāpiyamāne 
paṭṭhapiyamāne vivariyamāne vibhajiyamāne uttānīkayiramāne na 
jānāti na passati tamahaṃ bhikkhave bālaṃ puthujjanaṃ andhaṃ 
acakkhukaṃ ajānantaṃ apassantaṃ kinti karomī._
____

.Illustration
====
Everyman

[quote

S.4.196]
====

____
The ignorant Everyman does not restrain the six senses [from attraction and 
repulsion, through mindfulness]; he indulges himself as much as he likes in the 
five varieties of sensuous pleasure.

_assutavā puthujjano chasu phassāyatanesu asaṃvutakārī pañcasu 
kāmaguṇesu yāvadatthaṃ madaṃ āpajjati._
____

.Illustration
====
common man

[quote

Vin.1.10]
====

____
The pursuit of sensuous pleasures, which is low, vulgar, the way of the common 
man, ignoble, and unconducive to spiritual well-being.

_yo cāyaṃ kāmesu kāmasukhallikānuyogo hīno gammo pothujjaniko anariyo 
anatthasaṃhito._
____

.Illustration
====
common man

[quote

S.3.109]
====

____
'The man ignorant of the path' represents the common man.

_puriso amaggakusalo ti kho tissa puthujjanassetaṃ adhivacanaṃ._
____

.Illustration
====
common man

[quote

S.3.225]
====

____
One who has faith in [the significance of] these teachings and is intent on 
them is called a 'faith follower,' one who has entered the way of rightness 
&#8203;[comprised of spiritually wholesome factors], entered the plane of spiritually 
outstanding people, transcended the plane of the common man.

_Yo bhikkhave ime dhamme evaṃ saddahati adhivuccati ayaṃ vuccati 
saddhānusārī okkanto sammattaniyāmaṃ sappurisabhumiṃ okkanto vītivatto 
puthujjanabhumiṃ._
____

.Illustration
====
common man

[quote

Sn.v.820]
====

____
Whoever formerly fared alone who then pursues sexual intercourse, in the world 
is called a 'lurching vehicle,' 'contemptible,' a 'common man.'

_Eko pubbe caritvāna methunaṃ yo nisevati +
Yānaṃ bhantaṃ va taṃ loke hīnamāhu puthujjanaṃ._
____

.Illustration
====
common man

[quote

M.3.114]
====

____
I will not think those kinds of thought which are low, vulgar, the way of the 
common man, ignoble, and unconducive to spiritual well-being.

_ye te vitakkā hīnā gammā pothujjanikā anariyā anatthasaṃhitā... iti 
evarūpe vitakke na vitakkessāmī ti._
____

