== Pāpaka; Pāpa

=== Renderings

- _pāpa_: demerit/accumulated demerit

- _pāpa_: unvirtuousness

- _pāpa_/_pāpaka_: demeritorious

- _pāpa_/_pāpaka_ unvirtuous

- _pāpa/pāpaka_: wretched

- _pāpa/pāpaka_: odious

- _pāpakammina_: evildoer

- _pāpimant_: the Maleficent One

=== Introduction

==== Pāpaka: -ka suffix

The -_ka_ suffix of _pāpaka_ is in accordance with Duroiselle's observation: 
'Not seldom -_ka_ adds nothing whatever to the primary meaning of a word ' 
(PGPL, Para 581). DOP agrees (sv _Ka2_).

==== Pāpa and pāpaka: schedule of renderings

Our schedule of renderings is as follows:

1. Where _pāpa_ is antonymous to _puñña_ we call it 'demerit':
+
[quote, S.1.182]
____
He in this world who lives the religious life having spurned [the accumulating 
of] merit and demerit.

_Yodha puññañca pāpañca bāhetvā brahmacariyavā._
____

2. In the context of karmically consequential conduct, where _pāpaka_ is 
antonymous to _kalyāṇa_ we call it 'demeritorious':
+
[quote, A.3.185]
____
He is the inheritor of whatever karmically consequential conduct he undertakes 
whether meritorious or demeritorious.

_Yaṃ kammaṃ karissati kalyāṇaṃ vā pāpakaṃ vā tassa dāyādo 
bhavissatī ti._
____

3. Where _pāpaka_ is synonymous with _akusala_ we call it 'unvirtuous':
+
[quote, M.1.119]
____
When contemplating an object that arouses unvirtuous, spiritually unwholesome 
thoughts (_pāpakā akusalā vitakkā_), a bhikkhu should ponder a meditation 
object connected with what is spiritually wholesome (_aññaṃ nimittaṃ 
manasikātabbaṃ kusalūpasaṃhitaṃ_).
____

4. Where _pāpaka_ is antonymous to _bhaddaka_ and implies a bad inner nature 
we call it 'odious.'
+
[quote, A.5.212-213]
____
Whatever a bitter gourd seed absorbs leads to bitterness, acridity, and 
unpleasant taste. For what reason? The seed is odious (_bījaṃ hi bhikkhave 
pāpakaṃ_).

Whatever a sugar-cane seed absorbs leads to sweetness, pleasantness and 
delicious flavour. For what reason? The seed is excellent (_bījaṃ hi 
bhikkhave bhaddakaṃ_).
____

5. In relation to _diṭṭhi_, where _pāpika_ is antonymous to _bhaddakaṃ_ 
we call it 'odious':
+
[quote, A.5.212]
____
his view [of reality] is odious

_diṭṭhi hi bhikkhave pāpikā_

his perception [of reality] is excellent

_diṭṭhi hi bhikkhave bhaddikā._
____

6. Where _pāpaka_ means unpleasant we call it 'wretched.'
+
[quote, Vin.3.73]
____
what use to you is this wretched and difficult life?

_kiṃ tuyhaminā pāpakena dujjīvitena._
____

7. In reference to friends we call it 'unvirtuous.'
+
[quote, S.1.83]
____
King Ajātasattu of Magadha has unvirtuous friends (_ajātasattu vedehiputto 
pāpamitto_). King Pasenadi of Kosala has virtuous friends (_pasenadi kosalo 
kalyāṇamitto_).
____

8. When it implies unvirtuous behaviour we call it 'unvirtuous.'
+
[quote, Vin.2.203]
____
free of unvirtuous conduct

_pāpakammaṃ akubbato._
____
+
[quote, A.2.222]
____
What is unvirtuous? In this regard, some person kills

_Katamo ca bhikkhave pāpo? Idha bhikkhave ekacco pāṇātipātī hoti._
____

9. Similarly, where _pāpaka_ is antonymous to _kalyāṇa_ and implies bad 
practices, we call it 'unvirtuous.'
+
[quote, M.3.255-6]
____
unvirtuous, of an unvirtuous moral nature

_dussīlā pāpadhammā._
____
+
[quote, S.5.397]
____
virtuous and of a virtuous moral nature.

_sīlavantehi kalyāṇadhammehī ti._
____

10. When it describes someone who is unvirtuous we call it 'unvirtuous.' Thus 
an unvirtuous bhikkhu is unvirtuous (_pāpabhikkhu dussīlo_ A.2.239).

11. As a word of condemnation, we call it 'odious.'
+
[quote, Vin.4.259]
____
excessive greed is odious

_atilobho hi pāpako._
____

12. Māra's epithet is _pāpimant_, 'the Maleficent One.'

=== Illustrations: pāpa

.Illustration
====
pāpaṃ

demerit
====

[quote, S.4.348]
____
If, with a razor-rimmed wheel, one were to make the living beings of this earth 
into one mass of flesh, into one heap of flesh, because of this there would be 
demerit and an outcome of demerit.

_Khurapariyantena cepi cakkena yo imissā paṭhaviyā pāṇe ekaṃ 
maṃsakhalaṃ ekaṃ maṃsapuñjaṃ kareyya atthi tatonidānaṃ pāpaṃ 
atthi pāpassa āgamo._
____

.Illustration
====
pāpaṃ

demerit
====

____
If one were to go along the south bank of the Ganges killing and 
slaughtering... because of this there would be demerit and an outcome of 
demerit.

_atthi tatonidānaṃ pāpaṃ atthi pāpassa āgamo_
____

[quote, S.4.348]
____
If one were to go along the north bank of the Ganges giving gifts and making 
others give gifts... because of this there would be merit and an outcome of 
merit.

_atthi tatonidānaṃ puññaṃ atthi puññassa āgamo._
____

.Illustration
====
pāpaṃ

demerit
====

[quote, Th.v.81]
____
Whatever demerit was formerly generated by me in other lifetimes, that must be 
experienced now [in this lifetime].

_Yaṃ mayā pakataṃ pāpaṃ pubbe aññāsu jātisu; Idheva taṃ 
vedanīyaṃ._
____

.Illustration
====
pāpaṃ

demerit
====

[quote, S.1.182]
____
He in this world who lives the religious life having spurned [the accumulating 
of] merit and demerit, who fares in the world with reflectiveness, he is truly 
called a bhikkhu.

_Yodha puññañca pāpañca bāhetvā brahmacariyavā +
Saṅkhāya loke carati sa ve bhikkhū ti vuccati._
____

.Illustration
====
pāpaṃ

demerit
====

[quote, Dh.v.161]
____
Demerit generated by his ego, born from his ego, arisen from his ego, crushes 
the fool like a diamond crushes a hard gem.

_Attanā va kataṃ pāpaṃ attajaṃ attasambhavaṃ +
Abhimanthati dummedhaṃ vajiraṃ v'asmamayaṃ maṇiṃ._
____

.Illustration
====
pāpaṃ

something demeritorious
====

[quote, Thī.v.431]
____
Something demeritorious has been done by me. I shall destroy that accumulated 
demerit.

_Pāpaṃ hi mayā pakataṃ kammaṃ taṃ nijjaressāmi._
____

.Illustration
====
pāpaṃ

what is unvirtuous; pāpassa, demerit
====

____
Should a person do what is unvirtuous, he should not do it again and again. He 
should not develop a fondness for it. The accumulation of demerit is suffering.

_Pāpaṃ ce puriso kayirā na taṃ kayirā punappunaṃ +
Na tamhi chandaṃ kayirātha dukkho pāpassa uccayo._
____

[quote, Dh.v.117-8]
____
Should a person do what is meritorious, he should do it again and again. He 
should develop a fondness for it. The accumulation of merit is happiness.

_Puññaṃ ce puriso kayirā kayirāthetaṃ punappunaṃ +
Tamhi chandaṃ kayirātha sukho puññassa uccayo._
____

.Illustration
====
pāpaṃ

unvirtuous; pāpaṃ, demerit
====

[quote, Vin.2.203]
____
He who injures someone who is pure, free of unvirtuous conduct, the demerit 
affects him himself, the one with a defiled mind, with no respect [for others].

_Aduṭṭhassa hi yo dubbhe pāpakammaṃ akubbato; +
Tameva pāpaṃ phusati duṭṭhacittaṃ anādaraṃ._
____

.Illustration
====
pāpa

demerit
====

[quote, Th.v.348]
____
I have [now] cleansed away all demerit.

_Ninhātasabbapāpomhi._
____

.Illustration
====
pāpaṃ

unvirtuousness
====

• Seeing unvirtuousness as unvirtuous, become in that respect disillusioned, 
unattached, and liberated. +
_Pāpaṃ pāpakato disvā tattha nibbindatha virajjatha vimuccathā ti_ 
(It.33).

.Illustration
====
pāpa

unvirtuous
====

[quote, A.5.136]
____
Unvirtuous friendship is an obstacle to virtuous practices.

_pāpamittatā sīlānaṃ paripantho._
____

[quote, A.5.136]
____
Virtuous friendship is a condition that nourishes virtuous practices.

_kalyāṇamittatā sīlānaṃ āhāro._
____

.Illustration
====
pāpo

unvirtuous
====

____
What is unvirtuous?

_Katamo ca bhikkhave pāpo?_
____

____
In this regard, some person

_Idha bhikkhave ekacco_
____

____
kills

_pāṇātipātī hoti_
____

____
steals

_adinnādāyī hoti_
____

____
commits adultery

_kāmesu micchācārī hoti_
____

____
lies

_musāvādī hoti_
____

____
speaks maliciously, harshly or frivolous chatter

_pisunāvāco hoti... pharusāvāco hoti... samphappalāpī hoti_
____

____
is greedy

_abhijjhālu hoti_
____

____
has an unbenevolent attitude

_vyāpannacitto hoti_
____

[quote, A.2.222]
____
is of wrong view [of reality]

_micchādiṭṭhi hoti._
____

Comment:

This occurs in a group of four definitions:

1. What is unvirtuous?
+
****
_Katamo ca bhikkhave pāpo? Idha bhikkhave ekacco pāṇātipātī hoti... 
Micchādiṭṭhiko hoti._
****

2. What is worse than unvirtuousness?
+
****
_Katamo ca bhikkhave pāpena pāpataro? Idha bhikkhave ekacco attanā ca 
pāṇātipātī hoti. Parañca pāṇātipāte samādapeti... Attanā ca 
micchādiṭṭhiko hoti parañca micchādiṭṭhiyā samādapeti. Ayaṃ 
vuccati bhikkhave pāpena pāpataro._
****

3. What is virtuous?
+
****
_Katamo ca bhikkhave kalyāṇo? Idha bhikkhave ekacco pāṇātipātā 
paṭivirato hoti... sammādiṭṭhiko hoti._
****

4. What is better than virtuousness?
+
****
_Katamo ca bhikkhave kalyāṇena kalyāṇataro? Idha bhikkhave ekacco attanā 
ca pāṇātipātā paṭivirato hoti parañca pāṇātipātā veramaṇiyā 
samādapeti... Attanā ca sammādiṭṭhiko hoti parañca sammādiṭṭhiyā 
samādapeti._
****

.Illustration
====
pāpa

unvirtuous
====

[quote, M.3.255-6]
____
In future times, Ānanda, there will be members of the clan with an ochre robe 
round their necks, unvirtuous, of an unvirtuous moral nature.

_Bhavissanti kho panānanda anāgatamaddhānaṃ gotrabhuno kāsāvakaṇṭhā 
dussīlā pāpadhammā._
____

Comment:

The opposite of _dussīlā pāpadhammā_ is _sīlavantehi kalyāṇadhammehī_:

[quote, S.5.397]
____
Whatever there is in my family that is suitable for offering, all that I share 
unreservedly with those who are virtuous and of a virtuous moral nature.

_Yaṃ kho pana kiñci kule deyyadhammaṃ sabbaṃ taṃ appaṭivibhattaṃ 
sīlavantehi kalyāṇadhammehī ti._
____

.Illustration
====
pāpa

unvirtuous
====

[quote, A.2.239]
____
An unvirtuous bhikkhu is unvirtuous, of an unvirtuous moral nature, impure.

_pāpabhikkhu dussīlo hoti pāpadhammo asuci._
____

.Illustration
====
pāpa

odious
====

[quote, M.2.222]
____
If the pleasure and pain that beings feel are caused by fate and destiny, 
certainly the Nigaṇṭhas are of an odious fate and destiny in that they 
experience such unpleasant, racking, piercing sensations.

_Sace bhikkhave sattā saṅgatibhāvahetu sukhadukkhaṃ paṭisaṃvedenti 
addhā bhikkhave nigaṇṭhā pāpasaṅgatikā yaṃ etarahi evarūpā 
dukkhā tibbā kaṭukā vedanā vediyanti._
____

.Illustration
====
pāpa

odious
====

[quote, A.2.23]
____
He maintains an odious dogmatic view.

_pāpadiṭṭhi._
____

=== Illustrations: pāpaka

.Illustration
====
pāpakānaṃ

demeritorious
====

[quote, M.1.8]
____
Experiences here and there the karmic consequences of meritorious and 
demeritorious deeds

_tatra tatra kalyāṇapāpakānaṃ kammānaṃ vipākaṃ paṭisaṃvedeti._
____

.Illustration
====
pāpakaṃ

demeritorious
====

[quote, A.3.185]
____
He is the inheritor of whatever karmically consequential conduct he undertakes 
whether meritorious or demeritorious.

_Yaṃ kammaṃ karissati kalyāṇaṃ vā pāpakaṃ vā tassa dāyādo 
bhavissatī ti._
____

.Illustration
====
pāpikānaṃ

unvirtuous
====

[quote, M.1.95]
____
In this regard a bhikkhu has unvirtuous desires and is dominated by unvirtuous 
desires.

_Idhāvuso bhikkhu pāpiccho hoti pāpikānaṃ icchānaṃ vasaṃ gato._
____

.Illustration
====
pāpakā

unvirtuous
====

[quote, A.3.306-8]
____
Are there any unvirtuous, spiritually unwholesome factors unabandoned by me 
which, were I to die tonight, would be a spiritual obstruction to me?

_atthi nu kho me pāpakā akusalā dhammā appahīnā ye me assu rattiṃ 
kālaṃ karontassa antarāyāyā ti._
____

.Illustration
====
pāpake

unvirtuous
====

[quote, S.1.197]
____
A certain bhikkhu had gone for his daytime abiding, but kept thinking 
unvirtuous, spiritually unwholesome thoughts associated with the household life.

_pāpake akusale vitakke vitakketi gehanissite._
____

.Illustration
====
pāpakaṃ

unvirtuous
====

[quote, Sn.v.230-232]
____
Although he may do an unvirtuous deed by body, speech, or mind, he is incapable 
of hiding it.

_Kiñcāpi so kammaṃ karoti pāpakaṃ kāyena vācā uda cetasā vā +
Abhabbo so tassa paṭicchādāya._
____

.Illustration
====
pāpakaṃ

unvirtuous
====

[quote, M.1.127]
____
Neither shall our minds be worsened by this, nor shall we utter unvirtuous words

_na ceva no cittaṃ vipariṇataṃ bhavissati. Na ca pāpakaṃ vācaṃ 
nicchāressāma._
____

.Illustration
====
pāpikaṃ

unvirtuous
====

[quote, A.2.143]
____
He conceives an unvirtuous desire for respect, for gains, honour, and renown

_pāpikaṃ icchaṃ panidahati anavaññapaṭilābhāya 
lābhasakkārasilokapaṭilābhāya._
____

.Illustration
====
pāpako

unvirtuous
====

[quote, M.1.15]
____
Greed is unvirtuous, and hatred is unvirtuous

_lobho ca pāpako doso ca pāpako._
____

.Illustration
====
pāpako

odious, pāpa, unvirtuous
====

[quote, A.1.126-7]
____
Someone who is unvirtuous (_dussīlo_) should be shunned. Why so? Because one 
gains an odious reputation of having unvirtuous friends, companions, and 
comrades.

_pāpako kittisaddo abbhuggacchati pāpamitto purisapuggalo pāpasahāyo 
pāpasampavaṅko ti._
____

.Illustration
====
pāpako

odious
====

[quote, Vin.4.259]
____
One should be pleased with what is received, for excessive greed is odious.

_Yaṃ laddhaṃ tena tuṭṭhabbaṃ atilobho hi pāpako._
____

.Illustration
====
pāpakaṃ

odious
====

- Whatever a bitter gourd seed absorbs leads to its bitterness, acridity, and 
unpleasant taste. For what reason? The seed is odious (_bījaṃ hi bhikkhave 
pāpakaṃ_) (A.5.212).

- Whatever a sugar-cane seed absorbs leads to its sweetness, pleasantness and 
delicious flavour. For what reason? The seed is excellent (_bījaṃ hi 
bhikkhave bhaddakaṃ_) (A.5.213).

.Illustration
====
pāpako

odious
====

When the yakkha Sūciloma pressed his body, the Buddha said he was not afraid, 
saying:

[quote, Sn.p.48]
____
'But your touch is odious.'

_api ca te samphasso pāpako ti._
____

.Illustration
====
pāpakaṃ

odious
====

• One sees no odious dreams. +
☸ _Na pāpakaṃ supinaṃ passati..._ Vin.1.295).

.Illustration
====
pāpakaṃ

odious
====

[quote, M.1.257]
____
Odious dogmatic views,

_pāpakaṃ diṭṭhigataṃ._
____

.Illustration
====
pāpakā

odious
====

[quote, M.1.257]
____
We were unable to wean the bhikkhu Sāti from this odious dogmatic view.

_mayaṃ bhante nāsakkhimha sātiṃ bhikkhuṃ kevaṭṭaputtaṃ etasmā 
pāpakā diṭṭhigatā vivecetuṃ._
____

.Illustration
====
pāpakena

wretched
====

[quote, Vin.3.73]
____
My good fellow, what use to you is this wretched and difficult life? Death for 
you is better than life.

_ambho purisa kiṃ tuyhaminā pāpakena dujjīvitena matante jīvitā seyyo 
ti._
____

.Illustration
====
pāpako

wretched
====

[quote, Th.v.146]
____
While performing unvirtuous deeds the fool does not realise that later it will 
be bitter for him. The karmic consequence will be truly wretched.

_Atha pāpāni kammāni karaṃ bālo na bujjhati +
Pacchāssa kaṭukaṃ hoti vipāko hissa pāpako ti._
____

.Illustration
====
pāpako

wretched
====

[quote, Dh.v.211]
____
Therefore hold nothing beloved: separation from the beloved is wretched.

_Tasmā piyaṃ na kayirātha piyāpāyo hi pāpako._
____

.Illustration
====
pāpako

wretched
====

[quote, A.5.252]
____
The karmic consequence of killing is wretched.

_pāṇātipātassa kho pāpako vipāko._
____

.Illustration
====
pāpakamminaṃ

evildoer
====

[quote, M.1.39]
____
What can the Sundarikā River do? What the Payāga? What the Bāhukā? They 
cannot purify a hostile man, a wrongdoer, an evildoer.

_Kiṃ sundarikā karissati kiṃ payāgo kiṃ bāhukā nadī +
Veriṃ katakibbisaṃ naraṃ na hi naṃ sodhaye pāpakamminaṃ._
____

=== Illustrations: pāpimato

.Illustration
====
pāpimato

the Maleficent One
====

• By taking delight in bodily form one is held captive by Māra. By not 
taking delight in it one is freed from the Maleficent One. +
_Rūpaṃ kho bhante abhinandamāno baddho mārassa anabhinandamāno mutto 
pāpimato_ (S.3.75).

