== Pāragata; Pāragū

=== Renderings

- _pāragū_: reached the Far Shore

- _pāragū_: reached the far shore

- _pāragū_: gone beyond (something)

- _pāragū_: master (of the three Vedas)

- _pāragato_: reached the Far Shore

=== Introduction

==== 'Far Shore': nibbāna

[quote, Sn.v.1130]
____
'Far Shore' (_pāraṃ_) means _nibbāna_. The _Pārāyanavaggo_ indicates this 
when it says one would go from the Near Shore to the Far Shore if one developed 
the Supreme Way.

_Apārā pāraṃ gaccheyya bhāvento maggamuttamaṃ._
____

==== 'Near Shore': personal identity?

The (capitalised) 'Near Shore' likely means personal identity, because the 
simile in the _Āsivisopama Sutta_ (S.4.172) says the near shore of a great 
expanse of water (_orimaṃ tīraṃ_) is a metaphor for personal identity 
(_sakkāyassetaṃ adhivacanaṃ_) and the far shore (_pārimaṃ tīraṃ_) is 
a metaphor for Nibbāna (_nibbānassetaṃ adhivacanaṃ_).

==== Arahant: pāragato or pāragū

Therefore, because he has attained to Nibbāna, the arahant is 'one who has 
reached the Far Shore,' either _pāragato_ (S.4.157) or _pāragū_ (Sn.v.372).

==== Pāraṅgata vs. Pāragata

_Pāraṅgata_ and _pāragata_ stem from _paraṃ_ and _para_. PED explains the 
words as synonyms, as follows:

- _Pāragata_: 'one who has reached the opposite shore.'

- _Pāraṅgata_: 'gone to the other side, gone beyond, traversed, transcended.'

Pāli versions disagree on the spelling. For example, VRI usually spells 
_pāraṅgata_ and commonly ascribes _pāragata_ to BJT, as follows:

1. _pāraṅgato_ [_pāragato_ (sī. syā. kaṃ.)] (S.4.174).

2. _pāraṅgato_ [pāragato (sī. syā. kaṃ.)] (A.2.5).

3. _pāraṅgato_ [_pāragato_ (sī. syā. kaṃ.)] (A.4.11).

4. _pāraṅgatā_ [_pāragatā_ (sī. syā. pī.)] (A.4.228).

5. _pāraṅgatā_ [_pāragatā_ (ka. sī. syā.)] (It.50).

6. _tiṇṇo pāraṅgato_ [_pāragato_ (sī. aṭṭha. syā.)] (It.57).

However, VRI itself occasionally spells _pāragata_. For example, in 
combination with _tiṇṇo_, the ratio is 11:2 as follows:

1. _tiṇṇaṃ pāraṅgataṃ_ (Sn.v.359).

2. _tiṇṇā pāraṅgatā_ (A.4.411).

3. _tiṇṇo pāraṅgato_ (M.2.196).

4. _tiṇṇo pāraṅgato_ (S.4.156).

5. _tiṇṇo pāraṅgato_ (S.4.174).

6. _tiṇṇo pāraṅgato_ (S.4.175).

7. _tiṇṇo pāraṅgato_ (A.2.5).

8. _tiṇṇo hoti pāraṅgato_ (A.4.11).

9. _tiṇṇo pāraṅgato_ (It.57).

\10) _tiṇṇo pāraṅgato_ (Sn.v.638).

\11) _tiṇṇo pāraṅgato_ (Th.v.680).

1. _tiṇṇo pāragato_ (Dh.v.414).

2. _tiṇṇo pāragato_ (Sn.v.21).

On the basis of these findings, we normalise spellings in the Glossary and in 
our translations to _pāragato_.

==== Pāraguṃ and pāragū: qualified

Where _pāraguṃ_ and _pāragū_ are qualified they still indicate 
arahantship, and should be rendered as 'gone beyond [something]' For example:

_• pāragū dukkhassa_: gone beyond suffering (Sn.v.539).

_• jātimaraṇassa pāragā_: gone beyond birth and death (S.4.71).

==== Pāragū: master (of the three Vedas)

_Pāragū_ can also mean that a brahman scholar is 'master' of the three Vedas: 
_tiṇṇaṃ vedānaṃ pāragū_ (A.1.163).

=== Illustrations

.Illustration
====
pāragū

one who reaches the far shore
====

[quote, Sn.v.771]
____
So a person, being ever mindful, should avoid sensuous pleasures. Having 
forsaken them he would cross the flood [of suffering] like one, having bailed a 
boat, who reaches the far shore.

_Tasmā jantu sadā sato kāmāni parivajjaye +
Te pahāya tare oghaṃ nāvaṃ sitvāva pāragū ti._
____

.Illustration
====
pāragato

reached the far shore
====

[quote, S.1.48]
____
As long as he has not gained firm ground whilst [crossing] a river, a man 
strains with all his limbs. But on gaining firm ground, standing on the shore, 
he does not strain for he has reached the far shore.

_Yāva na gādhaṃ labhati nadīsu āyūhati sabbagattehi jantu +
Gādhañca laddhāna thale ṭhito so nāyūhati pāragato hi soti._
____

.Illustration
====
pāragato

reached the Far Shore
====

[quote, S.1.48]
____
Having reached the end of birth and death, he does not strain for he has 
reached the Far Shore.

_pappuyya jātimaraṇassa antaṃ nāyūhati pāragato hi so ti._
____

.Illustration
====
pāragato

reached the Far Shore
====

____
He is blessed with profound knowledge. He has fulfilled the religious life.

_Sa vedagū vusitabrahmacariyo_
____

[quote, S.4.157]
____
He is called one who has reached the end of the world [of phenomena], one who 
has reached the Far Shore.

_Lokantagū pāragato ti vuccatī ti._
____

.Illustration
====
pāragato

reached the Far Shore
====

[quote, Sn.v.21]
____
I have crossed [to the Far Shore], reached the Far Shore, having eliminated the 
flood [of suffering].

_tiṇṇo pāragato vineyya oghaṃ._
____

.Illustration
====
pāragū

gone beyond
====

[quote, Sn.v.539]
____
You have reached the end of suffering, gone beyond suffering.

_antagūsi pāragū dukkhassa._
____

.Illustration
====
pāragā

gone beyond
====

____
Having vanquished both attachment and hatred

_te rāgadose abhibhuyya bhikkhavo_
____

[quote, S.4.71]
____
Be those who have gone beyond birth and death.

_bhavātha jātimaraṇassa pāragā ti._
____

.Illustration
====
pāragū

gone beyond
====

[quote, A.2.15]
____
They are unattached; they have gone beyond birth and death.

_te asitā jātimaraṇabhayassa pāragū._
____

.Illustration
====
pāraguṃ gone beyond

[quote

It.40]
====

____
With self-centredness abandoned, he has gone beyond old age, I declare.

_Mānaṃ jahaṃ brūmi jarāya pāraguṃ._
____

.Illustration
====
pāraguṃ gone beyond

[quote

It.40-1]
====

____
Be those who have gone beyond birth and death.

_Bhavātha jātimaraṇassa pāragā ti._
____

.Illustration
====
pāragū

gone beyond
====

[quote, Th.v.1022]
____
He bears his last body having gone beyond birth and death

_Dhāreti antimaṃ dehaṃ jātimaraṇapāragū._
____

.Illustration
====
pāraguṃ

gone beyond
====

[quote, Sn.v.1105]
____
One who has done what needed to be done, who is free of perceptually obscuring 
states, and who has gone beyond all things.

_Katakiccaṃ anāsavaṃ pāraguṃ sabbadhammānaṃ._
____

.Illustration
====
pāragun

gone beyond
====

[quote, Th.v.38]
____
The devas venerate him, the one who has gone beyond individual existence.

_Devā namassanti bhavassa pāragun ti._
____

