== Pārāyana; Parāyaṇa

=== Renderings

- _pārāyana_: the way to the Far Shore

- _parāyaṇa_: means of survival

- _parāyaṇa_: destiny

- _parāyaṇa_: support

- _parāyaṇa_: final destination

- _parāyaṇa_: Final Destination (i.e. _nibbāna_)

=== Introduction

==== Parāyaṇa and Parāyana

These words are synonyms, though PED is silent on the matter. VRI has not 
normalised them, and thus both spellings are found there. For example, 
_sambodhiparāyaṇaṃ_ and _-naṃ._ For computer studies this is 
unsatisfactory, and we have normalised this Glossary to _parāyaṇaṃ_ in 
accordance with both Vedic and Sanskrit spellings.

==== Parāyaṇa from parā

_Parāyaṇa_ is derived from _parā+i_, where _parā_ is '_para+ā_. Ā is the 
directional prefix emphasizing _para.'_ This meaning is seen, for example, when 
Nibbāna is called 'the final destination' (_parāyaṇa_, S.4.373), and with 
the stream-enterer, who has enlightenment as his destiny 
(_sambodhiparāyaṇo,_ A.4.11-13).

==== Parāyaṇa: support

The meaning 'support' is shown here:

- In this regard one sees that very same lady after some time, eighty or ninety 
or a hundred years old, aged, as bent as a rafter, crooked, supported by a 
walking stick (_daṇḍaparāyaṇaṃ_), wobbling as she goes (M.1.88).

==== Parāyaṇa: means of survival

The meaning 'means of survival' can be seen here:

____
-- What is it that produces a person? What does he have that runs around? What 
enters upon the round of birth and death? What is his means of survival?

_Kiṃ su janeti purisaṃ kiṃ su tassa vidhāvati +
Kiṃ su saṃsāramāpādi kiṃ su tassa parāyaṇan ti_
____

[quote, S.1.38]
____
-- It is craving that produces a person; his thoughts are what runs around; a 
being enters upon the round of birth and death; his merit is his means of 
survival.

_Taṇhā janeti purisaṃ cittamassa vidhāvati +
Satto saṃsāramāpādi kammaṃ tassa parāyaṇan ti._
____

That merit is a means of survival is seen in this quote:

[quote, S.1.93]
____
Therefore one should do what is meritorious as a collection for a future life. 
Meritorious deeds are the support for living beings [when they arise] in the 
world hereafter."

_Tasmā kareyya kalyāṇaṃ nicayaṃ samparāyikaṃ puññāni 
paralokasmiṃ patiṭṭhā honti pāṇinanti._
____

==== Parāyaṇa and Pārāyana: not synonyms

PED says _pārāyana_ is the metric form of _parāyaṇa_. But Norman points 
out that Monier Williams (Sanskrit-English Dictionary) 'does not, however, 
quote such a metrical form' (GD, note on p.218.18, GD p.423).

==== Pārāyana from pāraṃ: 'the way to the Far Shore'

_Pārāyana_ occurs in relation to the fifth chapter of the _Suttanipāta_. Its 
spelling and meaning are derived from _pāraṃ,_ i.e. 'Far Shore':

[quote, Sn.v.1130]
____
This path is for going to the Far Shore, therefore it is called the way to the 
Far Shore.

_Maggo so pāraṃ gamanāya tasmā pārāyanaṃ iti._
____

=== Illustrations

.Illustration
====
parāyaṇaṃ

means of survival
====

[quote, A.1.155]
____
When one has parted this life, the bodily, verbal, and mental self-control one 
has had in this world will provide a haven, a shelter, an island, a refuge, and 
a means of survival.

_yo idha kāyena saṃyamo vācāya saṃyamo manasā saṃyamo taṃ tassa 
petassa tāṇañca lenañca dīpañca saraṇañca parāyaṇañcā ti._
____

.Illustration
====
parāyaṇe

means of survival
====

[quote, S.1.234]
____
I pay respects to those who are perfect in virtue, who are long trained in 
inward collectedness, who have rightly gone forth [into the ascetic life], and 
have the religious life as their [sole] means of survival.

_Ahañca sīlasampanne cirarattasamāhite +
Sammā pabbajite vande brahmacariyaparāyaṇe._
____

.Illustration
====
parāyaṇaṃ

Final Destination
====

____
The destruction of attachment, hatred, and undiscernment of reality. This is 
called the Final Destination.

_yo bhikkhave rāgakkhayo dosakkhayo mohakkhayo idaṃ vuccati bhikkhave 
parāyaṇaṃ._
____

[quote, S.4.373]
____
What is the path leading to the Final Destination. Mindfulness of the body.

_Katamo ca bhikkhave parāyaṇagāmī maggo? Kāyagatāsati._
____

.Illustration
====
parāyaṇaṃ

final destination
====

[quote, S.5.218]
____
The religious life is lived which has the Untroubled as its culmination, final 
destination, and conclusion.

_Nibbānogadhaṃ hi brāhmaṇa brahmacariyaṃ vussati nibbānaparāyaṇaṃ 
nibbānapariyosānan ti._
____

.Illustration
====
parāyaṇo

destiny
====

[quote, S.5.217]
____
One who lives a hundred years, even he has death as his destiny.

_Yo ca vassasataṃ jīve sopi maccuparāyaṇo._
____

.Illustration
====
parāyaṇo

destiny
====

[quote, A.4.11-13]
____
In destroying the first three ties to individual existence, he becomes a 
stream-enterer, no more liable to rebirth in the plane of damnation, assured of 
deliverance, with enlightenment as his destiny.

_So tiṇṇaṃ saṃyojanānaṃ parikkhayā sotāpanno hoti avinipātadhammo 
niyato sambodhiparāyaṇo._
____

.Illustration
====
parāyaṇo

destiny
====

[quote, D.2.93]
____
I am a stream-enterer, no more liable to rebirth in the plane of damnation, 
assured of deliverance, with enlightenment as my destiny.

_sotāpanno'hamasmi avinipātadhammo niyato sambodhiparāyaṇo ti._
____

.Illustration
====
parāyaṇa

destiny
====

[quote, Sn.v.377]
____
You discern the possible places of rebirth and the afterlife destinations for 
the world [of beings] including the devas.

_Tuvaṃ hi lokassa sadevakassa gatiṃ pajānāsi parāyaṇañca._
____

.Illustration
====
parāyaṇaṃ

destined
====

[quote, Sn.v.1114]
____
Knowing all stations for the stream of sense consciousness, the Perfect One 
knows [the stream of sense consciousness], whether it is established in this 
world, or liberated [from perceptually obscuring states], or destined to be so 
liberated.

_Viññāṇaṭṭhitiyo sabbā abhijānaṃ tathāgato +
Tiṭṭhantamenaṃ jānāti vimuttaṃ tapparāyaṇaṃ._
____

