== Pāsādika

=== Renderings

- _pāsādika_: beautifully behaved

- _pāsādika_: beautiful behaviour

- _pāsādika_: handsome

- _pāsādika_: beautiful

=== Illustrations

.Illustration
====
pāsādikaṃ

beautifully behaved
====

____
You will see the Blessed One

_dakkhissasi tvaṃ soṇa taṃ bhagavantaṃ_
____

____
who is beautifully behaved, faith inspiring,

_pāsādikaṃ pasādaniyaṃ_
____

[quote, Ud.58]
____
who has peaceful [mental] faculties and a peaceful mind,

_santindriyaṃ santamānasaṃ._
____

.Illustration
====
apāsādike

unbeautiful behaviour
====

____
Five dangers of unbeautiful behaviour

_pañcime bhikkhave ādīnavā apāsādike._
____

____
those without faith do not gain faith

_appasannā nappasīdanti_
____

____
some with faith start wavering

_pasannānañca ekaccānaṃ aññathattaṃ hoti_
____

____
the Teacher's training system is not fulfilled

_satthusāsanaṃ akataṃ hoti_
____

____
later disciples follow one's example

_pacchimā janatā diṭṭhānugatiṃ āpajjati_
____

• one's mind does not become serene** +
☸** _cittamassa nappasīdati_ (A.3.255).

.Illustration
====
pāsādike

beautiful behaviour
====

____
Five advantages of beautiful behaviour

_pañcime bhikkhave ānisaṃsā pāsādike_
____

____
those without faith are won over

_appasannā pasīdanti_
____

____
those with faith are inspired with further confidence

_pasannānañca bhīyyo bhāvo hoti_
____

____
the Teacher's word is fulfilled

_satthusāsanaṃ kataṃ hoti_
____

____
later disciples follow one's example

_pacchimā janatā diṭṭhānugatiṃ āpajjati_
____

• one's mind becomes serene** +
☸** _cittamassa pasīdati_ (A.3.256).

.Illustration
====
pāsādikassa

beautiful behaviour
====

[quote, Vin.1.45]
____
Having in many ways spoken in praise of being easy to support and help, of 
fewness of needs, of being content [with what is paltry and easily gotten], of 
erasing defilements, of austerity, of beautiful behaviour, of a dwindling away 
of the five grasped aggregates, of the exertion of energy,

_anekapariyāyena subharatāya supposatāya appicchassa santuṭṭhassa 
sallekhassa dhutassa pāsādikassa apacayassa viriyārambhassa vaṇṇaṃ 
bhāsitvā._
____

.Illustration
====
pāsādikaṃ

beautifully behaved
====

[quote, A.2.104]
____
In this regard, some person is beautifully behaved whether walking towards or 
away, looking at or away, flexing or extending his arms, or carrying his robes 
and bowl

_Idha bhikkhave ekaccassa puggalassa pāsādikaṃ hoti abhikkantaṃ 
paṭikkantaṃ ālokitaṃ vilokitaṃ sammiñjitaṃ pasāritaṃ 
saṅghāṭipattacīvaradhāraṇaṃ._
____

.Illustration
====
pāsādikaṃ

beautifully behaved
====

• With a person who is beautifully behaved in every respect, one's mind 
becomes serene. +
_Samantapāsādikaṃ āvuso puggalaṃ āgamma cittaṃ pasīdati_ (A.3.190).

.Illustration
====
pāsādikānaṃ

beautifully behaved
====

[quote, A.1.24]
____
Chief of those who is beautifully behaved in every respect is Upasena 
Vaṅgantaputta.

_Etadaggaṃ bhikkhave mama sāvakānaṃ bhikkhūnaṃ samantapāsādikānaṃ 
yadidaṃ upaseno vaṅgantaputto._
____

.Illustration
====
pāsādikataro

handsome
====

[quote, S.1.237]
____
The more the devas complained, muttered, and grumbled, the more lovely, 
attractive, and handsome the yakkha became.

_Yathā yathā kho bhikkhave devā tāvatiṃsā ujjhāyanti khīyanti 
vipācenti tathā tathā so yakkho abhirūpataro ceva hoti dassanīyataro ca 
pāsādikataro ca._
____

.Illustration
====
pāsādikaṃ

beautiful
====

[quote, Th.v.927]
____
Therefore their [way of] walking, eating, and conducting themselves was 
beautiful. Their [way of] deportment was smooth, like a stream of oil.

_Tato pāsādikaṃ āsi gataṃ bhuttaṃ nisevitaṃ +
Siniddhā teladhārā va ahosi iriyāpatho._
____

.Illustration
====
pāsādikā

beautiful
====

____
How delightful is the moonlit night!

_ramaṇīyā vata bho dosinā ratti_
____

____
How lovely is the moonlit night!

_abhirūpā vata bho dosinā ratti_
____

____
How attractive is the moonlit night!

_dassanīyā vata bho dosinā ratti_
____

[quote, D.1.47]
____
How beautiful is the moonlit night!

_pāsādikā vata bho dosinā ratti._
____

.Illustration
====
pāsādikaṃ

beautifully
====

• Venerable Pukkusāti spent most of the night seated in meditation. Then the 
Blessed One thought 'This noble young man behaves beautifully * +
☸* _Āyasmāpi kho pukkusāti bahudeva rattiṃ nisajjāya vītināmesi. Atha 
kho bhagavato etadahosi pāsādikaṃ nu kho ayaṃ kulaputto iriyati_ 
(M.3.238).

.Illustration
====
pāsādikaṃ

beautiful
====

[quote, A.4.355]
____
Beautiful and delightful indeed is this mango grove.

_pāsādikaṃ vatidaṃ ambavanaṃ ramaṇīyaṃ._
____

.Illustration
====
pāsādikāsi

beautiful
====

[quote, Thī.v.402]
____
You are beautiful, noble Isidāsī. Your youth is still unfaded.

_Pāsādikāsi ayye Isidāsī vayopi te aparihīno._
____

.Illustration
====
pāsādikaṃ

beautiful
====

[quote, M.1.167]
____
A beautiful woodland grove with a clear-flowing river

_pāsādikañca vanasaṇḍaṃ nadiñca sandantiṃ._
____

