== Pūtimutta

=== Renderings

- _pūtimutta_: concentrated urine

=== Introduction

==== Pūtimutta is not 'rotten urine'

_Pūti_ can mean rotten:

[quote, M.1.89]
____
bones rotted and crumbled to dust

_aṭṭhikāni pūtīni cuṇṇakajātāni._
____

[quote, M.1.73]
____
beings born in a rotten fish, in a rotten corpse, in rotten porridge

_sattā pūtimacche vā jāyanti pūtikuṇape vā pūtikummāse vā._
____

But _pūtimutta_, a consumable medicine, would not be 'rotten urine' because:

1. rotten urine would likely be poisonous.

2. the medicinal effectiveness of any product would hardly be improved by 
allowing it to rot.

3. Allowing urine to 'ferment' would require sterile equipment, and the Buddha 
made no allowance for any such equipment. Further, accumulating clay or shell 
vessels would be an impossible and ridiculous burden for bhikkhus living at the 
roots of trees. Thus _pūtimutta_ was likely a product to be consumed without 
storage.

PED calls _pūtimutta_ strong-smelling urine.

==== Pūtimutta is ordinary urine

_Pūtimutta_ is likely the same as ordinary urine (_mutta_) because both are 
used in the treatment of jaundice:

[quote, Vin.1.206]
____
Now at that time a certain bhikkhu had jaundice. They informed the Blessed One 
about it. [He said:] "I allow you, bhikkhus, to make him drink [a compound of] 
urine (_mutta_) and yellow myrobalan."

_Tena kho pana samayena aññatarassa bhikkhuno paṇḍurogābādho hoti. 
Bhagavato etamatthaṃ ārocesuṃ. Anujānāmi bhikkhave muttaharīṭakaṃ 
pāyetun ti._
____

[quote, M.1.316]
____
Suppose there were concentrated urine (_pūtimuttaṃ_) mixed with various 
medicines, and a man came sick with jaundice...

_Seyyathāpi bhikkhave pūtimuttaṃ nānābhesajjehi saṃsaṭṭhaṃ atha 
puriso āgaccheyya paṇḍurogī._
____

==== Pūtimutta has no medicinal properties

_Pūtimutta_ likely has no medicinal properties for several reasons:

1. In the previous paragraph, the phrase _pūtimuttaṃ nānābhesajjehi 
saṃsaṭṭhaṃ_ suggests that urine is merely a vehicle for medicinal 
substances.

2. _Pūtimutta_ is nowhere prescribed by the Buddha as a treatment in itself, 
but only together with other substances, for example with jaundice above, or 
for the treatment of snakebite, where it is the base into which dung, ashes, 
and clay can be mixed (Vin.1.206).

3. _Pūtimutta_ is linked in medicinal importance with ghee, butter, oil, 
honey, and molasses.
+
[quote, Vin.1.58]
____
Going forth [into the ascetic life] is with the support of _pūtimutta_ as 
medicine. You should make an effort with this for the rest of your life. The 
extra requisites are ghee, butter, oil, honey, and molasses.

_Pūtimuttabhesajjaṃ nissāya pabbajjā. Tattha te yāvajīvaṃ ussāho 
karaṇiyo. Atirekalābho sappi navatītaṃ telaṃ madhu phāṇitanti.._
____
+
Ghee, butter, oil, honey, and molasses are 'medicinal' only in respect of their 
nutritive properties:
+
[quote, V.1.200]
____
These five remedies, that is to say ghee, fresh butter, oil, honey, molasses, 
are remedies and are also agreed upon as remedies, and although they serve as 
nutriment for people yet they cannot be reckoned as substantial food.

_imāni kho pañca bhesajjāni seyyathīdaṃ sappi navanītaṃ telaṃ madhu 
phāṇitaṃ bhesajjāni ceva bhesajjasammatāni ca lokassa āhāratthañca 
pharanti na ca oḷāriko āhāro paññāyati._
____
+
It is accordance with this to regard _pūtimutta_ as useful only for its 
nutritive properties, which we will consider below.

4. When the Buddha was sick his resource was often simply hot or tepid water. 
For example, Upavāna was the Buddha's attendant at a time when he was affected 
by 'winds.'
+
[quote, S.1.174]
____
Please, find me some hot water.

_ingha me uṇh'odakaṃ jānāhi._
____
+
Some of the water was for bathing, and some for drinking with molasses. Then, 
again, after consuming Cunda's _sūkaramaddava_, and being attacked a painful 
and bloody illness, sitting at the root of a tree, he said:
+
[quote, D.2.128]
____
Ānanda, please bring me water. I am thirsty, Ānanda, and need [something] to 
drink.

_iṅgha me tvaṃ ānanda pānīyaṃ āhara pipāsito'mhi ānanda pivissāmī ti._
____

==== Pūtimutta: not cows' urine

[quote, A.2.27]
____
In the category of remedies, _pūtimutta_ is paltry, easily gotten, and 
blameless.

_Pūtimuttaṃ bhikkhave bhesajjānaṃ appañca sulabhañca tañca 
anavajjaṃ._
____

Because _pūtimutta_ is said to be easily gotten, it is unlikely that cows' 
urine is meant. This would be awkward, ridiculous, and potentially dangerous to 
collect, especially by bhikkhus living solitary lives in the forest.

==== Pūtimutta: source of ketone bodies and electrolytes

Venerable Kassapa fasted during illness (Ud.4), and his _Theragāthā_ verses 
show that he keenly promoted _pūtimutta_ (Th.v.1057). Drinking urine would 
preserve electrolytes, particularly sodium, potassium, calcium, magnesium, and 
phosphorus. The kidney's ability to retain these electrolytes takes up to ten 
days to adjust to fasting conditions. Drinking urine would reduce these 
obligatory losses and may therefore help prevent the refeeding syndrome which 
we discuss below:

- Early in fasting, weight loss is rapid... During the period of rapid weight 
loss, there is significant negative sodium balance, probably due to losses of 
the sodium salts of keto acids in the urine. (Fasting: The History, 
Pathophysiology, and Complications: Kerndt et al, West J Med 1982.)

- Potassium losses decrease after ten days of fasting though some losses 
persist. Magnesium, calcium, and phosphorous losses are minimal after the first 
week. (Fasting: The History, Pathophysiology, and Complications: Kerndt et al, 
West J Med 1982.)

- Renal potassium conservation develops relatively slowly in response to 
decreases in dietary potassium and is far less efficient than the kidneys' 
ability to conserve sodium. (www. merckmanuals.com.)

- Obligatory renal K+ loss is around 15 mmol/day, so it is reasonable to 
consider the minimal K+ intake necessary to maintain an extracellular fluid K+ 
within the normal range to be at least 25 mmol/day. (Core Concepts in the 
Disorders of Fluid, Electrolytes and Acid-Base Balance, ed. Mount et al., 
Springer 2013)

==== Pūtimutta: rules on offering

_Pūtimutta_ can be consumed by bhikkhus without needing to be formally offered:

[quote, Vin.1.206]
____
I allow that [item] which one receives while producing it as having been 
properly received while being produced. It does not need to be received again.

_Anujānāmi bhikkhave yaṃ karonto patigaṇhāti sveva paṭiggaho kato 
hoti. Na puna paṭiggahāpetabbo ti._
____

==== Danger of consuming urine

Some drugs are excreted in urine in their active form, for example, atenolol, 
cimetidine, digoxin, penicillin, quinine, salicylate, tetracycline, and 
thiazide diuretics.

==== Danger of fasting

1. Re-feeding syndrome is a potentially fatal illness that can occur following 
5-10 days of fasting, if food is introduced too suddenly, particularily in 
patients with a low body mass, and with previous malnourishment.

2. Its hallmark is hypophosphataemia due to the insulin surge.

3. It may also involve alteration in sodium, potassium, calcium, and magnesium 
balances; and in glucose, protein, and fat metabolism.

4. Refeeding should be started at no more than 50% of energy requirements, then 
gradually increased over 4-7 days.

5. Rehydration should be done cautiously.

6. Thiamine (vitamin B1, 200-300mg daily) supplementation should be used for at 
least 10 days to prevent Wernicke's encephalopathy and Korsakoff's syndrome.

Source: Refeeding syndrome: what it is, and how to prevent and treat it, 
Mehanna et al. British Medical Journal, June 2008.

==== Consuming urine: foul practice

The Buddha allowed concentrated urine to be consumed, but it is nonetheless 
considered filthy practice:

[quote, M.1.79]
____
As long as my own excrement and urine lasted, I fed on my own excrement and 
urine. Such was my great practice of feeding on filth.

_yāvakīvañca me sāriputta sakaṃ muttakarīsaṃ apariyādiṇṇaṃ hoti 
sakaṃ yeva sudaṃ muttakarīsaṃ āhāremi. Idaṃ su me sāriputta 
mahāvikaṭabhojanasmiṃ hoti._
____

==== Uses of unconcentrated urine

1. Unconcentrated mid-stream urine is a sterile fluid that may be useful in 
treating superficial wounds. Concentrated urine would be too salty.

2. Water consumed from village wells during almsround could be a later source 
of liquid for the afternoon meditation period.

=== Illustrations

.Illustration
====
pūtimutta

concentrated urine
====

[quote, Vin.1.58]
____
Going forth [into the ascetic life] is with the support of concentrated urine 
as medicine. You should make an effort with this for the rest of your life.

_Pūtimuttabhesajjaṃ nissāya pabbajjā. Tattha te yāvajīvaṃ ussāho 
karaṇiyo._
____

.Illustration
====
pūtimutta

concentrated urine
====

[quote, A.2.27]
____
In the category of remedies, concentrated urine is paltry, easily gotten, and 
blameless.

_Pūtimuttaṃ bhikkhave bhesajjānaṃ appañca sulabhañca tañca 
anavajjaṃ._
____

