== Rakkhati

=== Renderings

- _rakkhati_: to supervise [with mindfulness]

- _rakkhita_: supervised [by mindfulness]

- _rakkhati_: to watch over

- _rakkhati_: to guard

- _rakkhati_: to protect

- _anurakkhati_: to protect

- _anurakkhati_: to preserve

- _anurakkhati_: to foster

=== Introduction

==== To supervise [with mindfulness], or to be supervised [by mindfulness]

The main purpose of this section is to explain our parenthesis '[by 
mindfulness]'. We have shown that _saṃvara_ means restraint [of the sense 
faculties] [from attraction and repulsion, through mindfulness] (sv 
_Saṃvara_). Likewise, when _rakkhati_ or _rakkhita_ means supervise or 
supervised, the expressions _ārakkhasatino_ and _satārakkhena_ in the 
following quote shows it means to supervise [with mindfulness] or to be 
supervised [by mindfulness]:

[quote, A.3.138]
____
Come on, friend, abide with sense portals guarded [by mindfulness]. Take 
mindfulness as your supervisor. Be aware and mindful, and have a mind that is 
supervised [by mindfulness], a mind under the supervision of mindfulness.

_Etha tumhe āvuso indriyesu guttadvārā viharatha ārakkhasatino 
nipakkasatino sārakkhitamānasā satārakkhena cetasā samannāgatāti._
____

=== Illustrations: rakkhati

.Illustration
====
rakkhatā

supervisor; rakkhati, supervises [with mindfulness]
====

____
And how is he a supervisor?

_rakkhitā hoti_
____

____
Bhikkhus, in seeing a visible object via the visual sense,

_cakkhunā rūpaṃ disvā_
____

____
he does not grasp its aspects and features

_na nimittaggāhī nānuvyañjanaggāhī_
____

____
since by abiding with the faculty of sight unrestrained [from attraction and 
repulsion, through mindfulness]

_yatvādhikaraṇametaṃ cakkhundriyaṃ asaṃvutaṃ viharantaṃ_
____

____
greed, dejection, and unvirtuous, spiritually unwholesome factors would pursue 
him.

_abhijjhādomanassā pāpakā akusalā dhammā anvāssaveyyuṃ_
____

____
He applies himself to the restraint of the faculty [from attraction and 
repulsion, through mindfulness]

_tassa saṃvarāya paṭipajjati_
____

____
He supervises the faculty of sight [with mindfulness]

_rakkhati cakkhundriyaṃ_
____

[quote, A.3.163]
____
He attains restraint of the faculty of sight [through mindfulness]

_cakkhundriye saṃvaraṃ āpajjati._
____

.Illustration
====
arakkhite

unsupervised [by mindfulness]; arakkhitaṃ, unsupervised; arakkhitaṃ, 
unprotected
====

____
If the mind is unsupervised [by mindfulness], acts of body, speech, and mind 
are unsupervised [by the mind].

_Citte gahapati arakkhite kāyakammampi arakkhitaṃ hoti. Vacī kammampi 
arakkhitaṃ hoti. Manokammampi arakkhitaṃ hoti._
____

____
When acts of body, speech, and mind are unsupervised [by the mind], they are 
spiritually defiled._

_Tassa arakkhitakāyakammantassa arakkhitavacīkammantassa 
arakkhitamanokammantassa kāyakammampi avassutaṃ hoti. Vacīkammampi 
avassutaṃ hoti. Manokammampi avassutaṃ hoti._
____

[quote, A.1.261]
____
... It is like when a hut is poorly thatched, the hut, the rafters, and the 
walls are unprotected._

_Seyyathā pi gahapati kūṭāgāre ducchanne kūṭampi arakkhitaṃ hoti. 
Gopānasiyo pi arakkhitā honti. Bhitti pi arakkhitā hoti._
____

.Illustration
====
rakkheyya

watching over
====

[quote, M.1.115-117]
____
Bhikkhus, it is as if in the last month of the rains, in the autumn when the 
corn is thick, a cowherd might be watching over cows,

_Seyyathā pi bhikkhave vassānaṃ pacchime māse saradasamaye 
kiṭṭhasambādhe gopālako gāvo rakkheyya._
____

.Illustration
====
ārakkhā

guarding
====

____
Because of stinginess, guarding _

_macchariyaṃ paṭicca ārakkhā_
____

[quote, A.4.401]
____
Because of guarding, arises the use of sticks and swords; quarrels, arguments, 
disputes, strife, and malicious speech and lying, and many unvirtuous, 
spiritually unwholesome factors.

__ārakkhādhikaraṇaṃ daṇḍādānasatthādāna 
kalahaviggahavivādatuvaṃtuvaṃ pesuññamusāvādā aneke pāpakā akusalā 
dhammā sambhavanti._
____

.Illustration
====
arakkhito

protect
====

____
Those who misconduct themselves by way of body, speech, and mind do not 
&#8203;[spiritually] protect themselves.

_ye hi keci kāyena duccaritaṃ caranti vācāya duccaritaṃ caranti manasā 
duccaritaṃ caranti tesaṃ arakkhito attā_
____

[quote, S.1.73]
____
Even if protected by an army of elephants, cavalry or chariots, they do not 
&#8203;[spiritually] protect themselves. Why? Because that protection is external not 
inward.

_Kiñcāpi te hatthikāyo vā rakkheyya assakāyo vā rakkheyya rathakāyo vā 
rakkheyya pattikāyo vā rakkheyya atha kho tesaṃ arakkhito attā. Taṃ 
kissa hetu? Bāhirā hesā mahārāja rakkhā nesā rakkhā ajjhattikā._
____

.Illustration
====
rakkheyya

protect
====

[quote, Sn.v.702]
____
One should protect one's mind against spiritual flaws

_manopadosaṃ rakkheyya._
____

.Illustration
====
rakkhati

protect
====

____
And what is diligence [in the practice]?

_Katamo ca bhikkhave appamādo._
____

[quote, S.5.232]
____
In this regard a bhikkhu protects the mind against perceptually obscuring 
states and against states associated with perceptually obscuring states.

_Idha bhikkhave bhikkhu cittaṃ rakkhati āsavesu ca sāsavesu ca dhammesu._
____

.Illustration
====
rakkhanti

protect
====

[quote, Vin.1.295]
____
Five advantages of falling to sleep mindfully and in full consciousness... 
Devas protect one.

_Devatā rakkhanti._
____

.Illustration
====
rakkha

protect
====

An acrobat told his apprentice Medakathālikā to join him on the bamboo pole 
and stand on his shoulders, and said:

____
-- You protect me, dear Medakathālikā, and I'll protect you.

_tvaṃ samma medakathālike mamaṃ rakkha. Ahaṃ tvaṃ rakkhikissāmi._
____

____
'Thus safeguarding one another, protecting one another, we'll exhibit our 
skills, collect our fee, and get safely off the bamboo pole.'

_Evaṃ mayaṃ aññamaññaguttā aññamaññarakkhitā_
____

Medakathālikā replied:

____
-- That's not the way to do it, teacher. You protect yourself, teacher, and 
I'll protect myself. Thus, each safeguarding ourselves, and protecting 
ourselves, we'll exhibit our skills, collect our fee, and get safely off the 
bamboo pole.'

_na kho panetaṃ ācariya evaṃ bhavissati tvaṃ ācariya attānaṃ rakkha 
ahaṃ attānaṃ rakkhissāmi. Evaṃ mayaṃ attaguttā attarakkhitā 
sippāni ceva dassessāma lābhañca lacchāma sotthinā ca 
caṇḍālavaṃsā orohessāmā ti._
____

____
"That's the correct approach," the Blessed One said. "It's just as the 
apprentice Medakathālikā explained.

_So tattha ñāyo ti bhagavā avoca yathā medakathālikā antevāsī 
ācariyaṃ avoca_
____

____
If one wishes to protect oneself, one should undertake the basic practice of 
mindfulness.

_Attānaṃ bhikkhave rakkhissāmī ti satipaṭṭhānaṃ sevitabbaṃ._
____

____
If one wishes to protect others, one should undertake the basic practice of 
mindfulness.

_Paraṃ rakkhissāmī ti satipaṭṭhānaṃ sevitabbaṃ._
____

____
Protecting oneself, one protects others. Protecting others, one protects 
oneself.

_Attānaṃ bhikkhave rakkhanto paraṃ rakkhati. Paraṃ rakkhanto attānaṃ 
rakkhati._
____

____
"In what way in protecting oneself does one protect others? By the pursuit, 
development, and cultivation (of the basic practice of mindfulness).

_Kathañca bhikkhave attānaṃ rakkhanto paraṃ rakkhati āsevanāya 
bhāvanāya bahulīkammena._
____

____
"In what way in protecting others does one protect oneself? By developing 
patience, compassion, a mind of [unlimited, all-encompassing] goodwill, and 
sympathy.

_Kathañca bhikkhave paraṃ rakkhanto attānaṃ rakkhati khantiyā 
avihiṃsāya mettacittatāya anuddayatāya_
____

____
"If one wishes to protect oneself, one should undertake the basic practice of 
mindfulness.

_Attānaṃ bhikkhave rakkhissāmī ti satipaṭṭhānaṃ sevitabbaṃ_
____

____
If one wishes to protect others, one should undertake the basic practice of 
mindfulness.

_paraṃ rakkhissāmī ti satipaṭṭhānaṃ sevitabbaṃ_
____

[quote, S.5.168-9]
____
Protecting oneself, one protects others. Protecting others, one protects 
oneself."

_attānaṃ bhikkhave rakkhanto paraṃ rakkhati paraṃ rakkhanto attānaṃ 
rakkhatīti._
____

.Illustration
====
rakkhita

protected
====

[quote, Ud.41]
____
He stayed near Pārileyyaka in a protected woodland grove.

_pārileyyake viharati rakkhitavanasaṇḍe._
____

.Illustration
====
rakkhati

protect
====

[quote, Th.v.303-4]
____
The teaching indeed protects one who practises it.

_Dhammo have rakkhati dhammacāriṃ._
____

.Illustration
====
rakkhitā

in the guardianship of
====

[quote, M.3.54]
____
He fornicates with women who are in the guardianship of mother, father, 
brother, sister, or relations.

_yā tā māturakkhitā piturakkhitā mātāpiturakkhitā bhāturakkhitā 
bhaginirakkhitā ñātirakkhitā... tathārūpāsu cārittaṃ āpajjitā hoti._
____

=== Illustrations: anurakkhati

.Illustration
====
anurakkhate

protect
====

[quote, A.4.93]
____
A wife who protects her husband as a mother her son

_Mātāva puttaṃ anurakkhate patiṃ._
____

.Illustration
====
anurakkhe

protect
====

____
Just as a mother would protect with her life her own son, her only son, so 
would he cultivate an attitude toward all beings unlimited [by attachment, 
hatred, and undiscernment of reality], and [unlimited, all-encompassing] 
goodwill for all the world.

_Mātā yathā niyaṃ puttaṃ āyusā ekaputtamanurakkhe_
____

.Illustration
====
anurakkhatā

preserves
====

One religious theory, though carefully thought about may be false. Another 
religious theory, though not carefully thought about may be true. One religious 
theory, though well considered may be false. Another religious theory, though 
not well considered may be genuine, factual, and true.

[quote, M.2.171]
____
In such a situation it is not proper for a knowledgeable person who preserves 
truth to come to the unqualified conclusion, 'This alone is true; all else is 
false.'

_Saccamanurakkhatā bhāradvāja viññunā purisena nālamettha ekaṃsena 
niṭṭhaṃ gantuṃ idameva saccaṃ moghamaññan ti._
____

.Illustration
====
anurakkhati

foster
====

____
And what is inward striving through fostering?

_Katamañca bhikkhave anurakkhaṇappadhānaṃ?_
____

____
In this regard a bhikkhu fosters a favourable meditation object

_Idha bhikkhave bhikkhu uppannaṃ bhaddakaṃ samādhinimittaṃ anurakkhati_
____

____
the mental image of a skeleton

_aṭṭhikasaññaṃ_
____

____
the mental image of a maggot-infested corpse

_puḷavakasaññaṃ_
____

____
the mental image of a discoloured corpse

_vinīlakasaññaṃ_
____

____
the perception of a festering corpse

_vipubbakasaññaṃ_
____

____
the mental image of a cut up corpse

_vicchiddakasaññaṃ_
____

[quote, A.2.16-7]
____
the mental image of a bloated corpse

_uddhumātakasaññaṃ._
____

