== Rāga

=== Renderings

- _rāga_: attachment

- _rāga_: lust

.Illustration
====
rāga

attachment
====

[quote, S.5.84]
____
Bhikkhus, by much contemplating things that are a basis for attachment to 
sensuous pleasure, unarisen sensuous hankering arises, and arisen sensuous 
hankering increases and expands.

_Kāmarāgaṭṭhāniyānaṃ bhikkhave dhammānaṃ manasikārabahulīkārā 
anuppanno ceva kāmacchando uppajjati uppanno ca kāmacchando bhiyyobhāvāya 
vepullāya saṃvattati._
____

.Illustration
====
rāga

attachment
====

[quote, It.80]
____
For one who abides contemplating the unloveliness of the body the proclivity to 
attachment to the phenomenon of loveliness is abandoned.

_asubhānupassīnaṃ bhikkhave kāyasmiṃ viharataṃ yo subhāya dhātuyā 
rāgānusayo so pahīyati._
____

.Illustration
====
rāgā

attachment
====

[quote, S.4.307]
____
In the theatre or arena, among beings who are not free of attachment, who are 
bound [to individual existence] by the bondage of attachment, an actor 
entertains them with charming things that excite them even more strongly to 
attachment.

_Pubbe kho gāmaṇī sattā avītarāgā rāgabandhanabaddhā tesaṃ naṭo 
raṅgamajjhe samajjamajjhe ye dhammā rajanīyā te upasaṃharati bhiyyo 
sarāgāya._
____

.Illustration
====
rāgo

attachment
====

____
-- What do you think, headman? Before you saw Ciravāsi's mother or heard about 
her, did you have any fondness, attachment, or love for her?

_chando vā rāgo vā pemaṃ vā ti_
____

-- No, bhante (S.4.329-330).

.Illustration
====
rāgo

attachment
====

[quote, M.1.511]
____
If a blind man was sold a dirty garment, and was told it was beautiful and 
clean, when his vision was restored, his fondness and attachment regarding that 
garment would be abandoned.

_chandarāgo so pahīyetha._
____

.Illustration
====
rāgaṃ

attachment
====

____
When the perception of the unlastingness [of the five aggregates] is developed 
and cultivated,

_aniccasaññā bhikkhave bhāvitā bahulīkatā_
____

____
it destroys all attachment to sensuous pleasure

_sabbaṃ kāmarāgaṃ pariyādiyati_
____

____
it destroys all attachment to the refined material states of awareness

_sabbaṃ rūparāgaṃ pariyādiyati_
____

[quote, S.3.155]
____
it destroys all attachment to individual existence

_sabbaṃ bhavarāgaṃ pariyādiyati._
____

.Illustration
====
rāga

attachment
====

[quote, S.4.36]
____
When there is spiritually fettering delight, there is attachment. Where there 
is attachment, there is bondage [to individual existence].

_nandiyā sati sārāgo hoti sārāge sati saṃyogo hoti._
____

.Illustration
====
rāga

attachment
====

[quote, M.2.138]
____
The Buddha takes his food experiencing the flavour though not experiencing 
attachment to the flavour

_rasapaṭisaṃvedi... no ca rasarāgapaṭisaṃvedī._
____

.Illustration
====
rāga

attachment
====

[quote, D.3.249]
____
This is the liberation from attachment, namely the liberation [from 
perceptually obscuring states] through [unlimited, all-encompassing] detached 
awareness.

_nissaraṇaṃ hetaṃ āvuso rāgassa yadidaṃ upekkhā cetovimutti._
____

.Illustration
====
rāga

attachment
====

• When affected by a pleasant sense impression, he takes delight in it, he 
welcomes it, and persists in cleaving to it. The proclivity to attachment lurks 
within him. +
_So sukhāya vedanāya phuṭṭho samāno abhinandati abhivadati ajjhosāya 
tiṭṭhati. Tassa rāgānusayo anuseti_ (M.3.286).

.Illustration
====
rāgo

lust
====

[quote, S.2.231]
____
He sees women there lightly clad or lightly attired, and lust invades his mind.

_rāgo cittaṃ anuddhaṃseti._
____

.Illustration
====
rāgo

lust
====

[quote, D.3.88]
____
Because they spend an excessive amount of time gazing at each other, lust was 
aroused and sensuous passion arose in their bodies.

_Tesaṃ ativelaṃ aññamaññaṃ upanijjhāyataṃ sārāgo udapādi 
pariḷāho kāyasmiṃ okkami._
____

.Illustration
====
rāgena

lust
====

Erections (_aṅgajātaṃ kammaniyaṃ hoti_) are caused by a distended bowel 
or bladder, by bodily energies, from the sting of hairy caterpillars (?), or by 
lust (_rāgena vaccena passāvena vātena uccāliṅgapāṇakadaṭṭhena_) 
(Vin.3.37-8).

.Illustration
====
rāgena

lust
====

[quote, S.1.188]
____
I am burning with lust for sensuous pleasure, my mind is burning. Please tell 
me how to extinguish it, out of tender concern, O Gotama clansman.

_Kāmarāgena ḍayhāmi cittaṃ me pariḍayhati +
Sādhu nibbāpanaṃ brūhi anukampāya gotamāti._
____

