== Rūpa

=== Renderings

- _rūpa_: sight/s

- _rūpa_: visible object

- _rūpa_: matter

- _rūpa_: refined material states of awareness

- _rūpa_: refined material plane of existence

- _rūpa_: bodily form

- _rūpa_: shape

- _rūpa_: appearance

- _rūpin_: material

- _arūpa_: the immaterial states of awareness

- _arūpa_: immaterial plane of existence

=== Illustrations

.Illustration
====
rūpe

sights
====

[quote, Vin.1.37]
____
Brahmanic sacrifices glorify sights and sounds, also flavours, sensuous 
pleasures, and women.

_Rūpe ca sadde ca atho rase ca +
Kāmitthiyo cābhivadanti yaññā._
____

.Illustration
====
rūpā

sights
====

[quote, A.3.69]
____
These five varieties of sensuous pleasure are seen in a woman's body: charming 
sights, sounds, tastes, odours, and physical sensations;_

_Pañcakāmaguṇā ete itthirūpasmiṃ dissare +
Rūpā saddā rasā gandhā phoṭṭhabbā ca manoramā._
____

.Illustration
====
rūpa

visible object; rūpaṃ, sight
====

[quote, A.3.68]
____
I see no single visible object so attractive, so sensuous, so intoxicating, so 
captivating, so infatuating, so obstructive to the reaching of unsurpassed 
safety from the danger of bondage [to individual existence], as the sight of a 
woman.

_Nāhaṃ bhikkhave aññaṃ ekarūpampi samanupassāmi yaṃ evaṃ 
rajanīyaṃ evaṃ kamanīyaṃ evaṃ madanīyaṃ evaṃ bandhanīyaṃ 
evaṃ mucchanīyaṃ evaṃ antarāyakaraṃ anuttarassa yogakkhemassa 
adhigamāya yathayidaṃ bhikkhave itthirūpaṃ._
____

.Illustration
====
rūpa

appearance
====

Four persons in the world:

1. He who guages by appearance, and whose faith is inspired by appearance
+
****
_rūpappamāṇo rūpappasanno_
****

2. He who guages by voice, and whose faith is inspired by voice
+
****
_ghosappamāṇo ghosappasanno_
****

3. He who guages by asceticism, and whose faith is inspired by asceticism
+
****
_lūkhappamāṇo lūkhappasanno_
****

4. He who guages by the teaching, and whose faith is inspired by the teaching
+
****
_dhammappamāṇo dhammappasanno_ (A.2.71).
****

.Illustration
====
rūpaṃ

visible object
====

[quote, D.2.338]
____
It sees a visible object via its visual sense

_cakkhunāpi rūpaṃ passati._
____

.Illustration
====
rūpā

visible objects
====

[quote, M.3.267]
____
There are visible objects known via the visual sense that are likeable, 
loveable, pleasing, agreeable, connected with sensuous pleasure, and charming.

_Santi kho puṇṇa cakkhuviññeyyā rūpā iṭṭhā kantā manāpā 
piya**rūp**ā kāmūpasaṃhitā rajanīyā._
____

.Illustration
====
rūpaṃ

matter
====

____
Threefold classification of matter

_Tividhena rūpasaṅgaho_
____

____
visible and tangible matter

_sanidassanasappaṭighaṃ rūpaṃ_
____

____
invisible and tangible matter

_anidassanasappaṭighaṃ rūpaṃ_
____

[quote, D.3.217]
____
invisible and intangible matter.

_anidassanaappaṭighaṃ rūpaṃ._
____

.Illustration
====
rūpī

material
====

[quote, D.1.76]
____
This my body is material, is made of the four great material phenomena

_ayaṃ kho me kāyo rūpī cātummahābhūtiko._
____

.Illustration
====
rūpa

the refined material plane of existence; arūpa, the immaterial plane of 
existence
====

____
Three further types of craving

_Aparā pi tisso taṇhā_
____

____
craving for the sensuous plane of existence

_kāmataṇhā_
____

____
craving for the refined material plane of existence

_rūpataṇhā_
____

[quote, D.3.216]
____
craving for the immaterial plane of existence.

_arūpataṇhā._
____

.Illustration
====
rūpa

refined material plane of existence; arūpa, immaterial plane of existence
====

____
There are three states of individual existence

_tayo me āvuso bhavā_
____

____
individual existence in the sensuous plane of existence

_kāmabhavo_
____

____
individual existence in the refined material plane of existence

_rūpabhavo_
____

[quote, M.1.50]
____
individual existence in the immaterial plane of existence

_arūpabhavo._
____

.Illustration
====
rūpa

the refined material states of awareness; arūpa, immaterial states of awareness
====

____
Three further varietes of craving:

_aparā pi tisso taṇhā_
____

____
craving for refined material states of awareness

_rūpataṇhā_
____

____
craving for immaterial states of awareness

_arūpataṇhā_
____

[quote, D.3.216]
____
craving for the ending [of originated phenomena]

_nirodhataṇhā._
____

.Illustration
====
rūpa

bodily form
====

[quote, M.3.17]
____
The four great material phenomena are the indispensible and necessary 
conditions by which the aggregate of bodily form is to be discerned._

_Cattāro kho bhikkhu mahābhūtā hetu cattāro mahābhūtā paccayo 
rūpakkhandhassa paññāpanāya._
____

.Illustration
====
rūpaṃ

bodily form
====

____
The ignorant Everyman considers bodily form to be the [absolute] Selfhood, or 
the [absolute] Selfhood to be corporeal, or that bodily form to be part of the 
&#8203;[absolute] Selfhood, or that the [absolute] Selfhood to be part of bodily form.

_rūpaṃ attato samanupassati rūpavantaṃ vā attānaṃ attani vā rūpaṃ 
rūpasmiṃ vā attānaṃ_
____

[quote, M.3.228]
____
If that bodily form changes and alters, his mind is preoccupied with the change.

_Tassa taṃ rūpaṃ vipariṇamati aññathā hoti tassa 
rūpavipariṇāmaññathābhāvā rūpavipariṇāmānuparivatti 
viññāṇaṃ hoti._
____

.Illustration
====
rūpaṃ

bodily form
====

____
Why is it called bodily form? It is harassed, therefore it is called bodily 
form.

_Kiñca bhikkhave rūpaṃ vadetha: rūppatī ti kho bhikkhave tasmā rūpanti 
vuccati._
____

[quote, S.3.86]
____
Harassed by what? By cold, heat, hunger, thirst, horseflies, mosquitoes, wind, 
sun, snakes.

_Kena rūppati: sītena pi ruppati uṇhena pi ruppati jighacchāya pi ruppati 
pipāsāya pi ruppati ḍaṃsamakasavātātapasiriṃsapasamphassena pi 
ruppati._
____

.Illustration
====
rūpaṃ

bodily form
====

[quote, S.3.66-7]
____
If bodily form was endowed with personal qualities it would not lead to 
affliction and it would be possible to demand of bodily form: 'My bodily form: 
be thus! My bodily form: be not thus!'

_rūpañca hidaṃ bhikkhave attā abhavissa nayidaṃ rūpaṃ ābādhāya 
saṃvatteyya labbhetha ca rūpe evaṃ me rūpaṃ hotu evaṃ me rūpaṃ mā 
ahosī ti._
____

.Illustration
====
rūpa

bodily form
====

[quote, M.1.185]
____
And what is the aggregate of grasped bodily form? The four great material 
phenomena and any bodily form derived from the four great material phenomena.

_Katamo cāvuso rūpūpādānakkhandho? Cattāri ca mahābhūtāni catunnañca 
mahābhūtānaṃ upādāya rūpaṃ._
____

.Illustration
====
rūpaṃ

bodily form
====

____
-- What do you think, Aggivessana? When you say that bodily form is "my 
&#8203;[absolute] Selfhood," do you wield the power over this bodily form as to 
command it 'My bodily form: be thus! My bodily form: be not thus!'?

_Rūpaṃ me attā ti. Vattati te tasmiṃ rūpe vaso evaṃ me rūpaṃ hotu 
evaṃ me rūpaṃ mā ahosī ti?_
____

-- No, Master Gotama (M.1.232).

.Illustration
====
rūpaṃ

bodily form
====

____
With reference to this [wretched human] body, the one of extensive wisdom has 
taught that with the abandonment of three things one sees the bodily form 
discarded._

_Yo imaṃ kāyaṃ gārayhaṃ bhuripaññena desitaṃ +
pahānaṃ tiṇṇaṃ dhammānaṃ rūpaṃ passetha chaḍḍitaṃ._
____

[quote, S.3.143]
____
When vitality, warmth, and mental consciousness leave this [wretched human] 
body, then it lies there cast away: food for others, senseless

_Āyu usmā ca viññāṇaṃ yadā kāyaṃ jahantimaṃ +
Apaviddho tadā seti parabhattaṃ acetanaṃ._
____

.Illustration
====
rūpaṃ

bodily form
====

____
Friends, just as when space is enclosed with timber, vines, grass, and clay, it 
is considered a 'house,'

_Seyyathā pi āvuso kaṭṭhañca paṭicca valliñca paṭicca tiṇañca 
paṭicca mattikañca paṭicca ākāso parivārito agāraṃ tveva saṅkhaṃ 
gacchati;_
____

[quote, M.1.190]
____
likewise when space is enclosed by bones, tendons, muscle, and fascia, it is 
considered a 'bodily form.'

_evameva kho āvuso aṭṭhiñca paṭicca nahāruñca paṭicca maṃsañca 
paṭicca cammañca paṭicca ākāso parivārito rūpaṃ tveva saṅkhaṃ 
gacchati._
____

.Illustration
====
rūpāni

shape
====

____
So I, Anuruddhas, abiding diligently, vigorously, and resolutely applied [to 
the practice], perceived the light-manifestation but did not see shapes (though 
light is visible, it is not a shape).

_obhāsampi hi kho sañjānāmi na ca rūpāni passāmi._
____

____
Then for a whole night and a whole day and a whole night and day I saw shapes 
but did not perceive the light-manifestation.

_Rūpāni hi kho passāmi na ca obhāsaṃ sañjānāmi._
____

____
Concerning this, Anuruddhas, it occurred to me: 'It was at the time when I was 
ignoring the aspect of shape but contemplating the aspect of light that I 
perceived the light-manifestation but did not see shapes.

_yasmiṃ hi kho ahaṃ samaye rūpanimittaṃ amanasikaritvā 
obhāsanimittaṃ manasikaromi obhāsaṃ hi kho tasmiṃ samaye sañjānāmi 
na ca rūpāni passāmi._
____

[quote, M.3.161]
____
But it was at the time when I was ignoring the aspect of the light, but was 
contemplating the aspect of shape that, for a whole night and a whole day and a 
whole night and day, I saw shapes but did not perceive the light-manifestation.

_Yasmiṃ panāhaṃ samaye obhāsanimittaṃ amanasikaritvā rūpanimittaṃ 
manasikaromi. Rūpāni hi kho tasmiṃ hi samaye passāmi. Na ca obhāsaṃ 
sañjānāmi. Kevalampi rattiṃ kevalampi divasaṃ kevalampi rattindivanti._
____

