== Sabbe dhammā nālaṃ abhinivesāyā

=== Rendering

- _sabbe dhammā nālaṃ abhinivesāyā ti_: all things are unsuited to 
stubborn attachment

=== Introduction

==== Sabbe dhammā: 'all things'

_Sabbe dhammā nālaṃ abhinivesāyā ti_ is a key phrase in the scriptures 
because, having heard it (_sutaṃ hoti_), one 'fully understands the whole 
teaching' (_sabbaṃ dhammaṃ abhijānāti_ M.1.252). However, there is no 
agreement on how to best translate it. Even the opening words _sabbe dhammā_ 
are unsettled.

Horner calls _sabbe dhammā_ 'any (psycho-physical) conditions' in the 
sentence: 'It is not fitting that there should be inclination towards any 
(psycho-physical) conditions.' Bodhi transfers the negative so the sentence 
reads 'Nothing is worth adhering to.'

==== Abhiniveso: firm, unyielding attachment

That _abhiniveso_ implies firm, unyielding attachment can be illustrated in 
several ways:

1. In the royal banyan tree called Well Established. This tree was 'steadfastly 
attached' to twelve leagues, but its roots spread to [a further] five 
(_dvādasayojanāni abhiniveso ahosi pañcayojanāni mulakasantānakānaṃ_ 
A.3.369). These latter roots were therefore part of Well Established's 
attachment, but not its _steadfast_ attachment.

2. In the attachment of the dogmatist who considers his opinion alone is 
correct, which is called _idaṃsaccābhiniveso_, stubborn attachment to 
dogmatic opinions.

3. In the attachment to one language whose vocabulary one might continue to use 
in a different country:

[quote, M.3.235]
____
Whatever they label the thing in one particular country, dogmatically grasping 
and stubbornly adhering to [his own term] he asserts 'This alone is right; all 
else is wrong.'

_iti yathā yathā naṃ tesu tesu janapadesu sañjānanti tathā tathā 
thāmasā parāmassa abhinivissa voharati idameva saccaṃ moghamaññan ti._
____

4. Where _abhiniveso_ is better called 'relentless attachment.' This is seen in 
the wish of the _khattiya_ (_khattiyā_) to conquer land, the brahman to 
perform sacrifices, the householder to work, the thief to operate in darkness, 
and in women to be without co-wives.

==== Abhinivisati: to stubbornly adhere

That _abhiniveso_ implies stubborn attachment is apparent also in its relation 
to _abhinivisati_ a similar-looking word from a different root, meaning 
'stubbornly adhere.' It is effectively the verb form of _abhiniveso._ 
Illustrations given in more detail below show that stubbornly adhering (verb) 
leads to:

1. Stubborn attachment (_abhinivesa_)
+
****
_rūpaṃ abhinivissa uppajjanti saṃyojanābhinivesa-vinibandhājjhosānā_ 
(S.3.187).
****

2. Religious dogmatism, in which one declares of one's own views 'This alone is 
true, all else is false'

• The [religious] world is made up of many and various elements, and whatever 
of these elements that beings stubbornly adhere to, then dogmatically grasping 
and stubbornly adhering they assert 'This alone is true, all else is false.' +
_Anekadhātunānādhātu kho devānaminda loko. Tasmiṃ 
anekadhātunānādhātusmiṃ loke yaṃ yadeva sattā dhātuṃ abhinivisanti 
taṃ tadeva thāmasā parāmassa abhinivissa voharanti idameva saccaṃ 
moghamaññan ti_ (D.2.282).

3. Stubbornly grasping of odious dogmatic views, like the bhikkhu Sāti:

• Although questioned, interrogated, and examined by those bhikkhus, the 
bhikkhu Sāti, son of a fisherman, dogmatically grasping and stubbornly 
adhering to that same odious dogmatic view, asserted 'As I understand the 
teaching explained by the Blessed One, it is this personal _viññāṇa_ that 
roams and wanders the round of birth and death, not another.' +
☸ _tadeva pāpakaṃ diṭṭhigataṃ thāmasā parāmassa abhinivissa 
voharati evaṃ vyā kho ahaṃ āvuso bhagavatā dhammaṃ desitaṃ 
ājānāmi yathā tadevidaṃ viññāṇaṃ sandhāvati saṃsarati 
anaññan_ ti (M.1.257).

==== Nālaṃ

_Nālaṃ_ can be used with a dative or infinitive. The meanings of _nālaṃ_ 
in summary are:

1. With dative: incapable of, unsuited to, not enough, will not:

[quote, D.3.38]
____
He is incapable of conversation.

_nālaṃ sallāpāya._
____

• All things are unsuited to stubborn attachment +
_sabbe dhammā nālaṃ abhinivesāyā ti_ (M.1.251; S.4.50; A.4.88).

[quote, Sn.v.895-6]
____
What praise they receive is trifling, not enough to bring them consolation.

_appaṃ hi etaṃ na alaṃ samāya._
____

[quote, A.3.6]
____
He will not be negligent [in looking after himself]

_kumāro nālaṃ pamādāyā ti._
____

2. With infinitive: incapable of, unsuited to, not fit, not fitting, would not

[quote, S.2.94]
____
Incapable of being disillusioned with it.

_nālaṃ nibbindituṃ._
____

[quote, A.3.144]
____
A nurse is unsuited to caring for the sick if he possesses five qualities.

_nālaṃ gilānaṃ upaṭṭhātuṃ._
____

[quote, M.2.263]
____
What is unlasting is not fit to be delighted in, welcomed, or clung to. 

_yadaniccaṃ taṃ nālaṃ abhinandituṃ nālaṃ abhivadituṃ nālaṃ 
ajjhositun ti._
____

[quote, M.2.171]
____
It is not fitting for a wise man who preserves truth to come to the unqualified 
conclusion, "This alone is true, all else is false"

_saccamanurakkhatā bhāradvāja viññunā purisena nālamettha ekaṃsena 
niṭṭhaṃ gantuṃ idameva saccaṃ moghamaññan ti._
____

[quote, Sn.v.217]
____
Would neither extol nor speak disparagingly about it

_nālaṃ thutuṃ no pi nipaccavādī._
____

=== Illustrations: abhinivesa

.Illustration
====
abhinivesāyā

stubborn attachment
====

____
When a bhikkhu has heard that all things are unsuited to stubborn attachment

_sutaṃ hoti sabbe dhammā nālaṃ abhinivesāyā ti_
____

• ... he fully understands the whole teaching, +
_so sabbaṃ dhammaṃ abhijānāti_ (M.1.252).

.Illustration
====
abhiniveso

stubborn attachment
====

____
There are these four spiritual shackles

_cattārome bhikkhave ganthā_
____

1. the spiritual shackle of greed
+
****
_abhijjhā kāyagantho_
****

2. the spiritual shackle of ill will
+
****
_vyāpādo kāyagantho_
****

3. the spiritual shackle of adherence to observances and practices
+
****
_sīlabbataparāmāso kāyagantho_
****

4. the spiritual shackle of stubborn attachment to dogmatic opinions
+
****
_idaṃsaccābhiniveso kāyagantho_
****

[quote, S.5.59]
____
For the full understanding of these four spiritual shackles the noble eightfold 
path should be developed

_abhiññāya ariyo aṭṭhaṅgiko maggo bhāvetabbo._
____

.Illustration
====
abhinivesa

stubborn attachment
====

[quote, S.2.17]
____
Most of mankind is fastened by clinging, grasping, and stubborn attachment.

_Upayupādānābhinivesavinibaddho khvāyaṃ kaccāna loko yebhuyyena._
____

.Illustration
====
abhinivesa

stubborn attachment
====

____
How does there come to be stubborn attachment to the conventional expressions 
of one particular country's language and the overriding of local terminology?

_kathañca bhikkhave janapadaniruttiyā ca abhiniveso hoti samaññāya ca 
atisāro_
____

____
In this regard, in different countries they label the same thing a 'dish': a 
'bowl,' a 'vessel,' a 'saucer,' a 'pan,' a 'pot,' or a 'basin.'

_idha bhikkhave tadavekaccesu janapadesu pātī ti sañjānanti pattan ti 
sañjānanti vitthan ti sañjānanti sarāvan ti sañjānanti dhāropan ti 
sañjānanti poṇan ti sañjānanti pisīlavan ti sañjānanti._
____

[quote, M.3.235]
____
Whatever they label the thing in one particular country, dogmatically grasping 
and stubbornly adhering to [his own term] he asserts 'This alone is right; all 
else is wrong.'

_iti yathā yathā naṃ tesu tesu janapadesu sañjānanti tathā tathā 
thāmasā parāmassa abhinivissa voharati idameva saccaṃ moghamaññan ti._
____

.Illustration
====
abhinivesa

stubborn attachment
====

____
Bhikkhus, when what exists, by grasping what, by stubbornly adhering to what, 
do psychological bondage, stubborn attachment, emotional bondage, and cleaving 
arise?

_Kismiṃ nu kho bhikkhave sati kiṃ upādāya kiṃ abhinivissa uppajjanti 
saṃyojanābhinivesa-vinibandhājjhosānā ti_
____

• When there is bodily form, by grasping bodily form, by stubbornly adhering 
to bodily form, psychological bondage, stubborn attachment, emotional bondage, 
and cleaving arise +
☸ _rūpe kho bhikkhave sati rūpaṃ upādāya rūpaṃ ☸ abhinivissa 
uppajjanti saṃyojanābhinivesa-vinibandhājjhosānā_ (S.3.187).

.Illustration
====
abhiniveso

steadfastly attached
====

[quote, A.3.369]
____
Once upon a time there was a royal banyan tree called Well Established 
(_suppatiṭṭho nāma nīgrodharājā_) whose five extended branches provided 
a cool and pleasant shade. The royal banyan tree called Well Established was 
steadfastly attached to twelve leagues, and its roots spread to [a further] five

_dvādasayojanāni abhiniveso ahosi pañcayojanāni mulakasantānakānaṃ._
____

.Illustration
====
abhinivisanti

stubbornly adhere
====

[quote, D.2.282]
____
The [religious] world is made up of many and various elements, and whatever of 
these elements that beings stubbornly adhere to, then dogmatically grasping and 
stubbornly adhering they assert 'This alone is true, all else is false.'

_Anekadhātunānādhātu kho devānaminda loko. Tasmiṃ 
anekadhātunānādhātusmiṃ loke yaṃ yadeva sattā dhātuṃ abhinivisanti 
taṃ tadeva thāmasā parāmassa abhinivissa voharanti idameva saccaṃ 
moghamaññan ti._
____

.Illustration
====
abhinivissa

stubbornly adhere
====

• Although questioned, interrogated, and examined by those bhikkhus, the 
bhikkhu Sāti, son of a fisherman, dogmatically grasping and stubbornly 
adhering to that same odious dogmatic view, asserted 'As I understand the 
teaching explained by the Blessed One, it is this personal _viññāṇa_ that 
roams and wanders the round of birth and death, not another.' +
☸ _tadeva pāpakaṃ diṭṭhigataṃ thāmasā parāmassa abhinivissa 
voharati evaṃ vyā kho ahaṃ āvuso bhagavatā dhammaṃ desitaṃ 
ājānāmi yathā tadevidaṃ viññāṇaṃ sandhāvati saṃsarati 
anaññan_ ti (M.1.257).

.Illustration
====
abhinivesā

relentless attachment
====

____
For a _khattiya_ (_khattiyā_), land is his relentless attachment

_paṭhavibhinivesā_
____

____
For a brahman (_brāhmaṇā_), performing sacrifices is his relentless 
attachment

_yaññābhinivesā_
____

____
For a householder (_gahapatikā_), working is his relentless attachment

_kammantābhinivesā_
____

____
For a woman (_itthi_), being without a co-wife is her relentless attachment

_asapattībhinivesā_
____

____
For a thief (_corā_), darkness is his relentless attachment

_andhakārābhinivesā_
____

• For an ascetic (_samaṇā_) possessionlessness is his relentless 
attachment** +
☸** _ākiñcaññābhinivesā_ (A.3.363).

Comment:

To call a woman's wish to be without a co-wife a relentless attachment reflects 
the culture, where being without a co-wife was hard to attain without 
meritorious deeds (_dullabhāni akatapuññena_, S.4.249). The Buddha's father, 
for example, had two wives, the blood sisters Mahāmāyā and Mahāpajāpatī, 
and the bhikkhunī Uppalavaṇṇā was previously a co-wife.

=== Illustrations: nālaṃ+dative

.Illustration
====
nālaṃ

incapable [of affecting]
====

[quote, M.1.517]
____
Some religious teachers explain that there are seven absolute principles: 
earth, water, heat, wind, pleasure, pain, life. These seven principles do not 
move or change or injure one another. They are incapable [of affecting] one 
another's well-being, or ill-being, or well-being-plus-ill-being.

_nālaṃ aññamaññassa sukhāya vā dukkhāya vā sukhadukkhāya vā._
____

IBH: unable to affect one another's pleasure or pain

BB: None is able [to arouse] pleasure or pain or pleasure-and-pain in another.

.Illustration
====
nālaṃ

incapable of
====

Nigrodha the ascetic said:

____
The ascetic Gotama's wisdom is struck down by solitude.

_Suññāgārahatā samaṇassa gotamassa paññā_
____

____
He is out of touch with society.

_aparisāvacaro samaṇo gotamo_
____

[quote, D.3.38]
____
He is incapable of conversation.

_nālaṃ sallāpāya._
____

.Illustration
====
nālaṃ

incapable of
====

[quote, M.1.132]
____
The bhikkhu Ariṭṭha said that 'as I understand the teaching explained by 
the Blessed One, those things called obstructions by the Blessed One are 
incapable of obstructing one who follows them.

_te paṭisevato nālaṃ antarāyāyā ti._
____

.Illustration
====
nālaṃ

unsuited to
====

• All things are unsuited to stubborn attachment +
_sabbe dhammā nālaṃ abhinivesāyā ti_ (M.1.251; S.4.50; A.4.88).

Horner: It is not fitting that there should be inclination toward any 
(psycho-physical) conditions. MLS.1.306).

Bodhi: Nothing is worth adhering to (MLDB p.344).

Bodhi: Nothing is worth holding to (NDB p.1061).

.Illustration
====
nālaṃ

not enough
====

A bhikkhu asked whether 'for those who dispute, maintaining a dogmatic view, is 
criticism all that they bring upon themselves? Do they not also receive 
praise?' The Buddha replied:

[quote, Sn.v.895-6]
____
What praise they receive is trifling, not enough to bring them consolation.

_appaṃ hi etaṃ na alaṃ samāya._
____

.Illustration
====
nālaṃ

will not
====

[quote, A.3.6]
____
When a boy has grown up and has enough wisdom, then his nurse is unconcerned 
about the boy, thinking, 'The boy can now safeguard himself. He will not be 
negligent [in looking after himself]

_Yato ca kho so bhikkhave kumāro vuddho hoti alaṃpañño anapekkhā pana 
bhikkhave dhāti tasmiṃ kumāre hoti attaguttodāni kumāro nālaṃ 
pamādāyā ti._
____

Bodhi: 'won't be heedless'

.Illustration
====
nālaṃ

will not
====

[quote, A.3.6]
____
Similarly, when a bhikkhu has matured, he can safeguard himself. He will not be 
negligently applied [to the practice]

_attaguttodāni bhikkhu nālaṃ pamādāyā ti._
____

BB: 'won't be heedless'

=== Illustrations: nālaṃ+infinitive

.Illustration
====
nālaṃ

incapable of
====

____
That which is called 'mind' or 'cognition' or 'consciousness' (_vuccati 
cittaṃ iti pi mano iti pi viññāṇaṃ itipi_), the ignorant Everyman is 
incapable of being disillusioned with it, of being unattached to it, of being 
liberated from it. For what reason?

_Yañca kho etaṃ bhikkhave vuccati cittaṃ iti pi mano iti pi 
viññāṇaṃ iti pi tatrāssutavā puthujjano nālaṃ nibbindituṃ 
nālaṃ virajjituṃ nālaṃ vimuccituṃ. Taṃ kissa hetu?_
____

[quote, S.2.94]
____
Because for a long time this has been clung to by him, cherished and grasped 
thus: this is "[in reality] mine," this is "[in reality] what I am," this is 
"my [absolute] Selfhood."'

_Dīgharattaṃ hetaṃ bhikkhave assutavato puthujjanassa ajjhositaṃ 
mamāyitaṃ parāmaṭṭhaṃ etaṃ mama eso'hamasmi eso me attā ti._
____

Bodhi: the uninstructed worldling is unable to experience revulsion CDB p.595).

.Illustration
====
nālaṃ

unsuited
====

____
A nurse is unsuited to caring for the sick if he possesses five qualities

_nālaṃ gilānaṃ upaṭṭhātuṃ_
____

1. He incapable of preparing medicine
+
****
_na paṭibalo hoti bhesajjaṃ saṃvidhātuṃ_
****

2. He does not know what is suitable or unsuitable to give to the patient
+
****
_sappayāsappāyaṃ na jānāti asappāyaṃ upanāmeti sappāyaṃ 
apanāmeti._
****

3. He nurses the patient for worldly benefits not with a mind of [unlimited, 
all-encompassing] goodwill.
+
****
_āmisantaro gilānaṃ upaṭṭhahati no mettacitto_
****

4. He is disgusted at having to remove faeces, urine, vomit and spittle.
+
****
_jegucchi hoti uccāraṃ vā passāvaṃ vā vantaṃ vā khelaṃ vā 
nīharituṃ_
****

5. He is unable from time to time to gladden the patient with religious 
discourse.
+
****
_na paṭibalo hoti gilānaṃ kālena kālaṃ dhammiyā kathāya 
sandassetuṃ samādapetuṃ samuttejetuṃ sampahaṃsetuṃ_ (A.3.144).
****

Bodhi: possessing five qualities an attendant is not qualified to take care of 
a patient (NDB p.741).

Hare: possessing five qualities one who waits on the sick is not fit to help 
the sick (GD.3.110).

Reason 3 shows that this cannot be translated 'incapable of caring for the 
sick.'

.Illustration
====
nālaṃ

not fit
====

[quote, M.2.263]
____
What is unlasting is not fit to be delighted in, welcomed, or clung to. 

_yadaniccaṃ taṃ nālaṃ abhinandituṃ nālaṃ abhivadituṃ nālaṃ 
ajjhositun ti._
____

BB: what is impermanent is not worth delighting in (MLDB p.870).

IBH: what is impermanent is not worth rejoicing over (MLS.2.263).

.Illustration
====
nālaṃ

not fit
====

• A bhikkhu is not fit to live in secluded abodes in forests and quiet groves 
if possessed of four things: Thoughts of sensuous pleasure, ill will, and 
maliciousness, or fourthly, if he is void of penetrative discernment, 
dull-witted, an imbecile +
☸ _nālaṃ araññe vanapatthāni pantāni senāsanāni paṭisevituṃ_... 
_Kāmavitakkena vyāpādavitakkena vihiṃsāvitakkena duppañño hoti jaḷo 
eḷamūgo_ (A.2.252).

BB: is not fit to resort to remote lodgings (NDB p.617).

.Illustration
====
nālaṃ

not fit
====

[quote, A.3.146]
____
A bhikkhu is not fit to live apart from the monastic community if he is not 
content with any old robe, almsfood, abode, and therapeutic requisite 
whatsoever, and he abides full of sensuous thought

_nālaṃ saṅghamhā vavakāsituṃ._
____

BB: a bhikkhu is not fit... to live apart from the Saṅgha

.Illustration
====
nālaṃ

not fit
====

[quote, Vin.1.55]
____
A pupil is not fit to be dismissed if he has five qualities: profound devotion 
to and faith in his preceptor, a profound shame of wrongdoing, respect, and 
spiritual development.

_Pañcahi bhikkhave aṅgehi samannāgato saddhivihāriko nālaṃ 
panāmetuṃ._
____

IBH: 'it is not suitable to dismiss him'

.Illustration
====
nālaṃ

not fit
====

[quote, It.38]
____
What is born, brought about, arisen, produced, originated, unenduring ... is 
not fit to be delighted in.

_Jātaṃ bhūtaṃ samuppannaṃ kataṃ saṅkhatamaddhuvaṃ... nālaṃ 
tadabhinandituṃ._
____

.Illustration
====
nālaṃ

not fit, not fitting
====

If a family is possessed of seven qualities,

____
if not visited it is not fit to be visited,

_kulaṃ anupagantvā vā nālaṃ upagantuṃ_
____

____
or if visited, it is not fitting to sit down:

_upagantvā vā nālaṃ upanisīdituṃ_
____

- They do not rise up in an agreeable way.

- They do not pay respects in an agreeable way

- They do not offer a seat in an agreeable way

- etc (A.4.10).

BB: a family that has not yet been approached is not worth approaching, or one 
that has been approached is not worth sitting with. NDB p.1004. But 'worth' 
would mean, by contrast, that families that offer respect and gifts etc. are 
'worth approaching'.

Comment:

- The infinitive is used both actively and passively (PGPL, para.477).

.Illustration
====
nālaṃ

not fitting
====

[quote, M.2.171]
____
A view accepted for any reason may turn out to be either true or false. So 'it 
is not fitting for a wise man who preserves truth to come to the unqualified 
conclusion, "This alone is true, all else is false"'

_saccamanurakkhatā bhāradvāja viññunā purisena nālamettha ekaṃsena 
niṭṭhaṃ gantuṃ idameva saccaṃ moghamaññan ti._
____

BB: 'it is not proper'

.Illustration
====
nālaṃ

would not
====

[quote, Sn.v.217]
____
Whoever living on what is given by others, who would accept food whether the 
finest, or the mediocre, or the left-overs, and who would neither extol nor 
speak disparagingly about it, (_nālaṃ thutuṃ no pi nipaccavādī_) the 
wise know him as a sage

_Yadaggato majjhato sesato vā piṇḍaṃ labhetha paradattūpajīvī +
Nālaṃ thutuṃ nopi nipaccavādī taṃ vāpi dhīrā muniṃ vedayanti._
____

Norman: '[does] not deign to praise and does not speak disparagingly.'

.Illustration
====
nālaṃ

would not
====

[quote, Vin.1.340]
____
These venerables are learned... desirous of training. They would not for my 
sake or for anyone else's sake follow a wrong course through desire, hatred, 
undiscernment of reality, or fear.'

_ime kho āyasmantā bahussutā... sikkhākāmā nālaṃ mamaṃ vā 
kāraṇā aññesaṃ vā karaṇā chandā dosā mohā bhayā agatiṃ 
gantuṃ._
____

Comment:

- Horner: 'it is impossible for them, because of me or because of anyone else.'

_• karaṇā_: 'by means of, through, by (=__hetu__ or _nissāya_)' (PED).

