== Saddhā

=== Renderings

- _saddhā_: faith

- _saddhā_: faith [in the perfection of the Perfect One's transcendent insight]

- _saddha_: faithful

- _saddha_: in faith

- _saddha_: credulous

- _saddha_: faith in [the significance of abandoning spiritually unwholesome 
factors and undertaking] spiritually wholesome factors (the _Iṇa Sutta_, see 
Introduction)

=== Introduction

==== Saddhā: faith

_Saddhā_ can sometimes be rendered simply as faith:

[quote, S.5.221]
____
They would have to go by faith in others about this.

_te tattha paresaṃ saddhāya gaccheyyuṃ._
____

[quote, It.112]
____
Have faith in those arahants of noble discernment.

_Saddahāno arahataṃ ariyapaññāya._
____

[quote, S.3.225]
____
He has faith in [the significance of] these teachings

_ime dhamme evaṃ saddahati._
____

[quote, M.1.141-2]
____
Those who have a degree of faith in me, a degree of affection for me, are all 
destined for heaven.

_yesaṃ mayi saddhāmattaṃ pemamattaṃ sabbe te saggaparāyaṇāti._
____

==== Saddhā: technical sense

In relation to the Buddha _saddhā_ has a technical sense, meaning faith in the 
perfection of his transcendent insight. This is also the case where he is not 
the stated object of _saddhā_ because the definition for _saddhindriyaṃ_ 
shows that in such cases he is still the object:

[quote, S.5.196]
____
And what is the faculty of faith? In this regard, the noble disciple has faith. 
He has faith in the [perfection of the] Perfect One's transcendent insight: 'He 
is indeed the Blessed One, the Arahant, the Perfectly Enlightened One, perfect 
in insightfulness into reality and in conduct, the Sublime One, one who knows 
the world [of phenomena] [according to reality], the unexcelled trainer of men 
to be tamed, the teacher of devas and men, the Enlightened One, the Blessed 
One.'

_Katamañca bhikkhave saddhindriyaṃ idha bhikkhave ariyasāvako saddho hoti 
saddahati tathāgatassa bodhiṃ iti pi so bhagavā arahaṃ sammāsambuddho 
vijjācaraṇasampanno sugato lokavidū anuttaro purisadammasārathī satthā 
devamanussānaṃ buddho bhagavā ti. Idaṃ vuccati bhikkhave saddhindriyaṃ._
____

==== Saddha: adjective or adverb

_Saddha_ can be used as an adjective or adverb, 'faithful' or 'in faith':

[quote, D.2.141]
____
Faithful bhikkhus, bhikkhunīs, laymen and laywomen

_saddhā bhikkhū bhikkhuniyo upāsakā upāsikāyo._
____

[quote, D.1.5]
____
Food given in faith

_saddhādeyyāni bhojanāni._
____

==== Saddha: credulous

_Saddha_ sometimes means credulous:

[quote, Sn.v.853]
____
Not infatuated with objects of pleasure, not given to arrogance, gentle, 
intuitively insightful, not credulous, not filled with disgust;

_Sātiyesu anassāvī atimāne ca no yuto +
Saṇho ca paṭibhānavā na saddho na virajjati._
____

[quote, Dh.v.97]
____
The man who is not credulous... is the highest human.

_Assaddho... yo naro... sa ve uttamaporiso._
____

==== The Iṇa Sutta: faith in [the significance of abandoning spiritually 
unwholesome factors and undertaking] spiritually wholesome factors

In the Iṇa Sutta _saddhā_ has a different meaning, which we will research 
here:

1. A noble disciple who has unshakeable faith in the teaching (_dhamme 
aveccappasādena samannāgato hoti_) has come to the conclusion that:

[quote, S.5.390]
____
The teaching is well explained by the Blessed One, fathomable in this lifetime, 
realisable in the here and now, intriguing, personally applicable, to be 
realised by the wise for themselves._

_svākkhāto bhagavatā dhammo sandiṭṭhiko akāliko ehipassiko opanayiko 
paccattaṃ veditabbo viññūhī ti._
____

In the light of these qualities, the teaching's excellence and effectiveness, 
'unshakeable faith in the Dhamma' means 'unshakeable faith in the [significance 
of the] teaching.'

2. But in the _Iṇa Sutta_ the object of _saddhā natthi_ is _kusalesu 
dhammesu_. For reasons to be explained, we apply the same parenthesis: 
'significance of':

[quote, A.3.352]
____
Anyone who has no faith in [the significance of abandoning spiritually 
unwholesome factors and undertaking] spiritually wholesome factors.

_yassa kassaci saddhā natthi kusalesu dhammesu._
____

3. Applying the same parentheses, i.e. '[significance of],' would only be 
justified if 'the teaching' in Quote 1 concerns 'the abandoning of spiritually 
unwholesome factors and undertaking of spiritually wholesome factors' in Quote 
2. Which it does:

[quote, Dh.v.183]
____
The refraining from everything unvirtuous; the undertaking of what is 
spiritually wholesome; the purification of one's mind: this is the training 
system of the Buddhas.

_Sabbapāpassa akaraṇaṃ kusalassa upasampadā +
Sacittapariyodapanaṃ etaṃ buddhānaṃ sāsanaṃ._
____

4. According to our parenthesis, spiritually unwholesome factors are 
'abandoned' and spiritually wholesome factors are 'undertaken'. The parentheses 
come from these two quotes:

[quote, S.3.8]
____
The Blessed One praises the abandonment of spiritually unwholesome factors.

_bhagavā akusalānaṃ dhammānaṃ pahānaṃ vaṇṇeti._
____

[quote, S.3.9]
____
The Blessed One praises the undertaking of spiritually wholesome factors.

_bhagavā kusalānaṃ dhammānaṃ upasampadaṃ vaṇṇetī ti._
____

=== Illustrations

.Illustration
====
saddhā

faith [in the perfection of the Perfect One's transcendent insight]
====

____
And what is the proximate cause for gladness? Faith [in the perfection of the 
Perfect One's transcendent insight], one should reply.

_Kā ca bhikkhave pāmujjassa upanisā? Saddhātissa vacanīyaṃ._
____

[quote, S.2.30]
____
And what is the proximate cause for faith [in the perfection of the Perfect 
One's transcendent insight]? Suffering, one should reply._

_Kā ca bhikkhave saddhāya upanisā? Dukkhan tissa vacanīyaṃ._
____

.Illustration
====
saddhā

faith [in the perfection of the Perfect One's transcendent insight]
====

[quote, S.5.225]
____
It is indeed to be expected, bhante, that a noble disciple who has faith [in 
the perfection of the Perfect One's transcendent insight] will dwell 
energetically applied to the abandoning of spiritually unwholesome factors and 
the undertaking of spiritually wholesome factors.

_saddhassa hi bhante ariyasāvakassa etaṃ pāṭikaṅkhaṃ yaṃ 
āraddhaviriyo viharissati akusalānaṃ dhammānaṃ pahānāya kusalānaṃ 
dhammānaṃ upasampadāya._
____

.Illustration
====
saddhā

faith [in the perfection of the Perfect One's transcendent insight]
====

[quote, S.1.196]
____
Then I saw the Perfectly Enlightened One and faith [in the perfection of the 
Perfect One's transcendent insight] arose within me.

_Athaddasāma sambuddhaṃ saddhā no udapajjatha._
____

.Illustration
====
saddho

faith [in the perfection of the Perfect One's transcendent insight]
====

[quote, A.3.7]
____
A bhikkhu with no faith [in the perfection of the Perfect One's transcendent 
insight] falls away. He is not established in this true teaching.

_Assaddho bhikkhave bhikkhu cavati nappatiṭṭhāti saddhamme._
____

[quote, A.3.7]
____
A bhikkhu with faith [in the perfection of the Perfect One's transcendent 
insight] does not fall away. He is established in this true teaching.

_Saddho bhikkhave bhikkhu na cavati patiṭṭhāti saddhamme._
____

.Illustration
====
saddhā

faith [in the perfection of the Perfect One's transcendent insight]
====

____
As the Blessed One explained the teaching to me with its increasingly higher 
and more sublime levels, concerning what is inwardly dark and bright with their 
correlative combinations, thus through transcendent insight into a certain one 
of those teachings, I came to a conclusion about the teachings. I gained faith 
in the Teacher thus "The Blessed One is perfectly enlightened. The teaching is 
well explained by the Blessed One. The community of disciples is applied to an 
excellent practice.'

_Yathā yathā me āvuso bhagavā dhammaṃ deseti uttaruttariṃ 
paṇītapaṇītaṃ kaṇhasukkasappaṭibhāgaṃ tathā tathāhaṃ 
tasmiṃ dhamme abhiññāya idhekaccaṃ dhammaṃ dhammesu 
niṭṭhamagamaṃ satthari pasīdiṃ sammā sambuddho bhagavā svākkhāto 
bhagavatā dhammo supaṭipanno saṅgho ti._
____

[quote, M.1.320]
____
When one's faith in the [perfection of the] Perfect One's [transcendent 
insight] is settled, rooted, and established, and described in these terms, 
words, and phrases, then one's faith is said to be supported by reasons, rooted 
in vision [of things according to reality], and firm. It is not shakeable by 
any ascetic, Brahmanist, deva, māra, or brahmā, or by anyone in the world.

_Yassa kassa ci bhikkhave imehi ākārehi imehi padehi imehi vyañjanehi 
tathāgate saddhā niviṭṭhā hoti mūlajātā patiṭṭhitā ayaṃ 
vuccatī bhikkhave ākāravatī saddhā dassanamūlikā daḷhā asaṃhāriyā 
samaṇena vā brāhmaṇena vā devena vā mārena vā brahmunā vā kenaci 
vā lokasmiṃ._
____

