== Sakyaputtiya

=== Renderings

- _sakyaputta_ (for bhikkhus): young Sakyan bhikkhu

- _sakyaputta_ (for the Buddha): the Sakyans' Son

- _sakyaputtiya_: disciple of the Sakyans' Son

- _sakyadhītā_ (bhikkhunīs): [spiritual] daughter of the Sakyan

=== Introduction

==== Sakyaputto: Sakyan bhikkhus

_Sakyaputto_ is a term reserved for Sakyan bhikkhus. For example, Upanando 
Sakyaputto, Hatthako Sakyaputto, and others.

Why were Sakyan bhikkhus called _putto_? Perhaps they were much younger than 
other ascetics, especially in the early years of the Buddha's ministry. The 
Buddha was so much younger than contemporary religious teachers that King 
Pasenadi doubted he was enlightened at all (S.1.68). If so, then _sakyaputto_ 
does not mean 'son of the Sakyan clan' but 'young Sakyan bhikkhu.' This is in 
accordance with Bhikkhu Bodhi's rendering of _devaputta_ as 'young deva.' He 
says _devaputtas_ are 'young devas newly arisen in their respective heavenly 
planes' (CDB p.75).

Only bhikkhus of the Sakyan clan were given the -_putto_ suffix, not other 
clans.

==== Gotamo Sakyaputto: shades of glory

But Gotamo Sakyaputto could not possibly mean 'Gotama, the young Sakyan 
bhikkhu.' Here _sakyaputto_ has shades of glory. We treat it accordingly: 'the 
Sakyans' Son':

[quote, D.3.196]
____
Glory to Aṅgīrasa, the Sakyans' radiant Son.

_aṅgīrasassa namatthu sakyaputtassa sirīmato._
____

==== Sakyaputtiya: disciple of the Sakyans' Son

_Sakyaputtiya_ is a compound, says PED: _sakyaputta+iya_ 'belonging to the 
Sakyans' Son,' which we take as 'disciple of the Sakyans' Son.'

==== Bhikkhunī: [spiritual] daughter of the Sakyan

The comparable term for bhikkhunī is _samaṇī sakyadhītā_ (Vin.4.220): 
'female ascetic, [spiritual] daughter of the Sakyan.' The Buddha likewise 
called bhikkhus his spiritual sons:

[quote, It.101]
____
You are my spiritual sons, born of my mouth, born of the teaching.

_Tassa me tumhe puttā orasā mukhato jātā dhammajā._
____

_Orasa_ means 'true or legitimate,' says DOP.

=== Illustrations

.Illustration
====
sakko

the Sakyan
====

[quote, S.5.403]
____
Nandiya the Sakyan approached the Blessed One, venerated him, and sat down at a 
respectful distance.

_nandiyo sakko yena bhagavā tenupasaṅkami. Upasaṅkamitvā bhagavantaṃ 
abhivādetvā ekamantaṃ nisīdi._
____

.Illustration
====
sakyaputtā

young Sakyan bhikkhus
====

____
In the Eastern Bamboo Grove young Sakyan bhikkhus, companions,

_Pācīnavaṃsadāyamhi sakyaputtā sahāyakā_
____

[quote, Th.v.155]
____
Having given up no small store of wealth, delighted with whatever offerings 
enter their almsbowls

_Pahāyānappake bhoge uñchāpattāgate ratā._
____

.Illustration
====
sakyaputto

the young Sakyan bhikkhu
====

[quote, Vin.4.2]
____
Once, Hatthaka, the young Sakyan bhikkhu, was overthrown in debate.

_Tena kho pana samayena hatthako sakyaputto vādakkhitto hoti._
____

.Illustration
====
sakyaputto

the Sakyans' Son
====

[quote, M.1.502]
____
The ascetic Gotama, the Sakyans' Son, who went forth [into the ascetic life] 
from a Sakyan clan

_samaṇo gotamo sakyaputto sakyakulā pabbajito._
____

.Illustration
====
sakyaputta

young Sakyan bhikkhu; sakyaputtiyā, disciples of the Sakyans' Son
====

[quote, Vin.3.237]
____
Having given the young Sakyan bhikkhu, Venerable Upananda, a _kahāpaṇa_ of 
money, that man complained, muttered, and grumbled that 'Just as we accept gold 
and silver, so do these ascetic disciples of the Sakyans' Son.

_Atha kho so puriso āyasmato upanandassa sakyaputtassa kahāpaṇaṃ datvā 
ujjhāyati khīyati vipāceti: yatheva mayaṃ rūpiyaṃ paṭiggaṇhāma 
evameva ime samaṇā sakyaputtiyā rūpiyaṃ paṭiggaṇhantī ti._
____

.Illustration
====
sakyaputtiyo

disciple of the Sakyans' Son
====

[quote, D.3.7]
____
Do you, O worthless man, claim to be an ascetic disciple of the Sakyans' Son?

_Tvampi nāma moghapurisa samaṇo sakyaputtiyo paṭijānissī ti?'._
____

.Illustration
====
sakyaputtiyā

disciples of the Sakyans' Son
====

[quote, Ud.44]
____
These ascetic disciples of the Sakyans' Son are shameless

_alajjino ime samaṇā sakyaputtiyā._
____

.Illustration
====
sakyaputtiyo: disciple of the Sakyans' Son

[quote

Vin.1.96]
====

____
That bhikkhu who indulges in sexual intercourse becomes not an ascetic, not a 
disciple of the Sakyans' Son.

_Yo bhikkhu methunaṃ dhammaṃ paṭisevati assamaṇo hoti asakyaputtiyo._
____

.Illustration
====
sakyaputtiya

disciple of the Sakyans' Son
====

[quote, S.2.272]
____
There is no gratitude and thankfulness in some person here claiming to be a 
disciple of the Sakyans' Son.

_Na tveva idhekacce sakyaputtiyapaṭiññe siyā kāci kataññutā 
kataveditā._
____

.Illustration
====
sakyaputtiya

disciples of the Sakyans' Son
====

____
Who is here, friend?

_Ko'ttha āvuso ti?_
____

____
Friend, I am a bhikkhu.

_Ahamāvuso bhikkhū ti._
____

____
Of which group of bhikkhus, friend?

_Katamesaṃ āvuso bhikkhūnan ti?_
____

[quote, A.5.196]
____
The ascetic disciples of the Sakyans' Son, friend.

_Samaṇānaṃ āvuso sakyaputtiyānan ti._
____

