== Sambhava

=== Renderings

- _sambhava_: arising

- _sambhava_: arisen

- _sambhava_: spiritual maturation

- _sambhava_: individual existence

- _sambhava_: state of individual existence

- _sambhavesīnaṃ_: those about to arise [into new existence]

=== Illustrations

.Illustration
====
sambhavo

arising
====

[quote, A.3.411]
____
Sensation is the basis for the arising of sensuous yearnings

_phasso bhikkhave kāmānaṃ nidānasambhavo._
____

.Illustration
====
sambhavo

arising
====

[quote, A.5.262]
____
Greed is a basis for the arising of karmically consequential deeds.

_lobho kammanidānasambhavo._
____

.Illustration
====
sambhavaṃ

arising
====

[quote, A.2.10]
____
The arising of suffering is due to craving,

_taṇhā dukkhassa sambhavaṃ._
____

Comment:

Norman says the alternative reading _taṇhaṃ dukkhassa sambhavaṃ_ 
'probably arose from the inability of the scribes to fit the seeming nominative 
_taṇhā_ into the structure of the sentence. This problem disappears when we 
realise that _taṇhā_ is a truncated instrumental = _taṇhāya'_ (Group of 
Discourses n.741). This view is supported by the commentary (which says _etaṃ 
dukkhassa sambhavaṃ taṇhāya ādīnavaṃ ñatvā_) and also by the usual 
meaning of _sambhava,_ which is 'arising' not 'origin.'

.Illustration
====
sambhavo

arising
====

[quote, Ud.33]
____
Suffering arises because of attachment. With the destruction of all grasping, 
there is no arising of suffering.

_upadhiṃ paṭicca dukkhamidaṃ sambhoti +
sabbūpādānakkhayā natthi dukkhassa sambhavo._
____

.Illustration
====
sambhavo

arising
====

[quote, M.1.258]
____
Worthless man, have I not in many ways stated that _viññāṇa_ is 
dependently arisen; and that without necessary conditions there is no arising 
of _viññāṇa_

_anekapariyāyena paṭiccasamuppannaṃ viññāṇaṃ vuttaṃ aññatra 
paccayā natthi viññāṇassa sambhavo ti._
____

.Illustration
====
sambhava

arising
====

[quote, A.5.107]
____
Knowing the arising and cessation of the world [of phenomena] [according to 
reality], our minds will be imbued with that perception.

_Lokassa sambhavañca vibhavañca ñatvā +
taṃ saññā paricitañca no cittaṃ bhavissati._
____

.Illustration
====
sambhavaṃ

arising
====

[quote, Sn.v.1115]
____
Knowing the arising of nonexistence [according to reality], and knowing that 
spiritually fettering delight is a tie to individual existence, knowing this 
thus, then he sees this matter [according to reality].

_Ākiñcaññasambhavaṃ ñatvā nandi saṃyojanaṃ iti +
Evametaṃ abhiññāya tato tattha vipassati._
____

.Illustration
====
sambhavā

arise from
====

[quote, A.4.339]
____
All things arise from the paying of attention.

_manasikārasambhavā sabbe dhammā._
____

.Illustration
====
sambhavo

arisen from
====

[quote, D.1.34]
____
The [absolute] Selfhood is material, composed of the four great material 
phenomena, and arisen from parents.

_attā rūpī cātumahābhūtiko mātāpettikasambhavo._
____

.Illustration
====
sambhavaṃ

arisen
====

[quote, Sn.v.235]
____
Previous [karmically consequential deeds] are nullified, and no new [karmically 
consequential conduct] is arisen;

_Khīṇaṃ purāṇaṃ navaṃ natthi sambhavaṃ._
____

.Illustration
====
sambhavaṃ

arisen
====

____
-- Bhikkhus, do you see, 'This is brought about?'

_bhūtamidan ti bhikkhave passathā ti?_
____

-- Yes, bhante

____
-- Bhikkhus, do you see: 'It is arisen with that as its nourishing condition'?

_tadāhārasambhavan ti bhikkhave passathā ti?_
____

-- Yes, bhante (M.1.260).

.Illustration
====
sambhavaṃ

arisen
====

[quote, Dh.v.161]
____
Demerit generated by his ego, born from his ego, arisen from his ego, crushes 
the fool like a diamond crushes a hard gem.

_Attanā va kataṃ pāpaṃ attajaṃ attasambhavaṃ +
Abhimanthati dummedhaṃ vajiraṃ v'asmamayaṃ maṇiṃ._
____

.Illustration
====
sambhavesīnaṃ

those about to arise [into new existence]
====

[quote, S.2.101]
____
Bhikkhus, there are these four kinds of existential nourishment for the 
maintenance of beings that have been brought into existence and for the 
assistance of those about to arise [into new existence]. What four?

_Cattārome bhikkhave āhārā bhūtānaṃ vā sattānaṃ ṭhitiyā 
sambhavesīnaṃ vā anuggahāya._
____

Comment:

Norman views _sambhavesīnaṃ_ as the future active participle in -_esin_ 
(Elders Verses I, n.527), to be translated with the words 'about to.'

.Illustration
====
sambhavā

spiritual maturation
====

____
Seven things lead to a layperson's spiritual ruination

_Sattime bhikkhave upāsakassa parābhavā. Katame satta:_
____

____
He fails to see the bhikkhus;

_bhikkhudassanaṃ hāpeti_
____

____
Seven things lead to a layperson's spiritual maturation.

_Sattime bhikkhave upāsakassa sambhavā. Katame satta:_
____

[quote, A.4.27]
____
He does not fail to see the bhikkhus.

_Bhikkhudassanaṃ na hāpeti._
____

.Illustration
====
sambhavaṃ

individual existence
====

____
Then the Blessed One, mindful and fully conscious, at the Cāpāla Shrine 
relinquished the aspiration for further life.

_Atha kho bhagavā cāpāle cetiye sato sampajāno āyusaṅkhāraṃ ossajji_
____

Then a great earthquake occurred, frightening and terrifying, and peals of 
thunder shook the sky. Then the Blessed One on that occasion spoke this 
inspired utterance:

• Comparing the incomparable with individual existence, the Sage relinquished 
the aspiration for [renewed] states of individual existence +
_Tulamatulañca sambhavaṃ +
Bhavasaṅkhāramavassajji muni_

• Finding inward delight, inwardly collected, he shattered individual 
existence like a shell of armour +
_Abindi kavacamivattasambhavaṃ ti_ (Ud.64; S.5.263).

COMMENT

Commentary: _Atulañca sambhavan ti nibbānañceva bhavañca_.

.Illustration
====
sambhavā

states of individual existence; sambhavaṃ, arisen
====

[quote, Th.v.260]
____
States of individual existence are well-known to be without substantial 
reality, originated, unstable, always driven on. Knowing [that all] this arises 
from the ego, being mindful, I attained peace.

_Sambhavā suviditā asārakā saṅkhatā pacalitā saderitā +
Taṃ viditvā-m-ahaṃ attasambhavaṃ santimeva satimā samajjhagan ti._
____

Commentary: _sambhavā ti bhavā_

