== Sampanna

=== Renderings

- _sampanna_, convenient

- _sampanna_, splendid

- _sampanna_, excellent

- _sampanna_, perfectly

- _sampanna_, utterly

- _sampanna_, perfect

- _sampanna_, endowed with

- _sampanna_, full of

- _ākappasampanno_, perfect in behaviour

=== Illustrations

.Illustration
====
sampannaṃ

convenient
====

____
King Bimbisara thought 'Where could the Blessed One stay that would be neither 
too far from the village nor too near,

_kattha nu kho bhagavā vihareyya yaṃ assa gāmato neva atidure na accāsanna_
____

____
convenient for coming and going,

_gamanāgamanasampannaṃ_
____

[quote, Vin.1.39]
____
accessible for people whenever they want,

_aṭṭhikānaṃ aṭṭhikānaṃ manussānaṃ abhīkkamanīyaṃ._
____

Comment:

[quote, A.5.16]
____
This use of _sampanna_ is unusual_._ Likewise, an ideal residence should be 
neither too far from the village nor too near, and should be convenient for 
coming and going.

_Idha bhikkhave senāsanaṃ nātidūraṃ hoti nāccāsannaṃ 
gamanāgamanasampannaṃ._
____

.Illustration
====
sampanne

splendid
====

[quote, Vin.2.256]
____
Disease known as mildew attacks a splendid field of corn

_sampanne sālikkhette setaṭṭhikā nāma rogajāti nipatati._
____

.Illustration
====
sampanno

excellent
====

[quote, S.2.110]
____
A bronze cup of a beverage having an excellent colour, aroma, and flavour, but 
mixed with poison.

__āpānīyakaṃso vaṇṇasampanno gandhasampanno rasasampanno so ca kho 
visena saṃsaṭṭho._
____

.Illustration
====
sampanna

excellent
====

[quote, Th.v.1272]
____
Excellent explanation

_sampannaveyyākaraṇaṃ._
____

.Illustration
====
sampannaṃ excellent

[quote

Vin.2.196]
====

____
Who does not like what is excellent? Who does not like what is delicious?

_kassa sampannaṃ na manāpaṃ kassa sādu na ruccati ti._
____

COMMENT

Strictly: 'For whom is what is excellent not pleasing.'

.Illustration
====
sampanno

excellent
====

[quote, D.1.76]
____
A gem, a beryl, exquisite, of genuine quality, a well-cut octahedron, 
translucent, limpid, unblemished, excellent in every respect.

_maṇi veḷuriyo subho jātimā aṭṭhaṃso suparikammakato accho 
vippasanno anāvilo sabbākārasampanno._
____

.Illustration
====
sampanno

utterly
====

[quote, S.1.122]
____
That wise man was utterly resolute, meditative, always taking delight in 
meditation, applying himself day and night without attachment even to life.

_So dhīro dhitisampanno jhāyī jhānarato sadā +
Ahorattaṃ anuyuñjaṃ jīvitaṃ anikāmayaṃ._
____

.Illustration
====
sampanno

endowed with
====

____
Possessed of three qualities (_tīhi aṅgehi samannāgato_), a shopkeeper 
quickly attains greatness and increases his wealth: he is clear-sighted, 
capable, and endowed with rich resources.

_cakkhumā ca hoti vidhuro ca nissayasampanno ca_
____

And how is a shopkeeper endowed with rich resources? The shopkeeper becomes 
known to wealthy householders as capable of providing interest on loans. They 
offer him money, telling him to trade with it, support his family, and pay it 
back with interest in due course (A.1.117).

.Illustration
====
sampanno

endowed with
====

[quote, It.14-16]
____
A Wheel-turning monarch, faring righteously, a King of Righteousness, a 
conqueror of the four corners of the earth, maintaining stable control over the 
countryside, endowed with the seven Treasures.

_satataratanasampanno._
____

.Illustration
====
sampanno

endowed with
====

[quote, Thī.v.251]
____
A master of the three final knowledges, endowed with profound knowledge, fully 
versed in profound knowledge, spiritually cleansed.

_Tevijjo vedasampanno sottiyo camhi nahātako ti._
____

.Illustration
====
sampanno

full of
====

[quote, A.3.43]
____
A large tree with a massive trunk, with branches, leaves, fruit, strong roots, 
and full of fruit, is a resource for many birds.

_Sākhāpattaphalūpeto khandhimā ca mahādumo +
Mūlavā phalasampanno patiṭṭhā hoti pakkhinaṃ._
____

.Illustration
====
anākappasampannā

badly behaved
====

[quote, Vin.1.44]
____
Now at that time bhikkhus, being without preceptors, not being advised and 
instructed, walked for almsfood wrongly dressed, wrongly clothed, and badly 
behaved.

_anupajjhāyakā anovadiyamānā ananusāsiyamānā dunnivatthā duppārutā 
anākappasampannā piṇḍāya caranti._
____

Comment:

The bhikkhus were asking donors for food without invitation to do so, and were 
eating noisily.

.Illustration
====
anākappasampannā

badly behaved
====

[quote, Vin.2.211-2]
____
Now at that time the Group-of-Six bhikkhus, went into a refectory wrongly 
dressed, wrongly clothed, and badly behaved

_dunnivatthā duppārutā anākappasampannā bhattaggaṃ gacchanti._
____

Comment:

The bhikkhus were crowding other bhikkhus, and sitting in the village on their 
outer robes.

.Illustration
====
ākappasampanno

perfect in behaviour
====

[quote, A.3.78]
____
It is rare to find one gone forth in old age who is perfect in behaviour;

_dullabho ākappasampanno._
____

.Illustration
====
na sampanno

imperfect
====

[quote, A.3.261]
____
A resident bhikkhu is not to be esteemed (_āvāsiko bhikkhu abhāvanīyo 
hoti_) if he is imperfect in behaviour and in the practice of observances;

_Na ākappasampanno hoti na vattasampanno._
____

Comment:

Regarding the practice of observances, for example:

[quote, Vin.2.211]
____
'Bhikkhus, I will lay down an observance for bhikkhus who are leaving a 
residence, which should be observed by bhikkhus who are leaving a residence.'

_Tena hi bhikkhave gamikānaṃ bhikkhūnaṃ vattaṃ paññāpessāmi yathā 
gamikehi bhikkhū hi vattitabbaṃ._
____

.Illustration
====
sampanno

perfectly, perfect
====

[quote, Vin.4.245]
____
Now at that time several bhikkhunīs, having spent the rains in a 
village-residence, went to Sāvatthī, practising the observances perfectly, 
perfect in deportment, but badly dressed, wearing shabby robes.

_vattasampannā iriyāpathasampannā duccoḷā lūkhacīvarā._
____

.Illustration
====
sampanno

perfectly
====

____
Beings who perceive [only] what can be expressed and are entrenched in what can 
be expressed, not profoundly understanding what is expressed, they come under 
the yoke of death;

_Akkheyyasaññino sattā akkheyyasmiṃ patiṭṭhitā. +
Akkheyyaṃ apariññāya yogamāyanti maccuno._
____

____
But if one profoundly understands what can be expressed, and does not think 'I 
am the expressor,' the mind's liberation is achieved, the unsurpassed Peaceful 
State.

_Akkheyyañca pariññāya akkhātāraṃ na maññati +
Phūṭṭho vimokkho manasā santipadamanuttaraṃ._
____

[quote, It.53]
____
Perfectly understanding what can be expressed, the Peaceful One delights in the 
Peaceful State.

_Sa ce akkheyyasampanno santo santipade rato._
____

.Illustration
====
sampanno

perfect
====

[quote, S.5.199]
____
He is indeed the Blessed One, the Arahant, the Perfectly Enlightened One, 
perfect in insightfulness into reality and in conduct.

_iti pi so bhagavā arahaṃ sammāsambuddho vijjācaraṇasampanno._
____

.Illustration
====
sampanno

perfect
====

____
-- 'On what grounds, bhante, is one perfect [in the development of] the [five] 
spiritual faculties?'

_kittāvatā nu kho bhante indriyasampanno hotī ti?_
____

____
-- 'In this regard, bhikkhu, a bhikkhu develops the faculty of faith, the 
faculty of energetic application [to the practice], the faculty of mindfulness, 
the faculty of inward collectedness, and the faculty of penetrative discernment 
which lead to inward peace and enlightenment'

_idha bhikkhu bhikkhu saddhindriyaṃ... viriyindriyaṃ... satindriyaṃ... 
samādhindriyaṃ... paññindriyaṃ bhāveti upasamagāmiṃ 
sambodhagāmiṃ._
____

[quote, S.5.203]
____
'On these grounds one is perfect [in the development of] the [five] spiritual 
faculties.'

_Ettāvatā kho bhikkhu indriyasampanno hotī ti._
____

.Illustration
====
sampanno

perfect
====

____
-- 'On what grounds, bhante, is one perfect [in the development of] the [six] 
sense faculties?'

_indriyasampanno hotī ti?_
____

____
-- 'If, bhikkhu, one abides contemplating the [co-conditional] arising and 
disappearance of the faculty of sight... the faculty of mental cognisance, one 
is disillusioned with the faculty of mental cognisance

_Cakkhundriye ce bhikkhu udayabbayānupassī viharanto cakkhundriye 
nibbindati... manindriye ce bhikkhu udayabbayānupassī viharanto manindriye 
nibbindati._
____

____
... Being disillusioned [with originated phenomena], one is unattached [to 
originated phenomena]. Being unattached [to originated phenomena] one is 
liberated [from perceptually obscuring states].

_nibbindaṃ virajjati virāgā vimuccati._
____

[quote, S.4.140]
____
... On these grounds one is perfect [in the development of] the [six] sense 
faculties._

_ettāvatā kho bhikkhu indriyasampanno hotī ti._
____

.Illustration
====
sampanno

perfect
====

[quote, Sn.p.115]
____
The young brahman Vāseṭṭha said: 'When one is perfect in observances and 
practices, on this account one is a Brahman.'

_Vāseṭṭho māṇavo evamāha yato kho bho sīlavā ca hoti vattasampanno 
ca ettāvatā kho brāhmaṇo hoti ti._
____

Comment:

_Sīlavā ca hoti vattasampanno_: 'perfect in observances and practices.' We 
take this as _sīlabbatasampanno_, for notes on which see IGPT sv _Sīlabbata_. 
The term _sīlabbatasampanno_ occurs at A.1.168.

.Illustration
====
sampanno

perfect
====

[quote, A.4.352]
____
A bhikkhu is virtuous, abides restrained [in conduct] within the constraints of 
the rules of discipline. He is perfect in conduct and sphere of personal 
application, seeing danger in the slightest wrongdoing.

_bhikkhu sīlavā hoti pātimokkhasaṃvarasaṃvuto viharati 
ācāragocarasampanno aṇumattesu vajjesu bhayadassāvī._
____

.Illustration
====
sampannā

perfect
====

Bhikkhus, those bhikkhus who are

____
perfect in virtue

_sīlasampannā_
____

____
perfect in inward collectedness

_samādhisampannā_
____

____
perfect in wisdom

_paññāsampannā_
____

____
perfect in liberation [from perceptually obscuring states]

_vimuttisampannā_
____

____
perfect in the knowledge and vision that follows liberation [from perceptually 
obscuring states]

_vimuttiñāṇadassanasampannā_
____

even the sight of those bhikkhus is helpful, I declare (S.5.67).

.Illustration
====
sampannassa

perfect in
====

____
For one who is virtuous, perfect in virtue, there is no need to harbour the 
aspiration: 'May freedom from an uneasy conscience arise in me.

_Sīlavato bhikkhave sīlasampannassa na cetanāya karaṇīyaṃ 
avippaṭisāro me uppajjatū ti._
____

[quote, A.5.2]
____
It is quite natural that this should happen.

_Dhammatā esā bhikkhave yaṃ sīlavato sīlasampannassa avippaṭisāro 
uppajjati._
____

.Illustration
====
sampannassa

perfect in
====

[quote, S.5.91]
____
When a bhikkhu is perfect in proper contemplation, it is to be expected that he 
will develop and cultivate the seven factors of enlightenment.

_yoniso manasikārasampannassetaṃ bhikkhave bhikkhuno pāṭikaṅkhaṃ 
satta bojjhaṅge bhāvessati._
____

.Illustration
====
sampanna

perfect in
====

____
Now, an individual with which ten qualities is one whom I describe as perfect 
in what is spiritually wholesome, of the highest spiritual proficiency, an 
invincible ascetic who has attained the supreme attainment?

_Katamehi cāhaṃ thapati dasahi dhammehi samannāgataṃ purisapuggalaṃ 
paññāpemi sampannakusalaṃ paramakusalaṃ uttamapattipattaṃ samaṇaṃ 
ayojjhaṃ_
____

In this regard a bhikkhu is possessed of the right perception [of reality] of a 
finished disciple, the right thought of a finished disciple, the right 
speech... the right conduct... the right means of livelihood... the right 
endeavour... the right mindfulness... the right inward collectedness... the 
right knowledge [of things according to reality]... the right liberation [from 
perceptually obscuring states] of a finished disciple.

_• asekhāya sammādiṭṭhiyā samannāgato hoti_

_• asekhāya sammāvimuttiyā samannāgato hoti_ (M.2.29).

.Illustration
====
sampannassa

perfect
====

[quote, S.5.30]
____
When a bhikkhu is perfect in the aspiration [to abandon spiritually unwholesome 
factors and acquire spiritually wholesome factors], it is to be expected that 
he will develop and cultivate this noble eightfold path.

_Chandasampannassetaṃ bhikkhave bhikkhuno pāṭikaṅkhaṃ ariyaṃ 
aṭṭhaṅgikaṃ maggaṃ bhāvessati ariyaṃ aṭṭhaṅgikaṃ maggaṃ 
bahulīkarissatī ti._
____

The parenthesis comes from these quotes:

1. the Blessed One praises the abandonment of spiritually unwholesome factors.
+
****
_bhagavā akusalānaṃ dhammānaṃ pahānaṃ vaṇṇeti_ (S.3.8).
****

2. the Blessed One praises the undertaking of spiritually wholesome factors.
+
****
_bhagavā kusalānaṃ dhammānaṃ upasampadaṃ vaṇṇetī ti_ (S.3.9).
****

Commentary: _Chandasampadā ti kusalakattukamyatāchando_.

