== Samudaya

=== Renderings

- _samudaya_: origination

- _samudaya_: [co-conditional] origination

- _samudaya_: origin

- _samudaya_: originated

- _samudayadhamma_: of an originated nature

- _samudayadhamma_: [co-conditional] origination

=== Introduction

==== [Co-conditional] parenthesis

'The 'co-conditional' parenthesis is suggested by the following quote:

• Bhikkhus, I will teach you the [co-conditional] origination and 
&#8203;[co-conditional] vanishing of the four bases of mindfulness. Please listen. +
_catunnaṃ bhikkhave satipaṭṭhānānaṃ samudayañca atthaṅgamañca 
desissāmi. Taṃ suṇātha._

1. With the origination of food comes the origination of the body. With the 
ending of food comes the vanishing of the body.
+
****
_Āhārasamudayā kāyassa samudayo āhāranirodhā kāyassa atthaṅgamo._
****

2. With the origination of sensation comes the origination of sense 
impressions. With the ending of sensation comes the vanishing of sense 
impressions.
+
****
_Phassasamudayā vedanānaṃ samudayo. Phassanirodhā vedanānaṃ 
atthaṅgamo._
****

3. With the origination of denomination-and-bodily-form comes the origination 
of the mind. With the ending of denomination-and-bodily-form comes the 
vanishing of the mind.
+
****
_Nāmarūpasamudayā cittassa samudayo. Nāmarūpanirodhā cittassa 
atthaṅgamo._
****

4. With the origination of attention comes the origination of objects of the 
systematic teachings. With the ending of attention comes the vanishing of 
objects of the systematic teachings.
+
****
_Manasikārasamudayā dhammānaṃ samudayo. Manasikāranirodhā dhammānaṃ 
atthaṅgamo ti_ (S.5.184).
****

=== Illustrations

.Illustration
====
samudayo

origin
====

[quote, M.1.191]
____
The fondness, clinging, attraction, and cleaving within these five grasped 
aggregates is the origin of suffering._

_Yo imesu pañcasupādānakkhandhesu chando ālayo anunayo ajjhosānaṃ so 
dukkhasamudayo._
____

.Illustration
====
samudayo

origin
====

____
What is the noble truth of the origin of suffering?

_dukkhasamudayo ariyasaccaṃ_
____

[quote, M.3.251]
____
It is this craving that leads to renewed states of individual existence, 
accompanied by spiritually fettering delight and attachment, taking delight in 
this and that... This is called the origin of suffering.

_yāyaṃ taṇhā ponobhavikā nandirāgasahagatā tatra tatrābhinandinī... 
Idaṃ vuccatāvuso dukkhasamudayo ariyasaccaṃ._
____

.Illustration
====
samudayo

origin
====

[quote, S.2.108]
____
Attachment has craving as its basis, craving as its origin; it is generated and 
produced by craving.

_upadhi taṇhānidāno taṇhāsamudayo taṇhājātiko taṇhāpabhavo._
____

.Illustration
====
samudayā

origin
====

[quote, A.4.339]
____
Sensation is the origin of all things.

_phassasamudayā sabbe dhammā._
____

.Illustration
====
samudayāya

origination; samudayaṃ, originated
====

____
Bhikkhus, there are three bases for the arising of karmically consequential 
deeds. What three?_

_tīṇimāni bhikkhave nidānāni kammānaṃ samudayāya. Katamāni tīṇi._
____

____
Greed is a basis for the origination of karmically consequential deeds.

_lobho nidānaṃ kammānaṃ samudayāya_
____

____
Hatred is a basis for the origination of karmically consequential deeds.

_doso nidānaṃ kammānaṃ samudayāya_
____

• Undiscernment of reality is a basis for the origination of karmically 
consequential deeds. +
_moho nidānaṃ kammānaṃ samudayāya._

[quote, A.1.134]
____
Karmically consequential conduct produced from greed, born of greed, due to 
greed, originated by greed bears fruit wherever the rebirth of one's 
individuality occurs.

_Yaṃ bhikkhave lobhapakataṃ kammaṃ lobhajaṃ lobhanidānaṃ 
lobhasamudayaṃ yatthassa attabhāvo nibbattati tattha taṃ kammaṃ 
vipaccati._
____

.Illustration
====
samudayo

origination
====

____
With the origination of grasping comes the origination of individual existence

_upādānasamudayā bhavasamudayo_
____

[quote, M.1.50]
____
With the ending of grasping comes the ending of individual existence

_upādānanirodhā bhavanirodho._
____

.Illustration
====
samudaya

origination
====

____
This is the practice leading to the origination of personal identity.

_Ayaṃ kho pana bhikkhave sakkāya samudayagāminī paṭipadā_
____

[quote, M.3.284]
____
One regards the visual sense thus: this is "[in reality] mine," this is "[in 
reality] what I am," this is "my [absolute] Selfhood."

_cakkhuṃ etaṃ mama eso'hamasmi eso me attā ti samanupassati._
____

.Illustration
====
samudayā

origination
====

[quote, M.3.267]
____
Puṇṇa, with the origination of spiritually fettering delight comes the 
origination of suffering, I declare.

_nandi samudayā dukkhasamudayo puṇṇāti vadāmi._
____

.Illustration
====
samudaya

origination
====

• When it is said 'This is the practice leading to the origination of 
personal identity' it means a way of regarding things that leads to the 
&#8203;[further] origination of suffering' +
☸ _sakkāyasamudayagāminī paṭipadā ti itihidaṃ bhikkhave vuccati 
dukkhasamudayagāminī samanupassanā ti_).

• When it is said 'This is the practice leading to the ending of personal 
identity' it means a way of regarding things that leads to the ending of 
suffering +
☸ _ayaṃ vuccati bhikkhave sakkāyanirodhagāmini paṭipadā ti itihidaṃ 
bhikkhave vuccati dukkhasamudayagāmini samanupassanā ti_) (S.3.44).

.Illustration
====
samudaya

origination
====

• And what is the origination of bodily form?... advertence? +
_ko ca bhikkhave rūpassa samudayo... viññāṇassa samudayo._

____
In this regard a bhikkhu takes delight in, welcomes, persists in cleaving.

_Idha bhikkhave bhikkhu abhinandati abhivadati ajjhosāya tiṭṭhati._
____

And what is it that he takes delight in, welcomes, persists in cleaving to?

[quote, S.3.13-15]
____
He takes delight in bodily form, welcomes it, and persists in cleaving to it.

_rūpaṃ abhinandati abhivadati ajjhosāya tiṭṭhati._
____

.Illustration
====
samudaya

&#8203;[co-conditional] origination
====

____
And what is the development of the basic practice of mindfulness?

_Katamā ca bhikkhave satipaṭṭhānabhāvanā_
____

____
... In this regard a bhikkhu abides contemplating [co-conditional] origination 
in relation to the body.

_idha bhikkhave bhikkhu samudayadhammānupassī kāyasmiṃ viharati ātāpī 
sampajāno satimā vineyya loke abhijjhādomanassaṃ_
____

____
... He abides contemplating [co-conditional] disappearance in relation to the 
body.

_Vayadhammānupassī kāyasmiṃ viharati ātāpī sampajāno satimā vineyya 
loke abhijjhādomanassaṃ_
____

[quote, S.5.183]
____
... He abides contemplating [co-conditional] origination and disappearance in 
relation to the body, vigorously, fully consciously, and mindfully, having 
eliminated greed and dejection in regard to the world [of phenomena].

_Samudayavayadhammānupassī kāyasmiṃ viharati ātāpī sampajāno satimā 
vineyya loke abhijjhādomanassaṃ._
____

COMMENT

If 'a bhikkhu abides contemplating [co-conditional] origination' is converted 
into 'a bhikkhu abides contemplating origination factors' it has the following 
effect: instead of the bhikkhu contemplating with his senses, he instead 
contemplates with thought. But this would be impossible when mindfulness is 
practised without thinking:

[quote, A.4.301]
____
When you have thus developed and cultivated this meditation, then bhikkhu you 
should develop this meditation accompanied by thinking and pondering; without 
thinking, just pondering; without thinking or pondering.

_Yato kho te bhikkhu ayaṃ samādhi evaṃ bhāvito hoti bahulīkato tato 
tvaṃ bhikkhū imaṃ samādhiṃ savitakkampi savicāraṃ bhāveyyāsi. 
Avitakkampi vicāramattaṃ bhāveyyāsi. Avitakkampi avicāraṃ bhāveyyāsi._
____

.Illustration
====
samudayadhammaṃ

of an originated nature
====

[quote, S.4.28]
____
All is of an originated nature. What is the all that is of an originated 
nature? The visual sense is of an originated nature.

_Sabbaṃ bhikkhave samudayadhammaṃ. Kiñca bhikkhave sabbaṃ 
samudayadhammaṃ: cakkhuṃ bhikkhave samudayadhammaṃ._
____

.Illustration
====
samudayadhammaṃ

of an originated nature
====

____
The ignorant Everyman does not discern bodily form that is of an originated 
nature according to reality, thus: 'Bodily form is of an originated nature.'

_assutavā puthujjano samudayadhammaṃ rūpaṃ samudayadhammaṃ rūpan ti 
yathābhūtaṃ nappajānāti;_
____

____
He does not discern bodily form that is destined to disappear according to 
reality, thus: 'Bodily form is destined to disappear.

_vayadhammaṃ rūpaṃ vayadhammaṃ rūpan ti yathābhūtaṃ nappajānāti_
____

[quote, S.3.171]
____
He does not discern bodily form that is of an originated nature, and destined 
to disappear, according to reality, thus: 'Bodily form is of an originated 
nature, and destined to disappear.

_samudayavayadhammaṃ rūpaṃ samudayavayadhammaṃ rūpan ti yathābhūtaṃ 
nappajānāti._
____

.Illustration
====
samudayadhammaṃ

of an originated nature
====

[quote, Vin.1.11-12]
____
While this discourse was being propounded, the uncorrupted, stainless vision of 
the nature of reality arose within Venerable Koṇḍañña that whatever is of 
an originated nature is destined to cease.

__āyasmato koṇḍaññassa virajaṃ vītamalaṃ dhammacakkhuṃ udapādi 
yaṃ kiñci samudayadhammaṃ sabbaṃ taṃ nirodhadhamman ti._
____

