== Samādhi

=== Renderings

- _samādhi_: inward collectedness

- _samādhinimittaṃ_: object of meditation

- _samādhibhāvanā_: meditation

- _samādhi_: meditation

=== Illustrations

.Illustration
====
samādhi

inward collectedness
====

[quote, S.5.197]
____
And what is the faculty of inward collectedness? In this regard, the noble 
disciple, having made the relinquishment [of attachment] the basis [for 
spiritual development], gains inward collectedness, gains mental concentration.

_Katamañca bhikkhave samādhindriyaṃ idha bhikkhave ariyasāvako 
vossaggārammaṇaṃ karitvā labhati samādhiṃ labhati cittassa 
ekaggataṃ._
____

.Illustration
====
samādhi

inward collectedness
====

[quote, A.4.339]
____
Inward collectedness is the leader of all things.

_samādhipamukhā sabbe dhammā._
____

.Illustration
====
samādhiṃ

inward collectedness
====

[quote, Th.v.37]
____
They go to different countries, wandering unrestrained. If they lose their 
inward collectedness, what good will this international travelling do?

_Nānājanapadaṃ yanti vicarantā asaṃyatā +
Samādhiñca virādhenti kiṃsu raṭṭhacariyā karissati._
____

.Illustration
====
samādhi

inward collectedness
====

[quote, M.3.160]
____
Because of excessively reflecting upon shapes my inward collectedness fell away.

_Atinijjhāyitattādhikaraṇañca pana me rūpānaṃ samādhi cavi._
____

.Illustration
====
samādhiṃ

inward collectedness
====

[quote, S.3.125]
____
As I do not attain that inward collectedness, bhante, it occurs to me: 'May I 
not waste away!'

_Tassa mayhaṃ bhante taṃ samādhiṃ appaṭilabhato evaṃ hoti no ca 
khvāhaṃ parihāyāmī ti._
____

.Illustration
====
samādhinimittaṃ

object of meditation
====

____
Possessed of three factors a bhikkhu is incapable of either gaining an 
unattained spiritually wholesome factor, or developing an attained spiritually 
wholesome factor. Which three?

_tīhi dhammehi samannāgato bhikkhu abhabbo anadhigataṃ vā kusalaṃ 
dhammaṃ adhigantuṃ adhigataṃ vā kusalaṃ dhammaṃ phātikattuṃ. 
Katamehi tīhi:_
____

[quote, A.1.115]
____
In this regard, neither in the morning, afternoon, or evening does the bhikkhu 
carefully concentrate on an object of meditation.

_idha bhikkhave bhikkhu pubbanhasamayaṃ na sakkaccaṃ samādhinimittaṃ 
adhiṭṭhāti. Majjhantikaṃ samayaṃ na sakkaccaṃ samādhinimittaṃ 
adhiṭṭhāti. Sāyanhasamayaṃ na sakkaccaṃ samādhinimittaṃ 
adiṭṭhāti._
____

.Illustration
====
samādhibhāvanā

meditation
====

____
Bhikkhus there are these four types of meditation. Which four

_Catasso imā bhikkhave samādhibhāvanā. Katamā catasso?_
____

1. There is meditation which when developed and cultivated leads to pleasant 
states of meditation in this lifetime.
+
****
_Atthi bhikkhave samādhibhāvanā bhāvitā bahulīkatā 
diṭṭhadhammasukhavihārāya saṃvattati._
****

2. There is meditation which when developed and cultivated leads to the 
attainment of knowledge and vision [of things according to reality].
+
****
_Atthi bhikkhave samādhibhāvanā bhāvitā bahulīkatā 
ñāṇadassanapaṭilābhāya saṃvattati._
****

3. There is meditation which when developed and cultivated leads to mindfulness 
and full consciousness.
+
****
_Atthi bhikkhave samādhibhāvanā bhāvitā bahulīkatā satisampajaññāya 
saṃvattati._
****

4. There is meditation which when developed and cultivated leads to the 
destruction of perceptually obscuring states.
+
****
_Atthi bhikkhave samādhibhāvanā bhāvitā bahulīkatā āsavānaṃ khayāya 
saṃvattati_ (A.2.45).
****

.Illustration
====
samādhibhāvanā

meditation
====

____
What is the meditation which developed and cultivated that leads to the 
attainment of knowledge and vision [of things according to reality]?

_Katamā cāvuso samādhibhāvanā bhāvitā bahulīkatā 
ñāṇadassanapaṭilābhāya saṃvattati?_
____

[quote, D.3.223]
____
In this regard a bhikkhu focuses on the mental image of light, concentrates on 
the mental image of day. As by day, so by night; as by night, so by day. Thus 
with an attitude open and unclouded, he makes his mind radiant.

_Idhāvuso bhikkhu ālokasaññaṃ manasikaroti divāsaññaṃ 
adhiṭṭhāti yathā divā tathā rattiṃ yathā rattiṃ tathā divā. Iti 
vivaṭena cetasā apariyonaddhena sappabhāsaṃ cittaṃ bhāveti._
____

.Illustration
====
samādhibhāvanā

meditation
====

____
What is the meditation which developed and cultivated that leads to the 
destruction of perceptually obscuring states?

_Katamā cāvuso samādhibhāvanā bhāvitā bahulīkatā āsavānaṃ khayāya 
saṃvattati?_
____

[quote, D.3.223]
____
In this regard a bhikkhu abides contemplating the [co-conditional] arising and 
disappearance of the five grasped aggregates.

_Idhāvuso bhikkhu pañcasu upādānakkhandhesu udayabbayānupassī viharati._
____

.Illustration
====
samādhi

meditation
====

____
Three types of meditation:

_Tayo samādhi_
____

1. meditation with thinking and pondering
+
****
_savitakkasavicāro samādhi_
****

2. meditation without thinking, just pondering
+
****
_avitakkavicāramatto samādhi_
****

3. meditation without thinking or pondering
+
****
_avitakkāvicāro sāmādhi_
****

____
Three more types of meditation:

_Apare pi tayo samādhi_
____

1. Meditation on the voidness of an [absolute] Selfhood and of what could 
belong to an [absolute] Selfhood
+
****
_suññato samādhi_
****

2. meditation on the voidness of any abiding phenomena
+
****
_animitto samādhi_
****

3. meditation void of aspiration._ +
☸ appaṇihito samādhi_ (D.3.219).

.Illustration
====
samādhi

meditation
====

____
Mental concentration is meditation.

_Yā kho āvuso visākha cittassa ekaggatā ayaṃ samādhi._
____

____
The four bases of mindfulness are the objects of meditation.

_Cattāro satipaṭṭhānā samādhinimittā_
____

____
Four modes of right inward striving are the accessories of meditation.

_Cattāro sammappadhānā samādhiparikkhārā_
____

[quote, M.1.301]
____
Developing and cultivating these same things is the development of meditation.

_Yā tesaṃyeva dhammānaṃ āsevanā bhāvanā bahulīkammaṃ ayaṃ tattha 
samādhi bhāvanā ti._
____

.Illustration
====
samādhi

meditation
====

[quote, S.5.340]
____
Meditation through mindfulness with breathing if developed and cultivated leads 
to the destruction of perceptually obscuring states.

_Ānāpānasatisamādhi bhikkhave bhāvito bahulīkato āsavānaṃ khayāya 
saṃvattati._
____

