== Samāhita

=== Renderings

- _samāhita_: inwardly collected

- _samāhita_: collected

- _samāhita_: established

=== Introduction

==== -_atta_ suffix is redundant

In _samāhitatto_ we regard the -_atta_ suffix as redundant. For example:

[quote, S.1.169]
____
I am always inwardly collected

_niccasamāhitatto._
____

_Atta's_ role as a suffix is not noted in the Pāli grammar books, nor in the 
dictionaries sv _Atta_, though Duroiselle says _pahitatto_ means 'resolute, 
whose mind is bent upon, literally directed towards,' and _ṭhitatto_ means 
'of firm mind' (PGPL, para 555).

See notes sv _Attā_.

=== Illustrations

.Illustration
====
samāhito

inwardly collected
====

[quote, D.2.216]
____
As he abides contemplating the nature of the body internally he becomes 
perfectly inwardly collected and perfectly serene. Being thus perfectly 
inwardly collected and perfectly serene he arouses knowledge and vision 
externally of others' bodies [according to reality].

_Ajjhattaṃ kāye kāyānupassī viharanto tattha sammāsamādhiyati 
sammāvippasīdati. So tattha sammā samāhito sammāvippasanno bahiddhā 
parakāye ñāṇadassanaṃ abhinibbatteti._
____

.Illustration
====
samāhito

inwardly collected
====

[quote, S.3.13]
____
Bhikkhus, develop inward collectedness. A bhikkhu who is inwardly collected 
discerns things according to reality.

_samādhiṃ bhikkhave bhāvetha. Samāhito bhikkhave bhikkhu yathābhūtaṃ 
pajānāti._
____

.Illustration
====
samāhitaṃ

collected
====

[quote, Th.v.1]
____
My mind is well-collected.

_Cittaṃ me susamāhitaṃ_
____

.Illustration
====
samāhito

&#8203;[well] established
====

[quote, A.4.292]
____
This community of bhikkhus is spiritually purified, [well] established in 
penetrative discernment and virtue.

_Esa saṅgho ujubhūto paññāsīlasamāhito._
____

.Illustration
====
samāhito

established
====

[quote, Th.v.617]
____
The fool is miserable everywhere, being unestablished in virtue

_Sabbattha dummano bālo sīlesu asamāhito._
____

.Illustration
====
samāhito

established
====

[quote, A.2.8]
____
Well established in virtue

_sīlesu susamāhito._
____

