== Sappurisa

=== Renderings

- _sappurisa_: spiritually outstanding person

- a__sappurisa__: common person

=== Introduction

==== Asappurisa and puthujjana

The following quote treats _asappurisa_ ('the common person') and _puthujjana_ 
('the common man') as equivalent, and shows that a _sappurisa_ is at least a 
'faith follower' (_saddhānusārin_), and not necessarily a stream-enterer:

[quote, S.3.225]
____
One who has faith in [the significance of] these teachings and is intent upon 
them is called a 'faith follower,' one who has entered the way of rightness 
&#8203;[comprised of spiritually wholesome factors], entered the plane of spiritually 
outstanding people, transcended the plane of the common man. He is incapable of 
doing any deed for which he might be reborn in hell, the animal realm, or the 
sphere of ghosts; he is incapable of passing away without having realised the 
fruit of stream-entry.

_yo bhikkhave ime dhamme evaṃ saddahati adhimuccati ayaṃ vuccati 
saddhānusārī okkanto sammattaniyāmaṃ sappurisabhumiṃ okkanto vītivatto 
puthujjanabhumiṃ abhabbo taṃ kammaṃ kātuṃ yaṃ kammaṃ katvā 
nirayaṃ vā tiracchānayoniṃ vā pettivisayaṃ vā upapajjeyya abhabbo va 
tāva kālaṃ kātuṃ yāva na sotāpattiphalaṃ sacchikaroti._
____

==== Sappurisas and arahants

Arahants are 'greater than _sappurisas'_ (_sappurisena sappurisataro_) in being 
possessed of not eight, but ten path factors:

[quote, M.3.76]
____
Thus the disciple in training is endowed with eight factors, and the arahant 
with ten.

_Iti kho bhikkhave aṭṭhaṅgasamannāgato sekho dasaṅgasamannāgato 
arahā hoti._
____

☸ _Katamo ca bhikkhave sappuriso: idha bhikkhave ekacco sammādiṭṭhiko 
hoti sammāsaṅkappo sammāvāco sammākammanto sammaājīvo sammāvāyāmo 
sammāsati sammāsamādhi. Ayaṃ vuccati bhikkhave sappuriso_ (S.5.20).

☸ _Katamo ca bhikkhave sappurisena sappurisataro: idha bhikkhave ekacco 
sammādiṭṭhiko hoti sammāsaṅkappo sammāvāco sammākamanto 
sammāājīvo sammāvāyāmo sammāsati sammāsamādhi sammāñāṇī 
sammāvimutti. Ayaṃ vuccati bhikkhave sappurisena sappurisataro ti_ (S.5.20).

=== Illustrations

.Illustration
====
asappurisa

common people; sappurisehi, spiritually outstanding people
====

[quote, S.4.195]
____
This is a path pursued by common people not by spiritually outstanding people. 
This is not suitable for you.

_asappurisasevito ceso maggo na ceso maggo sappurisehi sevito na tvaṃ 
arahasī ti._
____

.Illustration
====
asappurisa

common people
====

[quote, A.5.113]
____
And what is the condition that nourishes not listening to the true teaching? 
Associating with common people, one should reply.

_ko cāhāro asaddhammasavaṇassa: asappurisasaṃsevotissa vacanīyaṃ._
____

.Illustration
====
asappuriso

common person; sappuriso, spiritually outstanding person
====

When the common person (a__sappuriso__) gains first jhāna, he thinks

____
'I am an attainer of the first jhāna; these other bhikkhus are not'

_ahaṃ khomhi paṭhamajjhānasamāpattiyā lābhī ime panaññe bhikkhū na 
paṭhamajjhānasamāpattiyā lābhino ti_
____

____
He thereby exalts himself and disparages others

_attānukkaṃseti paraṃ vambheti_
____

When a spiritually outstanding person (_sappuriso_) gains jhāna, he thinks:

____
'The perception that "It is void of personal qualities" even concerning the 
attainment of the first jhāna has been spoken of by the Blessed One

_paṭhamajjhānasamāpattiyāpi kho atammayatā vuttā bhagavatā_
____

[quote, M.3.42]
____
For whatsoever one thinks of in personal terms, it is different than [how one 
thinks of it]

_yena yena hi maññati tato taṃ hoti aññathā._
____

.Illustration
====
sappuriso

spiritually outstanding person
====

• And how does a spiritually outstanding person think? +
_Kathañca bhikkhave sappuriso sappurisacintī hoti:_

• In this regard a spiritually outstanding person is not intent upon his own 
harm, or the harm of others, or the harm of both. +
_idha bhikkhave sappuriso nevattavyābādhāya ceteti na paravyābādhāya 
ceteti na ubhayavyābādhāya ceteti evaṃ kho bhikkhave sappuriso 
sappurisacintī hoti._

• How does a spiritually outstanding person give counsel? He does not give 
counsel for his own harm, or of others, or of both. +
_Kathañca bhikkhave sappuriso sappurisamantī hoti? Idha bhikkhave sappuriso 
nevattavyābādhāya manteti na paravyābādhāya manteti na 
ubhayavyābādhāya manteti. Evaṃ kho bhikkhave sappuriso sappurisamantī 
hoti._

• How does a spiritually outstanding person speak? He abstains from lying, 
malicious speech, harsh speech, gossip. +
_Kathañca bhikkhave sappuriso sappurisavāco hoti? Idha bhikkhave sappuriso 
musāvādā paṭivirato hoti pisunāya vācāya paṭivirato hoti pharusāya 
vācāya paṭivirato hoti. Samphappalāpā paṭivirato hoti. Evaṃ kho 
bhikkhave sappuriso sappurisavāco hoti._

• How does a spiritually outstanding person act? He abstains from killing, 
stealing, and misconduct in sensuous pleasure. +
_Kathañca bhikkhave sappuriso sappurisakammanto hoti idha bhikkhave sappuriso 
pāṇātipātāpaṭivirato hoti adinnādānā paṭivirato hoti kāmesu 
micchācārā paṭivirato hoti. Evaṃ kho bhikkhave sappuriso 
sappurisakammanto hoti_ (M.3.21-2).

.Illustration
====
sappurisā

spiritually outstanding
====

[quote, Vin.1.56]
____
Indeed those who are spiritually outstanding, Sāriputta, are thankful and 
grateful.

_kataññuno hi sāriputta sappurisā katavedino._
____

.Illustration
====
sappurisaṃ

spiritually outstanding person
====

[quote, Sn.__v.22__9]
____
'Like a locking-post firmly embedded in the ground that is unshakeable by the 
winds of the four quarters, I declare, is the [quality of a] spiritually 
outstanding person, who, having penetrated the [four] noble truths, sees [the 
nature of reality] [and is unshaken by craving].

_Yathindakhīlo paṭhaviṃ sito siyā catubbhi vātehi asampakampiyo +
Tathūpamaṃ sappurisaṃ vadāmi yo ariyasaccāni avecca passati._
____

.Illustration
====
sappuriso

spiritually outstanding person
====

[quote, A.3.50]
____
A spiritually outstanding person gives what is hard to give

_So duccajaṃ sappuriso cajitvā._
____

