== Saññā; Sañjānāti

=== Renderings

- _saññā_: notion

- _saññā_: idea

- _saññā_: attitude

- _saññā_: mental image

- _saññā_: mental imagery

- _saññā_: perception

- _saññā_: modes of perception

- _saññā_: state of refined awareness

- _sañjānāti_: to label

- _sañjānāti_: to perceive

- _papañcasaññā_: entrenched perception

=== Introduction

==== Mental images: purifying or defiling

Mental imagery can be purifying or defiling:

1. Three varieties of spiritually unwholesome mental images: sensuous mental 
images, unbenevolent mental images, malicious mental images.
+
****
_Tisso akusalasaññā: kāmasaññā vyāpādasaññā vihiṃsāsaññā._
****

2. Three varieties of spiritually wholesome mental images: unsensuous mental 
images, benevolent mental images, compassionate mental images.
+
****
_Tisso kusalasaññā: nekkhammasaññā avyāpādasaññā 
avihiṃsāsaññā_ (D.3.215).
****

==== Sensual mental imagery ceases in first jhāna

Sensual mental imagery ceases in first jhāna:

[quote, D.1.182]
____
Secluded from sensuous pleasures and spiritually unwholesome factors, he enters 
and abides in first jhāna, which is accompanied by thinking and pondering, and 
rapture and physical pleasure born of seclusion [from sensuous pleasures and 
spiritually unwholesome factors]. For him the mental imagery of previous 
sensuous pleasure ceases.

_So vivicceva kāmehi vivicca akusalehi dhammehi savitakkaṃ savicāraṃ 
vivekajaṃ pītisukhaṃ paṭhamaṃ jhānaṃ upasampajja viharati. Tassa 
yā purimā kāmasaññā sā nirujjhati._
____

==== Mental images are the source of thought

Mental images are the source of thought:

[quote, S.2.144]
____
Because of mental imagery of visible objects, thought about visible objects 
arises

_Rūpasaññaṃ paṭicca uppajjati rūpasaṅkappo._
____

==== Ascetics must overcome unvirtuous mental imagery

Ascetics must overcome unvirtuous mental imagery:

[quote, S.2.152]
____
If any ascetic or Brahmanist does not quickly abandon, dispel, put an end to, 
and eradicate unvirtuous mental imagery that has arisen in him, he abides 
unhappily in this very lifetime.

_yo hi koci samaṇo vā brāhmaṇo vā uppannaṃ visamagataṃ saññaṃ na 
khippameva pajahati vinodeti vyantīkaroti anabhāvaṃ gameti so diṭṭhe 
ceva dhamme dukkhaṃ viharati._
____

[quote, Sn.v.175]
____
'One who abstains from sensuous mental imagery, who has transcended all ties to 
individual existence, with spiritually fettering delight in individual 
existence destroyed, he does not sink in the deep.'

_Virato kāmasaññāya sabbasaṃyojanātigo +
Nandibhavaparikkhīṇo so gambhīre na sīdati._
____

==== Arahants have overcome unvirtuous mental images

Arahants have overcome unvirtuous mental images:

[quote, M.3.125]
____
Friend, in the eighty years since I went forth [into the ascetic life] I do not 
recall a sensuous mental image having ever arisen in me.

_Asīti me āvuso kassapa vassāni pabbajitassa nābhijānāmi kāmasaññaṃ 
uppannapubbaṃ._
____

This is in accordance with the fact that:

[quote, S.2.263]
____
All spiritually unwholesome factors stem from uninsightfulness into reality, 
emanate from uninsightfulness into reality, and all are abolished when 
uninsightfulness into reality is abolished.

_Evameva kho bhikkhave ye keci akusalā dhammā sabbe te avijjāmūlakā 
avijjāsamosaraṇā. Avijjāsamugghātā sabbe te samugghātaṃ gacchanti._
____

==== Arahants perceive without mental images

Arahants perceive objects as they are, without any associated mental images:

• He does not conceive the slightest mental image regarding what is seen, 
heard, sensed, or cognised. +
_Tassīdha diṭṭhe vā sute mute vā pakappitā natthi aṇu pi saññā_ 
(Sn.v.802).

==== Arahants are susceptible to virtuous mental images

Arahants are nonetheless susceptible to virtuous mental images:

[quote, Th.v.589]
____
Just as the Veramba wind blows clouds in the rainy season, so [in the city of 
Veramba] mental images connected with physical seclusion [would] overwhelm me.

_Yathā abbhāni verambo vāto nudati pāvuse +
Saññā me abhikīranti vivekapaṭisaṃyuttā._
____

==== The Buddha was fully conscious of mental images

The Buddha was fully conscious of mental images:

[quote, M.3.124]
____
In this regard, Ānanda, the arising, continuance, and vanishing of sense 
impressions (_vedanā_), mental images (_saññā_), and thoughts (_vitakkā_) 
is known by the Perfect One.

_Idhānanda tathāgatassa viditā vedanā uppajjanti. Viditā upaṭṭhahanti. 
Viditā abbhatthaṃ gacchanti. Viditā saññā uppajjanti viditā 
upaṭṭhahanti. Viditā abbhatthaṃ gacchanti. Viditā vitakkā uppajjanti. 
Viditā upaṭṭhahanti. Viditā abbhatthaṃ gacchanti._
____

==== The arahant is free of unvirtuous and deluding mental images

So when the suttas say that the arahant is free of mental images, this would 
mean that he is free of:

1. unvirtuous mental images, and

2. deluding images

We parenthesise accordingly. This is justified, because in the 
_Madhupiṇḍika Sutta_, where the following quote comes from, the Buddha 
explains how his teaching does not lead to unwholesome consequences. This 
rationally means that the mental images he is condemning are those which are 
unwholesome. The usual combination of words used in the scriptures to capture 
unwholesome connotations is _pāpakā akusala_, i.e. 'unvirtuous and 
spiritually unwholesome.' We use this parenthesis here, for example:

[quote, M.1.108]
____
&#8203;[I proclaim] a doctrine, friend, such that... one does not abide quarrelling 
with anyone in the world; such that for the Brahman who abides emancipated from 
sensuous pleasures, free of uncertainty [about the significance of the 
teaching], free of anxiety, free of craving for all states of individual 
existence, [unvirtuous and spiritually unwholesome] mental images do not lurk 
within him.

_yathāvādī kho āvuso... na kenaci loke viggayha tiṭṭhati yathā ca pana 
kāmehi visaṃyuttaṃ viharantaṃ taṃ brāhmaṇaṃ akathaṅkathiṃ 
chinnakukkuccaṃ bhavābhave vītataṇhaṃ saññā nānusenti._
____

==== Solving the Kalahavivāda Sutta

To solve the puzzle of the _Kalahavivāda Sutta_ (Sn.v.873-4), we render 
_saññā_ as 'mental images,' as follows:

[quote, Sn.v.873]
____
&#8203;[Question:] 'For one attained to what state does bodily form vanish? Whether 
pleasant or painful, how does it vanish? Tell me this, how does it vanish? My 
objective is that we should know this.'

_Kathaṃ sametassa vibhoti rūpaṃ sukhaṃ dukkhaṃ vāpi kathaṃ vibhoti +
Etaṃ me pabrūhi yathā vibhoti taṃ jāniyāmāti me mano ahu_
____

[quote, Sn.v.874]
____
&#8203;[Answer:] 'He does not perceive mental images [of what is seen, heard, sensed, 
or cognised]. He does not perceive [what is seen, heard, sensed, or cognised] 
with deranged perception. He is not without perception. He does not perceive 
what has vanished. For one arrived at such a state, bodily form vanishes. 
Mental images are indeed the source of entrenched conception.'

_Na saññasaññī na visaññasaññī no pi asaññī na vibhūtasaññī +
Evaṃ sametassa vibhoti rūpaṃ saññānidānā hi papañcasaṅkhā._
____

=== Illustrations: saññā

.Illustration
====
saññāya

notion
====

[quote, Sn.v.886]
____
Apart from the mere notion of it, there are not many and various Perfect Truths 
in the world

_Na heva saccāni bahūni nānā aññatra saññāya niccāni loke._
____

.Illustration
====
saññaṃ

notion
====

[quote, Sn.v.841]
____
Inquiring, relying on a dogmatic view, bewildered by what you are attached to, 
you cannot comprehend the simplest notion. Thus you regard this teaching as 
foolish.

_Diṭṭhañca nissāya anupucchamāno samuggahītesu pamohamāgā +
Ito ca nāddakkhi aṇumpi saññaṃ tasmā tuvaṃ momuhato dahāsi._
____

.Illustration
====
saññaṃ

idea
====

[quote, D.2.134-5]
____
Then the Blessed One, mindful and fully conscious, lay down on his right side 
in the lion's posture with his feet placed together, having contemplated the 
idea of rising.

_Atha kho bhagavā dakkhiṇena passena sīhaseyyaṃ kappesi pāde pādaṃ 
accādhāya sato sampajāno uṭṭhānasaññaṃ manasikaritvā._
____

.Illustration
====
saññā

attitude
====

[quote, S.5.315]
____
Thoroughly dispelled the attitude of repugnance towards either internal things 
or external things.

_Ajjhattabahiddhā ca me dhammesu paṭighasaññā suppaṭivinītā._
____

.Illustration
====
saññā

attitude
====

[quote, Sn.v.148]
____
He would not wish for another's suffering out of anger, or from an attitude of 
repugnance.

_Na paro paraṃ nikubbetha nātimaññetha katthaci naṃ kañci +
Vyārosanā paṭighasaññā nāññamaññassa dukkhamiccheyya._
____

.Illustration
====
saññā

attitude
====

[quote, A.3.443]
____
An attitude of disillusionment with all originated phenomena will be as present 
to me as it might in relation to a murderer with a drawn sword

_sabbasaṅkhāresu ca me nibbidasaññā paccupaṭṭhitā bhavissati 
seyyathā pi ukkhittāsike vadhake._
____

.Illustration
====
saññā

attitude
====

____
Assuming what attitude do spiritually unwholesome factors flourish and 
spiritually wholesome factors fade?

_kathaṃrūpaṃ bhante saññāpaṭilābhaṃ sevato akusalā dhammā 
abhivaḍḍhanti kusalā dhammā parihāyanti_
____

In this regard, some person is

____
greedy and abides with a greedy attitude

_idha bhante ekacco abhijjhālu hoti abhijjhāsahagatāya saññāya viharati_
____

____
unbenevolent and abides with an unbenevolent attitude

_vyāpādavā hoti vyāpādasahagatāya saññāya viharati_
____

[quote, M.3.50-1]
____
malicious and abides with a malicious attitude.

_vihesavā hoti vihesāsahagatāya saññāya viharati._
____

.Illustration
====
saññaṃ

mental image
====

[quote, A.4.86]
____
But if by abiding thus you do not shake off that torpor, then focus on the 
mental image of light, concentrate on the mental image of day. As by day, so at 
night; as at night, so by day.

_No ce te evaṃ viharato taṃ middhaṃ pahīyetha tato tvaṃ moggallāna 
ālokasaññaṃ manasikareyyāsi divāsaññaṃ adhiṭṭheyyāsi yathā 
divā tathā rattiṃ yathā rattiṃ tathā divā._
____

.Illustration
====
saññā

mental images
====

____
Sensuous pleasures in this lifetime and in the hereafter, mental images of 
sensuous pleasures of this lifetime and of the hereafter, both alike are 
Māra's realm, Māra's domain, Māra's bait, Māra's hunting ground.

_Ye ca diṭṭhadhammikā kāmā ye ca samparāyikā kāmā yā ca 
diṭṭhadhammikā kāmasaññā yā ca samparāyikā kāmasaññā 
ubhayametaṃ māradheyyaṃ mārassesavisayo marassesanivāpo 
mārassesagocaro._
____

[quote, M.2.261-2]
____
They lead to unvirtuous, spiritually unwholesome mental states such as greed, 
ill will, and aggressiveness, which arise for the spiritual obstruction in this 
world of the noble disciple in training.

_Etthete pāpakā akusalā mānasā abhijjhāpi vyāpādāpi sārambhāpi 
saṃvattanti. Teva ariyasāvakassa idhamanusikkhato antarāyāya sambhavanti._
____

.Illustration
====
saññā

mental images
====

[quote, S.1.126]
____
How should a bhikkhu here abundantly dwell that, five floods crossed, he 
crosses the sixth? How should he apply himself so sensuous mental images are 
kept at bay and fail to grip him?

_Kathaṃ vihārī bahulodha bhikkhu pañcoghatiṇṇo atarīdha 
chaṭṭhaṃ +
Kathaṃ jhāyiṃ bahulaṃ kāmasaññā paribāhirā honti aladdha yo tanti._
____

.Illustration
====
saññā

mental imagery
====

[quote, D.3.266]
____
On attaining first jhāna, sensuous mental imagery is ended.

_paṭhamaṃ jhānaṃ samāpannassa kāmasaññā niruddhā hoti._
____

.Illustration
====
saññā

mental images
====

____
&#8203;[I proclaim] a doctrine, friend, such that...

_yathāvādī kho āvuso..._
____

____
&#8203;[unvirtuous and spiritually unwholesome] mental images do not lurk within him

_saññā nānusenti;_
____

[quote, M.1.108]
____
This is my doctrine; this is what I proclaim.

_evaṃ vādī kho ahaṃ āvuso evamakkhāyī ti._
____

COMMENT

The Buddha explained this statement as follows:

____
For whatever the reason that entrenched perception and conception assail a man, 
if there is found nothing there to be delighted in, welcomed, or clung to, this 
is the end of the proclivity to attachment etc

_Yatonidānaṃ bhikkhu purisaṃ papañcasaññāsaṅkhā samudācaranti 
ettha ce natthi abhinanditabbaṃ abhivaditabbaṃ ajjhositabbaṃ esevanto 
rāgānusayānaṃ_
____

This sutta therefore confirms the relationship between mental images and 
entrenched perception and conception. Other suttas say:

[quote, Sn.v.874]
____
Mental images are indeed the source of entrenched conception.

_saññānidānā hi papañcasaṅkhā._
____

.Illustration
====
saññānaṃ

mental images
====

[quote, Sn.v.732]
____
Recognising this danger, that suffering arises dependent on karmically 
consequential deeds, with the quelling of karmically consequential deeds, and 
the ending of mental images, in this way is there the destruction of suffering.

_Etamādīnavaṃ ñatvā dukkhaṃ saṅkhārapaccayā +
Sabbasaṅkhārasamathā saññānaṃ uparodhanā +
Evaṃ dukkhakkhayo hoti_
____

.Illustration
====
saññā

mental imagery
====

____
Possessed of six factors a bhikkhu abides unhappily in this very lifetime, with 
distress, vexation, and anguish, and at death a bad bourne can be expected. 
What six?

_Chahi bhikkhave dhammehi samannāgato bhikkhu diṭṭheva dhamme dukkhaṃ 
viharati savighātaṃ saupāyāsaṃ sapariḷāhaṃ kāyassa bhedā 
parammaraṇā duggati pāṭikaṅkhā. Katamehi chahi:_
____

[quote, A.3.429]
____
Thoughts of sensuous pleasure, ill will, and maliciousness; sensuous mental 
imagery, unbenevolent mental imagery, and malicious mental imagery.

_Kāmavitakkena, vyāpādavitakkena, vihiṃsāvitakkena, kāmasaññāya, 
vyāpādasaññāya, vihiṃsāsaññāya._
____

.Illustration
====
saññā

mental imagery
====

____
Because of the phenomenon of sensuous pleasure, sensuous mental imagery arises

_Kāmadhātuṃ bhikkhave paṭicca uppajjati kāmasaññā_
____

____
Because of sensuous mental imagery, sensuous thought arises,

_Kāmasaññaṃ paṭicca uppajjati kāmasaṅkappo_
____

[quote, S.2.151]
____
Because of sensuous thought, sensuous hankering arises

_Kāmasaṅkappaṃ paṭicca uppajjati kāmacchando._
____

.Illustration
====
saññā

mental imagery
====

____
Because of the phenomenon of ill will, unbenevolent mental imagery arises.

_vyāpādadhātuṃ bhikkhave paṭicca uppajjati vyāpādasaññā._
____

____
Because of unbenevolent mental imagery, unbenevolent thought arises

_vyāpādasaññaṃ paṭicca uppajjati vyāpādasaṅkappo._
____

[quote, S.2.151]
____
Because of unbenevolent thought, unbenevolent desire arises.

_vyāpādasaṅkappaṃ paṭicca uppajjati vyāpādacchando._
____

.Illustration
====
saññā

mental imagery
====

____
And which, carpenter, are spiritually unwholesome thoughts?

_Katame ca thapati akusalasaṅkappā_
____

____
Sensuous thought, unbenevolent thought, malicious thought. These are called 
spiritually unwholesome thoughts.

_kāmasaṅkappo vyāpādasaṅkappo vihiṃsāsaṅkappo ime vuccanti thapati 
akusalasaṅkappā._
____

____
And what, carpenter, is the origin of these spiritually unwholesome thoughts? 
Their origin is spoken of too. Their origin is in mental imagery, one should 
reply.

_ime ca thapati akusalasaṅkappā kiṃsamuṭṭhānā: samuṭṭhānampi 
nesaṃ vuttaṃ. Saññāsamuṭṭhānātissa vacanīyā._
____

• Which mental imagery? For mental imagery is manifold, multiplex and 
diverse: +
_Katamā saññā? Saññāpi hi bahū anekavidhā nānappakārakā_

[quote, M.2.27]
____
Sensuous mental imagery, unbenevolent mental imagery, malicious mental imagery: 
arising from these are spiritually unwholesome thoughts.

_kāmasaññā vyāpādasaññā vihiṃsāsaññā ito samuṭṭhānā 
akusalā saṅkappā._
____

.Illustration
====
saññā

mental images
====

• What is the meditation which developed and cultivated that leads to 
mindfulness and full consciousness? +
_Katamā cāvuso samādhibhāvanā bhāvitā bahulīkatā satisampajaññāya 
saṃvattati?_

In this regard the arising, continuance, and vanishing of

____
sense impressions

_viditā vedanā uppajjanti... upaṭṭhahanti... abbhatthaṃ gacchanti_
____

____
mental images

_viditā saññā uppajjanti... upaṭṭhahanti... abbhatthaṃ gacchanti_
____

____
thoughts

_viditā vitakkā uppajjanti... upaṭṭhahanti... abbhatthaṃ gacchanti_
____

is known by the bhikkhu (D.3.223).

.Illustration
====
saññā

mental image
====

[quote, S.5.129]
____
When the mental image of a skeleton is developed and cultivated it is of great 
fruit and benefit.

_aṭṭhikasaññā bhikkhave bhāvitā bahulīkatā mahapphalā hoti 
mahānisaṃsā._
____

.Illustration
====
saññā

perception/mental image
====

Beings do not know according to reality that:

1. This perception/ mental image leads to worsening.
+
****
_imā hānabhāgiyā saññā ti yathābhūtaṃ nappajānanti_
****

2. This perception/ mental image leads to stasis.
+
****
_Imā ṭhitibhāgiyā saññā ti yathābhūtaṃ nappajānanti_.
****

3. This perception/ mental image leads to distinction.
+
****
_Imā visesabhāgiyā saññā ti yathābhūtaṃ nappajānanti_
****

4. This perception/ mental image leads to the profound understanding [and 
destruction of the great masses of greed, hatred, and undiscernment of reality].
+
****
_Imā nibbedhabhāgiyā saññā ti yathābhūtaṃ nappajānanti_
****

[quote, A.2.167]
____
This is the cause and reason for some beings here not realising the Untroubled 
in this lifetime.

_Ayaṃ kho āvuso ānanda hetu ayaṃ paccayo yena midhekacce sattā 
diṭṭheva dhamme na parinibbāyantī ti._
____

COMMENT

The six perceptions leading to the profound understanding [and destruction of 
the great masses of greed, hatred, and undiscernment of reality] are:

1. the perception of the unlastingness [of the five aggregates] 
(_aniccasaññā_)

2. the perception that what is unlasting is existentially void (_anicce 
dukkhasaññā_)

3. the perception that what is existentially void is void of personal qualities 
(_dukkhe anattasaññā_)

4. the perception of the abandonment [of sensuous thoughts, unbenevolent 
thoughts, malicious thoughts, and unvirtuous, spiritually unwholesome factors] 
(_pahānasaññā_)

5. the perception of the passing away [of originated phenomena] 
(_virāgasaññā_)

6. the perception of the ending [of originated phenomena] (_nirodhasaññā_)

☸ _Cha nibbedhabhāgiyā saññā: Aniccasaññā anicce dukkhasaññā 
dukkhe anattasaññā pahānasaññā virāgasaññā nirodhasaññā_ 
(D.3.251).

COMMENT

When:

1. the mental image of a skeleton (_aṭṭhikasaññā_)

2. the mental image of a maggot-infested corpse (_puḷavakasaññā_)...

3. the mental image of a discoloured corpse (_vinīlakasaññā_)

4. the mental image of a cut up corpse (_vicchiddakasaññā_)

5. the mental image of a bloated corpse (_uddhumātakasaññā_)

is developed and cultivated it is of great fruit and benefit (S.5.129-134).

COMMENT

'The profound understanding [and destruction of the great masses of greed, 
hatred, and undiscernment of reality]': _Nibbijjhati_ means 'to pierce,' which 
we call 'to profoundly understand.' At S.5.88 _nibbijjhati_ is linked to 
_padāleti_ (to destroy), and to _lobhakkhandhaṃ dosakkhandhaṃ 
mohakkhandhaṃ._

.Illustration
====
papañcasaññā

entrenched perception
====

____
Thinking, Lord of the Devas, arises from entrenched perception and conception.

_Vitakko kho devānaminda papañcasaññāsaṅkhānidāno..._
____

[quote, D.2.277]
____
When they are present, thinking arises; when they are absent, thinking does not 
arise.

_papañcasaññāsaṅkhāya sati vitakko hoti papañcasaññāsaṅkhāya 
asati vitakko na hotī ti._
____

.Illustration
====
papañcasaññā

entrenched perception
====

____
For whatever the reason

_yatonidānaṃ_
____

____
that entrenched perception and conception assail a man

_purisaṃ papañcasaññāsaṅkhā samudācaranti_
____

____
if there is found nothing there to be delighted in, welcomed, or clung to

_ettha ce natthi abhinanditabbaṃ abhivaditabbaṃ ajjhositabbaṃ_
____

[quote, M.1.109]
____
this is the end of the proclivity to attachment...

_esevanto rāgānusayānaṃ...._
____

.Illustration
====
viparītasaññaṃ

distorted perception
====

____
Although contact with sensuous pleasures is unpleasant,

_dukkhasamphassesuyeva kāmesu_
____

[quote, M.1.507-8]
____
they acquire the distorted perception that it is pleasant.

_sukhami ti viparītasaññaṃ paccalatthuṃ._
____

.Illustration
====
sañña

perception
====

____
And why do you call it perception? One perceives therefore it is called 
perception. And what does one perceive?

_Kiñca bhikkhave saññaṃ vadetha sañjānātī ti kho bhikkhave tasmā 
saññā ti vuccati kiñca sañjānāti:_
____

[quote, S.3.87]
____
One perceives blue, one perceives yellow, one perceives red, one perceives 
white. .

_nīlampi sañjānāti; pītakampi sañjānāti; lohitakampi sañjānāti. 
Odātampi sañjānāti;._
____

.Illustration
====
sañña

perception
====

[quote, D.1.28]
____
There are certain devas called 'beings without perception.' When perception 
arises in them, those devas fall away from that group.

_Santi bhikkhave asaññasattā nāma devā. Saññuppādā ca pana te devā 
tamhā kāyā cavanti._
____

.Illustration
====
saññā

modes of perception; saññā, perception
====

Ānanda, if you tell the bhikkhu Girimānanda ten modes of perception 
(_dasasaññā bhāseyyāsi_) it may cure his illness. Which ten?

1. The perception of the unlastingness [of the five aggregates]
+
****
_aniccasaññā_
****

2. the perception of the voidness of personal qualities [in the six senses and 
their objects]
+
****
_anattasaññā_
****

3. the perception of the unloveliness [of the body]
+
****
_asubhasaññā_
****

4. the perception of the danger [of the body]
+
****
_ādīnavasaññā_
****

5. the perception of the abandonment [of sensuous thoughts, unbenevolent 
thoughts, malicious thoughts, and unvirtuous, spiritually unwholesome factors]
+
****
_pahānasaññā_
****

6. the perception of the passing away [of originated phenomena]
+
****
_virāgasaññā_
****

7. the perception of the ending [of originated phenomena]
+
****
_nirodhasaññā_
****

8. the perception of disgust for the whole world [of phenomena]
+
****
_sabbaloke anabhiratasaññā_
****

9. the perception of the unlastingness of all originated phenomena
+
****
_sabbasaṅkhāresu aniccasaññā_
****

[quote, A.5.108-9]
____
\10) mindfulness with breathing.

__ānāpānasati._
____

.Illustration
====
saññā

states of refined awareness; sañjānāti, perceives
====

____
Bhikkhus, there are four states of refined awareness. Which four?

_Catasso imā bhikkhave saññā katamā catasso:_
____

____
One being perceives what is limited.

_parittameko sañjānāti_
____

____
One being perceives what is exalted.

_mahaggatameko sañjānāti_
____

____
One being perceives what is limitless.

_appamāṇameko sañjānāti_
____

[quote, A.5.63]
____
One being perceives the state of awareness of nonexistence, where one perceives 
that there is [nowhere] anything at all.

_natthi kiñcī ti ākiñcaññāyatanameko sañjānāti._
____

.Illustration
====
saññā

perception; saññā, state of refined awareness
====

____
Secluded from sensuous pleasures and spiritually unwholesome factors, he enters 
and abides in first jhāna, which is accompanied by thinking and pondering, and 
rapture and physical pleasure born of seclusion [from sensuous pleasures and 
spiritually unwholesome factors].

_So vivicceva kāmehi vivicca akusalehi dhammehi savitakkaṃ savicāraṃ 
vivekajaṃ pītisukhaṃ paṭhamaṃ jhānaṃ upasampajja viharati._
____

____
For him the mental imagery of previous sensuous pleasure ceases.

_Tassa yā purimā kāmasaññā sā nirujjhati._
____

____
And at that time there is a subtle but true perception of the rapture and 
physical pleasure born of seclusion [from sensuous pleasures and spiritually 
unwholesome factors]. He is one with a subtle but true perception of the 
rapture and physical pleasure born of seclusion [from sensuous pleasures and 
spiritually unwholesome factors].

_Vivekajapītisukhasukhumasaccasaññā tasmiṃ samaye hoti. 
Vivekajapītisukhasukhumasaccasaññī yeva tasmiṃ samaye hoti._
____

[quote, D.1.184]
____
In this way one state of refined awareness arises through the training, and one 
state of refined awareness ceases through the training. And that is the 
training, said the Blessed One.

_Evampi sikkhā ekā saññā uppajjati. Sikkhā ekā saññā nirujjhati. 
Ayaṃ sikkhā ti bhagavā avoca._
____

.Illustration
====
saññānaṃ

states of refined awareness
====

____
Some [ascetics and Brahmanists] proclaim that the state of awareness of 
nonexistence, limitless and imperturbable, where one perceives that there is 
&#8203;[nowhere] anything at all, is the purest, highest, best, and greatest of those 
states of refined awareness, whether refined material states of awareness, or 
immaterial states of awareness, or states of refined awareness involving mental 
cognisance alone, or involving the external senses.

_Yā vā panetāsaṃ saññānaṃ parisuddhā paramā aggā anuttariyā 
akkhāyati yadi rūpasaññānaṃ yadi arūpasaññānaṃ yadi 
ekattasaññānaṃ yadi nānattasaññānaṃ natthi kiñci ti 
ākiñcaññāyatanaṃ eke abhivadanti appamāṇaṃ āneñjaṃ._
____

[quote, M.2.229-230]
____
But that [state of refined awareness] is originated and self-evident. And there 
is a ending of originated phenomena. Knowing the truth of this, seeing the 
deliverance [from originated phenomena] the Perfect One has gone beyond it.

_Tayidaṃ saṅkhataṃ oḷārikaṃ. Atthi kho pana saṅkhārānaṃ 
nirodho atthetanti iti viditvā tassa nissaraṇadassāvī tathāgato 
tadupātivatto._
____

=== Illustrations: sañjānāti

.Illustration
====
sañjānanti

label
====

____
How does there not come to be stubborn attachment to the conventional 
expressions of one particular country's language and non-overriding of local 
terminology?

_Katañca bhikkhave janapadaniruttiyā ca anabhiniveso hoti samaññāya ca 
anatisāro:_
____

____
In this regard, in different countries they label the same thing a 'dish': a 
'bowl,' a 'vessel,' a 'saucer,' a 'pan,' a 'pot,' or a 'basin.'

_idha bhikkhave tadavekaccesu janapadesu pātī ti sañjānanti pattan ti 
sañjānanti vitthan ti sañjānanti. Sarāvan ti sañjānanti dhāropan ti 
sañjānanti poṇan ti sañjānanti pisīlavan ti sañjānanti._
____

[quote, M.3.235]
____
Whatever they label the thing in one particular country, he thinks 'It seems 
these reverences are speaking with reference to this,' and speaks likewise 
without grasping the terminology.

_Iti yathā yathā naṃ tesu tesu janapadesu sañjānanti: idaṃ kira me 
āyasmanto sandhāya voharantī ti. Tathā tathā voharati aparāmasati._
____

.Illustration
====
sañjānāti

label
====

[quote, M.1.271]
____
'Ascetics, ascetics,' so people label you and you, on being asked: 'Who are 
you?' should acknowledge: 'We are ascetics.'

_Samaṇā samaṇāti vo bhikkhave jano sañjānāti. Tumhe ca panake tumhe ti 
puṭṭhā samānā samaṇāmhā ti paṭijānātha._
____

.Illustration
====
sañjānanti

perceive
====

[quote, M.3.124]
____
And those beings who had uprisen there perceived one another by means of this 
radiance, and thought: 'Indeed there are other beings who have arisen here.'

_yepi tattha sattā upapannā tepi tenobhāsena aññamaññaṃ sañjānanti 
aññepi kira bho santi sattā idhūpapannāti._
____

.Illustration
====
sañjānanti

perceive
====

[quote, M.1.21]
____
Now there are, brahman, some ascetics and Brahmanists who perceive night to be 
the same as day and who perceive day to be the same as night. Of these ascetics 
and Brahmanists I declare that they are abiding in delusion. For I, brahman, 
perceive night to be the same as night, I perceive day to be the same as day.

_Santi kho pana brāhmaṇa eke samaṇabrāhmaṇā rattiṃyeva samānaṃ 
divā ti sañjānanti divāyeva samānaṃ rattī ti sañjānanti idamahaṃ 
tesaṃ samaṇabrāhmaṇānaṃ sammohavihārasmiṃ vadāmi. Ahaṃ kho pana 
brāhmaṇa rattiṃyeva samānaṃ rattī ti sañjānāmi divāyeva samānaṃ 
divā ti sañjānāmi._
____

.Illustration
====
sañjānāmi

perceived to be
====

• From the time when I had complete faith in the Blessed One, from then on 
for a long time I have perceived that I will not be reborn in the plane of 
damnation, that I will not [go to] the plane of damnation. +
_Yadagge ahaṃ bhante bhagavati ekantagato abhippasanno tadagge ahaṃ bhante 
dīgharattaṃ avinipāto avinipātaṃ sañjānāmi_ (D.2.206).

.Illustration
====
sañjānāti

perceives
====

[quote, M.1.111]
____
What one experiences, one perceives. What one perceives, one thinks about. .

_Yaṃ vedeti taṃ sañjānāti. Yaṃ sañjānāti taṃ vitakketi._
____

