== Saḷāyatana

=== Renderings

- _cakkhu_: eye

- _cakkhu_: vision

- _cakkhu_: the visual sense

- _rūpāyatana_: visible object

- _phassāyatanāna_: sense

- _āyatana_: basis of sensation

- _saḷāyatana_: the six senses

- _ajjhattikāni āyatanāni_: internal bases of sensation

- _bāhirāni āyatanāni_: external bases of sensation

- _cha ajjhattikāni āyatanāni_: the six senses

- _cha bāhirāni āyatanāni_: the six sense objects

- _sabbāyatanehi_: the six senses and their objects

=== Introduction

==== Internal and external āyatana

There are two groups of sixfold bases of sensation: internal and external.

1. Six internal bases of sensation: the six senses
+
****
_Cha ajjhattikāni āyatanāni cakkhāyatanaṃ sotāyatanaṃ ghānāyatanaṃ 
jivhāyatanaṃ kāyāyatanaṃ manāyatanaṃ._
****

2. Six external bases of sensation: the six sense objects
+
****
_Cha bāhirāni āyatanāni rūpāyatanaṃ saddāyatanaṃ gandhāyatanaṃ 
rasāyatanaṃ phoṭṭhabbāyatanaṃ dhammāyatanaṃ_ (D.3.243).
****

==== Cakkhuṃ=cakkhāyatanaṃ

The scriptures rarely use the term _āyatanaṃ_ in reference to individual 
senses. Although _saḷāyatanaṃ_ occurs 668 times, _cakkhāyatanaṃ_ occurs 
just 11 times, and _cakkhundriyaṃ_ occurs 452 times. The shortage of 
_cakkhāyatanaṃ_ is because _cakkhāyatanaṃ_ is usually abbreviated to 
_cakkhuṃ_. The suffix -_āyatanaṃ_ is apparently disposable.

That _cakkhuṃ=cakkhāyatanaṃ_ is proven in several suttas. The 
_Girimānanda Sutta_ says _cakkhuṃ_ is part of _āyatanesu_: _cakkhuṃ 
anattā rūpā anattā... mano anattā dhammā anattā ti. Iti imesu chasu 
ajjhattikabāhiresu āyatanesu anattānupassī viharati_ (A.5.109). Similar 
evidence is found in the _Parihānadhamma Sutta_ (S.4.77) and the 
_Chabbisodhana Sutta_ (M.3.32).

The fuller terms for all six senses is listed in the _Sammādiṭṭhi Sutta_: 
_cakkhāyatanaṃ sotāyatanaṃ ghānāyatanaṃ jivhāyatanaṃ 
kāyāyatanaṃ manāyatanaṃ_ (M.1.52).

==== Āyatanaṃ=phassāyatanānaṃ

But _āyatanaṃ_ is also an abbreviation -- for _phassāyatanānaṃ_. At 
S.4.44 _cakkhuṃ_ is called _paṭhamaṃ phassāyatanaṃ_; _sotaṃ_ is 
_dutiyaṃ phassāyatanaṃ_; and so on.

So _cakkhu's_ full name is _cakkhusamphassāyatanaṃ._ The others are 
_sotasamphassāyatanaṃ ghānasamphassāyatanaṃ jivhāsamphassāyatanaṃ 
kāyasamphassāyatanaṃ manosamphassāyatanaṃ_. These full terms occur just 
once in the scriptures, in the _Dhātuvibhaṅga Sutta_ (M.3.239).

In this full rendering it is clear that _ayatana_ means 'basis.' For example, 
'basis of _cakkhusamphassa'_ etc_._ So now let us examine the meaning of 
_cakkhusamphassa_.

==== Cakkhusamphassa: visual sensation

_Cakkhusamphassa_ is explained in the following quote:

[quote, S.4.68]
____
Dependent on _cakkhu_ and visible objects there arises advertence to the visual 
field. The meeting, the encounter, the concurrence of these three things is 
called visual sensation.

_Cakkhuñca paṭicca rūpe uppajjati cakkhuviññāṇaṃ. Yā kho bhikkhave 
imesaṃ tiṇṇaṃ dhammānaṃ saṅgati sannipāto samavāyo ayaṃ 
vuccati bhikkhave cakkhusamphasso._
____

Thus _cakkhusamphassāyatanaṃ_ would mean 'basis for visual sensation.'

==== Terminology: full terms

The full terms of the six _āyatanā_ would therefore be:

• basis for visual sensation +
☸ _cakkhuṃ_ or _cakkhāyatanaṃ_

• basis for auditory sensation +
☸ _sotaṃ_ or _sotāyatanaṃ_

• basis for olfactory sensation +
☸ _ghānaṃ_ or _ghānāyatanaṃ_

• basis for gustatory sensation +
☸ _jivhā_ or _jivhāyatanaṃ_

• basis for tactile sensation +
☸ _kāyo_ or _kāyāyatanaṃ_

• basis for mental sensation +
☸ _mano_ or _manāyatanaṃ_

==== Terminology: abbreviated

The full terms are unwieldy in practice, and we will instead abbreviate them:

- the visual sense

- the auditory sense

- the olfactory sense

- the gustatory sense

- the tactile sense

- the mental sense

==== External āyatana: full and concise renderings

The corresponding objects of sensation are the external _āyatana_ (_bāhirāni 
āyatanāni_)_: rūpāyatanaṃ saddāyatanaṃ gandhāyatanaṃ rasāyatanaṃ 
phoṭṭhabbāyatanaṃ dhammāyatanaṃ._ These terms are not abbreviations. 
Therefore, if we again render _āyatana_ as 'basis,' then each of the 
_āyatanas_ are 'a basis of sensation,' and the _āyatanas_ can be rendered as:

____
visible objects basis of sensation

_rūpāyatanaṃ_
____

[quote, D.3.243]
____
mentally known objects basis of sensation

_dhammāyatanaṃ._
____

But the phrase 'basis of sensation' is redundant, and so we render the terms as:

____
visible objects...

_rūpāyatanaṃ..._
____

____
mentally known objects

_dhammāyatanaṃ_
____

==== Justifying the plural: visible objects

We have used the word 'objects.' The plural case is justified for three reasons:

1. Context supports it.

2. For grammatical reasons, by which it could be singular or plural.

3. By the common occurrence elsewhere of the plural case when the internal 
bases of sensation are in the singular case. For example:

[quote, M.3.281]
____
dependent on the visual sense and visible objects, advertence to the visual 
field arises

_Cakkhuñca paṭicca rūpe ca uppajjati cakkhuviññāṇaṃ._
____

==== Āyatanāni: renaming the Internal and external bases of sensation

The 'internal bases of sensation' can often instead be called 'the six senses,' 
and the 'external bases of sensation' can often instead be called 'the six 
sense objects.' For example:

[quote, M.3.32]
____
There are these six senses and their objects rightly explained by the Blessed 
One who knows and sees [the nature of reality], the Arahant, the Perfectly 
Enlightened One.

_cha kho panimāni āvuso ajjhattikabāhirāni āyatanāni tena bhagavatā 
jānatā passatā arahatā sammāsambuddhena sammadakkhātāni._
____

[quote, D.3.223]
____
He abides contemplating the voidness of personal qualities in the six senses 
and their objects.

_imesu chasu ajjhattikabāhiresu āyatanesu anattānupassī viharati._
____

[quote, S.5.426]
____
And what is the noble truth of suffering? One should reply: the six senses.

_Katamañca bhikkhave dukkhaṃ ariyasaccaṃ? Cha ajjhattikāni 
āyatanānītissa vacanīyaṃ._
____

[quote, S.4.174]
____
'The empty village' represents the six senses.

_Suñño gāmoti kho bhikkhave channetaṃ ajjhattikānaṃ āyatanānaṃ 
adhivacanaṃ._
____

[quote, S.4.174]
____
'Village-attacking dacoits' represents the six sense objects.

_Corā gāmaghātakāti kho bhikkhave channetaṃ bāhirānaṃ āyatanānaṃ 
adhivacanaṃ._
____

==== Rendering of phrases

Our renderings of terms produces the following phrases:

____
In seeing a visible object via the visual sense

_cakkhunā rūpaṃ disvā_
____

____
In hearing an audible object via the auditory sense

_sotena saddaṃ sutvā_
____

____
In smelling a smellable object via the olfactory sense

_ghānena gandhaṃ ghāyitvā_
____

____
In tasting a tasteable object via the gustatory sense

_jivhāya rasaṃ sāyitvā_
____

____
In feeling a tangible object via the tactile sense

_kāyena phoṭṭhabbaṃ phusitvā_
____

[quote, D.3.250]
____
In knowing a mentally known object via the mental sense

_manasā dhammaṃ viññāya._
____

==== Alternative spellings

In some cases there are alternative Pāli spellings, as follows:

____
in seeing a visible object (no alternative)

_rūpaṃ disvā_
____

____
in hearing an audible object (no alternative)

_saddaṃ sutvā_
____

____
in smelling a smellable object (three alternatives)

_gandhaṃ ghāyitvā; gandhaṃ ghatvā; gandhaṃ ghātvā_
____

____
in tasting a tasteable object (two alternatives)

_rasaṃ sāyitvā; rasaṃ bhotvā_
____

[quote, =when touched by a tangible object]
____
in feeling a tangible object (two alternatives)

_phoṭṭhabbaṃ phusitvā; phassaṃ phussa_
____

[quote, S.4.75; Th.v.802; Th.v.814]
____
in knowing a mentally known object (two alternatives)

_dhammaṃ viññāya; dhammaṃ ñatvā._
____

==== Alternative renderings for senses and sense objects

Sometimes suttas refer to the senses as physical organs, and we render them 
accordingly:

- eye and sights

- ear and sounds

- nose and odours

- tongue and flavours

- body and physical sensations

- mind and mental phenomenona

Two examples where these renderings are appropriate:

1. The ignorant Everyman is

- struck in the eye by pleasing and displeasing sights;

- struck in the ear by pleasing and displeasing sounds;

- struck in the nose by pleasing and displeasing odours;

- struck on the tongue by pleasing and displeasing flavours;

- struck on the body by pleasing and displeasing physical sensations;

[quote, S.4.201]
____
struck in the mind by pleasing and displeasing mental phenomena.

_assutavā puthujjano cakkhusmiṃ haññati manāpāmanāpehi rūpehi... 
manasmiṃ haññati manāpāmanāpehi dhammehi._
____

2. When a bhikkhu has not developed and cultivated mindfulness of the body,
+
****
_yassa kassaci bhikkhuno kāyagatā sati abhāvitā abahulīkatā_
****

____
the eye inclines towards pleasing visible objects

_cakkhu āviñjati manāpikesu rūpesu_
____

____
and displeasing visible objects are loathsome

_amanāpikassa rūpā paṭikkūlā honti_
____

- ear inclines towards pleasing audible objects

- nose inclines towards pleasing smellable objects

- tongue inclines towards pleasing tasteable objects

- body inclines towards pleasing tangible objects

- mind inclines towards pleasing mentally known objects (S.4.199).

=== Illustrations

.Illustration
====
cakkhu

eye
====

[quote, D.3.219]
____
There are three eyes. The physical eye, the divine eye, and the eye of 
penetrative discernment.

_Tīṇi cakkhuni maṃsacakkhu dibbacakkhu paññācakkhu._
____

.Illustration
====
cakkhunā

eye
====

[quote, Sn.v.1142]
____
I see him with my mind as if with my eye

_Passāmi naṃ manasā cakkhunā ca._
____

.Illustration
====
cakkhu

eye
====

[quote, A.5.110]
____
Illnesses of the eye, ear, nose, etc

_cakkhurogo sotarogo ghānarogo._
____

.Illustration
====
cakkhuṃ

vision
====

[quote, Vin.1.11-12]
____
While this discourse was being propounded, the uncorrupted, stainless vision of 
the nature of reality arose within Venerable Koṇḍañña that whatever is of 
an originated nature is destined to cease.

__āyasmato koṇḍaññassa virajaṃ vītamalaṃ dhammacakkhuṃ udapādi 
yaṃ kiñci samudayadhammaṃ sabbaṃ taṃ nirodhadhamman ti._
____

.Illustration
====
cakkhunā

vision
====

[quote, M.1.169]
____
Surveying the world with the vision of a Buddha, I saw beings with much dust in 
their eyes, and those with little.

_addasaṃ kho ahaṃ bhikkhave buddhacakkhunā lokaṃ volokento satte 
apparajakkhe mahārajakkhe._
____

.Illustration
====
cakkhuṃ

vision
====

[quote, M.1.510]
____
Māgandiya, you do not have noble vision by which you might know [spiritual] 
health and see the Untroubled.

_Taṃ hi te māgandiya ariyaṃ cakkhuṃ natthi yena tvaṃ ariyena cakkhunā 
ārogyaṃ jāneyyāsi nibbānaṃ passeyyāsī ti._
____

.Illustration
====
cakkhuṃ

vision
====

____
With purified divine vision surpassing that of men, he sees beings passing away 
and being reborn, inferior and superior, well-favoured and ill-favoured, 
fortunate and unfortunate,

_dibbena cakkhunā visuddhena atikkantamānusakena satte passati cavamāne 
upapajjamāne hīne paṇīte suvaṇṇe dubbaṇṇe sugate duggate_
____

[quote, D.1.82]
____
... and he understands how beings fare according to their deeds.

_yathākammūpage satte pajānāti._
____

.Illustration
====
cakkhuṃ

the visual sense
====

____
There are these six senses and their objects rightly explained by the Blessed 
One who knows and sees [the nature of reality], the Arahant, the Perfectly 
Enlightened One. Which six?

_cha kho panimāni āvuso ajjhattikabāhirāni āyatanāni tena bhagavatā 
jānatā passatā arahatā sammāsambuddhena sammadakkhātāni. Katamāni cha:_
____

____
the visual sense and visible objects

_cakkhuṃ ceva rūpā ca_
____

____
the auditory sense and audible objects

_sotañca saddā ca_
____

____
the olfactory sense and smellable objects

_ghānañca ghandhā ca_
____

____
the gustatory sense and tasteable objects

_jivhā ca rasā ca_
____

____
the tactile sense and tangible objects

_kāyo ca phoṭṭhabbā ca_
____

[quote, M.3.32]
____
the mental sense and mentally known objects

_mano ca dhammā ca._
____

.Illustration
====
cakkhuṃ

the visual sense
====

[quote, D.2.338]
____
When this [wretched human] body has vitality, warmth, and mental consciousness, 
then it goes and comes back, stands and sits and lies down, sees a visible 
object via its visual sense, hears an audible object via its auditory sense, 
smells a smellable object via its olfactory sense, tastes a tasteable object 
via its gustatory sense, feels a tangible object via its tactile sense, and 
knows a mentally known object via its mental sense.

_yadāyaṃ kāyo āyusahagato ca hoti usmāsahagato ca viññāṇasahagato ca 
tadā abhikkamati pi paṭikkamati pi tiṭṭhati pi nisīdati pi seyyampi 
kappeti cakkhunāpi rūpaṃ passati sotenapi saddaṃ suṇāti ghānenapi 
gandhaṃ ghāyati jivhāyapi rasaṃ sāyati kāyenapi phoṭṭhabbaṃ 
phusati manasāpi dhammaṃ vijānāti._
____

.Illustration
====
āyatanāni

senses
====

• There are just six senses, affected through one or other of which the fool 
experiences pleasure and pain. +
☸ _saḷevāyatanāni yehi puṭṭho bālo sukhadukkhaṃ 
paṭisaṃvediyati etesaṃ vā_ aññatarena (S.2.23-24).

.Illustration
====
saḷāyatana

six senses
====

____
With the origination of the six senses comes the origination of sensation

_saḷāyatanasamudayā phassasamudayo_
____

[quote, M.1.52]
____
With the ending of the six senses comes the ending of sensation

_saḷāyatananirodhā phassanirodho._
____

.Illustration
====
āyatanānaṃ

senses
====

[quote, D.2.307]
____
"What is birth? It is the birth, being born, arising, rebirth, appearance of 
aggregates, acquiring of senses by the various beings in the various classes of 
beings. This is called birth.

_Katamācāvuso jāti: yā tesaṃ tesaṃ sattānaṃ tamhi tamhi sattanikāye 
jāti sañjāti okkanti abhinibbatti khandhānaṃ pātubhāvo āyatanānaṃ 
paṭilābho ayaṃ vuccatāvuso jāti._
____

.Illustration
====
āyatanāni

senses
====

____
What are the six mastered senses?

_Katamāni ca bhikkhave cha abhibhāyatanāni_
____

____
In this regard, when a bhikkhu sees a visible object via the visual sense, and 
there does not arise in him unvirtuous, spiritually unwholesome memories and 
thoughts conducive to psychological bondage, the bhikkhu should understand 
that: 'This sense has been mastered.' For this has been called a mastered sense 
by the Blessed One.

_Idha bhikkhave bhikkhuno cakkhunā rūpaṃ disvā nūppajjanti pāpakā 
akusalā sarasaṅkappā saṃyojanīyā. Veditabbametaṃ bhikkhave bhikkhunā 
abhibhūtametaṃ āyatanaṃ abhibhāyatanaṃ hetaṃ vuttaṃ bhagavatā ti._
____

The sutta continues

____
In hearing an audible object via the auditory sense...

_Sotena saddaṃ sutvā_
____

____
In smelling a smellable object via the olfactory sense...

_Ghānena gandhaṃ ghāyitvā_
____

____
In tasting a tasteable object via the gustatory sense...

_Jivhāya rasaṃ sāyitvā_
____

____
In touching a tangible object via the tactile sense...

_Kāyena phoṭṭhabbaṃ phusitvā_
____

[quote, S.4.77]
____
In knowing a mentally known object via the mental sense...

_Manasā dhammaṃ viññāya._
____

.Illustration
====
sabbāyatanehi

the six senses and their objects
====

[quote, Sn.v.373]
____
One of purified wisdom who has utterly transcended egocentric conception in 
regards to things of the past and future, who is free of [bondage to] the six 
senses and their objects: he would properly fulfil the ideals of religious 
asceticism in the world.

_Atītesu anāgatesu cā pi kappātīto aticca suddhipañño +
Sabbāyatanehi vippamutto sammā so loke paribbajeyya._
____

