== Saṅkhāra

=== Renderings

- _saṅkhāra_: originated phenomenon

- _saṅkhāra_: originative factor

- _saṅkhāra_: karmically consequential deed

- _saṅkhāra_: effort

- _saṅkhāra_: aspiration

- _saṅkhāra_: untranquillising factors

- _saṅkhāra_: dynamic

- _saṅkhāra_: activity

- _saṅkhāra_: deed

- _saṅkhārakkhandha_: the aggregate of intentional activities

- _abhisaṅkhāra_: karmically consequential deed

- _abhisaṅkhāra_: aspiration

- _abhisaṅkhāra_: impulsion

- _āyusaṅkhārā_: factors essential to life

- _iddhābhisaṅkhāra_: act of psychic power

=== Introduction

==== Active and passive sense, and rendering saṅkhārakkhandha

_Saṅkhāra_ has either an active or passive sense, meaning either:

1. 'the things that are produced by a combination of co-operating factors,' or

2. 'factors (or forces) that function together in producing an effect.' (Bodhi, 
MLDB Intro p.55).

We call these 1) 'originated phenomena' and 2) 'originative factors.'

For example:

1. The ignorant Everyman considers bodily form to be the [absolute] Selfhood. 
That considering is an originated phenomenon. What is the basis, origin, object 
of genesis and production of that originated phenomenon? When the ignorant 
Everyman is affected by sense impression born of sensation and uninsightfulness 
into reality, craving arises. That originated phenomenon is born from that.
+
****
_rūpaṃ attato samanupassati. Yā kho pana sā bhikkhave samanupassanā 
saṅkhāro so. So pana saṅkhāro kinnidāno kiṃsamudayo kiñjātiko 
kimpabhavoti. Avijjāsamphassajena bhikkhave vedayitena phuṭṭhassa 
assutavato puthujjanassa uppannā taṇhā. Tatojo so saṅkhāro_ (S.3.96).
****

2. There has arisen in me this faculty of psychological pain. That arises with 
grounds, with a source, with originative factors, with necessary conditions. It 
would be impossible for that faculty of psychological pain to arise without 
grounds, without a source, without originative factors, without necessary 
conditions.'
+
****
_uppannaṃ kho me idaṃ domanassindriyaṃ. Tañca kho sanimittaṃ 
sanidānaṃ sasaṅkhāraṃ sappaccayaṃ. Taṃ vata animittaṃ anidānaṃ 
asaṅkhāraṃ appaccayaṃ domanassindriyaṃ uppajjissatī ti netaṃ 
ṭhānaṃ vijjati_ (S.5.214).
****

==== Saṅkhārakkhandha: the aggregate of intentional activities

In some circumstances _saṅkhāra_ means activity, not necessarily intentional:

[quote, M.1.301]
____
In-breathing and out-breathing are bodily activity. Thinking and pondering are 
speech activity. Perception and sense impression are mental activity.

_Assāsapassāsā kho āvuso visākha kāyasaṅkhāro vitakkavicārā 
vacīsaṅkhāro saññā ca vedanā ca cittasaṅkhāro ti._
____

But _saṅkhārakkhandha_ is defined in terms of _cetanā_ and _sañcetanā_. 
We therefore render it as 'the aggregate of intentional activities':

[quote, S.3.60]
____
What are intentional activities (i.e. _saṅkhārakkhandha_)? The aggregate of 
intentionality (_cetanākāyā_) is sixfold: intentionality concerning visible 
objects, audible objects, smellable objects, tasteable objects, tangible 
objects, and mentally known objects.

_katame ca bhikkhave saṅkhārā. Chayime bhikkhave cetanākāyā. 
Rūpasañcetanā saddasañcetanā gandhasañcetanā rasasañcetanā 
phoṭṭhabbasañcetanā dhammasañcetanā._
____

The Visuddhimagga calls _saṅkhārakkhandha_ 'formations' 
(_saṅkhatamabhisaṅkharontīti kho, bhikkhave, tasmā saṅkhārā ti 
vuccantī ti_). But Bhikkhu Bodhi calls this analysis 'later, more elaborate' 
(CDB p.841). Bodhi himself call the aggregate 'volitional formations.'

For discussion on calling _cetanā_ intentionality, not intention, see Glossary 
sv _Cetanā_.

==== The abhi- prefix

With acts of psychic power the _abhi_- prefix is applied consistently. In some 
words, like 'aspiration,' it sometimes occurs, sometimes not, and is without 
significance.

- Then the Blessed One performed an act of psychic power (_tathārūpaṃ 
iddhābhisaṅkhāraṃ abhisaṅkhāsi_) such that the brahman Brahmāyu saw 
that the Blessed One's penis was enclosed in a sheath (M.2.143).

=== Saṅkhāra and originated phenomenon

.Illustration
====
saṅkhāra

originated phenomenon
====

____
Or he is unsure, doubtful, undecided about the [significance of the] true 
teaching.

_kaṅkhī hoti vicikicchī aniṭṭhaṅgato saddhamme_
____

[quote, S.3.100]
____
That unsureness, doubt, and undecidedness about the [significance of the] true 
teaching is an originated phenomenon

_yā kho pana sā bhikkhave kaṅkhitā vicikicchitā aniṭṭhaṅgatatā 
saddhamme saṅkhāro so._
____

.Illustration
====
saṅkhāra

originated phenomenon
====

____
Ānanda, I have taught the successive ending of originated phenomena.

_anupubbasaṅkhārānaṃ nirodho akkhāto_
____

For one who attains:

____
first jhāna, speech is ended.

_paṭhamaṃ jhānaṃ samāpannassa vācā niruddhā hoti_
____

____
second jhāna, thinking and pondering are ended.

_vitakkavicārā niruddhā honti_
____

____
third jhāna, rapture is ended.

_pīti niruddhā hoti_
____

____
fourth jhāna, breathing is ended.

_assāsapassāsā niruddhā honti_
____

____
the state of awareness of boundless space, the perception of the refined 
material states of awareness is ended.

_rūpasaññā niruddhā hoti_
____

____
the state of awareness of boundless mental consciousness, the perception of the 
state of awareness of boundless space is ended.

__ākāsānañcāyatanasaññā niruddhā hoti_
____

____
the state of awareness of nonexistence, the perception of the state of 
awareness of boundless mental consciousness is ended.

_viññāṇañcāyatanasaññā niruddhā hoti_
____

____
the ending of perception and sense impression, perception and sense impression 
are ended.

_saññāvedayitanirodhaṃ samāpannassa saññā ca vedanā ca niruddhā 
honti_
____

[quote, S.4.217]
____
For a bhikkhu whose _āsavas_ are destroyed, attachment, hatred, and 
undiscernment of reality are ended.

_khīṇāsavassa bhikkhuno rāgo niruddho hoti doso niruddho hoti moho 
niruddho hoti._
____

.Illustration
====
saṅkhāra

originated phenomena
====

[quote, Th.v.715]
____
I do not have the thoughts "I have been" or "I will be." Originated phenomena 
will pass away. What lamentation is there in that?

_Na me hoti ahosin ti bhavissan ti na hoti me +
Saṅkhārā vigamissanti tattha kā paridevanā._
____

[quote, Th.v.716]
____
There is no fear for one who perceives according to reality the pure and simple 
origination of phenomena, and the pure and simple continuity of originated 
phenomena, captain.

_suddhaṃ dhammasamuppādaṃ suddhaṃ saṅkhārasantatiṃ +
passantassa yathābhūtaṃ na bhayaṃ hoti gāmaṇi._
____

.Illustration
====
saṅkhāra

originated phenomena
====

____
Now see, bhikkhus! That mountain's name has vanished, those people have died, 
and that Blessed One has passed away to the Untroubled-without-residue.

_Passatha bhikkhave sā cevimassa pabbatassa samaññā antarahitā. Te ca 
manussā kālakatā. So ca bhagavā parinibbuto._
____

[quote, S.2.191]
____
Thus unlasting are originated phenomena, thus unenduring are originated 
phenomena, thus unconsoling are originated phenomena. It is time enough, 
bhikkhus, to be disillusioned with all originated phenomena, to be unattached 
to them, to be liberated from them.

_Evaṃ aniccā bhikkhave saṅkhārā evaṃ addhuvā bhikkhave saṅkhārā 
evaṃ anassāsikā bhikkhave saṅkhārā. Yāvañcidaṃ bhikkhave alameva 
sabbasaṅkhāresu nibbindituṃ alaṃ virajjituṃ alaṃ vimuccituṃ._
____

.Illustration
====
saṅkhāra

originated phenomena
====

____
What, Ānanda, is the perception of the unlastingness of all originated 
phenomena?

_Katamācānanda sabbasaṅkhāresu aniccasaññā_
____

[quote, A.5.111]
____
In this regard a bhikkhu is revolted, appalled, and disgusted by all originated 
phenomena.

_Idhānanda bhikkhu sabbasaṅkhārehi aṭṭīyati harāyati jigucchati._
____

.Illustration
====
saṅkhāra

originated phenomena
====

[quote, D.2.36]
____
This is indeed a matter difficult to realise, namely the quelling of all 
originated phenomena, the relinquishment of the whole phenomenon of attachment, 
the destruction of craving, the passing away [of originated phenomena], the 
ending [of originated phenomena], the Untroubled.

_Idampi kho ṭhānaṃ duddasaṃ yadidaṃ sabbasaṅkhārasamatho 
sabbūpadhipaṭinissaggo taṇhakkhayo virāgo nirodho nibbānaṃ._
____

.Illustration
====
saṅkhāra

originated phenomena
====

[quote, S.1.135]
____
But why do you assume 'a being'? That is just your acquiescence in wrong view 
&#8203;[of reality], Māra. This is nothing but a heap of originated phenomena. Here 
no being is found.

_Kinnu satto ti paccesi māradiṭṭhigatannu te +
Suddhasaṅkhārapuñjoyaṃ nayidha sattūpalabbhati._
____

=== Saṅkhārakkhandha

.Illustration
====
saṅkhāra

intentional activities
====

[quote, S.3.101]
____
Whatever kind of intentional activities there are, whether past, future, or 
present, internal or external, gross or subtle, inferior or sublime, far or 
near: this is called the aggregate of intentional activities.

_Yā kāci saṅkhārā atīnānāgatapaccuppannaṃ ajjhattaṃ vā bahiddhā 
vā oḷārikaṃ vā sukhumaṃ vā hīnaṃ vā paṇītaṃ vā yaṃ dūre 
santike vā ayaṃ vuccati saṅkhārakkhandho._
____

.Illustration
====
saṅkhāra

intentional activities
====

[quote, A.1.82]
____
Unvirtuous, spiritually unwholesome factors arise with intentional activities, 
not without intentional activities. By abandoning those very intentional 
activities, those unvirtuous, spiritually unwholesome factors do not exist.

_Sasaṅkhārā bhikkhave uppajjanti pāpakā akusalā dhammā no 
asaṅkhārā. Tesaṃ yeva saṅkhārānaṃ pahānā evaṃ te pāpakā 
akusalā dhammā na honti._
____

.Illustration
====
saṅkhāra

intentional activities
====

[quote, D.2.35]
____
The Bodhisatta Vipassī dwelt contemplating the [co-conditional] arising and 
disappearance of the five aggregates:... Such are intentional activities; such 
the origination of intentional activities; such the vanishing of intentional 
activities...

_Iti saṅkhārā iti saṅkhārānaṃ samudayo iti saṅkhārānaṃ 
atthaṅgam._
____

.Illustration
====
saṅkhāra

intentional activities
====

____
An arising of intentional activities is discernable

_saṅkhārānaṃ uppādo paññāyati_
____

____
A disappearance is discernable

_vayo paññāyati_
____

[quote, S.3.38]
____
A changeability while persisting is discernable

__ṭhitassa aññathattaṃ paññāyati._
____

=== Saṅkhāra and karmically consequential deeds

==== Introduction

Karmically consequential deeds are the _saṅkhārā_ of _paṭiccasamuppāda_. 
Karmically consequential deeds are either:

1. meritorious
+
****
_puññaṃ_
****

2. demeritorious
+
****
_apuññaṃ_
****

3. karmically neutral
+
****
_āneñjaṃ_
****

Arahants do not perform karmically consequential deeds, whether meritorious, 
demeritorious, or karmically neutral.

.Illustration
====
saṅkhāra

karmically consequential deed
====

____
And what is dependent origination?

_katamo ca bhikkhave paṭiccasamuppādo?_
____

____
Karmically consequential deeds arise dependent on uninsightfulness into reality.

_avijjāpaccayā saṅkhārā_
____

[quote, S.2.2-4]
____
The stream of sense consciousness arises dependent on karmically consequential 
deeds.

_saṅkhārapaccayā viññāṇaṃ._
____

.Illustration
====
saṅkhāra

karmically consequential deed
====

____
Bhikkhus, if someone who has acquiesced in uninsightfulness into reality 
undertakes a karmically consequential deed that is meritorious, his stream of 
sense consciousness (_viññāṇaṃ_) is furnished with merit;

_Avijjāgatoyaṃ bhikkhave purisapuggalo puññaṃ ce saṅkhāraṃ 
abhisaṅkharoti puññopagaṃ hoti viññāṇaṃ._
____

____
If he undertakes a karmically consequential deed that is demeritorious, his 
stream of sense consciousness is furnished with demerit;

_Apuññaṃ ce saṅkhāraṃ abhisaṅkharoti apuññopagaṃ hoti 
viññāṇaṃ._
____

____
If he undertakes a karmically consequential deed that is karmically neutral, 
his stream of sense consciousness is furnished with what is karmically neutral.

_Āneñjaṃ ce saṅkhāraṃ abhisaṅkharoti āneñjūpagaṃ hoti 
viññāṇaṃ._
____

[quote, S.2.82]
____
When a bhikkhu has abandoned uninsightfulness into reality (_avijjā_) and 
aroused insightfulness into reality (_vijjā_), then, with the fading away of 
uninsightfulness into reality and the arising of insightfulness into reality, 
he does not undertake a karmically consequential deed that is meritorious, 
demeritorious, or karmically neutral.

_Yato kho bhikkhave bhikkhuno avijjā pahīṇā hoti vijjā uppannā so 
avijjāvirāgā vijjūppādā neva puññābhisaṅkhāraṃ abhisaṅkharoti. 
Na apuññābhisaṅkhāraṃ abhisaṅkharoti. Na āneñjābhisaṅkhāraṃ 
abhisaṅkharoti._
____

.Illustration
====
saṅkhāra

karmically consequential conduct
====

[quote, D.3.218]
____
Three kinds of karmically consequential conduct: karmically consequential 
conduct that is meritorious, demeritorious, or karmically neutral

_Tayo saṅkhārā: puññābhisaṅkhāro apuññābhisaṅkhāro 
āneñjābhisaṅkhāro._
____

Comment:

_Saṅkhāro_ and _abhisaṅkhāro_ are treated as synonyms.

.Illustration
====
saṅkhāra

karmically consequential deed
====

____
-- What do you think, bhikkhus: can a bhikkhu whose _āsavas_ are destroyed, 
undertake a karmically consequential deed that is meritorious, demeritorious, 
or karmically neutral?

_Taṃ kiṃ maññatha bhikkhave api nu kho khīṇāsavo bhikkhu 
puññābhisaṅkhāraṃ vā abhisaṅkhareyya apuññābhisaṅkhāraṃ vā 
abhisaṅkhareyya āneñjābhisaṅkhāraṃ vā abhisaṅkhareyyā ti._
____

-- No, bhante.

____
-- When there are utterly no karmically consequential deeds, with the ending of 
karmically consequential deeds, would the stream of sense consciousness be 
discerned?

_Sabbaso vā pana saṅkhāresu asati saṅkhāranirodhā api nu kho 
viññāṇaṃ paññāyethā ti?_
____

-- No, bhante (S.2.83).

Comment:

_Saṅkhāro_ and _abhisaṅkhāro_ are treated as synonyms.

.Illustration
====
saṅkhāra

karmically consequential deeds
====

• Wherever the stream of sense consciousness is established and has 
&#8203;[egoistically] matured, there is the appearance of denomination-and-bodily-form 
+
_Yattha patiṭṭhitaṃ viññāṇaṃ virūḷhaṃ atthi tattha 
nāmarūpassa avakkanti._

• Where there is the appearance of denomination-and-bodily-form, there is the 
growth of karmically consequential deeds. +
_Yattha atthi nāmarūpassa avakkanti atthi tattha saṅkhārānaṃ vuddhi._

• Where there is the growth of karmically consequential deeds, renewed states 
of individual existence and rebirth occur in the future. +
_Yattha atthi saṅkhārānaṃ vuddhi atthi tattha āyatiṃ 
punabbhavābhinibbatti_ (S.2.101).

.Illustration
====
saṅkhāra

karmically consequential deeds
====

What are karmically consequential deeds (_saṅkhārā_)? What is the 
&#8203;[co-conditional] origination of karmically consequential deeds? What is the 
&#8203;[co-conditional] ending? What is the practice leading to the ending?

____
Karmically consequential deeds are threefold: by way of body, speech, and mind.

_Tayome āvuso saṅkhārā: kāyasaṅkhāro vacīsaṅkhāro 
cittasaṅkhāro._
____

____
With the origination of uninsightfulness into reality comes the origination of 
karmically consequential deeds.

_Avijjāsamudayā saṅkhārasamudayo._
____

____
With the ending of uninsightfulness into reality comes the ending of karmically 
consequential deeds.

_Avijjānirodhā saṅkhāranirodho._
____

[quote, M.1.54]
____
The noble eightfold path is the practice leading to the ending of karmically 
consequential deeds.

_Ayameva ariyo aṭṭhaṅgiko maggo saṅkhāranirodhagāminī paṭipadā._
____

.Illustration
====
saṅkhāra

karmically consequential deeds
====

Those ascetics and Brahmanists who do not discern according to reality 
suffering, the origin of suffering, the ending of suffering, the practice 
leading to the ending of suffering

____
they take delight in karmically consequential deeds that lead to birth

_te jātisaṃvattanikesu saṅkhāresu abhiramanti_
____

[quote, S.5.449]
____
Taking delight in such karmically consequential deeds, they perform karmically 
consequential deeds that lead to birth

_Te jātisaṃvattanikesu saṅkhāresu abhiratā... jātisaṃvattanikepi 
saṅkhāre abhisaṅkharonti._
____

.Illustration
====
saṅkhāra

karmically consequential deed
====

____
Either on one's own initiative or prompted by others one undertakes a 
karmically consequential deed by way of body, speech, or mind because of which 
pleasure and pain arise for oneself personally.

_Sāmaṃ vā... pare vā taṃ ānanda kāyasaṅkhāraṃ... 
vacīsaṅkhāraṃ... manosaṅkhāraṃ abhisaṅkharonti yaṃ paccayāssa 
taṃ uppajjati ajjhattaṃ sukhadukkhaṃ_
____

[quote, S.2.40]
____
Either fully conscious or not fully conscious one undertakes a karmically 
consequential deed by way of body, speech, or mind because of which pleasure 
and pain arise for oneself personally.

_Sampajāno vā... asampajāno vā taṃ ānanda kāyasaṅkhāraṃ... 
vacīsaṅkhāraṃ... manosaṅkhāraṃ abhisaṅkharoti yaṃpaccayāssa 
taṃ uppajjati ajjhattaṃ sukhadukkhaṃ._
____

=== Saṅkhāra and effort

==== Introduction: saṅkhāra and effort

_Saṅkhāra_ is one of the factors of the four paths to psychic power 
(_cattāro iddhipāde_). And these four roads are one of the seven groups of 
factors conducive to enlightenment (_sattannaṃ bodhipakkhiyānaṃ 
dhammānaṃ_, D.3.97; It.96). We will first review these groups.

==== Introduction: the seven groups of factors conducive to enlightenment

The seven groups of factors conducive to enlightenment are:

1. the [contemplation of the] four bases of mindfulness, _ +
☸ cattāro satipaṭṭhānā_

2. the four modes of right inward striving,_ +
☸ cattāro sammappadhāneā_

3. the four paths to psychic power,_ +
☸ cattāro iddhipādā_

4. the five spiritual faculties, _ +
☸ pañcindriyāni_

5. the five spiritual powers, _ +
☸ pañca balāni_

6. the seven factors of enlightenment, _ +
☸ satta bojjhaṅgā_

7. the noble eightfold path,_ +
☸ ariyo aṭṭhaṅgiko maggo_ (M.2.238).

==== Introduction: the four paths to psychic power

Let us consider the first of the four paths to psychic power:

[quote, S.5.268]
____
The path to psychic power involving inward collectedness based on desire 
accompanied by the efforts of inward striving.

_chandasamādhi-padhānasaṅkhārasamannāgato iddhipādo._
____

In the context of the four paths to psychic power, therefore, we render 
_saṅkhāra_ as 'effort.' The efforts of inward striving are fourfold, as the 
following passage explains:

==== Introduction: the four efforts of inward striving

The four 'efforts of inward striving' (_padhānasaṅkhārā_) are:

1. To prevent the arising of unarisen spiritually unwholesome factors...
+
****
_So anuppannānaṃ pāpakānaṃ akusalānaṃ dhammānaṃ anuppādāya..._
****

2. To abandon arisen unvirtuous, spiritually unwholesome factors...
+
****
_Uppannānaṃ pāpakānaṃ akusalānaṃ dhammānaṃ pahānāya..._
****

3. To arouse unarisen spiritually wholesome factors...
+
****
_Anuppannānaṃ kusalānaṃ dhammānaṃ uppādāya..._
****

4. To maintain arisen spiritually wholesome factors, to support their nondecay, 
increase, expansion, and perfection through spiritual cultivation...
+
****
_Uppannānaṃ kusalānaṃ dhammānaṃ ṭhitiyā asammosāya bhiyyobhāvāya 
vepullāya bhāvanāya pāripūriyā..._
****

____
... he stirs up eagerness, endeavours, applies energy, exerts his mind, and 
strives.

_chandaṃ janeti vāyamati viriyaṃ ārabhati cittaṃ paggaṇhāti 
padahati._
____

[quote, S.5.268]
____
... These are called the efforts of inward striving.

_ime vuccanti padhānasaṅkhārā._
____

Comment:

The four 'efforts of inward striving' (_padhānasaṅkhārā_) are equivalent 
to the 'four modes of right inward striving,' mentioned above (_cattāro 
sammappadhānā_: S.5.244). The 'efforts of inward striving' therefore simply 
means 'inward striving.' The word 'efforts' (_saṅkhārā_) is redundant.

.Illustration
====
na saṅkhāra

effortless
====

[quote, D.3.278-9]
____
This inward collectedness is peaceful, sublime, tranquil, and concentrated, and 
is effortlessly controlled, restrained, and checked

_ayaṃ samādhi santo paṇīto paṭippassaddhaladdho ekodibhāvādhigato na 
saṅkhāraniggayhavāritāvato ti._
____

.Illustration
====
saṅkhāra

effort
====

Bhikkhus, these four persons are found in the world. Which four?

1. A person liberated with effort in this very lifetime.
+
****
_diṭṭheva dhamme sasaṅkhāraparinibbāyī hoti_
****

2. A person liberated with effort after the body breaks up.
+
****
_kāyassa bhedā sasaṅkhāraparinibbāyī hoti_
****

3. A person liberated effortlessly in this very lifetime.
+
****
_diṭṭheva dhamme asaṅkhāraparinibbāyī hoti_
****

4. A person liberated effortlessly after the body breaks up.
+
****
_kāyassa bhedā asaṅkhāraparinibbāyī hoti._
****

1. In what way is a person liberated with effort in this very lifetime?
+
****
_Kathañca bhikkhave puggalo diṭṭheva dhamme sasaṅkhāraparinibbāyī 
hoti?_
****

____
In this regard a bhikkhu is one who:

_Idha bhikkhave bhikkhu_
____

____
abides contemplating the unloveliness of the body

_asubhānupassī kāye viharati._
____

____
perceives the loathsome nature of digestion.

__āhāre paṭikkūlasaññī._
____

____
perceives disgust for the whole world [of phenomena].

_sabbaloke anabhiratasaññī._
____

____
contemplates the unlastingness of all originated phenomena.

_sabbasaṅkhāresu aniccānupassī._
____

____
and for whom the perception of [the ever-present possibility of] death is 
well-established within himself.

_maraṇasaññā kho panassa ajjhattaṃ sūpaṭṭhitā hoti._
____

3. In what way is a person liberated effortlessly in this very lifetime?
+
****
_Kathañca bhikkhave puggalo diṭṭheva dhamme asaṅkhāraparinibbāyī 
hoti?_
****

[quote, A.2.155-6]
____
In this regard a bhikkhu is one who enters and abides in first... fourth jhāna:

_Idha bhikkhave bhikkhu vivicceva kāmehi vivicca akusalehi dhammehi 
savitakkaṃ savicāraṃ vivekajaṃ pītisukhaṃ paṭhamaṃ jhānaṃ... 
catutthaṃ jhānaṃ upasampajja viharati._
____

.Illustration
====
saṅkhāra

effort
====

[quote, M.2.223]
____
When I confront the source of this suffering with effort, by confronting it 
with effort [the suffering] fades away.

_imassa kho me dukkhanidānassa saṅkhāraṃ padahato saṅkhārappadhānā 
virāgo hoti._
____

.Illustration
====
saṅkhāra

effort
====

____
If any ascetics or Brahmanists describe the entering upon this base [neither 
having nor lacking perception] to come about through a measure of effort 
regarding what is to be seen, heard, sensed, or cognised, that is declared to 
be a disaster for entering upon this base.

_Ye hi keci bhikkhave samaṇā vā brāhmaṇā vā 
diṭṭhasutamutaviññātabbassa saṅkhāramattena etassa āyatanassa 
upasampadaṃ paññāpenti vyasanaṃ hetaṃ bhikkhave akkhāyati etassa 
āyatanassa upasampadāya._
____

[quote, M.2.231-2]
____
For this base is not to be attained as an attainment with effort, but with a 
residue of effort.

_Na hetaṃ bhikkhave āyatanaṃ sasaṅkhārasamāpatti pattabbamakkhāyati. 
Saṅkhārāvasesa samāpattipattabbametaṃ bhikkhave āyatanaṃ akkhāyati._
____

=== Saṅkhāra and aspiration

==== Introduction

The Buddha said he could extend his lifespan by wishing for it.

[quote, S.5.259]
____
If he wishes, the Perfect One could live for a century or for slightly more 
than a century.

_Ākaṅkhamāno ānanda tathāgato kappaṃ vā tiṭṭheyya kappāvasesaṃ 
vā ti._
____

This supports us rendering _saṅkhāra_ in this section as 'aspiration.'

.Illustration
====
saṅkhāra

aspiration
====

____
'Let me then suppress this illness with energy and live on, having firmly 
established the aspiration for further life.'

_Yannūnāhaṃ imaṃ ābādhaṃ viriyena paṭippaṇāmetvā 
jīvitasaṅkhāraṃ adhiṭṭhāya vihareyyanti_
____

[quote, D.2.99; S.5.152-3]
____
Then the Blessed One suppressed his illness with energy and lived on having 
firmly established the aspiration for further life.

_Atha kho bhagavā taṃ ābādhaṃ viriyena paṭippanāmetvā 
jīvitasaṅkhāraṃ adhiṭṭhāya vihāsi._
____

.Illustration
====
saṅkhāra

aspiration
====

____
Then the Blessed One at the Cāpāla Shrine, mindful and fully conscious, 
relinquished the aspiration for further life...

_Atha kho bhagavā cāpāle cetiye sato samapajāno āyusaṅkhāraṃ ossaji_
____

Then the Blessed One spoke this inspired utterance:

[quote, Ud.64; S.5.263]
____
Comparing the incomparable with individual existence, the Sage relinquished the 
aspiration for [renewed] states of individual existence.

_Tulamatulañca sambhavaṃ +
Bhavasaṅkhāramavassajji muni._
____

.Illustration
====
saṅkhāra

aspiration
====

____
A bhikkhu thinks, 'Oh, that at the demise of the body at death, I might be 
reborn in the company of wealthy _khattiyas_.' He fixes his mind on that idea, 
concentrates on it, and develops it

_so taṃ cittaṃ dahati taṃ cittaṃ adhiṭṭhāti taṃ cittaṃ 
bhāveti_
____

[quote, M.3.99]
____
These aspirations and musings of his, when developed and cultivated, lead to 
his rebirth there

_tassa te saṅkhārā ca viharā ca evaṃ bhāvitā evaṃbahulīkatā 
tatrūpapattiyā saṃvattanti._
____

.Illustration
====
abhisaṅkhāra

aspiration
====

When Soṇa Koṭikaṇṇa asked to be allowed to go forth into the ascetic 
life, Venerable Mahākaccāna dissuaded him.

[quote, Ud.57]
____
Then whatever aspiration he had to go forth [into the ascetic life] subsided

_yo ahosi pabbajjābhisaṅkhāro so paṭippassambhi._
____

.Illustration
====
abhisaṅkhāra

aspiration
====

When Sīha, the general, told Nātaputta the Nigaṇṭha that he wished to 
visit the Buddha, Nātaputta dissuaded him.

[quote, A.4.180]
____
Then whatever aspiration he had to go and visit the Blessed One subsided.

_Atha kho sīhassa senāpatissa yo ahosi gamiyābhisaṅkhāro bhagavantaṃ 
dassanāya so paṭippassambhi._
____

.Illustration
====
abhisaṅkhāro

aspiration
====

Three necessary conditions (_paccayā_) for the persistence of the liberation 
&#8203;[from perceptually obscuring states] by focusing upon the unabiding 
&#8203;[phenomenon] (_animittāya cetovimuttiyā ṭhitiyā_):

____
not focusing upon any abiding phenomenon

_sabbanimittānañca amanasikāro_
____

____
focusing upon the unabiding phenomenon,

_animittāya ca dhātuyā manasikāro_
____

[quote, M.1.297]
____
a prior aspiration [for its persistence]

_pubbeva abhisaṅkhāro._
____

=== Saṅkhāra and mindfulness with breathing

==== Saṅkhāra in mindfulness with breathing: untranquillising factors

In this section, we will explore the meaning of _saṅkhāra_ as it occurs in 
mindfulness with breathing, and will show it can be rendered as 
'untranquillising factors' of body and mind.

==== Mindfulness with breathing and saṅkhāra

Mindfulness with breathing (_ānāpānasati_) involves training oneself as 
follows:

'I will breathe in... I will breathe out:

____
experiencing the whole body

_sabbakāyapaṭisaṃvedī assasissāmī ti... passasissāmī ti sikkhati_
____

____
tranquillising bodily _saṅkhāra_

_passambhayaṃ kāyasaṅkhāraṃ assasissāmī ti... passasissāmī ti 
sikkhati_
____

____
experiencing mental _saṅkhāra_

_cittasaṅkhārapaṭisaṃvedī assasissāmī ti... passasissāmī ti 
sikkhati_
____

[quote, M.1.425]
____
tranquillising mental _saṅkhāra_

_passambhayaṃ cittasaṅkhāraṃ assasissāmī ti... passasissāmī ti 
sikkhati._
____

To establish the meaning of _saṅkhāra_, let us see what factors are 
tranquillised in mindfulness with breathing.

==== Tranquillisation in mindfulness with breathing

The factors tranquillised in mindfulness with breathing are:

1. Trembling and unsteadiness:

[quote, S.5.316]
____
It is when inward collectedness by mindfulness with breathing has been 
developed and cultivated that no trembling or unsteadiness arises either in 
body or mind.

__ānāpānasatisamādhissa bhikkhave bhāvitattā bahulīkatattā neva 
kāyassa iñjitattaṃ vā hoti phanditattaṃ vā na cittassa iñjitattaṃ 
vā hoti phanditattaṃ vā._
____

2. Discursive thinking:

[quote, Ud.37]
____
Mindfulness with breathing should be developed to cut off discursive thinking

__ānāpānasati bhāvetabbā vitakkupacchedāya._
____

3. Four factors that are quelled with jhāna:

____
quelling of speech in first jhāna

_vācā paṭippassaddhā hoti_
____

____
quelling of thinking and pondering in second jhāna

_vitakkavicārā paṭippassaddhā honti_
____

____
quelling of rapture in third jhāna

_pīti paṭippassaddhā hoti_
____

[quote, S.4.218]
____
quelling of breathing in fourth jhāna

_assāsapassāsā paṭippassaddhā._
____

These quotes therefore indicate seven possible meanings of the _saṅkhāra_ 
that is tranquillised in mindfulness with breathing:

1. trembling of body and mind

2. unsteadiness of body and mind

3. discursive thinking

4. speech

5. thinking and pondering

6. rapture

7. breathing

==== Further study of the jhānas

In the search for the meaning of _saṅkhāra,_ we will see that tranquillity 
is not perfected until fourth jhāna. That is, whereas the first three jhānas 
are reckoned as unstable, fourth jhāna is stable. This stabilisation of body 
and mind seems the very essence of tranquillisation, and must surely be 
included in our search. First we will consider the duality of tranquillity.

==== The duality of tranquillity

We have seen above that in mindfulness with breathing, tranquillity is applied 
to _saṅkhāra_ both bodily and mentally (i.e. _passambhayaṃ 
kāyasaṅkhāraṃ assasissāmī ti... passambhayaṃ cittasaṅkhāraṃ 
assasissāmī ti_). This duality of tranquillity is firmly acknowledged 
elsewhere in the scriptures:

[quote, S.5.103-108]
____
There are tranquillity of body, tranquillity of mind.

_Atthi bhikkhave kāyapassaddhi cittappassaddhi._
____

Both aspects of tranquillity, of body and mind, result from rapture:

• For one whose mind is rapturous, the body becomes tranquil and the mind 
becomes tranquil, and this is the arousing of the enlightenment factor of 
tranquillity +
_Pītimanassa kāyopi passambhati cittampi passambhati. Yasmiṃ samaye 
bhikkhave bhikkhuno pītimanassa kāyopi passambhati cittampi passambhati 
passaddhisambojjhaṅgo tasmiṃ samaye bhikkhuno āraddho hoti_ (S.5.68).

This implies that tranquillity would be found the first two jhānas, because:

1. first jhāna involves rapture and physical pleasure born of seclusion
+
****
_vivekajaṃ pītisukhaṃ paṭhamaṃ jhānaṃ_
****

2. second jhāna involves rapture and physical pleasure born of inward 
collectedness
+
****
_samādhijaṃ pītisukhaṃ dutiyaṃ jhānaṃ_ (M.1.454-5).
****

Nonetheless, perfect meditative tranquillity is not to be found in first and 
second jhāna, because it is definitively linked only to fourth jhāna, as 
follows.

==== Bodily tranquillity and fourth jhāna

The scriptures associate tranquillity of bodily _saṅkhāra_ with fourth 
jhāna, as follows:

____
How is a bhikkhu one whose bodily _saṅkhāra_ has been tranquillised?

_Kathañca bhikkhave bhikkhu passaddhakāyasaṅkhāro hoti?_
____

[quote, D.3.270]
____
... In this regard, with the abandonment of physical pleasure and pain, and 
following the vanishing of psychological pleasure and pain, a bhikkhu enters 
and abides in fourth jhāna, which is free of pleasure and pain, and [is imbued 
with] purified detached awareness and mindfulness.

_Idhāvuso bhikkhu sukhassa ca pahānā dukkhassa ca pahānā pubbeva 
somanassadomanassānaṃ atthaṅgamā adukkhamasukhaṃ 
upekkhāsatipārisuddhiṃ catutthaṃ jhānaṃ upasampajja viharati._
____

==== The Buddha's teaching on 'the unstable'

This definitive association of tranquillity with fourth jhāna corresponds to 
the teaching on 'the unstable.' The Buddha said that whereas instability is 
associated with the first three jhānas, it is abolished in fourth jhāna, as 
follows:

____
In this regard a bhikkhu... enters and abides in first jhāna... That, I 
declare, is within the unstable. What there is within the unstable? The 
thinking and pondering that are unended.

_Idhūdāyi bhikkhu... paṭhamaṃ jhānaṃ upasampajja viharati. Idaṃ kho 
ahaṃ udāyi iñjitasmiṃ vadāmi. Kiñca tattha iñjitasmiṃ: yadeva tattha 
vitakkavicārā aniruddhā honti_
____

____
... A bhikkhu enters and abides in second jhāna. That, I declare, is within 
the unstable. What there is within the unstable? The rapture and physical 
pleasure that are unended.

_dutiyaṃ jhānaṃ upasampajja viharati. Idampi kho ahaṃ udāyi 
iñjitasmiṃ vadāmi. Kiñca tattha iñjitasmiṃ: yadeva tattha pītisukhaṃ 
aniruddhaṃ hoti._
____

____
... He enters and abides in third jhāna... That, I declare, is within the 
unstable. What there is within the unstable? The serenity with physical 
pleasure that is unended.

_tatiyaṃ jhānaṃ upasampajja viharati. Idampi kho ahaṃ udāyi 
iñjitasmiṃ vadāmi. Kiñca tattha iñjitasmiṃ: yadeva tattha 
upekkhāsukhaṃ aniruddhaṃ hoti._
____

[quote, M.1.454-5]
____
... With the abandonment of physical pleasure and pain, and following the 
vanishing of psychological pleasure and pain, a bhikkhu enters and abides in 
fourth jhāna, which is free of pleasure and pain, and [is imbued with] 
purified detached awareness and mindfulness. Now that, I declare, is within the 
not-unstable.

_Idhūdāyi bhikkhu sukhassa ca pahānā dukkhassa ca pahānā pubbeva 
somanassadomanassānaṃ atthaṅgamā adukkhaṃ asukhaṃ 
upekkhāsatipārisuddhiṃ catutthaṃ jhānaṃ upasampajja viharati. Idaṃ 
kho ahaṃ udāyi aniñjitasmiṃ vadāmi._
____

Thus any tranquillity occurring below fourth jhāna is part of 'instability.' 
Only in fourth jhāna does tranquillity reach its consummation. This gives us 
an eighth possible meaning for the _saṅkhāra_ that is tranquillised in 
mindfulness with breathing: 'instability.'

==== Conclusion: the advantages of tautology

We have said that in mindfulness with breathing, tranquillity is applied to 
_saṅkhāra_ both bodily and mentally, and we have shown that there are eight 
possible explanations for _saṅkhāra_. All these meanings can be captured 
with a noun that produces a tautology. In other words, what is tranquillised in 
mindfulness with breathing is 'untranquillising factors.' Although 
_saṅkhāraṃ_ is a singular, we treat it as a plural, because that is in 
accordance with this quote:

[quote, M.1.301]
____
In-breathing and out-breathing are bodily activity. Thinking and pondering are 
speech activity. Perception and sense impression are mental activity.

_Assāsapassāsā kho āvuso visākha kāyasaṅkhāro vitakkavicārā 
vacīsaṅkhāro saññā ca vedanā ca cittasaṅkhāro ti._
____

Thus the _ānāpānasati_ formulae can be translated accordingly:

- I will breathe in... I will breathe out:

____
... experiencing the whole body

_sabbakāyapaṭisaṃvedī assasissāmī ti... passasissāmī ti sikkhati_
____

____
... tranquillising bodily untranquillising factors

_passambhayaṃ kāyasaṅkhāraṃ assasissāmī ti... passasissāmī ti 
sikkhati_
____

____
... experiencing mental untranquillising factors

_cittasaṅkhārapaṭisaṃvedī assasissāmī ti... passasissāmī ti 
sikkhati_
____

[quote, M.1.425]
____
... tranquillising mental untranquillising factors

_passambhayaṃ cittasaṅkhāraṃ assasissāmī ti... passasissāmī ti 
sikkhati._
____

.Illustration
====
saṅkhāro

untranquillising factors
====

____
And how is a bhikkhu one whose bodily untranquillising factors have been 
tranquillised?

_Kathañca bhikkhave bhikkhu passaddhakāyasaṅkhāro hoti?_
____

____
In this regard a bhikkhu, with the abandonment of physical pleasure and pain, 
and following the vanishing of psychological pleasure and pain, he enters and 
abides in fourth jhāna, which is free of pleasure and pain, and [is imbued 
with] purified detached awareness and mindfulness.

_Idha bhikkhave bhikkhu sukhassa ca pahānā dukkhassa ca pahānā pubbeva 
somanassadomanassānaṃ atthaṅgamā adukkhaṃ asukhaṃ 
upekkhāsatipārisuddhiṃ catutthaṃ jhānaṃ upasampajja viharati._
____

[quote, A.2.41]
____
That is how a bhikkhu is one whose bodily untranquillising factors have been 
tranquillised.

_Evaṃ kho bhikkhave bhikkhu passaddhakāyasaṅkhāro hoti._
____

=== Saṅkhāra: miscellaneous

.Illustration
====
āyusaṅkhārā

factors essential to life
====

[quote, M.1.296]
____
Friend, the factors essential to life are not things that must be experienced. 
If they were, then a bhikkhu who attains the ending of perception and sense 
impression would not be seen to emerge from it.

_Na kho āvuso teva āyusaṅkhārā teva vedanīyā dhammā. Teva kho āvuso 
āyusaṅkhārā abhaviṃsu teva vedanīyā dhammā nayidaṃ 
saññāvedayitanirodhaṃ samāpannassa bhikkhuno vuṭṭhānaṃ 
paññāyetha._
____

.Illustration
====
āyusaṅkhārā

factors essential to life
====

____
As swift as are the sun and moon, and as swift as are the devas that run before 
the sun and moon, the factors essential to life perish even more swiftly than 
that.

_yathā ca candimasuriyānaṃ javo yathā ca yā devatā candimasuriyānaṃ 
purato dhāvanti tāsaṃ devatānaṃ javo tato sīghataraṃ āyusaṅkhārā 
khīyanti._
____

[quote, S.2.266]
____
Therefore, bhikkhus, you should train yourselves thus: 'We will abide 
diligently applied [to the practice]'

_Tasmātiha bhikkhave evaṃ sikkhitabbaṃ appamattā viharissāmā ti._
____

.Illustration
====
saṅkhāra

dynamic
====

____
If there arise in a bhikkhu unvirtuous, spiritually unwholesome thoughts 
connected with attachment, hatred, and undiscernment of reality, then he should 
pay attention to the dynamic quality of those thoughts

_uppajjanteva pāpakā akusalā vitakkā chandūpasaṃhitāpi 
dosūpasaṃhitāpi mohūpasaṃhitāpi tena bhikkhave bhikkhunā tesaṃ 
vitakkānaṃ vitakkasaṅkhārasaṇṭhānaṃ manasikātabbaṃ_
____

[quote, M.1.120]
____
... It is just as if a man walking fast might ask himself why he is walking 
fast. Why not walk slowly? Then walking slowly, why not stand? Then standing, 
why not sit? Then sitting, why not lie down? In this way he would substitute 
for each more effortful posture one that was less effortful.

_Evaṃ hi so bhikkhave puriso oḷārikaṃ oḷārikaṃ iriyāpathaṃ 
abhinivajjetvā sukhumaṃ sukhumaṃ iriyāpathaṃ kappeyya._
____

Notes:

- _Saṇṭhāna_: configuration, position; composition, nature, shape, form 
(PED).

.Illustration
====
saṅkhārā

activities
====

And what is the wonder of mind reading. When a bhikkhu has attained a state of 
inward collectedness which is void of thinking and reflecting, by encompassing 
a person's mind with his mind, he knows that:

[quote, A.1.171; D.3.104]
____
In the way that this person's mental activities are directed, so his mind will 
immediately think this thought.

_yathā imassa bhoto manosaṅkhārā paṇihitā tathā imassa cittassa 
anantarā imaṃ nāma vitakkaṃ vitakkessatī ti._
____

.Illustration
====
saṅkhārā

activity
====

____
-- How many activities are there?

_Kati panayye saṅkhārā ti_
____

____
-- There are these three activities: activities of body, speech, and mind.

_Tayome āvuso visākha saṅkhārā: kāyasaṅkhāro vacīsaṅkhāro 
cittasaṅkhāro ti._
____

____
-- What are these activities of body, speech, and mind?

_Katamo panayye kāyasaṅkhāro katamo vacīsaṅkhāro katamo 
cittasaṅkhāro ti_
____

____
-- In-breathing and out-breathing are bodily activity. Thinking and pondering 
are speech activity. Perception and sense impression are mental activity.

_Assāsapassāsā kho āvuso visākha kāyasaṅkhāro vitakkavicārā 
vacīsaṅkhāro saññā ca vedanā ca cittasaṅkhāro ti_
____

-- For what reason?

[quote, M.1.301]
____
-- Because in-breathing and out-breathing are bodily, bound up with the body, 
therefore they are bodily activity. And because first one thinks and reflects 
before breaking into speech, therefore thinking and pondering are speech 
activity. And because perception and sense impression are cognitive, bound up 
with cognition, therefore they are mental activity

_Assāsapassāsā kho āvuso visākha kāyikā ete dhammā kāyapaṭibaddhā 
tasmā assāsapassāsā kāyasaṅkhāro. Pubbe kho āvuso visākha vitakketvā 
vicāretvā pacchā vācaṃ bhindati tasmā vitakkavicārā vacīsaṅkhāro. 
Saññā ca vedanā ca cetasikā ete dhammā cittapaṭibaddhā tasmā saññā 
ca vedanā ca cittasaṅkhāro ti._
____

.Illustration
====
saṅkhārā

activity
====

[quote, M.1.296]
____
In both one who is dead and passed away, and in a bhikkhu who has attained the 
ending of perception and sense impression, their activities of body, speech, 
and mind have ceased and are quelled.

_Yvāyaṃ āvuso mato kālakato... Yo cāyaṃ bhikkhu 
saññāvedayitanirodhaṃ samāpanno tassapi kāyasaṅkhārā niruddhā 
paṭippassaddhā vacīsaṅkhārā niruddhā paṭippassaddhā 
cittasaṅkhārā niruddhā paṭippassaddhā._
____

.Illustration
====
saṅkhārā

deeds
====

[quote, D.2.214-5]
____
In this regard, some person's morally unrefined deeds of body, speech, and mind 
are unquelled.

_idhekaccassa oḷārikā kāyasaṅkhārā appaṭippassaddhā honti 
oḷārikā vacīsaṅkhārā appaṭippassaddhā honti oḷārikā 
cittasaṅkhārā appaṭippassaddhā honti._
____

.Illustration
====
iddhābhisaṅkhāraṃ

act of psychic power
====

Then I performed an act of psychic power (_tathārūpaṃ 
iddhābhisaṅkhāraṃ abhisaṅkhāsiṃ_) such that Baka the Brahmā and the 
members of his assembly could hear my voice but could not see me (M.1.330).

.Illustration
====
abhisaṅkhārassa

impulsion
====

The wheelwright set rolling (_pavattesi_) the wheel he had finished in six 
days. The wheel kept rolling as far as the impulsion took it (_yāvatikā 
abhisaṅkhārassa gati tāvatikaṃ gantvā_); then it circled round and round 
and fell to the ground (A.1.112).

