== Saṅgahavatthūni

=== Renderings

- _saṅgahavatthūni_: bases for winning over a following

=== Introduction

==== Saṅgaṇhāti: hold together

_Saṅgaṇhāti_ can mean 'hold together':

[quote, Vin.3.8]
____
Various flowers placed on a plank without being held together with a thread.

_nānāpupphāni phalake nikkhittāni suttena asaṅgahītāni._
____

==== Saṅgaṇhāti: assist

_Saṅgaṇhāti_ can mean 'assist':

[quote, Vin.1.50]
____
The pupil should be assisted and helped by the preceptor in regard to 
recitation, interrogation, exhortation, instruction.

_upajjhāyena bhikkhave saddhivihāriko saṅgahetabbo anuggahetabbo uddesena 
paripucchāya ovādena anusāsaniyā._
____

==== Saṅgaṇhāti: win over

_Saṅgaṇhāti_ can mean 'win over':

[quote, Vin.3.90]
____
Again, a certain unvirtuous bhikkhu by [giving away] the valuable goods and 
requisites belonging to the community of bhikkhus... wins over and cajoles 
householders. This is the fourth great thief found existing in the world.

_Puna ca paraṃ bhikkhave idhe'kacco pāpabhikkhu yāni tāni saṅghassa 
garubhaṇḍāni garuparikkhārāni... tehi gihī saṅgaṇhāti upalāpeti. 
Ayaṃ bhikkhave catuttho mahācoro santo saṃvijjamāno lokasmiṃ._
____

=== Illustrations

.Illustration
====
saṅgahavatthūni

bases for winning over a following
====

[quote, D.3.232]
____
Four bases for winning over a following: generosity, agreeable speech, 
beneficial conduct, and impartiality.

_cattāri saṅgahavatthūni dānaṃ peyyavajjaṃ atthacariyaṃ 
samānattatā._
____

.Illustration
====
saṅgahavatthūni

bases for winning over a following
====

____
There are four bases for winning over a following. Which four? Generosity, 
agreeable speech, beneficial conduct, and impartiality. These are the four 
bases for winning over a following.

_Cattārimāni bhikkhave saṅgahavatthūni. Katamāni cattāri? Dānaṃ 
peyyavajjaṃ atthacariyā samānattatā. Imāni kho bhikkhave cattāri 
saṅgahavatthūnīti._
____

____
Generosity, agreeable speech, beneficial conduct, and impartiality amidst 
conditions wherever possible as is suitable. These ways of winning over a 
following are [as important as] the linchpin of a rolling chariot.

_Dānañca peyyavajjañca atthacariyā ca yā idha +
Samānattatā ca dhammesu tattha tattha yathārahaṃ +
Ete kho saṅgahā loke rathassāṇīva yāyato._
____

____
If there were no such ways of winning over a following, then neither mother nor 
father would receive honour and veneration from their children.

_Ete ca saṅgahā nāssu na mātā puttakāraṇā +
Labhetha mānaṃ pūjaṃ vā pitā vā puttakāraṇā._
____

[quote, A.2.32]
____
But because there are ways of winning over a following, wise people contemplate 
them, thus they attain to greatness and are praised.

_Yasmā ca saṅgahā ete samavekkhanti paṇḍitā +
Tasmā mahattaṃ papponti pāsaṃsā ca bhavanti te ti._
____

.Illustration
====
saṅgahavatthūni

bases for winning over a following
====

____
-- Your following is large, Hatthaka.

_Mahatī kho tyāyaṃ hatthaka parisā_
____

____
... How did you win over this large following?

_kathaṃ pana tvaṃ hatthaka imaṃ mahatiṃ parisaṃ saṅgaṇhāhī ti?_
____

____
-- I did so by the four bases for winning over a following taught by the 
Blessed One.

_Yānimāni bhante bhagavatā desitāni cattāri saṅgahavatthūni tenāhaṃ 
imaṃ parisaṃ saṅgaṇhāmi._
____

____
... When I know 'This one is to be won over by a gift, I win him over with a 
gift.'

_Ahaṃ bhante yaṃ jānāmi ayaṃ dānena saṅgahetabbo ti taṃ dānena 
saṅgaṇhāmi._
____

____
... When I know 'This one is to be won over by agreeable speech, I win him over 
with agreeable speech.'

_Yaṃ jānāmi ayaṃ peyyavajjena saṅgahetabbo ti taṃ peyyavajjena 
saṅgaṇhāmi_
____

____
... When I know 'This one is to be won over by beneficial conduct, I win him 
over with beneficial conduct.'

_yaṃ jānāmi ayaṃ atthacariyāya saṅgahetabbo ti taṃ atthacariyāya 
saṅgaṇhāmi_
____

[quote, A.4.219]
____
... When I know 'This one is to be won over by impartiality, I win him over 
with impartiality.'

_yaṃ jānāmi ayaṃ samānattatāya saṅgahetabbo ti taṃ samānattatāya 
saṅgaṇhāmi._
____

