== Saṃvara; Saṃvuta

=== Renderings

- _saṃvara_: restraint [of the sense faculties] [from attraction and 
repulsion, through mindfulness] (i.e. _indriyasaṃvara_)

- _saṃvara_: restraint

- _saṃvara_: restraint [in conduct]

- _pātimokkhasaṃvara_: the constraints of the rules of discipline

- _saṃvuta_: sense faculties restrained [from attraction and repulsion, 
through mindfulness]

- _saṃvuta_: restrained

- _saṃvuta_: restrained [in conduct]

- _saṃvuta_: [bodily] restrained

=== Introduction

==== Indriyasaṃvara: animals sitting beside a post

_Indriyasaṃvara_ means 'restraint of the sense faculties [from attraction and 
repulsion, through mindfulness].' The parenthesis says the restraint operates 
via mindfulness. Without the parenthesis, 'restraint' tends to suggest the 
application of force: 'restraint of the sense faculties'. But the 
_Chappāṇaka Sutta_ shows that with _indriyasaṃvara_ there is no force at 
all. It is like training of wild animals by tying them to a post (S.4.200). 
Although the animals initially struggle to escape, eventually, worn out and 
fatigued, they sit or curl up beside the post. At this point, the animals are 
not 'restrained [by force].'

==== Indriyasaṃvara: body and mind are steady

The _Kuṇḍaliya Sutta_ (S.5.74) describes how restraint of the sense 
faculties [from attraction and repulsion, through mindfulness] should be 
developed (_indriyasaṃvaro kathaṃ bahulīkato_). It says that in this 
practice, 'his body is steady and his mind is steady, inwardly settled and 
&#8203;[temporarily] liberated [from perceptually obscuring states].' These adjectives 
show that _saṃvaro_ is not a matter of force:

____
And how, Kuṇḍaliya, is restraint of the sense faculties [from attraction 
and repulsion, through mindfulness] developed and cultivated so that it brings 
to perfection the three kinds of good conduct? In this regard, Kuṇḍaliya, 
seeing a pleasing visible object via the visual sense, a bhikkhu does not long 
for it or get excited by it or become attached to it. His body is steady and 
his mind is steady, inwardly settled and [temporarily] liberated [from 
perceptually obscuring states].

_Kathaṃ bhāvito ca kuṇḍaliya indriyasaṃvaro kathaṃ bahulīkato 
tīṇi sucaritāni paripūreti? Cakkhunā rūpaṃ disvā manāpaṃ 
nābhijjhati nābhihaṃsati na rāgaṃ janeti. Tassa ṭhito ca kāyo hoti 
ṭhitaṃ cittaṃ ajjhattaṃ susaṇṭhitaṃ suvimuttaṃ_
____

[quote, S.5.74]
____
In seeing a displeasing visible object via the visual sense, he is not 
disconcerted by it, not daunted, not dejected, free of ill will. His body is 
steady and his mind is steady, inwardly settled and [temporarily] liberated 
&#8203;[from perceptually obscuring states].

_cakkhunā kho paneva rūpaṃ disvā amanāpaṃ na maṅku hoti 
apatitthinacitto adīnamanaso avyāpannacetaso. Tassa ṭhito ca kāyo hoti 
ṭhitaṃ cittaṃ ajjhattaṃ susaṇṭhitaṃ suvimuttaṃ._
____

==== Indriyasaṃvara: restraint [through mindfulness]

_Indriyasaṃvara_ is developed by practising mindfulness, as these quotes show:

1. When a bhikkhu has developed and cultivated mindfulness of the body, the eye 
does not incline towards pleasing visible objects nor are displeasing visible 
objects loathsome... In this way there is restraint [of the sense faculties] 
&#8203;[from attraction and repulsion, through mindfulness].
+
****
_kāyagatā sati bhāvitā bahulīkatā cakkhu nāviñjati manāpikesu rūpesu 
amanāpikassa rūpāni nappaṭikkūlā honti... evaṃ kho bhikkhave saṃvaro 
hoti_ (S.4.200).
****

2. What is the condition that nourishes unrestraint of the sense faculties?
+
****
_Ko cāhāro indriyāsaṃvarassa?_
****
+
[quote, A.5.113]
____
... Lack of mindfulness and full consciousness, one should reply.

_Asatāsampajaññan tissa vacanīyaṃ._
____

3. What is the condition that nourishes restraint of the sense faculties [from 
attraction and repulsion, through mindfulness]?
+
****
_ko cāhāro indriyasaṃvarassa_
****
+
[quote, A.5.115]
____
... Mindfulness and full consciousness, one should reply.

_satisampajaññantissa vacanīyaṃ._
____

==== Indriyasaṃvara means no delight in sense objects

When the senses are mastered the bhikkhu takes no delight in sense objects:

[quote, S.4.78-80]
____
In what way is there restraint [of the sense faculties] [from attraction 
and repulsion, through mindfulness]?

_Kathañca bhikkhave saṃvaro hoti?_

...There are visible objects known via the visual sense that are likeable, 
loveable, pleasing, agreeable, connected with sensuous pleasure, and charming.

_Santi bhikkhave cakkhuviññeyyā rūpā iṭṭhā kantā manāpā piyarūpā 
kāmupasaṃhitā rajanīyā._

... If a bhikkhu does not take delight in them, welcome them, persist in 
cleaving to them, he should understand this thus: 'I am not falling away from 
spiritually wholesome factors. For this has been called not falling away by the 
Blessed One.

_Tañce bhikkhu nābhinandati nābhivadati nājjhosāya tiṭṭhati. 
Veditabbametaṃ bhikkhave bhikkhunā na parihāyāmi kusalehi dhammehi 
aparihānaṃ hetaṃ vuttaṃ bhagavatā ti._

... In this way there is restraint [of the sense faculties] [from attraction 
and repulsion, through mindfulness]

_Evaṃ kho bhikkhave saṃvaro hotī ti._
____

==== Unrestrained sense faculties equals grasping

Unrestrained sense faculties equal grasping, and this leads to greed and 
dejection:

[quote, S.4.178]
____
In seeing a visible object via the visual sense, do not grasp its aspects and 
features. Since by abiding with the faculty of sight unrestrained [from 
attraction and repulsion, through mindfulness], greed, dejection, and 
unvirtuous, spiritually unwholesome factors would pursue you.

_Cakkhunā rūpaṃ disvā mā nimittaggāhino ahuvattha mānuvyañjanaggāhino 
yatvādhikaraṇamenaṃ cakkhundriyaṃ asaṃvutaṃ viharantaṃ 
abhijjhādomanassā pāpakā akusalā dhammā anvāssaveyyuṃ._
____

==== Saṃvara as an abbreviation for indriyasaṃvara

When _saṃvara_ is used as an abbreviation for _indriyasaṃvara_ we 
parenthesise it as such: 'restraint [of the sense faculties] [from attraction 
and repulsion, through mindfulness].'

==== Saṃvuto: [bodily] restrained

Sometimes _saṃvuto_ means '[bodily] restrained':

[quote, Sn.v.413]
____
Going on uninterrupted house-to-house almsround, with sense portals guarded [by 
mindfulness], and [bodily] well-restrained;

_Sapadānaṃ caramāno guttadvāro susaṃvuto._
____

The parenthesis derives from this rule:

[quote, Vin.4.186]
____
In the village you should walk [bodily] well-restrained. If, disrespectful [of 
the rule], one walks in the village playing with one's hands or feet it is a 
dukkaṭa offence.

_Susaṃvutena antaraghare gantabbaṃ yo anādariyaṃ paṭicca hatthaṃ vā 
pādaṃ vā kīḷapento antaraghare gacchati āpatti dukkaṭassa._
____

==== The constraints of the rules of discipline: pātimokkhasaṃvara

We call _pātimokkhasaṃvara_ 'the constraints of the rules of discipline.' 
This can be illustrated with the following quotes:

1. the bhikkhu who practises within the constraints of the rules of discipline
+
****
_bhikkhu pātimokkhasaṃvarāya paṭipanno hotī ti_ (D.2.279).
****

2. Abide restrained [in conduct] within the constraints of the rules of 
discipline
+
****
_pātimokkhasaṃvarasaṃvutā viharāhi_ (M.3.2).
****

==== Sīlasaṃvuta: one who abides restrained in [conduct within the 
constraints of the] code of morality

Our parenthesis of _sīlasaṃvuta_ stems from our translation of 
_pātimokkhasaṃvarasaṃvuta_, i.e., we treat it as if it were 
_sīlasaṃvarasaṃvuta viharato_:

[quote, D.1.69]
____
When a bhikkhu is himself perfect in virtue he sees no danger anywhere due to 
his abiding restrained in [conduct within the constraints of] the code of 
morality.

_Sa kho so mahārāja bhikkhu evaṃ sīlasampanno na kutoci bhayaṃ 
samanupassati yadidaṃ sīlasaṃvarato._
____

[quote, A.3.329]
____
Those who delight in diligence, who are mindful and who abide restrained in 
&#8203;[conduct within the constraints of] the code of morality.

_Appamāde pamoditā nipakā sīlasaṃvutā._
____

[quote, Thī.v.405]
____
My father was a financier who lived restrained in [conduct within the 
constraints of the] code of morality.

_mayhaṃ pitā sīlasaṃvuto seṭṭhi._
____

=== Illustrations

.Illustration
====
asaṃvuta

unrestrained [from attraction and repulsion, through mindfulness]; 
saṃvarāya, restraint [through mindfulness]; saṃvaraṃ āpajjati, master
====

____
And how is a bhikkhu one with sense portals guarded [by mindfulness]?

_kathañca bhikkhave bhikkhu indriyesu guttadvāro hoti._
____

____
In this regard, in seeing a visible object via the visual sense, a bhikkhu does 
not grasp its aspects and features.

_Idha bhikkhave bhikkhu cakkhunā rūpaṃ disvā na nimittaggāhī hoti 
nānuvyañjanaggāhī_
____

____
Since, by abiding with the faculty of sight unrestrained [from attraction and 
repulsion, through mindfulness], greed, dejection, and unvirtuous, spiritually 
unwholesome factors would pursue him.

_yatvādhikaraṇamenaṃ cakkhundriyaṃ asaṃvutaṃ viharantaṃ abhijjhā 
domanassā pāpakā akusalā dhammā anvāssaveyyuṃ_
____

____
He applies himself to the restraint of the faculty [from attraction and 
repulsion, through mindfulness], he supervises the faculty of sight [with 
mindfulness], he attains restraint of the faculty of sight [through 
mindfulness].

_tassa saṃvarāya paṭipajjati rakkhati cakkhundriyaṃ cakkhundriye 
saṃvaraṃ āpajjati._
____

Suppose a chariot harnessed to thoroughbreds was standing ready on even ground 
at a crossroads, with a goad on hand. Then a proficient handler, a trainer of 
horses to be tamed, would mount it and, taking the reins in his left hand and 
the goad in his right, would drive away and return by any route he wants, 
whenever he wants.

So, too, a bhikkhu trains in

____
supervising these six sense faculties [with mindfulness]

_imesaṃ channaṃ indriyānaṃ ārakkhāya sikkhati_
____

____
restraining them [with mindfulness]

_saṃyamāya sikkhati_
____

____
taming them [with mindfulness]

_damāya sikkhati_
____

____
calming them [with mindfulness]

_upasamāya sikkhati_
____

[quote, S.4.176]
____
In this way a bhikkhu has sense portals guarded [by mindfulness].

_indriyesu guttadvāro hoti._
____

.Illustration
====
saṃvaro

restraint [of the sense faculties] [from attraction and repulsion, through 
mindfulness]
====

Suppose a man caught six animals with different natural habitats, and tied each 
of them with a strong cord: a snake, a crocodile, a bird, a dog, a jackal, and 
a monkey. Then he bound them to a strong post or pillar. Those six animals 
would each incline towards its own natural habitat.

- The snake would try to enter an anthill.

- The crocodile would try to enter the water.

- The bird would try to fly into the air.

- The dog would try to enter a village.

- The jackal would try to enter a charnel ground.

- The monkey would try to enter a forest.

When these six animals were worn out and fatigued, they would stand by that 
post or pillar, or sit or lie down there.

____
So, too, when a bhikkhu has developed and cultivated mindfulness of the body

_kāyagatā sati bhāvitā bahulīkatā_
____

____
the eye does not incline towards pleasing visible objects nor are displeasing 
visible objects loathsome

_cakkhu nāviñjati manāpikesu rūpesu amanāpikassa rūpāni nappaṭikkūlā 
honti;_
____

- the ear does not incline towards pleasing audible objects nor are displeasing 
audible objects loathsome;

- the nose does not incline towards pleasing smellable objects nor are 
displeasing smellable objects loathsome;

- the tongue does not incline towards pleasing tasteable objects nor are 
displeasing tasteable objects loathsome;

- the body does not incline towards pleasing tangible objects nor are 
displeasing tangible objects loathsome;

- the mind does not incline towards pleasing mentally known objects nor are 
displeasing mentally known objects loathsome.

[quote, S.4.200]
____
In this way there is restraint [of the sense faculties] [from attraction and 
repulsion, through mindfulness].

_Evaṃ kho bhikkhave saṃvaro hoti._
____

.Illustration
====
saṃvaro (=indriyasaṃvaro)

restraint [of the sense faculties] [from attraction and repulsion, through 
mindfulness]
====

____
And how is there restraint [of the sense faculties] [from attraction and 
repulsion, through mindfulness]?

_Kathañca bhikkhave saṃvaro hoti_
____

____
In this regard, in seeing a visible object via the visual sense, a bhikkhu is 
not intent upon an agreeable visible object, nor troubled by a disagreeable 
visible object.

_Idha bhikkhu cakkhunā rūpaṃ disvā piyarūpe rūpe nādhimuccati 
appiyarūpe rūpe na vyāpajjati_
____

[quote, S.4.189-90]
____
He abides having established mindfulness of the body, with an unlimited mental 
state, and he discerns according to reality, with the liberation [from 
attachment through inward calm] and the liberation [from uninsightfulness] 
through penetrative discernment, where those unvirtuous, spiritually 
unwholesome factors cease without remainder.

_upaṭṭhitakāyasati ca viharati appamāṇacetaso tañca cetovimuttiṃ 
paññāvimuttiṃ yathābhūtaṃ pajānāti yatthassa te uppannā pāpakā 
akusalā dhammā aparisesā nirujjhanti._
____

.Illustration
====
asaṃvaro (=indriya asaṃvaro)

unrestraint [of the sense faculties]
====

____
And how, bhikkhus is there unrestraint [of the sense faculties]?

_asaṃvaro hoti_
____

In this regard, in seeing a visible object via the visual sense, a bhikkhu is

____
intent upon an agreeable visible object

_piyarūpe rūpe adhimuccati_
____

____
troubled by a disagreeable visible object

_appiyarūpe rūpe vyāpajjati_
____

____
He abides without having established mindfulness of the body

_anupaṭṭhitakāyassati ca viharati_
____

____
with a small mind

_parittacetaso_
____

[quote, S.4.190]
____
and he does not discern according to reality, with the liberation [from 
attachment through inward calm] and the liberation [from uninsightfulness] 
through penetrative discernment, where those unvirtuous, spiritually 
unwholesome factors cease without remainder

_tañca cetovimuttiṃ paññāvimuttiṃ yathābhūtaṃ nappajānāti 
yatthassa te uppannā pāpakā akusalā dhammā aparisesā nirujjhanti._
____

.Illustration
====
asaṃvaro

unrestraint [of the sense faculties]
====

____
When a bhikkhu has not developed and cultivated mindfulness of the body,

_Evameva kho bhikkhave yassa kassaci bhikkhuno kāyagatā sati abhāvitā 
abahulīkatā_
____

____
the eye inclines towards pleasing visible objects

_taṃ cakkhu āviñjati manāpikesu rūpesu_
____

____
and displeasing visible objects are loathsome

_amanāpikassa rūpā paṭikkūlā honti_
____

[quote, S.4.199]
____
... In this way there is unrestraint [of the sense faculties].

_Evaṃ kho bhikkhave asaṃvaro hoti._
____

.Illustration
====
saṃvaro

restraint [of the sense faculties]
====

____
Suppose a man entered a thorny forest. There would be thorns in front of him 
and behind him, to his left and to his right, below him and above him. He would 
go forward and back aware, thinking, 'May no thorn prick me!'

_so sato ca abhikkameyya sato paṭikkameyya; mā maṃ kaṇṭako ti_
____

____
So, too, whatever in the world [of phenomena] is agreeable and pleasing is 
called a thorn in the [terminology of the] Noble One's training system.

_evaṃ kho bhikkhave yaṃ loke piyarūpaṃ sātarūpaṃ ayaṃ vuccati 
ariyassa vinaye kaṇṭako_
____

[quote, S.4.189]
____
Knowing [what is agreeable and pleasing] as a 'thorn,' one should understand 
restraint and unrestraint [of the sense faculties].

_taṃ kaṇṭako ti iti viditvā saṃvaro ca asaṃvaro ca veditabbo._
____

.Illustration
====
asaṃvutaṃ unrestrained [from attraction and repulsion

through mindfulness]; saṃvarāya, restraint of the sense faculties [from 
attraction and repulsion, through mindfulness]; saṃvaraṃ āpajjatha, master
====

____
Therefore dwell with sense portals guarded [by mindfulness].

_tasmātihabhikkhave indriyesu guttadvārā viharatha_
____

____
In seeing a visible object via the visual sense, do not grasp its aspects and 
features. Since by abiding with the faculty of sight unrestrained [from 
attraction and repulsion, through mindfulness], greed, dejection, and 
unvirtuous, spiritually unwholesome factors would pursue you.

_Cakkhunā rūpaṃ disvā mā nimittaggāhino ahuvattha mānuvyañjanaggāhino 
yatvādhikaraṇamenaṃ cakkhundriyaṃ asaṃvutaṃ viharantaṃ 
abhijjhādomanassā pāpakā akusalā dhammā anvāssaveyyuṃ_
____

[quote, S.4.178]
____
Apply yourself to the restraint of the faculty [from attraction and repulsion, 
through mindfulness]. Supervise the faculty of sight. Attain restraint of the 
faculty of sight [through mindfulness].

_tassa saṃvarāya paṭipajjatha rakkhatha cakkhundriyaṃ cakkhundriye 
saṃvaraṃ āpajjatha._
____

.Illustration
====
saṃvutassa

unrestrained [from attraction and repulsion, through mindfulness]
====

____
For one who abides with the faculty of sight unrestrained [from attraction and 
repulsion, through mindfulness], the mind is defiled by visible objects known 
via the visual sense.

_Cakkhundriyā asaṃvutassa bhikkhave viharato cittaṃ vyāsiñcati 
cakkhuviññeyyesu rūpesu_
____

____
For one with a defiled mind there is no gladness._

_tassa vyāsittacittassa pāmujjaṃ na hoti_
____

____
For one who abides with the faculty of sight restrained [from attraction and 
repulsion, through mindfulness], the mind is undefiled by visible objects known 
via the visual sense.

_Cakkhundriyaṃ saṃvutassa bhikkhave viharato cittaṃ na vyāsiñcati 
cakkhuviññeyyesu rūpesu_
____

[quote, S.4.78]
____
For one with an undefiled mind gladness arises._

_tassa avyāsittacittassa pāmojjaṃ jāyati._
____

.Illustration
====
asaṃvutakārī

restrain [from attraction and repulsion, through mindfulness]
====

[quote, S.4.196]
____
The ignorant Everyman does not restrain the six senses [from attraction and 
repulsion, through mindfulness]; he indulges himself as much as he likes in the 
five varieties of sensuous pleasure.

_assutavā puthujjano chasu phassāyatanesu asaṃvutakārī pañcasu 
kāmaguṇesu yāvadatthaṃ madaṃ āpajjati._
____

.Illustration
====
saṃvaro

unrestraint [of the sense faculties]
====

____
In what way is there unrestraint [of the sense faculties]?

_Kathañca bhikkhave asaṃvaro hoti?_
____

____
There are visible objects known via the visual sense that are likeable, 
loveable, pleasing, agreeable, connected with sensuous pleasure, and charming.

_Santi bhikkhave cakkhuviññeyyā rūpā iṭṭhā kantā manāpā piyarūpā 
kāmupasaṃhitā rajanīyā._
____

____
If a bhikkhu takes delight in them, welcomes them, persists in cleaving to 
them, he should understand this thus: 'I am falling away from spiritually 
wholesome factors. For this has been called falling away by the Blessed One.'

_Tañce bhikkhu abhinandati abhivadati ajjhosāya tiṭṭhati. 
Veditabbametaṃ bhikkhave bhikkhunā parihāyāmi kusalehi dhammehi 
parihānaṃ hetaṃ vuttaṃ bhagavatā ti._
____

[quote, S.4.76]
____
... In this way, there is unrestraint [of the sense faculties].

_Evaṃ kho bhikkhave asaṃvaro hoti._
____

.Illustration
====
saṃvaro

unrestraint [of the sense faculties]
====

• In what way is there restraint [of the sense faculties] [from attraction 
and repulsion, through mindfulness]? +
_Kathañca bhikkhave saṃvaro hoti?_

____
There are visible objects known via the visual sense that are likeable, 
loveable, pleasing, agreeable, connected with sensuous pleasure, and charming.

_Santi bhikkhave cakkhuviññeyyā rūpā iṭṭhā kantā manāpā piyarūpā 
kāmupasaṃhitā rajanīyā._
____

____
If a bhikkhu does not take delight in them, welcome them, persist in cleaving 
to them, he should understand this thus: 'I am not falling away from 
spiritually wholesome factors. For this has been called not falling away by the 
Blessed One._

_Tañce bhikkhu nābhinandati nābhivadati nājjhosāya tiṭṭhati. 
Veditabbametaṃ bhikkhave bhikkhunā na parihāyāmi kusalehi dhammehi 
aparihānaṃ hetaṃ vuttaṃ bhagavatā ti._
____

[quote, S.4.78-80]
____
In this way there is restraint [of the sense faculties] [from attraction and 
repulsion, through mindfulness]_

_Evaṃ kho bhikkhave saṃvaro hotī ti._
____

.Illustration
====
saṃvutindriyo

sense faculties restrained [from attraction and repulsion, through mindfulness]
====

[quote, Th.v.1081]
____
One who is not vain or puffed up, who is mindful, whose sense faculties are 
restrained [from attraction and repulsion, through mindfulness], looks glorious 
in rag-robes. He is like a lion in a mountain cave.

_Anuddhato acapalo nipako saṃvutindriyo +
Sobhati paṃsukūlena sīho va girigabbhare._
____

.Illustration
====
asaṃvutaṃ

unrestrained [from attraction and repulsion, through mindfulness]
====

____
On him who does not guard the senses of sight and hearing,

_Aguttaṃ cakkhusotasmiṃ_
____

____
Whose sense faculties are unrestrained [from attraction and repulsion, through 
mindfulness],

_indriyesu asaṃvutaṃ_
____

[quote, A.1.280]
____
His thoughts bound up with attachment will attack him like flies.

_Makkhikā anupatissanti saṅkappā rāganissitā._
____

.Illustration
====
asaṃvutehi

unrestrained [from attraction and repulsion, through mindfulness]
====

____
'Some bhikkhu enters the village for alms with his body, speech, and mind 
unsupervised [by mindfulness], with mindfulness unestablished, with sense 
faculties unrestrained [from attraction and repulsion, through mindfulness].

_arakkhiteneva kāyena arakkhitāya vācāya arakkhitena cittena 
anupaṭṭhitāya satiyā asaṃvutehi indriyehi_
____

[quote, S.2.270]
____
He sees women there lightly clad or lightly attired, and lust invades his mind.

_rāgo cittaṃ anuddhaṃseti._
____

.Illustration
====
saṃvaraṃ

restraint
====

If a bhikkhu commits an offence, he should confess it:

____
-- 'Bhante, I have committed such-and-such an offence; I confess it.'

_ahaṃ bhante itthannāmaṃ āpattiṃ āpanno taṃ paṭidesemī ti._
____

____
The other says:

_so evamāha_
____

____
-- 'Do you see it [as an offence]?'

_passasī ti_
____

____
-- 'Yes, I see it [as an offence].'

_passāmī ti._
____

____
-- 'Will you be restrained in future?'

_Āyatiṃ saṃvaraṃ āpajjeyyāsī ti_
____

[quote, M.2.248]
____
-- 'I will be restrained in future.'

_saṃvaraṃ āpajjissāmī ti._
____

COMMENT

_Passāmī_: 'I see it [as an offence].' By comparison:

[quote, M.3.246]
____
For one who sees a wrongdoing as such

_yo accayaṃ accayato disvā._
____

.Illustration
====
saṃvaratī

restrains
====

____
Trivial thoughts, subtle thoughts, mental jerkings that pursue one: without 
insight into these thoughts, one runs back and forth with wandering mind.

_Khuddā vitakkā sukhumā vitakkā anuggatā manaso uppilāvā +
Ete avidvā manaso vitakke hurāhuraṃ dhāvati bhantacitto._
____

[quote, Ud.37]
____
But with insight into these thoughts, one who is vigorous and mindful restrains 
them. One who is enlightened has entirely abandoned them, these mental jerkings 
that follow one along.

_Ete ca vidvā manaso vitakke ātāpiyo saṃvaratī satimā +
Anuggate manaso uppilāve asesamete pajahāsi buddho ti._
____

.Illustration
====
saṃvaraṃ

restraint
====

[quote, M.3.246]
____
Because it is considered growth in the Noble One's training system for one who 
sees a wrongdoing as such, to make amends for it in accordance with the 
teaching, and to show restraint in the future.

_Vuddhi hesā bhikkhu ariyassa vinaye yo accayaṃ accayato disvā yathā 
dhammaṃ paṭikaroti āyatiṃ saṃvaraṃ āpajjatī ti._
____

.Illustration
====
saṃvarāya

restrain
====

____
For two good reasons the Perfect One establishes training rules for his 
disciples.

_Dveme bhikkhave atthavase paṭicca tathāgatena sāvakānaṃ sikkhāpadaṃ 
paññattaṃ. Katame dve?_
____

____
To restrain unfriendly deeds (i.e. the bhikkhu's own deeds) in this lifetime, 
and to ward off unfriendly deeds (i.e. acts of retribution?) in the hereafter.

_diṭṭhadhammikānaṃ verānaṃ saṃvarāya samparāyikānaṃ verānaṃ 
paṭighātāya_
____

____
To restrain wrongdoings in this lifetime, and ward them off in the hereafter.

_diṭṭhadhammikānaṃ vajjānaṃ saṃvarāya samparāyikānaṃ 
vajjānaṃ paṭighātāya._
____

____
To restrain dangers in this lifetime, and ward them off in the hereafter.

_diṭṭhadhammikānaṃ bhayānaṃ saṃvarāya samparāyikānaṃ 
bhayānaṃ paṭighātāya._
____

[quote, A.1.98]
____
To restrain spiritually unwholesome factors in this lifetime, and ward them off 
in the hereafter.

_diṭṭhadhammikānaṃ akusalānaṃ dhammānaṃ saṃvarāya 
samparāyikānaṃ akusalānaṃ dhammānaṃ paṭighātāya._
____

.Illustration
====
saṃvuto

&#8203;[bodily] restrained
====

____
'In the village, I will sit [bodily] well-restrained' is a training to be 
undertaken.

_Susaṃvuto antaraghare nisīdissāmīti sikkhā karaṇīyā._
____

[quote, Vin.4.186]
____
If, disrespectful of the rule, one sits in the village fidgeting with one's 
hands or feet, it is a dukkaṭa offence.

_yo anādariyaṃ paṭicca hatthaṃ vā pādaṃ vā kīḷāpento 
antaraghare nisidati āpatti dukkaṭassa._
____

.Illustration
====
asaṃvutaṃ

unrestrained [in conduct]
====

[quote, Thī.v.452]
____
Fools are unrestrained [in conduct] of body, speech, and mind.

_Kāyena ca vācāya ca manasā ca asaṃvutā bālā._
____

.Illustration
====
saṃvutaṃ

restrained [in conduct]
====

____
In whom there is no wrongdoing by way of body, speech, or mind

_Yassa kāyena vācāya manasā natthi dukkataṃ_
____

[quote, Dh.v.391]
____
Who is restrained in these three respects, he is what I call a Brahman.

_Saṃvutaṃ tīhi ṭhānehi tamahaṃ brūmi brāhmaṇaṃ._
____

.Illustration
====
saṃvaro

restraint [in conduct]
====

[quote, S.1.73]
____
Restraint [in conduct] of body, speech, and mind is good. Restraint [in 
conduct] in all respects is good.

_Kāyena saṃvaro sādhu sādhu vācāya saṃvaro +
Manasā saṃvaro sādhu sādhu sabbattha saṃvaro._
____

COMMENT

This verse was spoken in response to King Pasenadi, who had said:

[quote, S.1.73]
____
Those who misconduct themselves by way of body, speech, and mind do not 
&#8203;[spiritually] protect themselves.

_ye kho keci kāyena duccaritaṃ caranti vācāya duccaritaṃ caranti manasā 
duccaritaṃ caranti tesaṃ arakkhito attā._
____

.Illustration
====
saṃvutadvāro

closed
====

[quote, Vin.1.248]
____
This, friend Roja, is his dwelling-place. The door is closed.

_Esāvuso roja vihāro saṃvutadvāro._
____

