== Saṃyojana

=== Renderings

- _saṃyojana_: tie

- _saṃyojana_: tie to individual existence

- _saṃyojana_: psychological bondage

- _saṃyojana_: bond

=== Introduction

==== On not parenthesising

_Saṃyojanāni_ is shown in the following quote to be an abbreviation of 
_bhavapaṭilābhiyāni saṃyojanāni_ ('ties to individual existence'). In 
which case, _saṃyojana_ could be parenthesised: 'tie [to individual 
existence].' However, that _saṃyojana_ means 'tie to individual existence' is 
so well established in the suttas, that parenthesis seems unnecessary. After 
all, in the same following quote _orambhāgiyāni saṃyojanāni_ is used, 
where, according to the same quote, it should read _orambhāgiyāni 
bhavapaṭilābhiyāni saṃyojanāni_.

____
&#8203;[In the arahant] the ties to individual existence in the low plane of existence 
are abandoned

_Imassa kho bhikkhave puggalassa orambhāgiyāni saṃyojanāni pahīṇāni_
____

____
... the ties to rebirth are abandoned

_Upapattipaṭilābhiyāni saṃyojanāni pahīṇāni_
____

[quote, A.2.134]
____
... the ties to individual existence are abandoned

_Bhavapaṭilābhiyāni saṃyojanāni pahīṇāni._
____

==== With specified objects: 'tie'

If _saṃyojana_ has an object it means simply 'tie.' For example:

[quote, It.42]
____
the tie to [renewed] birth and old age

_Saṃyojanaṃ jātijarāya._
____

==== Destruction of tie or ties

Destruction is usually of plural 'ties':

[quote, A.3.443]
____
The ties to individual existence will be abandoned by me;

_saṃyojanā ca me pahānaṃ gacchanti._
____

But occasionally singular 'tie':

• severed the tie to [renewed] birth and old age +
_Saṃyojanaṃ jātijarāya chetvā_ (It.42).

[quote, A.3.247]
____
obliterated the tie to individual existence.

_vāvattayi saṃyojanaṃ._
____

==== Saṃyojana: bond

_Saṃyojana_ can mean bond, for example:

[quote, S.4.163]
____
The black ox is not the bond of the white ox, nor is the white ox the bond of 
the black ox, but rather the single rope or yoke by which the two are yoked: 
that is the bond there.

_Na kho āvuso kāḷo balivaddo odātassa balivaddassa saṃyojanaṃ napi 
odāto balivaddo kāḷassa balivaddassa saṃyojanaṃ yena ca kho te ekena 
dāmena vā yottena vā saṃyuttā taṃ tattha saṃyojanaṃ._
____

[quote, S.4.163]
____
Koṭṭhita, friend, the visual sense is not the bond of visible objects nor 
are visible objects the bond of the visual sense, but rather the fondness and 
attachment that arises because of both are the bonds there.

_Na kho āvuso koṭṭhita cakkhu rūpānaṃ saṃyojanaṃ na rūpā 
cakkhussa saṃyojanaṃ. Yañca tattha tadubhayaṃ paṭicca uppajjati 
chandarāgo taṃ tattha saṃyojanaṃ._
____

==== Saṃyojana: psychological bondage

_Saṃyojana_ can mean psychological bondage:

[quote, S.3.187]
____
When there is bodily form, by grasping bodily form, by stubbornly adhering to 
bodily form, psychological bondage, stubborn attachment, emotional bondage, and 
cleaving arise.

_rūpe kho bhikkhave sati rūpaṃ upādāya rūpaṃ abhinivissa uppajjanti 
saṃyojanābhinivesa-vinibandhājjhosānā._
____

=== Illustrations

.Illustration
====
saṃyojanaṃ

tie to individual existence
====

[quote, S.4.301]
____
There is no tie to individual existence tethered by which the householder Citta 
will return to this [low] plane of existence.

_natthitaṃ saṃyojanaṃ yena saṃyojanena saṃyutto citto gahapati puna 
imaṃ lokaṃ āgaccheyyāti._
____

.Illustration
====
saṃyojanānaṃ

ties to individual existence
====

[quote, A.4.11-13]
____
In destroying the first three ties to individual existence, he becomes a 
stream-enterer, no more liable to rebirth in the plane of damnation, assured of 
deliverance, with enlightenment as his destiny.

_So tiṇṇaṃ saṃyojanānaṃ parikkhayā sotāpanno hoti avinipātadhammo 
niyato sambodhiparāyaṇo._
____

.Illustration
====
saṃyojana

ties to individual existence
====

[quote, A.3.373]
____
Transcended the ties to individual existence in the sensuous plane of existence

_kāmasaṃyojanātigā._
____

.Illustration
====
saṃyojanāni

ties to individual existence
====

1. There are these five ties to individual existence in the low plane of 
existence
+
****
_Pañcimāni bhikkhave orambhāgiyāni saṃyojanāni. Katamāni pañca:_
****

____
view of personal identity

_sakkāyadiṭṭhi_
____

____
doubt [about the significance of the teaching]

_vicikicchā_
____

____
adherence to observances and practices

_sīlabbataparāmāso_
____

____
sensuous hankering _

_kāmacchando_
____

[quote, S.5.61-62]
____
ill will _

_vyāpādo._
____

2. There are these five ties to individual existence in the middle and high 
planes of existence. What five?
+
****
_pañcimāni bhikkhave uddhambhāgiyāni saṃyojanāni. katamāni pañca?_
****

____
attachment to the refined material states of awareness _

_rūparāgo_
____

____
attachment to immaterial states of awareness _

_arūparāgo_
____

____
self-centredness _

_māno_
____

____
vanity

_uddhaccaṃ_
____

[quote, S.5.61-62]
____
uninsightfulness into reality

_avijjā._
____

.Illustration
====
saṃyojanaṃ

ties to individual existence
====

____
This religious life is lived for the abandonment and eradication of seven ties 
to individual existence. Which seven?

_Sattannaṃ bhikkhave saṃyojanānaṃ pahānāya samucchedāya 
brahmacariyaṃ vussati. Katamesaṃ sattannaṃ:_
____

1. attraction [to sensuous pleasure]
+
****
_anunayasaṃyojanaṃ_
****

2. repugnance
+
****
_paṭighasaṃyojanaṃ_
****

3. dogmatism
+
****
_diṭṭhisaṃyojanaṃ_
****

4. doubt [about the significance of the teaching]
+
****
_vicikicchāsaṃyojanaṃ_
****

5. pride
+
****
_mānasaṃyojanaṃ_
****

6. envy
+
****
_issāsaṃyojanaṃ_
****

7. stinginess
+
****
_macchariyasaṃyojanaṃ_ (A.4.7-9).
****

.Illustration
====
saṃyojanaṃ

ties to individual existence
====

____
Seven ties to individual existence

_Sattimāni bhikkhave saṃyojanāni. Katamāni satta?_
____

1. attraction [to sensuous pleasure]
+
****
_anunayasaṃyojanaṃ_
****

2. repugnance
+
****
_paṭighasaṃyojanaṃ_
****

3. dogmatism
+
****
_diṭṭhisaṃyojanaṃ_
****

4. doubt [about the significance of the teaching]
+
****
_vicikicchāsaṃyojanaṃ_
****

5. self-centredness
+
****
_mānasaṃyojanaṃ_
****

6. attachment to individual existence
+
****
_bhavarāgasaṃyojanaṃ_
****

7. uninsightfulness into reality
+
****
_avijjāsaṃyojanaṃ_ (D.3.254).
****

.Illustration
====
saṃyojanaṃ

tie to individual existence; saṃyojanam, bond
====

[quote, It.8]
____
Bhikkhus, I do not see any other single tie to individual existence, tethered 
by which beings would roam and wander the round of birth and death for such a 
long time as the tie of craving.

_Nāhaṃ bhikkhave aññaṃ ekasaṃyojanampi samanupassāmi yena 
saṃyojanena saṃyuttā sattā dīgharattaṃ sandhāvanti saṃsaranti 
yathayidaṃ bhikkhave taṇhāsaṃyojanaṃ._
____

.Illustration
====
saṃyojanaṃ

tie to individual existence
====

[quote, A.1.264]
____
I call this a tie to individual existence: the mind of attachment.

_Etamahaṃ bhikkhave saṃyojanaṃ vadāmi yo cetaso sārāgo._
____

.Illustration
====
saṃyojaniyo

psychological bondage; saṃyojanaṃ, bonds
====

[quote, S.3.167]
____
Bodily form is conducive to psychological bondage. The fondness and attachment 
are the bonds there.

_Rūpaṃ bhikkhave saṃyojaniyo dhammo. Yo tattha chandarāgo taṃ tattha 
saṃyojanaṃ._
____

.Illustration
====
saṃyojana

bond
====

[quote, S.4.36]
____
Tethered [to individual existence] by the bond of spiritually fettering 
delight, Migajāla, a bhikkhu is called 'one living with a partner.'

_nandisaṃyojanasaṃyutto kho migajāla bhikkhu sadutiyavihārī ti vuccati._
____

.Illustration
====
saṃyojanā

bonds
====

[quote, D.2.276]
____
Lord of the Devas, it is because of the bonds of envy and stinginess that, 
though they wish to abide free of unfriendliness, violence, enmity, hostility, 
and uncordiality, yet they in fact abide with all these things.'

_Issāmacchariyasaṃyojanā kho devānaminda devā manussā asurā nāgā 
gandhabbā ye caññe santi puthukāyā te averā adaṇḍā asapattā 
avyāpajjhā viharemu averino ti iti ce nesaṃ hoti. Atha ca pana saverā 
sadaṇḍā sasapattā savyapajjā viharanti saverino ti._
____

