== Saṃsagga; Saṃsaṭṭha

=== Renderings

- _saṃsagga_: association

- _saṃsagga_: consorting [with householders and ascetics]

- _asaṃsagga_: remaining aloof [from householders and ascetics]

- _saṃsaṭṭha_: engrossed in

- _saṃsaṭṭha_: consort with

- _saṃsaṭṭha_: mixed with

- _saṃsaṭṭha_: intermingled

- _saṃsaṭṭha_: mingling with each other [unbecomingly as regards conduct 
of body and speech]

- _asaṃsaṭṭha_: aloof from

- _asaṃsaṭṭha_: remain aloof [from householders and ascetics]

- _saṃsaggasaṃsaṭṭho_: embroiling oneself

- _visaṃsaṭṭha_: aloof from

- _visaṃsaṭṭha_: dissociated

=== Introduction

==== Objects of saṃsagga and saṃsaṭṭha

Sometimes the objects of _saṃsagga_ and _saṃsaṭṭha_ are 'householders 
and ascetics':

[quote, A.3.117]
____
A bhikkhu consorts with householders and ascetics in an unsuitable way like a 
layperson.

_bhikkhu saṃsaṭṭho viharati gahaṭṭhapabbajitehi ananulomikena 
gihisaṃsaggena._
____

[quote, Sn.v.628]
____
One who remains aloof from householders and ascetics alike, who roams about 
homeless [free of attachment to the five aggregates], and is of few needs, he 
is what I call a Brahman.

_Asaṃsaṭṭhaṃ gahaṭṭhehi anāgārehi cūbhayaṃ +
Anokasāriṃ appicchaṃ tamahaṃ brūmi brāhmaṇaṃ._
____

==== Objectless saṃsagga and saṃsaṭṭha

Sometimes the object is missing, and we parenthesise. For example:

[quote, Th.v.860]
____
Remaining aloof [from householders and ascetics alike], delighted with whatever 
offerings enter his almsbowl, Bhaddiya, son of Godhā, meditates [happily], 
perseveringly, and free of grasping.

_Asaṃsaṭṭho sātatiko uñchāpattāgate rato +
Jhāyati anupādāno putto godhāya bhaddiyo._
____

Here the object of _asaṃsaṭṭho_ is missing. But the first words of verses 
Th.v.857-860 form a list, namely: _appiccho, santuṭṭho, pavivitto, 
asaṃsaṭṭho_. This whole set of four words occurs in verse 581, where the 
meaning of _asaṃsaṭṭho_ is made clear i.e. _gahaṭṭhehi anāgārehi 
cūbhayaṃ_:

[quote, Th.v.581]
____
And a sage should abide with few needs, content [with what is paltry and easily 
gotten], living secludedly, remaining aloof from householders and ascetics 
alike.

_Appiccho ceva santuṭṭho pavivitto vase muni +
Asaṃsaṭṭho gahaṭṭhehi anāgārehi cūbhayaṃ._
____

On the basis of this, where there is no object, we parenthesise 'householders 
and ascetics.'

=== Illustrations

.Illustration
====
saṃsaṭṭho

engrossed in; visaṃsaṭṭho, aloof from
====

[quote, M.1.480]
____
"If we get this, we will do it; if not, we won't": even in relation to teachers 
bent on worldly benefits, inheritors of worldly benefits, engrossed in worldly 
benefits, such haggling by disciples is unacceptable. So what about the Perfect 
One who abides completely aloof from worldly benefits?

_Yopi so bhikkhave satthā āmisagaru āmisadāyādo āmisehi saṃsaṭṭho 
viharati tassapayaṃ evarūpī paṇopaṇaviyā na upeti. Evañca no assa 
atha naṃ kareyyāma. Na ca no evamassa na naṃ kareyyāmā ti. Kimpana 
bhikkhave yaṃ tathāgato sabbaso āmisehi visaṃsaṭṭho viharati._
____

.Illustration
====
saṃsaṭṭho

engrossed in; asaṃsaṭṭho, aloof from
====

____
In the first place some person lives engrossed in sensuous pleasures and 
spiritually unwholesome factors.

_Idha bho ekacco saṃsaṭṭho viharati kāmehi saṃsaṭṭho akusalehi 
dhammehi._
____

____
At some time he hears the noble teaching, properly contemplates it, and applies 
himself in accordance with it.

_So aparena samayena ariyadhammaṃ suṇāti yoniso manasikaroti 
dhammānudhammaṃ paṭipajjati_
____

[quote, D.2.214]
____
In doing so he lives aloof from sensuous pleasures and spiritually unwholesome 
factors.

_so ariyadhammasavanaṃ āgamma yoniso manasikāraṃ 
dhammānudhammapaṭipattiṃ asaṃsaṭṭho viharati kāmehi 
asaṃsaṭṭho akusalehi dhammehi._
____

.Illustration
====
saṃsaṭṭho

mixed with
====

[quote, S.2.110]
____
A bronze cup of a beverage having an excellent colour, aroma, and flavour, but 
mixed with poison.

__āpānīyakaṃso vaṇṇasampanno gandhasampanno rasasampanno so ca kho 
visena saṃsaṭṭho._
____

.Illustration
====
saṃsaṭṭhā

intermingled; visaṃsaṭṭhā, dissociated
====

____
-- Penetrative discernment and advertence: are these states intermingled or 
dissociated?

_Yā cāvuso paññā yañca viññāṇaṃ ime dhammā saṃsaṭṭhā 
udāhu visaṃsaṭṭhā_
____

____
... Is it possible to separate them in order to describe them separately?

_labbhā ca panime dhammānaṃ vinibbhujitvā vinibbhujitvā nānākaraṇaṃ 
paññāpetunti?_
____

____
-- Penetrative discernment and advertence are intermingled not dissociated, and 
it is impossible to separate them in order to describe them separately.

_Yā cāvuso paññā yañca viññāṇaṃ ime dhammā saṃsaṭṭhā no 
visaṃsaṭṭhā. Na ca labbhā imesaṃ dhammānaṃ vinibbhujitvā 
vinibbhujitvā nānākaraṇaṃ paññāpetuṃ_
____

____
... For what one discerns, that one knows

_Yañcāvuso pajānāti taṃ vijānāti._
____

[quote, M.1.292-3]
____
... What one knows, that one discerns

_Yaṃ vijānāti taṃ pajānāti._
____

.Illustration
====
saṃsaṭṭhā

mingling with each other [unbecomingly as regards conduct of body and speech]
====

____
Now at that time bhikkhunīs who were pupils of the nun Thullanandā dwelt 
mingling with each other [unbecomingly as regards conduct of body and speech].

_Tena kho pana samayena thullanandāya bhikkhuniyā antevāsikā bhikkhuniyo 
saṃsaṭṭhā viharanti_
____

[quote, Vin.4.239]
____
'Dwell mingling with each other' means: they dwell mingling with each other 
unbecomingly as regards conduct of body and speech.

_Saṃsaṭṭhā viharantīti saṃsaṭṭhā nāma ananulomikena 
kāyikavācasikena saṃsaṭṭhā viharanti._
____

.Illustration
====
saṃsaṭṭhā

consort
====

[quote, Vin.4.294]
____
Do not, lady, consort with a layman or layman's son. Be secluded [from them]. 
The community of bhikkhunīs indeed praises such seclusion in a sister.

_māyye saṃsaṭṭhā vihari gahapatinānāpi gahapatiputtenāpi viviccayye 
vivekaññeva bhaginiyā saṅgho vaṇṇetī ti._
____

.Illustration
====
saṃsaṭṭho

consort
====

[quote, A.5.82]
____
Again, the king dispatches his army at the wrong time. Those displeased by this 
think: 'The king consorts with the ascetic. Could this be the ascetic's work?

_Puna ca paraṃ bhikkhave rājā akāle senaṃ uyyojeti yesaṃ taṃ 
amanāpaṃ tesaṃ evaṃ hoti: rājā kho pabbajitena saṃsaṭṭho siyā 
nu kho pabbajitassa kammanti._
____

.Illustration
====
saṃsaṭṭhā

consorting with
====

[quote, A.3.109]
____
In the future there will be bhikkhus who live consorting with bhikkhunīs, 
sikkhamānās, and sāmaṇerīs.

_Puna ca paraṃ bhikkhave bhavissanti bhikkhū anāgatamaddhānaṃ 
bhikkhunīsikkhamānāsamaṇuddesehi saṃsaṭṭhā viharissanti._
____

.Illustration
====
asaṃsaṭṭho

remained aloof [from householders and ascetics alike]
====

[quote, S.2.203]
____
I have remained aloof [from householders and ascetics alike] and have spoken in 
praise of such aloofness

_asaṃsaṭṭho ceva asaṃsaggassa ca vaṇṇavādī._
____

.Illustration
====
asaṃsagga

remaining aloof [from householders and ascetics alike]
====

[quote, M.3.113]
____
That is to say: talk about fewness of needs, talk about contentment, talk about 
physical seclusion, talk about remaining aloof [from householders and ascetics 
alike], talk about the exertion of energy... he thinks: 'I will utter speech 
like this.'

_Seyyathīdaṃ appicchakathā santuṭṭhikathā pavivekakathā 
asaṃsaggakathā viriyārambhakathā... iti evarūpiṃ kathaṃ kathessāmī 
ti._
____

.Illustration
====
saṃsaggā

consorting [with householders and ascetics]; asaṃsaggena, remaining aloof 
&#8203;[from householders and ascetics]
====

[quote, S.2.158]
____
By consorting [with householders and ascetics] craving is born. By remaining 
aloof [from householders and ascetics] it is cut.

_Saṃsaggā vanatho jāto asaṃsaggena chijjati._
____

.Illustration
====
saṃsaggaṃ

association
====

____
I do not praise all association, nor do I criticise all association.

_Nāhaṃ moggallāna sabbeheva saṃsaggaṃ vaṇṇayāmi na panāhaṃ 
moggallāna sabbeheva saṃsaggaṃ na vaṇṇayāmi._
____

____
I do not praise association with householders and ascetics.

_Sagahaṭṭhapabbajitehi kho ahaṃ moggallāna saṃsaggaṃ na 
vaṇṇayāmi._
____

[quote, A.4.87-8]
____
But dwellings that are quiet, undisturbed by voices, with a quiet atmosphere, 
remote from people, suitable for solitary retreat, I praise the association 
with such dwellings.

_Yāni ca kho tāni senāsanāni appasaddāni appanigghosāni vijanavātāni 
manussarāhaseyyakāni paṭisallānasāruppāni tathārūpehi senāsanehi 
saṃsaggaṃ vaṇṇayāmī ti._
____

.Illustration
====
saṃsaggasaṃsaṭṭho

in embroiling himself
====

[quote, Dh.v.291]
____
He who wants his own happiness through causing others suffering, in embroiling 
himself in unfriendliness, from unfriendliness he will not be released.

_Paradukkhūpadhānena attano sukhamicchati +
Verasaṃsaggasaṃsaṭṭho verā so na parimuccati._
____

