== Saṅkhā

=== Renderings

- _saṅkhā_: conception

- _saṅkhā_: reason

- _saṅkhā_: ulterior motive

- _saṅkhātuṃ_: to reckon

- _saṅkhāya_: having reflected

- _saṅkhāya_: on reflection

- _saṅkhāya_: with reflectiveness

- _saṅkhaṃ gacchati_: to be reckoned

- _na upeti saṅkhaṃ_: to be beyond the limits of conception

=== Illustrations

.Illustration
====
saṅkhā

conception
====

[quote, M.1.111]
____
What one perceives, one thinks about. What one thinks about, one perceptually 
entrenches. Due to what one perceptually entrenches, entrenched perception and 
conception assail a man in relation to visible objects known via the visual 
sense whether past, future, or present.

_Yaṃ sañjānāti taṃ vitakketi. Yaṃ vitakketi taṃ papañceti. Yaṃ 
papañceti tatonidānaṃ purisaṃ papañcasaññāsaṅkhā samudācaranti 
atītānāgatapaccuppannesu cakkhuviññeyyesu rūpesu._
____

.Illustration
====
saṅkhā

conception
====

[quote, D.__2.27__7]
____
Lord of the Devas, the basis, origin, object of genesis and production, of 
thought is entrenched perception and conception. When there is entrenched 
perception and conception, thought arises. Without entrenched perception and 
conception, there is no thought.

_Vitakko kho devānaminda papañcasaññāsaṅkhānidāno 
papañcasaññāsaṅkhāsamudayo papañcasaññāsaṅkhājātiko 
papañcasaññāsaṅkhāpabhavo papañcasaññāsaṅkhāya sati vitakko hoti 
papañcasaññāsaṅkhāya asati vitakko na hotī ti._
____

.Illustration
====
saṅkhāya

conception
====

[quote, Sn.v.916]
____
A wise person should completely destroy the origin of entrenched conception, 
the notion "I am."

_mūlaṃ papañcasaṅkhāya mantā asmī ti sabbamuparundhe._
____

.Illustration
====
saṅkhāya

conception; saṅkhaṃ nopeti, beyond the limits of conception
====

____
Beings who perceive [only] what can be expressed and are entrenched in what can 
be expressed, not profoundly understanding what is expressed, they come under 
the yoke of death;

_Akkheyyasaññino sattā akkheyyasmiṃ patiṭṭhitā. +
Akkheyyaṃ apariññāya yogamāyanti maccuno._
____

____
But if one profoundly understands what can be expressed, and does not think 'I 
am the expressor,' the mind's liberation is achieved, the unsurpassed Peaceful 
State.

_Akkheyyañca pariññāya akkhātāraṃ na maññati +
Phūṭṭho vimokkho manasā santipadamanuttaraṃ._
____

____
Perfectly understanding what can be expressed, the Peaceful One delights in the 
Peaceful State.

_Sa ce akkheyyasampanno santo santipade rato_
____

[quote, It.53]
____
The one who is blessed with profound knowledge, being established in 
righteousness, though he makes use of conception he is beyond the limits of 
conception.

_Saṅkhāya sevī dhammaṭṭho saṅkhaṃ nopeti vedagū ti._
____

Comment

____
Though the one of great wisdom has transcended self-centredness he might still 
say 'I speak,'

_So vītivatto maññanaṃ sumedho +
Ahaṃ vadāmī ti pi so vadeyya_
____

____
and he might say 'They speak to me.'

_Mamaṃ vadantī ti pi so vadeyya_
____

[quote, S.1.14-15]
____
Proficient, understanding conventional terminology, he makes use of such terms 
merely for the purposes of communication.

_Loke samaññaṃ kusalo viditvā +
Vohāramattena so vohareyyā ti._
____

.Illustration
====
na upeti saṅkhaṃ

beyond the limits of conception
====

[quote, Sn.v.1074]
____
Just as a flame tossed about by the force of the wind vanishes, and is beyond 
the limits of conception, so a sage liberated from denomination-and-body 
vanishes, and is beyond the limits of conception.

_Acci yathā vātavegena khitt atthaṃ paleti na upeti saṅkhaṃ; +
Evaṃ muni nāmakāyā vimutto atthaṃ paleti na upeti saṅkhaṃ._
____

Comment:

This is explained two verses later as follows:

[quote, Sn.v.1076]
____
There is no measuring of one who has vanished. That no longer exists in 
relation to which one might speak of him. When all points of reference are 
removed, then all ways of talking about him are also removed.

_Atthaṅgatassa na pamāṇamatthi yena naṃ vajjuṃ taṃ tassa natthi +
Sabbesu dhammesu samūhatesu samūhatā vādapathā pi sabbe ti._
____

Comment:

____
The Perfect One has abandoned that bodily form... advertence by which one 
knowing the Perfect One might know him. It is chopped down at the root, 
completely and irreversibly destroyed, never to arise again in future.

_Yena rūpena... viññāṇena tathāgataṃ paññāpayamāno paññāpeyya 
taṃ rūpaṃ... viññāṇaṃ tathāgatassa pahīnaṃ ucchinnamūlaṃ 
tālāvatthukataṃ anabhāvakataṃ āyatiṃ anuppādadhammaṃ._
____

[quote, M.1.488]
____
... The Perfect One is liberated from being reckoned in terms of bodily form... 
advertence, Vaccha, he is profound, immeasurable, unfathomable like the ocean

_Rūpasaṅkhāvimutto... Viññāṇasaṅkhāvimutto kho vaccha tathāgato 
gambhīro appameyyo duppariyogāho seyyathā pi mahāsamuddo._
____

.Illustration
====
saṅkhā

consideration
====

[quote, M.1.105]
____
'But while I am staying in this quiet grove, unestablished mindfulness is not 
established...': Bhikkhus, on the basis of that consideration, that bhikkhu 
should depart from that quiet grove, he should not remain.

_Atha ca pana me imaṃ vanapatthaṃ upanissāya viharato anupaṭṭhitā 
ceva sati na upaṭṭhāti... Tena bhikkhave bhikkhunā saṅkhāpi tamhā 
vanapatthā pakkamitabbaṃ na vatthabbaṃ._
____

.Illustration
====
saṅkhāya

ulterior motive
====

[quote, A.2.143]
____
He visits families with an ulterior motive, he takes a seat with an ulterior 
motive, he explains the teaching with an ulterior motive, he restrains the 
calls of nature with an ulterior motive.

_So saṅkhāya kulāni upasaṅkamati saṅkhāya nisīdati saṅkhāya 
dhammaṃ bhāsati saṅkhāya uccārapassāvaṃ sandhāreti._
____

.Illustration
====
saṅkhātuṃ

reckon
====

[quote, D.3.111]
____
There are devas whose life-span is not to be reckoned by counting or 
computation.

_Santi bhante devā yesaṃ na sakkā gaṇanāya vā saṅkhānena vā āyuṃ 
saṅkhātuṃ._
____

.Illustration
====
saṅkhaṃ gacchati

reckoned
====

[quote, D.1.202]
____
Whenever the gross material acquired self is present, it is not reckoned as a 
mind-made material acquired self, nor an immaterial acquired self. It is 
reckoned only as a gross material acquired self on that occasion.

_yasmiṃ samaye oḷāriko attapaṭilābho hoti neva tasmiṃ samaye manomayo 
attapaṭilābho ti saṅkhaṃ gacchati. Na arūpo attapaṭilābho ti 
saṅkhaṃ gacchati. 'Oḷāriko attapaṭilābho'tveva tasmiṃ samaye 
saṅkhaṃ gacchati._
____

.Illustration
====
saṅkhaṃ gacchati

reckoned
====

[quote, D.1.201]
____
From a cow comes milk, from milk comes cream, from cream comes butter, from 
butter comes ghee, and from ghee comes cream of ghee. When there is milk, it is 
not then reckoned as cream or butter or ghee or cream of ghee. It is reckoned 
then only as milk.

_gavā khīraṃ khīramhā dadhi dadhimhā navanītaṃ navanītamhā sappi 
sappimhā sappimaṇḍo yasmiṃ samaye khīraṃ hoti neva tasmiṃ samaye 
dadhīti saṅkhaṃ gacchati. Na navanītanti saṅkhaṃ gacchati. Na 
sappīti saṅkhaṃ gacchati. Na sappimaṇḍoti saṅkhaṃ gacchati. 
Khīraṃ tveva tasmiṃ samaye saṅkhaṃ gacchati._
____

.Illustration
====
saṅkhāya

having reflected
====

[quote, D.2.228]
____
There are eight statements spoken by Sakka, Lord of the Devas, in praise of the 
Blessed One that are in accordance with reality. Having reflected on them we 
rejoice.

_atthi ca sakkena devānamindena tassa bhagavato aṭṭha yathābhuccā 
vaṇṇā bhāsitā te ca mayaṃ saṅkhāya modāmā ti._
____

.Illustration
====
saṅkhāya

having reflected
====

[quote, Sn.v.1048]
____
He for whom, having reflected on the world through and through, there is no 
spiritual instability in relation to anything in the world... he has overcome 
birth and old age, I declare.

_Saṅkhāya lokasmiṃ parovarāni +
Yassiñjitaṃ natthi kuhiñci loke._
____

Comment:

_Iñjitaṃ_: 'spiritual instability.' For example:

[quote, S.4.203]
____
The notion "I am" is a matter of spiritual instability,

_asmī ti bhikkhave iñjitametaṃ._
____

.Illustration
====
saṅkhāya

having reflected
====

[quote, Sn.v.391]
____
Having heard the teaching explained by the Sublime One, having reflected [on 
it], the disciple of excellent wisdom should make [appropriate] use of 
almsfood, abodes, beds and seats, and water to wash his robes.

_Piṇḍaṃ vihāraṃ sayanāsanañca āpañca 
saṅghāṭirajūpavāhanaṃ +
Sutvāna dhammaṃ sugatena desitaṃ saṅkhāya seve varapaññasāvako._
____

.Illustration
====
saṅkhāya

on reflection
====

[quote, D.3.224]
____
Four supports: here a bhikkhu on reflection pursues something, or endures it, 
or avoids it, or dispels it.

_Cattāri apassenāni: idhāvuso bhikkhu saṅkhāyekaṃ paṭisevati 
saṅkhāyekaṃ adhivāseti saṅkhāyekaṃ parivajjeti saṅkhāyekaṃ 
vinodeti._
____

.Illustration
====
saṅkhāya

with reflectiveness
====

[quote, S.1.182]
____
He in this world who lives the religious life having spurned [the accumulating 
of] merit and demerit, who fares in the world with reflectiveness, he is truly 
called a bhikkhu.

_Yodha puññañca pāpañca bāhetvā brahmacariyavā +
Saṅkhāya loke carati sa ve bhikkhū ti vuccati._
____

.Illustration
====
saṅkhāya

with reflectiveness
====

[quote, Sn.v.1041]
____
'The bhikkhu who in the face of sensuous pleasures lives the religious life 
with reflectiveness, free of craving, ever mindfully, and inwardly at peace, 
for him there are no states of spiritual instability.

_Kāmesu brahmacariyavā vītataṇho sadā sato +
Saṅkhāya nibbuto bhikkhu tassa no santi iñjitā._
____

