== Saṃvega; Saṃvejeti

=== Renderings

- _saṃvejeti_: to stir up an earnest attitude [to the practice]

- _saṃvejeti_: to be quickened

- _saṃvega_: earnest attitude [to the practice]

- _saṃvega_: earnest attitude [to one's work]

- _saṃvejanīya_: fill with an earnest attitude [to the practice]

- _saṃvijjati_: to be dismayed

- _saṃvijjati_: to be quickened

- _saṃvega_: dismay

=== Introduction

==== Earnest attitude [to the practice]: fear, dismay, or inspiration

An earnest attitude [to the practice] comes from fear, dismay, or inspiration. 
This can be seen in the following Illustrations.

=== Illustrations

.Illustration
====
saṃvejehī

stir up an earnest attitude [to the practice]
====

[quote, S.5.269-70]
____
Moggallāna, your companions in the religious life, dwelling on the ground 
floor of the Mansion of Migāra's Mother, are restless, frivolous, fidgety, 
talkative, garrulous, unmindful, not fully conscious, inwardly uncollected, 
mentally scattered, [and are dwelling with] their sense faculties unrestrained 
&#8203;[from attraction and repulsion, through mindfulness]. Go, Moggallāna, and stir 
up an earnest attitude [to the practice] in those bhikkhus.

_ete te moggallāna sabrahmacārayo heṭṭhāmigāramātupāsāde viharanti 
uddhatā unnaḷā capalā mukharā vikiṇṇavācā muṭṭhassatino 
asampajānā asamāhitā vibbhantacittā pākatindriyā. Gaccha moggallāna te 
bhikkhu saṃvejehī ti._
____

.Illustration
====
saṃvejeyyan

stir up an earnest attitude [to the practice]
====

____
'This deity dwells much too negligently applied [to the practice]. How about if 
I stirred up an earnest attitude [to the practice] in him?'

_atibāḷhaṃ kho ayaṃ yakkho pamatto viharati. Yannūnāhaṃ imaṃ 
yakkhaṃ saṃvejeyyan ti._
____

[quote, M.1.253]
____
Then Venerable MahāMoggallāna performed such a feat of psychic power that 
with his big toe he made the Vejayanta Palace shake and quake and tremble.

_Atha kho āyasmā mahāmoggallāno tathārūpaṃ iddhābhisaṅkhāraṃ 
abhisaṅkhāsi yathā vejayantaṃ pāsādaṃ pādaṅguṭṭhakena 
saṅkampesi sampakampesi sampavedhesi._
____

.Illustration
====
saṃvejetu

stir up an earnest attitude [to the practice]; saṃvejito, quickened
====

____
A certain bhikkhu was dwelling amongst the Kosalan people in a certain woodland 
grove. When that bhikkhu had gone for his daytime abiding, he kept thinking 
unvirtuous, spiritually unwholesome thoughts associated with the household life.

_Tena kho pana samayena so bhikkhu divāvihāragato pāpake akusale vitakke 
vitakketi gehanissite._
____

____
Then the deva inhabiting that woodland grove, being tenderly concerned for that 
bhikkhu, desiring his spiritual well-being, desiring to stir up in him an 
earnest attitude [to the practice] (_saṃvejetukāmā_), approached him and 
addressed him in verses:

_Atha kho yā tasmiṃ vanasaṇḍe adhivatthā devatā tassa bhikkhuno 
anukampikā atthakāmā taṃ bhikkhuṃ saṃvejetukāmā yena so bhikkhu 
tenupasaṅkami. Upasaṅkamitvā taṃ bhikkhuṃ gāthāhi ajjhabhāsi:_
____

____
Desiring seclusion [from sensuous pleasures and spiritually unwholesome 
factors] you entered the woods,

_Vivekakāmosi vanaṃ paviṭṭho_
____

____
Yet your mind gushes outwardly.

_atha te mano niccharatī bahiddhā_
____

____
Eliminate, man, your fondness for people;

_Jano janasmiṃ vinayassu chandaṃ_
____

____
Then you'll be truly happy, free of attachment.

_tato sukhī hohisi vītarāgo_
____

...

[quote, S.1.197]
____
Then that bhikkhu, quickened by that devata, was filled with an earnest 
attitude [to the practice].

_Atha kho so bhikkhu tāya devatāya saṃvejito saṃvegamāpādī ti._
____

.Illustration
====
saṃvegāya

earnest attitude [to the practice]
====

[quote, A.1.43]
____
There is one thing if developed and cultivated leads to an acutely earnest 
attitude [to the practice]. What one thing? Mindfulness of the body

_Ekadhammo bhikkhave bhāvito bahulīkato mahato saṃvegāya saṃvattati 
katamo ekadhammo kāyagatāsati._
____

.Illustration
====
saṃvejanīyaṃ

fill with an earnest attitude [to the practice]
====

____
There are four places [of pilgrimage] that fill one with an earnest attitude 
&#8203;[to the practice], and should be seen by a noble young man who has faith [in 
the perfection of the Perfect One's transcendent insight]

_Cattārimāni bhikkhave saddhassa kulaputtassa dassanīyāni saṃvejanīyāni 
ṭhānāni_
____

____
Where the Perfect One was born is a place [of pilgrimage] that fills one with 
an earnest attitude [to the practice], and should be seen by a noble young man 
who has faith [in the perfection of the Perfect One's transcendent insight].

_Idha tathāgato jāto ti bhikkhave saddhassa kulaputtassa dassanīyaṃ 
saṃvejanīyaṃ ṭhānaṃ_
____

____
Where the Perfect One fully awakened to unsurpassed, complete enlightenment is 
a place [of pilgrimage] that fills one with an earnest attitude [to the 
practice], and should be seen by a noble young man who has faith [in the 
perfection of the Perfect One's transcendent insight].

_Idha tathāgato anuttaraṃ sammāsambodhiṃ abhisambuddho ti bhikkhave 
saddhassa kulaputtassa dassanīyaṃ saṃvejanīyaṃ ṭhānaṃ_
____

____
Where the Perfect One set in motion the Wheel of the Teaching is a place [of 
pilgrimage] that fills one with an earnest attitude [to the practice], and 
should be seen by a noble young man who has faith [in the perfection of the 
Perfect One's transcendent insight].

_Idha tathāgato anuttaraṃ dhammacakkaṃ pavattesī ti bhikkhave saddhassa 
kulaputtassa dassanīyaṃ saṃvejanīyaṃ ṭhānaṃ_
____

[quote, D.2.140]
____
Where the Perfect One passed away to the Untroubled-without-residue is a place 
&#8203;[of pilgrimage] that fills one with an earnest attitude [to the practice], and 
should be seen by a noble young man who has faith [in the perfection of the 
Perfect One's transcendent insight].

_Idha tathāgato anupādisesāya nibbānadhātuyā parinibbuto ti bhikkhave 
saddhassa kulaputtassa dassanīyaṃ saṃvejanīyaṃ ṭhānaṃ._
____

.Illustration
====
saṃvijjati

quickened; saṃvegaṃ, earnest attitude [to its work]
====

[quote, A.2.114]
____
In this regard, one kind of noble thoroughbred horse is quickened and acquires 
an earnest attitude [to its work] as soon as it sees the shadow of the goad, 
thinking: 'What task will my trainer set for me today? What can I do to satisfy 
him?'

_Idha bhikkhave ekacco bhadro assājānīyo patodacchāyaṃ disvā 
saṃvijjati saṃvegaṃ āpajjati kiṃnu kho maṃ ajja assadammasārathī 
kāraṇaṃ kāressati kimassāhaṃ patikaromī ti._
____

.Illustration
====
saṃvijjati

quickened; saṃvegaṃ, an earnest attitude [to her work]
====

____
Just as when a daughter-in-law sees her father-in-law, she is quickened and 
acquires an earnest attitude [to her work], so too, when that bhikkhu thus 
recollects the Buddha, the Dhamma, and the community of bhikkhus, if detached 
awareness based on what is spiritually wholesome does not become established in 
him, then he is quickened because of this, and is filled with an earnest 
attitude [to the practice].

_Seyyathā pi āvuso suṇisā sasuraṃ disvā saṃvijjati saṃvegaṃ 
āpajjati evameva kho āvuso tassa ce bhikkhuno evaṃ buddhaṃ anussarato 
evaṃ dhammaṃ anussarato evaṃ saṅghaṃ anussarato upekkhā 
kusalanissitā na saṇṭhāti so tena saṃvijjati saṃvegaṃ āpajjati:_
____

[quote, M.1.186]
____
He thinks: 'It is a loss for me, not a gain; it is unfortunate for me, not 
fortunate, that when I recollect the Buddha, the teaching, and the community of 
the Blessed One's disciples in this way, detached awareness based on what is 
spiritually wholesome is not established within me.'_

_alābhā vata me na vata me lābhā dulladdhaṃ vata me na vata me 
suladdhaṃ yassa me evaṃ buddhaṃ anussarato evaṃ dhammaṃ anussarato 
evaṃ saṅghaṃ anussarato upekkhā kusalanissitā na saṇṭhātī ti._
____

.Illustration
====
saṃvego

earnest attitude [to the practice]
====

[quote, Th.v.510]
____
When I first saw the Teacher who is free of fear from any quarter, an earnest 
attitude [to the practice] arose in me, having seen the best of men .

_Yadā paṭhamamaddakkhiṃ satthāraṃ akutobhayaṃ +
Tato me ahu saṃvego passitvā purisuttamaṃ._
____

.Illustration
====
saṃvegaṃ

dismay
====

[quote, Sn.v.935]
____
Violence breeds fear. Look at people in conflict. I will tell you of my dismay, 
how it affected me.

_Attadaṇḍā bhayaṃ jātaṃ janaṃ passatha medhagaṃ +
Saṃvegaṃ kittayissāmi yathā saṃviditaṃ mayā._
____

.Illustration
====
saṃvijjanti

quickened; saṃvejanīyesu, dismaying
====

____
Few amongst beings are those quickened by situations that are dismaying.

_appakā te sattā ye saṃvejanīyesu ṭhānesu saṃvijjanti_
____

[quote, A.1.36]
____
More amongst beings are those who are not quickened by situations that are 
dismaying.

_Atha kho eteva sattā bahutarā ye saṃvejanīyesu ṭhānesu na 
saṃvijjanti._
____

____
Few amongst beings are those who when thus quickened strive properly.

_appakā te sattā ye saṃviggā yoniso padahanti._
____

[quote, A.1.36]
____
More amongst beings are those who when thus quickened do not strive properly.

_Atha kho eteva sattā bahutarā ye saṃviggā yoniso na padahanti._
____

.Illustration
====
saṃvejanīyesu ṭhānesu

situations that are dismaying; saṃviggassa, quickened
====

____
Bhikkhus, possessed of two factors, a bhikkhu lives full of physical and 
psychological pleasure in this very lifetime, and he has laid a foundation for 
the destruction of perceptually obscuring states. What are the two?

_Dvīhi bhikkhave dhammehi samannāgato bhikkhu diṭṭheva dhamme 
sukhasomanassabahulo viharati. Yoni cassa āraddhā hoti āsavānaṃ khayāya. 
Katamehi dvīhi?_
____

[quote, It.30]
____
Being quickened by situations that are dismaying. And the proper striving in 
one who is thus quickened.

_Saṃvejanīyesu ṭhānesu saṃvejanena. Saṃviggassa ca yoniso padhānena._
____

.Illustration
====
saṃviggo

dismay
====

____
As King Ajātasattu approached the mango-grove he was filled with fear, panic, 
and terror.

_Atha kho rañño māgadhassa ajātasattussa vedehiputtassa avidūre 
ambavanassa ahudeva bhayaṃ ahu chambhitattaṃ ahu lomahaṃso._
____

[quote, D.1.49-50]
____
And fearful, dismayed, and terrified, the king said to Jīvaka: 'Friend 
Jīvaka, you are not deceiving me? You are not tricking me? You are not 
delivering me up to an enemy?

_Atha kho rājā māgadho ajātasattu vedehiputto bhīto saṃviggo 
lomahaṭṭhajāto jīvakaṃ komārabhaccaṃ etadavoca kacci maṃ samma 
jīvaka na vañcesi? Kacci maṃ samma jīvaka na palambhesi? Kacci maṃ samma 
jīvaka na paccatthikānaṃ desi?._
____

Comment:

The corresponding terms are:

- _bhayaṃ chambhitattaṃ lomahaṃso_

_• bhīto saṃviggo lomahaṭṭhajāto_

_Saṃviggo_ corresponds to _chambhitattaṃ._

.Illustration
====
saṃviggaṃ

quickened
====

____
Then Venerable MahāMoggallāna, knowing that Sakka, Lord of the Devas, was 
quickened and terrified, asked him:

_Atha kho āyasmā mahāmoggallāno sakkaṃ devānamindaṃ saṃviggaṃ 
lomahaṭṭhajātaṃ viditvā sakkaṃ devānamindaṃ etadavoca:_
____

[quote, M.1.254]
____
'Kosiya, how did the Blessed One state to you in brief the liberation [from 
perceptually obscuring states] through the destruction of craving? It would be 
good if we, too, might get to hear that statement.'

_yathākathaṃ pana te kosiya bhagavā saṅkhittena 
taṇhāsaṅkhayavimuttiṃ abhāsi? Sādhu mayampi etissā kathāya bhāgino 
assāma savaṇāyā ti._
____

