== Sevati

=== Renderings

- _sevati_: to foster

- _sevati_: to undertake

- _sevati_: to encounter

- _sevati_: to assume

- _sevati_: to pursue

- _sevati_: to associate with

- _sevati_: to resort to

- _sevati_: to touch

- _sevati_: to make use of

- _sevati_: to live in

=== Illustrations

.Illustration
====
sevato

foster
====

____
And what assumed individuality causes spiritually unwholesome factors to 
flourish and spiritually wholesome factors to fade in one who fosters it?

_Kathaṃrūpaṃ bhante attabhāvapaṭilābhaṃ sevato akusalā dhammā 
abhivaḍḍhanti kusalā dhammā parihāyanti_
____

• If, bhante, an assumed individuality that is hostile is brought into being, 
unconducive to inner perfection, spiritually unwholesome factors flourish and 
spiritually wholesome factors fade in him. +
_savyāpajjhaṃ bhante attabhāvapaṭilābhaṃ abhinibbattayato 
apariniṭṭhitabhāvāya akusalā dhammā abhivaḍḍhanti kusalā dhammā 
parihāyanti_ (M.3.52).

.Illustration
====
sevato

undertake
====

[quote, M.3.54]
____
Undertaking what kind of bodily conduct, do spiritually unwholesome factors 
flourish and spiritually wholesome factors fade?

_Kathaṃrūpaṃ sāriputta kāyasamācāraṃ sevato akusalā dhammā 
abhivaḍḍhanti kusalā dhammā parihāyanti._
____

.Illustration
====
sevitabbaṃ

undertake
====

____
If one wishes to protect oneself, one should undertake the basic practice of 
mindfulness.

_Attānaṃ bhikkhave rakkhissāmī ti satipaṭṭhānaṃ sevitabbaṃ._
____

[quote, S.5.169]
____
If one wishes to protect others, one should undertake the basic practice of 
mindfulness.

_Paraṃ rakkhissāmī ti satipaṭṭhānaṃ sevitabbaṃ._
____

.Illustration
====
sevati

undertake
====

[quote, M.3.221]
____
There are three opportunities for mindfulness that a Noble One undertakes, 
undertaking which a Noble One is a teacher fit to instruct a group.

_Tayo satipaṭṭhānā yadariyo sevati yadariyo sevamāno satthā 
gaṇamanusāsitumarahati ti._
____

.Illustration
====
sevato

encounter
====

[quote, S.4.76]
____
He mindfully conducts himself in such a way that when knowing a mentally known 
object or encountering a sense impression [within himself], [attachment] is 
exhausted not built up.

_Yathāssa vijānato dhammaṃ sevato vāpi vedanaṃ +
Khīyati no pacīyati evaṃ so caratī sato._
____

.Illustration
====
sevato

assuming
====

____
Assuming what attitude do spiritually unwholesome factors flourish and 
spiritually wholesome factors fade?

_kathaṃrūpaṃ bhante saññāpaṭilābhaṃ sevato akusalā dhammā 
abhivaḍḍhanti kusalā dhammā parihāyanti_
____

In this regard, some person is

____
greedy and abides with a greedy attitude

_idha bhante ekacco abhijjhālu hoti abhijjhāsahagatāya saññāya viharati_
____

____
unbenevolent and abides with an unbenevolent attitude

_vyāpādavā hoti vyāpādasahagatāya saññāya viharati_
____

[quote, M.3.51]
____
malicious and abides with a malicious attitude.

_vihesavā hoti vihesāsahagatāya saññāya viharati._
____

.Illustration
====
sevitabbaṃ

pursue
====

[quote, D.2.281]
____
Lord of the Devas, I declare that visible objects known via the visual sense 
are of two kinds: the kind to be pursued, and the kind to be avoided.

_Cakkhuviññeyyaṃ rūpampāhaṃ devānaminda duvidhena vadāmi sevitabbampi 
asevitabbampī ti._
____

.Illustration
====
sevitabbaṃ

pursue
====

[quote, M.3.56]
____
'Bhante, whatever object perceived by the eye, if its pursuit leads to the 
increase of spiritually unwholesome factors and the decrease of spiritually 
wholesome factors, that is not to be pursued.

_Yathārūpaṃ bhante cakkhuviññeyyaṃ rūpaṃ sevato akusalā dhammā 
abhivaḍḍhanti kusalā dhammā parihāyantī ti evarūpaṃ 
cakkhuviññeyyaṃ rūpaṃ na sevitabbaṃ._
____

.Illustration
====
sevitabbo

associated with
====

[quote, A.1.126-7]
____
Therefore this kind of person should be passively observed, not associated 
with, followed, and honoured'

_tasmā evarūpo puggalo ajjhupekkhitabbo na sevitabbo na bhajitabbo na 
payirupāsitabbo._
____

.Illustration
====
sevitabbaṃ

associate with
====

[quote, M.3.59]
____
Bhante, such persons when associated with that cause spiritually unwholesome 
factors to flourish and spiritually wholesome factors to fade should not be 
associated with. But such persons when associated with that cause spiritually 
unwholesome factors to fade and spiritually wholesome factors to flourish 
should be associated with.

_Yathārūpaṃ bhante puggalaṃ sevato akusalā dhammā abhivaḍḍhanti 
kusalā dhammā parihāyanti evarūpaṃ puggalaṃ na sevitabbaṃ. 
Yathārūpañca kho bhante puggalaṃ sevato akusalā dhammā parihāyanti 
kusalā dhammā abhivaḍḍhanti. Evarūpaṃ puggalaṃ sevitabbaṃ._
____

.Illustration
====
sevato

resort to
====

[quote, Sn.v.963]
____
Resorting to lonely abodes.

_rittāsanaṃ sayanaṃ sevato._
____

.Illustration
====
sevitā

resorted to
====

[quote, Th.v.1065]
____
The mountains are resorted to by seers.

_nagā isibhi sevitā._
____

.Illustration
====
sevitaṃ

touched
====

[quote, Thī.v.379]
____
Just as a blue lotus in full blossom arisen from the water is untouched by men, 
likewise you, O practitioner of the religious life, will reach old age with 
your limbs untouched by men.

_Uppalaṃ v'udakā samuggataṃ suphullam amanussa sevitaṃ +
Evaṃ tuvaṃ brahmacārinī sakesu aṅgesu jaraṃ gamissasi._
____

.Illustration
====
sevitabbaṃ

make use of
====

[quote, M.3.59]
____
Whatever kind of robe when made use of spiritually unwholesome factors flourish 
and spiritually wholesome factors fade, such robes should not be made use of. 
Whatever kind of robe when made use of spiritually unwholesome factors fade and 
spiritually wholesome factors flourish, such robes should be made use of.

_Yathārūpaṃ bhante cīvaraṃ sevato akusalā dhammā abhivaḍḍhanti. 
Kusalā dhammā parihāyanti. Evarūpaṃ cīvaraṃ na sevitabbaṃ. 
Yathārūpañca kho bhante cīvaraṃ sevato akusalā dhammā parihāyanti 
kusalā dhammā abhivaḍḍhanti. Evarūpaṃ cīvaraṃ sevitabbaṃ._
____

.Illustration
====
sevitabbaṃ

lived in
====

[quote, M.3.59]
____
Whatever country when lived in spiritually unwholesome factors flourish and 
spiritually wholesome factors fade, such a country should not be lived in. 
Whatever country when lived in spiritually unwholesome factors fade and 
spiritually wholesome factors flourish, such a country should be lived in.

_Yathārūpaṃ bhante janapadaṃ sevato akusalā dhammā abhivaḍḍhanti. 
Kusalā dhammā parihāyanti. Evarūpaṃ janapadaṃ na sevitabbaṃ. 
Yathārūpañca kho bhante janapadaṃ sevato akusalā dhammā parihāyanti 
kusalā dhammā abhivaḍḍhanti. Evarūpaṃ janapadaṃ sevitabbaṃ._
____

