== Sottiya

=== Renderings

- _sottiya_: fully versed in Vedic scriptural knowledge

- _sottiya_: fully versed in profound knowledge

=== Introduction

==== Etymologically: hearing

_Sottiyo_ is linked to Vedic _śrotas_, 'hearing.'

==== Brahmans: academic mastery

For Brahmanists and students, _sottiyo_ meant academic mastery of the three 
Vedas:

[quote, Th.v.1170-1]
____
Fully versed in Vedic scriptural knowledge, perfect in Vedic scriptural 
knowledge,

_Sottiyo vedasampanno._
____

==== Buddhists: arahantship

For Buddhists _sottiyo_ implies arahantship: 'fully versed in profound 
knowledge,' which is defined in different ways. For example:

[quote, Sn.v.534]
____
One who has heard and fully understood the whole teaching... they call him 
fully versed in profound knowledge.

_Sutvā sabbadhammaṃ abhiññāya loke... sottiyo ti._
____

For further definitions, see Illustrations.

==== Teaching purposes: flow

For teaching purposes the Buddha sometimes linked _sottiyo_ to _srotas_, stream 
or flow, the root of the word 'rinsed.' For example:

[quote, A.4.145]
____
Through the rinsing away of seven things a bhikkhu is fully versed in profound 
knowledge.

_sattannaṃ bhikkhave dhammānaṃ nissutattā sottiyo hoti._
____

=== Illustrations

.Illustration
====
sottiyo

fully versed in profound knowledge
====

____
Formerly I was Brahmā's offspring, now I am a Brahman indeed,

_Brahmabandhu pure āsiṃ so idānimhi brāhmaṇo_
____

[quote, Thī.v.290]
____
A master of the three final knowledges, fully versed in profound knowledge, one 
who is blessed with profound knowledge, spiritually cleansed.

_Tevijjo sottiyo camhi vedagū camhi nahātako ti._
____

.Illustration
====
sottiyo

fully versed in profound knowledge
====

____
In what way is a bhikkhu one fully versed in profound knowledge?

_Kathañca bhikkhave bhikkhu sottiyo hoti?_
____

[quote, M.1.280]
____
Unvirtuous, spiritually unwholesome factors that are defiling, and which lead 
to renewed states of individual existence, suffering, unpleasant karmic 
consequences, and future birth, old age, and death are rinsed away from him

_Nissutāssa honti pāpakā akusalā dhammā saṅkilesikā ponobhavikā 
sadarā dukkhavipākā āyatiṃ jātijarāmaraṇīyā._
____

.Illustration
====
sottiyo

fully versed in profound knowledge
====

____
Through the rinsing away of seven things a bhikkhu is fully versed in profound 
knowledge.

_sattannaṃ bhikkhave dhammānaṃ nissutattā sottiyo hoti_
____

1. the view of personal identity is rinsed away from him.
+
****
_sakkāyadiṭṭhi nissutā hoti_
****

2. doubt [about the significance of the teaching] is rinsed away from him.
+
****
_vicikicchā nissutā hoti_
****

3. adherence to observances and practices is rinsed away from him.
+
****
_sīlabbataparāmāso nissuto hoti_
****

4. attachment is rinsed away from him.
+
****
_rāgo nissuto hoti_
****

5. hatred is rinsed away from him.
+
****
_doso nissuto hoti_
****

6. undiscernment of reality is rinsed away from him.
+
****
_moho nissuto hoti_
****

7. self-centredness is rinsed away from him.
+
****
_māno nissuto hoti_ (A.4.145).
****

.Illustration
====
sottiyo

fully versed in Vedic scriptural knowledge
====

____
Even if one obtained a hundred lifetimes repeatedly amongst human beings, all 
of them as a brahman, and was fully versed in Vedic scriptural knowledge, 
perfect in Vedic scriptural knowledge,

_Yo ca jātisataṃ gacche sabbā brāhmaṇajātiyo +
Sottiyo vedasampanno manussesu punappunaṃ._
____

[quote, Th.v.1170-1]
____
... And was a scholar [of the sacred texts], a master of the three Vedas, one 
would not deserve a fraction of the respect that is due [to Venerable 
MahāKassapa].

_Ajjhāyako pi ce assa tiṇṇaṃ vedānaṃ pāragū +
Etassa vandanāyetaṃ kalaṃ nāgghati soḷasiṃ._
____

