== Subha

=== Renderings

- _subha_: loveliness

- _subha_: lovely objects

- _subha_: exquisite

- _subha_: the Exquisite

- _asubha_: unloveliness

- _asubha_: unlovely

- _subhāsubhaṃ_: fair and foul

=== Introduction

==== The Exquisite means the Imperturbable

We will show in 8 steps that the Exquisite means fourth jhāna.

1. Meditation on [unlimited, all-encompassing] goodwill leads to the Exquisite:

[quote, S.5.119]
____
Bhikkhus, the liberation [from perceptually obscuring states] through 
&#8203;[unlimited, all-encompassing] goodwill has the Exquisite as its culmination, I 
declare, for a wise bhikkhu here who has not penetrated to a superior 
liberation.

_Subhaparamāhaṃ bhikkhave mettā cetovimuttiṃ vadāmi idha paññassa 
bhikkhuno uttariṃ vimuttiṃ appaṭivijjhato._
____

2. Having a mind that is immeasurable, unlimited, and well developed leads to 
the Imperturbable:

[quote, M.2.262]
____
How about if I, by transcending the world [of sensuous pleasure] with resolve, 
were to abide with an awareness that was abundant and enlarged (_vipulena 
mahaggatena cetasā_)? Having done so, unvirtuous, spiritually unwholesome 
mental states such as greed, ill will, and aggressiveness would not exist. With 
their abandonment, my mind would become immeasurable, unlimited, and well 
developed (_aparittañca me cittaṃ bhavissati appamāṇaṃ subhāvitan_). 
Applying himself and frequently abiding in this way, his mind becomes serene 
through that practice of spiritual development. When there is serenity, he 
either attains the Imperturbable now, or else he is intent upon discernment.

_Yannūnāhaṃ vipulena mahaggatena cetasā vihareyyaṃ abhibhuyya lokaṃ 
adhiṭṭhāya manasā. Vipulena hi me mahaggatena cetasā viharato abhibhuyya 
lokaṃ adhiṭṭhāya manasā. Ye pāpakā akusalā manasā abhijjhāpi 
sārambhāpi te na bhavissanti. Tesaṃ pahānā aparittañca me cittaṃ 
bhavissati appamāṇaṃ subhāvitan ti. Tassa evaṃ paṭipannassa 
tabbahulavihārino āyatane cittaṃ pasīdati. Sampasāde sati etarahi vā 
āneñjaṃ samāpajjati paññāya vā adhimuccati._
____

3. _Aniñjita_ includes fourth jhāna:

[quote, M.1.454-5]
____
Fourth jhāna I declare, is within the not-unstable.

_catutthaṃ jhānaṃ... aniñjitasmiṃ vadāmi._
____

Other jhānas are within the unstable:

[quote, M.1.454]
____
He enters and abides in third jhāna. That, I declare, is within the unstable.

_tatiyaṃ jhānaṃ upasampajja viharati. Idampi kho ahaṃ udāyi 
iñjitasmiṃ vadāmi._
____

4. _Āneñjaṃ_ and _aniñjita_ are synonyms. For example, Sn.v.750-1 says:

- Whatever suffering arises, all of it arises dependent on spiritual 
instability (_iñjitapaccayā_)... Therefore having relinquished spiritual 
instability (_ejaṃ vossajja_), imperturbable (_anejo_) and free of grasping, 
the bhikkhu should mindfully fulfil the ideals of religious asceticism 
(Sn.v.750-1).

5. Therefore, fourth jhāna is part of the Imperturbable.

6. The immaterial states are also part of the Imperturbable:

[quote, A.2.184]
____
And how is a bhikkhu one who has attained the Imperturbable? In this regard, by 
completely transcending refined material states of awareness, with the 
vanishing of states of refined awareness involving physical sensation, not 
focusing upon states of refined awareness involving the external senses, a 
bhikkhu enters and abides in the state of awareness of boundless space where 
one perceives that space is boundless... By completely transcending the state 
of awareness of nonexistence, a bhikkhu enters and abides in the state of 
awareness neither having nor lacking perception.

_Kathaṃ ca bhikkhave bhikkhu āneñjappatto hoti? Idha bhikkhave bhikkhu 
sabbaso rūpasaññānaṃ samatikkamā paṭighasaññānaṃ atthaṅgamā 
nānattasaññānaṃ amanasikārā ananto ākāsoti ākāsānañcāyatanaṃ 
upasampajja viharati... Sabbaso ākiñcaññāyatanaṃ samatikkamma 
nevasaññānāsaññāyatanaṃ upasampajja viharati. Evaṃ kho bhikkhave 
bhikkhu āneñjappatto hoti._
____

However, these immaterial states cannot be called the Exquisite, because in the 
list of the eight states of refined awareness the Exquisite is clearly 
separated from the immaterial states. For example, the third and fourth states 
are:

____
One is focused exclusively on the Exquisite. This is the third state of refined 
awareness

_Subhanteva adhimutto hoti. Ayaṃ tatiyo vimokkho._
____

[quote, D.2.71; M.2.13; A.4.307]
____
By completely transcending refined material states of awareness, with the 
vanishing of states of refined awareness involving physical sensation, not 
focusing upon states of refined awareness involving the external senses, one 
enters and abides in the state of awareness of boundless space where one 
perceives that space is boundless. This is the fourth state of refined awareness

_Sabbaso rūpasaññānaṃ samatikkamā paṭighasaññānaṃ atthaṅgamā 
nānattasaññānaṃ amanasikārā ananto ākāso ti ākāsanañcāyatanaṃ 
upasampajja viharati. Ayaṃ catuttho vimokkho.._
____

7. In developing _mettā_, one develops a mind that is abundant, exalted and 
measureless (_cetasā vipulena mahaggatena appamāṇena_):

[quote, M.1.126]
____
We shall abide pervading the whole world [of beings] with a mind of [unlimited, 
all-encompassing] goodwill, vast, exalted, unlimited, free of unfriendliness 
and hostility.

_sabbāvantaṃ lokaṃ mettāsahagatena cetasā vipulena mahaggatena 
appamāṇena averena avyāpajjhena pharitvā viharissāmāti._
____

8. According to point 2), the qualities of the mind that are aroused in 
practising _mettā_ would lead the meditator to the Imperturbable i.e. to 
fourth jhāna. Therefore the Exquisite equals fourth jhāna because [unlimited, 
all-encompassing] goodwill has the Exquisite as its culmination, says point 1).

==== The divine abidings, the Exquisite, and the immaterial states

The divine abidings have the following points of culmination:

[quote, S.5.119]
____
_Mettā_: the liberation [from perceptually obscuring states] through 
&#8203;[unlimited, all-encompassing] goodwill has the Exquisite as its culmination.

_subhaparamāhaṃ bhikkhave mettā cetovimuttiṃ vadāmi._
____

[quote, S.5.120]
____
_Karuṇā_: the liberation [from perceptually obscuring states] through 
&#8203;[unlimited, all-encompassing] compassion has the state of awareness of 
boundless space as its culmination.

__ākāsānañcāyatanaparamāhaṃ bhikkhave karuṇā cetovimuttiṃ vadāmi._
____

[quote, S.5.120]
____
_Muditā_: the liberation [from perceptually obscuring states] through 
&#8203;[unlimited, all-encompassing] joy has the state of awareness of boundless 
mental consciousness as its culmination.

_viññāṇañcāyatanaparamāhaṃ bhikkhave muditā cetovimuttiṃ vadāmi._
____

[quote, S.5.121]
____
_Upekkhā_: the liberation [from perceptually obscuring states] through 
&#8203;[unlimited, all-encompassing] detached awareness has the state of awareness of 
nonexistence as its culmination.

__ākiñcaññāyatanaparamāhaṃ bhikkhave upekkhā cetovimuttiṃ vadāmi._
____

It neatly fits the sequence to consider the Exquisite as fourth jhāna.

=== Illustrations

.Illustration
====
subha

loveliness/ unloveliness
====

[quote, S.2.150]
____
The phenomenon of loveliness is discernable because of unloveliness.

_yāyaṃ bhikkhu subhadhātu ayaṃ dhātu asubhaṃ paṭicca paññāyati._
____

.Illustration
====
subhā

loveliness
====

[quote, M.1.88]
____
What do you think, bhikkhus? Has her former loveliness and beauty vanished and 
a wretchedness become evident?_

_Taṃ kiṃ maññatha bhikkhave yā purimā subhā vaṇṇanibhā sā 
antarahitā ādīnavo pātubhūto ti?._
____

.Illustration
====
subhaṃ

lovely objects
====

[quote, Th.v.674]
____
There are many attractive things in the world, on this wide earth. They 
distract [the mind], it seems, [by promoting] thoughts of lovely objects that 
are associated with attachment.

_Bahūni loke citrāni asmiṃ paṭhavimaṇḍale +
Mathenti maññe saṅkappaṃ subhaṃ rāgūpasaṃhitaṃ._
____

COMMENT

Norman argues that _saṅkappaṃ_ should be treated as a plural, based on the 
presence of _saṅkappā_ in verse 675. In which case, _subhaṃ 
rāgūpasaṃhitaṃ_ are also plurals.

.Illustration
====
subhaṃ

lovely
====

[quote, A.2.52]
____
To consider the unlovely to be lovely is a perversion of perception.

_Asubhe bhikkhave subhan ti saññāvipallāso._
____

.Illustration
====
asubhaṃ

unlovely
====

[quote, Thī.v.388]
____
Knowing that what is originated is unlovely, my mind cleaves to nothing at all.

_Saṅkhatamasubhan ti jāniya sabbattheva mano na limpati._
____

.Illustration
====
asubhaṃ

unloveliness
====

[quote, M.1.424]
____
Develop the meditation on the unloveliness [of the body].

_Asubhaṃ rāhula bhāvanaṃ bhāvehi._
____

COMMENT

[quote, A.5.109]
____
And what, Ānanda, is the perception of the unloveliness [of the body]? In this 
regard, Ānanda, a bhikkhu reflects that this [wretched human] body from the 
soles of the feet up, and down from the hair on the crown of the head, covered 
in skin is full of various foul things. In this [wretched human] body there are 
head-hairs... urine. Thus he abides contemplating the unloveliness of this 
&#8203;[wretched human] body.

_Katamācānanda asubhasaññā: Idhānanda bhikkhu imameva kāyaṃ uddhaṃ 
pādatalā adho kesamatthakā tacapariyantaṃ pūraṃ nānappakārassa 
asucino paccavekkhati: atthi imasmiṃ kāye kesā... muttan ti._
____

.Illustration
====
asubhaṃ

unloveliness
====

[quote, A.2.155-6]
____
He abides contemplating the unloveliness of the body

_asubhānupassī kāye viharati._
____

.Illustration
====
subhaṃ

exquisite
====

[quote, D.3.34]
____
When someone attains the state of refined awareness that is exquisite, he knows 
that it is exquisite.

_yasmiṃ samaye subhaṃ vimokkhaṃ upasampajja viharati subhantveva tasmiṃ 
samaye pajānātī ti._
____

.Illustration
====
subhaṃ

exquisite/unlovely
====

[quote, D.3.34]
____
I do not say that when one enters and abides in the state of refined awareness 
that is exquisite, one knows that everything as unlovely. But rather I say that 
when one enters and abides in the state of refined awareness that is exquisite, 
one knows that it is exquisite.

_Na kho panāhaṃ bhaggava evaṃ vadāmi: yasmiṃ samaye subhaṃ 
vimokkhaṃ upasampajja viharati sabbaṃ tasmiṃ samaye asubhanteva 
pajānātī ti. Evañca khvāhaṃ bhaggava vadāmi: yasmiṃ samaye subhaṃ 
vimokkhaṃ upasampajja viharati subhantveva tasmiṃ samaye pajānātī ti._
____

.Illustration
====
subhaṃ

the Exquisite
====

[quote, D.2.71; D.2.112; D.3.262; D.3.288; M.2.13; A.4.307]
____
One is focused exclusively on the Exquisite. This is the third state of refined 
awareness

_Subhanteva adhimutto hoti. Ayaṃ tatiyo vimokkho._
____

.Illustration
====
subho

exquisite
====

[quote, D.1.76]
____
A gem, a beryl, exquisite

_maṇi veḷuriyo subho._
____

.Illustration
====
subhaṃ

the Exquisite
====

[quote, Sn.v.910]
____
Whatever he is attached to, that [for him] is "the Exquisite," so-called. He 
calls it Purity. It is there that he sees Perfect Truth.

_Yaṃ nissito tattha subhaṃ vadāno suddhiṃvado tattha tathaddasa so._
____

.Illustration
====
subhāsubhaṃ

fair and foul
====

[quote, S.1.104]
____
For long you have wandered the round of birth and death creating fair and foul 
masquerades. Enough of all that, Maleficent One. You are defeated, Destroyer.

_Saṃsaraṃ dīghamaddhānaṃ vaṇṇaṃ katvā subhāsubhaṃ +
Alaṃ te tena pāpima nihato tvamasi antakāti._
____

