== Suñña; Suññatā

=== Renderings

- _suñña_: empty

- _suñña_: desolate

- _suñña_: void

- _suñña_: void [of personal qualities]

- _suññatā_: [the perception of][relative] voidness

- _suññatā_: the [perception of the] absence [of any abiding phenomena]

- _suññatā_: the [perception of the] absence [of personal qualities]

- _suññato phasso_: sensation that is void [of the perception of personal 
qualities]

- _asuññataṃ_: state which is not absent

=== Introduction

==== Suñña meanings

Often _suñña_ simply means 'empty', 'void', or 'desolate':

[quote, S.4.174]
____
empty village

_suññaṃ gāmaṃ._
____

[quote, S.1.180]
____
desolate forest

_suññaṃ araññaṃ._
____

[quote, M.1.483]
____
That group of non-Buddhist ascetics is void even of one who goes to heaven.

_suññaṃ aduṃ titthāyatanaṃ antamaso saggūpagenāpīti._
____

[quote, M.3.104-5]
____
He knows that 'This state of perception is void of the perceptions of village 
and man.'

_So suññamidaṃ saññāgataṃ gāmasaññāyā ti pajānāti 
suññamidaṃ saññāgataṃ manussasaññāyā ti pajānāti._
____

[quote, S.4.174]
____
Whatever house he enters is empty, deserted, and void.

_yaññadeva gharaṃ paviseyya rittakaññeva paviseyya tucchakaññeva 
paviseyya suññakaññeva paviseyya._
____

[quote, S.4.174]
____
Whatever pot he takes hold of is empty, hollow, and void

_yaññadeva bhājanaṃ parimaseyya rittakaññeva parimaseyya tucchakaññeva 
parimaseyya suññakaññeva parimaseyya._
____

[quote, S.5.164]
____
This assembly appears empty to me now that Sāriputta and Moggallāna have 
passed away to the Untroubled-without-residue.

_Api ca khvāyaṃ bhikkhave parisā suññā viya khāyati parinibbutesu 
sāriputtamoggallānesu asuññā me sā bhikkhave parisā hoti._
____

==== Suñña: void [of personal qualities]

_Suñña_ has a technical sense, meaning 'void [of personal qualities]':

____
'Void [of personal qualities] is the world [of phenomena]': on what grounds, 
bhante, is this said?

_suñño loko suñño loko ti bhante vuccati kittāvatā nu kho bhante suñño 
loko ti vuccatī ti?_
____

[quote, S.4.54]
____
'Because, Ānanda, it is void of an [absolute] Selfhood and of what could 
belong to an [absolute] Selfhood, therefore it is said that the world [of 
phenomena] is void [of personal qualities].'_

_Yasmā ca kho ānanda suññaṃ attena vā attaniyena vā tasmā suñño loko 
ti vuccati._
____

==== Suññatā: three meanings

_Suññatā_ has three meanings:

1. [the perception of][relative] voidness

2. The [perception of the] absence [of any abiding phenomena]

3. The [perception of the] absence [of personal qualities]

We illustrate these as follows:

==== 1) Suññatā: [the perception of][relative] voidness

____
In the same way, Ānanda, a bhikkhu, not focusing upon the perceptions of 
village and man, focuses undistractedly on the perception of forest. His mind 
becomes energised, serene, settled, and intent upon the perception of forest.

_evameva kho ānanda bhikkhu amanasikaritvā gāmasaññaṃ amanasikaritvā 
manussasaññaṃ araññasaññaṃ paṭicca manasikaroti ekattaṃ. Tassa 
araññasaññāya cittaṃ pakkhandati pasīdati santiṭṭhati adhimuccati._
____

____
He knows that "Whatever states of suffering there are because of the 
perceptions of village and man are absent. And there is only this amount of 
suffering, namely the undistracted concentration focused on the perception of 
forest."

_So evaṃ pajānāti ye assu darathā gāmasaññaṃ paṭicca tedha na santi 
ye assu darathā manussasaññaṃ paṭicca tedha na santi atthi cevāyaṃ 
darathamattā yadidaṃ araññasaññaṃ paṭicca ekattan ti._
____

____
He knows that "This state of perception is void of the perceptions of village 
and man. And there is just this state which is not absent, namely the 
undistracted concentration focused on the perception of forest."

_So suññamidaṃ saññāgataṃ gāmasaññāyā ti pajānāti 
suññamidaṃ saññāgataṃ manussasaññāyā ti pajānāti atthi cevidaṃ 
asuññataṃ yadidaṃ araññasaññaṃ paṭicca ekattan ti._
____

____
He regards it as void of whatever is not there. Of the remainder, he discerns: 
"That [absence] being, this [relative voidness] is."

_Iti yaṃ hi kho tattha na hoti tena taṃ suññaṃ samanupassati yaṃ pana 
tattha avasiṭṭhaṃ hoti taṃ santamidaṃ atthī ti pajānāti._
____

[quote, M.3.104]
____
This is for him the undistorted, pure realisation of [the perception of] 
&#8203;[relative] voidness according to reality.

_Evam pi'ssa esā ānanda yathābhuccā avipallatthā parisuddhā 
suññatāvakkanti bhavati._
____

==== 2) Suññatā: the [perception of the] absence [of any abiding phenomena]

[quote, M.3.111]
____
There is this abiding discovered by the Perfect One, namely to enter and abide 
in the [perception of the] absence [of any abiding phenomena] internally, by 
not focusing upon any abiding phenomenon.

_Ayaṃ kho ānanda vihāro tathāgatena abhisambuddho yadidaṃ 
sabbanimittānaṃ amanasikārā ajjhattaṃ suññataṃ upasampajja 
viharituṃ._
____

Comment:

_Nimitta_: abiding phenomenon. An 'abiding phenomenon,' is a phenomenon that is 
regarded as an actual, existing thing instead of an everchanging condition. See 
Glossary sv _Nimitta_.

==== 3) Suññatā: the [perception of the] absence [of personal qualities]

____
And what, bhante, is the liberation [from perceptually obscuring states] 
through the [perception of the] absence [of personal qualities]?

_Katamā ca bhante suññatā cetovimutti_
____

[quote, M.1.297-8]
____
In this regard a bhikkhu, gone to the wilderness, or the root of a tree, or a 
solitary abode, reflects thus: 'This is void of an [absolute] Selfhood and of 
what could belong to an [absolute] Selfhood.'

_Idha bhante bhikkhu araññagato vā rukkhamūlagato vā suññāgāragato vā 
itipaṭisaṃcikkhati suññamidaṃ attena vā attaniyena vā._
____

==== Suññatā: dividing 'internal' and 'external'

When receiving visitors, the Buddha, although unaware of any abiding phenomena 
internally, perceived abiding phenomena externally through conventional 
perception, and would therefore be able to properly communicate with visitors:

[quote, M.3.111]
____
There is this abiding discovered by the Perfect One, namely to enter and abide 
in the [perception of the] absence [of any abiding phenomena] internally, by 
not focusing upon any abiding phenomenon. And if he is abiding thus, he is 
visited by bhikkhus, bhikkhunīs, laymen, laywomen, kings and kings' ministers, 
and non-Buddhist ascetics and their disciples, then the Perfect One, with his 
mind mentally inclining, verging, and drifting towards seclusion [from sensuous 
pleasures and spiritually unwholesome factors], psychologically withdrawn [from 
sensuous pleasures and spiritually unwholesome factors], taking delight in the 
practice of unsensuousness, is one whose words are exclusively connected with 
religious inspiration.

_Ayaṃ kho ānanda vihāro tathāgatena abhisambuddho yadidaṃ 
sabbanimittānaṃ amanasikārā ajjhattaṃ suññataṃ upasampajja 
viharituṃ. Tatra ce ānanda tathāgataṃ iminā vihārena viharantaṃ 
bhavanti upasaṅkamitāro bhikkhū bhikkhuniyo upāsakā upāsikāyo rājāno 
rājamahāmattā titthiyā titthiyasāvakā. Tatrānanda tathāgato 
vivekaninneneva cittena vivekapoṇena vivekapabbhārena vūpakaṭṭhena 
nekkhammābhiratena vyantībhūtena sabbaso āsavaṭṭhāniyehi dhammehi 
aññadatthu uyyojanikapaṭisaṃyuttaṃyeva kathaṃ kattā hoti._
____

==== Suññato phasso

_Suññato phasso_ occurs twice in the scriptures, and only in this passage:

____
When a bhikkhu has emerged from the attainment of the ending of perception and 
sense impression, sensations of three types affect him:

_Saññāvedayitanirodhasamāpattiyā vuṭṭhitaṃ kho āvuso visākha 
bhikkhuṃ tayo phassā phusanti:_
____

1. sensation that is void [of the perception of personal qualities]
+
****
_suññato phasso_
****

2. sensation that is void of the perception of abiding phenomena
+
****
_animitto phasso_
****

3. sensation that is void of aspiration
+
****
_appaṇihito phasso ti_ (M.1.302).
****

=== Illustrations

.Illustration
====
suññatassa

the [perception of the] absence [of personal qualities]
====

[quote, Thī.v.46]
____
I can attain both states: the [perception of the] absence [of personal 
qualities], and the [inward collectedness that is focused upon the] unabiding 
&#8203;[phenomena], whichever I wish.

_Suññatassānimittassa lābhinīhaṃ yadicchakaṃ._
____

.Illustration
====
suññatā

the [perception of the] absence [of any abiding phenomena]
====

[quote, A.1.72]
____
Those discourses spoken by the Perfect One that are profound, profound in 
meaning, transcendental, connected with the [perception of the] absence [of any 
abiding phenomena]

_ye te suttantā tathāgatabhāsitā gambhīrā gambhīratthā lokuttarā 
suññatā paṭisaṃyuttā._
____

.Illustration
====
suññato

void [of personal qualities]
====

[quote, M.1.435]
____
He regards whatever phenomena there that are connected with the five 
aggregates, as unlasting, as existentially void, as an illness, as a carbuncle, 
as a [piercing] arrow, as suffering, as an affliction, as alien, as destined to 
decay, as void [of personal qualities], as void of personal qualities.

_so yadeva tattha hoti rūpagataṃ vedanāgataṃ saññāgataṃ 
saṅkhāragataṃ viññāṇagataṃ te dhamme aniccato dukkhato rogato 
gaṇḍato sallato aghato ābādhato parato palokato suññato anattato 
samanupassati._
____

.Illustration
====
suññato

void [of personal qualities]
====

[quote, Sn.v.1119]
____
Being ever mindful, Mogharāja, view the world [of phenomena] as void [of 
personal qualities]. Having eradicated the notion of there being an [absolute] 
Selfhood, thus would one overcome death.

_Suññato lokaṃ avekkhassu mogharāja sadā sato +
Attānudiṭṭhiṃ ūhacca evaṃ maccutaro siyā._
____

.Illustration
====
suññaṃ

empty; suñña, void [of personal qualities]
====

• He would see an empty village. Whatever house he enters is empty, deserted, 
and void. Whatever pot he takes hold of is empty, hollow, and void. +
_So passeyya suññaṃ gāmaṃ: yaññadeva gharaṃ paviseyya rittakaññeva 
paviseyya tucchakaññeva paviseyya suññakaññeva paviseyya yaññadeva 
bhājanaṃ parimaseyya rittakaññeva parimaseyya tucchakaññeva parimaseyya 
suññakaññeva parimaseyya._

____
'The empty village' represents the six senses.

_Suñño gāmoti kho bhikkhave channetaṃ ajjhattikānaṃ āyatanānaṃ 
adhivacanaṃ_
____

[quote, S.4.174]
____
If a wise, capable, intelligent person examines them by way of the eye... by 
way of the mind, they appear to be empty, hollow, and void [of personal 
qualities].

_Cakkhuto... Manato cepi naṃ bhikkhave paṇḍito vyatto medhāvi 
upaparikkhati rittakaññeva khāyati tucchakaññeva khāyati suññakaññeva 
khāyati._
____

.Illustration
====
suññam

void; asuññataṃ, state which is not absent; suññatā, voidness
====

____
He knows that "This state of perception is void of the perceptions of village 
and man. And there is just this state which is not absent, namely the 
undistracted concentration focused on the perception of forest."

_So suññamidaṃ saññāgataṃ gāmasaññāyā ti pajānāti 
suññamidaṃ saññāgataṃ manussasaññāyā ti pajānāti atthi cevidaṃ 
asuññataṃ yadidaṃ araññasaññaṃ paṭicca ekattan ti._
____

____
He regards it as void of whatever is not there. Of the remainder, he discerns: 
"That [absence] being, this [relative voidness] is."

_Iti yaṃ hi kho tattha na hoti tena taṃ suññaṃ samanupassati yaṃ pana 
tattha avasiṭṭhaṃ hoti taṃ santamidaṃ atthī ti pajānāti._
____

[quote, M.3.104-5]
____
This is for him the undistorted, pure realisation of [the perception of] 
&#8203;[relative] voidness according to reality..

_Evam pi'ssa esā ānanda yathābhuccā avipallatthā parisuddhā 
suññatāvakkanti bhavati._
____

