== Suññāgāra

=== Renderings

- _suññāgāra_: solitary abode

- _suññāgāra_: solitude

=== Illustrations

.Illustration
====
suññāgārāni

solitary abodes
====

[quote, S.4.368-373]
____
These are the roots of trees. These are the solitary abodes. Meditate, 
bhikkhus. Do not be negligently applied [to the practice].

_Etāni bhikkhave rukkhamūlāni etāni suññāgārāni jhāyatha bhikkhave 
mā pamādattha._
____

.Illustration
====
suññāgāra

a solitary abode
====

[quote, M.1.297-8]
____
A bhikkhu, gone to the wilderness, or the root of a tree, or a solitary abode.

_bhikkhu araññagato vā rukkhamūlagato vā suññāgāragato vā._
____

.Illustration
====
suññāgāre

solitude
====

[quote, Vin.1.97]
____
When a bhikkhu is ordained he should not wrongfully claim a superhuman 
attainment, even wrongfully claiming "I delight in solitude"

_antamaso suññāgāre abhiramāmī ti._
____

.Illustration
====
suññāgāra

solitude
====

Nigrodha the ascetic said:

____
The ascetic Gotama's wisdom is struck down by solitude.

_Suññāgārahatā samaṇassa gotamassa paññā_
____

____
He is out of touch with society.

_aparisāvacaro samaṇo gotamo_
____

[quote, D.3.38]
____
He is incapable of conversation.

_nālaṃ sallāpāya._
____

