== Sāvajja; Anavajja

=== Renderings

- _anavajja_: blamelessness

- _anavajja_: blameless

- _sāvajjā_: blameworthy

=== Illustrations

.Illustration
====
anavajja

blamelessness, blameless
====

[quote, A.2.69-70]
____
And what is the pleasure of blamelessness? In this regard a noble disciple is 
endowed with blameless bodily conduct, blameless verbal conduct, and blameless 
mental conduct.

_Katamañca gahapati anavajjasukhaṃ? Idha gahapati ariyasāvako anavajjena 
kāyakammena samannāgato hoti anavajjena vacīkammena samannāgato hoti 
anavajjena manokammena samannāgato hoti._
____

.Illustration
====
sāvajjā

blameworthy
====

[quote, M.1.119]
____
That bhikkhu should examine the danger of those thoughts, that they are 
spiritually unwholesome, blameworthy, and have an unpleasant karmic 
consequences.

_tena bhikkhave bhikkhunā tesaṃ vitakkānaṃ ādīnavo upaparikkhitabbo 
itipime vitakkā akusalā itipime vitakkā sāvajjā itipime vitakkā 
dukkhavipākāti._
____

.Illustration
====
sāvajjānavajjā

blameworthy blameless
====

[quote, S.5.104]
____
There are spiritually wholesome and spiritually unwholesome factors; 
blameworthy and blameless factors; inferior and superior factors; and inwardly 
dark and bright factors with their correlative combinations.

_Atthi bhikkhave kusalākusalā dhammā sāvajjānavajjā dhammā 
hīnappaṇītā dhammā kaṇhasukkasappaṭibhāgā dhammā._
____

.Illustration
====
sāvajjā

blameworthy
====

____
Kālāmas, if you yourselves should consider:

_Yadā tumhe kālāmā attanāva jāneyyātha_
____

____
... "These teachings are unwholesome;

_ime dhammā akusalā_
____

____
... these teachings are blameworthy;

_ime dhammā sāvajjā_
____

[quote, A.1.189]
____
... you should abandon them.

_atha tumhe kālāmā pajaheyyātha._
____

.Illustration
====
sāvajjā

blameworthy; anavajjaṃ, blameless
====

[quote, A.1.263]
____
Conduct produced from, born of, due to, originated by greed is spiritually 
unwholesome and blameworthy. It has unpleasant karmic consequences.

_Yaṃ bhikkhave lobhapakataṃ kammaṃ lobhajaṃ lobhanidānaṃ 
lobhasamudayaṃ. Taṃ kammaṃ akusalaṃ taṃ kammaṃ sāvajjaṃ taṃ 
kammaṃ dukkhavipākaṃ._
____

[quote, A.1.263]
____
Conduct produced from, born of, due to, originated by non-greed is spiritually 
wholesome and blameless. It has pleasant karmic consequences.

_Yaṃ bhikkhave alobhapakataṃ kammaṃ alobhajaṃ alobhanidānaṃ 
alobhasamudayaṃ taṃ kammaṃ kusalaṃ taṃ kammaṃ anavajjaṃ taṃ 
kammaṃ sukhavipākaṃ._
____

.Illustration
====
sāvajjaṃ

blameworthy
====

• When pacing back and forth he brings about the death of many small beings. 
What karmic consequence does the Nigaṇṭha Nātaputta describe for him? +
_so abhikkamanto paṭikkamanto bahū khuddake pāṇe saṅghātaṃ 
āpādeti. Imassa pana gahapati nigaṇṭho nātaputto kaṃ vipākaṃ 
paññāpetī ti_.

• The Nigaṇṭha Nātaputta does not declare what is unintentional as 
greatly blameworthy. +
_Asañcetanikaṃ bhante nigaṇṭho nātaputto no mahāsāvajjaṃ 
paññāpetī ti._

• But what if one does it intentionally? +
Sace pana gahapati cetetī ti.

• Then it is greatly blameworthy. +
_Mahāsāvajjaṃ bhante hotī ti_ (M.1.377).

.Illustration
====
sāvajjo

blameworthy
====

____
Attachment is moderately blameworthy, and slow to fade away.

_rāgo kho āvuso appasāvajjo dandhavirāgī_
____

____
Hatred is very blameworthy, and quick to fade away.

_doso mahāsāvajjo khippavirāgī_
____

[quote, A.1.200]
____
Undiscernment of reality is very blameworthy, and slow to fade away.

_moho mahāsāvajjo dandhavirāgī ti._
____

.Illustration
====
anavajjaṃ

blameless
====

Rag-robes, food gathered on almsround, an abode at the root of a tree, and 
concentrated urine are:

[quote, A.2.27]
____
Paltry, easily gotten, and blameless.

_appañca sulabhañca tañca anavajjaṃ._
____

