== Sītibhūta

=== Renderings

- _sītibhūta_: freed from inward distress

=== Introduction

==== Summary

_Sītibhūta_ is linked to freedom from _taṇhā_, _rāga, dosa, moha,_ and 
_āsava,_ and therefore to freedom from anguish (_pariḷāha_) and inward 
torment (_pariḍayhati_). Although it is commonly rendered 'become cool,' and 
PED calls it 'tranquillized,' _sītibhūta_ is better represented by the term 
'freed from inward distress.'

==== Freedom from taṇhā, suffering, and burning

_Sītibhūta_ is linked to freedom from _taṇhā_:

[quote, Th.v.298]
____
Having removed [the arrow of] craving together with its origin, I am freed from 
inward distress. I have realised the Untroubled.

_samūlaṃ taṇhaṃ abbuyha sītibhūtosmi nibbuto ti._
____

It is therefore linked to freedom from sufferings, torments, and anguishes, 
because they are the products of _taṇhā_:

[quote, M.3.287]
____
Craving... grows. One's physical and psychological sufferings, torments, and 
anguishes increase.

_Taṇhā... pavaḍḍhati. Tassa kāyikāpi darathā pavaḍḍhanti 
cetasikāpi darathā pavaḍḍhanti kayikāpi santāpā pavaḍḍhanti 
cetasikāpi santāpā pavaḍḍhanti kāyikāpi pariḷāhā pavaḍḍhanti 
cetasikāpi pariḷāhā pavaḍḍhanti._
____

==== Freedom from rāga, dosa, moha, trouble, anguish, and burning

_Sītibhūta_ is linked to freedom from _rāga, dosa,_ and _moha_.

[quote, Th.v.79]
____
All my attachment is abandoned, my hatred is abolished, my undiscernment of 
reality is done away with. I am freed from inward distress. I have realised the 
Untroubled.

_Sabbo rāgo pahīno me sabbo doso samūhato +
Sabbo me vigato moho sītibhūtosmi nibbuto ti._
____

It is therefore linked to freedom from anguish, because that is the product of 
_rāga, dosa_ and _moha_:

[quote, A.1.137]
____
Would there not arise in that householder or householder's son anguish of body 
or mind that are born of attachment... hatred... undiscernment of reality, so 
that, being tormented by the anguish born of attachment... hatred... 
undiscernment of reality, he would sleep badly?

_Taṃ kimmaññasi kumāra? Api nu tassa gahapatissa vā gahapatiputtassa vā 
uppajjeyyuṃ rāgajā pariḷāhā kāyikā vā cetasikā vā yehi so 
rāgajehi pariḷāhehi pariḍayhamāno dukkhaṃ sayeyyāti?._
____

==== Freedom from āsava, suffering and burning

_Sītibhūta_ is linked to freedom from _āsavas_:

[quote, Thī.v.76]
____
destroyed all perceptually obscuring states. I am freed from inward distress. I 
have realised the Untroubled.

_khepetvā āsave sabbe sītibhūtāmhi nibbutā ti._
____

It is therefore linked to freedom from distress and anguish, because that is 
the quality of the _āsavas_.

[quote, A.3.245]
____
Vexatious and anguishing perceptually obscuring states

__āsavā vighātapariḷāhā._
____

==== Conclusion

We have shown that _sītibhūta_ is linked to freedom from

- sufferings, torments, and anguishes

- inward trouble

- anguish of body or mind

- distress and anguish

It is thus well-represented by the term 'freed from inward distress.'

=== Illustrations

.Illustration
====
sītibhūtāsi

freed from inward distress
====

[quote, Thī.v.16]
____
Your attachment has completely subsided. You are freed from inward distress. 
You have realised the Untroubled.

_Upasanto hi te rāgo sītibhūtāsi nibbutā ti._
____

.Illustration
====
sītibhūtāmhi

freed from inward distress
====

[quote, Thī.v.34]
____
As I abide in this way, all my attachment is abolished. My [sensuous] passion 
is annihilated. I am freed from inward distress. I have realised the 
Untroubled._

_Evaṃ viharamānāya sabbo rāgo samūhato +
Pariḷāho samucchinno sītibhūtāmhi nibbutā ti._
____

.Illustration
====
sītibhūto

freed from inward distress
====

[quote, Th.v.416]
____
Being rid of attachment to sense impression await the inevitable hour, being 
even in this world freed from inward distress.

_So vedayitāsu vītarāgo kālaṃ kaṅkha idheva sītibhūto ti._
____

