== Tatheva

=== Renderings

- _tatheva_: right

- _tatheva_: true

- _tatheva_: valid

- _tatheva_: incontrovertible

- _tatheva_: likewise

- _tatheva_: like

- _tatheva_: as they are

- _tatheva_: so

=== Illustrations

.Illustration
====
tatheva

right
====

[quote, Sn.v.374]
____
'One who has destroyed all states of attachment, having realised the 
&#8203;[Untroubled] State, having understood the teaching, having clearly seen the 
abandonment of all perceptually obscuring states: he would properly fulfil the 
ideals of religious asceticism in the world.

_Aññāya padaṃ samecca dhammaṃ vivaṭaṃ disvāna pahānamāsavānaṃ +
Sabbupadhīnaṃ parikkhayāno sammā so loke paribbajeyya._
____

[quote, Sn.v.375]
____
'This is surely right, Blessed One. An inwardly tamed bhikkhu who abides in 
this way and who has gone beyond everything conducive to psychological bondage, 
would properly fulfil the ideals of religious asceticism in the world.'

_Addhā hi bhagavā tatheva etaṃ yo so evaṃvihārī danto bhikkhu +
Sabbasaṃyojaniye ca vītivatto sammā so loke paribbajeyyā ti._
____

.Illustration
====
tatheva

right
====

[quote, It.121-2; A.2.24]
____
From the day of his unsurpassed enlightenment till the day of his passing away 
to the Untroubled-without-residue, whatever the Perfect One has said, spoken, 
and explained in that interval is completely right, not mistaken.

_Yañca bhikkhave rattiṃ tathāgato anuttaraṃ sammāsambodhiṃ 
abhisambujjhati yañca rattiṃ anupādisesāya nibbānadhātuyā 
parinibbāyati yaṃ etasmiṃ antare bhāsati lapati niddisati sabbaṃ taṃ 
tatheva hoti. No aññathā._
____

.Illustration
====
tatheva

valid
====

Those bhikkhus who rightly declared their arahantship, for them [their 
declaration] was valid. But as to those bhikkhus who declared their [attainment 
of] arahantship from over-estimation, it occurs to the Perfect One to explain 
the teaching to them.

_ye te bhikkhū sammadeva aññaṃ vyākaṃsu tesaṃ taṃ tatheva hoti. Ye 
pana te bhikkhū adhimānena aññaṃ vyākaṃsu tatra sunakkhatta 
tathāgatassa evaṃ hoti dhammaṃ nesaṃ desessan ti_ (M.2.252).

.Illustration
====
tatheva

true
====

[quote, A.3.123; Vin.2.186]
____
Whatever the young deva Kakudha says is completely true, not otherwise.

_Yaṃ kiñci kakudho devaputto bhāsati sabbaṃ taṃ tatheva hoti no 
aññathā'ti._
____

COMMENT

Kakudha had reported to MahāMoggallāna that the desire had arisen in 
Devadatta to take charge of the community of bhikkhus, and that this had led to 
the instant loss of his psychic powers.

.Illustration
====
tatheva

incontrovertible
====

[quote, Sn.v.908]
____
'Some believe that spiritual purity is on account of one's view. They say "I 
know and see [the nature of reality]. This is incontrovertible."

_Jānāmi passāmi tatheva etaṃ diṭṭhiyā eke paccenti suddhiṃ._
____

.Illustration
====
tatheva

likewise
====

[quote, Sn.v.33]
____
'One with sons rejoices in sons, one with cattle likewise rejoices in cattle. 
Worldly objects of attachment are truly a man's delight; one without worldly 
objects of attachment does not rejoice.'

_Nandati puttehi puttimā gomiko gohi tatheva nandati +
Upadhī hi narassa nandanā na hi so nandati yo nirupadhi._
____

.Illustration
====
tatheva

like
====

[quote, M.1.138]
____
'The world [of phenomena] is my [absolute] Selfhood. Having passed on, that I 
will be -- everlasting, enduring, eternal, of an unchangeable nature; I will 
endure like unto eternity itself':

_yampidaṃ diṭṭhiṭṭhānaṃ so loko so attā so pecca bhavissāmi 
nicco dhuvo sassato avipariṇāmadhammo sassatisamaṃ tatheva ṭhassāmī 
ti._
____

.Illustration
====
tatheva

like
====

[quote, Th.v.1026]
____
One of great learning who despises one of little learning on account of his 
learning, seems to me just like a blind lamp-bearer.

_Bahussuto appassutaṃ yo sutenātimaññati +
Andho padīpadhāro va tatheva paṭibhāti maṃ._
____

.Illustration
====
tatheva

as they are
====

[quote, S.1.23]
____
The world's attractive things are not sensuous yearning. The sensuous yearning 
of a man is his thoughts bound up with attachment. The world's attractive 
things remain as they are. The wise eliminate their hankering for them.

_Na te kāmā yāni citrāni loke saṅkapparāgo purisassa kāmo +
Tiṭṭhanti citrāni tatheva loke athettha dhīrā vinayanti chandaṃ._
____

.Illustration
====
tatheva

so
====

[quote, Sn.v.906]
____
Just as they honour their own doctrines, so they praise their own paths. If all 
their assertions were true, purity would, of course, be individually theirs.

_Saddhammapūjāpi nesaṃ tatheva yathā pasaṃsanti sakāyanāni +
Sabbeva vādā tathiyā bhaveyyuṃ suddhi hi nesaṃ paccattameva._
____

