== Tathāgata

=== Renderings

- _tathāgata_: the Perfect One

=== Introduction

==== Venerable Ñāṇamoli: 'Perfect One'

Ñāṇamoli translated _tathāgata_ as 'Perfect One' in all his translations: 
the _Majjhima Nikāya_, the _Visuddhimagga_, the _Nettippakaranaṃ_, and the 
_Life of the Buddha_. This term was restored to _Tathāgata_ when his 
translation of the _Majjhima Nikāya_ was published as _A Treasury of the 
Buddha's Words_, and later _The Middle Length Discourses of the Buddha_.

==== Horner: 'Accomplished One or Perfect One'

Horner (_Middle Length Sayings_, Volume 1, xvii) says that _tathāgata_ 
probably means Accomplished One or Perfect One, but argues that these 
renderings are inadequate because they have no etymological justification and 
moreover are equally applicable to any arahant.

==== The Buddha ignored etymology

As for her former objection, the Buddha also ignored etymology. It is true that 
he occasionally referred to _tathā_ (_yathāvādi tathākārī yathākārī 
tathāvādī tasmā tathāgato ti vuccati_, D.3.135) which would justify the 
word 'thus' in 'Thus Gone One.' But this hardly contradicts our assertion, 
because firstly he always ignored the _gata_/_āgata_ suffix, and secondly some 
of his explanations make no reference even to _tathā._ Therefore references to 
_tathā_ should be seen as mere wordplay. For example when Queen Mallikā said:

[quote, M.2.108]
____
Perfect One's do not speak untruth

_na hi tathāgatā vitathaṃ bhaṇantī ti._
____

==== All arahants are tathāgatas

As for Horner's latter objection that 'Perfect One' cannot be used of the 
Buddha because the term could equally applicable to any arahant, this argument 
also fails because _tathāgata_ is indeed occasionally applied to all arahants, 
for example at M.1.140:

[quote, M.1.140]
____
Bhikkhus, when the devas with Inda, Brahmā, and Pajāpati seek a bhikkhu who 
is liberated in mind, they do not find [anything of which they could say]: 'The 
stream of sense consciousness of the Perfect One is attached to this. For what 
reason? The Perfect One is untraceable even in this lifetime, I declare.

_Evaṃ vimuttacittaṃ kho bhikkhave bhikkhuṃ saindā devā sabrahmakā 
sapajāpatikā anvesaṃ nādhigacchanti idaṃ nissitaṃ tathāgatassa 
viññāṇan ti. Taṃ kissa hetu? Diṭṭhevāhaṃ bhikkhave dhamme 
tathāgataṃ ananuvejjoti vadāmi._
____

==== Different levels of perfection of the Perfect One

Even after his enlightenment the Buddha accepted the possibility of further 
developing the aggregates of virtue, inward collectedness, penetrative 
discernment, liberation [from perceptually obscuring states], and the knowledge 
and vision that follows liberation [from perceptually obscuring states], and 
said he would live under a teacher to do this:

[quote, S.1.139]
____
It would be for the sake of fulfilling the unfulfilled aggregate of virtuous 
practices... the knowledge and vision that follows liberation [from 
perceptually obscuring states] that I would honour, respect, and dwell under 
another ascetic or brahman in spiritual discipleship.

_aparipuṇṇassa kho sīlakkhandhassa... samādhikkhandhassa... 
paññākkhandhassa... vimuttikkhandhassa... vimuttiñāṇadassanakkhandhassa 
pāripuriyā aññaṃ samaṇaṃ vā brāhmaṇaṃ vā sakkatvā garukatvā 
upanissāya vihareyyaṃ._
____

This suggests the possibility of different levels of perfection, even at the 
exalted level of Perfect Ones.

==== Different levels of perfection amongst Perfect Ones

Related to this is the possibility that different _tathāgatas_ are at 
different levels of perfection. This was the basis of the Buddha's objection 
when Venerable Sāriputta claimed that there never was, nor is, nor will be, 
another ascetic or Brahmanist who has greater transcendent insight regarding 
enlightenment than the Blessed One (_na cāhu na ca bhavissati na cetarahi 
vijjati añño samaṇovā brāhmaṇo vā bhagavatā bhiyyobhiññataro 
yadidaṃ sambodhiyanti_ (D.3.99).

The Buddha said such a statement would only be valid if one knew the minds of 
all Buddhas, past, present and future (_atītānāgatapaccuppannesu arahantesu 
sammāsambuddhesu cetopariyañāṇaṃ_ (D.3.100).

==== Absolute perfection: nibbāna

Although 'Perfect One' validly renders _tathāgata_, the Buddha did not claim 
that he was therefore perfection itself. The Buddha was perfect in the terms in 
which he described himself. Absolute perfection, _accantaniṭṭho_ is none 
other than _nibbāna_ (M.1.252).

=== Illustrations

.Illustration
====
Perfect One
====

[quote, D.3.84]
____
This is a term for the Perfect One: the embodiment of the teaching, the 
embodiment of Brahmā, one who has become righteousness itself, one who has 
become Brahmā.

_Tathāgatassa hetaṃ vāseṭṭhā adhivacanaṃ dhammakāyo iti pi 
brahmakāyo iti pi dhammabhuto iti pi brahmabhuto iti pi._
____

.Illustration
====
Perfect One
====

____
Whatever in this world [of beings] with its devas,
māras, and brahmās, in the world of mankind with its ascetics and 
Brahmanists, its royalty and commoners is seen, heard, sensed, cognised, 
attained, sought after, pondered over, that has been fully understood by the 
Perfect One. Thus he is called the Perfect One.

_Yaṃ bhikkhave sadevakassa lokassa samārakassa sabrahmakassa 
sassamaṇabrāhmaṇiyā pajāya sadevamanussāya diṭṭhaṃ sutaṃ 
mutaṃ viññātaṃ pattaṃ pariyesitaṃ anuvicaritaṃ manasā yasmātaṃ 
tathāgatena abhisambuddhaṃ tasmā tathāgato ti vuccati_
____

____
From the day of his unsurpassed enlightenment till the day of his passing away 
to the Untroubled-without-residue, whatever the Perfect One has said, spoken, 
and explained in that interval is completely right, not mistaken. Thus he is 
called the Perfect One.

_Yañca bhikkhave rattiṃ tathāgato anuttaraṃ sammāsambodhiṃ 
abhisambujjhati yañca rattiṃ anupādisesāya nibbānadhātuyā 
parinibbāyati yaṃ etasmiṃ antare bhāsati lapati niddisati sabbaṃ taṃ 
tatheva hoti. No aññathā. Tasmā tathāgato ti vuccati._
____

____
The Perfect One is one who behaves in line with the way he speaks, and speaks 
in line with the way he behaves. Thus he is called the Perfect One.

_Yathāvādi bhikkhave tathāgato tathākārī. Yathākārī tathāgato 
tathāvādī. Iti yathāvādītatākārī yathākārī tathāvādī. Tasmā 
tathāgato ti vuccati._
____

[quote, It.121-2; A.2.24]
____
In this world [of beings] with its devas, māras, and brahmās, in the world of 
mankind with its ascetics and Brahmanists, its royalty and commoners, the 
Perfect One is the unconquered Conqueror [of all unvirtuous, spiritually 
unwholesome factors], all-seeing, the wielder of power. Thus he is called the 
Perfect One.

_Sadevake bhikkhave loke samārake sabrahmake sassamaṇabrāhmaṇiyā pajāya 
sadevamanussāya tathāgato abhibhū anabhibhūto. Aññadatthudaso vasavattī. 
Tasmā tathāgato ti vuccatītu._
____

.Illustration
====
Perfect One
====

[quote, D.3.134-5]
____
Concerning things past, future, and present the Perfect One is one who speaks 
at the right time, about what is true, what is beneficial, what is the 
teaching, what is the discipline. Therefore he is called the Perfect One.

_atītānāgatapaccuppannesu dhammesu tathāgato kālāvādī bhūtavādi 
atthavādī dhammāvadi vinayavādī tasmā tathāgato ti vuccati._
____

.Illustration
====
Perfect One
====

[quote, S.3.118]
____
The Perfect One, the unexcelled person, the supreme person, one who has 
attained the supreme attainment.

_tathāgato uttamapuriso paramapuriso paramapattipatto._
____

