== Taṃ kutettha labbhā ti

=== Renderings

- _taṃ kutettha labbhā ti_: How could it possibly be otherwise?

- _taṃ kutettha labbhā ti_: What can be possibly done about it?

- _taṃ kutettha labbhā ti_: What possible advantage is there in such a 
thought?

=== Introduction

==== Rhetorical question: threefold solution

The phrase _taṃ kutettha labbhā ti_ occurs many times in the scriptures. Its 
meaning is uncertain, but it seems to indicate a rhetorical question. Bodhi 
renders it in three ways:

- How is it possible that... ? (MLDB p.990)

- How is it to be obtained here... ? (CDB p.1645).

- How could I possibly think... ? (CDB p.666).

Our own threefold solution is as follows:

- How could it possibly be otherwise?

- What can be possibly done about it?

- What possible advantage is there in such a thought?

==== Relationship to an underlying truth

The validity of these renderings can be demonstrated by considering their 
relationship to an underlying truth:

1. 'How could it possibly be otherwise?' arises from the truth that 'being 
otherwise is impossible.' For example: What is born deteriorates: how could it 
possibly be otherwise?

2. 'What can be possibly done about it?' arises from the truth that 'this is an 
immutable fact.' For example: Originated phenomena are unlasting: what can be 
possibly done about it?

3. 'What possible advantage is there in such a thought?' arises from the truth 
that 'there is no possible advantage in such a thought.' For example, the 
Buddha said a bhikkhu was unworthy to be a visitor of families (_arahati na 
kulūpago hotuṃ_) if he did so with the thought that they should give him 
offerings, because if they did not comply he would be resentful. He said that 
the thought, 'May they give!' should be quelled with the thought, 'What 
possible advantage is there in such a thought?'

==== The Dvedhāvitakka Sutta: a comparison

Eradicating unvirtuous thoughts by recognising their lack of usefulness is 
described in a similar way in the _Dvedhāvitakka Sutta_ where the Buddha said 
that before his enlightenment, when afflicted by sensuous thought, unbenevolent 
thought, and malicious thought (_kāmavitakko; vyāpādavitakko; 
vihiṃsāvitakko_) he would reflect on such thoughts:

[quote, M.1.114]
____
This leads to my own harm, the harm of others, the harm of both. It is 
destructive of penetrative discernment, associated with distress, not conducive 
to the Untroubled

_attavyābādhāyapi saṃvattati paravyābādhāyapi saṃvattati 
ubhayavyābādhāyapi saṃvattati paññānirodhiko vighātapakkhiko 
anibbānasaṃvattaniko_
____

He said that by reflecting like this, the thought would vanish.

=== Illustrations

.Illustration
====
How could it possibly be otherwise?

The Buddha

approaching death, said to the weeping Ānanda:
====

[quote, D.2.118]
____
'How could it possibly be, Ānanda, that what is born, brought about, 
originated, destined to decay, not decay? It is not possible.'_

_Taṃ kutettha ānanda labbhā yaṃ taṃ jātaṃ bhūtaṃ saṅkhataṃ 
palokadhammaṃ taṃ vata mā palujjitī. Netaṃ ṭhānaṃ vijjati._
____

.Illustration
====
How could it possibly be otherwise?

When Prince Jayasena refused to accept that a bhikkhu could achieve 
non-distractedness of mind (_cittassa ekaggatan ti_)

the Buddha exclaimed to Aggivessana: 'How could it possibly be (_taṃ kutettha 
aggivessana labbhā_), that Prince Jayasena, living amidst sensuous pleasure, 
enjoying sensuous pleasure, being consumed by sensuous thought, tormented by 
sensuous passion, eager in the quest for sensuous pleasure, could know or see 
or realise that which must be known, seen, attained and realised through the 
practice of unsensuousness? It is impossible' (_netaṃ ṭhānaṃ vijjati_) 
(M.3.129).
====

.Illustration
====
How could it possibly be otherwise?

[quote

S.1.186]
====

____
When disgruntlement [with the celibate life] (i.e. lust) invaded Vaṅgīsa's 
mind while he was alone, he reflected 'How could it possibly be that someone 
else could dispel my disgruntlement [with the celibate life], and arouse 
delight in it? How about if I dispelled my disgruntlement [with the celibate 
life] myself, and aroused delight in it?

_taṃ kutettha labbhā yaṃ me paro anabhiratiṃ vinodetvā abhiratiṃ 
uppādeyya. Yannūnāhaṃ attanāva attano anabhiratiṃ vinodetvā 
abhiratiṃ uppādeyyan ti._
____

.Illustration
====
What can be possibly done about it?

[quote

Vin.2.284]
====

____
When the Buddha passed away, those bhikkhus who were free of attachment, bore 
&#8203;[the situation], saying: 'Originated phenomena are unlasting. What can be 
possibly done about it?.'

_Ye pana te bhikkhū vītarāgā te satā sampajānā adhivāsenti aniccā 
saṅkhārā taṃ kutettha labhā ti._
____

.Illustration
====
What can be possibly done about it?

When a brahman invited the Buddha to spent a rains residency period at Verañja

he later apologised for not supporting him, saying:
====

[quote, Vin.3.11]
____
"What can be possibly done about it? The household life is busy; there is much 
to do."

_Taṃ kutettha labbhā? Bahukiccā gharāvāsā bahukaraṇīyā._
____

.Illustration
====
What possible advantage is there in such a thought?

____
"Bhikkhus

a bhikkhu might approach families with the thought:
====

_Yo hi koci bhikkhave bhikkhu evaṃcitto kulāni upasaṅkamati_
____

____
'May they give to me, not hold back. May they give much, not little. May they 
give fine things, not shabby things. May they give promptly, not slowly. May 
they give respectfully, not casually.'

_dentuyeva me mā nādaṃsu. Bahuññeva me dentu mā thokaṃ. 
Paṇitaññeva me dentu mā lūkhaṃ. Sīghaññeva me dentu mā dandhaṃ. 
Sakkaccaññeva me dentu mā asakkaccan ti_
____

____
When a bhikkhu approaches families with such a thought, if they do not give, he 
thereby becomes resentful. On that account he experiences physical and 
psychological pain.

_Tassa ce bhikkhave bhikkhuno evaṃ cittassa kulāni upasaṅkamato na denti 
tena bhikkhu sandīyati. So tatonidānaṃ dukkhaṃ domanassaṃ 
paṭisaṃvedayati_
____

____
Such a bhikkhu is not worthy to be a visitor of families.

_Evarūpo kho bhikkhave bhikkhū na arahati kulūpago hotuṃ._
____

____
"Bhikkhus, a bhikkhu might approach families with the thought:

_Yo ca kho bhikkhave bhikkhu evaṃcitto kulāni upasaṅkamati_
____

____
'What possible advantage is there in such a thought when amidst families as: 
"May they give to me, not hold back.... May they give respectfully, not 
casually"?'

_Taṃ kutettha labbhā parakulesu dentu yeva me mā nādaṃsu_
____

____
When a bhikkhu approaches families with such a thought,

_Tassa me bhikkhave bhikkhuno evaṃcittassa kulāni upasaṅkamato_
____

if they do not give... if they give casually rather than carefully, he does not 
become resentful, nor does he experience physical and psychological pain 
(S.2.200).

.Illustration
====
What possible advantage is there in such a thought?

There are ten bases of resentment (_dasa āghātavatthūni_)

namely the thoughts:
====

____
He has harmed, is harming, or will harm me. Thinking thus, one arouses 
resentment.

_anatthamme acarīti... caratīti... carissatīti āghātaṃ bandhati_
____

____
He has harmed, is harming, or will harm someone beloved and dear to me. 
Thinking thus, one arouses resentment.

_Piyassa me manāpassa anatthaṃ acarīti... caratīti... carissatīti 
āghātaṃ bandhati_
____

____
He has benefited, is benefiting, or will benefit someone who is unbeloved or 
loathsome to me. Thinking thus, one arouses resentment.

_Appiyassa me amanāpassa atthaṃ acari... carati... carissatīti āghātaṃ 
bandhati_
____

[quote, A.5.150; D.3.263]
____
And tenthly, one is groundlessly irritated.

_aṭṭhāne ca kuppati._
____

There are correspondingly ten ways of overcoming resentment, via the thought 
_taṃ kutettha labbhāti,_ as follows:

- He has harmed, is harming, or will harm me. What possible advantage is there 
in such a thought?

- He has harmed, is harming, or will harm someone beloved and dear to me. What 
possible advantage is there in such a thought?

- He has benefited, is benefiting, or will benefit someone who is unbeloved or 
loathsome to me. What possible advantage is there in such a thought?

Finally, one overcomes groundless irritation through being groundlessly 
unirritated (_aṭṭhāne ca na kuppati_) (A.5.150).

