== Taṇhā

=== Renderings

- _taṇhā_: craving

- _bhavataṇhā_: craving for states of individual existence (i.e. treating 
_bhavataṇhā_ as a plural)

- _vibhavataṇhā_: craving for the cessation of states of individual 
existence (i.e. treating _vibhavataṇhā_ as a plural)

=== Introduction

==== Taṇhā is 'powerful and unsubdued'

_Taṇhā_ is usually and correctly called 'craving' (i.e. strong desire). This 
is justified by comparison with _kāmarāgo_, which is a tie to individual 
existence when it is 'powerful and unsubdued':

1. Craving is the seamstress. For craving stitches him to this or that state of 
individual existence and rebirth.
+
****
_taṇhā sibbanī_. _Taṇhā hi naṃ sibbati tassa tasseva bhavassa 
abhinibbattiyā_ (A.3.400).
****

2. When attachment to sensuous pleasure is powerful and unsubdued in him, it is 
a tie to individual existence in the low plane of existence.
+
****
_tassa so kāmarāgo thāmagato appaṭivinīto orambhāgiyaṃ saṃyojanaṃ_ 
(M.1.433).
****

==== Taṇhā comes from misperceiving sense impression

_Taṇhā_ arises dependent on sense impression, as follows:

[quote, D.2.31]
____
When there is sense impression, craving arises. Craving arises dependent on 
sense impression

_vedanāya kho sati taṇhā hoti vedanāpaccayā taṇhā ti._
____

How misperception of sense impression leads to craving is explained in the 
_Sammasa Sutta_ as follows:

____
Bhikkhus, whatever ascetics and Brahmanists in the past... in the future... 
at present regard that in the world which is agreeable and pleasing

_Ye hi ke ci bhikkhave atītamaddhānaṃ... anāgatamaddhānaṃ... etarahi 
samaṇā vā brāhmaṇā yaṃ loke piyarūpaṃ sātarūpaṃ_
____

____
as lasting

_taṃ niccato passanti_
____

____
as existentially substantial

_sukhato passanti_
____

____
as endowed with personal qualities

_attato passanti_
____

____
as unailing

__ārogyato passanti_
____

____
as free of danger

_khemato passanti_
____

[quote, S.2.108-9]
____
they nurture craving

_te taṇhaṃ vaḍḍhenti._
____

Therefore misperception produces _taṇhā_.

==== Bhavataṇhā and Vibhavataṇhā: plurals

There are three forms of _taṇhā_:

____
craving for sensuous pleasure

_kāmataṇhā_
____

____
craving for states of individual existence

_bhavataṇhā_
____

[quote, D.2.308]
____
craving for the cessation of states of individual existence

_vibhavataṇhā._
____

We treat _bhavataṇhā_ as a plural, in accordance with other suttas. For 
example:

1. not free of craving for various states of individual existence
+
****
_avitataṇhāse bhavābhavesu_ (Sn.v.776).
****

2. In relation to states of individual existence, the attachment to individual 
existence_._
+
****
_bhavesu bhavarāgo_ (A.2.10).
****

3. All these states of individual existence are unlasting, existentially void, 
destined to change. On perceiving this according to reality with perfect 
penetrative discernment he abandons craving for states of individual existence.
+
****
_Sabbe te bhavā aniccā dukkhā vipariṇāmadhammā_. +
_Evametaṃ yathābhūtaṃ sammappaññāya passato_ +
_Bhavataṇhā pahīyati_ (Ud.33).
****

We likewise treat _vibhavataṇhā_ as a plural, otherwise it would only be 
applicable to the annihilationist ideal. Here, because some devas and men are 
revolted, appalled, and disgusted by individual existence (_bhaveneva kho 
paneke aṭṭiyamānā harāyamāsā jigucchamānā_), they long for the 
cessation of individual existence (_vibhavaṃ abhinandanti_). They think:

[quote, It.44]
____
When that [absolute] Selfhood is annihilated, destroyed, and does not exist 
with the demise of the body at death, this is peaceful, this is sublime, this 
is reality.'

_yato kira bho ayaṃ attaṃ kāyassa bhedā parammaraṇā ucchijjati 
vinassati na hoti parammaraṇā etaṃ santaṃ etaṃ paṇītaṃ etaṃ 
yathāvantī._
____

However, through disgust with personal identity such people keep running and 
circling around that same personal identity just as a dog bound by a leash tied 
to a firm post or pillar keeps on running and circling around that same post or 
pillar (M.2.232-233).

This form of _taṇhā_ is no less a basis for renewed states of individual 
existence than the other two forms. But treating _vibhavataṇhā_ as a plural 
gives it a much broader application.

These plurals are therefore applicable in the following quotes:

[quote, D.3.216]
____
Three further types of craving

_Aparā pi tisso taṇhā_

craving for the sensuous plane of existence

_kāmataṇhā_

craving for the refined material plane of existence

_rūpataṇhā_

craving for the immaterial plane of existence.

_arūpataṇhā._
____

[quote, D.3.216]
____
Three further varietes of craving:

_aparā pi tisso taṇhā_

craving for refined material states of awareness

_rūpataṇhā_

craving for immaterial states of awareness

_arūpataṇhā_

craving for the ending [of originated phenomena]

_nirodhataṇhā._
____

==== Basis of the ego: Pārileyyaka Sutta

_Taṇhā_ creates egoistic ideas in the following way:

____
The ignorant Everyman considers bodily form to be the [absolute] Selfhood

_rūpaṃ attato samanupassati_
____

____
That considering is an originated phenomenon

_yā kho pana sā bhikkhave samanupassanā saṅkhāro so_
____

____
What is the basis, origin, object of genesis and production of that originated 
phenomenon?

_So pana saṅkhāro kinnidāno kiṃsamudayo kiñjātiko kimpabhavoti_
____

____
When the ignorant Everyman is affected by sense impression born of sensation 
and uninsightfulness into reality, craving arises.

_avijjāsamphassajena bhikkhave vedayitena phuṭṭhassa assutavato 
puthujjanassa uppannā taṇhā_
____

[quote, S.3.96]
____
That originated phenomenon is born from that

_tatojo so saṅkhāro._
____

==== Basis of the ego: other suttas

That assumptions of Selfhood stem from _taṇhā_ is confirmed in other suttas:

1. The view that the Tathāgata exists after death is called a matter of 
_taṇhā_ (_taṇhāgatametaṃ_) (A.4.69).

2. When ascetics and brahmans who are eternalists proclaim the eternity of the 
Self and the world in four ways, that is merely merely the agitation and 
trembling of those overcome by _taṇhā_ (_taṇhāgatametaṃ_) (D.1.40).

3. When the bhikkhu Sati had the view that 'it is this same consciousness that 
runs and wanders through the round of rebirths, not another', the Buddha said 
that the bhikkhu Sati was caught up in the vast net of _taṇhā_ (M.1.271).

4. When the Buddha explained the doctrine of no-Self, and a monk asked what 
Self will the actions done by not-Self affect, the Buddha said that the 
bhikkhu's mind was overcome by _taṇhā_ (_taṇhādhipateyyena_) (M.3.19).

5. It is craving that produces a person;
+
****
_taṇhā janeti purisaṃ_ (S.1.37).
****

=== Illustrations

.Illustration
====
taṇhā

craving
====

[quote, Sn.v.640]
____
Whichever homeless one, having abandoned sensuous pleasure in this world, 
should fulfil the ideals of religious asceticism, and for whom craving and 
individual existence are destroyed, he is what I call a Brahman.

_Yodha taṇhaṃ pahatvāna anāgāro paribbaje +
Taṇhābhavaparikkhīṇaṃ tamahaṃ brūmi brāhmaṇaṃ._
____

.Illustration
====
taṇhāya

craving
====

[quote, A.4.49]
____
If a bhikkhu's mind is imbued with the perception of the loathsome nature of 
digestion, his mind draws back, bends back, turns away from craving for 
flavours and is not attracted to them, and either indifference or loathing is 
established in him.

_Āhāre paṭikkūlasaññā paricitena bhikkhave bhikkhuno cetasā bahulaṃ 
viharato rasataṇhāya cittaṃ patilīyati patikuṭati pativaṭṭati na 
sampasārīyati upekkhā vā paṭikkūlyatā vā saṇṭhāti._
____

.Illustration
====
taṇhaṃ

craving
====

[quote, Sn.v.339]
____
Do not foster craving for robe material, almsfood, therapeutic requisites, and 
abodes

_cīvare piṇḍapāte ca paccaye sayanāsane etesu taṇhaṃ mā kāsi._
____

.Illustration
====
taṇhaṃ

craving
====

[quote, A.4.401]
____
Because of craving, search.

_taṇhaṃ paṭicca pariyesanā_

Because of search, acquisition

_pariyesanaṃ paṭicca lābho_

Because of acquisition, examination

_lābhaṃ paṭicca vinicchayo_

Because of examination, fondness and attachment

_vinicchayaṃ paṭicca chandarāgo_.
____

.Illustration
====
taṇhā

craving
====

[quote, Sn.v.856]
____
A person for whom there is no attachment, who, knowing the nature of reality 
&#8203;[according to reality], is not attached; and who has no craving for either 
individual existence or the cessation of individual existence.

_Yassa nissayatā natthi ñatvā dhammaṃ anissito +
Bhavāya vibhavāya vā taṇhā yassa na vijjati._
____

.Illustration
====
taṇhā

craving
====

[quote, D.2.62]
____
-- 'Ānanda, if there were no craving in any way,

craving for sensuous pleasure,

_kāmataṇhā_

craving for states of individual existence

_bhavataṇhā_

craving for the cessation of states of individual existence

_vibhavataṇhā_

with the total ending of craving

_sabbaso taṇhā nirodhā_

would search be evident?'

_api nu kho pariyesanā paññāyethā ti._

-- 'No, bhante'.
____

.Illustration
====
taṇhā

craving
====

____
Attachment has craving as its basis, craving as its origin; it is generated and 
produced by craving.

_upadhi taṇhānidāno taṇhāsamudayo taṇhājātiko taṇhāpabhavo_
____

[quote, S.2.108]
____
When there is craving, attachment comes to be. Without craving, attachment does 
not arise.

_taṇhāya sati upadhi hoti taṇhāya asati upadhi na hotī ti._
____

.Illustration
====
taṇhā

craving
====

____
And where does craving arise when it arises; where does it persist when it 
persists?

_taṇhā panāyaṃ kattha uppajjamānā uppajjati kattha nivisamānā 
nivisatī ti._
____

____
Whatever in the world [of phenomena] is agreeable and pleasing: it is here that 
craving arises when it arises; it is here that it persists when it persists._

_yaṃ kho kiñci loke piyarūpaṃ sātarūpaṃ etthesā taṇhā 
uppajjamānā uppajjati ettha nivisamānā nivisati._
____

____
And what in the world is agreeable and pleasing?

_Kiñca loke piyarūpaṃ sātarūpaṃ?_
____

____
The visual sense is agreeable and pleasing in the world: it is here that 
craving arises when it arises; it is here that it persists when it persists._

_Cakkhuṃ loke piyarūpaṃ sātarūpaṃ etthesā taṇhā uppajjamānā 
uppajjati ettha nivisamānā nivisati._
____

[quote, S.2.108]
____
So, too, the auditory sense, the olfactory sense, the gustatory sense, the 
tactile sense, and the mental sense have an agreeable and pleasing nature: it 
is here that craving arises when it arises; it is here that it persists when it 
persists._

_Sotaṃ... Ghānaṃ... Jivhā... Kāyo... Mano loke piyarūpaṃ 
sātarūpaṃ etthesā taṇhā uppajjamānā uppajjati ettha nivisamānā 
nivisati._
____

.Illustration
====
taṇhaṃ

craving
====

____
Bhikkhus, whatever ascetics and Brahmanists in the past regarded that in the world which 
is agreeable and pleasing

_ye ca kho ke ci bhikkhave atītamaddhānaṃ samaṇā vā brāhmaṇā vā 
yaṃ loke piyarūpaṃ sātarūpaṃ taṃ_
____

____
as unlasting

_aniccato addakkhuṃ_
____

____
as existentially void

_dukkhato addakkhuṃ_
____

____
as void of personal qualities

_anattato addakkhuṃ_
____

____
as an illness

_rogato addakkhuṃ_
____

____
as full of danger

_bhayato addakkhuṃ_
____

____
they abandoned craving

_te taṇhaṃ pajahiṃsu_
____

[quote, S.2.108-9]
____
In abandoning craving they abandoned attachment

_ye taṇhaṃ pajahiṃsu te upadhiṃ pajahiṃsu._
____

.Illustration
====
taṇhāya

craving
====

[quote, M.1.49]
____
The complete passing away and ending of this same craving, the giving up and 
relinquishment of it, the freedom from it, the letting go of it, is called the 
ending of suffering.

_Yo tassāyeva taṇhāya asesavirāganirodho cāgo paṭinissaggo mutti 
anālayo ayaṃ vuccatāvuso dukkhanirodho._
____

.Illustration
====
taṇhā

craving
====

[quote, S.1.107]
____
He for whom entangling and sticky craving no more exists to lead him anywhere.

_Yassa jālinī visattikā taṇhā natthi kuhiñci netave._
____

.Illustration
====
taṇhā

craving
====

____
With craving as his companion, man has wandered the round of birth and death 
for a long time. He cannot transcend the round of birth and death by states of 
individual existence in this world or another.

_Taṇhā dutiyo puriso dīghamaddhānaṃ saṃsaraṃ +
Itthabhāvaññathābhāvaṃ saṃsāraṃ nātivattati._
____

[quote, A.2.10]
____
Recognising this danger, that the arising of suffering is due to craving, let 
the bhikkhu, free of craving, free of grasping, mindful, fulfil the ideals of 
religious asceticism.

_Etamādīnavaṃ ñatvā taṇhā dukkhassa sambhavaṃ +
Vītataṇho anādāno sato bhikkhu paribbaje ti._
____

Comment:

Norman says the alternative reading _taṇhaṃ dukkhassa sambhavaṃ_ 
'probably arose from the inability of the scribes to fit the seeming nominative 
_taṇhā_ into the structure of the sentence. This problem disappears when we 
realise that _taṇhā_ is a truncated instrumental = _taṇhāya'_ (Group of 
Discourses n.741). This view is supported by the commentary (which says _etaṃ 
dukkhassa sambhavaṃ taṇhāya ādīnavaṃ ñatvā_) and also by the usual 
meaning of _sambhava,_ which is 'arising' not 'origin.'

.Illustration
====
taṇhā

craving
====

____
When one abides contemplating the sweetness of things that are conducive to 
psychological bondage, craving increases.

_saṃyojaniyesu dhammesu assādānupassino viharato taṇhā pavaḍḍhati_
____

[quote, S.2.89]
____
When one abides contemplating the wretchedness of things that are conducive to 
psychological bondage, craving ceases.

_saṃyojaniyesu dhammesu ādīnavānupassino viharato taṇhā nirujjhati._
____

.Illustration
====
taṇhā

craving
====

-- Master Gotama, when a flame is flung by the wind and goes some distance, 
what does Master Gotama declare to be its fuel on that occasion?

-- When, Vaccha, a flame is flung by the wind and goes some distance, I declare 
that it is fuelled by the wind. For on that occasion the wind is its fuel.

-- And, Master Gotama, when a being has laid down this [wretched human] body 
but is not yet possessed of another body, what does Master Gotama declare to be 
&#8203;[the being's] fuel on that occasion?

[quote, S.4.399]
____
-- When, Vaccha, a being has laid down this [wretched human] body but is not 
yet possessed of another body, I declare that [the being] is fuelled by 
craving. For on that occasion craving is [the being's] fuel.

_Yasmiṃ kho vaccha samaye imañca kāyaṃ nikkhipati satto ca aññataraṃ 
kāyaṃ anuppanno hoti tamahaṃ taṇhūpādānaṃ vadāmi. Taṇhāhissa 
vaccha tasmiṃ samaye upādānaṃ hotī ti._
____

.Illustration
====
taṇhā

craving
====

• This [wretched human] body has manifested through craving. With the help of 
craving, craving must be abandoned. +
_Taṇhāsambhūto ayaṃ bhagini kāyo. Taṇhaṃ nissāya taṇhā 
pahātabbā ti iti kho panetaṃ vuttaṃ._

The sutta explains this as follows:

A bhikkhu hears that another bhikkhu has attained arahantship. To him it occurs:

____
Surely, I too, through the destruction of perceptually obscuring states, in 
this very lifetime will enter and abide in the liberation [from attachment 
through inward calm] and the liberation [from uninsightfulness] through 
penetrative discernment, realising it for myself through transcendent insight.

_Tassa evaṃ hoti: kudassunāma ahampi āsavānaṃ khayā anāsavaṃ 
cetovimuttiṃ paññāvimuttiṃ diṭṭheva dhamme sayaṃ abhiññā 
sacchikatvā upasampajja viharissāmī ti._
____

[quote, A.2.146]
____
Then sometime later, with the help of craving, he abandons craving.

_So aparena samayena taṇhaṃ nissāya taṇhaṃ pajahati._
____

.Illustration
====
taṇhā

craving
====

[quote, Sn.v.114]
____
One with little wealth but exceeding craving is born into a _khattiya_ family. 
He longs for kingship in this world. That is the cause of spiritual ruination.

_Appabhogo mahātaṇho khattiye jāyato kule +
Sodha rajjaṃ patthayati taṃ parābhavato mukhaṃ._
____

.Illustration
====
taṇhā

craving
====

The savoury earth was very sweet, like honey. Then one creature with a greedy 
nature (_lolajātiko_) tasted the savoury earth placed on its finger and 
craving arose in it (_taṇhā cassa okkami_). Other beings did the same. Then 
they started breaking pieces off with their hands in order to eat it (D.3.85).

.Illustration
====
taṇhā

craving
====

[quote, Dh.v.349]
____
The craving of a person of distracted thoughts, who is full of attachment and 
contemplates the loveliness [of the female body] will only develop.

_Vitakkapamathitassa jantuno tibbarāgassa subhānupassino +
Bhiyyo taṇhā pavaḍḍhati._
____

.Illustration
====
taṇhā

craving
====

[quote, Dh.v.355]
____
Fools through craving for wealth destroy themselves and others too.

_Bhogataṇhāya dummedho hanti aññe va attānaṃ._
____

.Illustration
====
taṇhā

craving
====

[quote, S.2.3]
____
There are six categories of craving

_chayime taṇhākāyā_

craving for visible objects

_rūpataṇhā_

craving for audible objects

_saddataṇhā_

craving for smellable objects

_gandhataṇhā_

craving for tasteable objects

_rasataṇhā_

craving for tangible objects

_phoṭṭhabbataṇhā_

craving for mentally known objects

_dhammataṇhā._
____

