== Tevijja; Vijjā

=== Renderings

- _vijjā_: final knowledge

- _vijjā_: Vedic knowledge

- _vijjā_: insightfulness into reality

- _vijjā_: occult knowledge

- _tevijja_: master of threefold Vedic knowledge

- _tevijja_: master of the three final knowledges

- _tiracchānavijjā_: base art

=== Introduction

==== Brahman: tevijja, master of threefold Vedic knowledge

A brahman who is a 'master of the three Vedas' (_tiṇṇaṃ vedānaṃ 
pāragū_) is called 'a master of threefold Vedic knowledge' (_tevijja_), 
though the definition includes other qualities, as follows:

____
-- 'In what way, brahman, do brahmans declare a brahman to be a master of 
threefold Vedic knowledge?'

_Yathākathaṃ pana brāhmaṇa brāhmaṇā brāhmaṇaṃ tevijjaṃ 
paññāpentī ti_
____

____
-- 'In this regard, Master Gotama, a brahman is of pure ancestry on both sides 
of his family, of pure descent, unimpeachable and irreproachable with respect 
to birth as far back as the seventh generation.

_Idha pana bho gotama brāhmaṇo ubhato sujāto hoti mātito ca pitito ca 
saṃsuddhagahaṇiko yāva sattamā pitāmahāyugā akkhitto anupakkuṭṭho 
jātivādena_
____

____
he is a scholar [of the sacred texts]

_ajjhāyako_
____

____
he knows by heart the sacred texts

_mantadharo_
____

____
he is a master of the three Vedas

_tiṇṇaṃ vedānaṃ pāragū_
____

____
together with its glossaries, rituals

_sanighaṇḍukeṭubhānaṃ_
____

____
phonology, etymology

_sākkharappabhedānaṃ_
____

____
and fifthly, the commentaries

_itihāsapañcamānaṃ_
____

____
he is fully versed in linguistics, grammar, natural philosophy, and in the 
marks of a Great Man

_padako veyyākaraṇo lokāyatamahāpurisalakkhaṇesu anavayo_
____

[quote, A.1.166]
____
In this way, Gotama, do brahmans declare a brahman to be a master of threefold 
Vedic knowledge

_evaṃ kho bho gotama brāhmaṇā brāhmaṇaṃ tevijjaṃ paññāpentī 
ti._
____

==== Arahant: tevijja, master of the three final knowledges

A bhikkhu who has attained the three final knowledges (_tisso vijjā_) is a 
'master of the three final knowledges' (_tevijja_).

_Tisso vijjā_ are called the 'three final knowledges' because they were the 
last knowledges to be realised before the Buddha's enlightenment.

____
The three final knowledges are:

_Tisso vijjā_
____

____
the final knowledge: the knowledge through recalling of past lives

_pubbenivāsānussati ñāṇaṃ vijjā_
____

____
the final knowledge: knowledge of the transmigration of beings

_sattānaṃ cutūpapāte ñāṇaṃ vijjā_
____

[quote, D.3.275]
____
the final knowledge: the knowledge of the destruction of perceptually obscuring 
states_._

__āsavānaṃ khaye ñāṇaṃ vijjā._
____

=== Introduction: other meanings of vijjā

==== Vijjā: insightfulness into reality

_Vijjā_ is the opposite of _avijjā_ (uninsightfulness into reality). This is 
dealt with sv _Avijjā_.

____
The ignorant Everyman does not discern according to reality the origination, 
vanishing, sweetness, wretchedness, and deliverance in regards to the five 
aggregates.

_assutavā puthujjano rūpassa... viññāṇassa samudayañca atthaṅgamañca 
assādañca ādīnavañca nissaraṇañca yathābhūtaṃ nappajānāti._
____

____
...This is called uninsightfulness into reality

_ayaṃ vuccatāvuso avijjā_
____

____
... The learned noble disciple discerns these matters according to reality

_sutavā ariyasāvako rūpassa... viññāṇassa assādañca ādīnavañca 
nissaraṇañca yathābhūtaṃ pajānāti_
____

[quote, S.3.173-4]
____
... This is called insightfulness into reality

_Ayaṃ vuccatāvuso vijjā._
____

==== Vijjā: occult knowledge

_Vijjā_ can mean 'occult knowledge.' For example, the householder Kevaḍḍha 
suggested that if bhikkhus performed superhuman displays of psychic power, it 
would win the faith of the unbelievers of Nāḷandā. The Buddha replied that 
if a bhikkhu displayed various kinds of psychic power, someone with faith and 
trust might see him doing so and tell someone who was sceptical and 
unbelieving. And that man would say:

____
'There is something called Gandhāra occult knowledge, by means of which he 
wields various kinds of psychic power.

_atthi kho bho gandhārī nāma vijjā tāya so bhikkhu anekavihitaṃ 
iddhividhaṃ paccanubhoti_
____

[quote, D.1.213-4]
____
The Buddha concluded: 'Seeing this wretchedness in displays of psychic power, I 
am revolted, appalled, and disgusted by them.'

_Imaṃ kho ahaṃ kevaḍḍha iddhipāṭihāriye ādīnavaṃ sampassamāno 
iddhipāṭihāriyena aṭṭiyāmi harāyāmi jigucchāmi._
____

==== Tiracchānavijjā: base art

_Tiracchānavijjā_ means 'base art.' For example:

____
Some ascetics and Brahmanists, living off food given in faith, maintain 
themselves by such base arts and wrong means of livelihood such as these:

_Yathā vā paneke bhonto samaṇabrāhmaṇā saddhādeyyāni bhojanāni 
bhuñjitvā te evarūpāya tiracchānavijjāya micchājīvena jīvikaṃ 
kappenti seyyathīdaṃ_
____

____
... Determining lucky and unlucky gems, garments, staffs, swords, spears, 
arrows, bows, sticks...

_maṇilakkhaṇaṃ vatthalakkhaṇaṃ daṇḍalakkhaṇaṃ 
satthalakkhaṇaṃ asilakkhaṇaṃ usulakkhaṇaṃ dhanulakkhaṇaṃ 
āvudhalakkhaṇaṃ_
____

[quote, D.1.9]
____
... The ascetic Gotama refrains from these kinds of base arts and wrong means 
of livelihood.

_iti evarūpāya tiracchānavijjāya micchājīvā paṭivirato samaṇo gotamo 
ti._
____

=== Illustrations

.Illustration
====
vijjā

final knowledge
====

____
Which three things should be realised for oneself?

_Katame tayo dhammā sacchikātabbā?_
____

____
The three final knowledges.

_Tisso vijjā_
____

____
the final knowledge: the knowledge through recalling of past lives

_pubbenivāsānussati ñāṇaṃ vijjā_
____

____
the final knowledge: knowledge of the transmigration of beings

_sattānaṃ cutūpapāte ñāṇaṃ vijjā_
____

[quote, D.3.275]
____
the final knowledge: the knowledge of the destruction of perceptually obscuring 
states_._

__āsavānaṃ khaye ñāṇaṃ vijjā._
____

.Illustration
====
vijjā

final knowledge
====

[quote, Thī.v.433]
____
Seven days after going forth [into the ascetic life] I attained the three final 
knowledges

_sattāhaṃ pabbajitā tisso vijjā aphassayiṃ._
____

.Illustration
====
vijjā

final knowledge; vijjā, insightfulness into reality
====

____
I directed my mind to the knowledge through recalling of past lives;

_pubbenivāsānussatiñāṇāya cittaṃ abhininnāmesiṃ._
____

____
... I recalled my manifold former lives with their aspects and particulars. 
This was the first final knowledge attained by me in the first watch of the 
night;

_Iti sākāraṃ sauddesaṃ anekavihitaṃ pubbenivāsaṃ anussarāmi. Ayaṃ 
kho me brāhmaṇa rattiyā paṭhame yāme paṭhamā vijjā adhigatā_
____

____
Uninsightfulness into reality was dispelled, insightfulness into reality arose, 
darkness was dispelled, light arose

_avijjā vihatā vijjā uppannā tamo vihato aloko uppanno_
____

____
I directed my mind towards the knowledge of the transmigration of beings

_sattānaṃ cutūpapātañāṇāya cittaṃ abhininnāmesiṃ._
____

____
... Thus with purified divine vision surpassing that of men, I saw beings 
passing away and being reborn, inferior and superior, well-favoured and 
ill-favoured, fortunate and unfortunate, and discerned how beings fare 
according to their deeds.

_Iti dibbena cakkhunā visuddhena atikkantamānusakena satte passāmi cavamāne 
uppajjamāne hīne paṇīte suvaṇṇe dubbaṇṇe sugate duggate 
yathākammūpage satte pajānāmi._
____

____
This was the second final knowledge attained by me in the middle watch of the 
night.

_Ayaṃ kho me brāhmaṇa rattiyā majjhime yāme dutiyā vijjā adhigatā_
____

____
Uninsightfulness into reality was dispelled, insightfulness into reality arose, 
darkness was dispelled, light arose

_avijjā vihatā vijjā uppannā tamo vihato āloko uppanno_
____

____
I directed my mind towards the knowledge of the destruction of perceptually 
obscuring states.

__āsavānaṃ khayañāṇāya cittaṃ abhininnāmesiṃ._
____

____
... thus knowing, thus seeing, my mind was freed from the three perceptually 
obscuring states.

_Tassa me evaṃ jānato evaṃ passato kāmāsavā pi cittaṃ vimuccittha. 
Bhavāsavā pi cittaṃ vimuccittha. Avijjāsavā pi cittaṃ vimuccittha._
____

____
With release, there was the knowledge I was released. I knew that birth was 
destroyed. The religious life has been fulfilled. What had to be done has been 
done. There will be no further arising in any state of individual existence

_Vimuttasmiṃ vimuttami ti ñāṇaṃ ahosi. Khīṇā jāti vusitaṃ 
brahmacariyaṃ kataṃ karaṇīyaṃ nāparaṃ itthattāyāti 
abbhaññāsiṃ._
____

____
This was, brahman, the third final knowledge attained by me in the last watch 
of the night.

_Ayaṃ kho me brāhmaṇa rattiyā pacchime yāme tatiyā vijjā adhigatā_
____

[quote, Vin.3.3-4]
____
Uninsightfulness into reality was dispelled, insightfulness into reality arose, 
darkness was dispelled, light arose.

_avijjā vihatā vijjā uppannā tamo vihato āloko uppanno._
____

.Illustration
====
tevijjaṃ

master of threefold knowledge; tevijjo brāhmaṇo, Brahman master of threefold 
Vedic knowledge
====

____
One who knows his past lives, who sees heaven and the plane of sub-human 
existence, and has attained the destruction of birth, is a sage who has 
achieved supernormal attainments.

_Pubbenivāsaṃ yo vedi saggāpāyañca passati +
Atho jātikkhayaṃ patto abhiññā vosito muni._
____

____
By these three final knowledges one is a Brahman master of threefold Vedic 
knowledge.

_Etāhi tīhi vijjāhi tevijjo hoti brāhmaṇo_
____

[quote, A.1.168]
____
He is the [true] master of threefold Vedic knowledge, I declare, not the one 
who [merely] recites recitations

_Tamahaṃ vadāmi tevijjaṃ nāññaṃ lapitalāpanan ti._
____

Comment:

The Buddha here calls arahants 'Brahman masters of threefold Vedic knowledge.' 
We capitalise Brahman to indicate arahantship.

.Illustration
====
tevijjā

masters of threefold Vedic knowledge; tevijjaṃ threefold knowledge
====

____
The brahman masters of threefold Vedic knowledge, when physically sitting they 
are spiritually sinking, and in spiritually sinking they arrive at dejection, 
all the while thinking they are crossing into some happier land.

_tevijjā brāhmaṇā āsīditvā saṃsīdanti saṃsīditvā visādaṃ vā 
pāpuṇanti. Sukkhataraṇaṃ maññe pataranti._
____

[quote, D.1.248]
____
Thus this threefold knowledge of such brahmans is called the threefold 
knowledge of a waterless desert, the threefold knowledge of a pathless jungle, 
the threefold knowledge of disasterous misfortune.

_tasmā idaṃ tevijjānaṃ brāhmaṇānaṃ tevijjaṃ iraṇan ti pi 
vuccati tevijjaṃ vipinan ti pi vuccati tevijjaṃ vyasanan ti pi vuccatī ti._
____

.Illustration
====
tevijjo

master of the three final knowledges
====

[quote, Thī.v.251]
____
Formerly I was Brahmā's offspring, today I am a true Brahman, a master of the 
three final knowledges, endowed with profound knowledge, fully versed in 
profound knowledge, spiritually cleansed.

_Brahmabandhu pure āsiṃ ajjamhi saccabrāhmaṇo +
Tevijjo vedasampanno sottiyo camhi nahātako ti._
____

