== Tādin; Tādisa

=== Renderings

- _tādin_: the same

- _tādin_: one of such good qualities

- _tādin_: one of excellent qualities

- _tādin_: one like this

- _tādin_: such a one

- _tādisa_: of the same character

- _tādisa_: such a person

- _tādisa_: one like you

=== Introduction

==== Tādin: 'one of excellent qualities'

The meaning of _tādin_ can usually be understood from the context. Where we 
call it 'one of such good qualities,' it refers to qualities just mentioned. 
Sometimes, however, there are no such qualities mentioned, and so we say 'one 
of excellent qualities,' which is a natural development of the same idea. PED 
calls this _tādin_'s 'pregnant sense.'

Other translators resolve the issue in similar ways. PED says _tādin_ means 
'of such (good) qualities, "ecce homo"; in pregnant sense appl. to the 
Bhagavant & Arahants.' Norman calls it 'the venerable one,' and explains 'The 
word seems to mean "of such a kind=Buddha-like, or holy, venerable"' (Elders' 
Verses n.41).

==== Tādin and Tādisa: relationship

_Tādin_ is 'a reduction' of _tādisa_, says PED.

=== Illustrations

.Illustration
====
tādī

the same
====

[quote, Sn.v.712]
____
'[He would reflect:] "Since I received something, that is alright," or "Since I 
received nothing, that is good." Being the same in either event, he [would] 
return to that same tree.

_Alatthaṃ yadidaṃ sādhu nālatthaṃ kusalaṃ iti +
Ubhayeneva so tādī rukkhaṃvupanivattati._
____

.Illustration
====
tādino

one like this
====

&#8203;[The yakkha Sātāgira:]

-- 'Today is the Observance Day on the fifteenth day [of the half-month]. It is 
a magnificent night. Come on, let's go and see Gotama, the teacher with exalted 
appellatives.'

&#8203;[The yakkha Hemavata:]

[quote, Sn.v.154]
____
-- 'But is the mind of one like this favourably disposed to all beings?'

_Kacci mano supaṇihito sabbabhūtesu tādino._
____

.Illustration
====
tādi

such a one
====

____
A householder who offers gifts, seeking merit, looking for merit, devoted to 
charity, a liberal benefactor, giving food and drink to others in this world, 
such a one would succeed in his quest on account of those who are worthy to 
receive offerings.

_Yo yācayogo dānapati gahaṭṭho puññatthiko yajati puññapekkho +
Dadaṃ paresaṃ idha annapānaṃ ārādhaye dakkhiṇeyyebhi tādi_
____

.Illustration
====
tādī

one of such good qualities
====

[quote, Sn.v.519]
____
'One who spurns all unvirtuous deeds; who is free of [the three] spiritual 
stains; who is virtuous, inwardly collected, and inwardly unshakeable; who has 
transcended the round of birth and death; who is spiritually perfected, and 
free of attachment: the one of such good qualities is called a Brahman.

_Bāhitvā sabbapāpakāni vimalo sādhu samāhito ṭhitatto +
Saṃsāramaticca kevalī so asito tādi pavuccate sa brahmā._
____

.Illustration
====
tādī

one of such good qualities
====

[quote, Sn.v.803]
____
A Brahman is not to be gauged by his observances and practices. Gone to the Far 
Shore, one of such good qualities does not return.

_Na brāhmaṇo sīlavatena neyyo pāragato na pacceti tādī ti._
____

.Illustration
====
tādinā

one of excellent qualities
====

[quote, Th.v.878]
____
I was tamed without rod or blade by one of excellent qualities.

_Adaṇḍena asatthena ahaṃ dantomhi tādinā._
____

.Illustration
====
tādinā

one of excellent qualities
====

[quote, Sn.v.697]
____
Having been instructed by one of excellent qualities who was intent on his 
&#8203;[nephew's] spiritual well-being, who foresaw the [possibility of the] highest 
state of purity in the future [for him], then Nālaka, with a heap of 
accumulated merit, with sense faculties supervised [by mindfulness], awaited 
the Conqueror expectantly.

_Tenānusiṭṭho hitamanena tādinā anāgate paramavisuddhadassinā +
So nālako upacitapuññasañcayo jinaṃ patikkhaṃ parivasi rakkhitindriyo._
____

.Illustration
====
tādisaṃ

of the same character
====

[quote, Sn.v.112]
____
'He who puts in a position of authority an alcoholic or spendthrift woman, or a 
man of the same character, that is the cause of spiritual ruination.'

_Itthisoṇḍiṃ vikiraṇiṃ purisaṃ vāpi tādisaṃ +
Issariyasmiṃ ṭhāpeti taṃ parābhavato mukhaṃ._
____

.Illustration
====
tādisaṃ

such a person
====

[quote, Sn.v.317]
____
The wise and diligent man who associates with such a person, by carefully 
practising in accordance with the teaching as a matter of vital concern, he 
becomes knowledgeable, astute, and intelligent.

_Tadaṭṭhikatvāna nisamma dhīro dhammānudhammaṃ paṭipajjamāno +
Viññū vibhāvī nipuṇo ca hoti yo tādisaṃ bhajati appamatto._
____

.Illustration
====
tādisaṃ

one like you
====

[quote, Sn.v.459]
____
Then certainly this offering will have a good result since we have seen one 
like you who is [so] knowledgeable.'

_Addhā hi tassa hutamijjhe yaṃ tādisaṃ vedagumaddasāma._
____

