== Ubhatobhāgavimutto; Paññāvimutto; Paññāvimuttin; Cetovimuttin

=== Renderings

- _ubhatobhāgavimutto_: one who is liberated [from perceptually obscuring 
states] both through [penetrative discernment and through attaining the 
immaterial states of awareness]

- _paññāvimutto_: one who is liberated [from perceptually obscuring states] 
through penetrative discernment

- _paññāvimuttin_: one who is liberated [from uninsightfulness] through 
penetrative discernment

- _cetovimuttin_: one who is liberated [from attachment through inward calm]

=== Introduction

==== Paths to arahantship

Arahantship is gained either 1) by first attaining the four jhānas or 2), by 
first attaining the immaterial states of awareness, says the _Jhānanissaya 
Sutta_:

[quote, A.4.422]
____
The destruction of perceptually obscuring states depends on [attaining] 
first jhāna, I declare... depends on [attaining] the state of awareness of 
boundless space, I declare... etc.

_Paṭhamampahaṃ bhikkhave jhānaṃ nissāya āsavānaṃ khayaṃ 
vadāmi... Ākāsānañcāyatanampahaṃ bhikkhave nissāya āsavānaṃ 
khayaṃ vadāmi..._
____

This gives rise to two types of arahants: _ubhatobhāgavimutto_ and 
_paññāvimutto_:

1. If arahantship is gained through the immaterial states of awareness, the 
bhikkhu is called 'one who is liberated [from perceptually obscuring states] 
both through [penetrative discernment and through attaining the immaterial 
states of awareness]' (_ubhatobhāgavimutto_). The following passage is the 
basis of us saying this:
+
[quote, M.1.477-9]
____
And what is the individual liberated [from perceptually obscuring states] both 
through [penetrative discernment and through attaining the immaterial states of 
awareness]?

_Katamo ca bhikkhave puggalo ubhatobhāgavimutto_

... In this regard, some person abides touching with his very being those 
immaterial states of awareness, those peaceful states of refined awareness that 
transcend the refined material states of awareness, and by seeing [reality] 
with penetrative discernment, his perceptually obscuring states are destroyed.

_idha bhikkhave ekacco puggalo ye te santā vimokkhā atikkamma rūpe āruppā 
te kāyena phassitvā viharati paññāya cassa disvā āsavā parikkhīṇā 
honti._
____

2. If arahantship is gained through the jhānas, the bhikkhu is called 'one who 
is liberated [from perceptually obscuring states] through penetrative 
discernment' (_paññāvimutto_). The following passage is the basis of us 
saying this:
+
[quote, M.1.477-9]
____
And what is the individual liberated [from perceptually obscuring states] 
through penetrative discernment?

_Katamo ca bhikkhave puggalo paññāvimutto_

... In this regard, some person does not abide touching with his very being 
those immaterial states of awareness, those peaceful states of refined 
awareness that transcend the refined material states of awareness, but by 
seeing [reality] with penetrative discernment, his perceptually obscuring 
states are destroyed.

_idha bhikkhave ekacco puggalo ye te santā vimokkhā atikkamma rūpe āruppā 
te na kāyena phassitvā viharati paññāya cassa disvā āsavā 
parikkhīṇā honti._
____

==== Paññāvimutti and Cetovimutti: review

Regarding _paññāvimutti_ and _cetovimutti,_ we have shown (sv _Cetovimutti_) 
that:

1. the terms mean:

- _paññāvimutti_: liberation [from uninsightfulness] through penetrative 
discernment

- _cetovimutti_: liberation [from attachment through inward calm]

2. _paññāvimutti_ and _cetovimutti_ correspond to _vipassanā_ 
('insightfulness') and _samatha_ ('inward calm') respectively.

3. the terms do not necessarily imply arahantship. So the enlightened 
connotations of _paññāvimutti_ do not necessarily apply to _paññāvimutto_.

==== Paññāvimuttin and Cetovimuttin

Therefore let us now consider _paññāvimuttin_ and _cetovimuttin_ which occur 
only in the _Mahāmāluṅkya Sutta_. The terms stem etymologically from 
_paññāvimutti_ and _cetovimutti_ and therefore mean:

- _paññāvimuttin_: one who is liberated [from uninsightfulness] through 
penetrative discernment

- _cetovimuttin_: one who is liberated [from attachment through inward calm]

In the _Mahāmāluṅkya Sutta_, after the Buddha had explained the path and 
practice to abandon the five ties to individual existence in the low plane of 
existence, Ānanda enquired:

____
-- Bhante, if this is the path and practice to abandon the five ties to 
individual existence in the low plane of existence, then how is that some 
bhikkhus here are liberated [from attachment through inward calm] 
(_cetovimuttino_), while some are liberated [from uninsightfulness] through 
penetrative discernment (_paññāvimuttino_)?

_Eso ce bhante maggo esā paṭipadā pañcannaṃ orambhāgiyānaṃ 
saṃyojanānaṃ pahānāya atha kiñcarahi idhekacce bhikkhū cetovimuttino 
ekacce bhikkhū paññāvimuttino ti._
____

[quote, M.1.437]
____
-- The difference here, Ānanda, is in their [mental] faculties, I declare.

_Ettha kho tesāhaṃ ānanda indriyavemattataṃ vadāmī ti._
____

This confirms that the _paññāvimuttin_ and _cetovimuttin_ are not 
necessarily arahants, unlike the _paññāvimutto._

==== Commentary: -mutto and -muttin

The commentary to the _Mahāmāluṅkya Sutta_ says: _Samathavaseneva hi 
gacchantesu ekassa bhikkhuno cittekaggatā dhuraṃ hoti so cetovimutto nāma 
hoti. Ekassa paññā dhuraṃ hoti, so paññāvimutto nāma hoti. 
Vipassanāvaseneva ca gacchantesu ekassa paññā dhuraṃ hoti, so 
paññāvimutto nāma hoti._

Thus it mistakenly says _paññāvimutto_ and _cetovimutto_ where Ānanda had 
said _paññāvimuttino_ and _cetovimuttino_. Nonetheless, it correctly links 
_paññāvimutto_ to _vipassanā_, and _cetovimutto_ to _samatha._

=== Illustrations

.Illustration
====
paññāvimutto

liberated [from perceptually obscuring states] through penetrative discernment
====

____
The Perfect One, the Arahant, the Perfectly Enlightened One, who is liberated 
&#8203;[from perceptually obscuring states] through being without grasping, through 
disillusionment with, non-attachment to, and the ending of bodily form, is 
called the Perfectly Enlightened One.

_Tathāgato bhikkhave arahaṃ sammāsambuddho rūpassa nibbidā virāgā 
nirodhā anupādāvimutto sammāsambuddhā ti vuccati_
____

[quote, S.3.65]
____
Likewise, the bhikkhu who is liberated [from perceptually obscuring states] 
through penetrative discernment, through disillusionment with, non-attachment 
to, and the ending of bodily form, is called one who is liberated [from 
perceptually obscuring states] through penetrative discernment.

_bhikkhūpi bhikkhave paññāvimutto rūpassa nibbidā virāgā nirodhā 
anupādā vimutto paññāvimutto ti vuccati._
____

.Illustration
====
paññāvimuttassa

liberated [from perceptually obscuring states] through penetrative discernment
====

[quote, Sn.v.847]
____
For one who is liberated [from perceptually obscuring states] through 
penetrative discernment there is no undiscernment of reality.

_paññāvimuttassa na santi mohā._
____

.Illustration
====
vimuttaṃ ubhatobhāge

liberated [from perceptually obscuring states] both through [penetrative 
discernment and through attaining the immaterial states of awareness]
====

[quote, Th.v.1176]
____
Look at this good-looking Sāriputta coming, liberated [from perceptually 
obscuring states] both through [penetrative discernment and through attaining 
the immaterial states of awareness], inwardly well-collected.

_Imañca passa āyantaṃ sāriputtaṃ sudassanaṃ +
Vimuttaṃ ubhatobhāge ajjhattaṃ susamāhitaṃ._
____

