== Uddhacca; Uddhata

=== Renderings

- _uddhacca_: restlessness

- _uddhata_: restless

- _uddhacca_: agitation

- _uddhata_: agitated

- _uddhacca_: vanity

- _uddhata_: vain

- _dhammuddhacca_: righteous disquietude

=== Introduction

==== The problem of uddhacca

The problem of _uddhacca_ is illustrated in Bodhi's rendering of _uddhacca_, 
both the fourth hindrance and the ninth fetter, as 'restlessness,' and Norman's 
rendering both cases as 'conceit' (e.g. Thī.v.167, Th.v.1010, Th.v.760).

Strangely, DOP does not recognise 'conceit' for _uddhacca_ in spite of 
accepting 'puffed up' for _uddhata_, and acknowledging that _uddhacca_ is 
derived from _uddhata_.

==== The problem with restlessness

The five hindrances are hindrances to samādhi, and non-returners have perfect 
samādhi (_samādhismiṃ paripūrakārī hoti_, A.1.232) which implies that 
the five hindrances including _uddhacca_ are insignificant in non-returners. 
And yet non-returners are still troubled by _uddhacca_ the ninth fetter. So the 
two forms of _uddhacca_ must be different, and it is unlikely that the 
restlessness of the fourth hindrance is also the ninth fetter.

==== The problem with conceit

But Norman's suggestion is also problematic, because it implies that the 
hindrance to first jhāna would remain active until arahantship, when the ninth 
tie to individual existence is finally abandoned. Unless conceit can be 
temporarily quelled like lust and hatred, first jhāna would only be available 
to arahants. So again, _uddhacca_ must have two meanings.

==== Double meanings of uddhata and capala

Part of the confusion is that both _uddhata_ and _capala_ which frequently 
occur together, have double meanings, as follows:

Grouping 1:

- _uddhata_: restless

- _capala_: fidgety/fluttery

Grouping 2:

- _uddhata_: vain

- _capala_: puffed up

==== Uddhata and capala: illustrated

The meanings of _uddhacca_ and _capala_ can be illustrated as follows:

1. _uddhata_: restless

• When one's mind is restless it is timely to develop the enlightenment 
factors of tranquillity, inward collectedness, and detached awareness. +
☸ _Yasmiṃ bhikkhave samaye uddhataṃ cittaṃ hoti kālo tasmiṃ samaye 
passaddhisambojjhaṅgassa bhāvanāya_... (S.5.115).

2. _capala_: fluttery

[quote, Dh.v.33]
____
Like a fletcher straightens an arrow, the wise man straightens up his unsteady, 
fluttery mind, which is hard to supervise, hard to restrain.

_Phandanaṃ capalaṃ cittaṃ durakkhaṃ dunnivārayaṃ +
Ujuṃ karoti medhāvī usukāro va tejanaṃ._
____

3. _uddhato_: vain; _capalo_: puffed up

[quote, Th.v.1080]
____
A vain, puffed up bhikkhu clothed in rag-robes does not look glorious because 
of it. He is like a monkey in a lion-skin.

_Uddhato capalo bhikkhu paṃsukūlena pāruto +
Kapīva sīhacammena na so tenupasobhati._
____

4. _uddhato_: vain; _capalo_: puffed up

[quote, Th.v.157]
____
Because of improper contemplation I was addicted to finery. I was vain, puffed 
up, and afflicted by lust for sensuous pleasure.

_Ayoniso manasikārā maṇḍanaṃ anuyuñjisaṃ +
Uddhato capalo cāsiṃ kāmarāgena aṭṭito._
____

==== Dutiya Anuruddha Sutta: tranquility and peace are not 'restlessness'

An interesting muddle occurs in the _Dutiya Anuruddha Sutta_ (A.1.282), where 
Venerable Anuruddha complained about his slowness in attaining arahantship in 
spite of outstanding spiritual qualities. Venerable Sāriputta told him:

____
'Anuruddha, when you say "With purified divine vision surpassing that of men, I 
survey the thousandfold multi-universe system," that is your self-centredness 
(_māna_).

_Yaṃ kho te āvuso anuruddha evaṃ hoti: evāhaṃ dibbena cakkhunā 
visuddhena atikkantamānusakena sahassaṃ lokaṃ olokemī ti idante 
mānasmiṃ._
____

____
... 'When you say "My unflagging energy is aroused, unmuddled mindfulness is 
established, my body is tranquil and peaceful, my mind is collected and 
concentrated," that is your vanity (_uddhacca_).

_Yampi te āvuso anuruddha evaṃ hoti: āraddhaṃ kho pana me viriyaṃ 
asallīnaṃ upaṭṭhitā sati apammuṭṭhā passaddho kāyo asāraddho 
samāhitaṃ cittaṃ ekaggan ti idante uddhaccasmiṃ_
____

[quote, A.1.282]
____
... 'When you say "But for all that my mind is not liberated from perceptually 
obscuring states through being without grasping," that is your fretting 
(_kukkucca_).

_Yampi te āvuso anuruddha evaṃ hoti atha ca pana me na anupādāya āsavehi 
cittaṃ vimuccatī ti idante kukkuccasmiṃ._
____

It makes little sense to say that claiming one's body is tranquil and peaceful 
can be explained as restlessness (_uddhacca_), as Bodhi puts it. DOP's 
suggestion 'puffed up' is preferable, using 'vanity' as the noun for 
'puffed-upness.'

==== Causes of the fourth hindrance

The causes of _uddhacca_, the fourth hindrance, are:

1. Excessive exertion: if a meditator focuses excessively on the practice of 
effort, it leads to restlessness (_ekantaṃ paggahanimittaññeva 
manasikareyya ṭhānaṃ taṃ cittaṃ uddhaccāya saṃvatteyya_). The 
suttas say it is like a goldsmith who, if he blows too much on molten gold will 
simply burn it up.

2. No inward collectedness: Just as the goldsmith should sprinkle gold with 
water to keep it cool, the meditator should from time to time focus on the 
practice of inward collectedness (_kālena kālaṃ samādhinimittaṃ 
manasikātabbaṃ_) (A.1.256) or inward peacefulness (_cetaso vūpasamo_) 
(S.5.106) because this removes restlessness (_uddhaccassa pahānāya samatho 
bhāvetabbo_) (A.3.449).

3. Argumentative speech (_viggāhikakathaṃ_): this leads to overtalkativeness 
(_kathābāhullaṃ_). With overtalkativeness comes restlessness 
(_kathābāhulle sati uddhaccaṃ_) (A.4.87).

==== Agitation

Occasionally _uddhacca_ means 'agitation', not restlessness. For example, the 
Buddha said a bhikkhu should visit families in a humble manner, lest he be 
embarrassed if he receives nothing:

____
And so, from getting nothing, he becomes embarrassed _

_Itissa alābhena maṅkubhāvo_
____

____
... Being embarrassed, he becomes agitated

_maṅkubhūtassa uddhaccaṃ_
____

[quote, A.4.87]
____
... Being agitated, his sense faculties are unrestrained [from attraction and 
repulsion, through mindfulness]

_uddhatassa asaṃvaro._
____

==== Righteous disquietude: dhammuddhacca

One form of _uddhacca_ is called righteous disquietude (_dhammuddhacca_). It 
comprises the fourth path to arahantship. The first three paths are:

____
insightfulness preceded by inward calm

_samathapubbaṅgamaṃ vipassanaṃ_
____

____
inward calm preceded by insightfulness

_vipassanāpubbaṅgamaṃ samathaṃ_
____

____
inward calm together with insightfulness

_samathavipassanaṃ yuganaddhaṃ_
____

The fourth path is described as follows:

• Or a bhikkhu's mind is seized by righteous disquietude +
_bhikkhuno dhammuddhaccaviggahītaṃ mānaṃ hoti_

• ... But there comes a time when his mind becomes settled, calm, 
concentrated, and collected. +
_so samayo yantaṃ cittaṃ ajjhattaṃyeva santiṭṭhati sannisīdati ekodi 
hoti samādhiyati._

• ... In him the path is born +
_tassa maggo sañjāyati_ (A.2.157).

Therefore _dhammuddhacca_ is abandoned at stream-entry when the path is born, 
because:

[quote, S.5.348]
____
One possessed of this noble eightfold path, bhante, is called a stream-enterer.

_Yo hi bhante iminā ariyena aṭṭhaṅgikena maggena samannāgato ayaṃ 
vuccati sotāpanno._
____

==== Dhammuddhacca: a synonym for saṃvega

_Dhammuddhacca_ is perhaps a synonym for _saṃvega_. It could therefore be 
illustrated by this account of practice:

____
Seeing sensuous pleasures as [dangerous as] a blazing [grass torch being 
carried against the wind], and gold pieces as [dangerous as a sharp] knife, and 
life from the time of conception as suffering, and great danger in the 
&#8203;[possibility of the] hells,

_Kāme ādittato disvā jātarūpāni satthato +
Gabbhavokkantito dukkhaṃ nirayesu mahabbhayaṃ._
____

____
... Recognising this danger, I was filled with an earnest attitude [to the 
practice].

_Etamādīnavaṃ ñatvā saṃvegaṃ alabhiṃ tadā_
____

[quote, Th.v.790-1]
____
... I was quickened then peaceful. I have accomplished the destruction of 
perceptually obscuring states.

_Sohaṃ viddho tadā santo sampatto āsavakkhayaṃ._
____

COMMENT

Norman has said (Elders' Verses note 791) that 'it is possible that _viddha_ is 
the equivalent of _vyathita_, the past participle of _vyath_- "shaken." The 
context supports us treating it as standing for the past participle of 
_saṃvijjati_, to be quickened.

=== Illustrations

.Illustration
====
uddhacca

restlessness; anuddhato, not restless
====

[quote, M.1.521]
____
Abandoning restlessness and anxiety, he abides not restless, with a mind 
inwardly at peace. He purifies his mind of restlessness and anxiety.

_uddhaccakukkuccaṃ pahāya anuddhato viharati ajjhattaṃ vūpasantacitto. 
Uddhaccakukkuccā cittaṃ parisodheti._
____

.Illustration
====
uddhaccāya

restlessness
====

[quote, A.3.376]
____
If one's energy is excessive it leads to restlessness; if too lax it leads to 
indolence.

_accāraddhaṃ viriyaṃ uddhaccāya saṃvattati atilīnaṃ viriyaṃ 
kosajjāya saṃvattati._
____

.Illustration
====
uddhacca

restlessness
====

____
There is inward unpeacefulness. Much improper contemplation in that regard is a 
condition that nourishes both the arising of unarisen restlessness and anxiety, 
and the increase and expansion of arisen restlessness and anxiety.

_Atthi bhikkhave cetaso avūpasamo. Tattha ayoniso manasikārabahulīkāro 
ayamāhāro anuppannassa vā uddhaccakukkuccassa uppādāya uppannassa vā 
uddhaccakukkuccassa bhiyyobhāvāya vepullāya._
____

[quote, S.5.105-6]
____
There is inward peacefulness. Much proper contemplation in that regard is not a 
condition that nourishes either the arising of unarisen restlessness and 
anxiety, or the increase and expansion of arisen restlessness and anxiety.

_Atthi bhikkhave cetaso vūpasamo. Tattha yoniso manasikārabahulīkāro 
ayamanāhāro anuppannassa vā uddhaccakukkuccassa uppādāya uppannassa vā 
uddhaccakukkuccassa bhiyyobhāvāya vepullāya._
____

.Illustration
====
uddhacca

restlessness
====

____
And what is investigation that is too lax?

_atilīnā vīmaṃsā_
____

____
It is investigation accompanied by indolence, conjoined with indolence. This is 
called investigation that is too lax.

_yā bhikkhave vīmaṃsā kosajjasahagatā kosajjasampayuttā. Ayaṃ vuccati 
bhikkhave atilīnā vīmaṃsā._
____

____
And what is investigation that is too strained?

_atipaggahitā vīmaṃsā_
____

[quote, S.5.280]
____
It is investigation accompanied by restlessness, conjoined with restlessness. 
This is called investigation that is too strained.

_yā bhikkhave vīmaṃsā uddhaccasahagatā uddhaccasampayuttā. Ayaṃ 
vuccati bhikkhave atipaggahitā vīmaṃsā._
____

.Illustration
====
uddhacca

restlessness
====

Suppose, brahman, there is a bowl of water stirred by wind. If a clear-sighted 
man were to examine his facial reflection in it, he would neither discern nor 
see it according to reality.

[quote, S.5.123-4]
____
So too, brahman, when one dwells with a mind absorbed in and overcome by 
restlessness and anxiety, and does not discern according to reality the 
deliverance from the arisen restlessness and anxiety, one does not know or see 
either one's own well-being, or that of others, or that of both.

_yasmiṃ samaye uddhaccakukkuccapariyuṭṭhitena cetasā viharati 
uddhaccakukkuccaparetena uppannassa ca uddhaccakukkuccassa nissaraṇaṃ 
yathābhūtaṃ nappajānāti._
____

.Illustration
====
uddhataṃ

restless
====

• When one's mind is restless (_uddhataṃ cittaṃ_) it is timely to develop 
the enlightenment factors of tranquillity, inward collectedness, and detached 
awareness. +
☸ _Yasmiṃ bhikkhave samaye uddhataṃ cittaṃ hoti kālo tasmiṃ samaye 
passaddhisambojjhaṅgassa bhāvanāya_... _samādhisambojjhaṅgassa... 
upekkhāsambojjhaṅgassa bhāvanāya_

• For what reason? Because the mind is restless and it is easy to calm it 
with those things +
☸ __uddhataṃ bhikkhave cittaṃ. Taṃ etehi dhammehi suvūpasamaṃ hot__i 
(S.5.115).

.Illustration
====
uddhatā

restless
====

[quote, A.3.355]
____
These people say, "We are study bhikkhus, we are study bhikkhus,' but they are 
restless, frivolous, fidgety, talkative, garrulous, unmindful, not fully 
conscious, inwardly uncollected, mentally scattered, [and are dwelling with] 
their sense faculties unrestrained [from attraction and repulsion, through 
mindfulness].

_ime pana dhammayogamhā dhammayogamhā ti uddhatā unnaḷā capalā mukharā 
vikiṇṇavācā muṭṭhassatī asampajānā asamāhitā vibbhantacittā 
pākatindriyā._
____

.Illustration
====
uddhaccaṃ

agitated
====

[quote, S.4.87]
____
When there is contentious talk, an excess of words can be expected. When there 
is an excess of words, one becomes agitated. When one is agitated, one's sense 
faculties are unrestrained [from attraction and repulsion, through mindfulness].

_Viggāhikāya moggallāna kathāya sati kathābāhullaṃ pāṭikaṅkhaṃ. 
Kathābāhulle sati uddhaccaṃ. Uddhatassa asaṃvaro._
____

.Illustration
====
uddhaccaṃ

vanity
====

• Bhikkhus, there are these five ties to individual existence in the middle 
and high planes of existence. What five? +
_pañcimāni bhikkhave uddhambhāgiyāni saṃyojanāni. katamāni pañca?_

____
attachment to the refined material states of awareness _

_rūparāgo_
____

____
attachment to immaterial states of awareness _

_arūparāgo_
____

____
self-centredness _

_māno_
____

____
vanity _

_uddhaccaṃ_
____

[quote, S.5.61-62]
____
uninsightfulness into reality _

_avijjā._
____

.Illustration
====
uddhaccasmiṃ

vanity
====

____
-- 'Anuruddha, friend, when you say "With purified divine vision surpassing 
that of men, I survey the thousandfold multi-universe system," that is your 
self-centredness.

_Yaṃ kho te āvuso anuruddha evaṃ hoti: evāhaṃ dibbena cakkhunā 
visuddhena atikkantamānusakena sahassaṃ lokaṃ olokemī ti idante 
mānasmiṃ._
____

____
'When you say "My unflagging energy is aroused, unmuddled mindfulness is 
established, my body is tranquil and peaceful, my mind is collected and 
concentrated," that is your vanity.

_Yampi te āvuso anuruddha evaṃ hoti: āraddhaṃ kho pana me viriyaṃ 
asallīnaṃ upaṭṭhitā sati apammuṭṭhā passaddho kāyo asāraddho 
samāhitaṃ cittaṃ ekaggan ti idante uddhaccasmiṃ_
____

[quote, A.1.282]
____
'When you say "But for all that my mind is not liberated from perceptually 
obscuring states through being without grasping," that is your fretting.

_Yampi te āvuso anuruddha evaṃ hoti atha ca pana me na anupādāya āsavehi 
cittaṃ vimuccatī ti idante kukkuccasmiṃ._
____

.Illustration
====
uddhato

vain
====

[quote, Th.v.1080]
____
A vain, puffed up bhikkhu clothed in rag-robes does not look glorious because 
of it. He is like a monkey in a lion-skin.

_Uddhato capalo bhikkhu paṃsukūlena pāruto +
Kapīva sīhacammena na so tenupasobhati._
____

[quote, Th.v.1081]
____
One who is not vain or puffed up, who is mindful, whose sense faculties are 
restrained [from attraction and repulsion, through mindfulness], looks glorious 
in rag-robes. He is like a lion in a mountain cave.

_Anuddhato acapalo nipako saṃvutindriyo +
Sobhati paṃsukūlena sīho va girigabbhare._
____

.Illustration
====
uddhatā

vain
====

[quote, Th.v.958]
____
They will be vain, clothed in blue robes, deceitful, puffed up, talkative, and 
haughty. They will live the religious life as though they were Noble Ones.

_Uddhatā ca bhavissanti nīlacīvarapārutā +
Kuhā thaddhā lapā siṅgī carissantyariyā viya._
____

.Illustration
====
uddhato

vain
====

[quote, Th.v.157]
____
Because of improper contemplation I was addicted to finery. I was vain, puffed 
up, and afflicted by lust for sensuous pleasure.

_Ayoniso manasikārā maṇḍanaṃ anuyuñjisaṃ +
Uddhato capalo cāsiṃ kāmarāgena aṭṭito._
____

