== Ujjhāyati khīyati vipāceti

=== Renderings

- _ujjhāyati khīyati vipāceti_: to complain, mutter, and grumble

=== Introduction

==== Audible sounds

_Ujjhāyati khīyati vipāceti_ mean making verbal complaints that others can 
hear:

[quote, Vin.2.129]
____
When bhikkhus heard that woman complaining, muttering, and grumbling, they 
explained the matter to the Blessed One.

_Assosuṃ kho bhikkhū tassā itthiyā ujjhāyantiyā khiyantiyā 
vipācentiyā. Atha kho te bhikkhu bhagavato etamatthaṃ ārocesuṃ._
____

==== Intransitive verbs and synonyms

_Ujjhāyati khīyati vipāceti_ are intransitive verbs, and likely synonyms.

[quote, S.1.237]
____
The more the devas complained, muttered, and grumbled, the more lovely, 
attractive, and handsome the yakkha became.

_Yathā yathā kho bhikkhave devā tāvatiṃsā ujjhāyanti khīyanti 
vipācenti tathā tathā so yakkho abhirūpataro ceva hoti dassanīyataro ca 
pāsādikataro ca._
____

==== Avoiding negative connotations

The words do not imply ridicule of the complainer, so 'whine' or 'gripe' are 
inappropriate.

=== Illustrations

.Illustration
====
ujjhāyanti khīyanti vipācenti

complained, muttered, and grumbled
====

[quote, Vin.1.194]
____
Once the Group-of-Six bhikkhus entered a village with their sandals on. People 
complained, muttered, and grumbled that they were like laymen devoted to 
sensuous pleasures.

_Tena kho pana samayena chabbaggiyā bhikkhu saupāhanā gāmaṃ pavisanti. 
Manussā ujjhāyanti khīyanti vipācenti seyyathā pi gihī kāmabhogino ti._
____

.Illustration
====
ujjhāyati khiyati vipāceti

complained, muttered, and grumbled
====

[quote, Vin.2.160]
____
The poor tailor complained, muttered, and grumbled that 'For the laypeople who 
give requisites, the bhikkhus advise, instruct, and organise their building 
work. But I am poor. No one advises or instructs me, or organises my building 
work.'

_Atha kho so daḷiddo tunnavāyo ujjhāyati khiyati vipāceti ye imesaṃ 
samaṇānaṃ sakyaputtiyānaṃ denti 
cīvara-piṇḍapāta-senāsana-gilānapaccayabhesajjaparikkhāraṃ te ime 
ovadanti anusāsanti tesañca navakammaṃ adhiṭṭhenti. Ahaṃ panamhi 
daḷiddo. Na maṃ koci ovadati vā anusāsati vā navakammaṃ vā 
adhiṭṭhetī ti._
____

.Illustration
====
ujjhāyanti khīyanti vipācenti

complained, muttered, and grumbled
====

[quote, Vin.2.107]
____
Bhikkhus examined a facial mark in a mirror and in a bowl of water. People 
complained, muttered, and grumbled that they were like laymen devoted to 
sensuous pleasures

__ādāse pi udakapatte pi mukhanimittaṃ olokenti. Manussā ujjhāyanti 
khīyanti vipācenti seyyathā pi gihī kāmabhogino ti._
____

.Illustration
====
ujjhāyati khiyati vipāceti

complained, muttered, and grumbled
====

[quote, Vin.3.237]
____
Having given the young Sakyan bhikkhu, Venerable Upananda, a _kahāpaṇa_ of 
money, that man complained, muttered, and grumbled that 'Just as we accept gold 
and silver, so do these ascetic disciples of the Sakyans' Son.

_Atha kho so puriso āyasmato upanandassa sakyaputtassa kahāpaṇaṃ datvā 
ujjhāyati khīyati vipāceti: yatheva mayaṃ rūpiyaṃ paṭiggaṇhāma 
evameva ime samaṇā sakyaputtiyā rūpiyaṃ paṭiggaṇhantī ti._
____

