== Unnaḷā

=== Renderings

- _unnaḷa_: frivolous

=== Introduction

==== Unnaḷa: frivolous

Many meanings have been ascribed to _unnaḷa_, but illustrations below show 
that Norman's 'frivolous' works well.

==== Collins Compact Dictionary: frivolous

1. not serious or sensible in content, attitude or behaviour.

2. unworthy of serious or sensible treatment

==== Webster's Dictionary: frivolous

1. of little weight or importance

2a) lacking in seriousness; irresponsibly self-indulgent

2b) marked by unbecoming levity

=== Illustrations

.Illustration
====
unnaḷā

frivolous
====

[quote, A.2.26; It.113]
____
Bhikkhus, those bhikkhus who are deceitful, puffed up, talkative, haughty, 
frivolous, inwardly uncollected, are not my bhikkhus.

_Ye te bhikkhave bhikkhū kuhā thaddhā lapā siṅgī unnaḷā asamāhitā 
na me te bhikkhave bhikkhū māmakā._
____

.Illustration
====
unnaḷassa

frivolous
====

[quote, Th.v.634]
____
The virtue, inward collectedness, and penetrative discernment of a bhikkhu who 
is frivolous, negligently applied [to the practice], and with hopes directed to 
external things, do not reach fulfilment.

_Unnaḷassa pamattassa bāhirāsassa bhikkhuno +
Sīlaṃ samādhi paññā ca pāripūriṃ na gacchati._
____

.Illustration
====
unnaḷānaṃ

frivolous
====

[quote, Th.v.635; Dh.v.292]
____
What should be done is shunned. What should be avoided is done. Of those who 
are frivolous and negligently applied [to the practice] their perceptually 
obscuring states increase.

_Yaṃ hi kiccaṃ tadapaviddhaṃ akiccaṃ pana kayirati +
Unnaḷānaṃ pamattānaṃ tesaṃ vaḍḍhanti āsavā._
____

.Illustration
====
unnaḷā

frivolous
====

[quote, Th.v.958]
____
Being frivolous, thin-skinned fools, unestablished in virtue, they will wander 
about like combative deer.

_Ujjhānasaññino bālā sīlesu asamāhitā +
Unnaḷā vicarissanti kalahābhiratā magā._
____

.Illustration
====
unnaḷo

frivolous
====

[quote, Th.v.973]
____
A vain, frivolous fool in whom no virtue is found deserves the white robe. What 
will he do with an ochre robe?

_Uddhato unnaḷo bālo sīlaṃ yassa na vijjati +
Odātakaṃ arahati kāsāvaṃ kiṃ karissati._
____

