== Upadduta; Upaddava

=== Renderings

- _upadduta_: ravaged [by old age and death]

- _upadduta_: attacked

- _upadduta_: undone

- _upadduta_: oppressed

- _upaddava_: undoing

- _upaddava_: misfortune

=== Introduction

==== Parenthesising upadduta: ravaged [by old age and death]

In the following quote we parenthesise '[by old age and death]':

[quote, Ven. Tāḷapuṭa, Th.v.1133]
____
The mountains, oceans, rivers, and the earth; the four directions, the 
intermediate points, the nadir, and the zenith, are all unlasting. The three 
planes of existence are ravaged [by old age and death]. Where having gone, 
mind, will you delight happily?

_Nagā samuddā saritā vasundharā disā catasso vidisā adho divā +
Sabbe aniccā tibhavā upaddutā kuhiṃ gato citta sukhaṃ ramissasi._
____

We say 'ravaged [by old age and death]' based on a similar word combination in 
Th.v.1093 by the same Tāḷapuṭa, who said there that the body is unlasting 
and ravaged by old age and death (_maccujarāyupaddutaṃ_):

[quote, Ven. Tāḷapuṭa, Th.v.1093]
____
When will I dwell alone in the woods, free of fear, seeing [according to 
reality] that this [wretched human] body is unlasting, a seat of punishment and 
illness, ravaged by old age and death? When, oh when, will it be?

_Kadā aniccaṃ vadharoganīḷaṃ kāyaṃ imaṃ maccujarāyupaddutaṃ +
Vipassamāno vītabhayo vihassaṃ eko vane taṃ nu kadā bhavissati._
____

==== Parenthesising upadduta: ravaged [by old age and death]

In the following quote we parenthesise '[by old age and death]':

____
All is ravaged [by old age and death]. What is the all that is ravaged [by old 
age and death]?_

_Sabbaṃ bhikkhave upaddutaṃ. Kiñca bhikkhave sabbaṃ upaddutaṃ_
____

[quote, S.4.28-9]
____
... The visual sense is ravaged, visible objects are ravaged, advertence to the 
visual field is ravaged, visual sensation is ravaged, whatever sense impression 
that arises due to visual sensation -- whether pleasant, unpleasant, or neutral 
-- that too is ravaged [by old age and death].

_cakkhuṃ bhikkhave upaddutaṃ rūpā upaddutā cakkhuviññāṇaṃ 
upaddutaṃ cakkhusamphasso upadduto yampidaṃ cakkhusamphassapaccayā 
uppajjati vedayitaṃ sukhaṃ vā dukkhaṃ vā adukkhamasukhaṃ vā tampi 
upaddutaṃ._
____

We parenthesise like this for two reasons:

1. Firstly, this sutta is placed in the scriptures in a sequence of similar 
suttas, as follows:

[quote, S.4.26-9]
____
All is subject to birth... subject to old age... subject to illness... subject 
to death... productive of grief... All is ravaged... All is afflicted.

_Sabbaṃ bhikkhave... jātidhammaṃ... jarādhammaṃ... vyādhidhammaṃ... 
maraṇadhammaṃ... sokadhammaṃ... upaddutaṃ... upassaṭṭhaṃ._
____

2. Secondly, it is comparable to the _Addabhūta Sutta_ which says:

____
All is conquered. What is the all that is conquered?_

_Sabbaṃ bhikkhave addhabhūtaṃ. Kiñca bhikkhave sabbaṃ addhabhūtaṃ?_
____

____
... The visual sense is conquered, visible objects are conquered, etc. .

_Cakkhuṃ bhikkhave addhabhūtaṃ rūpā addhabhūtā_
____

[quote, S.4.21]
____
... Conquered by what? Conquered by birth, old age, and death; by grief, 
lamentation, physical pain, psychological pain, and vexation, I declare.

_Kena addhabhūtaṃ: addhabhūtaṃ jātiyā jarāmaraṇena sokehi paridevehi 
dukkhehi domanassehi upāyāsehi addhabhūtanti vadāmi._
____

We refrain from saying 'All is ravaged [by birth, old age, and death; by grief, 
lamentation, physical pain, psychological pain, and vexation]' for three 
reasons:

1. Most of the elements are not ravaged by physical pain.

2. To say that 'phenomena are ravaged by birth' is incongruous.

3. It is consonant with Tāḷapuṭa's _maccujarāyupaddutaṃ_ (Th.v.1093).

==== Parenthesising upadduta: ravaged [by death]

In the following quote we parenthesise '[by death]':

____
Then Yasa, having awoken sooner than usual saw his retinue asleep: one with a 
lute in her arm, one with a tabor under her chin, one with a drum under her 
arm, one with dishevelled hair, one who was dribbling, and others who were 
muttering. One would think it was a charnel ground before one's eyes. Seeing 
this, the danger [of sensuous pleasure] became apparent to him. His mind was 
established in disillusionment [with sensuous pleasure].

_Atha kho yaso kulaputto paṭigacceva pabujjhitvā addasa sakaṃ parijanaṃ 
supantaṃ. Aññissā kacche vīṇaṃ. Aññissā kaṇṭhe mudiṅgaṃ. 
Aññissā kacche ālambaraṃ. Aññaṃ vikkesikaṃ aññaṃ vikkhelikaṃ. 
Aññā vippalapantiyo. Hatthappattaṃ susānaṃ maññe. Disvānassa 
ādīnavo pāturahosi. Nibbidāya cittaṃ saṇṭhāsi._
____

[quote, Vin.1.15]
____
Then Yasa, the noble young man, uttered the solemn reflection: 'Alas, [all] is 
ravaged [by death]. Alas, [all] is afflicted [by death].'

_Atha kho yaso kulaputto udānaṃ udānesi upaddutaṃ vata bho 
upassaṭṭhaṃ vata bho ti._
____

Comment:

We say '[all] is ravaged [by death]' for the following reasons:

1. 'All' is consonant with the association elsewhere of _upaddutaṃ_ and 
_upassaṭṭhaṃ_ and _sabbaṃ_:

[quote, S.4.29]
____
All is ravaged... All is afflicted.

_Sabbaṃ bhikkhave... upaddutaṃ... upassaṭṭhaṃ._
____

2. 'Death' is consonant with the charnel ground.

3. 'Death' is consonant with Tāḷapuṭa's _maccujarāyupaddutaṃ_ 
(Th.v.1093).

=== Illustrations: upadduta

.Illustration
====
upaddutaṃ

attacked
====

[quote, Vin.3.67]
____
The family which supported Venerable Pilindivaccha was attacked by thieves, and 
two children were kidnapped.

__āyasmato pilindivacchassa upaṭṭhākakulaṃ corehi upaddutaṃ hoti. Dve 
ca dārakā nītā honti._
____

.Illustration
====
upaddutā

oppressed
====

____
People were oppressed by the begging, oppressed by the hinting,

_Manussā upaddutā yācanāya upaddutā viññattiyā_
____

... So when they saw bhikkhus they were perturbed, then alarmed, and then ran 
away... and when they saw cows they ran away, imagining them to be bhikkhus 
(Vin.3.144).

.Illustration
====
upaddutā

oppressed
====

[quote, Vin.2.170]
____
The resident bhikkhus were oppressed by having to assign abodes for the 
incoming bhikkhus who arrived.

__āvāsikā bhikkhū upaddutā honti āgantukagamikānaṃ bhikkhūnaṃ 
senāsanaṃ paññāpentā._
____

.Illustration
====
upaddutā

oppressed
====

____
Enough, friends, do not weep and wail! We are well rid of that Great Ascetic.

_alaṃ āvuso mā sovittha mā paridevittha. Sumuttā mayaṃ tena 
mahāsamaṇena._
____

____
We were always oppressed by him saying: 'This is allowable for you. This is not 
allowable'

_Upaddutā ca homa idaṃ vo kappati idaṃ vo na kappatī ti._
____

[quote, D.2.162]
____
Now we can do what we like, and not do what we don't like!'

_Idāni pana mayaṃ yaṃ icchissāma taṃ karissāma yaṃ na icchissāma na 
taṃ karissāmā ti._
____

=== Illustrations: upaddava

.Illustration
====
anupaddave

undestroyed
====

[quote, Dh.v.338]
____
Just as a tree that is felled will grow back if its roots are undestroyed and 
uninjured....

_Yathā pi mūle anupaddave daḷhe chinno pi rukkho punareva rūhati._
____

.Illustration
====
upaddavo

undoing
====

____
Being visited by brahmans and householders from town and country, he becomes 
infatuated, falls in love, succumbs to greed, and reverts to luxury.

_So anvāvaṭṭantesu brāhmaṇagahapatikesu negamesu ceva jānapadesu ca 
mucchati nikāyamati gedhaṃ āpajjati āvaṭṭati bāhullāya._
____

____
This is called the teacher who is undone through the undoing of teachers.

_Ayaṃ vuccatānanda upaddavo ācariyo ācariyūpaddavena_
____

____
He has been struck down by unvirtuous, spiritually unwholesome factors that are 
defiling, and which lead to renewed states of individual existence, suffering, 
unpleasant karmic consequences, and future birth, old age, and death.

_avadhiṃsu naṃ pāpakā akusalā dhammā saṅkilesikā ponobhavikā 
sadarā dukkhavipākā āyatiṃ jātijarāmaraṇiyā_
____

[quote, M.3.116]
____
In this way a teacher's undoing comes to be._

_evaṃ kho ānanda ācariyūpaddavo hoti._
____

.Illustration
====
undone

upaddutā; undoing, upaddavena
====

[quote, S.2.210]
____
If, Kassapa, one speaking rightly could say: 'Those living the religious life 
have been undone by the undoing of those who live the religious life; those 
living the religious life have been crushed by the crushing of those who live 
the religious life': it is of the present time that one could rightly say it.

_Yaṃ hi taṃ kassapa sammāvadamāno vadeyya upaddutā brahmacārī 
brahmacārūpaddavena abhibhavanā brahmacārī brahmacārābhibhavanenā ti. 
etarahi hi taṃ kassapa sammāvadanto vadeyya upaddutā brahmacārī 
brahmacārupaddavena abhibhavanā brahmacārī brahmacārābhibhavanenā ti._
____

.Illustration
====
upaddavo

misfortune
====

[quote, Sn.v.51]
____
'For me, this [wretched sensuous pleasure] is an affliction, a carbuncle, a 
misfortune, an illness, a [piercing] arrow, a danger.' [Considering thus], 
seeing this danger in the varieties of sensuous pleasure, one should live the 
religious life as solitarily as a rhinoceros horn.

__Ītī ca gaṇḍo ca upaddavo ca rogo ca sallañca bhayañca metaṃ +
Etaṃ bhayaṃ kāmaguṇesu disvā eko care khaggavisāṇakappo._
____

.Illustration
====
saupaddavā

misfortune
====

____
Now, bhante, it is not proper or fitting. That quarter which should be without 
fear, affliction, and misfortune is the very quarter which is full of fear, 
affliction, and misfortune.

_idaṃ bhante nacchannaṃ nappatirūpaṃ. Yāyaṃ bhante disā abhayā 
anītikā anupaddavā sāyaṃ disā sabhayā saītikā saupaddavā._
____

[quote, Vin.2.79]
____
Where there was calm, now there is a gale. It seems the very water is blazing. 
I have been raped by Master Dabba the Mallian.

_Yato nivātaṃ tato pavātaṃ. Udakaṃ maññe ādittaṃ. Ayyenamhi 
dabbena mallaputtena dūsitā ti._
____

