== Upekkhā

=== Renderings

- _upekkhindriyaṃ_: the faculty of physical-plus-psychological neutral 
experience

- _gehasitā upekkhā_: laypersons' neutral attitude

- _upekkhā nekkhammasitā ti_: ascetics' neutral attitude

- _sāmisā upekkhā_: worldly neutral attitude

- _nirāmisā upekkhā_: unworldly neutral attitude

- _upekkhāsambojjhaṅgo_: enlightenment factor of detached awareness

- _upekkhā brahmavihāra_: divine abiding of [unlimited, all-encompassing] 
detached awareness

- _upekkhako_: serene

- _upekkhā_: indifference

=== Introduction

==== Upekkhā: not equanimity

DOP calls _upekkhā_:

- disinterestedness, unaffectedness, lack of involvement or reaction.

PED calls it:

- looking on, hedonic neutrality or indifference, zero point between joy and 
sorrow, disinterestedness, neutral feeling, equanimity.

Equanimity is not prominent here. Equanimity means 'steadiness of mind under 
stress' (WordWeb), which is not the meaning of _upekkhā._ For example, in both 
fourth jhāna and the divine abiding, _upekkhā_ occurs in conditions of 
absolute serenity, not stress.

==== Upekkhā: neutral attitude

When PED calls _upekkhā_ 'zero point between joy and sorrow,' it shows that 
English lacks a word for it. We call it 'neutral attitude.'

==== Enlightenment factor of upekkhā: carefully, passively observing

The nature of _upekkhā_ is effectively revealed in the descriptions of the 
seven enlightenment factors of the _Sīla Sutta_. For the sake of comparison, 
let us first see how some of the other factors are also revealed. The sutta 
says:

____
Whenever the body becomes tranquil and the mind becomes tranquil in a bhikkhu 
whose mind is rapturous, on that occasion the enlightenment factor of 
tranquillity is aroused in the bhikkhu

_Yasmiṃ samaye bhikkhave bhikkhuno pītimanassa kāyopi passambhati cittampi 
passambhati passaddhisambojjhaṅgo tasmiṃ samaye bhikkhuno āraddho hoti_
____

____
Whenever his mind becomes collected in a bhikkhu whose body is tranquil and 
joyful, on that occasion the enlightenment factor of inward collectedness is 
aroused in the bhikkhu

_Yasmiṃ samaye bhikkhave bhikkhuno passaddhakāyassa sukhino cittaṃ 
samādhiyati samādhisambojjhaṅgo tasmiṃ samaye bhikkhuno āraddho hoti._
____

[quote, S.5.67-69]
____
When a bhikkhu carefully, passively observes the mind thus collected, on that 
occasion the enlightenment factor of _upekkhā_ is aroused in the bhikkhu.

_Yasmiṃ samaye bhikkhave bhikkhu tathā samāhitaṃ cittaṃ sādhukaṃ 
ajjhupekkhitā hoti. Upekkhāsambojjhaṅgo tasmiṃ samaye bhikkhuno āraddho 
hoti._
____

Thus the nature of the enlightenment factors is found in their means of 
cultivation:

- The enlightenment factor of tranquillity equals the bhikkhu's body and mind 
becoming tranquil.

- The enlightenment factor of inward collectedness equals the bhikkhu's mind 
becoming collected.

- The enlightenment factor of _upekkhā_ equals the bhikkhu carefully, 
passively observing.

The PED calls _upekkhā_ 'looking on,' close to our term: 'detached awareness.'

==== Upekkhako of third jhāna: serenity not equanimity

The formula for third jhāna is:

[quote, S.4.236]
____
With the fading away of rapture, he abides serene, mindful, and fully 
conscious, experiencing physical pleasure. He enters and abides in third jhāna 
in which the Noble Ones declare that he abides serene, mindful, and in physical 
pleasure

_pītiyā ca virāgā upekkhako ca viharati sato sampajāno sukhañca kāyena 
paṭisaṃvedeti yaṃ taṃ ariyā ācikkhanti upekkhako satimā 
sukhavihārīti taṃ tatiyajjhānaṃ upasampajja viharati._
____

Thus the _upekkhako_ of third jhāna is related to the fading away of rapture, 
for which we use the word 'serene,' not 'equanimous' because, unlike fourth 
jhāna, third jhāna is not stable:

____
Third jhāna, I declare, is within the unstable. What there is within the 
unstable? The serenity with physical pleasure that is unended.

_tatiyaṃ jhānaṃ... iñjitasmiṃ vadāmi kiñca tattha iñjitasmiṃ 
yadeva tattha upekkhāsukhaṃ aniruddhaṃ hoti_
____

[quote, M.1.454-5]
____
Fourth jhāna, I declare, is within the not-unstable.

_catutthaṃ jhānaṃ... aniñjitasmiṃ vadāmi._
____

If equanimity means 'steadiness of mind under stress,' then the _upekkhako_ of 
unstable third jhāna cannot rationally be called equanimous.

==== Upekkhāsatipārisuddhiṃ: upekkhā and sati are purified in fourth jhāna

The formula for fourth jhāna is:

[quote, S.4.236-7]
____
With the abandonment of physical pleasure and pain, and following the vanishing 
of psychological pleasure and pain, a bhikkhu enters and abides in fourth 
jhāna, which is free of pleasure and pain, and [is imbued with] purified 
detached awareness and mindfulness.

_idha bhikkhave bhikkhu sukhassa ca pahānā dukkhassa ca pahānā pubbeva 
somanassadomanassānaṃ atthaṅgamā adukkhamasukhaṃ 
upekkhāsatipārisuddhiṃ catutthaṃ jhānaṃ upasampajja viharati._
____

In the term _upekkhāsatipārisuddhiṃ_, the relationship between fourth 
jhāna, _upekkhā_, _and sati_ is unsettled. It has been translated as follows:

- Horner (1): fourth jhāna 'is entirely purified by equanimity and 
mindfulness' (M.3.36).

- Horner (2): fourth jhāna 'consists of purity of mindfulness and 
even-mindedness' (Vin.3.4).

- Bodhi (1): fourth jhāna has 'purity of mindfulness due to equanimity' 
(M.3.252).

- Bodhi (2): fourth jhāna 'includes the purification of mindfulness by 
equanimity' (A.5.31).

Thus Horner (1) says _upekkhā_ and _sati_ purify fourth jhāna, whereas Horner 
(2) says _upekkhā_ and _sati_ are simply part of fourth jhāna. Bodhi (1&2) 
says _sati_ is purified by _upekkhā_.

For us, we treat _upekkhā_ and _sati_ as near synonyms, and do not accept that 
fourth jhāna is purified by these factors, but rather that these two factors 
are purified in fourth jhāna. The situation is comparable to the meditation on 
the four great material phenomena, where one detaches the mind from these 
Elements (_cittaṃ virājeti_). This leads to the following statement:

____
Then there remains only mental consciousness, purified and refined.

_Athāparaṃ viññāṇaṃ yeva avasissati parisuddhaṃ pariyodātaṃ_
____

[quote, M.3.244]
____
_..._ What does one know with that mental consciousness? One knows what is 
pleasant, one knows what is unpleasant, one knows what is neutral.

_Tena ca viññāṇena kiṃ vijānāti: sukhan ti pi vijānāti dukkhan ti pi 
vijānāti adukkhamasukhan ti pi vijānāti._
____

In this meditation, by detaching the mind from the four great material 
phenomena, advertence is purified and refined, and then one knows what is 
pleasant, unpleasant, and neutral. Likewise, in fourth jhāna, with the 
abandonment of pleasure and pain, detached awareness and mindfulness are 
purified, and are then stable bases for contemplation:

[quote, D.1.79-86]
____
With his mind thus collected, purified, cleansed, unblemished, free of 
defilement, pliable, wieldy, stable, and attained to imperturbability, the 
bhikkhu directs and inclines it to the knowledge of the destruction of 
perceptually obscuring states.

_So evaṃ samāhite citte parisuddhe pariyodāte anaṅgaṇe vigatūpakkilese 
mudubhūte kammaniye ṭhite āneñjappatte āsavānaṃ khayañāṇāya 
cittaṃ abhinīharati abhininnāmeti._
____

==== Upekkhindriya: the faculty of physical-plus-psychological neutral experience

The five faculties of sense impression are:

1. the faculty of physical pleasure: pleasure born of bodily sensation
+
****
_sukhindriyaṃ_: _kāyasamphassajaṃ sukhaṃ_
****

2. the faculty of physical pain: pain born of bodily sensation
+
****
_dukkhindriyaṃ_: _kāyasamphassajaṃ dukkhaṃ_
****

3. the faculty of psychological pleasure: pleasure born of mental sensation:
+
****
_somanassindriyaṃ_: _manosamphassajaṃ sukhaṃ_
****

4. the faculty of psychological pain: pain born of mental sensation.
+
****
_domanassindriyaṃ: manosamphassajaṃ dukkhaṃ_
****

5. the faculty of physical-plus-psychological neutral experience: whatever 
sense impression there is, physical or psychological, that is neither pleasing 
nor displeasing
+
****
_yaṃ kho bhikkhave kāyikaṃ vā cetasikaṃ vā neva sātaṃ nāsātaṃ 
vedayitaṃ idaṃ vuccati bhikkhave upekkhindriyaṃ_ (S.5.211).
****

Thus the faculty of physical-plus-psychological neutral experience 
(_upekkhindriya_) includes

1. physical neutral experience

2. psychological neutral experience

We call it 'physical experience' not 'bodily experience' because it is the 
experience of all five of the external senses, not just the sense of touch. The 
terms 'sense impression born of bodily sensation' are likewise not restricted 
to physical touch because the five faculties of sense impression are a 
comprehensive model, where the physical senses are considered part of the body, 
giving rise to physical sense impressions.

==== Neutral attitude: counterpoint of joy and dejection

Neutral attitude is the counterpoint of joy and dejection. For example:

____
In seeing a visible object via the visual sense

_cakkhunā rūpaṃ disvā_
____

____
... one ponders a visible object which is the basis for joy

_somanassaṭṭhāniyaṃ rūpaṃ upavicarati_
____

____
... one ponders a visible object which is the basis for dejection,

_domanassaṭṭhāniyaṃ rūpaṃ upavicarati_
____

[quote, M.3.217]
____
... one ponders a visible object which is the basis for a neutral attitude.

_upekkhaṭṭhāniyaṃ rūpaṃ upavicarati._
____

==== Neutral attitude: diversified and undiversified

Neutral attitude is either diversified or undiversified:

____
What is the neutral attitude that is diversified, associated with diversity?

_upekkhā nānattā nānattasitā_
____

____
... There is a neutral attitude associated with visible objects, audible 
objects... mentally known objects.

_atthi bhikkhave upekkhā rūpesu atthi saddesu atthi gandhesu atthi rasesu 
atthi phoṭṭhabbesu._
____

____
... What is the neutral attitude that is undiversified, associated with 
undiversity?

_upekkhā ekattā ekattasitā_
____

____
... There is a neutral attitude associated with the state of awareness of 
boundless space, associated with the state of awareness of boundless mental 
consciousness, associated with the state of awareness of nonexistence, 
associated with the state of awareness neither having nor lacking perception.

_atthi bhikkhave upekkhā ākāsānañcāyatananissitā atthi 
viññāṇañcāyatananissitā atthi ākiñcaññāyatananissitā atthi 
nevasaññānāsaññāyatananissitā_
____

____
... In this regard, with the help of and by means of the neutral attitude that 
is undiversified, associated with undiversity, abandon and transcend the 
neutral attitude that is diversified, associated with diversity

_Tatra bhikkhave yā'yaṃ upekkhā ekattā ekattasitā taṃ nissāya taṃ 
āgamma yā'yaṃ upekkhā nānattā nānattasitā taṃ pajahatha taṃ 
samatikkamatha_
____

[quote, M.3.220]
____
... With the help of and by means of the perception that "It is void of 
personal qualities" abandon and transcend the neutral attitude that is 
undiversified, associated with undiversity.

_Atammayataṃ bhikkhave nissāya atammayataṃ āgamma yā'yaṃ upekkhā 
ekattā ekattasitā taṃ pajahatha taṃ samatikkamatha._
____

==== The power of detached awareness

Detached awareness can be used in the battle against attachment, against 
pleasure and pain, and against impossible comrades:

[quote, D.3.248-250]
____
If the liberation [from perceptually obscuring states] through [unlimited, 
all-encompassing] detached awareness is developed and cultivated... it is 
impossible, out of the question, that attachment would plague your mind. There 
is no such possibility.

_yaṃ upekkhāya cetovimuttiyā bhāvitāya... rāgo cittaṃ pariyādāya 
ṭhassatī ti netaṃ ṭhānaṃ vijjati._
____

[quote, S.4.71]
____
When touched by a tangible object do not be elated by pleasure. Do not tremble 
when touched by pain. Maintain detached awareness towards physical sensation, 
both pleasant and painful, not attracted or repelled by anything.

_Phassena phuṭṭho na sukhena majje +
Dukkhena phuṭṭhopi na sampavedhe +
Phassadvayaṃ sukhadukkhe upekkhe +
Anānuruddho aviruddha kenaci._
____

[quote, M.2.242]
____
If a bhikkhu thinks 'I am not able to make that person emerge from what is 
spiritually unwholesome and establish him in what is spiritually wholesome' he 
should not spurn detached awareness towards such a person._

_Na cāhaṃ sakkomi etaṃ puggalaṃ akusalā vuṭṭhāpetvā kusale 
patiṭṭhāpetun ti. Evarūpe bhikkhave puggale upekkhā nātimaññitabbā._
____

Further examples are in the Illustrations below.

==== Upekkhā brahmavihāra: [unlimited, all-encompassing] detached awareness

The practices of _mettā_, _karuṇā_, _muditā_ and _upekkhā_ are sometimes 
called the four divine abidings (_cattāro brahmavihārā_, D.2.196) and 
sometimes the four unlimited states (_catasso appamaññā_, D.3.223). 
Practising them together is called the 'unlimited liberation [from perceptually 
obscuring states]' (_appamāṇā cetovimutti_, S.4.296). The _Mahāvedalla 
Sutta_ (M.1.298) and _Godatta Sutta_ (S.4.296) say the 'makers of limitation' 
(_pamāṇakaraṇo_) are _rāgo doso_ and _moho_ (_rāgo kho āvuso 
pamāṇakaraṇo doso pamāṇakaraṇo moho pamāṇakaraṇo_). Therefore 
the four _brahmavihāras_ should be practised unlimited by _rāgo doso_ and 
_moho_. We call _upekkhā brahmavihārā_ '[unlimited, all-encompassing] 
detached awareness.' It is for overcoming attachment, ill will, vexation, 
disgust, and repugnance (N.B. _Upekkhā_ in both these quotes occurs in the 
context of the divine abidings):

1. For this is the liberation from attachment, namely the liberation [from 
perceptually obscuring states] through [unlimited, all-encompassing] detached 
awareness.
+
****
_nissaraṇaṃ hetaṃ āvuso rāgassa yadidaṃ upekkhā cetovimutti_ 
(D.3.248-250).
****

2. 'The Blessed One abides in a state of [unlimited, all-encompassing] detached 
awareness.' 'Jīvaka, any attachment, hatred, or undiscernment of reality 
whereby ill will, vexation, disgust, or repugnance might arise have been 
abandoned by the Perfect One... If what you said referred to that, then I allow 
it to you.'
+
****
_bhagavā hi bhante upekkhāvihārī ti... vyāpādavā vihesavā assa assa 
arati vā assa paṭighavā assa so rāgo so doso so moho tathāgatassa 
pahīno..._ (M.1.369-371).
****

=== Illustrations

.Illustration
====
sāmisā upekkhā

worldly neutral attitude
====

____
And what is the worldly neutral attitude?

_sāmisā upekkhā_
____

There are these five varieties of sensuous pleasure. What five?

____
Visible objects known via the visual sense...

_cakkhuviññeyyā rūpā..._
____

____
Tangible objects known via the tactile sense

_kāyaviññeyyā phoṭṭhabbā_
____

____
... that are likeable, loveable, pleasing, agreeable, connected with sensuous 
pleasure, and charming

_iṭṭhā kantā manāpā piyarūpā kāmūpasaṃhitā rajanīyā_
____

[quote, S.4.237]
____
... The neutral attitude that arises on account of the five varieties of 
sensuous pleasure is called the worldly neutral attitude.

_Yā kho bhikkhave ime pañcakāmaguṇe paṭicca uppajjati upekkhā ayaṃ 
vuccati bhikkhave sāmisā upekkhā._
____

.Illustration
====
nirāmisā upekkhā

unworldly neutral attitude
====

____
And what is the unworldly neutral attitude?

_nirāmisā upekkhā_
____

____
'With the abandonment of physical pleasure and pain, and following the 
vanishing of psychological pleasure and pain, a bhikkhu enters and abides in 
fourth jhāna, which is free of pleasure and pain, and [is imbued with] 
purified detached awareness and mindfulness.

_sukhassa ca pahānā dukkhassa ca pahānā pubbeva somanassadomanassānaṃ 
atthaṅgamā adukkhamasukhaṃ upekkhāsatipārisuddhiṃ catutthaṃ 
jhānaṃ upasampajja viharati_
____

[quote, S.4.237]
____
This is called the unworldly neutral attitude.

_ayaṃ vuccati bhikkhave nirāmisā upekkhā._
____

.Illustration
====
nirāmisā nirāmisatarā upekkhā

neutral attitude more than unworldly
====

____
And what is the neutral attitude more than unworldly?

_Katamā ca bhikkhave nirāmisā nirāmisatarā upekkhā_
____

[quote, S.4.237]
____
When a bhikkhu whose _āsavas_ are destroyed reviews his mind liberated from 
attachment, liberated from hatred, liberated from undiscernment of reality, 
there arises a neutral attitude. This is called the neutral attitude more than 
unworldly.

_yā kho bhikkhave khīṇāsavassa bhikkhuno rāgā cittaṃ vimuttaṃ 
paccavekkhato dosā cittaṃ vimuttaṃ paccavokkhato mohā cittaṃ vimuttaṃ 
paccavekkhato uppajjati upekkhā ayaṃ vuccati bhikkhave nirāmisā 
nirāmisatarā upekkhā._
____

.Illustration
====
upekkhā gehasitā

laypersons' neutral attitude
====

The ignorant Everyman experiences laypersons' joy when he attains objects of 
desire (_gehasitaṃ somanassaṃ_), laypersons' displeasure when he fails to 
attain them (_gehasitaṃ domanassaṃ_), and a third emotional reaction, 
laypersons' neutral attitude, _gehasitā upekkhā_. This is not associated with 
attaining or not attaining. It is simply an emotional reaction to objects, 
either physical or mental. For example:

____
In seeing a visible object via the visual sense, there arises in him the 
neutral attitude of the foolish Everyman who is undiscerning of reality. The 
neutral attitude such as this does not transcend the visible object. Therefore 
it is called the laypersons' neutral attitude.

_cakkhunā rūpaṃ disvā uppajjati upekkhā bālassa mūḷhassa 
puthujjanassa... Yā evarūpā upekkhā rūpaṃ sā nātivattati. Tasmā sā 
upekkhā gehasitā ti vuccati._
____

[quote, M.3.218]
____
On knowing a mentally known object via the mental sense, there arises in him 
the neutral attitude of the foolish Everyman who is undiscerning of reality. 
The neutral attitude such as this does not transcend the mental object. 
Therefore it is called the laypersons' neutral attitude.

_Manasā dhammaṃ viññāya uppajjati upekkhā bālassa mūḷhassa 
puthujjanassa... Yā evarūpā upekkhā dhammaṃ sā nātivattati. Tasmā sā 
upekkhā gehasitā ti vuccati._
____

.Illustration
====
nekkhammasitā upekkhā

ascetics' neutral attitude
====

____
What are the six types of ascetics' neutral attitude?

_cha nekkhammasitā upekkhā_
____

____
When one realises the unlastingness of visible objects... of mentally known 
objects, their changeableness, passing away and ending, and thinks, 'Formerly 
as well as now all these visible objects... mentally known objects are 
unlasting, existentially void, and destined to change,' from seeing this thus 
according to reality with perfect penetrative discernment, detached awareness 
arises.

_rūpānaṃ... dhammā tveva aniccataṃ viditvā 
vipariṇāmavirāganirodhaṃ pubbe ceva rūpā etarahi ca sabbe te rūpā... 
dhammā aniccā dukkhā vipariṇāmadhammā ti evametaṃ yathābhūtaṃ 
sammappaññāya passato uppajjati upekkhā_
____

____
Neutral attitude such as this transcends the visible objects... mentally known 
objects.

_yā evarūpā upekkhā rūpaṃ sā ativattati... dhammaṃ sā ativattati._
____

____
Therefore it is called the ascetics' neutral attitude.

_tasmā sā upekkhā nekkhammasitā ti vuccati_
____

[quote, M.3.219]
____
These are the six types of ascetics' neutral attitude._

_Imā cha nekkhammasitā upekkhā._
____

Comment:

This transcendent neutral attitude seems equivalent to detached awareness.

.Illustration
====
upekkhindriyaṃ

faculty of physical-plus-psychological neutral experience; upekkhako, 
indifferent
====

____
Bhikkhus, there are these five faculties of sense impression. What five? The 
faculty of physical pleasure, the faculty of psychological pleasure, the 
faculty of physical pain, the faculty of psychological pain, the faculty of 
physical-plus-psychological neutral experience.

_sukhindriyaṃ somanassindriyaṃ dukkhindriyaṃ domanassindriyaṃ 
upekkhindriyaṃ_
____

____
Dependent on a sensation to be experienced as physically pleasant, the faculty 
of physical pleasure arises. Being physically pleased, he knows that: 'I am 
physically pleased.'

_Sukhavedanīyaṃ bhikkhave phassaṃ paṭicca uppajjati sukhindriyaṃ. So 
sukhito va samāno sukhitosmi ti pajānāti_
____

____
Dependent on a sensation to be experienced as physically unpleasant, the 
faculty of physical pain arises. Being physically hurt, he knows that: 'I am 
physically hurt.'

_Dukkhavedanīyaṃ bhikkhave phassaṃ paṭiccauppajjati dukkhindriyaṃ. So 
dukkhito va samāno dukkhitosmī ti pajānāti._
____

____
Dependent on a sensation to be experienced as psychologically pleasant, the 
faculty of psychological pleasure arises. Being psychologically pleased he 
discerns: 'I am psychologically pleased.'

_Somanassavedanīyaṃ bhikkhave phassaṃ paṭicca uppajjati 
somanassindriyaṃ. So sumano va samāno sumanosmī ti pajānāti._
____

____
Dependent on a sensation to be experienced as psychologically unpleasant, the 
faculty of psychological pain arises. Being psychologically hurt, he discerns: 
'I am psychologically hurt.'

_Domanassavedanīyaṃ bhikkhave phassaṃ paṭicca uppajjati 
domanassindriyaṃ. So dummano va samāno dummanosmī ti pajānāti._
____

[quote, S.5.211-2]
____
Dependent on a sensation to be experienced as neutral, the faculty of 
physical-plus-psychological neutral experience arises. Being indifferent, he 
knows that: 'I am indifferent.'

_Upekkhāvedanīyaṃ bhikkhave phassaṃ paṭicca uppajjati upekkhindriyaṃ. 
So upekkhako va samāno upekkhakosmī ti pajānāti._
____

.Illustration
====
upekkhindriyaṃ

faculty of physical-plus-psychological neutral experience
====

____
And where does the arisen faculty of physical-plus-psychological neutral 
experience cease without remainder?

_Kattha cuppannaṃ upekkhindriyaṃ aparisesaṃ nirujjhati_
____

[quote, S.5.215]
____
In this regard, having completely transcended the state of awareness neither 
having nor lacking perception, a bhikkhu enters and abides in the ending of 
perception and sense impression. And it is here that the arisen faculty of 
physical-plus-psychological neutral experience ceases without remainder.

_idha bhikkhave bhikkhu sabbaso nevasaññānāsaññāyatanaṃ samatikkamma 
saññāvedayitanirodhaṃ upasampajja viharati. Ettha cuppannaṃ 
upekkhindriyaṃ aparisesaṃ nirujjhati._
____

.Illustration
====
neutral attitude
====

____
Sensuous pleasures have been compared by the Blessed One to a skeleton [of 
meatless bones smeared with blood which leaves a hungry dog unsatisfied

fatigued, and full of vexation]. They are full of suffering and vexation, while 
the danger in them is great.

_aṭṭhikaṅkalūpamā kāmā vuttā bhagavatā bahudukkhā bahūpāyāsā 
ādīnavo ettha bhiyyo ti_
____

[quote, M.1.364]
____
Having seen this thus according to reality with perfect penetrative 
discernment, having avoided the neutral attitude that is diversified, 
associated with diversity, one develops the neutral attitude that is 
undiversified, associated with undiversity, where grasping of worldly pleasures 
ceases without remainder.

_Evametaṃ yathābhūtaṃ sammappaññāya disvā yāyaṃ upekkhā nānattā 
nānattasitā taṃ abhinivajjetvā yāyaṃ upekkhā ekattā ekattasitā 
yattha sabbaso lokāmisūpādānā aparisesā nirujjhanti tamevupekkhaṃ 
bhāveti._
____

COMMENT

For notes on diversified and undiversified, see introduction.

.Illustration
====
upekkhā

indifference
====

____
If a bhikkhu's mind is imbued with the perception of the unloveliness [of the 
body], his mind draws back, bends back, turns away from involvement in sexual 
intercourse and is not attracted to it, and either indifference or loathing is 
established in him.

_Asubhasaññā paricitena bhikkhave bhikkhūno cetasā bahulaṃ viharato 
methunadhammasamāpattiyā cittaṃ patilīyati patikuṭati pativaṭṭati na 
sampasārīyati. Upekkhā vā paṭikkūlyatā vā saṇṭhāti._
____

____
If a bhikkhu's mind is imbued with the perception of [the ever-present 
possibility of] death, his mind draws back, bends back, and turns away from the 
hankering for life, and is not attracted to it, and either indifference or 
loathing is established in him.

_Maraṇasaññā paricitena bhikkhave bhikkhuno cetasā bahulaṃ viharato 
jīvitanikantiyā cittaṃ patilīyati patikuṭati pativaṭṭati na 
sampasārīyati. Upekkhā vā paṭikkūlyatā vā saṇṭhāti._
____

____
If a bhikkhu's mind is imbued with the perception of the loathsome nature of 
digestion, his mind draws back, bends back, turns away from craving for 
flavours and is not attracted to them, and either indifference or loathing is 
established in him.

_Āhāre paṭikkūlasaññā paricitena bhikkhave bhikkhuno cetasā bahulaṃ 
viharato rasataṇhāya cittaṃ patilīyati patikuṭati pativaṭṭati na 
sampasārīyati upekkhā vā paṭikkūlyatā vā saṇṭhāti_
____

____
If a bhikkhu's mind is imbued with the perception of disgust for the whole 
world [of phenomena], his mind shrinks from worldly intentions and is not 
attracted to them and either indifference or loathing is established in him.

_Sabbaloke anabhiratasaññā paricitena bhikkhave bhikkhuno cetasā bahulaṃ 
viharato lokacittesu cittaṃ patilīyati patikūṭati pativaṭṭati na 
sampasārīyati. Upekkhā vā paṭikkūlyatā vā saṇṭhāti._
____

[quote, A.4.47]
____
If a bhikkhu's mind is imbued with the perception of the unlastingness [of the 
five aggregates], his mind draws back, bends back, turns away from gains, 
honour, and renown and is not attracted to it, and either indifference or 
loathing is established in him.

_Aniccasaññā paricitena bhikkhave bhikkhuno cetasā bahulaṃ viharato 
lābhasakkārasiloke cittaṃ patilīyati patikuṭati pativaṭṭati na 
sampasārīyati upekkhā vā paṭikkūlyatā vā saṇṭhāti._
____

.Illustration
====
upekkhā

detached awareness
====

____
In this regard, in seeing a visible object via the visual sense, there arises 
in a bhikkhu pleasure, or displeasure, or pleasure plus displeasure.

_cakkhunā rūpaṃ disvā uppajjati manāpaṃ uppajjati amanāpaṃ uppajjati 
manāpāmanāpaṃ._
____

____
He knows that 'This pleasure has arisen in me, this displeasure... this 
pleasure plus displeasure has arisen in me.'

_uppannaṃ kho me idaṃ manāpaṃ uppannaṃ amanāpaṃ uppannaṃ 
manāpāmanāpaṃ_
____

____
And that is originated, self-evident, dependently arisen.

_tañca kho saṅkhataṃ oḷārikaṃ paṭiccasamuppannaṃ_
____

____
But this is peaceful, this is sublime, namely, detached awareness.

_Etaṃ santaṃ etaṃ paṇītaṃ yadidaṃ upekkhā ti._
____

____
With that, the arisen pleasure... displeasure... pleasure plus displeasure 
ceases, and detached awareness is established.

_Tassa taṃ uppannaṃ manāpaṃ uppannaṃ amanāpaṃ uppannaṃ 
manāpāmanāpaṃ nirujjhati upekkhā saṇṭhāti._
____

Just as a man with good eyes, having closed them, might open them; or having 
opened them, might close them, that is how quickly, how rapidly, how easily, no 
matter what it refers to, the pleasure... displeasure... pleasure plus 
displeasure ceases, and detached awareness is established (M.3.299).

.Illustration
====
upekkhā

detached awareness
====

[quote, M.1.186]
____
It is a loss for me, not a gain; it is unfortunate for me, not fortunate, that 
when I recollect the Buddha, the teaching, and the community of the Blessed 
One's disciples in this way, detached awareness based on what is spiritually 
wholesome is not established within me.

_alābhā vata me na vata me lābhā dulladdhaṃ vata me na vata me 
suladdhaṃ yassa me evaṃ buddhaṃ anussarato evaṃ dhammaṃ anussarato 
evaṃ saṅghaṃ anussarato upekkhā kusalanissitā na saṇṭhātī ti._
____

.Illustration
====
upekkhā

detached awareness
====

____
A bhikkhu practises thus: 'Had it not been, it would not have been "mine." It 
will be not; not "mine" will it be. That which is, that which is brought about, 
that I abandon.'

_no c'assa no ca me siyā na bhavissati na me bhavissati. Yadatthi yaṃ 
bhūtaṃ taṃ pajahāmī ti_
____

[quote, M.2.265]
____
In this way he attains detached awareness.

_evaṃ upekkhaṃ paṭilabhati._
____

.Illustration
====
upekkhā

detached awareness
====

____
A meditator must apply three ways of practice (_tīṇi nimittāni_) not 
exclusively, but from time to time: inward collectedness, effort, and detached 
awareness.

_kālena kālaṃ samādhinimittaṃ manasikātabbaṃ; kālena kālaṃ 
paggahanimittaṃ manasikātabbaṃ; kālena kālaṃ upekkhānimittaṃ 
manasikātabbaṃ_
____

[quote, A.1.256]
____
If he focuses exclusively on the practice of detached awareness it is likely 
that his mind will be not properly collected for the destruction of 
perceptually obscuring states

_ekantaṃ upekkhānimittaññeva manasikareyya ṭhānaṃ taṃ cittaṃ na 
sammā samādhiyetha āsavānaṃ khayāya._
____

.Illustration
====
upekkhaṃ

detached awareness
====

____
He discerns thus:

_So evaṃ pajānāti_
____

____
'When I confront the source of this suffering with effort, by confronting it 
with effort [the suffering] fades away.

_imassa kho me dukkhanidānassa saṅkhāraṃ padahato saṅkhārappadhānā 
virāgo hoti_
____

[quote, M.2.223]
____
When the source of this suffering is passively observed, through developing 
detached awareness, [the suffering] fades away.'

_imassa pana me dukkhanidānassa ajjhupekkhato upekkhaṃ bhāvayato virāgo 
hotī ti._
____

.Illustration
====
upekkhā brahmavihāra

&#8203;[unlimited, all-encompassing] detached awareness
====

[quote, D.3.223]
____
A bhikkhu abides pervading one quarter with a mind of [unlimited, 
all-encompassing] detached awareness, likewise the second quarter, the third 
quarter, and the fourth quarter. Thus above, below, across, in all directions, 
everywhere, he abides pervading the whole world [of beings] with a mind of 
&#8203;[unlimited, all-encompassing] detached awareness, vast, exalted, unlimited, 
free of unfriendliness and hostility.'

_upekkhāsahagatena cetasā ekaṃ disaṃ pharitvā viharati tathā dutiyaṃ 
tathā tatiyaṃ tathā catutthiṃ iti uddhamadho tiriyaṃ sabbadhi 
sabbatthatāya sabbāvantaṃ lokaṃ upekkhāsahagatena cetasā vipulena 
mahaggatena appamāṇena averena avyāpajjhena pharitvā viharati._
____

.Illustration
====
upekkhako

serene
====

There are five noble psychic powers that are free of perceptually obscuring 
states and attachment (_iddhi yā anāsavā anupadhikā ariyā ti_). These are 
where a bhikkhu, if he wishes (_sace ākaṅkhati_) can abide:

____
perceiving the unloathsomeness of what is loathsome

_paṭikkūle appaṭikkūlasaññī_
____

____
perceiving the loathsomeness of what is attractive

_appaṭikkūle paṭikkūlasaññī_
____

____
perceiving the unloathsomeness of what is loathsome and what is attractive

_paṭikkūle ca appaṭikkūle ca appaṭikkūlasaññī_
____

____
perceiving the loathsomeness of what is attractive and what is loathsome

_appaṭikkūle ca paṭikkūle ca paṭikkūlasaññī vihareyyanti_
____

[quote, D.3.112-3; A.3.169-170]
____
Or, by rejecting both what is attractive and loathsome can abide serene, 
mindful, and fully conscious.

_appaṭikkūlañca paṭikkūlañca tadubhayaṃ abhinivajjetvā upekkhako 
vihareyyaṃ sato sampajāno ti._
____

.Illustration
====
upekkhako

serene
====

[quote, A.2.196-7]
____
He, seeing an object via the visual sense, is neither elated nor depressed, but 
abides serene, mindful, and fully conscious.

_So cakkhunā rūpaṃ disvā neva sumano hoti na dummano upekkhako viharati 
sato sampajāno._
____

