== Upādānā; Upādiyati

=== Renderings

- _upādāna_: fuel

- _upādāna_: sustenance

- _upādāna_: grasping

- _upādānā_: fuelled

- _upādiyati_: to take up

- _upādiyati_: to absorb

- _upādiyati_: to grasp

=== Introduction

==== Grasping not clinging

That _upādāna_ is best rendered as grasping not clinging is nowhere clearer 
than in the fact that the Buddha 'does not sit while grasping his chin with his 
hand' (_na ca pāṇinā hanukaṃ upādiyitvā nisīdati_, M.2.138).

=== Illustrations

.Illustration
====
upādiyati

take up
====

[quote, M.3.266]
____
Sāriputta, he who lays down one body and takes up a new body is one I call 
blameworthy

_imañca kāyaṃ nikkhipati aññañca kāyaṃ upādiyati tamahaṃ 
saupavajjo ti vadāmi._
____

.Illustration
====
upādiyati

absorb
====

Suppose the seed of a nimb or creeper or bitter gourd be planted in moist soil. 
Whatever of the earth-nutriment or water-nutriment it absorbs (_yañceva 
paṭhavirasaṃ upādiyati yañca āporasaṃ upādiyati_), all that leads to 
its bitterness, acridity, and unpleasant taste (A.5.212).

.Illustration
====
upādiyati

grasp
====

[quote, (M.1.252)]
____
He does not grasp anything in the world [of phenomena]

_na kiñci loke upādiyati_
____

.Illustration
====
upādāya

grasping
====

[quote, S.4.88]
____
When there is the visual sense... the mental sense, by grasping the visual 
sense... the mental sense, by stubbornly adhering to the visual sense... the 
mental sense, the thought occurs "I am better" or "I am equal" or "I am worse"

_cakkhusmiṃ kho bhikkhave sati cakkhuṃ upādāya cakkhuṃ abhinivissa 
seyyo'hamasmī ti vā hoti sadiso'hamasmī ti vā hoti hīno'hamasmī ti vā 
hoti._
____

.Illustration
====
upādāya

grasping
====

[quote, M.1.501]
____
While Venerable Sāriputta considered this his mind was liberated [from 
perceptually obscuring states] through being without grasping.

_anupādāya āsavehi cittaṃ vimucci._
____

.Illustration
====
upādāya

grasping
====

____
'The notion "I am" occurs with grasping, not without grasping.

_Upādāya āvuso ānanda asmī ti hoti no anupādāya_
____

____
'Suppose, a youngster, youthful and fond of ornaments (vain), would examine 
their facial image in a mirror or in a bowl filled with pure, clean water.

_itthi vā puriso vā daharo yuvā maṇaḍanajātiko ādāse vā parisuddhe 
pariyodāte acche vā udakapatte sakaṃ mukhanimittaṃ paccavekkhamāno_
____

____
'They would look at it with grasping, not without grasping

_upādāya passeyya no anupādāya_
____

[quote, S.3.105]
____
So, too, the notion "I am" occurs with the grasping of (the five 
aggregates), not without grasping.

_Evameva kho āvuso ānanda rūpaṃ upādāya asmī ti hoti no 
anupādāya... viññāṇaṃ upādāya asmī ti hoti no anupādāya._
____

.Illustration
====
upādāno

sustenance
====

[quote, S.2.86]
____
Suppose there was a great tree and all its roots going downwards and across 
would send the sap upwards. With that as nourishment, with that as sustenance, 
that great tree would stand for a very long time

_tadāhāro tadupādāno ciraṃ dīghamaddhānaṃ tiṭṭheyya._
____

.Illustration
====
upādānaṃ

fuel
====

• I declare rebirth for one with fuel, not for one without fuel; just as a 
fire burns with fuel not without fuel. +
_Sa upādānassa kho' haṃ vaccha uppattiṃ paññāpemi no anupādānassa; 
seyyathā pi vaccha aghi saupādāno jalati no anupādāno:_

[quote, S.4.399-400]
____
... On that occasion craving is the fuel

_Taṇhāhissa vaccha tasmiṃ samaye upādānaṃ hotī ti._
____

.Illustration
====
upādānā

fuelled
====

[quote, M.3.243]
____
If I were to direct this detached awareness so purified and refined to the 
state of awareness of boundless space, and to develop my mind accordingly, then 
this detached awareness of mine, supported by that, fuelled by it, would remain 
for a very long time.

_imaṃ ce ahaṃ upekkhaṃ evaṃparisuddhaṃ evaṃpariyodātaṃ 
ākāsānañcāyatanaṃ upasaṃhareyyaṃ tadanudhammañca cittaṃ 
bhāveyyaṃ evaṃ ayaṃ upekkhā tannissitā tadupādānā ciraṃ 
dīghamaddhānaṃ tiṭṭheyya._
____

.Illustration
====
upādānaṃ

grasping
====

____
There are visible objects known via the visual sense that are likeable, 
loveable, pleasing, agreeable, connected with sensuous pleasure, and charming.

_cakkhuviññeyyā rūpā iṭṭhā kantā manāpā piyarūpā 
kāmūpasaṃhitā rajanīyā_
____

____
If a bhikkhu takes delight in them, welcomes them, and persists in cleaving to 
them, then the mind is attached to them.

_tañce bhikkhu abhinandati abhivadati ajjhosāya tiṭṭhati tassa taṃ 
abhinandato abhivadato ajjhosāya tiṭṭhato tannissitaṃ viññāṇaṃ 
hoti_
____

[quote, S.4.102]
____
That is grasping.

_tadupādānaṃ._
____

.Illustration
====
upādānaṃ

grasping
====

[quote, S.3.13]
____
Spiritually fettering delight in bodily form is grasping

_yā rūpe nandī tadupādānaṃ._
____

.Illustration
====
upādānaṃ

grasping
====

[quote, S.2.14]
____
Grasping arises dependent on craving

_taṇhāpaccayā upādānaṃ._
____

.Illustration
====
upādānaṃ

grasping
====

[quote, M.2.237]
____
And certainly when this Venerable regards himself thus: 'I am at peace. I am 
inwardly at peace. I am free of grasping' that is declared to be grasping on 
the part of this good ascetic or Brahmanist.

_Yañca kho ayamāyasmā santo'hamasmi nibbuto'hamasmi anupādino'hamasmī ti 
samanupassati tadapi imassa bhoto samaṇassa brāhmaṇassa 
upādānamakkhāyati._
____

.Illustration
====
upādānāya

grasping
====

[quote, M.1.498]
____
The ascetics whose doctrine and dogmatic view is that "Everything is acceptible 
to me," that view is close to attachment, bondage [to individual existence], 
delight, cleaving, and grasping;

_ye te samaṇabrāhmaṇā evaṃ vādino evaṃdiṭṭhino sabbaṃ me 
khamatī ti tesamayaṃ diṭṭhi sārāgāya santike saṃyogāya santike 
abhinandanāya santike ajjhosānāya santike upādānāya santike._
____

.Illustration
====
upadānaṃ

grasping
====

____
Neither is grasping the same as the five grasped aggregates
nor is it separate.

_na kho bhikkhu taññeva upādānaṃ te pañcupādānakkhandhā na pi 
aññatra pañcupādānakkhandhehi upādānaṃ_
____

[quote, S.3.100-1]
____
Whatever there is the fondness and attachment, that is the grasping.

_yo tattha chandarāgo taṃ tattha upādānan ti._
____

.Illustration
====
upadānaṃ

grasping
====

____
If there were no grasping in any way

_sabbaso upādāne asati upādānanirodhā_
____

____
grasping of sensuous pleasure

_kāmūpādānaṃ_
____

____
grasping of dogmatic views

_diṭṭhūpādānaṃ_
____

____
grasping of observances and practices

_sīlabbatūpādānaṃ_
____

____
grasping of theories of an [absolute] Selfhood

_attavādūpādānaṃ_
____

[quote, D.2.58]
____
would individual existence be discerned?

_api nu kho bhavo paññāyethā ti._
____

.Illustration
====
upādā

grasping
====

____
In this regard, having seen any kind of bodily form... advertence according to 
reality with perfect penetrative discernment as "not [in reality] mine," "not 
&#8203;[in reality] what I am," "not my [absolute] Selfhood," a bhikkhu is liberated 
&#8203;[from perceptually obscuring states] through being without grasping.

_Idha aggivessana bhikkhu yaṃ kiñci rūpaṃ atītānāgata paccuppannaṃ 
ajjhattaṃ vā bahiddhā vā oḷārikaṃ vā sukhumaṃ vā hīnaṃ vā 
paṇītaṃ vā yaṃ dūre sannike vā sabbaṃ rūpaṃ n'etaṃ mama 
n'eso'hamasmi na me so attā ti evametaṃ yathābhūtaṃ sammappaññāya 
disvā anupādā vimutto hoti._
____

_Yā kāci vedanā... saññā... saṅkhārā... viññāṇaṃ..._ (M.1.235).

Comment: Thus grasping equals seeing things as "[in reality] mine," "[in 
reality] what I am," "my [absolute] Selfhood."

