== Uṇṇata

=== Renderings

- _uṇṇamati_: to be swelled-headed

- _uṇṇati_: swelled-headedness

=== Illustrations

.Illustration
====
uṇṇamati

swelled-headed
====

____
He who is praised for presenting his argument in the midst of the assembly, 
having attained his objective is mirthful and swelled-headed because of it.

_Pasaṃsito vā pana tattha hoti akkhāya vādaṃ parisāya majjhe +
So hassati uṇṇamati ca tena pappuyya tamatthaṃ yathā mano ahu_
____

[quote, Sn.v.829-30]
____
That swelled-headedness will be the basis of later distress. Moreover, he 
speaks with conceit and arrogance.

_Yā uṇṇati sāssa vighātabhūmi mānātimānaṃ vadate paneso._
____

.Illustration
====
anuṇṇato

swelled-headedness
====

[quote, Sn.v.702]
____
One should live the religious life peacefully, without swelled-headedness.

_santo anuṇṇato care._
____

.Illustration
====
uṇṇametave

swelled-headed
====

[quote, Sn.v.199-206]
____
Whoever would think to be swelled-headed because of such a body, or would 
disparage another, what is this except not seeing it [according to reality]?

_Etādisena kāyena yo maññe uṇṇametave +
Paraṃ vā avajāneyya kimaññatra adassanāti._
____

.Illustration
====
uṇṇameyya

swelled-headed
====

[quote, Sn.v.366]
____
He who is not swelled-headed, thinking, 'He venerates me.'.

_Yo vandati maṃ na uṇṇameyya._
____

.Illustration
====
uṇṇameyya

swelled-headed
====

[quote, Sn.v.928]
____
A bhikkhu should not tremble at criticism, nor be swelled-headed when praised.

_Nindāya nappavedheyya na uṇṇameyya pasaṃsito bhikkhu._
____

