== Va jhayati

=== Renderings

- _Va jhayati_: he meditates [mindfully] indeed

- _Va jhayati_: he meditates [happily] indeed

=== Introduction

==== Va: three meanings

_Va_ is a shortened form occurring only in verse, says PED, as follows:

1. the shortened form of _iva_: 'like, like, as, as if'.

2. the shortened form for _eva_, which emphasises the word it follows, says 
DOP, for example: 'that very..., the same..., exactly that..., only, merely, 
just, indeed, really, certainly, absolutely, even, still'.

3. the shortened form of _vā_: 'or'.

Neither PED nor DOP say _va_ is ever redundant.

==== Va jhayati: he meditates mindfully or happily

The words _va jhayati_ occur 16 times in the suttas, 14 of which in the 
_Theragāthā_. Often it is linked to another word. From the following three 
examples we see that meditation in nature is done 'happily indeed.' Otherwise 
it is done 'mindfully indeed.'

1. _sato va jhāyati_: he meditates mindfully indeed (Th.v.518-520).

[quote, Th.v.518]
____
When the wise man [sees that] old age and death, to which the ignorant Everyman 
is attached, are existentially void, having profoundly understood existential 
voidness, he meditates mindfully indeed. One does not find greater delight than 
this.

_Yadā dukkhaṃ jarāmaraṇan ti paṇḍito aviddasū yattha sitā 
puthujjanā +
Dukkhaṃ pariññāya sato va jhāyati tato ratiṃ paramataraṃ na vindati._
____

2. _sumano va jhāyati_: he meditates happily indeed (Th.v.524).

[quote, Th.v.524]
____
When, seated on the banks of rivers full of flowers and beautifully garlanded 
woodland plants, he meditates happily indeed, one does not find greater delight 
than this.

_Yadā nadīnaṃ kusumākulānaṃ vicittavāneyyavaṭaṃsakānaṃ +
Tīre nisinno sumano va jhāyati tato ratiṃ paramataraṃ na vindati._
____

3. _bhaddova jhāyati_: he meditates happily indeed (Th.v.466).

[quote, Th.v.466]
____
In a woodland grove on the far side of Hog-plum Monastery, Bhaddiya, having 
removed [the arrow of] craving together with its origin, meditates there 
happily indeed.

_Pare ambāṭakārāme vanasaṇḍamhi bhaddiyo +
Samūlaṃ taṇhaṃ abbuyha tattha bhaddova jhāyati._
____

==== Va=ca: and

On one occasion we follow Norman in treating _va_ as _ca_ i.e. 'and free of 
remissness...' Norman likewise says 'and': 'rid of distress and rid of 
barreness of mind he meditates.'

[quote, Th.v.525]
____
When, having ended his own thinking and resorted to a cleft in the middle of 
the mountains, he meditates free of suffering (_vītaddaro_) and (_va_) free of 
remissness in practising the teaching (_vigatakhilo_), one does not find 
greater delight than this.

_Yadā vitakke uparundhiyattano nagantare nagavivaraṃ samassito +
Vītaddaro vigatakhilo va jhāyati tato ratiṃ paramataraṃ na vindati._
____

==== Va = iva: mopes like

On one occasion, va _jhāyatī_ stands for _iva jhāyatī_, i.e. 'he mopes 
like':

[quote, S.1.57]
____
So the fool, having left the teaching to follow a way opposed to the teaching, 
mopes like [the carter] with a broken axle when he falls into the mouth of 
Death.

_Evaṃ dhammā apakkamma adhammamanuvattiya +
Mando maccumukhaṃ patto akkhacchinno va jhāyatī ti._
____

For meanings of _jhāyati_ see Glossary sv _Jhāyati_.

==== The problematic forms

In the remaining cases, where _va_ emphasises _jhāyati_, it is not clear how 
it should be emphasised. Norman uses the phrase 'meditates indeed,' which deals 
with the problem without solving it. We choose to parenthesise and to follow 
the context. As noted above, when meditation is in nature, we parenthesise 
'[happily]'. For example:

[quote, Th.v.522]
____
When the thundercloud peals in the heavens, and the sky all around is full of 
rain, and the bhikkhu meditates [happily] indeed in his mountain cave, one does 
not find greater delight than this.

_Yadā nabhe gajjati meghadundubhi dhārākulā vihagapathe samantato +
Bhikkhū ca pabbhāragato va jhāyati tato ratiṃ paramataraṃ na vindati._
____

Where the meditation is not in nature, we parenthesise 'mindfully':

[quote, Th.v.892]
____
Having abandoned mother, father, sisters, brothers, and relatives; having 
abandoned the five varieties of sensuous pleasure; Anuruddha meditates 
&#8203;[mindfully] indeed.

_Pahāya mātāpitaro bhaginī ñātibhātaro +
Pañcakāmaguṇe hitvā anuruddho va jhāyati._
____

=== Illustrations

.Illustration
====
va jhayati

mopes [mournfully] indeed; va jhayati, mopes like [the carter]
====

____
As the carter who abandoned the highway, a road with an even surface, and 
entered upon a rugged bypath, mopes [mournfully] indeed with a broken axle

_Yathā sākaṭiko patthaṃ samaṃ hitvā mahāpathaṃ +
Visamaṃ maggamāruyha akkhacchinno va jhāyati._
____

[quote, S.1.57]
____
So the fool, having left the teaching to follow a way opposed to the teaching, 
mopes like [the carter] with a broken axle when he falls into the mouth of 
Death.

_Evaṃ dhammā apakkamma adhammamanuvattiya +
Mando maccumukhaṃ patto akkhacchinno va jhāyatī ti._
____

Comment:

The context of the first verse suggests _eva jhāyati_ and demands the 
parenthesis of a word like 'mournfully': mopes [mournfully] indeed. As noted 
above, the second suggests _iva jhāyati_: 'mopes like [the carter]'.

