== Vadhati; Vadha

=== Renderings

- _vadha_: killing

- _vadha_: destruction

- _vadha_: execution

- _vadha_: punishment

_• vadhaka_: murderer

- _vadhati_: to destroy

- _vadhati_: to punish

- _vadhati_: to crush

- _vadhati_: to slaughter

- _vadhati_: to kill

- _vadhati_: to murder

- _vadhati_: to strike

=== Introduction

==== Understanding the First Brahman Truth

Understanding the First Brahman Truth is challenged by the different meanings 
of _vadhati_ which range from punish to destroy. This uncertainty is reflected 
in translations of this Truth:

- Bodhi: All living beings are to be spared.

- Woodward: All living beings are not to be harmed.

We say 'destroyed':

[quote, A.2.176]
____
All beings ought not to be destroyed... In fully understanding the truth of 
this saying one is applied to the practice of sympathy and tender concern for 
beings.

_sabbe pāṇā avajjhā ti... Api ca yadeva tattha saccaṃ tadabhiññāya 
pāṇānaṃ yeva anuddayāya anukampāya paṭipanno hoti._
____

==== Harming does not fit

One cannot say 'All beings ought not to be harmed,' because firstly, _vadhati_ 
does not mean 'to harm,' and secondly, harming is sometimes for beings' 
benefit. For example:

____
If a young infant through the negligence of the nurse puts a stick or stone 
into its mouth, the nurse would quickly pay attention, and quickly remove it. 
If she could not immediately remove it, then taking hold of the head with the 
left hand, and crooking the finger of the right, would fetch it out even if she 
drew blood. Why is this?

_salohitampi āhareyya taṃ kissa hetu_
____

[quote, A.3.6]
____
... There would be some injury to the boy, I do not deny it. But, really, this 
is what should be done by the nurse wishing for the child's well-being, seeking 
its welfare, from tender concern, out of tender concern.

_atthesā bhikkhave kumārassa vihesā nesā natthīti vadāmi. Karaṇīyañca 
kho etaṃ bhikkhave dhātiyā atthakāmāya hitesiniyā anukampikāya 
anukampaṃ upādāya._
____

==== Striking does not fit

One cannot say 'All beings ought not to be struck,' for three reasons:

1. Firstly, although it is a pācittiya offence for a bhikkhu to strike a 
bhikkhu in anger (_Yo pana bhikkhu bhikkhussa kupito anattamano pahāraṃ 
dadeyya pācittiyan ti_, Vin.4.146), and a dukkaṭa offence to strike a 
layperson, it no offence at all to strike an animal, and also no offence if, 
being trapped in a difficult situation, a bhikkhu strikes a bhikkhu in order to 
escape (_Anāpatti kenaci viheṭhiyamāno mokkhādhippāyo pahāraṃ deti_, 
Vin.4.146).

2. Secondly, the Buddha, faced with a weak disciple, raised the possibility of 
physical punishment:

[quote, Th.v.200]
____
'Don't go nodding, Ragamuffin, lest I strike you on the ear.'

_Mā kho tvaṃ kappaṭa pacalāyi mā tvaṃ upakaṇṇamhi tāḷessaṃ._
____

3. Thirdly, the Buddha battled with the fire-serpent in Kassapa's fire-chamber, 
mastering his heat with heat, but without injuring his skin (_anupahacca 
chaviñca_, Vin.1.25).

Striking is not necessarily unvirtuous.

==== Gerundives

The gerundive is passive in sense, and expresses suitability, fitness, 
propriety, and may be translated by 'fit to be,' 'must be,' 'ought to be,' 'to 
be' (PGPL, para.466).

=== Illustrations: vadha

.Illustration
====
vadha

killing
====

[quote, M.1.345-6]
____
He abstains from wounding, killing, imprisoning, brigandage, plunder, and 
violence.

_Chedanavadhabandhanaviparāmosaālopasahasākārā paṭivirato hoti._
____

.Illustration
====
vadho

destruction
====

[quote, A.2.112]
____
For this, Kesi, is 'destruction' in the [terminology of the] Noble One's 
training system, when the Perfect One and one's knowledgeable companions in the 
religious life think one should not be spoken to and instructed.

_Vadho hesa kesi ariyassa vinaye yaṃ na tathāgato vattabbaṃ 
anusāsitabbaṃ maññati napi viññū sabrahmacārī vattabbaṃ 
anusāsitabbaṃ maññantī ti._
____

.Illustration
====
vadho

destruction
====

[quote, Vin.2.194]
____
Devadatta is intent upon the destruction of the Blessed One.

_devadattena kira bhagavato vadho payutto ti._
____

.Illustration
====
vadhāya

destruction
====

[quote, S.2.241]
____
Just as a plantain tree yields fruit to its own destruction and spiritual 
ruination, so Devadatta's gains, honour, and renown arose to his own 
destruction and spiritual ruination.

_Seyyathā pi bhikkhave kadali attavadhāya phalaṃ deti parābhavāya 
phalaṃ deti evameva kho bhikkhave attavadhāya devadattassa 
lābhasakkārasiloko udapādi parābhavāya devadattassa lābhasakkārasiloko 
udapādi._
____

.Illustration
====
vadhāya

destruction
====

[quote, S.1.67]
____
Like bait thrown out for the destruction of fish

_Āmisaṃva macchānaṃ vadhāya khittā ti._
____

.Illustration
====
vadhāya

execution
====

[quote, Vin.1.88]
____
Those who were caught were led off to execution.

_ye te gahitā te vadhāya onīyanti._
____

.Illustration
====
vadho

punishment
====

____
He who has mastered the thorn of sensuous pleasure,

_Yassa jito kāmakaṇṭako_
____

____
Abuse, punishment, and imprisonment,

_Akkoso ca vadho ca bandhanañca_
____

[quote, Ud.27]
____
Is as inwardly stable as a mountain, imperturbable,

_pabbato viya so ṭhito anejo._
____

=== Illustrations: vadhaka

.Illustration
====
vadhaka

murderer
====

[quote, Vin.2.193]
____
With the attitude of a murderer, drew the Perfect One's blood.

_vadhakacittena tathāgatassa ruhiraṃ uppāditanti._
____

.Illustration
====
vadhakaṃ

murderous
====

[quote, S.3.114]
____
He does not discern according to reality murderous bodily form as murderous 
bodily form.

_Vadhakaṃ rūpaṃ vadhakaṃ rūpanti yathābhūtaṃ nappajānāti._
____

=== Illustrations: vadhati

.Illustration
====
vadhitvā

destroyed
====

[quote, M.1.159]
____
This is called a bhikkhu who has blindfolded Māra, who is trackless having 
destroyed Māra's vision, and goes unseen by the Maleficent One.

_Ayaṃ vuccati bhikkhave bhikkhu andhamakāsi māraṃ apadaṃ vadhitvā 
māracakkhuṃ adassanaṃ gato pāpimato._
____

.Illustration
====
vadhitvā

punished
====

[quote, D.1.98]
____
Suppose a brahman, for some reason, has had his head shaved by the brahmans, 
and been punished with a bag of ashes, and banished from the country or the 
city.

_Idha brāhmaṇā brāhmaṇaṃ kismicideva pakaraṇe khuramuṇḍaṃ 
karitvā assapuṭena vadhitvā raṭṭhā vā nagarā vā pabbājeyyuṃ._
____

.Illustration
====
avajjhā

unpunishable
====

[quote, Sn.v.288]
____
Brahmans were unpunishable, unimpeachable, protected by law.

_Avajjhā brāhmaṇā āsuṃ ajeyyo dhammarakkhitā._
____

Norman: Brahmans were inviolable, unconquerable, protected by the law.

.Illustration
====
vadhito

crushed
====

• The fool lies prostrate as if crushed by his folly. +
☸ _Bālo hi bālyā vadhitova seti_ (Th.v.783) (M.2.73).

.Illustration
====
vadhitvā

slaughter
====

[quote, D.2.294]
____
A proficient butcher or his apprentice having slaughtered a cow.

_dakkho goghātako vā goghātakantevāsī vā gāviṃ vadhitvā._
____

.Illustration
====
vadhitvā

kill
====

[quote, D.3.23]
____
Lion... having killed the very best of the herd

_so varaṃ varaṃ migasaṅghe vadhitvā._
____

.Illustration
====
vadhitvā

kill
====

[quote, D.3.130]
____
Some foolish person takes pleasure and delight in killing beings.

_ekacco bālo pāṇe vadhitvā vadhitvā attānaṃ sukheti pīṇeti._
____

.Illustration
====
vadhitvā

murder
====

[quote, M.2.98]
____
Having murdered many people, he wears a necklace of their fingers.

_So manusse vadhitvā vadhitvā aṅgulīnaṃ mālaṃ dhāreti._
____

.Illustration
====
vadhitvā

struck
====

[quote, Vin.4.277]
____
The bhikkhunī Caṇḍakāḷī, having quarrelled with the bhikkhunīs, wept 
having struck herself again and again.

_caṇḍakāḷī bhikkhunī bhikkhunīhi saddhiṃ bhaṇḍitvā attānaṃ 
vadhitvā vadhitvā rodati._
____

