== Vanatha; Vana

=== Renderings

- _vanatha_: craving

- _vana_: craving

- _nibbanatha_: freedom from craving

- _nibbana_: freedom from craving

=== Introduction

==== Vana and vanatha: the negatives

The negatives of _vana_ and _vanatha_ are _nibbana_ and _nibbanatha_. See 
quotes below.

==== Vanatha: controversy

The meaning of _vanatha_ [_vana+tha_] is unsettled. The primary meaning is 
'underwood, brushwood, thicket.' In its figurative sense PED says 'lust, 
desire.' Buddhaghosa says _kilesa_. Dhammapāla says _taṇhā_. For example:

_• Vanatho jāto_ (S.2.158). Commentary: _kilesavanaṃ jātaṃ_ 
(Buddhaghosa).

- _Vanathaṃ na kareyya kuhiñci_ (Th.v.1214). Commentary: _taṇhaṃ na 
kareyyaṃ_ (Dhammapāla).

==== Vanatha means taṇhā

_Vanatha_ should be called _taṇhā_, not attachment, for two reasons:

1. the words _nibbanatho visallo_ occur together on two occasions, indicating 
synonymity, (Th.v.525-6; S.1.180) where _visallo_ means 'free of the arrow of 
_taṇhā_.' And if _nibbanatho_ (_nis+vanatha_) and _visallo_ are synonyms, 
then so are _vanatha_ and _taṇhā_. See illustrations below.

2. In Sn.v.16 _vanatha_ is the basis of grasping. This again fits well with 
calling it _taṇhā_ not attachment. See illustrations below.

==== Vana: controversy

_Vana_ has two meanings, _vana1_ (=Vedic _vana_) and _vana2_ (=__van__). The 
former means 'jungle,' the latter means 'desire'. The two words are confused in 
exegetical literature, says sharply critical PED:

- 'The Pāli (edifying) etymology clearly takes _vana1_ as belonging to 
_vana2_, and dogmatically equals it with _vana2_ as an allegorical expression 
('jungle') to _taṇhā_.'

What we said about _vanatha_ we can repeat with _vana_ (i.e. _vana2_). PED 
repeats its position on _vanatha_ (i.e. 'lust, desire'), but the commentators 
now switch. Dhammapāla says _kilesa,_ and Buddhaghosa says _taṇhā_:

- _Nibbano_ (Sn.v.1131): _kilesavanavirahito taṇhāvirahito eva vā_ 
(Buddhaghosa).

- _Vanādhimutto_ (Dh.v.344): _taṇhāvanā mutto_ (Buddhaghosa).

_• Vanā_ (Th.v.691): _kilesavanato_ (Dhammapāla).

==== Vana and vanatha: synonyms

The following quotes treat _vana_ and _vanatha_ (=__banatha__) as synonyms:

[quote, Dh.v.283]
____
Having cut down all forms of craving, be free of craving, bhikkhus.

_Chetvā vanañca vanathañca nibbanā hotha bhikkhavo._
____

[quote, Dh.v.344]
____
He, [wanting to be] free of craving, was intent upon [life in] the forest. 
&#8203;[Wanting to be] free of craving he ran to the forest.

_Yo nibbanatho vanādhimutto vanamutto vanameva dhāvati._
____

[quote, S.1.180]
____
My craving is chopped down at the root... I am free of craving.

_ucchinnamūlaṃ me vanaṃ... nibbanatho._
____

=== Illustrations

.Illustration
====
vanatho

craving
====

[quote, S.2.158]
____
By consorting [with householders and ascetics] craving is born. By remaining 
aloof [from householders and ascetics] it is cut.

_Saṃsaggā vanatho jāto asaṃsaggena chijjati._
____

Commentary (Buddhaghosa): _Vanatho jāto ti kilesavanaṃ jātaṃ_

.Illustration
====
vanathaṃ kareyya

cultivate craving
====

[quote, Th.v.1214]
____
One should not cultivate craving for anything. One who is free of craving, 
being without craving, he is a bhikkhu.

_Vanathaṃ na kareyya kuhiñci nibbanatho avanatho sa bhikkhu._
____

Commentary (Dhammapāla): _Vanathaṃ na kareyya kuhiñcīti 
ajjhattikabāhirappabhede sabbasmiṃ vatthusmiṃ taṇhaṃ na kareyyaṃ. 
Nibbanatho avanatho sa bhikkhū ti yo hi sabbena sabbaṃ nittaṇho._

.Illustration
====
vanatho

craving
====

[quote, Sn.v.16]
____
He in whom there is nothing born of craving acting as a cause for emotional 
bondage [to individual existence]

_Yassa vanathajā na santi keci vinibandhāya bhavāya hetukappā._
____

Comment:

_Vanathajā na santi keci vinibandhāya bhavāya hetukappā_: 'nothing born of 
craving acting as a cause for emotional bondage [to individual existence].' 
This 'nothing' would be grasping, because:

• Without grasping what is unlasting, existentially void, destined to change, 
could there arise psychological bondage, stubborn attachment, emotional 
bondage, and cleaving? +
☸ _Yaṃ panāniccaṃ dukkhaṃ vipariṇāmadhammaṃ api nu taṃ 
anupādāya uppajjeyyuṃ saṃyojanābhinivesa-vinibandhājjhosānā ti. No 
hetaṃ bhante_, (S.3.187).

Commentary (Buddhaghosa): _Vanathā jātāti vanathajā ti. Keci panāhu 
sabbepi kilesā gahanaṭṭhena vanatho ti vuccanti, aparāparuppannā pana 
vanathajā ti._

.Illustration
====
vanatho

craving
====

[quote, Dh.v.284]
____
So long as even the slightest craving of a man for women is not obliterated, so 
long is he emotionally bound to them, like a suckling calf to its mother.

_Yāva hi vanatho na chijjati aṇumatto pi narassa nārisu +
Paṭibaddhamano va tāva so vaccho khīrapako va mātari._
____

Commentary (Buddhaghosa): _Yāva hi vanatho ti yāva esa aṇumattopi 
kilesavanatho narassa nārīsu na chijjati._

.Illustration
====
nibbanatho

free of craving
====

[quote, S.1.180]
____
Free of craving, with the arrow [of craving] removed I find delight alone in 
the woods.

_Svāhaṃ vane nibbanatho visallo eko rame._
____

Commentary (Buddhaghosa): _Nibbanatho ti nikkilesavano_

.Illustration
====
vanaṃ

craving
====

[quote, S.1.180]
____
There is nothing in the woods I need to do. My craving is chopped down at the 
root. It is dried up. Free of craving, with the arrow [of craving] removed, and 
with disgruntlement [with the celibate life] cast off, I find delight alone in 
the woods.

_Na me vanasmiṃ karaṇīyamatthi ucchinnamūlaṃ me vanaṃ visūkaṃ +
Svāhaṃ vane nibbanatho visallo eko rame aratiṃ vippahāyāti._
____

Commentary (Buddhaghosa): _Ucchinnamūlaṃ me vanan ti mayhaṃ kilesavanaṃ 
ucchinnamūlaṃ. Nibbanathoti nikkilesavano_

.Illustration
====
nibbano

free of craving
====

[quote, Sn.v.1131]
____
Free of sensuous yearning, free of craving

_Nikkāmo nibbano._
____

Commentary (Buddhaghosa): _Nibbano ti kilesavanavirahito taṇhāvirahito eva 
vā_

.Illustration
====
vanā

craving; nibbano, freedom from craving
====

[quote, Th.v.691]
____
Gone from craving to freedom from craving.

_Vanā nibbanamāgataṃ._
____

Commentary (Dhammapāla): _Vanā nibbanamāgatan ti kilesavanato tabbirahitaṃ 
nibbanaṃ upagataṃ_

