== Vasala

=== Renderings

- _vasala_: wretch

- _vasali_: wretched woman

- _vasala_: wretched

=== Introduction

==== On insulting non-brahmans

_Vasala_ literally means 'little man' (PED). It was a term of abuse used by 
brahmans in reference to members of other social groups. For example, when 
Aggika Bhāradvāja saw the Blessed One coming in the distance, he shouted:

____
'Stop, you! Right there, shaveling! Right there, sham ascetic! Right there, 
wretch!

_tatreva muṇḍaka tatreva samaṇaka tatreva vasalaka tiṭṭhāhī ti._
____

==== On insulting other brahmans

Brahmans also used it to insult other brahmans. For example, when a brahman's 
wife praised the Buddha, the brahman said (of his own wife!):

[quote, S.1.160]
____
On the slightest pretext this wretched woman spouts praise of that shaveling 
ascetic!

_evamevaṃ panāyaṃ vasali yasmiṃ vā tasmiṃ vā tassa muṇḍakassa 
samaṇassa vaṇṇaṃ bhāsati._
____

==== On insulting one's own posterior

Brahmans used it to insult their own bodies:

[quote, Vin.2.221]
____
Now at that time a certain bhikkhu who had been born a brahman, having 
defaecated, did not want to rinse himself, thinking: 'Who would touch this 
wretched, stinking thing?' A worm remained in his anus.

_Tena kho pana samayena aññataro bhikkhu brāhmaṇa jātiko vaccaṃ katvā 
na icchati ācametuṃ ko imaṃ vasalaṃ duggandhaṃ āmasissatīti. Tassa 
vaccamagge kimi saṇṭhāsi._
____

==== No castes, no outcastes

Caste is 'one of the hereditary social classes in Hinduism that restrict the 
occupation of their members and the association with the members of other 
castes' (Webster's).

The four classes of the Buddha's time were therefore not technically castes 
because intermarriage was still possible (D.1.97). Marriage to even low-class 
women was common amongst brahmans (A.3.229). Queen Mallika was King Pasenadi's 
wife, though her father was a garland-maker.

So _vasala_ cannot mean 'outcaste'.

