== Vera

=== Renderings

- _vera_: unfriendliness

- _verā_: unfriendly deeds

- _verā_: deeds that beget unfriendliness

=== Illustrations

.Illustration
====
averā

free of unfriendliness; averino, uncordiality
====

[quote, D.2.276]
____
May we abide free of unfriendliness, violence, enmity, hostility, and 
uncordiality

_averā adaṇḍā asapattā avyāpajjhā viharemu averino ti._
____

.Illustration
====
verāni

unfriendly deeds (plural); verena, unfriendliness
====

[quote, M.3.154]
____
Unfriendly deeds do not in any way cease in this world through unfriendliness. 
They cease through friendliness. This is a timeless truth.

_Na hi verena verāni sammantīdha kudācanaṃ +
Averena ca sammanti esa dhammo sanantano._
____

Comment:

The singular/plural switch has proven problematic.

- Horner says 'wrathful moods': 'not by wrath are wrathful moods allayed'

- Bodhi misplaces the plural: 'Hatred is never allayed by further acts of hate.'

.Illustration
====
verāni

unfriendly deeds (plural); veraṃ, unfriendliness
====

&#8203;[Fault-finding devas:]

• 'If one does not grant pardon to those who confess their transgressions, 
being inwardly angry, intent on hatred, one strongly harbours unfriendliness.'* 
+
☸* _Accayaṃ desayantīnaṃ yo ce na paṭigaṇhati +
Kopantaro dosagaru sa veraṃ paṭimuccati._

&#8203;[The Buddha:]

[quote, S.1.24]
____
'If there was no transgression, if here there was no going astray, and if one's 
unfriendly deeds were stopped, through this one would be excellent in this 
world.'

_Accayo ce na vijjetha no cidhāpagataṃ siyā +
Verāni ca sammeyyuṃ tenīdha kusalo siyā._
____

.Illustration
====
verānaṃ

unfriendly deeds
====

____
For two good reasons the Perfect One establishes training rules for his 
disciples.

_Dveme bhikkhave atthavase paṭicca tathāgatena sāvakānaṃ sikkhāpadaṃ 
paññattaṃ. Katame dve?_
____

____
To restrain unfriendly deeds (i.e. the bhikkhu's own deeds) in this lifetime,

_diṭṭhadhammikānaṃ verānaṃ saṃvarāya_
____

[quote, A.1.98]
____
and to ward off unfriendly deeds (i.e. acts of retribution?) in the hereafter.

_samparāyikānaṃ verānaṃ paṭighātāya._
____

.Illustration
====
verā

unfriendly deed (plural); veraṃ, unfriendliness
====

&#8203;[Prince Dīghāvu, to Brahmādatta, the King of Kāsi, who executed Dīghāvu's 
father:]

'Concerning that, Your Majesty, which my father said to me at the time of his 
death:

____
"not far" means: Do not sustain unfriendliness long.

_mā dīghan ti mā ciraṃ veraṃ akāsī ti_
____

____
"not close" means: Do not hastily break with a friend.

_mā rassan ti mā khippaṃ mittehi bhijjitthā ti_
____

____
"Unfriendly deeds are not stopped by unfriendliness. Unfriendly deeds, dear 
Dīghāvu, are stopped by friendliness" means:

_na hi tāta Dīghāvu verena verā sammanti. Averena hi tāta dīghāvu verā 
sammantī ti_
____

____
'My parents were killed by a king. But if I were to deprive the king of life 
those who desired the king's well-being would deprive me of life and those who 
desired my well-being would deprive these of life. Thus that unfriendly deed 
would not be settled by unfriendliness.

_devena me mātāpitaro hatā ti sacāhaṃ devaṃ jīvitāvoropeyyaṃ ye 
devassa atthakāmā te maṃ jīvitā voropeyyuṃ. Ye me atthakāmā te te 
jīvitā voropeyyuṃ. Evaṃ taṃ veraṃ verena na vūpasameyya_
____

[quote, Vin.1.348]
____
'But now that life is granted me by a king, and life is granted a king by me, 
thus is that unfriendly deed settled by friendliness.'

_idāni ca pana me devena jīvitaṃ dinnaṃ. Mayā ca devassa jīvitaṃ 
dinnaṃ. Evaṃ taṃ veraṃ averena vūpasantaṃ._
____

.Illustration
====
averā

unfriendliness
====

[quote, M.1.288]
____
May these creatures sustain themselves happily, and be rid of unfriendliness, 
hostility, and spiritual defilement.

_ime sattā averā avyāpajjhā anīghā sukhi attānaṃ pariharantū ti._
____

.Illustration
====
verā

unfriendliness
====

[quote, Dh.v.291]
____
He who wants his own happiness through causing others suffering, in embroiling 
himself in unfriendliness, from unfriendliness he will not be released.

_Paradukkhūpadhānena attano sukhamicchati +
Verasaṃsaggasaṃsaṭṭho verā so na parimuccati._
____

.Illustration
====
veraṃ

unfriendliness
====

Then Prince Dīghāvu, having stroked the head of Brahmadatta, the King of 
Kasi, with his left hand, having drawn his sword with his right hand, spoke 
thus to Brahmadatta, the King of Kasi:

[quote, Vin.1.347]
____
-- I, Your Majesty, am Prince Dīghāvu, that son of Dīghāvu, the King of 
Kosala. You have done us much mischief. Our troops, vehicles, territory, 
storehouses and granaries were stolen by you, and my parents were killed by 
you. This could be a time when I could show my unfriendliness

_ayaṅkhavassa kālo yvāhaṃ veraṃ appeyyan ti._
____

.Illustration
====
averaṃ

freedom from unfriendliness
====

____
A noble disciple abandons and refrains from killing. In doing so, to limitless 
beings he gives freedom from fear, unfriendliness, and hostility.

_Idha bhikkhave ariyasāvako pāṇātipātaṃ pahāya pāṇātipātā 
paṭivirato hoti. Pāṇātipātā paṭivirato bhikkhave ariyasāvako 
aparimāṇānaṃ sattānaṃ abhayaṃ deti. Averaṃ deti. Avyāpajjhaṃ 
deti._
____

[quote, A.4.246]
____
Having done so, he partakes of limitless freedom from fear, unfriendliness, and 
hostility.

_Aparimāṇānaṃ sattānaṃ abhayaṃ datvā averaṃ datvā avyāpajjhaṃ 
datvā aparimāṇassa abhayassa averassa avyāpajjhassa bhāgī hoti._
____

.Illustration
====
averena

free of unfriendliness
====

[quote, M.1.126]
____
We shall abide pervading the whole world [of beings] with a mind of [unlimited, 
all-encompassing] goodwill, vast, exalted, unlimited, free of unfriendliness 
and hostility.

_Tadārammaṇañca sabbāvantaṃ lokaṃ mettāsahagatena cetasā vipulena 
mahaggatena appamāṇena averena avyāpajjhena pharitvā viharissāmāti._
____

.Illustration
====
veraṃ

unfriendliness
====

[quote, S.1.208]
____
One whose mind all day and night takes delight in harmlessness, has [unlimited, 
all-encompassing] goodwill for all beings and unfriendliness with none.

_Yassa sabbamahorattaṃ ahiṃsāya rato mano +
Mettaṃ so sabbabhūtesu veraṃ tassa na kenacī ti._
____

.Illustration
====
veraṃ

unfriendliness
====

[quote, S.1.83]
____
Victory begets unfriendliness.

_Jayaṃ veraṃ pasavati._
____

.Illustration
====
veraṃ

unfriendliness
====

[quote, S.2.68]
____
The killer, in killing, begets danger and unfriendliness in this lifetime.

_Yaṃ gahapati pāṇātipātī pāṇātipātapaccayā diṭṭhadhammikampi 
bhayaṃ veraṃ pasavati._
____

.Illustration
====
verāni

deeds that beget unfriendliness
====

[quote, A.3.204]
____
Having not abandoned five deeds that beget danger and unfriendliness one is 
called unvirtuous, and is reborn in hell. Which five? Killing, stealing, 
adultery, lying, and drinking.

_Pañca gahapati bhayāni verāni appahāya dussīlo iti vuccati. Nirayañca 
upapajjati. Katamāni pañca: pāṇātipātaṃ adinnādānaṃ kāmesu 
micchācāraṃ musāvādaṃ surāmerayamajjapamādaṭṭhānaṃ._
____

.Illustration
====
vera

deeds that beget unfriendliness
====

[quote, It.56]
____
One for whom attachment, hatred, and uninsightfulness into reality are 
discarded, they call him spiritually developed, a perfect one become supreme, 
enlightened, one who has left behind deeds that beget danger and 
unfriendliness, one who has abandoned the whole [phenomenon of attachment].

_Yassa rāgo ca doso ca avijjā ca virājitā taṃ bhāvitattaññataraṃ 
brahmabhūtaṃ tathāgataṃ +
Buddhaṃ verabhayātītaṃ āhu sabbappahāyinan ti._
____

