== Vicakkhaṇa

=== Renderings

- _vicakkhaṇa_: prudent

- _vicakkhaṇa_: wise

=== Illustrations

.Illustration
====
vicakkhaṇā

wise
====

[quote, D.3.167]
____
By this means, those who were intelligent and wise said that this person would 
have much happiness.

_Tenāhu naṃ atinipuṇā vicakkhaṇā +
Ayaṃ naro sukhabahulo bhavissati._
____

.Illustration
====
vicakkhaṇo

prudent
====

[quote, Th.v.105]
____
One who is prudent would not stay in an abode that was unconducive to his 
spiritual well-being.

_Na tvevānatthasaṃhitaṃ vase vāsaṃ vicakkhaṇo ti._
____

.Illustration
====
vicakkhaṇo

prudent
====

[quote, Vin.1.359]
____
When interrogated by the assembly he neither broods nor is embarrassed. His 
timely, prudent words, fitting as an explanation, delight the learned assembly.

_Tatheva pañhaṃ parisāsu pucchito na ceva pajjhāyati na maṅku hoti +
So kālāgataṃ vyākaraṇārahaṃ vaco rañjeti viññūparisaṃ 
vicakkhaṇo._
____

.Illustration
====
vicakkhaṇo

prudent
====

[quote, Sn.v.583]
____
If by lamenting and vexing himself, one who is undiscerning of reality elicited 
some advantange, then one who is prudent would do likewise.

_Paridevayamāno ce kiñcidatthaṃ udabbahe +
Sammūḷho hiṃsamattānaṃ kayirā ce naṃ vicakkhaṇo._
____

