== Vicikicchā

=== Renderings

- _vicikicchā_: doubt [about the significance of the teaching]

- _vicikicchati_: to be doubtful [about the perfection of the Perfect One's 
transcendent insight]

- _vicikicchati_: to be doubtful [about the perfection of the Blessed One's 
body]

- _satthari vicikicchati_: to be doubtful about the [perfection of the] 
Teacher's [transcendent insight]

- _dhamme vicikicchati_: to be doubtful about the [significance of the] teaching

- _saṅghe vicikicchati_: to be doubtful about the [praiseworthiness of the] 
community of disciples' [application to the practice]

- _sikkhāya vicikicchati_: to be doubtful about the [significance of the] 
training

- _vicikicchākathaṅkathāsallaṃ_: the arrow of doubt and uncertainty 
&#8203;[about the significance of the teaching]

- _vicikicchākathaṅkathāsallaṃ_: the arrow of doubt and uncertainty 
&#8203;[about the way of spiritual fulfilment, and of unfulfilment]

=== Introduction

==== The four words for doubt

There are four words for doubt:

1. _vicikicchā_: doubt

2. _kaṅkhā_: unsureness

3. _kathaṅkathā_: uncertainty

4. _vimati_: uncertainty

==== Classical objects of doubt

The classical objects of doubt are the Buddha, Dhamma, Saṅgha, and the 
training. Our renderings for these are as follows, with explanations to follow:

- Buddha: doubt about the [perfection of the] Perfect One's [transcendent 
insight]

- Dhamma: doubt about the [significance of the] teaching

- Saṅgha: doubt about the [praiseworthiness of the] community of disciples' 
&#8203;[application to the practice]

- The training: doubt about the [significance of the] training

==== Doubt about the [perfection of the] Buddha's [transcendent insight]

A noble disciple who has unshakeable faith in the Buddha (_ariyasāvako buddhe 
aveccappasādena samannāgato hoti_) has come to the conclusion that:

[quote, S.5.390]
____
He is indeed the Blessed One, the Arahant, the Perfectly Enlightened One, 
perfect in insightfulness into reality and in conduct, the Sublime One, one who 
knows the world [of phenomena] [according to reality], the unexcelled trainer 
of men to be tamed, the teacher of devas and men, the Enlightened One, the 
Blessed One.

_iti pi so bhagavā arahaṃ sammā sambuddho vijjācaraṇasampanno sugato 
lokavidu anuttaro purisadammasārathī satthā devamanussānaṃ buddho 
bhagavā ti._
____

According to this, the noble disciple's faith is not in the person of the 
Buddha, but in the perfection of his transcendent insight. This is in 
accordance with the definition of _saddhindriyaṃ_ which is linked to 
_tathāgatassa bodhiṃ_:

[quote, S.5.196]
____
And what is the faculty of faith? In this regard, the noble disciple has faith. 
He has faith in the [perfection of the] Perfect One's transcendent insight: 'He 
is indeed the Blessed One, the Arahant, the Perfectly Enlightened One, perfect 
in insightfulness into reality and in conduct, the Sublime One, one who knows 
the world [of phenomena] [according to reality], the unexcelled trainer of men 
to be tamed, the teacher of devas and men, the Enlightened One, the Blessed 
One.'

_Katamañca bhikkhave saddhindriyaṃ idha bhikkhave ariyasāvako saddho hoti 
saddahati tathāgatassa bodhiṃ iti pi so bhagavā arahaṃ sammāsambuddho 
vijjācaraṇasampanno sugato lokavidū anuttaro purisadammasārathī satthā 
devamanussānaṃ buddho bhagavā ti. Idaṃ vuccati bhikkhave saddhindriyaṃ._
____

Therefore doubt about the Buddha would mean 'doubt about the [perfection of 
the] Buddha's [transcendent insight].'

==== Doubt about the [significance of the] teaching

A noble disciple who has unshakeable faith in the teaching (_ariyasāvako 
dhamme aveccappasādena samannāgato hoti_) has come to the conclusion that:

• The teaching is well explained by the Blessed One, fathomable in this 
lifetime, realisable in the here and now, intriguing, personally applicable, to 
be realised by the wise for themselves._ +
☸ svākkhāto bhagavatā dhammo sandiṭṭhiko akāliko ehipassiko opanayiko 
paccattaṃ veditabbo viññūhī ti_ S.5.390).

In the light of these qualities, the teaching's excellence and effectiveness, 
doubt about the Dhamma means 'doubt about the [significance of the] teaching.'

==== Doubt about the [praiseworthiness of the] community of disciples' 
&#8203;[application to the practice]

A noble disciple who has unshakeable faith in the community of disciples 
(_ariyasāvako saṅghe aveccappasādena samannāgato hoti_) has come to the 
conclusion that:

• The community of the Blessed One's disciples is applied to an excellent 
practice, is applied to the correct practice, is applied to the noble practice, 
is applied to a proper practice; that is, the four pairs of persons, the eight 
types of individuals. This community of the Blessed One's disciples is worthy 
of offerings, hospitality, gifts, and honouring with joined palms. They are the 
unsurpassed field of merit for the world._ +
☸ supaṭipanno bhagavato sāvakasaṅgho ujupaṭipanno bhagato 
sāvakasaṅgho ñāyapaṭipanno bhagavato sāvakasaṅgho sāmīcipaṭipanno 
bhagavato sāvakasaṅgho yadidaṃ cattāri purisayugāni 
aṭṭhapurisapuggalā esabhagavato sāvakasaṅgho āhuneyyo pāhuneyyo 
dakkhiṇeyyo añjalikaraṇīyo anuttaraṃ puññakkhettaṃ lokassāti_ 
S.5.390).

'Unshakeable faith in the community of disciples' is therefore not primarily 
faith in the members of the community, but in the praiseworthiness of their 
application to the practice. Therefore doubt about the Saṅgha would mean 
'doubt about the [praiseworthiness of the] community of disciples' [application 
to the practice].'

==== Doubt about the [significance of the] training

The fourth area of doubt concerns 'the training' (_sikkhāya kaṅkhati 
vicikicchati_ (A.3.249). But what is doubtful about the training? The 
scriptures say:

• This religious life is lived for the sake of a benefit from the training... 
to inspire faith in those without faith, and to increase the faith of those 
with faith... for the complete destruction of suffering. +
☸ _Sikkhānisaṃsamidaṃ bhikkhave brahmacariyaṃ vussati_... 
_appasannānaṃ pasādāya pasannānaṃ bhiyyobhāvāya... sabbaso sammā 
dukkhakkhayāya_ (A.2.243).

Therefore, in relation to the training, doubt would mean 'doubt about the 
&#8203;[significance of the] training.'

==== Doubt about the [significance of the] Path and the practice

With the Path (_magga_) and practice (_paṭipadā_), we also render them in 
terms of 'significance':

[quote, D.2.155]
____
The Perfect One, Ānanda, has the actual knowledge that there is not one 
bhikkhu in this assembly of bhikkhus who is unsure or uncertain about the 
&#8203;[perfection of the] Buddha's [transcendent insight], or about the [significance 
of the] teaching, or about the [praiseworthiness of the] community of 
disciples' [application to the practice], or about the [significance of the] 
Path and the practice.

__ñāṇameva hettha ānanda tathāgatassa natthi imasmiṃ bhikkhu saṅghe 
ekabhikkhussāpi kaṅkhā vā vimati vā buddhe vā dhamme vā saṅghe vā 
magge vā paṭipadāya vā._
____

==== Unspecified doubt in the scriptures

Often the scriptures do not specify the object of doubt, whether it means doubt 
about the Buddha, or the teachings, or the community of disciples, or the 
training. However, most contexts suggest that unspecified doubt refers to the 
teachings, and there is definite evidence for this, too, as follows:

1. The second of the five ties to individual existence in the low plane of 
existence (_pañcorambhāgiyāni saṃyojanāni_) is usually called unspecified 
_vicikicchā_ (D.3.234). But in the _Mahāmāluṅkya Sutta_, this unspecified 
doubt is plainly linked to the teachings:
+
[quote, M.1.433]
____
A young infant does not have the notion 'teachings' (_dhammā ti pi na hoti_), 
so how could doubt about the [significance of the] teachings arise in him? Yet 
the proclivity to it lurks within him

_dhammā ti pi na hoti. Kuto panassa uppajjissati dhammesu vicikicchā 
anusetitvevassa vicikicchānusayo._
____

2. The fifth of the five hindrances is usually called unspecified 
_vicikicchā_, but when the bhikkhu in the _Upajjhāya Sutta_ experienced 
doubt, he linked it to the teachings, _dhammesu vicikicchā_:
+
[quote, A.3.69]
____
Bhante, my body now seems as if drugged. I have lost my bearings. The teachings 
do not occur to my mind. Lethargy and torpor plague my mind. I live the 
celibate life disgruntled. I am doubtful about the [significance of the] 
teaching (_dhammesu vicikicchā_)

_etarahi me bhante madhurakajāto ceva kāyo. Disā ca me na pakkhāyanti. 
Dhammā ca maṃ nappaṭibhanti. Thīnamiddhañca me cittaṃ pariyādāya 
tiṭṭhati. Anabhirato ca brahmacariyaṃ carāmi. Atthi ca me dhammesu 
vicikicchā ti._
____

3. In several suttas doubt is openly linked to _saddhamma_:
+
[quote, S.3.99]
____
The ignorant Everyman... is unsure, doubtful, undecided about the 
[significance of the] true teaching (_saddhamme_).

_assutavā puthujjano... kaṅkhī hoti vicikicchī aniṭṭhaṅgato saddhamme._
____
+
[quote, A.2.174]
____
Some person here is unsure, doubtful, undecided about the [significance of the] 
true teaching (_saddhamme_).

_Puna ca paraṃ brāhmaṇa idhekacco kaṅkhī hoti vicikicchī 
aniṭṭhaṅgato saddhamme._
____

4. Because all aspects of faith stem from faith in the teachings (see following 
quotes), doubt in the teachings necessarily implies doubt in all objects of 
faith. Therefore doubt in the teachings is effectively the all-embracing term, 
and can be used as such when the object of doubt is unspecified. That faith in 
the teachings is the basis of other aspects of faith is shown in these quotes:
+
[quote, M.1.179]
____
On hearing the teaching he acquires faith in the [perfection of the] Perfect 
One's [transcendent insight]

_So taṃ dhammaṃ sutvā tathāgate saddhaṃ paṭilabhati._
____
+
[quote, M.1.320]
____
As the Blessed One explained the teaching to me with its increasingly higher 
and more sublime levels, concerning what is inwardly dark and bright with their 
correlative combinations, thus through transcendent insight into a certain one 
of those teachings, I came to a conclusion about the teachings. I gained faith 
in the Teacher thus: "The Blessed One is perfectly enlightened. The teaching is 
well explained by the Blessed One. The community of disciples is applied to an 
excellent practice."

_Yathā yathā me āvuso bhagavā dhammaṃ deseti uttaruttariṃ 
paṇītapaṇītaṃ kaṇhasukkasappaṭibhāgaṃ tathā tathāhaṃ 
tasmiṃ dhamme abhiññāya idhekaccaṃ dhammaṃ dhammesu 
niṭṭhamagamaṃ satthari pasīdiṃ sammā sambuddho bhagavā svākkhāto 
bhagavatā dhammo supaṭipanno saṅgho ti._
____
+
[quote, A.5.115]
____
Faith [in the perfection of the Perfect One's transcendent insight] has a 
nourishing condition, I declare, not no nourishing condition. And what is the 
condition that nourishes it? Listening to the true teaching, one should reply.

_Saddhampahaṃ bhikkhave sāhāraṃ vadāmi saddhammasavanantissa 
vacanīyaṃ._
____

==== Two areas of doubt [about the significance of the teaching]: internal things and external things

The hindrance of doubt is twofold:

1. Doubt [about the significance of the teaching] in relation to internal 
things is a spiritual hindrance.
+
****
_Yadapi bhikkhave ajjhattaṃ dhammesu vicikicchā tadapi nīvaraṇaṃ_
****

2. Doubt [about the significance of the teaching] in relation to external 
things is also a spiritual hindrance.
+
****
_Yadapi bahiddhā dhammesu vicikicchā tadapi nīvaraṇaṃ_
****

[quote, S.5.110]
____
Thus what is concisely called the hindrance of doubt [about the significance of 
the teaching] becomes twofold by this method of exposition.

_Vicikicchā nīvaraṇanti itihidaṃ uddesaṃ gacchati tadamināpetaṃ 
pariyāyena dvayaṃ hoti._
____

==== Vicikicchā saṃyojana and nīvaraṇa: what is the difference?

_Vicikicchā saṃyojana_ is abandoned at stream-entry. _Vicikicchā 
nīvaraṇa_ is abandoned at arahantship. We call both terms 'doubt [about the 
significance of the teaching].' What is the difference?

1. _Vicikicchā saṃyojana_ is a powerful form of doubt that is a tie to 
individual existence in the low plane of existence:
+
[quote, M.1.434]
____
The ignorant Everyman abides with a mind absorbed in and overcome by doubt 
&#8203;[about the significance of the teaching]. He does not discern according to 
reality the deliverance from the arisen doubt [about the significance of the 
teaching]. When that doubt [about the significance of the teaching] is powerful 
and unsubdued in him, it is a tie to individual existence in the low plane of 
existence.

_vicikicchāpariyuṭṭhitena cetasā viharati vicikicchāparetena. Uppannāya 
ca vicikicchāya nissaraṇaṃ yathābhūtaṃ nappajānāti. Tassa sā 
vicikicchā thāmagatā appaṭivinītā orambhāgiyaṃ saṃyojanaṃ._
____

2. _Vicikicchā nīvaraṇa_ is a less powerful form of doubt that lingers till 
arahantship. Whereas arahants have abandoned the five hindrances so that they 
are chopped down at the root, completely and irreversibly destroyed, never to 
arise again in future (_pahīnā ucchinnamūlā tālāvatthukatā 
anabhāvakatā āyatiṃ anuppādadhammā_ S.5.327), disciples in training are 
still in the process of abandoning them (_nīvaraṇe pahāya viharanti_, 
S.5.327).

==== Purification of doubt and perfection of faith

The purification of doubt corresponds to an increasing faith which reaches 
perfection at arahantship. At levels below arahantship, the faculties, 
including the faculty of faith, are weaker, implying that doubt is stronger:

[quote, S.5.200]
____
One who has completed and fulfilled the five spiritual faculties is an arahant. 
If they are weaker than that, one is a non-returner; if still weaker, a 
once-returner; if still weaker, a stream-enterer.

_Imesaṃ kho bhikkhave pañcannaṃ indriyānaṃ samattā paripūrattā 
arahaṃ hoti. Tato mudutarehi anāgāmī hoti. Tato mudutarehi sakadāgāmī 
hoti. Tato mudutarehi sotāpanno hoti._
____

Although _aveccappasāda_ is associated with stream-entry, and with the phrase 
'The Blessed One is perfectly enlightened,' the _Cūḷahatthipadopama Sutta_ 
says one cannot in fact conclude that the Blessed One is perfectly enlightened 
until arahantship:

[quote, M.1.184]
____
And it is not until this point that a noble disciple can come to the 
conclusion: 'The Blessed One is perfectly enlightened; the teaching is well 
explained by the Blessed One; the community of the Blessed One's disciples is 
applied to an excellent practice.'

_Ettāvatā kho brāhmaṇa ariyasāvako niṭṭhaṃ gato hoti 
sammāsambuddho bhagavā svākkhāto bhagavatā dhammo supaṭipanno bhagavato 
sāvakasaṅgho ti._
____

==== Doubt: what are the consequences?

The scriptures say that if one is unsure, doubtful, undecided about, and has no 
faith in

- the [perfection of the] Teacher's [transcendent insight]

- the [significance of the] teaching

- the [praiseworthiness of the] community of disciples' [application to the 
practice]

- the [significance of the] training

[quote, D.3.237]
____
then one's mind does not incline to vigour, application, perseverance, and 
inward striving.

_idhāvuso bhikkhu satthari... dhamme... saṅghe... sikkhāya... kaṅkhati 
vicikicchati nādhimuccati na sampasīdati... tassa cittaṃ na namati 
ātappāya anuyogāya sātaccāya padhānāya. Yassa cittaṃ na namati 
ātappāya anuyogāya sātaccayā padhānāya._
____

• In contrast, Venerable Sāriputta said a noble disciple who has faith [in 
the perfection of the Perfect One's transcendent insight] will dwell 
energetically applied to the abandoning of spiritually unwholesome factors and 
the undertaking of spiritually wholesome factors; that he will be steadfast, 
unwavering in application [to the practice], not shirking the responsibility of 
&#8203;[undertaking] spiritually wholesome factors._ +
☸ Saddhassa hi bhante ariyasāvakassa etaṃ pāṭikaṅkhaṃ: yaṃ 
āraddhaviriyo viharissati akusalānaṃ dhammānaṃ pahānāya kusalānaṃ 
dhammānaṃ upasampadāya thāmavā daḷhaparakkamo anikkhittadhuro kusalesu 
dhammesu_ S.5.410).

[quote, S.5.398]
____
Sometimes a noble disciple might abide negligently applied [to the practice] 
(_ariyasāvako pamādavihārī hoti_). Although he has unshakeable faith in the 
Buddha and the teaching, he is content with that faith, and does not make 
further effort for physical seclusion by day nor for solitary retreat at night.

_aveccappasādena santuṭṭho na uttariṃ vāyamati divā pavivekāya 
rattiṃ paṭisallānāya._
____

According to Venerable Sāriputta's statement, this negligence is due to a 
relative lack of faith, or in other words, the fifth hindrance, doubt [about 
the significance of the teaching]. Thus, even amongst stream-enterers, some 
have stronger faith than others, which can be seen in their levels of diligence.

==== Cause of doubt about the significance of the teaching: craving

Doubt about the significance of the teaching comes from craving (_taṇhā_):

• The ignorant Everyman... is unsure, doubtful, undecided about the 
&#8203;[significance of the] true teaching. +
_assutavā puthujjano... kaṅkhī hoti vicikicchī aniṭṭhaṅgato 
saddhamme_

____
... That unsureness, doubt, and undecidedness about the [significance of the] 
true teaching is an originated phenomenon.

_yā kho pana sā bhikkhave kaṅkhitā vicikicchitā aniṭṭhaṅgatatā 
saddhamme saṅkhāro so._
____

____
... What is the basis, origin, object of genesis and production of that 
originated phenomenon?

_So pana saṅkhāro kinnidāno kiṃsamudayo kiñjātiko kimpabhavoti_
____

• ... When the ignorant Everyman is affected by sense impression born of 
sensation and uninsightfulness into reality, craving arises. +
_avijjāsamphassajena bhikkhave vedayitena phuṭṭhassa assutavato 
puthujjanassa uppannā taṇhā_

[quote, S.3.99]
____
... That originated phenomenon is born from that

_tatojo so saṅkhāro._
____

==== Cause of doubt about the significance of the teaching: improper contemplation

____
I do not see any one thing on account of which unarisen doubt [about the 
significance of the teaching] arises, and arisen doubt [about the significance 
of the teaching] increases and expands, as improper contemplation.

_Nāhaṃ bhikkhave aññaṃ ekadhammampi samanupassāmi yena anuppannā vā 
vicikicchā uppajjati uppannā vā vicikicchā bhiyyobhāvāya vepullāya 
saṃvattati yathayidaṃ bhikkhave ayoniso manasikāro_
____

[quote, A.1.4]
____
For one of improper contemplation, unarisen doubt [about the significance of 
the teaching] arises, and arisen doubt [about the significance of the teaching] 
increases and expands.

_Ayoniso bhikkhave manasikaroto anuppannā ceva vicikicchā uppajjati uppannā 
ca vicikicchā bhiyyobhāvāya vepullāya saṃvattatī ti._
____

____
I do not see any one thing on account of which unarisen doubt [about the 
significance of the teaching] does not arise, and arisen doubt [about the 
significance of the teaching] is abandoned, as proper contemplation.

_Nāhaṃ bhikkhave aññaṃ ekadhammampi samanupassāmi yena anuppannā vā 
vicikicchā nuppajjati uppannā vā vicikicchā pahīyati yathayidaṃ 
bhikkhave yoniso manasikāro_
____

[quote, A.1.4-5]
____
For one of proper contemplation unarisen doubt [about the significance of the 
teaching], and arisen doubt [about the significance of the teaching] is 
abandoned.

_Yoniso bhikkhave manasikaroto anuppannā ceva vicikicchā nuppajjati uppannā 
ca vicikicchā pahīyatī ti._
____

==== Overcoming doubt about the significance of the teaching by meditation

[quote, Ud.60]
____
Any unsureness [about the significance of the teaching] in relation to what is 
experienced by oneself or by others, either here or in the world beyond, is 
completely abandoned by those who meditate, by those who are vigorously applied 
&#8203;[to the practice], by those who live the religious life

_Yā kāci kaṅkhā idha vā huraṃ vā sakavediyā vā paravediyā vā +
Jhāyino tā pajahanti sabbā ātāpino brahmacariyaṃ carantā ti._
____

==== Overcoming doubt about the significance of the teaching by overcoming self-centredness

The _Nissāraṇīya Sutta_ (A.3.291-2) says doubt [about the significance of 
the teaching] persists as long as the notion "I am" has not vanished, which 
happens at arahantship (S.3.131). So, although the scriptures say that to enter 
first jhāna the five hindrances must first be suppressed (M.3.136; D.1.204), 
this can be only relatively true. According to the _Nissāraṇīya Sutta_, the 
hindrance of doubt is not properly suppressed before arahantship. Of course, 
this relative impurity of jhāna is maybe true for all five hindrances.

[quote, D.3.250]
____
If the notion "I am" has vanished, and one does not regard anything as "[in 
reality] what I am,"' it is impossible, out of the question, that the arrow of 
doubt and uncertainty [about the significance of the teaching] would plague 
your mind.

_aṭṭhānametaṃ āvuso anavakāso yaṃ asmī ti vigate ayamahamasmī ti 
asamanupassato atha ca panassa vicikicchākathaṅkathāsallaṃ cittaṃ 
pariyādāya ṭhassatī ti._
____

However, according to the _Cūḷasaccaka Sutta_, doubt about the significance 
of the teaching can be suppressed before arahantship by contemplating the 
voidness of personal qualities [in the five aggregates], as follows:

____
-- On what grounds is a disciple of Master Gotama one who practises his 
training system, who responds to his advice, who has overcome doubt [about the 
significance of the teaching] (_tiṇṇavicikiccho_), one who is free of 
uncertainty [about the significance of the teaching] (_vigatakathaṅkatho_), 
who has gained confidence [in the teaching], and abides no longer dependent on 
others regarding the [understanding of the] Teacher's training system?

_Kittāvatā nu kho bhoto gotamassa sāvako sāsanakaro hoti ovādapatikaro 
tiṇṇavicikiccho vigatakathaṅkatho vesārajjappatto aparappaccayo 
satthusāsane viharatī ti_
____

____
-- A disciple of mine sees each of the five aggregates according to reality 
with perfect penetrative discernment: This is "not [in reality] mine," this is 
"not [in reality] what I am," this is "not my [absolute] Selfhood"

_Idha aggivessana mama sāvako yaṃ kiñci rūpaṃ... viññāṇaṃ 
atītānāgata paccuppannaṃ ajjhattaṃ vā bahiddhā vā oḷārikaṃ vā 
sukhumaṃ vā hīnaṃ vā paṇītaṃ vā yaṃ dūre santike vā sabbaṃ 
viññāṇaṃ n'etaṃ mama n'eso'hamasmi na me so attā ti evametaṃ 
yathābhūtaṃ sammappaññāya passati_
____

____
-- On what grounds is a bhikkhu an arahant with perceptually obscuring states 
destroyed, one who has fulfilled [the religious life], done what had to be 
done, laid down the burden, achieved his objective, destroyed the ties to 
individual existence, and is liberated [from perceptually obscuring states] 
through the complete knowledge [of things according to reality]?

_Kittāvatā pana bho gotama bhikkhu arahaṃ hoti khīṇāsavo vusitavā 
katakaraṇīyo ohitabhāro anuppattasadattho parikkhīṇabhavasaṃyojano 
sammadaññā vimutto ti?_
____

____
-- In this regard, having seen any kind of bodily form... advertence according 
to reality with perfect penetrative discernment as "not [in reality] mine," 
"not [in reality] what I am," "not my [absolute] Selfhood," a bhikkhu is 
liberated [from perceptually obscuring states] through being without grasping.

_Idha aggivessana bhikkhu yaṃ kiñci rūpaṃ atītānāgata paccuppannaṃ 
ajjhattaṃ vā bahiddhā vā oḷārikaṃ vā sukhumaṃ vā hīnaṃ vā 
paṇītaṃ vā yaṃ dūre sannike vā sabbaṃ rūpaṃ n'etaṃ mama 
n'eso'hamasmi na me so attā ti evametaṃ yathābhūtaṃ sammappaññāya 
disvā anupādā vimutto hoti._
____

_Yā kāci vedanā... saññā... saṅkhārā... viññāṇaṃ..._ (M.1.235).

==== Overcoming doubt about the significance of the teaching: seeing with penetrative discernment

____
-- Bhikkhus, is doubt [about the significance of the teaching] abandoned in one 
who perceives according to reality with perfect penetrative discernment: 'This 
is brought about'?

_Bhūtamidan ti bhikkhave yathābhūtaṃ sammappaññāya passato yā 
vicikicchā sā pahīyatī ti_
____

-- Yes, bhante.

____
-- Bhikkhus, is doubt [about the significance of the teaching] abandoned in one 
who perceives according to reality with perfect penetrative discernment: 'It is 
arisen with that as its nourishing condition'?

_Tadāhārasambhavan ti bhikkhave yathābhūtaṃ sammappaññāya passato yā 
vicikicchā sā pahīyatī ti_
____

-- Yes, bhante.

____
-- Bhikkhus, is doubt [about the significance of the teaching] abandoned in one 
who perceives according to reality with perfect penetrative discernment: 'With 
the ending of that nourishing condition, what is brought about is destined to 
cease'?

_Tadāhāranirodhā yaṃ bhūtaṃ taṃ nirodhadhamman ti bhikkhave 
yathābhūtaṃ sammappaññāya passato yā vicikicchā sā pahīyatī ti_
____

-- Yes, bhante (M.1.260).

==== Doubt about the significance of the teaching, the unexplained issues, and dogmatism

____
-- Bhante, what is the cause and reason that doubt [about the significance of 
the teaching] does not arise in the learned noble disciple on account of the 
unexplained issues?

_Ko nu kho bhante hetu ko paccayo yena sutavato ariyasāvakassa vicikicchā 
nūppajjati avyākatavatthusu_
____

____
-- To the learned noble disciple, through the ending of dogmatism, doubt [about 
the significance of the teaching] does not arise on account of the unexplained 
issues

_diṭṭhinirodhā kho bhikkhu sutavato ariyasāvakassa vicikicchā 
nūppajjati avyākatavatthusu._
____

____
Asserting that the Perfect One exists after death: this is acquiescence in 
dogmatism.

_Hoti tathāgato parammaraṇā ti kho bhikkhu diṭṭhigatametaṃ_
____

____
Asserting that the Perfect One does not exist after death: this is acquiescence 
in dogmatism,

_na hoti tathāgato parammaraṇā ti kho bhikkhu diṭṭhigatametaṃ_
____

____
Asserting that the Perfect One both exists and does not exist after death: this 
is acquiescence in dogmatism,

_hoti ca na hoti ca tathāgato parammaraṇā ti kho bhikkhu 
diṭṭhigatametaṃ_
____

____
Asserting that the Perfect One neither exists nor does not exist after death: 
this is acquiescence in dogmatism.

_neva hoti na na hoti tathāgato parammaraṇā ti kho bhikkhu 
diṭṭhigatametaṃ_
____

The ignorant Everyman (_assutavā puthujjano_) does not discern

____
dogmatism

_diṭṭhiṃ nappajānāti_
____

____
the origin of dogmatism

_diṭṭhisamudayaṃ nappajānāti_
____

____
the ending of dogmatism

_diṭṭhinirodhaṃ nappajānāti_
____

____
the practice leading to the ending of dogmatism

_diṭṭhinirodhagāminiṃ paṭipadaṃ nappajānāti_
____

____
For him dogmatism grows

_tassa sā diṭṭhi pavaḍḍhati_
____

____
He is not freed from birth, old age, and death, from grief, lamentation, 
physical pain, psychological pain, and vexation. He is not freed, I declare, 
from suffering.

_So na parimuccati jātiyā jarāmaraṇena sokehi paridevehi dukkhehi 
domanassehi upāyāsehi na parimuccati dukkhasmāti vadāmi._
____

____
The learned noble disciple discerns

_sutavā ca kho bhikkhu ariyasāvako_
____

____
dogmatism

_diṭṭhiṃ pajānāti_
____

____
the origin of dogmatism

_diṭṭhisamudayaṃ pajānāti_
____

____
the ending of dogmatism

_diṭṭhinirodhaṃ pajānāti_
____

____
the practice leading to the ending of dogmatism

_diṭṭhinirodhagāminiṃ paṭipadaṃ pajānāti_
____

____
For him, dogmatism ceases

_tassa sā diṭṭhi nirujjhati_
____

[quote, A.4.69-70]
____
He is freed from birth, old age, and death, from grief, lamentation, physical 
pain, psychological pain, and vexation. He is freed, I declare, from suffering.

_So parimuccati jātiyā jarāmaraṇe sokehi paridevehi dukkhehi domanassehi 
upāyāyehi parimuccati dukkhasmāti vadāmi._
____

==== Doubt regarding the periods of the past, future, and present

The scriptures speak of 'doubt about the periods of the past, future, and 
present,' which makes better sense if taken as 'doubt about the [nature of 
reality in the] periods of the past, future, and present,' thus:

[quote, D.3.217]
____
Three states of unsureness: one is unsure, doubtful, undecided, unsettled, 
about the [nature of reality in the] periods of the past, the future, and the 
present

_Tisso kaṅkhā. Atītaṃ vā addhānaṃ... anāgataṃ vā addhānaṃ... 
etarahi vā paccuppannaṃ addhānaṃ ārabbha kaṅkhati vicikicchati 
nādhimuccati na sampasīdati._
____

This interpretation is illustrated in the following conversation:

____
If, headman, I were to teach you about the origination and vanishing of 
suffering with reference to the past, saying, 'So it was in the past,' 
unsureness about the [nature of reality in the] past might arise in you.

_Ahañce te gāmaṇi atītaṃ addhānaṃ ārabbha dukkhassa samudayañca 
atthaṅgamañca deseyyaṃ: evaṃ ahosi atītamaddhānan ti tatra te siyā 
kaṅkhā siyā vimati._
____

____
... And if I were to teach you about the origination and vanishing of suffering 
with reference to the future, saying, 'So it will be in the future,' unsureness 
about the [nature of reality in the] future might arise in you.

_Ahañce te gāmaṇi anāgatamaddhānaṃ ārabbha dukkhassa samudayañca 
atthaṅgamañca deseyyaṃ. Evaṃ bhavissati anāgatamaddhānan ti tatrāpi 
te siyā kaṅkhā siyā vimati._
____

____
... Instead, headman, while I am sitting right here, and you are sitting right 
there, I will teach you about the origination and vanishing of suffering. 
Listen, pay careful attention, and I will speak.

_Api cāhaṃ gāmaṇi idheva nisinno ettha ca te nisinnassa dukkhassa 
samudayañca atthaṅgamañca desissāmi. Taṃ suṇāhi sādhukaṃ 
manasikarohi bhāsissāmī ti_
____

Having shown the headman that suffering in the present stems from fondness and 
attachment in the present, the Buddha then extends the discussion to the past 
and future:

____
Through this profound truth that is seen, understood, realised in the here and 
now, penetrated, you can deduce about the past and the future thus:

_Iminā tvaṃ gāmaṇi dhammena diṭṭhena viditena akālikena pattena 
pariyogāḷhena atītānāgate nayaṃ nehi_
____

____
... Whatever suffering arose in the past, all of it stemmed from fondness, with 
fondness as its basis; for fondness is the origin of suffering.

_yaṃ kho kiñci atītamaddhānaṃ dukkhaṃ uppajjamānaṃ uppajjati 
sabbantaṃ chandamūlakaṃ chandanidānaṃ chando hi mūlaṃ dukkhassa_
____

[quote, S.4.327]
____
... Whatever suffering will arise in the future, all of it will stem from 
fondness, with fondness as its basis; for fondness is the origin of suffering.

_yaṃ hi kiñci anāgatamaddhānaṃ dukkhaṃ uppajjamānaṃ uppajjissati 
sabbantaṃ chandamūlakaṃ chandanidānaṃ chando hi mūlaṃ dukkhassā ti._
____

==== Doubt [about the perfection of the Blessed One's body]

Brahmans who searched the Buddha's body for the thirty-two marks of a Great 
Man, which, for them, were signs of perfect enlightenment, of a Great Man, were 
always 'doubtful' about the two marks which were not immediately obvious. To 
make any sense, this unspecified doubt is best understood as 'doubt [about the 
perfection of the Blessed One's body],' as these three examples show:

1. All thirty two of the marks that you have heard are the marks of a Great Man 
are to be found on my body. So, brahman, do not be unsure [about the perfection 
of the Blessed One's body].
+
****
_Ye te dvattiṃsāti sutā mahāpurisalakkhaṇā +
****
Sabbe te mama kāyasmiṃ. Mā te kaṅkhāhu brāhmaṇa_ (M.2.143).

2. Then Ambaṭṭha, the young brahman, while pacing back and forth with the 
Blessed One, looked for the thirty-two marks of a Great Man on the Blessed 
One's body, and could see all but two of them.
+
****
_Atha kho ambaṭṭho māṇavo bhagavantaṃ caṅkamantaṃ 
anucaṅkamamāno kāye dvattiṃsamahāpurisalakkhaṇāni samannesi. Addasa 
kho ambaṭṭho māṇavo bhagavato kāye dvattiṃsamahāpurisalakkhaṇāni 
yebhuyyena ṭhapetvā dve_
****

• ... He was unsure, doubtful, undecided, unsettled [about the perfection of 
the Blessed One's body] in respect of two of these marks: the sheathed genitals 
and the large tongue. +
☸ _Dvīsu mahāpurisalakkhaṇesu kaṅkhati vicikicchati nādhimuccati na 
sampasīdati kosohite ca vatthaguyhe pahūtajivhatāya ca_ ;

____
... And so, being aware of this, the Blessed One arranged by psychic power that 
Ambaṭṭha could see his sheathed genitals, and then, sticking out his 
tongue, he licked both ears and both nostrils backwards and forwards, and 
covered the whole width of his forehead with his tongue.

_Atha kho bhagavā tathārūpaṃ iddhābhisaṅkhāraṃ abhisaṅkāsi yathā 
addasa ambaṭṭho māṇavo bhagavato kosohitaṃ vatthaguyhaṃ. Atha kho 
bhagavā jivhaṃ ninnāmetvā ubho pi kaṇṇasotāni anumasi parimasi. Ubho 
pi nāsikāsotāni anumasi parimasi. Kevalampi naḷāṭamaṇḍalaṃ 
jivhāya chādesi._
____

[quote, D.1.105-6]
____
... Then Ambaṭṭha thought: 'The ascetic Gotama is possessed of all 
thirty-two marks of a Great Man, with all present and none missing.

_Atha kho ambaṭṭhassa māṇavassa etadahosi samannāgato kho samaṇo 
gotamo dvattiṃsamahāpurisalakkhaṇehi paripuṇṇehi no aparipuṇṇehī 
ti._
____

==== Ajita's quest: doubt [about the perfection of the Perfect One's transcendent insight]

The brahman Ajita was sent by his teacher to examine the Buddha as to whether 
he was perfectly enlightened or not, and to put him through a series of tests:

- 'If he is the Enlightened One, one of unobstructed vision, he will answer in 
speech the questions you ask in your mind.' (Sn.v.1005).

In this quest, Ajita used the word _kaṅkhā_ and _kaṅkhati_ which should be 
parenthesised as follows:

[quote, Sn.v.1021]
____
Give a detailed account of Bāvari's marks, best of men, the destroyer of 
unsureness. Let there be no unsureness in us [about the perfection of the 
Perfect One's transcendent insight].

_Lakkhaṇānaṃ pavicayaṃ, bāvarissa naruttama; +
Kaṅkhacchida pakāsehi, mā no kaṅkhāyitaṃ ahu._
____

==== Sakka's Questions: doubt about the way of spiritual fulfilment, and of unfulfilment

The Buddha removed the arrow of doubt and uncertainty long lurking in Sakka, 
Lord of the Devas, through answering his four main questions plus six 
subsidiary questions (D.2.283). But doubt and uncertainty about what? The 
answer is found at the end of the conversation in the _Sakkapañha Sutta_, when 
Sakka explained the history of his inquiry:

[quote, D.2.287]
____
Thinking that ascetics living secludedly were enlightened, and that I should go 
and follow them, I had asked them, 'What is the way of spiritual fulfilment? 
What is the way of spiritual unfulfilment?' But when asked, they were unable to 
explain the relevant path and practices.

_Yassu maññāmi samaṇe pavivittavihārino; +
Sambuddhā iti maññāno gacchāmi te upāsituṃ. +
Kathaṃ ārādhanā hoti kathaṃ hoti virādhanā; +
Iti puṭṭhā na sampāyanti magge paṭipadāsu ca._
____

This shows that the doubt and uncertainty long lurking in Sakka concerned the 
way of spiritual fulfilment (_ārādhanā_), and of unfulfilment 
(_virādhanā_). This qualification can therefore be parenthesised in 
translation. For example, after the Buddha answered each question, Sakka 
exclaimed:

____
'So it is, Blessed One, so it is, Sublime One. Having heard the Blessed One's 
answer to my question, unsureness [about the way of spiritual fulfilment, and 
of unfulfilment] is overcome in me; uncertainty [about the way of spiritual 
fulfilment, and of unfulfilment] has disappeared!'

_Evametaṃ bhagavā evametaṃ sugata tiṇṇā me'ttha kaṅkhā vigatā 
kathaṅkathā bhagavato pañhaveyyākaraṇaṃ sutvā ti._
____

Likewise, Sakka's exclamation at the end of the conversation can be rendered:

[quote, D.2.287]
____
Long I wandered, objective unfulfilled, doubtful and uncertain [about the way 
of spiritual fulfilment, and of unfulfilment], in quest of the Perfect One.

_Apariyositasaṅkappo vicikiccho kathaṅkathī. +
Vicariṃ dīghamaddhānaṃ anvesanto tathāgataṃ._
____

Sakka's four main questions are all consistent with an inquiry about the way of 
spiritual fulfilment, and of unfulfilment. They are as follows:

1. Because of what bond is it, that devas, humans, asuras, magical serpents, 
heavenly musicians and whatever other kinds there may be, although they wish to 
abide free of unfriendliness, violence, enmity, hostility, and uncordiality, 
why do they in fact abide with all these things?
+
****
_kiṃsaṃyojanā nu kho mārisa devā manussā asurā nāgā gandhabbā ye 
caññe santi puthukāyā te averā adaṇḍā asapattā avyāpajjhā viharemu 
averino ti iti ce nesaṃ hoti. Atha ca pana saverā sadaṇḍā sasapattā 
savyāpajjā viharanti saverino ti_
****

2. How does he conduct himself, the bhikkhu who practises within the 
constraints of the rules of discipline?
+
****
_kathaṃ paṭipanno pana mārisa bhikkhu pātimokkhasaṃvarāya paṭipanno 
hotī ti_
****

3. How does he conduct himself, the bhikkhu who applies himself to the 
restraint of the sense faculties [from attraction and repulsion, through 
mindfulness]?
+
****
_kathaṃ paṭipanno pana mārisa bhikkhu indriyasaṃvarāya paṭipanno 
hotī ti_
****

4. Do all ascetics and Brahmanists have the same doctrine, the same standard of 
discipline, the same aspiration, and pursue the same goal?
+
****
_sabbeva nu kho mārisa samaṇabrāhmaṇā ekantavādā ekantasīlā 
ekantachandā ekantaajjhosānā ti_ (D.2.276-83).
****

==== Māra's seventh army: doubt [about the significance of abandoning spiritually unwholesome factors and undertaking spiritually wholesome factors]

Before his enlightenment, the Buddha was tempted by Māra to abandon his 
struggle. It was here that the Buddha said that Māra's seventh army is doubt 
(_Sattamī vicikicchā te_, Sn.v.437). Usually we would call _vicikicchā_ 
'doubt [about the significance of the teaching].' See IGPT sv _Vicikicchā_. 
But here, as yet, there is no Buddha or teaching. We therefore take the object 
of _vicikicchā_ to be _kusalesu dhammesu_ from this quote:

[quote, M.3.136; D.1.204]
____
Abandoning doubt [about the significance of the teaching], he abides having 
overcome doubt [about the significance of the teaching], with no uncertainty 
about [the significance of abandoning spiritually unwholesome factors and 
undertaking] spiritually wholesome factors.

_Vicikicchaṃ pahāya tiṇṇavicikiccho viharati akathaṅkathī kusalesu 
dhammesu._
____

Accordingly, Māra's seventh army is 'doubt [about the significance of 
abandoning spiritually unwholesome factors and undertaking spiritually 
wholesome factors]'. This also accords with the nature of the Buddha's search 
at that time:

[quote, M.1.163]
____
Having gone forth [into the ascetic life] in search of what is spiritually 
wholesome, seeking the supreme state of sublime peace, I approached Āḷāra 
Kālāma.'

_So evaṃ pabbajito samāno kiṃkusalagavesī anuttaraṃ santivarapadaṃ 
pariyesamāno yena āḷāro kālāmo tenupasaṅkamiṃ._
____

==== Uncertainty about [the significance of abandoning spiritually unwholesome factors and undertaking] spiritually wholesome factors

We used this quote in the section above:

[quote, M.3.136; D.1.204]
____
Abandoning doubt [about the significance of the teaching], he abides having 
overcome doubt [about the significance of the teaching], with no uncertainty 
about [the significance of abandoning spiritually unwholesome factors and 
undertaking] spiritually wholesome factors. He cleanses his mind of doubt 
&#8203;[about the significance of the teaching].

_Vicikicchaṃ pahāya tiṇṇavicikiccho viharati akathaṅkathī kusalesu 
dhammesu. Vicikicchāya cittaṃ parisodheti._
____

We make two points:

1. Applying the same parentheses, i.e. '[significance of],' would only be 
justified if 'the teaching' concerns 'the abandoning of spiritually unwholesome 
factors and undertaking of spiritually wholesome factors.' Which it does, says 
this quote:
+
[quote, Dh.v.183]
____
The refraining from everything unvirtuous; the undertaking of what is 
spiritually wholesome; the purification of one's mind: this is the training 
system of the Buddhas.

_Sabbapāpassa akaraṇaṃ kusalassa upasampadā +
Sacittapariyodapanaṃ etaṃ buddhānaṃ sāsanaṃ._
____

2. According to our parenthesis, spiritually unwholesome factors are 
'abandoned' and spiritually wholesome factors are 'undertaken'. The parentheses 
come from these two quotes:
+
[quote, S.3.8]
____
The Blessed One praises the abandonment of spiritually unwholesome factors.

_bhagavā akusalānaṃ dhammānaṃ pahānaṃ vaṇṇeti._
____
+
[quote, S.3.9]
____
The Blessed One praises the undertaking of spiritually wholesome factors.

_bhagavā kusalānaṃ dhammānaṃ upasampadaṃ vaṇṇetī ti._
____

=== Illustrations

.Illustration
====
vicikicchā

doubt [about the significance of the teaching]
====

The man ignorant of the path would ask the knowledgeable man a question about 
the path, and the latter would say: 'Come, good man, this is the path. Go along 
it a little way and you will see a fork in the road. Avoid the left-hand branch 
and take the right-hand branch...

____
'The man ignorant of the path' represents the common man.

_puriso amaggakusalo ti kho tissa puthujjanassetaṃ adhivacanaṃ_
____

____
'The man knowledgeable about the path' represents the Perfect One, the Arahant, 
the Perfectly Enlightened One.

_Puriso maggakusalo ti kho tissa tathāgatassetaṃ adhivacanaṃ arahato 
sammāsambuddhassa_
____

____
'The forked road' represents doubt [about the significance of the teaching].

_Dvidhāpatho ti kho tissa vicikicchāyetaṃ adhivacanaṃ_
____

____
'The left-hand branch' represents the wrong eightfold path; that is, wrong view 
&#8203;[of reality]... wrong inward collectedness.

_Vāmomaggo ti kho tissa aṭṭhaṅgikassetaṃ micchāmaggassa adhivacanaṃ 
seyyathīdaṃ micchādiṭṭhiyā... micchāsamādhissa._
____

[quote, S.3.108-9]
____
'The right-hand branch' represents the noble eightfold path; that is, right 
perception [of reality]... right inward collectedness.

_Dakkhiṇo maggo ti kho tissa ariyassetaṃ aṭṭhaṅgikassa maggassa 
adhivacanaṃ seyyathīdaṃ sammādiṭṭhiyā... sammāsamādhissa._
____

.Illustration
====
vicikicchā

doubt [about the significance of the teaching]
====

[quote, S.5.97]
____
The hindrance of doubt [about the significance of the teaching] produces 
spiritual blindness, uninsightfulness, ignorance [of things according to 
reality], is destructive of penetrative discernment, vexatious, and not 
conducive to the Untroubled.

_Vicikicchānīvaraṇaṃ bhikkhave andhakaraṇaṃ acakkhukaraṇaṃ 
aññāṇakaraṇaṃ paññānirodhiyaṃ vighātapakkhiyaṃ 
anibbānasaṃvattanikaṃ._
____

.Illustration
====
vicikicchā

doubt [about the significance of the teaching]
====

[quote, S.5.123-4]
____
Again, brahman, when one dwells with a mind absorbed in and overcome by doubt 
&#8203;[about the significance of the teaching], and one does not discern according to 
reality the escape from the arisen doubt [about the significance of the 
teaching], on that occasion one neither knows nor sees [according to reality] 
one's own good, nor the good of others, nor the good of both.

_Puna ca paraṃ brāhmaṇa yasmiṃ samaye vicikicchāpariyuṭṭhitena 
cetasā viharati vicikicchāparetena. Uppannassa ca vicikicchāya 
nissaraṇaṃ yathābhūtaṃ na jānāti. Attatthampi tasmiṃ samaye 
yathābhūtaṃ na jānāti na passati. Paratthampi tasmiṃ samaye 
yathābhūtaṃ na jānāti na passati. Ubhayatthampi tasmiṃ samaye 
yathābhūtaṃ na jānāti na passati._
____

.Illustration
====
vicikicchā

doubt [about the significance of the teaching]
====

This quote shows that doubt [about the significance of the teaching] comes from 
clinging when one is assailed by entrenched perception and conception:

____
For whatever the reason that entrenched perception and conception assail a man

_yatonidānaṃ purisaṃ papañcasaññāsaṅkhā samudācaranti_
____

____
... if there is found nothing there to be delighted in, welcomed, or clung to

_ettha ce natthi abhinanditabbaṃ abhivaditabbaṃ ajjhositabbaṃ_
____

[quote, M.1.109]
____
_..._ this is the end of the proclivity to doubt [about the significance of the 
teaching]

_esevanto vicikicchānusayānaṃ._
____

.Illustration
====
kaṅkhī vecikicchī

unsure and doubtful [about the perfection of the Perfect One's transcendent 
insight]
====

&#8203;[Sabhiya:]

[quote, Sn.v.510]
____
'Unsure and doubtful [about the perfection of the Perfect One's transcendent 
insight], I have come longing to ask [these] questions. Put an end to them for 
me. Being asked, answer my questions truthfully one by one.'

_Kaṅkhī vecikicchī āgamaṃ pañhe pucchituṃ abhikaṅkhamāno +
Tes'antakaro bhavāhi pañhe me puṭṭho +
Anupubbaṃ anudhammaṃ vyākarohi me._
____

COMMENT

_Kaṅkhī vecikicchī_: 'Unsure and doubtful [about the perfection of the 
Perfect One's transcendent insight].' The object of Sabhiya's unsureness and 
doubt is unspecified, but there are two reasons we can say that his doubt is 
not 'doubt about the questions' (an expression which anyway is meaningless), 
but about the perfection of the Perfect One's transcendent insight.

1. The original purpose of the questions was not to discover their answers, but 
to find out under whom he should live the religious life.

2. It is indicated by the second sentence in this quote, beginning with 
'Certainly' (_addhā_):

[quote, Sn.v.541]
____
The unsureness I formerly had [about the perfection of the Perfect One's 
transcendent insight], that you have dealt with, O Seer. Certainly you are a 
perfectly enlightened sage. There are no hindrances in you.

_Yā me kaṅkhā pure āsi taṃ me vyākāsi cakkhumā +
Addhā munīsi sambuddho natthi nīvaraṇā tava._
____

.Illustration
====
kaṅkho

unsureness [about the significance of the teaching]
====

[quote, Sn.v.1059]
____
Having crossed to the Far Shore he is free of remissness in practising the 
teaching, and free of unsureness [about the significance of the teaching].

_tiṇṇo ca pāraṃ akhilo akaṅkho._
____

.Illustration
====
kaṅkhī

unsure about the [significance of the] true teaching; vicikicchī,doubtful 
about the [significance of the] true teaching
====

____
Again, some person here is unsure, doubtful, undecided about the [significance 
of the] true teaching.

_Puna ca paraṃ brāhmaṇa idhekacco kaṅkhī hoti vicikicchī 
aniṭṭhaṅgato saddhamme._
____

____
When he incurs a severe disease or illness, he thinks: 'Alas, I am unsure, 
doubtful, undecided about the [significance of the] true teaching.

_Tamenaññataro gāḷho rogātaṅko phusati. Tassaññatarena gāḷhena 
rogātaṅkena phuṭṭhassa evaṃ hoti: kaṅkhī vatamhi vicikicchī 
aniṭṭhaṅgato saddhammo ti._
____

[quote, A.2.174]
____
He grieves, suffers, and laments, weeps beating his chest, and falls into 
bewilderment. This, too, is one subject to death who is frightened and 
terrified of death.

_So socati kilamati paridevati urattāḷiṃ kandati sammohaṃ āpajjati. 
Ayampi kho brāhmaṇa maraṇadhammo samāno bhāyati santāsaṃ āpajjati 
maraṇassa._
____

.Illustration
====
kaṅkhā

unsureness about the [perfection of the] Perfect One's [transcendent insight]; 
vimati, uncertainty about the [perfection of the] Perfect One's [transcendent 
insight]
====

In the _Sampasādaniya Sutta_ Venerable Sāriputta recounts, in sixteen ways, 
the Buddha's unsurpassed ability to explain the teaching (_etadānuttariyaṃ 
yathā bhagavā dhammaṃ deseti_). Then the Buddha said:

[quote, D.3.116]
____
And therefore you, Sāriputta, should frequently repeat this systematic 
exposition of the teaching to the bhikkhus and bhikkhunīs, and to male and 
female lay-followers. And, by listening to such talk, any worthless persons' 
unsureness or uncertainty about the [perfection of the] Perfect One's 
&#8203;[transcendent insight] will be abandoned.

_tasmātiha tvaṃ sāriputta imaṃ dhammapariyāyaṃ abhikkhaṇaṃ 
bhāseyyāsi bhikkhunaṃ bhikkhunīnaṃ upāsakānaṃ upāsikānaṃ. 
Yesampi hi sāriputta moghapurisānaṃ bhavissati tathāgate kaṅkhā vā 
vimati vā tesamimaṃ dhammapariyāyaṃ sutvā yā tathāgate kaṅkhā vā 
vimati vā sā pahīyissatī ti._
____

.Illustration
====
kaṅkhā

unsureness; vimati, uncertainty [about what I have said]
====

[quote, M.3.271]
____
This will be a discourse by way of questions. Those who understand, should say 
'We understand.' Those who do not understand, should say 'We do not 
understand.' Anyone who is unsure or uncertain [about what I have said] should 
ask me, 'How is this, bhante? What is the meaning of this?.'

_paṭipucchakathā kho bhaginiyo bhavissati. Tattha ājānantīhi 
ājānāmātissa vacanīyaṃ na ājānantīhi na ājānāmātissa vacaniyaṃ. 
Yassā vā panassa kaṅkhā vā vimati vā ahameva tattha paṭipucchitabbo: 
idaṃ bhante kathaṃ imassa kvattho ti._
____

.Illustration
====
kaṅkhā

unsureness; vimati, uncertainty
====

[quote, M.3.276]
____
On an Observance Day, a fourteenth, there is neither unsureness nor uncertainty 
among the general public as to whether the moon is not full or full, for the 
moon is then not full.

_tadahuposathe cātuddase na hoti bahuno janassa kaṅkhā vā vimati vā ūno 
nu kho cando puṇṇo nu kho cando ti atha kho ūno cando tveva hoti._
____

.Illustration
====
kaṅkhā

unsureness; vimati, uncertainty
====

[quote, A.2.185]
____
Suppose a man were knowledgeable about the sound of a conch. While walking 
along the highway he might hear the sound of a conch. He would not be at all 
unsure or uncertain about [the source of the sound]; rather, he would conclude: 
'That is indeed the sound of a conch.'

_Seyyathā pi bhikkhave puriso kusalo bherisaddassa. So addhānamagga 
paṭipanno bherisaddaṃ suṇeyya tassa na heva kho assa kaṅkhā vā vimati 
vā bherisaddo nu kho na nu kho bherisaddoti. Atha kho bherisaddotveva 
niṭṭhaṃ gaccheyya._
____

.Illustration
====
kaṅkhā

unsureness; vimati, uncertainty
====

[quote, A.3.296]
____
I am one of the Blessed One's white-robed female lay disciples who maintains 
perfect virtue. If anyone has any unsureness or uncertainty about [the truth 
of] this, the Blessed One, the Arahant, the Perfectly Enlightened One is 
dwelling among the Bhaggas at Sumsumaragira, in the deer park at Bhesakala 
Grove. They can go and ask him.

_Yāvatā kho gahapati tassa bhagavato sāvikā gihī odātavasanā sīlesu 
paripūrakāriṇiyo ahaṃ tāsaṃ aññatarā. Yassa kho panassa kaṅkhā 
vā vimati vā ayaṃ so bhagavā arahaṃ sammāsambuddho bhaggesu viharati 
suṃsumāragire bhesakalāvane migadāye taṃ bhagavantaṃ upasaṅkamitvā 
pucchatu._
____

.Illustration
====
kaṅkhā

unsureness [about the significance of the teaching]
====

____
Spiritual purification through [the purification of] one's perception [of 
reality] is for the sake of spiritual purification through overcoming one's 
unsureness [about the significance of the teaching].

_Diṭṭhivisuddhi yāvadeva kaṅkhāvitaraṇavisuddhatthā._
____

[quote, M.1.149-150]
____
Spiritual purification through overcoming one's unsureness [about the 
significance of the teaching] is for the sake of spiritual purification through 
knowledge and vision of what is the Path and what is not the Path.

_Kaṅkhāvitaraṇavisuddhi yāvadeva maggāmaggañāṇadassanavisuddhatthā._
____

.Illustration
====
kaṅkhā

unsureness [about the significance of the teaching]
====

[quote, Ud.1]
____
When profound truths become manifest to the vigorous, meditative Brahman, then 
all his unsureness [about the significance of the teaching] disappears, for he 
discerns the conditioned nature of reality.

_Yadā have pātubhavanti dhammā ātāpino jhāyato brāhmaṇassa +
Athassa kaṅkhā vapayanti sabbā yato pajānāti sahetudhamman ti._
____

