== Vihaññati

=== Renderings

- _vihaññati_: inconvenienced

- _vihaññati_: troubled

- _vihaññati_: troubled by

- _vihaññati_: suffer hardship

=== Illustrations

.Illustration
====
vihaññāmi

inconvenienced
====

[quote, D.3.89]
____
Then it occurred to one of those beings who was inclined to laziness: 'Well 
now, why should I be inconvenienced by having to gather rice in the evening for 
supper and in the morning for breakfast? Why shouldn't I gather it all at once 
for both meals?

_Atha kho vāseṭṭhā aññatarassa sattassa alasajātikassa etadahosi ambho 
kimevāhaṃ vihaññāmi sāliṃ āharanto sāyaṃ sāyamāsāya pāto 
pātarāsāya? Yannūnāhaṃ sāliṃ āhareyyaṃ sakideva 
sāyapātarāsāyā ti._
____

.Illustration
====
vihaññanti

inconvenienced
====

[quote, Vin.2.117]
____
They were inconvenienced as they were ascending. 'I allow, bhikkhus, three 
&#8203;[kinds of] staircases.'

_Ārohantā vihaññanti. Anujānāmi bhikkhave tayo sopāṇe._
____

.Illustration
====
vihaññamānaṃ

troubled
====

[quote, Ud.14]
____
See how they are troubled, those who are attached to the perception of 
existence.

_Sakiñcanaṃ passa vihaññamānaṃ._
____

.Illustration
====
avihaññamāno

without being troubled by
====

[quote, Ud.21]
____
Mindful and fully conscious, enduring without being troubled [by it], sense 
impression that was unpleasant, acute, sharp, and severe, arisen as a karmic 
consequence of previous deeds'

_purāṇakammavipākajaṃ dukkhaṃ tibbaṃ kharaṃ kaṭukaṃ vedanaṃ 
adhivāsento sato sampajāno avihaññamāno._
____

.Illustration
====
vihaññamāne

troubled by
====

[quote, Sn.v.1121]
____
'Seeing people being troubled by [attachment to] bodily forms -- for people 
negligently applied [to the practice] are troubled by [attachment to] bodily 
forms -- therefore you, Pingiya, being diligently applied [to the practice], 
abandon bodily form for the sake of avoiding renewed states of individual 
existence.'

_Disvāna rūpesu vihaññamāne ruppanti rūpesu janā pamattā +
Tasmā tuvaṃ piṅgiya appamatto jahassu rūpaṃ apunabbhavāya._
____

COMMENT

_Rūpesu vihaññamāne_: 'troubled by [attachment to] bodily forms.' The 
locative shows the cause, reason, or motive of an action (PGPL, para601). The 
parenthesis 'attachment' is justified by the advice to 'abandon' (_jahassu_) in 
pāda d. The principle is repeated with _upādāya_ in verse 169:

[quote, Sn.v.169]
____
Because of grasping the six [sense objects] the world [of beings] suffers 
hardship.

_upādāya chassu loko vihaññati._
____

COMMENT

Troubled... troubled: _vihaññati_ and _ruppati_ are synonyms.

.Illustration
====
vihaññittho

troubled by
====

[quote, Th.v.385]
____
You abide out in the open air. These winter nights are cold. Do not be 
troubled, overcome by the cold. Snuggle into your dwelling with fastened bolts.

_Abbhokāse viharasi sītā hemantikā imā rattiyo +
Mā sītena pareto vihaññittho pavisa tvaṃ vihāraṃ phassit'aggaḷaṃ._
____

[quote, Th.v.386]
____
I will fasten onto the four unlimited states, and I will abide well-pleased 
with them. I will not be troubled by the cold, dwelling in the Imperturbable.

_Phassissaṃ catasso appamaññāyo tāhi ca sukhito viharissaṃ +
Nāhaṃ sītena vihaññissaṃ aniñjito viharanto ti._
____

.Illustration
====
vihaññati

troubled
====

[quote, Dh.v.15]
____
In this world he grieves, having passed on he grieves. The evildoer grieves in 
both places. He grieves, he is troubled, on considering his own immoral 
activities.

_Idha socati pecca socati pāpakārī ubhayattha socati +
So socati so vihaññati disvā kammakiliṭṭhamattano._
____

.Illustration
====
avihaññamāno

without being troubled by
====

• He politely eats whatever food they give him, whether poor or excellent, 
without being troubled [by it]. +
☸ _yaṃ kho panassa bhojanaṃ denti lūkhaṃ vā paṇītaṃ vā taṃ 
sakkaccaṃyeva paribhuñjati avihaññamāno_ (A.4.189)..

.Illustration
====
vihaññati

troubled by
====

[quote, D.1.119]
____
This brahman Soṇadaṇḍa is troubled by his own mind.

_vihaññati kho ayaṃ soṇadaṇḍo brāhmaṇo sakena cittena._
____

.Illustration
====
vihaññati

troubled by
====

[quote, Dh.v.62]
____
'I have sons. I have wealth': [thinking thus] the fool is troubled [by craving].

_Puttā matthi dhanammatthi iti bālo vihaññati._
____

COMMENT

Commentary: _puttataṇhāya ceva dhanataṇhāya ca haññati vihaññati 
dukkhayati puttā me nassiṃsū ti vihaññati nassantī ti vihaññati 
nassissantī ti vihaññati_.

.Illustration
====
vihaññati

suffers hardship
====

[quote, Sn.v.169]
____
Because of grasping the six [sense objects] the world [of beings] suffers 
hardship.

_upādāya chassu loko vihaññati._
____

.Illustration
====
vihaññanti

suffer hardship
====

[quote, Th.v.1058]
____
Whereas some suffer hardship when climbing a mountain, there climbs Kassapa, an 
inheritor of the Buddha's [teaching], fully conscious and mindful, assisted by 
his psychic power.

_Yattha eke vihaññanti āruhantā siluccayaṃ +
Tattha buddhassa dāyādo sampajāno patissato +
Iddhibalenupatthaddho kassapo abhirūhati._
____

.Illustration
====
vihaññasi

suffer hardship
====

[quote, Thī.v.387]
____
Should you ravish one who knows [the nature of reality], you will [thereafter] 
suffer hardship.

_Tvaṃ tādisikaṃ palobhaya jānantiṃ so imaṃ vihaññasi._
____

.Illustration
====
vihaññasi

suffer hardship
====

[quote, Thī.v.508]
____
Do not later suffer hardship like a carp swallowing a fishhook.

_Mā puthulomova baḷisaṃ gilitvā pacchā vihaññasi._
____

.Illustration
====
vihaññati

suffers hardship
====

[quote, A.1.129]
____
Having gone from here to hell, the one-eyed person suffers hardship.

_Ito so nirayaṃ gantvā ekacakkhu vihaññati._
____

.Illustration
====
vihaññati

suffers hardship
====

[quote, A.3.353]
____
A poor person who becomes indebted suffers hardship while enjoying himself.

_Daḷiddo iṇamādāya bhuñjamāno vihaññati._
____

.Illustration
====
vihaññanti

suffer hardship
====

[quote, Ud.18]
____
Affiliates suffer hardship.

_Sādhāraṇe vihaññanti._
____

