== Vihesā; Vihiṃsā

=== Renderings

==== Vihesā, Viheseti

- _viheseti_: to harm

- _viheseti_: to injure

- _viheseti_: to trouble

- _viheseti_: to harass

- _vihesā_: doing harm

- _vihesā_: injury

- _vihesā_: vexation

- _vihesā_: maliciousness

- _avihesā_: compassion

==== Vihiṃsati, Vihiṃsā

- _vihiṃsati_: to harm

- _vihiṃsati_: to injure

- _vihiṃsati_: to trouble

- _vihiṃsā_: troublesomeness

- _vihiṃsā_: maliciousness

- _vihiṃsā_: malicious

- _avihiṃsā_: compassion

=== Illustrations: vihesā

.Illustration
====
vihesā

doing harm
====

[quote, Sn.v.275]
____
One who delights in doing harm, a beast

_vihesābhirato mago._
____

.Illustration
====
vihesa

injury
====

[quote, Sn.v.247]
____
Those in this world who are unrestrained in [the harming of] living beings, 
stealing their possessions, intent on injury, unvirtuous, ferocious, harsh, 
disrespectful: what is rotten is this, not the eating of meat.

_Ye idha pāṇesu asaṃyatā janā paresamādāya vihesamuyyutā +
Dussīlaluddā pharusā anādarā esāmagandho na hi maṃsabhojanaṃ._
____

.Illustration
====
vihesaṃ

injury
====

[quote, Sn.v.276-7]
____
Injuring one who has spiritually developed himself

_Vihesaṃ bhāvitattānaṃ._
____

.Illustration
====
vihesesi

trouble
====

[quote, M.2.146]
____
He did not trouble me through [failure to quickly understand] the teaching.

_na ca maṃ dhammādhikaraṇaṃ vihesesi._
____

Comment:

See Glossary sv _Na ca maṃ dhammādhikaraṇaṃ vihesesi_

.Illustration
====
viheseti

trouble
====

[quote, A.4.194]
____
He troubles the assembly of bhikkhus by keeping silent.

_tuṇhibhāvena saṅghaṃ viheseti._
____

.Illustration
====
vihesā

troublesome
====

[quote, D.2.36]
____
If I were to explain the teaching to others and they did not understand, it 
would be wearisome and troublesome for me.

_ahañce ca kho pana dhammaṃ deseyyaṃ pare ca me na ājāneyyuṃ so 
mamassa kilamatho sā mamassa vihesā ti._
____

.Illustration
====
vihesā

troublesome
====

[quote, D.2.93]
____
If you come and ask the Perfect One the fate of everyone who dies, it would be 
troublesome for him.

_tasmiñce kālakate tathāgataṃ upasaṅkamitvā etamatthaṃ pucchissatha 
vihesā cesā ānanda tathāgatassa._
____

.Illustration
====
vihesā

vexation
====

[quote, M.1.498]
____
When there are disputes there are quarrels; with quarrels, distress; with 
distress, vexation.

_Iti viggahe sati vivādo vivāde sati vighāto vighāte sati vihesā._
____

.Illustration
====
vihesā

vexation
====

[quote, Th.v.794-5]
____
Many sense impressions arising from the visible object blossom [within 
oneself], greed and vexation as well, by which one's mind becomes disturbed.

_Tassa vaḍḍhanti vedanā anekā rūpasambhavā +
Abhijjhā ca vihesā ca cittamassūpahaññati._
____

.Illustration
====
vihesā

vexation
====

• Why recite these lesser and minor training rules? They only lead to 
anxiety, vexation, and perplexity. +
_kiṃ panimehi khuddisante vā sikkhāpadehi uddiṭṭhehi yāvadve 
kukkuccāya vihesāya vilekhāya saṃvattanti_ (Vin.4.143).

.Illustration
====
viheseyyam

harass
====

[quote, A.1.78]
____
If an elder bhikkhu corrects me, he would do so not tenderly concerned for my 
welfare. I should then tell him "No!" and harass him.

_thero cepi maṃ vadeyya ahitānukampī maṃ vadeyya no hitānukampī noti 
naṃ vadeyyaṃ viheseyyampi._
____

.Illustration
====
vihesiyamānaṃ

harass
====

• Ānanda, would you just simply passively observe an elder bhikkhu while he 
is being harassed? Truly, Ānanda, there is certainly no compassion in allowing 
an elder bhikkhu to be harassed. +
☸ atthi _nāma ānanda theraṃ bhikkhuṃ vihesiyamānaṃ 
ajjhupekkhissatha. Na hi nāma ānanda kāruññampi bhavissati theramhi 
bhikkhumhi vihesiyamānamhī ti_ (A.3.194).

.Illustration
====
vihesaṃ

maliciousness
====

• Furthermore, when a bhikkhu is contemplating maliciousness his mind does 
not become energised, serene, settled, and intent upon it. +
_Puna ca paraṃ āvuso bhikkhuno vihesaṃ manasikaroto vihesāya cittaṃ na 
pakkhandati nappasīdati na santiṭṭhati na vimuccati (read as adhimuccati. 
See IGPT sv Adhimuccati)._

• But when contemplating compassion his mind becomes energised, serene, 
settled, and intent upon it. +
_Avihesaṃ kho panassa manasikaroto avihesāya cittaṃ pakkhandati pasīdati 
santiṭṭhati vimuccati (read as adhimuccati)_ (D.3.240).

.Illustration
====
vihesā

maliciousness
====

[quote, D.3.249]
____
It is impossible, friend, out of the question, that one might develop and 
cultivate the liberation [from perceptually obscuring states] through 
&#8203;[unlimited, all-encompassing] compassion, make it one's vehicle and practice, 
carry it out, pursue it, and properly undertake it, yet still maliciousness 
would plague your mind. There is no such possibility.

_Aṭṭhānametaṃ āvuso anavakāso yaṃ karuṇāya cetovimuttiyā 
bhāvitāya bahulīkatāya yānīkatāya vatthukatāya anuṭṭhitāya 
paricitāya susamāraddhāya atha ca panassa vihesā cittaṃ pariyādāya 
ṭhassatī'ti netaṃ ṭhānaṃ vijjati. Nissaraṇaṃ hetaṃ āvuso 
vihesāya yadidaṃ karuṇā cetovimutti._
____

.Illustration
====
avihesā 

compassion
====

• This worthless man must have absolutely no sympathy, tender concern, or 
compassion for living beings. +
☸ _Na hi nāma bhikkhave tassa moghapurisassa pāṇesu anuddayā anukampā 
avihesā bhavissati_. (Vin.3.42).

=== Illustrations: vihiṃsa

.Illustration
====
vihiṃseyya

harm
====

[quote, Th.v.1227]
____
One should speak only that speech which is neither a torment to oneself, nor 
harmful to others. That speech [i.e. speech spoken gently, and with a mind of 
unlimited, all-encompassing goodwill] is indeed well-spoken.

_Tameva vācaṃ bhāseyya yāyattānaṃ na tāpaye +
Pare ca na vihiṃseyya sā ve vācā subhāsitā._
____

.Illustration
====
avihiṃsāya

unharmed
====

[quote, D.3.206]
____
The Atanatiya protective verses are beneficial, and through them bhikkhus, 
bhikkhunīs, and lay-followers may dwell guarded, protected, unharmed and at 
ease.

_Atthasaṃhitā bhikkhave āṭānāṭiyā rakkhā bhikkhūnaṃ 
bhikkhuṇīnaṃ upāsakānaṃ upāsikānaṃ guttiyā rakkhāya 
avihiṃsāya phāsuvihārāyā ti._
____

.Illustration
====
vihiṃsati

injures
====

[quote, Ud.12]
____
A person who injures with a stick beings who [likewise] desire happiness

_Sukhakāmāni bhūtāni yo daṇḍena vihiṃsati._
____

.Illustration
====
vihiṃsa

troublesomeness
====

[quote, M.3.134]
____
Properly reflecting, you should use almsfood not for fun, not for exuberance, 
not for the sake of comeliness and good looks, but just for the maintenance and 
nourishment of this [wretched human] body for restraining its troublesomeness, 
for supporting the religious life.

_Paṭisaṅkhā yoniso āhāraṃ āhāreyyāsi neva davāya na madāya na 
maṇḍanāya na vibhūsanāya yāvadeva imassa kāyassa ṭhitiyā yāpanāya 
vihiṃsūparatiyā brahmacariyānuggahāya._
____

.Illustration
====
vihiṃsa

troublesomeness
====

[quote, Vin.1.7]
____
Aware of the troublesomeness of it, Brahmā, I did not preach the excellent and 
sublime teaching amongst men.

_Vihiṃsasaññī paguṇaṃ na bhāsayiṃ dhammaṃ paṇītaṃ manujesu 
brahme ti._
____

.Illustration
====
vihiṃsati

troubles
====

[quote, It.86]
____
One who troubles the Perfect One with abuse, a peaceful person with a peaceful 
mind, will see that abuse of him is ineffective.

_Evameva tathāgataṃ yo vādena vihiṃsati +
Samaggataṃ santacittaṃ vādo tamhi na rūhati._
____

.Illustration
====
vihiṃsā

maliciousness, malicious
====

[quote, S.2.151]
____
Because of the phenomenon of maliciousness, malicious mental imagery arises, 
malicious thought, malicious desire, malicious passion, malicious quests.

_Vihiṃsādhātuṃ bhikkhave paṭicca uppajjati vihiṃsāsaññā. 
Vihiṃsāsaññaṃ paṭicca uppajjati vihiṃsāsaṅkappo. 
Vihiṃsāsaṅkappaṃ paṭicca uppajjati vihiṃsāchando. 
Vihiṃsāchandaṃ paṭicca uppajjati vihiṃsāpariḷāho. 
Vihiṃsāpariḷāhaṃ paṭicca uppajjati vihiṃsāpariyesanā._
____

.Illustration
====
vihiṃsakā

malicious; avihiṃsakā, compassionate
====

[quote, M.1.40-1]
____
Others will be malicious; we will be compassionate

_pare vihiṃsakā bhavissanti mayamettha avihiṃsakā bhavissāmā ti._
____

.Illustration
====
vihiṃsāya

maliciousness; avihiṃsā, compassion
====

[quote, A.3.447]
____
To abandon maliciousness, compassion should be developed.

_vihiṃsāya pahānāya avihiṃsā bhāvetabbā._
____

.Illustration
====
maliciousness

[quote

D.3.248]
====

____
For this is the liberation from maliciousness, namely the liberation [from 
perceptually obscuring states] through [unlimited, all-encompassing] compassion.

_Nissaraṇaṃ hetaṃ āvuso vihesāya yadidaṃ karuṇā cetovimutti._
____

