== Vijānata

=== Renderings

- _vijānata_: one who knows

- _vijānata_: one who understands [the teaching]

=== Introduction

==== Vijānata plus object

_Vijānata_ associated with an object means 'one who knows' or 'one who 
understands':

[quote, S.4.76]
____
He mindfully conducts himself in such a way that when knowing a mentally known 
object or encountering a sense impression [within himself], [attachment] is 
exhausted not built up.

_Yathāssa vijānato dhammaṃ sevato vāpi vedanaṃ +
Khīyati no pacīyati evaṃ so caratī sato._
____

Often it is linked to 'the teaching,' where it means 'one who understands':

[quote, Dh.v.60]
____
Long is the round of birth and death for the fool who does not understand the 
true teaching.

_Dīgho bālānaṃ saṃsāro saddhammaṃ avijānataṃ._
____

==== Vijānata minus object: parenthesising an object

Without an object, various passages show that _vijānata's_ object is 'the 
teaching':

[quote, S.1.198]
____
He listens but does not understand [the teaching], he looks but does not see 
&#8203;[the nature of reality]. Though the teaching is being spoken, the fool does not 
understand the meaning.

_Suṇāti na vijānāti āloketi na passati +
Dhammasmiṃ bhaññamānasmiṃ atthaṃ bālo na bujjhati._
____

[quote, S.1.193]
____
When the teaching has been so well explained, how can one who understands [it] 
be negligent [in practising it]?

_Evaṃ sudesite dhamme ko pamādo vijānataṃ._
____

=== Illustrations

.Illustration
====
vijānataṃ

one who understands [the teaching]
====

[quote, Th.v.14]
____
For one who understands [the teaching], there is no bondage [to individual 
existence].

_natthi saṅgo vijānatan ti._
____

.Illustration
====
vijānata

one who understands [the teaching]
====

[quote, S.1.20]
____
One who understands [the teaching] is worthy of a gift from those desiring 
merit.

_Puññamākaṅkhamānena deyyaṃ hoti vijānatāti._
____

.Illustration
====
vijānato

one who understands [the teaching]
====

[quote, Sn.v.953]
____
For one who is imperturbable, for one who understands [the teaching], there is 
no accumulated merit or demerit.

_Anejassa vijānato natthi kāci nisaṅkhiti._
____

.Illustration
====
vijānataṃ

one who understands [the teaching]
====

[quote, Sn.v.656]
____
'One who is endowed with the three final knowledges, who is inwardly at peace, 
who has destroyed renewed states of individual existence, thus know, 
Vāseṭṭha, he is Brahmā. For one who understands [the teaching], he is 
Sakka [Lord of the Devas].'

_Tīhi vijjāhi sampanno santo khīṇapunabbhavo +
Evaṃ vāseṭṭha jānāhi brahmā sakko vijānatan ti._
____

.Illustration
====
vijānataṃ

understands [the teaching]
====

[quote, S.1.127]
____
Perfect Ones, great Heroes, lead [others] by means of the true teaching. How 
could one who understands [the teaching] be jealous of those who lead [others] 
by the [true] teaching?

_Nayanti ve mahāvīrā saddhammena tathāgatā +
Dhammena nayamānānaṃ kā usūyā vijānatan ti._
____

.Illustration
====
vijānato

understands [the teaching]
====

[quote, S.1.163]
____
The fool thinks victory is through speech, and speaks harshly. One who 
understands [the teaching knows that] victory is for the one who endures [his 
foe's anger].

_Jayaṃ ve maññati bālo vācāya pharusaṃ bhaṇaṃ +
Jayaṃ ve cassa taṃ hoti yā titikkhā vijānato._
____

.Illustration
====
vijānatā

understand [the teaching]
====

[quote, Th.v.193]
____
For one who understands [the teaching], the night is for staying awake.

_Paṭijaggitumevesā ratti hoti vijānatā._
____

