== Vimokkha

=== Renderings

- _vimokkha_: deliverance [from perceptually obscuring states]

- _vimokkha_: state of refined awareness

- _saññāvimokkha_: deliverance from perception

- _vimokkho cetaso:_ deliverance of the mind [from individual existence]

=== Introduction

==== Vimokkha: arahantship

_Vimokkha_ occasionally means arahantship:

[quote, M.2.265]
____
This is the Deathless, namely the mind's deliverance [from perceptually 
obscuring states] through being without grasping.

_etaṃ amataṃ yadidaṃ anupādā cittassa vimokkho._
____

Sometimes this is called 'perpetual' and it is then equivalent to perpetual 
_vimutti_:

[quote, M.1.197]
____
Being diligently applied [to the practice], he attains perpetual deliverance 
&#8203;[from perceptually obscuring states] (_asamayavimokkhaṃ ārādheti_). And it 
is impossible for that bhikkhu to fall away from that perpetual liberation 
&#8203;[from perceptually obscuring states] (_asamayavimuttiyā parihāyetha_).

_Appamatto samāno asamayavimokkhaṃ ārādheti. Aṭṭhānametaṃ bhikkhave 
anavakāso yaṃ so bhikkhu tāya asamayavimuttiyā parihāyetha._
____

Cases where _vimokkha_ is not perpetual will be presented below.

==== Vimokkha of arahantship: deliverance [from perceptually obscuring states]

Although in the cases mentioned, _vimokkho_ has no specified object, the 
scriptures show that _āsavas_ (perceptually obscuring states) are the object, 
therefore in English, that parenthesis should be used. For example, in this 
conversation:

-- 'But, Sāriputta, if they were to ask you: 'Sāriputta, friend, through what 
state of deliverance (_kathaṃ vimokkhā_) have you declared your [attainment 
of] arahantship (_aññā vyākatā_) thus: "I know that birth is destroyed; 
the religious life has been fulfilled; what had to be done has been done; there 
will be no further arising in any state of individual existence?" Being asked 
thus, how would you answer?'

-- 'If they were to ask me this, bhante, I would answer thus: "Friends,

____
through an internal deliverance [from perceptually obscuring states]

_ajjhattavimokkhā khvāhaṃ āvuso_
____

____
through the destruction of all grasping _

_sabbūpādānakkhayā_
____

____
I abide mindfully in such a way that perceptually obscuring states (_āsavā_) 
do not pursue me

_tathā sato viharāmi yathā sataṃ viharantaṃ āsavā nānussavanti_
____

____
and I do not despise myself."_

_attānañca nāvajānāmī ti_
____

Being asked thus, bhante, I would answer in such a way.'

____
-- 'Very good, Sāriputta! And this is another way of explaining in brief that 
same point

_ayampi kho sāriputta pariyāyo etasseva atthassa saṅkhittena 
veyyākaraṇāya_
____

____
"I am not unsure about the perceptually obscuring states spoken of by the 
Ascetic

_ye āsavā samaṇena vuttā tesvāhaṃ na kaṅkhāmi_
____

[quote, S.2.54]
____
I do not doubt they have been abandoned by me"

_te me pahīṇāti na vicikicchāmī ti._
____

==== Vimokkha: eight states of refined awareness:

_Vimokkha_ usually means the eight _vimokkhas_ (_aṭṭha vimokkhā_). These 
correspond to the four jhānas, the four immaterial states and the ending of 
perception and sense impression (_saññāvedayitanirodhaṃ_).

'Immaterial states' (_āruppā_, D.3.224) is the shorter term for 'the 
immaterial states of awareness, those peaceful states of refined awareness that 
transcend the refined material states of awareness' (_santā vimokkhā 
atikkamma rūpe āruppā_) (M.1.34).

==== The eight vimokkhas

Here we list the eight _vimokkhas_. We call _vimokkha_ 'state of refined 
awareness,' and will explain this in due course.

____
There are eight states of refined awareness

_Aṭṭhime bhikkhave vimokkhā katame aṭṭha:_
____

1. Being in a refined material state of awareness, one sees visible objects. 
This is the first state of refined awareness
+
****
_Rūpī rūpāni passati. Ayaṃ paṭhamo vimokkho._
****

2. Being in an immaterial state of awareness, one sees visible objects. This is 
the second state of refined awareness
+
****
_Ajjhattaṃ arūpasaññī eko bahiddhā rūpāni passati. Ayaṃ dutiyo 
vimokkho._
****

3. One is focused exclusively on the Exquisite. This is the third state of 
refined awareness
+
****
_Subhanteva adhimutto hoti. Ayaṃ tatiyo vimokkho._
****

4. By completely transcending refined material states of awareness, with the 
vanishing of states of refined awareness involving physical sensation, not 
focusing upon states of refined awareness involving the external senses, one 
enters and abides in the state of awareness of boundless space where one 
perceives that space is boundless. This is the fourth state of refined awareness
+
****
_Sabbaso rūpasaññānaṃ samatikkamā paṭighasaññānaṃ atthaṅgamā 
nānattasaññānaṃ amanasikārā ananto ākāso ti ākāsanañcāyatanaṃ 
upasampajja viharati. Ayaṃ catuttho vimokkho._
****

5. By completely transcending the state of awareness of boundless space, one 
enters and abides in the state of awareness of boundless mental consciousness, 
where one perceives that mental consciousness is boundless. This is the fifth 
state of refined awareness
+
****
_Sabbaso ākāsānañcāyatanaṃ samatikkamma anantaṃ viññāṇan ti 
viññāṇañcāyatanaṃ upasampajja viharati. Ayaṃ pañcamo vimokkho._
****

6. By completely transcending the state of awareness of boundless mental 
consciousness, one enters and abides in the state of awareness of nonexistence, 
where one perceives that there is [nowhere] anything at all. This is the sixth 
state of refined awareness
+
****
_Sabbaso viññāṇañcāyatanaṃ samatikkamma natthi kiñcī ti 
ākiñcaññāyatanaṃ upasampajja viharati. Ayaṃ chaṭṭho vimokkho._
****

7. By completely transcending the state of awareness of nonexistence, one 
enters and abides in the state of awareness neither having nor lacking 
perception. This is the seventh state of refined awareness
+
****
_Sabbaso ākiñcaññāyatanaṃ samatikkamma nevasaññānāsaññāyatanaṃ 
upasampajja viharati. Ayaṃ sattamo vimokkho._
****

8. By completely transcending the state of awareness neither having nor lacking 
perception, one enters and abides in the ending of perception and sense 
impression. This is the eighth state of refined awareness
+
****
_Sabbaso nevasaññānāsaññāyatanaṃ samatikkamma saññāvedayitaṃ 
nirodhaṃ upasampajja viharati. Ayaṃ aṭṭhamo vimokkho ti. Ime kho 
bhikkhave aṭṭha vimokkhāti_ (D.2.71; D.2.112; D.3.262; D.3.288; M.2.13; 
A.4.307).
****

==== The vimokkhās are 'levels of refined awareness': the Poṭṭhapāda Sutta

The _Poṭṭhapāda Sutta_ shows why we call the eight _vimokkhas_ 'states of 
refined awareness' (_saññā_), because this is the term it uses:

____
Secluded from sensuous pleasures and spiritually unwholesome factors, he enters 
and abides in first jhāna, which is accompanied by thinking and pondering, and 
rapture and physical pleasure born of seclusion [from sensuous pleasures and 
spiritually unwholesome factors].

_So vivicceva kāmehi vivicca akusalehi dhammehi savitakkaṃ savicāraṃ 
vivekajaṃ pītisukhaṃ paṭhamaṃ jhānaṃ upasampajja viharati._
____

____
... For him the mental imagery of previous sensuous pleasure ceases.

_Tassa yā purimā kāmasaññā sā nirujjhati._
____

____
... And at that time there is a subtle but true perception of the rapture and 
physical pleasure born of seclusion [from sensuous pleasures and spiritually 
unwholesome factors]. He is one with a subtle but true perception of the 
rapture and physical pleasure born of seclusion [from sensuous pleasures and 
spiritually unwholesome factors].

_Vivekajapītisukhasukhumasaccasaññā tasmiṃ samaye hoti. 
Vivekajapītisukhasukhumasaccasaññī yeva tasmiṃ samaye hoti._
____

____
... In this way one state of refined awareness arises through the training, and 
one state of refined awareness ceases through the training. And that is the 
training, said the Blessed One...

_Evampi sikkhā ekā saññā uppajjati. Sikkhā ekā saññā nirujjhati. 
Ayaṃ sikkhā ti bhagavā avoca..._
____

... and so on, through the jhānas, up to the state of awareness of boundless 
mental consciousness (_viññāṇañcāyatana_). Then the sutta continues:

____
... Further, Poṭṭhapāda, by completely transcending the state of awareness 
of boundless mental consciousness, he enters and abides in the state of 
awareness of nonexistence, where one perceives that there is [nowhere] anything 
at all, and the previous subtle but true perception of the state of awareness 
of boundless mental consciousness ceases. And at that time there is a subtle 
but true perception of the state of awareness of nonexistence. He is one with a 
subtle but true perception of the state of awareness of nonexistence.

_Puna ca paraṃ poṭṭhapāda bhikkhu sabbaso viññāṇañcāyatanaṃ 
samatikkamma natthi kiñcī ti ākiñcaññāyatanaṃ upasampajja viharati. 
Tassa yā purimā viññāṇañcāyatanasukhumasaccasaññā sā nirujjhati. 
Ākiñcaññāyatanasukhumasaccasaññā tasmiṃ samaye hoti. 
Ākiñcaññāyatanasukhumasaccasaññiyeva tasmiṃ samaye hoti._
____

____
... In this way one state of refined awareness arises through the training, and 
one state of refined awareness ceases through the training. And that is the 
training, said the Blessed One.

_Evampi sikkhā ekā saññā uppajjati. Sikkhā ekā saññā nirujjhati. 
Ayampi sikkhā ti bhagavā avoca._
____

____
... Poṭṭhapāda, once the bhikkhu is possessed of that preliminary state of 
refined awareness, he proceeds from stage to stage till he reaches the highest 
state of refined awareness.

_Yato kho poṭṭhapāda bhikkhu idha sakasaññī hoti so tato amutra tato 
amutra anupubbena saññaggaṃ phusati._
____

____
... He attains to the ending [of originated phenomena].

_So nirodhaṃ phusati._
____

[quote, D.1.183-4]
____
And that, Poṭṭhapāda, is how the ending of successively refined states of 
refined awareness is attained in full consciousness.

_Evaṃ kho poṭṭhapāda anupubbābhisaññānirodhasampajānasamāpatti 
hoti._
____

==== Vimokkha: the Commentary

We will now discuss why _vimokkhas_ are called 'deliverances.' This meaning is 
a mystery even to the Commentary, because it explains the _vimokkhas_ as 
follows:

[quote, tr. Bodhi, NDB n.1776]
____
'In what sense are they emancipations? In the sense of releasing. In what sense 
releasing? In the sense of thoroughly freeing from adverse qualities, and in 
the sense of thoroughly freeing through delight in the object. What is meant is 
&#8203;[the mind's] occurrence on the object without constraint, free from worry, like 
a child sleeping on his father's lap, his body completely relaxed.'

_Vimokkhāti kenaṭṭhena vimokkhā? Adhimuccanaṭṭhena. Ko panāyaṃ 
adhimuccanaṭṭho nāma? Paccanīkadhammehi ca suṭṭhu muccanaṭṭho 
ārammaṇe ca abhirativasena suṭṭhu muccanaṭṭho pituaṅke 
vissaṭṭhaṅgapaccaṅgassa dārakassa sayanaṃ viya aniggahitabhāvena 
nirāsaṅkatāya ārammaṇe pavattīti vuttaṃ hoti._
____

But the 'adverse qualities' which are overcome by the eight _vimokkhās_ are 
none other than the _vimokkhās_ themselves. This is made clear in the 
_Sambādha Sutta_ which we now consider.

==== Sambādha Sutta (A.4.450): meaning of sambādho

The _Sambādha Sutta_ states that the jhānas and immaterial states are 
_sambādho_. Ordinarily this word means 'crowded,' but in the figurative sense 
PED calls it 'difficulty, trouble.' In the _Sambādha Sutta_ we accordingly 
render it as 'trouble' or 'something troublesome' or 'what is troublesome,' and 
the adjective as 'troublesome.'

==== Sambādha Sutta: the troublesomeness of jhānas and immaterial states

The _Sambādha Sutta_ concerns the deliverance from troublesome states of 
refined awareness through more refined states of refined awareness. Having 
considered this sutta, we will see that the eight _vimokkhas_ are deliverances 
in the same sense.

The _Sambādha Sutta_ is as follows:

____
The five varieties of sensuous pleasure are called inwardly troublesome by the 
Blessed One.

_Ime kho āvuso pañcakāmaguṇā sambādho vutto bhagavatā._
____

____
... In this regard a bhikkhu, secluded from sensuous pleasures and spiritually 
unwholesome factors, enters and abides in first jhāna, which is accompanied by 
thinking and pondering, and rapture and physical pleasure born of seclusion 
&#8203;[from sensuous pleasures and spiritually unwholesome factors].

_Idhāvuso bhikkhu vivicceva kāmehi vivicca akusalehi dhammehi savitakkaṃ 
savicāraṃ vivekajaṃ pītisukhaṃ paṭhamaṃ jhānaṃ upasampajja 
viharati._
____

____
... It is in reference to this that a deliverance from what is inwardly 
troublesome is spoken of by the Blessed One, in a way that is qualified, 
because again there is something inwardly troublesome.

_Ettāvatā pi kho āvuso sambādhe okāsādhigamo vutto bhagavatā 
pariyāyena. Tattha'patthi sambādho._
____

____
... What is troublesome in this case?_

_Kiñca tattha sambādho?_
____

____
... The thinking and pondering that are unended is troublesome in this case._

_Yadeva tattha vitakkavicārā aniruddhā honti ayamettha sambādho._
____

____
... Again, in this regard, with the subsiding of thinking and pondering, and 
&#8203;[the development of] internal serenity and concentration, a bhikkhu enters and 
abides in second jhāna which is without thinking and pondering, and is filled 
with rapture and physical pleasure born of inward collectedness.

_Puna ca paraṃ āvuso bhikkhu vitakkavicārānaṃ vūpasamā ajjhattaṃ 
sampasādanaṃ cetaso ekodibhāvaṃ avitakkaṃ avicāraṃ samādhijaṃ 
pītisukhaṃ dutiyaṃ jhānaṃ upasampajja viharati._
____

____
... It is in reference to this that a deliverance from what is inwardly 
troublesome is spoken of by the Blessed One, in a way that is qualified, 
because again there is something inwardly troublesome.

_Ettāvatā pi kho āvuso sambādhe okāsādhigamo vutto bhagavatā 
pariyāyena. Tattha'patthi sambādho._
____

____
... What is troublesome in this case?_

_Kiñca tattha sambādho?_
____

____
... The rapture that is unended is troublesome in this case._

_Yadeva tattha pīti aniruddhā hoti ayamettha sambādho._
____

____
... Again, in this regard, with the fading away of rapture, a bhikkhu abides 
serene, mindful, and fully conscious, experiencing physical pleasure. He enters 
and abides in third jhāna in which the Noble Ones declare that he abides 
serene, mindful, and in physical pleasure._

_Puna ca paraṃ āvuso pītiyā ca virāgā upekkhako ca viharati sato ca 
sampajāno sukhañca kāyena paṭisaṃvedeti yantaṃ ariyā ācikkhanti 
upekkhako satimā sukhavihārīti taṃ tatiyaṃ jhānaṃ upasampajja 
viharati._
____

____
... It is in reference to this that a deliverance from what is inwardly 
troublesome is spoken of by the Blessed One, in a way that is qualified, 
because again there is something inwardly troublesome.

_Ettāvatā pi kho āvuso sambādhe okāsādhigamo vutto bhagavatā 
pariyāyena. Tattha'patthi sambādho._
____

____
... What is troublesome in this case?_

_Kiñca tattha sambādho?_
____

____
... The serenity with physical pleasure that is unended is troublesome in this 
case._

_Yadeva tattha upekkhāsukhaṃ aniruddhaṃ hoti ayamettha sambādho._
____

____
... Again, in this regard, with the abandonment of physical pleasure and pain, 
and following the vanishing of psychological pleasure and pain, a bhikkhu 
enters and abides in fourth jhāna, which is free of pleasure and pain, and [is 
imbued with] purified detached awareness and mindfulness.

_Puna ca paraṃ āvuso bhikkhu sukhassa ca pahānā dukkhassa ca pahānā 
pubbeva somanassadomanassānaṃ atthaṅgamā adukkhamasukhaṃ 
upekkhāsatipārisuddhiṃ catutthaṃ jhānaṃ upasampajja viharati._
____

____
... It is in reference to this that a deliverance from what is inwardly 
troublesome is spoken of by the Blessed One, in a way that is qualified, 
because again there is something inwardly troublesome.

_Ettāvatā pi kho āvuso sambādhe okāsādhigamo vutto bhagavatā 
pariyāyena. Tattha'patthi sambādho._
____

____
... What is troublesome in this case?_

_Kiñca tattha sambādho?_
____

____
... The perception of the refined material states of awareness that is unended 
is troublesome in this case._

_Yadeva tattha rūpasaññā aniruddhā hoti ayamettha sambādho._
____

____
... Again, in this regard, by completely transcending refined material states 
of awareness, with the vanishing of states of refined awareness involving 
physical sensation, not focusing upon states of refined awareness involving the 
external senses, a bhikkhu enters and abides in the state of awareness of 
boundless space where one perceives that space is boundless.

_Puna ca paraṃ āvuso bhikkhu sabbaso rūpasaññānaṃ samatikkamā 
paṭighasaññānaṃ atthaṅgamā nānattasaññānaṃ amanasikārā ananto 
ākāso ti ākāsānañcāyatanaṃ upasampajja viharati._
____

____
... It is in reference to this that a deliverance from what is inwardly 
troublesome is spoken of by the Blessed One, in a way that is qualified, 
because again there is something inwardly troublesome.

_Ettāvatā pi kho āvuso sambādhe okāsādhigamo vutto bhagavatā 
pariyāyena. Tattha'patthi sambādho._
____

____
... What is troublesome in this case?_

_Kiñca tattha sambādho?_
____

____
... The perception of the state of awareness of boundless space that is unended 
is troublesome in this case._

_Yadeva tattha ākāsānañcāyatanasaññā aniruddhā hoti. Ayamettha 
sambādho._
____

____
... Again, in this regard, by completely transcending the state of awareness of 
boundless space, a bhikkhu enters and abides in the state of awareness of 
boundless mental consciousness, where one perceives that mental consciousness 
is boundless.

_Puna ca paraṃ āvuso bhikkhu sabbaso ākāsānañcāyatanaṃ samatikkamma 
anantaṃ viññāṇan ti viññāṇañcāyatanaṃ upasampajja viharati._
____

____
... It is in reference to this that a deliverance from what is inwardly 
troublesome is spoken of by the Blessed One, in a way that is qualified, 
because again there is something inwardly troublesome.

_Ettāvatā pi kho āvuso sambādhe okāsādhigamo vutto bhagavatā 
pariyāyena. Tattha'patthi sambādho._
____

____
... What is troublesome in this case?_

_Kiñca tattha sambādho?_
____

____
... The perception of the state of awareness of boundless mental consciousness 
that is unended is troublesome in this case._

_Yadeva tattha viññāṇañcāyatanasaññā aniruddhā hoti. Ayamettha 
sambādho._
____

____
... Again, in this regard, by completely transcending the state of awareness of 
boundless mental consciousness, a bhikkhu enters and abides in the state of 
awareness of nonexistence, where one perceives that there is [nowhere] anything 
at all.

_Puna ca paraṃ āvuso bhikkhu sabbaso viññāṇañcāyatanaṃ samatikkamma 
natthi kiñcīti ākiñcaññāyatanaṃ upasampajja viharati._
____

____
... It is in reference to this that a deliverance from what is inwardly 
troublesome is spoken of by the Blessed One, in a way that is qualified, 
because again there is something inwardly troublesome.

_Ettāvatā pi kho āvuso sambādhe okāsādhigamo vutto bhagavatā 
pariyāyena. Tattha'patthi sambādho._
____

____
... What is troublesome in this case?_

_Kiñca tattha sambādho?_
____

____
... The perception of the state of awareness of nonexistence that is unended is 
troublesome in this case._

_Yadeva tattha ākiñcaññāyatanasaññā aniruddhā hoti ayamettha 
sambādho._
____

____
... Again, in this regard, By completely transcending the state of awareness of 
nonexistence, a bhikkhu enters and abides in the state of awareness neither 
having nor lacking perception.

_Puna ca paraṃ āvuso bhikkhu sabbaso ākiñcaññāyatanaṃ samatikkamma 
nevasaññānāsaññāyatanaṃ upasampajja viharati._
____

____
... It is in reference to this that a deliverance from what is inwardly 
troublesome is spoken of by the Blessed One, in a way that is qualified, 
because again there is something inwardly troublesome.

_Ettāvatā pi kho āvuso sambādhe okāsādhigamo vutto bhagavatā 
pariyāyena. Tattha'patthi sambādho._
____

____
... What is troublesome in this case?_

_Kiñca tattha sambādho?_
____

____
... The perception of the state of awareness neither having nor lacking 
perception that is unended is troublesome in this case._

_Yadeva tattha nevasaññānāsaññāyatanasaññā aniruddhā hoti ayamettha 
sambādho._
____

____
... Again, in this regard, by completely transcending the state of awareness 
neither having nor lacking perception, a bhikkhu enters and abides in the 
ending of perception and sense impression. And, by seeing [reality] with 
penetrative discernment, his perceptually obscuring states are destroyed

_Puna ca paraṃ āvuso bhikkhu sabbaso nevasaññānāsaññāyatanaṃ 
samatikkamma saññāvedayitanirodhaṃ upasampajja viharati. Paññāya cassa 
disvā āsavā parikkhīṇā honti._
____

[quote, A.4.450-1]
____
... It is in reference to this that a deliverance from what is inwardly 
troublesome is spoken of by the Blessed One, in a way that is unqualified._

_Ettāvatā pi kho āvuso sambādhe okāsādhigamo vutto bhagavatā 
nippariyāyenāti._
____

==== What to call vimokkha?

The _Sambādha Sutta_ concerns the deliverances from the troublesomeness 
associated with states of refined awareness by attaining more refined states of 
refined awareness. If the eight _vimokkhas_ are considered deliverances in the 
same sense, it explains why they have been called deliverances. We will now 
discuss why we do not call them 'deliverances,' but instead call them 'states 
of refined awareness.'

Let us first translate the list of _vimokkhas_ as 'deliverances [from 
troublesomeness through states of refined awareness],' and we will see, and 
then resolve, the cumbersomeness it creates:

____
There are eight deliverances [from troublesomeness through states of refined 
awareness].

_Aṭṭhime bhikkhave vimokkhā katame aṭṭha:_
____

1. Being in a refined material state of awareness, one sees visible objects. 
This is the first deliverance [from troublesomeness through states of refined 
awareness].
+
****
_Rūpī rūpāni passati. Ayaṃ paṭhamo vimokkho._
****

2. Being in an immaterial state of awareness, one sees visible objects. This is 
the second deliverance [from troublesomeness through states of refined 
awareness].
+
****
_Ajjhattaṃ arūpasaññī eko bahiddhā rūpāni passati. Ayaṃ dutiyo 
vimokkho._
****

It is cumbersome to label _vimokkha_ like this, and it adds nothing to the 
understanding of the text. Accordingly, we label _vimokkha_ as 'state of 
refined awareness.' That is:

1. Being in a refined material state of awareness, one sees visible objects. 
This is the first state of refined awareness.
+
****
_Rūpī rūpāni passati. Ayaṃ paṭhamo vimokkho._
****

2. Being in an immaterial state of awareness, one sees visible objects. This is 
the second state of refined awareness.
+
****
_Ajjhattaṃ arūpasaññī eko bahiddhā rūpāni passati. Ayaṃ dutiyo 
vimokkho._
****

==== Vimokkho cetaso: deliverance of his mind [from individual existence]

At the passing away of the Buddha, Venerable Anuruddha said:

[quote, S.1.159]
____
The deliverance of his mind [from individual existence] was like the quenching 
of a lamp

_pajjotasseva nibbānaṃ vimokkho cetaso ahūti._
____

Here we parenthesise '[from individual existence]' because when the arahant 
dies, states of individual existence altogether cease:

____
These two aspects of the Untroubled were made known by the Seer, free of 
attachment, and of excellent qualities.

_Duve imā cakkhumatā pakāsitā +
Nibbānadhātu anissitena tādinā_
____

____
... One aspect is realisable in this lifetime, with residue, but with the 
conduit to renewed states of individual existence destroyed;

_Ekā hi dhātu idha diṭṭhadhammikā +
Saupādisesā bhavanettisaṅkhayā._
____

[quote, It.38-9]
____
... The other, having no residue, is that wherein states of individual 
existence altogether cease.

_Anupādisesā pana samparāyikā +
Yamhi nirujjhanti bhavāni sabbaso._
____

=== Illustrations

.Illustration
====
vimokkha

states of refined awareness
====

[quote, M.1.69-71]
____
The Perfect One discerns according to reality the attainment, the defilement, 
the purification and the emergence in regard to the jhānas, the states of 
refined awareness, and states of inward collectedness.

_jhānavimokkhasamādhisamāpattīnaṃ saṅkilesaṃ vodānaṃ 
vuṭṭhānaṃ yathābhūtaṃ pajānāti._
____

.Illustration
====
vimokkhaṃ

state of refined awareness
====

[quote, D.3.34]
____
When someone attains the state of refined awareness that is exquisite, he knows 
that it is exquisite

_yasmiṃ samaye subhaṃ vimokkhaṃ upasampajja viharati subhantveva tasmiṃ 
samaye pajānātī ti._
____

.Illustration
====
sāmiso vimokkho

material state of refined awareness; nirāmiso vimokkho, immaterial state of 
refined awareness;
====

____
And what is the material state of refined awareness?_

_Katamo ca bhikkhave sāmiso vimokkho_
____

____
The state of refined awareness connected with refined material states of 
awareness is the material state of refined awareness.

_rūpapaṭisaṃyutto vimokkho sāmiso vimokkho._
____

____
And what is the immaterial state of refined awareness?

_Katamo ca bhikkhave nirāmiso vimokkho:_
____

____
The state of refined awareness connected with immaterial states of awareness is 
the immaterial state of refined awareness

_arūpapaṭisaṃyutto vimokkho nirāmiso vimokkho_
____

____
And what is the state of refined awareness more than immaterial?

_Katamo ca bhikkhave nirāmisā nirāmisataro vimokkho._
____

____
When a bhikkhu whose _āsavas_ are destroyed reviews his mind

_yo kho bhikkhave khīṇāsavassa bhikkhuno_
____

____
liberated from attachment

_rāgā cittaṃ vimuttaṃ paccavekkhato_
____

____
liberated from hatred

_dosaṃ cittaṃ vimuttaṃ paccavekkhato_
____

____
liberated from undiscernment of reality

_mohā cittaṃ vimuttaṃ paccavekkhato_
____

____
there arises in him a state of refined awareness

_uppajjati vimokkho_
____

[quote, S.4.237]
____
This is called the state of refined awareness more than immaterial

_ayaṃ vuccati bhikkhave nirāmisā nirāmisataro vimokkho ti._
____

.Illustration
====
vimokkhā

states of refined awareness
====

[quote, M.1.472]
____
A forest bhikkhu should endeavour [to attain] those immaterial states of 
awareness, those peaceful states of refined awareness that transcend the 
refined material states of awareness.

_Āraññakenāvuso bhikkhunā ye te santā vimokkhā atikkamma rūpe āruppā 
tattha yogo karaṇīyo._
____

.Illustration
====
vimokkho

state of refined awareness
====

State of refined awareness (_vimokkho_) means:

____
the state of refined awareness that is void [of the perception of personal 
qualities]

_suññato vimokkho_
____

____
the state of refined awareness that is focused upon the unabiding [phenomena]

_animitto vimokkho_
____

[quote, Vin.3.92]
____
the state of refined awareness that is void of aspiration

_appaṇihito vimokkho._
____

.Illustration
====
vimokkhā

state of refined awareness
====

____
And what is the individual liberated [from perceptually obscuring states] both 
through [penetrative discernment and through attaining the immaterial states of 
awareness]?

_Katamo ca bhikkhave puggalo ubhatobhāgavimutto_
____

____
In this regard, some person abides touching with his very being those 
immaterial states of awareness, those peaceful states of refined awareness that 
transcend the refined material states of awareness, and by seeing [reality] 
with penetrative discernment, his perceptually obscuring states are destroyed.

_idha bhikkhave ekacco puggalo ye te santā vimokkhā atikkamma rūpe āruppā 
te kāyena phassitvā viharati paññāya cassa disvā āsavā parikkhīṇā 
honti._
____

[quote, M.1.477-9]
____
This is called an individual liberated [from perceptually obscuring states] 
both through [penetrative discernment and through attaining the immaterial 
states of awareness].

_Ayaṃ vuccati bhikkhave puggalo ubhatobhāgavimutto._
____

.Illustration
====
vimokkho

deliverance [from perceptually obscuring states]
====

[quote, Thī.v.116]
____
The deliverance of my mind [from individual existence] was like the quenching 
of the lamp.

_padīpasseva nibbānaṃ vimokkho ahu cetaso._
____

.Illustration
====
vimokkhāya

deliverance [from perceptually obscuring states]
====

____
"Bhante, the bhikkhu Vakkali is intent upon deliverance [from perceptually 
obscuring states]."

_vakkali bhante bhikkhu vimokkhāya cetetī ti._
____

• The other deva said 'Surely, bhante, he will be liberated [from 
perceptually obscuring states].' +
☸ _Aparā devatā bhagavantaṃ etadavoca so hi nūna bhante suvimutto 
vimuccissatī_ ti (S.3.121).

.Illustration
====
vimokkho

deliverance [from perceptually obscuring states]
====

____
But if one profoundly understands what can be expressed, and does not think 'I 
am the expressor.'

_Akkheyyañca pariññāya akkhātāraṃ na maññati_
____

[quote, It.53]
____
The mind's deliverance [from perceptually obscuring states] is achieved, the 
unsurpassed Peaceful State.

_Phūṭṭho vimokkho manasā santipadamanuttaraṃ._
____

.Illustration
====
vimokkho

deliverance from perception
====

[quote, Sn.v.1072]
____
Being liberated [from perceptually obscuring states] through the highest 
deliverance from perception

_Saññāvimokkhe parame vimutto._
____

COMMENT

_Saññāvimokkhe parame_: 'through the highest deliverance from perception.' 
Although perception ceases with the ending of perception and sense impression 
(_saññāvedayitaṃ nirodhaṃ_), the 'highest deliverance' would be 
arahantship, which lies beyond it. This is confirmed by the statement 'not 
subject to [renewed states of individual existence]' in the next verse.

