== Vimuttiñāṇadassana

=== Renderings

- _vimuttiñāṇadassana_: the knowledge and vision that follows liberation 
&#8203;[from perceptually obscuring states]

=== Introduction

==== Vimuttiñāṇadassana: finding the connective

_Vimuttiñāṇadassana_ is usually translated with the connective 'of':

- 'the knowledge and vision of liberation' (Bodhi, A.5.3)

- the knowledge and vision of freedom (Horner, M.1.146).

But the suttas do not say that liberation is associated with knowledge 'of' 
liberation. They say that following liberation, the bhikkhu has the knowledge 
'that' he is liberated, and 'that' birth is destroyed etc.:

[quote, M.3.108]
____
Being liberated [from perceptually obscuring states], the knowledge arises that 
he is [thus] liberated. He knows that birth is destroyed; the religious life 
has been fulfilled; what had to be done has been done; there will be no further 
arising in any state of individual existence.

_Vimuttasmiṃ vimuttami ti ñāṇaṃ hoti. Khīṇā jāti vusitaṃ 
brahmacariyaṃ kataṃ karaṇīyaṃ nāparaṃ itthattāyā ti pajānāti._
____

==== Vimutti equals āsavakkhaya

We have shown (sv _Vimutta_) that _vimutta_/_vimutti_ should be parenthesised: 
liberated/liberation [from perceptually obscuring states]. We used this quote 
to demonstrate this:

[quote, M.1.183-4]
____
For him thus knowing and seeing, his mind is liberated from perceptually 
obscuring states due to pursuing sensuous pleasure, liberated from perceptually 
obscuring states due to pursuing individual existence, and liberated from 
perceptually obscuring states due to uninsightfulness into reality. Being 
liberated [from perceptually obscuring states], the knowledge arises that he is 
&#8203;[thus] liberated.

_Tassa evaṃ jānato evaṃ passato kāmāsavāpi cittaṃ vimuccati 
bhavāsavāpi cittaṃ vimuccati avijjāsavāpi cittaṃ vimuccati. 
Vimuttasmiṃ vimuttami ti ñāṇaṃ hoti._
____

In other words, _vimutti_ equals _āsavakkhaya_, as further indicated in this 
quote:

[quote, A.3.21]
____
This is the first occasion of liberation [from perceptually obscuring states] 
in which, for a bhikkhu abiding diligently, vigorously, and resolutely applied 
&#8203;[to the practice], his unliberated mind is liberated [from perceptually 
obscuring states], his undestroyed perceptually obscuring states are destroyed, 
the unreached safety from the danger of bondage [to individual existence] is 
reached._

_Idaṃ bhikkhave paṭhamaṃ vimuttāyatanaṃ yattha bhikkhuno appamattassa 
ātāpino pahitattassa viharato avimuttaṃ vā cittaṃ vimuccati 
aparikkhīṇā vā āsavā parikkhayaṃ gacchanti ananuppattaṃ vā 
anuttaraṃ yogakkhemaṃ anupāpuṇāti._
____

==== Vimuttiñāṇadassanakkhandha implies multiplicity

_Vimuttiñāṇadassana_ is one of the five aggregates that should be realised 
for oneself: _Katame pañca dhammā sacchikātabbā? Pañca dhammakkhandhā: 
sīlakkhandho samādhikkhandho paññākkhandho vimuttikkhandho 
vimuttiñāṇadassanakkhandho_ (D.3.279).

Following his enlightenment, the Buddha said that he sought to perfect each of 
these five aggregates. For example, he said:

[quote, S.1.139]
____
It would be for the sake of fulfilling the unfulfilled aggregate of the 
knowledge and vision that follows liberation [from perceptually obscuring 
states] that I would honour, respect, and dwell under another ascetic or 
brahman in spiritual discipleship. But I do not see another ascetic or brahman 
in the world [of beings] with its devas, māras, and brahmās, in the world of 
mankind with its ascetics and Brahmanists, its royalty and commoners who is 
more perfect that I in the knowledge and vision that follows liberation [from 
perceptually obscuring states] that I could honour, respect, and dwell under in 
spiritual discipleship.

_aparipuṇṇassa kho vimuttiñāṇadassanakkhandhassa pāripuriyā aññaṃ 
samaṇaṃ vā brāhmaṇaṃ vā sakkatvā garukatvā upanissāya 
vihareyyaṃ. na kho panāhaṃ passāmi sadevake loke samārake sabrahmake 
sassamaṇabrāhmaṇiyā pajāya sadevamanussāya attanā vimutti 
ñāṇadassanasampannataraṃ aññaṃ samaṇaṃ vā brāhmaṇaṃ vā 
yamahaṃ sakkatvā garukatvā upanissāya vihareyyaṃ._
____

If _vimuttiñāṇadassana_ is an aggregate, it is a group of knowledges. It 
cannot be simply 'knowledge and vision of liberation.'

==== Vimuttiñāṇadassana before enlightenment

_Vimuttiñāṇadassana_ is usually associated with arahants. However, the 
Buddha's question to the unenlightened Ānanda indicates that it may be 
operative even before enlightenment:

[quote, S.5.162]
____
'Why, Ānanda, when Sāriputta passed away, did he take away your aggregate of 
virtuous practices, inward collectedness, penetrative discernment, liberation 
&#8203;[from perceptually obscuring states], and the knowledge and vision that follows 
liberation [from perceptually obscuring states]?' 'No, bhante.'

_Kinnu kho te ānanda sāriputto sīlakkhandhaṃ vā ādāya parinibbuto 
samādhikkhandhaṃ vā ādāya parinibbuto paññākkhandhaṃ vā ādāya 
parinibbuto vimuttikkhandhaṃ vā ādāya parinibbuto 
vimuttiñāṇadassanakkhandhaṃ vā ādāya parinibbuto ti? Na kho me bhante._
____

Although the destruction of perceptually obscuring states (_āsavakkhaya_) is 
prominently associated with arahantship, _āsavas_ are in fact destroyed from 
stream-entry onwards. The three types of individuals who are at least 
stream-enterers but not arahants are called _kāyasakkhī, diṭṭhappatto_ 
and _saddhāvimutto._ The _Kīṭāgiri Sutta_ (M.1.438) says that for each of 
these individuals some of his perceptually obscuring states are destroyed 
(_ekacce āsavā parikkhīṇā honti_). Therefore 
_vimuttiñāṇadassanakkhandha_ likely begins at stream-entry. Before 
stream-entry, no perceptually obscuring states are destroyed (_āsavā 
aparikkhīṇā honti_, M.1.479).

==== The knowledge and vision that follows liberation [from perceptually obscuring states]: further aspects

If _vimuttiñāṇadassana_ is an aggregate, then it has various of its aspects 
of knowledge that become apparent to an arahant, and perhaps even before that. 
We have already noted various instances of knowledge in this quote:

[quote, M.3.108]
____
Being liberated [from perceptually obscuring states], the knowledge arises that 
he is [thus] liberated. He knows that birth is destroyed; the religious life 
has been fulfilled; what had to be done has been done; there will be no further 
arising in any state of individual existence.

_Vimuttasmiṃ vimuttami ti ñāṇaṃ hoti. Khīṇā jāti vusitaṃ 
brahmacariyaṃ kataṃ karaṇīyaṃ nāparaṃ itthattāyā ti pajānāti._
____

Other instances of knowledge are given as the conclusion of other suttas:

1. He knows that birth is destroyed; the religious life has been fulfilled; 
what had to be done has been done; there will be no further arising in any 
state of individual existence. This, too, is called a footprint of the Perfect 
One, a scratch mark of the Perfect One, a tusk slash of the Perfect One. And it 
is not until this point that a noble disciple can come to the conclusion: 'The 
Blessed One is perfectly enlightened; the teaching is well explained by the 
Blessed One; the community of the Blessed One's disciples is applied to an 
excellent practice.
+
****
_Khīṇā jāti vusitaṃ brahmacariyaṃ kataṃ karaṇīyaṃ nāparaṃ 
itthattāyāti pajānāti. Idampi vuccati brāhmaṇa tathāgatapadaṃ iti pi 
tathāgatanisevitaṃ iti pi tathāgatārañjitaṃ itipi. Ettāvatā kho 
brāhmaṇa ariyasāvako niṭṭhaṃ gato hoti sammāsambuddho bhagavā 
svākkhāto bhagavatā dhammo supaṭipanno bhagavato sāvakasaṅgho ti_ 
(M.1.183-4).
****

2. He knows that birth is destroyed; the religious life has been fulfilled; 
what had to be done has been done; there will be no further arising in any 
state of individual existence.
+
****
_Tassa evaṃ jānato evaṃ passato kāmāsavāpi cittaṃ vimuccati 
bhavāsavāpi cittaṃ vimuccati avijjāsavāpi cittaṃ vimuccati. 
Vimuttasmiṃ vimuttami ti ñāṇaṃ hoti. Khīṇā jāti vusitaṃ 
brahmacariyaṃ kataṃ karaṇīyaṃ nāparaṃ itthattāyā ti pajānāti._
****

____
He knows that whatever states of suffering there are because of perceptual 
obscuration due to pursuing sensuous pleasure, of perceptual obscuration due to 
pursuing individual existence, and of perceptual obscuration due to 
uninsightfulness into reality, are absent. And there is only this amount of 
suffering, namely what is connected with the six senses which are dependent on 
the body and have life as their necessary condition.

_So evaṃ pajānāti ye assu darathā kāmāsavaṃ paṭicca tedha na santi 
ye assu darathā bhavāsavaṃ paṭicca tedha na santi ye assu darathā 
avijjāsavaṃ paṭicca tedha na santi atthi cevāyaṃ darathamattā 
yadidaṃ imameva kāyaṃ paṭicca saḷāyatanikaṃ jīvitapaccayā ti._
____

[quote, M.3.108]
____
He knows that "This state of perception is void of perceptual obscuration due 
to pursuing sensuous pleasure, of perceptual obscuration due to pursuing 
individual existence, and of perceptual obscuration due to uninsightfulness 
into reality. And there is just this state which is not absent, namely what is 
connected with the six senses which are dependent on the body and have life as 
their necessary condition. He regards it as void of whatever is not there. Of 
the remainder, he discerns: "That [absence] being, this [relative voidness] 
is." This is for him the undistorted, pure, supreme, unsurpassed realisation of 
&#8203;[the perception of] [relative] voidness according to reality.

_So suññamidaṃ saññāgataṃ kāmāsavenā ti pajānāti suññamidaṃ 
saññāgataṃ bhavāsavenā ti pajānāti suññamidaṃ saññāgataṃ 
avijjāsavenā ti pajānāti atthi cevidaṃ asuññataṃ yadidaṃ imameva 
kāyaṃ paṭicca saḷāyatanikaṃ jīvitapaccayā ti. Iti yaṃ hi kho 
tattha na hoti tena taṃ suññaṃ samanupassati yaṃ pana tattha 
avasiṭṭhaṃ hoti taṃ santamidaṃ atthī ti pajānāti. Evam pi'ssa esā 
ānanda yathābhuccā avipallatthā parisuddhā paramānuttarā 
suññatāvakkanti bhavati._
____

=== Illustrations

.Illustration
====
vimuttiñāṇadassanaṃ

the knowledge and vision that follows liberation [from perceptually obscuring 
states]
====

____
For one who is disillusioned [with originated phenomena] and unattached [to 
originated phenomena], there is no need to harbour the aspiration: 'May I 
realise the knowledge and vision that follows liberation [from perceptually 
obscuring states]':

_Nibbindassa bhikkhave virajjantassa na cetanāya karaṇīyaṃ 
vimuttiñāṇadassanaṃ sacchikaromī ti._
____

[quote, A.5.3]
____
It is quite natural that one who is disillusioned [with originated phenomena] 
and unattached [to originated phenomena] will realise the knowledge and vision 
that follows liberation [from perceptually obscuring states].

_Dhammatā esā bhikkhave yaṃ nibbiṇṇo viratto vimuttiñāṇadassanaṃ 
sacchikaroti._
____

.Illustration
====
vimuttiñāṇadassanaṃ

the knowledge and vision that follows liberation [from perceptually obscuring 
states]
====

[quote, M.3.113]
____
Talk about liberation [from perceptually obscuring states], talk about the 
knowledge and vision that follows liberation [from perceptually obscuring 
states], he thinks: 'I will utter speech like this.'

_vimuttikathā vimuttiñāṇadassanakathā iti evarūpiṃ kathaṃ 
kathessāmīti._
____

