== Vinicchaya

=== Renderings

- _vinicchaya_: analysis

- _vinicchaya_: examination

- _vinicchaya_: dogmatic opinion

- _vinicchināti_: to divide

- _vinicchināti_: to investigate

=== Illustrations

.Illustration
====
vinicchaya

analysis
====

____
'One should know the analysis of pleasure, and knowing that, one should devote 
oneself to inward pleasure.' So it was said. In reference to what was it said?

_Sukhavinicchayaṃ jaññā sukhavinicchayaṃ ñatvā ajjhattaṃ 
sukhamanuyuñjeyyā'ti iti kho panetaṃ vuttaṃ kiñcetaṃ paṭicca 
vuttaṃ:_
____

____
There are these five varieties of sensuous pleasure. What five? Visible objects 
known via the visual sense... tangible objects known via the tactile sense that 
are likeable, loveable, pleasing, agreeable, connected with sensuous pleasure, 
and charming. These are the five varieties of sensuous pleasure.

_pañcime bhikkhave kāmaguṇā. Katame pañca: cakkhuviññeyyā rūpā... 
kāyaviññeyyā poṭṭhabbā iṭṭhā kantā manāpā piyarūpā 
kāmūpasaṃhitā rajanīyā. Ime kho bhikkhave pañcakāmaguṇā._
____

____
The physical and psychological pleasure that arises from the five varieties of 
sensuous pleasure: this is called sensuous pleasure, a vile pleasure, the 
pleasure of the common man, an ignoble pleasure. This pleasure should not be 
pursued, developed, and cultivated, I declare. It should be feared.

_Yaṃ kho bhikkhave ime pañcakāmaguṇe paṭicca uppajjati sukhaṃ 
somanassaṃ idaṃ vuccati kāmasukhaṃ mīḷhasukhaṃ puthujjanasukhaṃ 
anariyasukhaṃ. Na āsevitabbaṃ na bhāvetabbaṃ na bahulīkātabbaṃ 
bhāyitabbaṃ etassa sukhassāti vadāmi._
____

• In this regard, secluded from sensuous pleasures and spiritually 
unwholesome factors, a bhikkhu enters and abides in first jhāna... a bhikkhu 
enters and abides in fourth jhāna._ +
☸ Idha bhikkhave bhikkhu vivicceva kāmehi vivicca akusalehi dhammehi 
savitakkaṃ savicāraṃ vivekajaṃ pītisukhaṃ paṭhamaṃ jhānaṃ 
upasampajja viharati… catutthaṃ jhānaṃ upasampajja viharati._

____
This is called the pleasure of the practice of unsensuousness, the pleasure of 
physical seclusion, the pleasure of inward peace, the pleasure of 
enlightenment. This pleasure should be pursued, developed, and cultivated, I 
declare. It should not be feared.

_Idaṃ vuccati nekkhammasukhaṃ pavivekasukhaṃ upasamasukhaṃ 
sambodhisukhaṃ āsevitabbaṃ bhāvetabbaṃ bahulīkātabbaṃ. Na 
bhāyitabbaṃ etassa sukhassāti vadāmi._
____

[quote, M.3.233-4]
____
'One should know the analysis of pleasure, and knowing that, one should devote 
oneself to inward pleasure.' So it was said. It was in reference to this that 
it was said._

_Sukhavinicchayaṃ jaññā sukhavinicchayaṃ ñatvā ajjhattaṃ 
sukhamanuyuñjeyyā'ti iti yaṃ taṃ vuttaṃ idametaṃ paṭicca vuttaṃ_
____

.Illustration
====
vinicchayo

examination
====

• Because of acquisition, examination _ +
lābhaṃ paṭicca vinicchayo_

• Because of examination, fondness and attachment _ +
vinicchayaṃ paṭicca chandarāgo_ (A.4.401).

.Illustration
====
vinicchayā

dogmatic opinions
====

&#8203;[The Buddha:]

[quote, Sn.v.837]
____
'In regards to dogmatic religious views, of none of them have I said "I 
proclaim this." But rather, in scrutinising views, without grasping, while 
searching, I realised inward peace.'

_Idaṃ vadāmī ti na tassa hoti dhammesu niccheyya samuggahītaṃ +
Passañca diṭṭhīsu anuggahāya ajjhattasantiṃ pacinaṃ adassaṃ._
____

&#8203;[Māgandiya:]

[quote, Sn.v.838]
____
'About dogmatic opinions that have been conceived, you indeed speak without 
grasping.'

_Vinicchayā yāni pakappitāni te ve munī brūsi anuggahāya._
____

Comment:

_Vinicchayā_ is obviously a synonym of _dhammesu niccheyya samuggahītaṃ_.

.Illustration
====
vinicchayā

dogmatic opinions; vinicchayaṃ, dogmatic opinions
====

[quote, Sn.v.866]
____
From where do dogmatic opinions come from, anger, lies, uncertainty [about the 
significance of the teaching], and other such things spoken of by the Ascetic?

_vinicchayā cā pi kutopahūtā +
Kodho mosavajjañca kathaṅkathā ca ye vāpi dhammā samaṇena vuttā._
____

[quote, Sn.v.867]
____
A person develops dogmatic opinions from seeing the cessation and continuance 
of bodily forms in the world.

_Rūpesu disvā vibhavaṃ bhavañca vinicchayaṃ kubbati jantu loke._
____

.Illustration
====
vinicchitāni

divided
====

[quote, A.4.140-1; Vin.1.65]
____
Both Pātimokkhas have been properly transmitted to him in detail, properly 
classified, well mastered, properly divided by rule and phrase.

_ubhayāni kho panassa pātimokkhāni vitthārena svāgatāni honti 
suvibhattāni suppavattīni suvinicchitāni suttaso anuvyañjanaso._
____

.Illustration
====
vinicchiyamāne

investigating
====

[quote, Vin.2.95]
____
While bhikkhus are investigating that legal matter endless brawls arise.

_Tehi ce bhikkhave tasmiṃ adhikaraṇe vinicchiyamāne anaggāni ceva 
bhassāni jāyanti._
____

.Illustration
====
vinicchinitvā

investigate
====

____
If the community of bhikkhus, not having investigated that case, not having got 
to the root of it, achieves unanimity, that unanimity is unrighteous.

_saṅgho taṃ vatthuṃ avinicchinitvā amūlā mūlaṃ gantvā 
saṅghasāmaggiṃ karoti adhammikā sā upāli saṅghasāmaggī ti_
____

[quote, Vin.1.358]
____
If the community of bhikkhus, having investigated the case, having got to the 
root of it, achieves unanimity in the community of bhikkhus, that unanimity is 
righteous

_saṅgho taṃ vatthuṃ vinicchinitvā mūlā mūlaṃ gantvā 
saṅghasāmaggiṃ karoti, dhammikā sā upāli saṅghasāmaggī ti._
____

.Illustration
====
vinicchinī

investigates
====

[quote, Th.v.551]
____
Wisdom investigates what is heard _

_Paññā sutavinicchinī._
____

