== Virajjati; Viratta; Virājetvā

=== Renderings

- _virajjati_: to be unattached

- _virajjati_: to be unattached [to originated phenomena]

- _virajjati_: to be disgusted

- _virajjati_: to be filled with disgust

- _viratta_: unattached

- _viratta_: disgusted

- _virājetvā_: having detached

- _virājetvā_: having discarded

=== Introduction

==== Virajjati: to be unattached [to originated phenomena]

Often _virajjati_ has an object:

[quote, A.3.347]
____
The Buddha is unattached to the world.

_buddho loke virajjati._
____

Where it does not have an object we parenthesise 'to originated phenomena':

[quote, M.3.20]
____
Being disillusioned [with originated phenomena], he is unattached [to 
originated phenomena]. Being unattached [to originated phenomena], he is 
liberated [from perceptually obscuring states].

_nibbindaṃ virajjati virāgā vimuccati._
____

This is accordance with our parenthesis of _Nibbidā_. See Glossary sv 
_Nibbidā_. It is also in accordance with other similar quotes:

[quote, S.2.191]
____
It is time enough, bhikkhus, to be disillusioned with all originated phenomena, 
to be unattached to them, to be liberated from them.

_Yāvañcidaṃ bhikkhave alameva sabbasaṅkhāresu nibbindituṃ alaṃ 
virajjituṃ alaṃ vimuccituṃ._
____

=== Illustrations: virajjati

.Illustration
====
virajjati

unattached
====

[quote, S.1.112]
____
Seeing 'I am not this, this is not mine,' thus is one unattached in that 
respect.

_N'eso'hamasmi n'etaṃ me evaṃ tattha virajjati._
____

.Illustration
====
virajjati

disgusted
====

[quote, Sn.v.813]
____
He does not think he is spiritually purified by that means, namely [through 
further attachment to] what is seen, heard, sensed, [or cognised], nor does he 
want to be spiritually purified by means of further [attachment]. He is neither 
attached [to these things] nor disgusted [by them].

_Dhono na hi tena maññati yadidaṃ diṭṭhasutaṃ mutesu vā +
Nāññena visuddhimicchati na hi so rajjati no virajjatī ti._
____

Comment:

'He is neither attached [to these things] nor disgusted [by them].' This 
continues a theme of Sn.v.811:

[quote, Sn.v.811]
____
He does not hold anything as either beloved or unbeloved.

_na piyaṃ kubbati no pi appiyaṃ._
____

.Illustration
====
virajjati

filled with disgust
====

[quote, Sn.v.853]
____
Not infatuated with objects of pleasure, not given to arrogance, gentle, 
intuitively insightful, not credulous, not filled with disgust;

_Sātiyesu anassāvī atimāne ca no yuto +
Saṇho ca paṭibhānavā na saddho na virajjati._
____

=== Illustrations: viratta

.Illustration
====
viratta

unattached
====

____
In seeing a visible object with mindfulness muddled, focusing on the agreeable 
aspect, one experiences it with a mind of attachment and persists in cleaving 
to it.

_Rūpaṃ disvā sati muṭṭhā piyaṃ nimittaṃ manasikaroto +
Sārattacitto vedeti tañca ajjhosa tiṭṭhati._
____

But

[quote, S.4.73-6]
____
On seeing a visible object, one who is mindful is not attached to visible 
objects. He experiences it with an unattached attitude and does not persist in 
cleaving to it.

_Na so rajjati rūpesu rūpaṃ disvā patissato +
Virattacitto vedeti tañca nājjhosa tiṭṭhati._
____

.Illustration
====
virattaṃ

unattached
====

[quote, Ud.41]
____
Who is unattached to things that are charming

_virattaṃ rajaniyesu._
____

.Illustration
====
virattaṃ

unattached
====

[quote, S.3.45]
____
If a bhikkhu's mind is unattached to bodily form... advertence, it is liberated 
from perceptually obscuring states through being without grasping.

_Rūpadhātuyā... viññāṇadhātuyā ce bhikkhave bhikkhuno cittaṃ 
virattaṃ vimuttaṃ hoti anupādāya āsavehi._
____

.Illustration
====
viratta

unattached
====

[quote, Sn.v.235]
____
Those whose minds are unattached to future individual existence.

_Virattacittā āyatike bhavasmiṃ._
____

.Illustration
====
viratta

disgusted
====

Now at that time Nathaputta the Nigaṇṭha had just died at Pāvā. And at 
his death the Nigaṇṭhas divided into two parties, in mutual strife and 
conflict, quarrelling and wounding each other with their speech...

[quote, D.3.118]
____
Even the white-robed lay disciples were shocked, disgusted, and indignant at 
the Nigaṇṭhas.

_ye pi nigaṇṭhassa nātaputtassa sāvakā gihī odātavasanā te tesu 
nigaṇṭhesu nātaputtiyesu nibbinnarūpā virattarūpā paṭivānarūpā._
____

.Illustration
====
viratta

disgusted
====

____
Who, I wonder, has set me at odds with this family?_

_kosudāni maṃ imasmiṃ kule paribhindi_
____

[quote, A.4.87]
____
These men seem disgusted by me

_virattarūpā'dāni me manussāti._
____

.Illustration
====
viratta

disgusted
====

[quote, Vin.2.16]
____
This householder Citta is now full of hatred. He has no regard for me. He is 
disgusted by me.

_duṭṭho'dānāyaṃ citto gahapati anapekkho virattarūpo mayī ti._
____

=== Illustrations: virājetvā

.Illustration
====
virājetvā

having detached
====

[quote, A.2.196]
____
Having detached his mind from things that are charming

_so rajanīyesu dhammesu cittaṃ virājetvā._
____

.Illustration
====
virājetvā

having discarded
====

• Five varieties of sensuous pleasure are taught in the world, with [sensuous 
pleasure of] the mind as sixth. Having discarded hankering for these, [the 
world of beings] is released from suffering. +
_Pañcakāmaguṇā loke manochaṭṭhā paveditā +
Ettha chandaṃ virājetvā evaṃ dukkhā pamuccati_ Sn.v.171).

.Illustration
====
virājetvā

having discarded
====

[quote, Thī.v.14]
____
Having discarded fondness for individual existence you will live the religious 
life inwardly at peace.

_Bhave chandaṃ virājetvā upasantā carissasī ti._
____

.Illustration
====
virājetvā

having discarded
====

[quote, Sn.v.139]
____
Having discarded attachment to sensuous pleasure he reached the brahmā world.

_Kāmarāgaṃ virājetvā brahmalokūpago ahu._
____

.Illustration
====
virājetvā

having discarded
====

[quote, D.2.51]
____
Having discarded sensuous hankering for sensuous pleasures.

_kāmesu kāmacchandaṃ virājetvā idhūpapannā ti._
____

