== Viriya

=== Renderings

- _viriya_: energy

- _viriya_: effort

- _āraddhaviriyo_: energetic

- _āraddhaviriyo_: energetically

- _āraddhaviriyo_: energetically applied [to the practice]

- _āraddhaviriyo_: energetic person

- _viriyaṃ ārabhituṃ_: to be energetically applied [to the practice]

- _viriyaṃ ārabhati_: to apply energy

- _viriyindriya_: faculty of energetic application [to the practice]

- _viriyasambojjhaṅga_: enlightenment factor of energetic application [to the 
practice]

=== Introduction

==== Āraddhaviriyo: energetically applied

_Āraddhaviriyo_ means being somehow energetically applied, for example to the 
supreme goal:

[quote, Sn.v.68]
____
One who is energetically applied to the attainment of the supreme goal.

_Āraddhaviriyo paramatthapattiyā._
____

Where _āraddhaviriyo_ occurs without qualification, we qualify it with 'to the 
practice' in accordance with this definition:

____
"One who is energetically applied [to the practice], one who is energetically 
applied [to the practice]" is said. On what grounds is one energetically 
applied [to the practice]?

__āraddhaviriyo āraddhaviriyo ti bhante vuccati. Kittāvatā nu kho bhante 
āraddhaviriyo hotī ti?_
____

____
... 'In this regard, Moggallāna, a bhikkhu abides energetically thus: 
"Willingly, let only skin, sinews, and bones remain, and let the flesh and 
blood dry up in my body, but I will not relax my energy so long as I have not 
attained what can be attained by manly strength, by manly energy, by manly 
application [to the practice].

_idha moggallāna bhikkhu āraddhaviriyo viharati kāmaṃ taco ca nahārū ca 
aṭṭhī ca avasissatu sarīre upasussatu maṃsalohitaṃ yaṃ taṃ 
purisathāmena purisaviriyena purisaparakkamena pattabbaṃ na taṃ 
apāpuṇitvā viriyassa saṇṭhānaṃ bhavissatī ti._
____

[quote, S.2.276]
____
... In this way is one energetically applied [to the practice].

_Evaṃ kho moggallāna āraddhaviriyo hotī ti._
____

For the rendering 'application [to the practice]' for _parakkama_, see Glossary 
sv _Parakkama_.

==== Viriyasambojjhaṅga: the enlightenment factor of energetic application 
&#8203;[to the practice]

That _viriyasambojjhaṅga_ means 'the enlightenment factor of energetic 
application [to the practice]' can be judged from the following two quotes:

1. "While he scrutinises the teaching with penetrative discernment, examines 
it, inquires into it, unflagging energy is aroused. Whenever a bhikkhu's 
unflagging energy is aroused as he scrutinises the teaching with penetrative 
discernment, examines it, inquires into it, on that occasion the enlightenment 
factor of energetic application [to the practice] is aroused in the bhikkhu; on 
that occasion the bhikkhu develops the enlightenment factor of energetic 
application [to the practice]; on that occasion the enlightenment factor of 
energetic application [to the practice] is perfected through spiritual 
cultivation in the bhikkhu.
+
****
_Yasmiṃ samaye ānanda bhikkhuno taṃ dhammaṃ paññāya pavicanato 
pavicarato parivīmaṃsamāpajjato āraddhaṃ hoti viriyaṃ asallīnaṃ 
viriyasambojjhaṅgo tasmiṃ samaye bhikkhuno āraddho hoti. 
Viriyasambojjhaṅgaṃ tasmiṃ samaye bhikkhu bhāveti. Viriyasambojjhaṅgo 
tasmiṃ samaye bhikkhuno bhāvanāpāripūriṃ gacchati. Āraddhaviriyassa 
uppajjati pīti nirāmisā_ (S.5.332).
****

2. On an occasion when the mind becomes sluggish, it is timely to develop... 
the enlightenment factor of energetic application [to the practice]... For what 
reason? Because the mind is sluggish.
+
****
_Yasmiñca kho bhikkhave samaye līnaṃ cittaṃ hoti kālo tasmiṃ samaye... 
viriyasambojjhaṅgassa bhāvanāya... Taṃ kissa hetu: līnaṃ bhikkhave 
cittaṃ._ (S.5.113).
****

==== Viriyindriya: faculty of energetic application [to the practice]

That _viriyindriya_ means 'the faculty of energetic application [to the 
practice]' can be judged from this quote:

[quote, S.5.225]
____
It is indeed to be expected, bhante, that a noble disciple who has faith [in 
the perfection of the Perfect One's transcendent insight] will dwell 
energetically applied to the abandoning of spiritually unwholesome factors and 
the undertaking of spiritually wholesome factors; that he will be steadfast, 
unwavering in application [to the practice], not shirking the responsibility of 
&#8203;[undertaking] spiritually wholesome factors. That energy, bhante, is his 
faculty of energetic application [to the practice].

_saddhassa hi bhante ariyasāvakassa etaṃ pāṭikaṅkhaṃ: yaṃ 
āraddhaviriyo viharissati akusalānaṃ dhammānaṃ pahānāya kusalānaṃ 
dhammānaṃ upasampadāya thāmavā daḷhaparakkamo anikkhittadhuro kusalesu 
dhammesu. Yaṃ hissa bhante viriyaṃ tadassa viriyindriyaṃ._
____

==== Viriyabalaṃ: the power of energetic application [to the practice]

That _viriyabalaṃ_ means 'the power of energetic application [to the 
practice]' can be judged from this quote:

[quote, A.3.2]
____
And what is the power of energetic application [to the practice]. In this 
regard, a noble disciple abides energetically applied to the abandoning of 
spiritually unwholesome factors and the undertaking of spiritually wholesome 
factors, steadfast, unwavering in application [to the practice], not shirking 
the responsibility of [undertaking] spiritually wholesome factors.

_Katamañca bhikkhave viriyabalaṃ idha bhikkhave ariyasāvako āraddhaviriyo 
viharati akusalānaṃ dhammānaṃ pahānāya kusalānaṃ dhammānaṃ 
upasampadāya thāmavā daḷha parakkamo anikkhittadhuro kusalesu dhammesu. 
Idaṃ vuccati bhikkhave viriyabalaṃ._
____

==== Viriyaṃ ārabhituṃ: to be energetically applied [to the practice]

That _viriyaṃ ārabhituṃ_ means 'to be energetically applied [to the 
practice]' can be judged from this quote:

____
When the teaching has thus been well explained by me, elucidated, disclosed, 
revealed, free of patchwork, it is indeed fitting for a noble young man who has 
gone forth [into the ascetic life] out of faith to be energetically applied [to 
the practice] thus:

_Evaṃ svākkhāte kho bhikkhave mayā dhamme uttāne vivaṭe pakāsite 
chinnapilotike alameva saddhā pabbajitena kulaputtena viriyaṃ ārabhituṃ:_
____

[quote, S.2.28]
____
... 'Willingly, let only skin, sinews, and bones remain, and let the flesh and 
blood dry up in my body, but I will not relax my energy so long as I have not 
attained what can be attained by manly strength, by manly energy, by manly 
application [to the practice].'

_kāmaṃ taco ca nahāru ca aṭṭhi ca avasissatu sarīre upasussatu 
maṃsalohitaṃ yaṃ taṃ purisatthāmena purisaviriyena purisaparakkamena 
pattabbaṃ na taṃ apāpuṇitvā viriyassa saṇṭhānaṃ bhavissati._
____

=== Illustrations

.Illustration
====
viriya

effort
====

• "Did you earlier have the effort, 'I will go to the monastery,' and after 
you arrived at the monastery, was the corresponding effort quelled?" "Yes, 
sir." +
_Ahosi te pubbe viriyaṃ ārāmaṃ gamissāmī ti tassa te ārāmagatassa 
yaṃ tajjaṃ viriyaṃ taṃ paṭippassaddhanti evaṃ bho_ (S.5.273).

.Illustration
====
viriya

energy
====

[quote, It.114]
____
'Struggling with hands and feet' represents the exertion of energy.

_satthehi ca pādehi ca vāyāmo ti kho bhikkhave viriyārambhassetaṃ 
adhivacanaṃ._
____

.Illustration
====
viriya

&#8203;[application of] energy; viriyasambojjhaṅgo, the enlightenment factor of 
energetic application [to the practice]
====

[quote, S.5.111]
____
Whatever [application of] bodily energy there is, is the enlightenment factor 
of energetic application [to the practice]; whatever [application of] mental 
energy there is, is also the enlightenment factor of energetic application [to 
the practice]. Thus what is concisely called the enlightenment factor of 
energetic application [to the practice] becomes twofold by this method of 
exposition.

_Yadapi bhikkhave kāyikaṃ viriyaṃ tadapi viriyasambojjhaṅgo. Yadapi 
cetasikaṃ viriyaṃ tadapi viriyasambojjhaṅgā. Viriyasambojjhaṅgoti 
itihidaṃ uddesaṃ gacchati. Tadamināpetaṃ pariyāyena dvayaṃ hoti._
____

.Illustration
====
viriyaṃ

energy
====

[quote, A.3.376]
____
If one's energy is excessive it leads to restlessness; if too lax it leads to 
indolence. Therefore Soṇa, resolve [to apply yourself] moderately 
energetically, and achieve a balance in the faculties, and in this manner pick 
up the object of meditation.

_Evameva kho soṇa accāraddhaṃ viriyaṃ uddhaccāya saṃvattati 
atilīnaṃ viriyaṃ kosajjāya saṃvattati. Tasmātiha tvaṃ soṇa 
viriyasamataṃ adhiṭṭhahaṃ indriyānañca samataṃ paṭivijjha tattha 
ca nimittaṃ gaṇhāhī ti._
____

.Illustration
====
viriyaṃ

energy
====

[quote, S.5.67-69]
____
While he scrutinises the teaching with penetrative discernment, examines it, 
inquires into it, unflagging energy is aroused.

_Tassa taṃ dhammaṃ paññāya pavicinato pavicarato 
parivīmaṃsamāpajjato āraddhaṃ hoti viriyaṃ asallīnaṃ._
____

.Illustration
====
āraddhaviriyassa

energetically applied [to the practice]
====

[quote, S.5.225]
____
A noble disciple who has faith [in the perfection of the Perfect One's 
transcendent insight], who is energetically applied [to the practice], and 
whose mindfulness is established, having made the relinquishment [of 
attachment] the basis [for spiritual development], will gain inward 
collectedness, will gain mental concentration.

_saddhassa hi bhante ariyasāvakassa āraddhaviriyassa upaṭṭhitasatino 
etaṃ pāṭikaṅkhaṃ yaṃ vossaggārammaṇaṃ karitvā labhissati 
samādhiṃ labhissati cittassekaggataṃ._
____

.Illustration
====
āraddhaviriyo

energetic person
====

____
Bhikkhus, the lazy person abides in misery, soiled by unvirtuous, spiritually 
unwholesome factors, and great is the personal good that he neglects.

_dukkhaṃ hi bhikkhave kusīto viharati vokiṇṇo pāpakehi akusalehi 
dhammehi. Mahantañca sadatthaṃ parihāpeti._
____

[quote, S.2.29]
____
But the energetic person abides happily, secluded from unvirtuous, spiritually 
unwholesome factors, and great is the personal good that he achieves.

_Āraddhaviriyo ca kho bhikkhave sukhaṃ viharati pavivitto pāpakehi 
akusalehi dhammehi mahantañca sadatthaṃ paripūreti._
____

.Illustration
====
āraddhaviriyo

being energetic
====

[quote, A.5.92-3]
____
Am I much given to laziness? Or am I much given to being energetic?_

_kusīto nu kho bahulaṃ viharāmi āraddhaviriyo nu kho bahulaṃ viharāmi._
____

.Illustration
====
viriyaṃ ārabhati

to apply energy
====

[quote, M.1.25]
____
It can be expected that he will not stir up eagerness, endeavour, apply energy, 
to abandon that blemish.

_tasse taṃ pāṭikaṅkhaṃ na chandaṃ janessati na vāyamissati na 
viriyaṃ ārabhissati tassaṅgaṇassa pahānāya._
____

