== Viruddha; Virodha

=== Renderings

- _viruddha_: hostile

- _viruddha_: repelled

- _virodha_: rejecting

- _virodha_: dislike

- _virodha_: hostility

- _anurodha_: welcoming

- _anuruddha_: attracted

=== Illustrations: Viruddha

.Illustration
====
anuruddho

attracted; viruddha, repelled
====

[quote, S.4.71]
____
Maintain detached awareness towards physical sensation, both pleasant and 
painful, not attracted or repelled by anything.

_Phassadvayaṃ sukhadukkhe upekkhe +
Anānuruddho aviruddha kenaci._
____

.Illustration
====
aviruddho

not repelled by
====

[quote, Sn.v.854]
____
One not training himself in the hope of material gain, who is unshaken if he 
gets nothing, who is not repelled by flavours, nor greedy with craving for them;

_Lābhakamyā na sikkhati alābhe ca na kuppati +
Aviruddho ca taṇhāya rasesu nānugijjhati._
____

.Illustration
====
aviruddhaṃ

unhostile
====

[quote, Sn.v.630]
____
One who is unhostile amidst the hostile, inwardly at peace amidst the violent, 
free of grasping amidst the grasping, he is what I call a Brahman.

_Aviruddhaṃ viruddhesu attadaṇḍesu nibbutaṃ +
Sādānesu anādānaṃ tamahaṃ brūmi brāhmaṇaṃ._
____

.Illustration
====
aviruddho

not hostile
====

[quote, Sn.v.704]
____
Having abandoned sensuous pleasures completely, he is one who abstains from 
sexual intercourse. He is neither hostile towards nor attached to living 
beings, whether timid or mettlesome.

_Virato methunā dhammā hitvā kāme parovare +
Aviruddho asāratto pāṇesu tasathāvare._
____

.Illustration
====
aviruddho

free of hostility
====

[quote, Sn.v.365]
____
Being free of hostility by way of speech, mind, and body, having properly 
understood the teaching, and longing for the Untroubled State, he would 
properly fulfil the ideals of religious asceticism in the world.

_Vacasā manasā ca kammunā ca aviruddho sammā viditvā dhammaṃ +
Nibbānapadābhipatthayāno sammā so loke paribbajeyya._
____

=== Illustrations: Virodha

.Illustration
====
anurodha

welcoming; virodhaṃ, rejecting
====

• In seeing a visible object via the visual sense a bhikkhu is attached to an 
agreeable visible object and troubled by a disagreeable visible object. He 
abides without mindfulness of the body established, with a small mind, and he 
does not discern according to reality, with the liberation [from attachment 
through inward calm] and the liberation [from uninsightfulness] through 
penetrative discernment, where those unvirtuous, spiritually unwholesome 
factors cease without remainder. +
_So cakkhunā rūpaṃ disvā piyarūpe rūpe sārajjati appiyarūpe rūpe 
vyāpajjati. Anupaṭṭhitakāyasati ca viharati paritta cetaso tañca 
cetovimuttiṃ paññāvimuttiṃ yathābhūtaṃ nappajānāti yatthassa te 
pāpakā akusalā dhammā aparisesā nirujjhanti._

• Engaged as he is in welcoming and rejecting, whatever sense impression he 
experiences -- whether pleasant, unpleasant, or neutral -- he takes delight in 
it, welcomes it, and persists in cleaving to it. In so doing, spiritually 
fettering delight arises. Spiritually fettering delight in sense impression is 
grasping +
_So evaṃ anurodhavirodhaṃ samāpanno yaṃ kiñci vedanaṃ vedeti sukhaṃ 
vā dukkhaṃ vā adukkhamasukhaṃ vā so taṃ vedanaṃ abhinandati 
abhivadati ajjhosāya tiṭṭhati tassa taṃ vedanaṃ abhinandato abhivadato 
ajjhosāya tiṭṭhato uppajjati nandī. Yā vedanāsu nandī tadupadānaṃ_ 
(M.1.266).

.Illustration
====
anurodha

welcoming; virodha, rejecting
====

____
He welcomes the arisen acquisition and rejects the arisen loss. He welcomes the 
arisen prestige and rejects the arisen imprestige. He welcomes the arisen 
praise and rejects the arisen criticism. He welcomes the arisen pleasure and 
rejects the arisen pain.

_Uppannaṃ yasaṃ anurujjhati ayase paṭivirujjhati uppannaṃ pasaṃsaṃ 
anurujjhati nindāya paṭivirujjhati. Uppannaṃ sukhaṃ anurujjhati. Dukkhe 
paṭivirujjhati_
____

[quote, A.4.158]
____
As he is thus engaged in welcoming and rejecting, he is not freed from birth, 
old age, or death; from grief, lamentation, physical pain, psychological pain, 
or despair. He is not freed, I declare, from suffering.

_So evaṃ anurodhavirodhasamāpanno na parimuccati jātiyā jarāya maraṇena 
sokehi paridevehi dukkhehi domanassehi upāyāsehi na parimuccati dukkhasmāti 
vadāmi._
____

.Illustration
====
virodha

dislike
====

[quote, S.4.71]
____
Whether enjoying a sweet delicious tasteable object, or sometimes tasting what 
is unpalatable, eat the sweet tasteable object without cleaving, and do not 
show dislike for the unpalatable.

_Rasañca bhotvā sāditañca sāduṃ athopi bhotvāna asādumekadā +
Sāduṃ rasaṃ nājjhosāya bhuñje virodhamāsādusu nopadaṃsaye._
____

.Illustration
====
avirodha

non-hostility
====

[quote, M.2.105]
____
May my enemies indeed from time to time listen to the teaching of those who 
preach patience and who praise non-hostility, and may they act in conformity 
with it.

_Disā hi me khantivādānaṃ avirodhappasaṃsinaṃ +
Suṇantu dhammaṃ kālena tañca anuvidhīyantu._
____

