== Vivaṭṭacchadda

=== Renderings

- _vivaṭṭacchadda_: completely renounced the round of rebirth

=== Introduction

==== Analysis: context better than etymology

_Vivaṭṭacchaddo_ has long been a subject of debate. Because even its 
spelling is unsettled, resolving its meaning must be primarily based on 
context, not etymology. Extensive notes that demonstrate the longstanding 
interest in this term can be found at:

- PED: under _Vivattacchada_

- Norman: Group of Discourses p.229 n.372

- Bodhi: NDB n.713.

- Bodhi: MLDB n.853

==== 'Removed the covering': neologism

Many commentaries say _vivaṭṭacchadda_ means 'one who has removed the 
covering,' as follows:

[quote, Sv.1.250; tr. Bodhi, NDB, n.713]
____
Here, having been born into the world, he dwells having entirely removed the 
covering in the world (_loke tam chadanam vivattetva_), in the darkness of 
defilements covered by seven coverings (_chadanehi_): lust, hatred, delusion, 
conceit, views, ignorance, and misconduct.

_Arahaṃ hoti sammāsambuddho loke vivaṭṭacchadoti ettha 
rāga-dosa-moha-māna-diṭṭhi-avijjā-duccaritachadanehi sattahi 
paṭicchanne kilesandhakāre loke taṃ chadanaṃ vivaṭṭetvā samantato 
sañjātāloko hutvā ṭhitoti vivaṭṭacchado._
____

But, although _taṇhā_ is called a covering (_taṇhāchadanachāditā_, 
Ud.76), these seven factors are not. And although _avijjā_ comes close by 
being called an eggshell, it is 'broken through' not 'removed.'

[quote, A.4.176; Vin.3.3]
____
Amongst the manyfolk who are void of insight into reality, enveloped and 
smothered [in uninsightfulness into reality], having broken through the 
eggshell of uninsightfulness into reality (_avijjaṇḍakosaṃ padāletvā_), 
I alone in the world have fully awakened to unsurpassed, complete enlightenment.

_Evameva kho ahaṃ brāhmaṇa avijjāgatāya pajāya aṇḍabhūtāya 
pariyonaddhāya avijjaṇḍakosaṃ padāletvā eko'va loke anuttaraṃ 
sammāsambodhiṃ abhisambuddho._
____

Nonetheless, Bodhi accepts the commentary's explanation, and translates 
_vivaṭṭacchadda_ as 'those who have removed the coverings,' and explains 
his decision as follows:

- Though various conjectures might be proposed with respect to the original 
expression and its meaning, given the difficulty of settling these questions 
across Buddhist textual traditions, the most expedient course open to me is to 
translate the term as it has been preserved and interpreted in the Pāli 
tradition (NDB n.713).

'Remove the coverings' would certainly fit the context, but to avoid its absurd 
connotations it would be better parenthesised to: 'remove the coverings [of 
lust, hatred, delusion, conceit, views, ignorance, and misconduct],' or, more 
justifiably, 'remove the covering [of _avijjā_].'

==== 'With deceit removed': unfitting

Norman uses the spelling _vivattacchadda_ and calls it 'with deceit removed,' 
because in Sanskrit, according to Monier Williams, _chadman_ has the meaning 
'deceit, disguise.' But this rendering does not fit the contexts.

==== Our interpretation

_Vivaṭṭacchaddo_ is primarily found in poetry, and we regard _vi_- as an 
unwarranted prefix, but in accordance with Warder's comments, who says:

- The verses of the Dīgha Nikāya illustrate their most important linguistic 
and metrical characteristics. The linguistic features to remark are twofold: 
poetic licence and the use of archaic forms obsolete in everyday speech... 
Poetic licence is most noticeable in the freedom of word order in verse. Since 
the inflections generally show the relations between words in a sentence, 
almost any deviation from the prose order is possible without serious change of 
meaning... A prefix may be dropped or added where the meaning of the sentence 
will tolerate a slight change of nuance (Warder, Introduction to Pāli p.354-5).

Because prefixes are subject to poetic licence, we therefore regard 
_vivaṭṭacchaddo_ as standing for _vaṭṭa chaḍḍo_, with _vi_- for 
emphasis. Comments in the PED show that we are not the first to explain 
_chadda_ as _chaḍḍa_: the commentaries have done likewise. But the real 
strength of our argument lies in the fittingness of our rendering, which we 
parade in the Illustrations below.

==== Meaning of chaḍḍeti

_Chaḍḍeti_ means 'throw' or 'pour,' and _vicchaḍḍeti_ means 'scatter 
about':

[quote, M.2.138]
____
He discards the bowl water neither too far nor too close, and he does not 
scatter it about.

_So pattodakaṃ chaḍḍeti nātidūre nāccāsanne na ca 
vicchaḍḍayamāno._
____

In later Pāli, _vicchaḍḍeti_ meant to throw out, to vomit, says PED.

==== Chinnaṃ vaṭṭaṃ

If _vivaṭṭacchadda_ means 'completely renounced the round of rebirth,' then 
it is comparable to _chinnaṃ vaṭṭaṃ_, 'the round of rebirth destroyed' 
in this passage:

[quote, Ud.__7__5]
____
He has destroyed the round of rebirth, abandoned longing. The dried-up stream 
no longer flows. The round of rebirth, destroyed, no longer continues. This is 
truly the end of suffering.

_Acchecchi vaṭṭaṃ byagā nirāsaṃ vusukkhā saritā na sandati. 
Chinnaṃ vaṭṭaṃ na vattati esevanto dukkhassā ti._
____

=== Illustrations

.Illustration
====
vivaṭṭacchaddo

completely renounced the round of rebirth
====

[quote, Sn.v.372]
____
One who is spiritually purified, who has conquered [all unvirtuous, spiritually 
unwholesome factors], who has completely renounced the round of rebirth, who 
has mastery over mentally known objects, who has reached the Far Shore, who is 
imperturbable, and is proficient in the knowledge of the ending [of originated 
phenomena] [according to reality]: he would properly fulfil the ideals of 
religious asceticism in the world.

_Saṃsuddhajino vivaṭṭacchaddo dhammesu vasī pāragū anejo +
Saṅkhāranirodhañāṇakusalo sammā so loke paribbajeyya._
____

.Illustration
====
vivaṭṭacchaddo

one who has completely renounced the round of rebirth
====

[quote, D.1.89]
____
But if he goes forth from the household life into the ascetic life he will 
become the Arahant, the Perfectly Enlightened One in the world, one who has 
completely renounced the round of rebirth.

_Sace kho pana agārasmā anagāriyaṃ pabbajati arahaṃ hoti sammāsambuddho 
loke vivaṭṭacchaddo._
____

Comment: Here _vivaṭṭacchaddo_ occurs in prose.

.Illustration
====
vivaṭṭacchaddo

one who has completely renounced the round of rebirth
====

[quote, D.3.179]
____
But if he goes forth [from the household life into the ascetic life] he will be 
free of unvirtuousness, an ascetic with spiritual defilement quelled, one who 
has completely renounced the round of rebirth.

_Atha ce pabbajati bhavati vipāpo +
Samaṇo samitarajo vivaṭṭacchaddo._
____

.Illustration
====
vivaṭṭacchaddo

completely renounced the round of rebirth
====

[quote, A.2.44]
____
They in the world who have completely renounced the round of rebirth.

_vivaṭṭacchaddā ye loke._
____

