== Viveka

=== Renderings

- _viveka_: seclusion [from sensuous pleasures and spiritually unwholesome 
factors]

- _viveka_: physical seclusion (=__paviveka__, metri causa)

=== Introduction

==== Parenthesis: seclusion [from sensuous pleasures and spiritually 
unwholesome factors]

_Viveka_ usually has no designated object. Our parenthesis comes from this 
quote:

[quote, M.1.301]
____
Secluded from sensuous pleasures and spiritually unwholesome factors, a bhikkhu 
enters and abides in first jhāna, which is accompanied by thinking and 
pondering, and rapture and physical pleasure born of seclusion [from sensuous 
pleasures and spiritually unwholesome factors].

_Idhāvuso visākha bhikkhu vivicceva kāmehi vivicca akusalehi dhammehi 
savitakkaṃ savicāraṃ vivekajaṃ pītisukhaṃ paṭhamaṃ jhānaṃ 
upasampajja viharati._
____

Because _vivekajaṃ_ corresponds to _vivicceva kāmehi vivicca akusalehi 
dhammehi_, therefore _viveka_ = seclusion [from sensuous pleasures and 
spiritually unwholesome factors].

==== Viveka = vavakaṭṭha & nekkhamma

Our renderings for _vavakaṭṭha_ and _nekkhamma_ are:

- _Vavakaṭṭha_: 'withdrawn [from sensuous pleasures and spiritually 
unwholesome factors].' See Glossary sv _Vavakaṭṭha_.

- _Nekkhamma_: 'the practice of unsensuousness.' See Glossary sv _Nekkhamma_.

In the following quote _vivekaninnaṃ cittaṃ hoti_ equals 
_vavakaṭṭhaṃ_ plus _nekkhammābhirataṃ_:

[quote, A.4.224]
____
His mind inclines, verges, and drifts towards seclusion [from sensuous 
pleasures and spiritually unwholesome factors]. It is withdrawn [from sensuous 
pleasures and spiritually unwholesome factors], taking delight in the practice 
of unsensuousness.

_vivekaninnaṃ cittaṃ hoti vivekapoṇaṃ vivekapabbhāraṃ 
vavakaṭṭhaṃ nekkhammābhirataṃ._
____

Therefore, again, _viveka_ = 'seclusion [from sensuous pleasures and 
spiritually unwholesome factors].'

==== Viveka means physical seclusion, metri causa

_Paviveka_ not _viveka_ means physical seclusion. Only in verse does _viveka_ 
mean physical seclusion, metri causa. See Glossary sv _Paviveka_.

=== Illustrations

.Illustration
====
vivekā

seclusion [from sensuous pleasures and spiritually unwholesome factors]
====

[quote, Sn.v.772]
____
Abiding attached within the inner recesses of the heart, covered in defilement 
and steeped in confusion, such a being is far from seclusion [from sensuous 
pleasures and spiritually unwholesome factors]. Abandoning the pleasures of the 
world is truly difficult.

_Satto guhāyaṃ bahunābhicchanno tiṭṭhaṃ naro mohanasmiṃ pagāḷho; 
+
Dūre vivekā hi tathāvidho so kāmā hi loke na hi suppahāyā._
____

.Illustration
====
viveka

seclusion [from sensuous pleasures and spiritually unwholesome factors]
====

[quote, Sn.v.851]
____
A person who is not attached to the future, who does not grieve over the past, 
who finds seclusion [from sensuous pleasures and spiritually unwholesome 
factors] amidst sensation, and is not led into dogmatic views;

_Nirāsatti anāgate atītaṃ nānusocati +
Vivekadassī phassesu diṭṭhīsu ca na nīyati._
____

.Illustration
====
vivekaṃ

seclusion [from sensuous pleasures and spiritually unwholesome factors]
====

[quote, Sn.v.915]
____
I ask the enlightened kinsman of the Sun clan, the great Seer, about seclusion 
&#8203;[from sensuous pleasures and spiritually unwholesome factors] and about the 
Peaceful State. Seeing in what way is a bhikkhu freed from passion, grasping 
nothing in the world?

_Pucchāmi taṃ ādiccabandhu vivekaṃ santipadañca mahesi; +
Kathaṃ disvā nibbāti bhikkhu anupādiyāno lokasmiṃ kiñci._
____

.Illustration
====
viveka

seclusion [from sensuous pleasures and spiritually unwholesome factors]
====

____
For a long time his mind has inclined, verged and drifted towards seclusion 
&#8203;[from sensuous pleasures and spiritually unwholesome factors].

_yaṃ hi taṃ bhikkhave cittaṃ dīgharattaṃ vivekaninnaṃ 
vivekapoṇaṃ vivekapabbhāraṃ._
____

[quote, S.5.53]
____
Thus there is no possibility that he will return to lay life.

_Taṃ vata hīnāyāvattissatīti netaṃ ṭhānaṃ vijjati._
____

.Illustration
====
viveka

seclusion [from sensuous pleasures and spiritually unwholesome factors]
====

[quote, M.1.302]
____
When a bhikkhu has emerged from the attainment of the ending of perception and 
sense impression his mind inclines, verges, and drifts towards seclusion [from 
sensuous pleasures and spiritually unwholesome factors].

_Saññāvedayitanirodhasamāpattiyā vuṭṭhitassa kho āvuso visākha 
bhikkhuno vivekaninnaṃ cittaṃ hoti vivekapoṇaṃ vivekapabbhāranti._
____

.Illustration
====
viveka

seclusion [from sensuous pleasures and spiritually unwholesome factors]
====

____
A certain bhikkhu had gone for his daytime abiding, but kept thinking 
unvirtuous, spiritually unwholesome thoughts associated with the household life.

_pāpake akusale vitakke vitakketi gehanissite_
____

Then the deva inhabiting that woodland grove, being tenderly concerned for that 
bhikkhu, desiring his spiritual well-being, desiring to stir up in him an 
earnest attitude [to the practice] (_saṃvejetukāmā_), approached him and 
addressed him in verses:

____
Desiring seclusion [from sensuous pleasures and spiritually unwholesome 
factors] you entered the woods,

_Vivekakāmosi vanaṃ paviṭṭho_
____

____
Yet your mind gushes outwardly.

_atha te mano niccharatī bahiddhā_
____

____
Eliminate, man, your fondness for people;

_Jano janasmiṃ vinayassu chandaṃ_
____

[quote, S.1.197]
____
Then you'll be truly happy, free of attachment.

_tato sukhī hohisi vītarāgo._
____

.Illustration
====
viveka

seclusion [from sensuous pleasures and spiritually unwholesome factors]
====

[quote, S.5.78]
____
In this regard a bhikkhu develops the enlightenment factor of mindfulness (... 
detached awareness) which conduces to seclusion [from sensuous pleasures and 
spiritually unwholesome factors], to non-attachment [to originated phenomena], 
to the ending [of originated phenomena], and which results in the 
relinquishment [of the whole phenomenon of attachment].

_Idha bhikkhave bhikkhu satisambojjhaṅgaṃ bhāveti (... 
upekkhāsambojjhaṅgaṃ bhāveti) vivekanissitaṃ virāganissitaṃ 
nirodhanissitaṃ vossaggapariṇāmiṃ._
____

.Illustration
====
viveka

seclusion [from sensuous pleasures and spiritually unwholesome factors]
====

[quote, Sn.v.474]
____
He who is not relying on [the fulfilment of any] expectation [for anything in 
the world], who has discovered seclusion [from sensuous pleasures and 
spiritually unwholesome factors], who has gone beyond the dogmatism experienced 
by others, and for whom there are no bases whatsoever [for the establishment of 
his stream of sense consciousness]: the Perfect One is worthy of the oblation.

_Āsaṃ anissāya vivekadassī paravediyaṃ diṭṭhimupātivatto +
Ārammaṇā yassa na santi keci tathāgato arahati pūraḷāsaṃ._
____

.Illustration
====
viveka

seclusion [from sensuous pleasures and spiritually unwholesome factors]
====

[quote, Dh.v.75]
____
One is the path to worldly gain, another the path leading to the Untroubled. 
Fully understanding this, the bhikkhu, the disciple of the Buddha, should not 
take delight in worldly honour. He should cultivate seclusion [from sensuous 
pleasures and spiritually unwholesome factors] instead.

_Aññā hi lābhūpanisā aññā nibbānagāminī +
Evametaṃ abhiññāya bhikkhu buddhassa sāvako +
Sakkāraṃ nābhinandeyya vivekamanubrūhaye._
____

.Illustration
====
viveke

seclusion [from sensuous pleasures and spiritually unwholesome factors]
====

[quote, Sn.v.818]
____
Tell us of the distress, dear sir, that befalls one who is applied to sexual 
intercourse. Having heard your explanation we will train ourselves in seclusion 
&#8203;[from sensuous pleasures and spiritually unwholesome factors].

_Methunamanuyuttassa vighātaṃ brūhi mārisa +
Sutvāna tava sāsanaṃ viveke sikkhissāmase._
____

.Illustration
====
viveko

physical seclusion (=paviveko)
====

• Blissful is the physical seclusion of one who is content [with what is 
paltry and easily gotten], who has heard the teaching, and who sees [the nature 
of reality]._ +
Sukho viveko tuṭṭhassa sutadhammassa passato_ (Ud.10).

.Illustration
====
viveka

physical seclusion (=paviveka)
====

[quote, Th.v.589]
____
Just as the Veramba wind blows clouds in the rainy season, so [in the city of 
Veramba] mental images connected with physical seclusion [would] overwhelm me.

_Yathā abbhāni verambo vāto nudati pāvuse +
Saññā me abhikīranti vivekapaṭisaṃyuttā._
____

