== Viññāṇaṃ anidassanaṃ anantaṃ sabbato pabhaṃ

=== Renderings

- _viññāṇaṃ anidassanaṃ anantaṃ sabbato pabhaṃ_: the mind with no 
attribute, boundless, altogether free of defilement

=== Introduction

==== Viññāṇaṃ anidassanaṃ = saññāvedayitanirodha

_Viññāṇaṃ anidassanaṃ anantaṃ sabbato pabhaṃ_ occurs in the 
scriptures twice (D.1.223; M.1.329). Its meaning is unsettled. We will show 
here that it means the ending of perception and sense impression 
(_saññāvedayitanirodha_). Let us examine the phrase step by step.

1. The phrase cannot mean _nibbāna_ because although _anidassanaṃ_ is indeed 
a synonym for _nibbāna_ (S.4.370), _nibbāna_ is never elsewhere in the 
scriptures called _viññāṇaṃ_; and furthermore, _nibbāna_ is never 
described as _sabbato pabhaṃ_. See synonyms of _nibbāna_ at S.4.368-373.

2. In the scriptures _pabhassara_ is commonly linked to _cittaṃ._ For example:

[quote, A.3.16-17]
____
the mind is pliable and workable and radiant

_cittaṃ mudu ca kammaniyañca pabhassarañca._
____

That the related word _pabhaṃ_ is linked in our verse to _viññāṇaṃ_ 
suggests that _viññāṇaṃ_ is the phenomenon more usually known as 
_cittaṃ_. This is not greatly surprising because the two words are already 
used as synonyms elsewhere in the scriptures. For example:

[quote, S.2.95]
____
That which is called 'mind' or 'cognition' or 'consciousness' arises as one 
thing and ceases as another by day and by night.

_Yañca kho etaṃ bhikkhave vuccati cittaṃ iti pi mano iti pi 
viññāṇaṃ iti pi taṃ rattiyā ca divasassa ca aññadeva uppajjati 
aññaṃ nirujjhati._
____

Therefore the _viññāṇaṃ_ in our phrase might make more sense if 
understood as _cittaṃ_. Accordingly, we will call it 'mind.'

3. _Anidassanaṃ_ can mean invisible. For example:

[quote, M.1.127]
____
Because empty space is formless and invisible; it is not easy to draw pictures 
there

__ākāso arūpī anidassano tattha na sukaraṃ rūpaṃ likhituṃ._
____

However, PED gives nine meanings to _nidassana_ including 'attribute.' 
Therefore we render _anidassana_ as 'with no attribute.'

4. If _viññāṇaṃ_ has no attribute, then _sabbato pabhaṃ_ cannot 
rationally be rendered as 'altogether radiant.' We therefore adopt the _via 
negativa_ approach. This is easily accomplished because in the scriptures 
_pabhassara_ means liberation from defilement. For example:

[quote, A.1.10]
____
The mind is intrinsically radiant: it is defiled by extrinsic defilements

_Pabhassaramidaṃ bhikkhave cittaṃ tañca kho āgantukehi upakkilesehi 
upakkiliṭṭhan ti._
____

Therefore _sabbato pabhaṃ_ can be rendered as 'altogether free of 
defilement.' This is compatible with 'having no attribute.'

5. Our phrase is associated with the ending of all phenomena because it is 
linked in its two references to these two statements:

[quote, D.1.223]
____
\a) Here denomination-and-bodily-form is completely ended

_Ettha nāmañca rūpañca asesaṃ uparujjhati._
____

[quote, M.1.329]
____
\b) It is not reached by the totality of everything

_sabbassa sabbattena ananubhūtaṃ._
____

These statements both suggest our phrase means the ending of perception and 
sense impression (_saññāvedayitanirodha_) because:

[quote, M.1.53]
____
\a) _Nāma_ includes sense impression and perception

_Vedanā saññā cetanā phasso manasikāro idaṃ vuccatāvuso nāmaṃ._
____

\b) 'Everything' (_sabba_) by definition includes 'whatever sense impression 
that arises due to mental sensation' (_yampidaṃ manosamphassapaccayā 
uppajjati vedayitaṃ sukhaṃ vā dukkhaṃ vā adukkhamasukhaṃ_, S.4.27).

Therefore our phrase implies a state 'not reached by' sense impression.

6. Our phrase is part of a five-line verse, which is quoted in full in the 
Illustrations below. The last line of that verse includes the term 'the ending 
of _viññāṇa_' (_viññāṇassa nirodhena_) (D.1.223). So whereas we are 
researching the meaning of '_viññāṇa_ with no attribute' (_viññāṇaṃ 
anidassanaṃ_), we are faced with the fact that it is equivalent to the ending 
of _viññāṇa_. This appears to be a combination of incompatible terms, 
unless the two _viññāṇas_ have different meanings. Since we have already 
decided to call _viññāṇaṃ anidassanaṃ_ 'mind with no attribute,' let 
us now quickly settle the meaning of the 'ending of _viññāṇa_.'

7. Since we have agreed that _viññāṇaṃ anidassanaṃ_ concerns the 
ending of perception and sense impression (_saññāvedayitanirodha_), 
therefore _viññāṇassa nirodhena_ means _saññāvedayitanirodhena_, the 
ending of perception and sense impression_._

In conclusion, the mind with no attribute means the ending of perception and 
sense impression.

==== Not to be confused: tadāyatanaṃ

_Viññāṇaṃ anidassanaṃ_ should not be confused with the following quote 
in which these three phrases show that _nibbāna_ is meant:

1. supreme state of deliverance

2. no foundation

3. truly the end of suffering

The quote is this:

[quote, Ud.80]
____
There is that supreme state of deliverance where there is neither solidness, 
liquidness, warmth, nor gaseousness; no state of awareness of boundless space, 
no state of awareness of boundless mental consciousness, no state of awareness 
of nonexistence, no state of awareness neither having nor lacking perception; 
neither this world, nor a world beyond, nor both; neither sun nor moon. There, 
I declare, there is no coming, no going, no staying, no passing away, no being 
reborn. It is neither fixed, nor moving, and has no foundation. This is truly 
the end of suffering.

_Atthi bhikkhave tadāyatanaṃ yattha neva paṭhavī na āpo na tejo na vāyo 
na ākāsānañcāyatanaṃ na viññāṇañcāyatanaṃ na 
ākiñcaññāyatanaṃ na nevasaññānāsaññāyatanaṃ nāyaṃ loko na 
paraloko na ubho candimasūriyā. Tatrāpāhaṃ bhikkhave neva āgatiṃ 
vadāmi na gatiṃ na ṭhitiṃ na cutiṃ na upapattiṃ; appatiṭṭhaṃ 
appavattaṃ anārammaṇamevetaṃ. Esevanto dukkhassā ti._
____

=== Illustrations

.Illustration
====
viññāṇaṃ anidassanaṃ anantaṃ sabbato pabhaṃ

[quote

M.1.329]
====

____
The mind with no attribute, boundless, altogether free of defilement: that is 
not reached by the solidness of earth, the liquidness of water, the warmth of 
fire, the gaseousness of wind... the totality of everything.

_Viññāṇaṃ anidassanaṃ anantaṃ sabbato pabhaṃ taṃ paṭhaviyā 
paṭhavattena ananubhūtaṃ āpassa āpattena ananubhūtaṃ tejassa 
tejattena ananubhūtaṃ vāyassa vāyattena ananubhūtaṃ... sabbassa 
sabbattena ananubhūtaṃ._
____

.Illustration
====
viññāṇaṃ anidassanaṃ anantaṃ sabbato pabhaṃ

____
The mind with no attribute

boundless, altogether free of defilement:
====

_Viññāṇaṃ anidassanaṃ anantaṃ sabbato pabhaṃ_
____

____
Here liquidness, solidness, warmth, and gaseousness have no footing;

_Ettha āpo ca paṭhavī tejo vāyo na gādhati_
____

____
Here long and short, small and large, fair and foul, and 
denomination-and-bodily-form are completely ended.

_Ettha dīghañca rassañca aṇuṃthūlaṃ subhāsubhaṃ; +
Ettha nāmañca rūpañca asesaṃ uparujjhati_
____

[quote, D.1.223]
____
Through the ending of perception and sense impression, these are thereby 
completely ended.

_Viññāṇassa nirodhena etthetaṃ uparujjhatī ti._
____

