== Viññāṇa

=== Renderings

- _viññāṇa_: advertence

- _viññāṇa_: stream of sense consciousness

- _viññāṇasota_: stream of sense consciousness

- _viññāṇa_: mind

- _viññāṇa_: mental consciousness

- _viññāṇa_: thought

- _viññāṇa_: insight

- _viññāṇa_: 'personal _viññāṇa_' (Bhikkhu Sāti)

=== Introduction

==== Viññāṇa: the mental component of sensation

As a component of _phassa_, _viññāṇa_ is the mental component of 
sensation. It arises dependent on the association of the internal and external 
sense bases. For example:

[quote, M.1.111]
____
Dependent on the visual sense and visible objects, advertence to the visual 
field arises

_cakkhuñcāvuso paṭicca rūpe ca uppajjati cakkhuviññāṇaṃ._
____

We call it 'advertence.' We regard it as equivalent to attention, but without 
its false connotations. 'Advertence' is clearly conditional, whereas 
'attention' seems to imply an independent entity which hovers over objects, and 
which is under the control of intention. Attention is represented by the term 
_manasikāra_. For example:

• With the origination of attention comes the origination of objects of the 
systematic teachings. With the ending of attention comes the vanishing of 
objects of the systematic teachings. +
_Manasikārasamudayā dhammānaṃ samudayo. Manasikāranirodhā dhammānaṃ 
atthaṅgamo ti_ (S.5.184).

There are six varieties of advertence corresponding to the six senses. We call 
these: advertence to the visual field, advertence to the auditory field, 
advertence to the olfactory field, advertence to the gustatory field, 
advertence to the tactile field, and advertence to the mental field 
(_cakkhuviññāṇaṃ sotaviññāṇaṃ ghānaviññāṇaṃ 
jivhāviññāṇaṃ kāyaviññāṇaṃ manoviññāṇaṃ_, M.3.281).

==== Viññāṇakkhandha: advertence

The phenomenon of _viññāṇakkhandha_ is also 'advertence,' and is defined 
as that by which one discerns objects and sense impression, for instance 
different flavours (Quote 1, S.3.87) or pleasure and pain (Quote 2, M.1.292-3):

Quote 1)

[quote, S.3.87]
____
And why do you call it advertence? One knows therefore it is called advertence. 
And what does one know? One knows sour, one knows bitter, one knows pungent, 
one knows sweet, one knows sharp, one knows mild, one knows salty, one knows 
bland. 'One knows,' bhikkhus, therefore it is called advertence.

_Vijānātī ti kho bhikkhave tasmā viññāṇan ti vuccati. Kiñca 
vijānāti: ambilampi vijānāti tittakampi vijānāti kaṭukampi vijānāti 
madhurakampi vijānāti khārikampi vijānāti akhārikampi vijānāti 
loṇikampi vijānāti aloṇikampi vijānāti. Vijānātī ti kho bhikkhave 
tasmā viññāṇan ti vuccati._
____

Quote 2)

[quote, M.1.292-3]
____
One knows, one knows. Therefore advertence is said. What does one know? One 
knows what is pleasant, one knows what is unpleasant, one knows what is neutral.

_Vijānāti vijānātī ti kho āvuso tasmā viññāṇan ti vuccati. Kiñca 
vijānāti sukhan ti pi vijānāti dukkhan ti pi vijānāti adukkhamasukhan ti 
pi vijānāti._
____

==== Viññāṇa: the instrument of knowledge, not a knowing phenomenon

The instrumental case in the following quote (_tena ca viññāṇena_) shows 
that _viññāṇa_ is the instrument through which one knows sensation.

[quote, M.3.242]
____
What does one know with that _viññāṇa_? One knows what is pleasant, one 
knows what is unpleasant, one knows what is neutral.

_Tena ca viññāṇena kiṃ vijānāti: sukhan ti pi vijānāti dukkhan ti pi 
vijānāti adukkhamasukhan ti pi vijānāti._
____

This suggests that _viññāṇa_ is a knowing phenomenon, which is how Bodhi 
understands it. He says 'Usually in the suttas _viññāṇa_ is presented 
simply as the basic awareness of an object via one of the sense bases, i.e. as 
bare "consciousness of" rather than as a discriminative capacity' (CDB p.1072 
n.114). But this presupposes that awareness of an object produces sensation, 
whereas awareness of an object is surely equivalent to sensation, and it would 
lead to the following translation:

[quote, M.3.281]
____
Dependent on the visual sense and visible objects, basic awareness of an object 
arises. The association of the three is sensation.

_Cakkhuñca paṭicca rūpe ca uppajjati cakkhuviññāṇaṃ. Tiṇṇaṃ 
saṅgati phasso._
____

But the suttas say that for sensation there needs to be all three elements:

• That they should experience anything without sensation could not be +
☸ _te vata aññatra phassā paṭisaṃvedissantīti netaṃ ṭhānaṃ 
vijjati_) (D.1.43).

==== Viññāṇakkhandha = viññāṇa of phassa: Mahāhatthipadopama Sutta

The _viññāṇa_ of the fifth aggregate is the _viññāṇa_ of _phassa_. 
This can be demonstrated in three ways:

1. The _Mahāhatthipadopama Sutta_ says:
+
[quote, M.1.190]
____
If the visual sense is operational and visible objects come into its range, and 
there is an operative interaction between them, then the appropriate class of 
_viññāṇa_ is manifested... The _viññāṇa_ in whatever is thus brought 
about comprises _viññāṇūpādānakkhandha.'_

_ajjhattikañce cakkhuṃ aparibhinnaṃ hoti bāhirā ca rūpā āpāthaṃ 
āgacchanti tajjo ca samannāhāro hoti evaṃ tajjassa viññāṇabhāgassa 
pātubhāvo hoti... yaṃ tathābhūtassa viññāṇaṃ taṃ 
viññāṇūpādānakkhandhe saṅgahaṃ gacchati._
____

2. If the fifth aggregate was different from the _viññāṇa_ of _phassa_, 
then the _viññāṇa_ of _phassa_ would have no aggregate to belong to. It is 
not material, so it could not belong to the first aggregate of bodily form. Nor 
could it belong to the three immaterial aggregates, because they depend on 
_phassa_:
+
[quote, M.3.17]
____
Sensation is the indispensible and necessary condition by which the aggregates 
of sense impression, perception, and intentional activities are to be 
discerned._

_phasso hetu phasso paccayo vedanakkhandhassa... saññākkhandhassa... 
saṅkhārakkhandhassa paññāpanāya._
____

3. _Viññāṇakkhandha_ and _phasso_ have the same source, i.e. 
_nāmarūpaṃ_:
+
[quote, S.3.102]
____
Denomination-and-bodily-form is the indispensible and necessary condition 
by which the aggregate of advertence is to be discerned.

nāmarūpaṃ hetu nāmarūpaṃ paccayo viññāṇakkhandhassa 
paññāpanāyā ti_.
____
+
[quote, Sn.v.872]
____
Sensation arises dependent on denomination-and-bodily-form.

_Nāmañca rūpañca paṭicca phasso._
____

==== Viññāṇakkhandha = viññāṇa of phassa: puzzling relationship to 
nāmarūpa

If the _viññāṇa_ of the fifth aggregate is identical with the 
_viññāṇa_ of _phassa_, then it must also arise from the six senses and 
their objects. But the quotes above say it arises from _nāmarūpa_. To explain 
this, we will now show that '_nāmarūpa_' can mean the six senses and their 
objects because of the expression 'external _nāmarūpa'_ which we now discuss.

==== External nāmarūpa + internal nāmarūpa = senses + objects

Our explanation is based on the following quote:

[quote, S.2.24]
____
There is this [wretched human] body and the external _nāmarūpa_. Thus is this 
dyad. Because of the dyad there is sensation.

_Iti ayañceva kāyo bahiddhā ca nāmarūpaṃ. Itthetaṃ dvayaṃ. Dvayaṃ 
paṭicca phasso._
____

In this quote, 'this [wretched human] body' seems to stand for 'internal 
_nāmarūpa_.' The quote corresponds to the more common explanation:

[quote, M.3.281]
____
Dependent on the visual sense and visible objects, advertence to the visual 
field arises. The association of the three is sensation.

_Cakkhuñca paṭicca rūpe ca uppajjati cakkhuviññāṇaṃ. Tiṇṇaṃ 
saṅgati phasso._
____

'The visual sense' is the first of the six senses (_ajjhattikāni āyatanāni_, 
D.3.243), and 'visible objects' is the first of the six sense objects 
(_bāhirāni āyatanāni_, D.3.243).

By comparison of quotes, internal _nāmarūpa_ corresponds to the six senses, 
and external _nāmarūpa_ corresponds to the six sense objects. So when the 
scriptures say that '_nāmarūpa_ is the indispensible and necessary condition 
by which the aggregate of advertence is to be discerned' it is likely that 
_nāmarūpa_ corresponds to the six senses and their objects.

==== Viññāṇa of paṭiccasamuppāda: stream of sense consciousness

In the context of _paṭiccasamuppāda_, we call _viññāṇa_ the 'stream of 
sense consciousness.' Bodhi calls this 'the underlying stream of consciousness 
which sustains personal continuity through a single life and threads together 
successive lives' (CDB p.769 n.154). This _viññāṇa_ arises in the mother's 
womb and supports the development of _nāmarūpa_:

[quote, D.2.63]
____
If a stream of sense consciousness did not arise in the womb, would 
denomination-and-bodily-form develop there? No, bhante.

_viññāṇañca hi ānanda mātukucchismiṃ na okkamissatha api nu kho 
nāmarūpaṃ mātukucchismiṃ samuccissathā ti? No hetaṃ bhante._
____

[quote, D.2.63]
____
If the stream of sense consciousness of a young boy or girl were eradicated, 
would denomination-and-bodily-form grow, mature, and develop? No, bhante.

_viññāṇañca hi ānanda daharasseva sato vocchijjissatha kumārakassa vā 
kumārikāya vā api nu kho nāmarūpaṃ vuddhiṃ virūḷhiṃ vepullaṃ 
āpajjissathā ti? No hetaṃ bhante._
____

At death, this same _viññāṇa_ finds a new place to establish itself 
(_viññāṇaṃ patiṭṭhitan ti_, S.1.122), and can be named after the 
individual it used to be, for example:

[quote, S.1.122]
____
The stream of sense consciousness of the noble young man Godhika

_godhikassa kulaputtassa viññāṇaṃ._
____

In arahants, because there is no rebirth, their _viññāṇa_ is not 
established anywhere (_appatiṭṭhitena viññāṇena parinibbuto ti_). 
Other suttas say the _viññāṇa_ is demolished (_viññāṇaṃ 
uparujjhatī ti_ Sn.v.1111). The mysterious relationship between these two 
apparently equal events -- 'not established _viññāṇa_' and 'demolished 
_viññāṇa_' -- is presumably no more to be resolved than the question as to 
whether an arahant continues to exist after death, or not.

==== The stream of sense consciousness depends on perception

Although there are nine realms of beings (_nava sattāvāsā_ A.4.401), there 
are only seven stations for _viññāṇa_ (_satta viññāṇaṭṭhitiyo_ 
D.2.69), which implies that in two realms there is no _viññāṇa._ These two 
realms are:

____
the group of beings without perception

_asaññasattāyatanaṃ_
____

[quote, D.2.69]
____
the group of beings neither having nor lacking perception

_nevasaññānāsaññāyatanameva._
____

Thus in the context of the nine realms of beings, _viññāṇa_ depends on 
perception. Without perception a being has no _viññāṇa._ This is 
consistent with our calling this _viññāṇa_ the 'stream of sense 
consciousness.'

==== Stream of sense consciousness: six streams

This _viññāṇa_ is comprised of six streams (M.1.53; S.2.44). These streams 
are named in Pāli in the same way as the _viññāṇa_ of _phasso_. We call 
these:

____
the stream of visual consciousness

_cakkhuviññāṇaṃ_
____

____
the stream of auditory consciousness

_sotaviññāṇaṃ_
____

____
the stream of olfactory consciousness

_ghānaviññāṇaṃ_
____

____
the stream of gustatory consciousness

_jivhāviññāṇaṃ_
____

____
the stream of tactile consciousness

_kāyaviññāṇaṃ_
____

____
the stream of mental consciousness

_manoviññāṇaṃ_
____

The stream of sense consciousness plays an important role in rebirth.

==== The stream of sense consciousness and rebirth

The stream of sense consciousness plays a key role in rebirth:

____
For beings [obstructed by] uninsightfulness into reality, and [tethered to 
individual existence] by craving

_avijjānīvaraṇānaṃ sattānaṃ taṇhāsaṃyojanānaṃ_
____

• ... the stream of sense consciousness is established in the low plane of 
existence** +
☸** _hīnāya dhātuyā viññāṇaṃ patiṭṭhitaṃ_

____
... the stream of sense consciousness is established in the middle plane of 
existence

_majjhimāya dhātuyā viññāṇaṃ patiṭṭhitaṃ_
____

____
... the stream of sense consciousness is established in the high plane of 
existence

_paṇītāya dhātuyā viññāṇaṃ patiṭṭhitaṃ_
____

[quote, A.1.223-4]
____
In this way renewed states of individual existence and rebirth occur in the 
future

_evaṃ āyatiṃ punabbhavābhinibbatti hoti._
____

==== The stream of sense consciousness and kamma

The effect of _kamma_ on the stream of sense consciousness is explained in this 
quote:

____
Bhikkhus, if one who has acquiesced in uninsightfulness into reality undertakes 
a karmically consequential deed that is meritorious, his stream of sense 
consciousness is furnished with merit;

_Avijjāgatoyaṃ bhikkhave purisapuggalo puññaṃ ce saṅkhāraṃ 
abhisaṅkharoti puññopagaṃ hoti viññāṇaṃ._
____

____
If he undertakes a karmically consequential deed that is demeritorious, his 
stream of sense consciousness is furnished with demerit;

_Apuññaṃ ce saṅkhāraṃ abhisaṅkharoti apuññopagaṃ hoti 
viññāṇaṃ._
____

____
If he undertakes a karmically consequential deed that is karmically neutral, 
his stream of sense consciousness is furnished with what is karmically neutral.

_Āneñjaṃ ce saṅkhāraṃ abhisaṅkharoti āneñjūpagaṃ hoti 
viññāṇaṃ._
____

[quote, S.2.82]
____
... When a bhikkhu has abandoned uninsightfulness into reality and aroused 
insightfulness into reality, then, with the fading away of uninsightfulness 
into reality and the arising of insightfulness into reality, he does not 
undertake a karmically consequential deed that is meritorious, demeritorious, 
or karmically neutral.

_Yato kho bhikkhave bhikkhuno avijjā pahīṇā hoti vijjā uppannā so 
avijjāvirāgā vijjūppādā neva puññābhisaṅkhāraṃ abhisaṅkharoti 
na apuññābhisaṅkhāraṃ abhisaṅkharoti na āneñjābhisaṅkhāraṃ 
abhisaṅkharoti._
____

==== The stream of sense consciousness is liberated [from perceptually 
obscuring states]

Some suttas say that at arahantship, the stream of sense consciousness is 
liberated [from perceptually obscuring states], like this:

____
Bhikkhus, if a bhikkhu has abandoned attachment to bodily form, with the 
abandonment of attachment the basis is removed: there is no establishment of 
his stream of sense consciousness.

_Rūpadhātuyā ce bhikkhave bhikkhuno rāgo pahīno hoti rāgassa pahānā 
vocchijjatārammaṇaṃ patiṭṭhā viññāṇassa na hoti_
____

[quote, S.3.53]
____
... When the stream of sense consciousness is unestablished, not [egoistically] 
matured, without the performance of [karmically consequential deeds], it is 
liberated [from perceptually obscuring states].

_tadappatiṭṭhitaṃ viññāṇaṃ avirūḷhaṃ anabhisaṅkhacca 
vimuttaṃ._
____

____
Being thus liberated it is inwardly stable

_Vimuttattā ṭhitaṃ_
____

____
Being inwardly stable it is inwardly at peace

__Ṭhitattā santusitaṃ_
____

____
Being inwardly at peace, he is not apprehensive

_Santusitattā na paritassati._
____

[quote, S.3.54]
____
Being not apprehensive, he realises the Untroubled for himself.

_Aparitassaṃ paccattaṃ yeva parinibbāyati._
____

_Vimuttaṃ_, _ṭhitaṃ, and santusitaṃ_ are neuter singulars in agreement 
with _viññāṇaṃ._ But _paritassati_ seems to refer to the individual who 
is individually liberated.

In other suttas, the same process is described, but where the liberated entity 
is the _citta_, or the bhikkhu:

[quote, S.3.45]
____
If a bhikkhu's mind is unattached to bodily form... advertence, it is liberated 
from perceptually obscuring states through being without grasping.

_Rūpadhātuyā... viññāṇadhātuyā ce bhikkhave bhikkhuno cittaṃ 
virattaṃ vimuttaṃ hoti anupādāya āsavehi._
____

• When a bhikkhu sees it thus according to reality with perfect penetrative 
discernment, he is liberated [from perceptually obscuring states] through being 
without grasping. +
☸ _bhikkhu_... _evametaṃ yathābhūtaṃ sammappaññāya disvā anupādā 
vimutto hoti_ (M.1.235).

In the latter case, _vimutto_ is masculine singular in agreement with _bhikkhu_.

==== The stream of sense consciousness ceases with arahantship

Arahants have no stream of sense consciousness because they are free of 
karmically consequential deeds:

-- What do you think, bhikkhus: can a bhikkhu whose _āsavas_ are destroyed, 
undertake a karmically consequential deed that is meritorious, demeritorious, 
or karmically neutral?

-- No, bhante.

____
When there are utterly no karmically consequential deeds, with the ending of 
karmically consequential deeds, would the stream of sense consciousness be 
discerned?

_Sabbaso vā pana saṅkhāresu asati saṅkhāranirodhā api nu kho 
viññāṇaṃ paññāyethā ti?_
____

-- No, bhante.

____
-- When there is utterly no stream of sense consciousness, with the ending of 
the stream of sense consciousness, would denomination-and-bodily-form be 
discerned?

_Sabbaso vā pana viññāṇe asati viññāṇanirodhā api nu kho 
nāmarūpaṃ paññāyethā ti?_
____

-- No, bhante (S.2.83).

==== Viññāṇasota: stream of sense consciousness

The suttas say that _viññāṇasotaṃ_ is a stream that is established in 
this world and the world beyond, which is indistinguishable from the stream of 
sense consciousness. _Viññāṇa_ is apparently an abbreviation for 
_viññāṇasotaṃ_.

[quote, D.3.105]
____
He comes to know man's stream of sense consciousness as an unbroken stream that 
is established in both this world and the world beyond. That is the third 
attainment of vision [of things according to reality].

_purisassa ca viññāṇasotaṃ pajānāti ubhayato abbocchinnaṃ idha loke 
patiṭṭhitañca paraloke patiṭṭhitaṃ ca. Ayaṃ tatiyā 
dassanasamāpatti._
____

[quote, D.3.105]
____
He comes to know man's stream of sense consciousness as an unbroken stream that 
is established neither in this world nor in the world beyond. That is the 
fourth attainment of vision [of things according to reality].

_purisassa ca viññāṇasotaṃ pajānāti ubhayato abbocchinnaṃ idha loke 
appatiṭṭhitañca paraloke appatiṭṭhitañca. Ayaṃ catutthā 
dassanasamāpatti._
____

This is therefore an 'unestablished stream,' which we now discuss.

==== Stream of sense consciousness that is not established in arahants

The last paragraph presumably refers to arahants because the arahants 
_viññāṇa_ is not established anywhere. For example, when the arahant 
Godhika died, the Buddha said that with the stream of sense consciousness 
unestablished, the noble young man Godhika had passed away to the 
Untroubled-without-residue' (_appatiṭṭhitena ca bhikkhave viññāṇena 
godhiko kulaputto parinibbutoti_) (S.1.122).

It is easily understandable how the _viññāṇa_ of a living arahant could be 
called 'unestablished,' because the arahant still has a stream of sense 
impression but no sense of a personal identity. But after his death, the issue 
of an unestablished _viññāṇa_ is inexplicable__,__ because other suttas 
say the arahant's _viññāṇa_ is demolished (_viññāṇaṃ uparujjhatī 
ti_ Sn.v.1111). We have noted this problem above. It is one of the unexplained 
issues (_avyākatavatthū_, A.4.68-70).

==== Refining of mental consciousness means detaching the mind

_Viññāṇa_ is sometimes used to mean 'mental consciousness'. This mental 
consciousness (_viññāṇaṃ_) becomes purified and refined when one 
detaches the mind (_cittaṃ_) from the material phenomena through seeing them 
as being void of personal qualities:

____
The internal Solidness Phenomenon and the external Solidness Phenomenon are 
simply the Solidness Phenomenon, which should be seen according to reality with 
perfect penetrative discernment as "not [in reality] mine," "not [in reality] 
what I am," "not my [absolute] Selfhood."'

_Yā ceva kho pana ajjhattikā paṭhavīdhātu yā ca bāhirā 
paṭhavīdhātu paṭhavīdhāturevesā taṃ n'etaṃ mama n'eso'hamasmi na 
me so attā ti evametaṃ yathābhūtaṃ sammappaññāya daṭṭhabbaṃ._
____

____
... When one sees it thus according to reality with perfect penetrative 
discernment, one is disillusioned with the Solidness Phenomenon and one 
detaches the mind from the Solidness Phenomenon

_Evametaṃ yathābhūtaṃ sammappaññāya disvā paṭhavīdhātuyā 
nibbindati paṭhavīdhātuyā cittaṃ virājeti_
____

... and similarly for the Liquidness Phenomenon, Warmth Phenomenon, Gaseousness 
Phenomenon, Space Element.

____
... Then there remains only mental consciousness, purified and refined

_Athāparaṃ viññāṇaṃ yeva avasissati parisuddhaṃ pariyodātaṃ_
____

[quote, M.3.242]
____
What does one know with that mental consciousness? One knows what is pleasant, 
one knows what is unpleasant, one knows what is neutral.

_Tena ca viññāṇena kiṃ vijānāti: sukhan ti pi vijānāti dukkhan ti pi 
vijānāti adukkhamasukhan ti pi vijānāti._
____

==== Boundless mental consciousness

_Viññāṇa_ can be used as a kasiṇa object (_viññāṇakasiṇa_) and 
stands in contrast to the kasiṇas of earth, water, fire, wind, blue, yellow, 
red, white, space. Therefore we again call it mental consciousness. Thus one 
perceives the kasiṇa of mental consciousness extending above, below, and 
across from oneself, with no subject/object duality and without limitation 
(_viññāṇakasiṇameko sañjānāti uddhaṃ adho tiriyaṃ advayaṃ 
appamāṇaṃ_ A.5.60).

==== Boundless mental consciousness: sphere of meditation

[quote, M.2.13]
____
Boundless mental consciousness is a sphere of meditation, perhaps similar to 
the _viññāṇakasiṇa_. To enter the state of awareness of boundless mental 
consciousness a bhikkhu must completely transcend the state of awareness of 
boundless space, and enter and abide in the state of awareness of boundless 
mental consciousness, where one perceives that mental consciousness is boundless

_sabbaso ākāsānañcāyatanaṃ samatikkamma anantaṃ viññāṇan ti 
viññāṇañcākāsānañcāyatanaṃ samatikkamma anantaṃ viññāṇan ti 
viññāṇañcāyatanaṃ upasampajja viharati._
____

==== Boundless mental consciousness: station for the stream of sense 
consciousness

The state of awareness of boundless mental consciousness is the sixth station 
for the stream of sense consciousness.

[quote, D.2.69]
____
There are beings, Ānanda, that, by completely transcending the state of 
awareness of boundless space, arise in the state of awareness of boundless 
mental consciousness, where one perceives that mental consciousness is 
boundless. This is the sixth station for the stream of sense consciousness.

_Santānanda sattā sabbaso ākāsānañcāyatanaṃ samatikkamma anantaṃ 
viññāṇan ti viññāṇañcāyatanūpagā. Ayaṃ chaṭṭhā 
viññāṇaṭṭhiti._
____

==== Viññāṇa: Mind

_Viññāṇa_ is used to mean mind:

[quote, M.3.227]
____
The ignorant Everyman considers bodily form to be the [absolute] Selfhood, or 
the [absolute] Selfhood to be corporeal. If that bodily form changes and 
alters, his mind is preoccupied with the change.

_Tassa taṃ rūpaṃ vipariṇamati aññathā hoti. Tassa 
rūpavipariṇāmaññathābhāvā rūpavipariṇāmānuparivatti 
viññāṇaṃ hoti._
____

- If a bhikkhu sees a visible object via the visual sense, and his mind pursues 
the phantasm of the visible object (_rūpanimittānusāri viññāṇaṃ 
hoti_)... then his mind is called 'distracted and scattered externally 
(_bahiddhā viññāṇaṃ vikkhittaṃ visaṭanti vuccati_ (M.3.225).

[quote, S.4.102]
____
There are, Lord of the Devas, visible objects known via the visual sense that 
are likeable, loveable, pleasing, agreeable, connected with sensuous pleasure, 
and charming. If a bhikkhu takes delight in them, welcomes them, and persists 
in cleaving to them, then the mind is attached to them (_tannissitaṃ 
viññāṇaṃ hoti_). That is grasping.

_Santi kho devānaminda cakkhuviññeyyā rūpā iṭṭhā kantā manāpā 
piyarūpā kāmūpasaṃhitā rajanīyā tañce bhikkhu abhinandati abhivadati 
ajjhosāya tiṭṭhati tassa taṃ abhinandato abhivadato ajjhosāya 
tiṭṭhato tannissitaṃ viññāṇaṃ hoti tadupādānaṃ._
____

==== Viññāṇa: Thoughts

_Viññāṇa_ is used in the plural to mean 'thoughts' (_viññāṇānaṃ_):

[quote, Th.v.419]
____
(The eightfold path) causes the thunderbolt of knowledge [of things according 
to reality] to fall on thoughts which have been taken hold of.

_Viññāṇānaṃ pariggahe ñāṇavajīranipātino._
____

==== Viññāṇa: Insight

_Viññāṇa_ can mean insight:

[quote, Th.v.1035]
____
Wanting insight into the teaching, one should associate with a disciple of the 
Buddha who has great learning, who is an expert in the teaching, and who is 
wise.

_Bahussutaṃ dhammadharaṃ sappaññaṃ buddhasāvakaṃ 
dhammaviññāṇamākaṅkhaṃ taṃ bhajetha tathāvidhaṃ._
____

- I thought, 'By this practice of austerities, I have not attained any 
superhuman attainment of knowledge and vision worthy of the Noble Ones. Could 
there be another path to enlightenment? (_siyā nu kho añño maggo bodhāyā 
ti_).

• ... Then something occurred to me. Once, while my Sakyan father was 
working, while I was sitting in the cool shade of a roseapple tree, secluded 
from sensuous pleasures and spiritually unwholesome factors, and having entered 
and abided in the first jhāna, which is accompanied by thinking and pondering, 
and rapture and physical pleasure born of seclusion [from sensuous pleasures 
and spiritually unwholesome factors], I recalled asking myself 'Could this be 
the way to enlightenment' (_siyā nu kho eso maggo bodhāyā ti_). +
_Tassa mayhaṃ aggivessana etadahosi abhijānāmi kho paṇāhaṃ 
pitusakkassa kammante sītāya jambucchāyāya nisinno vivicceva kāmehi 
vivicca akusalehi dhammehi savitakkaṃ savicāraṃ vivekajaṃ pītisukhaṃ 
paṭhamaṃ jhānaṃ upasampajja viharitā. Siyā nu kho eso maggo 
bodhāyāti._

____
... Following that memory came the insight

_tassa mayhaṃ aggivessana satānusāriviññāṇaṃ ahosi_
____

[quote, M.1.246]
____
... 'This indeed is the way to enlightenment'

_esova maggo bodhāyā ti._
____

==== Personal viññāṇa: the bhikkhu Sāti

The bhikkhu Sāti used the term _viññāṇa_ to indicate his idea of a 
personal _viññāṇa_, calling it _tadevidaṃ viññāṇaṃ_. This stands 
opposed to what the Buddha called 'dependently arisen _viññāṇa_' 
(_paṭiccasamuppannaṃ viññāṇaṃ_) in the following conversation:

____
-- Bhante, as I understand the teaching explained by the Blessed One, it is 
this personal _viññāṇa_ that roams and wanders the round of birth and 
death, not another'

_ahaṃ bhante bhagavatā dhammaṃ desitaṃ ājānāmi yathā tadevidaṃ 
viññāṇaṃ sandhāvati saṃsarati anaññan ti._
____

____
-- What is that _viññāṇa_, Sāti?

_Katamaṃ taṃ sāti viññāṇan ti_
____

____
-- Bhante, it is that which speaks and experiences and feels here and there the 
karmic consequences of meritorious and demeritorious deeds

_yvāyaṃ bhante vado vedeyyo tatra tatra kalyāṇapāpakānaṃ kammānaṃ 
vipākaṃ paṭisaṃvedetī ti_
____

[quote, M.1.258]
____
-- Worthless man, to whom indeed have you known me to explain the teaching that 
way? Worthless man, have I not in many ways stated that _viññāṇa_ is 
dependently arisen; and that without necessary conditions there is no arising 
of _viññāṇa_.

_anekapariyāyena paṭiccasamuppannaṃ viññāṇaṃ vuttaṃ aññatra 
paccayā natthi viññāṇassa sambhavo ti._
____

=== Illustrations

.Illustration
====
advertence: mentally known objects

The sixfold body of advertence should be understood.
====

____
Dependent on the visual sense and visible objects advertence to the visual field arises

_Cakkhuñca paṭicca rūpe ca uppajjati cakkhuviññāṇaṃ_
____

____
Dependent on the auditory sense and audible objects, advertence to the auditory 
field arises

_Sotañca paṭicca sadde ca uppajjati sotaviññāṇaṃ_
____

____
Dependent on the olfactory sense and smellable objects, advertence to the 
olfactory field arises

_Ghānañca paṭicca gandhe ca uppajjati ghānaviññāṇaṃ_
____

____
Dependent on the gustatory sense and tasteable objects, advertence to the 
gustatory field arises

_Jivhañca paṭicca rase ca uppajjati jivhāviññāṇaṃ_
____

____
Dependent on the tactile sense and tangible objects, advertence to the tactile 
field arises

_Kāyañca paṭicca phoṭṭhabbe ca uppajjati kāyaviññāṇaṃ_
____

[quote, M.3.281]
____
Dependent on the mental sense and mentally known objects, advertence to the 
mental field arises

_Manañca paṭicca dhamme ca uppajjati manoviññāṇaṃ._
____

.Illustration
====
stream of sense consciousness
====

____
And what is the stream of sense consciousness (_viññāṇaṃ_)?

_Katamañca bhikkhave viññāṇaṃ?_
____

____
There are these six streams of sense consciousness:

_Chayime bhikkhave viññāṇakāyā_
____

____
the stream of visual consciousness

_cakkhuviññāṇaṃ_
____

____
the stream of auditory consciousness

_sotaviññāṇaṃ_
____

____
the stream of olfactory consciousness

_ghānaviññāṇaṃ_
____

____
the stream of gustatory consciousness

_jivhāviññāṇaṃ_
____

____
the stream of tactile consciousness

_kāyaviññāṇaṃ_
____

[quote, S.2.2-4]
____
the stream of mental consciousness

_manoviññāṇaṃ._
____

.Illustration
====
stream of sense consciousness
====

____
"Then it occurred to me:

_tassa mayhaṃ bhikkhave etadahosi_
____

____
When there is what
does denomination-and-bodily-form arise? What is denomination-and-bodily-form 
dependent on?

_kimhi nu kho sati nāmarūpaṃ hoti. Kiṃ paccayā nāmarūpan ti._
____

____
Then through proper contemplation, there took place in me a realisation through 
penetrative discernment

_Tassa mayhaṃ bhikkhave yoniso manasikārā ahu paññāya abhisamayo ti_
____

____
When there is the stream of sense consciousness, denomination-and-bodily-form 
arises. Denomination-and-bodily-form arises dependent on the stream of sense 
consciousness.

_viññāṇe kho sati nāmarūpaṃ hoti viññāṇapaccayā nāmarūpan ti_
____

____
"Then it occurred to me:

_tassa mayhaṃ bhikkhave etadahosi_
____

____
When there is what, does the stream of sense consciousness arise? What is the 
stream of sense consciousness dependent on?

_kimhi nu kho sati viññāṇaṃ hoti. Kiṃ paccayā viññāṇan ti._
____

____
Then through proper contemplation, there took place in me a realisation through 
penetrative discernment

_Tassa mayhaṃ bhikkhave yoniso manasikārā ahu paññāya abhisamayo:_
____

____
When there is denomination-and-bodily-form, the stream of sense consciousness 
arises. The stream of sense consciousness arises dependent on 
denomination-and-bodily-form.

_nāmarūpe kho sati viññāṇaṃ hoti nāmarūpapaccayā viññāṇan ti_
____

____
"Then it occurred to me:

_tassa mayhaṃ bhikkhave etadahosi_
____

____
The stream of sense consciousness turns back at denomination-and-bodily-form; 
it does not go further

_paccudāvattati kho idaṃ viññāṇaṃ nāmarūpamhā nāparaṃ gacchati_
____

____
On account of this one can be born, age and die, pass away and be reborn

_Ettāvatā jāyetha vā jīyetha vā mīyetha vā cavetha vā upapajjetha vā _
____

[quote, S.2.104]
____
Namely through the stream of sense consciousness being dependent on 
denomination-and-bodily-form; and denomination-and-bodily-form being dependent 
on the stream of sense consciousness._

_yadidaṃ nāmarūpapaccayā viññāṇaṃ viññāṇapaccayā 
nāmarūpaṃ._
____

.Illustration
====
stream of sense consciousness
====

[quote, D.2.35]
____
With the ending of denomination-and-bodily-form comes the ending of the stream 
of sense consciousness.

_nāmarūpanirodhā viññāṇanirodho._
____

.Illustration
====
stream of sense consciousness
====

____
"Bhikkhus one who is full of attachment is unliberated; one who is free of attachment is 
liberated.

_Upayo bhikkhave avimutto anupayo vimutto._
____

____
The stream of sense consciousness (_viññāṇaṃ_) while standing, might 
stand clinging to bodily form (_rūpūpayaṃ_); with bodily form as its basis 
(_rūpārammaṇaṃ_) established on bodily form (_rūpappatiṭṭhaṃ_) 
with a sprinkling of spiritually fettering delight, it might [egoistically] 
grow, mature, and develop.

_rūpūpayaṃ vā bhikkhave viññāṇaṃ tiṭṭhamānaṃ tiṭṭheyya 
rūpārammaṇaṃ rūpappatiṭṭhaṃ nandūpasecanaṃ vuddhiṃ 
virūḷahiṃ vepullaṃ āpajjeyya_
____

Bhikkhus, one who is full of attachment is unliberated; one who is free of 
attachment is liberated. The stream of sense consciousness, while standing, 
might stand

- clinging to sense impression (_vedanūpayaṃ_)...

- clinging to perception (_saññūpayaṃ_)...

- clinging to intentional activities (_saṅkhārūpayaṃ_)...

- With them as its basis, established on them, with a sprinkling of spiritually 
fettering delight, the stream of sense consciousness might [egoistically] grow, 
mature, and develop (S.3.53).

Comment:

The first four aggregates are called _catasso viññāṇaṭṭhitiyo_ 
(D.3.228).

.Illustration
====
the stream of sense consciousness
====

[quote, S.3.53]
____
Bhikkhus, though someone might say: 'Apart from bodily form, apart from sense 
impression, apart from conception, apart from intentional activities, I will 
make known the coming and going of the stream of sense consciousness, its 
transmigration, its [egoistic] growth, maturation, and development,' that would 
be impossible.

_Yo bhikkhave evaṃ vadeyya: ahamaññatra rūpā aññatra vedanāya 
aññatra saññāya aññatra saṅkhārehi viññāṇassa āgatiṃ vā 
gatiṃ vā cutiṃ vā uppattiṃ vā vuddhiṃ vā virūḷhiṃ vā 
vepullaṃ vā paññāpessāmīti netaṃ ṭhānaṃ vijjati._
____

.Illustration
====
stream of sense consciousness and arahantship
====

____
Bhikkhus if a bhikkhu has abandoned attachment to bodily form, with the abandonment of 
attachment the basis is removed: there is no establishment of his stream of 
sense consciousness.

_Rūpadhātuyā ce bhikkhave bhikkhuno rāgo pahīno hoti rāgassa pahānā 
vocchijjatārammaṇaṃ patiṭṭhā viññāṇassa na hoti_
____

If he has abandoned attachment

- to the phenomenon of sense impression...

- to the phenomenon of perception...

- to the phenomenon of intentional activities...

- to the phenomenon of advertence,

____
with the abandonment of attachment the basis is removed: there is no 
establishment of his stream of sense consciousness.

_vedanādhātuyā .. saññādhātuyā... saṅkhāradhātuyā... 
viññāṇadhātuyā ce bhikkhave bhikkhunā rāgo pahīno hoti. Rāgassa 
pahānā vocchijjatārammaṇaṃ patiṭṭhā viññāṇassa na hoti_
____

[quote, S.3.53]
____
... When the stream of sense consciousness is unestablished, not [egoistically] 
matured, without the performance of [karmically consequential deeds], it is 
liberated [from perceptually obscuring states].

_tadappatiṭṭhitaṃ viññāṇaṃ avirūḷhaṃ anabhisaṅkhacca 
vimuttaṃ._
____

.Illustration
====
stream of sense consciousness
====

____
How is the stream of sense consciousness destroyed for one who is mindful
for one living the religious life? Having come to ask the Blessed One, let us 
hear that word of yours.

_Kathaṃ satassa carato viññāṇaṃ uparujjhati +
Bhagavantaṃ puṭṭhumāgamma taṃ suṇoma vaco tava_
____

[quote, Sn.v.1110-11]
____
For one who is mindful, for one living the religious life, if he does not take 
delight in sense impression either internally or externally, in this way his 
stream of sense consciousness is destroyed.

_Ajjhattañca bahiddhā ca vedanaṃ nābhinandito +
Evaṃ satassa carato viññāṇaṃ uparujjhatī ti._
____

.Illustration
====
stream of sense consciousness
====

[quote, M.1.140]
____
Bhikkhus, when the devas with Inda, Brahmā, and Pajāpati seek a bhikkhu who 
is liberated in mind, they do not find [anything of which they could say]: 'The 
stream of sense consciousness of the Perfect One is attached to this. For what 
reason? The Perfect One is untraceable even in this lifetime, I declare.

_evaṃ vimuttacittaṃ kho bhikkhave bhikkhuṃ saindā devā sabrahmakā 
sapajāpatikā anvesaṃ nādhigacchanti idaṃ nissitaṃ tathāgatassa 
viññāṇan ti. Taṃ kissa hetu? Diṭṭhevāhaṃ bhikkhave dhamme 
tathāgataṃ ananuvejjoti vadāmi._
____

.Illustration
====
mental consciousness
====

[quote, Dh.v.41]
____
Not long, indeed, till it will rest, this [wretched human] body here, beneath 
the clod, discarded, void of mental consciousness, like a useless block of wood.

_Aciraṃ vatayaṃ kāyo paṭhaviṃ adhisessati +
Chuddho apetaviññāṇo niratthaṃ va kaliṅgaraṃ._
____

.Illustration
====
mental consciousness
====

[quote, D.1.76]
____
This my body is material, made of the four great material phenomena, arisen 
from parents, and fed on rice and gruel. It is unlasting, and is liable to be 
injured, abraded, broken, and demolished. And this is my mental consciousness 
which is connected and bound to it.

_ayaṃ kho me kāyo rūpī cātummahābhūtiko mātāpettikasambhavo 
odanakummāsūpacayo aniccucchādana-parimaddana-bhedana-viddhaṃsanadhammo. 
Idañca pana me viññāṇaṃ ettha sitaṃ ettha paṭibaddhan ti._
____

.Illustration
====
mental consciousness
====

____
Six elements

_cha dhātuyo_
____

____
the Solidness Phenomenon

_paṭhavīdhātu_
____

____
the Liquidness Phenomenon

__āpodhātu_
____

____
the Warmth Phenomenon

_tejodhātu_
____

____
the Gaseousness Phenomenon

_vāyodhātu_
____

____
the Space Element

__ākāsadhātu_
____

[quote, D.3.247]
____
the Mental Consciousness Element

_viññāṇadhātu._
____

.Illustration
====
Mental Consciousness
====

[quote, S.3.232]
____
Bhikkhus, fondness and attachment regarding the Solidness Phenomenon... the 
Liquidness Phenomenon... the Warmth Phenomenon... the Gaseousness Phenomenon... 
the Space Element... the Mental Consciousness Element is a spiritual defilement.

_Yo bhikkhave paṭhavidhātuyā chandarāgo cittasse'so upakkileso. Yo 
āpodhātuyā chandarāgo cittasse'so upakkileso yo tejodhātuyā chandarāgo 
cittasse'so upakkileso yo vāyodhātuyā chandarāgo cittasse 'so upakkileso yo 
ākāsadhātuyā chandarāgo cittasse'so upakkilesoyo viññāṇadhātuyā 
chandarāgo cittasse'so upakkileso._
____

.Illustration
====
mental consciousness
====

[quote, M.1.296]
____
When this [wretched human] body is bereft of three states -- vitality,
warmth, and mental consciousness -- it is then discarded and forsaken, left 
lying senseless like a log.

_Yadā kho āvuso imaṃ kāyaṃ tayo dhammā jahanti āyu usmā ca 
viññāṇaṃ athāyaṃ kāyo ujjhito avakkhitto seti yathā kaṭṭhaṃ 
acetanan ti._
____

.Illustration
====
mental consciousness
====

[quote, Vin.1.93]
____
When in his mother's womb the first thought has arisen, the first mental 
consciousness manifested, his birth is (to be reckoned) from that time.

_Yaṃ bhikkhave mātukucchismiṃ paṭhamaṃ cittaṃ uppannaṃ 
paṭhamaṃ viññāṇaṃ pātubhūtaṃ tadupādāya sāvassa jāti._
____

