== Vossagga

=== Renderings

- _vossagga_: generosity

- _vossagga_: relinquishment [of attachment]

- _vossagga_: granting leave

- _vossagga_: delegation

- _vossajjati_: to relinquish [attachment]

- _vossajjati_: to relinquish

=== Introduction

==== The meaning of vossaggapariṇāmiṃ

In the formula of the seven factors of enlightenment, _vossaggapariṇāmiṃ_ 
('results in relinquishment') is said to be the result of that practice:

____
In this regard a bhikkhu develops the enlightenment factor of mindfulness which 
conduces to seclusion [from sensuous pleasures and spiritually unwholesome 
factors], to non-attachment [to originated phenomena], to the ending [of 
originated phenomena], and which results in _vossagga.'_

_Idha bhikkhave bhikkhu satisambojjhaṅgaṃ bhāveti vivekanissitaṃ 
virāganissitaṃ nirodhanissitaṃ vossaggapariṇāmiṃ._
____

But the goal of the seven factors of enlightenment is also said to be 1) 
_bodha_ 2) _taṇhakkhaya,_ and 3) _vijjāvimutti_, all of which imply 
_nibbāna_:

1. They lead to enlightenment, therefore they are called factors of 
enlightenment
+
****
_Bodhāya saṃvattantīti kho bhikkhu tasmā bojjhaṅgāti vuccanti_ (S.5.83).
****

2. And what is the path and practice leading to the destruction of craving? It 
is the seven factors of enlightenment.
+
****
_Katamo ca bhikkhave maggo katamā ca paṭipadā taṇhakkhayāya 
saṃvattati: yadidaṃ satta bojjhaṅgā_ (S.5.86).
****

3. The seven factors of enlightenment, when developed and cultivated, bring to 
perfection insightfulness into reality and liberation [from perceptually 
obscuring states].
+
****
_satta bojjhaṅgā bhāvitā bahulīkatā vijjāvimuttiṃ paripūrenti_ 
(S.5.329).
****

Because _bodha_, _taṇhakkhaya_ and _vijjāvimutti_ imply _nibbāna_ it would 
be congruous if _vossagga_ was understood in the same way. How, then, should it 
be rendered? Let us consider its synonyms, _cāgo_ and _paṭinissaggo_, which 
are likewise equivalent to _nibbāna_ in the following sense:

[quote, M.3.245]
____
For this, bhikkhu, is the supreme noble relinquishment, namely the 
relinquishment of the whole phenomenon of attachment.

_Eso hi bhikkhu paramo ariyo cāgo yadidaṃ sabbūpadhipaṭinissaggo._
____

That _sabbūpadhipaṭinissaggo_ is a synonym of _nibbāna_ is demonstrated 
here:

[quote, Vin.1.5]
____
This is indeed a matter difficult to realise, namely the quelling of all 
originated phenomena, the relinquishment of the whole phenomenon of 
attachment... the Untroubled.

_Idampi kho ṭhānaṃ duddasaṃ yadidaṃ sabbasaṅkhārasamatho 
sabbūpadhipaṭinissaggo taṇhakkhayo virāgo nirodho nibbānaṃ._
____

Thus, to be equivalent to _bodha_, _taṇhakkhaya_ and _vijjāvimutti_, 
_vossaggapariṇāmiṃ_ should be rendered as 'results in the relinquishment 
&#8203;[of the whole phenomenon of attachment].'

==== Vossagga in other contexts

Having established that the object of _vossagga_ is _upadhi_, we take this as 
its object elsewhere where an object is needed, most importantly in the phrase:

[quote, S.5.197]
____
Having made the relinquishment [of attachment] the basis [for spiritual 
development]

_vossaggārammaṇaṃ karitvā._
____

See full quote below.

=== Illustrations

.Illustration
====
vossagga

generosity
====

[quote, S.5.396-7]
____
She dwells at home with a mind unblighted by stinginess, freely generous, 
liberal, taking delight in generosity, devoted to charity, delighted in giving 
and sharing.

_vigatamalamaccherena cetasā agāraṃ ajjhāvasati muttacāgā payatapāṇī 
vossaggaratā yācayogā dānasaṃvibhāgaratā._
____

.Illustration
====
vossagga

relinquishment [of attachment]
====

____
And what is the faculty of inward collectedness?

_Katamañca bhikkhave samādhindriyaṃ_
____

[quote, S.5.197]
____
In this regard, the noble disciple, having made the relinquishment [of 
attachment] the basis [for spiritual development], gains inward collectedness, 
gains mental concentration.

_idha bhikkhave ariyasāvako vossaggārammaṇaṃ karitvā labhati samādhiṃ 
labhati cittassa ekaggataṃ. Idaṃ vuccati bhikkhave samādhindriyaṃ._
____

.Illustration
====
vossajja

relinquishing [attachment]
====

[quote, S.1.106-7]
____
He should live the religious life relinquishing [attachment].

_Vossajja careyya._
____

COMMENT

_Careyya_: 'should live the religious life.' See Glossary sv _Eko care 
khaggavisāṇakappo_.

.Illustration
====
vossaṭṭha

relinquish [attachment]
====

[quote, S.3.241]
____
Bhante, what is the cause and reason why some egg-born nāgās here observe the 
Uposatha and relinquish [attachment to] their bodies?

_ko nu kho bhante hetu ko paccayo yenamidhekacce aṇḍajā nāgā uposathaṃ 
upavasanti vossaṭṭhakāyā ca bhavantī ti._
____

Comment:

Nāgās can undertake the precepts of virtue on the Uposatha days and even 
resolve to uphold the precepts at the cost of their lives (CDB p.1101 n.285).

.Illustration
====
vossajja

relinquishing
====

[quote, Sn.v.751]
____
Recognising this danger, that suffering arises dependent on spiritual 
instability, therefore having relinquished spiritual instability and ended 
karmically consequential deeds, imperturbable and free of grasping, the bhikkhu 
should mindfully fulfil the ideals of religious asceticism.

_Etamādīnavaṃ ñatvā dukkhaṃ iñjitapaccayā +
Tasmā hi ejaṃ vossajja saṅkhāre uparundhiya +
Anejo anupādāno sato bhikkhu paribbaje ti._
____

.Illustration
====
vossaggena

grant leave
====

[quote, D.3.190]
____
A master should serve his servants and employees by occasionally granting them 
leave.

_samaye vossaggena._
____

.Illustration
====
vossaggena

delegate
====

[quote, D.3.190]
____
A husband should serve his wife by delegating authority to her

_issariyavossaggena._
____

.Illustration
====
vossajjitvā

delegated
====

[quote, D.2.231]
____
Completely delegated all our responsibilities

_sabbakiccāni sammā vossajjitvā._
____

[quote, D.2.231]
____
Alas! At the very moment we had completely delegated all our responsibilities 
to Govinda the brahman, and we, provided with and possessed of the five 
varieties of sensuous pleasure, were enjoying ourselves, Govinda the brahman 
passed away.

_yasmiṃ vata bho mayaṃ samaye govinde brāhmaṇe sabbakiccāni sammā 
vossajjitvā pañcahi kāmaguṇehi samappitā samaṅgībhūtā paricārema 
tasmiṃ no samaye govindo brāhmaṇo kālakato ti._
____

