== Vyāpajjha; Vyābajjhā

=== Renderings

- _vyāpajjha_: hostility

- _vyābajjha_: affliction

=== Introduction

==== Considerable confusion: BJT editor astonished

That _vyāpajjha_ and _vyābajjha_ are hopelessly confused is expressed in the 
digital edition of the Sri Lanka Buddha Jayanti Tripiṭaka, where the editor 
comments on this quote:

____
Properly reflecting, he uses therapeutic requisites simply to ward off 
troublesome feelings that have arisen and for maximum freedom from affliction.

_Paṭisaṅkhā yoniso gilānapaccayabhesajjaparikkhāraṃ paṭisevati 
yāvadeva uppannānaṃ veyyābādhikānaṃ vedanānaṃ paṭighātāya 
avyābajjhaparamatāya._
____

However, at M.1.10 an alternative spelling occurs: _avyāpajjhaparamatāya,_ 
about which the BJT editor has this to say:

- We correct the 'p' in _avyāpajjha_ of the BJT text to 'b' in agreement with 
the PTS M1 and Nld readings. We regard _avyābajjha_ as the correct reading 
because it is derived from the basic Pāli word _vyābādha vyābādhya 
vyābajjha_. In view of this process of derivation, we opt the final reading to 
be _avyābajjha_. At the same time it is astonishing to find the derivative 
from the Pāli word _vyāpāda_ written as _vyāpajjha_. The two words appear 
to be the result of a considerable amount of mutual confusion.

==== Bodhi: similar correction

A vacillation between _savyābajjhā_ and _savyāpajjhā_ is seen in a passage 
at M.2.130, which in 2001 Bhikkhu Bodhi translated as follows:

[quote, M.2.130]
____
Great king, those gods who are still subject to affliction come back to this 
&#8203;[human] state, those gods who are no longer subject to affliction do not come 
back to this [human] state (Bodhi, 2001)

_Ye te mahārāja devā savyābajjhā te devā āgantāro itthattaṃ ye te 
devā avyābajjhā te devā anāgantāro itthattan ti._
____

But in 2005, he adopted the alternative Pāli, and translated as follows:

[quote, M.2.130]
____
Great king, those gods who are still subject to ill will come back to this 
&#8203;[human] state, those gods who are no longer subject to ill will do not come 
back to this [human] state (Bodhi, 2005).

_Ye te mahārāja devā savyāpajjhā te devā āgantāro itthattaṃ ye te 
devā avyāpajjhā te devā anāgantāro itthattan ti._
____

Although either reading could be justified, the 2001 edition is preferable for 
two reasons:

1. Non-returners do not usually proclaim themselves in terms of freedom from 
ill will. More usually they proclaim themselves in terms of freedom from 
sensuous hankering:
+
[quote, D.2.51]
____
We, dear sir, who lived the religious life under the Blessed One Vipassī have 
been reborn here having discarded sensuous hankering for sensuous pleasures.

_Te mayaṃ mārisa vipassimhi bhagavatī brahmacariyaṃ caritvā kāmesu 
kāmacchandaṃ virājetvā idhūpapannā ti._
____

2. It is in accordance with other suttas to define non-returnership in terms of 
non-affliction because non-returners have demolished all demerit in their 
lifetime, and therefore the associated affliction to be experienced:

[quote, A.5.300]
____
Whatever demeritorious karmically consequential conduct was previously 
undertaken by this [wretched human] body born of deeds, all [the consequences 
of] that must be experienced now [in this lifetime]; it will not [be able to] 
arise hereafter.' Thus developed, the liberation [from perceptually obscuring 
states] through [unlimited, all-encompassing] goodwill leads to 
non-returnership for a wise bhikkhu here who has not penetrated to a more 
exalted liberation.

_yaṃ kho me idha kiñcī pubbe iminā karajakāyena pāpakammaṃ kataṃ 
sabbaṃ taṃ idha vedanīyaṃ na taṃ anugaṃ bhavissatī ti. Evaṃ 
bhāvitā kho bhikkhave mettācetovimutti anāgāmitāya saṃvattati idha 
paññassa bhikkhuno uttariṃ vimuttiṃ appaṭivijjhato._
____

==== Confusion noted in PED

The source of the confusion between the spellings can be seen in PED's comments:

1. Vyābādha (& byābādha) [fr. vi+ā+bādh, but semantically connected with 
vi+ā+pad, as in vyāpāda & vyāpajjha

2. Avyāpajjha1 (abyābajjha) (nt.) [a + vyapajjha or bajjha, a confusion 
between the roots bādh or pad]

3. Avyāpajjha2 (abyābajjha) adj.) [either a + vyāpadya or more likely a + 
vyābādhya]

==== Resolving the confusion

We resolve the confusion as follows:

1. All _bya_- prefixes are spelt here as _vya_-

2. We spell _vyāpajjha_ with 'h.' We regard _vyāpajja_ as a misspelling. PED 
likewise does not recognise this as a word.

3. _Vyāpajjha_ ('hostility') is commonly associated with _veraṃ_ 
('unfriendliness'), implying that the words are synonyms. In the context of 
_veraṃ_ we therefore regard _vyābajjhā_ ('affliction') as a misspelling, 
and correct it to _vyāpajjhā_. For example, consider this passage:

____
To limitless beings he gives freedom from fear, unfriendliness, and hostility.

_aparimāṇānaṃ sattānaṃ abhayaṃ deti. Averaṃ deti. Avyāpajjhaṃ 
deti._
____

[quote, A.4.246]
____
... In doing so, he partakes of limitless freedom from fear, unfriendliness, 
and hostility.

_Aparimāṇānaṃ sattānaṃ abhayaṃ datvā averaṃ datvā avyāpajjhaṃ 
datvā aparimāṇassa abhayassa averassa avyāpajjhassa bhāgī hoti._
____

A misspelt variant reading is given in VRI, as follows:

- _Aparimāṇānaṃ sattānaṃ abhayaṃ datvā averaṃ datvā 
avyābajjhaṃ datvā aparimāṇassa abhayassa averassa avyābajjhassa bhāgī 
hoti._

=== Illustrations: vyāpajjhaṃ

.Illustration
====
vyāpajjhaṃ

hostility
====

• Freedom from hostility in the world is happiness, and being restrained [in 
conduct] towards living beings +
_☸ Avyāpajjhaṃ sukhaṃ loke pāṇabhutesu saṃyamo_ (Ud.10) (Vin.1.3).

.Illustration
====
vyāpajjhaṃ

hostility
====

[quote, D.1.167-8]
____
A bhikkhu develops a mind of [unlimited, all-encompassing] goodwill which is 
free of unfriendliness and hostility.

_bhikkhu averaṃ avyāpajjhaṃ mettacittaṃ bhāveti._
____

.Illustration
====
vyāpajjhaṃ

hostile
====

____
And what, Puṇṇa, is conduct that is dark with dark karmic consequences

_kammaṃ kaṇhaṃ kaṇhavipākaṃ_
____

____
In this regard, some person undertakes a hostile karmically consequential deed 
by way of body... speech... mind

_savyāpajjhaṃ kāyasaṅkhāraṃ... vacīsaṅkhāraṃ... 
manosaṅkhāraṃ abhisaṅkharoti_
____

Having done so, he is reborn in a hostile world (_savyāpajjhaṃ lokaṃ 
upapajjati_) where hostile sensations affect him (_savyāpajjhā phassā 
phusanti_) and he experiences hostile sense impressions that are exclusively 
unpleasant (_savyāpajjhaṃ vedanaṃ vedeti ekantadukkhaṃ_), as experienced 
by the beings in hell (M.1.390).

.Illustration
====
avyāpajjhena

free of hostility
====

[quote, M.1.126]
____
We shall abide pervading the whole world [of beings] with a mind of [unlimited, 
all-encompassing] goodwill, vast, exalted, unlimited, free of unfriendliness 
and hostility.

_sabbāvantaṃ lokaṃ mettāsahagatena cetasā vipulena mahaggatena 
appamāṇena averena avyāpajjhena pharitvā viharissāmāti._
____

.Illustration
====
vyāpajjhaṃ

hostile
====

[quote, M.3.52]
____
If, bhante, an assumed individuality that is hostile is brought into being, 
unconducive to inner perfection, spiritually unwholesome factors flourish and 
spiritually wholesome factors fade in him.

_savyāpajjhaṃ bhante attabhāvapaṭilābhaṃ abhinibbattayato 
apariniṭṭhitabhāvāya akusalā dhammā abhivaḍḍhanti kusalā dhammā 
parihāyanti._
____

.Illustration
====
avyāpajjhaṃ

unhostile
====

[quote, A.3.213]
____
One should develop an unhostile, beneficent attitude which leads to the world 
of the devas.

_Avyāpajjhaṃ hitaṃ cittaṃ devalokāya bhāvaye._
____

.Illustration
====
avyāpajjhā

without hostility
====

____
He has a benevolent mind and unhateful thoughts:

_Avyāpannacitto kho pana hoti appaduṭṭhamanasaṅkappo_
____

[quote, M.1.288]
____
May these creatures sustain themselves happily, and be rid of unfriendliness, 
hostility, and spiritual defilement.

_ime sattā averā avyāpajjhā anīghā sukhi attānaṃ pariharantū ti._
____

.Illustration
====
avyāpajjhā

non-hostility
====

[quote, It.31]
____
The Perfect One takes pleasure and delight in non-hostility. In doing so, this 
thought often occurs: 'By this behaviour I harm no one at all, whether weak or 
strong.'

_Avyāpajjhārāmo bhikkhave tathāgato avyāpajjharato. Tamenaṃ bhikkhave 
tathāgataṃ avyāpajjhārāmaṃ avyāpajjharataṃ esova vitakko bahulaṃ 
samudācarati: imāyāhaṃ irīyāya na kiñci vyābādhemi tasaṃ vā 
thāvaraṃ vā ti._
____

=== Illustrations: vyābajjhā

.Illustration
====
vyābajjhā

affliction
====

[quote, A.3.338]
____
Properly reflecting, he uses therapeutic requisites simply to ward off 
troublesome feelings that have arisen and for maximum freedom from affliction.

_Paṭisaṅkhā yoniso gilānapaccayabhesajjaparikkhāraṃ paṭisevati 
yāvadeva uppannānaṃ veyyābādhikānaṃ vedanānaṃ paṭighātāya 
avyābajjhaparamatāya._
____

.Illustration
====
vyābajjhaṃ

affliction
====

[quote, It.14-16]
____
The wise are reborn in a world of happiness that is free of affliction.

_Avyābajjhaṃ sukhaṃ lokaṃ paṇḍito upapajjatī tī._
____

.Illustration
====
avyābajjhaṃ

affliction
====

[quote, M.1.89-90]
____
The highest sweetness of sense impressions is freedom from affliction, I 
declare.

_Avyābajjhaparamāhaṃ bhikkhave vedanānaṃ assādaṃ vadāmi._
____

