== Vyāpāda; Vyāpanna

=== Renderings

- _vyāpanna_: unbenevolent

- _avyāpanna_: benevolent

- _vyāpāda_: ill will

- _vyāpāda_: unbenevolent

- _avyāpāda_: goodwill

- _avyāpāda_: benevolent

=== Introduction

==== Etymology: vyāpanna

_Vyāpanna_ is the past participle of _vyāpajjati_, and an adjective.

[quote, M.1.313]
____
He has an unbenevolent attitude

_vyāpannacitto hoti._
____

==== Etymology: vyāpāda

_Vyāpāda_ and _avyāpāda_ are nouns from _vyāpajjati_: ill will and 
goodwill.

==== Vyāpāda and avyāpāda: adjectives

_Vyāpāda_ and _avyāpāda_ are also adjectives: 'unbenevolent' and 
'benevolent'. For example:

[quote, S.2.151]
____
Because of the phenomenon of ill will, unbenevolent mental imagery arises.

_vyāpādadhātuṃ bhikkhave paṭicca uppajjati vyāpādasaññā._
____

[quote, D.3.215]
____
Three spiritually wholesome ways of thought: unsensuous thought, benevolent 
thought, compassionate thought.

_Tayo kusalasaṅkappā: nekkhammasaṅkappo avyāpādasaṅkappo 
avihiṃsāsaṅkapo._
____

==== Ill will: not malevolence

'Ill will' means 'lack of well-wishing,' but not necessarily 'malevolence,' as 
Horner calls it, which means the wish to harm, and would be difficult to 
distinguish from _vihiṃsā_, maliciousness.

==== Ill will is hatred

____
-- 'What do you think, Sāḷha: is there hatred?'

_Taṃ kiṃ maññatha sāḷhā atthi doso ti?_
____

-- 'Yes, bhante.

[quote, A.1.194]
____
-- 'I call it ill will, Sāḷha.

_Vyāpādo ti kho ahaṃ sāḷhā etamatthaṃ vadāmi._
____

==== Goodwill is non-hatred

____
-- 'What do you think, Sāḷha: is there non-hatred?'

_Taṃ kiṃ maññatha sāḷhā atthi adoso ti?_
____

-- 'Yes, bhante.

[quote, A.1.195]
____
-- 'I call it goodwill, Sāḷha.

_Avyāpādo ti kho ahaṃ sāḷhā etamatthaṃ vadāmi._
____

=== Illustrations: vyāpādo

.Illustration
====
vyāpādassa

ill will
====

[quote, S.5.64]
____
There is the quality of repulsiveness. Much improper contemplation in that 
regard is a condition that nourishes both the arising of unarisen ill will, and 
the increase and expansion of arisen ill will.

_Atthi bhikkhave paṭighanimittaṃ. Tattha ayoniso manasikārabahulīkāro 
ayamāhāro anuppannassa vā vyāpādassa uppādāya uppannassa vā 
vyāpādassa bhiyyobhāvāya vepullāya._
____

.Illustration
====
vyāpādo

ill will
====

[quote, D.3.248-250]
____
If the liberation [from perceptually obscuring states] through [unlimited, 
all-encompassing] goodwill is developed and cultivated, it is impossible, out 
of the question, that ill will would plague your mind.

_Aṭṭhānametaṃ āvuso anavakāso yaṃ mettāya cetovimuttiyā 
bhāvitāya... atha ca panassa vyāpādo cittaṃ pariyādāya ṭhassatī ti._
____

.Illustration
====
vyāpāda

unbenevolent
====

[quote, A.2.16]
____
He does not tolerate an arisen unbenevolent thought...

_Uppannaṃ vyāpādavitakkaṃ nādhivāseti_
____

.Illustration
====
vyāpāda

unbenevolent
====

____
Because of the phenomenon of ill will, unbenevolent mental imagery arises.

_vyāpādadhātuṃ bhikkhave paṭicca uppajjati vyāpādasaññā._
____

____
Because of unbenevolent mental imagery, unbenevolent thought arises

_vyāpādasaññaṃ paṭicca uppajjati vyāpādasaṅkappo_
____

____
Because of unbenevolent thought, unbenevolent desire arises.

_vyāpādasaṅkappaṃ paṭicca uppajjati vyāpādacchando_
____

____
Because of unbenevolent desire, unbenevolent passion arises

_vyāpādacchandaṃ paṭicca uppajjati vyāpādapariḷāho_
____

____
Because of unbenevolent passion, unbenevolent quests arise

_vyāpādapariḷāhaṃ paṭicca uppajjati vyāpādapariyesanā_
____

[quote, S.2.151]
____
Engaged in unbenevolent quests, the ignorant Everyman conducts himself wrongly 
in three ways: by body, speech, and mind.

_vyāpādapariyesanaṃ bhikkhave pariyesamāno assutavā puthujjano tīhi 
ṭhānehi micchā paṭipajjati kāyena vācāya manasā._
____

=== Illustrations: a/vyāpanna

.Illustration
====
avyāpanna

benevolent
====

____
He has a benevolent mind and unhateful thoughts:

_Avyāpannacitto kho pana hoti appaduṭṭhamanasaṅkappo_
____

[quote, M.1.288]
____
May these creatures sustain themselves happily, and be rid of unfriendliness, 
hostility, and spiritual defilement.

_ime sattā averā avyāpajjhā anīghā sukhi attānaṃ pariharantū ti._
____

.Illustration
====
vyāpanna

unbenevolent; avyāpādo, goodwill,
====

[quote, M.1.44]
____
One with an unbenevolent mind has goodwill to circumvent it.

_Vyāpannacittassa purisapuggalassa avyāpādo hoti parikkamanāya._
____

.Illustration
====
avyāpannacitto

benevolent
====

[quote, D.1.71]
____
Abandoning ill will and hatred he abides with a benevolent mind, tenderly 
concerned for the welfare of all living beings.

_Vyāpādapadosaṃ pahāya avyāpannacitto viharati 
sabbapāṇabhūtahitānukampī._
____

