== Vyāpajjati

=== Renderings

- _vyāpajjati_: to be troubled

- _vyāpajjati_: to be upset

=== Illustrations: vyāpajjati

.Illustration
====
vyāpajjati 

troubled
====

[quote, S.4.119]
____
In this regard, in seeing a visible object via the visual sense, a bhikkhu is 
not intent upon an agreeable visible object, nor troubled by a disagreeable 
visible object.

_Idha bhikkhu cakkhunā rūpaṃ disvā piyarūpe rūpe nādhimuccati 
appiyarūpe rūpe na vyāpajjati._
____

.Illustration
====
avyāpajjamāno

untroubled
====

[quote, Sn.v.1065]
____
Having [unlimited, all-encompassing] compassion, Brahman, explain the teaching 
about seclusion [from sensuous pleasures and spiritually unwholesome factors], 
which, when I understand it, then, as untroubled as space, I can live the 
religious life inwardly at peace, and free of attachment.

_Anusāsa brahme karuṇāyamāno vivekadhammaṃ yamahaṃ vijaññaṃ; +
Yathāhaṃ ākāsova avyāpajjamāno idheva santo asito careyyaṃ._
____

.Illustration
====
vyāpajjati

upset
====

[quote, A.3.181]
____
He takes offence, becomes angry, upset, and resentful. He evinces anger, 
hatred, and irritation.

_abhisajjati kuppati vyāpajjati patitthīyati kopañca dosañca appaccayañca 
pātukaroti._
____

.Illustration
====
vyāpajjeyya

upset
====

[quote, A.3.306]
____
I may stumble and fall. The food I have eaten may upset me.

_Upakkhalitvāvāhaṃ papateyyaṃ bhattaṃ vāpi me bhuttaṃ vyāpajjeyya._
____

