== Yasa

=== Renderings

- _yasa_: glory

- _yasa_: reputation

- _yasa_: prestige

- _yasa_: celebrated

- _yasa_: fame

- _ayasa_: discredit

- _ayasa_: inglorious

- _ayasa_: ingloriousness

- _ayasa_: imprestige

- _ayasa_: bad reputation

=== Introduction

==== Prestige: definition

Prestige means:

1. standing or estimation in the eyes of people: weight or credit in general 
opinion

2. commanding position in people's minds (Webster's)

==== Prestige: from previous acts of generosity

Prestige is a worldly condition that stems partly from previous acts of 
generosity:

-- Bhante, there might be two disciples equal in faith, in virtue, and in 
discernment, but one is generous while the other is not. With the demise of the 
body at death, they would both be reborn in the heavenly worlds. When they have 
become devas, would there be any difference between them?

[quote, A.3.33]
____
-- There would be, Sumanā. The generous one would surpass the other in five 
ways: in celestial life span, beauty, happiness, prestige, and authority.

_dibbena āyunā dibbena vaṇṇena dibbena sukhena dibbena yasena dibbena 
ādhipateyyena._
____

==== Loss of prestige: anger

[quote, A.4.95]
____
When a person is overcome and oppressed by anger, he loses whatever prestige he 
had acquired through diligence.

_Kodhanoyaṃ bhikkhave purisapuggalo kodhābhibhūto kodhapareto yo pi'ssa so 
hoti yaso appamādādhigato tamhāpi dhaṃsati kodhābhibhūto._
____

==== Loss of prestige: sexual intercourse

- Whoever formerly fared alone who then pursues sexual intercourse, in the 
world is called a 'lurching vehicle,' 'contemptible,' a 'common man.'

[quote, Sn.v.816-7]
____
... His earlier prestige and reputation is lost.

_Yaso kitti ca yā pubbe hāyate vāpi tassa sā._
____

==== Not clinging to prestige

Bhikkhus should not to cling to prestige:

[quote, A.4.160-1]
____
It is well for a bhikkhu to abide continuously mastering acquisition, loss, 
prestige, imprestige, honour, depreciation, unvirtuous desires and unvirtuous 
friendships that have arisen.

_Sādhu bhikkhave bhikkhu uppannaṃ lābhaṃ abhibhuyya abhibhuyya vihareyya. 
Uppannaṃ alābhaṃ... yasaṃ... ayasaṃ... sakkāraṃ... asakkāraṃ... 
pāpicchataṃ... pāpamittataṃ abhibhuyya abhibhuyya vihareyya._
____

==== Yasa: glory, atirocati

Sometimes _yasa_ is better called 'glory' because it is associated with 
_atirocati_, to shine. For example, when, due to his virtuous qualities, a 
pauper was reborn in the company of the Tāvatiṃsā devas:

[quote, S.1.232]
____
He outshone the other devas in beauty and glory.

_so aññe deve atirocati vaṇṇena ceva yasasā ca._
____

==== Yasa: glory, the waxing fortnight

Sometimes _yasa_ is associated with the moon in the waxing fortnight, and again 
must be called glory:

____
If one transgresses what is righteous through desire, hatred, fear, or 
undiscernment of reality, one's glory fades like the moon in the waning 
fortnight.

_Chandā dosā bhayā mohā yo dhammaṃ ativattati +
Nihīyati tassa yaso kālapakkheva candimā ti_
____

[quote, A.2.18]
____
If one does not transgress what is righteous through desire, hatred, fear, or 
undiscernment of reality, one's glory swells like the moon in the waxing 
fortnight.

_Chandā dosā bhayā mohā yo dhammaṃ nātivattati +
Āpūrati tassa yaso sukkapakkheva candimā ti._
____

=== Illustrations

.Illustration
====
yasasā

glory
====

[quote, D.2.208]
____
Those devas who had lived the religious life under the Blessed One, and had 
recently appeared in the Tāvatiṃsā Heaven, outshone the other devas in 
beauty and glory.

_aññe deve atirocanti vaṇṇena ceva yasasā ca._
____

.Illustration
====
yaso

glory
====

____
Bhikkhus, a noble disciple possessed of four factors is said to be well off, 
with great wealth and riches, of great glory. What four?"

_Catūhi bhikkhave dhammehi samannāgato ariyasāvako aḍḍho mahaddhano 
mahābhogo mahāyaso ti vuccati. Katamehi catūhi_
____

1. He has unshakeable faith in the [perfection of the] Buddha's [transcendent 
insight],
+
****
_buddhe aveccappasādena samannāgato hoti_
****

2. He has unshakeable faith in the [significance of the] teaching,
+
****
_Dhamme aveccappasādena samannāgato hoti_
****

3. He has unshakeable faith in the [praiseworthiness of the] community of 
disciples' [application to the practice],
+
****
_Saṅghe aveccappasādena samannāgato hoti_
****

4. He possesses the virtues dear to the Noble Ones.
+
****
_Ariyakantehi sīlehi samannāgato hoti_ (S.5.402).
****

.Illustration
====
yasasā

glory
====

When five hundred Licchavis visited the Blessed One,

- some were clothed in blue, with blue ornaments;

- some were clothed in yellow, with yellow ornaments;

- some were clothed in red, with red ornaments;

- some were clothed in white, with white ornaments.

[quote, A.3.239]
____
Yet the Blessed One outshone them all in beauty and glory.

_Tyāssudaṃ bhagavā atirocati vaṇṇena ce va yasasā ca._
____

.Illustration
====
yasasā

glory
====

The Blessed One was dwelling at Campā together with many bhikkhus, lay 
followers, and devas:

[quote, S.1.195]
____
He outshone them in beauty and glory.

_atirocati vaṇṇena ceva yasasā ca._
____

.Illustration
====
yaso

glory
====

People who are

- energetic,

- attentive,

- pure in conduct,

- careful in conduct,

- restrained,

- of right livelihood,

- diligent,

[quote, Dh.v.24]
____
their glory grows.

_yaso'bhivaḍḍhati._
____

.Illustration
====
yasavā

glorious
====

[quote, A.3.51]
____
The person who gives the best, the giver of the foremost, the giver of the 
excellent, is long-lived and glorious wherever he is reborn.

_Yo aggadāyī varadāyī seṭṭhadāyī ca yo naro +
Dīghāyu yasavā hoti yattha yatthūpapajjatī ti._
____

.Illustration
====
yasaṃ

prestige
====

Regarding a head-anointed _khattiya_ king:

- he is of pure descent on both his maternal and paternal sides

- he is rich, with great wealth and property

- he is powerful, possessing an army of four divisions

- his counselor is wise, competent, and intelligent.

[quote, A.3.151]
____
These four qualities enhance his prestige.

_Tassime cattāro dhammā yasaṃ paripācenti._
____

.Illustration
====
yaso

prestige
====

[quote, A.2.32]
____
When a man dwells in a suitable location, making friends with Noble People, and 
is endowed with a rightly directed disposition, having made merit in the past, 
then grain, wealth, prestige, and a good reputation, along with happiness 
accrue to him.

_Patirūpe vase dese ariyamittakaro siyā +
Sammāpaṇidhisampanno pubbe puññakato naro +
Dhaññaṃ dhanaṃ yaso kitti sukhañcetaṃdhivattatī ti._
____

.Illustration
====
yaso

prestige
====

____
A noble disciple possessing four qualities is practising a way that brings 
prestige and leads to heaven. What four?

_yasopaṭilābhiniṃ saggasaṃvattanikaṃ._
____

[quote, A.2.65]
____
In this regard, a noble disciple serves the community of bhikkhus with robe 
material, almsfood, abodes, and therapeutic requisites.

_Idha gahapati ariyasāvako bhikkhusaṅghaṃ paccupaṭṭhito hoti 
cīvarena... piṇḍapātena... senāsanena... 
gilānapaccayabhesajjaparikkhārena._
____

.Illustration
====
yaso

prestige
====

[quote, A.3.40]
____
By giving, he becomes dear and many consort with him. He attains a good 
reputation and his prestige increases.

_Dadaṃ piyo hoti bhajanti naṃ bahū kittiñca pappoti yasobhivaḍḍati._
____

.Illustration
====
_ayaso_ imprestige; yaso

prestige
====

[quote, A.2.188]
____
Eight worldly conditions whirl around the world [of beings], and the world [of 
beings] whirls around eight worldly conditions, namely: acquisition and loss, 
imprestige and prestige, criticism and praise, pleasure and pain.

_aṭṭha lokadhammā lokaṃ anuparivattanti loko ca aṭṭha lokadhamme 
anuparivattati: lābho ca alābho ca ayaso ca yaso ca nindā ca pasaṃsā ca 
sukhañca dukkhañcā ti._
____

.Illustration
====
yase__

__ prestige
====

[quote, Th.v.664-5]
____
Not to acquisition nor loss, not to imprestige nor reputation, not to criticism 
nor praise, not to pain nor pleasure, to nothing do they cleave, as a waterdrop 
does not cleave to a lotus-leaf.

_Na heva lābhe nālābhe n'ayase na ca kittiyā +
Na nindāyaṃ pasaṃsāya na te dukkhe sukhamhi ca. +
Sabbattha te na limpanti udabindu va pokkhare._
____

.Illustration
====
yaso__

__ prestige
====

____
Now, acquisition arises for a learned noble disciple. He reflects, 'Acquisition 
has arisen for me. He discerns it according to reality as unlasting, 
existentially void, and destined to change...

_Sutavato ca kho bhikkhave ariyasāvakassa uppajjati lābho. So iti 
paṭisañcikkhati; uppanto kho me ayaṃ lābho so ca kho anicco dukkho 
vipariṇāmadhammoti yathābhūtaṃ pajānāti_
____

... Loss arises... Prestige arises... Imprestige arises... Criticism arises... 
Praise arises... Pleasure arises... Pain arises... (S.5.158).

.Illustration
====
_yaso

_ prestige
====

____
Insignificant is the loss of prestige. The worst thing to lose is wisdom.

_Appamattikā esā bhikkhave parihāni yadidaṃ yasoparihāni. Etaṃ 
patikiṭṭhaṃ bhikkhave parihānīnaṃ yadidaṃ paññāparihānīti._
____

[quote, A.1.15]
____
Insignificant is the increase in prestige. The best thing to increase is wisdom.

_Appamattikā esā bhikkhave vuddhi yadidaṃ yasovuddhi. Etadaggaṃ bhikkhave 
vuddhīnaṃ yadidaṃ paññāvuddhi._
____

.Illustration
====
yasaṃ__

__ prestige
====

[quote, D.3.192]
____
Kind and friendly, approachable, free of stinginess, a guide, teacher, and 
diplomat, such a person attains prestige.

_Saṅgāhako mittakaro vadaññū vītamaccharo +
Netā vinetā anunetā tādiso labhate yasaṃ._
____

.Illustration
====
yasassi

prestigious
====

[quote, A.5.137]
____
A noble disciple who grows in wealth and grain, in children, wives, and 
livestock, is wealthy and prestigious, and is venerated by relatives, friends, 
and royalty.

_Sa bhogavā hoti yasassi pūjito ñātīhi mittehi athopi rājuhi._
____

.Illustration
====
yasa

prestige
====

____
Among all the teachers now existing in the world, Cunda, I see none who has 
attained to such gains and prestige as I have.

_Yāvatā kho cunda etarahi satthāro loke uppannā nāhaṃ cunda aññaṃ 
ekasatthārampi samanussami evaṃ lābhaggayasaggappattaṃ yatharivāhaṃ_
____

[quote, D.3.126]
____
Of all the orders and groups in the world, I see none attained to such gains 
and prestige as the community of bhikkhus.

_Yāvatā kho pana cunda etarahi saṅgho vā gaṇo vā loke uppanno nāhaṃ 
cunda aññaṃ ekasaṅghampī samanupassāmi evaṃ lābhaggayasaggappattaṃ 
yatharivāyaṃ cunda bhikkhusaṅgho._
____

.Illustration
====
yasa

celebrated
====

[quote, A.3.114]
____
He is well-known and celebrated and has a following of many people, including 
householders and ascetics.

__Ñāto hoti yasassī gahaṭṭhapabbajitānaṃ bahujanaparivāro._
____

.Illustration
====
yaso

fame
====

-- Who are making such an uproar, Nāgita, like fishermen with a haul of fish?

-- Bhante, brahman householders have brought food to offer to the Blessed One 
and the community of bhikkhus.

[quote, A.3.31]
____
-- Let me never attain fame, Nāgita! May fame never reach me!

_māhaṃ nāgita yasena samāgamo mā ca mayā yaso._
____

.Illustration
====
ayasaṃ

inglorious
====

When her sister, the bhikkhunī Sundarīnandā, became pregnant, the bhikkhunī 
Thullanandā explained why she had kept it secret:

____
Whatever is criticism for her is criticism for me; whatever is disgrace for her 
is disgrace for me; whatever is inglorious for her is inglorious for me; 
whatever is a loss for her is a loss for me.

_Yo etissā avaṇṇo mayheso avaṇṇo yā etissā akitti mayhesā akitti yo 
etissā ayaso mayheso ayaso yo etissā alābho mayheso alābho_
____

[quote, Vin.4.216]
____
... How can I, noble ladies, speak to others of my own blameworthiness, my own 
disgrace, my own ingloriousness, my own loss?

_kyāhaṃ ayye attano avaṇṇaṃ attano akittiṃ attano ayasaṃ attano 
alābhaṃ paresaṃ ārocessāmī ti._
____

.Illustration
====
ayasaṃ

discredit
====

____
If a bhikkhu arouses disdain in others for a bhikkhu, or if he criticises that 
bhikkhu

_ujjhāpeti vā khīyati vā_
____

____
desiring to bring him blame

_avaṇṇaṃ kattukāmo_
____

____
desiring to bring him discredit,

_ayasaṃ kattukāmo_
____

____
desiring to bring him shame

_maṅku kattukāmo_
____

it is an offence of pācittiya (Vin.4.38).

.Illustration
====
āyasakayyaṃ

bad reputation
====

[quote, A.4.95]
____
Maddened by anger he acquires a bad reputation.

_Kodhasammadasammatto āyasakayyaṃ nigacchati._
____

.Illustration
====
yasasā

reputation
====

[quote, D.1.137]
____
Through an army with its four divisions that is loyal and dependable, it seems 
he overcomes his enemies through his reputation.

_caturaṅginiyā senāya samannāgato assavāya ovādapaṭikarāya sahati 
maññe paccatthike yasasā._
____

.Illustration
====
yaso

reputation
====

[quote, D.1.117]
____
If anyone were despised by this company, his reputation would suffer, and then 
his income would suffer, for our income depends on the gaining of a reputation.

_Yaṃ kho panāyaṃ parisā paribhaveyya yaso pi tassa hāyetha. Yassa kho 
pana yaso hāyetha bhogā pi tassa hāyeyyuṃ. Yasoladdhā kho panamhākaṃ 
bhogā._
____

