== Yogakkhema

=== Renderings

- _yogakkhema_: safety from the danger of bondage [to individual existence]

- _yogakkhemin_: one who has reached safety from the danger of bondage [to 
individual existence]

- _khemin_: one who has reached safety from the danger of bondage [to 
individual existence]

- _khemattaṃ_: one who has reached safety from the danger of bondage [to 
individual existence]

=== Introduction

==== Yoga: states of bondage [to individual existence]

In relation to _yogakkhema_, _yoga_ means the four states of bondage [to 
individual existence]. These are listed in the _Yoga Sutta_ (A.2.10), as 
follows:

1. the bondage [to individual existence] that arises from [attachment to] 
sensuous pleasure
+
****
_kāmayogo_
****

2. the bondage [to individual existence] that arises from [attachment to] 
states of individual existence
+
****
_bhavayogo_
****

3. the bondage [to individual existence] that arises from dogmatism
+
****
_diṭṭhiyogo_
****

4. the bondage [to individual existence] that arises from uninsightfulness into 
reality
+
****
_avijjāyogo_
****

This issue is discussed sv _Yoga_.

==== Khema: safety

_Khema_ means safe or safety (see sv _Khema_).

[quote, Dh.v.189]
____
Those are not safe refuges. Those are not the supreme refuge.

_Netaṃ kho saraṇaṃ khemaṃ netaṃ saraṇamuttamaṃ._
____

[quote, A.3.104]
____
In a time of peril, people migrate to places of safety

_Bhaye kho pana sati manussā yena khemaṃ tena saṅkamanti._
____

==== Safety from [the danger of] bondage [to individual existence]

Bondage [to individual existence] (_yoga_) is a danger because it involves 
being tethered to unvirtuous, spiritually unwholesome factors. The unpleasant 
consequences of this are described in the _Yoga Sutta_, as follows:

[quote, A.2.11]
____
He is tethered to unvirtuous, spiritually unwholesome factors that are defiling 
and which lead to renewed states of individual existence, suffering, unpleasant 
karmic consequences, and future birth, old age, and death. Thus he is called 
one who has not reached safety from the danger of bondage [to individual 
existence].

_Saṃyutto pāpakehi akusalehi dhammehi saṅkilesikehi ponobhavikehi sadarehi 
dukkhavipākehi āyatiṃ jātijarāmaraṇikehi tasmā ayogakkhemī ti 
vuccati._
____

Therefore _yogakkhema_ does not mean safety from bondage [to individual 
existence], but safety from the danger of bondage [to individual existence].

==== Yogakkhemī = 'one who has reached safety'

One who realises _yogakkhema_ is called _yogakkhemī_ which could mean either:

- one who is safe from the danger of bondage [to individual existence], or,

- one who has reached safety from the danger of bondage [to individual 
existence]

But _yogakkhema_ occurs in the phrases with the verbs _ārādhayanti_ and 
_nānupāpuṇāti_, which indicates that _yogakkhema_ is something one 
attains, but does not become:

[quote, It.111]
____
They fathom the true teaching; both attain unsurpassed safety from the danger 
of bondage [to individual existence].

__ārādhayanti saddhammaṃ yogakkhemaṃ anuttaraṃ._
____

[quote, M.1.105]
____
He does not reach unsurpassed safety from the danger of bondage [to individual 
existence]

_anuttaraṃ yogakkhemaṃ nānupāpuṇāti._
____

Therefore _yogakkhemī_ means one who has reached safety from the danger of 
bondage [to individual existence]. One does not oneself become absolutely safe. 
Being _yogakkhemī_ is not a personal attainment.

==== Khemī and khematta: abbreviations for yogakkhemī

_Khemī_ and _khematta_ occur in verses and by implying _yogakkhemī_, they can 
be taken as such because the Buddha offers no other safety.

[quote, S.1.53-4]
____
Not apart from enlightenment and austerity, not apart from restraint of the 
sense faculties [from attraction and repulsion, through mindfulness], not apart 
from relinquishing all, do I see any safety for living beings.

_nāññatra bojjhā tapasā nāññatra indriyasaṃvarā +
Nāññatra sabbanissaggā sotthiṃ passāmi pāṇinanti._
____

_Khematta_ occurs just once in the scriptures; _khemī_ occurs twice. The words 
occur as follows:

[quote, Sn.v.145]
____
May all creatures be happy and safe [from the danger of bondage to individual 
existence]. May they be happy.

_Sukhino va khemino hontu sabbe sattā bhavantu sukhitattā._
____

[quote, Dh.v.258]
____
One who has reached safety from the danger of bondage [to individual 
existence], and who is unhating and fearless is called wise.

_Khemī averī abhayo paṇḍito ti pavuccati._
____

[quote, S.1.112]
____
Though they seek him everywhere, Māra and his army do not find him, one thus 
unattached, who has reached safety from the danger of bondage [to individual 
existence], who has transcended all ties to individual existence.

_Evaṃ virattaṃ khemattaṃ sabbasaṃyojanātigaṃ +
Anvesaṃ sabbaṭhānesu mārasenāpi nājjhagāti._
____

=== Illustrations

.Illustration
====
yogakkhemino

reached safety from the danger of bondage [to individual existence]
====

[quote, It.50]
____
Beings who are tethered [to individual existence] by the tie of craving, whose 
minds are attached to various states of individual existence, are tethered [to 
individual existence] by Māra's tie. They have not reached safety from the 
danger of bondage [to individual existence]. [Such] beings follow the round of 
birth and death, and go to rebirth and death.

_Taṇhāyogena saṃyuttā rattacittā bhavābhave +
Te yogayuttā mārassa ayogakkhemino janā +
Sattā gacchanti saṃsāraṃ jātimaraṇagāmino._
____

.Illustration
====
yogakkhemaṃ

safety from the danger of bondage [to individual existence]
====

[quote, It.111]
____
Householders and ascetics alike, each supported by the other, both fathom the 
true teaching; both attain unsurpassed safety from the danger of bondage [to 
individual existence].

_sāgārā anagārā ca ubho aññoññanissitā; ārādhayanti saddhammaṃ 
yogakkhemaṃ anuttaraṃ._
____

