== Yogo karaṇīyo

=== Renderings

- _yogo karaṇīyo_: an effort should be made [to profoundly understand this]

- _yogo karaṇīyo_: an effort should be made [to abandon this].

- _yogo karaṇīyo_: an effort should be made [to realise this].

- _yogo karaṇīyo_: an effort should be made [to develop this].

- _yogo karaṇīyo_: should endeavour [to study and master]

- _yogo karaṇīyo_: should endeavour [to attain]

=== Introduction

==== Yogo karaṇīyo: which infinitive?

_Yogo karaṇīyo_ commonly occurs with a nominative, locative, or 
instrumental, but never with an infinitive. Therefore the phrase _Idaṃ 
dukkhan ti yogo karaṇīyo_ strictly means, 'This is suffering. An effort 
should be made.' But what effort? To see? To understand? To realise?

==== In parenthesis: to profoundly understand, abandon, realise, develop

The _Pariññeyya Sutta_ (S.5.436) explains _yogo karaṇīyo_ in the context 
of the four noble truths, and therefore shows in this context how it should be 
parenthesised, as follows:

____
Of these four noble truths, there is a noble truth to be profoundly understood, 
a noble truth to be abandoned, a noble truth to be realised, a noble truth to 
be developed.

_Imesaṃ kho bhikkhave catunnaṃ ariyasaccānaṃ atthi ariyasaccaṃ 
pariññeyyaṃ atthi ariyasaccaṃ pahātabbaṃ atthi ariyasaccaṃ 
sacchikātabbaṃ atthi ariyasaccaṃ bhāvetabbaṃ_
____

____
What is the noble truth to be profoundly understood?

_Katamañca bhikkhave ariyasaccaṃ pariññeyyaṃ_
____

____
Suffering is a noble truth to be profoundly understood.

_dukkhaṃ bhikkhave ariyasaccaṃ pariññeyyaṃ_
____

____
The origin of suffering is a noble truth to be abandoned.

_dukkhasamudayo ariyasaccaṃ pahātabbaṃ_
____

____
The ending of suffering is a noble truth to be realised.

_dukkhanirodho ariyasaccaṃ sacchikātabbaṃ_
____

____
The practice leading to the ending of suffering is a noble truth to be 
developed.

_dukkhanirodhagāminī paṭipadā ariyasaccaṃ bhāvetabbaṃ._
____

____
Therefore, bhikkhus:

_Tasmātiha bhikkhave_
____

____
'This is suffering': an effort should be made [to profoundly understand this]._

_idaṃ dukkhan ti yogo karaṇīyo_
____

____
'This is the origin of suffering': an effort should be made [to abandon this]._

_ayaṃ dukkhasamudayo ti yogo karaṇīyo_
____

____
'This is the ending of suffering': an effort should be made [to realise this]._

_ayaṃ dukkhanirodhoti yogo karaṇīyo_
____

[quote, S.5.436]
____
'This is the practice leading to the ending of suffering': an effort should be 
made [to develop this]._

_ayaṃ dukkhanirodhagāminī paṭipadā ti yogo karaṇīyoti._
____

==== In parenthesis: to study and master

The _Gulissāni Sutta_ says:

[quote, M.1.472]
____
A forest bhikkhu should endeavour [to study and master] advanced aspects of the 
teaching and discipline

_Āraññakenāvuso bhikkhunā abhidhamme abhivinaye yogo karaṇīyo._
____

The parenthesis 'to study and master' comes from the _Āṇi Sutta_, which says:

[quote, S.2.267]
____
When those discourses spoken by the Perfect One that are profound, profound in 
meaning, transcendental, connected with the [perception of the] absence [of any 
abiding phenomena] are being recited, we will really listen, lend an ear, and 
apply our minds to understand [them], and we will think those teachings should 
be studied and mastered (_uggahetabbaṃ pariyāpuṇitabbaṃ_). Thus should 
you train yourselves.

_ye te suttantā tathāgatabhāsitā gambhīrā gambhīratthā lokuttarā 
suññatapaṭisaṃyuttā tesu bhaññamānesu sussusissāma sotaṃ 
odahissāma aññācittaṃ upaṭṭhāpessāma te ca dhamme uggahetabbaṃ 
pariyāpuṇitabbaṃ maññissāmā ti. Evaṃ hi vo bhikkhave sikkhitabbanti._
____

==== In parenthesis: to attain

The _Gulissāni Sutta_ says:

[quote, M.1.472]
____
A forest bhikkhu should endeavour [to attain] those immaterial states of 
awareness, those peaceful states of refined awareness that transcend the 
refined material states of awareness.

_Āraññakenāvuso bhikkhunā ye te santā vimokkhā atikkamma rūpe āruppā 
tattha yogo karaṇīyo._
____

The parenthesis 'to attain' (_lābhī ceva hoti_) comes from the 
_Tatiyasamādhi Sutta_ (A.2.94) which says a bhikkhu should ask how to attain 
states of inward composure.

[quote, A.2.92]
____
Later on he attains inward calm.

_So aparena samayena... lābhī ca ajjhattaṃ cetosamathassa._
____

==== In parenthesis: to attain

The _Gulissāni Sutta_ says:

[quote, M.1.472]
____
A forest bhikkhu should endeavour [to attain] a superhuman attainment

_Āraññakenāvuso bhikkhunā uttarimanussadhamme yogo karaṇīyo._
____

The parenthesis 'to attain' (_adhigato_) comes from the _Dasadhamma Sutta_:

[quote, A.5.87]
____
One who has gone forth [into the ascetic life] should frequently reflect: 'Have 
I attained (_adhigato_) a superhuman attainment of knowledge and vision such 
that when questioned in my last days by my companions in the religious life, I 
will not be ashamed?'

_Atthinu kho me uttarimanussadhammā alamariyañāṇadassana viseso adhigato 
sohaṃ pacchime kāle sabrahmacārīhi puṭṭho na maṅkubhavissāmī ti 
pabbajitena abhiṇhaṃ paccavekkhitabbaṃ._
____

==== With instrumental case: to attain

In the following quote, the instrumental _ñāṇāya yogo karaṇīyo_ 
indicates 'for the sake of,' which supports our parenthesising with the 
infinitive 'to attain:'

[quote, S.2.129]
____
Bhikkhus, one who does not know and see according to reality old age and death 
should endeavour [to attain] knowledge of old age and death according to reality

_jarāmaraṇaṃ bhikkhave ajānatā apassatā yathābhūtaṃ jarāmaraṇe 
yathābhūtaṃ ñāṇāya yogo karaṇīyo._
____

This parenthesis is further justified by the _Dasadhamma Sutta_ mentioned 
above, where _ñāṇa_ is linked to _adhigato_:

[quote, A.5.87]
____
Have I attained (_adhigato_) a superhuman attainment of knowledge and vision

_Atthinu kho me uttarimanussadhammā alamariyañāṇadassana viseso adhigato._
____

==== With instrumental case: to attain

In the following quote, the instrumental _adhipaññādhammavipassanāya yogo 
karaṇīyo_ again indicates 'for the sake of,' which supports our again 
parenthesising with the infinitive 'to attain:'

[quote, A.2.93]
____
The person who attains inward calm, but not the factors of higher penetrative 
discernment and insightfulness, having firmly established inward calm, should 
endeavour [to attain] the factors of higher penetrative discernment and 
insightfulness.

_Tatra bhikkhave yvāyaṃ puggalo lābhī hoti ajjhattaṃ cetosamathassa na 
lābhī adhipaññādhammavipassanāya tena bhikkhave puggalena ajjhattaṃ 
cetosamathe patiṭṭhāya adhipaññādhammavipassanāya yogo karaṇīyo._
____

This parenthesis is further justified by the occurrence in the sentence of 
_lābhī hoti_, 'he attains.'

