== Yoniso

=== Renderings

- _yoniso_: proper

- _yoniso_: properly

- _yoniso_: appropriately

=== Illustrations

.Illustration
====
yoniso

properly
====

[quote, Th.v.77]
____
Formely this mind roamed where it wanted, where it liked, as it pleased. Now I 
shall control it properly, as a mahout controls an elephant in rut.

_Idaṃ pure cittamacari cārikaṃ yenicchakaṃ yatthakāmaṃ yathāsukhaṃ 
+
Tadajjahaṃ niggahessāmi yoniso hatthippabhinnaṃ viya aṅkusaggaho ti._
____

.Illustration
====
ayoniso

improper
====

[quote, Th.v.291]
____
The fool who hurries at the time for going slowly and dawdles at the time for 
haste, goes to misery due to improper management of himself.

_Yo dandhakāle tarati taraṇīye ca dandhaye +
Ayoniso saṃvidhānena bālo dukkhaṃ nigacchati._
____

.Illustration
====
yoniso

properly
====

[quote, Th.v.347]
____
I properly reflected on the truth and reality of the matter

_Tathaṃ yāthāvakaṃ atthaṃ yoniso paccavekkhisaṃ._
____

.Illustration
====
yoniso

properly
====

[quote, Vin.2.291-2]
____
These ascetic disciples of the Sakyans' Son use everything properly; they do 
not let things go to waste.

_Atha kho rājā udeno sabbevime samaṇā sakyaputtiyā yoniso upanenti. Na 
kulavaṃ gamentīti._
____

.Illustration
====
yoniso

proper
====

[quote, D.1.117]
____
Soṇadaṇḍa is a fool, he has no sense: he can't put a proper question to 
the ascetic Gotama.

_bālo soṇadaṇḍo brāhmaṇo abyatto nāsakkhi samaṇaṃ gotamaṃ 
yoniso pañhaṃ pucchitun ti._
____

.Illustration
====
ayoniso

improperly
====

[quote, M.3.138]
____
If one lives the religious life improperly, one will not procure any benefit.

_ayoniso brahmacariyaṃ caranti abhabbā phalassa adhigamāya._
____

.Illustration
====
yoni

proper
====

[quote, M.3.141]
____
Suppose a man needing milk... pulled a recently-calved cow by her horn... he 
would still be unable to draw milk. Why is that? Because that is not the proper 
way to draw milk.

_Seyyathā pi bhūmija puriso khīratthiko... gāviṃ taruṇavacchaṃ 
visāṇato āviñcheyya... abhabbo khīrassa adhigamāya. Taṃ kissa hetu? 
Ayoni hesā bhūmija khīrassa adhigamāya._
____

.Illustration
====
yoniso

properly
====

[quote, M.3.134]
____
Properly reflecting you should use almsfood not for fun, not for exuberance, 
not for the sake of comeliness and good looks, but just for the maintenance and 
nourishment of this [wretched human] body for restraining its troublesomeness, 
for supporting the religious life.

_Paṭisaṅkhā yoniso āhāraṃ āhāreyyāsi neva davāya na madāya na 
maṇḍanāya na vibhūsanāya yāvadeva imassa kāyassa ṭhitiyā yāpanāya 
vihiṃsūparatiyā brahmacariyānuggahāya. Iti purāṇañca vedanaṃ 
paṭihaṅkhāmi. Navañca vedanaṃ na uppādessāmi. Yātrā ca me 
bhavissati anavajjatā ca phāsuvihāro cāti._
____

.Illustration
====
yoniso

properly
====

[quote, S.3.140]
____
Bhikkhus, suppose that this river Ganges was carrying along a large lump of 
froth. A clear-sighted man would inspect it, consider it, and properly 
investigate it. As he does so, it would appear to be empty, hollow, 
insubstantial. For what substantial reality could there be in a lump of froth?

_Seyyathā pi bhikkhave ayaṃ gaṅgānadī mahantaṃ pheṇapiṇḍaṃ 
āvaheyya tamenaṃ cakkhumā puriso passeyya nijjhāyeyya yoniso 
upaparikkheyya tassa taṃ passato nijjhāyato yoniso upaparikkhato 
rittakaññeva khāyeyya tucchakaññe va khāyeyya asārakaññeva khāyeyya 
kiṃ hi siyā bhikkhave pheṇapiṇḍe sāro?._
____

.Illustration
====
yoniso

properly
====

[quote, A.3.387]
____
In this regard a bhikkhu, properly reflecting, abides with the faculty of sight 
restrained through restraint [of attraction and repulsion, through mindfulness].

_idha bhikkhave bhikkhū paṭisaṅkhā yoniso cakkhundriyasaṃvarasaṃvuto 
viharati._
____

.Illustration
====
yoniso

proper
====

[quote, Vin.1.22; S.1.105]
____
Through proper contemplation, through proper and right inward striving, I 
attained and realised the unsurpassed liberation [from perceptually obscuring 
states].

_mayhaṃ kho bhikkhave yoniso manasikārā yoniso sammappadhānā anuttarā 
vimutti anuppattā anuttarā vimutti sacchikatā._
____

.Illustration
====
yoniso

proper
====

____
There is the quality of loveliness.

_Atthi bhikkhave subhanimittaṃ._
____

[quote, S.5.64]
____
Much improper contemplation in that regard is a condition that nourishes both 
the arising of unarisen sensuous hankering, and the increase and expansion of 
arisen sensuous hankering.

_Tattha ayoniso manasikārabahulīkāro ayamāhāro anuppannassa vā 
kāmacchandassa uppādāya uppannassa vā kāmacchandassa bhiyyobhāvāya 
vepullāya._
____

.Illustration
====
yoniso

proper
====

____
What things should a virtuous bhikkhu properly contemplate?"

_sīlavatā āvuso sāriputta bhikkhunā katame dhammā yoniso manasikātabbā 
ti_
____

[quote, S.3.167]
____
A virtuous bhikkhu should properly contemplate the five aggregates as being 
unlasting, existentially void, an illness, a carbuncle, a [piercing] arrow, 
suffering, an affliction, alien, destined to decay, void [of personal 
qualities], void of personal qualities.

_Sīlavatāvuso koṭṭhata bhikkhunā pañcupādānakkhandhā aniccato 
dukkhato rogato gaṇḍato sallato aghato ābādhato parato palokato suññato 
anattato yoniso manasikātabbā._
____

.Illustration
====
yoniso

proper
====

[quote, A.5.113]
____
What is the condition that nourishes lack of mindfulness and full 
consciousness? Improper contemplation, one should reply

_ko cāhāro asatāsampajaññassa: ayoniso manasikārotissa vacanīyaṃ._
____

.Illustration
====
yoniso

proper
====

[quote, A.1.200]
____
What is the cause and reason that unarisen undiscernment of reality arises, or 
that arisen undiscernment of reality increases and expands? Improper 
contemplation, one should reply.

_Ko panāvuso hetu ko paccayo yena anuppanno vā moho uppajjati uppanno vā 
moho bhiyyobhāvāya vepullāya saṃvattatī ti? Ayoniso manasikārotissa 
vacanīyaṃ._
____

.Illustration
====
yoniso

proper
====

[quote, D.3.214]
____
Being quickened by situations that are dismaying, and the proper striving in 
one who is thus quickened.

_saṃvego ca saṃvejanīyesu ṭhānesu saṃviggassa ca yoniso padhānaṃ._
____

.Illustration
====
yoniso

properly
====

[quote, Th.v.1116]
____
Properly regard the [five grasped] aggregates as suffering, and abandon that 
from which suffering arises.

_Dukkhan ti khandhe paṭipassa yoniso yato ca dukkhaṃ samudeti taṃ jaha._
____

.Illustration
====
ayoniso

inappropriately
====

[quote, D.2.338]
____
What fools these border folk are! How can they possibly search so 
inappropriately for the sound of the trumpet?

_yāvabālā ime paccantajānapadā manussā. Kathaṃ hi nāma ayoniso 
saṅkhasaddaṃ gavesissantī ti._
____

.Illustration
====
ayoniso

inappropriately
====

[quote, M.3.208]
____
I knew the worthless man Udāyī would inappropriately interfere right now.

_Aññāsiṃ kho ahaṃ ānanda idānevāyaṃ udāyī moghapuriso 
ummujjamāno ayoniso ummujjissatī ti._
____

