== Ñāya

=== Renderings

- _ñāya_: the noble practice

- _ñāya_: the correct approach

- _ñāya dhamma_: the noble practice

- _ariya ñāya_: the noble practice

- _ariya ñāya_: the noble doctrine

=== Introduction

==== Ñāya: noble practice

_Ñāya_ occurs either alone or with _ariyo_ or _dhamma_. These words mean:

- _ñāya_: 'noble practice'

- _ariyo_: 'noble'

- _dhamma_: 'practice'

Therefore any combination of these words usually means 'the noble practice.' 
But if _ñāya_ means 'noble practice,' and _dhamma_ means 'practice,' then 
_dhamma_ is redundant.

[quote, A.2.37]
____
He explained the noble practice which is of benefit to devas and men

_Hitaṃ devamanussānaṃ ñāyaṃ dhammaṃ pakāsayī._
____

[quote, S.5.19]
____
He fulfils the noble practice that is spiritually wholesome.

__ārādhako hoti ñāyaṃ dhammaṃ kusalan ti._
____

Bodhi incorporates the redundancy by using a comma:

[quote, Bodhi, A.2.37]
____
He revealed the Dhamma, the method, for the benefit of devas and humans

_Hitaṃ devamanussānaṃ ñāyaṃ dhammaṃ pakāsayī._
____

[quote, Bodhi, S.5.19]
____
He attains the method, the Dhamma that is wholesome.

__ārādhako hoti ñāyaṃ dhammaṃ kusalan ti._
____

==== The noble practice: definition

The noble practice means 'practices that are virtuous and spiritually 
wholesome':

____
He applies himself to the welfare and happiness of the manyfolk.

_bahujanahitāya paṭipanno hoti bahujanasukhāya_
____

[quote, A.2.36]
____
... By him are many folk established in the noble practice, namely in the 
aggregate of practices that are virtuous and spiritually wholesome.

_bahu'ssa janatā ariye ñāye patiṭṭhāpitā yadidaṃ kalyāṇadhammatā 
kusaladhammatā._
____

Comments:

1. The -_tā_ suffix denotes multitude, collection (PGPL: para 581).

2. Whatever there is in my family that is suitable for offering, all that I 
share unreservedly with those who are virtuous and of a virtuous moral nature.
+
****
_Yaṃ kho pana kiñci kule deyyadhammaṃ sabbaṃ taṃ appaṭivibhattaṃ 
sīlavantehi kalyāṇadhammehī ti_ (S.5.397).
****

==== Ñāya: 'correct approach'

A different meaning for _ñāya_ is indicated in the story about 
Medakathālikā, the acrobat's apprentice (S.5.168) where it means 'correct 
approach.' See Illustrations.

==== Ariyo ñāyo: the noble doctrine

_Ariyo ñāyo_ in reference to dependent origination (_paṭiccasamuppāda_ 
S.2.70) means 'noble doctrine':

____
'the noble doctrine that one has clearly seen and correctly penetrated by 
penetrative discernment'

_ariyo ñāyo paññāya sudiṭṭho hoti suppaṭividdho_
____

_Ñāyo_ is properly called 'doctrine' because it is equivalent to _dhamma_ 
that the Buddha used, again in reference to dependent origination:

____
It is through not fathoming, not penetrating this doctrine that this generation 
is tangled up like string

_etassa ānanda dhammassa ananubodhā appaṭivedhā evamayaṃ pajā 
tantākulakajātā_
____

In both cases dependent origination is a doctrine to be penetrated.

=== Illustrations

.Illustration
====
ñāya

noble practice
====

____
The community of the Blessed One's disciples is applied to an excellent 
practice,

_supaṭipanno bhagavato sāvakasaṅgho_
____

____
The community of the Blessed One's disciples is applied to the correct practice,

_ujupaṭipanno bhagavato sāvakasaṅgho_
____

____
The community of the Blessed One's disciples is applied to the noble practice.

__ñāyapaṭipanno bhagavato sāvakasaṅgho_
____

[quote, S.5.343]
____
The community of the Blessed One's disciples is applied to a proper practice.

_sāmīcipaṭipanno bhagavato sāvakasaṅgho._
____

.Illustration
====
ñāyassa

noble practice
====

[quote, S.5.142]
____
This is the one-destination path... for acquiring the noble practice, for 
realising the Untroubled, namely, the [contemplation of the] four bases of 
mindfulness.

_ekāyano ayaṃ bhikkhave maggo... ñāyassa adhigamāya nibbānassa 
sacchikiriyāya. Yadidaṃ cattāro satipaṭṭhānā._
____

.Illustration
====
ñāya

noble practice
====

____
If anyone told a follower of that teaching: 'Certainly the Venerable is 
applying himself to the noble practice, and will fulfil the noble practice,'

_Yo kho cunda evarūpaṃ sāvakaṃ evaṃ vadeyya addhāyasmā 
ñāyapaṭipanno ñāyamārādhessatī ti_
____

____
... the one who praises, the person who was praised, and the one who, on 
hearing such praise, should make still greater efforts, would all beget much 
merit. Why?

_yo ca pasaṃsati yañca pasaṃsati yo ca pasaṃsito bhiyyo somattāya 
viriyaṃ ārabhati sabbe te bahuṃ puññaṃ pasavanti. Taṃ kissa hetu?_
____

[quote, D.3.121]
____
... Because the teaching and discipline are well explained, well expounded, and 
lead to deliverance [from suffering], and to inward peace._

_Evaṃ hetaṃ cunda hoti svākkhāte dhammavinaye suppavedite niyyānike 
upasamasaṃvattanike._
____

.Illustration
====
ñāyaṃ dhammaṃ

the noble practice
====

[quote, A.2.37]
____
He explained the noble practice which is of benefit to devas and men, hearing 
and understanding which the manyfolk gain faith [in the perfection of the 
Perfect One's transcendent insight].

_Hitaṃ devamanussānaṃ ñāyaṃ dhammaṃ pakāsayī_ +
_Yaṃ ve disvā ca sutvā ca pasīdati bahujjano._
____

.Illustration
====
ñāyaṃ dhammaṃ

the noble practice
====

[quote, M.1.514]
____
These four kinds of religious life without consolation have been declared, 
wherein a wise man certainly would not live the religious life, or if he should 
live it, would not fulfil the noble practice that is spiritually wholesome.

_cattāri ca anassāsikāni brahmacariyāni akkhātāni yattha viññū puriso 
sasakkaṃ brahmacariyaṃ na vaseyya vasanto vā na ārādheyya ñāyaṃ 
dhammaṃ kusalan ti._
____

.Illustration
====
ñāyaṃ dhammaṃ

the noble practice
====

[quote, M.2.181]
____
If, brahman, anyone from a clan of _khattiyas_ goes forth from the household 
life into the ascetic life, and, after encountering the teaching and discipline 
proclaimed by the Perfect One, he abstains from killing, stealing, 
incelibacy... he fulfils the noble practice that is spiritually wholesome.

__ārādhako hoti ñāyaṃ dhammaṃ kusalaṃ._
____

.Illustration
====
ñāyaṃ dhammaṃ

the noble practice
====

[quote, S.5.19]
____
Whether it is a layperson or one gone forth [into the ascetic life] who applies 
himself to wrong practice, because of doing so he does not fulfil the noble 
practice that is spiritually wholesome.

_Gihī vā bhikkhave pabbajito vā micchāpaṭipanno 
micchāpaṭipattādhikaraṇahetu nārādhako hoti ñāyaṃ dhammaṃ 
kusalaṃ._
____

.Illustration
====
ñāyo

correct approach
====

An acrobat told his apprentice Medakathālikā to join him on the bamboo pole 
and stand on his shoulders, and told him:

____
-- 'You protect me, dear Medakathālikā, and I'll protect you.

_tvaṃ samma medakathālike mamaṃ rakkha. Ahaṃ tvaṃ rakkhikissāmi._
____

... Thus safeguarding one another (_aññamaññaguttā_), protecting one 
another (_aññamaññarakkhitā_), we'll exhibit our skills, collect our fee, 
and get safely off the bamboo pole.'

Medakathālikā replied:

____
-- 'That's not the way to do it, teacher. You protect yourself, teacher, and 
I'll protect myself.

_na kho nāmenaṃ ācariya evaṃ bhavissati tvaṃ ācariya attānaṃ rakkha 
ahaṃ attānaṃ rakkhissāmi_
____

... Thus, each safeguarding ourselves (_attaguttā_), and protecting ourselves 
(_attarakkhitā_), we'll exhibit our skills, collect our fee, and get safely 
off the bamboo pole.'

The Buddha praised Medakathālikā, saying:

[quote, S.5.168-9]
____
-- 'That's the correct approach: it's just as the apprentice Medakathālikā 
told his teacher.

_So tattha ñāyo ti bhagavā avoca yathā medakathālikā antevāsī 
ācariyaṃ avoca._
____

.Illustration
====
ñāyo

doctrine
====

____
"And what is the noble doctrine that he has clearly seen and correctly 
penetrated by penetrative discernment?

_Katamo cassa ariyo ñāyo paññāya sudiṭṭho hoti suppaṭividdho?_
____

____
The noble disciple carefully and properly contemplates dependent origination 
thus:

_Idha gahapati ariyasāvako paṭiccasamuppādaññeva sādhukaṃ 
yonisomanasikaroti_
____

[quote, S.2.70]
____
'When there is this, that comes to be. With the arising of this, that arises. 
Without this, that does not come to be. With the ending of this, that ceases.

_iti imasmiṃ sati idaṃ hoti imassuppādā idaṃ uppajjati imasmiṃ asati 
idaṃ na hoti imassa nirodhā idaṃ nirujjhati._
____

Comment:

Dependent origination is elsewhere called _dhamma_:

[quote, D.2.55]
____
It is through not fathoming, not penetrating this doctrine that this generation 
is tangled up like string

_Etassa ānanda dhammassa ananubodhā appaṭivedhā evamayaṃ pajā 
tantākulakajātā._
____

