== Ñāṇa

=== Renderings

- _ñāṇa_: knowledge

- _ñāṇa_: knowledge [of things according to reality]

- _ñāṇa_: perception (_Poṭṭhapāda Sutta_)

- _aññāṇa_: ignorance

- _aññāṇa_: ignorance [of things according to reality]

- _aññāṇa_: incomprehension

=== Introduction

==== Ñāṇa: factual knowledge or insightful knowledge

_Ñāṇa_ is derived from _jānāti_ and means either factual knowledge or 
insightful knowledge. Factual knowledge is the knowledge of someone looking 
into a well and knowing, 'There is water' (_tassa udakan ti hi kho ñāṇaṃ 
assa_ S.2.118). Insightful knowledge is knowing, for example, old age and death 
according to reality (_jarāmaraṇe yathābhūtaṃ ñāṇāya_ S.2.132).

Thus to indicate insightful knowledge, _yathābhūtaṃ_ is used, at least 
sometimes. Where it is missing, it should be parenthesised.

==== Aññāṇa: lack of factual knowledge or insightful knowledge

Correspondingly, there are the opposites: lack of factual knowledge and lack 
insightful knowledge. The former is the ignorance (_aññāṇa_) that a 
bhikkhu might have of a Pātimokkha rule, and who exclaims 'Only now do I 
realise! This regulation, it seems, is handed down as a Pātimokkha rule' 
(Vin.4.144). The latter is, for example, of the first noble truth: ignorance of 
suffering [according to reality] (_dukkhe aññāṇaṃ_ S.5.430).

Here we have parenthesised [according to reality] to indicate insightful 
knowledge. This is clearly justified because in other suttas, _yathābhūtaṃ_ 
is associated with the formula: _So idaṃ dukkhan ti yathābhūtaṃ 
pajānāti_ (S.5.199).

==== Parenthesising: association of terms

Our parenthesis is also justified because of the association of _ñāṇa_ with 
terms where we have explained that a similar parenthesis is used:

1. _dassana_: vision [of things according to reality].

• He has knowledge and vision of all phenomena [according to reality], +
☸ _Sabbesu dhammesu ca ñāṇadassī_ (Sn.v.478). See Glossary sv _Dassana_.

2. _ñatvā_: knowing [according to reality].

• One who is uncertain [about the significance of the teaching] should train 
in the path of knowledge [of things according to reality], [for these] things 
have been spoken of by the Ascetic having [likewise] known them [according to 
reality]. +
☸ _Kathaṅkathī ñāṇapathāya sikkhe ñatvā pavuttā samaṇena 
dhammā_ (Sn.v.868). See Glossary sv _Ñatvā_.

==== Poṭṭhapāda Sutta: unusual

The use of _ñāṇaṃ_ in the _Poṭṭhapāda Sutta_ is unusual. It will be 
discussed in the Illustrations.

=== Illustrations: unparenthesised

.Illustration
====
ñāṇaṃ

knowledge
====

[quote, M.3.245]
____
For this, bhikkhu, is the highest penetrative discernment, namely knowledge of 
the complete destruction of suffering.

_Esā hi bhikkhu paramā ariyā paññā yadidaṃ sabbadukkhakkhaye 
ñāṇaṃ._
____

.Illustration
====
ñāṇaṃ

knowledge
====

[quote, M.3.108]
____
For him thus knowing and seeing, his mind is liberated [from perceptually 
obscuring states].

_Tassa evaṃ jānato evaṃ passato kāmāsavā pi... avijjāsavā pi cittaṃ 
vimuccati._

Being liberated [from perceptually obscuring states], the knowledge arises that 
he is [thus] liberated.

_Vimuttasmiṃ vimuttami ti ñāṇaṃ hoti._
____

.Illustration
====
ñāṇan

knowledge
====

[quote, M.3.210]
____
Some ascetic or Brahmanist says 'All those who kill... will be reborn in the 
realm of happiness, in the heavenly worlds.'

_So evamāha yo kira bho pāṇātipātī... micchādiṭṭhi sabbo so 
kāyassa bhedā parammaraṇā sugatiṃ saggaṃ lokaṃ upapajjati._

And says: 'Those who know thus, know rightly; those who know otherwise, their 
knowledge is wrong.'

_Ye evaṃ jānanti te sammā jānanti ye aññathā jānanti micchā tesaṃ 
ñāṇan ti._
____

.Illustration
====
ñāṇaṃ

knowledge
====

[quote, S.2.118]
____
Suppose, friend, there was a well along a desert road, but it had neither a 
rope nor a bucket. Then a man came, oppressed by the heat, tired, parched, and 
thirsty.

He would look into the well and would have the knowledge, 'There is water,' but 
he would not be able to make bodily contact with it.

_So taṃ udapānaṃ olokeyya. Tassa udakan ti hi kho ñāṇaṃ assa na ca 
kāyena phusitvā vihareyya._
____

.Illustration
====
ñāṇaṃ

knowledge
====

[quote, D.3.275]
____
The three final knowledges.

_Tisso vijjā_

the final knowledge: the knowledge through recalling of past lives

_pubbenivāsānussati ñāṇaṃ vijjā_

the final knowledge: the knowledge of the transmigration of beings

_sattānaṃ cutūpapāte ñāṇaṃ vijjā_

the final knowledge: the knowledge of the destruction of perceptually obscuring 
states_._

__āsavānaṃ khaye ñāṇaṃ vijjā._
____

.Illustration
====
ñāṇaṃ

knowledge
====

____
As regards the past, the Perfect One has knowledge of past lives. He can 
remember as far back as he wishes.

_Atītaṃ kho cunda addhānaṃ ārabbha tathāgatassa satānusāri 
ñāṇaṃ hoti. So yāvatakaṃ ākaṅkhati tāvatakaṃ anussarati._
____

[quote, D.3.134]
____
As for the future, this knowledge, born of enlightenment, arises in him 'This 
is the last birth; there will be no renewed states of individual existence.'

_Anāgatañca kho addhānaṃ ārabbha tathāgatassa bodhijaṃ ñāṇaṃ 
uppajjati ayamantimā jāti natthidāni punabbhavo ti._
____

.Illustration
====
ñāṇaṃ

knowledge
====

____
Two kinds of knowledge

_dve ñāṇāni_
____

____
knowledge of destruction

_khaye ñāṇaṃ_
____

[quote, D.3.274]
____
knowledge of non-rearising

_anuppāde ñāṇaṃ._
____

.Illustration
====
ñāṇaṃ tathaṃ

knowledge of things according to reality
====

____
Knowing the arising of nonexistence [according to reality], and knowing that 
spiritually fettering delight is a tie to individual existence,

_Ākiñcaññasambhavaṃ ñatvā nandi saṃyojanaṃ iti_
____

____
knowing this thus, then he sees this matter [according to reality].

_Evametaṃ abhiññāya tato tattha vipassati_
____

[quote, Sn.v.1115]
____
This is the knowledge of things according to reality of the Brahman who has 
perfected the religious life

_Etaṃ ñāṇaṃ tathaṃ tassa brāhmaṇassa vusīmato ti._
____

.Illustration
====
yathābhūtaṃ ñāṇāya

knowledge of old age and death according to reality
====

[quote, S.2.132]
____
One who does not know and see old age and death according to reality should 
vigorously endeavour [to attain] knowledge of old age and death according to 
reality

_Jarāmaraṇaṃ bhikkhave ajānatā apassatā yathābhūtaṃ jarāmaraṇe 
yathābhūtaṃ ñāṇāya ātappaṃ karaṇīyaṃ._
____

=== Illustrations: parenthesised

.Illustration
====
ñāṇaṃ

knowledge [of things according to reality]
====

____
In one of right inward collectedness, right knowledge [of things according to 
reality] comes into being.

_sammāsamādhissa sammāñāṇaṃ pahoti_
____

[quote, M.3.71-77]
____
In one of right knowledge [of things according to reality], right liberation 
&#8203;[from perceptually obscuring states] comes into being.

_sammāñāṇassa sammāvimutti pahoti._
____

.Illustration
====
ñāṇa

knowledge of bodies [according to reality]
====

[quote, D.2.216]
____
As he abides contemplating the nature of the body internally he becomes 
perfectly inwardly collected and perfectly serene. Being thus perfectly 
inwardly collected and perfectly serene, he arouses knowledge and vision 
externally of others' bodies [according to reality].

_So tattha sammā samāhito sammāvippasanno bahiddhā parakāye 
ñāṇadassanaṃ abhinibbatteti._
____

.Illustration
====
ñāṇa

knowledge [of things according to reality]; aññāṇa, ignorance [of things 
according to reality]
====

____
By destroying the origin of ignorance [of things according to reality], [the 
eightfold path] is a destroyer of the operation of the karmic mechanism.

_Aññāṇamūlabhedāya kammayantavighāṭano_
____

[quote, Th.v.419]
____
It causes the thunderbolt of knowledge [of things according to reality] to fall 
on thoughts which have been taken hold of.

_Viññāṇānaṃ pariggahe ñāṇavajīranipātino._
____

.Illustration
====
ñāṇa

knowledge of it [according to reality]; aññāṇa, ignorance of it [according 
to reality]
====

[quote, M.1.302]
____
Neutral sense impression: knowledge of it [according to reality] is pleasant, 
ignorance of it [according to reality] is unpleasant.

_adukkhamasukhā vedanā ñāṇasukhā aññāṇadukkhā ti._
____

.Illustration
====
ñāṇamhi

knowledge [of things according to reality]
====

[quote, S.1.129]
____
What difference does womanhood make when the mind is well-collected, when 
knowledge [of things according to reality] exists in one who rightly sees the 
nature of reality?

_Itthibhāvo kiṃ kayirā cittamhi susamāhite +
Ñāṇamhi vattamānamhi sammā dhammaṃ vipassato._
____

=== Illustrations: aññāṇa

.Illustration
====
aññāṇaṃ

ignorance of it [according to reality]; ñāṇaṃ knowledge of 
it [according to reality]
====

[quote, S.5.430]
____
Bhikkhus, ignorance of suffering [according to reality], the origin of suffering, the 
ending of suffering, the practice leading to the ending of suffering, is called 
uninsightfulness into reality, and it is on account of this quality that one 
lacks insight into reality.

_Yaṃ kho bhikkhu dukkhe aññāṇaṃ dukkhasamudaye aññāṇaṃ 
dukkhanirodhe aññāṇaṃ dukkhanirodhagāminiyā paṭipadāya 
aññāṇaṃ ayaṃ vuccati bhikkhu avijjā ettāvatā ca avijjāgato hoti._

Bhikkhus, whatsoever is the knowledge of suffering [according to reality], of 
the origin of suffering, the ending of suffering, and of the practice leading 
to the ending of suffering, is called insightfulness into reality, and it is on 
these grounds that one is possessed of insight into reality.

_Yaṃ kho bhikkhu dukkhe ñāṇaṃ dukkhasamudaye ñāṇaṃ dukkhanirodhe 
ñāṇaṃ dukkhanirodhagāminiyā paṭipadāya ñāṇaṃ ayaṃ vuccati 
bhikkhu vijjā ettāvatā ca vijjāgato hoti._
____

.Illustration
====
aññāṇa

ignorance [of things according to reality]
====

[quote, It.82]
____
These three kinds of spiritually unwholesome thoughts produce spiritual 
blindness, uninsightfulness, ignorance [of things according to reality], are 
destructive of penetrative discernment, vexatious, and not conducive to the 
Untroubled. Which three? Sensuous thought, unbenevolent thought, and malicious 
thought.

_Kāmavitakko... Vyāpādavitakko... Vihiṃsāvitakko bhikkhave andhakaraṇo 
acakkhukaraṇo aññāṇakarano paññānirodhiko vighatapakkhiko 
anibbānasaṃvattaniko._
____

.Illustration
====
aññāṇa

ignorance
====

If a bhikkhu, while the half-monthly Pātimokkha is being recited, says "Only 
now do I realise! This regulation, it seems, is handed down as a Pātimokkha 
rule, is included as a Pātimokkha rule, and comes up for recitation every 
half-month." If other bhikkhus know that this bhikkhu has already sat through 
two or three recitations of the Pātimokkha, if not more:

[quote, Vin.4.144]
____
there is no acquittal for that bhikkhu due to ignorance,

_na ca tassa bhikkhuno aññāṇakena mutti._
____

.Illustration
====
aññāṇa

incomprehension
====

Vacchagotta asked the Buddha where an arahant was reborn after death. The 
Buddha said one cannot say he is either reborn or not reborn. Vacchagotta 
exclaimed:

[quote, M.1.487]
____
'I have fallen into incomprehension and bewilderment.'

_Etthāhaṃ bho gotama aññāṇamāpādiṃ ettha sammohamāpādiṃ._
____

=== Illustrations: Poṭṭhapāda Sutta

.Illustration
====
ñāṇaṃ

perception (Poṭṭhapāda Sutta)
====

The use of _ñāṇaṃ_ in the _Poṭṭhapāda Sutta_ is unusual. The Buddha 
tells Poṭṭhapāda that:

[quote, D.1.185]
____
'A state of refined awareness arises first, perception [of that state] 
afterwards. From the arising of a state of refined awareness comes the 
perception [of that state]. Thus one knows that perception has a specific and 
necessary condition.'

_Saññā kho poṭṭhapāda paṭhamaṃ uppajjati pacchā ñāṇaṃ. 
Saññuppādā ca pana ñāṇuppādo hoti. So evaṃ pajānāti idappaccayā 
kira me ñāṇaṃ udapādī ti._
____

COMMENT

Poṭṭhapāda's question stemmed from the Buddha's explanation of how various 
states of refined awareness (_saññā_) arise, and how there is a 'subtle but 
true perception' of those states (_sukhumasaccasaññā tasmiṃ samaye hoti_). 
Thus _saññā_ has two meanings: state of refined awareness, and perception of 
that state. For example:

____
Further, Poṭṭhapāda, with the overcoming in every way of the state of 
awareness of boundless space, a bhikkhu enters and abides in the state of 
awareness of boundless mental consciousness, where one perceives that mental 
consciousness is boundless.

_Puna ca paraṃ poṭṭhapāda bhikkhu sabbaso ākāsānañcāyatanaṃ 
samatikkamma anantaṃ viññāṇan ti viññāṇañcāyatanaṃ upasampajja 
viharati._
____

[quote, D.1.183-4]
____
... And for him the previous subtle but true perception (_saññā_) of the 
state of awareness of boundless space ceases. And at that time there is a 
subtle but true perception (_saññā_) of the state of awareness of boundless 
mental consciousness. He is one with a subtle but true perception of the state 
of awareness of boundless mental consciousness.

_Tassa yā purimā ākāsānañcāyatanasukhumasaccasaññā sā nirujjhati. 
Viññāṇañcāyatanasukhumasaccasaññā tasmiṃ samaye hoti. 
Viññāṇañcāyatanasukhumasaccasaññī yeva tasmiṃ samaye hoti._

... In this way one state of refined awareness (_saññā_) arises through 
the training, and one state of refined awareness (_saññā_) ceases through 
the training.

_Evampi sikkhā ekā saññā uppajjati. Sikkhā ekā saññā nirujjhati_ 
____

Now, following the Buddha's explanation, Poṭṭhapāda wanted to know the 
relationship between states of refined awareness and perception of those 
states. This was because he had recently attended discussions on the 'thorough 
ending of states of refined awareness' (_abhisaññānirodhe_) in which 
philosophers had explained the relationship beween the two. For instance, one 
philosopher said states of refined awareness (_saññā_) arise and cease 
without indispensible or necessary conditions (_ahetū appaccayā purisassa 
saññā uppajjanti pi nirujjhanti pi_). When they arise, one is perceptive [of 
them] (_Yasmiṃ samaye uppajjanti saññī tasmiṃ samaye hoti_), when they 
disappear, one is unperceptive [of them] (_Yasmiṃ samaye nirujjhanti 
asaññī tasmiṃ samaye hotī ti_). But in asking which comes first, states 
of refined awareness or perception of those states, Poṭṭhapāda would have 
needed to ask, 'Which comes first, _saññā_ or _saññā_?' To avoid this 
situation, he called perception '_ñāṇaṃ_.' The Buddha accepted this 
substitution and gave the answer above, adding that perception has a specific 
and necessary condition (_idappaccayā kira me ñāṇaṃ udapādī_).

