== Ādīnava

=== Renderings

- _ādīnava_: danger

- _ādīnava_: wretchedness

- _ādīnava_: disadvantage

=== Illustrations

.Illustration
====
ādīnavaṃ

danger
====

It would be better for the faculty of sight to be blotted out by a red-hot iron 
pin, burning, blazing, and glowing, than for one to grasp the features or 
aspects of a visible object known via the visual sense.

For if one's stream of sense consciousness should stand tied to the sweetness 
of the features or aspects of the object, and if one should die on that 
occasion, it is possible that one will go to one of two places of rebirth: hell 
or the animal realm.

[quote, S.4.168]
____
Seeing this danger I speak thus.

_Imaṃ khvāhaṃ bhikkhave ādīnavaṃ disvā evaṃ vadāmi._
____

.Illustration
====
ādīnavo

danger
====

When a bhikkhu is focusing on some meditation object that arouses unvirtuous, 
spiritually unwholesome thoughts then:

[quote, M.1.120]
____
he should examine the danger of those thoughts, that they are spiritually 
unwholesome, blameworthy, and have an unpleasant karmic consequence

_tesaṃ vitakkānaṃ ādīnavo upaparikkhitabbo itipime vitakkā akusalā 
itipime vitakkā sāvajjā itipime vitakkā dukkhavipākāti._
____

.Illustration
====
ādīnavaṃ danger

[quote

Sn.v.731-2]
====

____
Recognising this danger, that suffering arises dependent on karmically 
consequential deeds

_Etamādīnavaṃ ñatvā dukkhaṃ saṅkhārapaccayā._
____

.Illustration
====
ādīnavaṃ danger

____
-- Ānanda

friend, do the bhikkhus teach the abandonment of attachment, hatred, and 
undiscernment of reality?'
====

_rāgassa pahānaṃ paññāpetha dosassa pahānaṃ paññāpetha mohassa 
pahānaṃ paññāpethāti_
____

-- We do indeed, friend.

____
-- Seeing what danger therein do you so teach?'

__ādīnavaṃ disvā_
____

-- Why, friend, one who is overpowered and overcome by attachment, hatred, and 
undiscernment of reality, is intent upon his own harm, upon the harm of others, 
upon the harm of both, and so experiences psychological pain and dejection. But 
if attachment, hatred, and undiscernment of reality are abandoned he is not 
intent upon his own harm, upon the harm of others, upon the harm of both, and 
thus does not experience psychological pain and dejection (A.1.216-7).

.Illustration
====
ādīnavaṃ danger

• Suppose that I

being myself liable to defilement, knowing the danger of [seeking] what is 
liable to defilement, should seek the undefiled, the unsurpassed safety from 
the danger of bondage [to individual existence], the Untroubled. +
====

☸ _kinnu kho ahaṃ_... _attanā saṅkilesadhammo samāno saṅkilesadhamme 
ādīnavaṃ viditvā asaṅkiliṭṭhaṃ anuttaraṃ yogakkhemaṃ 
nibbānaṃ pariyeseyyan ti_ (M.1.163).

.Illustration
====
ādīnavā

danger
====

• Five dangers of having faith which is based on a single individual +
_Pañcime bhikkhave ādīnavā puggalappasāde. Katame pañca:_

When a person's complete faith is based on a single individual (_puggale 
puggalo abhippasanno hoti_) and that person falls into an error such that the 
community of bhikkhus suspends him, then he will think: 'The community of 
bhikkhus has suspended he who is beloved and dear to me.' And he will be no 
more full of faith in the bhikkhus (_bhikkhūsu appasādabahulo hoti_), and 
from being without faith he will not follow other bhikkhus, and from not 
following other bhikkhus he will not hear the true teaching, and from not 
hearing the true teaching he will fall away from the true teaching (A.3.270).

.Illustration
====
ādīnava

danger
====

____
And what, Ānanda, is the perception of the danger [of the body]?

_Katamācānanda ādīnavasaññā_
____

____
In this regard, Ānanda, a bhikkhu... reflects that this [wretched human] body 
is very unpleasant and a great danger.

_bahu dukkho kho ayaṃ kāyo bahu ādīnavo_
____

• Many illnesses arise in it, namely, illnesses of the eye, ear, nose... 
cold, heat, hunger, thirst, faeces and urine. +
☸ _iti imasmiṃ kāye vividhā ābādhā uppajjanti seyyathīdaṃ 
cakkhurogo sotarogo ghānarogo... sītaṃ uṇhaṃ jighacchā pipāsā 
uccāro passāvo ti_).

[quote, A.5.110]
____
Thus he abides contemplating the danger of this [wretched human] body.

_Iti imasmiṃ kāye ādīnavānupassī viharati._
____

.Illustration
====
ādīnavo

danger
====

[quote, Vin.1.15]
____
Then Yasa, having awoken sooner than usual saw his retinue asleep: one with a 
lute in her arm, one with a tabor under her chin, one with a drum under her 
arm, one with dishevelled hair, one who was dribbling, and others who were 
muttering. One would think it was a charnel ground before one's eyes. Seeing 
this, the danger [of sensuous pleasure] became apparent to him. His mind was 
established in disillusionment [with sensuous pleasure].

_Atha kho yaso kulaputto paṭigacceva pabujjhitvā addasa sakaṃ parijanaṃ 
supantaṃ. Aññissā kacche vīṇaṃ. Aññissā kaṇṭhe mudiṅgaṃ. 
Aññissā kacche ālambaraṃ. Aññaṃ vikkesikaṃ aññaṃ vikkhelikaṃ. 
Aññā vippalapantiyo. Hatthappattaṃ susānaṃ maññe. Disvānassa 
ādīnavo pāturahosi. Nibbidāya cittaṃ saṇṭhāsi._
____

.Illustration
====
ādīnavo

danger
====

____
What is the danger of sensuous pleasures?

_Ko ca bhikkhave kāmānaṃ ādīnavo?_
____

Firstly, due to whatever craft by which a noble young man makes his living... 
he is exposed to cold and heat, he is injured by contact with horseflies, 
mosquitoes, wind, sun, and snakes, facing death from hunger and thirst. This is 
the danger of sensuous pleasures, a mass of suffering discernable in this 
lifetime (_ādīnavo sandiṭṭhiko dukkhakkhandho_), having sensuous pleasure 
as its cause, its source, its basis, its cause being simply sensuous pleasure 
(M.1.85-7).

.Illustration
====
ādīnavaṃ

danger
====

[quote, D.1.109]
____
The Blessed One delivered a graduated discourse on generosity, on morality, on 
heaven, explaining the danger, degradation, and defilement of sensuous 
pleasures, and the advantage of the practice of unsensuousness.

_bhagavā ānupubbīkathaṃ kathesi seyyathīdaṃ dānakathaṃ sīlakathaṃ 
saggakathaṃ kāmānaṃ ādīnavaṃ okāraṃ saṅkilesaṃ nekkhamme ca 
ānisaṃsaṃ pakāsesi._
____

.Illustration
====
ādīnavaṃ

danger
====

[quote, Thī.v.226]
____
Seeing danger in sensuous pleasures, and safety in the practice of 
unsensuousness

_Kāmesvādīnavaṃ disvā nekkhammaṃ daṭṭhu khemato._
____

.Illustration
====
ādīnava

danger
====

[quote, M.1.369]
____
He takes that almsfood without being ensnared by, infatuated with, or clinging 
to it, but seeing the danger of it, discerning deliverance.

_So taṃ piṇḍapātaṃ agathito amucchito anajjhopanno ādīnavadassāvī 
nissaraṇapañño paribhuñjati._
____

.Illustration
====
ādīnavaṃ

danger
====

[quote, D.2.44]
____
The Blessed One Buddha Vipassī explained the danger, degradation, and 
defilement of originated phenomena and the advantage of the Untroubled.

_saṅkhārānaṃ ādīnavaṃ okāraṃ saṅkilesaṃ nibbāne ca 
ānisaṃsaṃ pakāsesi._
____

.Illustration
====
ādīnavaṃ

wretchedness
====

____
They considered him wise when he was committed to faring alone, but now that he 
is devoted to sexual intercourse he is harassed as a fool.

_Paṇḍito ti samaññāto ekacariyaṃ adhiṭṭhito +
Athāpi methune yutto mandova parikissati_
____

[quote, Sn.v.820-1]
____
Recognising the wretchedness of all this, the sage for his whole life 
resolutely lives the religious life by himself. He does not pursue sexual 
intercourse.

_Etamādīnavaṃ ñatvā muni pubbāpare idha +
Ekacariyaṃ daḷhaṃ kayirā na nisevetha methunaṃ._
____

.Illustration
====
ādīnavo

wretchedness
====

____
Bhikkhus, if there were no sweetness in the five aggregates, beings would not 
be attached to them

_No cedaṃ bhikkhave rūpassa... viññāṇassa assādo abhavissa nayidaṃ 
sattā rūpasmiṃ... viññāṇasmiṃ sārajjeyyuṃ_
____

[quote, S.3.30]
____
If there were no wretchedness in the five aggregates beings would not be 
disillusioned with them.

_No cedaṃ bhikkhave rūpassa... viññāṇassa ādīnavo abhavissa nayidaṃ 
sattā rūpasmiṃ... viññāṇasmiṃ nibbindeyyuṃ._
____

.Illustration
====
ādīnavo

wretchedness
====

____
The physical and psychological pleasure that arises from sense impression is 
the sweetness of sense impression.

_Yaṃ vedanaṃ paṭicca uppajjati sukhaṃ somanassaṃ ayaṃ vedanāya 
assādo._
____

[quote, S.4.220]
____
That sense impression is unlasting, existentially void, destined to change, is 
the wretchedness of sense impression.

_Yā vedanā aniccā dukkhā vipariṇāmadhammā ayaṃ vedanāya ādīnavo._
____

.Illustration
====
ādīnavo

wretchedness; ādīnavo, wretchedness
====

____
What is the wretchedness of bodily forms?

_Ko ca bhikkhave rūpānaṃ ādīnavo?_
____

____
In this regard, one might see that same woman, eighty or ninety or a hundred 
years old..._

_Idha bhikkhave tameva bhaginiṃ passeyya aparena samayena āsītikaṃ vā 
nāvutikaṃ vā vassasatikaṃ vā jātiyā..._
____

____
What do you think, bhikkhus? Has her former loveliness and beauty vanished and 
a wretchedness become evident?_

_Taṃ kiṃ maññatha bhikkhave yā purimā subhā vaṇṇanibhā sā 
antarahitā ādīnavo pātubhūto ti?_
____

____
Yes, bhante

_Evaṃ bhante._
____

[quote, M.1.88]
____
This is the wretchedness of bodily forms._

_Ayampi bhikkhave rūpānaṃ ādīnavo._
____

.Illustration
====
ādīnavo

wretchedness
====

[quote, S.3.102]
____
That bodily form is unlasting, existentially void, destined to change, is the 
wretchedness of bodily form

_Yaṃ rūpaṃ aniccaṃ dukkhaṃ vipariṇāmadhammaṃ ayaṃ rūpassa 
ādīnavo._
____

.Illustration
====
ādīnava

wretchedness
====

[quote, S.2.85]
____
Bhikkhus, when one abides contemplating the wretchedness of things conducive to 
grasping, craving ceases.

_Upādāniyesu bhikkhave dhammesu ādīnavānupassino viharato taṇhā 
nirujjhati._
____

Comment:

The contemplations on wretchedness that lead to the ending of craving are 
likely those listed in this quote:

____
'Bhikkhus, whatever ascetics and Brahmanists in the past regarded that in the 
world which is agreeable and pleasing

_ye ca kho ke ci bhikkhave atītamaddhānaṃ samaṇā vā brāhmaṇā vā 
yaṃ loke piyarūpaṃ sātarūpaṃ taṃ_
____

____
as unlasting

_aniccato addakkhuṃ_
____

____
as existentially void

_dukkhato addakkhuṃ_
____

____
as void of personal qualities

_anattato addakkhuṃ_
____

____
as an illness

_rogato addakkhuṃ_
____

____
as full of danger

_bhayato addakkhuṃ_
____

[quote, S.2.110]
____
they abandoned craving

_te taṇhaṃ pajahiṃsu._
____

.Illustration
====
ādīnavā

disadvantage
====

____
Bhikkhus, there are these five disadvantages of a campfire.

__ādīnavā aggismiṃ_
____

[quote, A.3.256]
____
It is bad for the eyes, causes a bad complexion, causes weakness, promotes 
gregariousness, leads to gossip.

_Acakkhusso dubbaṇṇakaraṇo dubbalakaraṇo saṅgaṇikāpavaddhano 
tiracchānakathāpavattaniko._
____

.Illustration
====
ādīnavā

disadvantage
====

____
Bhikkhus, there are five disadvantages in not chewing tooth-wood:

__ādīnavā dantakaṭṭhassa akhādane_
____

____
&#8203;[Bad mouth hygiene] is unsightly,

_acakkhussaṃ_
____

____
The mouth stinks,

_mukhaṃ duggandhaṃ hoti_
____

____
One's taste buds are not cleansed

_rasaharaṇiyo na visujjhantī_
____

____
Bile and gastric mucus smother one's food

_pittaṃ semhaṃ bhattaṃ pariyonandhati_
____

____
One's food is not pleasing

_bhattamassa nacchādeti_
____

____
There are five advantages in chewing tooth-wood:

__ānisaṃsā dantakaṭṭhassa khādane_
____

____
&#8203;[Good mouth hygiene] is sightly,

_cakkhussaṃ_
____

[quote, Vin.2.137; A.3.250]
____
The mouth does not stink, etc.

_mukhaṃ na duggandhaṃ hoti._
____

.Illustration
====
ādīnavā

disadvantage
====

____
Bhikkhus, there are these five disadvantages for one who engages in lengthy and 
unsettled wandering. What five?

_Pañcime bhikkhave ādīnavā dīghacārikaṃ anavattha cārikaṃ 
anuyuttassa viharato. Katame pañca:_
____

[quote, A.3.257]
____
One does not hear what one has not heard; one does not clarify what one has 
heard; one is not perfect in the portion that one has heard; one contracts a 
severe illness; and one has no friends.

_Assutaṃ na suṇāti sutaṃ na pariyodapeti sutenekaccena avisārado hoti 
bāḷhaṃ rogātaṅkaṃ phusati na ca mittavā hoti._
____

