== Āghāta

=== Renderings

- _āghāta_: resentment

=== Illustrations

.Illustration
====
āghātaṃ

resentment
====

• Ten bases of resentment +
_Dasa imāni bhikkhave āghātavatthūni:_

____
He has harmed, is harming, or will harm me. Thinking thus, one arouses 
resentment.

_anatthamme acarīti... caratīti... carissatīti āghātaṃ bandhati_
____

____
He has harmed, is harming, or will harm someone beloved and dear to me. 
Thinking thus, one arouses resentment.

_Piyassa me manāpassa anatthaṃ acarīti... caratīti... carissatīti 
āghātaṃ bandhati_
____

____
He has benefited, is benefiting, or will benefit someone who is unbeloved or 
loathsome to me. Thinking thus, one arouses resentment.

_Appiyassa me amanāpassa atthaṃ acari... carati... carissatīti āghātaṃ 
bandhati_
____

[quote, A.5.150]
____
Tenthly, one is groundlessly irritated

_aṭṭhāne ca kuppati._
____

.Illustration
====
āghātaṃ

resentment
====

____
Bhikkhus, there are these ten ways of dispelling resentment.

_Dasa ime bhikkhave āghātapaṭivinayā. Katame dasa:_
____

In thinking

- He has harmed, is harming, or will harm me.

- He has harmed, is harming, or will harm someone beloved and dear to me.

____
He has benefited, is benefiting, or will benefit someone who is unbeloved or 
loathsome to me.

_Appiyassa me amanāpassa atthaṃ acari... carati... carissatīti āghātaṃ 
bandhati_
____

____
He dispels resentment by asking himself: 'What possible advantage is there in 
such a thought?'

_Taṃ kutettha labbhāti āghātaṃ paṭivineti_
____

[quote, A.5.150]
____
Tenthly, one is groundlessly unirritated.

_aṭṭhāne ca na kuppati._
____

.Illustration
====
āghāto

resentment
====

____
Then Devadatta reflected that 'The Blessed One in an assembly which included a 
king disparaged me with the term, 'one to be spewed like spittle,' while he 
extolled Sāriputta and Moggallāna.

_Atha kho devadatto sarājikāya maṃ bhagavā parisāya kheḷāsakavādena 
apasādeti sāriputtamoggallāne va ukkaṃsatī ti._
____

____
Angry and displeased, having venerated the Blessed One, having circled him 
rightwards, he departed.

_Kupito anattamano bhagavantaṃ abhivādetvā padakkhiṇaṃ katvā pakkāmi._
____

[quote, Vin.2.189]
____
And this was the first time that Devadatta felt resentment towards the Blessed 
One.

_Ayaṃ carahi devadattassa bhagavati paṭhamo āghāto ahosi._
____

.Illustration
====
āghāta

resentment
====

____
Bhikkhus, there are these five ways of dispelling resentment whereby all 
resentment arisen in a bhikkhu can be dispelled.

_Pañcime bhikkhave āghātapaṭivinayā yattha bhikkhuno uppanno āghāto 
sabbaso paṭivinetabbo._
____

____
When resentment has arisen for someone:

_Yasmiṃ bhikkhave puggale āghāto jāyetha_
____

____
one can develop [unlimited, all-encompassing] goodwill for that person

_mettā tasmiṃ puggale bhāvetabbā_
____

____
one can develop [unlimited, all-encompassing] compassion for that person

_karuṇā tasmiṃ puggale bhāvetabbā_
____

____
one can develop detached awareness towards that person

_upekkhā tasmiṃ puggale bhāvetabbā_
____

____
one can arouse unmindfulness and inattention regarding him

_asati amanisikāro tasmiṃ puggale āpajjitabbā_
____

[quote, A.3.185]
____
one can concentrate on the ownership of karmically consequential conduct by 
that person

_kammassakatā tasmiṃ puggale adhiṭṭhātabbā._
____

.Illustration
====
āghāto

resentment
====

____
How should resentment be dispelled for the person whose bodily and verbal 
conduct is pure and who from time to time gains mental clarity and serenity?

_Tatrāvuso yvāyaṃ puggalo parisuddhakāyasamācāro 
parisuddhavavīsamācāro labhati ca kālena kālaṃ cetaso vivaraṃ cetaso 
pasādaṃ kathaṃ tasmiṃ puggale āghāto paṭivinetabbo_
____

____
On that occasion one should contemplate the purity of his bodily and verbal 
conduct, and the mental clarity and serenity that he gains from time to time.

_yā pi'ssa parisuddhakāyasamācāratā sā pi'ssa tasmiṃ samaye 
manasikātabbā. Yā pi'ssa parisuddhavacīsamācāratā sā pi'ssa tasmiṃ 
samaye manasikātabbā. Yampi so labhati kālena kālaṃ cetaso vivaraṃ 
cetaso pasādaṃ tam pi'ssa tasmiṃ samaye manasikātabbaṃ._
____

[quote, A.3.190]
____
In this way resentment for that person can be dispelled.

_Evaṃ tasmiṃ puggale āghāto paṭivinetabbo._
____

.Illustration
====
anāghātaṃ

resentment
====

[quote, A.5.80]
____
Is [unlimited, all-encompassing] goodwill established in my heart for my 
companions in the religious life with no resentment? Is this state found in me 
or not?

_mettaṃ nu kho me cittaṃ paccupaṭṭhitaṃ sabrahmacārīsu 
anāghātaṃ saṃvijjati nu kho me eso dhammo udāhu noti?._
____

.Illustration
====
āghāto

resentment
====

[quote, M.3.245]
____
Formerly, when he was ignorant, he was full of resentment, ill will, and hatred.

_Tasseva kho pana pubbe aviddasuno āghāto hoti vyāpādo sampadoso._
____

.Illustration
====
āghātaṃ labhanti

resentful
====

____
Now at that time well-behaved bhikkhus protested when a formal act that was 
legally invalid was being carried out by the Group-of-Six bhikkhus.

_Tena kho pana samayena pesalā bhikkhū chabbaggiyehi bhikkhūhi adhammakamme 
kayiramāne paṭikkosanti._
____

[quote, Vin.1.115]
____
The Group-of-Six bhikkhus became resentful and irritated, and threatened to 
kill them.

_Chabbaggiyā bhikkhū labhanti āghātaṃ labhanti appaccayaṃ vadhena 
tajjenti._
____

.Illustration
====
āghāto karaṇīyā

resentful
====

[quote, M.1.140]
____
Therefore if others abuse, revile, scold, or trouble you, on that account you 
should not be resentful, irritated, or displeased.

_Tasmātiha bhikkhave tumhe cepi pare akkoseyyuṃ paribhāseyyuṃ roseyyuṃ 
viheseyyuṃ ghaṭṭeyyuṃ tatra tumhehipi na āghāto na appaccayo na 
cetaso anabhiraddhi karaṇīyā._
____

