== Āhāra

=== Renderings

- _āhāra_: existential nourishment

- _āhāra_: nourishing condition

- _āhāra_: nourishment

- _āhāra_: food

- _āhāra_: diet

- _āhāra_: digestion

- _āhāra_: fuel/firing

=== Introduction

==== Existential nourishment

The four kinds of _āhārā_ are for 'the maintenance of beings that have been 
brought into existence and for the assistance of those about to arise [into new 
existence]' (_bhūtānaṃ vā sattānaṃ ṭhitiyā sambhavesīnaṃ vā 
anuggahāya_). Therefore we call them the four kinds of existential nourishment.

Comment: Norman says _sambhavesīnaṃ_ is the future active participle in 
-_esin_ (Elders Verses I n.527), to be translated with the words 'about to.'

=== Illustrations

.Illustration
====
āhāro

nourishment
====

[quote, S.2.86]
____
Suppose there was a great tree and all its roots going downwards and across 
would send the sap upwards. With that as nourishment, with that as sustenance, 
that great tree would stand for a very long time

_Seyyathā pi bhikkhave mahārukkho tassa yāni ceva mūlāni adhogamāni yāni 
ca tiriyaṅgamāni sabbāni tāni uddhaṃ ojaṃ abhiharanti. Evaṃ hi so 
bhikkhave mahārukkho tadāhāro tadupādāno ciraṃ dīghamaddhānaṃ 
tiṭṭheyya._
____

.Illustration
====
āhāra

nourishment; āhāro, food
====

[quote, Vin.1.199]
____
What now if I allowed medicine for bhikkhus, both medicine itself as well as 
what could be regarded as medicine, which though it serves as nourishment in 
the world, could not be regarded as gross food?

_Kinnū kho ahaṃ bhikkhūnaṃ bhesajjaṃ anujāneyyaṃ yaṃ 
bhesajjañceva assa bhesajjasammatañca lokassa āhāratthañca phareyya na ca 
oḷāriko āhāro paññāyeyyā ti._
____

.Illustration
====
āhāro

food
====

[quote, Sn.v.985]
____
Without food, he shrivelled up.

_Ussussati anāhāro._
____

.Illustration
====
āhāra

food
====

[quote, Th.v.123]
____
Seeing that the body subsists on food, I go searching.

_Āhāraṭṭhitiko samussayo iti disvāna carāmi esanaṃ._
____

.Illustration
====
āhāraṃ

food
====

____
The ascetic disciples of the Sakyans' Son eat righteous food

_dhammikaṃ samaṇā sakyaputtiyā āhāraṃ āhārenti_
____

[quote, S.3.240]
____
The ascetic disciples of the Sakyans' Son eat blameless food

_anavajjaṃ samaṇā sakyaputtiyā āhāraṃ āhārenti._
____

.Illustration
====
āhāraṃ

food
====

[quote, S.2.99]
____
Wouldn't they eat that food only for the sake of crossing the desert?

_Nanu te bhikkhave yāvadeva kantārassa nittharaṇatthāya āhāraṃ 
āhareyyunti?._
____

.Illustration
====
āhāra

food
====

[quote, A.2.145]
____
This [wretched human] body has come into being through food, sister. With the 
help of food, food must be abandoned.

_Āhārasambhūto ayaṃ bhagini kāyo. Āhāraṃ nissāya āhāro pahātabbo._
____

.Illustration
====
āhāra

food
====

____
And what is the [co-conditional] origination of the body?

_Ko ca bhikkhave kāyassa samudayo._
____

[quote, S.5.184]
____
With the origination of food comes the origination of the body. With the ending 
of food comes the vanishing of the body.

_Āhārasamudayā kāyassa samudayo āhāranirodhā kāyassa atthaṅgamo._
____

.Illustration
====
āhāro

diet
====

[quote, A.1.167]
____
There my name was so-and-so, my clan was so-and-so, my caste was so-and-so, my 
diet was such-and-such.

_evaṃnāmo evaṃgotto evaṃvaṇṇo evamāhāro._
____

.Illustration
====
āhāre

digestion
====

[quote, A.4.47]
____
If a bhikkhu's mind is imbued with the perception of the loathsome nature of 
digestion, his mind draws back, bends back, turns away from craving for 
flavours and is not attracted to them, and either indifference or loathing is 
established in him.

_Āhāre paṭikkūlasaññā paricitena bhikkhave bhikkhuno cetasā bahulaṃ 
viharato rasataṇhāya cittaṃ patilīyati patikuṭati pativaṭṭati na 
sampasārīyati upekkhā vā paṭikkūlyatā vā saṇṭhāti._
____

.Illustration
====
āhāro

firing
====

• Suppose a great bonfire was burning, consuming ten, twenty, thirty, or 
forty loads of wood, and a man would cast dry grass, dry cowdung, and dry wood 
into it from time to time. +
_tatra puriso kālena kālaṃ sukkhāni ceva tiṇāni pakkhipeyya sukkhāni 
ca gomayāni pakkhipeyya sukkhāni ca kaṭṭhāni pakkhipeyya_

• Thus, with that as firing, with that as fuel, that great bonfire would burn 
for a very long time. +
_evaṃ hi so bhikkhave mahā aggikkhandho tadāhāro tadupādāno ciraṃ 
dīghamaddhānaṃ jaleyya_ (S.2.84-90).

.Illustration
====
āhāro

fuel
====

[quote, S.3.126]
____
Just as an oil lamp burns because of oil and a wick, and with the exhaustion of 
the oil and wick it is extinguished through lack of fuel,

_Seyyathā pi assaji telañca paṭicca vaṭṭiñca paṭicca telappadīpo 
jhāyeyya. Tasseva telassa ca vaṭṭiyā ca pariyādānā anāhāro 
nibbāyeyya._
____

.Illustration
====
āhāro

fuel
====

____
A fire blazes because of its firing of grass and sticks. When this is 
exhausted, and no more is brought to it, then being without fuel, it is simply 
reckoned as extinguished.

_Yaṃ hi so gotama aggi tiṇakaṭṭhūpādānaṃ paṭicca ajali tassa ca 
pariyādānā aññassa ca anupahārā anāhāro nibbuto'teva saṅkhaṃ 
gacchatī ti_
____

.Illustration
====
āhārā

existential nourishment
====

____
There are these four kinds of existential nourishment for the maintenance of 
beings that have been brought into existence and for the assistance of those 
about to arise [into new existence]. Which four?

_Cattāro me āvuso āhārā bhūtānaṃ vā sattānaṃ ṭhitiyā 
sambhavesīnaṃ vā anuggahāya. Katame cattāro._
____

____
physical food, gross or subtle

_kabaliṅkāro āhāro oḷāriko vā sukhumo vā_
____

____
secondly, sensation

_phasso dutiyo_
____

____
thirdly, mental intentionality

_manosañcetanā tatiyā_
____

[quote, M.1.48]
____
fourthly, the stream of sense consciousness

_viññāṇaṃ catutthaṃ._
____

Comment:

Norman views _sambhavesīnaṃ_ as the future active participle in -_esin_ 
(Elders Verses I, n.527), to be translated with the words 'about to.'

.Illustration
====
āhāro

existential nourishment
====

[quote, S.2.13]
____
The existential nourishment of a stream of sense consciousness is a necessary 
condition for future renewed states of individual existence and rebirth.

_viññāṇāhāro āyatiṃ punabbhavābhinibbattiyā paccayo._
____

.Illustration
====
āhāra

existential nourishment
====

[quote, D.3.211]
____
All beings subsist on existential nourishment.

_sabbe sattā āhāraṭṭhitikā._
____

.Illustration
====
āhāra

existential nourishment
====

____
Whatever suffering arises, all of it arises dependent on existential 
nourishment. Through the ending of existential nourishment, there is no arising 
of suffering.

_Yaṃ kiñci dukkhaṃ sambhoti sabbaṃ āhārapaccayā +
Āhārānaṃ nirodhena natthi dukkhassa sambhavo._
____

[quote, Sn.v.747-9]
____
Recognising this danger, that suffering arises dependent on existential 
nourishment, profoundly understanding all existential nourishment, one is free 
of attachment to all existential nourishment.

_Etamādīnavaṃ ñatvā dukkhaṃ āhārapaccayā +
Sabbāhāraṃ pariññāya sabbāhāramanissito._
____

.Illustration
====
āhārā

existential nourishment
====

____
With the origination of craving comes the origination of existential 
nourishment.

_taṇhāsamudayā āhārasamudayo_
____

____
With the ending of craving comes the ending of existential nourishment.

_taṇhānirodhā āhāranirodho_
____

[quote, M.1.48]
____
The practice leading to the ending of existential nourishment is the noble 
eightfold path

_ayameva ariyo aṭṭhaṅgiko maggo āhāra nirodhagāminī paṭipadā._
____

.Illustration
====
āhāra

existential nourishment
====

____
What is born, brought about, arisen, produced, originated, unenduring,

_Jātaṃ bhūtaṃ samuppannaṃ kataṃ saṅkhatamaddhuvaṃ_
____

____
Conjoined with old age and death,

_Jarāmaraṇasaṅghātaṃ_
____

____
A hotbed of illnesses,

_roganiḍḍhaṃ_
____

____
Easily destroyed

_pabhaṅguṇaṃ_
____

____
Having existential nourishment as its support and source

__āhāranettippabhavaṃ_
____

[quote, It.38]
____
It is not fit to be delighted in

_nālaṃ tadabhinandituṃ._
____

.Illustration
====
āhāra

food; nourishing condition
====

____
Just as this [wretched human] body subsists on food, it survives because of 
food, without food it does not survive

_Seyyathā pi bhikkhave ayaṃ kāyo āhāraṭṭhitiko āhāraṃ paṭicca 
tiṭṭhati. Anāhāro no tiṭṭhati._
____

____
Likewise the seven factors of enlightenment subsist on nourishing conditions, 
they survive because of nourishing conditions, without nourishing conditions 
they do not survive.

_Evameva kho bhikkhave satta bojjhaṅgā āhāraṭṭhitikā āhāraṃ 
paṭicca tiṭṭhanti. Anāhārā no tiṭṭhanti._
____

____
What is the condition that nourishes both the arising of the unarisen 
enlightenment factor of mindfulness, and the perfection through spiritual 
cultivation of the arisen enlightenment factor of mindfulness?

_Ko ca bhikkhave āhāro anuppannassa vā satisambojjhaṅgassa uppādāya 
uppannassa vā satisambojjhaṅgassa bhāvanāya pāripūriyā?_
____

[quote, S.5.65]
____
There are things that support the enlightenment factor of mindfulness. Much 
proper contemplation in that regard is a condition that nourishes both the 
arising of the unarisen enlightenment factor of mindfulness, and the perfection 
through spiritual cultivation of the arisen enlightenment factor of mindfulness.

_Atthi bhikkhave satisambojjhaṅgaṭṭhānīyā dhammā. Tattha yoniso 
manasikārabahulīkāro ayamāhāro anuppannassa vā satisambojjhaṅgassa 
uppādāya uppannassa vā satisambojjhaṅgassa bhāvanāya pāripūriyā._
____

.Illustration
====
āhāro

nourishing condition
====

[quote, S.5.105]
____
There are things that support the enlightenment factor of detached awareness. 
Much proper contemplation in that regard is a condition that nourishes both the 
arising of the unarisen enlightenment factor of detached awareness, and the 
perfection through spiritual cultivation of the arisen enlightenment factor of 
detached awareness.

_Atthi bhikkhave upekkhāsambojjhaṅgaṭṭhānīyā dhammā. Tattha yoniso 
manasikārabahulīkāro ayamāhāro anuppannassa vā upekkhāsambojjhaṅgassa 
uppādāya uppannassa vā upekkhāsambojjhaṅgassa bhāvanāya pāripūriyā._
____

.Illustration
====
āhāro

nourishing condition
====

[quote, A.5.116]
____
What is the condition that nourishes uninsightfulness into reality? The five 
hindrances, one should reply._

_ko cāhāro avijjāya? Pañca nīvaraṇā tissa vacanīyaṃ._
____

.Illustration
====
āhāro

nourishing condition
====

____
And what is the condition that nourishes both the arising of unarisen sensuous 
hankering, and the increase and expansion of arisen sensuous hankering?

_Ko ca bhikkhave āhāro anuppannassa vā kāmacchandassa uppādāya uppannassa 
vā kāmacchandassa bhiyyobhāvāya vepullāya_
____

[quote, S.5.102-3]
____
There is the quality of loveliness. Much improper contemplation in that regard 
is a condition that nourishes both the arising of unarisen sensuous hankering, 
and the increase and expansion of arisen sensuous hankering.

_Atthi bhikkhave subhanimittaṃ. Tattha ayoniso manasikārabahulīkāro 
ayamāhāro anuppannassa vā kāmacchandassa uppādāya uppannassa vā 
kāmacchandassa bhiyyobhāvāya vepullāya._
____

.Illustration
====
āhāraṃ

nourishing condition
====

____
Craving for states of individual existence has a specific and necessary 
condition.

_idappaccayā bhavataṇhā ti._
____

• It has a nourishing condition, I declare, not no nourishing condition. +
_Bhavataṇhampahaṃ bhikkhave sāhāraṃ vadāmi no anāhāraṃ_

____
What is its nourishing condition?

_ko cāhāro bhavataṇhāya_
____

[quote, A.5.117]
____
Uninsightfulness into reality, one should reply.

_avijjā tissa vacanīyaṃ._
____

.Illustration
====
āhāro

nourishing condition
====

[quote, A.5.136]
____
Virtuous friendship is a condition that nourishes virtuous practices.

_kalyāṇamittatā sīlānaṃ āhāro._
____

.Illustration
====
āhāraṃ

nourishing condition
====

____
Faith [in the perfection of the Perfect One's transcendent insight] has a 
nourishing condition, I declare, not no nourishing condition.

_Saddhampahaṃ bhikkhave sāhāraṃ vadāmi no anāhāraṃ._
____

____
And what is the condition that nourishes faith [in the perfection of the 
Perfect One's transcendent insight]?

_Ko cāhāro saddhāya_
____

[quote, A.5.115]
____
Listening to the true teaching, one should reply.

_saddhammasavanantissa vacanīyaṃ._
____

.Illustration
====
āhāra

nourishing condition
====

____
-- Bhikkhus, do you see, 'This is brought about?'

_bhūtamidan ti bhikkhave passathā ti?_
____

-- Yes, bhante

____
-- Bhikkhus, do you see: 'It is arisen with that as its nourishing condition'?

_tadāhārasambhavan ti bhikkhave passathā ti?_
____

-- Yes, bhante

[quote, M.1.260]
____
-- Bhikkhus, do you see: 'With the ending of that nourishing condition, what is 
brought about is destined to cease'?

_tadāhāranirodhā yaṃ bhūtaṃ taṃ nirodhadhamman ti bhikkhave passathā 
ti?_

-- Yes, bhante.
____
