== Ājānāti

=== Renderings

- _ājānātī_: to learn

- _ājānātī_: to realise

- _ājānātī_: to know

- _ājānātī_: to understand

=== Introduction

==== Ājānāti and Aññāya

_Aññāya_ is the absolutive of _ājānātī_. We treat it here, and also 
separately, sv _Aññāya_.

=== Illustrations

.Illustration
====
aññāya

having learned
====

Whatever bhikkhunī without having obtained permission from the community of 
bhikkhunīs which carried out the proceedings in accordance with the rule, the 
discipline, the Teacher's word, not having learned the group's desire 
(_anaññāya gaṇassa chandaṃ_), should restore a bhikkhunī suspended by a 
complete assembly of bhikkhunīs, that bhikkhunī has fallen into a matter that 
is a foremost offence entailing a formal meeting of the community of 
bhikkhunīs involving being sent away (Vin.4.231).

.Illustration
====
aññāsi

knew
====

• When the Blessed One knew that Pokkharasāti's mind was ready, teachable, 
free of the five hindrances, uplifted, and serene, then he preached the 
religious discourse unique to the Buddhas +
_Yadā bhagavā aññāsi brāhmaṇaṃ pokkharasātiṃ kallacittaṃ 
muducittaṃ vinīvaraṇacittaṃ udaggacittaṃ pasannacittaṃ_ (D.1.110).

.Illustration
====
aññāsi

realise
====

____
When you realised my unsureness [about the perfection of the Perfect One's 
transcendent insight]

_Yaṃ me kaṅkhitamaññāsi_
____

[quote, Sn.v.539-540]
____
You helped me overcome my doubts. Homage to you.

_Vicikicchā maṃ tārayī namo te._
____

.Illustration
====
aññāya

realising
====

____
A bhikkhu investigates the meaning of the teachings he has retained in mind

_dhatānañca dhammānaṃ atthūpaparikkhitā hoti _
____

[quote, A.4.298]
____
Realising their meaning and significance, he practises in accordance with the 
teaching

_atthamaññāya dhammamaññāya dhammānudhammapaṭipanno ca hoti._
____

.Illustration
====
aññāsiṃ

knew
====

[quote, M.3.208]
____
I knew the worthless man Udāyī would inappropriately interfere right now.

_aññāsiṃ kho ahaṃ ānanda idānevāyaṃ udāyī moghapuriso 
ummujjamāno ayoniso ummujjissatī ti._
____

.Illustration
====
aññāya

having understood
====

[quote, It.91-2]
____
A wise person through fully understanding the teaching, having understood the 
teaching, becomes inwardly at peace, like an unruffled lake, imperturbable.

_dhammamabhiññāya dhammamaññāya paṇḍito +
rahadova nivāte ca anejo vūpasammati._
____

.Illustration
====
aññāya

knowing
====

[quote, A.4.235]
____
Knowing my reflection, the Teacher, unsurpassed in the world, through his 
psychic power approached me with a mind-made body.

_Mama saṅkappamaññāya satthā loke anuttaro +
Manomayena kāyena iddhiyā upasaṅkami._
____

.Illustration
====
aññāya

having understood
====

[quote, Sn.p.218]
____
If, having understood the meaning and significance of each question [and its 
answer], one applied oneself in accordance with the teaching, one would go 
beyond old age and death.

_ekamekassa cepi pañhassa atthamaññāya dhammamaññāya dhammānudhammaṃ 
paṭipajjeyya gaccheyyeva jarā maraṇassapāraṃ._
____

.Illustration
====
aññāya

having understood
====

____
These explain the teaching dispelling all suffering

_Te tassa dhammaṃ desenti sabbadukkhāpanūdanaṃ_
____

[quote, Vin.2.148]
____
He, having understood that teaching, realises the Untroubled in this world, and 
is free of perceptually obscuring states.

_Yaṃ so dhammaṃ idhaññāya parinibbāti anāsavo ti._
____

.Illustration
====
aññāya

having understood
====

The deva Ghaṭīkāra announced that seven bhikkhus had attained arahantship. 
The Buddha replied:

____
You speak well of those who have abandoned Māra's snare.

_Kusalī bhāsasi tesaṃ mārapāsappahāyinaṃ_
____

[quote, S.1.35]
____
Having understood whose teaching did they sever the bonds of individual 
existence?

_Kassa te dhammamaññāya acchiduṃ bhavabandhanaṃ._
____

.Illustration
====
aññāya

having understood
====

[quote, S.1.126]
____
Having understood the teaching, meditating thought-free,

_Aññāya dhammaṃ avitakkajhāyī._
____

.Illustration
====
aññāya

understanding
====

[quote, Sn.v.933]
____
Then, understanding this teaching, scrutinising it, a bhikkhu should train 
himself in it ever mindfully.

_Etañca dhammamaññāya vicinaṃ bhikkhu sadā sato sikkhe._
____

.Illustration
====
aññātaṃ

ājānāsī, understand
====

____
-- 'By grasping, bhikkhu, one is held captive by Māra. By not grasping one is 
freed from the Maleficent One.'

_Upādiyamāno kho bhikkhu baddho mārassa anupādiyamāno mutto pāpimato ti._
____

____
-- 'I understand, Blessed One. I understand, Sublime One.'

_aññātaṃ bhagavā aññātaṃ sugatā ti._
____

[quote, S.3.73]
____
-- 'In what way do you understand the meaning of my brief statement?'

_yathākathaṃ pana tvaṃ bhikkhu mayā saṅkhittena bhāsitassa vitthārena 
atthaṃ ājānāsī ti?._
____

.Illustration
====
ājānāmī

understand
====

[quote, M.3.52]
____
This statement spoken in brief by the Blessed One, where the meaning was not 
explained in detail, thus do I understand the meaning in detail.

_Imassa kho ahaṃ bhante bhagavatā saṅkhittena bhāsitassa vitthārena 
atthaṃ avibhattassa evaṃ vitthārena atthaṃ ājānāmī ti._
____

.Illustration
====
ājānāma

understand
====

[quote, D.1.189]
____
We do not understand a word of the ascetic Gotama's explanation of the teaching.

_Na kho pana mayaṃ kiñci samaṇassa gotamassa ekaṃsikaṃ dhammaṃ 
desitaṃ ājānāma._
____

