== Ākappa

=== Renderings

- _ākappa_: behaviour

- _ākappa_: way of behaviour

- _anākappasampanna_: badly behaved

- _ākappasampanno_: perfect in behaviour

- _na ākappasampanno_: imperfect in behaviour

=== Illustrations

.Illustration
====
anākappasampannā

badly behaved
====

[quote, Vin.1.44]
____
Now at that time bhikkhus, being without preceptors, not being advised and 
instructed, walked for almsfood wrongly dressed, wrongly clothed, and badly 
behaved.

_anupajjhāyakā anovadiyamānā ananusāsiyamānā dunnivatthā duppārutā 
anākappasampannā piṇḍāya caranti._
____

Comment:

The bhikkhus were asking donors for food without invitation, and eating noisily.

.Illustration
====
anākappasampannā

badly behaved
====

[quote, Vin.2.211-2]
____
Now at that time the Group-of-Six bhikkhus, went into a refectory wrongly 
dressed, wrongly clothed, and badly behaved

_dunnivatthā duppārutā anākappasampannā bhattaggaṃ gacchanti._
____

Comment:

The bhikkhus were crowding other bhikkhus, and sitting inside the village on 
their outer robes.

.Illustration
====
ākappasampanno

perfect in behaviour
====

[quote, A.3.78]
____
It is rare to find one gone forth [into the ascetic life] in old age 
(_buḍḍhapabbajito_) who is perfect in behaviour.

_dullabho ākappasampanno._
____

.Illustration
====
na ākappasampanno

imperfect in behaviour
====

[quote, A.3.261]
____
A resident bhikkhu is not to be esteemed (_abhāvanīyo hoti_) if he is 
imperfect in behaviour and in the practice of observances;

_Na ākappasampanno hoti na vattasampanno._
____

Regarding the practice of observances, the Buddha said, for example:

[quote, Vin.2.211]
____
-- 'Well then I will lay down an observance for bhikkhus who are leaving a 
residence and which should be observed by bhikkhus who are leaving a residence.'

_Tena hi bhikkhave gamikānaṃ bhikkhūnaṃ vattaṃ paññāpessāmi yathā 
gamikehi bhikkhū hi vattitabbaṃ._
____

.Illustration
====
ākappa

behaviour
====

[quote, A.1.38]
____
This is a certain type of gain, namely, good behaviour.

_Addhamidaṃ bhikkhave lābhānaṃ yadidaṃ ākappasampadā._
____

.Illustration
====
ākappā

way of behaviour
====

[quote, Th.v.950]
____
Tell me this, being asked: in future times, what will be [the bhikkhus' and 
bhikkhunīs'] desires, aspirations, and ways of behaviour?

_Kiṃchandā kimadhippāyā kimākappā bhavissare +
Anāgatamhi kālamhi taṃ me akkhāhi pucchito._
____

.Illustration
====
ākappo

way of behaviour
====

[quote, A.5.88]
____
One who has gone forth [into the ascetic life] should frequently reflect: 'My 
way of behaviour should now be different [to laypeoples'].'

_Añño me ākappo karaṇīyo ti pabbajitena abhiṇhaṃ paccavekkhitabbaṃ._
____

Comment:

[quote, A.5.210]
____
The _Samaṇasaññā Sutta_ says this reflection leads to consistently 
virtuous behaviour

_Santatakārī hoti santatavutti sīlesu._
____

.Illustration
====
ākappaṃ

way of behaviour
====

____
He develops the dog-practice fully and uninterruptedly.

_kukkuravataṃ bhāveti paripuṇṇaṃ abbokiṇṇaṃ_
____

____
He develops doglike conduct fully and uninterruptedly;

_kukkurasīlaṃ bhāveti paripuṇṇaṃ abbokiṇṇaṃ_
____

____
He develops a doglike mentality fully and uninterruptedly;

_kukkuracittaṃ bhāveti paripuṇṇaṃ abbokiṇṇaṃ_
____

____
He develops a doglike way of behaviour fully and uninterruptedly.

_kukkurākappaṃ bhāveti paripuṇṇaṃ abbokiṇṇaṃ_
____

Having done so, with the demise of the body at death, he reappears in the 
company of dogs (M.1.387-8).

.Illustration
====
ākappaṃ

way of behaviour
====

• A woman contemplates the femininity in herself, the feminine occupation, 
ways of behaviour, manners, desires, voice, and attractiveness. She is excited 
by that, she takes delight in that. +
_Itthi bhikkhave ajjhattaṃ itthindriyaṃ manasikaroti itthikuttaṃ 
itthākappaṃ itthividhaṃ itthicchandaṃ itthissaraṃ itthālaṅkāraṃ 
sā tattha rajjati tatrābhiramati._

Being thus excited and delighted, she contemplates the masculinity about her, 
the masculine occupation, ways of behaviour, manners, desires, voice, and 
attractiveness. She is excited by that, she takes delight in that (A.4.57).

