== Ākiñcañña; Kiñcana

=== Renderings

- _ākiñcaññā_: the perception of nonexistence

- _ākiñcaññā_: nonexistence

- _ākiñcañña_: possessionlessness

- _akiñcana_: liberated from the perception of existence

- _akiñcana_: free of the perception of existence (_nibbāna_)

- _akiñcana_: possessionless

- _akiñcana_: destitute

- _kiñcana_: attachment to the perception of existence

- _na hoti kiñci_: to have no attachment to the perception of existence

- _sakiñcana_: attached to the perception of existence

- _kiñcana_: anything at all

- _natthi kiñci_: there is [nowhere] anything at all

- _natthi kiñcanaṃ_: there is [nowhere] anything at all

=== Introduction: ākiñcañña

==== Three meanings

_Ākiñcañña_ has three meanings:

1. nonexistence

2. the perception of nonexistence

3. possessionlessness

==== 1) Nonexistence

The meaning 'nonexistence,' can be seen in _ākiñcañña's_ relationship to 
_natthi kiñcī ti_, the perception that there is [nowhere] anything at all, as 
in this passage:

[quote, S.4.296]
____
He enters and abides in the state of awareness of nonexistence, where one 
perceives that there is [nowhere] anything at all.

_natthi kiñcī ti ākiñcaññāyatanaṃ upasampajja viharati._
____

The same relationship between 'nonexistence' and 'the perception that there is 
&#8203;[nowhere] anything at all' can be seen when Venerable Posāla asked about the 
knowledge of 'one who sees that there is [nowhere] anything at all' (_natthi 
kiñcī ti passato_ Sn.v.1113). The Buddha referred to this as 'knowing the 
arising of nonexistence [according to reality]' (_ākiñcaññasambhavaṃ 
ñatvā,_ Sn.v.1115):

[quote, Sn.v.1113]
____
-- I ask, Sakyan, about the knowledge of one whose perception of bodily form 
has vanished, who has abandoned all bodily forms, who sees that there is 
&#8203;[nowhere] anything at all either internally or externally. How is such a person 
to be led further?

_Vibhūtarūpasaññissa sabbakāyappahāyino +
Ajjhattañca bahiddhā ca natthi kiñcī ti passato +
Ñāṇaṃ sakkānupucchāmi kathaṃ neyyo tathā vidho._
____

[quote, Sn.v.1115]
____
-- Knowing the arising of nonexistence [according to reality], and knowing that 
spiritually fettering delight is a tie to individual existence, knowing this 
thus, then he sees this matter [according to reality]. This is the knowledge of 
things according to reality of the Brahman who has perfected the religious life

_Ākiñcaññasambhavaṃ ñatvā nandi saṃyojanaṃ iti +
Evametaṃ abhiññāya tato tattha vipassati: +
Etaṃ ñāṇaṃ tathaṃ tassa brāhmaṇassa vusīmato ti._
____

The phrase 'either internally or externally' supports us parenthesising 
'[nowhere] anything.'

==== 2) The perception of nonexistence

The meaning 'the perception of nonexistence' can be seen where 
_ākiñcaññaṃ_ is linked to _natthī ti_ when the Buddha told Venerable 
Upasīva that being intent upon the perception of nonexistence 
(_ākiñcaññaṃ pekkhamāno_) means with the help of the reflection 'It does 
not exist':

[quote, Sn.v.1070]
____
Being intent upon the perception of nonexistence, being mindful, with the help 
of the reflection 'It does not exist,' cross the flood [of suffering].

_Ākiñcaññaṃ pekkhamāno satimā natthī ti nissāya tarassu oghaṃ._
____

==== 3) A state of possessionlessness

_Ākiñcaññaṃ_'s third meaning is possessionlessness. For example, the 
bhikkhunī Subhā (Thī.v.341) reflecting on a return to the household life 
said:

____
It would be unseemly for me, longing for a state of possessionlessness,

_Na metaṃ assa patirūpaṃ ākiñcaññaṃ hi patthaye_
____

[quote, Thī.v.341]
____
... Having junked gold and silver, to take them back again.

_Yo jātarūpaṃ rajataṃ chaḍḍetvā puna-r-āgahe._
____

Possessionlessness means either:

1. having minimal possessions. For example, the brahman Bāvari, longing for a 
state of possessionlessness, lived on gleanings and fruit (Sn.v.976-982).

2. Or it means having no luxurious possessions. For example, Subhā 'junked 
gold and silver.'

These meanings are practically equivalent.

=== Illustrations: ākiñcaññaṃ

.Illustration
====
ākiñcaññaṃ

possessionlessness
====

____
The Brahman speaks thus

_brāhmaṇo evamāha_
____

____
'I am not in any way anything "belonging to anyone"; and not in any way is 
there anywhere anything "belonging to me."'

_nāhaṃ kvacani kassaci kiñcanatasmiṃ +
na ca mama kvacani katthaci kiñcanatātthī ti_
____

[quote, A.2.177]
____
In fully understanding the truth of this saying one is applied to the practice 
of possessionlessness.

_api ca yadeva tattha saccaṃ tadabhiññāya ākiñcaññaṃ yeva 
paṭipadaṃ paṭipanno hoti._
____

Comment:

The _Uposatha Sutta_ (A.1.206) says the particular application of this 
contemplation is in personal relationships, where usually a man's parents know 
him as their son, and he knows them as his parents (_ayaṃ amhākaṃ putto ti 
so pi jānāti ime mayhaṃ mātāpitaro ti_). Similarly, his slaves and 
servants know him as their master, and he knows them as his slaves and servants 
(_ayaṃ amhākaṃ ayyo ti. So pi jānāti ime mayhaṃ dāsakammakaraporisā 
ti_). This reflection therefore overcomes the idea that beings possess each 
other.

.Illustration
====
ākiñcaññaṃ

a state of possessionlessness
====

The brahman Bāvari, longing for a state of possessionlessness 
(_ākiñcaññaṃ patthayāno_), lived on gleanings and fruit. When someone 
asked him for money, Bāvari said:

[quote, Sn.v.982]
____
'Whatever I had that was suitable for offering has all been disposed of by me'

_yaṃ kho mamaṃ deyyadhammaṃ sabbaṃ vissajjitaṃ mayā._
____

Possessionless therefore means having nothing suitable for offering to others.

=== Introduction: akiñcana

==== Akiñcana: meanings

_Akiñcana_ has four meanings:

1. liberated from the perception of existence

2. free of the perception of existence

3. possessionless

4. destitute

==== Relation to ākiñcaññā: liberated from the perception of existence

_Akiñcanaṃ_ is related to _ākiñcaññā_, which we have seen above can 
mean 'the perception of nonexistence,' and _akiñcanaṃ_ shares this meaning 
because _akiñcanaṃ_ describes:

____
'A person for whom there is [nowhere] anything at all in either the past, the 
future, or the present,

_Yassa pure ca pacchā ca majjhe ca natthi kiñcanaṃ_
____

[quote, Sn.v.645]
____
... Who is liberated from the perception of existence, free of grasping, he is 
what I call a Brahman.

_Akiñcanaṃ anādānaṃ tamahaṃ brūmi brāhmaṇaṃ._
____

_Akiñcanaṃ_ therefore means 'liberated from the perception of existence.' We 
will consider _natthi kiñcanaṃ_ below.

==== Relation to ākiñcaññā: free of the perception of existence

In relation to _nibbāna_, _akiñcana_ must be rendered as 'free of the 
perception of existence':

[quote, Sn.v.1093-4]
____
This Island, supreme, free of the perception of existence, free of grasping, I 
call it the Untroubled, the destruction of old age and death.

_Akiñcanaṃ anādānaṃ etaṃ dipaṃ anaparaṃ +
Nibbānaṃ iti taṃ brūmi jarāmaccuparikkhayaṃ._
____

==== Relation to ākiñcaññā: possessionless

We have seen that _ākiñcaññaṃ_ means possessionlessness, and again, 
_akiñcanaṃ_ shares this meaning. For example:

[quote, D.3.171]
____
Possessionless, gone forth [into the ascetic life]

_Akiñcanaṃ pabbajitaṃ._
____

[quote, A.5.232]
____
Having abandoned sensuous pleasures, being possessionless, one who is wise 
should cleanse himself of spiritual defilements.

_hitvā kāme akiñcano pariyodapeyya attānaṃ cittaklesehi paṇḍito._
____

==== Relation to ākiñcaññā: destitution

Related to possessionlessness is destitution:

[quote, D.3.185]
____
The drunkard is broke and destitute

_Yo vāruṇī adhano akiñcano._
____

=== Illustrations: akiñcano

.Illustration
====
akiñcano

liberated from the perception of existence
====

[quote, S.1.141]
____
This bhikkhu Brahmadeva, madam, free of attachment, has surpassed the devas. 
Liberated from the perception of existence, not supported by a patron, this 
very bhikkhu has entered your house for alms.

_Eso hi te brāhmaṇī brahmadevo nirupadhiko atidevappatto +
Akiñcano bhikkhu anaññaposī yo te so piṇḍāya gharaṃ paviṭṭho._
____

.Illustration
====
akiñcano

liberated from the perception of existence
====

[quote, Sn.v.1059]
____
Liberated from the perception of existence, liberated [from individual 
existence] in the sensuous plane of existence, certainly he has crossed this 
&#8203;[wretched] flood [of suffering].

_akiñcanaṃ kāmabhave asattaṃ addhā hi so oghamimaṃ atāri._
____

.Illustration
====
akiñcano

liberated from the perception of existence
====

[quote, Sn.v.455]
____
I wander in the world, a sage, liberated from the perception of existence.

_akiñcano manta carāmi loke._
____

=== Introduction: kiñcanaṃ and kiñci

==== Kiñcana and kiñci: meanings

We will show in this section that the synonyms _kiñcana_ and _kiñci_ have 
these meanings:

1. _kiñcana_: something

2. _kiñci_: something

3. _kiñcana_: anything at all

4. _sakiñcana_: attached to the perception of existence

5. _kiñcana_: attachment to the perception of existence

6. _kiñci_: attachment to the perception of existence

==== 1) kiñcana: something

In the scriptures, _na... kiñcana_ ordinarily means 'nothing':

- 'There is nothing in the world (na... _kiñcanamatthi loke_) which has not 
been seen, heard, sensed, or cognised by you' (Sn.v.1122).

==== 2) kiñci: something

_Kiñci_ equals _kiñcana_ says PED, which can be seen here:

[quote, S.2.100]
____
There is nothing further that a noble disciple needs to do

_ariyasāvakassa natthi kiñci uttariṃ karaṇīyanti._
____

==== 3) Kiñcana: anything at all

We have seen that _kiñcana_ and _kiñci_ can mean 'something.' But sometimes 
_kiñcana_ is better as 'anything at all':

[quote, S.1.12]
____
One should not do anything at all anywhere that is unvirtuous by body, speech, 
or mind.

_Pāpaṃ na kayirā vacasā manasā kāyena vā kiñcana sabbaloke._
____

[quote, Sn.v.951]
____
One for whom there is no thought of anything at all, 'This is mine,' or, 'This 
belongs to others,'

_Yassa natthi idaṃ meti paresaṃ vāpi kiñcanaṃ._
____

==== 4) Sakiñcano: attached to the perception of existence

_Sakiñcanaṃ_ is sometimes contrasted with _akiñcanā_:

[quote, Ud.14]
____
How pleasant it is, for one who is _akiñcanā_... See how they are troubled, 
those who are _sakiñcanaṃ_

_sukhino vata ye akiñcanā... sakiñcanaṃ passa vihaññamānaṃ._
____

And since we have already shown that _akiñcanā_ can mean 'liberated from the 
perception of existence,' _sakiñcanaṃ_ would mean 'attached to the 
perception of existence.' Thus the passage should read:

____
How pleasant it is, for one who is liberated from the perception of existence,

_Sukhino vata ye akiñcanā_
____

____
Those who are blessed with profound knowledge are indeed people liberated from 
the perception of existence

_Vedaguno hi janā akiñcanā_
____

____
See how they are troubled, those who are attached to the perception of 
existence.

_Sakiñcanaṃ passa vihaññamānaṃ_
____

[quote, Ud.14]
____
Man is emotionally bound to man.

_Jano janasmiṃ paṭibaddhacitto ti._
____

==== 5) Kiñcana: attachment to the perception of existence'

If _sakiñcanaṃ_ can mean 'attached to the perception of existence' by 
extension, _kiñcana_ can mean 'attachment to the perception of existence,' for 
example here:

____
Three forms of attachment to the perception of existence:

_tayo kiñcanā_
____

____
... attachment is attachment to the perception of existence,

_rāgo kiñcanaṃ_
____

____
.... hatred is attachment to the perception of existence,

_doso kiñcanaṃ_
____

[quote, D.3.217]
____
... undiscernment of reality is attachment to the perception of existence

_moho kiñcanaṃ._
____

==== 6) Na hoti kiñci: to have no attachment to the perception of existence

But _sakiñcanaṃ_ is sometimes contrasted with _na hoti kiñci_:

[quote, Ud.13]
____
How pleasant it is, for one who _na hoti kiñci..._ See how they are troubled, 
those who are _sakiñcanaṃ_

_sukhaṃ vata tassa na hoti kiñci... sakiñcanaṃ passa vihaññamānaṃ_
____

According to this, _na hoti kiñci_ is equivalent to _akiñcanā_, implying 
that, like _kiñcana, kiñci_ can also mean 'attachment to the perception of 
existence.' Thus the quote can be translated like this:

[quote, Ud.13]
____
How pleasant it is, for one with no attachment to the perception of existence, 
who has mastered the teaching, who is learned. See how they are troubled, those 
who are attached to the perception of existence. Man is emotionally bound to 
man.

_Sukhaṃ vata tassa na hoti kiñci saṅkhātadhammassa bahussutassa +
Sakiñcanaṃ passa vihaññamānaṃ jano janasmiṃ paṭibaddharūpo ti._
____

=== Illustrations: kiñcanaṃ, kiñci

.Illustration
====
sakiñcano

attached to the perception of existence; akiñcanaṃ liberated from the 
perception of existence
====

____
I do not call one a Brahman due to one's birth from a particular womb, or due 
to having arisen from a particular mother.

_Na cāhaṃ brāhmaṇaṃ brūmi yonijaṃ mattisambhavaṃ_
____

____
If he is attached to the perception of existence, [one who nonetheless regards 
himself a Brahman] is simply a snob.

_Bhovādi nāma so hoti sace hoti sakiñcano_
____

[quote, Sn.v.620; Dh.v.396]
____
But one who is liberated from the perception of existence, free of grasping, he 
is what I call a Brahman.

_Akiñcanaṃ anādānaṃ tamahaṃ brūmi brāhmaṇaṃ._
____

.Illustration
====
natthi kiñcī

there is [nowhere] anything at all
====

[quote, M.1.293]
____
The state of awareness of nonexistence can be known, where one perceives that 
there is [nowhere] anything at all

_natthi kiñcī ti ākiñcaññāyatanaṃ neyyan ti._
____

.Illustration
====
natthi kiñcanaṃ

there is [nowhere] anything at all
====

____
The world [of beings], fettered by undiscernment of reality, appears truly 
fit-for-purpose.

_Mohasambandhano loko bhabbarūpo va dissati_
____

____
... For the fool tethered by attachment and blanketed in darkness

_Upadhisambandhano bālo tamasā parivārito_
____

[quote, Ud.79]
____
... it indeed seems eternal, but for one who sees [the nature of reality], 
there is [nowhere] anything at all.

_Sassato-r-iva khāyati passato natthi kiñcanaṃ ti._
____

.Illustration
====
natthi kiñcanaṃ

there is [nowhere] anything at all; akiñcanaṃ liberated from the perception 
of existence
====

____
A person for whom there is [nowhere] anything at all in either the past, the 
future, or the present,

_Yassa pure ca pacchā ca majjhe ca natthi kiñcanaṃ_
____

[quote, Sn.v.645]
____
Who is liberated from the perception of existence, free of grasping, he is what 
I call a Brahman.

_Akiñcanaṃ anādānaṃ tamahaṃ brūmi brāhmaṇaṃ._
____

.Illustration
====
natthi kiñcanaṃ

there is [nowhere] anything at all
====

[quote, Ud.80]
____
For one who has mastered craving, for one who knows and sees [the nature of 
reality], there is [nowhere] anything at all.

_Paṭividdhā taṇhā jānato passato natthi kiñcanaṃ ti._
____

