== Ārambha; Sārambha; Samārambha

=== Renderings

==== Usual meanings

- _ārambha_: exertion

- _ārambha_: slaughter

- _samārambha_: slaughter

- _samārambha_: destruction

- _sārambha_: aggressive

- _sārambha_: aggressiveness

==== Harmful conduct

- _ārambha_: harmful conduct

- _samārambha_: harmful conduct

- _sārambha_: harmful conduct

==== Ārabhati

- _ārabhati_: to kill

- _ārabhati_: to exert (energy)

==== Samārambha, minor meanings

- _samārambha_: onerous

- _samārambha_: arrangement

=== Introduction

==== Ārambha: exertion

In the context of energy (_viriya_)_, ārambha_ means exertion:

1. 'Struggling with hands and feet' represents the exertion of energy.
+
****
_satthehi ca pādehi ca vāyāmo ti kho bhikkhave viriyārambhassetaṃ 
adhivacanaṃ_ (It.114).
****

2. There are the phenomenon of exertion, the phenomenon of endeavour, the 
phenomenon of application [to the practice]. Much proper contemplation in that 
regard is a condition that nourishes both the arising of the unarisen 
enlightenment factor of energetic application [to the practice], and the 
perfection through spiritual cultivation of the arisen enlightenment factor of 
energetic application [to the practice].
+
****
_Atthi bhikkhave ārambhadhātu nikkamadhātu parakkamadhātu. Tattha yoniso 
manasikārabahulīkāro ayamāhāro anuppannassa vā viriyasambojjhaṅgassa 
uppādāya uppannassa vā viriyasambojjhaṅgassa bhāvanāya pāripūriyā_ 
(S.5.104).
****

==== Ārambha: slaughter

_Ārambha_ can also mean slaughter:

[quote, S.1.76]
____
The horse sacrifice, the human sacrifice, the Sammāpāsa sacrifice, the 
Vājapeyya sacrifice, the Niraggala sacrifice, great sacrifices, great acts of 
slaughter, are not of much fruit.

_Assamedhaṃ purisamedhaṃ sammāpāsaṃ vājapeyyaṃ niraggalaṃ +
Mahāyaññā mahārambhā na te honti mahapphalā._
____

==== Ārabhati: kill or exert (energy)

Ārabhati has two meanings, corresponding to the double maning of _ārambha_: 
kill, and exert.

1. In this regard, bhikkhus, some person kills and is conscience-stricken.
+
****
_Idha bhikkhave ekacco puggalo ārabhati ca vippaṭisāri ca hoti_ (A.3.165).
****

2. They kill living beings
+
****
_pāṇaṃ ārabhanti_ (M.1.368).
****

3. If anyone slaughters a living being for the Perfect One or his disciple, he 
begets much demerit on five occasions.
+
****
_Yo kho jīvaka tathāgataṃ vā tathāgatasāvakaṃ vā uddissa pāṇaṃ 
ārabhati. So pañcahi ṭhānehi bahuṃ apuññaṃ pasavati_ (M.1.371).
****

4. He stirs up eagerness, endeavours, applies energy, exerts his mind, and 
strives.
+
****
_chandaṃ janeti vāyamati viriyaṃ ārabhati cittaṃ paggaṇhāti 
padahati_ (M.2.26).
****

==== Samārambha: slaughter or destruction

_Samārambha_ commonly means slaughter or destruction:

1. Formerly there were just three illnesses: desire, hunger, and old age. But 
from the slaughter of cattle came ninety-eight.
+
****
_Tayo rogā pure āsuṃ icchā anasanaṃ jarā +
****
Pasūnañca samārambhā aṭṭhānavuti-m-āgamuṃ_ (Sn.v.311).

2. The ascetic Gotama abstains from destroying seeds and plants.
+
****
_Bījagāmabhūtagāmasamārambhā paṭivirato samaṇo gotamo_ (D.1.5).
****

==== Sārambha: aggressiveness or aggressive

_Sārambha_ usually means aggressive or aggressiveness:

1. Speaking aggressively in relation to views, they do not transcend the round 
of birth and death.
+
****
_Diṭṭhisu sārambhakathā saṃsāraṃ nātivattatī ti_ (Ud.70).
****

2. Speak not harshly to anyone. Those spoken to might retort. Aggressive speech 
is unpleasant. Retaliation might befall you.
+
****
_Māvoca pharusaṃ kañci vuttā paṭivadeyyuṃ taṃ +
****
Dukkhā hi sārambhakathā paṭidaṇḍā phuseyyuṃ taṃ_ (Dh.v.133).

3. Sensuous pleasures in this lifetime; sensuous pleasures in the hereafter... 
lead to unvirtuous, spiritually unwholesome mental states such as greed, ill 
will, and aggressiveness, which arise for the spiritual obstruction in this 
world of the noble disciple in training.
+
****
_ye ca diṭṭhadhammikā kāmā ye ca samparāyikā kāmā... etthete 
pāpakā akusalā mānasā abhijjhāpi vyāpādāpi sārambhāpi saṃvattanti 
teva ariyasāvakassa idhamanusikkhato antarāyāya sambhavanti_ (M.2.262).
****

==== 'Harmful conduct'

In some circumstances, _ārambha, samārambha,_ and __sārambha__can mean 
'harmful conduct'. This meaning is acknowledged in DOP under _Ārambha_, and 
called 'wrongly directed exertion or action'. This is close in meaning to 
_akusala_, and could therefore be called 'spiritually unwholesome conduct.' But 
because the three words usually mean 'aggression' and 'slaughter,' we prefer 
'harmful conduct.' We illustrate this as follows:

1. _Ārambha_: harmful conduct
+
[quote, Sn.v.744]
____
Whatever suffering arises, all of it arises dependent on harmful conduct. That 
is the first consideration.

_Yaṃ kiñci dukkhaṃ sambhoti sabbaṃ ārambhapaccayā ti. 
Ayamekānupassanā_

With the complete fading away and ending of harmful conduct, there is no 
arising of suffering. That is the second consideration.

_arambhānaṃ tveva asesavirāganirodhā natthi dukkhassa sambhavo ti. Ayaṃ 
dutiyānupassanā._
____

2. _Samārambha_: harmful conduct
+
[quote, A.2.197-8]
____
As to those vexatious and anguishing perceptually obscuring states that arise 
due to harmful conduct of body, in the case of one who abstains from such 
harmful conduct of body, it follows that those vexatious and anguishing 
perceptually obscuring states do not exist in him.

_ye kāyasamārambhapaccayā uppajjanti āsavā vighātapariḷāhā 
kāyasamārambhā paṭiviratassa evaṃsa te āsavā vighātapariḷāhā na 
honti._
____

3. _Sārambha_: harmful conduct
+
[quote, Th.v.37]
____
They go to different countries, wandering unrestrained. If they lose their 
inward collectedness, what good will this international travelling do? 
Therefore one should eliminate [such] harmful conduct. One should meditate 
unaccompanied.

_Nānājanapadaṃ yanti vicarantā asaṃyatā +
Samādhiñca virādhenti kiṃsu raṭṭhacariyā karissati +
Tasmā vineyya sārambhaṃ jhāyeyya apurakkhato ti._
____

==== Samārambha's two minor meanings:

_Samārambha_ has two minor meanings. 'Onerous' is unsurprising, being close in 
meaning to _ārambha_, exertion. But 'arrangement' is indeed unexpected.

1. _Samārambha_: onerous (i.e. a food offering is less onerous than an animal 
sacrifice):
+
[quote, D.1.144]
____
The perpetual offerings made by families which are dedicated to virtuous 
ascetics, is a sacrifice less difficult and less onerous and is of more fruit 
and more benefit than the [animal] sacrifice with its three modes and sixteen 
accessories.

_Yāni kho pana tāni brāhmaṇa niccadānāni anukūlayaññāni sīlavanne 
pabbajite uddissa dīyanti ayaṃ kho brāhmaṇa yañño imāya tividhāya 
yaññasampadāya soḷasaparikkhārāya appaṭṭataro ca appasamārambhataro 
ca mahapphalataro ca mahānisaṃsataro cā ti._
____

2. _Samārambha_: arrangement
+
[quote, Vin.4.67]
____
If any bhikkhu knowingly eats almsfood which a bhikkhunī has caused to be 
prepared, unless there was a prior arrangement with the householder, this is an 
offence of pācittiya.

_Yo pana bhikkhu jānaṃ bhikkhunīparipācitaṃ piṇḍapātaṃ bhuñjeyya 
aññatra pubbe gihīsamārambhā pācittiyan ti._
____
+
'Arrangement' is explained in the word commentary as follows:
+
[quote, Vin.4.67]
____
An arrangement with the householder means: either they are one's relatives, or 
&#8203;[the bhikkhus] were [previously] invited, or [the meal] is ordinarily 
&#8203;[scheduled to be] prepared for the bhikkhu.

_Gihīsamārambho nāma ñātaka vā honti pavārikā vā pakatipaṭiyattaṃ vā._
____

