== Ārammaṇa

=== Renderings

- _ārammaṇa_: basis [for spiritual development]

- _ārammaṇa_: basis

- _ārammaṇa_: basis [for the establishment of one's stream of sense 
consciousness]

- _ārammaṇa_: foundation

- _ārammaṇa_: object of mindfulness

- _ārammaṇa_: opportunity [to attack]

=== Introduction

==== Primary meaning

The primary meaning of _ārammaṇa_ is 'foundation,' says PED.

==== Basis [for the establishment of one's stream of sense consciousness]

In this quote we parenthesise _ārammaṇā_ as 'bases [for the establishment 
of his stream of sense consciousness]':

[quote, Sn.v.477]
____
He for whom there are no bases whatsoever [for the establishment of his stream 
of sense consciousness]: the Perfect One is worthy of the oblation.

_Ārammaṇā yassa na santi keci tathāgato arahati pūraḷāsaṃ._
____

Reasons:

1. The commentary says: _Ārammaṇā ti paccayā punabbhavakāraṇānī ti 
vuttaṃ hoti_.

2. This suggests that _ārammaṇaṃ viññāṇassa ṭhitiyā_ is meant, a 
phrase which occurs here, where _ārammaṇaṃ_ is linked to _punabbhava_:

____
Whatever one is intent upon, conceives of, and identifies with, this becomes 
the basis for the establishment of one's stream of sense consciousness.

_yañca bhikkhave ceteti yañca pakappeti yañca anuseti ārammaṇametaṃ 
hoti viññāṇassa ṭhitiyā_
____

____
... When there is the basis, there is the establishment of one's stream of 
sense consciousness.

_Yañca ārammaṇe sati patiṭṭhā viññāṇassa hoti._
____

[quote, S.2.65]
____
... When one's stream of sense consciousness is established and has 
&#8203;[egoistically] matured, renewed states of individual existence and rebirth 
occur in the future.

_Tasmiṃ patiṭṭhite viññāṇe virūḷhe āyatiṃ 
punabbhavābhinibbatti hoti._
____

==== Basis [for spiritual development]

'Basis [for spiritual development]' suits many contexts. See Illustrations.

==== Object of mindfulness

Sometimes _ārammaṇa_ means 'object of mindfulness'. For example, when 
Tāḷapuṭa addressed his mind:

[quote, Th.v.1141]
____
I shall bind you to the object of mindfulness by force as one binds an elephant 
to a post with a firm rope.

__ārammaṇe taṃ balasā nibandhisaṃ nāgaṃ va thambhamhi daḷhāya 
rajjuyā._
____

To support us calling _ārammaṇa_ 'object of mindfulness,' the following 
passage concerns the same themes, of binding an elephant to a post, and where 
the mind is tied to the four bases of mindfulness (_cattāro 
satipaṭṭhānā_). But because _bandhati_ Th.v.1141 takes a locative, 
_ārammaṇe_ is locative singular, not accusative plural, and does not mean 
_cattāro satipaṭṭhānā_. Norman accordingly says, 'I shall bind you to 
the meditation-base by force.'

[quote, M.3.136]
____
As, Aggivessana, an elephant tamer, driving a great post into the ground, ties 
a forest elephant to it by his neck so as to subdue his forest ways, so as to 
subdue his forest memories and thoughts, and so as to subdue his suffering, 
fatigue, and anguish at leaving the forest, so as to make him pleased with 
villages and make him take delight in human ways. Even so, Aggivessana, these 
four bases of mindfulness are to tie the mind so as to subdue the ways of 
householders and to subdue the memories and thoughts of householders and to 
subdue the suffering, fatigue, and anguish of householders; they are for 
acquiring the noble practice, and for realising the Untroubled.

_Seyyathā pi aggivessana hatthidamako mahantaṃ thambhaṃ paṭhaviyaṃ 
nikhaṇitvā āraññakassa nāgassa gīvāyaṃ upanibandhati. 
Āraññakānañceva sīlānaṃ abhinimmadanāya āraññakānañceva 
sarasaṅkappānaṃ abhinimmadanāya āraññakānañceva 
darathakilamathapariḷāhānaṃ abhinimmadanāya gāmante abhiramāpanāya 
manussakantesu sīlesu sampādanāya evameva kho aggivessana ariyasāvakassa 
ime cattāro satipaṭṭhānā cetaso upanibandhanā honti. Gehasitānañceva 
sīlānaṃ abhinimmadanāya gehasitānañceva sarasaṅkappānaṃ 
abhinimmadanāya gehasitānañceva darathakilamathapariḷāhānaṃ 
abhinimmadanāya ñāyassa adhigamāya nibbānassa sacchikiriyāya._
____

Others render the term similarly, as follows:

- Bodhi at S.3.270 'meditation object' (NDB n.305).

- DOP recognises 'basis of meditation.'

For other examples of 'object of mindfulness,' see Illustrations.

==== Opportunity [to attack]

_Ārammaṇa's_ meaning 'opportunity [to attack]' is supported by PED which 
acknowledges 'chance' and 'get a chance.'

=== Illustrations

.Illustration
====
ārammaṇaṃ

basis [for spiritual development]
====

____
And what is the faculty of inward collectedness?

_samādhindriyaṃ_
____

[quote, S.5.197]
____
In this regard, the noble disciple, having made the relinquishment [of 
attachment] the basis [for spiritual development], gains inward collectedness, 
gains mental concentration.

_vossaggārammaṇaṃ karitvā labhati samādhiṃ labhati cittassa 
ekaggataṃ._
____

.Illustration
====
ārammaṇaṃ

basis [for spiritual development]
====

____
For one making offerings, the act of charity is the basis [for spiritual 
development].

__ārammaṇaṃ yajamānassa yaññaṃ_
____

[quote, Sn.v.506]
____
Based on this one abandons one's spiritual flaws.

_ettha patiṭṭhāya jahāti dosaṃ._
____

.Illustration
====
ārammaṇaṃ

basis [for spiritual development]
====

____
We shall abide pervading that person with a mind of [unlimited, 
all-encompassing] goodwill,

_tañca puggalaṃ mettāsahagatena cetasā pharitvā viharissāma._
____

• With this as our basis [for spiritual development] * +
☸* _Tadārammaṇañca_

[quote, M.1.126]
____
we shall abide pervading the whole world [of beings] with a mind of [unlimited, 
all-encompassing] goodwill, vast, exalted, unlimited, free of unfriendliness 
and hostility.

_sabbāvantaṃ lokaṃ mettāsahagatena cetasā vipulena mahaggatena 
appamāṇena averena avyāpajjhena pharitvā viharissāmāti._
____

.Illustration
====
ārammaṇaṃ

basis [for spiritual development] (= anussati ṭhānāni)
====

____
Bhikkhus, there are these six bases of meditation

_Chayimāni bhikkhave anussati ṭhānāni. Katamāni cha_
____

____
In this regard, the noble disciple reflects on the Perfect One:'He is the 
Blessed One...

_tathāgataṃ anussarati: iti pi so bhagavā..._
____

[quote, A.3.313]
____
By making this [reflection] the basis [for spiritual development] some beings 
here are thereby purified.

_Idampi kho bhikkhave ārammaṇaṃ karitvā evamidhekacce sattā visujjhanti._
____

.Illustration
====
ārammaṇaṃ

basis [for spiritual development]
====

____
-- Tell me, All-Seeing Eye, a basis [for spiritual development] supported by 
which I might cross this [wretched] flood [of suffering].

_Ārammaṇaṃ brūhi samantacakkhu yaṃ nissito oghamimaṃ tareyyaṃ_
____

[quote, Sn.v.1069-70]
____
-- Being intent upon the perception of nonexistence, being mindful, with the 
help of the reflection 'It does not exist,' cross the flood [of suffering].

_Ākiñcaññaṃ pekkhamāno satimā natthī ti nissāya tarassu oghaṃ._
____

.Illustration
====
ārammaṇaṃ

basis
====

____
Bhikkhus, there are these two pleasures. What two?

_Dvemāni bhikkhave sukhāni._
____

[quote, A.1.81]
____
The pleasure with rapture as its basis, and the pleasure without rapture as its 
basis.

_sappītikārammaṇañca sukhaṃ nippītikārammaṇañca sukhaṃ._
____

.Illustration
====
ārammaṇaṃ

basis
====

____
Bhikkhus, there are these two pleasures. What two?

_Dvemāni bhikkhave sukhāni_
____

[quote, A.1.82]
____
The pleasure with the refined material states of awareness as its basis, and 
the pleasure with immaterial states of awareness as its basis.

_rūpārammaṇañca sukhaṃ arūpārammaṇañca sukhaṃ._
____

.Illustration
====
ārammaṇā

basis
====

[quote, A.1.83]
____
Bhikkhus, it is with what is originated as their basis that unvirtuous, 
spiritually unwholesome factors arise, not without what is originated.

_Saṅkhatārammaṇā bhikkhave uppajjanti pāpakā akusalā dhammā no 
asaṅkhatārammaṇā._
____

.Illustration
====
ārammaṇā

basis
====

____
Samiddhi, what is the basis upon which man's thoughts arise?

_kimārammaṇā samiddhi purisassa saṅkappavitakkā uppajjantī ti?_
____

[quote, A.4.385]
____
Denomination-and-bodily-form is the basis, bhante.

_nāmarūpārammaṇā bhante ti._
____

.Illustration
====
ārammaṇaṃ

basis
====

A layperson might establish a robe fund for a bhikkhu who is not a relative, 
thinking: 'Having purchased robe material with this fund, I will clothe the 
bhikkhu so and so.'

'For a bhikkhu' means

____
for the good of a bhikkhu

_bhikkhussatthāya_
____

[quote, Vin.3.216]
____
making a bhikkhu the basis [of the robe fund]

_bhikkhuṃ ārammaṇaṃ karitvā._
____

.Illustration
====
ārammaṇaṃ

foundation
====

____
There is that supreme state of deliverance (_tadāyatanaṃ_) where there is 
neither solidness, liquidness, warmth, nor gaseousness; no state of awareness 
of boundless space, no state of awareness of boundless mental consciousness, no 
state of awareness of nonexistence, no state of awareness neither having nor 
lacking perception; neither this world, nor a world beyond, nor both; neither 
sun nor moon.

_Atthi bhikkhave tadāyatanaṃ yattha neva paṭhavī na āpo na tejo na vāyo 
na ākāsānañcāyatanaṃ na viññāṇañcāyatanaṃ na 
ākiñcaññāyatanaṃ na nevasaññānāsaññāyatanaṃ nāyaṃ loko na 
paraloko na ubho candimasūriyā._
____

____
There, I declare, there is no coming, no going, no staying, no passing away, no 
being reborn.

_Tatrāpāhaṃ bhikkhave neva āgatiṃ vadāmi na gatiṃ na ṭhitiṃ na 
cutiṃ na upapattiṃ._
____

____
It is neither fixed, nor moving, and has no foundation

_appatiṭṭhaṃ appavattaṃ anārammaṇamevetaṃ_
____

[quote, Ud.80]
____
This is truly the end of suffering

_Esevanto dukkhassā ti._
____

.Illustration
====
ārammaṇaṃ

object of mindfulness
====

[quote, S.5.156]
____
While he is contemplating the nature of the body, there arises in him, with the 
body as the object of mindfulness, either bodily anguish, or mental 
sluggishness, or his mind is distracted outwardly.

_tassa kāye kāyānupassino viharato kāyārammaṇo vā uppajjati kāyasmiṃ 
pariḷāho cetaso vā līnattaṃ bahiddhā vā cittaṃ vikkhipati._
____

The sutta continues:

____
with sense impressions as the object of mindfulness

_vedanāsu vedanānupassino viharato vedanārammaṇo vā uppajjati kāyasmiṃ 
pariḷāho_
____

____
with the mind as the object of mindfulness

_citte cittānupassino viharato cittārammaṇo vā uppajjati kāyasmiṃ 
pariḷāho_
____

____
with certain objects of the systematic teachings as the object of mindfulness

_dhammesu dhammānupassino viharato dhammārammaṇo vā uppajjati kāyasmiṃ 
pariḷāho_
____

.Illustration
====
ārammaṇaṃ

opportunity [to attack]
====

[quote, D.3.58]
____
Keep to your own sphere of personal application, to your ancestral haunts. If 
you do so, Māra will not get his chance, his opportunity [to attack] you.

_Gocare bhikkhave caratha sake pettike visaye. Gocare bhikkhave carataṃ sake 
pettike visaye na lacchati māro otāraṃ na lacchati māro ārammaṇaṃ._
____

.Illustration
====
ārammaṇaṃ

opportunity [to attack]
====

Suppose, friends, there is a peaked house or a hall built of thickly packed 
clay and freshly plastered. If a man approaches it from the east with a blazing 
grass torch, or the west, the north, south, from below, or above, whichever way 
he approaches it:

[quote, S.4.187]
____
the fire does not get its chance, its opportunity [to attack] the building.

_neva labhetha aggi otāraṃ na labhetha aggi ārammaṇaṃ._
____

.Illustration
====
ārammaṇaṃ

opportunity [to attack]
====

____
Bhikkhus, at the present time the Licchavis dwell using blocks of wood as 
cushions; they are diligently and vigorously applied to the practice of 
archery. With these, King Ajātasattu of Magadha, the son of Queen Videha, has 
no chance, no opportunity [to attack] them.

_na labhati otāraṃ na labhati ārammaṇaṃ_
____

But in the future the Licchavis will become delicate, with soft and tender 
hands and feet; they will sleep until sunrise on soft beds with pillows of 
cotton wool. Then King Ajātasattu of Magadha will get his chance, his 
opportunity [to attack] them (S.2.268).

