== Āsava

=== Renderings

- _āsava_ (singular): perceptual obscuration

- _āsavā_ (plural): perceptually obscuring states

- _kāmāsava_: perceptual obscuration due to pursuing sensuous pleasure

- _bhavāsava_: perceptual obscuration due to pursuing individual existence

- _avijjāsava_: perceptual obscuration due to uninsightfulness into reality

- _sāsava_: associated with perceptually obscuring states

- _khīṇāsava_: one whose _āsavas_ are destroyed

Singular forms of _āsava_ commonly indicate the uncountable noun ('perceptual 
obscuration'). Plural forms indicate the countable noun ('perceptually 
obscuring states').

=== Introduction

==== On translating 'āsava'

- The PED says _āsavas_ 'intoxicate the mind, bemuddle it, befoozle it, so 
that it cannot rise to higher things' but it admits the 'difficulty of 
translating the term.'

- Horner says _āsava_ has 'always been a problem to translators' 
(MLS.1.xxiii). She calls it 'canker' because 'I have come on no other 
translation that seems preferable,' and by which she means 'anything that 
frets, corrodes, corrupts, or consumes slowly and secretly.'

- Mrs. Rhys Davids also accepts 'canker.' She says that in canker 'we lose the 
liquid meaning, the permeation, as of ink on blotting-paper, and which is kept 
in view in "intoxicants," "drugs," "floods," "poisons"' (GS.3.ix).

But because _āsavas_ are defiling (_saṅkilesikā_), they are sometimes 
called 'taints.' And sometimes the word is left untranslated, for example by 
Norman (in _The Group of Discourses_), by Malalasekera (in _The Buddhist 
Dictionary of Pāli Proper Names_) and even by the Pāli dictionaries 
themselves. For example, the DOP renderings are:

_• āsavakkhaya_: 'destruction of the _āsavas'_

_• āsavakhīṇa_: 'with _āsavas_ destroyed; free of the _āsavas'_

_• āsavaṭṭhānīya_, being a basis or cause of the _āsavas_

_• anāsava_: 'free of the _āsavas'_

_• sāsava_: 'connected with the _āsavas'_

==== Primary sense: outflow and intoxicating product

The 'liquid meaning' is supported by the primary sense of _āsava_, which is 
found as an alternative reading in certain Pāli editions, namely 'discharge 
from a sore.' This is illustrated in the following passage, where the PTS and 
VRI alternative reading for _assandati_ (to ooze) is _āsavaṃ deti_ (to 'give 
an outflow'):

• When a sore is beaten with a stick or shard, it oozes (or, 'gives an 
outflow') all the more. +
☸ _duṭṭhārukā kaṭṭhena vā kaṭhalena vā ghaṭṭitā 
bhiyyosomattāya assandati_ (_āsavaṃ deti_) (A.1.127).

However, _āsava_ has another primary sense, namely 'intoxicating product' 
which can be seen in the definition of alcoholic spirits (_merayo_), as follows:

[quote, Vin.4.110]
____
Alcoholic spirits means the intoxicating product of flowers, fruits, honey, 
sugar'

_Merayo nāma pupphāsavo phalāsavo madhvāsavo guḷāsavo._
____

T.W. Rhys Davids was unaware of this definition when in 1899 he said:

- 'Unfortunately, the word _āsava_ has not been yet found in its concrete, 
primary, sense; unless indeed Buddhaghosa's statement (at Asl. 48) that well 
seasoned spirituous liquors were called _āsavā_ be taken literally. It is 
therefore impossible to be sure what is the simile that underlies the use of 
the word in its secondary, ethical sense. Perhaps after all it is the idea of 
overwhelming intoxication, and not of flood or taint or ooze, that we ought to 
consider' (Dialogues.1.92 n.3).

When the Buddha was conversing with bhikkhus over the body of the inebriated 
venerable Sāgata, he asked them:

[quote, Vin.4.110]
____
But would one have deranged perception (_visaññi assā_) if one drunk only 
that which may be drunk?"

_Api nu kho bhikkhave taṃ pātabbaṃ yaṃ pivitvā visaññi assā ti._
____

If _āsava_ is the basis of alcoholic deranged perception, the same term was 
likely used in reference to the spiritual defilements that are the bases of the 
mental derangement that we will call 'perceptual obscuration,' concerning which 
the Buddha said:

[quote, A.2.143]
____
Those beings are hard to find in the world who can claim to be free of mental 
illness even for a moment except the one whose _āsavas_ are destroyed.

_Te bhikkhave sattā dullabhā lokasmiṃ ye cetasikena rogena muhuttampi 
ārogyaṃ paṭijānanti aññatra khīṇāsavehi._
____

==== The obscuring nature of āsavas

In this Glossary _āsavas_ are called 'perceptually obscuring states' (plural) 
or perceptual obscuration (singular) because of the obscuring role they play in 
perception, and which is illustrated in _paṭiccasamuppāda_, as follows:

[quote, M.1.46-56]
____
With the origination of perceptual obscuration comes the origination of 
uninsightfulness into reality

__āsavasamudayā avijjāsamudayo._
____

The obscuring role of _āsavas_ is also described in terms of _sammūḷho,_ 
like this:

[quote, M.1.250]
____
It is through the non-abandonment of perceptually obscuring states that one is 
undiscerning of reality

_Āsavānaṃ hi aggivessana appahānā sammūḷho hoti._
____

[quote, M.1.250]
____
It is through the abandonment of perceptually obscuring states that one is 
discerning of reality.

_Āsavānaṃ hi aggivessana pahānā asammūḷho hoti._
____

==== Singulars and plurals

In the scriptures, _āsava_ moves freely between singulars and plurals. For 
example, the _Sammādiṭṭhi Sutta_ (M.1.55) asks:

____
And what is perceptual obscuration? What is the origin of perceptual 
obscuration?

_Katamo panāvuso āsavo? Katamo āsavasamudayo?_
____

The answer is:

____
There are these three perceptually obscuring states:

_Tayo'me āvuso āsavā_
____

1. perceptual obscuration due to pursuing sensuous pleasure
+
****
_kāmāsavo_
****

2. perceptual obscuration due to pursuing individual existence
+
****
_bhavāsavo_
****

3. perceptual obscuration due to uninsightfulness into reality
+
****
_avijjāsavo_.
****

Horner stays true to the singular/plural, but the result is awkward, and her 
translation stumbles in the opening questions, which involve an uncountable 
noun, not a countable noun:

- 'And what, your reverences, is a canker? What the uprising of a canker?.'.. 
Your reverences, there are these three cankers: the canker of sense-pleasures, 
the canker of becoming, the canker of ignorance.'

Bodhi deals with the problem by pluralising:

- 'And what are the taints? What is the origin of the taints? There are these 
three taints: the taint of sensuous desire, the taint of being, and the taint 
of ignorance.'

But Pāli grammars do not support pluralising. This counts against most 
renderings of _āsava_ because they are unuseable without it, including: 
'intoxicants,' 'drugs,' 'floods,' 'poisons.'

==== How many āsavas?

In the scriptures there are two categories of _āsavas_:

1. A broad, undefined category which includes a wide range of defilements. The 
_pañca nīvaraṇā_ are practically part of this category. This category of 
_āsavas_ are gradually worn down from stream-entry onwards. We will discuss 
these points in due course.

2. A narrow, well-defined category which is clearly differentiated from the 
_pañca nīvaraṇā_ and occurs in the scriptures only in relation to 
arahantship. In this narrow, well-defined category there are three _āsavas_: 
_kāmāsavo bhavāsavo_ and _avijjāsavo. Diṭṭhāsavo_ is controversial. It 
occurs just once in the scriptures (at A.4.179), and in a note to this passage 
(NDB n.1649) Bodhi says the word occurs only in the Sinhala edition, not the 
Roman or Burmese editions. Furthermore, elsewhere in the Sinhala edition, 
parallel passages make no reference to _diṭṭhāsavo_. Thus the occurrence 
at A.4.179 is likely interpolative. Hence, like Bodhi, we discount it.

==== The connective in kāmāsavo, bhavāsavo, and avijjāsavo

The terms _kāmāsavo bhavāsavo_ and _avijjāsavo_ are commonly translated 
with the connective 'of.' For example, Bodhi says 'the taint of sensuality,' 
'the taint of existence' and 'the taint of ignorance.' But the scriptures say 
the connective is _paccayā_ 'due to.' For example, in the _Vappa Sutta_ 
(A.2.196-7) the Buddha divides _āsavas_ into two groups:

1. _āsavas_ which arise due to harmful conduct of body, speech, or mind 
(_kāya... vacī... manosamārambhapaccayā uppajjanti āsavā_) and which do 
not exist in one who abstains from such endeavours (_kāya... vacī... 
manosamārambhā paṭiviratassa evaṃsa te āsavā vighātapariḷāhā na 
honti_).

2. _āsavas_ which arise due to _avijjā_ (_avijjāpaccayā uppajjanti 
āsavā_) and when _avijjā_ vanishes and _vijjā_ arises (_avijjāvirāgā 
vijjuppādā_), those vexatious and anguishing _āsavas_ do not exist in him 
(_evaṃsa te āsavā vighātapariḷāhā na honti_).

==== Translating kāmāsavo, bhavāsavo, and avijjāsavo

The twofold division of the _Vappa Sutta_ should be compared to the usual 
threefold division (D.3.216), namely:

1. _kāmāsavo_

2. _bhavāsavo_

3. _avijjāsavo_

Here, _avijjāsavo_ corresponds to _avijjāpaccayā uppajjanti āsavā_, and 
_kāmāsavo_ and _bhavāsavo_ would then necessarily correspond to _kāya... 
vacī... manosamārambhapaccayā uppajjanti āsavā_ because the division is 
comprehensive_._ There are no _āsavas_ outside this twofold division. We infer 
from this that:

_• avijjāsavo_ means the _āsavo_ that arises due to _avijjā._

_• kāmāsavo_ means the _āsavo_ that arises due to endeavour by body, 
speech, or mind in relation to sensuous pleasure, which we will call 'the 
_āsava_ due to pursuing sensuous pleasure.'

_• bhavāsavo_ means the _āsavo_ that arises due to endeavour by body, 
speech, or mind in relation to states of individual existence, which we will 
call 'the _āsava_ due to pursuing individual existence.'

Because we render _āsava_ as 'perceptual obscuration,' these become:

_• avijjāsavo_: perceptual obscuration due to _avijjā._

_• kāmāsavo_: perceptual obscuration due to pursuing sensuous pleasure.'

_• bhavāsavo_: perceptual obscuration due to pursuing individual existence.

Here the sources of _āsavas_ are not themselves _āsavas_. Thus _avijjāsava_ 
does not mean the _āsava_ of _avijjā_ but the _āsava_ due to _avijjā_; and 
so on. This is in accordance with _paṭiccasamuppāda_ which says _āsava_ is 
due to _avijjā_ (_avijjāsamudayā āsavasamudayo_ (M.1.55).

We also see that _āsavas_ are either _paccayā uppajjanti āsavā_ ('_āsavas_ 
due to') or _samārambhapaccayā uppajjanti āsavā_ ('_āsavas_ due to 
pursuing') the former occurring with _avijjā_ the latter with acts of body, 
speech, and mind (_kāya... vacī... mano_).

==== Translating āsavā plural

In the cases above, _āsava_ is in the singular case, indicating a state of 
perceptual obscuration (singular) due to some condition. But in the 
_Nissāraṇīya Sutta_ (A.3.245) the _āsavas_ are _paccayā uppajjanti 
āsavā_ indicating perceptually obscuring states (plural) due to some 
condition. We have seen above that, when not associated with _avijjā, āsavas_ 
are _samārambhapaccayā uppajjanti āsavā,_ i.e. 'perceptually obscuring 
states that arise due to pursuing.' But in relation to mental factors like ill 
will or maliciousness, to have these states is to pursue them. Therefore we 
will refer to 'perceptually obscuring states that arise due to ill will or 
maliciousness' rather than 'perceptually obscuring states that arise due to 
pursuing ill will or maliciousness.' Accordingly, the _Nissāraṇīya Sutta_ 
can be translated as follows:

_• kāmapaccayā uppajjanti āsavā_: perceptually obscuring states that 
arise due to pursuing sensuous pleasure

_• vyāpādapaccayā uppajjanti āsavā_: perceptually obscuring states that 
arise due to ill will

_• vihesāpaccayā uppajjanti āsavā_: perceptually obscuring states that 
arise due to maliciousness

_• rūpapaccayā uppajjanti āsavā_: perceptually obscuring states that 
arise due to pursuing refined material states of awareness

_• sakkāyapaccayā uppajjanti āsavā_: perceptually obscuring states that 
arise due to pursuing personal identity.

==== Potaliya Sutta: paccayā uppajjanti āsavā

____
The _Potaliya Sutta_ (M.1.361) is another sutta where the connective is 
_paccayā uppajjanti_. It says that 'whereas vexatious and anguishing 
perceptually obscuring states would arise due to killing, there are no 
vexatious and anguishing perceptually obscuring states in abstaining from it.'

_ye ca pāṇātipātapaccayā uppajjeyyuṃ āsavā vighātapariḷāhā 
pāṇātipātā paṭiviratassa evaṃsa te āsavā vighātapariḷāhā na 
honti_
____

The same is said of stealing, lying, malicious speech, rapacious greed 
(_giddhilobho_), spiteful scolding (_nindāroso_), angry despair 
(_kodhūpāyāso_) and arrogance (_atimāno_). Here the words 'pursuing' is 
again redundant. To kill is to pursue killing. To be arrogant is to pursue 
arrogance.

==== Ārabhati Sutta: ārambhajā āsavā

The _Ārabhati Sutta_ (A.3.165) says _āsavas_ are 'born of.' For example, if 
someone kills and is conscience-stricken, he should be advised that 
perceptually obscuring states born of killing are found in him (_ārambhajā 
āsavā saṃvijjanti_), and perceptually obscuring states born of an uneasy 
conscience are developing (_vippaṭisārajā āsavā pavaḍḍhanti_). But to 
say that _āsavas_ are 'born of' certain conditions is the same as saying they 
are 'due to' those conditions, which is our preferred phrasing.

==== How pursuit leads to āsavas

The way that pursuit leads to _āsavas_ can be seen throughout the scriptures. 
For example:

1. There is the quality of loveliness. Much improper contemplation in that 
regard is a condition that nourishes both the arising of unarisen sensuous 
hankering, and the increase and expansion of arisen sensuous hankering.
+
****
_Atthi bhikkhave subhanimittaṃ. Tattha ayoniso manasikārabahulīkāro 
ayamāhāro anuppannassa vā kāmacchandassa uppādāya uppannassa vā 
kāmacchandassa bhiyyobhāvāya vepullāya_ (S.5.105).
****

2. And what are the issues that should not be contemplated that he contemplates?
+
****
_Katame ca bhikkhave dhammā na manasikaraṇīyā ye dhamme manasikaroti?_
****

... Whatever issues that, when he contemplates them:

____
... unarisen perceptual obscuration due to pursuing sensuous pleasure arises, 
and arisen perceptual obscuration due to pursuing sensuous pleasure increases

_anuppanno vā kāmāsavo uppajjati uppanno vā kāmāsavo pavaḍḍhati_
____

____
... unarisen perceptual obscuration due to pursuing individual existence 
arises, and arisen perceptual obscuration due to pursuing individual existence 
increases

_anuppanno vā bhavāsavo uppajjati uppanno vā bhavāsavo pavaḍḍhati_
____

[quote, M.1.7]
____
... unarisen perceptual obscuration due to uninsightfulness into reality 
arises, and arisen perceptual obscuration due to uninsightfulness into reality 
increases.

_anuppanno vā avijjāsavo uppajjati uppanno vā avijjāsavo pavaḍḍhati._
____

3. In this regard a bhikkhu, properly reflecting, abides with the faculty of 
sight restrained through restraint [of attraction and repulsion, through 
mindfulness]. The vexatious and anguishing perceptually obscuring states that 
would arise if he were to abide with the faculty of sight unrestrained through 
unrestraint [of attraction and repulsion, through mindfulness] do not arise for 
him when he abides with the faculty of sight restrained through restraint [of 
attraction and repulsion, through mindfulness].
+
****
_Idha bhikkhave bhikkhu paṭisaṅkhā yoniso cakkhundriyasaṃvarasaṃvuto 
viharati. Yaṃ hi'ssa bhikkhave cakkhundriyasaṃvaraṃ asaṃvutassa 
viharato uppajjeyyuṃ āsavā vighātapariḷāhā 
cakkhundriyasaṃvarasaṃvutassa viharato evaṃsa te āsavā 
vighātapariḷāhā na honti_ (M.1.9).
****

==== Sāsavo: 'associated with perceptually obscuring states'

____
Sometimes the scriptures use the term _sāsavo_, which we render as 'associated 
with perceptually obscuring states.' For example, the _Sāsava Sutta_ (A.5.242) 
says the factors of the wrong tenfold path are 'associated with perceptually 
obscuring states.'

_micchādiṭṭhi... micchāvimutti. Ayaṃ vuccati bhikkhave sāsavo dhammo_
____

____
Whereas right factors are 'free of perceptually obscuring states'

_sammādiṭṭhi... sammāvimutti. Ayaṃ vuccati bhikkhave anāsavo dhammo ti_
____

The _Sāsavadhamma Sutta_ (A.5.275) defines the issue in terms of acts, not 
path factors. It says that although unrighteous acts, like killing, are 
'associated with perceptually obscuring states' (_sāsavo dhammo_) righteous 
acts, like refraining from killing, are not (_anāsavo dhammo_).

Here, unrighteous acts include stealing, sexual misconduct, lying, malicious 
speech, harsh speech, frivolous speech, greed (_abhijjhā_), ill will 
(_vyāpādo_), and wrong view [of reality] (_micchādiṭṭhi_).

==== Sabbāsava Sutta: examples of āsavas

We will now give specific examples of āsavas. The _Sabbāsava Sutta_ (M.1.9) 
lists the first three ties to individual existence (_saṃyojanāni_):

____
the view of personal identity _

_sakkāyadiṭṭhi_
____

____
doubt [about the significance of the teaching]

_vicikicchā_
____

____
adherence to observances and practices

_sīlabbataparāmāso_
____

____
It says when the noble disciple reflects on the four noble truths these ties to 
individual existence are abandoned, and calls them 'perceptually obscuring 
states to be abandoned by seeing' (i.e. by seeing the four noble truths).

_sakkāyadiṭṭhi vicikicchā sīlabbataparāmāso. Ime vuccanti bhikkhave 
āsavā dassanā pahātabbā._
____

These three ties are therefore _āsavas_, perceptually obscuring states.

==== Chabbisodhana Sutta: examples of āsavas

The _Chabbisodhana Sutta_ (M.3.32) says an arahant may be asked in what way he 
knows and sees with regard to the six senses and their objects, that through 
being without grasping his mind is liberated [from perceptually obscuring 
states] (_imesu chasu ajjhattikabāhiresu āyatanesu anupādāya āsavehi 
cittaṃ vimuttan ti_).

He would reply that through the destruction, fading away, ending, giving up, 
and relinquishment (_khayā virāgā nirodhā cāgā paṭinissaggā_) of

- fondness (_chando_),

- attachment (_rāgo_),

- spiritually fettering delight (_nandi_),

- craving (_taṇhā_),

- clinging and grasping (_upayupādānā_),

- obstinate adherence, stubborn attachment, and identification (_cetaso 
adhiṭṭhānābhinivesānusayā_)

regarding the visual sense, visible objects, etc (_cakkhusmiṃ āvuso rūpe 
cakkhuviññāṇe cakkhuviññāṇaviññātabbesu dhammesu_) he knows that 
his mind is liberated [from perceptually obscuring states] (_vimuttaṃ me 
cittan ti pajānāmi_).

Thus fondness, attachment etc are _āsavas_, perceptually obscuring states.

==== Dutiya Bhikkhu Sutta: examples of āsavas

The Dutiya Bhikkhu Sutta (S.5.8) equates destruction of perceptually obscuring 
states to the elimination of _rāga, dosa,_ and _moha_:

____
The elimination of attachment, hatred, and undiscernment of reality: the 
destruction of perceptually obscuring states is spoken of in that way.

_rāgavinayo dosavinayo mohavinayo ti āsavānaṃ khayo tena vuccatī ti_
____

Thus _rāga, dosa,_ and _moha_ are _āsavas_, perceptually obscuring states.

==== Sabbāsava and Kuṇḍaliya Suttas: examples of āsavas

[quote, M.1.9]
____
Some examples of _āsavas_ can be derived from comparison of texts. For 
example, the _Sabbāsava Sutta_ says 'vexatious and anguishing _āsavas_ would 
arise if one were to abide with an uncontrolled faculty of sight.

_cakkhundriyasaṃvaraṃ asaṃvutassa viharato uppajjeyyuṃ āsavā 
vighātapariḷāhā._
____

The _Kuṇḍaliya Sutta_ (S.5.73) explains what those _āsavas_ are. It says 
if there is restraint of the sense faculties [from attraction and repulsion, 
through mindfulness] (_indriyasaṃvaro_) one does not long for 
(_nābhijjhati_) or get excited by (_nābhihaṃsati_) or become attached to 
(_na rāgaṃ janeti_) delightful objects, nor become disconcerted by (_na 
maṅku hoti_), daunted (_apatitthinacitto_), dejected (_adīnamanaso_) or 
unbenevolent (_avyāpannacetaso_) regarding objectionable objects.

Longing, excitement, and attachment are therefore _āsavas_, perceptually 
obscuring states. And so are disconcertedness, dauntedness, dejectedness, and 
ill will ('unbenevolence').

==== Devadattavipatti and Dutiyalokadhamma Suttas: examples of āsavas

The _Devadattavipatti Sutta_ (A.4.161) says a bhikkhu should abide continuously 
mastering (_abhibhuyya abhibhuyya vihareyya_) the eight worldly conditions 
(acquisition, loss, prestige, imprestige etc), otherwise vexatious and 
anguishing _āsavas_ will arise (_uppajjeyyuṃ āsavā vighātapariḷāhā_).

The _Dutiyalokadhamma Sutta_ (A.4.157) explains what those _āsavas_ are. It 
says that instead of reflecting on the nature of the eight worldly conditions 
(_so ca kho anicco dukkho vipariṇāmadhammo ti_), the ignorant Everyman 
welcomes (_anurujjhati_) what he likes and rejects (_paṭivirujjhati_) what he 
dislikes.

Therefore welcoming and rejecting are _āsavas_, perceptually obscuring states.

==== Sampasādaniya Sutta: examples of āsavas

The _Sampasādaniya Sutta_ (D.3.112) says the nine psychic powers, for example 
multiplying one's body, are associated with perceptually obscuring states and 
with attachment (_iddhi yā sāsavā saupadhikā_). The association of 
_sāsavā_ and _saupadhikā_ suggests the two words are associated in meaning, 
and that attachment (_upadhi_) is therefore an _āsava_, a perceptually 
obscuring state.

==== Jatukaṇṇī Sutta: examples of āsavas

The _Jatukaṇṇī Sutta_ says:

[quote, Sn.v.1100]
____
For one completely free of greed for denomination-and-bodily-form, brahman, 
there are no _āsavas_ by reason of which he would go into the power of death.

_Sabbaso nāmarūpasmiṃ vītagedhassa brāhmaṇa +
Āsavāssa na vijjanti yehi maccuvasaṃ vaje ti._
____

Greed (_gedha_) is therefore an _āsava_, a perceptually obscuring state.

==== Mahācattārīsaka Sutta: examples of āsavas

The _Mahācattārīsaka Sutta_ (M.3.72) says the eightfold path is twofold: one 
aspect is 'associated with perceptually obscuring states, that is meritorious 
and results in attachment' (_sāsavo puññabhāgiyo upadhivepakko_), the other 
aspect is not (_ariyo anāsavo_). The meaning _āsava_ here is to be found in 
the word _upadhivepakkā_, 'result in attachment.'

If _āsavas_ 'result in attachment,' then they are represented by _taṇhā_ 
because 'when there is _taṇhā_, _upadhi_ arises' (_taṇhāya sati upadhi 
hoti_ S.2.108). Therefore, as we have already noted above, _taṇhā_ is an 
_āsava_, a perceptually obscuring state.

==== Āsavakkhaya Sutta: examples of āsavas

The _Āsavakkhaya Sutta_ says:

____
'Bhikkhus, I declare that the destruction of the _āsavas_ is for one who knows 
and sees, not for one who does not know and see. Knowing and seeing what are 
the _āsavas_ destroyed?

_Jānato ahaṃ bhikkhave passato āsavānaṃ khayaṃ vadāmi no ajānato no 
apassato. Kiñca bhikkhave jānato kiṃpassato āsavānaṃ khayo hoti_
____

____
This is suffering: knowing and seeing this [according to reality] the _āsavas_ 
are destroyed.

_idaṃ dukkhan ti bhikkhave jānato passato āsavānaṃ khayo hoti_
____

____
'This is the origin of suffering': knowing and seeing this [according to 
reality] the _āsavas_ are destroyed.

_ayaṃ dukkhasamudayo ti jānato passato āsavānaṃ khayo hoti_
____

____
'This is the ending of suffering': knowing and seeing this [according to 
reality] the _āsavas_ are destroyed.

_ayaṃ dukkhanirodhoti jānato passato āsavānaṃ khayo hoti_
____

[quote, S.5.434]
____
'This is the practice leading to the ending of suffering': knowing and seeing 
this [according to reality] the _āsavas_ are destroyed.

_ayaṃ dukkhanirodhagāminī paṭipadā ti jānato passato āsavānaṃ khayo 
hoti._
____

But knowing and seeing the four noble truths involves the ending of the second 
noble truth, which must therefore be the _āsavas_ that are destroyed. 
Therefore the elements of the second noble truth are _āsavas._

The full formula of the second noble truth is:

____
It is this craving that leads to renewed states of individual existence, 
accompanied by spiritually fettering delight and attachment, taking delight in 
this and that, namely craving for sensuous pleasure, craving for states of 
individual existence, and craving for the cessation of states of individual 
existence.

_yāyaṃ taṇhā ponobhavikā nandirāgasahagatā tatra tatrābhinandinī 
seyyathīdaṃ kāmataṇhā bhavataṇhā vibhavataṇhā_
____

This formula centres on three elements: _taṇhā, nandi,_ and _rāga._ 
Therefore, as we have already noted, these three are _āsavas_, perceptually 
obscuring states.

==== Freeing oneself of āsavas: Dutiyahāliddikāni Sutta

Many suttas explain how to free oneself of the _āsavas_ using the word 
_vimutti_, which means 'liberation from the _āsavas_.' For example, the 
_Dutiyahāliddikāni Sutta_ (S.3.13) says _vimutti_ comes from the destruction 
or relinquishment of nine _āsavas_:

[quote, S.3.13]
____
Through the destruction, fading away, ending, giving up, and relinquishment of 
fondness, attachment, spiritually fettering delight, craving, clinging, 
grasping, obstinate adherence, stubborn attachment, and identification one's 
mind is said to be liberated [from perceptually obscuring states]

_yo chando yo rāgo yā nandi yā taṇhā ye upayupādānā cetaso 
adhiṭṭhānābhinivesānusayā tesaṃ khayā virāgā nirodhā cāgā 
paṭinissaggā... cittaṃ suvimuttan ti vuccati._
____

==== Freeing oneself of āsavas: Santatara Sutta

The _Santatara Sutta_ (It.62) says one is liberated from the _āsavas_ by 
attaining the ending of perception and sense impression 
(_saññāvedayitanirodhadhātu_) which in this quote is called simply 
_nirodha_:

[quote, It.62]
____
Those who profoundly understand the refined material states of awareness and 
are not stuck in the immaterial states of awareness, with the ending [of 
originated phenomena], they are liberated [from perceptually obscuring states].

_ye ca rūpe pariññāya arūpesu asaṇṭhitā +
nirodhe ye vimuccanti._
____

==== Freeing oneself of āsavas: Pārileyyaka Sutta

The _Pārileyyaka Sutta_ says the _āsavas_ are immediately destroyed when one 
sees that the components of one's identity are unlasting, originated, and 
dependently arisen:

____
The ignorant Everyman considers bodily form to be the [absolute] Selfhood

_rūpaṃ attato samanupassati_
____

____
... That considering is an originated phenomenon

_yā kho pana sā bhikkhave samanupassanā saṅkhāro so_
____

____
... What is the basis, origin, object of genesis and production of that 
originated phenomenon?

_So pana saṅkhāro kinnidāno kiṃsamudayo kiñjātiko kimpabhavoti_
____

____
... When the ignorant Everyman is affected by sense impression born of 
sensation and uninsightfulness into reality, craving arises.

_avijjāsamphassajena bhikkhave vedayitena phuṭṭhassa assutavato 
puthujjanassa uppannā taṇhā_
____

____
... That originated phenomenon is born from that

_tatojo so saṅkhāro_
____

____
... That originated phenomenon, that craving, that sense impression, that 
sensation, that uninsightfulness into reality is unlasting, originated, 
dependently arisen.

_sopi kho saṅkhāro... taṇhā... vedanā... phasso... avijjā aniccā 
saṅkhatā paṭiccasamuppannā_
____

[quote, S.3.96]
____
... When one knows and sees this, there is the immediate destruction of 
perceptually obscuring states

_anantarā āsavānaṃ khayo hoti._
____

==== Freeing oneself of āsavas: Sabbāsava Sutta

Given the wide-ranging nature of perceptually obscuring states it is no wonder 
that they must be overcome by a range of different methods. This is the subject 
of the _Sabbāsava Sutta_, which says perceptually obscuring states are 
abandoned in seven ways:

1. Contemplating issues that should be contemplated and not contemplating 
issues that should not be contemplated
+
****
_(Sutavā ariyasāvako) ye dhammā na manasikaraṇīyā te dhamme na 
manasikaroti ye dhammā manasikaraṇīyā te dhamme manasikaroti._
****

2. Abiding with the faculty of sight... faculty of mental cognisance restrained 
through restraint [of attraction and repulsion, through mindfulness].
+
****
_bhikkhu paṭisaṅkhā yoniso cakkhundriyasaṃvarasaṃvuto... 
manindriyasaṃvarasaṃvuto viharati_
****

3. Using the robe, almsfood, abode, therapeutic requisites, properly reflecting.
+
****
_bhikkhu paṭisaṅkhā yoniso cīvaraṃ... 
gilānapaccayabhesajjaparikkhāraṃ paṭisevati_
****

4. Enduring cold, heat... Enduring bodily sense impressions that are 
unpleasant, acute, sharp, piercing, displeasing, objectionable, and 
life-threatening.
+
****
_bhikkhu paṭisaṅkhā yoniso khamo hoti... uppannānaṃ sārīrikānaṃ 
vedanānaṃ dukkhānaṃ tibbānaṃ kharānaṃ kaṭukānaṃ asātānaṃ 
amanāpānaṃ pāṇaharānaṃ adhivāsakajātiko hoti._
****

5. Avoiding wild elephants and horses... and unsuitable seats, unsuitable alms 
resorts, and unvirtuous friends that would make one's knowledgeable companions 
in the religious life suspect one of unvirtuous ways of conduct
+
****
_bhikkhu paṭisaṅkhā yoniso caṇḍaṃ hatthiṃ parivajjeti... 
Yathārūpe anāsane nisinnaṃ yathārūpe agocare carantaṃ yathārūpe 
pāpake mitte bhajantaṃ viññū sabrahmacārī pāpakesu ṭhānesu 
okappeyyuṃ._
****

6. Not tolerating arisen sensuous, unbenevolent or malicious thoughts.
+
****
_bhikkhu paṭisaṅkhā yoniso uppannaṃ kāmavitakkaṃ... 
vyāpādavitakkaṃ... vihiṃsāvitakkaṃ nādhivāseti_
****

7. Developing the enlightenment factor of mindfulness... the enlightenment 
factor of detached awareness.
+
****
_bhikkhu paṭisaṅkhā yoniso satisambojjhaṅgaṃ... upekkhā 
sambojjhaṅgaṃ bhāveti_ (M.1.7).
****

==== Destruction of āsavas starts at stream-entry

Although _āsavakkhaya_ is prominently associated with arahantship, _āsavas_ 
are in fact destroyed from stream-entry onwards. The three types of individuals 
who are at least stream-enterers but not arahants are called _kāyasakkhī, 
diṭṭhappatto,_ and _saddhāvimutto._ The _Kīṭāgiri Sutta_ (M.1.438) 
says that for each of these individuals some of his perceptually obscuring 
states are destroyed (_ekacce āsavā parikkhīṇā honti_). But before 
stream-entry, no perceptually obscuring states are destroyed (_āsavā 
aparikkhīṇā honti_, M.1.479). We will show below that these _āsavas_ are 
otherwise known as _saṃyojanāni_ i.e. ties to individual existence.

==== Destruction of āsavas: gradual process

Although many suttas say the _āsavas_ are destroyed just before arahantship, 
the _Uposatha Sutta_ (S.3.155) says destroying the _āsavas_ is a more gradual 
process. The sutta compares the wearing away of _āsavas_ to the wearing away 
of an adze handle. It says when a carpenter looks at the handle of his adze, he 
sees the impressions of his fingers and his thumb, but he does not know how 
much of the handle wore away that day, or how much on previous days. He only 
knows that when the handle is worn away, that it has worn away.

Likewise, when a bhikkhu abides devoted to spiritual development, no such 
knowledge occurs to him that so much of his _āsavas_ were destroyed that day, 
or so much on previous days, yet when they are destroyed, the knowledge occurs 
to him that they have been destroyed (_ettakaṃ vata me ajja āsavānaṃ 
khīṇaṃ ettakaṃ hiyyo ettakaṃ pare ti. Atha khvassa khīṇe 
khīṇaṃtveva ñāṇaṃ hoti_). According to this, destroying the 
_āsavas_ is a gradual, barely perceptible process.

==== Pañca nīvaraṇā: not āsavas

The _Upakkilesa Sutta_ says that to overcome the _āsavas_ one must first 
suppress the _pañca nīvaraṇā_:

[quote, A.3.16-17]
____
When one's mind is free of these five defilements, it is pliable and workable 
and radiant, not brittle, but is properly collected for the destruction of 
perceptually obscuring states.

_Yato ca kho bhikkhave cittaṃ imehi pañcahi upakkilesehi vippamuttaṃ hoti 
taṃ hoti cittaṃ mudu ca kammaniyañca pabhassarañca na ca pabhaṅgu 
sammāsamādhīyati āsavānaṃ khayāya._
____

This implies that the _pañca nīvaraṇā_ are different from _āsavas_.

==== Pañca nīvaraṇā: are practically āsavas

But the _nīvaraṇas_ and _āsavas_ have much in common, and although 
differentiating them is technically justifed, it is problematic to do so, 
because of their similarlty. For example:

1. Both are defiling and weakening of penetrative discernment:

[quote, M.1.250]
____
Him I call undiscerning of reality, Aggivessana, who has not abandoned 
perceptually obscuring states that are defiling... For it is through the 
non-abandonment of perceptually obscuring states that one is undiscerning of 
reality.

_Yassa kassaci aggivessana ye āsavā saṅkilesikā... appahīnā tamahaṃ 
sammūḷho ti vadāmi. Āsavānaṃ hi aggivessana appahānā sammūḷho 
hoti._
____

[quote, S.5.95]
____
Sensuous hankering (and each of the _nīvaraṇas_) is a spiritual obstruction, 
a spiritual hindrance, a spiritual defilement, a weakener of penetrative 
discernment.

_kāmacchando āvaraṇo nīvaraṇo cetaso upakkileso paññāya 
dubbalīkaraṇo._
____

2. Both _nīvaraṇas_ and _āsavas_ are productive of _avijjā_:

[quote, M.1.46-56]
____
With the origination of perceptual obscuration comes the origination of 
uninsightfulness into reality

__āsavasamudayā avijjāsamudayo._
____

[quote, A.5.116]
____
What is the condition that nourishes uninsightfulness into reality? The five 
hindrances, one should reply._

_ko cāhāro avijjāya? Pañca nīvaraṇā tissa vacanīyaṃ._
____

3. In our analysis above, certain factors found to be _āsavas_ are also 
_nīvaraṇas_. For example, the first of the _nīvaraṇas_ is _kāmacchanda_; 
and we have shown above that _chanda_ is an _āsava_. The fifth of the 
_nīvaraṇas_ is _vicikicchā_, which we have shown above is also an _āsava_.

4. The other three _nīvaraṇas_ are linked to _āsava_ via _vimutta_. We have 
shown in the Vimutta section that _vimutta_ means 'liberated from _āsavas_.' 
The third and fourth of the _nīvaraṇas_ are _thīnamiddhaṃ_ and _uddhacca 
kukkucca_. These are treated like _āsavas_ in this quote:

[quote, S.5.76-7]
____
My mind is [temporarily] liberated [from perceptually obscuring states]. I have 
abolished lethargy and torpor and thoroughly dispelled restlessness and 
anxiety. My energy is aroused. I pay attention as a matter of vital concern, 
not sluggishly.

_cittañca me suvimuttaṃ thīnamiddhañca me susamūhataṃ. Uddhacca 
kukkuccañca me suppaṭivinītaṃ. Āraddhañca me viriyaṃ aṭṭhikatvā 
manasikaromi no ca līnan ti._
____

The second _nīvaraṇa_ is ill will, and this is shown to be an _āsava_ via 
_cetovimutta_:

[quote, D.3.248]
____
If the liberation [from perceptually obscuring states] through [unlimited, 
all-encompassing] goodwill is developed and cultivated, it is impossible, out 
of the question, that ill will would plague your mind.

_Aṭṭhānametaṃ āvuso anavakāso yaṃ mettāya cetovimuttiyā 
bhāvitāya bahulīkatāya... atha ca panassa vyāpādo cittaṃ pariyādāya 
ṭhassatī ti._
____

==== Temporary and unshakeable liberation from _āsava_

That _āsavas_ once destroyed do not return is proven by the stream-enterer's 
situation. Some of his _āsavas_ are destroyed (_ekacce āsavā parikkhīṇā 
honti_ M.1.438) and the rest will certainly follow because he does not take an 
eighth [human] existence even if very negligently applied [to the practice] 
(_kiñcāpi te honti bhusaṃ pamattā na te bhavaṃ aṭṭhamamādiyanti_). 
This, therefore, is a feature of some _āsavas_: once destroyed, they do not 
return, even in succeeding lives.

But other _āsavas_ are liable to return. This is implied in these two quotes, 
because _cetovimutti_ means liberation from the _āsavas_:

1. To whatever extent there are unlimited liberations from perceptually 
obscuring states, the unshakeable liberation [from perceptually obscuring 
states] is declared the chief among them.
+
****
_yāvatā kho bhante appamāṇā cetovimuttiyo akuppā tāsaṃ cetovimutti 
aggamakkhāyati_ (S.4.297).
****

If some liberations from perceptually obscuring states are 'unshakeable,' then 
others are shakeable i.e. some _āsavas_ are liable to return.

2. Then Venerable Godhika, abiding diligently, vigorously, and resolutely 
applied [to the practice] attained temporary liberation [from perceptually 
obscuring states]. But then Venerable Godhika fell away from that temporary 
liberation [from perceptually obscuring states].
+
****
_Atha kho āyasmā godhiko appamatto ātāpī pahitatto viharanto sāmayikaṃ 
cetovimuttiṃ phusi. Atha kho āyasmā godhiko tāya sāmayikāya 
cetovimuttiyā parihāyi_ (S.1.120).
****

So, some _āsavas_ are liable to return. These quotes therefore show that 
liberation from the _āsavas_ is not necessarily unshakeable. The same point is 
seen in the _Sabbāsava Sutta_, which describes various modes of behaviour in 
which _āsavas_ might arise, and if these modes of behaviour are avoided, then 
those _āsavas_ do not exist. For example:

____
In this regard a bhikkhu, properly reflecting, does not tolerate an arisen 
sensuous thought. He abandons it, dispels it, puts an end to it, eradicates it.

_Idha bhikkhave bhikkhu paṭisaṅkhā yoniso uppannaṃ kāmavitakkaṃ 
nādhivāseti pajahati vinodeti vyantīkaroti. Anabhāvaṃ gameti._
____

[quote, M.1.11]
____
... The vexatious and anguishing _āsavas_ that would arise if he were not to 
dispel these things do not arise for him when he dispels them.

_Yaṃ hissa bhikkhave avinodayato uppajjeyyuṃ āsavā vighātapariḷāhā. 
Vinodayato evaṃsa te āsavā vighātapariḷāhā na honti._
____

According to this, _āsavas_ may or may not arise according to the standard of 
one's practice. So even if they disappear, they may later reappear.

This contradiction of reappearing versus non-reappearing _āsavas_ stems from 
the two categories of āsavas mentioned above, firstly, the broad, undefined 
category which practically includes the _pañca nīvaraṇā_, and secondly, 
the narrow, well-defined category which does not. _Āsavas_ that are liable to 
reappear belong to the former category, whereas it seems that _āsavas_ which 
are removed permanently are otherwise called _saṃyojanāni,_ i.e. the ties to 
individual existence. We have already seen that the first three such ties are 
specifically called _āsavas_. These and the other seven ties to individual 
existence fall into two groups, as follows:

1. There are these five ties to individual existence in the low plane of 
existence
+
****
_Pañcimāni bhikkhave orambhāgiyāni saṃyojanāni. Katamāni pañca:_
****

____
view of personal identity

_sakkāyadiṭṭhi_
____

____
doubt [about the significance of the teaching]

_vicikicchā_
____

____
adherence to observances and practices

_sīlabbataparāmāso_
____

____
sensuous hankering _

_kāmacchando_
____

[quote, S.5.61-62]
____
ill will _

_vyāpādo._
____

2. There are these five ties to individual existence in the middle and high 
planes of existence. What five?
+
****
_pañcimāni bhikkhave uddhambhāgiyāni saṃyojanāni. katamāni pañca?_
****

____
attachment to the refined material states of awareness _

_rūparāgo_
____

____
attachment to immaterial states of awareness _

_arūparāgo_
____

____
self-centredness _

_māno_
____

____
vanity

_uddhaccaṃ_
____

[quote, S.5.61-62]
____
uninsightfulness into reality

_avijjā._
____

==== Āsavas and rebirth

That __āsava__s play an important role in rebirth is evident in these quotes:

1. Perceptually obscuring states that are defiling, and which lead to renewed 
states of individual existence, suffering, unpleasant karmic consequences, and 
future birth, old age, and death;
+
****
_ye āsavā saṅkilesikā ponobhavikā sadarā dukkhavipākā āyatiṃ 
jātijarāmaraṇīyā_ (M.1.250).
****

2. 'Those perceptually obscuring states through which I might have become a 
deva... a heavenly musician... a deity... a human being have been abandoned by 
me, chopped down at the root, completely and irreversibly destroyed.'
+
****
_Yesaṃ kho ahaṃ brāhmaṇa āsavānaṃ appahīṇattā devo... 
gandhabbo... yakkho... manusso bhaveyyaṃ te me āsavā pahīṇā 
ucchinnamūlā tālāvatthukatā anabhāvakatā āyatiṃ anuppādadhammā_ 
(A.2.38).
****

3. What is the variety in perceptually obscuring states?
+
****
_Katamā ca bhikkhave āsavānaṃ vemattatā_
****

[quote, A.3.414]
____
... There are perceptually obscuring states leading to hell, to the animal 
realm, to the realm of ghosts, to the human realm, and to the heavenly realms.

_atthi bhikkhave āsavā nirayagāminiyā... tiracchānayonigāminiyā... 
pettivisayagāminiyā... manussalokagāminiyā... devalokagāminiyā... ayaṃ 
vuccati bhikkhave āsavānaṃ vemattatā._
____

==== Āsavas and unpleasant karmic consequences

_Āsavas_ lead to renewed states of individual existence, suffering, unpleasant 
karmic consequences (_āsavā saṅkilesikā ponobhavikā sadarā 
dukkhavipākā_ M.1.250). This can be illustrated with the following quotes 
concerning _taṇhā_, which we have said above is an _āsava_.

[quote, M.1.507-8]
____
The more such beings pursue sensuous pleasure the more their craving for 
sensuous pleasure increases and the more they are tormented by sensuous passion

_Yathā yathā kho māgandiya sattā kāmesu avītarāgā kāmataṇhāhi 
khajjamānā kāmapariḷāhena pariḍayhamānā kāme paṭisevanti tathā 
tathā tesaṃ sattānaṃ kāmataṇhā ceva pavaḍḍhati kāmapariḷāhena 
ca pariḍayhanti.._
____

• For one who abides attached, tethered [to individual existence], 
undiscerning of reality, contemplating sweetness, the five grasped aggregates 
are heaped up in the future. Craving that leads to renewed states of individual 
existence, accompanied by spiritually fettering delight and attachment, taking 
delight in this and that, grows. +
_Tassa sārattassa saṃyuttassa sammūḷhassa assādānupassino viharato 
āyatiṃ pañcupādānakkhandhā upacayaṃ gacchanti. Taṇhā cassa 
ponobhavikā nandirāgasahagatā tatra tatrābhinandinī sā cassa 
pavaḍḍhati._

• ... One's physical and psychological sufferings, torments, and anguishes 
increase. +
_Tassa kāyikāpi darathā pavaḍḍhanti cetasikāpi darathā pavaḍḍhanti 
kayikāpi santāpā pavaḍḍhanti cetasikāpi santāpā pavaḍḍhanti 
kāyikāpi pariḷāhā pavaḍḍhanti cetasikāpi pariḷāhā 
pavaḍḍhanti_

• ... One experiences physical and psychological unpleasantness +
_so kāyadukkhampi cetodukkhampi paṭisaṃvedeti_ (M.3.287).

=== Illustrations

.Illustration
====
āsavā

perceptually obscuring states
====

____
In seeing a visible object with mindfulness muddled, focusing on the agreeable 
aspect, one experiences it with a mind of attachment and persists in cleaving 
to it.

_Rūpaṃ disvā sati muṭṭhā piyaṃ nimittaṃ manasikaroto +
Sārattacitto vedeti tañca ajjhosa tiṭṭhati_
____

[quote, Th.v.98; S.4.76]
____
One's perceptually obscuring states develop, the origin of individual 
existence, leading to renewed states of individual existence.

_Tassa vaḍḍhanti āsavā bhavamūlā bhavagāmino ti._
____

.Illustration
====
āsavānaṃ

perceptually obscuring states
====

____
This, bhikkhu, is a designation for the Untroubled: the elimination of 
attachment, hatred, and undiscernment of reality.

_Nibbānadhātuyā kho etaṃ bhikkhu adhivacanaṃ rāgavinayo dosavinayo 
mohavinayoti._
____

[quote, S.5.8]
____
The destruction of perceptually obscuring states is spoken of in that way.

_Āsavānaṃ khayo tena vuccatī ti._
____

.Illustration
====
sāsavo

perceptually obscuring states
====

[quote, D.3.272]
____
One thing to be profoundly understood: sensation associated with perceptually 
obscuring states is productive of grasping.

_Katamo eko dhammo pariññeyyo? Phasso sāsavo upādāniyo._
____

.Illustration
====
sāsavaṃ

associated with perceptually obscuring states
====

____
Whatever bodily form there is, past, future, or present, internal or external, 
gross or subtle, inferior or sublime, far or near,

_yaṃ kiñci bhikkhave rūpaṃ atītānāgatapaccuppannaṃ ajjhattaṃ vā 
bahiddhā vā oḷārikaṃ vā sukhumaṃ vā hīnaṃ vā paṇītaṃ vā 
yaṃ dūre santike vā_
____

____
associated with perceptually obscuring states

_sāsavaṃ_
____

____
and productive of grasping

_upādāniyaṃ_
____

[quote, S.3.47]
____
this is called the aggregate of grasped bodily form

_ayaṃ vuccati rūpūpādānakkhandho._
____

.Illustration
====
āsavesu

perceptually obscuring states
====

____
And what is diligence [in the practice]?

_Katamo ca bhikkhave appamādo_
____

[quote, S.5.232]
____
In this regard a bhikkhu protects the mind against perceptually obscuring 
states and against states associated with perceptually obscuring states.

_Idha bhikkhave bhikkhu cittaṃ rakkhati āsavesu ca sāsavesu ca dhammesu._
____

.Illustration
====
āsavā

perceptually obscuring states
====

____
And what are the perceptually obscuring states to be abandoned by enduring?

_Katame ca bhikkhave āsavā adhivāsanā pahātabbā?_
____

____
In this regard a bhikkhu, properly reflecting, endures cold, heat, hunger, and 
thirst; the touch of horseflies, mosquitoes, wind, sun, and snakes. He endures 
ill-spoken, unwelcome words and arisen bodily sense impressions that are 
unpleasant, acute, sharp, piercing, displeasing, objectionable, and 
life-threatening.

_Idha bhikkhave bhikkhu paṭisaṅkhā yoniso khamo hoti sītassa uṇhassa 
jighacchāya pipāsāya ḍaṃsamakasavātātapasiriṃsapasamphassānaṃ 
duruttānaṃ durāgatānaṃ vacanapathānaṃ uppannānaṃ sārīrikānaṃ 
vedanānaṃ dukkhānaṃ tibbānaṃ kharānaṃ kaṭukānaṃ asātānaṃ 
amanāpānaṃ pāṇaharānaṃ adhivāsakajātiko hoti._
____

____
The vexatious and anguishing perceptually obscuring states that would arise if 
he were not to endure these things do not arise for him when he endures them.

_Yaṃ hissa bhikkhave anadhivāsayato uppajjeyyuṃ āsavā 
vighātapariḷāhā adhivāsayato evaṃsa te āsavā vighātapariḷāhā na 
honti._
____

[quote, M.1.10]
____
These are called the perceptually obscuring states to be abandoned by enduring.

_Ime vuccanti bhikkhave āsavā adhivāsanā pahātabbā._
____

.Illustration
====
āsavānaṃ

perceptually obscuring states
====

____
Five things developed and cultivated lead to the destruction of perceptually 
obscuring states:

__āsavānaṃ khayāya saṃvattanti_
____

In this regard a bhikkhu is one who

____
abides contemplating the unloveliness of the body

_asubhānupassī kāye viharati._
____

____
perceives the loathsome nature of digestion.

__āhāre paṭikkūlasaññī._
____

____
perceives disgust for the whole world [of phenomena].

_sabbaloke anabhiratasaññī._
____

____
contemplates the unlastingness of all originated phenomena.

_sabbasaṅkhāresu aniccānupassī._
____

[quote, A.3.83]
____
and for whom the perception of [the ever-present possibility of] death is 
well-established within himself.

_maraṇasaññā kho panassa ajjhattaṃ sūpaṭṭhitā hoti._
____

