== Āsā

=== Renderings

- _āsā_: expectation

- _āsā_: hope

=== Introduction

==== Parenthesis

Where an object of expectation is needed, we parenthesise '[for anything]' or 
'[for anything in the world],' following the first quote:

1. Having loosened the spiritual shackle of grasping by which they are bound 
&#8203;[to the realm of death], they nurse no expectations for anything in the world.
+
****
_Ādānaganthaṃ gathitaṃ visajja āsaṃ na kubbanti kuhiñci loke_ 
(Sn.v.794).
****

2. 'He who is not relying on [the fulfilment of any] expectation [for anything 
in the world];
+
****
_Āsaṃ anissāya_ (Sn.v.474).
****

3. He in whom there are no expectations [for anything] in either this world or 
the world beyond.
+
****
_Āsā yassa na vijjanti asmiṃ loke paramhi ca_ (Sn.v.634).
****

=== Illustrations

.Illustration
====
āsāya

expectantly; āsā, expectation
====

[quote, Th.v.530]
____
The field is ploughed expectantly. The seed is sown expectantly. Merchants go 
to sea expectantly, bringing back wealth. Let that expectation in which I rest 
&#8203;[my hopes] be realised.

_Āsāya kasate khettaṃ bījaṃ āsāya vappati +
Asāya vāṇijā yanti samuddaṃ dhanahārakā +
Yāya āsāya tiṭṭhāmi sā me āsā samijjhatu._
____

.Illustration
====
āsā

expectation
====

[quote, Vin.3.196]
____
The expectation [of receiving] robe material is disappointed.

_cīvarāsā vā upacchinnā._
____

.Illustration
====
āsā

expectation
====

[quote, M.3.138]
____
There are certain ascetics and Brahmanists who teach thus, who hold this view: 
If one lives the religious life while nursing an expectation, one will not 
procure any benefit.

_Eke samaṇabrāhmaṇā evaṃvādino evaṃdiṭṭhino āsañcepi karitvā 
brahmacariyaṃ caranti abhabbā phalassa adhigamāya._
____

.Illustration
====
āsā

expectation
====

[quote, M.3.143]
____
If one squeezes the udder of a recently-calved cow while nursing an expectation 
one could [nonetheless] procure milk.

_Āsañcepi karitvā gāviṃ taruṇavacchaṃ thanato āviñcheyya bhabbo 
khīrassa adhigamāya._
____

.Illustration
====
āso

expectation
====

____
There are these three types of persons found in the world. Which three. One 
without expectation. One who is full of expectation. One who is rid of 
expectation.

_Tayome bhikkhave puggalā santo saṃvijjamānā lokasmiṃ. Katame tayo: 
nirāso āsaṃso vigatāso._
____

____
What is the person without expectation. Here, a person has been reborn in a low 
family... He hears that the _khattiyas_ have anointed such-and-such a 
_khattiya_. It does not occur to him [to think:] 'When will the _khattiyas_ 
anoint me?'

_Katamo ca bhikkhave puggalo nirāso: idha bhikkhave ekacco puggalo nīce kule 
paccājāto hoti... So suṇāti itthannāmo kira khattiyo khattiyehi 
khattiyābhisekena abhisittāti tassa na evaṃ hoti: kudassu nāma mamampi 
khattiyā khattiyābhisekena abhisiñcissantīti._
____

[quote, A.1.107-8]
____
What is the person who is full of expectation? Here, someone is the eldest son 
of a head-anointed _khattiya_ king... He hears that the _khattiyas_ have 
anointed such-and-such a _khattiya_. It occurs to him [to think:] 'When will 
the _khattiyas_ anoint me?'

_Katamo ca bhikkhave puggalo āsasaṃso. Idha bhikkhave rañño khattiyassa 
muddhāvasittassa jeṭṭho putto hoti ābhiseko anabhisitto macalappatto. So 
suṇāti itthannāmo kira khattiyo khattiyehi khattiyābhisekena abhisittoti. 
Tassa evaṃ hoti. Kudassu nāma mamampi khattiyā khattiyābhisekena 
abhisiñcissantīti._
____

.Illustration
====
āsā

expectation
====

[quote, Sn.v.864]
____
On account of what are things agreeable in the world, and wanted in the world? 
And what is the source of the expectation and hope that a man has for the 
hereafter?

_Piyā su lokasmiṃ kutonidānā ye cā pi lobhā vicaranti loke +
Āsā ca niṭṭhā ca kutonidānā ye samparāyāya narassa honti._
____

[quote, Sn.v.865]
____
Things are agreeable and wanted in the world on account of desire. Desire is 
also the source of the expectation and hope that a man has for the hereafter.

_Chandānidānāni piyāni loke ye cā pi lobhā vicaranti loke +
Āsā ca niṭṭhā ca itonidānā ye samparāyāya narassa honti._
____

Comment:

_Niṭṭhā_: 'hope.' PED calls _niṭṭhā_ 'aim.' This would give 'what is 
the source of the aim that a man has for the hereafter.' Norman calls it 
'fulfilment [of hope]' which likewise does not fit.

.Illustration
====
āsā

hope
====

[quote, D.2.206]
____
The hope is established in me to become a once-returner.

_Āsā ca pana me santiṭṭhati sakadāgāmitāyā ti._
____

.Illustration
====
āsā

hope
====

[quote, A.1.86]
____
Two hopes are difficult to abandon. Which two? The hope to get something, and 
the hope to survive.

_Dvemā bhikkhave āsā duppajahā. Katamā dve: lābhāsā ca jīvitāsā ca. 
Imā kho bhikkhave dve āsā duppajahāti._
____

