== Ātāpin; Ātappa

=== Renderings

- _ātāpin_: vigorously applied [to the practice]

- _ātāpin_: vigorously

- _ātāpin_: vigorous

- _ātappa_: vigorous endeavour

- _ātappaṃ karoti_: to vigorously apply oneself [to the practice]

- _ātappaṃ karoti_: to vigorously endeavour

=== Introduction

==== Ātāpin: vigorously

_Ātāpin_ has been called 'ardent' since 1875 when Childer's dictionary was 
published, which means 'enthusiastic.' But the scriptures more strongly suggest 
'vigorous' or 'vigorously,' and DOP appropriately calls it 'energetic.' But, 
two points:

1. It usually an adverb, so it mostly means 'vigorously' not 'vigorous.'

2. Its link to various qualifiers show that it is an abbreviation, and must be 
parenthesised in translation.

==== Ātāpin: three qualifiers

We parenthesise _ātāpin_ in accordance with suttas where it is linked to some 
qualifier. In the following examples it is linked to 'inward striving' 
'contemplating' and 'practising the teaching'. It is from the last ('practising 
as I instructed him') that we render it as 'vigorously applied [to the 
practice]':

[quote, S.2.267-8]
____
We will abide using blocks of wood as cushions, and be diligently and 
vigorously applied to inward striving.

_Kaliṅgarūpadhānā viharissāma appamattā ātāpino padhānasmin ti._
____

[quote, S.5.182]
____
A bhikkhu abides contemplating the nature of the body, vigorously, fully 
consciously, and mindfully, having eliminated greed and dejection in regard to 
the world [of phenomena]

_bhikkhu kāye kāyānupassī viharati ātāpī sampajāno satimā vineyya loke 
abhijjhādomanassaṃ._
____

[quote, A.5.86]
____
My disciple who abides diligently, vigorously, and resolutely applied [to the 
practice] for one night and day, practising as I instructed him, might 
experience exclusively happiness for a hundred years.

_Idha mama sāvako... ekaṃ rattindivaṃ appamatto ātāpī pahitatto 
viharanto yathā mayānusiṭṭhaṃ tathā paṭipajjamāno satampi vassāni 
ekanta sukhapaṭisaṃvedī vihareyya._
____

=== Illustrations

.Illustration
====
anātāpī

not vigorously applied [to the practice]; ātappaṃ karoti, vigorously apply 
himself [to the practice]
====

-- In this regard, friend, a bhikkhu thinks:

• 'If unarisen unvirtuous, spiritually unwholesome factors arise in me, this 
would lead to my harm,' but he does not vigorously apply himself [to the 
practise]. +
_Idhāvuso bhikkhu anuppannā me pāpakā akusalā dhammā uppajjamānā 
anatthāya saṃvatteyyunti na ātappaṃ karoti_

[quote, S.2.195-6]
____
... In this way he is someone not vigorously applied [to the practice].

_Evaṃ kho āvuso anātāpī hoti._
____

.Illustration
====
ātāpī

vigorously applied [to the practice]
====

[quote, A.2.17]
____
These four modes of inward striving were explained by the enlightened kinsman 
of the Sun clan, by means of which a bhikkhu who is vigorously applied [to the 
practice] can attain the destruction of suffering.

_Ete padhānā cattāro desitādiccabandhunā +
Yehi bhikkhu idhātāpī khayaṃ dukkhassa pāpuṇe ti._
____

.Illustration
====
ātāpī

vigorously applied [to the practice]
====

[quote, S.4.145]
____
Bhante, it would be good if the Blessed One would explain the teaching to me in 
brief, so that, having heard the teaching from the Blessed One, I might abide 
alone, withdrawn [from human fellowship, sensuous pleasures, and spiritually 
unwholesome factors], diligently, vigorously, and resolutely applied [to the 
practice].

_sādhu me bhante bhagavā saṅkhittena dhammaṃ desetu yamahaṃ bhagavato 
dhammaṃ sutvā eko vūpakaṭṭho appamatto ātāpī pahitatto vihareyyanti._
____

.Illustration
====
ātāpī

vigorously applied [to the practice]
====

• If, while he is walking, any greed in a bhikkhu is done away with, any ill 
will, any lethargy and torpor, any restlessness and anxiety, any doubt [about 
the significance of the teaching] is done away with; +
_Carato ce pi bhikkhave bhikkhuno abhijjhā vigatā hoti vyāpādo vigato hoti 
thīnamiddhaṃ vigataṃ hoti uddhaccakukkuccaṃ vigataṃ hoti vicikicchā 
pahīṇā hoti._

• If unflagging energy is aroused; if unmuddled mindfulness is established; 
if his body is tranquil and peaceful; if his mind is collected and concentrated 
+
_Āraddhaṃ hoti viriyaṃ asallīnaṃ upaṭṭhitā sati asammuṭṭhā 
passaddho kāyo asāraddho samāhitaṃ cittaṃ ekaggaṃ_

• then a bhikkhu walking like this is said to be constantly and continuously 
afraid of wrongdoing, and vigorously, energetically, and resolutely applied [to 
the practice]. +
_carampi bhikkhave bhikkhu evambhūto ātāpī ottappī satataṃ samitaṃ 
āraddhaviriyo pahitatto ti vuccati_ (It.118-9).

.Illustration
====
ātāpino

vigorously applied
====

____
Bhikkhus, at the present time the Licchavis dwell using blocks of wood as 
cushions; they are diligently and vigorously applied to the practice of archery.

_Kaliṅgarūpadhānā bhikkhave etarahi licchavī viharanti appamattā 
ātāpino upāsanasmiṃ._
____

[quote, S.2.267-8]
____
Bhikkhus, at the present time the bhikkhus dwell using blocks of wood as 
cushions; they are diligently and vigorously applied to inward striving.

_Kaliṅgarūpadhānā bhikkhave etarahi bhikkhū viharanti appamattā 
ātāpino padhānasmiṃ._
____

.Illustration
====
ātappaṃ karaṇīyaṃ

vigorously endeavour
====

____
Three occasions when one should vigorously endeavour.

_Tīhi bhikkhave ṭhānehi ātappaṃ karaṇīyaṃ. Katamehi tīhi:_
____

1. One should vigorously endeavour to prevent the arising of unarisen 
unvirtuous, spiritually unwholesome factors.
+
****
_anuppannānaṃ pāpakānaṃ akusalānaṃ dhammānaṃ anuppādāya 
ātappaṃ karaṇīyaṃ._
****

2. One should vigorously endeavour to arouse unarisen spiritually wholesome 
factors _ +
☸ Anuppannānaṃ kusalānaṃ dhammānaṃ uppādāya ātappaṃ 
karaṇīyaṃ._

3. One should vigorously endeavour to endure arisen bodily sense impressions 
that are unpleasant, acute, sharp, piercing, displeasing, objectionable, and 
life-threatening
+
****
_☸ Uppannānaṃ sārīrikānaṃ vedanānaṃ dukkhānaṃ tibbānaṃ 
kharānaṃ kaṭukānaṃ asātānaṃ amanāpānaṃ pāṇaharānaṃ 
adhivāsanāya ātappaṃ karaṇīyaṃ_ (A.1.153).
****

.Illustration
====
ātāpī

vigorously applied [to the practice]
====

[quote, A.2.13]
____
If a sensuous thought, unbenevolent thought, or malicious thought arises in a 
bhikkhu while he is walking, and he tolerates it, does not abandon it, dispel 
it, put an end to it, and eradicate it, then that bhikkhu is said to be not 
vigorously applied [to the practice], unafraid of wrongdoing, constantly and 
continuously lazy and slothful while walking.

_Carato cepi bhikkhave bhikkhuno uppajjati kāmavitakko vā vyāpādavitakko 
vā vihiṃsāvitakko vā. Tañca bhikkhu adhivāseti nappajahati na vinodeti 
na vyantīkaroti na anabhāvaṃ gameti. Carampi bhikkhave bhikkhu evambhūto 
anātāpī anottāpī satataṃ samitaṃ kusīto hīnaviriyo'ti vuccati._
____

.Illustration
====
ātāpino

vigorously applied [to the practice]
====

[quote, Dh.v.144]
____
Like a good horse touched by the whip, be vigorously applied [to the practice] 
and have an earnest attitude [to the practice].

_Asso yathā bhadro kasāniviṭṭho ātāpino saṃvegino bhavātha._
____

Comment

_Saṃvegino_: earnest attitude [to the practice]. See Glossary sv _Saṃvega_.

.Illustration
====
ātāpino

vigorously applied [to the practice]
====

• In what way, Anuruddhas, do you abide diligently, vigorously, and 
resolutely applied [to the practice]? +
_Yathākathampana tumhe anuruddhā appamattā ātāpino pahitattā 
viharathāti?_

• In this regard, bhante... whoever notices the pots of water for drinking, 
washing, or for the toilets is empty or drained, he replenishes them... And 
every fifth night we sit together all night and discuss the teaching. +
☸ _Idha pana bhante... yo passati pānīyaghaṭaṃ vā 
paribhojanīyaghaṭaṃ vā vaccaghaṭaṃ vā rittaṃ tucchaṃ so 
upaṭṭhapeti_... _Pañcāhikaṃ kho pana mayaṃ bhante sabbarattikaṃ 
dhammiyā kathāya sannisīdāma_ (M.1.207).

.Illustration
====
ātappaṃ

vigorous endeavour [to practise the teaching]
====

[quote, M.3.187]
____
The vigorous endeavour [to practise the teaching] must be made today._

_ajje va kiccaṃ ātappaṃ._
____

.Illustration
====
ātappaṃ

vigorous endeavour [to practise the teaching]
====

[quote, Dh.v.276]
____
The vigorous endeavour [to practise the teaching] must be made by you 
yourselves. Perfect Ones are just path-proclaimers.

_tumhehi kiccaṃ ātappaṃ akkhātāro tathāgatā._
____

.Illustration
====
ātāpiniyo

vigorously applied [to the practice]
====

____
Gotami, I hope the bhikkhunīs are abiding diligently, vigorously, and 
resolutely applied [to the practice].

_kacci gotami bhikkhuniyo appamattā ātāpiniyo pahitattā viharantī ti._
____

[quote, Vin.3.235]
____
Bhante, how could the bhikkhunīs be diligently applied [to the practice]? The 
masters, the Group-of-Six bhikkhus, are getting the bhikkhunīs to wash, dye, 
and comb sheep wool. Thus the bhikkhunīs are neglecting the recitation, the 
interrogation, the higher virtue, the higher mental states, and the higher 
penetrative discernment._

_Kuto bhante bhikkhunīnaṃ appamādo. Ayyā chabbaggiyā bhikkhunīhi 
eḷakalomāni dhovāpenti pi rajāpenti pi vijaṭāpenti pi. Bhikkhunīyo 
eḷakalomāni dhovantiyo rajantiyo vijaṭentiyo riñcanti uddesaṃ 
paripucchaṃ adhisīlaṃ adhicittaṃ adhipaññanti._
____

.Illustration
====
ātāpī

vigorously applied [to the practice]
====

[quote, S.1.13]
____
A bhikkhu who is mindful and vigorously applied [to the practice] can 
disentangle this tangle__.

_Ātāpī nipako bhikkhu so imaṃ vijaṭaye jaṭanti._
____

.Illustration
====
ātāpī

vigorously
====

[quote, S.5.182]
____
A bhikkhu abides contemplating the nature of the body, vigorously, fully 
consciously, and mindfully, having eliminated greed and dejection in regard to 
the world [of phenomena]

_bhikkhu kāye kāyānupassī viharati ātāpī sampajāno satimā vineyya loke 
abhijjhādomanassaṃ._
____

.Illustration
====
ātāpi

vigorously
====

[quote, A.3.38]
____
She does not despise her husband, the man who always and constantly and 
vigorously and eagerly supports her, bringing her everything she wants.

_Yo naṃ bharati sabbadā niccaṃ ātāpi ussuko +
Sabbakāmaharaṃ posaṃ bhattāraṃ nātimaññati._
____

.Illustration
====
ātappāya

vigorous endeavour
====

[quote, A.5.19]
____
His mind inclines to vigorous endeavour, application, perseverance, and inward 
striving.

_tassa cittaṃ namati ātappāya anuyogāya sātaccāya padhānāya._
____

.Illustration
====
ātappamakaruṃ

vigorously endeavoured
====

____
'Bhikkhus, watch the approaching host of devas.'

_Devakāyā abhikkantā te vijānātha bhikkhavo_
____

[quote, D.2.256]
____
Hearing the Buddha's call, the bhikkhus vigorously endeavoured to comply.

_Te ca ātappamakaruṃ sutvā buddhassa sāsanaṃ._
____

.Illustration
====
ātappamanvāya

vigorous endeavour
====

____
A certain ascetic or Brahmanist through vigorous endeavour, exertion, 
application, diligence, and right contemplation

_ekacco samaṇo vā brāhmaṇo vā ātappamanvāya padhānamanvāya 
anuyogamanvāya appamādamanvāya sammāmanasikāramanvāya_
____

• attains to such a state of inward collectedness that he thereby recalls his 
manifold past lives. +
_*☸* tathārūpaṃ cetosamādhiṃ phusati yathā samāhite citte 
anekavihitaṃ pubbenivāsaṃ anussarati_ (D.1.13).

.Illustration
====
ātappaṃ karohi

vigorously apply yourself [to the practice]
====

[quote, Sn.v.1062]
____
Therefore vigorously apply yourself [to the practice]. Be aware and mindful 
right here and now. Having heard my word, train yourself in the quenching of 
the ego.

_Tenahātappaṃ karohi idheva nipako sato +
Ito sutvāna nigghosaṃ sikkhe nibbānamattano._
____

.Illustration
====
ātāpino

vigorous
====

[quote, Ud.1]
____
When profound truths become manifest to the vigorous, meditative Brahman, then 
all his unsureness [about the significance of the teaching] disappears, for he 
discerns the conditioned nature of reality.

_Yadā have pātubhavanti dhammā ātāpino jhāyato brāhmaṇassa +
Athassa kaṅkhā vapayanti sabbā yato pajānāti sahetudhamman ti._
____

