== Āvila

=== Renderings

- _āvila_: full of impurity

- _āvila_: muddied

- _anāvila_: free of spiritual impurity

- _anāvila_: free of impurity

- _anāvila_: undefiled

- _anāvila_: unmuddied

- _anāvila_: unturbid

- _anāvila_: unblemished

=== Illustrations

.Illustration
====
āvila

full of impurity; anāvilaṃ, free of spiritual impurity
====

[quote, Thī.v.369]
____
Why do you, whose mind is full of impurity, full of defilements, stand 
obstructing me, who am free of spiritual impurity, spiritually unblemished, 
with a mind that is completely liberated [from perceptually obscuring states]?

_Āvilacitto anāvilaṃ sarajo vītarajaṃ anaṅgaṇaṃ +
Sabbattha vimuttamānasaṃ kiṃ maṃ ovariyāna tiṭṭhasi._
____

.Illustration
====
anāvila

free of impurity
====

[quote, Th.v.438]
____
Frequently reflecting on the purity of my mind which is free of defilements and 
impurity, I will abide free of perceptually obscuring states.

_Vippamuttaṃ kilesehi suddhacittaṃ anāvilaṃ +
Abhiṇhaṃ paccavekkhanto viharissaṃ anāsavo._
____

.Illustration
====
anāvilo

free of impurity
====

[quote, Sn.v.1039]
____
A bhikkhu should not be greedy for sensuous pleasures. His mind should be free 
of impurity.

_Kāmesu nābhigijjheyya manasānāvilo siyā._
____

.Illustration
====
anāvilaṃ

free of impurity
====

[quote, Sn.v.483]
____
One whose aggressiveness has vanished, whose mind is free of impurity

_Sārambhā yassa vigatā cittaṃ yassa anāvilaṃ._
____

.Illustration
====
anāvilaṃ

free of impurity
====

[quote, Sn.v.637]
____
&#8203;[One whose mind is] as stainless as the moon, purified, serene, and free of 
impurity.

_Candaṃ va vimalaṃ suddhaṃ vippasannamanāvilaṃ._
____

.Illustration
====
āvilattaṃ

state of impurity
====

[quote, Sn.v.967]
____
When he is conscious of a state of mental impurity he should dispel it with the 
thought: "It is part of inward darkness.

_Yadāvilattaṃ manaso vijaññā kaṇhassa pakkho ti vinodayeyya._
____

.Illustration
====
anāvila

undefiled
====

[quote, D.3.270]
____
How is a bhikkhu of undefiled thought? In this regard a bhikkhu has abandoned 
sensuous thought, unbenevolent thought, malicious thought.

_Kathañcāvuso bhikkhu anāvilasaṅkappo hoti. Idhāvuso bhikkhuno 
kāmasaṅkappo pahīno hoti vyāpādasaṅkappo pahīno hoti 
vihiṃsāsaṅkappo pahīno hoti._
____

.Illustration
====
anāvilo

unmuddied
====

[quote, S.1.169]
____
The practice is a lake with fords of virtue, unmuddied, praised by good people 
to good people, where those who are blessed with profound knowledge go to 
bathe, and, dry-limbed, cross to the Far Shore.

_Dhammo rahadobrāhmaṇa sīlatittho anāvilo sabbhi sataṃ pasattho +
Yattha have vedaguno sinātā anallagattā5va taranti pāraṃ._
____

.Illustration
====
anāvilāni

muddied
====

[quote, Ud.41]
____
He drank muddied water

_Āvilāni ca pānīyāni pivati._
____

==== Illustration: , unturbid

[quote, D.1.84]
____
Just as in a mountain valley there were a lake of water, crystal clear, limpid, 
unturbid, and a man standing on the bank with eyes to see should perceive the 
oysters and shells, the gravel and pebbles, and shoals of fish as they move 
about or lie within it.

_Seyyathā pi mahārāja pabbatasaṅkhepe udakarahado accho vippasanno 
anāvilo. Tattha cakkhumā puriso tīre ṭhito passeyya sippisambūkampi 
sakkharakaṭhalampi macchagumbampi carantampi tiṭṭhantamp._
____

==== Illustration: , unblemished

[quote, D.1.76]
____
A gem, a beryl, exquisite, of genuine quality, a well-cut octahedron, 
translucent, limpid, unblemished, excellent in every respect,

_maṇi veḷuriyo subho jātimā aṭṭhaṃso suparikammakato accho 
vippasanno anāvilo sabbākārasampanno._
____

