== Āyatana

=== Renderings

- _āyatana_: state of awareness

- _āyatana_: supreme state of deliverance

- _āyatana_: practice of spiritual development

- _āyatana_: occasion

- _āyatana_: group

- _āyatana_: aspect

- _āyatana_: dogma

- _āyatana_: place

- _āyatana_: (redundancy)

=== Introduction

==== Āyatana: supreme state of deliverance

'Supreme state of deliverance' is most clearly indicated in the _Cūḷavedalla 
Sutta_ (M.1.303) where it is linked to _vimokkha_, deliverance [from 
perceptually obscuring states]:

[quote, M.1.303]
____
When will I attain that supreme state of deliverance... In arousing desire for 
supreme deliverance [from perceptually obscuring states]

_kudassu nāmāhaṃ tadāyatanaṃ upasampajja viharissāmi... Iti anuttaresu 
vimokkhesu pihaṃ upaṭṭhāpayato._
____

==== Āyatana: practices of spiritual development

The rendering 'practices of spiritual development' is most clearly indicated in 
the _Mahāsakuludāyi Sutta_ (M.2.1-18) where _āyatana_ occurs in a list with 
the seven groups of factors conducive to enlightenment as follows:

____
Again, Udāyin, I have explained to my disciples the practice by which they 
develop

_Puna ca paraṃ udāyi akkhātā mayā sāvakānaṃ paṭipadā 
yathāpaṭipannā me sāvakā_
____

____
the [contemplation of the] four bases of mindfulness,_

_cattāro satipaṭṭhāne bhāventi._
____

____
the four modes of right inward striving,_

_cattāro sammappadhāne bhāventi._
____

____
the four paths to psychic power,_

_cattāro iddhipāde bhāventi._
____

____
the five spiritual faculties,_

_pañcindriyāni bhāventi._
____

____
the five spiritual powers,_

_pañca balāni bhāventi._
____

____
the seven factors of enlightenment,_

_satta bojjhaṅge bhāventi._
____

____
the noble eightfold path,_

_ariyaṃ aṭṭhaṅgikaṃ maggaṃ bhāventi._
____

____
the eight practices of spiritual development that lead to mastery ,_

_aṭṭha abhibhāyatanāni bhāventi._
____

____
the ten practices of spiritual development through kasiṇas,_

_dasakasiṇāyatanāni bhāventi._
____

[quote, M.2.11-15]
____
the four jhānas

_cattāri jhānāni bhāventi._
____

==== Cakkhāyatanaṃ and cakkhusamphassāyatana

_Cakkhāyatanaṃ_ and _cakkhusamphassāyatana_ are discussed in the Glossary 
sv _Saḷāyatana_.

=== Illustrations

.Illustration
====
āyatanaṃ

state of awareness
====

____
Secluded from sensuous pleasures and spiritually unwholesome factors, a bhikkhu 
enters and abides in first jhāna, which is accompanied by thinking and 
pondering, and rapture and physical pleasure born of seclusion [from sensuous 
pleasures and spiritually unwholesome factors].

_Idhāvuso bhikkhu vivicceva kāmehi vivicca akusalehi dhammehi savitakkaṃ 
savicāraṃ vivekajaṃ pītisukhaṃ paṭhamaṃ jhānaṃ upasampajja 
viharati._
____

[quote, A.4.452]
____
He abides contacting that state of awareness accordingly with his very being.

_Yathā yathā ca tadāyatanaṃ tathā tathā naṃ kāyena phassitvā 
viharati._
____

.Illustration
====
āyatanaṃ

state of awareness
====

[quote, S.4.296]
____
By completely transcending the state of awareness of boundless mental 
consciousness, a bhikkhu enters and abides in the state of awareness of 
nonexistence, where one perceives that there is [nowhere] anything at all.

_sabbaso viññāṇañcāyatanaṃ samatikkamma natthi kiñcī ti 
ākiñcaññāyatanaṃ upasampajja viharati._
____

.Illustration
====
āyatanaṃ

supreme state of deliverance
====

[quote, M.1.303]
____
A bhikkhu thinks 'When will I attain that supreme state of deliverance which 
the Noble Ones have attained? In arousing desire for supreme deliverance [from 
perceptually obscuring states], psychological pain arises due to desire.

_bhikkhu iti paṭisañcikkhati kudassu nāmāhaṃ tadāyatanaṃ upasampajja 
viharissāmi yadariyā etarahi āyatanaṃ upasampajja viharantī ti. Iti 
anuttaresu vimokkhesu pihaṃ upaṭṭhāpayato uppajjati pihappaccayā 
domanassaṃ._
____

Comment:

_Vimokkha_ means deliverance [from perceptually obscuring states] (i.e. the 
āsavas), which supports us calling _āyatana_ 'supreme state of deliverance.'

.Illustration
====
āyatanaṃ

supreme state of deliverance, state of awareness
====

[quote, Ud.80]
____
There is that supreme state of deliverance where there is neither solidness, 
liquidness, warmth, nor gaseousness; no state of awareness of boundless space, 
no state of awareness of boundless mental consciousness, no state of awareness 
of nonexistence, no state of awareness neither having nor lacking perception; 
neither this world, nor a world beyond, nor both; neither sun nor moon. There, 
I declare, there is no coming, no going, no staying, no passing away, no being 
reborn. It is neither fixed, nor moving, and has no foundation. This is truly 
the end of suffering.

_Atthi bhikkhave tadāyatanaṃ yattha neva paṭhavī na āpo na tejo na vāyo 
na ākāsānañcāyatanaṃ na viññāṇañcāyatanaṃ na 
ākiñcaññāyatanaṃ na nevasaññānāsaññāyatanaṃ nāyaṃ loko na 
paraloko na ubho candimasūriyā. Tatrāpāhaṃ bhikkhave neva āgatiṃ 
vadāmi na gatiṃ na ṭhitiṃ na cutiṃ na upapattiṃ; appatiṭṭhaṃ 
appavattaṃ anārammaṇamevetaṃ. Esevanto dukkhassā ti._
____

.Illustration
====
āyatane

supreme state of deliverance
====

The Buddha said:

____
-- Therefore that supreme state of deliverance should be known where the visual 
sense ceases and perception of visible objects passes away.

_se āyatane veditabbe yattha cakkhuñca nirujjhati rūpasaññā ca virajjati_
____

...

____
That supreme state of deliverance should be known where the mental sense ceases 
and perception of mentally known objects passes away.

_se āyatane veditabbe yattha mano ca nirujjhati dhammasaññā ca virajjati se 
āyatane veditabbeti_
____

Venerable Ānanda explained:

[quote, S.4.98]
____
-- This was stated by the Blessed One, friends, with reference to the ending of 
the six senses.

_saḷāyatananirodhaṃ no etaṃ āvuso bhagavatā sandhāya bhāsita._
____

Comment:

_Saḷāyatananirodhaṃ_ means _nibbāna_ at A.2.161-2 (_channaṃ āvuso 
phassāyatanānaṃ asesavirāganirodhā papañcanirodho_). Ānanda indicates 
it has the same meaning here. This justifies us calling _āyatane_ 'that 
supreme state of deliverance.'

Comment:

_Se āyatane_ is an Eastern form of Pāli, discussed by Bodhi: CDB p.1414 
n.102).

.Illustration
====
āyatane

practice of spiritual development
====

____
How about if I, by transcending the world [of sensuous pleasure] with resolve, 
were to abide with an awareness that was abundant and enlarged? Having done so, 
unvirtuous, spiritually unwholesome mental states such as greed, ill will, and 
aggressiveness would not exist. With their abandonment, my mind would become 
immeasurable, unlimited, and well developed.

_Yaṃnūnāhaṃ vipulena mahaggatena cetasā vihareyyaṃ abhibhuyya lokaṃ 
adhiṭṭhāya manasā. Vipulena hi me mahaggatena cetasā viharato abhibhuyya 
lokaṃ adhiṭṭhāya manasā ye pāpakā akusalā mānasā abhijjhāpi 
vyāpādāpi sārambhāpi te na bhavissanti. Tesaṃ pahānā aparittañca me 
cittaṃ bhavissati appamāṇaṃ subhāvitan ti._
____

[quote, M.2.262]
____
Applying himself and frequently abiding in this way, his mind becomes serene 
through that practice of spiritual development.

_Tassa evaṃ paṭipannassa tabbahulavihārino āyatane cittaṃ pasīdati._
____

.Illustration
====
āyatanāni

practice of spiritual development
====

____
There are eight practices of spiritual development that lead to mastery 
(_aṭṭha abhibhāyatanāni_), Ānanda. What eight?

_Aṭṭha kho imāni ānanda abhibhāyatanāni. Katamāni aṭṭha?_
____

____
Being in a refined material state of awareness, one sees a limited quantity of 
shapes, beautiful or ugly. By gaining mastery over them, one is aware that one 
knows and sees them [according to reality]. This is the first practice of 
spiritual development leading to mastery.

_Ajjhattaṃ rūpasaññī eko bahiddhā rūpāni passati parittāni 
suvaṇṇadubbaṇṇāni tāni abhibhuyya jānāmi passāmī ti 
evaṃsaññī hoti. Idaṃ paṭhamaṃ abhibhāyatanaṃ_
____

...

____
Being in an immaterial state of awareness, one sees shapes that are of a white 
luster like the morning star, or like fine Benares muslin. By gaining mastery 
over them, one is aware that one knows and sees them [according to reality]. 
This is the eighth practice of spiritual development leading to mastery.

_Ajjhattaṃ arūpasaññī eko bahiddhā rūpāni passati odātāni 
odātavaṇṇāni odātanidassanāni odātanibhāsāni... Tāni abhibhuyya 
jānāmi passāmī ti evaṃsaññī hoti. Idaṃ aṭṭhamaṃ 
abhibhāyatanaṃ._
____

[quote, D.2.110-111]
____
"These, Ānanda, are the eight practices of spiritual development that lead to 
mastery.

_Imāni kho aṭṭha ānanda abhibhāyatanāni._
____

.Illustration
====
āyatane

practice of spiritual development
====

____
When one's mind is free of these five defilements, it is pliable and workable 
and radiant, not brittle, but is properly collected for the destruction of 
perceptually obscuring states;

_Yato ca kho bhikkhave cittaṃ imehi pañcahi upakkilesehi vippamuttaṃ hoti 
taṃ hoti cittaṃ mudu ca kammaniyañca pabhassarañca na ca pabhaṅgu 
sammāsamādhīyati āsavānaṃ khayāya._
____

[quote, A.3.16-17]
____
and one can turn one's mind to the realisation through transcendent insight of 
whatever condition is realisable through transcendent insight, and become an 
eye-witness in every case, if there is the practice of spiritual development.

_Yassa yassa ca abhiññāsacchikaraṇīyassa dhammassa cittaṃ 
abhininnāmeti abhiññā sacchikiriyāya tatra tatreva sakkhibhabbataṃ 
pāpuṇāti sati sati āyatane._
____

Comment:

[quote, M.1.33-6]
____
The _Ākaṅkheyya Sutta_ says supernormal states come from inward calm, 
meditation, insightfulness, and devotion to solitary abodes.

_ajjhattaṃ cetosamathamanuyutto anirākatajjhāno vipassanāya samannāgato 
brūhetā suññāgārānaṃ._
____

Comment:

_Sati sati_: _Sati_ means 'if, such being the case' (PGPL, 603iii).

.Illustration
====
āyatanāni

practices of spiritual development
====

____
Bhikkhus, there are these ten practices of spiritual development through 
kasiṇas. Which ten?

_Dasaimāni bhikkhave kasiṇāyatanāni. Katamāni dasa._
____

____
One individual perceives the kasiṇa of earth extending above, below, and 
across from himself, with no subject/object duality and without limitation

_paṭhavīkasiṇameko sañjānāti uddhaṃ adho tiriyaṃ advayaṃ 
appamāṇaṃ_
____

...

____
One individual perceives the kasiṇa of mental consciousness extending above, 
below, and across from himself, with no subject/object duality and without 
limitation

_viññāṇakasiṇameko sañjānāti uddhaṃ adho tiriyaṃ advayaṃ 
appamāṇaṃ_
____

[quote, A.5.60]
____
The best of these ten practices of spiritual development through kasiṇas is 
when an individual perceives the kasiṇa of mental consciousness extending 
above, below, and across from himself, with no subject/object duality and 
without limitation.

_Etadaggaṃ bhikkhave imesaṃ dasannaṃ kasiṇāyatanānaṃ yadidaṃ 
viññāṇakasiṇameko sañjānāti uddhaṃ adho tiriyaṃ advayaṃ 
appamāṇaṃ._
____

.Illustration
====
āyatanāni

occasions
====

____
There are five occasions of liberation [from perceptually obscuring states] 
(_vimuttāyatanāni_) in which, for a bhikkhu abiding diligently, vigorously, 
and resolutely applied [to the practice], his unliberated mind is liberated 
&#8203;[from perceptually obscuring states], his undestroyed perceptually obscuring 
states are destroyed, the unreached safety from the danger of bondage [to 
individual existence] is reached. Which five?_

_Pañcimāni bhikkhave vimuttāyatanāni yattha bhikkhuno appamattassa 
ātāpino pahitattassa viharato avimuttaṃ vā cittaṃ vimuccati 
aparikkhīṇā vā āsavā parikkhayaṃ gacchanti ananuppattaṃ vā 
anuttaraṃ yogakkhemaṃ anupāpuṇāti. Katamāni pañca?_
____

____
In the first case, a teacher explains the Buddha's teaching

_satthā dhammaṃ deseti_
____

____
The bhikkhu accordingly realises the meaning and significance of the teaching _

_tathā tathā so tasmiṃ dhamme atthappaṭisaṃvedī ca hoti 
dhammapaṭisaṃvedī ca_
____

• gladness arises +
_Tassa atthappaṭisaṃvedino dhammappaṭisaṃvedino pāmujjaṃ jāyati_

• from this, rapture +
_pamuditassa pīti jāyati_

• from this his body becomes tranquil +
_pītimanassa kāyo passambhati_

• from this he experiences physical pleasure ** +
**__passaddhakāyo sukhaṃ vedeti__

• from this, his mind becomes collected +
_sukhino cittaṃ samādhiyati_.

____
This is the first occasion of liberation [from perceptually obscuring states]_

_Idaṃ bhikkhave paṭhamaṃ vimuttāyatanaṃ yattha bhikkhuno appamattassa 
ātāpino pahitattassa viharato avimuttaṃ vā cittaṃ vimuccati 
aparikkhīṇā vā āsavā parikkhayaṃ gacchanti ananuppattaṃ vā 
anuttaraṃ yogakkhemaṃ anupāpuṇāti._
____

The other occasions are:

____
in the course of explaining the teaching to others in detail as he has heard 
and memorised it

_yathāsutaṃ yathāpariyattaṃ dhammaṃ vitthārena paresaṃ deseti_
____

____
as he is reciting the teaching.

_yathāsutaṃ yathāpariyattaṃ dhammaṃ vitthārena sajjhāyaṃ karoti_
____

____
when he applies his mind to the teaching, thinks about and ponders it, and 
concentrates his attention on it.

_yathāsutaṃ yathāpariyattaṃ dhammaṃ cetasā anuvitakketi anuvicāreti 
manasānupekkhati._
____

[quote, A.3.21]
____
when some meditation object has been correctly grasped by a bhikkhu correctly 
contemplated, correctly pondered, correctly penetrated by penetrative 
discernment

_aññataraṃ samādhinimittaṃ suggahītaṃ hoti sumanasikataṃ 
sūpadhāritaṃ suppaṭividdhaṃ paññāya._
____

.Illustration
====
āyatanāni

group
====

[quote, D.1.51]
____
Bhante, just as there are these different groups of professionals, such as 
mahouts, horsemen, charioteers, archers...

_Yathā nu kho imāni bhante puthusippāyatanāni seyyathīdaṃ hatthārohā 
assārohā rathikā dhanuggahā._
____

.Illustration
====
āyatanaṃ

group
====

[quote, M.1.483]
____
That group of non-Buddhist ascetics is void even of one who goes to heaven

_suññaṃ aduṃ titthāyatanaṃ antamaso saggūpagenāpīti._
____

.Illustration
====
āyatane

aspect
====

[quote, M.3.114]
____
A bhikkhu should constantly reflect: 'Does there arise in my mind any dealing 
with any aspect of the five varieties of sensuous pleasure?'

_atthi nu kho me imesu pañcasu kāmaguṇesu aññatarasmiṃ vā 
aññatarasmiṃ vā āyatane uppajjati cetaso samudācāroti._
____

.Illustration
====
āyatanāni

dogmas
====

____
Bhikkhus, there are some ascetics and Brahmanists who speculate about the 
future and who hold dogmatic views concerning the future, who make various 
assertions about the future.

_santi bhikkhave eke samaṇabrāhmaṇā aparantakappikā 
aparantānudiṭṭhino aparantaṃ ārabbha anekavihitāni adhivuttipadāni 
abhivadanti_
____

____
Some assert that the _attā_ is perceptive and unimpaired after death

_Saññī attā hoti arogo parammaraṇā ti ittheke abhivadanti._
____

• Some assert that the _attā_ is unperceptive and unimpaired after death. +
_asaññī attā hoti arogo parammaraṇā ti ittheke abhivadanti_

____
Some assert that the _attā_ is neither perceptive nor unperceptive and 
unimpaired after death.

_nevasaññīnāsaññī attā hoti arogo parammaraṇā ti ittheke abhivadanti_
____

____
Or they assert the annihilation, destruction, and cessation of cessation of 
beings [at death].

_sato vā pana sattassa ucchedaṃ vināsaṃ vibhavaṃ paññapenti_
____

____
Or they proclaim a view concerning the highest pleasure in this lifetime.

_Diṭṭhadhammanibbānaṃ vā paneke abhivadanti_
____

• Thus they either assert an _attā_ that is unimpaired after death +
_iti santaṃ vā attānaṃ paññāpenti arogaṃ parammaraṇā._

____
Or they assert the annihilation, destruction, and cessation of beings [at death]

_Sato vā pana sattassa ucchedaṃ vināsaṃ vibhavaṃ paññāpenti_
____

[quote, M.2.228]
____
Or they proclaim a view concerning the highest pleasure in this lifetime.

_Diṭṭhadhammanibbānaṃ vā paneke abhivadanti._
____

...

[quote, M.2.233]
____
Bhikkhus, those ascetics and Brahmanists who speculate about the future and who 
hold dogmatic views concerning the future, who make various assertions about 
the future, all of them proclaim one or other of these five dogmas 
(_pañcāyatanāni_).

_Ye hi keci bhikkhave samaṇā vā brāhmaṇā vā aparantakappikā 
aparantānudiṭṭhino aparantaṃ ārabbha anekavihitāni adhivuttipadāni 
abhivadanti sabbe te imāneva pañcāyatanāni abhivadanti etesaṃ vā 
aññataraṃ._
____

.Illustration
====
āyatanāni

dogma
====

____
Bhikkhus, there are these three dogmas of non-Buddhist ascetics which, when 
questioned, probed, and examined by the wise, and taken to their logical 
conclusion, would be rated as inwardly paralysing (i.e. 'no eagerness or 
endeavour to do what should be done and avoid what should not be done,' _na 
hoti chando vā vāyāmo vā idaṃ vā karaṇīyaṃ idaṃ vā akaraṇīyan 
ti_). What three?

_Tīṇimāni bhikkhave titthāyatanāni yāni paṇḍitehi 
samanuyuñjiyamānāni samanugāhiyamānāni samanubhāsiyamānāni parampi 
gantvā akiriyāya saṇṭhahanti. Katamāni tīṇi:_
____

1. There are certain ascetics and Brahmanists who teach thus, who hold this 
view: Whatsoever pleasure or pain or neutral experience is experienced, all 
that is due to some previous action.
+
****
_santi bhikkhave eke samaṇabrāhmaṇā evaṃvādino evaṃdiṭṭhino 
yaṃ kiñcāyaṃ purisapuggalo paṭisaṃvedeti sukhaṃvā dukkhaṃ vā 
adukkhamasukhaṃ vā sabbaṃ taṃ pubbekatahetū ti._
****

2. There are others who teach: Whatsoever pleasure or pain or neutral 
experience is experienced, all that is due to the creation of a Supreme Deity.
+
****
_Santi bhikkhave eke samaṇabrāhmaṇā evaṃvādino evaṃdiṭṭhino 
yaṃ kiñcāyaṃ purisapuggalo paṭisaṃvedeti sukhaṃ vā dukkhaṃ vā 
adukkhamasukhaṃ vā sabbaṃ taṃ issaranimmāṇahetū ti._
****

3. Others teach that all sense impression has no basis or necessary condition.
+
****
_Santi bhikkhave eke samaṇabrāhmaṇā evaṃvādino evaṃdiṭṭhino 
yaṃ kiñcāyaṃ purisapuggalo paṭisaṃvedeti sukhaṃ vā dukkhaṃ vā 
adukkhamasukhaṃ vā sabbaṃ taṃ ahetuappaccayā ti_ (A.1.174).
****

.Illustration
====
āyatane

place
====

[quote, A.3.43]
____
A large tree with a massive trunk, with branches, leaves, fruit, strong roots, 
and full of fruit, is a resource for many birds. Having flown through the sky, 
they resort to this charming place.

_Sākhāpattaphalūpeto khandhimā ca mahādumo +
Mūlavā phalasampanno patiṭṭhā hoti pakkhinaṃ. +
Manorame āyatane sevanti naṃ vihaṅgamā._
____

.Illustration
====
āyatane

redundant: forest (place)
====

[quote, S.2.269]
____
Bhikkhus, once there was a great lake in a forest with bull elephants living 
nearby.

_Bhūtapubbaṃ bhikkhave araññāyatane mahāsarasi taṃ nāgā upanissāya 
viharanti._
____

.Illustration
====
āyatane

redundant: forest (place)
====

[quote, D.3.94]
____
They made little leaf huts in the forest and meditated in them.

_Te araññāyatane paṇṇakuṭiyo karitvā paṇṇakuṭīsu jhāyanti._
____

.Illustration
====
āyatane

redundant (occasion)
====

[quote, M.1.523]
____
It is astounding and extraordinary, Venerable Ānanda, that [firstly, in this 
teaching and training system] there is no glorifying of one's own teaching and 
no disparaging of the teaching of others, but [only] the (occasion of the) 
explanation of the Buddha's teaching, and [that secondly] there are so many 
Emancipated Ones to be discerned.

_Acchariyaṃ bho ānanda abbhutaṃ bho ānanda na ca nāma 
sadhammokkaṃsanā bhavissati na paradhammāvasādanā āyatane ca 
dhammadesanā tāva bahukā ca niyyātāro paññāyissanti._
____

Comment:

'That [firstly, in this teaching and training system].' The parenthesis comes 
from the preceding question: _Kīva bahukā pana bho ānanda imasmiṃ 
dhammavinaye niyyātāro ti?_

